### ISSUE TITLE
Couldn't find onnx.pb.h in latest onnx-1.1.2

### ISSUE THREAD

**Issue by Nagamani732** [onnx/onnx#1001]
The following line is included in onnx_pb.h but couldn't find where the file located in. Any idea where the file will be?

Thanks in advance !!

https://github.com/onnx/onnx/blob/241a350272ff7babce154ef58033ad9424e6bfd5/onnx/onnx_pb.h#L64

**Comment by linkerzhang** [comment]
The file is generated by running protoc, so if you following the development guide and build the repo from source code. it will be auto-generated and put in folder \onnx\.setuptools-cmake-build\onnx\.

**Comment by Nagamani732** [comment]
Yes, I cloned the repo(onnx) and built from source in **windows 10.** After doing cmake the following project files has been generated ALL_BUILD, gen_onnx_operators_proto, gen_onnx_proto, INSTALL, onnx, onnx_proto, ZERO_CHECK in built directory. I just opened ALL_BUILD project in VS2017 and tried to run but ended up the following error.

Could you please help me to resolve this ?

Thanks in advance !!


> Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\checker.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\defs\function.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\defs\data_type_utils.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\common\ir_pb_converter.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\defs\schema.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	
Error	C2220	warning treated as error - **no 'object' file generated (compiling source file D:\workspace\onnx\onnx\optimizer\optimize.cc)**	onnx	d:\workspace\vcpkg\packages\protobuf_x86-windows\include\google\protobuf\stubs\logging.h	100	


FYI: I followed the same above steps in **ubuntu 16.04** and it works. The only difference is I did a make after cmake

**Comment by prasanthpul** [comment]
Closing this old issue. Please reopen if you still have issue with latest versions.

**Comment by blueardour** [comment]
Hi, guys, would you mind to share the gcc/g++/protoc version? I met a c++ compiling problem when include the onnx.pb.h.

**Comment by ankmathur96** [comment]
I'm still having this issue when compiling from source on Ubuntu 16.04 on latest - I think I used the setup instructions correctly. Is there any insight into why this might be happening? When I check out commit (5b7ac729f08a04b62a8ef401aa149ba25f07d26c), installation seems to work fine.
