### ISSUE TITLE
Adding missing operators required by Faster RCNN

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#1003]
- [ ] BBoxTransform

- [ ] BoxWithNMSLimit

- [ ] GenerateProposals

- [x] RoIAlign

**Comment by Anubhav7** [comment]
@houseroad do we know when this would be available? Looking forward to this.

**Comment by fuzzyBatman** [comment]
@houseroad I think RoiAlign is available now.

**Comment by houseroad** [comment]
Models have been added to https://github.com/onnx/models already. So close the issues. (some ops are added with different implementations.)

**Comment by fuzzyBatman** [comment]
@houseroad Is **GenerateProposals** added? That one is required for Detectron models.

**Comment by houseroad** [comment]
No, i think generateproposal is split into smaller ops. You can check the onnx model faster-rcnn and mask-rcnn's implementation.

**Comment by fuzzyBatman** [comment]
Ah. Thanks.

**Comment by houseroad** [comment]
link: https://github.com/onnx/models/tree/master/faster_rcnn :-)

**Comment by fuzzyBatman** [comment]
The model is pretrained using facebookresearch/maskrcnn-benchmark. Do you know if it is possible to export custom models from facebookresearch/maskrcnn-benchmark?
