### ISSUE TITLE
Dimension mismatch - did you forget to set broadcast=1?

### ISSUE THREAD

**Issue by christoph-conrads** [onnx/onnx#101]
I exported a simple model for MNIST from PyTorch 0.2.0+803afd5 (a commit from yesterday, Oct 9, 2017, self-built) and imported it with onnx 0.2 (py27hac7d9f4_1 from conda channel *ezyang*) into Caffe2 (commit cbe0d2821230a451c9dee9414abbace4a4112329 built from source).

Originally, the model tried to scale all pixel values from the range [0, 255] to [0, 1] by executing `x = x / 255` but this causes an error during the export on the PyTorch side:
```
RuntimeError: Couldn't export DivConstant function - maybe it doesn't implement a symbolic definition?
```
Instead, I settled for
```python
        c_np = np.array( [1.0/255], dtype=np.float32 )
        c_t = torch.Tensor(c_np)
        c = torch.autograd.Variable(c_t, requires_grad=False)

        x = x * c
```
When I try to run the imported ONNX model, I get the following output:
```
christoph:~/caffe2-demo$ python run-onnx.py MNIST.fc.protoWARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Traceback for operator 1 in network torch-jit-export
Traceback (most recent call last):
  File "run-onnx.py", line 50, in <module>
    sys.exit( main() )
  File "run-onnx.py", line 43, in main
    output = model.run(x)
  File "/home/christoph/anaconda2/lib/python2.7/site-packages/onnx_caffe2-0.2-py2.7.egg/onnx_caffe2/backend_rep.py", line 50, in run
  File "/home/christoph/caffe2.x86_64-linux-gnu/caffe2/python/workspace.py", line 221, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/christoph/caffe2.x86_64-linux-gnu/caffe2/python/workspace.py", line 186, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at elementwise_op.h:187] A.dims() == B.dims(). 1 784 vs 1. Dimension mismatch - did you forget to set broadcast=1? Error from operator: 
input: "1" input: "8" output: "9" name: "" type: "Mul" device_option { device_type: 0 cuda_gpu_id: 0 }
```

Please provide advice.

**Comment by bddppq** [comment]
Will add support for DivConstant soon in this [PR](https://github.com/pytorch/pytorch/pull/2923)

**Comment by dzhulgakov** [comment]
As for missing broadcast=1 for Mul, looks like pytorch exporter doesn't export it properly right now (see also #83). @houseroad - can you help with that?

**Comment by houseroad** [comment]
@dzhulgakov Sure, I will take a look. :-)

**Comment by houseroad** [comment]
@christoph-conrads I think with @bddppq's patch, PyTorch can correctly export DivConstant and MulConstant. You don't need to turn constant to tensor now. And AddConstant and SubConstant are also working now. Not sure if you are still blocked or not.

I am working on the broadcasting for Add/Sub/Mul/Divide now.

**Comment by christoph-conrads** [comment]
Exporting `x = x / 255` from [PyTorch commit a0ac72e](https://github.com/pytorch/pytorch/tree/a0ac72e84e2f14c42d1bfdd695c411c0f101487c) works for me.
