### ISSUE TITLE
GRU equations/python

### ISSUE THREAD

**Issue by skottmckay** [onnx/onnx#1019]
Should R[zrh] be treated the same as W[zrh] values and be transposed before use? That would match the CNTK implementation and be a more consistent treatment of the W and R values. 

Current equations are
```
    zt = f(Xt*(Wz^T) + Ht-1*Rz + Wbz + Rbz)
    rt = f(Xt*(Wr^T) + Ht-1*Rr + Wbr + Rbr)
    ht = g(Xt*(Wh^T) + (rt (.) Ht-1)*Rh + Rbh + Wbh) # default, when linear_before_reset = 0
    ht = g(Xt*(Wh^T) + (rt (.) (Ht-1*Rh + Rbh) + Wbh) # when linear_before_reset != 0
    Ht = (1 - zt) (.) ht + zt (.) Ht-1
```

current python from GRU_helper.py
```
  z = self.f(np.dot(self.X, np.transpose(w_z)) + np.dot(self.H_0, r_z) + w_bz + r_bz)
  r = self.f(np.dot(self.X, np.transpose(w_r)) + np.dot(self.H_0, r_r) + w_br + r_br)
  h_default = self.g(np.dot(self.X, np.transpose(w_h)) + np.dot(r * self.H_0, r_h) + w_bh + r_bh)
  h_linear = self.g(np.dot(self.X, np.transpose(w_h)) + r * (np.dot(self.H_0, r_h) + r_bh) + w_bh)
```

python with transpose of R[zrh] that produces same results as CNTK
```
  z = self.f(np.dot(row, np.transpose(w_z)) + np.dot(self.H_0, np.transpose(r_z)) + w_bz + r_bz)
  r = self.f(np.dot(row, np.transpose(w_r)) + np.dot(self.H_0, np.transpose(r_r)) + w_br + r_br)
  h_default = self.g(np.dot(row, np.transpose(w_h)) + np.dot(r * self.H_0, np.transpose(r_h)) + w_bh + r_bh)
  h_linear = self.g(np.dot(row, np.transpose(w_h)) + r * (np.dot(self.H_0, np.transpose(r_h)) + r_bh) + w_bh)
```

**Comment by skottmckay** [comment]
FWIW The LSTM python transposes the R weights before calling np.dot with Ht-1:

https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/lstm.py#L71
            gates = np.dot(x, np.transpose(self.W)) + np.dot(H_t, np.transpose(self.R)) + np.add(
                *np.split(self.B, 2))

**Comment by anderspapitto** [comment]
@skottmckay so, if I understand correctly, the issue you're raising applies to all of LSTM/GRU/RNN in the same way. So let's look at the simplest case, RNN. It has one equation,

```
- Ht = f(Xt*(Wi^T) + Ht-1*Ri + Wbi + Rbi)
```

You are proposing to change it to

```
- Ht = f(Xt*(Wi^T) + Ht-1*(Ri^T) + Wbi + Rbi)
```

correct?

**Comment by skottmckay** [comment]
Your understanding is correct. As for what the correct fix is I don't have the expertise to say. What I'm going off is:
  * The LSTM python transposes R, and produces the same output as CNTK
  * The GRU python does not transpose R and does not match the CNTK output. Changing it to transpose R results in it matching the CNTK output

I haven't tested the RNN output, and the RNN python does not transpose R currently.

I would expect that they should all treat the R weights the same way, and the python should match the equations. So either the equations should change to transpose R as in your comment, or the LSTM python should change to not transpose R. The latter would mean CNTK output differs from the ONNX python for at least GRU and LSTM (and possibly RNN as well).

**Comment by skottmckay** [comment]
My GRU python statement was out of date. There was a recent change to the GRU python to transpose Rz and Rr but not Rh, and that change also added the transpose of R weights to LSTM.

https://github.com/onnx/onnx/commit/d2a46da13b0b0e9d3ed7a1da34e015b4bc8fe0de#diff-98b0f6b804ec8aebff60069760608d05 

For RNN, transposing R produces the same output as CNTK.
