### ISSUE TITLE
Converting detection model to SSD doesnt succeeed

### ISSUE THREAD

**Issue by ravikantgupta9** [onnx/onnx#1020]
I am trying to convert this (https://s3.amazonaws.com/amdegroot-models/ssd300_mAP_77.43_v2.pth) detection model to onnx but I am facing this error

The repo containing the training and testing code is here https://github.com/amdegroot/ssd.pytorch

This is the error I get. Any help on how to resolve it?

this is the code I am running

    num_classes = 21
    net = build_ssd('test', 300, num_classes) # from https://github.com/amdegroot/ssd.pytorch/blob/master/ssd.py
    dummy_input = Variable(torch.randn(1, 3, 300, 300))
    model = torch.load('weights/ssd300_mAP_77.43_v2.pth')
    net.load_state_dict(model)
    torch.onnx.export(net, dummy_input, "ssd.onnx")

This is the error I get

/home/ravf/repos/ssd.pytorch/ssd.py:34: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  self.priors = Variable(self.priorbox.forward(), volatile=True)
/home/ravf/repos/ssd.pytorch/layers/modules/l2norm.py:17: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.weight,self.gamma)
Traceback (most recent call last):
  File "test.py", line 106, in <module>
    convert_to_onnx()
  File "test.py", line 86, in convert_to_onnx
    torch.onnx.export(net, dummy_input, "ssd.onnx")
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 84, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 134, in _export
    trace, torch_out = torch.jit.get_trace_graph(model, args)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 255, in get_trace_graph
    return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 288, in forward
    out = self.inner(*trace_inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ravf/repos/ssd.pytorch/ssd.py", line 103, in forward
    self.priors.type(type(x.data))                  # default boxes
RuntimeError: Attempted to trace Detect, but tracing of legacy functions is not supported

Can anybody help me understanding what the problem might be and how to fix it?

**Comment by ZQMgh** [comment]
I met the same problem

**Comment by Xiaoyang-Rebecca** [comment]
The same problem +1

**Comment by prasanthpul** [comment]
This problem seems to be specific to PyTorch. Can you please file this in the PyTorch GitHub so the PyTorch experts can take a look?

**Comment by carolinepacheco** [comment]
I have the same problem :(

**Comment by raviv** [comment]
+1

**Comment by ShuaiHuang** [comment]
+1

**Comment by lianxxx** [comment]
+1

**Comment by raviv** [comment]
Anyone found a solution for that?

**Comment by isthatyoung** [comment]
I have the same problem, so I remove the detection and concat loc, conf, prior together first.

**Comment by LeiJiangJNU** [comment]
I have the same problem:(     +1

**Comment by isthatyoung** [comment]
One solution works. Because onnx did not support legacy function, and Detect derived from Function of torch.autograd, so one simple solution, you could must all the operation in Detect to a simple function 'def Detect(xx, xx, xx...)'. In ssd.py, output = detect(self.num_classes, 0, 200, 0.01, 0.3, loc.view(loc.size(0), -1, 4).detach(), self.softmax(...).detach()), self.prior.type(type(x.data)).detach()) It works.

**Comment by FantasyJXF** [comment]
> One solution works. Because onnx did not support legacy function, and Detect derived from Function of torch.autograd, so one simple solution, you could move all the operations in class Detect to a simple function 'def Detect(xx, xx, xx...)'. Then in ssd.py, output = detect(self.num_classes, 0, 200, 0.01, 0.3, loc.view(loc.size(0), -1, 4).detach(), self.softmax(...).detach()), self.prior.type(type(x.data)).detach()) It works.

That's genius, one more question, how should I update the `Detect` class to make it compatiable with the new pytorch?

**Comment by zhiqwang** [comment]
@FantasyJXF This is caused by an inheritance of `torch.autograd.Function` which cannot be traced. You probably want to convert the model to use the `nms` functions provided by torchvision, those have tracing support.
