### ISSUE TITLE
Should we relax the requirement of "initializers must be in inputs"?

### ISSUE THREAD

**Issue by KeDengMS** [onnx/onnx#1021]
Netron does not check it, as [this model](https://gist.github.com/KeDengMS/656253c15da8c0880543eae06303c13d/raw/a85bcb4ab1e65b752762b325ac45a5d63776436e/one_initializer_not_in_inputs.onnx) loads fine, even though the initializer Add1_Input1 is not in inputs.

We ran into this because our code assumed this before, and now the implementation has relaxed the check. Does it make sense to relax in the spec, as at least two implementations (ours + netron) are now ignoring it?

**Comment by fdwr** [comment]
It makes sense to list any application-bindable inputs/outputs of the graph in the onnx::GraphProto, but it's dubious to list the names of tensors for _all_ internal nodes that just take static initializer inputs for weights. For example, the squeezenet ONNX file lists every single node's input tensor in the onnx::GraphProto input, but the graph really only has one bindable tensor of interest to an application (data_0), which gets lost in the noise.

**Comment by snnn** [comment]
See the discussion at https://github.com/onnx/models/issues/1

@bddppq

**Comment by gramalingam** [comment]
Please see https://github.com/onnx/onnx/pull/1718 for the final resolution.
