### ISSUE TITLE
ONNX 1.2 release

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#1023]
Release notes:
IR Changes
•	Add function and attribute reference (PR #802).
•	Add dimension denotation (PR #443) and type denotation (PR #879).
Operator Changes
Latest operator set version is 8 for ONNX domain and 1 for ONNX_ML domain.
•	Type and shape inference function added for all operators.
•	Add new operators.
o	Upsample (PR #861) – promoted from experimental, attributes and behavior updated to support arbitrary # of dimensions.
o	Identity (PR #892) – promoted from experimental.
o	Acos, Asin, Atan, Cos, Sin, Tan (PR #869).
o	Multinomial (PR #897)
•	Remove FC (experimental) op (PR #977).
•	Move to numpy broadcasting semantics (PR #907).
•	Clarify “optional” semantics for input/output and adjust RNN/GRU/LSTM/BatchNormalization/Dropout accordingly (PR #1006, PR #1014).
•	AveragePool – formulas for output shape updated (PR #751), extended to support average count including padding (PR #884)
•	BatchNormalization – clarify outputs can be n-dim (PR #733)
•	Cast – change to attr from string to int (PR #727)
•	ConstantFill (exp) – change value attr from optional to default value of 0 (PR #808)
•	InstanceNormalization – clarify outputs can be n-dim (PR #733)
•	MaxPool – formulas for output shape updated (PR #751)
•	AveragePool, MaxPool, Conv – update to support dimension denotation (PR #443)
•	Reshape – add output shape as an input (PR #608)
•	Size – change output from int to scalar tensor (PR #759)
•	Tile – replace tiles and axis inputs with repeats to match numpy (PR #757)
•	ZipMap – update type constrains from map to seq (PR #818)
•	Affine – add default values for alpha and beta attributes (PR #820)
•	FeatureVectorizer – update behavior (PR #843)
•	LinearClassifier – coefficient attribute is now required (PR #836)
•	RandomNormalLike, RandomUniformLike – change input type constraints and change behavior to copy shape instead of compute it (PR #846)
•	Selu – change default value of attributes to match other frameworks (PR #839)
•	ArgMax, ArgMin – specify default values for axis attribute (PR #847)
•	DepthToSpace, SpaceToDepth – blocksize attribute is now required (PR #847)
•	GRU, LSTM, RNN – specify default value for activation_* attributes (PR #847)
•	Reduce* – specify default behavior for axes attribute (PR #847)
•	Concat, Gather, Squeeze, Unsqueeze – accept any tensor type (PR #957)
•	Add, Div, Mul, Pow, Sub – enhance 1-element broadcast case (PR #902)
•	Pad – clarify pads attribute (PR #962)
•	LRN – specify default values and clarify behavior (PR #965) 
•	ConvTranspose – clarify padding behavior and remove restriction on output_padding attribute (PR #1012)
•	All ops – updated type constraints (PR #666)

Please share your comments if any.

**Comment by jspisak** [comment]
@linkerzhang thanks for starting this Ke. Let me know if there is anything I need to push on my side..

**Comment by jspisak** [comment]
@linkerzhang - have we release v1.2.2 yet?
