### ISSUE TITLE
Why is there an additional Reshape layer in LeNet's onnx pb file ?

### ISSUE THREAD

**Issue by Nagamani732** [onnx/onnx#1025]
The following is the LeNet model's layer types that I could see in deploy.prototxt. I just converted this from caffe->caffe2->onnx using the respectively conversion tools that are available. 

> Conv
MaxPool
Conv
MaxPool
Gemm
Relu
Gemm
Softmax

After the conversion I could ses a new layer in onnx pb file

>   node {
>     input: "pool2_1"
>     input: "OC2_DUMMY_1"
>     output: "OC2_DUMMY_0"
>     op_type: "Reshape"
>   }

In onnx pb file I could see 
> Conv
MaxPool
Conv
MaxPool
**Reshape** -- This layer is added newly
Gemm
Relu
Gemm
Softmax

So why is this layer being added and what is OC2_DUMMY_1 ?
Sorry if I didn't state the issue clearly

Thanks in advance !!

**Comment by arogozhnikov** [comment]
Agree with @wschin, and most probably, OC2_DUMMY_1 is just an expected resulting shape.

**Comment by Nagamani732** [comment]
Well understood. Thanks @wschin and @arogozhnikov
