### ISSUE TITLE
Validate that raw_data XOR floats/etc field is used in TensorProto

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#103]
In the onnx model (from the zoo), I'm seeing tensor data stored in raw_data field when it's "FLOAT" type. Shouldn't it be in float_data please? if not, do we want to create (or we already have) rules which field should be used for which type please? or we just have to go thru all fields to fetch out the data regardless of its type?

**Comment by bddppq** [comment]
For each data type the data can be stored in the corresponding data field (e.g. "FLOAT" -> float_data) or raw_data (except string, which can only be stored in "string_data" field). Storing it in raw_data field is for efficient protobuf parsing, see here: https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py#L46

**Comment by ezyang** [comment]
The rule is that either `raw_data` is set, OR one of the other fields is set, appropriate for the type. @bddppq, do you know if the validator is testing for this? It's an error for multiple to be simultaneously set. Maybe we should have just gotten rid of the non-data fields.

In any case, float data will only ever be in `float_data` or `raw_data`, you don't have to test for ints.

**Comment by bddppq** [comment]
I don't think there is any place checking this, we could check initializer in check_graph.

**Comment by ezyang** [comment]
Yep; also we need to check it for tensor constants

**Comment by linkerzhang** [comment]
Thanks! We may also come out of helper functions to parse the raw_data in this way. :).

**Comment by ezyang** [comment]
Keeping this issue open to track validating tensor proto format.

**Comment by ezyang** [comment]
Aaand fixed now :)
