### ISSUE TITLE
OnnxBackendRealModelTest failed

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#1036]
pytest failed on 8 OnnxBackendRealModelTests:
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_bvlc_alexnet_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_densenet121_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_inception_v1_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_inception_v2_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_resnet50_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_shufflenet_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_squeezenet_cpu": true,
  "onnx/test/test_backend_test.py::OnnxBackendRealModelTest::test_vgg19_cpu": true

Here is one of the test failure outputs:  
    @classmethod
    def prepare(cls,
                model,  # type: ModelProto
                device='CPU',  # type: Text
                **kwargs  # type: Any
                ):  # type: (...) -> Optional[onnx.backend.base.BackendRep]
        super(DummyBackend, cls).prepare(model, device, **kwargs)

        # test shape inference
        model = onnx.shape_inference.infer_shapes(model)
        value_infos = {vi.name: vi for vi in itertools.chain(model.graph.value_info, model.graph.output)}

        if do_enforce_shape_inference_coverage(model):
            for node in model.graph.node:
                for i, output in enumerate(node.output):
                    if node.op_type == 'Dropout' and i != 0:
                        continue
>                   assert output in value_infos
E                   AssertionError: assert 'conv1_2' in {'conv1_1': name: "conv1_1"\ntype {\n  tensor_type {\n    elem_type: FLOAT\n    shape {\n      dim {\n        dim_value: 1\n ...dim_value: 1000\n      }\n      dim {\n        dim_value: 1\n      }\n      dim {\n        dim_value: 1\n      }\n    }\n  }\n}\n}

onnx\test\test_backend_test.py:49: AssertionError

**Comment by snnn** [comment]
Hi @liqunfu

Were you running this test against onnx 1.2 release? With which backend?

**Comment by houseroad** [comment]
@liqunfu do you still have the problem?

**Comment by raymondxyang** [comment]
Same issue observed here @liqunfu @houseroad @snnn . happen locally against 1.2.1/1.2.2 release and master branch... cannot reproduce on other PC..

**Comment by kit1980** [comment]
I have the same issue on a Windows machine with the current master branch.

**Comment by kit1980** [comment]
[onnx-test-error.txt](https://github.com/onnx/onnx/files/2129280/onnx-test-error.txt)

**Comment by raymondxyang** [comment]
Root cause located: The pytest will automatically use cached models in ~/.onnx/models (user_profile\.onnx\models for windows). Delete all model caches there and it will sync with updated models on aws. All tests passed after updates.
