### ISSUE TITLE
ONNX-ML.Proto3 does not compile for C#

### ISSUE THREAD

**Issue by codemzs** [onnx/onnx#1045]
Compiler complains about [default = ….]; being used at 11 different places in the [onnx-ml.proto3](https://github.com/onnx/onnx/blob/master/onnx/onnx-ml.proto3) file. Error message"onnx-ml.proto3: Explicit default values are not allowed in proto3."

Command used: E:\protobuf-csharp-port\lib>protoc.exe -I="E:\protobuf-csharp-port\lib" --csharp_out="E:\protobuf-csharp-port\lib" "E:\protobuf-csharp-port\lib\onnx-ml.proto3

E:\protobuf-csharp-port\lib>protoc.exe --version
libprotoc 3.5.1

This is causing regression in [MLdotNet](https://github.com/dotnet/machinelearning/) C# based machine learning toolkit that was relying on proto3 to generate C# code from the proto file, since the compiler only supports 3.0. If there is a workaround for this issue that you can suggest then it will be highly appreciated. I'm seeing from PR #443 that ONNX is locked to proto2 but if that is the case then can you please clarify why proto3 files are being produced?

CC: @linkerzhang @tjingrant @bddppq

**Comment by NiklasGustafsson** [comment]
Our agreement last year was to use the common subset of v2 and v3 of protobuf. Any feature that cannot be precisely represented in both v2 and v3 should not be used.

**Comment by tjingrant** [comment]
Quoting @dzhulgakov 

>So, we're actually locked to proto2 'syntax' but it is supported by newer version of protobuf 'compiler' like protobuf>3
>Thus default values are on the table actually and can be defined as a fake message with default fields: https://developers.google.com/protocol-buffers/docs/proto#optional
>I guess it's better to put it into a proto file so one might want to use the constants from C++ side.
>In general diff seems reasonable to be merged, cc linkerzhang ezyang for more perspective

Might help to get his opinion too.

**Comment by codemzs** [comment]
@tjingrant @dzhulgakov  proto2 is not supported by protoc for C# code generation, at least for compiler version 3.5.1. Correct me if there is a newer compiler that supports proto2 for C# as well.

**Comment by sbodenstein** [comment]
The same happens for `onnx.proto3` on master with all `protoc` compilers (I've tested compilers between versions 3.1 and 3.5.1). For example:
```
"/Downloads/protoc-3.5.1-osx-x86_64/bin/protoc" -I="/git/protobuflink/proto" --python_out="/Downloads/protobuf-3.5.1/examples/" "/git/protobuflink/proto/onnx.proto3"
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3.
onnx.proto3: Explicit default values are not allowed in proto3
```

**Comment by bddppq** [comment]
@codemzs Since #1052 is merged now, could you confirm whether this issue is resolved?

**Comment by codemzs** [comment]
@bddppq I confirm that #1056 resolves this issue. Thank you, @linkerzhang for the fix. Looking forward to creating my next PR against ONNX repo and updating [tutorials](https://github.com/onnx/tutorials) markdown file.
