### ISSUE TITLE
Cannot import caffe2.python.onnx.backend with new onnx release

### ISSUE THREAD

**Issue by lburzawa** [onnx/onnx#1056]
I got a segmentation fault when trying to import caffe2.python.onnx.backend after installing onnx 1.2.1 from pip3. I just rebuilt caffe2 from the master branch of pytorch (version 0.8.2) but the issue remains. Any ideas? My protobuf version is 3.5.1.

**Comment by lburzawa** [comment]
Can be fixed by building onnx from source.

**Comment by Khrylx** [comment]
I also encountered this problem and tried to build onnx from source, i.e., I run
`python setup.py install`

Could you please tell me how did u fix it?

**Comment by lburzawa** [comment]
I just built it from source, running your command but with sudo and python3. It doesn't work for you?

**Comment by Khrylx** [comment]
It works now. Turns out I also need to use protobuf version too, thanks!

**Comment by haifenghan** [comment]
I have the same issue to import caffe2.python.onnx.backend as follows:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.                                                        
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Segmentation fault (core dumped)

```
Some related versions:

protobuf: 3.5.1
onnx: 1.2.1 (python setup.py install)
python: 2.7.15rc1
caffe2: build from tip source following instructions of https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

**Comment by haifenghan** [comment]
It works fine for me now.
I find my Anaconda confuses caffe2.
After commenting out the following, there is no issue any more:
`# PATH="/home/haifeng/softwares/anaconda3/bin:$PATH"`

**Comment by sgarcia22** [comment]
from caffe2.python import onnx
from onnx import backend
Also works

**Comment by anirudhacharya** [comment]
I am encountering the same issue with caffe2 and ONNX v1.2.1 pip install. I get Segmentation Fault.

**Comment by jspisak** [comment]
cc @houseroad @bddppq  Are we working on this one?

**Comment by haifenghan** [comment]
@anirudhacharya 
ONNX for pip package has this issue. After building it from source, it works fine for me.
```git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install```
