### ISSUE TITLE
Can we have an option to export static graph?

### ISSUE THREAD

**Issue by qigtang** [onnx/onnx#1067]
When using pytorch 0.4, export resnet to onnx, the FC layer will be something like

 %169 : Float(1, 512, 1, 1) = onnx::AveragePool[kernel_shape=[7, 7], pads=[0, 0, 0, 0], strides=[1, 1]](%168), scope: ResNet/AvgPool2d[avgpool]
  %170 : Float(1, 512) = onnx::Flatten[axis=1](%169), scope: ResNet
  %171 : Float(1, 6) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%170, %101, %102), scope: ResNet/Linear[fc]
  return (%171);

Latest version of pytorch save it as 
  %190 : Float(1, 512, 1, 1) = onnx::AveragePool[kernel_shape=[7, 7], pads=[0, 0, 0, 0], strides=[1, 1]](%189), scope: ResNet/AvgPool2d[avgpool]
  %191 : Dynamic = onnx::Shape(%190), scope: ResNet
  %192 : Dynamic = onnx::Slice[axes=[0], ends=[1], starts=[0]](%191), scope: ResNet
  %193 : Long() = onnx::Squeeze[axes=[0]](%192), scope: ResNet
  %194 : Long() = onnx::Constant[value={-1}](), scope: ResNet
  %195 : Dynamic = onnx::Unsqueeze[axes=[0]](%193), scope: ResNet
  %196 : Dynamic = onnx::Unsqueeze[axes=[0]](%194), scope: ResNet
  %197 : Dynamic = onnx::Concat[axis=0](%195, %196), scope: ResNet
  %198 : Float(1, 512) = onnx::Reshape(%190, %197), scope: ResNet
  %199 : Float(1, 6) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%198, %121, %122), scope: ResNet/Linear[fc]
  return (%199);

The new one actually caused trouble for us. For embedded device, we want fixed size, and let TensorRT optimize the graph for deployment.  I don't want the "nice" dynamic feature in onnx.

It is possible to put an option to latest pytorch, so that we can choose to export a static and simpler graph?

**Comment by houseroad** [comment]
@qigtang I think it's more appropriate to post the feature request in pytorch repo, instead here.

**Comment by houseroad** [comment]
Close since it's an issue in PyTorch ONNX exporter.
