### ISSUE TITLE
ERROR:onnx.checker.check_model()

### ISSUE THREAD

**Issue by YUIAZU000** [onnx/onnx#1072]
I ran onnx.checker.check_model() on my model and  i got an error:
'onnx.onnx_cpp2py_export.checker.ValidationError: model with IR version < 3 cannot have opset_import specified.'
How can i fix it?

**Comment by houseroad** [comment]
@YUIAZU000 how do you generate/get the model?

**Comment by YUIAZU000** [comment]
@houseroad I have sovled the problem by updating my torch version. Thank you for your reply.

**Comment by houseroad** [comment]
The problem is solved.

**Comment by fanser** [comment]
@YUIAZU000 Hi, what is your updated pytorch version ? My pytorch version is 0.3.0.post4. I meet the same problem....

**Comment by YUIAZU000** [comment]
@fanser You should update your pytorch to latest version.

**Comment by uhvardhan** [comment]
So I tried converting a Pytorch model to onnx model first with 0.3.1 torch version. It throws errors in the latest version.

Then I tried to convert onnx model to a tensorflow model which requires the pytorch-onnx model conversion to take place in 0.4.0. 

Any solution to this problem..?/

Thanks
