### ISSUE TITLE
[bug] onnx::Node::isBefore

### ISSUE THREAD

**Issue by cycheng** [onnx/onnx#1073]
Node* p = next();
    while (p != nullptr) {
      if (p == n) {
        return true;
      }
      p = next();  <= should be p = p->next();
    }

**Comment by houseroad** [comment]
@fumihwh @anderspapitto could you take a look?

**Comment by fumihwh** [comment]
@houseroad It's a bug...... but the fix is not just as @cycheng said.
`p` will never be `nullptr`.

**Comment by fumihwh** [comment]
@anderspapitto I made a PR. Could you take a look?
