### ISSUE TITLE
Will ONNX support ops "Gather, StridedSlice, Pack, ExpandDims, Rsqrt, TopKV2 "?

### ISSUE THREAD

**Issue by jiangsuliji** [onnx/onnx#1085]
Without these ops, hard to convert TF model to ONNX.

**Comment by anirudhacharya** [comment]
[Gather](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gather), [TopK](https://github.com/onnx/onnx/blob/master/docs/Operators.md#TopK), [ExpandDims](https://github.com/onnx/onnx/blob/master/docs/Operators.md#unsqueeze) are already supported. Could you share the definition of the other three operators. They are probably already there with different names.

**Comment by askhade** [comment]
@jiangsuliji : Is this issue still relevant? Please use the latest TF to ONNX converter to convert your model and if you see any issues create a new issue. Thanks!
