### ISSUE TITLE
I want to  installing caffe2 with python3.6.5 given by Anaconda throght the guide "Build From Source",I got errors from the file pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc

### ISSUE THREAD

**Issue by TerYang** [onnx/onnx#1087]
First I installed Anaconda ,and updated its modules  (and some third party modules),Then I created a environment named py_caffe2, following the guide of "Build From Source" ,I successfully installed some Dependencies as the guide showed below
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      git \
      libgoogle-glog-dev \
      libgtest-dev \
      libiomp-dev \
      libleveldb-dev \
      liblmdb-dev \
      libopencv-dev \
      libopenmpi-dev \
      libsnappy-dev \
      libprotobuf-dev \
      openmpi-bin \
      openmpi-doc \
      protobuf-compiler \
      python-dev \
      python-pip                          
sudo pip install \
      future \
      numpy \
      protobuf
"balaba" (go straight with the guide),when I tried cmake .. I lerant from the blog https://github.com/caffe2/caffe2/issues/1943 ,and set the right python version with python 3.6 with the command :(py_caffe2) terr@terr-Founder-PC:~/.conda/envs/py_caffe2/pytorch/build$  cmake -DPYTHON_INCLUDE_DIR=/home/terr/.conda/envs/py_caffe2/include/python3.6m -DUSE_MPI=OFF ..

and got the Feedback as below:
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-8736-gf45a3d5
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-unused-parameter -Wno-unknown-warning-option -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-variable -Wno-unused-function
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_CAFFE2          : ON
--   BUILD_ATEN            : OFF
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 3.6.5
--     Python includes     : /home/terr/.conda/envs/py_caffe2/include/python3.6m
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ASAN              : OFF
--   USE_CUDA              : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--     USE_GLOO_IBVERBS    : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.3.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/terr/.conda/envs/py_caffe2/pytorch/build

Finally, I got errors when I tried command  "sudo make install",the errors are showed as below :

(py_caffe2) terr@terr-Founder-PC:~/.conda/envs/py_caffe2/pytorch/build$ sudo make install (command scene)

/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:8:25: error: expected constructor, destructor, or type conversion before ‘(’ token
 ONNX_OPERATOR_SET_SCHEMA(
                         ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:36:46: error: expected unqualified-id before ‘,’ token
         .TypeConstraint("B", {"tensor(bool)"}, "Only bool"));
                                              ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:36:48: error: expected unqualified-id before string constant
         .TypeConstraint("B", {"tensor(bool)"}, "Only bool"));
                                                ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:160:25: error: expected constructor, destructor, or type conversion before ‘(’ token
 ONNX_OPERATOR_SET_SCHEMA(
                         ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:201:39: error: expected unqualified-id before ‘,’ token
         .TypeConstraint("I", {"int64"}, "Only int64")
                                       ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:201:41: error: expected unqualified-id before string constant
         .TypeConstraint("I", {"int64"}, "Only int64")
                                         ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:202:38: error: expected unqualified-id before ‘,’ token
         .TypeConstraint("B", {"bool"}, "Only bool"));
                                      ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:202:40: error: expected unqualified-id before string constant
         .TypeConstraint("B", {"bool"}, "Only bool"));
                                        ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:204:25: error: expected constructor, destructor, or type conversion before ‘(’ token
 ONNX_OPERATOR_SET_SCHEMA(
                         ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:229:39: error: expected unqualified-id before ‘,’ token
         .TypeConstraint("I", {"int32"}, "Indices"));
                                       ^
/home/terr/.conda/envs/py_caffe2/pytorch/third_party/onnx/onnx/defs/controlflow/defs.cc:229:41: error: expected unqualified-id before string constant
         .TypeConstraint("I", {"int32"}, "Indices"));
                                         ^
third_party/onnx/CMakeFiles/onnx.dir/build.make:86: recipe for target 'third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o' failed
make[2]: *** [third_party/onnx/CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o] Error 1
CMakeFiles/Makefile2:1004: recipe for target 'third_party/onnx/CMakeFiles/onnx.dir/all' failed
make[1]: *** [third_party/onnx/CMakeFiles/onnx.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
help ! help ! help! I have been failure N times between 2 months

**Comment by prasanthpul** [comment]
Please reopen if you are still having issues with the latest versions
