### ISSUE TITLE
Invalid target compile option for MSVC build

### ISSUE THREAD

**Issue by skottmckay** [onnx/onnx#1093]
https://github.com/onnx/onnx/commit/8bbeb2ae453a113f6557afe5048d428a69af8bbb had these changes

```
-if (WIN32)
-    # parallel build
-    add_compile_options(/MP)
-    add_compile_options(/WX)
-    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /WX")
-    set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} /WX")
-endif()

 if (WIN32)
+    target_compile_options(onnx_proto PRIVATE
+        /MP
+        /MX
+    )
     target_compile_options(onnx PRIVATE
+        /MP
+        /MX
         /wd4800 # disable warning type' : forcing value to bool 'true' or 'false' (performance warning)
         /wd4503 # identifier' : decorated name length exceeded, name was truncated
     )
     target_compile_options(onnx_pybind PRIVATE
+        /MP
+        /MX
```

Which removed /WX and replaced it with /MX. Assuming that was a typo as I get this warning from an MSVC build:
  Warning	D9002	ignoring unknown option '/MX'	onnx_proto	

Correcting this would also require onnx_proto to ignore C4146 as /WX will treat warnings as errors.
        /wd4146 # unary minus operator applied to unsigned type, result still unsigned

**Comment by askhade** [comment]
Seems like this issue is resolved. @skottmckay please reopen it if I am wrong.
