### ISSUE TITLE
consumed_inputs enforced by checker

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#1094]
From the documents of ONNX-1.0 and ONNX-1.1.2 branches, there are no consumed_inputs attributes in BatchNormalization. However, the ONNX checker enforces the existence of that attribute. Is there any plan to fix those release branches? If checker is called before executing a model, this might be a critical bug.

**Comment by bddppq** [comment]
`consumed_inputs` was a special thing in the old days, we later got rid of it in the entire onnx repo and should have bumped BatchNormalization's opset.
I just checked the doc and it's showing up in BatchNormalization-1 (aka opset 1) https://github.com/onnx/onnx/blob/master/docs/Changelog.md#BatchNormalization-1.

**Comment by wschin** [comment]
The document you shared is not the one I saw in ONNX-1.0 and ONNX-1.1.2 branches. This inconsistency leads to my major concern: when checker doesn't match the document (e.g., [BatchNormalization ](https://github.com/onnx/onnx/blob/rel-1.1.2/docs/Operators.md#BatchNormalization)in 1.1.2 Operators.md), which one is the truth? Personally, Operators.md should be the ultimate guide because users may not directly dive into all the source codes. If my assumption is correct, we should not [call checker](https://github.com/onnx/onnx/blob/2f85783fc43576b5e39b207f95d5f789641ae706/onnx/backend/base.py#L57) until it's consistency with Operators.md. Also, I would expect that some runtimes may stay with previous ONNX releases a while so there is likely a need of fixing either their documents or their checkers.

**Comment by weixingzhang** [comment]
Recently, I ran into this issue too.

**Comment by houseroad** [comment]
The problem should be caused by the missed patches while creating the new release package. I think using the new release (e.g., 1.2.2) should solve the problem.
