### ISSUE TITLE
"old" operators do not define shape propagation

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1099]
As can be seen in e.g. https://github.com/onnx/onnx/blob/v1.2.1/onnx/defs/math/old.cc the operators do not define the shape propagation function.

This leads to missing results for shape_inference for the model zoo (e.g. VGG19)

This function should be defined even for old operators where semantic for propagation did not change and/or the models shall be updated.

I'd also suggest to issue a warning if shape cannot be propagated instead of simply not doing it.

**Comment by linkerzhang** [comment]
To solve "This leads to missing results for shape_inference for the model zoo (e.g. VGG19)" is to update the models to latest version. 

For old versions, it's by design that they don't have shape inference functions.

**Comment by linkerzhang** [comment]
btw, @houseroad  is helping to update the models, I think.

**Comment by Flamefire** [comment]
> For old versions, there is indeed no shape inference function, which I don't think we should add them now.

Why? The work is pretty basic C&P from the new versions as most of them just removed/added an attribute. Updating the example models only helps for these. Solving the root cause would help others too that have or are even stuck with old version models.

Would you at least consider adding a warning when shape inference is not available? This has to to be shown to the user and a programmer (I mean: When I call the function from python, then my python code should be able to know, that shape inference failed and why)
