### ISSUE TITLE
Missing/wrong documentation for opset_import/OperatorSetId

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1100]
The OperatorSetId is not defined in https://github.com/onnx/onnx/blob/master/docs/IR.md

> opset_import | OperatorSetId | A collection of operator set identifiers made available to the  model. An implementation must support all operators in the set or reject  the model.

`operator set identifiers` may be assumed to be a simple string. In fact it is a `{domain, version}` struct.

**Comment by linkerzhang** [comment]
@NiklasGustafsson is helping to refine ONNX documentation.
