### ISSUE TITLE
Check matching shapes in model-checker/shape_inference

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1101]
I think (at least) the VGG19 example onnx file has an error which is not detected due to insufficient checking of input/output dimensions.

It affects the first GEMM layer. The output of the preceding MaxPool layer is: 
`"pool5_1"{ tensor:FLOAT, shape: [1x512x7x7]}`

The GEMM layer gets `[u'pool5_1', u'fc6_w_0', u'fc6_b_0'])` with `%fc6_w_0[FLOAT, 4096x25088]
  %fc6_b_0[FLOAT, 4096]`

While this is practically matching (`512*7*7 == 25088`) it would need an extra Flatten layer to be valid because Gemm is defined as A[M x K] * B[K x N].

I therefore propose to add appropriate checks to the model-checker or at least to the shape_inference

**Comment by houseroad** [comment]
@anderspapitto shall we consider how to combine the shape inference with checker?

**Comment by Flamefire** [comment]
Furthermore: How would one handle such a model? IMO it would be correct, to reject it, as the shape is not `(M,N)` as the operator expects. But then the definition says: "The shape of A should be (M, K)", so it is not a **must**.

Could the checker generally be extended to check, that the dimensionality of the tensors is correct?
