### ISSUE TITLE
Error in exporting PyTorch model to ONNX 

### ISSUE THREAD

**Issue by wise-east** [onnx/onnx#1109]
`loaded_model = torch.load('BLSTM-CRF_bie_model_best.pt')`
`torch.onnx.export(loaded_model, inputs, "BLSTM_onnx.pt")`
*`inputs` is a dummy input that is in correct form for the built model 

I'm trying to convert a model trained with PyTorch to a format that is compatible with ONNX, but the lines of code above are returning an error. I have followed the instructions shown in the tutorial.  I simply can't figure out what the problem is and would welcome any kind of guidance. 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-172-321e852c15a8> in <module>()
----> 1 torch.onnx.export(loaded_model, inputs, "BLSTM_onnx.pt")
      2 #Returns the following error:
      3 #RuntimeError: /Users/soumith/code/builder/wheel/pytorch-src/torch/csrc/jit/tracer.h:117: getTracingState: Assertion `var_state == state` failed.

~/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py in export(*args, **kwargs)
     23 def export(*args, **kwargs):
     24     from torch.onnx import utils
---> 25     return utils.export(*args, **kwargs)
     26 
     27 

~/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten)
     82             as ATen ops.
     83     """
---> 84     _export(model, args, f, export_params, verbose, training, input_names, output_names)
     85 
     86 

~/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_type)
    132     # training mode was.)
    133     with set_training(model, training):
--> 134         trace, torch_out = torch.jit.get_trace_graph(model, args)
    135 
    136     if orig_state_dict_keys != _unique_state_dict(model).keys():

~/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py in get_trace_graph(f, args, kwargs, nderivs)
    253     if not isinstance(args, tuple):
    254         args = (args,)
--> 255     return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
    256 
    257 

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             hook(self, input)
    488         if torch.jit._tracing:
--> 489             result = self._slow_forward(*input, **kwargs)
    490         else:
    491             result = self.forward(*input, **kwargs)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    477         tracing_state._traced_module_stack.append(self)
    478         try:
--> 479             result = self.forward(*input, **kwargs)
    480         finally:
    481             tracing_state.pop_scope()

~/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py in forward(self, *args)
    286         _tracing = True
    287         trace_inputs = _unflatten(all_trace_inputs[:len(in_vars)], in_desc)
--> 288         out = self.inner(*trace_inputs)
    289         out_vars, _ = _flatten(out)
    290         _tracing = False

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             hook(self, input)
    488         if torch.jit._tracing:
--> 489             result = self._slow_forward(*input, **kwargs)
    490         else:
    491             result = self.forward(*input, **kwargs)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
    465     def _slow_forward(self, *input, **kwargs):
    466         input_vars = tuple(torch.autograd.function._iter_tensors(input))
--> 467         tracing_state = torch.jit.get_tracing_state(input_vars)
    468         if not tracing_state:
    469             return self.forward(*input, **kwargs)

~/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py in get_tracing_state(args)
     33     if not torch._C._is_tracing(args):
     34         return None
---> 35     return torch._C._get_tracing_state(args)
     36 
     37 

RuntimeError: /Users/soumith/code/builder/wheel/pytorch-src/torch/csrc/jit/tracer.h:117: getTracingState: Assertion `var_state == state` failed.

**Comment by strayMat** [comment]
I have the same issue when exporting another pytorch implementation of a [biLSTM-CRF](https://github.com/strayMat/tag_serve/tree/master/nermodel). Could this be the LSTM operator which does not seem to be supported by   onnx for now ? (as stated [here](https://pytorch.org/docs/master/onnx.html)).

**Comment by prasanthpul** [comment]
This is an error with PyTorch and can't be addressed in ONNX. Please file the issue at https://github.com/pytorch/pytorch/ to the right folks can address it
