### ISSUE TITLE
 "pooling_convention"/"ceil_mode"  attribute for pooling operators (Max/Avg)

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#1113]
Ref:    https://github.com/onnx/onnx/issues/549

Current pool operators do not have "ceil_mode" option. ONNX expects ""Floor value of the dimension is used"
https://github.com/onnx/onnx/blob/master/docs/Operators.md#MaxPool

Frameworks while exporting could adjust padding to match the "floor" value, but this might lead to accuracy issue, since for given input shape  and kernel shape,  changing the pad values will lead to different pooling values.

Proposing to add this attribute to all pool operators.

**Comment by Roshrini** [comment]
@bddppq @houseroad

**Comment by houseroad** [comment]
yes, agree, @spidyDev do you mind to create a PR to add this feature to max/avg pools?

**Comment by riacheruvu** [comment]
Any progress on this issue?
