### ISSUE TITLE
Squeeze operator attribute "axes" should be optional.

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#1114]
Currently squeeze operator requires attribute "axis"  attribute .(https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze)

I think this attribute should be marked optional. As per convention on most frameworks( i.e TF, Pytorch, MXNet), absence of this attribute meant all the dimensions with value "1" will be removed.

This will be useful  for converters while exporting models to ONNX when "axis" is not specified, else the input shape has to be determined. Also, will be in accordance with numpy squeeze definition

@bddppq @houseroad @dzhulgakov

**Comment by houseroad** [comment]
I agree with you. I have crafted a PR to address this https://github.com/onnx/onnx/issues/1114
I prefer not bumping up the opset version since it's backward compatible and it's more like a spec bug fixing. Feel free to review it.
