### ISSUE TITLE
support for locally connected layer (SpatialConvolutionLocal in pytorch)

### ISSUE THREAD

**Issue by mohsenmalmir** [onnx/onnx#112]
are there any plans to support spatial convolution from pyTorch?
I saved my network using onnx from pytorch, and it includes SpatialConvolutionLocal node. When loading it from onnx, it throws the following error:

`  File ".../python2.7/site-packages/onnx/checker.py", line 36, in check_node
    'Node op_type {} not recognized by onnx.'.format(node.op_type))
NameError: Node op_type SpatialConvolutionLocal not recognized by onnx.
`

The forward function of my network definition is like this:

 `    

       def forward(self, x):

        local = torch.nn.backends.thnn.backend.SpatialConvolutionLocal.apply

        x = local(x, self.W1, self.B1, 7, 7, 1, 1, 0, 0, 21, 29, 15,23)

        ...

        return x
`

Thanks!

**Comment by prasanthpul** [comment]
Please reopen if it's still an issue with latest ONNX and latest PyTorch
