### ISSUE TITLE
CELU as an ONNX operator?

### ISSUE THREAD

**Issue by zasdfgbnm** [onnx/onnx#1121]
I'm adding CELU ([paper](https://arxiv.org/pdf/1704.07483.pdf)) to PyTorch (https://github.com/pytorch/pytorch/pull/8551). I want to be able to export this operator to ONNX, but I don't know what is the best way to do that.

One option is to add a new operator `Celu` to onnx, and PyTorch just export a node named 'Celu'. Another option is to export it as composed by existing ops.

I don't know which is better:

On the one hand, `Elu`, `Selu`, `Relu`, etc. are all there in ONNX, although they can be easily composed by existing ops. Which makes it looks better to make `Celu` part of the family.

On the other hand, there are some other operators that is also very common but can be composed by existing ops not in ONNX, such as https://github.com/onnx/onnx/issues/870.

**Comment by prasanthpul** [comment]
Probably best to do it as a function. That way it can be optimized by runtimes that know about it but can still be executed by those that don't. @linkerzhang what do you think? do we need any enhancement to functions to fully enable this?

**Comment by ebarsoum** [comment]
Yes, if still interested please add it as function: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md

**Comment by jeremycochoy** [comment]
Hello. I do need CELU unit in production setup. Is someone working on it or can I add it for you? :)
