### ISSUE TITLE
CI Test for PR failing and I don't know why

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1126]
Pull request https://github.com/onnx/onnx/pull/1122 is failing and it's not clear to me from the Travis CI why. Could someone familiar with this please take a quick look and make a suggestion?

The mypy and linting are both ok. 

The PR is to changes initialisation of weights in the LSTM test from constant (1 everywhere) to random values. 

Apologies if this is not the correct place to raise this issue.

**Comment by houseroad** [comment]
I have answer your question in your PR.

**Comment by newling** [comment]
Thanks.
