### ISSUE TITLE
LSTM biases - W bias and R bias -> one bias

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1127]
I am wondering what the motivation is for having both a W bias and an R bias, and not just a single bias per gate. It seems unnecessary as they are just added together.

**Comment by newling** [comment]
Seems like it's the same in [Pytorch LSTM](https://pytorch.org/docs/stable/nn.html?highlight=lstm#torch.nn.LSTM) which is apparently an artefact from CuDNN as discussed [here](https://discuss.pytorch.org/t/redundant-biases-in-lstm-definition/5668) . Is there a good motivation for ONNX to do it like this though?

**Comment by newling** [comment]
I guess having 2 biases makes a difference for training. With two biases, overall update will be different:  suppose the two bias vectors are initialised with the same values, each is updated with `rate*dL/dbias`, so effectively the overall bias is updated with `2*rate*dL/dbias`, twice what it would be if there was just one bias vector.

**Comment by bddppq** [comment]
As you have figured out, they are two parameters during training, so conceptually they are different. Besides, we intentionally designed such fixed RNNs to match the representation as in vendor libraries so backends can easily add support to it by directly passing to vendor libraries.

**Comment by newling** [comment]
Ok, thanks for verifying. It seems like a good design choice to me now 👍
