### ISSUE TITLE
TensorProto with empty dims

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1131]
In an ONNX LSTM model exported from Pytorch, there are Constant NodeProtos whose TensorProtos have rank 0 (i.e. `dims_size()` returns zero). Moreover `raw_data().size()` is greater than the size of the type (in this type `INT64`), so the tensors are not singletons.

Is this valid? i.e. can dims be an empty repeated int64? 

Please let me know if you need more info.

**Comment by dzhulgakov** [comment]
Do you have a small repro? Also, what is the size of raw_data().size()? cc @anderspapitto 

In general empty dims means 0-rank tensor aka scalar

**Comment by bddppq** [comment]
@newling @dzhulgakov Do I understand correctly that it's indeed a scalar/singleton so we can close this issue?

**Comment by newling** [comment]
Hi, yes sorry I should have closed this - indeed a singleton. Closing.
