### ISSUE TITLE
Mapping between tensorproto seq in initializer and value info seq in input

### ISSUE THREAD

**Issue by aggarwal-himanshu** [onnx/onnx#1133]
Hi,
I wanted to know how the onnx maps contents of tensorproto passed in initializer to value_info_proto passed in inputs, while creating a graph. I am trying to create a simple convnet with predefined weights. 

Also, here weights and biases should be treated as external inputs right? and should be specified in make_graph as inputs?
Thanks.

**Comment by bddppq** [comment]
weights appear both in initializers (as TensorProto with actual numeric values) and in `graph.input` (only ValueInfoProto, so only the meta data like data type and shape).

**Comment by aggarwal-himanshu** [comment]
Thanks @bddppq
