### ISSUE TITLE
Div operator behavoir for integers

### ISSUE THREAD

**Issue by kit1980** [onnx/onnx#1153]
The spec doesn't define it, what's the expected result for Div and integer types, like Div([1, 2], [3, 4])?

**Comment by houseroad** [comment]
The output type will be Integer as well. The result should be [0, 0]

**Comment by kit1980** [comment]
What about Div([-1, -2], [3, 4]) ?
And can you add this to the spec?

**Comment by cbourjau** [comment]
There are examples in the docs, but it is not written out explicitly. I think this issue is still relevant.
