### ISSUE TITLE
shape in reshape operator a TensorProto?

### ISSUE THREAD

**Issue by aggarwal-himanshu** [onnx/onnx#1160]
Can someone help me what type does reshape expects for shape. Is shape needs to be a TensorProto, just like how weights are in conv (and need to be passed as both initializer and input), or  is it need to be TensorShapeProto?

Thanks

**Comment by houseroad** [comment]
The second input of `Reshape` expects an int64 tensor. It can be an output of `Constant` node, or a TensorProto in the initializer list.

**Comment by houseroad** [comment]
Yes, it can be, as long as it's int64 tensor.
