### ISSUE TITLE
the output of Tiny Yolo V2 is not correct

### ISSUE THREAD

**Issue by aoke79** [onnx/onnx#1162]
Dear Sir,
I'm trying to use Tiny_yolo_v2 to do the detection, but I found the Width/Height of the Box is not correct, which should be in [0, 1], after we compute it. many of them are very huge. 
Box_Width = (float)((grid[index+2] * c_biases[2 * box_index + 0]) / 13);
Box_Height = (float)((grid[index+2] * c_biases[2 * idx_box + 1]) / 13);
Might you please help check that?
thanks a lot,
-Sam

**Comment by prasanthpul** [comment]
I assume you are using the model from the zoo? https://github.com/onnx/models/tree/master/tiny_yolov2 If so, we should move this issue to the zoo.

**Comment by aoke79** [comment]
hi prasanthpul ,
Yes, I've downloaded the model there, please  help move the issue there. 
thanks a lot,
-Sam

**Comment by prasanthpul** [comment]
moved to model zoo
