### ISSUE TITLE
Google Net would not work for GPU

### ISSUE THREAD

**Issue by aoke79** [onnx/onnx#1163]
Dear Sir,
I have integrated GoogleNet, but I found it works on CPU, but I choose GPU, it failed. I don't know why. Might you please help check that. I'm using Microsoft's sample code,Windows Machine Learning Explorer, to integrate this model. the link is like below:
https://docs.microsoft.com/en-us/windows/uwp/machine-learning/samples
https://blogs.technet.microsoft.com/machinelearning/2018/03/13/how-three-lines-of-code-and-windows-machine-learning-empower-net-developers-to-run-ai-locally-on-windows-10-devices/

thanks a lot,
-Sam

**Comment by prasanthpul** [comment]
Since this is specific to WindowsML, please file the issue with Windows. On the Windows 10 machine, type “feedback” on your search box, bring up the Feedback Hub app and follow the flow.
