### ISSUE TITLE
[Proposal] Operators

### ISSUE THREAD

**Issue by cheolho** [onnx/onnx#1168]
I would like to use a custom model in converting models through mmDNN.
While converting, I got some warnings and errors.
```
UserWarning: ONNX export failed on ATen operator norm because torch.onnx.symbolic.norm does not exist
UserWarning: ONNX export failed on ATen operator clamp_min because torch.onnx.symbolic.clamp_min does not exist
```

I propose operators:
- torch.onnx.symbolic.norm
- torch.onnx.symbolic.clamp_min

**Comment by houseroad** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L693 torch.norm is able to be exported.
