### ISSUE TITLE
The way to feed inputs, named value pairs or just an array?

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1171]
I'm looking the sample code on https://github.com/onnx/models

```python
model = onnx.load('model.onnx')
test_data_dir = 'test_data_set_0'

# Load inputs
inputs = []
inputs_num = len(glob.glob(os.path.join(test_data_dir, 'input_*.pb')))
for i in range(inputs_num):
    input_file = os.path.join(test_data_dir, 'input_{}.pb'.format(i))
    tensor = onnx.TensorProto()
    with open(input_file, 'rb') as f:
        tensor.ParseFromString(f.read())
    inputs.append(numpy_helper.to_array(tensor))

# Run the model on the backend
outputs = list(backend.run_model(model, inputs))
```

The code indicates, model's input is an ordered array.  But I don't think onnx spec defined the order at anywhere. 

Should we define it?

**Comment by jerryz123** [comment]
Has this been resolved? Is this defined anywhere?

I'm implementing an ONNX backend right now, and the issue I'm running into is I do not know how to bind the inputs array from `run_model` to the list of input Tensors defined in the ONNX graph. 
It seems like the order needs to correspond with the order in which they are defined in the model proto.

However, how does this work when I have a model with inputs A, B, where A has an initializer but B does not, and I want to only pass in input for B?
