### ISSUE TITLE
Dropout random node test

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#1173]
The `test_dropout_random`, located [here](https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node/test_dropout_random), has the `ratio` attribute set to 0.2 . However, the input and output in the test are exactly same.

How can I have a valid dropout and still get output to be same as the input?

**Comment by ebarsoum** [comment]
dropout is pass-through in inference.

**Comment by houseroad** [comment]
@ayush1999 like @ebarsoum said, right now, onnx only supports inference.

**Comment by ayush1999** [comment]
So just to be clear, dropout works only when training, right? During the testing, the Dropout should be inactive.

**Comment by houseroad** [comment]
Yes, `Dropout` right now just behaves as `Identity`. There is a working group on this topic, if you are interested, feel free to reach out in the gitter room. https://gitter.im/onnx/training

At the moment, officially, onnx is for inference only.
