### ISSUE TITLE
Backward pass on two layers connected to one 

### ISSUE THREAD

**Issue by manuelelucchi** [onnx/onnx#1186]
Hi, I have a doubt
In this situation we have the Maxpool output that get copied to both the 2 connected nodes (resnet 18v2 onnx pretrained from your models repo opened with Netron) but how will this managed in the backward? the two gradient will be summed or something else? it's not explicit since maxpool expects only one gradient
![schizzo](https://user-images.githubusercontent.com/17146198/42601089-c1b137fe-8564-11e8-80da-e935acc5de76.png)

Regards, 
Manuele

**Comment by linboqiao** [comment]
I use netron to show computaion graph,  but it only shows forward phase ops.
Have you figured out how to draw a computation graph in backward phase?
