### ISSUE TITLE
Missing alpha and beta values

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#1189]
I was trying to load the vgg19 model in the onnx/models repo. However, the `gemm` operator in the model doesn't seem to have to `alpha` or `beta` attributes. Also, the operator docs ([here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gemm)) don't mention any default values that the attributes should take in case they are missing from a  model.

Can you tell me what do these attributes default to? Also, it'd be better to add this data in the docs too.

cc @houseroad Some urgent help please.

**Comment by houseroad** [comment]
It's 1.0 and 1.0. Will fix it in https://github.com/onnx/onnx/pull/1193

**Comment by houseroad** [comment]
Fixed
