### ISSUE TITLE
Creating Constant operator with float16 data type causes error.

### ISSUE THREAD

**Issue by arogowie-intel** [onnx/onnx#1190]
Hi, 

I was trying to run this code:
```
values = np.random.randn(5, 5).astype(np.float16)
node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['values'],
    value=onnx.helper.make_tensor(
        name='const_tensor',
        data_type=onnx.TensorProto.FLOAT16,
        dims=values.shape,
        vals=values.flatten(),
    ),
)
```

Creating and running such node with onnx version 1.2.2 installed with flag `--no-binary` from `pip` causes following error:
```
>           getattr(tensor, field).extend(vals)
E           TypeError: -0.2021 has type numpy.float16, but expected one of: int, long

../../../../.virtualenvs/onnx/lib/python3.5/site-packages/onnx/helper.py:152: TypeError
```

According to [doc](https://github.com/onnx/onnx/blob/master/docs/Operators.md#type-constraints-14) `float16` type should be supported.

**Comment by benschreiber** [comment]
I am seeing the same issue when trying to use make_tensor for float16.

**Comment by jcwchen** [comment]
Use the conversion mention here: https://github.com/onnx/onnx/issues/3715#issuecomment-919232773 should help. Close this old issue now. Please reopen it if you still have question. Thanks!
