### ISSUE TITLE
Is Dlib support in the plans?

### ISSUE THREAD

**Issue by RobertoMalatesta** [onnx/onnx#12]
Is a to-Dlib support in the plans?
I find it very effective for pre-trained models deployment, especially in resource-constrained environments, so a Dlib ouputputter wold be really handy.

Thank you for this project.

-- Rob

**Comment by prasanthpul** [comment]
We would welcome community contribution for this.

You can also use https://github.com/Microsoft/onnxruntime, written in C++ to be a high performance cross platform inference engine for onnx models
