### ISSUE TITLE
install failed.   conda install -c ezyang onnx

### ISSUE THREAD

**Issue by shuweihsu** [onnx/onnx#120]
Hit the this error on Windows 10 64bit (build 16299).  Could someone please take a look?  Thanks!

(C:\Users\swhsu\AppData\Local\Continuum\anaconda3) C:\Users\swhsu\Documents>conda install -c ezyang onnx
Fetching package metadata ...............

PackageNotFoundError: Packages missing in current channels:

  - onnx

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/ezyang/win-64
  - https://conda.anaconda.org/ezyang/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by houseroad** [comment]
@ezyang probably does not compile the windows version and upload it.

**Comment by ezyang** [comment]
I'll give it a try.

**Comment by houseroad** [comment]
Now we use conda-forge channel.
