### ISSUE TITLE
MaxUnpool Operator Request

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#1217]
Since MaxPool can output indices, next step is MaxUnpool operator.

**Comment by waltsims** [comment]
Any Progress on this? I'm trying to do live inference of [a type Unet model](https://github.com/abhi4ssj/quickNAT_pytorch).

**Comment by prasanthpul** [comment]
MaxUnpool was added several months ago: https://github.com/onnx/onnx/pull/1494
