### ISSUE TITLE
Where is list of features, what all could be done with onnx?

### ISSUE THREAD

**Issue by abhishekkumardwivedi** [onnx/onnx#122]
I did go through some blogs and could understand onnx is for translating model from one platform to the other. But upon coming to onnx github, I didn't get proper idea on how to use it, what all features and frameworks are supported, whom it is for, etc. README should be little more then installation instruction or to have link of other references.

**Comment by ebarsoum** [comment]
ONNX is a common intermediate presentation of a computation graph,, it targets framework developers. It is not for translating per se, each framework have its own way to represent a neural network graph, ONNX is a way to standardize that.
