### ISSUE TITLE
MaxPool pads vs auto_pad

### ISSUE THREAD

**Issue by arogowie-intel** [onnx/onnx#1230]
Which attribute takes precedence in case when both are present?

**Comment by arogowie-intel** [comment]
@houseroad  Thank you for your response! 

Regarding to what you've just written, please update [MNIST model  opset 7](https://www.cntk.ai/OnnxModels/mnist/opset_7/mnist.tar.gz) since it has MaxPool nodes with simultaneously  existing both `pads` and `auto_pad` attributes.

Moreover there is incorrect MNIST opset 1 version [model](https://www.cntk.ai/OnnxModels/mnist/opset_7/mnist.tar.gz) in model zoo repository. (There was an [issue](https://github.com/onnx/models/issues/66) regarding this). This one also should be updated.

Sorry if this is not the right place to report problems with model zoo.

**Comment by houseroad** [comment]
@arogowie-intel could you open an issue in the model zoo repo? @prasanthpul is in charge of this MNIST model.

**Comment by houseroad** [comment]
@arogowie-intel actually `auto_pad` has value `NOTSET`. I think which is OK.

**Comment by arogowie-intel** [comment]
According to [documentation](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#attributes-48) `NOTSET` isn't a correct value. The only legitible ones are:

>  auto_pad must be either SAME_UPPER, SAME_LOWER or VALID

 I think ONNX checker shouldn't pass anything that doesn't conform to documentation.

**Comment by houseroad** [comment]
@arogowie-intel, I agree. We should either fix the model or add `NOTSET` to the spec/doc.

**Comment by postrational** [comment]
It seems `NOTSET` is mentioned in the ONNX definitions here:
https://github.com/onnx/onnx/blob/4695828eac9b31c97fc211b43609c4ba3a9cd9e7/onnx/defs/nn/defs.cc#L205

The default value is not presented on the generated `Operators.md` documentation:
https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by houseroad** [comment]
I added it https://github.com/onnx/onnx/pull/1274

**Comment by houseroad** [comment]
The doc is updated. :-)
