### ISSUE TITLE
ONNX 1.3 Release

### ISSUE THREAD

**Issue by jspisak** [onnx/onnx#1234]
Release Note [Preliminary]
---------------------------
Snapshot release of master commit onnx/onnx@bae6333

- ONNXIFI 1.0
  - [ONNX native backend interface](https://github.com/onnx/onnx/blob/master/docs/ONNXIFI.md)
- Operator Set 8
  - Control Flow Operators graduated from experimental
    - [Loop](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Loop), [If](https://github.com/onnx/onnx/blob/master/docs/Operators.md#If) and [Scan](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Scan)
  - Added new operator [Expand](https://github.com/onnx/onnx/blob/master/docs/Operators.md#expand-8)
  - Updated operators [Max](https://github.com/onnx/onnx/blob/master/docs/Operators.md#max), [Min](https://github.com/onnx/onnx/blob/master/docs/Operators.md#min), [Mean](https://github.com/onnx/onnx/blob/master/docs/Operators.md#mean) and [Sum](https://github.com/onnx/onnx/blob/master/docs/Operators.md#sum) to support broadcasting
  - Support output indices in operator [MaxPool](https://github.com/onnx/onnx/blob/master/docs/Operators.md#maxpool)
  - Varies documentation improvements
- Introduced `Function` concept for representing composed operators [experimental]
  - [MeanVarianceNormalization](https://github.com/onnx/onnx/blob/master/docs/Functions.md#experimental-meanvariancenormalization) is our first example of using this feature
- Enhanced shape inference
  - Support shape inference for Reshape operator with constant new shape
- More ONNX optimization passes
  - Available passes are [here](https://github.com/onnx/onnx/blob/master/onnx/optimizer/optimize.h#L30)
- More operator backend tests
  - New [test coverage stat page](https://github.com/onnx/onnx/blob/master/docs/TestCoverage.md) is added
- Opset Version Converter
  - Supported operators include: Add, Mul, Gemm, Relu, BatchNorm, Concat, Reshape, Sum, MaxPool, AveragePool, Dropout
  - All models in [model zoo](https://github.com/onnx/models) are covered, except [tiny-yolo-v2](https://github.com/onnx/models/tree/master/tiny_yolov2) (PRelu needs adapter, WIP)
- Quantization coming soon
  -  We are currently working with the community to collect more feedback and finalize. We expect this to happen quickly and will be released as quickly as possible and out of cycle if needed.
----
Shall we kick off the effort around the 1.3 release? My initial thoughts:
- We target a clean release from master (not a cherry pick)
- Keep RNN/CF as experimental 
- Converge and merge quantization (if possible)

Thoughts?

cc @Maratyszcza @prasanthpul @linkerzhang @lupesko @houseroad @bddppq

**Comment by Maratyszcza** [comment]
We also want to release ONNXIFI 1.0 together with ONNX 1.3

**Comment by houseroad** [comment]
Per offline discussion with @bddppq, we won't provide binaries in new release (on Linux platform, Windows should still provide binaries). If your local gcc's version is higher than 4.9, installing new release should address the issues.

**Comment by houseroad** [comment]
Just checked, our conda package is 1.1.2. Let's also cover the conda part, too.

**Comment by houseroad** [comment]
BTW, probably we can also add opset version converter into 1.3.
