### ISSUE TITLE
export failed on GRU because batch_first not supported

### ISSUE THREAD

**Issue by lovettchris** [onnx/onnx#1245]
Anyone know how to workaround this issue?  
```
ONNX export failed on GRU because batch_first not supported
```

I train my GRU model using batch_first=True, so I'm not exactly sure what I need to do to make that trained model exportable.

**Comment by ebarsoum** [comment]
Hi @lovettchris which framework did you use for the training?

**Comment by wangyunxiaa** [comment]
@lovettchris it is not supported "batch_first=True", you should retrain your model by setting batch_first=False, I solved the problem by this way.
