### ISSUE TITLE
caffe2 backend for resnet50 opset 6 onnx model fails on batches of > 1 images

### ISSUE THREAD

**Issue by tareshsethi** [onnx/onnx#1249]
I am trying to use caffe2's backend to run a resnet50 onnx model (opset 6). I am able to run the backend on a single image input as a numpy array of size (1 x 3 x 224 x 224), but am unable to run the backend with the exact same code on two images input as a numpy array of size (2 x 3 x 224 x 224). In workspace.py (caffe2), there seems to be a value error indicating I/O operation on closed file, and then a runtime error copied below. I am currently running on cpu. If it helps, caffe2's backend on the squeezenet onnx model (opset 6) works fine for batches of > 1 images

RuntimeError: [enforce fail at reshape_op.h:104] total_size == size. 4096 vs 2048. Argument `shape` does not agree with the input data. (4096 != 2048) Error from operator: 
input: "gpu_0/pool5_1" input: "OC2_DUMMY_1" output: "OC2_DUMMY_0" output: "OC2_DUMMY_2" name: "" type: "Reshape" device_option { device_type: 0 cuda_gpu_id: 0 }

**Comment by houseroad** [comment]
The `Reshape`'s output is statically determined... which is really bad...

**Comment by tareshsethi** [comment]
Thank you for your response. Is there an easy way to change the reshape's output without working with the caffe2/onnx code? Or is the best way to run inference on multiple images just to loop about those images

**Comment by houseroad** [comment]
One thing we can do is to apply constant folding on `Reshape`, if both inputs are available in initializers, we can eliminate such `Reshape`. Are you interested in creating an optimization pass for this?

**Comment by houseroad** [comment]
Actually, there is a simple fix on this. We can use -1 for the first dimension in `Reshape`. I will update the model later.

**Comment by tareshsethi** [comment]
Thank you!
