### ISSUE TITLE
ConstantFill ops' input should be better documented?

### ISSUE THREAD

**Issue by pengwa** [onnx/onnx#1253]
It seems that input can be 2 type of data:

- input tensor, which can be of any type
- shape tensor, which should be of type int. 

In document, it says:
"If input_as_shape is set to true, then the input should be a 1D tensor containing the desired output shape (the dimensions specified in extra_shape will also be appended)"

what if input_as_shape is set to false? Shall we make the document more clear? since when I fist read it, just think the input type T1 is not correctly, mixed with float and int. 
"T1 : tensor(float), tensor(int32), tensor(int64), tensor(bool)
Constrain input types to float, int32, int64, bool tensors."

**Comment by prasanthpul** [comment]
ConstantFill was an experimental op and has been removed
