### ISSUE TITLE
how to transform a kaldi model to onnx

### ISSUE THREAD

**Issue by wangyunxiaa** [onnx/onnx#1265]
I want to transform a kaldi model to onnx， however onnx do not support the framework by now, if i want to do this without its own tool,how could i do? Shoud i install the pykaldi environment on my computer and do the transform by myself ?  can i complete my work just with the onnx?

**Comment by prasanthpul** [comment]
The Kaldi authors, the community, or you would need to create a converter to take a Kaldi model and convert it into ONNX. The converter can be standalone or built into Kaldi. Depending on the operators in Kaldi, not all Kaldi models may currently be convertible to ONNX. You can see examples of other converters in the onnxmltools and tensorflow-onnx repos. The ONNX format is described in https://github.com/onnx/onnx/blob/master/docs/IR.md

**Comment by wangyunxiaa** [comment]
Do I need to install pykaldi  on my computer？ since onnx installed in python environment while kaldi common used and trained in c++ environment. if i donot have python-kaldi environment,how to load and parse the kaldi model?  thank you very much for your reply~

**Comment by wangyunxiaa** [comment]
by the way,if i used a unit of p-lstm to affine its output to a fixed value not default by the hidden number, could the onnx have corresponding unit? i have check the file "operators.md", but have not find the corresponding lstm unit. however i find "<sub>experimental</sub> <a href="#GRUUnit">GRUUnit</a>",but it has no detail definition, is this a unit defined by the user ?

**Comment by wangyunxiaa** [comment]
I also confused that how can I load and parse the kaldi model while caldi is trained in c++ environment,if I want to transform the model to onnx on python,shoud I install the pycaldi?

**Comment by prasanthpul** [comment]
For Kaldi questions, you should ask on the Kaldi GitHub or forums. Folks here do not know about Kaldi.

**Comment by wangyunxiaa** [comment]
well,thank you very much for your reply! if my lstm-unit has a projection,which means that the output dim is not equal to the hidden units number,does this unit supported by ONNX?

**Comment by askhade** [comment]
Closing this as stale issue.
