### ISSUE TITLE
Downsampling op

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1266]
Is there an op to downsample a tensor? The exact opposite of the  [Upsample](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample) op

In other words something like numpy slicing,
 
```
X = numpy.random.randn(10, 10, 10, 10)
X[0::2, 0::3, 1::4, 2::2].shape
Out[13]: (5, 4, 3, 4)
```

**Comment by newling** [comment]
Trying to figure out how pytorch handles striding, I exported a model with x[0::2, 0::2]:

```
In [27]: downsample()
/usr/local/lib/python3.6/site-packages/torch/onnx/symbolic.py:65: UserWarning: ONNX export failed on slice because step!=1 is currently not supported not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
```

Seems like this means the smaller resnet architectures (18, 34) as described in the original paper cannot be represented in ONNX.

**Comment by SleepProgger** [comment]
I just ran into the same problem.
Is there any way around this ?
Torch supports striding just fine, and so does the onnx specs, so in wonder why this is not supported.

**Comment by marcoleewow** [comment]
I am facing the same problem, @SleepProgger did you find a workaround solution?

**Comment by askhade** [comment]
ONNX now has a resize op. The scales input when set to < 1 will do downsampling
