### ISSUE TITLE
Opset version in backends that support Onnx importing

### ISSUE THREAD

**Issue by tareshsethi** [onnx/onnx#1268]
Hello! I am trying to survey which backend/s to enable onnx importing. I've installed caffe2 and am able to import an onnx model, but I've realized that the installed caffe2 backend only supports models that were generated using opset 6. How can I easily find which opset a backend supports?

**Comment by houseroad** [comment]
In most cases, c2 onnx backend should also be able to run the opset 7 and opset 8 models

**Comment by houseroad** [comment]
most frameworks is under quick development, we don't have that list yet, and it's not easy to maintain either.

**Comment by prasanthpul** [comment]
ONNX Runtime supports all ONNX opsets since 7: https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md
