### ISSUE TITLE
Different initializer formats in ModelProto files

### ISSUE THREAD

**Issue by JamesAllingham** [onnx/onnx#1271]
Hi all,

I've been working on importing ONNX ModelProto files and I've come across something that has confused me. It seems to me that ModelProto files with the same IR version, can store the initializers in different formats.

This is the case with the SqueezeNet found in the old (and deprecated) ONNX [model zoo](https://github.com/lupesko/model-zoo/tree/master/models/image_classification/squeezenet) and the one found in the new [model zoo](https://github.com/onnx/models/tree/master/squeezenet). 

In the case of the older ModelProto, the initializer tensors all seem to be in the *raw_data* field where as in the case of the newer ModelProto, the field containing the initializer tensors seems to be determined by the *data_type* field (i.e. if the datatype is "Float" then the corresponding tensor is in the "float_data" field).

Is the older format deprecated or must I be able to support both of them? Does the ONNX specification guarantee that if there is data in the raw_data field there will not be any in the other fields? In other words: can I use this to determine which format is being used?

**Comment by snnn** [comment]
You should support both of them.

**Comment by houseroad** [comment]
Please check: https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L360

Yes, you can use either `raw_data` or `type_data` field. But only one should be present, otherwise, it won't be valid.

**Comment by taliesinb** [comment]
@houseroad can you clarify the reason that raw_data is still present vs xxx_data, if the opportunity for more efficient packing makes xxx_data strictly better? my guess was that packing that protobuf might choose to do for xxx_data could be slower, so the choice gives applications a tradeoff between size and speed.

**Comment by askhade** [comment]
raw_data is usually used to hold large initializers. Although there is no guidance/suggestion from onnx to use one or the other per my knowledge. In case of large models, we also enable storing the data in external files and in this case all the tensors with raw data are serialized to external files.
