### ISSUE TITLE
graph.shape_dict has keys without values

### ISSUE THREAD

**Issue by jbmaxwell** [onnx/onnx#1272]
I'm trying to convert a "tiramisu" UNet (https://github.com/bfortuner/pytorch_tiramisu) to coreml, via onnx-coreml. During the conversion I was getting an error: `TypeError: Error while converting op of type: Concat. Error message: Unsupported axis 1 in input of shape`. Of course, this is a onnx-coreml problem, not onnx, but tracking down the error I discovered that many layers have shape_dicts with keys but no values—i.e., no shape entry. Is this a bug, or is there some way to track down why this is happening?

My conversion is super basic, at this stage:
```
import torch
from torch.autograd import Variable
import torch.onnx

dummy_input = Variable(torch.randn(1, 3, 88, 128).cuda())
torch.onnx.export(model, dummy_input, 'convertedModel.onnx')
```

**Comment by askhade** [comment]
Initially we did not have shape inference implemented for all ops. Since then, we have improved shape inference a lot. Please try again with the latest onnx and create a new issue if you see the same behavior.
