### ISSUE TITLE
Typing of variadic inputs and outputs

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#1273]
This issue relates to the typing of variadic inputs and outputs of operators. The mechanism/language for specifying the signature of operators allows us to specify an input X to be variadic of type T, where the type T can be constrained (e.g., to be a tensor of float or double). The specification is not precise as to whether:

(A) all the actual parameters, say X1 and X2, must have the same type T or
(B) whether they can be of different types T1 and T2 satisfying the given constraint on T.

I think almost all of the existing standard operators are of the kind (A) above: e.g., Concat, Sum, Max, Min.

However, with the experimental control-flow operators (If, Loop), we encounter operators of kind (B) above.

Right now, we don't have a mechanism for distinguishing between (A) and (B), and this will cause problems with type-checking.

We have two possible solutions:

(1) We extend the enum FormalParameterOption (in <https://github.com/onnx/onnx/blob/master/onnx/defs/schema.h> ) by adding a new kind called HeterogeneousVariadic to represent kind (B), and treating the current Variadic to mean kind (A).

(2) We extend the type system (TypeProto in https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto ) to allow sequences and tuples, treating sequences as homgeneous (all elements are of same type) and tuples as heterogeneous (elements can be of different types). 

The second solution has other advantages (we can have more than one input be variadic … a situation that arises with control-flow constructs as well), but is a more significant and bigger change that may take time to work through.

**Comment by ebarsoum** [comment]
I like approach (2) better.
