### ISSUE TITLE
Error converting pytorch to caffe2

### ISSUE THREAD

**Issue by johnsoong** [onnx/onnx#1275]
I succeed in converting pytorch to caffe2.
but I can't run the caffe2 model, it seems that i didn't set is_test flag, how to set this flag in converting.

Traceback for operator -247010440 in network torch-jit-export
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/onnx_caffe2/backend_rep.py", line 48, in run
    workspace.CreateNet(self.predict_net)
  File "/usr/local/caffe2/python/workspace.py", line 147, in CreateNet
    StringifyProto(net), overwrite,
  File "/usr/local/caffe2/python/workspace.py", line 166, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at spatial_batch_norm_op.h:23] (is_test_ && OutputSize() == 1) || (!is_test_ && OutputSize() == 5). 

when I used this caffe2 model in Android:
E/native: [E operator_schema.cc:83] Argument 'is_test' is required for Operator 'SpatialBN'.

Can anyone tell me how to fix it....

THX.

**Comment by prasanthpul** [comment]
Please use the latest PyTorch. If you continue to have issues, please file an issue in the PyTorch github so the right experts can help with this PyTorch/Caffe2 issue.

**Comment by ganliqiang** [comment]
> I succeed in converting pytorch to caffe2.
> but I can't run the caffe2 model, it seems that i didn't set is_test flag, how to set this flag in converting.
> 
> Traceback for operator -247010440 in network torch-jit-export
> Traceback (most recent call last):
> File "", line 1, in 
> File "/usr/local/lib/python2.7/dist-packages/onnx_caffe2/backend_rep.py", line 48, in run
> workspace.CreateNet(self.predict_net)
> File "/usr/local/caffe2/python/workspace.py", line 147, in CreateNet
> StringifyProto(net), overwrite,
> File "/usr/local/caffe2/python/workspace.py", line 166, in CallWithExceptionIntercept
> return func(*args, **kwargs)
> RuntimeError: [enforce fail at spatial_batch_norm_op.h:23] (is_test_ && OutputSize() == 1) || (!is_test_ && OutputSize() == 5).
> 
> when I used this caffe2 model in Android:
> E/native: [E operator_schema.cc:83] Argument 'is_test' is required for Operator 'SpatialBN'.
> 
> Can anyone tell me how to fix it....
> 
> THX.

i have meet isue,have you finished it  and how do you solve this erros ?thanks
