### ISSUE TITLE
C++ static linking of ONNX results in conflicts with existing symbols

### ISSUE THREAD

**Issue by apwojcik** [onnx/onnx#1277]
We are trying to implement an ONNX importer for a C++ runtime. Our runtime will be used by frontend applications, which also use ONNX models.

When trying to execute a process which runs both frontend and backend components, we are seeing errors indicating that a Protocol Buffers symbol name `conflicts with the existing symbol`.

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "onnx.AttributeProto" conflicts with the existing symbol "onnx.AttributeProto".
[libprotobuf FATAL google/protobuf/descriptor.cc:1164] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
 what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
Aborted (core dumped)
```
Did anyone already run into this problem? Have you found a good solution to this issue?

**Comment by yinghai** [comment]
How do you build it? How do you build the onnx lib as dependency?

**Comment by apwojcik** [comment]
We link onnx statically to the importer. We want to use onnx messages as the interface. The client application is supposed to use onnx messages to talk to us. We compile and link against onnx.pb.cc and onnx.pb.h and the client application is using libonnx.

**Comment by yinghai** [comment]
This will likely have problems as protobuf has a global registry based on proto file name. If you have two `.so` file that contains `onnx.pb.cc`, this issue will happen. The trick we do is to define a different namespace for onnx when used in third-party and rely on onnx's CMakefile to do the symbol replacement and renaming. Here is an example:

https://github.com/onnx/onnx-tensorrt/blob/fa0964e8477fc004ee2f49ee77ffce0bf7f711a9/CMakeLists.txt#L93-L97

**Comment by apwojcik** [comment]
I would like to let you know that we eventually fixed the problem by statically linking the protobuf library into our shared object. No namespace change was required in ONNX and the client application is working fine with our library.

**Comment by postrational** [comment]
There may be advantages to choosing one of the approaches or the other. One requires ONNX namespace mangling, the other creates larger binaries. 

@bddppq @yinghai Would you consider the static binding approach? Do you see any reason not to use it?
