### ISSUE TITLE
Test case for conv transpose with group > 1.

### ISSUE THREAD

**Issue by pranavsharma** [onnx/onnx#1279]
Hi, I'm looking for a test case for conv transpose with group > 1. Anyone? Thanks!

**Comment by houseroad** [comment]
Check the data here:

https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/pytorch-converted/test_Conv2d_groups

**Comment by pranavsharma** [comment]
This is for conv, not conv transpose.

**Comment by pranavsharma** [comment]
sure, will do sometime next week.

**Comment by houseroad** [comment]
Awesome, thanks!
