### ISSUE TITLE
onnx installed from binaries has no attribute 'save'

### ISSUE THREAD

**Issue by elboyran** [onnx/onnx#1298]
Installing onnxfrom binaries, e.g. using
`conda install -c conda-forge onnx`.
Running the [notebooks](https://github.com/onnx/onnx/blob/master/onnx/examples) from the [Python API Overview](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md):
[load_model_ipynb](https://github.com/onnx/onnx/blob/master/onnx/examples/load_model.ipynb) works, while
[save_model.ipynb](https://github.com/onnx/onnx/blob/master/onnx/examples/save_model.ipynb) gives an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2b4262020c53> in <module>()
     16 
     17 # Save the ONNX model
---> 18 onnx.save(onnx_model, new_model_path)
     19 
     20 print('The model is saved.')

AttributeError: module 'onnx' has no attribute 'save'
```

The same is observed from a command line:
```
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx.load
<function load at 0x7ff9973dce18>
>>> onnx.save
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnx' has no attribute 'save'
```

**Comment by houseroad** [comment]
Because conda package on conda-forge is outdated. I just checked it's 1.1.2.. too old.

Please install from source.

**Comment by elboyran** [comment]
It is a good idea to either update the binaries or state they are not up to date. 
Installing from binaries is the first thing a new user sees in the **Installation** section of the documentation.
