### ISSUE TITLE
check model failed?

### ISSUE THREAD

**Issue by mlinxiang** [onnx/onnx#1306]
i compile pytorch from src(master branch) and compile onnx from src(master branch)， when i export a pytorch model success, but check model failed as follow, how can i fix this?
![image](https://user-images.githubusercontent.com/6283983/44318145-5e91cb80-a467-11e8-90a2-fd0cb190d751.png)

**Comment by houseroad** [comment]
probably a problem with our check, empty input name means this input is skipped (not provided, since it's optional)

**Comment by mlinxiang** [comment]
@houseroad this is the detail information<https://github.com/pytorch/pytorch/issues/10680> , what can i do to pass this check?

**Comment by mlinxiang** [comment]
have been fix in pytorch master branch
