### ISSUE TITLE
'oneof' in protobuf is not like 'union' in C programming language

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1308]
oneof means:
"At most one field will be set at the same time"

So, you can leave all of them unset. It's not true for C/C++.  Usually It's not what you want.

For example,

```
  message Dimension {
    oneof value {
      int64 dim_value = 1;
      string dim_param = 2;   // namespace Shape
    };
  }
```
What if both dim_value and dim_param are not set?

ONNX should clarify such cases. Is it allowed or not?

**Comment by houseroad** [comment]
one of them should be set. We should clarify it in the spec.

**Comment by snnn** [comment]
> one of them should be set. We should clarify it in the spec.

@gramalingam , do you agree?
