### ISSUE TITLE
proposal: optimization pass  converting Shape() + inferred static shape into static initializers

### ISSUE THREAD

**Issue by 0wu** [onnx/onnx#1309]
I use current version of pytorch/onnx to export an resnet50 model.  It generates a Shape() operator whose result can be inferred statically given fixed size of input to the network.
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/13663916/44373750-aaf8fd80-a49f-11e8-8e95-6a35230b2bdb.png">

Does it make sense to implement optimization passes to
(1) convert Shape +inferred shape into static initializer for the input of the downstream next operator?
(2) perform [constant folding](https://en.wikipedia.org/wiki/Constant_folding) to operators with only constant inputs such as Slice, Squeeze, Unsqueeze, Concat operators in my case?

Alternatively, we could also convert the "shape" input of Reshape operator into Constant  thanks to the inferred shape and remove the subgraph used to compute the shape.

**Comment by daquexian** [comment]
I have developed https://github.com/daquexian/onnx-simplifier for exactly this problem.

Actually, I doubt whether it can be implemented as an optimization pass -- it requires the pass to inference the model.

**Comment by askhade** [comment]
ONNX shape inference is now able to handle such cases. See : https://github.com/onnx/onnx/blob/main/docs/proposals/SymbolicShapeInfProposal.md for details. 

Turn on data_prop during shape inference
