### ISSUE TITLE
Can't load onnx model via CNTK

### ISSUE THREAD

**Issue by dimargn** [onnx/onnx#1312]
Hi
I'm trying to donwload onnx model using CNTK package in Visual Studio
Function modelFunc = Function.Load("D:\\shufflenet\\model.onnx", DeviceDescriptor.CPUDevice, ModelFormat.ONNX);

In the load function i get the following error:
An unhandled exception of type 'System.ApplicationException' occurred in Cntk.Core.Managed-2.3.1.dll
Additional information: Inside File: proto\onnx\ONNXToCNTK.cpp  Line: 412  Function: CNTK::ONNXToCNTKHelper::CreateConstant  -> Feature Not Implemented.

What can be the problem?
I tried to use both CNTK 2.3.1 and 2.3.5
Onnx Model location is https://s3.amazonaws.com/download.onnx/models/opset_8/shufflenet.tar.gz

Thanks

**Comment by ebarsoum** [comment]
Can you try the nightly build? 2.3.1 is pretty old.

**Comment by dimargn** [comment]
I tried to use 2.3.1 after the failure in 2.3.5, it failed in both versions

**Comment by dimargn** [comment]
I can't install nightly build on VS2013. I have there Nuget 4.2.0
Is it possible to install this package just from VS2017?

**Comment by ebarsoum** [comment]
For Python here, the nightly build wheel: https://cntk.ai/nightly-windows.html, you don't need VS.
For .Net you will need to install the nightly build NuGet, you can use VS2017 community edity, which is free.

Also, this repo is for ONNX related issues, please continue the discussion for CNTK issue in CNTK github repo.
