### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#133]
I installed onnx via "pip install onnx" under Acaconda3, but got the following error messages. Could someone take a look? Many thanks.

1.
C:\Users\wechi\AppData\Local\Temp\pip-build-h08l6ivk\onnx\onnx/onnx.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No such file or directory

2.
Command "c:\local\anaconda3-4.1.1-windows-x86_64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\wechi\\AppData\\Local\\Temp\\pip-build-h08l6ivk\\onnx\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\wechi\AppData\Local\Temp\pip-n5v8t6tg-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\wechi\AppData\Local\Temp\pip-build-h08l6ivk\onnx\

**Comment by linkerzhang** [comment]
The error is complaining the protobuf header files could not be found. In windows environment, the steps of setting up onnx are,
1. conda install -c conda-forge protobuf numpy
2. git clone --recursive https://github.com/onnx/onnx.git
3. pip install -e onnx/

**Comment by linkerzhang** [comment]
Oh, this is an error when installing from PyPi. Will fix it and update this thread.

**Comment by linkerzhang** [comment]
@bddppq could you help to update the PyPi with latest onnx changes please? Thank you very much!

**Comment by prasanthpul** [comment]
Thank you @linkerzhang for making the fix and thank you @bddppq for updating the package on pypi!

I have verified I am able to successfully install on Windows (I used python=3.5) using the instructions from the README:
```
conda install -c conda-forge protobuf numpy
pip install onnx
```

**Comment by linkerzhang** [comment]
Thank you @bddppq ! 
@wschin , you may want to try again and close the issue if no more issues :) Thanks!

**Comment by mkolod** [comment]
@linkerzhang I still have problems with a direct PyPI/pip installation (conda installation is successful, but I can't use conda in all environments). What I get is:

```$pip install onnx
Collecting onnx
  Using cached onnx-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Could not find "protoc" executable!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Dsfunc/onnx/```

This happens even if I install the protobuf package first (for both Python 2 and 3).

Any suggestions as to how to fix this? I'd assume that if the package installation had any requirements, they would be pulled first?

**Comment by mkolod** [comment]
@linkerzhang [I added a PR](https://github.com/onnx/onnx/pull/144) which clarifies this in the documentation.

**Comment by guoyuhong** [comment]
I have the same problem in Windows using Anaconda3. After checking [setup.py](https://github.com/onnx/onnx/blob/master/setup.py), I found that the enviroment virable "CONDA_PREFIX" is missing. After adding this variable, it worked.

**Comment by houseroad** [comment]
I think it is good to clarify that we should set the `ONCDA_PREFIX` or `PROTOBUF_INCDIR`/`PROTOBUF_LIB` in `README.md`.

**Comment by ayermolo** [comment]
In case anyone else is having issues. This is what worked for me:
#Otherwise I was getting error saying
#LNK1112: module machine type 'x64' conflicts with target machine type 'x86'
Open x64 Native Tools Command Prompt


Environment: ONNX_ML=1, CONDA_PREFIX="C:\ProgramData\Anaconda3"
SET PATH=%CONDA_PREFIX%;%CONDA_PREFIX%\Scripts;%PATH%

git clone https://github.com/onnx/onnx.git

#At least in my environment I was getting error below otherwise. If I didn't do this
#CondaHTTPError: HTTP 000 CONNECTION FAILED
activate.bat C:\ProgramData\Anaconda3

conda install -y -c conda-forge protobuf=3.5.2 numpy
cd onnx
python setup.py --quiet bdist_wheel --universal --dist-dir .
pip3 install -e .[mypy]

Big help was looking at output console 
https://ci.appveyor.com/project/onnx/onnx

**Comment by stiv-yakovenko** [comment]
I have this problem on linux, what should I do to fix it?
