### ISSUE TITLE
SEG FAULT WHEN IMPORTING TORCH.ONNX and CAFFE2.ONNX

### ISSUE THREAD

**Issue by ram1897** [onnx/onnx#1340]
Segmentation fault occurs when both caffe2's ONNX and pytorch's ONNX is imported

CODE SAMPLE:

from caffe2.python.onnx.backend import Caffe2Backend
import torch.onnx 

No issue occurs when only one of them are imported.

**Comment by houseroad** [comment]
How did you install them?

**Comment by ram1897** [comment]
@houseroad Caffe2 and pytorch from Anaconda

**Comment by raymondxyang** [comment]
Hi Ram this is a known issue. We are solving it in 1.3 release soon. Temp solution to use older versions of ONNX is to install onnx from source using pip with --no-binary option.

**Comment by houseroad** [comment]
https://pypi.org/project/onnx/ 1.3.0 is live. Try it :-)

**Comment by raymondxyang** [comment]
Oops I think I misunderstood the problem. It is about importing ONNX from caffe2 and pytorch @houseroad

**Comment by houseroad** [comment]
Try to install both pytorch and caffe2 from source. @ram1897
