### ISSUE TITLE
Add input/output type information when registering an operator?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#135]
For type inference, we may want to define input/output types when registering an operator. Are we all OK to add this into onnx operator registering API please? One design may be,
  // Grammar for type strings used in Input(), Output().
  // <type> ::= <data_type> | tensor(<data_type>) | sparse(<data_type>) | <type_parameter>
  // <data_type> :: = "float" | "int32" | "string" | "bool" | "uint8"
  //                | "int8" | "uint16" | "int16" | "int64" | "float16"
  //                | "double"
  // <type_parameter> is specified more with TypeConstraints. For exmaple, it could be "T",
  // which may be one of {"float", "int32", "double"}.
  OpSchema& Input(const int n, const char* name, const char* description, const char* typeStr);
  OpSchema& Output(const int n, const char* name, const char* description, const char* typeStr);
  OpSchema& TypeConstraint(const char* typeStr,
                           const std::vector<const char*>& constraints,
                           const char* description);

Thoughts?

**Comment by bddppq** [comment]
I think for type inference the `typeStr` in `Input` and `Output` is not necessary, just the mapping from input types to output types is (i.e. the TypeConstraints in your description IIUC).
For the input types to output types mapping, I prefer to directly use c++ functions, in which we can directly refer to the type system defined in our proto file, instead of creating a new one in the string syntax.

**Comment by linkerzhang** [comment]
Thank you very much for the great comments! Some personal thoughts.
1. Using c++ functions is not that descriptive and readable given our operator definitions are open standards though the c++ functions look a little bit more convenient for functionality, say type inference (easy to call).
2. There's not always a type mapping from input types to output types, am I right? (I'd go thru more in detail about all our operators)
3. I don't have very strong preferences to use string to represent type here instead of using type system defined well in our proto file. The reasons using "string" are,
a. our TypeProto now contains TensorTypeProto and SparseTensorTypeProto, which both contain a TensorShapeProto. I personally think "shape" is not the thing we want to define as input/output type here. "shape" is something be inferred with shape inference functions.
b. For scalar types, I think it looks more straightforward to have "data_type" directly instead of wrapping it into a "TensorTypeProto" in users (who define operators)' perspective.
4. I don't quite get how we handle type "T" case if using functions and type system in proto files.

For example, 
.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"float", "int32", "double"}, "Sum of two numbers").

**Comment by linkerzhang** [comment]
Looks like if using type system defined in proto file, the TypeProto will need to add a type parameter in-place, like,
oneof value {

    // The type of a tensor.

    TensorTypeProto tensor_type = 1;



    // The type of a sparse tensor.

    SparseTensorTypeProto sparse_tensor_type = 2;

    string type_parameter =3;
  }

**Comment by linkerzhang** [comment]
Any disadvantages of using "string" for type declaration please?

**Comment by ezyang** [comment]
It's an interesting little type system you have proposed here :)

For the PL nerds in the audience, this type system is `intersection types plus bounded polymorphism <https://www.cis.upenn.edu/~bcpierce/papers/thesis.pdf>`_. I don't know any mainstream languages which support this combo, but intersection types have been making there way into more modern frameworks (e.g., `intersection types in Flow <https://flow.org/en/docs/types/intersections/>`_) and so it not completely insane to suppose that we might add it to ONNX. esp., if it only lives in the operator specifications.

The big open question is whether or not these types are ever going to leak there way into the type descriptions in ONNX. Today, ONNX models are always monomorphic, because you say *exactly* what the input type is going to be. But people have been asking to export models that work on multiple types, and then you're going to have to decide what you're going to do...

**Comment by linkerzhang** [comment]
Thank you @ezyang !

For the big open question you mentioned, I feel for current model/graph designed in ONNX, they will be always monomorphic as it is.
For peoples' asking to export models that work on multiple types, that might be the scope of "Function", which also holds a DAG (bunch of nodes) and is able to handle different types, similar with an operator today.

**Comment by ezyang** [comment]
Sure, but then you're still in the same situation: are we in the business of recording the types of Function? I assume we are not going to insert n copies of a network, one for each overload.

As a PL nut, I would *love* to see us put in a proper type system, that can express all the things we want and also have reasonable metatheory backing it. But I definitely wouldn't assume that all the other stakeholders in ONNX agree with me :)

**Comment by linkerzhang** [comment]
not sure whether I understand the question clearly. Types supported by a "Function" should be declared inline, similar with TypeConstraints of an operator declaration.

**Comment by gramalingam** [comment]
Also, it would also help if you could clarify if there is any concern with the proposed type system in the simpler monomorphic setting that is currently being used (before worrying about polymorphic settings)?

**Comment by gramalingam** [comment]
@linkerzhang, my understanding is that
.Input(0, "a", "input a", "float")
signifies an input that is a (scalar) float represented as a tensor (with 1 element). Is that correct?

**Comment by gramalingam** [comment]
Also: in your example
.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"float", "int32", "double"}, "Sum of two numbers").
I guess you mean that T is a tensor of float or int32 or double. So, is the "tensor(...)" part implicit? It would be better to make it explicit as below, I think:
.Input(0, "a", "input a", "Tensor(T)")
.Input(1, "b", "input b", "Tensor(T)")
.Output(0, "c", "sum", "Tensor(T)")
.TypeConstraints("T", {"float", "int32", "double"}, "Sum of two numbers").

We can introduce short-hand notation if desired, but it will be helpful to be explicit here to understand the proposal.

**Comment by linkerzhang** [comment]
@gramalingam , Not exactly. 

When using <data_type> directly, it means the type is scalar. It means there's no dimension data. When using tensor<data_type>, it means the type is a tensor with <data_type> as its element type. so back to your example, if tensor type wants to be specified, it should be,
.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"Tensor<float>", "Tensor<int32>", "Tensor<double>"}, "Sum of two numbers").

**Comment by linkerzhang** [comment]
Sorry that I hit the "Comment" button too early. Rama's example should be as below, 
.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"tensor<float>", "tensor<int32>", "tensor<double>"}, "Sum of two numbers").

**Comment by linkerzhang** [comment]
interesting, looks like I can't input something like tensor<int32>.

.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"tensor < int32 >", "tensor < float > ", "tensor < double >"}, "Sum of two numbers").

**Comment by linkerzhang** [comment]
@gramalingam , Not exactly.
When using <data_type> directly, it means the type is scalar. It means there's no dimension data. When using tensor<data_type>, it means the type is a tensor with <data_type> as its element type. so back to your example, if tensor type wants to be specified, it should be,

.Input(0, "a", "input a", "T")
.Input(1, "b", "input b", "T")
.Output(0, "c", "sum", "T")
.TypeConstraints("T", {"tensor < int32 >", "tensor < float > ", "tensor < double >"}, "Sum of two numbers").

btw, please ignore the space among "tensor", "<", "int32", "float“, "double", ">".  because I can't input those strings continuously. :(.

**Comment by linkerzhang** [comment]
Issue resolved by PR#184
