### ISSUE TITLE
Shape Inference Fails for Tiny_Yolov2 and Resnet100 (Arcface)

### ISSUE THREAD

**Issue by Ac2zoom** [onnx/onnx#1357]
When running test_backend_test.py including tiny_yolov2 and arcface (resnet100) from the Model Zoo, shape inference fails due to 2 different assertions.

In tiny_yolov2, the assertion dim.WhichOneof('value') == 'dim_value' fails on some dim, indicating that shape_inference has not filled in all shapes.

In resent100 (arcface), the assertion output in value_infos fails, which is quite confusing.  This would seem to indicate that the output of some node is not present in the value_infos.

**Comment by prasanthpul** [comment]
Is this still an issue with latest version of everything?
