### ISSUE TITLE
Add python 2.7 pip wheel package for windows?

### ISSUE THREAD

**Issue by BowenBao** [onnx/onnx#1362]
I checked on pip https://pypi.org/project/onnx/1.2.2/#files for various onnx versions. It seems they are all missing cp27 windows wheel package (both win32 and amd64). Is there a particular reason for that?

**Comment by raymondxyang** [comment]
Hi Bowen please see the thread https://github.com/onnx/onnx/issues/936#issuecomment-388508457 here for the info.
