### ISSUE TITLE
[Operators doc] input tensor name "X" is not listed in Inputs but mentioned in remark for Softmax, Hardmax and LogSoftmax

### ISSUE THREAD

**Issue by huningxin** [onnx/onnx#1369]
Softmax operator doc: https://github.com/onnx/onnx/blob/master/docs/Operators.md#softmax mentions "X does not need to explicitly be a 2D vector", however the Inputs section (https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-76) doesn't list "X", only "input" is listed. 

Same issue for Hardmax (https://github.com/onnx/onnx/blob/master/docs/Operators.md#hardmax) and Logsoftmax (https://github.com/onnx/onnx/blob/master/docs/Operators.md#logsoftmax)

**Comment by houseroad** [comment]
Fixed
