### ISSUE TITLE
[Operators doc] questions about "storage_order" attribute of MaxPool 

### ISSUE THREAD

**Issue by huningxin** [onnx/onnx#1370]
For MaxPool (https://github.com/onnx/onnx/blob/master/docs/Operators.md#maxpool) attribute "storage_order", doc says "0 is row major, and 1 is column major. Default is 0".

I have two questions:
1. What's the reason that only MaxPool op has "storage_order" attribute but other ops don't have? It doesn't look consistent.
2. When "storage_order" is 1, does it mean input "X"'s shape is NHWC? The doc of Input "X" (https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-43) doesn't mention that clearly, it just says "Input data tensor from the previous operator; dimensions for image case are (N x C x H x W), where N is the batch size, C is the number of channels, and H and W are the height and the width of the data."

**Comment by EllieJinghan** [comment]
Does this attribute only apply for indices? In addition, what does it mean for non image case, whose dimensions are in the form of (N x C x D1 x D2 ... Dn)? The description '0 is row major, and 1 is column major' looks confusing for me. Could you give a specific example?

**Comment by houseroad** [comment]
Because `MaxPool` may output the indices (optional 2nd output), and only this output is related to the storage_order, since it will use a flatten global index.

**Comment by houseroad** [comment]
Row major vs column major, you can refer to https://en.wikipedia.org/wiki/Row-_and_column-major_order

**Comment by houseroad** [comment]
@EllieJinghan would you like to add more description (such as an example)? :-)

**Comment by EllieJinghan** [comment]
Sure. Will add it this week.
