### ISSUE TITLE
Incompatibility between old protobuf python package on Windows 

### ISSUE THREAD

**Issue by raymondxyang** [onnx/onnx#1376]
After installing 1.3 release we noticed the error of `TypeError: __new__() got an unexpected keyword argument 'serialized_options'` when import onnx. It is solved after we update the protobuf py lib using pip.

Shall we explicate the version requirement (I guess its only valid for Mac and Windows since on Linux we used an older version of protobuf lib) in setup.py?

**Comment by bddppq** [comment]
Maybe find out the least compatible version and then we do `protobuf >= xxx` in setup.py?

**Comment by raymondxyang** [comment]
But on linux we used a old version protobuf..

**Comment by bddppq** [comment]
@raymondxyang Hmm it's weird. If there is real needs for this, in setup.py you can check for OS and specify different protobuf version restrictions

**Comment by raymondxyang** [comment]
I ll test to see if it works with a later protobuf then update the setup.py accordingly

**Comment by snnn** [comment]
Protobuf runtime version(the protobuf py lib) should be same as the protoc version. If they are not the same, runtime version must be larger than protoc version.

**Comment by prasanthpul** [comment]
Is this still an issue?

**Comment by yuslepukhin** [comment]
Please, check the updated build instructions including the recommendations for protobuf version.

**Comment by yuslepukhin** [comment]
Closing. Re-open as necessary.
