### ISSUE TITLE
Dilation attribute for MaxPool is not supported

### ISSUE THREAD

**Issue by karljang** [onnx/onnx#1378]
My Pytorch model is using the dilation option for MaxPool, so I cannot export it to ONNX format.
I believe it is a good-to-have feature for audio-related models.
Could you include this feature for the next relase?

**Comment by houseroad** [comment]
Sounds good, would you like to create a PR to add this attribute to the spec?

**Comment by karljang** [comment]
Hi~, it took so long time for me to visit this issue.
I've made a PR for this.
Please review #1864 PR.
Thanks~!

**Comment by fdwr** [comment]
@karljang : Does this imply additions are needed to the inverse operation too, MaxUnpool? I'm guessing not, since MaxUnpool consumes the Indices tensor which already accounts for dilations and is agnostic to them. That is, a MaxPool dilation of size 2 would return indices that were spaced 2 element locations apart, meaning MaxUnpool doesn't need to care what the original dilations were.

**Comment by karljang** [comment]
@fdwr Sorry for the delay.
Looks interesting. Actually, I didn't pay attention to MaxUnpool. 
Anyway, I agree with you. The 'indices' input to MaxUnpool will cover this case.
Thanks for sharing your idea.

**Comment by karljang** [comment]
Closing it because my PR was merged.

**Comment by nikitaved** [comment]
I believe, it makes sense to still introduce the `dilation` parameter to avoid issues like this: https://github.com/pytorch/pytorch/issues/68420. Indices alone are not sufficient to recover the right shape.

**Comment by nikitaved** [comment]
I believe it might make sense to support `dilation` for MaxUnpool as well. This parameter affects the shape of the MaxPool's output, so having it will make the output shape more explicit and easier to handle for a user. If dilation is not specified, it is still possible to deduce the dilation value from the kernel size, stride, padding, and the desired output shape for MaxUnpool.
