### ISSUE TITLE
ValidationError while exporting onnx model from mxnet

### ISSUE THREAD

**Issue by vtkingdom** [onnx/onnx#1380]
hi:
    I am exporting a mxnet model to onnx model with a mxnet2onnx project at https://github.com/NVIDIA/mxnet_to_onnx, and  I am facing a ValidationError like this:

onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: consumed_inputs for operator BatchNormalization

==> Context: Bad node spec: input: "conv_1" input: "bn_1_gamma" input: "bn_1_beta" input: "bn_1_moving_mean" input: "bn_1_moving_var" output: "bn_1" name: "bn_1" op_type: "BatchNormalization" attribute { name: "consumed_inputs" ints: 0 ints: 0 ints: 0 ints: 1 ints: 1 type: INTS } attribute { name: "epsilon" f: 1.00001e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "momentum" f: 0.9 type: FLOAT } attribute { name: "spatial" i: 1 type: INT }

I am using onnx-1.3.0 with python2.7 on centos. 
Is consumed_inputs is deprecated ?

**Comment by vern2019** [comment]
@vtkingdom Is it solved？

**Comment by TriLoo** [comment]
same error, onnx-1.4.1, mxnet-cu100 with python 3.6. Error Info:

Unrecognized attribute: spatial for operator BatchNormalization.

**Comment by prasanthpul** [comment]
According to the note at https://github.com/NVIDIA/mxnet_to_onnx, the project is deprecated. You should instead use the exporter integrated into MXNet. If you encounter ayn issue with MXNet exporter, please file an issue in the MXnet github.

**Comment by clhne** [comment]
> same error, onnx-1.4.1, mxnet-cu100 with python 3.6. Error Info:
> 
> Unrecognized attribute: spatial for operator BatchNormalization.

same problems, have you solved yet?

**Comment by TriLoo** [comment]
Yes, @clhne 

You can fix the mxnet python file. find the python file and remove the spatial attribute from BatchNormalzie. However, I have forget which file should be fixed. Maybe: onnx file or batch normal python definition file!

If I find the file name, I will list it here.

**Comment by ashkanaev** [comment]
@TriLoo 
> Yes, @clhne
> 
> You can fix the mxnet python file. find the python file and remove the spatial attribute from BatchNormalzie. However, I have forget which file should be fixed. Maybe: onnx file or batch normal python definition file!
> 
> If I find the file name, I will list it here.

Does it mean, onnx somehow decide for model which spatial or non-spatial mode will be applied?
