### ISSUE TITLE
AveragePool count_include_pad has no default and is not "required"

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1386]
It would be nice if the doc generation could prevent this kind of doc bug, ie default value isn't just plain text.

**Comment by fumihwh** [comment]
@newling 
Actually it has default value 0. Yes, you're right. We should fix the doc anyway.

**Comment by newling** [comment]
@fumihwh 
Good to know, thank you. Actually I guessed it was 0 by looking at the tests, but for completeness it would be good to have it documented. cheers.

**Comment by houseroad** [comment]
@newling @fumihwh do you want to make a diff to automatically add default value to the doc?

**Comment by houseroad** [comment]
@fumihwh yeah, add some logic to gen_doc.py, do you want to take this task?

**Comment by fumihwh** [comment]
@houseroad Sure

**Comment by houseroad** [comment]
@fumihwh great job! well done!!!
