### ISSUE TITLE
Source of input data to Unsqueeze in Inception_v2 and DenseNet121 Opset 8 unclear

### ISSUE THREAD

**Issue by riacheruvu** [onnx/onnx#1387]
Netron shows that the Unsqueeze node in Inception_v2 takes as input a large array (as shown in the attached picture), which is not in the onnx file or fed as input to the Unsqueeze node. This is also occurring in DenseNet121. Where is the data in the Unsqueeze node coming from or is this a bug?

If this is not the right place to post this, please let me know.
![screenshot](https://user-images.githubusercontent.com/22090501/45189688-1c021a00-b1ef-11e8-8a47-8fde03fe0276.png)

**Comment by houseroad** [comment]
It's from the initializer, it's turn the 1d tensor (bias) to a 3d tensor.

**Comment by riacheruvu** [comment]
I do not understand where the 1D tensor is coming from.  Is the initializer creating random data and inputting it to the Unsqueeze node?

**Comment by houseroad** [comment]
You can consider it as weight of the model. And it's generated while training. It's stored in the initializer.

**Comment by riacheruvu** [comment]
Could you share how it is being generated? I am trying to implement the computation being done by the Unsqueeze node. I apologize for any ambiguity.

**Comment by riacheruvu** [comment]
Thank you!
