### ISSUE TITLE
Caffe2 pbtxt read

### ISSUE THREAD

**Issue by ram1897** [onnx/onnx#1392]
Hi,
Can we convert caffe2 to onnx by passing the two '.pbtxt' files instead of '.pb' files. If so what is the statement to achieve it

**Comment by houseroad** [comment]
in theory, .pbtxt can be converted to .pb, but we don't officially support that. You need to manually convert it to .pb and feed it to caffe2.

**Comment by ram1897** [comment]
Hi @houseroad how to convert it, any idea?
