### ISSUE TITLE
error at to export pack_padded_sequence model

### ISSUE THREAD

**Issue by sheljoy** [onnx/onnx#1399]
My model uses the pack_padded_sequence function to deal with the variant sequence, but there is error when to export the model into onnx file.

 <function _symbolic_pack_padded_sequence.<locals>.pack_padded_sequence_trace_wrapper at 0x00000244040A0C80>, [149 defined in (%149 : Float(1, 15, 3) = aten::embedding[padding_idx=-1, scale_grad_by_freq=0, sparse=0](%2, %148), scope: pMHCMatch/seqRNNbase[pepRNN]/Embedding[embedding]
), [15]], 2, <function _symbolic_pack_padded_sequence.<locals>._onnx_symbolic_pack_padded_sequence at 0x00000244040A0BF8>

**Comment by houseroad** [comment]
Could you provide a code snippet for reproduction? cc: @anderspapitto
