### ISSUE TITLE
Human-Readable (JSON) Output

### ISSUE THREAD

**Issue by mbehrisch** [onnx/onnx#14]
Hi, 

First of all, this is the project that I was waiting for. 
However, I have often to do with many different layouts. 
Would it be possible to add a human-readable output for the network structure? Similar to this project:
[CaffeModel2Json](https://github.com/vadimkantorov/caffemodel2json)

Thanks a lot!

**Comment by ezyang** [comment]
Hi @mbehrisch! Because ONNX is a protobuf based format, you can get a human readable format using the protobuf pretty printer. In ONNX, it's pretty simple to see this; just print a GraphProto object (e.g., that you loaded with `onnx.load`).

**Comment by mbehrisch** [comment]
Perfect! Got it running right away....
Here is my code (maybe it helps)

```
try {
    InputStream inputStream = Main.class.getResourceAsStream("/alexnet.proto");
    System.out.println("loaded");
    GraphProto model = GraphProto.parseFrom(inputStream);
    System.out.println("parsed");
    JsonFormat.Printer printer = JsonFormat.printer();
    System.out.println(printer.print(model));
} catch (IOException e) {
    e.printStackTrace();
}
```

**Comment by bddppq** [comment]
@mbehrisch Thanks for the code snippet. It's definitely helpful for other people.

**Comment by MuLx10** [comment]
@mbehrisch  Can you get python equivalent of this snippet
