### ISSUE TITLE
Control Flow for RNNs [proposal]

### ISSUE THREAD

**Issue by zdevito** [onnx/onnx#140]
Adding control flow to support RNN-like operations in ONNX
----------------------------------

Goals
* Be minimally invasive on the current ONNX
* Express the loops we see in custom RNNs
* Be straightforward to optimize (RNN scheduling, dynamic batching, etc.)

Non-Goals
* Support tree transformer style transformations (this may be something we want in the future, but it is sufficiently different from other things we want to handle that it is worth considering separately)
* Support arbitrary irreducible control-flow (i.e. goto statements).

To extend our current format, we can introduce two new special operators, **Loop** and **If** to support control flow. **Loop** will be capable of representing both `while` and `for`-style loops to minimize the number of total control flow operators. To represent the body of a loop or a condition these ops will contain as an attribute inner `Graphs` of nodes.  In these operators, nested Graph of nodes will introduce a **new scope** for input/output values. Values defined in the outer scope are still usable in the inner scopes, but any values defined inside the If/Loop will go out of scope when the block is exited.  Using scoping rather than forcing all inner graphs to require explicit inputs will cut down on the amount of arguments that are inputs to these operators. Otherwise case where we have several loop nests and a large network like a resnet in the body of the inner-most loop would require hundreds of weights to be threaded through each op. 

Since inner scopes are only valid in the body of loops both `If` and `Loop` define output values that are usable in the block they are defined. For `If`, this is equivalent to treating it like an if-expression with multiple outputs. For `Loop` this is equivalent to treating it like a scan/fold op with multiple outputs. 

New Operators
===========

If
* Inputs
    * cond -- the condition for the If
* Attributes
    * Graph then_branch -- the Graph to run if the condition is true, N outputs
    * Graph else_branch -- the Graph  to run if the condition is false, N outputs
* Outputs
     * v<sub>0</sub> ... v<sub>N</sub> -- one for each value produced by the if, `then_branch` and `else_branch` should specify N graph outputs as well.

While

This loop has multiple termination conditions:

1) Static trip count. Iteration count specified at compile time. Set by setting
   the static_trip_count attribute (optional)
2) Dynamic trip count. Iteration count specified at runtime. Set by specifying
   the input M, and setting the attribute has_trip_count = true (optional)
3) Loop conditional net. A net that has a single boolean result that specifies
   whether the loop should continue. Set by specifying the cond attribute.

   The graph body will only be run if all of the above conditions are true. In
the event that an optional condition is not specified, that condition is treated
as if it were always true.

Note that it is the responsiblity of the backend to properly schedule this
operator with respect to the data dependencies of both the condition net
and the body net.

* Inputs
     * v<sub>0</sub> ... V<sub>N-1</sub> -- the initial values of any loop-carried dependencies (values that change across loop iterations)
     * (optional) M -- a maximum trip-count for the loop specified at runtime
* Attributes
     * Bool has_trip_count -- does M exist in input list
     * (optional) Int static_trip_count -- a maximum trip-count for loop specified at compile time
     * (optional) String loop_var -- if specified, it defines a new value that will be the trip-count of the loop, starting at 0. This name can also be used in the LoopIndexTensor operator defined below.
     * Graph cond -- the Graph run before each iteration to determine whether to continue, has 1 scalar boolean output
     * Graph body -- the Graph run each iteration, has N inputs and N+K outputs (N loop-carried dependencies, plus the K "scan_outputs".  Each scan_output is created by concatenating the value of the specified output value at the end of each iteration of the loop. It is an error if the dimensions of these values change across iterations. (This is a way to avoid adding lists of Tensors to ONNX. In the future: it is not an error, and these "scan_outputs" have type `List[Tensor]`).
*  Outputs (N+K total):
      * o<sub>0</sub>...o<sub>N-1</sub>: the final values of loop-carried dependencies
      * s<sub>0</sub>...s<sub>K-1</sub>: the values of the "scan_outputs"

Inside a `Loop`, we can allow special operations that query the loop index:

LoopIndexTensor
* Inputs: T -- tensor to be indexed (has N dims)
  * Attributes:
  * String loop_var -- loop_var to use in the indexing
* Outputs: O -- tensor of N - 1 dims that is a sub tensor of T

This is a special operator only valid inside the loop that defines `loop_var` that supports the common case behavior of accessing the correct element of the input sequence in an RNN. While the same tensor can be computed using a normal Index plus the loop_var,  this operator can be optimized more aggressively by the Loop execution engine to discover more opportunities for parallelism.

Edits: renamed M and K confusion

**Comment by gdiamos** [comment]
I would highly recommend just supporting arbitrary (including irreducible control flow).  Optimizations over these forms are standard in the compiler community.  Restrictions just end up making optimizations nonstandard and introduce additional complexity to handle exceptions.

**Comment by salexspb** [comment]
How various sequence length within a minibatch is going to be handled? Currently in Caffe2 timestep blob is passed to some of the ops that have a custom logic inside. Like LSTMUnit op has various modes. In one mode it just fills results with 0s after the sequence boarder. In another and pull them towards the end (maximum sequence lengths within a minibatch).

These are two different modeling usecases (not optimizations). In one case it can be a simple ecoder producing a single timestep state. In another case with attention we will use all states (scan output kind of output). 

In caffe2 this logic made it harder to create new types of cells. Because you had to have a special 0 filling op / pulling towards the end op inside your cell. So you can't just use arbirary ops within your cell, they have to understand seq lengths. 


So the question is - how we make sure ONNX implementation is going to be easy to map on such optimized code dealing with various seq. boarder usecases?

**Comment by dzhulgakov** [comment]
1) One thing to note is that this design describes things closer to the backend - i.e. how execution needs to be handled. Another representation of RNN would be to describe what happens to a single sequence and rely on auto-batching logic to handle sequences padding, masking, etc (what @salexspb is talking about)

The above "single sequence" representation is also interesting to explore and maybe we should add it to the spec. But imho, we should add it only in addition to plain-while-loop representation proposed here. It might be interesting to abstract in ONNX the path of converting between the two representations at some point.

2) For optimizations of bidirectional RNNs it might make sense to add "reverse" to LoopIndexTensor that works only if fixed trip count is provided. It'd avoid manually flipping the tensor or doing the math on loop_var

3) To @gdiamos concern, one of the value of ONNX in my opinion is being able to represent DL compute patterns as close to reality as possible to enable specialized optimizations in backends. For example, some backends might have a support for RNN as a fixed-size for loop. If we represent RNN as a generic while loop with iteration conditions expressed as ops it makes it harder to pattern-match RNN-like fixed for loop. If we go with more restrictive implementation, it's always easier to lower it to a more elemental one.

It's similar philosophy to Gemm op. Yes, we can represent it as matrix multiplies + transposes + addition. But frequent usage of particular pattern in practice means that it's justifiable to keep more higher-level implementation to make optimizations easier.

**Comment by tqchen** [comment]
Structured for loop is easier than irreducible control-flow even from compilation point of view, since it makes it easier to do loop transformations in such form as opposed to goto

**Comment by gramalingam** [comment]
Yes, structured loops are easier in multiple ways than irreducible control-flow. In its current form, ONNX is more a dataflow graph (without any explicit control-flow). Generalizing its semantics to support arbitrary irreducible cycles is more complex (than for structured loops).

**Comment by MrGeva** [comment]
What is the ETA of loops in ONNX?

**Comment by RanACohen** [comment]
We believe that a slightly higher representation level which is compiler friendly, but still generic enough is an operation such as TensorIterator.
 
Such operation that accepts an iteration axis, start, size and stride (for  input and output) + a body would make it easy to compile any RNN type and also efficient enough to execute..

Thoughts?

**Comment by jamesr66a** [comment]
+1 for the original proposal, this will allow implementation of (for example) beam search in a way that supports the state-carrying behavior as well as preserving all outputs from each time-step.

Can I suggest we move forward with this lower level proposal and split out the higher-level interface into another issue?

**Comment by gramalingam** [comment]
I suggest not tying the LoopIndexTensor operator so tightly with a loop. Indexing a tensor is a natural operation, independent of loops. Let's call this just "IndexTensor" and not restrict it to inside loops.
This requires rationalizing the use of "loop_var" attribute as well. I think "loop_var" is a variable representing a dynamic runtime value, and so it is best represented as an input instead of as an attribute.

**Comment by gramalingam** [comment]
What is the semantics of trip_count in a loop? Is it an additional condition along with loop-condition or an alternative for the loop-condition?

**Comment by prasanthpul** [comment]
Control flow operators were added in 1.3 (https://github.com/onnx/onnx/releases/tag/v1.3.0). Please open a new issue if additions or changes are needed
