### ISSUE TITLE
Please clarify which opset_import to use when ir_version is 1

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#1403]
Hi,

It seems like onnx checker allows opset_imports to be empty assumes opset_imports=1 when ir_version=1 as evidenced by the following code snippet:
```
  } else {
    if (opset_imports.empty())
      opset_imports[ONNX_DOMAIN] = 1;
    else
      fail_check(
          "model with IR version < 3 cannot have opset_import specified");
  }
```

However, onnx-ml.proto states opset_imports cannot be empty:
```

  // The OperatorSets this model relies on.
  // All ModelProtos MUST have at least one entry that
  // specifies which version of the ONNX OperatorSet is
  // being imported.
  //
  // All nodes in the ModelProto's graph will bind against the operator
  // with the same-domain/same-op_type operator with the HIGHEST version
  // in the referenced operator sets.
  repeated OperatorSetIdProto opset_import = 8;
```

So which one should be followed? Are we allowing opset_import to be empty when ir_version=1 and assume opset_import to be 1? This behavior is not documented anywhere, please help clarify.

**Comment by tjingrant** [comment]
@prasanthpul thanks, so that means if we see IR version 1, we should assume opset_imports to be [1] right? If so, I suppose it's better to document this behavior somewhere? I can send in a pull request if you agree.

Also the documentation is a bit inaccurate to claim `All ModelProtos MUST have opset_imports` because the documentation in the onnx-ml should be accurate for all ir_version, not just the latest one.  The rationale is that we do not use a different protobuf specification for different ir_version, therefore the documentation should not be specific to any particular ir_version.

**Comment by prasanthpul** [comment]
@tjingrant IR version 1 models used a different proto file, one that did not have opset field. I'm not aware of any IR version=1 models in the wild.. IR version has been 3 since ONNX 1.0

@NiklasGustafsson can you see how best to address this in IR.md and the proto files?

**Comment by tjingrant** [comment]
I see, the main reason I'm asking is because the tutorial fb wrote up about onnx-tf has a model with ir_version 1. c.f. https://github.com/onnx/tutorials/issues/52

The output of the following script:
```
import onnx
from onnx_tf.backend import prepare

model = onnx.load('assets/super_resolution.onnx')
print model.ir_version
```

is 1. Maybe updating the model is the right solution, but unfortunately I do not have the original model to be re-exported to onnx.

**Comment by NiklasGustafsson** [comment]
Is there even a runtime implementation that supports IR version 1?

**Comment by tjingrant** [comment]
@NiklasGustafsson regardless of the answer to your question, i believe we should address this undefined behavior. The checker assumes opset_imports=1 when ir_version is 1, this behavior is not documented, could we at least make this assumption explicit in the documentation?

Otherwise checker will keep thinking opset_imports=1 when ir_version is 1 and backends will have no rules in determining which opset to import. This is a rather obvious problem, albeit one with little practical implication.

Ultimately, I think I'll try to get the tutorial updated; but nonetheless, it shouldn't take much efforts to patch up the documentation to fix this small loophole.

**Comment by houseroad** [comment]
I checked the commits between ir 1, ir 2 and ir 3, I didn't find big changes in the spec (probably adding `Pad` op is the biggest one), I think it's ok to assume opset 1 when ir_version is 1.

@tjingrant Yeah, please get example updated, in real world, probably no backend supports IR version 1 any more...

**Comment by tjingrant** [comment]
@houseroad I cannot update the onnx model as I don't have access to the original model exported to onnx. Ping @jamesr66a from fb who authored the original tutorial, I believe he can update the model relatively easily without changing anything else.
