### ISSUE TITLE
How to use latest ONNX (1.3) in Pytorch (torch.onnx.export())?

### ISSUE THREAD

**Issue by thlinh** [onnx/onnx#1404]
Hi,
I'm new to ONNX and PyTorch. I had some models written in PyTorch and they works OK. When trying to convert to ONNX using torch.onnx.export() there is an error that aten::expand is not supported. Last week I saw that ONNX 1.3 starts to support expand. I have downloaded and installed ONNX 1.3 but I think torch.onnx.export() is still working in the old way. I have 2 questions:
- How to tell PyTorch to use the latest ONNX, instead of the old one (I tried uninstall / reinstall but didn't help)
- Is there a step-by-step help to add new operator ? (since my model still has some other operators which seems to be not supported yet, for example sort(),...)
Many thanks in advance.

**Comment by houseroad** [comment]
`onnx` and `pytorch` are separate packages, to use onnx 1.3, you just need to install the right version of `onnx`. Your problem is in pytorch, there is some issue related to `aten::expand` in pytorch tracer, so it cannot be exported correctly. PyTorch team is working on that.
