### ISSUE TITLE
Operator: Hardtanh

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#141]
Requested at https://github.com/pytorch/pytorch/issues/3253

PyTorch docs: http://pytorch.org/docs/master/nn.html#torch.nn.Hardtanh

Unfortunately, this operator does not seem to be widely supported in other frameworks. We'll have to see if there is a good desugaring.

**Comment by dzhulgakov** [comment]
Can we use ATen operator for this kind of less-popular ops? See https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/aten/docs/pytorch_to_caffe2.md for Zach's intructions

**Comment by postrational** [comment]
Would that make all of the ONNX ecosystem frameworks dependent on the ATen library?

**Comment by dzhulgakov** [comment]
I'm not saying that we should pull ATen into ONNX spec, we explicitly shouldn't. Experimental ops are more of a temporary backdoor for framework pairs.

For HardTanh specifically, I'm not sure it's popular enough to be in the core ONNX. Another way is to break it down into elemental ops, but that would be lower priority now I'd say.

**Comment by inflation** [comment]
The `HardTanh` is pretty annoying since `ReLU6` uses it.

**Comment by ghop02** [comment]
I'm pretty new to ONNX and am wondering where the community falls on the priority for the support for various operators, similar to this sort of request.

> For HardTanh specifically, I'm not sure it's popular enough to be in the core ONNX

Is there some sort of cutoff for popular enough? It just seems like the sort of thing that supporting as many operator types as possible would make ONNX so much more flexible and really streamline the path from research to production.

**Comment by Ac2zoom** [comment]
https://github.com/onnx/onnx/pull/1136

**Comment by houseroad** [comment]
Turn out, HardTanh can be expressed by [Clip](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip).
