### ISSUE TITLE
ResizeNearestNeighbor supports only const tensor size

### ISSUE THREAD

**Issue by BenjaminCoquelle** [onnx/onnx#1419]
When converting a TF model to ONNX, the upscale operation is translated into ResizeNearestNeighbor.
In TF this operation can operate on any sizes, but it is not the case for ONNX

**Comment by houseroad** [comment]
@BenjaminCoquelle could you be more concrete about the problem? What's the problem with `Upsample` operator?

**Comment by BenjaminCoquelle** [comment]
The problem is upscale doesn't allow random sizes and expect a const tensor size

**Comment by linkerzhang** [comment]
are you asking to have scales to be Upsample's input (dynamic) instead of attribute (static)?

**Comment by jcwchen** [comment]
I think it should be resolved. Please reopen it if you still have questions. Thanks!
