### ISSUE TITLE
Operator: UpsamplingBilinear2d

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#142]
Requested at: https://github.com/pytorch/pytorch/issues/3253

PyTorch docs: http://pytorch.org/docs/master/nn.html#torch.nn.UpsamplingBilinear2d

Does not appear to be supported in Caffe2

**Comment by dzhulgakov** [comment]
Similarly, for C2 export only we can use ATen op: https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/aten/docs/pytorch_to_caffe2.md

**Comment by ebarsoum** [comment]
Should be covered by: https://github.com/onnx/onnx/pull/290

**Comment by houseroad** [comment]
Already covered.
