### ISSUE TITLE
Travis build times out...

### ISSUE THREAD

**Issue by ArmenAg** [onnx/onnx#1424]
The travis build times out when testing as seen here: 

- https://api.travis-ci.org/v3/job/430273307/log.txt
- https://api.travis-ci.org/v3/job/430312636/log.txt

`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

This is happening because the tests sometimes take too long. The recommended solutions are here: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

Should we add `travis_wait` to the script.sh call in .travis.yml?

**Comment by houseroad** [comment]
Yeah, not very stable, mainly because we download some large models from s3, probably we should split the tests between different variances.

**Comment by ArmenAg** [comment]
I'm not sure how we would split the tests. Could we increase the wait time? Or maybe we can add more verbosity so that the timeout doesn't happen.

**Comment by jcwchen** [comment]
TravisCI has been deprecated for a while. Close it now.
