### ISSUE TITLE
How can we get values of weights from any layer of the model

### ISSUE THREAD

**Issue by csbenk** [onnx/onnx#1425]
I want to get the weight & bias values of any layer of choice, how can I access the same?
I could get the Kernel Shape, stride, pad, inputs, output for a particular layer. But how do I get the parameter values of a layer from `model.onnx` file. I am new to Protobuf.

**Comment by csbenk** [comment]
Thanks a lot @houseroad. Is there a function to convert the raw data to floating point matrix? Or can I convert to float from raw data (binary) and rearrange in the weight matrix dimensions.

**Comment by csbenk** [comment]
I got it, I used the `numpy_helper`
`numpy_helper.to_array(weights[0].raw_data)`

**Comment by gramalingam** [comment]
@grjulian : you need to look at the nodes in the graph to figure out which initializer is being used for what purpose.

**Comment by holoLens8** [comment]
Hello,
@csbenk how do you get the stride and the pad values of a particular layer ?

**Comment by holoLens8** [comment]
> For example, in python:
> 
> ```
> model = onnx.load('model.onnx')
> weights = model.graph.initializer
> ```

How to get 

> For example, in python:
> 
> ```
> model = onnx.load('model.onnx')
> weights = model.graph.initializer
> ```



> I got it, I used the `numpy_helper`
> `numpy_helper.to_array(weights[0])`

How to parse the obtained result of numpy_helper.to_array(node[0])?

**Comment by TMVector** [comment]
Hi @holoLens8, here is an example (I'm using [mobilenetv2](https://github.com/onnx/models/blob/master/vision/classification/mobilenet/model/mobilenetv2-7.onnx)). You can load the model in [Netron](https://lutzroeder.github.io/netron/) to explore visually and find the nodes you want.

![image](https://user-images.githubusercontent.com/4268638/83302498-5eedf780-a1f3-11ea-889c-6c83567b4116.png)

You will be able to see the names of the node inputs. Here I have selected the first `Conv` node, and the weight input **W** is named `mobilenetv20_features_conv0_weight`. This code snippet will give you the constant (weight matrix, bias, etc.) as a numpy array:

```python
import onnx, onnx.numpy_helper
model = onnx.load("path/to/model")
[tensor] = [t for t in model.initializer if t.name == "mobilenetv20_features_conv0_weight"]
w = numpy_helper.to_array(tensor)
```

You can understand how to interpret the numpy array by looking at the operator documentation -- for example the [`Conv`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv) operator says that the weight tensor is of shape:
> (M x C/group x kH x kW), where C is the number of channels, and kH and kW are the height and width of the kernel, and M is the number of feature maps.

**Comment by holoLens8** [comment]
@TMVector thanks a lot :)

**Comment by atemysemicolon** [comment]
Is there a way to reverse it? i.e. From numpy to binary?

**Comment by TMVector** [comment]
@atemysemicolon there is the corresponding [`onnx.numpy_helper.from_array`](https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py#L25) function to convert a numpy ndarray into an ONNX `TensorProto`.

**Comment by harishch4** [comment]
while using [onnx.numpy_helper.from_array](https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py#L25),  i was not able to print the complete data. 

Tensor[1000, 1280] =  

[[-3.1177139e-02  8.9587316e-02 -7.4811943e-02 ... -3.3274688e-02
  -6.3843600e-02 -4.2156242e-02]
 [-2.2172749e-02  5.4803323e-02  1.2471121e-02 ... -4.2400297e-02
  -2.5824906e-02  1.2330567e-02]
 [-6.9284970e-03  2.1576457e-02 -3.0860623e-02 ... -7.2696269e-02
  -6.1195876e-02 -5.7696817e-03]
 ...
 [-4.4350196e-02  2.8589193e-02 -2.1555275e-02 ... -2.9260164e-02
  -4.3548528e-02  6.3868217e-02]
 [-1.9760828e-02  1.3970371e-01  4.8443124e-02 ... -9.5596071e-03
   1.5065874e-03  1.2227104e-04]
 [ 5.1319666e-02  3.0963048e-02  6.9039240e-02 ...  5.7983715e-03
  -5.5185873e-03 -2.5348091e-02]]

Data is getting truncated by "...",  Is there a way to print the complete data?

**Comment by harishch4** [comment]
> while using [onnx.numpy_helper.from_array](https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py#L25), i was not able to print the complete data.
> 
> Tensor[1000, 1280] =
> 
> [[-3.1177139e-02 8.9587316e-02 -7.4811943e-02 ... -3.3274688e-02
> -6.3843600e-02 -4.2156242e-02]
> [-2.2172749e-02 5.4803323e-02 1.2471121e-02 ... -4.2400297e-02
> -2.5824906e-02 1.2330567e-02]
> [-6.9284970e-03 2.1576457e-02 -3.0860623e-02 ... -7.2696269e-02
> -6.1195876e-02 -5.7696817e-03]
> ...
> [-4.4350196e-02 2.8589193e-02 -2.1555275e-02 ... -2.9260164e-02
> -4.3548528e-02 6.3868217e-02]
> [-1.9760828e-02 1.3970371e-01 4.8443124e-02 ... -9.5596071e-03
> 1.5065874e-03 1.2227104e-04]
> [ 5.1319666e-02 3.0963048e-02 6.9039240e-02 ... 5.7983715e-03
> -5.5185873e-03 -2.5348091e-02]]
> 
> Data is getting truncated by "...", Is there a way to print the complete data?

I was able to achieve it by setting threshold as below:
`numpy.set_printoptions(threshold=sys.maxsize)`

**Comment by abhishek27m1992github** [comment]
I'm trying to get the weights & biases info using c++ code as shown below but not able to get the weights value but able to get the type and shape 
// Print Weights
    auto graph = m_Model.graph();
    if(graph.initializer_size() > 0)
    {
      std::cout << "Weight & Biases Info:" << std::endl;
      /* for(auto& tensorProto : graph.initializer())
      {
        handleTensorproto(tensorProto);
        std::cout << std::endl;
	    } */
     
      for(auto& initializer : graph.initializer())
      {
        //auto initializer = graph.initializer(i);//.at(i);
        std::string name = initializer.name();
        //if(nodename == name)
        {
          std::cout << name << ": ";   
          //std::cout << initializer.data_type() <<"=" ; 
          std::cout << initializer.DataType_Name(initializer.data_type()) << " ";
          if(initializer.dims_size() > 0)
          {
            std::cout << "[ ";
            for(auto& dim: initializer.dims())
            {
              std::cout << dim << " ";
            }
            std::cout << "]";
          }

          //std::cout << initializer.raw_data();
          //std::cout << initializer.GetTypeName();
          //handleTensorproto(initializer);
          auto type = initializer.data_type();
          switch(type)
          {
            //std::cout << "Abhishek" << std::endl;
            case onnx::TensorProto_DataType::TensorProto_DataType_FLOAT:
            {
              //std::cout << initializer.float_data_size();
              //if(initializer.float_data_size() > 0)
              {
                //std::cout << "Float value " << std::endl;
                for(const float& value : initializer.float_data())
                {  
                  std::cout << value << ",";
                }
              } 
              break;
            }

            case onnx::TensorProto_DataType::TensorProto_DataType_INT64:
            {
              //std::cout << initializer.float_data_size();
              //if(initializer.float_data_size() > 0)
              {
                //std::cout << "Float value " << std::endl;
                for(const int64_t& value : initializer.int64_data())
                {  
                  std::cout << value << ",";
                }
              } 
              break;
            }
            default:
            {
              std::cout <<"no TensorProto_DataType matched";
            }

          }
