### ISSUE TITLE
Trying to understand OptimizedRNN

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#143]
Hi, I'm wonder what is the weight tensor defined in OptimizedRNN operator:

```
weights
All parameters of the stack packed together in the opaque tensor. The size must be compatible with input attributes passed to the op.
The layout format is the one used by CuDNN and very similar to TensorRT:

The weight structure holds weights and biases for each layer of the network. Each parameter matrix is linearly appended after the previous parameter matrix without padding.

The order of matrixes {K, L, D, R, N, C} is defined as:

K - type of the matrix: weight (first) or bias second
L - The number of layers in the RNN - num_layers
D - The direction of the layer: normal (first) or reverse (second). (in case of directions=2)
R - The type of the connection: input-hidden (first) or hidden-hidden (second)
N - The number of gates matrices in the RNN, dependent on the cell_type: -- For relu or tanh there is one gate -- For gru there are 3 gates ordered as reset, update, hidden -- For lstm there are 4 gates ordered as input, forget, cell, output
C - The size of each matrix, which varies. -- If the linear layer on the input is skipped (skip_input_transform=1) and then for the first layer (L=1) the weight matrix (K=weight) on the input connection (R=input-hidden) is skipped, i.e. has 0 parameters in the list -- For the first layer (L=1) weight matrix (K=weight) on input connection (R=input-hidden), dimensions are {hidden_size, input_size} -- For other layers (L>1) weight matrix (K=weight) on input connection (R=input-hidden), dimensions are {hidden_size, directions * hidden_size} -- For weight matrix (K=weight) on recurrent connection (R=hidden-hidden), dimensions are {hidden_size, hidden_size} -- For all biases (K=bias), dimensions are {hidden_size}
```

When using `{K, L, D, R, N, C}` to denote the order of matrixes, are you describing the order of dimensions within the weight tensor? Is the weight tensor a 6D tensor with each dimension explained as above?

**Comment by dzhulgakov** [comment]
It's just the order of matrixes appended together in one buffer (to avoid having K*L*D*R*N*C separate inputs). Matrices have different sizes and just get appended continuously. So it's not precisely 6-d tensor because the inner blocks have different dims.

**Comment by tjingrant** [comment]
When you say `_order of matrixes_`, I'd expect whatever comes into the ensuing curly braces to be matrices and I only need to substitute these letters, which are just variables representing matrices with parameter values like weight matrix and bias vector. However, the way you used these letters seems to suggest that K, L, D, R, N, C are all scalar values. How can a list of scalars be used to denote the order of matrices? Are we defining a lexicographic order of matrices here based on their corresponding tuple value (K, L, D, R, N, C)?

Or more importantly, are K, L, D, R, N, C scalar values or variables representing matrices?

**Comment by dzhulgakov** [comment]
yes, it's interpreted as an ordered tuple (K,L,D,R,N,C). I'll clarify the comment. I'll also add the helper code for stacking / unstacking this layout.

**Comment by tjingrant** [comment]
Please do. Also I do not see a compelling case for using set notation here which implies orderlessness. This is the reason why I took K, L, D, R, N, C as variables representing matrices. Because, unless I'm mistaken, it only makes sense to specify order with content in a curly braces when you are describing arrays.

**Comment by yuanbyu** [comment]
I am also a bit confused by the packing. Consider a single layer unidirectional LSTM. Here are a few ways of packing I can think of. It seems that you are using 3. Is it correct? What do you think about 4?

1. 
`WiWfWoWcRiRfRoRcWbiWbfWboWbcRbiRbfRboRbc`

2. 
`WiWfWoWcWbiWbfWboWbcRiRfRoRcRbiRbfRboRbc`

3.
`WiWbiWfWbfWoWboWcWbcRiRbiRfRbfRoRboRcRbc`

4. 
`WiWbiRiRbi
WfWbfRfRbf
WoWboRoRbo
WcWbcRcRbc`

**Comment by yuanbyu** [comment]
Sorry option 4 is:

```
WiWbiRiRbi
WfWbfRfRbf
WoWboRoRbo
WcWbcRcRbc
```

**Comment by prasanthpul** [comment]
OptimizedRNN was removed as part of #149.
Is this issue still valid?

**Comment by tjingrant** [comment]
I believe not; and the new presentation seems much better.
