### ISSUE TITLE
Export resnet18 from pytorch

### ISSUE THREAD

**Issue by mrgloom** [onnx/onnx#1440]
Following this onxx tutor : https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb

Model successfully exported:

```
from torch.autograd import Variable
import torch.onnx
import torchvision

# Export model to onnx format
dummy_input = Variable(torch.randn(1, 3, 224, 224))
model = torchvision.models.resnet18(pretrained=True)
torch.onnx.export(model, dummy_input, "resnet18.onnx")
```

But  check not passed:

```
import onnx
model = onnx.load("resnet18.onnx")
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))
```

```
Traceback (most recent call last):
  File "resnet18_onnx.py", line 13, in <module>
    onnx.checker.check_model(model)
  File "/Users/myuser/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input index 3 must be set to consumed for operator BatchNormalization

==> Context: Bad node spec: input: "123" input: "2" input: "3" input: "4" input: "5" output: "124" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "momentum" f: 1 type: FLOAT } doc_string: "/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py(1254): batch_norm\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py(66): forward\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/resnet.py(140): forward\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(465): _slow_forward\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(475): __call__\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(109): forward\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py(477): __call__\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py(77): get_trace_graph\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py(144): _trace_and_get_graph_from_model\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py(177): _model_to_graph\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py(226): _export\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py(94): export\n/Users/myuser/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py(26): export\nresnet18_onnx.py(7): <module>\n"
```

What is wrong?

**Comment by mrgloom** [comment]
Looks like `onnx` should be installed from master : https://github.com/pytorch/pytorch/issues/6300

git clone --recursive https://github.com/onnx/onnx.git
pip install ./onnx

**Comment by mrgloom** [comment]
I managed to export model and import it in Tensorflow, but max difference is quite large `diff: 7.5956607`

```
from torch.autograd import Variable
import torch.onnx
import torchvision
import onnx
from onnx_tf.backend import prepare
import numpy as np

print('torch.__version__', torch.__version__)
print('torchvision.__version__', torchvision.__version__)
print('onnx.__version__', onnx.__version__)

# https://github.com/onnx/tutorials/blob/master/tutorials/PytorchOnnxExport.ipynb

# Export model to onnx format
dummy_input = Variable(torch.randn(1, 3, 224, 224))
model = torchvision.models.resnet18(pretrained=True)
torch.onnx.export(model, dummy_input, "resnet18.onnx")
o1 = model.forward(dummy_input)
o1 = o1.detach().numpy()

# Check model
model = onnx.load("resnet18.onnx")
onnx.checker.check_model(model)
print(onnx.helper.printable_graph(model.graph))

# Import model in tensorflow
model = onnx.load("resnet18.onnx")
tf_rep = prepare(model)
o2 = tf_rep.run(dummy_input)._0

print('diff:', np.max(np.abs(o1-o2)))
```

**Comment by houseroad** [comment]
@fumihwh would like to take a look at this interesting case?

**Comment by ehsab** [comment]
Hi,

Did you solve this problem? I am trying to convert resnet18 (pretrained from torchvision) to TF using onnx. I could convert it but it doesn't predict well. It most of the time predict one class no Mather what you feed as input. Any idea?

**Comment by mrgloom** [comment]
Looks like it was an issue that onnx was incompatible with pytorch 0.4.1, I downgraded to 0.4.0 and seems it works.

https://github.com/nerox8664/pytorch2keras/issues/34

**Comment by ehsab** [comment]
Thanks for the prompt reply. I use different versions but it didn't solve the problem. In the link you shared, they suggested to use change_ordering=True to adjust the orders. Did you use the same approach? did you use onnx? I couldn't find the same option in onnx to force it to change the order.

Thanks,

**Comment by ehsab** [comment]
I did the same as [here](https://github.com/nerox8664/pytorch2keras/issues/9#issuecomment-423779462).
I loaded the torchvision resnet18 and converted it. It works now but the prediction is wrong.

**Comment by inuinana** [comment]
Was this problem solved? I have the same issue now.

**Comment by prasanthpul** [comment]
Can you confirm you are using latest PyTorch to export the model?
Can you confirm whether you are using ONNX Runtime to inference the model?

**Comment by Shuwrood-SSW** [comment]
> Can you confirm you are using latest PyTorch to export the model?
> Can you confirm whether you are using ONNX Runtime to inference the model?

l try to export the Resnet pre-trained model using different versions of Py?
but the  predicting results in ONNX Runtime(using the .onnx model converted )  are different in PY

**Comment by Shuwrood-SSW** [comment]
> I did the same as [here](https://github.com/nerox8664/pytorch2keras/issues/9#issuecomment-423779462).
> I loaded the torchvision resnet18 and converted it. It works now but the prediction is wrong.

did you solve the problem?

**Comment by Abhishekvats1997** [comment]
> I did the same as [here](https://github.com/nerox8664/pytorch2keras/issues/9#issuecomment-423779462).
> I loaded the torchvision resnet18 and converted it. It works now but the prediction is wrong.

Did you normalize the image before passing to the onnx model? I forgot to do that and ended up wasting a couple of hourswhy the prediction was always same.
