### ISSUE TITLE
How to stack LSTM operators?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#1442]
I want to stack two sequence-output LSTM operators but I don't see how.

According to the [LSTM operator spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM), the LSTM input tensor "X" has shape [S N D], where S=sequence_length, N=batch_size, and D=input_size. Its output sequence tensor "Y" has shape [S d N H], where d=num_directions, and H=num_hidden. If I want to stack two LSTMs, do I need to put something between them to make the output shape of the first LSTM match the input shape of the second LSTM?  That is, it appears that I would need to transform [S d N H] into [S N d*H]. Am I supposed to do that, and if so, how?

Thanks

**Comment by anderspapitto** [comment]
yes, I believe so. You can see one related example here https://github.com/pytorch/pytorch/blob/d9c27f4d8d2e71a5dd3b3c3f82790d14a296124f/torch/onnx/symbolic.py#L1166 - this is the code which does automatic conversion of pytorch (multilevel, bidirectional) LSTM into onnx
