### ISSUE TITLE
Shall we bump operator set version for both backward and forward compatibility breaking changes? 

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#1443]
It's stated that operator set version is bumped if and only if there's a backward compatibility breaking change in ONNX. However, there're two facts/issues,
1. Previously changes didn't fully follow this rule. For example, adding new operators is always against new operator set version.
2. For non backward breaking but forward breaking changes, say, adding type constraints for an op, without bumping operator set version,  it's hard for an onnx runtime to elegantly fail to run a model referring the updated op.

Thoughts? @bddppq @houseroad  @yuanbyu @ebarsoum @gramalingam @lupesko

**Comment by gramalingam** [comment]
Yes, I agree … it makes sense to bump opset version in both cases

**Comment by houseroad** [comment]
I think we already did both in practice. For example, adding new op, even adding new attributes.

**Comment by houseroad** [comment]
@linkerzhang yeah, that sounds good on our side. :-)

**Comment by linkerzhang** [comment]
@fdwr

**Comment by fdwr** [comment]
@linkerzhang Should the issue be closed now, after 1475?

**Comment by linkerzhang** [comment]
Closing this issue as it is resolved by #1415
