### ISSUE TITLE
Initializers and graph inputs

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#1449]
The ONNX spec requires every initializer X to also appear in the list of graph inputs. I suggest relaxing this constraint. It appears to have no advantage and several disadvantages (due to changes that have happened since the original spec). With the transformations to lift "Constants" into "Initializers", this restriction looks a bit odd. Furthermore, the original spec allowed callers to override the values specified in the initializers, which also seems to have been removed. Any thoughts?

**Comment by houseroad** [comment]
One advantage is that, we can use input to replace the value in the initializer. If we don't want this feature, we can relax the restriction.

**Comment by snnn** [comment]
If we changed that, it means we need to update IR version. Then the new model cannot be loaded in an old runtime. This is not good.

**Comment by houseroad** [comment]
We don't need to change proto, but probably bumping up the IR version. And backends have to support new version, I think it won't bring us a lot of benefits.

**Comment by gramalingam** [comment]
@houseroad : yes, compatibility is a good reason to leave things as they are for now. But I feel that there is still ambiguity about whether inputs are allowed to replace the value in the initializer (though that was the original intent; it seems to have been changed along the way.) Optimizations like lifting a "Constant" to be an "Initializer" do complicate things. Okay ... let me leave this open just to see if anybody has any other opinion before closing it.

**Comment by skottmckay** [comment]
In the scenario of lifting a Constant to an initializer, isn't it a confusing and unexpected side effect to have to add a graph input? Doesn't the usage of a Constant node declare an intention to not allow it to be overridden by an input? 

Is an alternative to have a separate list of non-graph input initializers that are used in scenarios like Constant lifting, to clarify which initializers match graph inputs and are overridable, and which ones don't?

**Comment by gramalingam** [comment]
Yes, I agree that it is confusing.

The alternative you propose is one possibility. It has the advantage of supporting both kinds of initializers. (However, I am not sure if even the current standard permits overriding of initializers by inputs. The changes in https://github.com/onnx/onnx/pull/690 seemed to have changed the intention/goals of allowing such overriding.)

It would be nice to eliminate the confusion one way or another.
