### ISSUE TITLE
Should ONNX state that IR backward compatibility is always kept please?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#1450]
In practice, IR backward compatibility is always kept. We don't remove things but adding "optional" stuff. This is good. 

The question is, shall we move one more step to note it down in ONNX spec to say IR backward compatibility MUST always be kept please?

Thoughts?

@bddppq @houseroad @dzhulgakov @yuanbyu @gramalingam @prasanthpul @ebarsoum @lupesko

**Comment by yuanbyu** [comment]
It would be great if we could keep ONNX IR format backward compat. Some of the extension points we introduced in the IR format were intended to avoid breaking changes.
