### ISSUE TITLE
[Discussion] Numpy compatibility when possible

### ISSUE THREAD

**Issue by tqchen** [onnx/onnx#146]
This is related to #83 But I want to raise this as a general issue. Some of the current onnx operators are not compatible with numpy.

- min/max are elementwise instead of reduction. In numpy being maximum and minimum
- The broadcast semantics are not ready
- split's output attribute naming.
 
While some of these can be viewed as minor issues. But in general, we can find that the frameworks are leaning toward numpy API. So when we design our in-memory IR in NNVM, we are starting to adopt the principle that: ```use numpy API when such operator exist```

I understand there are concerns about support level and granularity. While these are valid concerns, many of them can actually be addressed by other operators that are not in numpy(e.g. gemm). I am opening this issue to see how other's opinion toward this. I find the general IR requires three major requirements:
- coverage
- conciseness
- conventional (reflects conventional usage of API)

While it is easy to design for the first two points. Adopting numpy API when possible hit the third one more easily.

**Comment by nouiz** [comment]
I totally agree that keeping the API NumPy compatible is very important!

**Comment by houseroad** [comment]
@tqchen yes, I think align the specification will several benefits. We will discuss this in next ONNX workshop.

**Comment by ebarsoum** [comment]
That is recommended: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md
