### ISSUE TITLE
Negative indexing in slice

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#147]
Currently, we are doing Caffe2 behavior, which says negative indexes are inclusive. This allows you to pass 0:-1 to indicate that the entire range should be taken.

HOWEVER, this is inconsistent with Numpy behavior.

```
>>> import numpy
>>> x = numpy.ndarray(shape=(2,4))
>>> x[0:-1, 1:3]
array([[  5.21625023e-317,   1.16138128e-012]])
>>> x[0:, 1:3]                                                                                                  
array([[  5.21625023e-317,   1.16138128e-012],
       [  2.16449511e+233,   1.95218670e-110]])
```

This is because Python's slice syntax permits omitting the ending index to say 'go to the end'.  But in the format we've picked (IntTensor for starts and ends), this is not representable.

My suggestion for now is that we disallow negative indexing for now, pending a resolution of this problem.

**Comment by bddppq** [comment]
This could address this issue in the translation level: https://github.com/onnx/onnx-caffe2/pulls
Also there will be Caffe2 changes soon to adjust the negative indexing semantics.
