### ISSUE TITLE
Feature Request: Tokenization + Word Indexing

### ISSUE THREAD

**Issue by soaxelbrooke** [onnx/onnx#1474]
This is a direct comment on the [NLP strategy wiki page](https://github.com/onnx/onnx/wiki/NLP-in-ONNX:-A-Strategy-Proposal) regarding tokenization and word indexing.

Currently, I'm doing framework selection for a generic text classifier platform, and have done extensive research into this, and felt I had to comment, since I see inclusion of tokenization and word index mapping as a critical part of a model's interface.  There are a few problems that in-model tokenization and word index mapping solves:

- Without included tokenization and word indexing, model roll outs must be synchronized with API server updates - if you are serving from an FaaS or edge server (like cloudflare workers), this is a big risk
- Putting word indexing into API servers (instead of the model) requires putting them in deployment artifacts, adding significant weight to otherwise small and simple deployments
- Clients must re-implement tokenization and word indexing in every implementation (did they forget to lowercase, etc), making bugs more likely

Also, tokenization and word indexing have extremely simple interfaces - for tokenization, the model developer may provide a regex for splitting or matching, and for word indexing they simply provide a mapping of words to indexes.

If these features had 1st class presence, I believe that would significantly diminish existing barriers to wider deployment of NLP models via ONNX.

**Comment by ArmenAg** [comment]
This might be tough. A lot of different companies have different internal tokenization methods. How would you standardize this? Also word indexing is becoming less and less popular for methods like BPE/Unigram. How would your proposal deal with that?

**Comment by soaxelbrooke** [comment]
Maybe there was a misunderstanding, by word indexing, I mean the process of transforming a token (word, byte pair, character, etc) into an embedding index that is the traditional input to a neural NLP model.

BPE and non-whitespace separated languages make the tokenization story a bit more complicated, but for character-level models and for whitespace separated languages, we can provide a simple interface via regex.  In this way, the engineer simply provides a regex to match tokens and potentially a sequence length, and this produces a sequence of tokens matched by the regex.  The same could be done using regex splitting instead of matching.

For word indexing, its the same problem as mapping to word embeddings - except mapping tokens to integers instead of integers to float arrays.

**Comment by snnn** [comment]
Hi @soaxelbrooke ,

So the problem is like : if you have a set of words, you want to assign an unique numeric id to each of them? I believe this is an extremely hard problem and there is no best way of doing this.

**Comment by soaxelbrooke** [comment]
The actual vocab learning (assignment of tokens to indexes, learning of which tokens are in-vocabulary) would be the responsibility by the application code - as I see it, the deployment artifact for the vocab would simply be a hash map from token to integer index.

For a concrete example, Keras has a `Tokenizer` class for learning vocabs and transforming text into word indexes.  The vocabulary the `Tokenizer` learns is [stored in `word_index`](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/text.py#L193), a simple Python dictionary.  In this way, at deploy time you can recreate this tokenizer just by assigning a vocab from disk (from a JSON file, etc).

**Comment by ArmenAg** [comment]
So here is my problem with this. Building a word_index is trivial once the tokenization is known. The tokenizer in Keras is a very simple one and is not reflective of what is done in production. For example, the word tokenization we use at MS is not regex based but is a non-trivial library. Furthermore word_index doesn't make sense for techniques like BPE/Unigram where tokenization requires going through a tree/language model.

Without standardizing tokenization it doesn't make sense to support word_index.

**Comment by snnn** [comment]
Even it's already tokenized, it's not trivial if you have an industrial level data set.

**Comment by soaxelbrooke** [comment]
Yes, this definitely wouldn't cover all cases - but I'm hoping that perfect won't get in the way of good.  If we limit the scope (for now) of tokenization to regex matching, then we can rest on the work done to standardize regex implementations and leverage people's preexisting knowledge of it.  In my opinion, this would still be very useful for most people deploying NLP models via ONNX, but I would understand if it didn't provide sufficient coverage of tokenization techniques.

**Comment by soaxelbrooke** [comment]
For some context, I'm working on a text classifier platform where model inference will happen in a few environments: on a server, in a PaaS like Cloud ML Engine, and in the browser.  Re-implementation of more complex tokenization in the browser is a risk, as it is for further places we deploy where we don't get to ship our application code.  This is a non-problem for server-only deployments, but I wanted to add some context for why this was is of such great interest.

**Comment by WilliamTambellini** [comment]
+1 for a tokenizerv onnx op, even if simply regexp based.

**Comment by prasanthpul** [comment]
have you seen https://github.com/onnx/onnx/blob/master/docs/Operators.md#StringNormalizer and https://github.com/onnx/onnx/blob/master/docs/Operators.md#TfIdfVectorizer

**Comment by soaxelbrooke** [comment]
@prasanthpul Unfortunately, neither of those solve the core problem here of turning an N x 1 matrix of un-tokenized strings into an N x M matrix of tokens.  The `TfidfVectorizer` does vectorize, but the bag-of-words assumption in it prevents sequence classification with things like RNNs.

**Comment by yuslepukhin** [comment]
This is how it is currently supported as a non-standard op in Microsoft/onnxruntime. Would this be an acceptable proposal:

> Tokenizer divides each string in X into a vector of strings along the last axis. Allowed input shapes are [C] and [N, C].
  If the maximum number of tokens found per input string is D, the output shape would be [N, C, D] when input shape is [N, C].
  Similarly, if input shape is [C] then the output should be [C, D]. Tokenizer has two different operation modes.
  The first mode is selected when "tokenexp" is not set and "separators" is set. If "tokenexp" is set and "separators" is not set,
  the second mode will be used. The first mode breaks each input string into tokens by removing separators.  Let's  assume "separators" is [" "] and consider an example.
  If input is   ["Hello World", "I love computer science !"] whose shape is [2],   then the output would be [["Hello", "World", padvalue, padvalue, padvalue],
 ["I", "love", "computer", "science", "!"]]
 whose shape is [2, 5] because you can find at most 5 tokens per input string.
 Note that the input at most can have two axes, so 3-D and higher dimension are not supported.

>  For each input string, the second mode searches matches of "tokenexp" and each match will be a token in Y.
 The matching of "tokenexp" is conducted greedily (i.e., a match should be as long as possible).
 This operator searches for the first match starting from the beginning of the considered string,
 and then launches another search starting from the first remained character after the first matched token.
 If no match found, this operator will remove the first character from the remained string and do another search.
 This procedure will be repeated until reaching the end of the considered string.

>   Let's consider another example to illustrate the effect of setting "mark" to true.
  If input is ["Hello", "World"],
  then the corresponding output would be [0x02, "Hello", "World", 0x03].
  This implies that if mark is true, [C]/[N, C] - input's output shape becomes [C, D+2]/[N, C, D+2].`

**Comment by soaxelbrooke** [comment]
I'm a bit unsure what the second mode is doing - is that to achieve subword tokenization?

**Comment by yuslepukhin** [comment]
Both modes are essentially the same thing. First mode an array of separators is applied sequentially. In the second mode a regex is used for the purpose.

**Comment by EmergentOrder** [comment]
+ 1 for tokenization support, even if limited.

For word indexing, ONNX-ML contains a Map type: https://github.com/onnx/onnx/blob/master/onnx/onnx-ml.proto#L667
I'm not sure if there is support in ONNX Runtime though.

**Comment by skaiware** [comment]
Perhaps a way to move forward on that project would be to think about algos like 'sentencepiece' :
https://github.com/google/sentencepiece
Such algo/library can do both (de)tokenizing and word indexing (tokens to IDs). 
If we consider an input string as a seq of unicode chars, meaning as a 1d tensor of (utf32?) chars, then such algos convert a string to a 1d tensor of IDs (some kind of uint), that could then feed a network (embedding layer, ...).
A SP model is moreover (usually) a single PB file, meaning in theory friendly with onnx.

**Comment by WilliamTambellini** [comment]
Perhaps a way to move forward on that project would be to think about algos like 'sentencepiece' :
https://github.com/google/sentencepiece
Such algo/library can do both (de)tokenizing and word indexing (tokens to IDs).
If we consider an input string as a seq of unicode chars, meaning as a 1d tensor of (utf32?) chars, then such algos convert a string to a 1d tensor of IDs (some kind of uint), that could then feed a network (embedding layer, ...).
A SP model is moreover (usually) a single PB file, meaning in theory friendly with onnx.

**Comment by EmergentOrder** [comment]
Looks like this already exists, thanks to @xadupre and co. !
See: https://github.com/microsoft/ort-customops
one of the goals of which is: "Build all-in-one ONNX model from the pre/post processing code"
Specifically, https://github.com/microsoft/ort-customops lists GPT2Tokenizer, WordpieceTokenizer and SentencepieceTokenizer as supported, along with a number of other text utils.
