### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

### ISSUE THREAD

**Issue by uhvardhan** [onnx/onnx#1478]
Hi, 
I am trying to convert Pytorch model to onnx model. Here is the code I am using:
`import torch
from torch.autograd import Variable

### Load the trained model from file

path = "model_0000_4_4_6_98_160.pth"

trained_model = torch.load(path)

trained_model.state_dict()

### Export the trained model to ONNX
trained_model = torch.nn.DataParallel(trained_model, device_ids=range(torch.cuda.device_count()))
dummy_input = Variable(torch.randn(1, 3, 224, 224)) # one black and white 28 x 28 picture will be the input to the model
torch.onnx.export(trained_model.module, dummy_input, "model.onnx")`

I get the above runtime error. Any suggestions? I saw in another issue that removing the nn.DataParallel wrapper helps, but I did do that right? 

Thanks

**Comment by ArmenAg** [comment]
What does your pytorch model look like?

**Comment by uhvardhan** [comment]
It's a complete model including the weights. I can paste the output here

**Comment by uhvardhan** [comment]
`DataParallel(
  (module): ResNet(
    (conv1): Conv2d(3, 4, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True)
    (relu): ReLU(inplace)
    (maxpool): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), dilation=(1, 1), ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True)
      )
    )
    (layer2): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(4, 6, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(6, 6, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True)
        (downsample): Sequential(
          (0): Conv2d(4, 6, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True)
        )
      )
    )
    (layer3): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(6, 98, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(98, eps=1e-05, momentum=0.1, affine=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(98, 98, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(98, eps=1e-05, momentum=0.1, affine=True)
        (downsample): Sequential(
          (0): Conv2d(6, 98, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(98, eps=1e-05, momentum=0.1, affine=True)
        )
      )
    )
    (layer4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(98, 160, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True)
        (relu): ReLU(inplace)
        (conv2): Conv2d(160, 160, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True)
        (downsample): Sequential(
          (0): Conv2d(98, 160, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(160, eps=1e-05, momentum=0.1, affine=True)
        )
      )
    )
    (avgpool): AvgPool2d(kernel_size=7, stride=1, padding=0, ceil_mode=False, count_include_pad=True)
    (fc): Linear(in_features=160, out_features=16, bias=True)
  )
)`

This is the output I get when I print the pytorch model

**Comment by ArmenAg** [comment]
How are you using scatter? is it the inplace op? If you want to see the type of ops supported by 
pytorch->onnx check out https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py
