### ISSUE TITLE
Windows build (64bit) fails with protobuf 3.6 on conda-forge

### ISSUE THREAD

**Issue by raymondxyang** [onnx/onnx#1485]
Windows build fails with protobuf 3.6 (64bit) on conda-forge, which was published yesterday. Will do more investigating on the issue

**Comment by snnn** [comment]
Any logs?

I'm using protobuf 3.6.1 with onnx on Windows, it works fine. Protobuf 3.5.x has a serious bug on Windows.

**Comment by raymondxyang** [comment]
i.e https://ci.appveyor.com/project/onnx/onnx/builds/19356108

**Comment by askhade** [comment]
#2452 fixes the Windows ONNX build failures in conda envs

**Comment by askhade** [comment]
The build failure with later versions of protobuf when using conda-forge have been identified and fixed in the above mentioned PR. Closing this issue.

Next step is to update the CI to not use 3.5.2 because of the bug Changming mentioned. Will create a new issue for this one.
