### ISSUE TITLE
Please cleanup the code related to ONNX_NAMESPACE::ConvertVersion

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1496]
```c++
ModelProto ConvertVersion(
    const ModelProto& mp_in,
    const int target_version);
```

First, at here, "const int" make no sense. Please remove const.
Second, find all the callers, who is invoking this function. You'll find more problems.

**Comment by snnn** [comment]
BTW, please stop abusing const. Use it only when such use increases readability. 
https://google.github.io/styleguide/cppguide.html#auto

**Comment by houseroad** [comment]
PR is merged
