### ISSUE TITLE
Are there any plans to add MXNet support?

### ISSUE THREAD

**Issue by jasmeetsb** [onnx/onnx#15]
Are there any plans to add Apache MXNet support and if so by when?

Thanks,
Jasmeet Bhatia

**Comment by mbehrisch** [comment]
Indirectly this is already possible. There is a **MXNet -> Caffe converter** and a **Caffe -> Pytorch converter**.
Mabe this side helps [https://github.com/ysh329/deep-learning-model-convertor](https://github.com/ysh329/deep-learning-model-convertor). My personal experience is that the converters help if you have standard network structures.

**Comment by ebarsoum** [comment]
We love more frameworks to support ONNX, we are open to PR.

**Comment by Yangqing** [comment]
cc @mli FYI - there are discussions between ONNX and mxnet but there is no set timeline yet.

**Comment by mli** [comment]
we are still in discussing when mxnet will support onnx. I don't have a concrete time yet, but will update this thread once it is on the roadmap.

**Comment by tqchen** [comment]
since mxnet is migrating toward nnvm compiler, https://github.com/onnx/onnx/issues/89 would be relevant

**Comment by bddppq** [comment]
https://mxnet.apache.org/api/python/contrib/onnx.html
