### ISSUE TITLE
RuntimeError: ONNX export failed: Could not export a broadcasted operation; ONNX likely does not support this form of broadcasting.

### ISSUE THREAD

**Issue by thach4567** [onnx/onnx#1502]
When I was trying to convert from pytorch model to onnx graph i encountered this error line then didn't know where to go. 
![onnx-issues](https://user-images.githubusercontent.com/15871037/46846140-b2d27f80-ce08-11e8-90e2-9b40d69c5e95.png)
I scolled down and saw these lines 
![onnx_return_issues](https://user-images.githubusercontent.com/15871037/46845773-1065cc80-ce07-11e8-9c97-40d0ee742dcf.png)
Can anyone help me out? I don't know which computation ONNX doesn't support right now. I think maybe the line `return(%)` show the computation units aren't supported in ONNX, but in ONNX v1.3.0 doc all that computations are already in. 
I used : 
**pytorch** : v0.4.1
**onnx** : v1.3.0
**python** : v3.6
**webdnn** : v1.2.6
 Thank you!

**Comment by houseroad** [comment]
ONNX supports numpy broadcasting now, which is the same as pytorch. You may upgrade your pytorch to higher version (such as nightly build), and try to export the model again.

**Comment by thach4567** [comment]
@houseroad yes, I tried pytorch-nightly as you said. But it appeared new errors. Do you have any idea ?
![image](https://user-images.githubusercontent.com/15871037/46941730-00175100-d096-11e8-86ec-bbbeb66880ea.png)
Many thanks !

**Comment by houseroad** [comment]
This should be an unsupported feature in PyTorch's ONNX exporter. Please report it in the PyTorch github repository with code snippet for reproduction. Thanks!
