### ISSUE TITLE
Add Aten operators in torch/onnx/symbolic.py, but no use

### ISSUE THREAD

**Issue by wangyunxiaa** [onnx/onnx#1504]
when i am tring to transfor a pretrained pytorch model to onnx, I got errors as following:

`/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator nll_loss because torch.onnx.symbolic.nll_loss does not exist
  .format(op_name, op_name))
/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/torch/onnx/utils.py:500: UserWarning: ONNX export failed on ATen operator view_as because torch.onnx.symbolic.view_as does not exist
  .format(op_name, op_name))

RuntimeError: ONNX export failed: Couldn't export operator aten::nll_loss`

and the net struct is as followings:

`Graph we tried to export:
graph(%input_1 : Long(1, 2)
      %input_2 : Long(1)
      %learned_0 : Float(10001, 200)
      %learned_1 : Float(800, 200)
      %learned_2 : Float(800, 200)
      %learned_3 : Float(800)
      %learned_4 : Float(800)
      %learned_5 : Float(200, 200)
      %learned_6 : Float(10001)
      %learned_7 : Float(10001)) {
  %10 : Float(1, 2, 200) = onnx::Gather(%learned_0, %input_1), scope: RNNModel/Embedding[encoder]
  %11 : Float(1, 2, 200) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%10), scope: RNNModel
  %12 : Float(1!, 1, 200) = onnx::Slice[axes=[1], ends=[-1], starts=[0]](%11), scope: RNNModel
  %13 : Float(1!, 1, 200), %14 : Dynamic = onnx::Dropout[ratio=0](%12), scope: RNNModel/Dropout[drop]
  %15 : Long() = onnx::Constant[value={1}]()
  %16 : Dynamic = onnx::Shape(%13), scope: RNNModel/LSTM[rnn]
  %17 : Long() = onnx::Gather[axis=0](%16, %15), scope: RNNModel/LSTM[rnn]
  %18 : Long() = onnx::Constant[value={1}]()
  %19 : Long() = onnx::Constant[value={200}]()
  %20 : Dynamic = onnx::Unsqueeze[axes=[0]](%18), scope: RNNModel/LSTM[rnn]
  %21 : Dynamic = onnx::Unsqueeze[axes=[0]](%17), scope: RNNModel/LSTM[rnn]
  %22 : Dynamic = onnx::Unsqueeze[axes=[0]](%19), scope: RNNModel/LSTM[rnn]
  %23 : int[] = onnx::Concat[axis=0](%20, %21, %22), scope: RNNModel/LSTM[rnn]
  ......
  %69 : Float(1, 10001) = onnx::LogSoftmax[axis=1](%66), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %70 : Dynamic = prim::Undefined(), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %71 : Long() = onnx::Constant[value={0}]()
  %72 : Long() = onnx::Constant[value={-100}]()
  %73 : Float(1) = aten::nll_loss(%69, %68, %70, %71, %72), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %output : Float(1, 1) = aten::view_as(%73, %55), scope: RNNModel/IndexLinear[criterion]
  return (%output);
}
`

The operator "aten::nll_loss"and "aten::view_as" i want are standardized in ONNX:

`Tensor nll_loss(const Tensor & self, const Tensor & target, const Tensor & weight, int64_t reduction, int64_t ignore_index) const override;`
`Tensor view_as(const Tensor & self, const Tensor & other) const override;`

so, i define the symbolic function in torch/onnx/symbolic.py as following:

`@parse_args('v', 'v', 'v', 'i', 'i')
def nll_loss(g, input, target, weight, reduction, ignore_index):
    return g.op("Aten",
                input,
                target,
                weight,
                operator_s="nll_loss",
                reduction_i=reduction,
                ignore_index_i=ignore_index)

@parse_args('v', 'v')
def view_as(g, self, other):
    return g.op("Aten", self, other, operator_s="view_as")`

But it is no use,the error still exists， does anyone know where there is an error?
thanks!

**Comment by houseroad** [comment]
Could you paste a code snippet to reproduce the problem?

**Comment by wangyunxiaa** [comment]
thank you very much for your repley, 
I have found the error, beause i installed pytorch by source,but i just changed the source code,when i update the file in the installed path it worked.

by the way,I have successfully converted the model to onnx,but i found there has some op like"prim::Undefined()",does these op affect the subsequent conversion ？

The converted onnx model checked ok, but i cannot convert it to tensorflow:

`
model = onnx.load("vpmodel.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)
`
the above checking codes all run ok, but when i do the following `tf_rep = prepare(model)` ,I got another errors as following:

`/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/common/handler_helper.py:74: UserWarning: Unknown op MeanVarianceNormalization in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
Traceback (most recent call last):
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2657, in gather
    return params.sparse_read(indices, name=name)
AttributeError: 'Tensor' object has no attribute 'sparse_read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "checkonnx.py", line 28, in <module>
    tf_rep = prepare(model)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/backend.py", line 76, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/backend.py", line 96, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/backend.py", line 150, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/backend.py", line 245, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/handlers/handler.py", line 60, in handle
    return ver_handle(node, **kwargs)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/handlers/backend/gather.py", line 14, in version_1
    return [cls.make_tensor_from_onnx_node(node, **kwargs)]
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 111, in make_tensor_from_onnx_node
    return cls._run_tf_func(tf_func, inputs, attrs)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/onnx-tensorflow/onnx_tf/handlers/backend_handler.py", line 180, in _run_tf_func
    **dict([(p, attrs[p]) for p in params if p in attrs]))
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2659, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3142, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 609, in _apply_op_helper
    param_name=input_name)
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64
`
the pytorch model has 2 inputs,and all the input type are TensorLong, does the error caused due to the input type?

**Comment by houseroad** [comment]
The first problem is that you try to export `nll_loss`, and it's not supported by the exporter in the pytorch, which I think it's legit, since ONNX is for inference only right now.

The second problem seems 1) the exported model is incorrect, or 2) onnx-tf doesn't support the op well. You may check the model using netron, and post it in the onnx-tf repo.
