### ISSUE TITLE
weird maxpool_with_argmax_2d_precomputed_strides test

### ISSUE THREAD

**Issue by kali** [onnx/onnx#1508]
Hey folks,

I think the second output ("z") of this unit test is kind of wrong, or... there is something i don't understand in the second output specification.

I would expect it to be `[[[[6, 8],    [16, 18]]]]` matching exactly the first output layout.

**Comment by fumihwh** [comment]
@kali 
`storage_order=1` means column major. Index counts by column instead of row.

**Comment by kali** [comment]
@fumihwh  Thanks. I missed the attribute.
