### ISSUE TITLE
batch norm non-spatial mode test case and spec clarification

### ISSUE THREAD

**Issue by pranavsharma** [onnx/onnx#1515]
It looks like the spec is incorrect w.r.t the dimensions for B, mean, var and scale when spatial = 0. The dimensions should be 1xCxHxW or 1xCxDxHxW (at least as per the [cudnn APIs](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnDeriveBNTensorDescriptor)). 

Also we should add a test case.

**Comment by snnn** [comment]
@pranavsharma  please verify if this issue can be closed.
