### ISSUE TITLE
onnx reports undefined symbol with protobuf 3.6.1, _ZNK6google8protobuf7Message11GetTypeNameEv

### ISSUE THREAD

**Issue by xiaotiancd** [onnx/onnx#1516]
Hi,
I am trying to build onnx from source on a Power Linux(redhat) machine, the installation can pass, but every time when I use it, will generate the error message below:
 
python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/xuxt/.local/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-ppc64le.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/mnt/xuxt/.local/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-ppc64le.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/mnt/xuxt/.local/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-ppc64le.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /mnt/xuxt/.local/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-ppc64le.egg/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

I installed the protoc and protobuf from the latest source as well and passed its test, but this symbol from onnx does not exist.
   $ ldd onnx_cpp2py_export.so
	linux-vdso64.so.1 =>  (0x0000200000050000)
	libprotobuf.so.17 => /mnt/xuxt/DLC/dep/lib/libprotobuf.so.17 (0x0000200000260000)
	libstdc++.so.6 => /mnt/xuxt/DLC/dep/lib64/libstdc++.so.6 (0x0000200000590000)
	libm.so.6 => /lib64/libm.so.6 (0x00002000007b0000)
	libgcc_s.so.1 => /mnt/xuxt/DLC/dep/lib64/libgcc_s.so.1 (0x00002000008a0000)
	libc.so.6 => /lib64/libc.so.6 (0x00002000008e0000)
	/lib64/ld64.so.2 (0x0000200000000000)

xuxt@f3:~$ protoc --version
libprotoc 3.6.1
xuxt@f3:~$ which protoc
/mnt/xuxt/DLC/dep/bin/protoc

what I need to do then? thank you!

Xiaotian

**Comment by houseroad** [comment]
according to your error message, it depends on /mnt/xuxt/DLC/dep/lib/libprotobuf.so.17.
try to add `/mnt/xuxt/DLC/dep/lib/` to LD_LIBRARY_PATH
something like `export LD_LIBRARY_PATH=/mnt/xuxt/DLC/dep/lib/:$LD_LIBRARY_PATH`

**Comment by xiaotiancd** [comment]
@houseroad  thanks for your reply. if the LD_LIBRARY_PATH does not have the dir, my ldd command output I posted will not have the file ibprotobuf.so.17.   So do you think onnx does not compatible with the libprotobuf.so.17?

see the output:
uxt@f3n01:~$ echo $LD_LIBRARY_PATH
/mnt/xuxt/DLC/dep/lib:/mnt/xuxt/DLC/dep/lib64:/usr/local/lib

$ ldd onnx_cpp2py_export.so
linux-vdso64.so.1 => (0x0000200000050000)
libprotobuf.so.17 => /mnt/xuxt/DLC/dep/lib/libprotobuf.so.17 (0x0000200000260000)
libstdc++.so.6 => /mnt/xuxt/DLC/dep/lib64/libstdc++.so.6 (0x0000200000590000)
libm.so.6 => /lib64/libm.so.6 (0x00002000007b0000)
libgcc_s.so.1 => /mnt/xuxt/DLC/dep/lib64/libgcc_s.so.1 (0x00002000008a0000)
libc.so.6 => /lib64/libc.so.6 (0x00002000008e0000)
/lib64/ld64.so.2 (0x0000200000000000)

**Comment by houseroad** [comment]
Can you check whether you have multiple versions of protobuf in your environment? ONNX may be compiled with a different version of protobuf

**Comment by snnn** [comment]
We can get rid of such errors forever by: statically link to protobuf

**Comment by xiaotiancd** [comment]
thanks to you two, static link works.

**Comment by earlyEpiphyte** [comment]
> thanks to you two, static link works.
I meet the same problem as yours. Can you tell me some details about static link? I really don`t konw how to do.
