### ISSUE TITLE
tf.reverse_sequence equivalence 

### ISSUE THREAD

**Issue by pengwa** [onnx/onnx#1526]
for RNN, the input has shape [batch_size, max_seq_length, input_size], sometimes we need to reverse each sequence in the bathch, but each sequence's length could be different, usually specified with tensor of shape [batch_size].

TF has the function (https://www.tensorflow.org/api_docs/python/tf/reverse_sequence) to revert the sequence of different length. is this planned in ONNX? Or is a set of primitive ops possible to do the similar thing?

**Comment by pengwa** [comment]
I used a Scan who has only one Identity in the body graph, to achieve this. closed this.

**Comment by pengwa** [comment]
reactive since in OPSET 9, Scan does not have sequence_length as input any more.

**Comment by ebarsoum** [comment]
Already in ONNX: https://github.com/onnx/onnx/blob/master/docs/Operators.md#ReverseSequence

**Comment by imaihal** [comment]
Excuse me for reopening old issue. 

What is the expected behavior when using 3D input in onnx reverse_sequence? Can we get the same results with tf?
Following is an example of 3D input (just change 4x4 input in https://github.com/onnx/onnx/blob/main/docs/Operators.md#ReverseSequence to 1x4x4)

 In tf.reverse_sequence, we can set `batch_axis=2`. So, we can get the same results in 4x4 input as follows. However, since `batch_axis` in onnx is limited in 0 or 1, we can't get the same results with tf. 
```
>>> input = [[[0.0, 4.0, 8.0, 12.0], [1.0, 5.0, 9.0, 13.0], [2.0, 6.0, 10.0, 14.0], [3.0, 7.0, 11.0, 15.0]]]
>>> seq_lengths = [4, 3, 2, 1]
>>> output = tf.reverse_sequence(input, seq_lengths, seq_axis=1, batch_axis=2)
>>> print(output)
tf.Tensor(
[[[ 3.  6.  9. 12.]
  [ 2.  5.  8. 13.]
  [ 1.  4. 10. 14.]
  [ 0.  7. 11. 15.]]], shape=(1, 4, 4), dtype=float32)
```

**Comment by imaihal** [comment]
I think we can get the same results in onnx reverse_sequence by using transpose op before and after reverse_sequence. This is because `time_axis` and `batch_axis` should be 0 or 1. Is this requested in onnx reverse_sequence? 

```
>>> input
[[[0.0, 4.0, 8.0, 12.0], [1.0, 5.0, 9.0, 13.0], [2.0, 6.0, 10.0, 14.0], [3.0, 7.0, 11.0, 15.0]]]
>>> input1 = tf.transpose(input, perm=[1, 2, 0])
>>> output1 = tf.reverse_sequence(input1, seq_lengths, seq_axis=0, batch_axis=1)
>>> output = tf.transpose(output1, perm=[2, 0, 1])
>>> output
<tf.Tensor: shape=(1, 4, 4), dtype=float32, numpy=
array([[[ 3.,  6.,  9., 12.],
        [ 2.,  5.,  8., 13.],
        [ 1.,  4., 10., 14.],
        [ 0.,  7., 11., 15.]]], dtype=float32)>

```

**Comment by justinchuby** [comment]
I think combining with transpose is doable.
