### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict

### ISSUE THREAD

**Issue by olgapeled** [onnx/onnx#1528]
Hi All,

I am trying to convert yolo2 pytorch to onnx model and I got:
"RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict"

This is the code example:
https://github.com/purelyvivid/yolo2_onnx/blob/master/1.yolo2_pytorch_onnx_save_model.ipynb

Any ideas?

**Comment by prasanthpul** [comment]
This seems to be a PyTorch error. Can you file the issue on the PyTorch GitHub?
