### ISSUE TITLE
incorrect ConvTranspose Bias shape

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#1531]
The current spec `Optional 1D bias to be added to the convolution, has size of C.` maybe incorrect.
Pytorch: https://pytorch.org/docs/stable/nn.html#torch.nn.ConvTranspose2d
Tensorflow: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/convolutional.py#L839
Bias should have size `M` (say feature maps or filters or out channel) not `C`

**Comment by houseroad** [comment]
Fixed by @fumihwh , thanks!
