### ISSUE TITLE
Scan op description 

### ISSUE THREAD

**Issue by pengwa** [onnx/onnx#1537]
>  // execute loop
>       for (int t = 0; t < N; ++t) {
>           // generate the scan-input elements: the notation T<axis=k>[t] indicates the sub-tensor
>           **// of rank one less than T obtained by indexing T at position t along axis k.**
>           _si_1 = (scan_1<axis=0>[batch])<axis=1>[t];_
>           ... ;
>           si_m = (scan_m<axis=0>[batch])<axis=1>[t];
>           // execute loop-body
>           st_1, ..., st_n, so_1, ..., so_k = loop-body(st_1, ..., st_n, si_1, ..., si_m)
>           // accumulate the scan-output elements
>           scan_out_1 = Concat<axis=0>(scan_out_1, so_1); ... ; scan_out_k = Concat<axis=0>(scan_out_k, so_k);
>       }

should _that_ be?

si_1 = (scan_1<axis=0>[batch])<axis=**0**>[t]

because scan_1<axis=0>[batch] will have sequence_length as the first dim?

**Comment by houseroad** [comment]
cc: @ebarsoum

**Comment by gramalingam** [comment]
Yes, that is right. Equivalently, we should swap the order of the two indexing operations. In any case, the newer scan op has dropped the batch-axis discussion, so this is not relevant to the current (opset 9) scan op. (However, it is worth updating the documentation of the opset 8 scan operation.)
