### ISSUE TITLE
make_tensor with float16 fails

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1539]
The function would need to perform the float16->uint16_t conversion but doesn't

Error message is `TypeError: 0.4956 has type numpy.float16, but expected one of: int, long`

**Comment by nicklhy** [comment]
@Flamefire I can still get this error in my program. Actually, it could be produced with the below script
```
import onnx
import numpy as np

x = np.random.uniform(0, 1, (10, 10)).astype(np.float16)
onnx.helper.make_tensor(
    name='data',
    data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[x.dtype],
    dims=np.shape(x),
    vals=x.flatten().tolist(),
    raw=False
)
```
Can I ask how you solved this problem?

**Comment by Flamefire** [comment]
Honestly I don't understand my own comment anymore.  From a quick look: This is a low-level function so you are expected to have done all conversions already. So you *must* pass the correct type (float16 reinterpretet as uint16 in this case) to this function already as per the ONNX spec. If you want to use numpy types use the numpy helper: https://github.com/onnx/onnx/blob/4023baee006a9468516bf249f3b1c4a719a5adb8/onnx/numpy_helper.py#L70
