### ISSUE TITLE
How to use Softmax for pixel classification?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#1543]
I want to do pixel classification, where my output tensor has shape [N C H W], where for each combination of [N,H,W], the C values are normalized to sum to 1.  I don't see how Softmax can be used to produce this tensor. According to the Doc (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Softmax), 

"The input is a 2-D tensor (Tensor) of size (batch_size x input_feature_dimensions). The output tensor has the same shape and contains the softmax values of the corresponding input. Input does not need to explicitly be a 2D vector; rather, it will be coerced into one."

But since C is an internal dimension, there is no way to reshape the input [N C H W] into a 2D tensor that isolates C as the final dimension.

What is the recommended thing to do?

**Comment by ebarsoum** [comment]
Why can't you transpose it first? https://github.com/onnx/onnx/blob/master/docs/Operators.md#Transpose

**Comment by mathisdon** [comment]
Sounds promising. Can you be more specific please?

**Comment by houseroad** [comment]
For example tensor A's shape is (N, C, H, W), and you would like to coerce the tensor to (N x H x W, C).

You can always A' = transpose(A, perms=(0, 2, 3, 1)), now A' is (N, H, W, C) , then you can apply the Softmax.
