### ISSUE TITLE
What is the output shape of the Softmax operator? Doc is ambiguous.

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#1544]
The Softmax Doc (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Softmax) says the input tensor can be either **2D**, or can be **coerced into 2D**, and that the output tensor has **"the same shape as the input tensor"**.

But is the output tensor the same shape as the input tensor **before** or **after** it is coerced into 2D? The Doc simply does not say. 

So, which is it?

**Comment by houseroad** [comment]
The output shape is without coercion. I have created a pr to address it.
