### ISSUE TITLE
v0.2.1 has no attribute '__version__'

### ISSUE THREAD

**Issue by imai-lm** [onnx/onnx#155]
ONNX v0.2.1 (and latest version from github) has no attribute `__version__`:
```
root@837e5d9119f4:/workspace/test# pip install onnx==0.2.1
Collecting onnx==0.2.1
Requirement already satisfied: protobuf in /usr/local/lib/python3.5/dist-packages (from onnx==0.2.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==0.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from onnx==0.2.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf->onnx==0.2.1)
Installing collected packages: onnx
Successfully installed onnx-0.2.1
root@837e5d9119f4:/workspace/test# python
Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnx' has no attribute '__version__'
```

**Comment by bddppq** [comment]
We used to do `from .version import version as __version__` in `onnx/__init__.py`,  but linter doesn't like it :-), so it got removed in a auto cleanup in 9bc425d
@houseroad We probably should add it back (and add a marker to make linter ignores it) as it's kinda convention in many Python packages.

**Comment by houseroad** [comment]
Yeah, my bad. Let's add it back.

**Comment by houseroad** [comment]
Here we go. https://github.com/onnx/onnx/pull/156

**Comment by houseroad** [comment]
@bddppq Shall we update the pip package?

**Comment by bddppq** [comment]
pip package is kinda like our release channel, so as we don't treat every commit and bug fix as a new release, I'm not going to update the pip package at this time.

@imai-lm Could you verify whether the fix works for you?
