### ISSUE TITLE
Any interest in ONNX.JS to run ONNX models in browser?

### ISSUE THREAD

**Issue by EmmaNingMS** [onnx/onnx#1551]
Hi, as you know, running ML in browsers could benefit to building cross-platform AI experience with low develop cost,  protecting user privacy as well as reducing server-client communications. We are currently working on ONNX.JS project to empower web developer to run ONNX modes directly in browser and got very promising perf result. Anyone has any interest in this project? We would like to share more and hear feedbacks from community.

**Comment by bddppq** [comment]
Yes I'm interested! :-)

**Comment by EmmaNingMS** [comment]
Glad you are interested :).  Do you have specific user scenario/customer requirement for transfer learning? As the beginning, we are focusing on inference models in browser. And ONNXJS project will go opensource in Nov.

**Comment by fumihwh** [comment]
@EmmaNingMS Interesting. Maybe you could also try Tensorflow.js by using onnx-tf.

**Comment by EmmaNingMS** [comment]
@fumihwh Tensorflow.js is the major benchmark we are looking into. Based on one of the public perf reports about Tensorflow.js, ONNXJS is better now. And we will do apple-apple comparison from our side.

**Comment by EmmaNingMS** [comment]
@bddppq @fumihwh @martinraison [ONNX.js](https://github.com/Microsoft/onnxjs) is open sourced now. . Welcome any feedback.

**Comment by ddavydenko** [comment]
I am interested in knowing more! By reading about it so far I am seeing that there is Node.js being used. Which makes me think there is server infrastructure involved in running actual inference and ONNX.js being a client for engaging standard server-based inference via frontend friendly interface. Am I correct or I am missing some fundamental details? Any additional documents to read about it would be much appreciated :)
