### ISSUE TITLE
Proposal: Op Registry

### ISSUE THREAD

**Issue by ArmenAg** [onnx/onnx#1560]
Once we start getting into more complicated passes having knowledge about operators becomes incredibly useful. What I propose is to maintain a registry of operators mapping to a set of descriptors. 

For example let's take a look at the [eliminate_nop_monotone_argmax](https://github.com/onnx/onnx/blob/master/onnx/optimizer/passes/eliminate_nop_monotone_argmax.h) pass. Within the pass we have to maintain an unordered set of ops that are monotone. The correct design would be to have a registry which we can ask whether or not if a certain op is monotone. Once such a registry is implemented, passes can be generalized through descriptors, therefore as we add new ops and their respective descriptors our passes naturally scale out.

Some possible descriptors we could have are:
- monotonic
- elementwise independent (op works on an individual element without knowledge of other elements, such as log, but not softmax since it requires calculating a sum over an axis)
- elementwise dependent (softmax, logsoftmax, softmin, softplus)
- reduction
- shape transform (e.g. transpose, view)

@houseroad @bddppq What do you guys think?

**Comment by ArmenAg** [comment]
@houseroad Any comments on this? I have a couple of passes in mind that could benefit from this.

**Comment by houseroad** [comment]
We can maintain our own mapping, also we can extend existing operator schema to specify such attributes: https://github.com/onnx/onnx/blob/master/onnx/defs/schema.h

I prefer the latter, since it's like a descriptor of the operator.

**Comment by ArmenAg** [comment]
@houseroad I think adding this to the operator schema is a great idea. What should we call such attributes (i.e. OpAnnotation, OptimAnnotation)? Also if we went this way, is there a easy way to view these attributes through the IR?

I can start working on this once we've cleared up the scope.

**Comment by ArmenAg** [comment]
@houseroad So I was taking a look at `ir_pb_converter.cc` and it seems that the IR is constructed from a proto object. So in order to have these annotations visible to the IR wouldn't we need to change onnx.proto?

**Comment by houseroad** [comment]
Either OpAnnotation or OptimAnnotation sounds good to me. We can add some helper functions to provide such access in our operator schema (not IR). We should not change IR, because this is purely about the operator spec.

**Comment by linkerzhang** [comment]
Quick question? should this kind of annotation be part of ONNX standard? I'm seeing them an implementation detail in each backend.

**Comment by houseroad** [comment]
@linkerzhang Probably we should give a better name to it. It's not general annotation, but some attribute/constraints the operator has. For example, `ElementwiseIndependent ` attribute, this is not an implementation detail, but describe that the computation can be done elementwise independently, this is a quite useful hint for us to do the optimization at ONNX level (not backend specific)

**Comment by ArmenAg** [comment]
The annotations for Op's should be in ONNX, but should not appear in the ONNX proto format. They are hints per Op that should help our optimization framework. For example the _Log_ operator is elementwise/indepement/strictly_monotonic_increasing regardless of the backend. We shouldn't rely on backend implementing this.

We can rename what these annotations\attributes are called. I'm completely open to this.
