### ISSUE TITLE
Model checker does not find missing output tensors

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1561]
It is currently possible for a graph to have no outputs w/o the checker complaining. I'd argue that unless there are no nodes, this is always invalid.

Furthermore one could argue that all "unconnected" node outputs (outputs from nodes not mentioned in the inputs from any other node) should be outputs of the graph. Not sure whether this is true in all cases though.

**Comment by houseroad** [comment]
I don't remember that in our IR spec, we have to have at least one output. If this is not claimed in our spec, the model checker should allow it. If you would like to change our spec, please open another issue. The constants are `unconnected` nodes.
