### ISSUE TITLE
[operator docs] Cast op attributed to incorrect opset

### ISSUE THREAD

**Issue by vinitra** [onnx/onnx#1568]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#cast

In the documentation above, it says that the most recent version of the Cast operator was created in opset 6, but it seems like it was modified in opset 7 based on the release documentation below:

https://github.com/onnx/onnx/releases/tag/v1.2.1
https://github.com/onnx/onnx/pull/727

**Comment by houseroad** [comment]
Reference to the discussion: https://github.com/onnx/onnx/pull/1008/files#r189758005
