### ISSUE TITLE
How to parse TensorProto raw_data in python

### ISSUE THREAD

**Issue by wlgcqh** [onnx/onnx#1572]
I wonder how to parse TensorProto raw_data in python,
onnx_model = onnx.load(args.onnx_model)
graph = onnx_model.graph
node = graph.node[0]
attribute_proto = node.attribute[0]
tensor = attribute_proto.t
tensor.raw_data is binary code，how to parse it.

**Comment by Nitin286roxs** [comment]
refer #1425

**Comment by TommyHuang821** [comment]
I have the same question.
Because #1425 is for weights, the some items, such as op_type: "Constant" with "raw_data" is stored in 「node」(not in initializers ).
It doesn't work by
```
node = model.graph.node
numpy_helper.to_array(node[0])
```
how to parse?
Thanks

**Comment by vandanavk** [comment]
> I have the same question.
> Because #1425 is for weights, the some items, such as op_type: "Constant" with "raw_data" is stored in 「node」(not in initializers ).
> It doesn't work by
> 
> ```
> node = model.graph.node
> numpy_helper.to_array(node[0])
> ```
> 
> how to parse?
> Thanks

@TommyHuang821 did you find a way to do this?

**Comment by Nitin286roxs** [comment]
_model_path =  "~/model.onnx"
_model = onnx.load(_model_path)
_graph=_model.graph
for initializer in _graph.initializer:
  W= numpy_helper.to_array(initializer)

this works for me..
using this u will get every layers parameter.

**Comment by ranazulay** [comment]
> _model_path = "~/model.onnx"
> _model = onnx.load(_model_path)
> _graph=_model.graph
> for initializer in _graph.initializer:
> W= numpy_helper.to_array(initializer)
> 
> this works for me..
> using this u will get every layers parameter.

This isn't helpful to the question above it. In case of a constant value for a node, the value isn't in graph.initializer.

Anybody else able to retrieve data from raw_data parts of actual nodes? not parameters from initializer segment.

**Comment by Frozenmad** [comment]
I encounter the same problem. Are there any solutions to access the value of type Constant?
