### ISSUE TITLE
convert onnx/modelzoo/shuffnet.onnx failed

### ISSUE THREAD

**Issue by cswwp** [onnx/onnx#1575]
I want to convert onnx model zoo shufflenet model.onnx to caffe2 init.pb and predict.pb, but it show error as follows:  

File "demo.py", line 30, in <module>
    init_net, predict_net = c2.onnx_graph_to_caffe2_net(model)
  File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 940, in onnx_graph_to_caffe2_net
    return cls._onnx_model_to_caffe2_net(model, device=device, opset_version=opset_version, include_initializers=True)
  File "/home/parker/anaconda2/envs/demo/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 933, in _onnx_model_to_caffe2_net
    raise RuntimeError('ONNX conversion failed')
RuntimeError: ONNX conversion failed

anyone help?

**Comment by houseroad** [comment]
https://s3.amazonaws.com/download.onnx/models/opset_9/shufflenet.tar.gz,
you can directly download the caffe2 version here

**Comment by houseroad** [comment]
If more help is needed, let me know

**Comment by sky186** [comment]
@houseroad 
hello ，i run your  example/pytorch_to_caffe.py,not succeed
please tell me  now ,onnx version ,,support pytorch mxnet version 
now I use onnx1.4.1, pytorch 1.1.0  
I see someone say   onnx_caffe2  is intergrated to caffe 2,so I modifies this
 onnx_caffe2.helper, not to modifies.

# from onnx_caffe2.backend import Caffe2Backend
import caffe2.python.onnx.backend as Caffe2Backend
from onnx_caffe2.helper import c2_native_run_net, save_caffe2_net, load_caffe2_net, \

but,error this 
 Caffe2Backend.onnx_graph_to_caffe2_net(onnx_model.graph, device="CPU")
AttributeError: 'module' object has no attribute 'onnx_graph_to_caffe2_net'
I know I need to modify interface usage, Do you have an example？

    benchmark_caffe2_model, benchmark_pytorch_model
