### ISSUE TITLE
pytorch data type is "NCHW" but tensorflow data type is "NHWC", when pytorch to onnx, and onnx to tensorflow how this diff process?

### ISSUE THREAD

**Issue by mlinxiang** [onnx/onnx#1576]
i export a pytorch model to onnx, and export onnx model to tensorflow pb.  i find that pytorch use "NCHW" but tensorflow use "NHWC" order， when i use tensorflow quantization the converted pb， the channl has not match problem。 so， is there any config or other additional process?
![image](https://user-images.githubusercontent.com/6283983/47908969-7fe05080-dec9-11e8-9127-c19b422ba120.png)

**Comment by houseroad** [comment]
@fumihwh would you like to explain how it works?

**Comment by houseroad** [comment]
You can check how to use denotation in the TensorProto: https://github.com/onnx/onnx/blob/master/docs/DimensionDenotation.md

**Comment by askhade** [comment]
@mlinxiang  : Closing this issue now. Please reopen this or create a new one if you still have questions regarding this.
