### ISSUE TITLE
C# onnx protobuf won't write zero values for int Attributes 

### ISSUE THREAD

**Issue by cal58** [onnx/onnx#1581]
This causes some attributes to have no value, which in turn causes errors when checking if the model is valid.

Does anyone have experience with Protobuf who can suggest a fix or a work around?

**Comment by gramalingam** [comment]
Does the PR https://github.com/onnx/onnx/pull/1495 not fix this issue? For model producers, it is a good idea to set the "AttributeType type" field of an attribute … which should help the model consumer interpret the attribute accordingly.

**Comment by cal58** [comment]
I missed that - looks like it should fix it. Thanks :)
