### ISSUE TITLE
CI for IBM Power

### ISSUE THREAD

**Issue by tedhtchang** [onnx/onnx#1589]
Hi,
I am looking into creating CI that tests ONNX builds on IBM Power. We are hoping to achieve the following goals:
1. Run CI tests for PRs on IBM Power
2. Show build status/output/artifact on the ONNX Github README so community can see.
Is there any recommendation for us to achieve these goals?

**Comment by houseroad** [comment]
First we are open to support IBM Power in our CI. I am not aware any CI service providers support IBM Power arch. However you can still maintain your own CI machines and systems (e.g., jenkins).

cc: @bddppq @raymondxyang @zrphercule

**Comment by tedhtchang** [comment]
@houseroad For the provider, we plan to request Powerci access at OSUOSL who hosts Jenkins and IBM Power Systems. We can create Jenkins jobs to build ONNX there.

**Comment by prasanthpul** [comment]
Is there a CI now for this?
