### ISSUE TITLE
Trying to build from source for use with C++

### ISSUE THREAD

**Issue by Valentin4869** [onnx/onnx#1592]
I'm trying to build the source on Ubuntu 16.04 to parse models in a C++ application. I'm getting the following errors when I try to compile an empty program that includes the headers `onnx/onnx_pb.h `and `onnx/proto_utils.h`:

`In file included from test.cpp:3:0:
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:38:65: error: ‘AttributeProto’ does not name a type
 template<typename T> inline std::vector<T> RetrieveValues(const AttributeProto& attr);
                                                                 ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:39:61: error: ‘AttributeProto’ does not name a type
 template<> inline std::vector<int64_t> RetrieveValues(const AttributeProto& attr) {
                                                             ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h: In function ‘std::vector<_RealType> ONNX_NAMESPACE::RetrieveValues(const int&) [with T = long int]’:
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:40:16: error: request for member ‘ints’ in ‘attr’, which is of non-class type ‘const int’
   return {attr.ints().begin(), attr.ints().end()};
                ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:40:37: error: request for member ‘ints’ in ‘attr’, which is of non-class type ‘const int’
   return {attr.ints().begin(), attr.ints().end()};
                                     ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:40:49: error: could not convert ‘{<expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<long int>’
   return {attr.ints().begin(), attr.ints().end()};
                                                 ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h: At global scope:
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:43:65: error: ‘AttributeProto’ does not name a type
 template<> inline std::vector<std::string> RetrieveValues(const AttributeProto& attr) {
                                                                 ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h: In function ‘std::vector<_RealType> ONNX_NAMESPACE::RetrieveValues(const int&) [with T = std::__cxx11::basic_string<char>]’:
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:44:17: error: request for member ‘strings’ in ‘attr’, which is of non-class type ‘const int’
   return { attr.strings().begin(), attr.strings().end() };
                 ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:44:41: error: request for member ‘strings’ in ‘attr’, which is of non-class type ‘const int’
   return { attr.strings().begin(), attr.strings().end() };
                                         ^
/home/m/Downloads/onnx-master (2)/onnx/proto_utils.h:44:57: error: could not convert ‘{<expression error>, <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<std::__cxx11::basic_string<char> >’
   return { attr.strings().begin(), attr.strings().end() };
`

Any idea what the issue is and how to fix it?

I basically built the code and then copied the files to the onnx directory so it can find `onnx.pb.h`. I'm not sure if this was the right way to do it.

+ I'm thinking the default protobuf src it's using is too old? I tried pointing it to the most recent version (downloaded src and -I"newprotobuf"), but same issue. Does it use some kind of environment variable for finding the protobuf directory?

**Comment by yuslepukhin** [comment]
Is your compiler being able to find both protobuf headers and standard STL headers? The blob of C++ output is not very helpful w/o a context.

**Comment by WilliamTambellini** [comment]
I guess onnx cmake is still not checking if the version of protobuf is the expected one(s) cf :
https://github.com/onnx/onnx/pull/1794
Have you checked you have used/are using a compatible version of pb ?

**Comment by yuslepukhin** [comment]
@WilliamTambellini I have commented on that PR. 2.6.1 is a great choice when you have it built locally from source, otherwise one does not know what they are getting.

**Comment by yuslepukhin** [comment]
Please, re-open if still relevant. I am closing this.
