### ISSUE TITLE
onnx as external project in cmake

### ISSUE THREAD

**Issue by edsDev** [onnx/onnx#1602]
Hi, I'm trying to include onnx as an external project with ExternalProject_Add in cmake. However, it seems impossible to use a protobuf compiler which is also compiled and generated in the same project as cmake always fails to find protoc when configuring because it is simply not there yet. Of course, I could include onnx using add_subdirectory, but I'm just wondering is there a better solution?

**Comment by snnn** [comment]
Please use 'add_subdirectory' instead.

**Comment by edsDev** [comment]
The problem is that ExternalProject_Add wouldn't actually build protobuf until building phase. However, onnx fails to configure because absence of protoc compiler. At last, I decided to use execute_process to invoke another cmake instance to build them and solved the dependency manually. Thanks.
By the way, I'm cross compiling onnx library for Android and ending up getting the error 'cannot modify file onnx/lib/.ninja_deps'. Actually, the onnx library compiles and not until installing onnxifi that cmake errs. It works if I comment onnxifi away.
Here is the steps I build the library:
Platform: Windows 10
Android SDK: 27

- Build protobuf without binary
- Copy a pre-built protoc binary into protobuf installation directory (./bin)
- Build onnx with CMAKE_PREFIX_PATH set to protobuf installation path

**Comment by Timonsc** [comment]
Did you succeed in crosscompiling onnx for android? I am trying that without success so far.

**Comment by edsDev** [comment]
> Did you succeed in crosscompiling onnx for android? I am trying that without success so far.

I did successfully make onnx library work in Android by tweaking some CMake options (maybe by removing onnxifi). But as the original project is no longer accessible for me, I'm sorry I can't provide you with further details.

**Comment by linkerzhang** [comment]
@daquexian any suggestion here please?

**Comment by daquexian** [comment]
@Timonsc 

Here is cmake code I used for [DNNLibrary](https://github.com/JDAI-CV/DNNLibrary) (An Android NNAPI Wrapper). You should firstly build protoc for host and set the variable `DNN_CUSTOM_PROTOC_EXECUTABLE` accordingly

```cmake
option(protobuf_BUILD_TESTS "" OFF)
option(protobuf_BUILD_EXAMPLES "" OFF)
if (${CMAKE_SYSTEM_NAME} STREQUAL "Android")
    option(protobuf_BUILD_PROTOC_BINARIES "" OFF)
else()
    option(protobuf_BUILD_PROTOC_BINARIES "" ON)
endif()
add_subdirectory(${PROJECT_SOURCE_DIR}/third_party/protobuf/cmake)
set(ONNX_BUILD_MAIN_LIB ON)
if (${CMAKE_SYSTEM_NAME} STREQUAL "Android" AND NOT EXISTS ${DNN_CUSTOM_PROTOC_EXECUTABLE})
    message(FATAL ERROR "DNN_CUSTOM_PROTOC_EXECUTABLE is not set or wrong.")
endif()
set(ONNX_CUSTOM_PROTOC_EXECUTABLE ${DNN_CUSTOM_PROTOC_EXECUTABLE})
option(ONNX_USE_LITE_PROTO "" ON)
add_subdirectory(${PROJECT_SOURCE_DIR}/third_party/onnx)
target_compile_definitions(onnx_proto PRIVATE ONNX_BUILD_MAIN_LIB)

```

**Comment by yuslepukhin** [comment]
@edsDev Does the solution above work for you?

**Comment by edsDev** [comment]
@yuslepukhin As mentioned above, because I'm no longer accessible to the code and working something on onnx, I'm sorry I can't respond you with useful information. I'll close the issue.
