### ISSUE TITLE
third_party/onnx/CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.obj:onnxifi_wrapper.c:(.text+0x347): undefined reference to `InitOnceExecuteOnce' when building with MinGW-w64

### ISSUE THREAD

**Issue by KOLANICH** [onnx/onnx#1604]

**Comment by KOLANICH** [comment]
>What's you OS version

Windows 7, 32 bit

>compiler version

MinGW-w64 8.1

>On Windows, why don't you use VC instead?

VC is bundled with telemetry, commercial, proprietary and  ... considered as generating slower code than gcc (once I was very surprised when changing compiler from MSVC to gcc has speeded up one of my apps in C++ from 15 minutes to 10 seconds, but this may be a result of combination of all the factors - I has also changed OS (Windows -> Kubuntu) and bitness (32 -> 64) and stdlib (msvc -> glibc++), so CPU registers were better utilized ).

**Comment by KOLANICH** [comment]
>If GCC can speedup your code by 90 times, we definitely need to report a BUG to the VC team. I never saw such things before.

To be honest - this had happenned several years ago, then I have stopped using VS, so IDK how good it is now. Since that app heavily used c++ cointainers, I guess the problems may be in the stdlib, but I have not tested that (the obvious test is to build with clang and to link against VS and GNU stdlibs and measure the difference).

>InitOnceExecuteOnce function is available on your system, but did you set _WIN32_WINNT properly ?

It should be available, but I'm not sure if it is available in MinGW-w64 (MinGW links stdlib not against the dll in the system (if it did this way, this would have caused inability to run the app on a machine with a different version of the dll), but against an own file).

**Comment by snnn** [comment]
InitOnceExecuteOnce  is part of the windows API, not C/C++ stdlib.
