### ISSUE TITLE
ConvTranspose auto_pad spec contradiction?

### ISSUE THREAD

**Issue by BowenBao** [onnx/onnx#1609]
In operators documentation, ConvTranpose states that 

> output_shape can also be explicitly specified in which case pads values are auto generated using these equations:
> 
> total_padding[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + kernel_shape[i] - output_shape[i]
> **If (auto_pads != SAME_UPPER): pads[start_i] = total_padding[i]/2; pads[end_i] = total_padding[i] - (total_padding[i]/2)**
> **Else: pads[start_i] = total_padding[i] - (total_padding[i]/2); pads[end_i] = (total_padding[i]/2).**

which is to pad extra at upper when auto_pads is _NOT_ SAME_UPPER, however in

> auto_pad : string (default is NOTSET)
> auto_pad must be either NOTSET, SAME_UPPER, SAME_LOWER or VALID. Where default value is NOTSET, which means explicit padding is used. SAME_UPPER or SAME_LOWER mean pad the input so that the output size match the input.In case of odd number **add the extra padding at the end for SAME_UPPER** and at the beginning for SAME_LOWER. VALID mean no padding. DEPRECATION NOTE: auto_pad is only intended to support legacy uses, and for framework authors, one is explicitly encouraged to use explicit padding specified in the pads attribute.

the spec says to pad extra at upper when auto_pads is SAME_UPPER.

**Comment by linkerzhang** [comment]
Thank you! Good catch! The formula should be fixed. Do you want to send a PR for it please?

**Comment by jcwchen** [comment]
It should be resolved by https://github.com/onnx/onnx/pull/3440. Thanks!
