### ISSUE TITLE
numpy.setdiff1d or tf.setdiff1d equivalence

### ISSUE THREAD

**Issue by pengwa** [onnx/onnx#1613]
>>> a = np.array([1, 2, 3, 2, 4, 1])
>>> b = np.array([3, 4, 5, 6])
>>> np.setdiff1d(a, b)
array([1, 2])

there is no direct op for sure, is there any clue we build with a onnx graph using existing node?

**Comment by ebarsoum** [comment]
You might be able to do it with TopK for sorting, Unique to remove duplicate, and Scan to iterate through both list. Can you share which model need setdiff1?
