### ISSUE TITLE
About onnx tutorial

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [onnx/onnx#1618]
Recently, I read some code which used onnx.helper module to build a graph.Then I search repo for this module and find [this](https://github.com/onnx/onnx/blob/master/onnx/examples/Protobufs.ipynb) .Could you give me some official docs about all kind of onnx modules for using onnx better,more than model convertion.
Or whether I  miss something important  in the repo?

**Comment by MoonBunnyZZZ** [comment]
> Recently, I read some code which used onnx.helper module to build a graph.Then I search repo for this module(find this [).Could](urlhttps://github.com/onnx/onnx/blob/master/onnx/examples/Protobufs.ipynb) you give me some official docs about all kind of onnx modules for using onnx better,more than model convertion.
> Or whether I miss something important in the repo?

**Comment by houseroad** [comment]
We have a separate repo for tutorials: https://github.com/onnx/tutorials

Also, please check useful resources here: https://github.com/onnx/onnx/#learn-about-onnx-spec
