### ISSUE TITLE
Several version onnx do not work

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [onnx/onnx#1620]
First using 'conda install -c conda-forge onnx,thre onnx version is 1.1.2'.When using onnx.check.check_model:

>   File "/home/moon/miniconda3/envs/2/lib/python2.7/site-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input index 3 must be set to consumed for operator BatchNormalization
==> Context: Bad node spec: input: "001_convolutional" input: "001_convolutional_bn_scale" input: "001_convolutional_bn_bias" input: "001_convolutional_bn_mean" input: "001_convolutional_bn_var" output: "001_convolutional_bn" name: "001_convolutional_bn" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "momentum" f: 0.99 type: FLOAT }

Then using 'conda install -c conda-forge protobuf numpy,pip install onnx',th error is :

>  │>>> import onnx
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "onnx/__init__.py", line 6, in <module>
    from .onnx_pb import *  # noqa
ImportError: No module named onnx_pb

I also try  installing from source 1.3.0.

> git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install

the error is :

>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/moon/miniconda3/envs/2.7/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/home/moon/miniconda3/envs/2.7/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/moon/miniconda3/envs/2.7/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/moon/miniconda3/envs/2.7/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

source 1.2.2 also tried,error is :

> subprocess.CalledProcessError: Command '[u'/usr/bin/cmake', u'--build', '.', u'--', u'-j', '4']' returned non-zero exit status 2

@huitseeker @ezyang @shinh @dougalsutherland

**Comment by yuslepukhin** [comment]
There has been a number of issues on this. This is related to a mistmatch of protoc version and a libprotobuf version. If the compiler is newer it generates references to the symbols not present in the library. Make sure that they are of the same version.
