### ISSUE TITLE
cannot find pybind while installing onnx master 

### ISSUE THREAD

**Issue by hanzhaogang** [onnx/onnx#1624]
**context:**
win7, miniConda3
**Error:**

    `CMake Warning at CMakeLists.txt:353 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.

      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:

        pybind11Config.cmake
        pybind11-config.cmake

      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.

    CMake Error at CMakeLists.txt:362 (message):
      cannot find pybind`

I have installed the pybind11 master branch. But still hit this error. I tried to find thoes two files but failed.
Can anyone advise?

**Comment by hanzhaogang** [comment]
see this link: [1](https://github.com/pybind/pybind11/issues/1379)

**Comment by blokhin** [comment]
Still an issue for me, as I'm not a `conda` user 😢

**Comment by jiapei100** [comment]
**pybind11** has **ALREADY** been successfully installed by `pip install --user pybind11` . There is **NO pybind11Config.cmake** at all. For **onnx**, `python setup.py build` brings me the following error:

```console
......
Generated: ....../onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: ....../onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
CMake Warning at CMakeLists.txt:402 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at CMakeLists.txt:411 (message):
  cannot find pybind
```

**Comment by pranv12** [comment]
> Still an issue for me, as I'm not a `conda` user

I'm also having same issue. Did you solved your problem?

**Comment by pvnieo** [comment]
I'm having the same issue. I'm not a conda user.

**Comment by blokhin** [comment]
@pranv12 @pvnieo see https://github.com/pybind/pybind11/issues/1379#issuecomment-623709112

**Comment by Joffreybvn** [comment]
I had this issue while trying to build ONNX locally within a virtualenv. Solved this way:

### Be sure to have Cmake:
`sudo snap install cmake --classic`

### Clone, build and install
1. Clone the repo:
```
git clone https://github.com/pybind/pybind11.git 
cd pybind11 
mkdir build 
cd build 
```
2. Set the python virtualenv you use with Onnx
With pyenv: `pyenv local 3.8.x`
3. Build
```
cmake .. 
sudo make install
```

Pybind is installed for Python 3.8 in `/usr/local/include/pybind11`

**Comment by caleb-depotanalytics** [comment]
building onnxruntime with vitisai on ZCU102 also still fails due to this
