### ISSUE TITLE
CMake Error Could NOT find PythonLibs While building ONNX on windows7

### ISSUE THREAD

**Issue by hanzhaogang** [onnx/onnx#1625]
-- Found PythonLibs: C:/ProgramData/Miniconda3/libs/Python36.lib
  -- Found PythonInterp: C:/ProgramData/Miniconda3/python.exe (found suitable ve
rsion "3.6.6", minimum required is "3.6")
  CMake Error at C:/ProgramData/Miniconda3/Lib/site-packages/cmake/data/share/cm
ake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
    Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found suitable
    version "3.6.6", minimum required is "3.6")
  Call Stack (most recent call first):
    C:/ProgramData/Miniconda3/Lib/site-packages/cmake/data/share/cmake-3.12/Modu
les/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    C:/ProgramData/Miniconda3/Lib/site-packages/cmake/data/share/cmake-3.12/Modu
les/FindPythonLibs.cmake:265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    CMakeLists.txt:388 (find_package)

**Can updating python to 3.7 solve this issue?**

**Comment by hanzhaogang** [comment]
updated to python3.7, still hit the issue:

    -- Found PythonInterp: C:/Users/Administrator/AppData/Local/Programs/Python/
Python37/python.exe (found version "3.7.1")
    -- Found PythonLibs: C:/Users/Administrator/AppData/Local/Programs/Python/Py
thon37/libs/Python37.lib
    -- Found PythonInterp: C:/Users/Administrator/AppData/Local/Programs/Python/
Python37/python.exe (found suitable version "3.7.1", minimum required is "3.7")
    CMake Error at C:/Users/Administrator/AppData/Local/Programs/Python/Python37
/Lib/site-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandard
Args.cmake:137 (message):
      Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found suitable
      version "3.7.1", minimum required is "3.7")
    Call Stack (most recent call first):
      C:/Users/Administrator/AppData/Local/Programs/Python/Python37/Lib/site-pac
kages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:37
8 (_FPHSA_FAILURE_MESSAGE)
      C:/Users/Administrator/AppData/Local/Programs/Python/Python37/Lib/site-pac
kages/cmake/data/share/cmake-3.12/Modules/FindPythonLibs.cmake:265 (FIND_PACKAGE
_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:388 (find_package)


    -- Configuring incomplete, errors occurred!

**Comment by hanzhaogang** [comment]
solved.  this is the grammar of finding python packages for cmake 3.12 has changed. So we should change : 
    find_package(PythonInterp ${PY_VERSION} REQUIRED)
    find_package(PythonLibs ${PY_VERSION} REQUIRED)
into:
    find_package(Python ${PY_VERSION} REQUIRED)""

see this linkd: https://cmake.org/cmake/help/v3.12/module/FindPython.html](https://cmake.org/cmake/help/v3.12/module/FindPython.html)

the original answer for this issue can be fund at: [https://cmake.org/cmake/help/v3.12/module/FindPython.html](https://cmake.org/cmake/help/v3.12/module/FindPython.html)

**Comment by hanzhaogang** [comment]
I think we should add a if...else sentence to determine the cmake version in the cMakeList.txt. 
for old cmake version, we use  
find_package(PythonInterp ${PY_VERSION} REQUIRED)
find_package(PythonLibs ${PY_VERSION} REQUIRED)
for new version, we use:
find_package(Python ${PY_VERSION} REQUIRED)

**Comment by yuslepukhin** [comment]
@hanzhaogang Please, try following the most recent updated instructions for building on Windows.

**Comment by lunixbochs** [comment]
Can we revisit this? I think find_package(Python) is required to support the version of Python that ships with the latest Xcode.
