### ISSUE TITLE
Optimizer Framework

### ISSUE THREAD

**Issue by jeffsaremi** [onnx/onnx#1628]
Is there going to be an Optimizer framework where we could create our own passes and optimizations and plug them in?
I looked at onnx/optimizer/optimizer.h and it had this:
```
#include "onnx/common/stl_backports.h"
#include "onnx/optimizer/passes/eliminate_identity.h"
#include "onnx/optimizer/passes/eliminate_nop_transpose.h"
#include "onnx/optimizer/passes/fuse_consecutive_transposes.h"
#include "onnx/optimizer/passes/fuse_add_bias_into_conv.h"
#include "onnx/optimizer/passes/fuse_transpose_into_gemm.h"
#include "onnx/optimizer/passes/lift_lexical_references.h"
#include "onnx/optimizer/passes/nop.h"
#include "onnx/optimizer/passes/split.h"
```
This to me screams like "I am not a framework. Do NOT use me".

**Comment by ArmenAg** [comment]
Yes we do have an optimization framework. If you're interested in adding optimizations check out the [documentation](https://github.com/onnx/onnx/blob/master/docs/Optimizer.md). Also by your header it looks like you're using an older version of the code, there was a significant rewrite done for the optimization framework recently so please check out the master code.

**Comment by aisri** [comment]
What does this optimization **extract_constant_to_initializer** do ?

**Comment by houseroad** [comment]
I think it moves `Constant` node to initializer list.

**Comment by daquexian** [comment]
@aisri To eliminate the unnecessary manipulations in SSD-like models, try my [onnx-simplifier](https://github.com/daquexian/onnx-simplifier). 

The comparison: https://github.com/daquexian/onnx-simplifier/issues/3#issuecomment-491472946

**Comment by ruabuliuqiu** [comment]
> Wanted to add some points to the thread.
> When a framework exports model to ONNX, for some reason they introduce a lot of ugly transposes and reshapes which can lead to overhead during compute and may not be necessary at all.
> 
> Is there a plan to address such unnecessary reshape, transpose, & shape manipulations. I have seen such cases when exporting SSD based & Encoder Decoder based models.
> 
> How can we have a compact layer list circumventing such nasty operations.

hi，I don't know how to remove reshape and transpose nodes in onnx model. can you help me？This caused  that failed to convert onnx to caffe model.

**Comment by ruabuliuqiu** [comment]
> @aisri To eliminate the unnecessary manipulations in SSD-like models, try my [onnx-simplifier](https://github.com/daquexian/onnx-simplifier).
> 
> The comparison: [daquexian/onnx-simplifier#3 (comment)](https://github.com/daquexian/onnx-simplifier/issues/3#issuecomment-491472946)

我邮件跟您联系过，您的建议是在第一次导出onnx模型就去除reshape和transpose 操作，但我的网络里根本没这些操作啊，只是转出onnx时出现的，还卡着在，不知道怎么弄

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this issue, please raise an issue there. Thank you!
