### ISSUE TITLE
Combo Operators

### ISSUE THREAD

**Issue by jeffsaremi** [onnx/onnx#1629]
I was looking at the Optimizer code and saw some passes like these:
```
#include "onnx/optimizer/passes/fuse_add_bias_into_conv.h"
#include "onnx/optimizer/passes/fuse_transpose_into_gemm.h"
```
These are very specific versions of what I am looking for.
I want to "fuse" whatever operator that makes sense into an existing one. For example I should be able to fuse "Transpose" into any non-trivial Operator. However that to me requires a generic concept such as "Combination Operator" Where I have a main Operator and some "sub-Ops" following that.

I should also be able to extend this concept to "Inputs" to an Operator and not necessarily the output.

**Comment by ArmenAg** [comment]
I'm not sure I understand what you're saying. 

> I want to "fuse" whatever operator that makes sense into an existing one. For example I should be able to fuse "Transpose" into any non-trivial Operator. 

what _makes sense_ is defined by the user who is writing the pass. Without a deep understanding of the underlying semantics of the op, we can't do any form of optimization (not just fuse). 

Could you please provide an example of what you mean?

**Comment by jeffsaremi** [comment]
After careful review I'd like to pull this back.
