### ISSUE TITLE
Does onnx have a operator cerresponding to the proposal operator in Deformable-Convnets(Based on mxnet)

### ISSUE THREAD

**Issue by hanzhaogang** [onnx/onnx#1636]
I trained a model under Deformable-ConvNets(https://github.com/msracver/Deformable-ConvNets) which is based on mxnet. While trying to export it into onnx format, I hit this error: Cannot find custom operator proposal. (I guess that it is used for region proposal in the RPN layer.)

The proposal operator, which I confirmed that is a custom operator defined by the Deformable-ConvNets, is defined as a subclass of mxnet.operator.CustomOp.

the trackback:
D:>python onnx_conv_test.py
[14:15:48] C:\Jenkins\workspace\mxnet\mxnet\src\nnvm\legacy_json_util.cc:209: Lo
ading symbol saved by previous version v1.2.1. Attempting to upgrade...
Traceback (most recent call last):
File "onnx_conv_test.py", line 25, in
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], n
p.float32, onnx_file)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\mxnet\contrib\onnx\mx2onnx\export_model.py", line 75, in export_model
sym_obj, params_obj = load_module(sym, params)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\mxnet\contrib\onnx\mx2onnx_export_helper.py", line 58, in load_module
sym, arg_params, aux_params = mx.model.load_checkpoint(model_name, num_epoch
s)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\mxnet\model.py", line 437, in load_checkpoint
symbol = sym.load('%s-symbol.json' % prefix)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\mxnet\symbol\symbol.py", line 2620, in load
check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\mxnet\base.py", line 252, in check_call
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:15:48] C:\Jenkins\workspace\mxnet\mxnet\src\operator
custom\custom.cc:104: Check failed: CustomOperator::Get()->Find(params.op_type)
!= nullptr Cannot find custom operator proposal

Despite that it seems have nothing to do with onnx,  I wonder that is there a corresponding operator in onnx for the operator `proposal`?

**Comment by Zehaos** [comment]
Still in progress... #1010
