### ISSUE TITLE
Onnx Model Checker fails when model has interpolate layer on pytorch 1.0

### ISSUE THREAD

**Issue by achigeor** [onnx/onnx#1638]
# Enviroment

- Ubuntu 18.04
- python 2.7.15
- pytorch-nightly-cpu       1.0.0.dev20181119     py2.7_cpu_0 
- onnx == 1.3.0

# Issue
After pytorch 0.4 nn.Upsample was deprecated and we use nn.functional.interpolate instead. 

On pytorch 1.0, while I can convert a model with an interpolate layer in it, I get the following error when running
`onnx.checker.check_model(onnx_model)`:
```
File "/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/onnx/checker.py", line 82, in check_model`
`    C.check_model(model.SerializeToString())`
`onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].
```
`
==> Context: Bad node spec: input: "input" input: "3" output: "4" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING } doc_string: "/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/nn/functional.py(2164): interpolate\ntest2.py(18): forward\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/nn/modules/module.py(467): _slow_forward\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/nn/modules/module.py(477): __call__\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/jit/__init__.py(225): forward\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/nn/modules/module.py(479): __call__\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/jit/__init__.py(172): get_trace_graph\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/onnx/utils.py(192): _trace_and_get_graph_from_model\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/onnx/utils.py(224): _model_to_graph\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/onnx/utils.py(281): _export\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/onnx/utils.py(104): export\n/home/anaconda2/envs/pytorch_0.1/lib/python2.7/site-packages/torch/onnx/__init__.py(27): export\ntest2.py(34): <module>\n"
`
# Question

On pytorch 0.4.1 the snippet below works properly. Is it possible to make it run using pytorch 1.0, and if yes how?

Thanks!

# Minimal Example to reproduce
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx`

class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        x = F.interpolate(x, scale_factor=2, mode='nearest')
        return x

torch_model = TestModel()
dummy_input = torch.randn(1, 3, 256, 256)

torch_out = torch.onnx.export(torch_model, dummy_input, 'test_model.onnx', verbose=True)

onnx_model = onnx.load('test_model.onnx')
print onnx_model
onnx.checker.check_model(onnx_model)
```

**Comment by lyuwenyu** [comment]
I have the same problem. Have you solve it ?

**Comment by achigeor** [comment]
@lyuwenyu Nope :/

**Comment by achigeor** [comment]
Issue still exists in latest stable release of pytorch 1.0 (installed from conda - not source)

**Comment by xxradon** [comment]
@achigeor @lyuwenyu  EveryOne,I think I got a way to handle this bug,change the code https://github.com/onnx/onnx/blob/f612532843bd8e24efeab2815e45b436479cc9ab/onnx/defs/tensor/defs.cc#L1179

`if (!hasNInputShapes(ctx, 1))`
to 
`if (!hasNInputShapes(ctx, 2))`.
And rebuild the onnx and install ,then you will find "onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1]." error can be fixed.
Tips,before you install the onnx,you should use pip uninstall onnx.

**Comment by spandantiwari** [comment]
@achigeor - we have recently fixed issues related to upsample/interpolate in PyTorch ONNX exporter. I think the issue you are seeing is fixed too. I have tested it with latest PyTorch and it passes the checker. Could you please try the latest nightly build (`conda install pytorch-nightly-cpu -c pytorch`) and see if it eliminates this issue. If you still see it, please let us know. For now, we will close this issue.

**Comment by achigeor** [comment]
@spandantiwari Thanks for the heads-up! Will try the latest nightly :)
