### ISSUE TITLE
How do you read a model with onnx format in a C++ application? Is there some documentation on it?

### ISSUE THREAD

**Issue by Con-Mi** [onnx/onnx#1641]

**Comment by harrysummer** [comment]
The content of ONNX file is just a ProtoBuf message. You can load it by initializing an `onnx::ModelProto`, and then use `ParseFrom...` interface of Protobuf to load the model.

**Comment by Con-Mi** [comment]
Do you have example code I can take a look at?

**Comment by harrysummer** [comment]
Didn't test it but should be like:
```c++
#include "onnx_pb.h"
...
onnx::ModelProto model;
std::ifsteam in(filename, std::ios_base::binary);
model.ParseFromIstream(&in);
in.close();
```
