### ISSUE TITLE
Node, Tensor, and Input names

### ISSUE THREAD

**Issue by ardorem** [onnx/onnx#1644]
Hi, I was trying to traverse the ONNX graph and wondered if the TensorProto and InputProto names are unique for a graph. I noticed that NodeProto names are not actually unique when converted from Keras. Is there a documentation that clarifies the naming rules of different tiers of Protos in ONNX graph? Thanks for reading and your help!

**Comment by linkerzhang** [comment]
TensorProto names must be unique, if it's not the case, there should be a model bug. NodeProto names might be unique too, however, it's not required to always have a node name (it means nodeproto may not have name).

**Comment by newling** [comment]
From the spec (IR.md), on TensorProto names

> The graph MUST use single static assignment for all node outputs, which means that all node output names MUST be unique within a graph. In the case of a nested subgraph, a node output name MUST be distinct from the names from the outer scopes that are visible in the nested subgraph
