### ISSUE TITLE
replace dynamic shape with fixed shape like (1, 3, 244,244)

### ISSUE THREAD

**Issue by whitelok** [onnx/onnx#1645]
When I convert onnx to caffe, the Dynamic input shape of Concat is really a problem.
Caffe need a fixed input shape each layer.

  %387 : Dynamic = onnx::Unsqueeze[axes=[0]](%384), scope: RefineSSD
  %388 : Dynamic = onnx::Unsqueeze[axes=[0]](%385), scope: RefineSSD
  %389 : Dynamic = onnx::Unsqueeze[axes=[0]](%386), scope: RefineSSD
  %390 : Dynamic = onnx::Concat[axis=0](%387, %388, %389), scope: RefineSSD

Is there any method for me to get the actually input shape of Concat or replace Dynamic with actually shape ? 

P.S. the graph input shape is fixed (1, 3, 244,244).

**Comment by whitelok** [comment]
@houseroad

**Comment by prasanthpul** [comment]
Please reopen if it's still an issue
