### ISSUE TITLE
New Operators Request List

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#1646]
We are maintaining a list to track the requests for new operators. Please post your request here.

- [ ] Less or equal than (https://github.com/onnx/onnx/issues/870)
- [ ] Greater or equal than (https://github.com/onnx/onnx/issues/870)
- [ ] CELU (https://github.com/onnx/onnx/issues/1121)
- [ ] FFT (https://github.com/onnx/onnx/issues/298)
- [ ] RFFT (https://github.com/onnx/onnx/issues/298)
- [ ] IFFT (https://github.com/onnx/onnx/issues/298)
- [ ] IRFFT (https://github.com/onnx/onnx/issues/298)
- [ ] DCT (https://github.com/onnx/onnx/issues/298)
- [ ] IDCT (https://github.com/onnx/onnx/issues/298)

**Comment by michael200892458** [comment]
BBoxTransform
RoIAlign
BBoxTransform
BoxWithNMSLimit
GenerateProposals
CopyCPUToGPU
CopyGPUToCPU
ResizeNearest

the above operators is not support

**Comment by prasanthpul** [comment]
RoiAlign is here: https://github.com/onnx/onnx/pull/1869

**Comment by linkerzhang** [comment]
ResizeNearest is here: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize.

**Comment by linkerzhang** [comment]
I'll put a question mark on whether we need CopyCPUToGPU and CopyGPUToCPU, which may be taken as a runtime implementation detail, instead of a model representation requirement.

**Comment by gramalingam** [comment]
Agree, we shouldn't have CopyCPUtoGPU or CopyGPUToCPU. They are runtime implementation concerns.

**Comment by fuzzyBatman** [comment]
[CropAndResize](https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize) (tensorflow)

Current work
- Issue #2100 
- PR #2102

**Comment by fuzzyBatman** [comment]
[InvertPermutation](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/invert-permutation) (tensorflow)

**Comment by jeremycochoy** [comment]
Is anyone working on FFT/IFFT/RFFT/IRFFT? I'd be happy to add them otherwise.

**Comment by garymm** [comment]
Fourier transform (signal) ops are tracked by #3573.
All the other ops from the original list were added at some point. I don't think this issue is useful anymore so closing.
