### ISSUE TITLE
Invalid linkage for tests on MSVC build

### ISSUE THREAD

**Issue by voidcycles** [onnx/onnx#1652]
When building from master and the latest rel-1.3.0 tag, it appears there's an invalid config for building the tests and benchmarks on the MSVC build.  The gtest.lib appears to be statically linked, but the test requires dynamic linkage:

Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in function_get_test.obj	onnx_gtests	...\onnx\repo\build\gtest.lib(gtest-all.obj)	1

**Comment by askhade** [comment]
@voidcycles : Are you still facing this issue? Can you add more details regarding how you are building this? Alternatively can you check the build instructions here : https://github.com/onnx/onnx#source
to see if they resolve your issue.

**Comment by yuslepukhin** [comment]
Closing. Please, re-open if necessary.

**Comment by alinpahontu2912** [comment]
Hey @yuslepukhin, I have encountered the same issue while trying to build pytorch static libraries from source. To reproduce, build pytorch or libtorch ([instructions here](https://github.com/pytorch/pytorch)) and set BUILD_SHARED_LIBS=OFF and set CMAKE_BUILD_TYPE to Release or MinSizeRel.
