### ISSUE TITLE
raise error in TensorRT

### ISSUE THREAD

**Issue by wlgcqh** [onnx/onnx#1657]
/home/beiqi.qh/workplace/tensor_rt/code-samples/posts/TensorRT-introduction/onnx/libonnx_proto.a(onnx.pb.cc.o): In function `onnx::TypeProto::ByteSizeLong() const':
onnx.pb.cc:(.text+0x217): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
/home/beiqi.qh/workplace/tensor_rt/code-samples/posts/TensorRT-introduction/onnx/libonnx_proto.a(onnx.pb.cc.o): In function `onnx::OperatorSetIdProto::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
onnx.pb.cc:(.text+0x255): undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
onnx.pb.cc:(.text+0x26b): undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long, google::protobuf::io::CodedOutputStream*)'
/home/beiqi.qh/workplace/tensor_rt/code-samples/posts/TensorRT-introduction/onnx/libonnx_proto.a(onnx.pb.cc.o): In function `onnx::OperatorSetIdProto::ByteSizeLong() const':
onnx.pb.cc:(.text+0x2f8): undefined reference to `google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(google::protobuf::UnknownFieldSet const&)'
/home/beiqi.qh/workplace/tensor_rt/code-samples/posts/TensorRT-introduction/onnx/libonnx_proto.a(onnx.pb.cc.o): In function `onnx::AttributeProto::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
onnx.pb.cc:(.text+0x37a): undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloat(int, float, google::protobuf::io::CodedOutputStream*)'
onnx.pb.cc:(.text+0x3a9): undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long, google::protobuf::io::CodedOutputStream*)'
onnx.pb.cc:(.text+0x3d9): undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::string const&, google::protobuf::io::CodedOutputStream*)'

**Comment by prasanthpul** [comment]
It's not clear this is an issue in ONNX. Please file the issue with TensorRT as the problem seems specific to their implementation
