### ISSUE TITLE
Specifications for SVMClassifier is not precise enough

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#1661]
There are N columns  for N classes if the operators output probabilities but if N > 2. What happens when the operator outputs raw scores for N(N-1)/2 support vectors? libsvm returns N(N-1)/2 columns, scikit-learn normalizes the scores to get N columns. The spec should choose one behavior or add a parameter to specify which one is expected.

**Comment by prasanthpul** [comment]
@xadupre Can you submit a PR for how you believe this should be?

**Comment by xadupre** [comment]
Since scikit-learn still has a bug about the way it normalizes outputs (probably being fixed by this PR https://github.com/scikit-learn/scikit-learn/pull/10440 but still not merged), I suggest keeping the normalization of scikit-learn out of the scope of the function and specifying the dimension of the outputs is different if parameter prob_a is filled. Is that ok for you?
