### ISSUE TITLE
Operators: Det, Log Det

### ISSUE THREAD

**Issue by will-rice** [onnx/onnx#1671]
Important in probabilistic models. Already in Pytorch and Tensorflow.

**Comment by will-rice** [comment]
Found a solution through ATen.
```@parse_args('v')
def logdet(g, self):
    return g.op("ATen", self)


@parse_args('v')
def det(g, self):
    return g.op("Aten", self)```

**Comment by ajaysg** [comment]
is there any way to implement logdet without ATen operator

**Comment by will-rice** [comment]
when I opened this issue I looked into it and didn't find anything. This has been a while though so there may be a way that I missed or wasn't available at the time. However, if you can modify the ATen files in pytorch to get an onnx model to export with logdet, but then getting it to other frameworks from onnx didn't work out since it wasn't directly supported in onnx.

**Comment by ajaysg** [comment]
My onnx model graph has ATen operator. when i try to convert that to tensorrt it throws an error like
No importer registered for op: ATen
what is the solution?

**Comment by ajaysg** [comment]
please tell how to write logdet function without ATen

**Comment by will-rice** [comment]
Yeah that’s what I was saying. I don’t think there is a good solution at this point unless you want to write the onnx part yourself. It looks like most pytorch (if not all) is ATen on the backend so you are stuck with ATen. To get around this we usually port a pytorch model to tensorflow for use in a production environment.

**Comment by ajaysg** [comment]
but porting a pytorch model to other frameworks is possible only through onnx? is there any other way
