### ISSUE TITLE
NopDropout elimination replaces mask usage by input

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1672]
In https://github.com/onnx/onnx/blob/ea694bf5cbccf34e08f36a8d9365d9011b72aeb4/onnx/optimizer/passes/eliminate_nop_dropout.h#L31 all outputs of the Dropout layer are replaced with inputs. However the 2nd output of that layer is `mask` which shall contain the mask. In the NoOp case this is all `1s` and NOT the input

**Comment by houseroad** [comment]
This is bug. We should check there is no second output.

**Comment by Flamefire** [comment]
> This is bug. We should check there is no second output.

Why is the mask output disallowed in this case? I'd expect it to be valid and simply filled with `1s`. Or did you mean that it can only be eliminated if there is NO mask output?

**Comment by houseroad** [comment]
Actually, both are correct handling.

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this issue, please raise an issue there. Thank you!
