### ISSUE TITLE
Why is training of ONNX models made impossible?

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1673]
It seems that for example in the Dropout Operator Version 7 the `is_test` attribute was removed without any further description in https://github.com/onnx/onnx/pull/1014

The converter states that the Dropout Operator cannot be used for training: https://github.com/onnx/onnx/blob/77dad845d41692f5a97622d7af40028b39e6b7fd/onnx/version_converter/adapters/dropout_6_7.h#L15 which is Odd as this is literally the only case where it is used (in test mode it does nothing)

So why was this done? Should it be really impossible to train an ONNX model? If not, why make it an error in the converter and not refer to something like "the backend specifies whether the network is run in training mode. if in test mode this Operator is run as-if `ratio=0`"

**Comment by houseroad** [comment]
First, it's not impossible. But a few features are missing. For example, we don't clear definition on the gradient ops, we don't support some attributes/outputs required by training. Some team from Chainer already started working on training using ONNX.

**Comment by Flamefire** [comment]
Ok can you then explain the above linked "Training is not supported with Dropout Op" introduced with Op version 7?

We ware working in a BMBF project which includes training of/with ONNX models.
