### ISSUE TITLE
Proposal: Semantic Correctness Checks

### ISSUE THREAD

**Issue by ArmenAg** [onnx/onnx#1677]
Currently in ONNX we have correctness checks over the graph specification which insures that the graph is well formed. This can be seen as a form of syntactic check, what are lacking are semantic checks. Even if the graph is well formed, semantically there might be error which we should warn the user about.

Let me give an example to clear up what I mean. Let's say we have the graph:

```
graph torch-jit-export (
  %x[FLOAT, 32x8]
) {
  %1 = Relu(%x)
  %2 = Div(%x, %1)
  return %2
}
```

From the point of ONNX this a perfectly okay graph (assuming the protobuf is well formed) but semantically this graph is highly problematic.  The Relu operator would cause us to divide by zero. This type of semantic check would be incredibly useful to ONNX users, and can proactively catch a lot of bugs.  Proactively capturing possible runtime errors isn't the only thing semantic checks can do. For example if the user has two linear dense transformations in a row most likely they forgot to include an activation function, since semantically this doesn't make sense. These small type of semantic checks would have saved me a lot of headaches especially for some of the more complicated/researchy things I've worked on.

So how do we implement this? Luckily all the tools needed are in or almost in master. In our rewrite of the optimization framework, we included the concept of immutable passes and most recently we've built out the ability to add high level annotations to ops. All that would be requires is to start writing immutable passes and change the checker to warn the user when we get semantic errors. Furthermore the existent of semantic checkers will pressure us to add a granular level of Op Annotation which in return would improve our optimization passes.

@houseroad @spandantiwari Thoughts?

**Comment by houseroad** [comment]
Such analysis should be pretty useful, and I also thought about it before. However, I didn't have enough cycle to convert the idea to real code. Instead of implementing them as optimization passes, I think we can implement them as optimization passes, but expose different APIs to our users. Because when running the optimizer, folks will expect the graph to be changed. However, for the analysis, they probably look for some reports and advices, but not changing their graph, because most likely we don't/cannot guarantee such analysis is complete and correct.

**Comment by houseroad** [comment]
Sounds good, I will review your annotation pr today or later this weekend.

**Comment by spandantiwari** [comment]
@ArmenAg  - Yes, this is a good idea. There are several such scenarios where this can be useful. @ArmenAg - as we discussed, overflows and other divide-by-zero situations could be folded in this. 

Yes, I also see this as an immutable pass, more akin to a "lint" type checker in spirit than optimization. I also agree with @houseroad that it's best to expose this as an API of its own. Ideally the output should be a report that, if needed, can be easily checked programmatically to see if any issues were found.
