### ISSUE TITLE
Extensibility of ONNX operators

### ISSUE THREAD

**Issue by imai-lm** [onnx/onnx#168]
I often add my own operators and expand frameworks (such as PyTorch) in my group. But in such cases, can't I export the models to ONNX? Or, is there a good way to create such extensible but ONNX-compliant model?
Quantization, for example, is not generally (nor officially) supported but becoming more and more in use these days. Can't I add such operators myself, or, should I propose each operator here individually and wait for being accepted as an official operator?

**Comment by ezyang** [comment]
We are working on a proposal for private extensions to operators in ONNX; it should be out later today.

**Comment by imai-lm** [comment]
That sounds good. I'll wait for it, and have a discussion afterwards.

**Comment by ezyang** [comment]
It's in https://github.com/onnx/onnx/pull/175; look at "Vendor extensions to operators"

**Comment by imai-lm** [comment]
Thanks, I read it. And I have one question:
> The list of vendor prefixes will be coordinated by 
> the ONNX standards team

So, is an original (i.e. non-approved) vendor prefix prohibited?  For example, suppose I added some original operator 'foo' to PyTorch and extended the exporter `torch.nn.export()` to produce the operator with a name such as 'PyTorchEx.Foo'... Is using the original prefix 'PyTorchEx' not allowed? 
Or, is there a good way to get a valid vendor prefix?

**Comment by ezyang** [comment]
Good question.  I think you'd have to grab yourself another prefix, e.g., `PyTorchImai.` for such extensions, but I'm open to other suggestions.

Another possibility is to go full Java with the namespace, so it's something like `org.pytorch` and then you'd just pick your own domain name for your namespace.

**Comment by imai-lm** [comment]
In the former case, do I have to ask your team to get some prefix name, and do you approve my application and put it into your prefix list?
If so, IMHO, it's easier for both of us to follow the Java namespacing convention; I don't have to consider the prefix name and apply it to you, and also you don't have to manage your list and (potentially many) applications.

**Comment by bonotake** [comment]
I'm the same person as @imai-lm. Sorry for confusing.
@ezyang  Please let me confirm my understanding; after all in v1.0, an operator vendor must define OperatorSet that is identified by (domain, op_version) pair, and put the same domain in NodeProto for the vendor's private operators. Is this correct?
And one question is, the naming convention of the vendor's domain is the same as that of domains in ModelProto, i.e. a reverse domain name such as `com.facebook.fair`?

**Comment by ezyang** [comment]
> after all in v1.0, an operator vendor must define OperatorSet that is identified by (domain, op_version) pair, and put the same domain in NodeProto for the vendor's private operators. Is this correct?

That's correct. So if you are NVIDIA and you've got some super fancy cudnn operators, you would add an `opset_import { domain = "com.nvidia", op_version = 1 }` to models that use it (where 1 is whatever version of the NVIDIA opset you wanted to use.)

> And one question is, the naming convention of the vendor's domain is the same as that of domains in ModelProto, i.e. a reverse domain name such as com.facebook.fair?

Yep, reverse domain name.

**Comment by ezyang** [comment]
Closing this issue as fixed, but feel free to ask more questions.
