### ISSUE TITLE
Generalizing Fuse MatMul and Add into GEMM pass

### ISSUE THREAD

**Issue by ArmenAg** [onnx/onnx#1682]
@vloncar @houseroad 

I recently was looking at a graph at work and saw a lot of MatMul + Add operations. Here's a sample image of what I'm talking about:

![image](https://user-images.githubusercontent.com/4429794/49622131-2f9f5700-f97d-11e8-8876-c50b40d146e7.png)

I tried running the new pass @vloncar added but it didn't work. The shape output of MatMul is **float32[32, 100]** and the Initializer in Add is **float32[100]**. 

Is the pass not applying because of this portion of the [code](https://github.com/onnx/onnx/blob/master/onnx/optimizer/passes/fuse_matmul_add_bias_into_gemm.h#L46)?
```
    if (orig_bias->node()->kind() != kConstant &&
        orig_bias->node()->kind() != kParam) {
      return false;
    }
```
If so why are we doing this?

**Comment by houseroad** [comment]
Interesting, could you provide some code snippet to let me reproduce the problem?

**Comment by ArmenAg** [comment]
Here's an end to end example that's not working:

I'm debugging this from my side as well, since this Op could bring down latency by a margin that's important to me.

```python
import torch.nn.functional as F
import torch.nn as nn
import torch.onnx
import torch

import onnx
from onnx import optimizer


class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.mat = nn.Parameter(torch.randn(100, 100, requires_grad=True))
        self.bias = nn.Parameter(torch.randn(100, requires_grad=True))

    def forward(self, x):
        x = x.view(-1, 100)
        return x @ self.mat + self.bias


dummy_input = torch.randn((32, 100))

torch.onnx.export(Model(), dummy_input, "test.onnx")
model = onnx.load("test.onnx")

model_opt = optimizer.optimize(model, ["fuse_matmul_add_bias_into_gemm"])
onnx.save(model_opt, "test_opt.onnx")
optimized_model = onnx.load("test_opt.onnx")

print(onnx.helper.printable_graph(model.graph))
print(onnx.helper.printable_graph(model_opt.graph))

```

**Comment by ArmenAg** [comment]
The culprit is the Reshape operator. There's no shape information saved after the reshape so this [line fails](https://github.com/onnx/onnx/blob/master/onnx/optimizer/passes/fuse_matmul_add_bias_into_gemm.h#L59):
```c++
if (static_cast<int64_t>(x_shape.size()) == 2 && x_shape[0].is_int)
```

@houseroad Is there a way we can propagate all shape information prior to doing optimization to insure we have the most amount of shape information possible?

**Comment by houseroad** [comment]
Yes, you can directly manipulate the protobuf, and add the shape information for the output of the reshape. That should enable the shape inference after reshape

**Comment by ArmenAg** [comment]
Do we have an automated way of filling in shape information for our graphs? Or do we solely rely on front-end exporters doing the job correctly?

**Comment by houseroad** [comment]
Unfortunately, no automated way... (Actually I didn't get the meaning of the automated). What we do is adding to ValueInfoProto to (value_info)[https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L265]. Actually, we can add a helper function in (helper.py)[https://github.com/onnx/onnx/blob/master/onnx/helper.py] to support this. Manipulating the proto is not fun for everyone.

**Comment by ArmenAg** [comment]
@houseroad 

This is a good segway into having canonicalization in our optimization framework. Before we run any pass we should canonicalize the graph. 

I can write a more detailed proposal later, but some basic things to do would be to infer shapes of the model using `shape_inference::InferShapes ` so we don't have to rely on the frontend exporters, exporting shape information (most don't by the way).  Some other things that we can do is bubble up cast operators through ShapeTransforms (as defines by OpAnnotationFlag) and that way we could have a more advanced cast fusion optimization (btw which is something I'll add later).

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this question, please raise an issue there. Thank you!

**Comment by boumedine-billal** [comment]
### matmul, add_bias --> gemm

I used this conversion, but sometimes it wasn't working, so I created this simple function to make sure the matmul add_bias was turned into a gem.



```
"""my  fuse_matmul_add_bias_into_gemm"""
def fuse_matmul_add_bias_into_gemm(model_proto):
    onnx_model = OnnxModel(model_proto)
    nodes = model_proto.graph.node

    
    """
    with open('Gemm\\Gemm.pickle', 'wb') as file:
    pickle.dump(node, file)  
    with open('Gemm\\Gemm.pickle', 'rb') as file:
    gemm_node_ = pickle.load(file) 
    import codecs
    pickled = codecs.encode(pickle.dumps(gemm_node_), "base64").decode()
    """
    
    # gemm_node base64
    base64 = ('gANjb25ueC5vbm54X21sX3Bi'
              'MgpOb2RlUHJvdG8KcQApUnEB'
              'fXECWAoAAABzZXJpYWxpemVk'
              'cQND\n1goWbW9kZWxfMi9kZW'
              '5zZV8yL1JlbHU6MAombW9kZW'
              'xfMi9vdXRwdXQvTWF0TXVsL1'
              'JlYWRWYXJp\nYWJsZU9wOjAK'
              'J21vZGVsXzIvb3V0cHV0L0Jp'
              'YXNBZGQvUmVhZFZhcmlhYmxl'
              'T3A6MBIYbW9kZWxf\nMi9vdX'
              'RwdXQvQmlhc0FkZDowGgxmdX'
              'NlZF9nZW1tXzEiBEdlbW0qDw'
              'oFYWxwaGEVAACAP6ABASoO\n'
              'CgRiZXRhFQAAgD+gAQEqDQoG'
              'dHJhbnNBGACgAQIqDQoGdHJh'
              'bnNCGACgAQJxBHNiLg==\n')
    
    gemm_node_ = pickle.loads(codecs.decode(base64.encode(), "base64"))
    
    '''
    print(gemm_node_)
    '''

    added_layers = []
    removed_layers = []    

    for node in nodes:
        if node.op_type == 'MatMul':
            matmul_node = node
            add_node = onnx_model.get_children(node)[0]
            
            x = matmul_node.input[0]
            w = matmul_node.input[1]
            b = add_node.input[1]
            y = add_node.output[0]
            
            gemm_node = deepcopy(gemm_node_)
            gemm_node.input[0]  = x
            gemm_node.input[1]  = w
            gemm_node.input[2]  = b
            gemm_node.output[0] = y
            
            # gemm_node.attribute[0] = 1
            # gemm_node.attribute[1] = 1
            # gemm_node.attribute[2] = 0
            # gemm_node.attribute[3] = 0
            
            gemm_node.name = ''
            
            removed_layers.append(matmul_node)
            removed_layers.append(add_node)
            added_layers.append(gemm_node)
    
    
    for removed_layer in removed_layers:
        model_proto.graph.node.remove(removed_layer)
        
    for added_layer in added_layers:
        model_proto.graph.node.append(added_layer)
        
    onnx_model.update_graph() 
          

def optimize_fp_model(model_path):
    check_model_extension(model_path)
    model_proto = onnx.load(model_path)
    
    '''
    Convert static batch to dynamic batch
    '''
    model_proto = convert_model_batch_to_dynamic(model_proto)
    
    '''
    Optimizer
    '''
    model_proto = onnxoptimizer.optimize(model_proto,
                                       [
                                        'fuse_bn_into_conv',
                                        'fuse_add_bias_into_conv',
                                        'fuse_pad_into_conv',
                                        'fuse_matmul_add_bias_into_gemm',
                                        'fuse_transpose_into_gemm',               '''<--- sometimes it wasn't working''
                                        'eliminate_nop_flatten',
                                        'eliminate_nop_pad',
                                        'eliminate_nop_transpose',
                                        'eliminate_unused_initializer',
                                        'eliminate_duplicate_initializer'
                                        ])
    '''
    new fuse_matmul_add_bias_into_gemm
    '''
    fuse_matmul_add_bias_into_gemm(model_proto)

    # Save optimized model
    model_name = model_path.split(".onnx")
    model_path = model_name[0] + "_optimized.onnx"
    onnx.save(model_proto, model_path)

    return model_path
```

**Comment by AnitaLiu98** [comment]
> ### matmul, add_bias --> gemm
> I used this conversion, but sometimes it wasn't working, so I created this simple function to make sure the matmul add_bias was turned into a gem.
> 
> ```
> """my  fuse_matmul_add_bias_into_gemm"""
> def fuse_matmul_add_bias_into_gemm(model_proto):
>     onnx_model = OnnxModel(model_proto)
>     nodes = model_proto.graph.node
> 
>     
>     """
>     with open('Gemm\\Gemm.pickle', 'wb') as file:
>     pickle.dump(node, file)  
>     with open('Gemm\\Gemm.pickle', 'rb') as file:
>     gemm_node_ = pickle.load(file) 
>     import codecs
>     pickled = codecs.encode(pickle.dumps(gemm_node_), "base64").decode()
>     """
>     
>     # gemm_node base64
>     base64 = ('gANjb25ueC5vbm54X21sX3Bi'
>               'MgpOb2RlUHJvdG8KcQApUnEB'
>               'fXECWAoAAABzZXJpYWxpemVk'
>               'cQND\n1goWbW9kZWxfMi9kZW'
>               '5zZV8yL1JlbHU6MAombW9kZW'
>               'xfMi9vdXRwdXQvTWF0TXVsL1'
>               'JlYWRWYXJp\nYWJsZU9wOjAK'
>               'J21vZGVsXzIvb3V0cHV0L0Jp'
>               'YXNBZGQvUmVhZFZhcmlhYmxl'
>               'T3A6MBIYbW9kZWxf\nMi9vdX'
>               'RwdXQvQmlhc0FkZDowGgxmdX'
>               'NlZF9nZW1tXzEiBEdlbW0qDw'
>               'oFYWxwaGEVAACAP6ABASoO\n'
>               'CgRiZXRhFQAAgD+gAQEqDQoG'
>               'dHJhbnNBGACgAQIqDQoGdHJh'
>               'bnNCGACgAQJxBHNiLg==\n')
>     
>     gemm_node_ = pickle.loads(codecs.decode(base64.encode(), "base64"))
>     
>     '''
>     print(gemm_node_)
>     '''
> 
>     added_layers = []
>     removed_layers = []    
> 
>     for node in nodes:
>         if node.op_type == 'MatMul':
>             matmul_node = node
>             add_node = onnx_model.get_children(node)[0]
>             
>             x = matmul_node.input[0]
>             w = matmul_node.input[1]
>             b = add_node.input[1]
>             y = add_node.output[0]
>             
>             gemm_node = deepcopy(gemm_node_)
>             gemm_node.input[0]  = x
>             gemm_node.input[1]  = w
>             gemm_node.input[2]  = b
>             gemm_node.output[0] = y
>             
>             # gemm_node.attribute[0] = 1
>             # gemm_node.attribute[1] = 1
>             # gemm_node.attribute[2] = 0
>             # gemm_node.attribute[3] = 0
>             
>             gemm_node.name = ''
>             
>             removed_layers.append(matmul_node)
>             removed_layers.append(add_node)
>             added_layers.append(gemm_node)
>     
>     
>     for removed_layer in removed_layers:
>         model_proto.graph.node.remove(removed_layer)
>         
>     for added_layer in added_layers:
>         model_proto.graph.node.append(added_layer)
>         
>     onnx_model.update_graph() 
>           
> 
> def optimize_fp_model(model_path):
>     check_model_extension(model_path)
>     model_proto = onnx.load(model_path)
>     
>     '''
>     Convert static batch to dynamic batch
>     '''
>     model_proto = convert_model_batch_to_dynamic(model_proto)
>     
>     '''
>     Optimizer
>     '''
>     model_proto = onnxoptimizer.optimize(model_proto,
>                                        [
>                                         'fuse_bn_into_conv',
>                                         'fuse_add_bias_into_conv',
>                                         'fuse_pad_into_conv',
>                                         'fuse_matmul_add_bias_into_gemm',  '''<--- sometimes it wasn't working''
>                                         'fuse_transpose_into_gemm',             
>                                         'eliminate_nop_flatten',
>                                         'eliminate_nop_pad',
>                                         'eliminate_nop_transpose',
>                                         'eliminate_unused_initializer',
>                                         'eliminate_duplicate_initializer'
>                                         ])
>     '''
>     new fuse_matmul_add_bias_into_gemm
>     '''
>     fuse_matmul_add_bias_into_gemm(model_proto)
> 
>     # Save optimized model
>     model_name = model_path.split(".onnx")
>     model_path = model_name[0] + "_optimized.onnx"
>     onnx.save(model_proto, model_path)
> 
>     return model_path
> ```

Thanks for your code. Could you please let me known what is OnnxModel class?
