### ISSUE TITLE
pytest segmentation fault

### ISSUE THREAD

**Issue by haohaibo** [onnx/onnx#1687]
I install onnx locally from source code master. And `python -c "import onnx"` works fine.
But `pytest` fails. Detailed below:
`pytest
/home/hhao/.local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.23) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.12, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /home/scratch.hhao_gpu/repos/github/onnx, inifile: setup.cfg
plugins: nbval-0.9.1
collected 1247 items                                                                                                                                                       

onnx/test/basic_test.py ....                                                                                                                                         [  0%]
onnx/test/checker_test.py .............                                                                                                                              [  1%]
onnx/test/elu_test.py .                                                                                                                                              [  1%]
onnx/test/helper_test.py .................F....                                                                                                                      [  3%]
onnx/test/numpy_helper_test.py ............                                                                                                                          [  4%]
onnx/test/optimizer_test.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                                                                              [  8%]
onnx/test/relu_test.py .                                                                                                                                             [  8%]
onnx/test/schema_test.py ...                                                                                                                                         [  9%]
onnx/test/shape_inference_test.py .................F........................FF.........F......F.............FF.FF............F....FFFFF.............F...........Segmentation fault (core dumped) `

**Comment by haohaibo** [comment]
Here I paste the error message. It seems that I can't `mport onnx.onnx_cpp2py_export.defs as C`
```
================================================================================== ERRORS ==================================================================================
_________________________________________________________________ ERROR collecting onnx/test/basic_test.py _________________________________________________________________
ImportError while importing test module '/home/scratch.hhao_gpu/repos/github/onnx/onnx/test/basic_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/local/lib/python2.7/site-packages/six-1.12.0-py2.7.egg/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
onnx/test/basic_test.py:6: in <module>
    from onnx import AttributeProto, NodeProto, GraphProto, ModelProto, TensorProto, IR_VERSION
onnx/__init__.py:11: in <module>
    import onnx.helper  # noqa
onnx/helper.py:13: in <module>
    import onnx.defs as defs
onnx/defs/__init__.py:7: in <module>
    import onnx.onnx_cpp2py_export.defs as C
E   ImportError: No module named onnx_cpp2py_export.defs
________________________________________________________________ ERROR collecting onnx/test/checker_test.py ________________________________________________________________
```

**Comment by lovettchris** [comment]
haohaibo your issue is different, according to the docs:

> Note that this command does not work from a source checkout directory; in this case you'll see:
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'
Change into another directory to fix this error.

**Comment by lovettchris** [comment]
houseroad, attached is the stack trace of the crash that I'm seeing with v1.5.0.

[stack.txt](https://github.com/onnx/onnx/files/3209692/stack.txt)

My repro is my [torch_importer_test.py](https://github.com/microsoft/ELL/blob/master/tools/importers/torch/test/torch_importer_test.py) on Python 3.6.7.  The crash repros when I revert to older versions of onnx, so I suspect it might be an incompatibility with newer versions of protobuf? (I'm on 3.7.1).

**Comment by lovettchris** [comment]
Here's a much simpler repro.  I created an PyToch model in memory and exported it to ONNX using torch.onnx.export, then when I try and load it with onnx.load, the load succeeds, but then on process shutdown I get a core dump saying:
```
*** Error in `python': free(): invalid pointer: 0x000055c3503336f8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f736f89f7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f736f8a837a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f736f8ac53c]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD2Ev+0x439)[0x7f7353b042b9]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD0Ev+0xa)[0x7f7353b0438a]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD2Ev+0x409)[0x7f7353b04289]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD0Ev+0xa)[0x7f7353b0438a]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD2Ev+0x409)[0x7f7353b04289]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD0Ev+0xa)[0x7f7353b0438a]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD2Ev+0x1dd)[0x7f7353b0405d]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/../../../../../libprotobuf.so.18(_ZN6google8protobuf14DynamicMessageD0Ev+0xa)[0x7f7353b0438a]
/root/miniconda3/envs/py36/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so(+0x22f31)[0x7f7353c66f31]
python(+0x1a499d)[0x55c34f41899d]
```
[model.zip](https://github.com/onnx/onnx/files/3214357/model.zip)
