### ISSUE TITLE
Couldn't parse integer: FLOAT

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#1691]
**Error**
```
google.protobuf.text_format.ParseError: 9:20 : Couldn't parse integer: FLOAT
``` 

**Repro**
```
from onnx import ModelProto
from google.protobuf import text_format
model = ModelProto()
with open('model.pbtxt') as f:
    text_format.Merge(f.read(), model)
```
```
ir_version: 3
graph {
  node {
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: FLOAT
        float_data: 1.0
        name: "one_tensor"
      }
      type: TENSOR
    }
  }
}
```

@bddppq looks like #1626 regressed this.

**Comment by bddppq** [comment]
protobuf text format has poor backward compatibility (e.g. renaming a field would also break old models serialized with text format). Could you change to use binary format?

**Comment by lutzroeder** [comment]
1) This is a breaking change to the ONNX `.proto` definition. The text parser only highlights the PR broke the protobuf contract. Since the protobuf needs to be deserialized successfully to check `ir_version` don't think there is even a workaround supporting two formats. The correct action from a standards and compatibility perspective would be to revert the change, deprecate the old field and introduce a new one.

2) If a breaking change is needed, changing this to `int` seems a bad design choice as neither tooling can interpret these values nor are they human readable. For example, `27` can now mean anything and there is no way to look up its meaning. If a breaking change is needed to make this extensible it should probably be changed to `string`. This way there would be at least some way to agree what it stands for instead of third parties making up numbers that could mean anything...

3) The file is from a user regression test for Netron. I can change the files but not sure about the users they came from.

**Comment by houseroad** [comment]
This is indeed a breaking change for pbtxt users (including Netron). I would recommend bumping up the ir_version.

**Comment by lutzroeder** [comment]
Bumping `ir_version` won't be enough. The file needs to be parsed to check the `ir_version` but existing files fail parse.

**Comment by prasanthpul** [comment]
@lutzroeder ONNX guarantees binary compatiblity but pbtxt is not supported. we'll update the documentation accordingly
