### ISSUE TITLE
docker image with python3?

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1693]
Hi,

I just downloaded the docker image 'onnx/onnx-docker:cpu' from docker hub, and I found it only has python2, there is no python3. I'm planning to add https://github.com/Microsoft/onnxruntime to https://ac2zoom.github.io/onnx-backend-scoreboard/, but this onnx runtime only supports python3.  Is it possible to create a python3 docker image and let onnx-backend-scoreboard use python3?

Thanks.

**Comment by houseroad** [comment]
Yes, that's doable, let me check the script which generates the docker image.

**Comment by snnn** [comment]
Very thanks!

**Comment by houseroad** [comment]
I didn't get time to work on that yet. Here is the script: https://github.com/houseroad/dockerfiles/blob/master/onnx-docker/onnx-docker-cpu/Dockerfile
Feel free to play with it if you want.
