### ISSUE TITLE
example in gather op spec is wrong

### ISSUE THREAD

**Issue by HectorSVC** [onnx/onnx#1708]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gather
Example 2: data = [ [1.0, 1.2, 1.9], [2.3, 3.4, 3.9], [4.5, 5.7, 5.9], ] indices = [ [0, 2], ] axis = 1, output = [ [ [1.0, 1.9], [2.3, 3.9], [4.5, 5.9], ], ]
for this example, the output shape should be [3, 1, 2] instead of [1, 3, 2], correct output = [ [ [1.0, 1.9]], [[2.3, 3.9]], [[4.5, 5.9], ], ]

**Comment by daquexian** [comment]
Fixed by #3040
