### ISSUE TITLE
How to transform pytotrch model to onnx model with opset 7?

### ISSUE THREAD

**Issue by zccyman** [onnx/onnx#1715]
I use pytorch1.0 to transform pytorch model to onnx model with opset 9, but tensorRT doesn't support opset 9 so far.

**Comment by houseroad** [comment]
We have version converter, please check https://github.com/onnx/onnx/blob/master/docs/OpsetVersionConverter.md

**Comment by zccyman** [comment]
@houseroad my code like this:
	original_model = onnx.load(inference_file)#opset9

	onnx.checker.check_model(original_model)
	print('The model is checked!')

	#opset9 -> opset7
	converted_model = version_converter.convert_version(original_model, 7)
	onnx.checker.check_model(converted_model)
	print('The model is checked!')

but run it, I get some errors:
graph(%0 : Float(1, 3, 224, 224)
      %1 : Float(64, 3, 11, 11)
      %2 : Float(64)
      %3 : Float(192, 64, 5, 5)
      %4 : Float(192)
      %5 : Float(384, 192, 3, 3)
      %6 : Float(384)
      %7 : Float(256, 384, 3, 3)
      %8 : Float(256)
      %9 : Float(256, 256, 3, 3)
      %10 : Float(256)
      %11 : Float(128, 9216)
      %12 : Float(128)
      %13 : Float(128, 128)
      %14 : Float(128)
      %15 : Float(2, 128)
      %16 : Float(2)) {
  %17 : Float(1, 64, 55, 55) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[11, 11], pads=[2, 2, 2, 2], strides=[4, 4]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %18 : Float(1, 64, 55, 55) = onnx::Relu(%17), scope: AlexNet/Sequential[features]/ReLU[1]
  %19 : Float(1, 64, 27, 27) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%18), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %20 : Float(1, 192, 27, 27) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%19, %3, %4), scope: AlexNet/Sequential[features]/Conv2d[3]
  %21 : Float(1, 192, 27, 27) = onnx::Relu(%20), scope: AlexNet/Sequential[features]/ReLU[4]
  %22 : Float(1, 192, 13, 13) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%21), scope: AlexNet/Sequential[features]/MaxPool2d[5]
  %23 : Float(1, 384, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%22, %5, %6), scope: AlexNet/Sequential[features]/Conv2d[6]
  %24 : Float(1, 384, 13, 13) = onnx::Relu(%23), scope: AlexNet/Sequential[features]/ReLU[7]
  %25 : Float(1, 256, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%24, %7, %8), scope: AlexNet/Sequential[features]/Conv2d[8]
  %26 : Float(1, 256, 13, 13) = onnx::Relu(%25), scope: AlexNet/Sequential[features]/ReLU[9]
  %27 : Float(1, 256, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%26, %9, %10), scope: AlexNet/Sequential[features]/Conv2d[10]
  %28 : Float(1, 256, 13, 13) = onnx::Relu(%27), scope: AlexNet/Sequential[features]/ReLU[11]
  %29 : Float(1, 256, 6, 6) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%28), scope: AlexNet/Sequential[features]/MaxPool2d[12]
  %30 : Long() = onnx::Constant[value={0}](), scope: AlexNet
  %31 : Tensor = onnx::Shape(%29), scope: AlexNet
  %32 : Long() = onnx::Gather[axis=0](%31, %30), scope: AlexNet
  %33 : Long() = onnx::Constant[value={9216}](), scope: AlexNet
  %34 : Tensor = onnx::Unsqueeze[axes=[0]](%32)
  %35 : Tensor = onnx::Unsqueeze[axes=[0]](%33)
  %36 : Tensor = onnx::Concat[axis=0](%34, %35)
  %37 : Float(1, 9216) = onnx::Reshape(%29, %36), scope: AlexNet
  %38 : Float(1, 9216), %39 : Tensor = onnx::Dropout[ratio=0.5](%37), scope: AlexNet/Sequential[classifier]/Dropout[0]
  %40 : Float(1, 128) = onnx::Gemm[alpha=1, beta=1, transB=1](%38, %11, %12), scope: AlexNet/Sequential[classifier]/Dropout[0]
  %41 : Float(1, 128) = onnx::Relu(%40), scope: AlexNet/Sequential[classifier]/ReLU[2]
  %42 : Float(1, 128), %43 : Tensor = onnx::Dropout[ratio=0.5](%41), scope: AlexNet/Sequential[classifier]/Dropout[3]
  %44 : Float(1, 128) = onnx::Gemm[alpha=1, beta=1, transB=1](%42, %13, %14), scope: AlexNet/Sequential[classifier]/Dropout[3]
  %45 : Float(1, 128) = onnx::Relu(%44), scope: AlexNet/Sequential[classifier]/ReLU[5]
  %46 : Float(1, 2) = onnx::Gemm[alpha=1, beta=1, transB=1](%45, %15, %16), scope: AlexNet/Sequential[classifier]/ReLU[5]
  return (%46);
}

The model is checked!
The model is checked!

(pytorch) h:\github\pytorch-inference\examples>cd h:\github\pytorch-inference\examples && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && D:\ProgramData\Anaconda3\envs\pytorch\python.exe c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 51121 h:\github\pytorch-inference\examples\transform_model.py "
graph(%0 : Float(1, 3, 224, 224)
      %1 : Float(64, 3, 11, 11)
      %2 : Float(64)
      %3 : Float(192, 64, 5, 5)
      %4 : Float(192)
      %5 : Float(384, 192, 3, 3)
      %6 : Float(384)
      %7 : Float(256, 384, 3, 3)
      %8 : Float(256)
      %9 : Float(256, 256, 3, 3)
      %10 : Float(256)
      %11 : Float(128, 9216)
      %12 : Float(128)
      %13 : Float(128, 128)
      %14 : Float(128)
      %15 : Float(2, 128)
      %16 : Float(2)) {
  %17 : Float(1, 64, 55, 55) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[11, 11], pads=[2, 2, 2, 2], strides=[4, 4]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %18 : Float(1, 64, 55, 55) = onnx::Relu(%17), scope: AlexNet/Sequential[features]/ReLU[1]
  %19 : Float(1, 64, 27, 27) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%18), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %20 : Float(1, 192, 27, 27) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%19, %3, %4), scope: AlexNet/Sequential[features]/Conv2d[3]
  %21 : Float(1, 192, 27, 27) = onnx::Relu(%20), scope: AlexNet/Sequential[features]/ReLU[4]
  %22 : Float(1, 192, 13, 13) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%21), scope: AlexNet/Sequential[features]/MaxPool2d[5]
  %23 : Float(1, 384, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%22, %5, %6), scope: AlexNet/Sequential[features]/Conv2d[6]
  %24 : Float(1, 384, 13, 13) = onnx::Relu(%23), scope: AlexNet/Sequential[features]/ReLU[7]
  %25 : Float(1, 256, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%24, %7, %8), scope: AlexNet/Sequential[features]/Conv2d[8]
  %26 : Float(1, 256, 13, 13) = onnx::Relu(%25), scope: AlexNet/Sequential[features]/ReLU[9]
  %27 : Float(1, 256, 13, 13) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%26, %9, %10), scope: AlexNet/Sequential[features]/Conv2d[10]
  %28 : Float(1, 256, 13, 13) = onnx::Relu(%27), scope: AlexNet/Sequential[features]/ReLU[11]
  %29 : Float(1, 256, 6, 6) = onnx::MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%28), scope: AlexNet/Sequential[features]/MaxPool2d[12]
  %30 : Long() = onnx::Constant[value={0}](), scope: AlexNet
  %31 : Tensor = onnx::Shape(%29), scope: AlexNet
  %32 : Long() = onnx::Gather[axis=0](%31, %30), scope: AlexNet
  %33 : Long() = onnx::Constant[value={9216}](), scope: AlexNet
  %34 : Tensor = onnx::Unsqueeze[axes=[0]](%32)
  %35 : Tensor = onnx::Unsqueeze[axes=[0]](%33)
  %36 : Tensor = onnx::Concat[axis=0](%34, %35)
  %37 : Float(1, 9216) = onnx::Reshape(%29, %36), scope: AlexNet
  %38 : Float(1, 9216), %39 : Tensor = onnx::Dropout[ratio=0.5](%37), scope: AlexNet/Sequential[classifier]/Dropout[0]
  %40 : Float(1, 128) = onnx::Gemm[alpha=1, beta=1, transB=1](%38, %11, %12), scope: AlexNet/Sequential[classifier]/Dropout[0]
  %41 : Float(1, 128) = onnx::Relu(%40), scope: AlexNet/Sequential[classifier]/ReLU[2]
  %42 : Float(1, 128), %43 : Tensor = onnx::Dropout[ratio=0.5](%41), scope: AlexNet/Sequential[classifier]/Dropout[3]
  %44 : Float(1, 128) = onnx::Gemm[alpha=1, beta=1, transB=1](%42, %13, %14), scope: AlexNet/Sequential[classifier]/Dropout[3]
  %45 : Float(1, 128) = onnx::Relu(%44), scope: AlexNet/Sequential[classifier]/ReLU[5]
  %46 : Float(1, 2) = onnx::Gemm[alpha=1, beta=1, transB=1](%45, %15, %16), scope: AlexNet/Sequential[classifier]/ReLU[5]
  return (%46);
}

The model is checked!
Traceback (most recent call last):
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\__main__.py", line 265, in main
    wait=args.wait)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\__main__.py", line 256, in handle_args
    run_main(addr, name, kind, *extra, **kwargs)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_local.py", line 52, in run_main
    runner(addr, name, kind == 'module', *extra, **kwargs)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\runner.py", line 32, in run
    set_trace=False)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 1283, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 1290, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "c:\Users\zccyman\.vscode\extensions\ms-python.python-2018.12.1\pythonFiles\lib\python\ptvsd\_vendored\pydevd\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "h:\github\pytorch-inference\examples\transform_model.py", line 95, in <module>
    transformModel_onnx(model_file, inference_file, tensor_size)
  File "h:\github\pytorch-inference\examples\transform_model.py", line 62, in transformModel_onnx
    converted_model = version_converter.convert_version(original_model, 7)
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\onnx-1.3.0-py3.5-win-amd64.egg\onnx\version_converter.py", line 166, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: H:\github\pytorch-inference\thirdparty\onnx\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For Constant

so I guess this converter doesn't support opset9 so for.

**Comment by Casablancaaa** [comment]
@zccyman have you fixed this issue?

**Comment by gemfield** [comment]
It also does not support PRelu (with onnx version 1.4.1):
```bash
Traceback (most recent call last):
  File "gemfield.py", line 12, in <module>
    converted_model = version_converter.convert_version(original_model, 7)
  File "/opt/conda/lib/python3.6/site-packages/onnx/version_converter.py", line 166, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /onnx/onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For PRelu
```

**Comment by shakkeel1330** [comment]
`RuntimeError: /onnx/onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For MatMul`
No MatMul support as well(with onnx version ? I mean, MatMul is pretty rudimentary right? Or am I missing?
I was trying convert an onnx model - IR version:4(generated from a Keras model) to IR version:3 since onnx.js supports only IR version 3.

**Comment by fs-eire** [comment]
@shakkeel1330 FYI - there is an active PR that add support to IR version 4: https://github.com/Microsoft/onnxjs/pull/108

**Comment by shakkeel1330** [comment]
Thank you, for responding :)

**Comment by fs-eire** [comment]
@shakkeel1330 ONNX.js [latest release](https://github.com/Microsoft/onnxjs/releases/tag/v0.1.5) support IR v4 now.

**Comment by shakkeel1330** [comment]
@fs-eire Awesome! Thank you so much.

**Comment by markstrefford** [comment]
> We have version converter, please check https://github.com/onnx/onnx/blob/master/docs/OpsetVersionConverter.md

This link is broken
