### ISSUE TITLE
Big Endian support in numpy helper

### ISSUE THREAD

**Issue by kavanabhat** [onnx/onnx#1730]
Are there any plans to support big endian format in the onnx numpy helper? This is needed for save/retrieval of onnx models on big endian systems. Here is a sample error output when trying to import the onnx backend for caffe2 on AIX.

$python
import onnx
import caffe2.python.onnx.backend
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/tmp/pytorch_python2_64/build/caffe2/python/onnx/backend.py", line 35, in <module>
   import onnx.numpy_helper
 File "/home/user1/onnx/build/lib.aix-7.2-2.7/onnx/numpy_helper.py", line 16, in <module>
   'Numpy helper for tensor/ndarray is not available on big endian '
RuntimeError: Numpy helper for tensor/ndarray is not available on big endian systems yet.

**Comment by houseroad** [comment]
I think this is an issue in the upstream project, i.e., Numpy. I would suggest to create issue in Numpy repository.

**Comment by entossdev** [comment]
numpy has big-endian support. The above error is being thrown from the onnx numpy_helper.py located at https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py which is part of this project. So, please reopen the issue and let us know any plans on adding big endian support.

**Comment by fjfjfan** [comment]
@houseroad I have the same problem, could you please help reopen the issue?  Thanks a lot!

**Comment by kavanabhat** [comment]
Model loading and saving works fine on big endian systems with big endian error check removed in https://github.com/onnx/onnx/blob/master/onnx/numpy_helper.py. So, removal of this check allows model load/save on same type of platforms. To support load/save of onnx models across big/little endian systems may need changes in the onnx formats to record the endianness of the data and the processing tools to do the conversion as needed.

**Comment by shajithchandran** [comment]
For those who are interested in inferencing on Big Endian Machine..
I wrote a tool to convert Little Endian ONNX Model to Big Endian Format and vice versa. Using the tools, i was able to run some of the models from ONNX Model Zoo on Big Endian Machine (AIX).
[https://github.com/shajithchandran/onnx-convertor-le-be](url)
