### ISSUE TITLE
tensor value mismatch at int_zeros test case on ConstantOfShape

### ISSUE THREAD

**Issue by disktnk** [onnx/onnx#1738]
`int_zeros` test case on `ConstantOfShape` sets `1` to `tensor_value`, Should the node return `np.ones((10, 6), dtype=np.int32)`? 

https://github.com/onnx/onnx/blob/master/docs/Operators.md#constantofshape

If the name `int_zeros` is correct, `tensor_value` should be set `[0]`, I think.

**Comment by houseroad** [comment]
Fixed
