### ISSUE TITLE
Updates to ops should require updates to version converter in addition to doc updates

### ISSUE THREAD

**Issue by prasanthpul** [onnx/onnx#1740]
When an op is updated, we require version to be bumped and docs to be updated. We should also require the version converter to be updated to support the change. Otherwise we end up with a bunch of tech debt on the version converter side.

**Comment by cepera-ang** [comment]
Completely agree, current situation is that there, in principle, is a support for different op sets, but in practice many tools support only particular version and there is no easy way to inter-operate. Basically, onnx graphs with different op set are completely foreign to most tools, unfortunately. 

And native onnx converter from any opset to any opset (when possible) will be great leap to the real interoperability between onnx-supporting tools.
