### ISSUE TITLE
Pattern Match in predicated ONNX passes

### ISSUE THREAD

**Issue by Legorock** [onnx/onnx#1742]
Hi,

Before the optimization framework is updated, I had couple of ONNX passes that worked on Conv nodes. Now, I want to port my passes to the new structure which is quite better than previous (IMHO). However, when I look at the "example" passes in the repository, I see that a lot of check and bail out logic is still in the `runTransform` method instead of `patternMatchPredicate`. Is there a reason for this behavior or is it just a matter of time to port them and run tests ? In my opinion, all the "check if, return false" logic should go into matching!

Best regards

**Comment by askhade** [comment]
optimizers has been moved to a separate repo under onnx. Please open an issue there. Thanks
