### ISSUE TITLE
Python 3.7 wheels missing

### ISSUE THREAD

**Issue by letmaik** [onnx/onnx#1750]
Python 3.7 is now out for half a year, I think it's time to add PyPI wheels for this version to avoid unpleasant installation issues when trying to build from source as fallback, esp. on Windows.

**Comment by houseroad** [comment]
cc: @raymondxyang

**Comment by prasanthpul** [comment]
We should do this for ONNX 1.5 if not sooner

**Comment by prasanthpul** [comment]
3.7 whls were added in April: https://pypi.org/project/onnx/#files
