### ISSUE TITLE
Concept of experimental op should be removed

### ISSUE THREAD

**Issue by prasanthpul** [onnx/onnx#1752]
Experimental ops were originally allowed to enable ops that were temporarily in the spec and then would be either promoted to core or deleted. There is no versioning for experimental ops and there are no guarantees with them. This causes problems for anyone who uses an experimental ops. Although cautioned to not use experimental ops for real scenarios, they are being used that way in many cases.

Using custom domains is a better solution addressing the scenarios experimental ops were trying to solve. And they do not have the side effects of experimental ops. So we should find a path for the existing experimental ops and then remove the concept.

**Comment by walrusmcd** [comment]
Totally agree.   Great point too calling out that some people actually shipped models using these ops, and all of our converters produced models using this ops.  The attribute of "experimental" was hidden from them and not obvious in a way that protected them.

Let's clean it up and promotes/delete the ops taking care to not break any backward compatibility issues.

Using custom domains is a great way to move forward and solve the issue.

**Comment by jspisak** [comment]
Thanks @prasanthpul for tagging us into this issue. I think we are in agreement on the spirit and motivation but will need some time to this into account on our side. We would like to propose that we align this change with v1.5 in order to remove the dependencies we have in the meantime. cc @houseroad

**Comment by prasanthpul** [comment]
1.5 seems like a good time to make this happen

**Comment by prasanthpul** [comment]
#1909
