### ISSUE TITLE
Why move DynamicSlice experimental operator from opset 9 to opset 1?

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx#1756]
DynamicSlice is an experimental operator that was added at around Sept 2018. Originally it was a operator in opset 9, but it get move to opset 1 recently. I'm wondering why this operator need to move to opset 1? Why it can't be an experimental operator in opset 9?

**Comment by prasanthpul** [comment]
Experimental ops don't have versioning and should not be used in production models. Which makes them not very useful in my view. (https://github.com/onnx/onnx/issues/1752)

**Comment by winnietsang** [comment]
@prasanthpul Currently all the experimental ops are defined under the OpSet_Onnx_ver1 in onnx/onnx/defs/operator_sets.h file, so they are in opset version 1, does it mean all the backend converter need to support all the experimental ops? I can't tell which ops are experimental from that header file. 
I understand you can manually refer to onnx/docs/Operators.md to find all the experimental operators. But if I want to programmatically figure out which operator are experimental which file should I use?

**Comment by prasanthpul** [comment]
the opschemas have SetSupportLevel(SupportType::EXPERIMENTAL)

**Comment by walrusmcd** [comment]
I'm not sure I understand the nuance of making it opset9 vs opset1.   

DynamicSlice was added in opset9.  so it should stay in 9, not get moved down to 1.   opset1 is supposed to be immutable.     right?

Don't we have an issue if it is put into opset1 in that existing engines will get confused?   We can create a model using DynamicSlice, it will show up as opset1, a runtime like Windows RS5 would load it and get very confused (Windows RS5 shipped with opset 7 support) .

**Comment by chinhuang007** [comment]
I also think putting all experimental ops in opset1 is very confusing. 

Knowing an op is experimental is not enough for the framework converters to determine when (at which opset) the op is first introduced. Therefore the converters won't be able to properly validate models with respective versions. 

If experimental ops have no versioning, they probably should belong to a specific opsetExp, rather than dumped into opset1. Even so, there should be a way to find out when an experimental op is first created.

**Comment by linkerzhang** [comment]
The "experimental op" concept will be removed from ONNX standard in next release (1.5).

For all the existing experimental ops, they'll be either, 1) promoted to ONNX standard op set if useful, or 2) removed.

Feel free to share your opinion if some existing experimental ops are useful in your mind please.

**Comment by linkerzhang** [comment]
#1752

**Comment by prasanthpul** [comment]
#1836

**Comment by ajaysg** [comment]
My onnx model graph has ATen operator. when i try to convert that to tensorrt it throws an error like 
**No importer registered for op: ATen**
what is the solution?
