### ISSUE TITLE
Operations on weights should be eliminated

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#1758]
Many models, like [this](https://drive.google.com/file/d/1WdWn12HPr5Ziz69PBk-JyU8YtiEfU2mu/view?usp=sharing) in https://github.com/daquexian/DNNLibrary/issues/17#issuecomment-455934190, have operations on weights(like reshape, transpose). It makes the model complicated. These operations should be eliminated since they can totally be done offline.

**Comment by daquexian** [comment]
What's more, if the input size is fixed, shape op on weights could also be done offline

**Comment by daquexian** [comment]
I have made a simple script file to solve this issue and published it in https://github.com/daquexian/onnx-simplifier.

**Comment by neginraoof** [comment]
@daquexian How are you handling operations on weights?

**Comment by daquexian** [comment]
@neginraoof I use onnxruntime to perform constant-folding on onnx models. please check out https://github.com/daquexian/onnx-simplifier
