### ISSUE TITLE
onnx 1.4.0 install failed

### ISSUE THREAD

**Issue by Haffon** [onnx/onnx#1762]
$ pip3 install onnx
Collecting onnx
  Downloading https://files.pythonhosted.org/packages/64/a8/bcceb51c0e054df304c446557c3b39c8d109dab0ffd10771c0aa5d0ed967/onnx-1.4.0.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.8MB 217kB/s 
Collecting protobuf (from onnx)
...
  [ 11%] Linking C shared library libonnxifi_dummy.so
  /usr/bin/env: ‘python\r’: No such file or directory
  --mypy_out: protoc-gen-mypy: Plugin failed with status code 127.
  CMakeFiles/gen_onnx_proto.dir/build.make:61: recipe for target 'onnx/onnx.pb.cc' failed
  make[2]: *** [onnx/onnx.pb.cc] Error 1
  CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/gen_onnx_proto.dir/all' failed
  make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 11%] Built target onnxifi_loader
  [ 11%] Built target onnxifi_dummy
  Makefile:127: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-nxpqzi9e/onnx/setup.py", line 328, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
...
  ----------------------------------------
  Failed building wheel for onnx

OS: Ubuntu 16.04.5

**Comment by Haffon** [comment]
$ pip3 install onnx==1.3.0 is okay in the same enviroment.

**Comment by lburzawa** [comment]
It also failed for me because of pybind11 dependencies. Installing pybind11 through pip did not help. In the end I git cloned the repo, installed from there and it worked.

**Comment by clbuttic** [comment]
There are \r's all over the place. Searching for 'python\r' in the Pypi file gives the following results:

./onnx/backend/test/stat_coverage.py:#!/usr/bin/env python
./onnx/gen_proto.py:#!/usr/bin/env python
./onnx/defs/gen_doc.py:#!/usr/bin/env python
./third_party/pybind11/docs/changelog.rst:  .. code-block:: python
./third_party/pybind11/docs/classes.rst:    % python
./third_party/pybind11/docs/faq.rst:.. code-block:: python
./third_party/pybind11/docs/basics.rst:    $ python
./third_party/pybind11/docs/advanced/smart_ptrs.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/embedding.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/embedding.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/strings.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/eigen.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/eigen.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/eigen.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/cast/functional.rst:    $ python
./third_party/pybind11/docs/advanced/cast/custom.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/functions.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/pycpp/object.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/pycpp/utilities.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/classes.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/classes.rst:.. code-block:: python
./third_party/pybind11/docs/advanced/classes.rst:initialized when needed.  More specifically, they are initialized when a python
./third_party/pybind11/docs/advanced/classes.rst:.. code-block:: python
./third_party/pybind11/tests/test_sequences_and_iterators.cpp:    // Obsolete: special data structure for exposing custom iterator types to python
./third_party/pybind11/tests/test_eigen.cpp:    // test_eigen_ref_to_python
./third_party/pybind11/include/pybind11/iostream.h:    .. code-block:: python
./third_party/pybind11/include/pybind11/iostream.h:    .. code-block:: python
./third_party/pybind11/include/pybind11/pybind11.h:    pybind11/pybind11.h: Main header file of the C++11 python
./third_party/pybind11/setup.py:#!/usr/bin/env python
./third_party/benchmark/tools/compare.py:#!/usr/bin/env python
./third_party/benchmark/tools/strip_asm.py:#!/usr/bin/env python
./third_party/benchmark/tools/compare_bench.py:#!/usr/bin/env python
./third_party/benchmark/mingw.py:#! /usr/bin/env python
./tools/mypy-onnx.py:#!/usr/bin/env python
./tools/gen_coverage_report.py:#!/usr/bin/env python
./tools/protoc-gen-mypy.py:#!/usr/bin/env python

It will be required to convert all of those files to unix versions. A quick way to do it:

grep -RlP 'python\x0d' . | xargs dos2unix

**Comment by clbuttic** [comment]
The docs probably shouldn't be converted.

**Comment by raymondxyang** [comment]
I did the source release on a Windows machine. Let me patch it and release from a linux environment again

**Comment by raymondxyang** [comment]
We'll finish publishing binary version for 1.4.0 soon. Then we'll push the patched 1.4.1 today

**Comment by raymondxyang** [comment]
The patch (v1.4.1) is released on pypi (source). Binary coming soon

**Comment by houseroad** [comment]
PyPi package has been updated. So close the issue.
