### ISSUE TITLE
Meaning of Crop border and scale?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#1764]
Hi,
I can't tell from the documentation what the meaning of 'border' and 'scale' are for the Crop operator. 

(1) Are leftBorder  and topBorder the number of pixels that are removed, or are they the start indices? If they are start indices, is it origin 0?

(2) Same question for rightBorder and bottomBorder.

(3) The doc says "If scale is given, then optionally start the crop offset by the left/top border amounts." Aren't we doing that anyway? How are the height and width in the 'scale' attribute used? It doesn't say. Why is it called scale?

Thanks

**Comment by mathisdon** [comment]
Any answer for this yet?

**Comment by prasanthpul** [comment]
Adding @linkerzhang to help clarify

Please note Crop is experimental so should not be used for real models

**Comment by mathisdon** [comment]
>> Please note Crop is experimental so should not be used for real models

How would you recommend implementing a Crop operation in ONNX?

**Comment by wschin** [comment]
There are two cases.
- If your input tensor (the one you want to crop) has a static size, you can call `Slice`. 
- If your input tensor's shape is dynamic (i.e., unknown until runtime), you need to calculate shape of input tensor via `Size` plus some arithmetic operations and then call `DynamicSlice`.

**Comment by prasanthpul** [comment]
Crop was removed. You can use DynamicSlice instead
