### ISSUE TITLE
Differentiate modes in Upsample operator

### ISSUE THREAD

**Issue by vandanavk** [onnx/onnx#1774]
Currently, [Upsample operator](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#upsample-9) in ONNX specifies mode as 'linear' for linear, bilinear, trilinear etc. Changing this to exactly specify which type of linear mode it is, will help importing in different frameworks.

Or is there any other way to distinguish between linear, bilinear from ONNX Upsample?

**Comment by linkerzhang** [comment]
Thank you. Yep. the spec is not clear. We'd clarify it by either having linear meaning bilinear or adding bilinear/trilinear to make the mode clear.

Do you want to send out a PR for this please?

**Comment by jcwchen** [comment]
Upsample has been deprecated and the doc for similar op Resize has been clarified about what these modes are. Close it now. Thanks!
