### ISSUE TITLE
doc issue for Greater op

### ISSUE THREAD

**Issue by nbcsm** [onnx/onnx#1775]
in Opset9, it is not limited to ```float tensors``` anymore.

https://github.com/onnx/onnx/blob/15c33c945851907411619f599900c3852108e7e3/onnx/defs/logical/defs.cc#L82-L94

**Comment by linkerzhang** [comment]
yes, all numeric types were added. is there any concern please?

**Comment by nbcsm** [comment]
the description for T is still **float tensors**

**Comment by prasanthpul** [comment]
thanks for the catch @nbcsm. Are you able to submit a PR to fix?
