### ISSUE TITLE
C++ API - Determining node relationships

### ISSUE THREAD

**Issue by Valentin4869** [onnx/onnx#1777]
I'm trying to parse an onnx model in a C++ application. For now I'm trying to print all the nodes' attributes, but apparently some nodes (conv) have 3 inputs (I'm guessing weights, input image and biases?), but what exactly to these numbers mean? The node inputs start as "0,1,2" corresponding to `node.input(0...2)` for the first layer, and the output is further down at `node.output(0)=17`, and this exact same number is the next layer's input.

So what exactly do these numerical identifiers mean? They don't seem to be node indices. And there is no documentation anywhere for the C++ API.
Here's the code (tested and runs):

Do I basically have to check which two nodes have corresponding input and output ids?

**Comment by linkerzhang** [comment]
yes, ONNX is using "tensor name" to do the connection. One node has output "a", the other node has input  ”a", which means there's an edge between the two nodes. 

ONNX repo does not have/maintain a c++ API, btw.
