### ISSUE TITLE
unable to install scimath on  windows 10

### ISSUE THREAD

**Issue by hk2124** [onnx/onnx#1779]
Using cached https://files.pythonhosted.org/packages/fc/da/df00c7c0b55106b5ba67aa20b948238cb303af5fa930053e047d7e64a693/scimath-4.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\haris\AppData\Local\Temp\pip-install-h6xhp09y\scimath\setup.py", line 13, in <module>
        execfile(join('scimath', '__init__.py'), info)
    NameError: name 'execfile' is not defined

**Comment by prasanthpul** [comment]
What is the command you used to install ONNX?

**Comment by devshaaran** [comment]
Assuming your using `Python3`. Python3 doesn't have the execfile command please replace the `execfile(join('scimath', 'init.py'), info)` with this :

`exec(open(join('scimath','init.py')).read(),info)`

For more information on this topic please refer to this 

[https://stackoverflow.com/questions/6357361/alternative-to-execfile-in-python-3](url)

**Comment by prasanthpul** [comment]
Thanks @devshaaran .

This does not seem related to ONNX, so closing. Please re-open if you believe it is.
