### ISSUE TITLE
check_graph and printable_graph error with pytorch tutorial.

### ISSUE THREAD

**Issue by ahmedhosny** [onnx/onnx#178]
I am running this within **onnx/onnx-docker:cpu** that comes with the following versions:
```
-e git+https://github.com/onnx/onnx@d4db8ff1ab98b7e4923d139b3d66d0a6006d2d58#egg=onnx
-e git+https://github.com/onnx/onnx-caffe2@dc4d2b49c8a7a3082196f7e495d2dcd579e12acb#egg=onnx_caffe2
torch==0.2.0+246a382
torchvision==0.1.8
```
Just following along this [pytorch onnx tutorial](http://pytorch.org/docs/master/onnx.html)
I am able to export alexnet as .proto from pytorch, but the check_graph fails:
```
 File "try.py", line 32, in <module>
    onnx.checker.check_graph(graph)
  File "/root/programs/onnx/onnx/checker.py", line 81, in check_graph
    raise RuntimeError('You cannot pass an object that is not GraphProto.')
RuntimeError: You cannot pass an object that is not GraphProto.
```
I get also an error with printable_graph:
```
 File "try.py", line 34, in <module>
    onnx.helper.printable_graph(graph)
  File "/root/programs/onnx/onnx/helper.py", line 257, in printable_graph
    header = ['graph', graph.name]
AttributeError: 'ModelProto' object has no attribute 'name'
```
Same errors with torchvision.models.resnet50.
Any ideas? wrong versions maybe?

**Comment by houseroad** [comment]
I have tested the tutorial on my laptop in a clean docker image (cpu version). There is no problem.
So I think your pytorch may be too old in your docker container. (I guess you may reinstalled the pytorch in the docker using conda.) In our docker image, pytorch is already installed, no need to reinstall it through conda.

Could you try the tutorial with the clean version of docker image?

**Comment by ahmedhosny** [comment]
I didn't touch any of the libs  - but I re-pulled a fresh docker image and still same issue - did you test the image within the past 20 days (last it was updated)? I'll test again on another machine to see if I can replicate.

**Comment by houseroad** [comment]
@ahmedhosny , I have updated my comments. My original guess was wrong. Turn out the tutorial is out of date.

**Comment by ahmedhosny** [comment]
thanks! That worked. I see you beat me to the PR! Should probably keep this open till they merge..

**Comment by bddppq** [comment]
https://github.com/pytorch/pytorch/pull/3426
