### ISSUE TITLE
find_executable doesn't work well on Windows

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1783]
Even I have cmake in my path, it still complains 

"AssertionError: Could not find "cmake" executable!"

If I set my PATH as:
```
set PATH=%PATH%;C:\Program Files\CMake\bin
```
It's fine.

If I set my PATH as:
```
set PATH=%PATH%;"C:\Program Files\CMake\bin"
```
Then it won't work for python's distutils.spawn.find_executable.

**Comment by yuslepukhin** [comment]
@snnn Is this a CMake/Windows issue? Things work perfectly fine if you install into C:\Cmake
