### ISSUE TITLE
Question: How to support customized python layer in ONNX

### ISSUE THREAD

**Issue by fanghuaqi** [onnx/onnx#1785]
Hi all,
      
I have a question for usage of ONNX format, if I have a model in TensorFlow format, and I want to convert it to ONNX format, but it contains some python layer in TensorFlow, see [example here](https://github.com/mariolew/Deep-Alignment-Network-tensorflow/blob/master/DAN-TF/models.py#L92-L95), how can I achieve this in ONNX, and is there a way to represent that layer in ONNX?

Thanks
Huaqi

**Comment by prasanthpul** [comment]
The TensorFlow to ONNX converter (https://github.com/onnx/tensorflow-onnx) has an option (--custom-ops) that allows you to preserve the custom ops. Then you can implement the custom op separately.

**Comment by houseroad** [comment]
You have to export the customized op in your own domain. If you think it's general enough, you can create a proposal to add it to the ONNX standard opset by following this doc: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md

**Comment by fanghuaqi** [comment]
@linkerzhang @prasanthpul @houseroad  Thanks for your explanation, it make me feel clear about my question.

**Comment by prasanthpul** [comment]
Also consider the new PyOp in ONNX Runtime: https://github.com/microsoft/onnxruntime/blob/master/docs/PyOp.md
