### ISSUE TITLE
Update Slice to accept dynamic inputs and remove dynamicslice exp op

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#1787]
We're now having Slice and DynamicSlice (Experimental). I'd suggest to update Slice to accept dynamic inputs (instead of attributes), and remove DynamicSlice. @houseroad @ebarsoum

**Comment by BowenBao** [comment]
I'll submit a PR soon for updating Slice with dynamic inputs. Also the pr is going to propose adding optional input `steps` for more usage coverage.

**Comment by prasanthpul** [comment]
addressed by https://github.com/onnx/onnx/pull/1836
