### ISSUE TITLE
From onnx to simple c

### ISSUE THREAD

**Issue by rspadim** [onnx/onnx#1789]
Could be possible inplement a simple (static array and statict typed predict function) converter from onnx to c code? Like treelight do with xgb?

Double predict(double *data)

Obvious it’s a single output, justo explain, i don’t want file functions or stdlib vectors. Just plain c code to predict a single “row” of data, without batch prediction

**Comment by prasanthpul** [comment]
Can you provide more details on what you want to do? If you have an ONNX model and want to inference it, there are several backends that can do so including https://github.com/Microsoft/onnxruntime which has a C API.
