### ISSUE TITLE
More kernels in SVM

### ISSUE THREAD

**Issue by olegb94** [onnx/onnx#1791]
Some libraries (like OpenCV, dlib) provide larger set of kernels in SVM than the one that ONNX has right now. This set includes **chi2** and **histogram intersection** kernels, so it should be possible to have these kernels in ONNX.

**Comment by prasanthpul** [comment]
It's certainly possible to add more. We included the commonly used ones. Do you have models that would use the additional kernels? Would you be willing to do a PR to add them to the spec and the runtime?

**Comment by wschin** [comment]
If there are many good kernels, we should consider to make `kernel` as an attribute (type: GraphProto which takes two inputs and produce one output).
