### ISSUE TITLE
Require protobuf 2.6.1 at cmake time

### ISSUE THREAD

**Issue by WilliamTambellini** [onnx/onnx#1793]
Hi,
here is a compilation failure using onnx master on a default uptodate centos 7.5:

cmake .. 
...
 Found Protobuf: /usr/lib64/libprotobuf.so;-lpthread (found version "2.5.0") 

> --   CMake version         : 3.9.3
--   ONNX version          : 1.4.1
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
-- 
--   Protobuf compiler     : /usr/bin/protoc
--   Protobuf includes     : /usr/include
--   Protobuf libraries    : /usr/lib64/libprotobuf.so;-lpthread
--   BUILD_ONNX_PYTHON     : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wtambellini/repos/onnx/build

~/repos/onnx/build] (master)
$ make
Scanning dependencies of target gen_onnx_proto
[  1%] Running gen_proto.py on onnx/onnx.in.proto
Processing /home/wtambellini/repos/onnx/onnx/onnx.in.proto
Writing /home/wtambellini/repos/onnx/build/onnx/onnx.proto
Writing /home/wtambellini/repos/onnx/build/onnx/onnx.proto3
generating /home/wtambellini/repos/onnx/build/onnx/onnx_pb.py
[  3%] Running C++ protocol buffer compiler on /home/wtambellini/repos/onnx/build/onnx/onnx.proto
onnx/onnx.proto:429:5: Expected "required", "optional", or "repeated".
onnx/onnx.proto:429:17: Missing field number.
onnx/onnx.proto:457:3: Expected "required", "optional", or "repeated".
onnx/onnx.proto:457:15: Missing field number.
make[2]: *** [onnx/onnx.pb.cc] Error 1
make[1]: *** [CMakeFiles/gen_onnx_proto.dir/all] Error 2
make: *** [all] Error 2

I suspect onnx not to be buildable with protobuf 2.5 but looks like the CMakeList.txt does nt check if found protobuf version is adequate,  is nt it ?

**Comment by WilliamTambellini** [comment]
Yes I confirm. 
The usual way is to assert third parties versions at cmake time. 
Would you consider asserting/checking the version of protobuf in CMakeLists.txt ?
I could prepare a PR if we agree on specs/changes.

**Comment by houseroad** [comment]
Sounds good to me.

**Comment by WilliamTambellini** [comment]
https://github.com/onnx/onnx/pull/1794
