### ISSUE TITLE
Clarify meaning of operator Constant

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1799]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#constant defines the attribute of this operator as 

```
value : tensor (required)
    The value for the elements of the output tensor. 
```

This is misleading as it sounds like it is a scalar. From the example code and the fact, that no shape is given as an input the specification should read:

```
value : T (required)
    The value of the output tensor. 
```

More general: In ConstantOfShape the same name `tensor` is used. Shouldn't it be always `T<x>` with an appropriate type constraint?

**Comment by skottmckay** [comment]
A tensor always has a shape, and Constant returns a tensor. The tensor could contain a single scalar though. https://github.com/onnx/onnx/blob/master/docs/IR.md#tensor-shapes

The python example for Constant shows it returning a tensor of shape {5, 5}. https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-18

ConstantOfShape is generating a tensor of a given shape, filled with the default or provided value. As the documentation says, an empty shape will return what's considered a scalar. https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-18

**Comment by Flamefire** [comment]
That's how I understood it too especially with the Python example. But ONNX is a specification first and foremost and the specification is confusing/unclear ("The value [singular] for the elements [plural]..."). So the request is to make it more clear.

Additionally why is "tensor" used for the specification and not the more formal "T" with contraints as in most other places? This would also allow for automatic validation.
