### ISSUE TITLE
Improve error messages in shape inference

### ISSUE THREAD

**Issue by letmaik** [onnx/onnx#1800]
If there's a shape mismatch then the error message is something like (as of 1.4.1):
> RuntimeError: Inferred shape and existing shape differ in dimension 0: (200) vs (250)

It would be very helpful to include the ID of the value in the error message.

**Comment by ajaysg** [comment]
any way to resolve this, i am getting the same issue with mul operator

**Comment by jcwchen** [comment]
This should be covered in this PR: https://github.com/onnx/onnx/pull/2783
Please reopen it if you still have the problem. Thanks.
