### ISSUE TITLE
ONNX model doesn't get added

### ISSUE THREAD

**Issue by valavakilian** [onnx/onnx#1801]
Hi. I am trying to follow the winML tutorial but as I add my ONNX file to the project, it doesn't provide me with the  cs file for the model does not  pop up. Is there a specific project I should be working with to get the files to appear ?

**Comment by prasanthpul** [comment]
Since this is WinML specific, it should be filed in https://github.com/Microsoft/Windows-Machine-Learning.

@walrusmcd to follow up

**Comment by valavakilian** [comment]
Thank you. I will close this issue then
