### ISSUE TITLE
[Q] What is the excact output ConstantOfShape with empty input shape

### ISSUE THREAD

**Issue by Flamefire** [onnx/onnx#1803]
The definition of `ConstantOfShape` contains a notable special case:

> input: 1D tensor. The shape of the expected output tensor. If empty tensor is given, the output would be a scalar

However the test case for this is missing. I also couldn't find any other notion how a "scalar" tensor is defined.   
So what are the dimensions of the output tensor in this case? To put it in code: Is the following supposed to pass:

```
graph = self._make_graph([],
        [make_node("Constant", [], ['shape'],
                   value=make_tensor('shape', TensorProto.INT64, (0,), [])), # Empty tensor?
         make_node("ConstantOfShape", ['shape'], ['y'], value=make_tensor('value', TensorProto.INT32, (1, ), (2, )))],
        [])
self._assert_inferred(graph,
        [make_tensor_value_info('shape', TensorProto.INT64, (0,)),
make_tensor_value_info('y', TensorProto.INT32, [])]) # scalar tensor
# Runtime output would be the scalar value "2" in a tensor of an empty shape(?)
```

**Comment by yuslepukhin** [comment]
A scalar Tensor has an empty shape which incidentally allocates memory for exactly one element of type.

**Comment by prasanthpul** [comment]
please reopen if needed

**Comment by Flamefire** [comment]
While I agree with the definition of @yuslepukhin (see my example test code) this is nowhere documented. So as documentation about "scalar tensor" and a test case for this special case is missing I wouldn't close this until that is done.

**Comment by gramalingam** [comment]
A tensor with an empty-shape is a tensor of rank 0, which is widely interpreted to be the same as a scalar (not just in ONNX). See the section https://github.com/onnx/onnx/blob/master/docs/IR.md#tensor-shapes for a documentation about this. So, this treatment is not special to this operator. (But test-cases are always useful for edge-cases like this. Please feel free to create a PR for test-cases. But note that shape-inference is different from what happens at runtime. At runtime, a scalar will have an empty-shape, but whether shape-inference will be able to figure that out statically depends on the context.)

**Comment by Flamefire** [comment]
> A tensor with an empty-shape is a tensor of rank 0, which is widely interpreted to be the same as a scalar (not just in ONNX). See the section https://github.com/onnx/onnx/blob/master/docs/IR.md#tensor-shapes for a documentation about this.

Great 👍  This wasn't there when I opened this (or I haven't found it). So most important part is done.

> but whether shape-inference will be able to figure that out statically depends on the context

Sounds like a good test case for shape-inference
