### ISSUE TITLE
Scatter operator attribute axis validity is unclear

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#1806]
Operator https://github.com/onnx/onnx/blob/master/docs/Operators.md#Scatter spec

States the following validity condition for `axis` attribute

> Accepted range in [-r, r-1]

However, `r` is defined as a rank of the input Tensor.

This raises two questions:

- How can axis attribute be validated at the time of kernel instantiated since no input is available yet.

- When kernel is invoked and axis appears to be out of bounds what is declared invalid, input or the attribute?

**Comment by pk-g** [comment]
regarding first question, axis shall not be fully validated at the time of kernel instantiation when input info is unavailable. however, in case of out of bound axis, it makes more sense to treat the axis as invalid since input is just data, but the operation that has been intended on data is invalid. For instance, default axis of 0 or axis value of -1 is always valid, because input definition guarantees r >= 1, but anything else would require previous assumption of expected input shape.

**Comment by yuslepukhin** [comment]
@pk-g The issue here is the attribute is a constant that is assessed during kernel instantiated. `r` on the other hand is variable. As such it can not flip/flop from being valid or invalid depending on the input.
After kernel is instantiated with a specific Axis value, it means that it is capable on handling input that has `r` of at least the `axis` value. This would be the validation criteria for the input, not the attribute, since attribute is a constant property of the instantiated kernel and the input, as you put it, just an instance of data. Treating axis value as invalid would mean that the instantiated kernel is invalid and I am not where we'd go from here.

**Comment by yuslepukhin** [comment]
@pk-g It boils down to this. Suppose you have an instantiated graph that has an instance of kernel with `axis=x`. Then on repeated execution with various kinds of input, the kernel should either return success if `r` is inline with the `axis` or all of the sudden return an error code that we have an invalid kernel instance in the graph. I am not sure I am getting this.

**Comment by yuslepukhin** [comment]
@pk-g The validation criteria for `axis` as worded is not valid. It has to be either re-phrased or removed. Constant property can not be validated against variable input that occurs in the future.

**Comment by pk-g** [comment]
I believe it is important to be consistent regarding how we treat out of bound axis among different ops in onnx spec. The already established pattern in onnx spec addresses similar issue with shape inference errors indicating invalid axis. here's an example from onnxruntime when an out of bound axis is used within gather op, which btw uses same wording for axis validation in [spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gather):

[E:onnxruntime:Default, runner.cc:184 RunTests] Test gather_5 failed:[ShapeInferenceError] axis must be in [-r, r-1]

you may also take a look at how shape inference is defined in existing examples from Flatten and Gather ops:

(line 786-788 from) https://github.com/onnx/onnx/blob/master/onnx/defs/tensor/defs.cc 
(line 1353-1356 from) https://github.com/onnx/onnx/blob/master/onnx/defs/nn/defs.cc
