### ISSUE TITLE
Upsample problem

### ISSUE THREAD

**Issue by NogizakaDaisuki** [onnx/onnx#1807]
I am trying to use TensorRT to speed up the yolov3.
But when I try to use the example code to convert darknet to onnx, some error appeared like this:

Traceback (most recent call last):
  File "yolov3_to_onnx.py", line 761, in <module>
    main()
  File "yolov3_to_onnx.py", line 754, in main
    onnx.checker.check_model(yolov3_model_def)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node (086_upsample) has input size 1 not in range [min=2, max=2].

==> Context: Bad node spec: input: "085_convolutional_lrelu" output: "086_upsample" name: "086_upsample" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "scales" floats: 1 floats: 1 floats: 2 floats: 2 type: FLOATS }

**Comment by linkerzhang** [comment]
yes, from the error message, the model converted does not following the current spec.

The latest upsample https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample in operator set 9 is having "scales" as inputs, instead of attributes.

**Comment by zhouyongxiu** [comment]
@NogizakaDaisuki Hi, I encounter the same problem, have you solved it?

**Comment by linkerzhang** [comment]
@zhouyongxiu  converting your model into onnx using ONNX operator set <=8 should solve the issue, since the new Upsample definition (having "scales" as inputs) was introduced in operator set 9.

**Comment by zhenyu707** [comment]
@zhouyongxiu  May I know how to change ONNX operator set <=8 ?

**Comment by zhouyongxiu** [comment]
@zhenyu707 sorry, I don.'t know

**Comment by zhenyu707** [comment]
Hello @linkerzhang , May I know how to change ONNX operator set <=8 ?

**Comment by linkerzhang** [comment]
https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L203 is the field used to store a list of <domain, version> pairs, which the model is referring to. For example, it may have ["onnx.ai", 9] in your model, you can change it to ["onnx.ai", 8] to solve the problem.

**Comment by zhouyongxiu** [comment]
@zhenyu707 you can try onnx==1.2.2, I solved it with this version.

**Comment by Nioolek** [comment]
> @ zhenyu707你可以尝试onnx == 1.2.2，我用这个版本解决了它。

Thank you.I use onnx==1.2.2,and it work

**Comment by jinfagang** [comment]
Doesn't work at all:

```
Traceback (most recent call last):
  File "yolov3_to_onnx.py", line 812, in <module>
    main()
  File "yolov3_to_onnx.py", line 805, in main
    onnx.checker.check_model(yolov3_model_def)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "085_convolutional_lrelu" input: "086_upsample_scale" output: "086_upsample" name: "086_upsample" op_type: "Upsample" attribute { name: "mode" s: "nearest" type: STRING }
[20:16:06] fagantryhytjgjin:yolov3_onnx $ pip2 list | grep onnx
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
onnx                  1.2.2  
```

**Comment by Rapternmn** [comment]
Works for pip3 install onnx==1.4.1

**Comment by Rapternmn** [comment]
Check https://github.com/Rapternmn/PyTorch-Onnx-Tensorrt for the implementation.

**Comment by bainro** [comment]
pip2 install onnx==1.2.2 did not work for me.

I looked at which versions were available using: pip2 install onnx==

I tried a couple different versions and 1.5.0 ended up working.

**Comment by Nioolek** [comment]
> pip2 install onnx == 1.2.2对我不起作用。
> 
> 我使用以下方法查看了可用的版本：pip2 install onnx ==
> 
> 我尝试了几个不同的版本，最终1.5.0正常工作了。

Thank you. I will try it!

**Comment by guanshuicheng** [comment]
> Works for pip3 install onnx==1.4.1

it works for me，Why are you so handsome

**Comment by wavesCHJ** [comment]
> Works for pip3 install onnx==1.4.1

python 3.7,  pip install onnx==1.4.1 will get erros , 
changes to python 3.6 ,  install onnx==1.4.1 successfully and it works. 
thanks!

**Comment by ducnguyenhuynh** [comment]
solution:
 You can bulid from source with any version:
https://github.com/onnx/onnx
