### ISSUE TITLE
How would you run inference with onnx?

### ISSUE THREAD

**Issue by Con-Mi** [onnx/onnx#1808]
There is no inference session with Onnx once you load a model? For example it exists in Onnx javascript version. Is there a plan to add this?

**Comment by prasanthpul** [comment]
To inference ONNX models, you can use ONNX Runtime (https://github.com/Microsoft/onnxruntime) or one of the other supported frameworks (https://github.com/onnx/tutorials). If you want to run your model in a web browser, you can use ONNX.JS (https://github.com/Microsoft/onnxjs)

ONNX Runtime example in python:
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("model.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred = sess.run([label_name], {input_name: X_test.astype(numpy.float32)})[0]

**Comment by Con-Mi** [comment]
Ok I follow one of the examples on onnxruntime that is on the website.
Here is the code for it.

import onnxruntime as nxrun
import numpy as np
from skimage.transform import resize
from skimage import io


img = io.imread("./cat.jpg")
img = np.rollaxis(img, 2, 0) 
img224 = resize(img / 255, (3, 224, 224), anti_aliasing=True)
ximg = img224[np.newaxis, :, :, :]
ximg = ximg.astype(np.float32)

# ximg = np.random.rand(1, 3, 224, 224).astype(np.float32)
sess = nxrun.InferenceSession("./squeezenet1.1.onnx")

print("The model expects input shape: ", sess.get_inputs()[0].shape)
print("The shape of the Image is: ", ximg.shape)

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
result = sess.run(None, {input_name: ximg})
prob = result[0]
print(prob.ravel()[:10])

The code above throws a segementation fault. The onnx model I am using is downloaded from the github repo from [here](https://github.com/onnx/models/tree/master/models/image_classification/squeezenet) 

I also tried to use my models trained with PyTorch, for example a ResNet50. 
When I load the model as above I receive the error:
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : No suitable kernel definition found for op BatchNormalization(9)
Seems that there is no support for BatchNormalization in onnxruntime.

In my opinion I dont think the inference part, onnxruntime should not diverge from onnx in general. Maybe it could be merged in the future.

**Comment by prasanthpul** [comment]
Currently ONNX Runtime supports opset 8. Opset 9 is part of ONNX 1.4 (released 2/1) and support for it in ONNX Runtime is coming in a few weeks. ONNX Runtime aims to fully support the ONNX spec, but there is a small delta between specification finalization and implementation.

Can you share the details of the segfault you are seeing? and also which OS, etc

**Comment by Con-Mi** [comment]
I noticed that ONNX Runtime supports ONNX 1.3. That is why it should be merged in ONNX.
I am running Ubuntu 18.04, python 3.6 with anaconda packages. I don't know what other details you want

**Comment by prasanthpul** [comment]
We would be very happy to contribute onnxruntime under the onnx GitHub if there is sufficient community interest.

**Comment by prasanthpul** [comment]
@Con-Mi can you file an issue at https://github.com/Microsoft/onnxruntime for the segfault you are experiencing so that the right folks can take a look? Please include any output you get. thanks

**Comment by leimao** [comment]
What is this `None` for `sess`?
