### ISSUE TITLE
Merging ONNX and ONNX-ML IR profiles

### ISSUE THREAD

**Issue by prasanthpul** [onnx/onnx#1813]
One of ONNX's strengths is that is supports both DNN and traditional ML. Having ops in separate domains is fine. But currently the ONNX-ML.proto is a slight extension of ONNX.proto. What would it take to have ONNX-ML.proto be the only IR?

**Comment by linkerzhang** [comment]
as we're separating operators in different domains for onnx and onnx-ml. I think it's ok to have only onnx-ml.proto as the only IR, because the extension in onnx-ml.proto are several ml types, which are used by ml operators only. The extended types do not impact the model format.

**Comment by houseroad** [comment]
before merging two protos, we should go through the differences, and make sure that we agree on the new features from onnx-ml, for example, the definition of SparseTensor.

**Comment by prasanthpul** [comment]
There was a great discussion and consensus on the sparse tensor plan in the Beijing workshop session. @liqunfu can share details

**Comment by liqunfu** [comment]
The sparse tensor plan from Beijing workshop includes to promote sparse tensor type from ONNX-ML.proto to ONNX.proto. It is in line with this proposal to merge ONNX and ONNX-ML. Regarding @houseroad's concern of SparseTensor definition, that definition is very light weighted. It is open to changes when related ops and generators are updated or added.
