### ISSUE TITLE
torch.onnx.symbolic.normal does not exist

### ISSUE THREAD

**Issue by jbmaxwell** [onnx/onnx#1815]
I'm trying to convert a PyTorch VAE to onnx, but I'm getting: `torch.onnx.symbolic.normal does not exist`

The problem appears to originate from a `reparametrize()` function: 

```
    def reparametrize(self, mu, logvar):
        std = logvar.mul(0.5).exp_()
        if self.have_cuda:
             eps = torch.normal(torch.zeros(std.size()),torch.ones(std.size())).cuda()
        else:
           eps = torch.normal(torch.zeros(std.size()),torch.ones(std.size()))
        eps = Variable(eps)
        return eps.mul(std).add_(mu)
```

I also tried:

    eps = torch.cuda.FloatTensor(std.size()).normal_()

which produced the error: 

```
    Schema not found for node. File a bug report.
    Node: %173 : Float(1, 20) = aten::normal(%169, %170, %171, %172), scope: VAE 
    Input types:Float(1, 20), float, float, Generator
```

I am using `cuda`.

**Comment by prasanthpul** [comment]
Since this is an issue in PyTorch rather than ONNX, please file an issue in the PyTorch GitHub (https://github.com/pytorch/pytorch) so the right folks can take a look

**Comment by jbmaxwell** [comment]
Ah, okay. Thanks. So is any torch.onnx issue now strictly PyTorch, not onnx?

**Comment by prasanthpul** [comment]
torch.* would be PyTorch related. If PyTorch team determines the issue is in the ONNX spec, then we can address in ONNX
