### ISSUE TITLE
convert Upsample op form opset-9 to older verison

### ISSUE THREAD

**Issue by ZyuZyuZyu** [onnx/onnx#1817]
I am using a framework which is supporting an older version of ONNX, and the representation of Upsample-op looks like 
{
    'Upsample',
    inputs=['X'],
    outputs=['Y'],
    mode='nearest',
    width_scale=2,
    height_scale=2,
}
but in the new verison of ONNX, Upsample-op looks like
{
    'Upsample',
    inputs=['X', 'scales'],
    outputs=['Y'],
    mode='nearest',
}
change an attributes to inputs makes me difficult to fix the framework.
So, before this happend, I am wondering if there is anyway to change this op to an older version or Is there anyway to directly modify the onnx model file? I am not familiar with onnx very much, but any suggestions is welcome! Thanks a lot!

**Comment by prasanthpul** [comment]
You can try using https://github.com/onnx/onnx/blob/master/docs/OpsetVersionConverter.md to upgrade/downgrade models but not all ops may be properly supported.

BTW, what is your e2e flow? You have a framework that exports models in the old format. What are you using for inferencing?

**Comment by ZyuZyuZyu** [comment]
> You can try using https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md to upgrade/downgrade models but not all ops may be properly supported.
> 
> BTW, what is your e2e flow? You have a framework that exports models in the old format. What are you using for inferencing?

Thanks~ @prasanthpul , But seems that Upsample is just out of the valid-op list. We do have a inference engine which is used for infer the model from our model-optimize-framework. And now we using pytorch to generate ONNX model, upgrading pytroch version to 1.0.0 lead to this problem.

**Comment by linkerzhang** [comment]
can pytorch exporter support exporting models with specific op set version please? @spandantiwari  @houseroad 

@ZyuZyuZyu to fix the specific model, you may change the "opset_import" in your model to refer to old version. It should be ["", 9] or ["onnx.ai", 9] in your model, changing it to ["", 7] or ["onnx.ai", 7] can ask the model to still refer to old Upsample definition.

**Comment by houseroad** [comment]
yes, right now, pytorch exporter already support opset concepts, and support different behaviors for the ops in different opsets. However, the support of opset in upsample is not appropriate added yet. @spandantiwari and his team is working on that I believe.

**Comment by spandantiwari** [comment]
We are just beginning to add the updated version of ops that changed in opset 10 to PT exporter. Current PT exporter from master should be able to export correctly to opset 9. If older versions are needed, then there's an open PR in ONNX (https://github.com/onnx/onnx/pull/1847) that updates the opset version converter to support going back from 9 to 8.
