### ISSUE TITLE
bool tensor and raw data

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#1819]
If a bool tensor was serialized into a TensorProto with raw_data, How the data can be stored? 1 bit for each element or 1 byte for each?

Thanks.

**Comment by houseroad** [comment]
I guess it's probably 8 bytes per element.

**Comment by houseroad** [comment]
The standard np.bool type is 1 byte. And I think most of the frameworks use 1 byte. I would suggest to stick to 1 byte as well

**Comment by snnn** [comment]
Got it. Thanks.
