### ISSUE TITLE
Change the default value of epsilon in BatchNormalization slightly

### ISSUE THREAD

**Issue by gwtnb** [onnx/onnx#1820]
The current default value of epsilon in [BatchNormalization](https://github.com/onnx/onnx/blob/57372f39631fddc720287a4703040c0551d4ee48/docs/Operators.md#BatchNormalization) is 1e-5 in float (of course with rounding), but this value is not so useful because cuDNN does not accept it. cuDNN aeccepts epsilon which is greater than or equal to 1e-5 in _double_. In C, `1e-5F < 1e-5` is true when the rounding mode is [round half to even](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even), which is default in IEEE 754.

It seems that the default value is intended to be used as is, so the default value should be accepted by cuDNN.

Changing the default value to 1.00000007e-5 or the type of epsilon to double resolves this issue. I guess that the former one does not harm in most cases.

**Comment by shinh** [comment]
+1. FYI, ONNX runtime (https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/cudnn_common.h#L56) and our implementation (https://github.com/pfnet-research/chainer-compiler/blob/master/runtime/ops/normalization.cc#L119) needed a workaround for this issue, and probably other implemeters would need the same.
