### ISSUE TITLE
Error converting upsample operator from pytorch to tensorflow.

### ISSUE THREAD

**Issue by piyush-jaiswal** [onnx/onnx#1827]
Converting the ```Upsample``` operator from ```pytorch``` to ```tensorflow``` using [torch.onnx](https://pytorch.org/docs/stable/onnx.html) and [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) throws an error:

Upsample operator in torch:
```x = torch.arange(1,5).view(1,1,2,2).float()```
```torch.nn.functional.upsample(x, scale_factor=2, mode="bilinear", align_corners=False)```

Error:
```RuntimeError: Upsample without nearest or bilinear is not supported in Tensorflow.```

The issue seems to be that ```torch.onnx``` [exports](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L752-L760) ```bilinear``` mode as ```linear``` to ```onnx```. ```onnx-tensorflow``` [expects](https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/handlers/backend/upsample.py#L23-L25) this mode as one of ```nearest``` or ```bilinear```. Both seem to be written for version 9 of the operator.

I wanted to know if this an issue suitable for ```onnx``` or ```onnx-tensorflow``` and is there a PR open in any one of them that addresses this issue?

Also,
This [PR](https://github.com/onnx/onnx/pull/861#pullrequestreview-116503190) promoting ```Upsample``` from ```version 1``` to ```version 7``` opted for ```linear``` to include all the linear modes instead of adding ```linear``` and ```trilinear``` explicitly because of change in specs from supporting ```4D tensors``` to ```nD tenors```.

Further, comments in this [PR](https://github.com/pytorch/pytorch/pull/13382) seem to suggest that ```linear``` mode is the way to go.

 So, is there a reason now as to why explicitly specifying ```bilinear``` and ```trilinear``` is suggested in this [issue](https://github.com/onnx/onnx/issues/1774)?

**Comment by linkerzhang** [comment]
this may be moved to pytorch community, I think.

**Comment by PK15946** [comment]
Also have this issue, have you solved the problem? @piyush-jaiswal

**Comment by piyush-jaiswal** [comment]
@PK15946, changing [mode_s](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L872-L873) to `bilinear` and building `pytorch` from source, solved the issue for me.

**Comment by piyush-jaiswal** [comment]
Based on @linkerzhang's comment, [moved](https://github.com/pytorch/pytorch/issues/17928) the issue to pytorch. Hence, closing this.
