### ISSUE TITLE
Add optimizer pass: fuse_mul_into_conv

### ISSUE THREAD

**Issue by fredvannijnatten** [onnx/onnx#1828]
I really love the ONNX optimizer! There is already a fuse_bn_into_conv and a fuse_add_bias_into_conv. In addition to these I would like to request to add fuse_mul_into_conv for when there is a multiplication by a constant.

It will be useful for the scenario where input scaling / output scaling is included into the network. The scaling can subsequently be merged with a following or preceding conv.

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this question, please raise an issue there. Thank you!
