### ISSUE TITLE
Why does ir_version have int32 type in op sets

### ISSUE THREAD

**Issue by letmaik** [onnx/onnx#1840]
In the model, ir_version is int64. Why is there this difference?

**Comment by prasanthpul** [comment]
where are you seeing this? there is no ir_version in opset (OperatorSetIdProto)

All the versions are int64 in https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto

**Comment by prasanthpul** [comment]
this is in https://github.com/onnx/onnx/blob/master/onnx/onnx-operators.in.proto

**Comment by gramalingam** [comment]
A more general question: it seems to me that most parts of onnx-operators.in.proto are unused at this point (and are somewhat forward-looking … e.g., if functions inside a model become a reality, we might need something like FunctionProto). Perhaps there is a better way to organize these parts (which may be experimental)? (But I agree we should make things like ir_version consistent and uniform.)

**Comment by linkerzhang** [comment]
it should be fixed (make int64). @letmaik  do you want to send a PR to fix it please?
