### ISSUE TITLE
Error converting ONNX to caffe2

### ISSUE THREAD

**Issue by rracinskij** [onnx/onnx#1841]
Hi,

trying to adapt a script from https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html :
for an export from ONNX to caffe2 results in error:
```
import onnx
import caffe2.python.onnx.backend as onnx_caffe2_backend
from caffe2.python.predictor import mobile_exporter

model = onnx.load('models/mb1-ssd.onnx')
prepared_backend = onnx_caffe2_backend.prepare(model)
c2_workspace = prepared_backend.workspace
c2_model = prepared_backend.predict_net
init_net, predict_net = mobile_exporter.Export(c2_workspace, c2_model, c2_model.external_input)
```
but it fails:

> ...anaconda3/lib/python3.6/site-packages/caffe2/python/predictor/mobile_exporter.py", line 41, in add_tensor
>     kTypeNameMapper[blob.dtype],
> KeyError: dtype('float64')

**Comment by prasanthpul** [comment]
The error seems specific to Caffe2 and not ONNX. Can you file this issue in the Caffe2 repo instead?

**Comment by rracinskij** [comment]
Ok, thank you.
