### ISSUE TITLE
Input type for ConstantOfShape operator tests are incorrect

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#1842]
`ConstantOfShape` operator takes a single input constrained to type `int64`. Both the node tests use input generated using np.array() which defaults to type `int32`. It should pass `dtype=np.int64` to be complaint with the operator spec.

CC: @zrphercule , @yuslepukhin

**Comment by linkerzhang** [comment]
thank you! @hariharans29 , do you want to create a PR to fix it please? @spandantiwari @zrphercule  as FYI.

**Comment by prasanthpul** [comment]
I believe this is addressed - please reopen if not
