### ISSUE TITLE
support for slice_like operator from mxnet gluoncv

### ISSUE THREAD

**Issue by zavalit** [onnx/onnx#1845]
hi  
`slice_like` was introduced in gluon-cv to allow detection model to handle variant input resolutions adaptively.

is there any plans to support this operator as well on onnx side?

**Comment by linkerzhang** [comment]
can dynamic slice work for the model you have please?

**Comment by zavalit** [comment]
sorry, i don't get your point. 
the context gluon-cv use it is:
```
slice_like(x,y,axes=(2,3))
```
i'm not aware of any alternative dynamic slice here

**Comment by prasanthpul** [comment]
@linkerzhang is asking whether https://github.com/onnx/onnx/pull/1836 addresses your need. can you check?
I didn't easily find definition of slice_like in gluon-cv documentation. do you have a link?

**Comment by zavalit** [comment]
sorry for a bit if delay.
1. you can find it on mxnet: https://beta.mxnet.io/api/ndarray/_autogen/mxnet.ndarray.slice_like.html
2. to #1836 i can not really obtain what exact behaviour do i have to expect from it. do you may be have any examples there?

**Comment by chop2** [comment]
Hi, any plan to add slice_like op ?
