### ISSUE TITLE
[Discussion] ONNX Tensorflow Backend

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#185]
Hi all,

Not so long ago we (Arpith Jacob, Tian Jin and Gheorghe-Teodor Bercea from IBM Research) have developed an experimental Tensorflow backend for ONNX for our internal research purpose at IBM Research. During our development of this project, we realized that this conversion is no minor effort and decided to publish our work here: https://github.com/tjingrant/onnx-tf. We have been contributing to this public repository since then.

We would very much like to get comments from the community and help anyone who has the same need. 

Edit: we have passed all 9 model tests.

~~For model tests, we have passed 6 of the 9 model tests. Two failed (Inception) because of a TF bug related to average pooling op with 7x7 window. See: https://github.com/tensorflow/tensorflow/issues/12293 . Workarounds require changing the code and thus impractical in practice. But we have stepped through every layer with the caffe2 backend and we can confirm that it breaks precisely at the pooling layer with 7x7 window.~~

~~Shufflenet also fails. We installed the caffe backend for ONNX but as of this week, when we run the shufflenet through caffe backend, we get the following error:~~
```
RuntimeError: [enforce fail at operator.cc:119] schema->Verify(operator_def). Operator def did not pass schema checking: input: "OC2_DUMMY_1" output: "gpu_0/shuffle_0_1" output: "OC2_DUMMY_1" name: "" type: "Reshape" arg { name: "shape" ints: 1 ints: 112 ints: 56 ints: 56 } device_option { device_type: 0 cuda_gpu_id: 0 }
```
~~We will look into the cause once we have a reference implementation from the caffe backend.~~

Best wishes,
Tian Jin.

**Comment by bddppq** [comment]
The RuntimeError is very likely related to a known bug fixed in this commit: https://github.com/onnx/onnx-caffe2/commit/abcc7cccc5097ad7a9da9ea55368ebee86f42c8f, could you try the newest version of onnx-caffe2?

**Comment by tjingrant** [comment]
Thanks, we refreshed our onnx-caffe2 install and the model now runs, but apparently we see the same average pool op with 7x7 window and 1x1 stride. What we can do now is limited but will try to see what workarounds we can come up with.

**Comment by bddppq** [comment]
Thanks a lot for your contribution! I believe a lot of people are looking forward to this converter #3

Regarding to testing, it would be better to directly hook up to the onnx backend test: https://github.com/onnx/onnx/blob/master/onnx/backend/test.py , the setup should be relatively easy, e.g. https://github.com/onnx/onnx-caffe2/blob/master/tests/onnx_backend_test.py.

**Comment by tjingrant** [comment]
We will look into setting up the backend tests very soon. Regarding the pooling bug in Inception model, I have uploaded a Gist here for anyone interested: https://gist.github.com/tjingrant/8228a908d15155c7ebc547fc6e57c57f#file-main-py . The gist contain large data files so it may be better to just download and run. It illustrates the difference between Numpy, Caffe and TF with regard to avg pooling. With zero-padding taken into account, the result of Numpy and Caffe are reasonably close yet TF result is significantly different. 

Please let us know if you think I did something wrong.

**Comment by dzhulgakov** [comment]
Thanks a lot for the contribution! We should see how to consolidate tf backend/frontend and potentially move it under onnx/ repo.

From looking at the TF issue it seems it's a bug on GPU specifically. Have you tried running comparison on CPU?

@fmassa - any updates on your work on tf backend?

**Comment by tjingrant** [comment]
Hi, I took another look at the code today and it turns out that manual padding for average pooling op is not a good idea. Sorry for prematurely attributing this error to the TF issue. 

As you may know Tensorflow does not support fine-grained specification of padding. For a quick example, check out here https://www.tensorflow.org/api_docs/python/tf/nn/avg_pool. This is giving us a lot of trouble.  In our latest attempt to battle this issue, we special-cased some scenarios where native pooling ops can be used and implemented our own python version of pooling as a custom TF node which mimics Caffe2 behavior. And we are very excited to see that doing so helped us pass all 9 model tests on both CPU and GPU (interestingly, TF supports different tensor formats depending on whether you are on a CPU or a GPU thus the behavior of our converter is different on each device).

As for moving under a onnx repo, I brought up this idea to our team during today's meeting and we are very excited to do so. Would you like me to push our repo here once we clear all the backend tests (I will integrate these tests very soon)?

**Comment by bddppq** [comment]
@tjingrant Implementing an Operator in converter might not be a good idea IMO. Have you tried using the native tensorflow pooling ops on cpu (as @dzhulgakov pointed out, the bug seems be only on GPU)? And it would be better to directly fix the bug in tensorflow.

**Comment by tjingrant** [comment]
@bddppq Hi, I totally agree it is not a good idea. As I explained, the bug does not impact our implementation. On GPU, we use "NCHW" format which will always be translated to CuDNN calls. The complication arises because tensorflow pooling op natively supports either "SAME" padding or "VALID" padding. If the padding is neither "SAME" nor "VALID", then there is no native way to support this kinda of padding. 

In addition, because average pooling op needs to know what paddings are added (because the padded values have to be excluded from the averaging process). Thus using tf.pad is out of question as well. 

However, this usually does not occur (in all 9 model tests, this only occurred in shufflenet) and we will try to use native pooling ops as much as we can before switching to our custom node which can be useful in verifying other parts of the neural net.

**Comment by tjingrant** [comment]
FYI https://www.tensorflow.org/api_docs/python/tf/nn/avg_pool .

**Comment by Yangqing** [comment]
First of all I share your pain in dealing with the padding size :)

If you would like to check the math, when I wrote Caffe2 and was trying to provide tf compatibility, I wrote a short summary of note here:

https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2_legacy.proto#L8-L21

Although I believe you have already sorted out everything.

**Comment by dzhulgakov** [comment]
The implementation you have in https://github.com/onnx/onnx/issues/185#issuecomment-342284182 with _compatibility_pool is definitely not permanent: it has pretty bad performance and also it won't work with model serialization (as it's a python function).

As you correctly noticed, TF's padding story is a bit messed up. Until you get custom op (which is harder to distribute too) as a less-performant workaround you can try to call https://www.tensorflow.org/api_docs/python/tf/pad directly - it supports pixel values for padding.

**Comment by tjingrant** [comment]
@dzhulgakov how would you specify the pixel values to pad? If you pad zero, then you need the tf average pooling op to know where you padded zeros so as to exclude them from averaging which is impossible.

**Comment by tjingrant** [comment]
@Yangqing I've read your comments and they are very helpful as we double check our implementation. It would be very helpful to get your opinion about how to best support the average pooling ops in ONNX with arbitrary paddings using only existing Tensorflow ops so that the results match up with Caffe2. Or is it possible at all to do it without custom ops?

**Comment by tjingrant** [comment]
Please walk me through this particular example. The shufflenet has the following first pooling layer which accepts input of spacial dim [14, 14] as in https://arxiv.org/pdf/1707.01083.pdf page 4 Table 1:
```
input: "gpu_0/pool_0_1"
output: "gpu_0/pool_1_1"
name: ""
op_type: "AveragePool"
attribute {
  name: "strides"
  ints: 2
  ints: 2
}
attribute {
  name: "pads"
  ints: 1
  ints: 1
  ints: 1
  ints: 1
}
attribute {
  name: "kernel_shape"
  ints: 3
  ints: 3
}
```
Following the equation in the caffe2 note, same padding is calculated as
```
R_out=ceil(56/2)=28
Pr = ((28-1)*2+3-56)=1
```
Pr is odd, thus only pad right. Thus a same padding in this case is [0, 0, 1, 1] not [1, 1, 1, 1]. Thus this pooling op is neither VALID nor SAME.

**Comment by Yangqing** [comment]
It is impossible if you do not specify the input size and need to specify the size at runtime. if the input size is known, you can potentially do a shape inference, get the explicit pad values, use the pad value in an explicit Pad operator, and then carry out conv/pool in a padding=0 case (I assume VALID basically gives you that).

**Comment by tjingrant** [comment]
I think there may be a confusion of terminology here. When i ask about pad values, I'm referring to the constant_values parameter in tf.pad  https://www.tensorflow.org/api_docs/python/tf/pad. We are already doing what @Yangqing is suggesting for Max Pooling op and it works just as @Yangqing suggests. But Avg pooling is different because we cannot just pad zeros.

**Comment by Yangqing** [comment]
Ah yeah, in that case there is indeed no perfectly matching solution. I have heard that TensorFlow is planning to adopt an explicit padding mechanism; cc'ing @rajatmonga to see if there are some point of contacts we can follow up with.

**Comment by fmassa** [comment]
@dzhulgakov I was waiting for green light to release the implementation I had (which just came out last week).
By looking at @tjingrant implementation, it seems that what they have is a superset of my implementation, so I believe it's better to go with their implementation.

**Comment by rajatmonga** [comment]
Yes, explicit padding for these ops is on our list and we have a design/spec, however there hasn't been much progress on the work.

**Comment by tjingrant** [comment]
@fmassa we regret not being able to see your implementation sooner and we understand that legal clearance can be very tricky to obtain. We are very lucky to be permitted to be developing in the public early on. On the other hand, we welcome collaborations from any interested party.

@dzhulgakov we have integrated the backend tests and everything looks good with the only exception for RNN (API changed quite recently and we need some time for update). Any plan to move our repository under the ONNX organizational account soon? I believe moving this repo out of my personal account would be a good way to facilitate collaborations.

**Comment by dzhulgakov** [comment]
Re padding: I wonder if we can make some kind of hack in the case you mentioned with shufflenet. If you know the input size then you can compute which sizes of padding do not change the output size. In this particular case both [1,1,1,1] and [0,0,1,1] (measured in pixels) produce the same output dimensions because of stride=2 convs. Is it safe to just extend the logic of `get_tf_pad` so that it captures it? Usually it's the behavior the user wants out of pooling anyway.

As mentioned above, `_compatibility_avg_pool` is not cool to include (other than debug mode) because it makes resulting models unserializable and also has terrible perf. I'd explicitly hide (and fail instead) it unless maybe some flag is passed in.

**Comment by dzhulgakov** [comment]
@tjingrant - regarding contributions - let's make it official! :) Here's https://github.com/onnx/onnx-tensorflow (let me know if you prefer onnx-tf), I added you with write access - let me know if somebody else from your side needs to be a committer.

As for RNN tests - don't worry about it immediately. As you mentioned, we iterated on the spec a bit (adding individual ops for different variants instead of one gigantic one), so I'd wait for a week or so until it settles and we update the tests.

**Comment by tjingrant** [comment]
Hi, thanks a lot! This would definitely help us move forward quickly. Please add @arpith-jacob, @doru1004 from our team to be additional collaborators. 

As for padding, I agree with you that the difference between [1,1,1,1] and [0,0,1,1] may not matter in terms of what the user want out of the pooling op. But then if a user import a trained model from another backend, output of the pooling layer may go slightly astray (as you may have noticed, in our tests we stepped our models with Caffe2 layer by layer to ensure not only the end results but also the intermediate ones are within acceptable tolerance). Therefore, in this case, it is important that the user knows what he's doing, and consequently he may very well know how to modify the model's padding attribute to get better support from Tensorflow.

I agree that passing a debug flag is a better temporary workaround until TF has support for arbitrary padding. I will implement this feature and disable compatibility avg pool by default.

**Comment by tjingrant** [comment]
Please let us know if there's a need to maintain the MIT license. We picked Apache 2.0 simply because TF uses Apache 2.0.

**Comment by dzhulgakov** [comment]
For other repos keeping the license of the target framework is fine. So feel free to keep Apache 2.0 for onnx-tensorflow.

**Comment by tjingrant** [comment]
Ping @bddppq , @dzhulgakov , can anyone please enable Travis-CI for us? I do not have the authorization to do so.

**Comment by bddppq** [comment]
Need someone has admin access to the onnx-tensorflow repo (or to the onnx org) to enable it :-) @dzhulgakov

**Comment by dzhulgakov** [comment]
Sorry for delay. @tjingrant - I gave you Admin privileges for onnx-tensorflow - please use it wisely :)

**Comment by tjingrant** [comment]
@dzhulgakov thank you and I will!
