### ISSUE TITLE
randn  error with tensorboardX

### ISSUE THREAD

**Issue by JurijsNazarovs** [onnx/onnx#1854]
Hello,

I am using pytorch and tensorboardX to create a graph of my network. When I try to create a graph by .add_graph() I get following error:

```
i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

Invoked with: %104 : Tensor = onnx::RandomNormal(), scope: BTCNN
, 'shape', 100 defined in (%100 : int[] = prim::ListConstruct(%87, %91, %95, %99), scope: BTCNN
) (occurred when translating randn)
```

As I understand, message says that problem is with onnx not able to process ```torch.randn```

Issue with tensorboardX: https://github.com/lanpa/tensorboardX/issues/359

**Comment by prasanthpul** [comment]
ONNX supports RandomNormal: https://github.com/onnx/onnx/blob/master/docs/Operators.md#RandomNormal

So this seems like an issue with PyTorch. Please file an issue in the PyTorch Github.
