### ISSUE TITLE
Why is GlobalAveragePool output size NC11 when input size is NCxyz...?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#1857]
According to the Doc https://github.com/onnx/onnx/blob/master/docs/Operators.md#GlobalAveragePool,
the output of GlobalAveragePool is always (N x C x 1 x 1), even when the input size is (N x C x D1 x D2 ... Dn).

Is this documentation correct? If not, what is the output size? I expected it to be [N x C] in all non-RNN cases.

**Comment by houseroad** [comment]
Merged.
