### ISSUE TITLE
PR 1874: Mod(ulus) Operator

### ISSUE THREAD

**Issue by jeffsaremi** [onnx/onnx#1875]
This is a very fundamental operator which happens to be missing.
I have added it and hoping that I could get it reviewed. thanks
https://github.com/onnx/onnx/pull/1874

**Comment by jeffsaremi** [comment]
I'm getting CI Build errors on this PR
https://github.com/onnx/onnx/pull/1874

They're not clear to me or I don't know what to look for. Could someone guide me as to locating these errors?
thanks

**Comment by prasanthpul** [comment]
Looks like the PR has been successfully merged a while back. Thanks for the contribution
