### ISSUE TITLE
When operator specification proto exists, move schema definitions to Python

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#188]
The primary reason OperatorSchema is implemented in C++ is so that the C++ checker can make use of it (C++ checker is useful because it is portable and can be used in embedded settings.) Once we have a protobuf version of OperatorSchema, however, we can move the actual definitions out into Python, generate the proto, and have the checker work off of that.

Not a priority for Nov release.

**Comment by gramalingam** [comment]
What about aspects that cannot be captured in the protobuf, such as perhaps a shape-inference function?

**Comment by ezyang** [comment]
Good question. I'd wouldn't mind forcing us to fully spec out how to express this in the protobuf, but it's a discussion we should have. If we can't do this, we'll have to do something like keep some parts of the spec in the C++ checker.

**Comment by dzhulgakov** [comment]
Just curious - how is having schema in Python helps? Is it purely cosmetic change?

**Comment by ebarsoum** [comment]
If there is still interest in discussion the above, please join our SIG meeting.
