### ISSUE TITLE
At least one CI build and install ONNX in debug mode

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#1880]
Otherwise, some check may fail silently. Such as https://github.com/onnx/onnx/blob/master/onnx/defs/schema.cc#L820

https://github.com/onnx/onnx/pull/1878 is for fixing the checks. But we need CI to detect such breakage.

**Comment by houseroad** [comment]
cc: @linkerzhang @prasanthpul @zrphercule @bddppq

**Comment by snnn** [comment]
Then don't enable 'COVERAGE' . I thought it was by design.
