### ISSUE TITLE
Permission to use ONNX logo in monochromatic icon

### ISSUE THREAD

**Issue by rowanmiller** [onnx/onnx#1893]
I work on the .NET team at Microsoft.

For web content around samples for ML.NET we use icons for each sample (see middle of [this page](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet) for an example). 

One of the samples shows how to use ML.NET with ONNX. I'm asking for permission to use a monochromatic version of the ONNX logo as the icon for this sample.

Here is a quick mock up that shows what we'd like to do.

![image](https://user-images.githubusercontent.com/4741851/55260283-36502380-5225-11e9-82b9-fe74bfa4347c.png)

Is this acceptable to you?

**Comment by prasanthpul** [comment]
will follow up directly.
