### ISSUE TITLE
Converting a onnx model into cpp source code

### ISSUE THREAD

**Issue by charanpool** [onnx/onnx#1897]
Hello,
I am trying to convert a graph or neural network structure present in onnx format(.onnx file) into a cpp source code, that includes the graph and node structures. For example, I am having a tinyyolov2.onnx, which I wanted to represent it in cpp source code as we can do with nnef. Any idea of how to approach it?

**Comment by prasanthpul** [comment]
Can you elaborate on what you are looking for? Since the ONNX file is in protobuf, you can access it from C++. The graph contains operators that require implementations. There are C++ implementations of these operators in several projects including ONNX Runtime.

**Comment by charanpool** [comment]
@prasanthpul Thankyou for responding faster. My question is how to access(open the file and recognise the nodes and edges between those nodes) that .onnx file from C++ and create a C++ network(graph) structure from those obtained nodes and edges?

**Comment by charanpool** [comment]
I have tried an approach but encountered some problem which I mentioned [here](https://github.com/onnx/onnx-tensorflow/issues/404). Please go through it once and help me resolve it.
