### ISSUE TITLE
ExtractImagePatches is not supported

### ISSUE THREAD

**Issue by ayermolo** [onnx/onnx#1904]
I am trying to convert yolov2-voc generated by DarkFlow in to ONNX, and running in to this error
"ValueError: tensorflow op ExtractImagePatches is not supported"

I am using tensorflow=1.9.0, onnx=1.4.1, opset=7, tfonnx=1.5.0/9fcb06.

According to folks at TFConverter issue is ONNX has no support for ExtractImagePatches.
https://github.com/onnx/tensorflow-onnx/issues/436

What is the process for adding such support to ONNX?

Thank You

**Comment by MidoriYakumo** [comment]
In my opinion, any general op is supported in ONNX, it only depends on whether your inference backend can parse and infer it correctly. For example, I use aten::affine_grid, aten::adaptive_max_poolnd, caffe2::RoiAlign and caffe2::PsRoiPool between my training framework and my inference engine. 
ONNX is just an exchange format, it's easy to define ONNX op for yourself.

**Comment by ayermolo** [comment]
Well it's not just about defining OP yourself, it's also about other tools that can use it. In this case a TF to ONNX converter tool.

**Comment by MidoriYakumo** [comment]
So it's just the problem of tensorflow-onnx. Here is a reference for [PyTorch](https://github.com/pytorch/pytorch/blob/3079d95b6c29e71262766f8acb5c24456d27706b/torch/onnx/symbolic.py), define op like `g.op("tf::ExtractImagePatches", ksizes_i=ksizes, strides_i=strides, ...) `require just few lines.

**Comment by ayermolo** [comment]
Seems like it?

**Comment by jhagege** [comment]
Hi, any update on this ? 
Thanks!

**Comment by jhagege** [comment]
@spandantiwari any idea if someone has been working on it ? 
Alternatively, any workaround to export a model that uses this TF operator ? 
Thanks much !

**Comment by kothari1997narayan** [comment]
Tensorflow op [raft_1/while/ExtractImagePatches: ExtractImagePatches] is not supported

Facing similar issue while trying to convert tensorflow model to onnx.
