### ISSUE TITLE
PyTorch export of Upsample

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [onnx/onnx#1918]
-------------------------------------------------------------------------------
1.Using : 
from onnx import helper
helper.make_node(
            'Upsample',
            mode='nearest',
            scales=[1.0, 1.0, 2, 2],
            inputs=inputs,
            outputs=[layer_name],
            name=layer_name,
        )
I got :  
onnx::Upsample[mode = 'nearest', scales = [1, 1, 2, 2]]....
----------------------------------------------------------------------------

2.   by using :nn.Upsample(scale_factor=2, mode = 'nearest') and torch.onnx.export, I just got 
onnx::Upsample[mode="nearest"].....
-----------------------------------------------------------------------------------
How can I get the 1 result with 2 way ? 
Some parameters should be used?

**Comment by prasanthpul** [comment]
This looks like a PyTorch-specific issue. @houseroad can you confirm?
If so, suggest moving this to PyTorch github so it can be addressed

**Comment by MenGuangwen-CN-0411** [comment]
@prasanthpul  Thank you for your reply.

**Comment by houseroad** [comment]
I think we fixed it in the pytorch exporter already. Let's close it. If we still have the problem with pytorch's master please report the issue on pytorch github repo.
