### ISSUE TITLE
When I use helper.make_graph to create onnx graph, the nodes are not topologically sorted

### ISSUE THREAD

**Issue by jiafatom** [onnx/onnx#1920]
One user creates an [issue](https://github.com/onnx/keras-onnx/issues/58) on keras2onnx converter, I want to post it here for suggestions:
Looking at [IR doc](https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs), onnx graph node is A list of nodes, forming a partially ordered computation graph based on input/output data dependencies.

At converter side, we have onnx nodes, initializers, etc, and we use onnx helper.make_graph API to make graph. The input onnx nodes we have are not topologically sorted, we are expecting onnx helper.make_graph to do that, but it does not. Shall we support this in make_graph? Thanks

**Comment by paulbauriegel** [comment]
@jiafatom Having the same problem. The created ONNX model  runs only on the ONNXRuntime and not anywhere else. When `onnx.checker.check_model(onnx_model)` fails with some `ValidationError: Nodes in a graph must be topologically sorted ...` e.g.:

```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Bottleneck_BatchNorm/cond/Merge:01' of node: 
input: "Bottleneck_BatchNorm/cond/Merge:01" output: "Bottleneck_BatchNorm/cond/Merge:0" name: "Identity1" op_type: "Identity" domain: ""
 is not output of any previous nodes.
```

All tools I tried so far fail to load the model:
<details>
<summary>OpenCV</summary>

```
----> 1 net = cv2.dnn.readNetFromONNX('facenet.onnx')
error: OpenCV(4.1.1-pre) /home/paul/openvino-toolkit/opencv/modules/dnn/src/onnx/onnx_importer.cpp:320: error: (-204:Requested object was not found) Blob Bottleneck_BatchNorm/cond/Merge:01 not found in const blobs in function 'getBlob'
```
</details>

<details>
<summary>ONNX-Tensorflow</summary>


```
Traceback (most recent call last):
  File "/home/paul/anaconda3/envs/openvino/bin/onnx-tf", line 11, in <module>
    load_entry_point('onnx-tf', 'console_scripts', 'onnx-tf')()
  File "/home/paul/onnx-tensorflow/onnx_tf/cli.py", line 20, in main
    return onnx_tf.converter.main(args[1:])
  File "/home/paul/onnx-tensorflow/onnx_tf/converter.py", line 22, in main
    convert(**{k: v for k, v in vars(args).items() if v is not None})
  File "/home/paul/onnx-tensorflow/onnx_tf/converter.py", line 137, in convert
    tf_rep = backend.prepare(onnx_model, **kwargs)
  File "/home/paul/onnx-tensorflow/onnx_tf/backend.py", line 53, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/home/paul/anaconda3/envs/openvino/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Bottleneck_BatchNorm/cond/Merge:01' of node: 
input: "Bottleneck_BatchNorm/cond/Merge:01" output: "Bottleneck_BatchNorm/cond/Merge:0" name: "Identity1" op_type: "Identity" domain: ""
```
</details>
<details>
<summary>OpenVINO</summary>

```
[ ERROR ]  Cannot pre-process ONNX graph after reading from model file "/home/paul/facenet.onnx". File is corrupt or has unsupported format. Details: Reference to Bottleneck_BatchNorm/cond/Merge:01 is not satisfied. A node refer not existing data tensor. ONNX model is not consistent. Protobuf fragment: input: "Bottleneck_BatchNorm/cond/Merge:01"
output: "Bottleneck_BatchNorm/cond/Merge:0"
name: "Identity1"
op_type: "Identity"
domain: ""
```
</details>

**Comment by benschreiber** [comment]
I am also seeing the same issue. https://github.com/onnx/keras-onnx/issues/170

**Comment by gramalingam** [comment]
I agree it would be useful to add a topological-sort utility. As of today, make_graph expects the inputs to be supplied in sorted order. We could provide the topological-sort as a separate utility. If make_graph does the sort, I would make it sort conditionally based on some user-flag … there is no point in unnecessarily sorting it if the user has already done it.

**Comment by jiafatom** [comment]
we just checked in the code that perform topological sort on converter side, related issues got resolved, so close this.

**Comment by EmreOzkose** [comment]
Hi @jiafatom , How did you perform topological sort?
