### ISSUE TITLE
Question about averagepool_2d_precomputed_same_upper test

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#1921]
In the test `averagepool_2d_precomputed_same_upper`, the input_shape is [1, 1, 5, 5] and the expected output_shape is [1, 1, 3, 3] when auto_pad = 'SAME_UPPER'. I thought the purpose of using the auto_pad attribute is so that appropriate pads are computed so as to make output_shape the same as the input_shape. Am I missing something ?

**Comment by hariharans29** [comment]
CC: @houseroad @zrphercule

**Comment by pranavsharma** [comment]
Raised by a user here: https://github.com/Microsoft/onnxruntime/issues/495
