### ISSUE TITLE
Why treat warnings as errors on windows even when ONNX_WERROR is off?

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#1936]
https://github.com/onnx/onnx/blob/master/CMakeLists.txt#L404 and L451, L464

It is inconsistent between windows and linux/macos. On linux/macos the "treat warnings as errors" is controlled by ONNX_WERROR, but on windows it is always on.

**Comment by linkerzhang** [comment]
it's more strict on windows by design.

**Comment by askhade** [comment]
Closing this as by design. @daquexian  : If you have further questions on this topic please reopn this issue or create a new one
