### ISSUE TITLE
Add Tensor(String) Input support for Equal ops

### ISSUE THREAD

**Issue by waterknows** [onnx/onnx#1937]
We would like to have the ONNX Equal operator to support tensor(string) input type, similar to what Equal operator in Tensorflow is doing: https://www.tensorflow.org/api_docs/python/tf/math/equal

**Comment by linkerzhang** [comment]
do you want to send a PR to propose the update?

**Comment by yuxiaosun** [comment]
Thanks! I am drafting the PR. This is more of a data type change to exsiting operator - should I modify the exisiting operator? or what would be the best way to start?
