### ISSUE TITLE
Backend Tests

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#194]
Hi, as more backends are supported, I think things like here (https://github.com/onnx/onnx/blob/d94a749aab901ebc94338bed1730f3ca496e7168/onnx/backend/test_rnn.py#L322) should be avoided.

One solution is to use test names and allow a regex filter to disable tests at each individual backend level. I can go ahead and submit a PR if people agree this is a good idea.

**Comment by bddppq** [comment]
Yes I agree this shouldn't happen, I will make a commit to fix it. Most test cases in backend test were initially created in the onnx-caffe2 repo, I guess this is one of the places I forgot to clean up when doing the transition.

Each test case has name (e.g. "test_slice", "test_squeezenet"), and they are standard python `unittest.TestCase`, I think python test drivers already have provided functionalities to do the filtering.

btw. We want to beef up the Backend Test, feel free to contribute test cases to increase coverage :-)

**Comment by tjingrant** [comment]
@bddppq sure thing, we have written quite a bit of tests in our onnx-tf repository, will look at what we can contribute.

**Comment by bddppq** [comment]
#200
