### ISSUE TITLE
Must the inputs to a GraphProto have unique names?

### ISSUE THREAD

**Issue by newling** [onnx/onnx#1946]
It doesn't say so in onnx.proto,  

```
// The inputs and outputs of the graph.
  repeated ValueInfoProto input = 11;
  repeated ValueInfoProto output = 12;
```

but maybe it should?

**Comment by gramalingam** [comment]
Yes, they are supposed to be unique. See: https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph

**Comment by newling** [comment]
Ok, thanks for the link.
