### ISSUE TITLE
No conversion function registered for op type SoftmaxActivation yet.

### ISSUE THREAD

**Issue by AnaRhisT94** [onnx/onnx#1954]
AttributeError: No conversion function registered for op type SoftmaxActivation yet.

Hi, would love to know if there'll be an extension that will take care of the Softmax Activation anytime soon.

Also, should I just use another activation instead with my mxnet model and re-train it?
If so, which activation are you currently supporting? 
from this link: https://openii.cn/ai/mxnet/commit/7d91602ba771d973360f8a0c66c976c67f700aa3
it seems like softrelu, sigmoid, softsign, how can I confirm it?

**Comment by kovtun77** [comment]
"SoftmaxActivation" is deprecated. Use "softmax" with axis=1 instead.
See [this](https://github.com/onnx/onnx/issues/2000) answer and manual for [SoftmaxActivation](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.SoftmaxActivation) and [softmax](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.softmax).

**Comment by prasanthpul** [comment]
Please reopen if @kovtun77's answer is not sufficient

**Comment by mnakhaeecourse** [comment]
I have encoutered the same problem what is the solution?

**Comment by Cocoalate** [comment]
Hi, same question. Alhough my original model is mtcnn. Any success yet?
