### ISSUE TITLE
Linking against onnx_proto on windows

### ISSUE THREAD

**Issue by ayermolo** [onnx/onnx#1961]
I am building a project that links against onnx_proto in Visual Studio. I am running in to an issue that I need to create two seperate folders. One for debug, and one for release. This is because in cmake it calls add_msvc_runtime_flag(onnx_proto). Which explicitly sets either /MD or MDd depending on CMAKE_BUILD_TYPE. With visual studio you can emit -DCMAKE_BUILD_TYPE, and it chooses automatically. Commenting out, experimentally, the call fixes the issue. I can have one solution, and just choose in it between debug and release. Is this call really necessary, can it be optional or something?

**Comment by askhade** [comment]
#2452 adds the change in utils.cmake to correctly set the options based on build configurations. This PR should fix this issue.
