### ISSUE TITLE
Does Onnx support 8bit or 16bit quantization?

### ISSUE THREAD

**Issue by yizhaoyanbo** [onnx/onnx#1972]
Does ONNX support 8bit or 16bit quantization? I have converted my pytoch model to ONNX. And I wanna to quantize the ONNX model  to 8bit model.  I am looking for a proper tool to do the convertion. thanks.

**Comment by prasanthpul** [comment]
@linkerzhang

**Comment by asweh** [comment]
ارجو مساعده بي سترجاع حسابي

**Comment by zhyj3038** [comment]
I am doing the same work. but I found some difficult.
the node name of pytorch model and onnx model are not same. so we can not quantize pytorch model.
but  I can not get activation values with onnx model ,so this way also hopeless.

**Comment by mkwml** [comment]
> U can directly quantization the pytorch model, I have done the work

hi, what the quantization tool u have used?

**Comment by linkerzhang** [comment]
To clarify, ONNX repo itself does not have a tool to do the quantization, but has the spec of supporting 8bit quantization (with a small set of ops).

**Comment by zhyj3038** [comment]
> > U can directly quantization the pytorch model, I have done the work
> 
> hi, what the quantization tool u have used?

there is no tools.  following tensorRT's method and coding
