### ISSUE TITLE
ONNX does not support iterations?

### ISSUE THREAD

**Issue by MuruganR96** [onnx/onnx#1989]
ONNX does not support iterations in Pytorch

**Comment by ebarsoum** [comment]
Can you share the PT code? Which version of PT are you using?

**Comment by MuruganR96** [comment]
Sir actually i have pretrained pytorch model. this is a link for model GitHub repo (https://github.com/mozilla/TTS). this is an iterations based model. is it ppossible to convert tensorflow model.?

Thank you for your response @ebarsoum sir.

**Comment by spandantiwari** [comment]
@MuruganR96 - I am not exactly sure what you mean by iterations, ONNX supports Scan and Loop. If you have trouble converting the PyTorch model to ONNX, please open an issue in PyTorch GitHub repo with the code and export script. Thanks.
