### ISSUE TITLE
Op Request Arange

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#1992]
Similar to numpy.arange([start, ]stop, [step, ]dtype=None)

I think this signature is good enough :-)

**Comment by houseroad** [comment]
cc: @spandantiwari this may be useful in decoder case.

**Comment by spandantiwari** [comment]
@houseroad - yes, this could be useful. ONNX definitely needs more generator ops.

**Comment by wschin** [comment]
How about compose using Loop and define a FunctionProto for it?
