### ISSUE TITLE
Squeeze gives no error when axis selected shape entry is not 1.

### ISSUE THREAD

**Issue by vuzelac-cadence** [onnx/onnx#1993]
Editing `test_squeeze` in `tests/shape_inference_test.py`to remove axis 5 only (is not 1). Testing that the axis is removed passes.
```
def test_squeeze(self):  # type: () -> None
        graph = self._make_graph(
            [('x', TensorProto.FLOAT, (1, 3, 1, 1, 2, 2))],
            [make_node('Squeeze', 'x', 'y', axes=[5])],
            [])
        self._assert_inferred(graph, [make_tensor_value_info('y', TensorProto.FLOAT, (1, 3, 1, 1, 2))])
```

Per the documentation, this should raise error ?

**Comment by askhade** [comment]
Right this check has now been added to Squeeze operator's shape inference function. 
Closing this issue. @vuzelac-cadence  : please reopen it or create a new one if you have any concerns.
