### ISSUE TITLE
CategoryMapper should have cats_int64s and cats_strings as initializers instead of attribute

### ISSUE THREAD

**Issue by ke1337** [onnx/onnx#1994]
[CategoryMapper](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#aionnxmlcategorymapper) is a useful op to map strings to indices. For NLP models, it might be quite common to have multiple inputs that use the same mapping. With cats_int64s/cats_strings as attribute, the mapping table would be duplicated in all CategoryMapper nodes. It would be nice to have cats_int64s/cats_strings as initializers, to allow nodes to reuse the same mapping.

**Comment by linkerzhang** [comment]
@KeDengMS you'd want to change the attributes to be inputs actually, right?

**Comment by KeDengMS** [comment]
Yes
