### ISSUE TITLE
When will `aten::upsample_trilinear3d` be supported?

### ISSUE THREAD

**Issue by yxchng** [onnx/onnx#1999]
Currently I am facing the error

`
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_trilinear3d
`

Can I know when will the operation be supported?

**Comment by linkerzhang** [comment]
I'm assuming this is an error when exporting onnx model from pytorch, right? @spandantiwari @houseroad  may comment on it.

**Comment by houseroad** [comment]
Yes, this is a pytorch onnx exporter problem. I would suggest opening an issue in pytorch repo and close this one.

**Comment by linkerzhang** [comment]
close this one as it's tracked in pytorch side (which is correct :))
