### ISSUE TITLE
Running setup.py pytest on Windows debug build produces invalid STL iterator exception

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#2003]
Running debug build `setup.py pytest` off 5bde6371620b76302864bce90f521d72eda95d0e produces STL debug invalid iterator exception. Closer examination reveals that the optimizer code attempts to operate on invalid STL iterator.

> =================================================================== test session starts ====================================================================
platform win32 -- Python 3.6.7, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: C:\dev\onnx, inifile: setup.cfg, testpaths: onnx/test, onnx/examples
plugins: nbval-0.9.1
collected 1491 items
onnx\test\basic_test.py ....                                                                                                                          [  0%]
onnx\test\checker_test.py ................                                                                                                            [  1%]
onnx\test\elu_test.py .                                                                                                                               [  1%]
onnx\test\helper_test.py ......................                                                                                                       [  2%]
onnx\test\numpy_helper_test.py ............                                                                                                           [  3%]
onnx\test\optimizer_test.py ..................

![image](https://user-images.githubusercontent.com/11303988/57326475-6e1e7680-70c1-11e9-8703-5ce1427679ec.png)

![image](https://user-images.githubusercontent.com/11303988/57326515-88f0eb00-70c1-11e9-92fe-9844484fd3e6.png)

The issue appears to originate from this line of code:

![image](https://user-images.githubusercontent.com/11303988/57326566-aaea6d80-70c1-11e9-9530-6e8468a28f20.png)

With axes being of size 4 and bias_shape being of size 4, coding of
axes.begin() + 1 + bias_shape.size() attempts to seek the iterator past the end making it invalid and STL debug iterator asserts. Further attempt to subtract rank would not be valid either.

I am not fluent in the optimizer code but it seems prudent to calculate the iterator advance first in its entirety, before attempting to advance the iterator, grouping the arithmetic into parenthesis.

**Comment by linkerzhang** [comment]
#2004  merged
