### ISSUE TITLE
Adding Sparse Tensor support in ONNX

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#2008]
In a previous ONNX workshop, there was agreement to add SparseTensor support to ONNX. Please find a design document for this attached:
[SparseDesign.docx](https://github.com/onnx/onnx/files/3154766/SparseDesign.docx)

**Comment by gramalingam** [comment]
Adding updated design document:
[SparseDesign-V2.docx](https://github.com/onnx/onnx/files/3347252/SparseDesign-V2.docx)

**Comment by jxchenus** [comment]
I found that a GraphProto loses its sparse tensor initializer going through the optimizer:

#0 onnx::graphProtoToGraph (gp=..., nested=nested@entry=false)
at .../onnx/common/ir_pb_converter.cc:188
#1 0x0000000000568d3f in onnx::ImportModelProto (mp=...)
at .../onnx/common/ir_pb_converter.cc:338
#2 0x000000000054e39a in onnx::optimization::Optimizer::optimize (
this=this@entry=0x7fffffffcf00, mp_in=...)
at .../onnx/optimizer/optimize.h:26
#3 0x0000000000534d3c in onnx::optimization::Optimize (mp_in=..., names=...)
at .../onnx/optimizer/optimize.cc:32

Is this a known issue?

**Comment by jxchenus** [comment]
Filed a bug with more information for the above issue: https://github.com/onnx/onnx/issues/3009

**Comment by garymm** [comment]
Is this done? https://github.com/onnx/onnx/pull/2019 is merged.

**Comment by lokitoth** [comment]
@garymm Based on the design-doc, it seems like there are still more operators to be enlightened to sparse support (Add/Mul, etc.). 

@gramalingam: Will there be more work here to support additional operators?

**Comment by askhade** [comment]
SparseTensor was added to ONNX's type system starting this PR #3398 

I think we can close this issue now. In future will most likely need to extend more operators to support SparseTensor type but that can be tracked by a separate issue and it should be done on a case by case basis driven by models. 

@gramalingam  thoughts?
