### ISSUE TITLE
is sizeof(AttributeKind) correct? 

### ISSUE THREAD

**Issue by one-hello** [onnx/onnx#2011]
file:ir.h line:90 
ONNX_ASSERT(size_t(kind) < sizeof(names) / sizeof(AttributeKind));  ==> ONNX_ASSERT(size_t(kind) < sizeof(names) / sizeof(const char*));

**Comment by linkerzhang** [comment]
good catch! the bug is never shown is because sizeof(AttributeKind) is 1, while sizeof(const char*) is 4. Do you mind to send PR to fix it?

**Comment by linkerzhang** [comment]
this is fixed by @one-hello . thank you!
