### ISSUE TITLE
optimization pass `split_init` breaks graph

### ISSUE THREAD

**Issue by okdshin** [onnx/onnx#2024]
I found the optimization pass `split_init` breaks graph. 

Script is this:
```
import os                                                              
import onnx                                                            
from onnx import optimizer                                             
                                                                       
                                                                       
def optimize(src_model_path, dst_model_path=None):                     
    if dst_model_path is None:                                         
        name, ext = os.path.splitext(src_model_path)                   
        dst_model_path = name + "optimized" + ext                      
    original_model = onnx.load(src_model_path)                         
                                                                       
    passes = ['split_init']  # <- here                                           
    optimized_model = optimizer.optimize(original_model, passes)       
    onnx.save(optimized_model, "_".join(passes) + "_" + dst_model_path)
                                                                       
                                                                       
if __name__ == '__main__':                                             
    import fire                                                        
    fire.Fire(optimize)                                                
```

I ran it with mobilenetv2-1.0 distributed [here](https://github.com/onnx/models/tree/master/models/image_classification/mobilenet).
```
python optimize_onnx_split_init.py mobilenetv2-1.0.onnx
```

We can see the graph by `netron`:
```
netron mnt/split_init_mobilenetv2-1.0optimized.onnx
```

`netron` shows like this:
![2019-05-17-15_32_00](https://user-images.githubusercontent.com/1490699/57907792-5e6d1200-78b9-11e9-89c0-01af58133c16.png)

For comparing, the original graph is this:
![2019-05-17-15_34_08](https://user-images.githubusercontent.com/1490699/57907898-a429da80-78b9-11e9-8774-5ca1f5144320.png)

All links are broken.
Other optimization passes doesn't break graph. `split_init` seems buggy.

**Comment by linkerzhang** [comment]
@okapies do you want to try a fix? :)

**Comment by okapies** [comment]
@linkerzhang Hi, is it really me you're mentioned? (He is my colleague but not the same person)

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have question related to the optimizer, please raise an issue there. Thank you!
