### ISSUE TITLE
KDTree support

### ISSUE THREAD

**Issue by lmiroslaw** [onnx/onnx#2026]
Hi Team,

For a project in particle physics we need to port KDTree algorithm to ONNX. Ultimately, we want to deploy the algorithm on Azure Data Box and run it on Intel FPGAs.

Here are a few references from SciPy:
https://scipy-cookbook.readthedocs.io/items/KDTree_example.html
https://scipy-cookbook.readthedocs.io/items/KDTree_example.html

We know you don't support KDTree today. How likely you can support it in near future based on its mathematical formula and algebra operations?

**Comment by wschin** [comment]
Here is a possible signature for KDTree operator and it can also support advanced GBDT models trained by LightGBM. Would it meet your requirements?

![image](https://user-images.githubusercontent.com/3524474/57974140-62a43880-7968-11e9-8700-37389c7fd456.png)

**Comment by ebarsoum** [comment]
This have been a while without activity, please activate if this still a priority.
