### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by WIll-Xu35** [onnx/onnx#2027]
Hi all,

I just finished installing protobuf 3.7.1 (download prebuilt one), and onnx 1.5.0 via pip3. But when I import onnx in python3, this error occurred: 'TypeError: __new__() got an unexpected keyword argument 'serialized_options''

I've searched online and someone suggest downgrade protobuf to 3.4.0, but I'm using Jetson TX2 as my developing environment and there is no prebuilt one for aarch64.

Any idea how to solve this issue?

Many thanks!

**Comment by RandySheriffH** [comment]
Do you have stack trace about the exception?

**Comment by raymondxyang** [comment]
What's the OS running on? The distributed onnx on pypi is built with old version of protobuf.

**Comment by WIll-Xu35** [comment]
@RandySheriffH @raymondxyang Thank you for your replies. I'll try to build the latest protobuf and onnx myself. The OS is L4T (Ubuntu 18.04) running on Nvidia Jetson TX2.

**Comment by tsaizhenling** [comment]
I'm observing the same issue with onnx 1.7.0 protobuf 3.4.0 on windows
