### ISSUE TITLE
ConstantOfShape backend tests omit input data type

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#2033]
Two backend tests for ConstantOfShape omit data type specification in the input. Such as [here](https://github.com/onnx/onnx/blob/819afd05a885921dd4dea066749ca08661daefc8/onnx/backend/test/case/node/constantofshape.py#L17).

The standard specifies that the input must be int64 but on different platforms python defaults integers either to in32 or int64 thereby resulting in test failures bc runtime expects int64.

Fixing the test requires regenerating test data in version 9. Is it doable?

**Comment by gramalingam** [comment]
If I understand the question right, yes: e.g., see: https://github.com/onnx/onnx/blob/5d0975f43c1224edce17177783b859fca4b8e2b1/onnx/backend/test/case/node/scan.py#L60

**Comment by yuslepukhin** [comment]
> 
> 
> If I understand the question right, yes: e.g., see:
> 
> https://github.com/onnx/onnx/blob/5d0975f43c1224edce17177783b859fca4b8e2b1/onnx/backend/test/case/node/scan.py#L60

The above does specify the type when creating input numpy arrays.

**Comment by yuslepukhin** [comment]
[This](https://github.com/onnx/onnx/commit/5c51f0dbbe88ee1536f17ee7bd462b2ab3772c52) addresses the issue
