### ISSUE TITLE
Onnx support DynamicSlice operator but without Operator Schemas info

### ISSUE THREAD

**Issue by hexiaoting** [onnx/onnx#2036]
When I convert tensorflow's inceptionv4 model to onnx, 
Operator StridedSlice from tensorfow is convert to DynamicSlice, But There is no information about DynamicSlice in onnx operator schema[https://github.com/onnx/onnx/blob/master/docs/Operators.md](url)

Does onnx use Slice operator to replace DynamicSlice in the future?

**Comment by prasanthpul** [comment]
DynamicSlice was an experimental operator that has been removed (experimental ops can be removed at any time with no backward compatibility, unlike regular ops). Older versions of the TF converter may have used this experimental op. Can you try using the latest converter (https://github.com/onnx/tensorflow-onnx) and see if you still see this?

**Comment by hexiaoting** [comment]
I convert Tensorflow model to ONNX follow this tutorial: [https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowExport.ipynb](url)
What's the difference between this tutorial that I used with tensorflow-onnx?

**Comment by prasanthpul** [comment]
We need to update that tutorial; it uses onnx-tf. The teams have since joined forces and you should use tensorflow-onnx for converting from TF to ONNX. onnx-tf will focus on ONNX to TF.

**Comment by hexiaoting** [comment]
I tried tensorflow-onnx to convert inceptionv4, No dynamicSlice operator anymore. StridedSlice is converted to Slice. Thank you @pranavsharma
