### ISSUE TITLE
Summary of Training Story in ONNX

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2038]
**PR #2314 contains minimal changes to enable training. It contains spec changes and introduces Gradient operator. Other operators such as optimizers and losses will be added in different PRs.**

The list below summarizes PRs related ONNX Training WG's progress.

For loss, one can see #1939.
For distinguishing behaviors of operators in training and inference phases, see #1887.
For optimizers, we have #1955, #1970, #1959.

**Comment by chinhuang007** [comment]
Should https://github.com/onnx/onnx/pull/2168 be added here?

**Comment by wschin** [comment]
@chinhuang007, yes! Thank you!
