### ISSUE TITLE
Build from source in ONNX 1.5.0

### ISSUE THREAD

**Issue by KeDengMS** [onnx/onnx#2039]
Was trying to install ONNX 1.5.0, but the version in conda-forge is 1.1.2, while pypi is 1.3.0.
Hit several issues when installing from source, including seg fault because of libprotobuf mismatch, lpthreads not found, etc. It would be nice if the wheels or build docs are updated.

Here's the steps that seems to work in Ubuntu 16.04, CMake 3.14, Conda 4.6.14:
```
conda create --name=onnx_py37 python=3.7.2 protobuf=3.6.1 pybind11=2.2 numpy scipy pytest
conda activate onnx_py37
pip install -e git://github.com/onnx/onnx#egg=onnx
```

**Comment by linkerzhang** [comment]
@RandySheriffH

**Comment by RandySheriffH** [comment]
Meet with similar issues lately, will sync with team and create a task refactoring the build process.

**Comment by RandySheriffH** [comment]
![image](https://user-images.githubusercontent.com/48490400/58515775-c8f43c80-815a-11e9-8a02-c5fdaac7b2fd.png)

**Comment by RandySheriffH** [comment]
Seems not working for windows.

**Comment by askhade** [comment]
@raymondxyang : I heard you were working on this issue.... Can you add your updates here...

**Comment by askhade** [comment]
@KeDengMS , @RandySheriffH  : Please take a look at PR #2452 and let me know if this fixes your issue

**Comment by askhade** [comment]
Closing this item as #2452 has been merged. Please reopen this issue or create a new one if you are stilling hitting any problems
