### ISSUE TITLE
Op request Std and Var

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2045]
There is `Mean` and even `Mod` but `Std` and `Var` are not implemented as separate operators. They are quite useful when normalizing inputs.
I first created the [issue here](https://github.com/microsoft/onnxruntime/issues/1086) because `aten::std` could not be exported.

**Comment by RanyaJumah** [comment]
Hi, 
Any update? since I failed to export Pytorch model contain var operation to ONNX :(

"RuntimeError: Exporting the operator var to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator." Thank you!

**Comment by garymm** [comment]
Var support was added to PyTorch ONNX export in https://github.com/pytorch/pytorch/pull/45678
Std was added in https://github.com/pytorch/pytorch/pull/22310

I think this can probably be closed.
@jcwchen can you close this please?

**Comment by jcwchen** [comment]
Sure. Thank you @garymm for the update! Close it now since they have been supported.
