### ISSUE TITLE
Op request, extend Flatten ops

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2046]
[Flatten](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Flatten) currently is too specific, please make it more generic to support [PyTorch's flatten](https://pytorch.org/cppdocs/api/function_namespaceat_1a55843006e38a3a24949dc0704598da87.html) with start and end dimension, instead of always returning 2D

```python
flatten(input, start_dim=0, end_dim=-1) -> Tensor

Flattens a contiguous range of dims in a tensor.

Args:
    input (Tensor): the input tensor
    start_dim (int): the first dim to flatten
    end_dim (int): the last dim to flatten

Example::

    >>> t = torch.tensor([[[1, 2],
                           [3, 4]],
                          [[5, 6],
                           [7, 8]]])
    >>> torch.flatten(t)
    tensor([1, 2, 3, 4, 5, 6, 7, 8])
    >>> torch.flatten(t, start_dim=1)
    tensor([[1, 2, 3, 4],
            [5, 6, 7, 8]])
Type:      builtin_function_or_method
```

**Comment by hariharans29** [comment]
Hi @dashesy,

I will address this request.

Thanks.

**Comment by postrational** [comment]
@hariharans29 Please add a link to your PR here when it's ready.
