### ISSUE TITLE
MeanVarianceNormalization operator attribute "axes" should default to []

### ISSUE THREAD

**Issue by tedhtchang** [onnx/onnx#2047]
I think the attribute "axes" defined here https://github.com/onnx/onnx/blob/master/docs/Operators.md#meanvariancenormalization default should be changed to [], an empty list of ints, since the input tensor no longer has the shape [N,C,H,W]. 
Also, consider add note to explain "C-coordinate" or remove it.

**Comment by dashesy** [comment]
Better yet would be to support flexible reduction span, that does not know anything about C,H,W. I currently use [this](https://github.com/pytorch/pytorch/issues/20867) implementation (that is from Caffe) and `across_channels` in that case reduces all C,H,W. 

`MeanVarianceNormalization` could accept a `start_axis=0` and `end_axis=-1` to be generic enough.

**Comment by hobei** [comment]
@dashesy MeanVarianceNormalization currently axes with a default of of 0, 2, 3. Not sure how this can be represented with just 'start_axis' & 'end_axes'. 

On another note the MeanVarianceNormalization can use ReduceMean internally. This also takes a list of axes. We would need to modify ReduceMean also.

Maybe alternative would be to too add an additional 'exclude_axes' attribute. By default it is empty and does not exclude any axes, where as 'axes' includes all axes when empty. If you then have [N,C, D1, D2,..,Dn] you could have 'exclude_axes' set to (1) to normalize over all but "C". You would need to check to make sure you have not included & excluded the same axes
