### ISSUE TITLE
Troubles I met when trying to update docs

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#2049]
I ran [tools/update_doc.sh](tools/update_doc.sh) to update the docs.

I found

1. **(solved by myself in #2478)** The version of ONNX schema version [has been updated to 11](https://github.com/onnx/onnx/blob/master/onnx/defs/schema.h#L652), however, the onnx model has not been uploaded. For example, https://s3.amazonaws.com/download.onnx/models/opset_11/bvlc_alexnet.tar.gz is an invaild url.

   When running `tools/update_doc.sh`, the urls in `data.json` are edited to opset 11 ([link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/cmd_tools.py#L36) and [link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/model/__init__.py#L61)), and are loaded in [link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/loader/__init__.py#L45). **As a result, the process of updating docs cannot succeed.**

   The download will be skipped if there are already models of the same name on the disk. This could be the reason why the problem got ignored. However, **this problem prevents new contributors from contributing to ONNX.** 

1. **(Solved by myself in #2050)** The script echoes "Please run this script in the ONNX root folder" when "onnx/defs/gen_doc.py" _exists_.

1. **(Solved by myself in #2050)** The script runs `python setup.py develop` without `--user`. So the script can only be run as a root user. It's not the best practice. What's more, the script will create or edit many files, and they will be all owned by root. As a result, the regular user cannot delete, edit or git add them anymore without running chown manually. 

1. **(Unsolved)** I got the following error when running onnx/defs/gen_doc.py.

   > Traceback (most recent call last):
   >   File "/home/daquexian/repos/onnx/onnx/defs/gen_doc.py", line 350, in <module>
   >     main(Args)
   >   File "/home/daquexian/repos/onnx/onnx/defs/gen_doc.py", line 240, in main
   >     s += display_schema(schema, [schema])
   >   File "/home/daquexian/repos/onnx/onnx/defs/gen_doc.py", line 196, in display_schema
   >     type_constraint.type_param_str, allowedTypeStr)
   > UnboundLocalError: local variable 'allowedTypeStr' referenced before assignment

   After digging into it, I found a strange thing

   ```python
   Python 3.7.3 (default, Mar 26 2019, 21:43:19)
   [GCC 8.2.1 20181127] on linux
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import onnx
   >>> a=onnx.defs.get_all_schemas_with_history()[1]
   >>> a.type_constraints[0].allowed_type_strs
   ['tensor(float)', 'tensor(double)', 'tensor(int64)', 'tensor(int32)']
   >>> a.type_constraints[0].allowed_type_strs
   []
   >>> a.inputs[0].name
   'X'
   >>> a.inputs[0].name
   ''
   ```
   It is this strange thing that causes the above error. However I don't know the reason. It only happens when installing onnx by `python setup.py install` but not installing wheel from pypi. I validated it on both python 3.7 and python 3.6.

**Comment by daquexian** [comment]
I proposed a PR to solve 2 and 3 https://github.com/onnx/onnx/pull/2050. For 4 I have no idea the problem is only on my side or it is a common problem.

**Comment by daquexian** [comment]
My steps to reproduce No.4:
1. Run `pip uninstall onnx` repeatedly until the existing onnx is completely uninstalled
1. Install onnx by `python setup.py install`
1. Run onnx/defs/gen_doc.py

**Comment by pkourdis** [comment]
Hitting also No.4 issue with ONNX v1.4.0. Maybe there is some issue with the Python bindings to C++.

**Comment by daquexian** [comment]
@pkourdis My workaround:

```patch
From 8964e446d2c33368d3bf8011ff103733a52c9f77 Mon Sep 17 00:00:00 2001
From: daquexian <daquexian566@gmail.com>
Date: Thu, 23 May 2019 11:05:40 +0800
Subject: [PATCH] Fix gen_doc.py

---
 onnx/defs/gen_doc.py | 16 ++++++++++++----
 1 file changed, 12 insertions(+), 4 deletions(-)

diff --git a/onnx/defs/gen_doc.py b/onnx/defs/gen_doc.py
index bc30dad7..6937e35d 100644
--- a/onnx/defs/gen_doc.py
+++ b/onnx/defs/gen_doc.py
@@ -210,6 +210,14 @@ def support_level_str(level):  # type: (OpSchema.SupportType) -> Text
         "<sub>experimental</sub> " if level == OpSchema.SupportType.EXPERIMENTAL else ""
 
 
+class Schema(object):
+    def __init__(self, i):
+        self.i = i
+
+    def __getattr__(self, item):
+        return getattr(defs.get_all_schemas_with_history()[self.i], item)
+
+
 def main(args):  # type: (Type[Args]) -> None
     with io.open(args.changelog, 'w', newline='') as fout:
         fout.write('## Operator Changelog\n')
@@ -220,8 +228,8 @@ def main(args):  # type: (Type[Args]) -> None
 
         # domain -> version -> [schema]
         dv_index = defaultdict(lambda: defaultdict(list))  # type: Dict[Text, Dict[int, List[OpSchema]]]
-        for schema in defs.get_all_schemas_with_history():
-            dv_index[schema.domain][schema.since_version].append(schema)
+        for i, schema in enumerate(defs.get_all_schemas_with_history()):
+            dv_index[schema.domain][schema.since_version].append(Schema(i))
 
         fout.write('\n')
 
@@ -251,8 +259,8 @@ def main(args):  # type: (Type[Args]) -> None
 
         # domain -> support level -> name -> [schema]
         index = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))  # type: Dict[Text, Dict[int, Dict[Text, List[OpSchema]]]]
-        for schema in defs.get_all_schemas_with_history():
-            index[schema.domain][int(schema.support_level)][schema.name].append(schema)
+        for i, schema in enumerate(defs.get_all_schemas_with_history()):
+            index[schema.domain][int(schema.support_level)][schema.name].append(Schema(i))
 
         fout.write('\n')
 
-- 
2.21.0
```

**Comment by pkourdis** [comment]
@daquexian thank you, works great!

**Comment by daquexian** [comment]
@pkourdis My pleasure :)

@prasanthpul @linkerzhang @houseroad Any ideas on No.4? :) It's a common problem and breaks documentation updating without the above hacky workaround.

**Comment by raymondxyang** [comment]
I am taking a look... got same issue reported earlier

**Comment by daquexian** [comment]
@raymondxyang Is there any progress? Thanks! :)

**Comment by daquexian** [comment]
@raymondxyang @prasanthpul @houseroad I really think this issue needs more attention than it receives now. Even though it is hard to fix problem 4, it is relatively easy and definitely needed to update models to fix problem 1.

**Comment by daquexian** [comment]
What's more, I always have a mess of diff on the generated models:

![image](https://user-images.githubusercontent.com/11607199/63659840-45dc9400-c7e6-11e9-9c0b-6f4781aff59c.png)

I believe not only me are suffering from these problems. I'm very curious that how did other people propose their PRs

**Comment by daquexian** [comment]
Details about problem 1:

When running `tools/update_doc.sh`, the urls in `data.json` are edited to opset 11 ([link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/cmd_tools.py#L36) and [link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/model/__init__.py#L61)), and are loaded in [link](https://github.com/onnx/onnx/blob/master/onnx/backend/test/loader/__init__.py#L45). As a result, tools/update_doc.sh fails since they are trying to download invalid opset 11 urls.

The download will be skipped if there are already models of the same name on the disk. This could be the reason why the problem got ignored.

**Comment by wschin** [comment]
For (1), could we have the script to download the model from the latest version number? For example, it first trys downloading model_opset11, then model_opset10, etc, and stops once a download successes.

**Comment by daquexian** [comment]
> For (1), could we have the script to download the model from the latest version number? For example, it first tries downloading model_opset11, then model_opset10, etc, and stops once a download successes.

Thanks for your attention! I'm afraid it may cause the following case: 

1. model A in opset 10 is downloaded successfully 

2. model B in opset 10 exists but the download fails due to network error, then model B in opset 9 is downloaded.

In this case, the opset version will be inconsistent. How about maintaining a "latest release version"? It is worthwhile to be maintained anyway.

**Comment by wschin** [comment]
Is network problem a real problem? We can rerun the script if `git diff` or the CI build shows something wrong. On the other hand, we can maintain the latest version number for each model, but it would slight decrease the maintainability of the code (after updating a model, the author needs to update the corresponding version number in this codebase).

**Comment by daquexian** [comment]
> we can maintain the latest version number for each model, but it would slight decrease the maintainability of the code

Is there a unified opset version for all models (instead of latest version for each model)? For example, currently all opset 10 urls are valid.

**Comment by wschin** [comment]
> we can maintain the latest version number for each model, but it would slight decrease the maintainability of the code
> 
> Is there a consistent opset version for all models (instead of different version for each model)? For example, currently all opset 10 urls are valid.

In general no. It's hard to ask model owners to recreate a new model each time ONNX bump an opset version. On the other hand, model zoo owner should make sure the official models are always update-to-date.

**Comment by daquexian** [comment]
> In general no. It's hard to ask model owners to recreate a new model each time ONNX bumps an opset version. On the other hand, model zoo owner should make sure the official models are always update-to-date.

I think models from the model zoo are only needed

**Comment by kit1980** [comment]
Any update on No.4? Got the same issue today.
`>>> a.type_constraints[0].allowed_type_strs []` basically means ONNX can not be installed correctly from source in this case...

**Comment by daquexian** [comment]
> Any update on No.4? Got the same issue today.
> `>>> a.type_constraints[0].allowed_type_strs []` basically means ONNX can not be installed correctly from source in this case...

Does the workaround https://github.com/onnx/onnx/issues/2049#issuecomment-499387816 work for you?

**Comment by kit1980** [comment]
> Any update on No.4? Got the same issue today.
> >>> a.type_constraints[0].allowed_type_strs [] basically means ONNX can not be installed correctly from source in this case...
> 
> Does the workaround #2049 (comment) work for you?

Yes, it works, thanks.
But this is not right and the underlying onnx installation is till broken at least in some sense.

**Comment by daquexian** [comment]
> > Any update on No.4? Got the same issue today.
> > > > > a.type_constraints[0].allowed_type_strs [] basically means ONNX can not be installed correctly from source in this case...
> > 
> > 
> > Does the workaround #2049 (comment) work for you?
> 
> Yes, it works, thanks.
> But this is not right and the underlying onnx installation is still broken at least in some sense.

I sometimes feel that onnx is unfriendly to the community :| Fresh contributors will come across No.1 and No.4 problems and feel exhausted
