### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError with upsample

### ISSUE THREAD

**Issue by wsl1014** [onnx/onnx#2056]
onnx.onnx_cpp2py_export.checker.ValidationError: Op registered for Upsample is depracted in domain_version of 1

Can anybody help me???
3Q

**Comment by wsl1014** [comment]
um...Change the version to 1.2.2 will work..... The way of changing version I used was wrong before,,,

**Comment by yuzhiyiliu** [comment]
Your version of onnx is 1.5.0? try onnx==1.4.1?
