### ISSUE TITLE
How to convert MXNet object dection models to ONNX?

### ISSUE THREAD

**Issue by tengdai722** [onnx/onnx#2059]
It seems that there are set op operators under "contrib" not supported by ONNX, and most if not all MXNet object detection models using those operators. Will it be possible those get supported? Or is there any alternative way to convert those models to ONNX?

**Comment by prasanthpul** [comment]
This seems like a MXNet-specific issue. Can you file this on the MXNet github https://github.com/apache/incubator-mxnet so the right experts can take a look?
