### ISSUE TITLE
Op request, more Resize options

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2062]
[Resize](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize) currently only accepts `mode` (`linear` or `nearest`). But to get full compatibility with PyTorch's [interpolate](https://pytorch.org/docs/stable/nn.html#interpolate) `Resize` should also have the option for `align_corners` as well as `size`. 
1. `align_corners` is important when we want to keep the scale be size-invariant.
2. `size` is important when we want to resize to a fixed size. When the input shape is dynamic, it is easier than relying on `scales` to find the correct aspect ratio, plus `size` avoid the need to floating point division to find `scales`.
3. 'area' mode (less critical, but 'area' usually produces better results for resizing)

**Comment by ebarsoum** [comment]
Merged.
