### ISSUE TITLE
Op Request NonMaxSuppression More Options

### ISSUE THREAD

**Issue by saurabh-shandilya** [onnx/onnx#2063]
NonMaxSuppression in its current form has only one output of size  [num_selected_indices, 3]. num_selected_indices can potentially change for every input depending on the data-content. Can we add following 2 along the lines of Tensorflow NonMaxSuppressionV4 -
a) an additional output to indicate valid indices chosen along with b)
b) an additional input/attribute to indicate if the index output is padded to have [max_output_boxes_per_class *num_classes , 3] sized output, thus supporting static shapes (more opportunities for optimization)

The current implementation also limits the same box to be shared across all the classes. This may not be the case with networks like FRCNN. Why can't we add an attribute to indicate if the box is shared across the classes and depending on that  box input can be either 
 [num_batches, 1, spatial_dimension, 4] or [ [num_batches, num_classes, spatial_dimension, 4]?

**Comment by zacario-li** [comment]
> NonMaxSuppression in its current form has only one output of size [num_selected_indices, 3]. num_selected_indices can potentially change for every input depending on the data-content. Can we add following 2 along the lines of Tensorflow NonMaxSuppressionV4 -
> a) an additional output to indicate valid indices chosen along with b)
> b) an additional input/attribute to indicate if the index output is padded to have [max_output_boxes_per_class *num_classes , 3] sized output, thus supporting static shapes (more opportunities for optimization)
> 
> The current implementation also limits the same box to be shared across all the classes. This may not be the case with networks like FRCNN. Why can't we add an attribute to indicate if the box is shared across the classes and depending on that box input can be either
> [num_batches, 1, spatial_dimension, 4] or [ [num_batches, num_classes, spatial_dimension, 4]?

I agree with you.

**Comment by ebarsoum** [comment]
Can you submit a PR?

**Comment by saurabh-shandilya** [comment]
Is someone working on this?

**Comment by ksaurabh-cadence** [comment]
@spandantiwari I believe the issue is assigned to you. When can we expect this op to be available? :-) Thanks.

**Comment by spandantiwari** [comment]
@ksaurabh-cadence - If you are asking about the op being included in ONNX, then that was done in some time ago. [NonMaxSupression](https://github.com/onnx/onnx/blob/master/docs/Operators.md#NonMaxSuppression)

**Comment by ksaurabh-cadence** [comment]
@spandantiwari That still doesn't have the extra options which were requested here - most importantly padding to make the output shape fixed instead of variable. I am not quite sure what changed between opset10 and opset11. They look same.

**Comment by Godricly** [comment]
Can we have a more generic definition of NMS? Because the metric may varies for different tasks. For myself, I'd prefer a NMS for quadrilaterals. But the current definition requires rectangles.
