### ISSUE TITLE
mxnet model convert to onnx:  No conversion function registered for op type LinearRegressionOutput yet.

### ISSUE THREAD

**Issue by eeqmcc** [onnx/onnx#2064]
INFO:root:Converting json and weight file to sym and params
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    converted_model_path = onnx_mxnet.export_model(sym, params, [(8,3,416,416),(8,14196),(8,84,26,26),(8,84,26,26),(8,100,5),(8,2),(8,3)], np.float32, onnx_file)
  File "C:\Users\sunbo\.conda\envs\mxnet-new\lib\site-packages\mxnet\contrib\onnx\mx2onnx\export_model.py", line 83, in export_model
    verbose=verbose)
  File "C:\Users\sunbo\.conda\envs\mxnet-new\lib\site-packages\mxnet\contrib\onnx\mx2onnx\export_onnx.py", line 253, in create_onnx_graph_proto
    idx=idx
  File "C:\Users\sunbo\.conda\envs\mxnet-new\lib\site-packages\mxnet\contrib\onnx\mx2onnx\export_onnx.py", line 90, in convert_layer
    raise AttributeError("No conversion function registered for op type %s yet." % op)
AttributeError: No conversion function registered for op type LinearRegressionOutput yet.

No matter which loss function I use, there will be a similar error.

the loss function:
`
            rpn_bbox_loss = mx.sym.LinearRegressionOutput(name='rpn_bbox_loss', data=rpn_bbox_pred2, label=rpn_bbox_target2)
`

this is my convert code:
```
import mxnet as mx
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet
import logging
logging.basicConfig(level=logging.INFO)

sym='./SNIPER-symbol.json'
params='./SNIPER-0002.params'
input_shape=(8,3,416,416)
onnx_file='./out.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [(8,3,416,416),(8,14196),(8,84,26,26),(8,84,26,26),(8,100,5),(8,2),(8,3)], np.float32, onnx_file)
```

and this is my weights file and symbol file:
SNIPER-symbol.json:
https://drive.google.com/open?id=1oonndx3snHrJhpMbI8A1PhsHXp4EaJ-m
SNIPER-0002.params
https://drive.google.com/open?id=1fOyIxydTjlZHvXSTDkSzhuBAx3Ln1CB4

menet version: 1.4.0
python: 3.6.8
cuda: 9.0
cudnn: 7.5
system: windows10, 64bits

**Comment by prasanthpul** [comment]
This looks like an issue with the MXNet exporter. Can you file this issue at https://github.com/apache/incubator-mxnet for the MXNet experts to take a look?
