### ISSUE TITLE
Requirements on PRs of Proposing ONNX Operators

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2066]
The major goal of ONNX is to make deep neural networks and some classical machine learning models portable. Due to the mathematical nature of AI, we have standardized a lot mathematical operations such as convolution and matrix multiplication. However, I often observe that operator signature misses important information. For example, in ConvTranspose's signature, there is no mathematical equations to describe ConvTranspose's actual behavior, so the reader cannot see how to compute the output from the given inputs. It means that we define an operator which still has undefined behavior. The same thing happens to RoiAlign and Conv. It seems that we tend to save time when formally defining complicated operators.

Also, sometime I find operator proposals without a well-defined motivation and a proper validation procedure. We can't just say `ONNX should add operator to support a TF module`. We need to see `how the targeted TF module runs and how the proposed signature fills the gap`. To this end, for each operator proposal, the author needs to provide a Python reference implementation (which can only depends on numpy) and compare the reference implementation's outcome against the targeted TF module. 

Consequently, I'd suggest adding the following items to be `must-to-have` in each ONNX operator PR.

1. Some mathematical equations to describe the proposed operator's behavior if it’s a math operator. The author can use pseudo code instead if the proposed operator has nothing to do with math.
2. The PR should contain a Python reference implementation of the proposed operator.
3. The PR should use the reference implementation to create tests.
4. A python script to compare the reference implementation's output and the targeted module's output.

If we have all of these items, we can gain some fundamental benefits.

1. It guarantees that the proposed signature solves the targeted problem.
2. All partners can have a simple implementation to start.
3. It eliminates the ambiguity carried by pure text, and ONNX really standardizes math equations. 

Any comments please?

**Comment by linkerzhang** [comment]
The key part of this proposal is the 2) The PR should contain a Python reference implementation of the proposed operator.

@xinlicai showed a great auto-test tool in last ONNX workshop. The tool indeed covers "python reference implementation" for existing ops. It will be very good if this tool can be leveraged and be expanded when adding more ops.

**Comment by wschin** [comment]
I also think we should enforce that `for operators which can be composed by less than 10 primitives, they must be proposed as functions`.

**Comment by linkerzhang** [comment]
FYI. The auto-test tool from Alibaba was pushed out https://github.com/alibaba/sionnx.

**Comment by ebarsoum** [comment]
Here the updated criteria: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md
