### ISSUE TITLE
Node & operator version match

### ISSUE THREAD

**Issue by Rasterer** [onnx/onnx#2067]
Hi, I have some questions about operator & node version match.

- Is it allowed to use an old operator version in a model, i.e. use a version which is not the highest in current opset? If yes, how to do node & operator version matching? I don't find any version info in NodeProto

- Does onnx implementation need only implement the highest version operators in one opset, or it should implement all old versions?

**Comment by linkerzhang** [comment]
https://github.com/onnx/onnx/blob/master/docs/Versioning.md gives you some idea about the overall versioning design.

to answer your question:
1. Yes, it's allowed. 
2. It's up to the onnx partner. it's not a "MUST" to implement all old versions.

To clarify more,
1. NodeProto does not have version. A model has "opset_import" https://github.com/onnx/onnx/blob/master/onnx/onnx-ml.proto#L210 showing which operator domain+version this model is using. For one model, it can use multiple operator sets from multiple domains, but, for one domain, the model can refer to only one operator set version at most.
2. ONNX partners have the flexibility of implementing any operator set version. However, it does also mean, the partner will only be able to run ONNX models which are using the specific set of operator set versions (implemented).

**Comment by Rasterer** [comment]
Got it, thank you for your detail clarification!
