### ISSUE TITLE
Question about the Resize downsample_linear unit test

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx#2070]
I try to run the unit test for Resize operator by using the equivalent Tensorflow operator (tf.image.resize), I got the matching result for 3 of the test cases except the "downsample_linear" test case. 
In the test case it state that
output = np.array([[[[1, 2.66666651]]]], dtype=np.float32)
but when I run it using tf.image.resize I got this result back
output = tf.Tensor([[[[1. 3.]]]], shape=(1, 1, 1, 2), dtype=float32)
May someone please explain how the output is generated in the test case? Thanks

**Comment by daquexian** [comment]
The resize op will be updated in https://github.com/onnx/onnx/pull/2057. https://github.com/onnx/onnx/pull/2057#issuecomment-496053050 is about the existing test cases

**Comment by askhade** [comment]
Closing this issue. @winnietsang please reopen this or a new one in case you are still observing any issue.
