### ISSUE TITLE
Problem with version_converter

### ISSUE THREAD

**Issue by antonfr** [onnx/onnx#2072]
Hello, 
I have problem with version converter for some pre-trained models

```
import onnx
from onnx import version_converter
onnx_model = onnx.load('model.onnx')
converted_model = version_converter.convert_version(onnx_model, target_version = 7)
onnx.save(converted_model, 'model_7.onnx')
```

That works fine for AlexNet model. For Yolo models (both tiny and full), got the following error:
 
```
IndexError                                Traceback (most recent call last)
<ipython-input-12-ca7ddfad851d> in <module>()
----> 1 converted_model = version_converter.convert_version(onnx_model, target_version = 7)

//anaconda/lib/python3.6/site-packages/onnx/version_converter.py in convert_version(model, target_version)
    164         raise ValueError('VersionConverter only accepts int as target_version, incorrect type: {}'.format(type(target_version)))
    165     model_str = model.SerializeToString()
--> 166     converted_model_str = C.convert_version(model_str, target_version)
    167     return onnx.load_from_string(converted_model_str)

IndexError: unordered_map::at: key not found
```

**Comment by prasanthpul** [comment]
Did you already try:
converted_model = version_converter.convert_version(onnx_model, 7)

The Yolov3 model (https://github.com/onnx/models/tree/master/yolov3) cannot be down converted to opset 7 as it required ops that are only in opset10.
TinyYolo already has a opset 7 pretrained model, so you don't need to down convert it: https://github.com/onnx/models/tree/master/tiny_yolov2

**Comment by r4ghu** [comment]
Hi @antonfr, Did you make any progress with this issue?

**Comment by yashpatel5400** [comment]
I've also run into this issue (although through a slightly different entrypoint) -- has there been any resolution?

**Comment by padmasreenagarajan** [comment]
even i faced the same issue with YOLOV3,opset 9..i need opset 9 as opset 9 is only supported by TIDL (Texas instruments Deep Learning library) @yashpatel5400 @r4ghu @prasanthpul
