### ISSUE TITLE
Upsampling

### ISSUE THREAD

**Issue by zhly0** [onnx/onnx#2073]
Hi,in  the doc,onnx is support UpSampling,but I got error:
AttributeError: No conversion function registered for op type UpSampling yet.
onnx:1.5.0
mxnet:1.4.0

**Comment by prasanthpul** [comment]
You'll need to provide more info on where you are getting the error from.

But please note that Upsample is deprecated: https://github.com/onnx/onnx/blob/master/docs/Operators.md#upsample-deprecated

**Comment by zhly0** [comment]
@prasanthpul ,Thanks,I use mxnet operator upsampling,and I get the onnx doc from here:https://cwiki.apache.org/confluence/display/MXNET/ONNX+Operator+Coverage,it happens when I convert mxnet model to IR.my code is:
import mxnet as mx
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet

# Downloaded input symbol and params files
sym = r'symbol.json'
params = r'0000.params'
# Standard Imagenet input - 3 channels, 224*224
input_shape = (1,3,640,640)
# Path of the output file
onnx_file = r'mxnet_exported_resnet50.onnx'

# Invoke export model API. It returns path of the converted onnx model
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)

**Comment by irmowan** [comment]
@zhly0 Same problem as you meet. How do you solve it?
