### ISSUE TITLE
Graph splitting in ONNX model

### ISSUE THREAD

**Issue by lsy323** [onnx/onnx#2078]
Hi all,

I'm new to ONNX and I have a question about splitting the ONNX model.

Does ONNX has APIs to get a part of the model, given the inputs and outputs ports?

For example, we have a model input->fc1->fc2->fc3->output, but we want a new graph which is a part of the original graph, say new_input->fc1->fc2->new_output.

Thanks a lot!

**Comment by gramalingam** [comment]
You can use the python API to transform the model as needed. E.g. as below. It is slightly awkward as we need to use Protobuf's API for working with collections (like nodes).
```python
def transform(model):
    oldnodes = [n for n in model.graph.node]
    newnodes = oldnodes[0:2] # or whatever
    del model.graph.node[:] # clear old nodes
    model.graph.node.extend(newnodes)

def apply(transform, infile, outfile):
    model = onnx.load(infile)
    transform(model)
    onnx.save(model, outfile)
```

**Comment by lsy323** [comment]
Hi @gramalingam 

Thanks for the example. Look like we need to use Protobuf API to modify the structure of an ONNX model
