### ISSUE TITLE
Resize-mxnet

### ISSUE THREAD

**Issue by zhly0** [onnx/onnx#2079]
Hi，onnx，
    I want to add resize op in mxnet：since there is no resize in it：https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/contrib/onnx/mx2onnx/_op_translations.py，I refered to this：
https://github.com/onnx/onnx/blob/b605eafbd4299dda6be91a0cc8bbf2d8622965ec/docs/Operators.md#Resize，the inputs of  resize 's make_node need two args,one is real inputs,the other is the reszie scale,but when seeting the scale ,the graph checher said:  File "C:\Users\Administrator\AppData\Roaming\Python\Python36\site-packages\onn
x\checker.py", line 52, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topolo
gically sorted, however input '2' of node:

my code is :

@mx_op.register("Resize")
def convert_Resize(node, **kwargs):
    name, input_nodes, attrs = get_inputs(node, kwargs)
    scales = '1.,1.,2.,2.'
    upsampling_node = onnx.helper.make_node(
        "Resize",
        inputs=[input_nodes[0],'2'],
        outputs=[name],
        mode='nearest',
        name=name
    )
    return [upsampling_node] 

it seems get stucked into a circle.one inputs is not allowed,two inputs the checker will make the scale parameter  as a node in the graph.

**Comment by Joe2loft** [comment]
hi， when I try to transform retinaface  from PyTorch to Onnx to Mxnet，I meet the same promble，mxnet doesn't support resize op，have you sloved this problem?
