### ISSUE TITLE
What is the correct way to use Loop operator

### ISSUE THREAD

**Issue by itamargr** [onnx/onnx#2082]
Hi. I am trying to use loop operator fro the following loop:
```
a = 3
b = 6
keep_going = True
max_trip_count = 10
user_defined_vals = []
for i in range(max_trip_count):
    if not keep_going:
        break
    my_local = a + b
    b = a - b
    keep_going = my_local > b
    user_defined_vals.append(b + b)
b_out = b
keep_going_out = keep_going
```
The expected output is of the code is `b=6` and `user_defined_vals=[-6, 12]`

When I try to mimic the loop using onnx in this way:
```
import onnx.helper as helper
from onnx import TensorProto
import numpy as np
from onnxruntime.backend import prepare


# Create the body network
body = helper.make_graph(
    [
        helper.make_node("Add", ["a", "b"], ["my_local"]),
        helper.make_node("Sub", ["a", "b"], ["b"]),
        helper.make_node("Greater", ["my_local", "b"], ["keep_going"]),
        helper.make_node("Add", ["b", "b"], ["user_defined_vals"]),
    ],
    "body",
    [
        helper.make_tensor_value_info('iteration_num', TensorProto.INT64, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1])
    ],
    [
        helper.make_tensor_value_info('keep_going', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('my_local', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals', TensorProto.FLOAT, [1]),
    ]
)

# Create the outer network
graph_proto = helper.make_graph(
    [
        helper.make_node("Loop", ["max_trip_count", "keep_going_inp", "b"],
                         ["b", "my_local", "user_defined_vals"], body=body)
    ],
    "outer",
    [
        helper.make_tensor_value_info('a', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('max_trip_count', TensorProto.INT64, [1]),
    ],
    [
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals', TensorProto.FLOAT, [10, 1]),
    ]
)
model = helper.make_model(graph_proto)

# Run the network
a = np.array([3], dtype=np.float32)
b = np.array([6], dtype=np.float32)
keep_going = np.array([True], dtype=np.bool)
max_trip_count = np.array([10], dtype=np.int64)
model_rep = prepare(model)  # Import the ONNX model to onnxruntime
out = model_rep.run([a, b, keep_going, max_trip_count])

```
and I got an error: 
>   File "/usr/local/lib/python3.5/dist-packages/onnxruntime/backend/backend.py", line 75, in prepare
>     check_model(model)
>   File "/usr/local/lib/python3.5/dist-packages/onnx/checker.py", line 86, in check_model
>     C.check_model(model.SerializeToString())
> onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'b' has been used as output names multiple times.
> 
> ==> Context: Bad node spec: input: "max_trip_count" input: "keep_going_inp" input: "b" output: "b" output: "my_local" output: "user_defined_vals" op_type: "Loop" attribute { name: "body" g { node { input: "a" input: "b" output: "my_local" op_type: "Add" } node { input: "a" input: "b" output: "b" op_type: "Sub" } node { input: "my_local" input: "b" output: "keep_going" op_type: "Greater" } node { input: "b" input: "b" output: "user_defined_vals" op_type: "Add" } name: "body" input { name: "iteration_num" type { tensor_type { elem_type: 7 shape { dim { dim_value: 1 } } } } } input { name: "keep_going_inp" type { tensor_type { elem_type: 9 shape { dim { dim_value: 1 } } } } } input { name: "b" type { tensor_type { elem_type: 1 shape { dim { dim_value: 1 } } } } } output { name: "keep_going" type { tensor_type { elem_type: 9 shape { dim { dim_value: 1 } } } } } output { name: "b" type { tensor_type { elem_type: 1 shape { dim { dim_value: 1 } } } } } output { name: "my_local" type { tensor_type { elem_type: 1 shape { dim { dim_value: 1 } } } } } output { name: "user_defined_vals" type { tensor_type { elem_type: 1 shape { dim { dim_value: 1 } } } } } } type: GRAPH }

When I try to change the network to
```
body = helper.make_graph(
    [
        helper.make_node("Add", ["a", "b"], ["my_local"]),
        helper.make_node("Sub", ["a", "b"], ["b_loop"]),
        helper.make_node("Greater", ["my_local", "b_loop"], ["keep_going"]),
        helper.make_node("Add", ["b_loop", "b_loop"], ["user_defined_vals"]),
    ],
    "body",
    [
        helper.make_tensor_value_info('iteration_num', TensorProto.INT64, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1])
    ],
    [
        helper.make_tensor_value_info('keep_going', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('b_loop', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('my_local', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals', TensorProto.FLOAT, [1]),
    ]
)

# Create the outer network
graph_proto = helper.make_graph(
    [
        helper.make_node("Loop", ["max_trip_count", "keep_going_inp", "b"],
                         ["b_loop", "my_local", "user_defined_vals"], body=body)
    ],
    "outer",
    [
        helper.make_tensor_value_info('a', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('max_trip_count', TensorProto.INT64, [1]),
    ],
    [
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals', TensorProto.FLOAT, [10, 1]),
    ]
)
model = helper.make_model(graph_proto)
```
the network runs, but I get `b=6` and `user_defined_vals=[-6, -6, ..., -6] (10 times)` and it looks like `b` did not change during the loop and `b_loop` tensor is not connected to `b` tensor as I expected.

How do I operate Loop layer correctly ?

Thanks, Itamar

**Comment by gramalingam** [comment]
It looks like you specified "b" as the output of the "outer" graph. Can you change it to "b_loop" which represents the updated b? Can you also try changing the "b" in the body graph to "b_in" (just to diagnose things)? There could be some ambiguity/bug when a subgraph's input hides an outer scope name.

**Comment by skottmckay** [comment]
The subgraph's inputs and outputs are in a different scope to the outer graph values. So the 'b' that's an explicit input to the subgraph is a different instance to the outer scope 'b'. Updates within the loop would change this inner scope value, and return it using the name from the Loop outputs. 

It should have worked if your main graph output was 'b_loop' not 'b' (i.e the value the Loop operator is producing rather than the input to the Loop, as nothing updates a value in-place), but due to a bug in onnxruntime we end up with both 'b' values being passed in to subgraph execution, and the outer scope value happens to overwrites the graph input on each iteration and we lose the update from the previous iteration. I'll fix that.

For clarity it's probably better to not use outer scope names in the explicit subgraph inputs or outputs. The following should work with the current onnxruntime version, and will hopefully clarify what's happening a little:

```
body = helper.make_graph(
    [
        helper.make_node("Add", ["a", "b_in"], ["my_local"]),
        helper.make_node("Sub", ["a", "b_in"], ["a_sub_b_in"]),
        helper.make_node("Greater", ["my_local", "a_sub_b_in"], ["keep_going"]),
        helper.make_node("Add", ["a_sub_b_in", "a_sub_b_in"], ["user_defined_vals"]),
    ],
    "body",
    [
        helper.make_tensor_value_info('iteration_num', TensorProto.INT64, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('b_in', TensorProto.FLOAT, [1])
    ],
    [
        helper.make_tensor_value_info('keep_going', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('a_sub_b_in', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('my_local', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals', TensorProto.FLOAT, [1]),
    ]
)

# Create the outer network
graph_proto = helper.make_graph(
    [
        helper.make_node("Loop", ["max_trip_count", "keep_going_inp", "b"],
                         ["b_loop", "my_local_loop", "user_defined_vals_loop"], body=body)
    ],
    "outer",
    [
        helper.make_tensor_value_info('a', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('b', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('keep_going_inp', TensorProto.BOOL, [1]),
        helper.make_tensor_value_info('max_trip_count', TensorProto.INT64, [1]),
    ],
    [
        helper.make_tensor_value_info('b_loop', TensorProto.FLOAT, [1]),
        helper.make_tensor_value_info('user_defined_vals_loop', TensorProto.FLOAT, [2, 1]),
    ]
)
```

The 'b_in' value is provided to the subgraph execution based on the order of the arguments to Loop and not the input name. The subgraph produces an output called 'a_sub_b_in' which will be passed in to the subgraph execution during the next iteration as 'b_in' (again based on order not name). 

When the subgraph execution completes, the Loop node will output the final value of 'a_sub_b_in' as 'b_loop', and the accumulated values from user_defined_vals as user_defined_vals_loop.

**Comment by itamargr** [comment]
Thanks @skottmckay. It works
