### ISSUE TITLE
Op Request for MultiBoxDetection, MultiBoxPrior and MultiBoxTarget

### ISSUE THREAD

**Issue by anirudhacharya** [onnx/onnx#2086]
These operators are used in object detection models. Spec for the operators - 
 - [MultiBoxDetection](http://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=multibox#mxnet.ndarray.contrib.MultiBoxDetection) 
 - [MultiBoxPrior](http://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=multibox#mxnet.ndarray.contrib.MultiBoxPrior) 
 - [MultiBoxTarget](http://mxnet.incubator.apache.org/api/python/ndarray/contrib.html?highlight=multibox#mxnet.ndarray.contrib.MultiBoxTarget)

**Comment by ebarsoum** [comment]
Hi @anirudhacharya ,

Can you share the models that uses those operator?

Thanks,
Emad

**Comment by anirudhacharya** [comment]
@ebarsoum sorry for the late reply. 

SSD models use these operators. For example, here - https://github.com/apache/incubator-mxnet/blob/master/example/ssd/symbol/common.py#L289

**Comment by postrational** [comment]
Are frameworks other than MXNet using similar ops?
Can you point to documentation describing the specific calculations these ops do?

Is there any chance they could be implemented as `Function`s of more primitive ONNX ops?

**Comment by anirudhacharya** [comment]
> Are frameworks other than MXNet using similar ops?
Not sure
> Can you point to documentation describing the specific calculations these ops do?
the description of the issue each operator is linked to the documentation of the corresponding operator.
> 
> Is there any chance they could be implemented as `Function`s of more primitive ONNX ops?
It might be possible, I have not tried it.

**Comment by maclema** [comment]
Here is the source of the MXNet operators if it helps. This is a current blocker to optimizing MXNet SSD models with TVM. Would like to help where possible, however the actual writing of the ONNX ops is a little over my head.

https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/multibox_prior.cc
https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/multibox_detection.cc
https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/multibox_target.cc
