### ISSUE TITLE
Attributes to support more value types if makes sense

### ISSUE THREAD

**Issue by vadimkantorov** [onnx/onnx#2090]
As part of converting NVidia OpenSeq2seq's [wav2letter model](https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/wave2letter.html#training) from [TensorFlow to ONNX](https://github.com/onnx/tensorflow-onnx/) I stumbled on ONNX helper not supporting a few value types: Tensor shape list; Data type list and Function: https://github.com/onnx/tensorflow-onnx/issues/578

I can work around it by hacking into ONNX's helper and removing these attributes, but it would be nice if these could be converted properly or ignored (with a warning?) by `onnx.helper.make_attribute`.

**Comment by gramalingam** [comment]
A tensor-shape can be encoded as a list of ints (which is used in a number of ops already). A primitive data-type can be encoded as an int too (which is also used in some ops). If you want to encode the name of a function, it can be done using a string type. So, I guess you are not suggesting any extensions to ONNX's attribute-system (at the protobuf level). It sounds like you want some utilities to map TF's representation of these things into ONNX's representation? It seems to me that would be better off being in the TF2ONNX converter. Or, are you looking for some other extension in ONNX?

**Comment by vadimkantorov** [comment]
My feedback indeed comes from tf-onnx usage experience of converting a certain tf model. It redirects some tf attribute handling to ONNX, so I wondered if it makes sense to extend ONNX attribute system based on these experiences
