### ISSUE TITLE
I met thie error when run onnx inference.

### ISSUE THREAD

**Issue by bemoregt** [onnx/onnx#2099]
Hi, @huitseeker @ezyang @shinh @dougalsutherland @orionr 

My Code -

import time
import numpy as np
import onnxruntime as rt

im = np.random.rand(1, 3, 256, 384).astype('uint8')

sess = rt.InferenceSession("model.onnx")

t0 = time.time()
output =  sess.run(['prob'], {'data': im})[0]
print (time.time() - t0)

I met thie error when run onnx inference. -
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:data

What's wrong to me ??

Best,
@bemoregt.

**Comment by prasanthpul** [comment]
Please verify that 'data' is the name the model is expecting. 

Since this is regarding ONNX Runtime, please file further issues at https://github.com/microsoft/onnxruntime
