### ISSUE TITLE
Int64->Int32

### ISSUE THREAD

**Issue by dvd42** [onnx/onnx#2107]
I am trying to import [this model](https://github.com/onnx/models/tree/master/ssd) from the onnx model zoo to OpenCV. However OpenCV does not support 64 bit integers and some of the tensors in this model seem to be of Int64 type.
Is there a way to convert the Int64 tensors inside the model to Int32?

**Comment by ajaysg** [comment]
i am also facing the same issue with my onnx. Are you getting Type Parameter issue while in onnx runtime

**Comment by dvd42** [comment]
No. In my case it seems that it is a problem with OpenCV's ONNX importer. I will close this issue.
