### ISSUE TITLE
ERROR: Failed building wheel for onnx

### ISSUE THREAD

**Issue by Santhosh1509** [onnx/onnx#2109]
OS: Ubuntu 18.04
Python Version: 2.7.15+
Device: Jetson Nano

Packages pre installed in the virtuale env

> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Package           Version
> ----------------- -------
> numpy             1.16.4 
> pip               19.1.1 
> protobuf          3.8.0  
> setuptools        41.0.1 
> six               1.12.0 
> typing            3.6.6  
> typing-extensions 3.7.2  
> wheel             0.33.4 

Tried:
    pip -vv install onnx==1.4.1
Even after
    python -m pip install --upgrade pip
Getting this Error
> Removed build tracker '/tmp/pip-req-tracker-aetPg2'
> ERROR: Command "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-sKvx4d/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-PJVN9K/install-record.txt --single-version-externally-managed --compile --install-headers /home/rlpl123/.virtualenvs/test_yolov3_outofthebox/include/site/python2.7/onnx" failed with error code 1 in /tmp/pip-install-sKvx4d/onnx/
> Exception information:
> Traceback (most recent call last):
>   File "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
>     status = self.run(options, args)
>   File "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 414, in run
>     use_user_site=options.use_user_site,
>   File "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/local/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
>     **kwargs
>   File "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 951, in install
>     spinner=spinner,
>   File "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> InstallationError: Command "/home/rlpl123/.virtualenvs/test_yolov3_outofthebox/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-sKvx4d/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-PJVN9K/install-record.txt --single-version-externally-managed --compile --install-headers /home/rlpl123/.virtualenvs/test_yolov3_outofthebox/include/site/python2.7/onnx" failed with error code 1 in /tmp/pip-install-sKvx4d/onnx/

Any solution?

**Comment by Santhosh1509** [comment]
My bad did
   ` sudo apt-get install protobuf-compiler libprotoc-dev`
solved the issue

**Comment by ErfanRoshan** [comment]
In summary, to install onnx successfully in Ubuntu 20.04, you'll need to install this version of onnx pip install onnx==1.4.1

goodluck

**Comment by CoolJosh0221** [comment]
I'm on mac and i have the same issue

**Comment by DylDevs** [comment]
> In summary, to install onnx successfully in Ubuntu 20.04, you'll need to install this version of onnx : pip install onnx==1.4.1
> 
> goodluck

I just want to comment on this, if you want to use a newer version, the latest version I tested that works is:
onnx==1.6.0
