### ISSUE TITLE
Operator versioning follow up

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#211]
High priority:
- [x] Make sure the checker correctly handles versioning (e.g., if you get a model pegged to old version, it better use that version)
- [x] Documentation generation for different versions
  - [ ] Generate diffs in the documentation
  - [ ] Better cross-referencing in Changelog
- [ ] Infra for old to new operator conversion
- [x] Merge the versioning PRs for onnx-caffe2
- [x] Merge the versioning PRs for PyTorch
- [ ] Propagate versioning PRs to other backends

Other:
- [ ] Start generating the protobufs described in `onnx-operators.proto`
- [ ] ONNX/ONNX-ML versioning policy
- [ ] Grammar fixes / copyediting
- [ ] Move experimental into their own operator sets

**Comment by linkerzhang** [comment]
One more thing we may need (probably covered in your list above).
1. An API added into schema.h for domain setting, say, SetDomain.

Meanwhile, my understanding of the 2nd item above is to generate OperatorSetProto, and OperatorProto instances per all registration in onnx. However, it looks like it's not that straight forward to get the latest operator set version from all existing operator registrations. Say, we may group all operator registrations with same "sinceversion" together as a OperatorSetProto instance, however, people who wants to bump the version will have no idea about which is the latest version unless we generate the OperatorSetProto instance and check in to source tree. Is this what in your mind please?

Thank you!

**Comment by prasanthpul** [comment]
Many of these have since been addressed. Open a new issue for anything that is outstanding
