### ISSUE TITLE
Network input dimensions for initiating the graph

### ISSUE THREAD

**Issue by charanpool** [onnx/onnx#2111]
We are trying to parse the given onnx model into a graph structure in CPP. For most of the networks(like tiny-yolov2, yolov3, vgg-16) the input will be an image that must be fed to the starting node of the network. How can we know the input tensor dimensions of that network from the given onnx file? (For example for both the yolov2 and yolov3 networks it is 1, 3, 416, 416).

**Comment by JohnCraigPublic** [comment]
Netron is a nice tool that can open any onnx model and shows you the names and dimensions of the inputs and outputs.

**Comment by charanpool** [comment]
I am asking for the programmatic approach to find the initial input dimensions of a given network.

**Comment by gramalingam** [comment]
In the proto definition, the inputs field of a graph (https://github.com/onnx/onnx/blob/355a4954ea4e5836a5e943589509951c44feb6b4/onnx/onnx.in.proto#L280 ) are instances of ValueInfoProto, which contains an input name and input type. The type, when it is a Tensor, contains a TensorShapeProto, which lists the dimensions (as either symbolic strings, when not statically fixed, or as a constant value).

**Comment by charanpool** [comment]
Yes, that's correct but the problem is with the behaviour of the onnx::TypeProto_Tensor. See the following code segment :
```
for(int i = 0; i < model.graph().input().size(); i++)
{
        std::cout<<model.graph().input(i).name().c_str()<<"\n";
        std::cout<<model.graph().input(i).type().Tensor().elem_type()<<"\n";
}
```

The above code gives the following error:
```
test5.cpp: In function ‘int main()’:
test5.cpp:19:44: error: invalid use of ‘onnx::TypeProto::Tensor’
   std::cout<<model.graph().input(i).type().Tensor().elem_type()<<"\n";
```

Here there is no stipulated format to check TensorProto structure present inside the TypeProto structure.
So, What is the way to access the shape of the tensor?

**Comment by gramalingam** [comment]
I think "model.graph().input(i).type().Tensor().elem_type()" should be changed to "model.graph().input(i).type().tensor_type().elem_type()" … "Tensor" is the name of the type, and "tensor_type" is the name of the field.

**Comment by charanpool** [comment]
Thanks, @gramalingam.
