### ISSUE TITLE
Error after converting a model optimized by Neo AI (Sagemaker) to ONNX

### ISSUE THREAD

**Issue by wmlba** [onnx/onnx#2112]
After optimizing a resnet50.onnx model using Sagemaker Neo, tried to convert the output back to ONNX and got the error below:

MXNetError: Failed loading Op batch_norm0_div of type tvm_op: [10:30:54] src/core/op.cc:55: Check failed: op != nullptr Operator tvm_op is not registered

Stack trace returned 10 entries:
[bt] (0) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::StackTrace()+0x44) [0x7ff170587394]
[bt] (1) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(nnvm::Op::Get(std::string const&)+0x345) [0x7ff17387ce75]
[bt] (2) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3945a25) [0x7ff1738b9a25]
[bt] (3) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3945e14) [0x7ff1738b9e14]
[bt] (4) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::JSONObjectReadHelper::ReadAllFields(dmlc::JSONReader*)+0x110) [0x7ff1738bdcd0]
[bt] (5) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3942e6c) [0x7ff1738b6e6c]
[bt] (6) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x394396f) [0x7ff1738b796f]
[bt] (7) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(std::_Function_handler<nnvm::Graph (nnvm::Graph), nnvm::Graph (*)(nnvm::Graph)>::_M_invoke(std::_Any_data const&, nnvm::Graph)+0x131) [0x7ff1731caa41]
[bt] (8) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(nnvm::ApplyPasses(nnvm::Graph, std::vector<std::string, std::allocator<std::string> > const&)+0x52d) [0x7ff1738800fd]
[bt] (9) /home/ec2-user/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::LoadLegacyJSONPass(nnvm::Graph)+0x19f) [0x7ff1731c566f]

**Comment by prasanthpul** [comment]
This looks like an issue with sagemaker outputting invalid ops. Please file an issue in that github so the experts can take a look

**Comment by shnamin** [comment]
I'm getting the same errors after converting my model to jetson Nano. Any solutions?
