### ISSUE TITLE
Output shape of Global{Max,Average}Pool

### ISSUE THREAD

**Issue by newling** [onnx/onnx#2113]
The spec says for the output that, 
>Dimensions will be N x C x 1 x 1

Should the output not have as many 1s are there are spatial dimensions, and not exactly 2 1s always?

**Comment by daquexian** [comment]
It has been fixed by https://github.com/onnx/onnx/pull/2147 :)

**Comment by askhade** [comment]
Closing this issue since it's fixed by the above referenced PR. @newling : Please reopen this issue or add another one if you still have concerns. Thanks!
