### ISSUE TITLE
Document on graph->initializer is inconsistent with the document fix to issue #1449 

### ISSUE THREAD

**Issue by xykong58** [onnx/onnx#2114]

**Comment by xykong58** [comment]
The document fix to issue #1449 relaxes the requirement that graph's initializer must be a subset of graph's inputs.  But the document on the initializer still remains,

initializer           Tensor[]             A list of named tensor values, used to specify default values for some of 
                                                    the inputs of the graph. Each initializer value is associated with an input
                                                    by name matching.

**Comment by gramalingam** [comment]
Thanks for pointing this out. Yes, it would be nice to update it to say "A list of named tensor values. When an initializer has the same name as a graph input, it specifies a default value for that input. When an initializer has a name different from all graph inputs, it specifies a constant value.". Do you want to create  PR to fix it?

**Comment by xykong58** [comment]
Sure, I will create a PR for this.
