### ISSUE TITLE
Spec bug to do with LSTM operator

### ISSUE THREAD

**Issue by lovettchris** [onnx/onnx#2116]
The [LSTM Spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM) has WB, RB, WBb, RBb, and PB weights for "backward input", but it doesn't show how those are used in the Equations.

**Comment by ebarsoum** [comment]
Hi @lovettchris,

Yes, the doc need improvement, the equation of the backward input are exactly the same as the forward input. LSTM support 3 modes: forward, reverse and bidirection.

In forward and reverse mode, it uses only the non-backward weights. For the reverse mode the input sequence is reversed. For bidirection, both weights are concatenated, the forward weights used on the input and the backward weights used on the reverse of the input. 

Look at the below for more details: https://github.com/microsoft/onnxruntime/blob/b7cc611563cfd1bafdff14e38fb50ec9c48c3d68/onnxruntime/test/providers/cpu/rnn/LSTM.py

Thanks,
Emad
