### ISSUE TITLE
AtrributError 

### ISSUE THREAD

**Issue by shbnm21** [onnx/onnx#2119]
torch_out=torch.onnx.export(model,x,model.onnx, verbose=True)

Export function gives the graph but when I print torch_out it gives None but it should print tensor value 

And this is causing AtrributError when comparing torch_out with caffe2 model

np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

In this I am getting AtrributError
Nonetype object has no attribute 'data'

What could be the reason?

**Comment by prasanthpul** [comment]
From what you describe, this sounds like an error in PyTorch. Please file the issue in the PyTorch Github s the right experts can take a look.

If the issue is in ONNX code, please reopen the issue

**Comment by shbnm21** [comment]
I just want to know does onnx supports variational autoencoder-GAN model?
If yes 
How to export multiple models to onnx
Cz the model I am working generates 
More than one .pth files.
So do I need to export them individually?
