### ISSUE TITLE
Bug in slice shape inference when the input has dim_param for the specified axes

### ISSUE THREAD

**Issue by sonu1-p** [onnx/onnx#2121]
The slice op shape inference is first copying all input dim_values/dim_params to output shape. This is fine for dim_values as we will later override their value if needed(based on start, end, axis, step). But in case input has a dim_param for a dim and that dim was in the list of axis to be sliced, then we will end up not changing its value at all, which is incorrect. We cannot say that after slicing the size of this dim is going to remain same as input. But because of dim_param being copied as is this is happening.

https://github.com/onnx/onnx/blob/355a4954ea4e5836a5e943589509951c44feb6b4/onnx/defs/tensor/defs.cc#L608

**Comment by gramalingam** [comment]
Yes, there is a problem with the existing shape-inference. I can take a shot at fixing it (once a pending PR gets through).

**Comment by postrational** [comment]
@gramalingam Could you describe the change you were planning to make to fix shape-inference for this case?
