### ISSUE TITLE
Invoked with: %112 : Tensor = onnx::RandomNormal() - occurred when translating randn

### ISSUE THREAD

**Issue by arijit17** [onnx/onnx#2123]
Hi all:

I'm getting this error:
```
TypeError: i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

 

Invoked with: %112 : Tensor = onnx::RandomNormal(), scope: XXXXX
, 'shape', 108 defined in (%108 : int[] = prim::ListConstruct(%102, %107, %106), scope: XXXXX
) (occurred when translating randn)
```

Any idea how to get around it?

**Comment by prasanthpul** [comment]
The error message seems like this is a problem in PyTorch. Please file an issue in the PyTorch github so the right experts can take a look.

If this is actually an issue in ONNX code, please reopen the issue

**Comment by arijit17** [comment]
@prasanthpul Thank you. A Pytorch issue is filed here: https://github.com/pytorch/pytorch/issues/22069
Let me know if I'm doing something wrong.
