### ISSUE TITLE
help with denotation in helper funtions

### ISSUE THREAD

**Issue by SiR0N** [onnx/onnx#2125]
Hello,
I want to create a onnx model using helper function like: [https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#creating-an-onnx-model-using-helper-functions](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#creating-an-onnx-model-using-helper-functions)
  
But I want to use images therefore I would want to add denotations. I saw that It can be done by `helper.make_tensor_value_info`  [https://github.com/onnx/onnx/blob/master/onnx/helper.py#L290](https://github.com/onnx/onnx/blob/master/onnx/helper.py#L290)

I want to create a model similar to them: 
[https://github.com/lutzroeder/netron/files/2587943/onnx_denotation_models.zip](https://github.com/lutzroeder/netron/files/2587943/onnx_denotation_models.zip)

any tips how I can do this? I could not find any example.

**Comment by linkerzhang** [comment]
@tjingrant do you have some example codes to share?

**Comment by linkerzhang** [comment]
you may refer to https://github.com/onnx/onnx/blob/master/docs/TypeDenotation.md to get the idea about how to denotate the image model you want. basically, the steps are,
1. First set the TypeProto.denotation =IMAGE for the ValueInfoProto data_0 (this is your image model input)
    Because it's an image, the model consumer now knows to go look for image metadata on the model
2. Then include 3 metadata strings on ModelProto.metadata_props 
Image.BitmapPixelFormat = Bgr8
Image.ColorSpaceGamma = SRGB
Image.NominalPixelRange = NominalRange_0_255
3. For that same ValueInfoProto, make sure to also use Dimension Denotations to denote NCHW 
TensorShapeProto.Dimension[0].denotation = DATA_BATCH
TensorShapeProto.Dimension[1].denotation = DATA_CHANNEL
TensorShapeProto.Dimension[2].denotation = DATA_FEATURE
TensorShapeProto.Dimension[3].denotation = DATA_FEATURE

**Comment by SiR0N** [comment]
@linkerzhang Thanks for your reply, I already had a look at that website but it is not clear to me how to do it by code and I am not sure how to do the first either the third steps. I could add the metadata_props. This is my code:

```
meta_dat = {
    "Image.BitmapPixelFormat":"Bgr8",
    "Image.ColorSpaceGamma":"SRGB",
    "Image.NominalPixelRange":"NominalRange_0_255"

}
shape_den = ["DATA_BATCH","DATA_CHANNEL","DATA_FEATURE","DATA_FEATURE"]
x = helper.make_tensor_value_info('x',TensorProto.FLOAT,  [1,3,1080,1920])
y = helper.make_tensor_value_info('y', TensorProto.FLOAT, [1,3,1080,1920])
r = helper.make_tensor_value_info('r', TensorProto.FLOAT, [1,3,1080,1920], shape_denotation=shape_den)
node_def = helper.make_node(
    'Add',
    ['x', 'y'],
    ['r'],
    )


graph_def = helper.make_graph(
    [node_def],
    'scalar-adder-model',
    [x, y],
    [r],
)
model_def = helper.make_model(graph_def)
helper.set_model_props(model_def,meta_dat)
```

I want to add the metadata to "r" tensor. I tried with  TypeProto.denotation =IMAGE instead of TensorProto.FLOAT but it does not work. Can you share any example code?

**Comment by linkerzhang** [comment]
I see. 

I think there's a missing functionality in make_tensor_value_info to allow you set the type denotation.

For you to hack it right now, what you can do is,
1. add one more argument in make_tensor_value_info to allow users to give type denotation (string).
2. https://github.com/onnx/onnx/blob/master/onnx/helper.py#L303, after this line,
    add value_info_proto.type.denotation = "IMAGE" (the argument you added).

**Comment by SiR0N** [comment]
Thanks! it works! I share my code.
`r = helper.make_tensor_value_info('r', TensorProto.FLOAT, [1,3,1080,1920], shape_denotation=shape_den, denotation="IMAGE")`

In make_tensor_value_info [https://github.com/onnx/onnx/blob/master/onnx/helper.py#L290](https://github.com/onnx/onnx/blob/master/onnx/helper.py#L290)

```
def make_tensor_value_info(
        name,  # type: Text
        elem_type,  # type: int
        shape,  # type: Optional[Sequence[Union[Text, int]]]
        doc_string="",  # type: Text
        shape_denotation=None,  # type: Optional[List[Text]]
        denotation="",
):  # type: (...) -> ValueInfoProto
    """Makes a ValueInfoProto based on the data type and shape."""
    value_info_proto = ValueInfoProto()
    value_info_proto.name = name
    if doc_string:
        value_info_proto.doc_string = doc_string

    tensor_type_proto = value_info_proto.type.tensor_type
    if denotation:
        value_info_proto.type.denotation = denotation

    tensor_type_proto.elem_type = elem_type
    tensor_shape_proto = tensor_type_proto.shape
```

Hope it would help more people

**Comment by linkerzhang** [comment]
@SiR0N do you mind to create a PR for this change please? I'll be more than happy to merge it sooner than later. :) Thanks!

**Comment by SiR0N** [comment]
@linkerzhang is my code totally right?

I guess there should be any way to say that this metadata belongs to this tensor, for example, if I want to include the denotation to my inputs "x" and "y", it would use always the same metadata, maybe the shape/BitmapPixelFormat/ColorSpaceGamma/NominalPixelRange of input and outputs are different.
