### ISSUE TITLE
Add an attribute in slice op to support ellipse mask?

### ISSUE THREAD

**Issue by jiafatom** [onnx/onnx#2131]
In tensorflow, ellipse mask is supported in [strided_slice](https://www.tensorflow.org/api_docs/python/tf/strided_slice) op. In onnx, we use slice op to mimic tf strided_slice. If the input has dynamic dimensions (we only know it until runtime), the dimensions of the ellipse mask is also dynamic. Can we add a new attribute in slice op to indicate where the ellipse mask starts? For example, we call this attribute `ellipse_mask_starts`, then runtime backend can compute the dimensions of the ellipse mask on the fly.

For example, we have `starts=[0, 0, 0]`, `end=[1, 2, 3]`, we say `ellpse_mask_starts=1`, then if the input is 7-d tensor (calculated at runtime), it is equivalent to 
`starts=[0,0,0,0,0,0,0], end=[1,max,max,max,max,2,3]`
where it inserts the ellipse mask at the location `1` as `ellpse_mask_starts` specified.

Thanks.

**Comment by ebarsoum** [comment]
Hi @jiafatom,

Can you share which model uses ellipse mask? 

Thanks,
Emad

**Comment by jiafatom** [comment]
We have done this at converter side, so close this task.
