### ISSUE TITLE
Issues in the example used in Loop's documentation and related specification

### ISSUE THREAD

**Issue by xykong58** [onnx/onnx#2134]
In the example used in documenting "Loop",  %b should be the initial value
for a loop-carried dependence. But in the example, the %b and %b_out's scope seems
to be mixed,  should the example changed from

  graph body-net (
    %i[INT32, scalar]
    %keepgoing[BOOL, scalar]
    %b[INT32, scalar]
  ) {
    %my_local = Add(%a, %b)
    %b_out = Sub(%a, %b)
    %keepgoing_out = Greater(%my_local, %b_out)
    %user_defined_vals = Add(%b, %b)
    return %keepgoing_out, %b_out, %user_defined_vals
  }

==>

  graph body-net (
    %i[INT32, scalar]
    %keepgoing[BOOL, scalar]
    %b[INT32, scalar]
  ) {
    %my_local = Add(%a, %b)
    %b_out = Sub(%a, %b)
    %keepgoing_out = Greater(%my_local, %b_out)
    %user_defined_vals = Add(%b_out, %b_out)                  // change from %b to %b_out
    return %keepgoing_out, %b_out, %user_defined_vals
  }

**Comment by xykong58** [comment]
I miss the fact that the outputs and inputs are ordered so that loop-carried names are matched to the
inputs to the loop carried ones.

**Comment by gramalingam** [comment]
Yes. The ONNX example shown above is legal (both %b and %b_out are valid names to use in the assignment to %user_defined_vals). However, the ONNX example is not consistent with the equivalent C code shown in the documentation. One or the other needs to be changed.

**Comment by xykong58** [comment]
Maybe the ONNX code pattern should be disallowed since
it introduces irregular loop carried dependence pattern, which is hardly used in the domain.

**Comment by xykong58** [comment]
Assume ONNX is in SSA, the initial value and corresponding returned value should be considered as
inputs to a PHI, something like,

             %phi_out = PHI(%b, %b_out)

The use of %b in the loop body is to use %phi_out in SSA representation, therefore, the loop body
contains uses of %phi_out which are dominated by both %phi_out and %b_out, which violates the SSA
representation.

**Comment by xykong58** [comment]
There are similar specification issues for Scan, the initial state and corresponding updated state should be also considered as inputs to a PHI, i.e., 
           %phi_out = phi(initial_state, updated_state);

And use of initial_state inside the scan-loop-body can be considered uses of %phi_out.

**Comment by gramalingam** [comment]
Why should the code-pattern be disallowed? The sub-graph is just a graph describing a computation. The specification should just focus on the meaning of the inputs and outputs of the sub-graph. How the sub-graph computes its outputs from its inputs is its own business. Placing unnecessary restrictions there will just complicate things. The phi-vertices etc. are just a mental model for an implementor, not necessary for the spec.

**Comment by xykong58** [comment]
Hm, allowing x_in and x_out live in the same time does not confirm to SSA, and complicated the backend analysis if the backend is relying on the SSA properties of the ONNX.

**Comment by gramalingam** [comment]
I don't believe ONNX provided this kind of guarantee. In the original formulation, there were no control-flow ops, and the term SSA was mis-used to mean that there should be only one "definition" of any variable. For specification purposes, I think it is better to take a "functional language" perspective, where these are all just variables.

**Comment by xykong58** [comment]
My understanding from the IR.md is that the ONNX graph must be adhered to SSA.

"Each graph MUST specify a name.

The graph MUST adhere to single static assignment (SSA) for all node outputs; this means that all node output names MUST be unique within a graph."

If that is not the case, the above graph should be changed.

**Comment by xykong58** [comment]
But I do prefer the ONNX is kept to confirm SSA, so that the backend analysis/translation will be greatly simplified.

**Comment by vinodgro** [comment]
> I think it is better to take a "functional language" perspective, where these are all just variables.
If we take this approach, which is a good idea, then an output variable should be thought of a binding over a scope/region, and a later binding of the same region just hides the previous binding. Like a let binding.

**Comment by xykong58** [comment]
We may consider to document that the SSA semantics not guranteed for Tensors defined and used cross iterations in the loop body of Loop/Scan,  semantically,  the copy of the %b_out to %b happens at the end of the loop body in the example,

graph body-net (
%i[INT32, scalar]
%keepgoing[BOOL, scalar]
%b[INT32, scalar]
) {
%my_local = Add(%a, %b)
%b_out = Sub(%a, %b)
%keepgoing_out = Greater(%my_local, %b_out)
%user_defined_vals = Add(%b, %b)
return %keepgoing_out, %b_out, %user_defined_vals
}

**Comment by ArchRobison** [comment]
The ONNX example might be easier to follow if variables are uniquely named.  At least if I understand this part correctly:
```
graph body-net (
    %i[INT32, scalar]
    %keepgoing[BOOL, scalar]
    %b[INT32, scalar]
```
the `%keepgoing`and `%b` are parameters of the graph `body-net` and do not refer to the identifiers with the same name in graph `predict-net`, right?

**Comment by xykong58** [comment]
Based on the fact that body-net is a sub-graph interface, the %b should be a formal parameter.
Replace %b with %b_in,  %keepgoing with %keepgoing_in and  it would look like,

graph body-net (
%i[INT32, scalar]
%keepgoing_in[BOOL, scalar]
%b_in[INT32, scalar]
) {
%my_local = Add(%a, %b_in)
%b_out = Sub(%a, %b_in)
%keepgoing_out = Greater(%my_local, %b_out)
%user_defined_vals = Add(%b_in, %b_in)
return %keepgoing_out, %b_out, %user_defined_vals
}

**Comment by xykong58** [comment]
I submit a PR for fixing the code example, 
    https://github.com/onnx/onnx/pull/2144
