### ISSUE TITLE
What to do with ConstantOfShape?

### ISSUE THREAD

**Issue by iiSeymour** [onnx/onnx#2136]
ConstantOfShape was introduced in opset 9 *(which is what pytorch 1.1.0 only exports)* and it's not yet supported in many of the conversions tools *(CoreML, TensorFlow, TensorRT)*.

It also cannot be downgraded with the onnx version converter: 

> RuntimeError: /onnx/onnx/version_converter/adapters/no_previous_version.h:17: adapt: Assertion `false` failed: No Previous Version of ConstantOfShape exists

What is the best way to handle ConstantOfShape for model interoperability?

**Comment by linkerzhang** [comment]
Yep. ONNX version converter is designed to try to downgrade an updated op to an old version if needed. 

For this case, ConstantOfShape is a new op so that ONNX version converter does not work.

If you want to do some conversion manually, I think old version of "Constant + Tile" should work.

**Comment by iiSeymour** [comment]
I think `tile` will do the job, thanks :+1: 

The ONNX runtime is great and runs well on CPU + GPU, also the ONNX TensorFlow project has since release [1.3.0](https://github.com/onnx/onnx-tensorflow/releases/tag/v1.3.0) so it's just TensorRT and CoreML now.

**Comment by WilliamZhaoz** [comment]
Hi @linkerzhang ,
I hit the same problem, when I convert ONNX model to IR model (for OpenVINO), I got 
"
There is no registered "infer" function for node "399" with op = "ConstantOfShape". Please implement this function in the extensions
"
My ONNX modle is converted from a pytorch model, but there is no ConstantOfShape in my PyTorch model, how can I avoid using this op?

**Comment by Manojbhat09** [comment]
Hello @iiSeymour Would be great if you could provide any help with clue to get around with. Other ops in the model need opset 11 support, can we somehow modify the graph to incorporate tile?

**Comment by LucasKirsten** [comment]
Any solutions?
