### ISSUE TITLE
add error meesage for Conv operatior if bias is not 1D

### ISSUE THREAD

**Issue by lei-Qiao** [onnx/onnx#2139]
Hello, when I make graph for one Conv node with bias not in 1D, there is no error message, but the result is numerical wrong. It's better to show error message if bias shape is wrong, instead of use parts of bias input

**Comment by whitelok** [comment]
have you ever used onnx.checker.check_model ? This API can detect this error.

**Comment by postrational** [comment]
> result is numerical wrong
What did you use to calculate the result?
