### ISSUE TITLE
"identity0" key error while using mxnet to import an pytorch model saved in the form of .onnx 

### ISSUE THREAD

**Issue by Damian96gz** [onnx/onnx#2151]
Hello, can anyone help?

I have a pytorch model and I want to serve it use mxnet-model-serving. But when I tried to import the model using the onnx_mxnet.import_model() function. 

> sym, arg_params, aux_params = onnx_mxnet.import_model("cnn1.onnx")

I met the following error msgs:
   
> Traceback (most recent call last):
>   File ".\download.py", line 4, in <module>
>     sym, arg_params, aux_params = onnx_mxnet.import_model("cnn1.onnx")
>   File "C:\Users\ckunlin\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\contrib\onnx\onnx2mx\import_model.py", line 59, in import_model
>     sym, arg_params, aux_params = graph.from_onnx(model_proto.graph)
>   File "C:\Users\ckunlin\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\contrib\onnx\onnx2mx\import_onnx.py", line 115, in from_onnx
>     mxnet_sym = self._convert_operator(node_name, op_name, onnx_attr, inputs)
>   File "C:\Users\ckunlin\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\contrib\onnx\onnx2mx\import_onnx.py", line 61, in _convert_operator
>     op_name, new_attrs, inputs = convert_map[op_name](attrs, inputs, self)
>   File "C:\Users\ckunlin\AppData\Local\Continuum\anaconda3\lib\site-packages\mxnet\contrib\onnx\onnx2mx\_op_translations.py", line 434, in reshape
>     reshape_shape = list(proto_obj._params[inputs[1].name].asnumpy())
> KeyError: 'identity0'

The Pytorch code to save the onnx model:

![image](https://user-images.githubusercontent.com/37749318/60649239-3e4adf80-9e74-11e9-81ba-d2b5ae6c2a32.png)

![image](https://user-images.githubusercontent.com/37749318/60649354-6b978d80-9e74-11e9-8471-df03a8263147.png)

![image](https://user-images.githubusercontent.com/37749318/60649420-87029880-9e74-11e9-89e5-96fd24b52a5a.png)

**Comment by szza** [comment]
这个问题请问解决了吗

**Comment by Damian96gz** [comment]
> 这个问题请问解决了吗

没有。。。但是我试着用了onnx runtime serving ，可以serve这个model

**Comment by linkerzhang** [comment]
This might be a serving issue in mxnet side, given the model exported from pytorch to onnx can be served by onnxruntime. 

I'm closing it now.
