### ISSUE TITLE
ZipMap produces redundant data and could be more efficient

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#2153]
ZipMap produces dictionaries with always the same keys. It does not matter too much if the labels are integer but redundant when the labels are string. It could be useful to have a dedicated container which behaves like a sequence of map but internally is not. For a simple linear model, the time spent in ZipMap is significant. With this change, it would be almost costless.

```
class ZipMapDictionary(dict):
    """Custom dictionary, reduces redundant information."""
    __slots__ = ['_rev_keys', '_index', '_mat']

    @staticmethod
    def build_rev_keys(keys):
        res = {}
        for i, k in enumerate(keys):
            res[k] = i
        return res

    def __init__(self, rev_keys, index, mat=None):
        dict.__init__(self)
        self._rev_keys = rev_keys
        self._index = index
        self._mat = mat

    def __getitem__(self, key):
        return self._mat[self._index, self._rev_keys[key]]

    def __setitem__(self, pos, value):
        raise RuntimeError("Changing an element is not supported.")

    def __len__(self):
        return self._mat.shape[1]

    def __iter__(self):
        for k in self._rev_keys:
            yield k

    def __contains__(self, key):
        return key in self._rev_keys

    def items(self):
        for k, v in self._rev_keys.items():
            yield k, self._mat[self._index, v]

    def keys(self):
        for k in self._rev_keys.keys():
            yield k

    def values(self):
        for v in self._mat[self._index]:
            yield v

    def asdict(self):
        res = {}
        for k, v in self.items():
            res[k] = v
        return res


class ArrayZipMapDictionary(list):
    """Mocks an array of dictionary without changing the data it receives."""

    def __init__(self, rev_keys, mat):
        list.__init__(self)
        self._rev_keys = rev_keys
        self._mat = mat

    def __len__(self):
        return self._mat.shape[0]

    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

    def __getitem__(self, i):
        return ZipMapDictionary(self._rev_keys, i, self._mat)

    def __setitem__(self, pos, value):
        raise RuntimeError("Changing an element is not supported.")

    @property
    def values(self):
        return self._mat

    @property
    def columns(self):
        res = [(v, k) for k, v in self._rev_keys.items()]
        res.sort()
        return [_[1] for _ in res]


keys = ['cl0', 'cl1']
values = numpy.array([[0.5, 0.5], [0.1, 0.9]])
azm = ArrayZipMapDictionary(
    ZipMapDictionary.build_rev_keys(keys), values)
```

**Comment by linkerzhang** [comment]
do you want to create a PR for it? Thanks!

**Comment by gramalingam** [comment]
Is it correct to say that ZipMap tries to convert a tensor (representing a 2-dimensional table) into a sequence of "rows", each row being represented as a map? If so, yes, it seems inefficient. But how is it used subsequently? Why is the representation of a row as dictionary needed? When it can be effectively "compiled away"? I would find it useful to understand the common pattern in which ZipMap is used.

**Comment by xadupre** [comment]
The model below shows how a logistic regression is currently converted from scikit-learn into ONNX. The node LinearClassifier contains the label but it is only used to make sure of the order of the probabilities columns. The operator ZipMap is added to give the user access the class names by mapping class name to each probability. I suggested in #2149 that label information could be removed from every classifier to keep that information in one place. If the ZipMap operator is improved, we can keep the model below that way, otherwise, I'm thinking of removing ZipMap and adding a constant in the graph to store the class labels and give users a possibility to retrive them.

![image](https://user-images.githubusercontent.com/22452781/60789047-6da46980-a15e-11e9-94cb-fd4e282c4f0c.png)

**Comment by gramalingam** [comment]
I think your second suggestion (removing ZipMap and returning the class-labels separately) seems the simplest solution. In particular, you can return the class-labels as constant string-tensor (mapping index j to the j-th class-label). (The first alternative is sort of adding an abstraction-wrapper around the probability-tensor and the class-label-tensor … we can do that in C++ or in Python, but it is more complex to integrate it into ONNX.)

**Comment by gramalingam** [comment]
A clarification: while your first solution is a possibility, that is really more to do with an implementation of ONNX (such as onnxruntime) … so, that seems a more appropriate suggestion for onnxruntime. I don't think there is anything to be done on the ONNX/ONNXML side. I don't think there is a change to the spec of the op. I don't think there is any change to the type-system either.
