### ISSUE TITLE
ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by wg1996** [onnx/onnx#2158]
When I try transfer a mobilenet_v2 model from pytorch to onnx, ValueRrror has appeared.
ValueError: only one element tensors can be converted to Python scalars
How can I sovle it? Here is my code:
```
import torch
import torchvision
import torch.onnx
from torch.autograd import  Variable

# An instance of your model
model = torchvision.models.mobilenet_v2(pretrained=True)
print(model)

x = torch.randn(1, 3, 224, 224,requires_grad=True)
# Export the model
torch_out = torch.onnx._export(model, x, "mobilenet_v2.onnx", export_params=True)
```

**Comment by wait1988** [comment]
Same error as you

**Comment by linkerzhang** [comment]
This is a pytorch to onnx exporting error. It will be good to move it to pytorch community.
adding @spandantiwari , could you help to take a look and close this issue once it's tracked in pytorch? Thanks

**Comment by spandantiwari** [comment]
Sure @linkerzhang. @wg1996 - this is indeed a PyTorch export issue, so PyTorch is the right forum for raising it. I see that you already have this issue opened in PyTorch (https://github.com/pytorch/pytorch/issues/22674), so let's track it there. This issue can be closed.

**Comment by spandantiwari** [comment]
To close the loop on this - this issue has been fixed in PyTorch master.

**Comment by linkerzhang** [comment]
Thank you! @spandantiwari

**Comment by hedaobaishui** [comment]
Thanks @spandantiwari
