### ISSUE TITLE
'--user' option is not supported in a virtualenv

### ISSUE THREAD

**Issue by hobei** [onnx/onnx#2161]
The --user option has been added to the update_doc.sh and also in pytorch /scripts/onnx/tesh.sh. This is to ensure that the python packages are installed without root privileges. However this option is not supported when running in a virtualenv

```
If this command returns Can not perform a '--user' install. User site-packages are not visible in this virtualenv. then you are already in a Python virtual environment. You will need to deactivate this environment or contact your system administrator to install virtualenv for you in this environment.
``` 

I found this problem when runnning update_doc.sh when using a virtualenv. This problem is also preventing the circle_ci tested from installing ninja, which is done in a virtual env that is sourced in ./circleci/test.sh. See last two pull requests. 

Suggest that these scripts need to check to see if they are executing in a virtualenv and not add this option

**Comment by prasanthpul** [comment]
#2171

**Comment by hobei** [comment]
Fixed in another commit

**Comment by houseroad** [comment]
https://circleci.com/gh/onnx/onnx/2371?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link fixed.
