### ISSUE TITLE
Cleaning up shape-inference utilities

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#2162]
Many of the shape-inference utilities (such as in getAttribute, getRepeatedAttribute, hasInputShape, etc. in https://github.com/onnx/onnx/blob/master/onnx/defs/shape_inference.h ) can be turned into methods of InferenceContext. This would help simplify the code and make it a bit more compact.

**Comment by linkerzhang** [comment]
I would keep InferenceContext as a pure interface. but feel free to have all those re-useable methods centralized in a utility/helper class/file please. Do you want to create a PR for it? Thanks!
