### ISSUE TITLE
Is there any way to implement a Range Op without using Loop Op?

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx#2166]
Hi, 
  I want to implement a _3-fold subsample_ witch means to take one element every three elements, like [1,2,3,4,5,6,7] -> [1, 4, 7].  The simplest way I guess is to use Shape and Range Op but I found Range is during implementation now. I guess Loop Op can implement Range Op but Loop Op is not supported in onnx-to-tensorflow now.
  Is there any other way to implement this subsample?
  Thanks!

**Comment by gramalingam** [comment]
Can't you use a "Slice" op?

**Comment by JiayiFu** [comment]
> Can't you use a "Slice" op?
It seems to be feasible. I will try it. thx!
