### ISSUE TITLE
What's your choice for these existing operators?

### ISSUE THREAD

**Issue by hexiaoting** [onnx/onnx#2174]
There are so many operators in `caffe2(400+)`/`pytorch`, But `ONNX` only supports 139 operators.

Why do we only choose these 139 operators for implementation? Are there any rules or any other considerations?

Is ir_version field used to distinguish different stable list of operators?

**Comment by wschin** [comment]
We start with popular ones (operator used in important models get higher priority) and try to compose the rest using those popular ones. `ir_version` controls model format. You need to see the operator set to find the right operator.

**Comment by ebarsoum** [comment]
The goal is not to implement all possible operators, we prioritize operators based on models and as @wschin  said, you can compose a lot of those operators using ONNX primitive OPs. Here the criteria of adding new operators: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md
