### ISSUE TITLE
Intended behavior for Gather indices out of bounds?

### ISSUE THREAD

**Issue by kahmed10** [onnx/onnx#2179]
In [tensorflow](https://www.tensorflow.org/api_docs/python/tf/gather), Gather throws an exception on the CPU side if any value within _indices_ is out of bounds. On the GPU side, the output values are set to 0 for that index. Is this is the same behavior in onnx?

**Comment by askhade** [comment]
All index values are expected to be within bounds. It is an error if any of the index values are out of bounds. Runtimes will handle such errors in a runtime-specific fashion
