### ISSUE TITLE
Error converting pytorch to caffe2

### ISSUE THREAD

**Issue by shbnm21** [onnx/onnx#2181]
I am getting an error when converting onnx model to caffe2
error is in concat operator of caffe2
here is error

Original python traceback for operator 0 in network torch-jit-export_predict in exception above (most recent call last):
RuntimeError Traceback (most recent call last)
in ()
25
26 # Run the Caffe2 net:
---> 27 c2_out = prepared_backend.run(W)[0]
28
29 # Verify the numerical correctness upto 3 decimal places

3 frames
/usr/local/lib/python3.6/dist-packages/caffe2/python/workspace.py in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
209 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
210 try:
--> 211 return func(*args, **kwargs)
212 except Exception:
213 op_id = op_id_fetcher()

RuntimeError: [enforce fail at concat_split_op.h:289] dim == dim_j. Expect dimension = 32 got 1 at axis = 0 for input: 1. The input tensors can only have different dimensions when arg 'add_axis' = 0 and along the axis = 1 <[32, 3, 256, 256]> vs <[1, 512, 8, 8]>.
Error from operator:
input: "0" input: "1" output: "24" output: "OC2_DUMMY_0" name: "" type: "Concat" arg { name: "axis" i: 1 } device_option { device_type: 0 device_id: 0 }frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f9cb682c441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)

**Comment by linkerzhang** [comment]
You may ask the question in Caffe2 community.
