### ISSUE TITLE
Changing Batch SIze

### ISSUE THREAD

**Issue by joyIntel** [onnx/onnx#2182]
I have an onnx model. I just want to change the batch size of the model. 

I have attached an image of a single node of the graph. The first one shows `batch size = 1` and the second one shows `batch size = 4`. How to make this change using python code ??

![Change_Batch_Size](https://user-images.githubusercontent.com/39498824/61585324-49a53880-ab0d-11e9-997b-43cddd54d093.png)

**Comment by gramalingam** [comment]
Hi, 

You can change the batch-size as below. Note that you can also make the batch-size symbolic (e.g, "N") to indicate an unknown value … then you don't need to keep changing it for every different batch-size.

```python
import onnx

def change_input_dim(model):
    # Use some symbolic name not used for any other dimension
    sym_batch_dim = "N"
    # or an actal value
    actual_batch_dim = 4 

    # The following code changes the first dimension of every input to be batch-dim
    # Modify as appropriate ... note that this requires all inputs to
    # have the same batch_dim 
    inputs = model.graph.input
    for input in inputs:
        # Checks omitted.This assumes that all inputs are tensors and have a shape with first dim.
        # Add checks as needed.
        dim1 = input.type.tensor_type.shape.dim[0]
        # update dim to be a symbolic value
        dim1.dim_param = sym_batch_dim
        # or update it to be an actual value:
        # dim1.dim_value = actual_batch_dim


def apply(transform, infile, outfile):
    model = onnx.load(infile)
    transform(model)
    onnx.save(model, outfile)

apply(change_input_dim, r"input-file-name, r"output-file-name")

```

**Comment by joyIntel** [comment]
Hey @gramalingam , thanks for helping. Here `actual_batch_dim` you habe given an int value (4). So I am getting this error `TypeError: 4 has type int, but expected one of: bytes, unicode `. How to handle this ?

**Comment by joyIntel** [comment]
String "4" works.

**Comment by gramalingam** [comment]
Please don't use string "4" … a string's meaning is an unknown value. If you want to use "actual_batch_dim", you need to replace "dim1.dim_param = sym_batch_dim" by "dim1.dim_value = actual_batch_dim" as shown in the comment … use one or the other, depending on whether you want a symbolic value or actual value.

**Comment by joyIntel** [comment]
Ok. thanks @gramalingam

**Comment by VincentDuf** [comment]
Hey,
I want to do the same (changing batch size of a loaded model) but when I apply your steps I get this error:

`TypeError: Cannot set onnx.TensorShapeProto.Dimension.dim_param to 64: 64 has type <class 'int'>, but expected one of: (<class 'bytes'>, <class 'str'>)`

How should I deal with it ? (using bytes() function gives me the bytes format in the model.graph.input printout...)

**Comment by mmaaz60** [comment]
> Hi,
> 
> You can change the batch-size as below. Note that you can also make the batch-size symbolic (e.g, "N") to indicate an unknown value … then you don't need to keep changing it for every different batch-size.
> 
> ```python
> import onnx
> 
> def change_input_dim(model):
>     # Use some symbolic name not used for any other dimension
>     sym_batch_dim = "N"
>     # or an actal value
>     actual_batch_dim = 4 
> 
>     # The following code changes the first dimension of every input to be batch-dim
>     # Modify as appropriate ... note that this requires all inputs to
>     # have the same batch_dim 
>     inputs = model.graph.input
>     for input in inputs:
>         # Checks omitted.This assumes that all inputs are tensors and have a shape with first dim.
>         # Add checks as needed.
>         dim1 = input.type.tensor_type.shape.dim[0]
>         # update dim to be a symbolic value
>         dim1.dim_param = sym_batch_dim
>         # or update it to be an actual value:
>         # dim1.dim_value = actual_batch_dim
> 
> 
> def apply(transform, infile, outfile):
>     model = onnx.load(infile)
>     transform(model)
>     onnx.save(model, outfile)
> 
> apply(change_input_dim, r"input-file-name, r"output-file-name")
> ```

It looks like you are not changing the output dimensions

**Comment by klnrdknt** [comment]
> > Hi,
> > You can change the batch-size as below. Note that you can also make the batch-size symbolic (e.g, "N") to indicate an unknown value … then you don't need to keep changing it for every different batch-size.
> > ```python
> > import onnx
> > 
> > def change_input_dim(model):
> >     # Use some symbolic name not used for any other dimension
> >     sym_batch_dim = "N"
> >     # or an actal value
> >     actual_batch_dim = 4 
> > 
> >     # The following code changes the first dimension of every input to be batch-dim
> >     # Modify as appropriate ... note that this requires all inputs to
> >     # have the same batch_dim 
> >     inputs = model.graph.input
> >     for input in inputs:
> >         # Checks omitted.This assumes that all inputs are tensors and have a shape with first dim.
> >         # Add checks as needed.
> >         dim1 = input.type.tensor_type.shape.dim[0]
> >         # update dim to be a symbolic value
> >         dim1.dim_param = sym_batch_dim
> >         # or update it to be an actual value:
> >         # dim1.dim_value = actual_batch_dim
> > 
> > 
> > def apply(transform, infile, outfile):
> >     model = onnx.load(infile)
> >     transform(model)
> >     onnx.save(model, outfile)
> > 
> > apply(change_input_dim, r"input-file-name, r"output-file-name")
> > ```
> 
> It looks like you are not changing the output dimensions

So, how should that be done? Does it need to be? Some more detail would be of help.

**Comment by miroenev** [comment]
Augmented the [original answer](https://github.com/onnx/onnx/issues/2182#issuecomment-513888258) to include modifying the batch size in the outputs.

This resolves an ShapeInferenceError/ONNXRuntimeError which would be raised when running inference through a network whose outputs have not also been modified to reflect the change in batch size.

```
import onnx

def change_batch_size(input_model_path,
                      output_model_path,
                      new_batch_size = 1,
                      batch_dimension_index = 0):
        
    model = onnx.load(input_model_path)
    
    inputs = model.graph.input
    outputs = model.graph.output
    
    for input_op in inputs:
        op_batch_size = input_op.type.tensor_type.shape.dim[batch_dimension_index]
        op_batch_size.dim_value = new_batch_size

    for output_op in outputs:
        op_batch_size = output_op.type.tensor_type.shape.dim[batch_dimension_index]
        op_batch_size.dim_value = new_batch_size
    
    onnx.save(model, output_model_path)

change_batch_size( "batch_8.onnx", "batch_8_mod_batch_1.onnx", new_batch_size)
```

**Comment by imneonizer** [comment]
This works for me
````python
import onnx

def change_input_dim(model,):
    batch_size = "N"

    # The following code changes the first dimension of every input to be batch_size
    # Modify as appropriate ... note that this requires all inputs to
    # have the same batch_size 
    inputs = model.graph.input
    for input in inputs:
        # Checks omitted.This assumes that all inputs are tensors and have a shape with first dim.
        # Add checks as needed.
        dim1 = input.type.tensor_type.shape.dim[0]
        # update dim to be a symbolic value
        if isinstance(batch_size, str):
            # set dynamic batch size
            dim1.dim_param = batch_size
        elif (isinstance(batch_size, str) and batch_size.isdigit()) or isinstance(batch_size, int):
            # set given batch size
            dim1.dim_value = int(batch_size)
        else:
            # set batch size of 1
            dim1.dim_value = 1

def apply(transform, infile, outfile):
    model = onnx.load(infile)
    transform(model,)
    onnx.save(model, outfile)

apply(change_input_dim, <path-to-input-model>, <path-to-output-model>)
````

Now you can either pass a string or an integer, both of them will work.
- Any string which can be casted to integer will set explicit batch size. e.g `"4"` will set `batch_size=4`
-  Any string which cannot be casted to string will set dynamic batchsize.
-  You can also pass an integer to set the batch size explicitly wihout casting.

**Comment by ivan23kor** [comment]
The scripts above did not work for me for the MNIST model (need to change graph.output, graph.value_info and reshape nodes).
After more scrutiny I found [this post](https://nietras.com/2021/05/24/set-dynamic-batch-size-using-onnx-sharp/) so I implemented a Python script that works for MNIST:
```
import onnx
import os

from argparse import ArgumentParser


def rebatch(infile, outfile, batch_size):
    model = onnx.load(infile)
    graph = model.graph

    # Change batch size in input, output and value_info
    for tensor in list(graph.input) + list(graph.value_info) + list(graph.output):
        tensor.type.tensor_type.shape.dim[0].dim_param = batch_size

    # Set dynamic batch size in reshapes (-1)
    for node in (node for node in graph.node if node.op_type == 'Reshape'):
        for init in graph.initializer:
            if init.name != node.input[1] or init.int64_data[0] != 1:
                continue
            init.int64_data[0] = -1

    onnx.save(model, outfile)

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('infile')
    parser.add_argument('outfile')
    parser.add_argument('--batch_size', default='N')
    args = parser.parse_args()

    rebatch(args.infile, args.outfile, args.batch_size)
```

**WARNING!!!** Change line 13 if you want an int instead of a symbolic parameter for batch size.

**Comment by punov** [comment]
For anybody searching for solution to convert to fixed batch size (not the dynamic one),
here's a slight modification for it:

```
def rebatch(infile, outfile, batch_size):
    model = onnx.load(infile)
    graph = model.graph

    for tensor in list(graph.input) + list(graph.value_info) + list(graph.output):
        tensor.type.tensor_type.shape.dim[0].dim_value = batch_size

    for node in  graph.node:
        if node.op_type != 'Reshape':
            continue
        for init in graph.initializer:
            # node.input[1] is expected to be a reshape
            if init.name != node.input[1]:
                continue
            # Shape is stored as a list of ints
            if len(init.int64_data) > 0:
                # This overwrites bias nodes' reshape shape but should be fine
                init.int64_data[0] = batch_size
            # Shape is stored as bytes
            elif len(init.raw_data) > 0:
                shape = bytearray(init.raw_data)
                struct.pack_into('q', shape, 0, batch_size)
                init.raw_data = bytes(shape)

    onnx.save(model, outfile)
    
rebatch(input_path, output_path, 4)
```

**Comment by stan-infinity** [comment]
So far this works for us, changes:
- using a impossible fix batch size of 777 (the export_batch_size) as a placeholder
- searching for nodes that have that placeholder and only modifying those ones
- changing Constant nodes


```python

def make_dynamic_batch(infile: str, outfile: Optional[str] = None, batch_size: str = 'N', export_batch_size: Optional[int] = None):
    import onnx
    import struct
    if outfile is None:
        outfile = infile
    model = onnx.load(infile) # type: ignore
    graph = model.graph

    for tensor in list(graph.input) + list(graph.value_info) + list(graph.output):
        dims = tensor.type.tensor_type.shape.dim
        if len(dims) == 0:
            continue
        dim0 = dims[0]
        if export_batch_size is not None and dim0.HasField('dim_value') and dim0.dim_value == export_batch_size:
            dim0.ClearField('dim_value')
            dim0.dim_param = batch_size
        elif export_batch_size is None:
            dim0.ClearField('dim_value')
            dim0.dim_param = batch_size

    # Set dynamic batch size in reshapes (-1)
    for node in graph.node:
        if node.op_type != 'Reshape':
            continue
        for init in graph.initializer:
            # node.input[1] is expected to be a reshape
            if init.name != node.input[1]:
                continue
            # Shape is stored as a list of ints
            if len(init.int64_data) > 0:
                # This overwrites bias nodes' reshape shape but should be fine
                init.int64_data[0] = -1
            # Shape is stored as bytes
            elif len(init.raw_data) > 0:
                shape = bytearray(init.raw_data)
                struct.pack_into('q', shape, 0, -1)
                init.raw_data = bytes(shape)

    # Replace export_batch_size with -1 in Constant node attributes
    if export_batch_size is not None:
        for node in graph.node:
            if node.op_type == 'Constant':
                for attr in node.attribute:
                    if attr.type == 7:  # INTS
                        if export_batch_size in attr.ints:
                            attr.ints[0] = -1

    onnx.save(model, outfile) # type: ignore

```
