### ISSUE TITLE
The operator list can not find `fc_layer` 

### ISSUE THREAD

**Issue by wawltor** [onnx/onnx#2185]
Could you please show me a way to search the operator lists? Thank you very much.

**Comment by wawltor** [comment]
> _No description provided._
Could you please give me a way to search the op lists?

**Comment by prasanthpul** [comment]
https://github.com/onnx/onnx/blob/master/docs/Operators.md.

**Comment by askhade** [comment]
@wawltor : Does this solve your question?

**Comment by wawltor** [comment]
> @wawltor : Does this solve your question?
yes, it works.
