### ISSUE TITLE
Is there any works going on implementing MLIR plugin for ONNX??

### ISSUE THREAD

**Issue by tkclimb** [onnx/onnx#2190]
I'm wondering if the ONNX community does or plans to work with MLIR to import or export. Is there anyone who knows about this?

I saw this post but it doesn't sound about this repository.
https://groups.google.com/a/tensorflow.org/forum/#!searchin/mlir/onnx%7Csort:date/mlir/2FT4sD8kqTY/lOTxReAHDAAJ

**Comment by prasanthpul** [comment]
We'd love to hear more if you are planning to write an ONNX dialect!

**Comment by bhack** [comment]
Check also https://github.com/tensorflow/mlir/blob/master/g3doc/MLIRForGraphAlgorithms.md

/cc @joker-eph

**Comment by joker-eph** [comment]
I am not aware of anyone working on this, feels free to email the mailing-list to inquire: not everyone may watch the issue tracker.

**Comment by tjingrant** [comment]
Linking to our contribution proposal https://github.com/onnx/onnx/issues/2499.

**Comment by bhack** [comment]
Some activity Is going ahead at https://github.com/clang-ykt/ONNF
