### ISSUE TITLE
Poor documentation for NonMaxSuppression

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2192]
Please improve the documentation for NonMaxSuppression.
There are 3 optional inputs, and none of them have defaults defined:
max_output_boxes_per_class, iou_threshold, score_threshold.

There are typos and poor grammar making it hard to understand. Examples: 
"The boxes doesn't has class dimension which means it alwasy has scores calculated for different classes on same box."
"cornersand"
"Pytoch"

**Comment by prasanthpul** [comment]
@HectorSVC

**Comment by HectorSVC** [comment]
thanks for the findings.
For the optional input, you can always know whether they are exist or not. If they are not exist, which means you don't need to do the filter based on the threshold for example.

For the typos:
"cornersand" should be "corners and".
"Pytoch" should be "Pytorch".

**Comment by HectorSVC** [comment]
https://github.com/onnx/onnx/pull/2193

**Comment by HectorSVC** [comment]
@mathisdon would you mind close the issue if no more comments?
