### ISSUE TITLE
 g = process_tf_graph? why do this work?

### ISSUE THREAD

**Issue by sy-swjtu** [onnx/onnx#2205]
g = process_tf_graph(tf_graph,
                             continue_on_error=args.continue_on_error,
                             target=args.target,
                             opset=args.opset,
                             custom_op_handlers=custom_ops,
                             extra_opset=extra_opset,
                             shape_override=args.shape_override,
                             input_names=inputs,
                             output_names=outputs,
                             inputs_as_nchw=args.inputs_as_nchw)
hi,
I have a question, trace-based means that it operates by executing your model once. 
If the model is dynamic, the export won’t be accurate. 
Why did you do this?
Can you give a detailed explanation, or reference?
Very thankful！！！

**Comment by askhade** [comment]
The right place for this issue is in onnx/tensorflow-onnx converter repository : https://github.com/onnx/tensorflow-onnx/issues
