### ISSUE TITLE
Does Gemm support 3-d inputs?

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx#2209]
I am working on the importer for Tensorflow and facing a question about how to support Gemm with 3-d inputs, https://github.com/onnx/onnx-tensorflow/issues/471

The doc and test cases here, https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gemm, seem to cover 2-d inputs.

Here is a PR for Gemm with additional test cases, also having all 2-d inputs.
https://github.com/onnx/onnx/pull/2060/files

Does ONNX Gemm support 3-d inputs? If so, what is the output shape if A has shape (a, b, c) and B has shape (b, c, d)? Could we have a test case for 3-d inputs?

**Comment by askhade** [comment]
GEMM only supports 2-d inputs. (you can refer this link for more details: https://github.com/onnx/onnx/blob/fabe39d524b0d80cc2fca0ccbcb0e7b5e67a4f80/onnx/defs/math/defs.cc#L781)

GEMM can also be expressed as Matmul + Add and both these ops support 3-d inputs... You can check whether matmul + add apply for your scenario

**Comment by chinhuang007** [comment]
@askhade Thanks for the confirmation that ONNX Gemm only supports 2-d inputs. When there is a need to for 3-d inputs, we will try matmul + add.
