### ISSUE TITLE
The rank for "iou_threshold" and "score_threshold" of NonMaxSuppression is unclear

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx#2212]
In https://github.com/onnx/onnx/blob/master/docs/Operators.md#nonmaxsuppression, it state that both "iou_threshold" and "score_threshold" are scalar but in the unit tests all of the values for "iou_threshold" and "score_threshold" are 1D tensor. I also look at https://github.com/onnx/onnx/blob/master/onnx/defs/object_detection/defs.cc, I can't tell what is the expected rank for both "iou_threshold" and "score_threshold". May someone please clarify what is the expected rank for these two inputs.

**Comment by askhade** [comment]
The spec says it is a Scalar so it should be treated as a scalar. I will update the tests and shape inference for this op to reflect the same.
