### ISSUE TITLE
How to use ssd.onnx?

### ISSUE THREAD

**Issue by ujsyehao** [onnx/onnx#2215]
This repository has provided ssd.onnx, Can you provide convert_onnx.py and how to use ssd.onnx?

**Comment by askhade** [comment]
Can you add a link to ssd.oonx and also add some context as to what you are trying to do.

**Comment by ebarsoum** [comment]
Are you talking about https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/ssd?

**Comment by askhade** [comment]
looks like ebarsoum answered your question. Closing this issue .... if you have more questions regarding this please open an issue here : https://github.com/onnx/models/issues
