### ISSUE TITLE
How to add a node to the end of a graph

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2216]
I am using PyTorch to export a model, but the exporter does not export NMS. So one solution is for me to export before NMS and then add NMS  `node = onnx.helper.make_node('NonMaxSuppression')` manually after loading the exported model.

**Comment by askhade** [comment]
Yes this is the right way and I suppose the only way

**Comment by fumihwh** [comment]
First way: If you want to `add a node to the end of a graph`, use `onnx.helper` to make a node and append to model.graph.node is right way.
Don't forget to modify `graph.output` also.
Second way: modify your code, add support to export `nms` to exporter.

**Comment by ebarsoum** [comment]
@dashesy which version of PyTorch are you using, and which model are you exporting?

**Comment by dashesy** [comment]
@ebarsoum PyTorch 1.1 and model is darknet.
@fumihwh thanks, that is what I suspected. Is there any examples you are aware of, that manipulates the `graph.node` and `graph.output`? There are some numbers there that are not obvious what they are. A good documentation for `graph.node` and `graph.output` would be helpful too.

**Comment by MasterGG** [comment]
> r code, add support to export `nms` to exporter.

I have searched ONNX documents, And didn't find how to modify the graph.output,could you give me some advice ,or show me the link for onnx api.

**Comment by MasterGG** [comment]
> First way: If you want to `add a node to the end of a graph`, use `onnx.helper` to make a node and append to model.graph.node is right way.
> Don't forget to modify `graph.output` also.
> Second way: modify your code, add support to export `nms` to exporter.

@fumihwh I have searched ONNX documents, And didn't find how to modify the graph.output,could you give me some advice ,or show me the link for onnx api.

**Comment by kolingv** [comment]
@dashesy Hi, could you post your codes here if have solved the isssue?

**Comment by dashesy** [comment]
@kolingv exporting NMS should be already supported by torchvision. I used [this](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms.py#L12) to export NMS at that time (together with [this](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms/nms_cpu.cpp#L114) in C code). 
It was much simpler to add a custom ops and let the tracer export it than manipulating the graph after the fact. Specially that there is no good documentation on how to do that.

**Comment by kolingv** [comment]
@dashesy The interfece of torchvision nms is not the same as that from onnx nms, it may not work . I'll try exporting nms from torchvision if i can spare time

**Comment by kolingv** [comment]
> @kolingv exporting NMS should be already supported by torchvision. I used [this](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms.py#L12) to export NMS at that time (together with [this](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms/nms_cpu.cpp#L114) in C code).
> It was much simpler to add a custom ops and let the tracer export it than manipulating the graph after the fact. Specially that there is no good documentation on how to do that.

Follow the tutorial "export Pytorch model with custom op to ONNX and run it in ONNX Runtime" [here](https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator), and combine with corresponding cpp file [here](https://github.com/BowenBao/inference/tree/master/cloud/single_stage_detector/pytorch) -> infer.py  I've exported it to onnx sucessfully by registering custom NMS op in pytorch. However it was exported as multi_label_nms, not the desired 'NonMaxSupression' block defined in onnx operators. 

While quoted from the tutorial mentioned above, 
"You can export your custom operator using existing ONNX ops, or you can create custom ONNX ops to use. In both cases, you need to add the symbolic method to the exporter, and register your custom symbolic using torch.onnx.register_custom_op_symbolic" and "If you are using existing ONNX ops only, you do not need to go through this last step (register in onnxrutime)."

These words made me confused. I did exported to an existing ONNX op! 

BTW, i made a model with onnx helper functions and then sucessfully run on onnxrutime. But append a NMS node to the existing graph didn't pass onnxruntime - report sth like no register NMS module. 

I'm really confused how onnx match onnxruntime. 

Really appreciate if u have any clues.

**Comment by dashesy** [comment]
@kolingv [here](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms.py#L12) we are exporting with ONNX `NonMaxSuppression` ops. If we let the custom namespace remain the generated onnx file cannot run in onnxruntime without also registering a custom layer there.
Namespace is just what you declare e.g. [here](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms/nms_cpu.cpp#L114)

**Comment by bhavitvyamalik** [comment]
While adding NMS node at the end of ONNX graph it asks for the following parameters:
```
node = onnx.helper.make_node(
    'NonMaxSuppression',
    inputs=['boxes', 'scores', 'max_output_boxes_per_class', 'iou_threshold', 'score_threshold'],
    outputs=['selected_indices'],
    center_point_box=1
)
```
Now my output is a single node which I get after running ONNX session for inference and post that I do slicing to get boxes and scores. This means should I simply use only my node name in place of 'boxes' and 'scores'? Also, how can I modify my graph.output?

**Comment by kolingv** [comment]
> While adding NMS node at the end of ONNX graph it asks for the following parameters:
> 
> ```
> node = onnx.helper.make_node(
>     'NonMaxSuppression',
>     inputs=['boxes', 'scores', 'max_output_boxes_per_class', 'iou_threshold', 'score_threshold'],
>     outputs=['selected_indices'],
>     center_point_box=1
> )
> ```
> 
> Now my output is a single node which I get after running ONNX session for inference and post that I do slicing to get boxes and scores. This means should I simply use only my node name in place of 'boxes' and 'scores'? Also, how can I modify my graph.output?

1. Yes, replacing with 'boxes' and 'scores', but remember to initialize other parameters such as 'max_output_boxes_per_class', 'iou_threshold', 'score_threshold'. 
2. To modify ur graph output, u may need to extend grpha output like this:
```python
 output_name = "name"
output_value_info = onnx.helper.ValueInforProto()
output_value_infro.name = output_name
model.graph.output.extend([output_value_info])
```

**Comment by bhavitvyamalik** [comment]
I was successfully able to add NMS node after inserting my node in the graph and modifying graph output but while inferencing it gives me the following error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Node () input arg ([100]) does not have type information set by parent node.
```

How my input is like (2060, 2061 are boxes and score nodes):
```
max_output_boxes_per_class = np.array([100]).astype(np.int64)
iou_threshold = np.array([0.5]).astype(np.float32)
score_threshold = np.array([0.0]).astype(np.float32)
inputs=['2060', '2061', f"{max_output_boxes_per_class}", f"{iou_threshold}", f"{score_threshold}"]
```
inputs parameters only accept string values. Once it converts successfully it tries to search those nodes in case of max_output_boxes_per_class, iou_threshold, and score_threshold and gives that error. How should I proceed in that case?

**Comment by avasbr** [comment]
so i'm trying to do the exact same thing but struggling to get even to the point that you're at @bhavitvyamalik ; specifically we would want to remove the `bboxes` and `scores` nodes and replace it with the output of the `NonMaxSuppression` correct? and from what i can see, using `graph.output.extend([...])` adds onto the list.  Here's what I have so far:

```
# get the nodes and node indices corresponding to bboxes and scores respectively
bbox_node_idx, bbox_node = [(i,n) for i,n in enumerate(graph.node) if n.output == ["bboxes"]][0]
score_node_idx, score_node = [(i,n) for i,n in enumerate(graph.node) if n.output == ["scores"]][0]

# make a new nms node
nms_node = onnx.helper.make_node(
    'NonMaxSuppression',
    inputs=[str(bbox_node_idx), str(score_node_idx), '200', '0.3', '0.9'],
    outputs=['selected_indices'],
)
```

So after I make this node, I assume I have to actually attach it. Here i'm just doing:
```
# connect to non-max suppression op
graph.node.insert(bbox_node_idx, nms_node)
graph.node.insert(score_node_idx, nms_node)
```

Is this correct so far? At this point i'm not sure how i communicate to the graph to replace the `bboxes` and `scores` to just get out the `selected_indices`. I tried to go along the lines of what @kolingv suggested two posts up, but I think i need to do a bit more, and I feel like i'm missing what that is. 

But it looks like even with all this, the checker isn't happy. Perhaps the `max_output_boxes_per_class`, `iou_threshold`, and `score_threshold` values also need to be constant nodes in the graph that then need to be referenced?

**Comment by dashesy** [comment]
It may be easier to create a simple PyTorch `nn.Module` and export from there. You can then look at that exported graph and create nodes manually of you wish.

**Comment by avasbr** [comment]
@dashesy thanks for the suggestion. 

that's how i started, and would love to do it this way, but the main issue i faced there was that the `nms` function in pytorch doesn't have a `scores_threshold` (`keep = nms(scores, bboxes, iou_threshold`) and as a result, the `NonMaxSuppression` op doesn't initialize it when I inspect the onnx graph. Of course, I can filter scores and bboxes w/ this threshold myself, but there are reasons I would like that taken care of directly by the `NonMaxSuppression` op directly -  the onnx model is not really my end goal, I'm transforming this to other accelerators (openvino, tensorRT, etc) and if i do this filtering myself, then the scores and bboxes become dynamic shapes, which is another separate thing to deal with.

Is there a way I can write my flow within the `nn.Module` forward function that makes onnx realize that I want the scores threshold inside the NonMaxSuppression op?

**Comment by dashesy** [comment]
You can use this to export with the threshold:

```python
    @parse_args('v', 'v', 'f', 'f')
    def symbolic_multi_class_nms(g, boxes, scores, iou_threshold, score_threshold):
        boxes = unsqueeze(g, boxes, 0)
        scores = unsqueeze(g, scores, 0)
        max_output_per_class = g.op('Constant', value_t=torch.tensor([10000], dtype=torch.long))
        iou_threshold = g.op('Constant', value_t=torch.tensor([iou_threshold], dtype=torch.float))
        score_threshold = g.op('Constant', value_t=torch.tensor([score_threshold], dtype=torch.float))
        nms_out = g.op('NonMaxSuppression', boxes, scores, max_output_per_class, iou_threshold, score_threshold)
        return select(g, nms_out, 1, g.op('Constant', value_t=torch.tensor([1, 2], dtype=torch.long)))
```

Then you can change the nms code [here](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms/nms_cpu.cpp#L15) to actually use that threshold. You do not have to make it work even, as long as the [signature](https://github.com/microsoft/pytorch_od/blob/4692837df0bd042be5327a96f933e2b6c5e1f6bc/mictorch/nms/nms_cpu.cpp#L114) is correct nms will export correctly.

From my experience working with exported ONNX is like working with compiled code to machine code, it is doable but not easy.

**Comment by avasbr** [comment]
I see.. thanks for this! but just to make sure I understand, this means I'd have to actually modify source code in pytorch and maintain that, correct?

**Comment by dashesy** [comment]
This is not PyTorch's (torchvision actually) but yes you need to copy the C code and build in your repo. In the repo I linked it is a simple c extension you can copy.

**Comment by avasbr** [comment]
Got it. Thanks again for all the help @dashesy 

As an aside, I dug a bit more into the onnx docs and found this to be quite useful: https://github.com/onnx/onnx/blob/master/docs/IR.md

It doesn't cover specific examples of how to do things, but it clarified a number of concepts for me. In the end, I was able to attach a `NonMaxSuppression` op with `score_threshold`, `iou_threshold`, and `max_output_boxes_per_class` as constant values, and pass the onnx checker as well. For whoever it might help in the future, here's the full code that worked for me, when going from an onnx model that currently outputs decoded bboxes and scores:

onnx version: 1.7.0
pytorch version: 1.4.0

```
onnx_fpath = [Path to .onnx model]
onnx_model = onnx.load(onnx_fpath)

# make constant tensors
score_threshold = onnx.helper.make_tensor("score_threshold", TensorProto.FLOAT, [1], [0.9])
iou_threshold = onnx.helper.make_tensor("iou_threshold", TensorProto.FLOAT, [1], [0.3])
max_output_boxes_per_class = onnx.helper.make_tensor("max_output_boxes_per_class", TensorProto.INT64, [1], [200])

# create the NMS node
inputs=['bboxes', 'scores', 'max_output_boxes_per_class', 'iou_threshold', 'score_threshold',]
outputs = ["selected_indices"]
nms_node = onnx.helper.make_node(
    'NonMaxSuppression',
    inputs,
    ["selected_indices"],
)

# add to the list of graph nodes
graph.node.append(nms_node)

# append to the output (now the outputs would be scores, bboxes, selected_indices)
output_value_info = onnx.helper.make_tensor_value_info("selected_indices", TensorProto.INT64, shape=[])
graph.output.append(output_value_info)

# add to initializers - without this, onnx will not know where these came from, and complain that they're neither outputs of other # nodes, nor inputs. As initializers, however, they are treated as constants needed for the NMS op
graph.initializer.append(score_threshold)
graph.initializer.append(iou_threshold)
graph.initializer.append(max_output_boxes_per_class)

# check that it works and re-save
onnx.checker.check_model(onnx_model)
onnx.save(onnx_model, onnx_fpath)
```

**Comment by bhavitvyamalik** [comment]
Hi @avasbr,
I tried your latest method but it gives me the following error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running NonMaxSuppression node. Name:'' Status Message: Not satisfied: ret.IsOK()
non_max_suppression.cc:116 ComputeNot satisfied: boxes_shape.NumDimensions() == 3
non_max_suppression.cc:77 PrepareComputeboxes must be a 3D tensor.
```
Also, why didn't you use center_point_box=1 while defining NMS node?

**Comment by avasbr** [comment]
@bhavitvyamalik do your bboxes have a batch dimension? for bboxes and scores the shapes need to be `[num_batch, num_anchors, 4]` and `[num_batch, num_classes, num_anchors]` respectively. Also, `center_point_box` just communicates what format your boxes are in, e.g. 1 = [cx, cy, w, h], 0=[x1, y1, x2, y2]. In my case, I needed them to be 0 because that's the format I went with, but that just depends on your implementation.

And yes, you can certainly use the defaults and do the filtering yourself, but in my case I wanted the NMS node to take care of that for me.

**Comment by afazel** [comment]
> Got it. Thanks again for all the help @dashesy
> 
> As an aside, I dug a bit more into the onnx docs and found this to be quite useful: https://github.com/onnx/onnx/blob/master/docs/IR.md
> 
> It doesn't cover specific examples of how to do things, but it clarified a number of concepts for me. In the end, I was able to attach a `NonMaxSuppression` op with `score_threshold`, `iou_threshold`, and `max_output_boxes_per_class` as constant values, and pass the onnx checker as well. For whoever it might help in the future, here's the full code that worked for me, when going from an onnx model that currently outputs decoded bboxes and scores:
> 
> onnx version: 1.7.0 pytorch version: 1.4.0
> 
> ```
> onnx_fpath = [Path to .onnx model]
> onnx_model = onnx.load(onnx_fpath)
> 
> # make constant tensors
> score_threshold = onnx.helper.make_tensor("score_threshold", TensorProto.FLOAT, [1], [0.9])
> iou_threshold = onnx.helper.make_tensor("iou_threshold", TensorProto.FLOAT, [1], [0.3])
> max_output_boxes_per_class = onnx.helper.make_tensor("max_output_boxes_per_class", TensorProto.INT64, [1], [200])
> 
> # create the NMS node
> inputs=['bboxes', 'scores', 'max_output_boxes_per_class', 'iou_threshold', 'score_threshold',]
> outputs = ["selected_indices"]
> nms_node = onnx.helper.make_node(
>     'NonMaxSuppression',
>     inputs,
>     ["selected_indices"],
> )
> 
> # add to the list of graph nodes
> graph.node.append(nms_node)
> 
> # append to the output (now the outputs would be scores, bboxes, selected_indices)
> output_value_info = onnx.helper.make_tensor_value_info("selected_indices", TensorProto.INT64, shape=[])
> graph.output.append(output_value_info)
> 
> # add to initializers - without this, onnx will not know where these came from, and complain that 
> # they're neither outputs of other nodes, nor inputs. As initializers, however, they are treated 
> # as constants needed for the NMS op
> graph.initializer.append(score_threshold)
> graph.initializer.append(iou_threshold)
> graph.initializer.append(max_output_boxes_per_class)
> 
> # check that it works and re-save
> onnx.checker.check_model(onnx_model)
> onnx.save(onnx_model, onnx_fpath)
> ```

Hi, I have created the onnx format model using the code you provided here, however when I test it using this code: 
```
ort_session = onnxruntime.InferenceSession("Complex_yolo_epoch_300_with_nms.onnx")
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input_imgs)}
            ort_outs = ort_session.run(None, ort_inputs)
```
It gives me this error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running NonMaxSuppression node. Name:'' Status Message: non_max_suppression.cc:92 PrepareCompute The most inner dimension in boxes must have 4 data.
```
I know that the shape of boxes should be [num_batches, spatial_dimension, 4] and in my case it is  [num_batches, spatial_dimension, 10], but I do not know how can I pass only the first 4 to NMS layer. How can I reshape it?
