### ISSUE TITLE
How onnx to get the any intermediate layers output?

### ISSUE THREAD

**Issue by wawltor** [onnx/onnx#2218]

**Comment by gramalingam** [comment]
That's more a question about a specific runtime: whether it provides a feature like that. From a ONNX perspective, you could add the intermediate variable of interest to the output list to promote it as an output variable.

**Comment by wawltor** [comment]
> That's more a question about a specific runtime: whether it provides a feature like that. From a ONNX perspective, you could add the intermediate variable of interest to the output list to promote it as an output variable.
yes, thank you for your answer, but some runtime tools like onnxruntime, caffe2backend are not to support to intermediate layers output ......

**Comment by wawltor** [comment]
> That's more a question about a specific runtime: whether it provides a feature like that. From a ONNX perspective, you could add the intermediate variable of interest to the output list to promote it as an output variable.

OK, thank you very much.

**Comment by MasterGG** [comment]
@gramalingam So how to add the intermediate layers as the output ?
