### ISSUE TITLE
onnx export supports only int64. my model weights and biases are floats. 

### ISSUE THREAD

**Issue by ajaysg** [onnx/onnx#2222]

**Comment by askhade** [comment]
Can you add more context?

**Comment by ajaysg** [comment]
**Description**
I am having a pytorch model which is exported to onnx format. I am trying to use that model in onnxruntime. But i am getting the error mentioned in the issue 

**System information**
- OS Platform and Distribution : **Linux Ubuntu 16.04**
- ONNX Runtime installed from (source or binary): **Binary via pip**
- ONNX Runtime version: **onnxruntime==0.4.0 (CPU version)**
- Python version: 3.6
- Visual Studio version (if applicable):**No**
- GCC/Compiler version (if compiling from source): **No**
- CUDA/cuDNN version:**CUDA 9/cuDNN 7**
- GPU model and memory:**Tesla K20XM and 6GB**

**Note: I am NOT USING onnxruntime-gpu**

**To Reproduce**
import onnx
import onnxruntime as rt
sess = rt.InferenceSession("waveglow.onnx")

**Expected Behavior**
After the session creation i should be able to infer with my model.

**Screenshots**
![oie_lcHA5bVXf4sL](https://user-images.githubusercontent.com/22977639/62302941-de5a4f80-b498-11e9-86a6-e3aa22eb8590.png)

Model is from the repository https://github.com/NVIDIA/waveglow/tree/4b1001fa3336a1184b8293745bb89b177457f09b

Link to original pytorch model: https://drive.google.com/file/d/1cjKPHbtAMh_4HTHmuIGNkbOkPBD9qwhj/view?usp=sharing

Link to onnx model:
https://drive.google.com/file/d/1N4D4pu-ibYBgm890ZJWRUkneQuyUKA_H/view?usp=sharing

**Script used to convert the pytorch model to onnx by passing dummy input**
waveglow_path = './waveglow_256channels.pt'
waveglow = torch.load(waveglow_path)['model']

mel_extra=torch.tensor(np.full((1,80,222),-10.0)).float()
dummy_input=torch.autograd.Variable(mel_extra).cuda().float()

audio = torch.tensor(np.full((1,222), -0.5)).float()
audio_input = torch.autograd.Variable(audio).cuda().float()

torch.onnx.export(waveglow, ((dummy_input, audio_input),), "./waveglow.onnx")

**Comment by ajaysg** [comment]
my model weights and biases are in float. Also my model accepts only float inputs. So i traced the onnx  graph with float inputs. when i try to use that in onnxrt i am getting the error.

**Comment by askhade** [comment]
Error: Type parameter (T) bound to different types (tensor(int64) and tensor(float) in node ()
This error indicates in your model you have a node whose inputs are not symmetric 1 input is int64_t ad another is float. This is a problem when the node spec expects both inputs to to of same type but encounters a model which has different types... Mul, Div are examples of such operators...

This seems like a model conversion issues.

**Comment by askhade** [comment]
Please open this issue here : https://github.com/pytorch/pytorch/issues?utf8=%E2%9C%93&q=is:issue+is:open+onnx
