### ISSUE TITLE
OnnxRunTime only supports LightGBMClassifier and not regressor?

### ISSUE THREAD

**Issue by shirazzaman** [onnx/onnx#2225]
Hi,
   I converted a lightgbm / xgboost regressor model and it throws error "untimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node LgbmRegressor:TreeEnsembleRegressor(1)"

However the Classifier works fine. Are Regressors not supported yet ? I am using latest version of onnxruntime and onnxmltools.

**Comment by gramalingam** [comment]
(This discussion belongs to onnxruntime: https://github.com/Microsoft/onnxruntime/issues ). I see an implementation in onnxruntime here: https://github.com/microsoft/onnxruntime/blob/9e926fef1cf7c0ed9ccde5e88453fd91266f3c9b/onnxruntime/core/providers/cpu/ml/treeregressor.cc#L10 ) for float type. Do you know if your model is using some other type (double, int32 or int64)?

**Comment by shirazzaman** [comment]
Thank you. I was trying with int64. I tried again with float types (np.random.random_sample) and it throws error [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime11NonOnnxTypeIdEE) , expected: (N11onnxruntime11NonOnnxTypeIfEE).

**Comment by shirazzaman** [comment]
It seems that the issues was ONNXRuntime only support float32, so i casted my dataframe to float32 and it worked !!!

However, the results i see from xgboost regressor is different from onnxruntime.
For example, xgboost prediction is 0.4275872 and onnxruntime predicts 0.53023404.

**Comment by shirazzaman** [comment]
lightgbm prediction on the other hand is closer to original.

**Comment by ebarsoum** [comment]
Please move this discussion to ONNX Runtime repo.
