### ISSUE TITLE
Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)

### ISSUE THREAD

**Issue by ajaysg** [onnx/onnx#2226]
What is the difference between Inferred elem type and existing elem type? i am getting this error when i try to use my onnx model in caffe2 backend. The error traceback is from this path 
**File "/home/x23/anaconda3/envs/onnx_parser/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)**

**Comment by ajaysg** [comment]
@prasanthpul

**Comment by gramalingam** [comment]
The likely explanation is that there is a type error in the model: for example, declaring a graph output Y to be a Int32 tensor type, while the type-inference of the node/op that produces the output Y indicates it is a float tensor type.

**Comment by ajaysg** [comment]
What can be done to resolve this error

**Comment by askhade** [comment]
Most likely this is model conversion issue. If you can identify which node is experiencing this issue and its input types then let us know. We can check the shape inference function and make sure there is no bug in the shape inference for this node.

**Comment by ajaysg** [comment]
**(op_type:Mul, name:): Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x23/anaconda3/envs/onnx_parser/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 704, in prepare
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/x23/anaconda3/envs/onnx_parser/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)

**There is no node specified in the traceback but the operator is Multiplication operator**

**Comment by ajaysg** [comment]
please find the attached text file of onnx graph . I can find Long(Int64) data type in all the **mul** nodes. Please advise me on how to resolve this issue
[2.txt](https://github.com/onnx/onnx/files/3480378/2.txt)

**Comment by askhade** [comment]
@spandantiwari : Can you take a look at this issue... this seems to be originating from model conversion

**Comment by gramalingam** [comment]
@ajaysg: is the ONNX model available? that might be more useful for debugging.

**Comment by gramalingam** [comment]
Actually, the following seems a mismatch:
```
  %966 : Long() = onnx::Mul(%961, %964), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %967 : Float() = onnx::ATen(%965), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %968 : Float() = onnx::Mul(%966, %967), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
```

**Comment by ajaysg** [comment]
yes @gramalingam not only there but in the following places also
`%1112 : Long() = onnx::Mul(%1107, %1110), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1113 : Float() = onnx::ATen(%1111), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1114 : Float() = onnx::Mul(%1112, %1113), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0`


`%1258 : Long() = onnx::Mul(%1253, %1256), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1259 : Float() = onnx::ATen(%1257), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1260 : Float() = onnx::Mul(%1258, %1259), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0`

`%1404 : Long() = onnx::Mul(%1399, %1402), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1405 : Float() = onnx::ATen(%1403), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1406 : Float() = onnx::Mul(%1404, %1405), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0`

`%1552 : Long() = onnx::Mul(%1547, %1550), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1553 : Float() = onnx::ATen(%1551), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1554 : Float() = onnx::Mul(%1552, %1553), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0`

`%1698 : Long() = onnx::Mul(%1693, %1696), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1699 : Float() = onnx::ATen(%1697), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0
  %1700 : Float() = onnx::Mul(%1698, %1699), scope: WaveGlow/Invertible1x1Conv # waveglow/glow.py:100:0`

and in some 12 nodes. The problem is with Mul operator

**Comment by ajaysg** [comment]
i could find opschema for Mul here

[https://github.com/onnx/onnx/blob/4eb737c8eacf48f8771d515d0a373a4b964cfab7/onnx/defs/math/defs.cc#L141](url)

it is calling a function called **MathDocGenerator**

[https://github.com/onnx/onnx/blob/4eb737c8eacf48f8771d515d0a373a4b964cfab7/onnx/defs/math/defs.cc#L23](url)
In the above mentioned line should we include different data types like 
float32 etc....

just an observation as i do not know the clear solution. please advise

**Comment by gramalingam** [comment]
@ajaysg : I assume that you generated this using the PyTorch ONNX exporter. If so, it looks like an issue for the PyTorch ONNX exporter to fix. Can you please create an issue over at PyTorch, here: https://github.com/pytorch/pytorch/issues?utf8=%E2%9C%93&q=is:issue+is:open+onnx

**Comment by askhade** [comment]
gramalingam and I were able to confirm this is indeed an issue with the Pytorch ONNX exporter and they have some guidance for working around it... Please open your issue in the repo added by gramalingam

Closing this issue here
