### ISSUE TITLE
The op support the SSD model

### ISSUE THREAD

**Issue by wawltor** [onnx/onnx#2227]
I saw the the CV SSD model in model zoom， I want to know which operators to support the model ssd, like box coder, prior box. Thank you very much.

**Comment by ebarsoum** [comment]
Here the list of all the operators in ONNX: https://github.com/onnx/onnx/blob/master/docs/Operators.md

You can also visualize the model in Netron: https://github.com/lutzroeder/netron

**Comment by ckqsars** [comment]
When I use onnx to run ssd model,  the error is "No Op registered for PriorBox with domain_version of 11".
But the PriorBox is in your operators list.

**Comment by fengyuentau** [comment]
@ckqsars Are you sure PriorBox is in the list of ONNX operators? I cannot find one.

**Comment by ThurgaShri** [comment]
PriorBox is in the caffe2onnx's list of operators, but not in the list of onnx operators. Any solution on how to overcome this issue of "No Op registered for PriorBox with domain_version of 11" when loading the converted model (caffe to onnx) in onnx?
