### ISSUE TITLE
Build on cmake3.1 will failed due to cmake_policy(SET CMP0063 NEW)

### ISSUE THREAD

**Issue by VictorYXL** [onnx/onnx#2229]
When try to build onnx on Ubuntu18.04 and cmake 3.1.3, the build will failed.
CMake Error at onnx/CMakeLists.txt:14 (cmake_policy):
  Policy "CMP0063" is not known to this version of CMake.

**Comment by VictorYXL** [comment]
CMP0063 dependents on CMake 3.3
https://cmake.org/cmake/help/v3.3/policy/CMP0063.html
So cmake_minimum_required should update to 3.3 or 
cmake_policy(SET CMP0063 NEW) should be add condition like 
if(POLICY CMP0063)
    cmake_policy(SET CMP0063 NEW)
endif()

**Comment by sutario** [comment]
good
