### ISSUE TITLE
Model incorrect after optimization with eliminate_identity

### ISSUE THREAD

**Issue by reymondzzzz** [onnx/onnx#2230]
I take onnxconverter-common from master. Convert my nested model from keras to onnx and call checker. All is well. But this model doesn't be optimized.

```
onnx_model = keras2onnx.convert_keras(model, model.name, target_opset=7)
passes = ['eliminate_identity']
onnx_model = onnx.optimizer.optimize(onnx_model, passes)
onnx.checker.check_model(onnx_model)

Traceback (most recent call last):
  File "/home/kstarkov/ml/detector/bin/deploy/freeze_model_to_onnx.py", line 73, in <module>
    onnx.checker.check_model(onnx_model)
  File "/home/kstarkov/py_envs/p3_keras_tensorflow/lib/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
```
This problem only with eliminate_identity. Another passes working is good.
InferenceSession with optimized model falls.
```
onnx_model = onnx.optimizer.optimize(onnx_model, passes)
onnx.save(onnx_model, onnx_output_filename)
sess = rt.InferenceSession(onnx_output_filename)
input_name = sess.get_inputs()[0].name
onnx_out = sess.run([o.name for o in sess.get_outputs()], {input_name: input_data})

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by askhade** [comment]
@reymondzzzz : Can you share your model?

**Comment by reymondzzzz** [comment]
@askhade Sorry, I can not share my model, but I can share code with reproduce problem
[test.zip](https://github.com/onnx/onnx/files/3492525/test.zip)

**Comment by dashesy** [comment]
I have simillar issue with `fuse_bn_into_conv` pass [here](https://github.com/onnx/onnx/issues/2401)

**Comment by daquexian** [comment]
It has been fixed by https://github.com/onnx/onnx/pull/2574 (and onnx-optimizer has been moved to https://github.com/onnx/optimizer). Please feel free to reopen it if the problem still exists.
