### ISSUE TITLE
dump model to plain c

### ISSUE THREAD

**Issue by rspadim** [onnx/onnx#2232]
hi folks, there's any tool to convert onnx to plain c code? something to predict "row" by "row"?

predict(array_of_double_in, array_of_double_out)

thanks

**Comment by prasanthpul** [comment]
do you mean you want to run an ONNX model from C code?

**Comment by ebarsoum** [comment]
I am not aware of any tool that convert ONNX model to plain c code, but you can use ONNX Runtime (https://github.com/microsoft/onnxruntime) from C API to evaluate any ONNX model.

**Comment by XVilka** [comment]
You might want to extend something like these:
- https://github.com/codeplea/genann
- https://github.com/attractivechaos/kann

Both would require some patching, but I am sure that's feasible.
