### ISSUE TITLE
onnx model 50x slower than in pytorch

### ISSUE THREAD

**Issue by drapado** [onnx/onnx#2238]
Hi, I exported my deep learning model from pytorch with an inference time of 2 ms. When I run it on onnx (doesn't matter onnx, onnx runtime python or C#) the inference time goes to 100 ms.

I also notice the GPU usage not going more than 30% when processing images.

Is this normal?

**Comment by prasanthpul** [comment]
This is not expected.

The ONNX repository does not have any runtime. Sounds like you are using ONNX Runtime. Can you open this in the https://github.com/microsoft/onnxruntime repo? Be sure to specify the versions of PyTorch, ONNX Runtime, and opset version. If possible, share the model.
