### ISSUE TITLE
Why the number of output for Concat Op is one?

### ISSUE THREAD

**Issue by qzhong0605** [onnx/onnx#2243]
I got an onnx model converted from densenet121 caffe2 model. However, the `concat` operator for caffe2 has two outputs, including `concat result` and `split_info`, and the output of `concat` operator have only one. And I got the following result for `concat` operator
```
onnx_node: input: "concat_5_13"
input: "conv5_14/x2"
output: "concat_5_14"
name: ""
op_type: "Concat"
attribute {
  name: "axis"
  i: 1
  type: INT
}

onnx_node: output: "_concat_5_14_dims"
op_type: "Constant"
attribute {
  name: "value"
  t {
    dims: 2
    data_type: 6
    name: "split_info"
    raw_data: "\007\000\000\000\007\000\000\000"
  }
  type: TENSOR
}
```
Q:
1. Why does the output of `concat` for `onnx` have only one  ?
2. If the output has only one, why we need save the `split_info` output of `concat` operator for `caffe2` when performing transformation. Here , we wouldn't connect all the nodes into a DAG graph.

**Comment by linkerzhang** [comment]
1. Yes, Concat op was designed with having only one output https://github.com/onnx/onnx/blob/master/docs/Operators.md#concat. The split_info (the other output designed in Caffe2) should be used for training support, but ONNX was designed for inference only (we are now in the process of adding training support though).
2. When doing transformation (from caffe2 to onnx), the reason to add a separate constant node to keep the split info is actually just for keeping information complete, I believe. @bddppq or @houseroad  may help to confirm please. The Constant node may not be needed in model inference though.
