### ISSUE TITLE
slice_axis  has input size 1 not in range [min=3, max=5].

### ISSUE THREAD

**Issue by caiqi** [onnx/onnx#2245]
I tried to convert mxnet model to onnx format.With onnx 1.3, the slice operation is normal. But with onnx 1.5, the slice_axis convertion fails :

op_type: "Slice" attribute { name: "axes" ints: 3 type: INTS } attribute { name: "ends" ints: 2 type: INTS } attribute { name: "starts" ints: 0 type: INTS }

Thanks.

**Comment by caiqi** [comment]
A simple reproducible code is: 

```
from mxnet import gluon
import numpy as np
from onnx import checker
import onnx
import mxnet as mx
from mxnet.contrib import onnx as onnx_mxnet

print("mx version", mx.__version__)
print("onnx version", onnx.__version__)


class SimpleModule(gluon.HybridBlock):
    def __init__(self, **kwargs):
        super(SimpleModule, self).__init__(**kwargs)
        with self.name_scope():
            offsets = np.ones((1, 128, 10, 10))
            self.offsets = self.params.get_constant('offset', offsets)

    def hybrid_forward(self, F, x, offsets):
        x = x.slice_axis(axis=2, begin=0, end=10)
        x = x.slice_axis(axis=3, begin=0, end=10)
        x = x + offsets
        return x


net = SimpleModule()

net.initialize()
net.collect_params().reset_ctx(mx.gpu())
fake_image = mx.nd.random.uniform(shape=(1, 128, 20, 20), ctx=mx.gpu())
net.hybridize()
result = net(fake_image)
net.export('simple_slice')

sym = 'simple_slice-symbol.json'
params = 'simple_slice-0000.params'
input_shape = (1, 128, 20, 20)

onnx_file = './mxnet_exported_slices.onnx'

converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)

model_proto = onnx.load_model(converted_model_path)
checker.check_graph(model_proto.graph)

```

mx version 1.5.0
onnx version 1.5.0

**Comment by YIYANGCAI** [comment]
same problem

**Comment by YIYANGCAI** [comment]
I just find the source code of Slice, finding out that all method in it has parameters from 3 to 5, the starts, ends, and axes are inputs, not attributes

**Comment by askhade** [comment]
@YIYANGCAI  yes you are right... Slice op was updated and since version 10 some attributes were move to be inputs. Please take a look here :

https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-3---5

**Comment by krishnak** [comment]
is there a work around, I don't know the intricacies of both mxnet as well as ONNX, I need to convert mxnet to caffe model and I was trying to get to ONNX as an  intermediate model and I am bitten by this bug?

**Comment by YZW-explorer** [comment]
Hello everyone!How did you solve this problem?I ran into the same problem.
