### ISSUE TITLE
KeyError: 'max_unpool2d' pytorch to onnx 

### ISSUE THREAD

**Issue by habib-19** [onnx/onnx#2251]
Unable to convert [ENet](https://github.com/davidtvs/PyTorch-ENet) to ONNX because of missing max_unpool2d error? 

ONNX export failed on ATen operator max_unpool2d because torch.onnx.symbolic_opset9.max_unpool2d does not exist

operating system: Ubuntu 18.04.1 LTS
Python 3.6.9 :: Anaconda, Inc.
Torch 1.2.0

ONNX export failed on ATen operator max_unpool2d because torch.onnx.symbolic_opset9                      .max_unpool2d does not exist

**KeyError: 'max_unpool2d'**

**Comment by prasanthpul** [comment]
Looks like a bug in PyTorch. Please file issue in that repo. @spandantiwari as heads up.
