### ISSUE TITLE
 not a valid scope name in onnx_tf.backend  and ONNX FATAL in  onnx_caffe2_backend when running one onnx model

### ISSUE THREAD

**Issue by xqch1983** [onnx/onnx#2254]
Hi ,
I downloaded onnx model **ssd-mobilenet 300x300** from https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection, and try to run these modle using two backend seperately. but failed with folloing info.
ONNX FATAL: Don't know how to translate op Resize
ONNX FATAL: Don't know how to translate op NonMaxSuppression in **caffe2.python.onnx.backend**
ValueError: 'image_tensor:0' is not a valid scope name in onnx_tf.backend. 
later, try to attached the script codes here.

**Comment by prasanthpul** [comment]
These seem like bugs in caffe2 and in TF. suggest opening in the those repos.

Consider using [ONNX Runtime](https://github.com/microsoft/onnxruntime) which runs these models.
