### ISSUE TITLE
Modifying / optimizing a graph after export

### ISSUE THREAD

**Issue by tanguycdls** [onnx/onnx#2259]
Hi I have a similar case than #2216, I also want to be able to modify a graph generated through Pytorch: I would like to be able to keep only a part of a graph: The usecase is if we have two inputs of the graph that are now fixed and we want to optimize the graph. 
```
InputA + InputB -> Int1
inputD + inputE -> Int2
int1 + Int2 -> output. 
```
If InputD and InputE are constant we can simplify the graph and keep only a constant node Int2;
How can I simplify a graph as so ? I found https://github.com/onnx/onnx/blob/master/onnx/examples/Protobufs.ipynb
I tried the following:
-Create an initializer with 
`tenseurs = helper.make_tensor('ExampleConstant', TensorProto.FLOAT, [12], np.random.rand(12))`
- Then we create a node with constant value following the example in https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant
I can then remove the previous node and add my node instead at the good position and recreate a new graph using 
```
helper.make_graph(new_node, 'test_model', onnx_model.graph.input,
                  onnx_model.graph.output,
                  initializer=onnx_model.graph.initializer)
```
- When I compare that with Pytorch: I found that Pytorch consider the weights matrix as an input and initialize them in model.graph.initializer. What's the difference between using the Constant  operator with a tensor value and using an Initializer as an input of the graph? 

- Also I got an error with the graph not being topologically sorted, is there any function to do that ?
- Are there any plan to include over ONNX a graph library to make those change easier ? In Python we could use NetworkX Directed Graph as a wrapper around nodes. If yes I could be interested to contribute.

**Comment by dashesy** [comment]
@tanguycdls There is a `extract_constant_to_initializer` in `onnx.optimizer` not very well documented but I think that is what moves constants to become initializer. Also I noticed changing the graph is easier than recreating it with `make_graph`, just use `append`, `remove` and `insert`.
For example this is how I modify an invalid graph to make Pad opset11 and remove Equal (that for some reason is different in opset11 also

```python
onnx_model = onnx.load(onnxfile)
graph = onnx_model.graph
pads = onnx.helper.make_tensor('avg_pads', onnx.TensorProto.INT64, [8], np.zeros(8, dtype=int))
graph.initializer.append(pads)
node = graph.node[584]
new_node = onnx.helper.make_node(
    'Pad',
    name='__Pad_584_fixed',
    inputs=['675', 'avg_pads'],
    outputs=['676'],
    mode='constant'
)
graph.node.remove(node)
graph.node.insert(584, new_node)
# Fix Equals (replace with Not)
node = graph.node[322]
new_node = onnx.helper.make_node(
    'Not',
    name='__Not__Equal_322',
    inputs=['412'],
    outputs=['414'],
)
graph.node.remove(node)
graph.node.insert(322, new_node)

onnx.checker.check_model(onnx_model)
onnx.save(onnx_model, onnxfile)
```

**Comment by qiuyang163** [comment]
@dashesy  why when I use graph.node.insert function, it tips me 'AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'insert'' error ?

**Comment by MasterGG** [comment]
how to add a intermediate layer to the output list?

**Comment by dashesy** [comment]
> @dashesy why when I use graph.node.insert function, it tips me 'AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'insert'' error ?

odd, not sure. This is what I get:

```python
In [63]: type(graph.node)
Out[63]: google.protobuf.pyext._message.RepeatedCompositeContainer

In [64]: graph.node.insert?
Docstring: Inserts a message before the specified index.
Type:      builtin_function_or_method
```

@MasterGG Have you tried adding it to `graph.output`? you will need to add a value_info.

First find the output name from the node you want the output of

```python
n = [n for n in graph.node if n.output == ['prob']][0]
```

[Create value_info](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#creating-an-onnx-model-using-helper-functions) and add it to `graph.output`

```python
prob_info = helper.make_tensor_value_info('prob', TensorProto.FLOAT, [1, 4])
graph.output.insert(1,prob_info)
```

**Comment by MasterGG** [comment]
@dashesy Thanks for your advice, it solved my confusion perfectly.

**Comment by WangXuanBT** [comment]
> @dashesy why when I use graph.node.insert function, it tips me 'AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'insert'' error ?

I met the same problem, just update your protobuf to a newer version. 
u may need conda install -c anaconda protobuf==3.11.4
