### ISSUE TITLE
slice op in 1.5.0 is not work

### ISSUE THREAD

**Issue by cjt222** [onnx/onnx#2268]
my onnx is 1.5.0, i try to use slice op to deal with data，which input shape is [20,10,5]，but it not work which shape of output is not changed,but when i install onnx 1.4.1, it works well,i want to know if i use this op in a wrong way

![image](https://user-images.githubusercontent.com/17508662/63910512-927bd580-ca59-11e9-910a-2165df0793f1.png)
![image](https://user-images.githubusercontent.com/17508662/63910590-f9998a00-ca59-11e9-969e-f31dbbe731f8.png)

![image](https://user-images.githubusercontent.com/17508662/63910572-e25a9c80-ca59-11e9-8fcb-b7296a52c252.png)

**Comment by askhade** [comment]
@cjt222 :Slice was updated in opset 10 : https://github.com/onnx/onnx/blob/master/docs/Operators.md#slice

Please make sure your slice op is configured right for the opset version you are using.

**Comment by cjt222** [comment]
yeah，i try to 10 is ok, but 9is wrong

**Comment by wschin** [comment]
If you want to use `Slice` in opset 9, you need to make sure [this field](https://github.com/onnx/onnx/blob/414285bbab4e1a260ee09d6c9cb7fd90eae97049/onnx/onnx.proto#L218) only contains opset 9. You can print out your ONNX model for double-checking.
