### ISSUE TITLE
export CNN RNN model pytorch onnx

### ISSUE THREAD

**Issue by cristinasegalin** [onnx/onnx#2270]
I am trying to convert a pytorch cnn followed by rnn to onnx.
Not sure if I have to export them separately or there is a way to export the combined network in one pass only.

**Comment by askhade** [comment]
@cristinasegalin  : Please use pytorch repo for pytorch exporter related issues\questions : https://github.com/pytorch/pytorch/issues?utf8=%E2%9C%93&q=is:issue+is:open+onnx
