### ISSUE TITLE
Question about QLinearMatMul operator

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx#2282]
Here are the operations required for QLinearMatMul
1. Dequantize a and Dequantize b
2. MatMul(a, b)
3. Quantize x 

I'm wondering can we use the existing operators like DequantizeLinear, MatMul and QuantizeLinear to do the same thing instead of introduce a new operator?

After I reread the description of all three operators, I notice that DequantizeLinear and QuantizeLinear both have scale and zero_point as scalar only, but QLinearMatMul state that scale and zero_point can be scalar or 1-D tensor( per row for 'a' and per column for 'b') 

Is it possible to extend DequantizeLinear and QuantizeLinear  to support 1-D tensor as input for scale and zero_point and also add one more input to indicate the scale and zero_point should be apply per row or per column of input x?

**Comment by jcwchen** [comment]
DequantizeLinear and QuantizeLinear should support 1-D tensor as input for scale and zero_point now: https://github.com/onnx/onnx/pull/2772

**Comment by jcwchen** [comment]
Close it now since it should be resolved. Please reopen it if you still have question. Thanks!
