### ISSUE TITLE
Behavior of cast needs clearer spec

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#2285]
Current spec reads:

> Conversion from a numerical type to any numerical type is always allowed. User must be aware of precision loss and value change caused by range difference between two types. For example, a 64-bit float 3.1415926459 may be round to a 32-bit float 3.141592. Similarly, converting an integer 36 to Boolean may produce 1 because we truncate bits which can't be stored in the targeted type"

Two issues that need clarification:
* For float->int, is the behavior truncation towards zero, round to nearest, floor, or ceiling?
* If the result is out of bounds for the output type, is the behavior clamping or truncation?  For example, converting 36 to Boolean should be `false` if bits are truncated, since 36 is `10100` in binary.

**Comment by ArchRobison** [comment]
Thanks for the clarification.

**Comment by ebarsoum** [comment]
Can you submit a PR?

**Comment by MaximKalininMS** [comment]
In addition, what happens when the value is out of range or nan? As a point of reference, in numpy:
```
>>> x = np.array([-40000.0, -30000.0, -2.7, -2.5, -2.2, -1.7, -1.5, -1.2, 0, 1.2, 1.5, 1.7, 2.2, 2.5, 2.7, 30000.0, 40000.0, float('nan'), float('inf')])
>>> x.astype(np.int16)
array([ 25536, -30000,     -2,     -2,     -2,     -1,     -1,     -1,
            0,      1,      1,      1,      2,      2,      2,  30000,
       -25536,      0,      0], dtype=int16)
>>> x.astype(np.bool)
array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])
```

**Comment by askhade** [comment]
Looks like this is done... Closing this PR. Please open a new one if there are concerns or questions.

**Comment by fdwr** [comment]
> Please open a new one if there are concerns
The wording could be better still. Currently it weakly implies the behavior with "...an integer *may* result 100" rather than a clear authoritative wording like "rounding to an integer *yields* 100 because of truncation". Also, the Cast ONNX backend tests are very light, lacking even a single integer test case [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-14). That should be fixed, but I'd open a separate issue for that.
