### ISSUE TITLE
ONNX Checker doesn't validate input type related creteria 

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#2292]
Ideally ONNX checker should validate all the type related criteria. 

For example - Type homogeneity should be enforced. If two inputs are bound to type parameter T, a check should ensure that the inputs are indeed homogeneous in the model graph (and that the input types are valid per op spec).

**Comment by wschin** [comment]
It sounds very reasonable. Would you be able to add a fix? :)

**Comment by hariharans29** [comment]
Thanks @wschin. @RandyShuai will most probably work on improving the checker. If he cannot get to this, I ll take a look at this. :)

**Comment by gramalingam** [comment]
As further information: please note that there are really two parts to "checking" a model. One is the so-called "checker" documented here: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#checking-an-onnx-model . The second is the so-called "shape inference" documented here: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#running-shape-inference-on-an-onnx-model . The second one is also a checker that can report errors in an input model. The job of checking for type errors belongs to the second checker. 

Having said that, there is some functionality missing in the second inference tool, which I have described to @RandyShuai. Hopefully, he will be adding this.

**Comment by hariharans29** [comment]
@gramalingam - Thanks for the info. Should the shape and type inferencing be done automatically as part of the first checker as well ? That way we can by a single API call validate a model wholisticially ? Is there a rationale why there should be 2 separate "checkers" ?

**Comment by gramalingam** [comment]
@hariharans29 : yes … we should expose a single top-level checker that calls both lower-level checkers internally.

**Comment by RandySheriffH** [comment]
Let's see if this is what we need:
https://github.com/onnx/onnx/pull/2367

**Comment by hariharans29** [comment]
I checked the commit - looks great. So I guess we just need to call check_model() with full_check = True.

Thanks @RandySheriffH.
