### ISSUE TITLE
There is a gap between onnx and onnx backends

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx#2300]
Since a long time ago, onnx supported up to opset10, and many onnx models added to official model zoo. but there are little backend supports fully of them.
 such as onnx_tensorrt.

It's impossible convert onnx model trt engine using `onnx2trt` after several months opset10 release.

When will those ops updated by these backends such as ONNX TensorRT?

**Comment by jinfagang** [comment]
BTW, if there any plugin needs to written, then how to contribute to `onnx_tensorrt` to make them support? Any docs or guidelines?

**Comment by wschin** [comment]
TensorRT has been integrated into https://github.com/microsoft/onnxruntime with many other computation [providers ](https://github.com/microsoft/onnxruntime#high-performance). It's cross-platform and a lightweight engine.
