### ISSUE TITLE
Add optimizer pass: Remove single input Concat operations 

### ISSUE THREAD

**Issue by HarryVancao** [onnx/onnx#2308]
As per https://github.com/onnx/models/issues/214, some models may contain "Concat" operators with only one input. This is essentially an identity operation. 

Adding a pass to detect this can help reduce file size with additional benefits.

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have questions related to the optimizer, please raise an issue there. Thank you!
