### ISSUE TITLE
Do the output tensors of the "IF" operator's subgraphs need to have the same names?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2309]
The outputs of the IF operator are the outputs of whichever of its two subgraphs was executed. The Doc says that the outputs of the two subgraphs **"must be of the same shape and same data type"**. But must they also have the same names? 

I would expect so. Otherwise, the IF operator would introduce different names into the workspace depending on which branch of the IF was excecuted. 

Please clarify,
Thanks

**Comment by gramalingam** [comment]
Closing this issue. Please reopen in case any further clarification is required.
