### ISSUE TITLE
Do two subgraphs with the same name refer to the same graph (with shared weights)?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2311]
If an ONNX file contains two subgraphs called by different operators, but the subgraphs have the same name, are they necessarily the same graph, or could they be completely different? 

If they are the same graph, is the intention that the two instances share the same parameters?

**Comment by gramalingam** [comment]
An ONNX model does not (currently) have a mechanism to create a named subgraph that can be referenced and used by multiple nodes. Instead, subgraphs are defined "inline" in a node as an attribute value. So, there is no question of multiple nodes sharing a subgraph. (The plan for shared subgraphs is actually to use "functions" but this is also a future extension.)
