### ISSUE TITLE
Allow creation of older opset ops/nodes 

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#2313]
It will be great if the onnx helper's `make_node()` abstraction helps us create older opset nodes/ops that we can use to cover shape inference tests and support testing the optimizer passesfor the older version of the op's spec. 

This will help guard against shape inference regressions for older opsets and test to make sure optimizer passes can handle correctly all versions of an op's spec.

**Comment by gramalingam** [comment]
This already exists, at least for the shape inference use case mentioned. For example, see https://github.com/onnx/onnx/blob/1316afc9f972f81340faa05763e2898f38bcc3b0/onnx/test/shape_inference_test.py#L1484 for a shape-inference testcase for a specific opset version. (I haven't looked at optimizer passes, so don't know about it.)

**Comment by gramalingam** [comment]
opset is specified at the graph/model level, not at a node level.

**Comment by hariharans29** [comment]
Hi @gramalingam -

Thanks for pointing this out.

I understand that opset is at a model/graph level - this makes sense but I did think we needed to pass some sort of opset identifier while using `make_node()` from the helper.py to construct a `NodeProto` - apparently not. 

I tried following that logic from the line you just pointed and it looks like internally `make_model()` is called. I think in the optimizer case, we need to modify the internal class `TestOptimizer`'s API where `make_model()` is called to support older opset models.

**Comment by hariharans29** [comment]
Hi @gramalingam and @wschin -

As part of #2031, I added support in the class `TestOptimizer` to create a model with an older opset and I preserved the previous opset optimizer tests for `Pad` (renamed `..._opset10`). So #2031will resolve this issue.

**Comment by wschin** [comment]
Since this issue can already be solved by existing infra, please let me close it.
