### ISSUE TITLE
How to test a single node input and output?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx#2319]
I followed a example from [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample)

Here is test script:

```
import onnx
import numpy as np
# import expect
from onnx import helper
from onnx.backend.test.case.node import expect


node = onnx.helper.make_node(
    'Upsample',
    inputs=['X', 'scales'],
    outputs=['Y'],
    mode='nearest'
)
print(node)

data = np.array([[[
    [1, 2],
    [3, 4]
]]], dtype=np.float32)

scales = np.array([1, 1, 2, 3], dtype=np.float32)
output = np.array([[[
    [1, 1, 1, 2, 2, 2],
    [1, 1, 1, 2, 2, 2],
    [3, 3, 3, 4, 4, 4],
    [3, 3, 3, 4, 4, 6],
]]], dtype=np.float32)

expect(node, inputs=[data, scales], outputs=[output],
       name='test_upsample_nearest', opset_imports=[helper.make_opsetid("", 9)])
```

How should I see the output with input? Does it only valid with shape rather than value?

**Comment by gramalingam** [comment]
The above code is used to **generate a test case**, which can be used to test any implementation of ONNX. ONNX itself does not provide any implementations of the ops that users can use to run examples or test-cases.

**Comment by worry54** [comment]
What does function `expect` mean? Where is the test case generated saved, and how can I use it?

**Comment by GeneralJing** [comment]
same question. can anyone give more explanation on this?
