### ISSUE TITLE
Operator signature consistency

### ISSUE THREAD

**Issue by prasanthpul** [onnx/onnx#232]
There is inconsistency in some of the operator signatures. Propose establish these guidelines and update any operators that do not follow them:
- All attribute names should be lower case and use underscores when it helps with readability
- Any input/output variable represented by a single letter is capitalized (i.e. X)
- Any input/output variable represented by a full word or multiple words is all lower case and uses underscores when it helps with readability
- Any input/output variable that represents a bias tensor will utilize the name "B"
- Any input/output variable that represents a weight tensor will utilize the name “W”
- “axes” vs. “axis”
- “axes” is used when an input, output or attribute is representing multiple axis
- “axis” is used when an input, output or attribute is representing a single axis
- Default type for integers will use variants on int, no uints, default is int64
- Any instance of multiplying a weight tensor by input tensor and adding bias we’ll following the format of W*X^T+B

**Comment by dzhulgakov** [comment]
Proposal sound reasonable.

For input/output names they are currently serve purely descriptive purposes and don't get serialized in models. Thus we can freely rename them for consistency.

Attributes do get serialized and thus 'axis/axes' is a breaking change. In terms of naming - the only attribute that doesn't adhere to your proposal is `transA/transB` on `Gemm`. Not sure whether we want to change those.

**Comment by prasanthpul** [comment]
For bias we were pretty consistently using "bias" already, so I went with that and fixed the few inconsistent ones in #245

**Comment by prasanthpul** [comment]
Proposal changed for: All attribute names should be lower case and use underscores when it helps with readability

**Comment by prasanthpul** [comment]
Closing this issue as this is now covered by PR #270
