### ISSUE TITLE
Time to upgrade protobuf

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2321]
I got the error message below about a deprecated Python feature when running ONNX tests locally. It seems that it's time to upgrade ONNX to use newer protobuf version. Otherwise, our code might not work with Python 3.8.
```
c:\programdata\anaconda3\lib\site-packages\google\protobuf\descriptor.py:47
c:\programdata\anaconda3\lib\site-packages\google\protobuf\descriptor.py:47:

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
 from google.protobuf.pyext import _message
```
Here is how it can be reproduced.

1. pip install -e onnx
2. cd onnx
3. pytest

Not using recent versions of protobuf also causes [problem](https://github.com/conda-forge/onnx-feedstock/issues/29) and [problem](https://github.com/conda-forge/onnx-feedstock/issues/14) to other packages.

**Comment by cdluminate** [comment]
Any progress?

**Comment by askhade** [comment]
ONNX now uses protobuf 3.11.3 for linux, windows and mac
