### ISSUE TITLE
Shape inference broken

### ISSUE THREAD

**Issue by letmaik** [onnx/onnx#2322]
See https://github.com/onnx/tensorflow-onnx/issues/674#issuecomment-531965813.

After https://github.com/onnx/tensorflow-onnx/pull/557 got merged, doing shape inference via `onnx.shape_inference.infer_shapes(m)` doesn't work anymore. I'm using the onnx 1.5.0. This is for opset 9.

**Comment by wschin** [comment]
Thanks for reporting. Do you have a minimal model for reproducing the error message?

**Comment by letmaik** [comment]
Not at the moment, are there any unit tests for this? Maybe I can spot what's missing.

**Comment by wschin** [comment]
Given that the shape inference is broken, I don't feel we have a test. It'd be awesome if you can make one.

**Comment by raj-parihar** [comment]
Did this get fix?

**Comment by askhade** [comment]
this has been fixed now. Refer to PR https://github.com/onnx/onnx/pull/2901
