### ISSUE TITLE
Typo in MaxPool definition ceil_mode attribute

### ISSUE THREAD

**Issue by HarryVancao** [onnx/onnx#2325]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-37

ceil_mode: 
"Wether to use ceil or floor (default) to compute the output shape.:"
should be 
**Whether** to use ceil or floor (default) to compute the output shape.

**Comment by jcwchen** [comment]
I think it has been fixed. Thanks for brining this up.
