### ISSUE TITLE
[Feature Request] Debug ops

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2327]
Can we add a `debug` ops, that would be a no-op instruction, just with configurable scopes to attach to things like input/output shapes and values?

**Comment by wschin** [comment]
Humm, I guess you are talking about runtime engine's ability to debug a model execution. Is it related to spec?

**Comment by dashesy** [comment]
No, this is like a scope that is added to a LabView model. Let's say I want to inspect data/shape that passes an edge, I can attach a scope node to it. Then depending on the runtime, the scope could just print the values, or graph them or log them.

**Comment by dashesy** [comment]
A custom ops for a specific runtime? so I would for example install `onnxruntime` and then add an `onnxruntime.debug(x: Tensor)->Tensor` node?
That would couple runtime to the platform too tightly, whereas a debug node would leave the runtime to use the already exported model and log/debug/breakpoint at a given debug ops.
