### ISSUE TITLE
Implement constant folding optimizer pass

### ISSUE THREAD

**Issue by letmaik** [onnx/onnx#2331]
It would be good if a "constant fold" optimizer pass was implemented. This is related to https://github.com/onnx/onnx/issues/1309.

**Comment by daquexian** [comment]
I have developed https://github.com/daquexian/onnx-simplifier for exactly the same problem depending on onnx runtime.

Actually, I doubt whether it can be implemented as an optimization pass -- it requires the pass to inference the model.

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have questions related to the optimizer, please raise an issue there. Thank you!
