### ISSUE TITLE
Issue Exporting Pytorch model that uses PackedSequence

### ISSUE THREAD

**Issue by daquilnp** [onnx/onnx#2334]
I have a model where I manipulate some data and place it in a PackedSequence.

Here is the snippet I use it for:
```
t_word_attention= self.word_attention(packed_sentences.data,
                                                     packed_words_per_sentence.data)  
t_word_attention= self.dropout(t_word_attention)
input_packed_sentences = PackedSequence(data=t_word_attention,
                                   batch_sizes=packed_sentences.batch_sizes,
                                    sorted_indices=packed_sentences.sorted_indices,
                                    unsorted_indices=packed_sentences.unsorted_indices)
out, _ = self.sentence_rnn(input_packed_sentences)
```
It works great during training and inference. However, when I try to export the model to ONNX I get the following error:
`ONNX export failed: Cannot export individual pack_padded_sequence or pad_packed_sequence; these operations must occur in pairs.`

I am running Pytorch 1.2.0 and ONNX 1.5.0

**Comment by prasanthpul** [comment]
Since this is an issue with PyTorch export, please file the issue in PyTorch repo. @spandantiwari as fyi
