### ISSUE TITLE
[Feature request] MaxPool operator should have optional "input_shape" output

### ISSUE THREAD

**Issue by HarryVancao** [onnx/onnx#2341]
The MaxUnpool operator has an optional input, called output_shape which acts as a replacement for the pad attribute. Typically this is to eliminate ambiguity on the shape of the MaxUnpool's output. 

Since the typical MaxUnpool operator is linked to a MaxPool operator, it would be useful to have the MaxPool operator optionally output its corresponding input_shape.

**Comment by fdwr** [comment]
Wouldn't just call `Shape(X)`?

Currently one does:
1. `MaxPool(X) -> (Y, I)`
2. ... stuff ...
3. `MaxUnpool(Y, I, Shape(X)) -> originalX`

And you're proposing:
1. `MaxPool(X) -> (Y, I, input_shape)`
2. ... stuff ...
3. `MaxUnpool(Y, I, input_shape) -> originalX`

Correct assessment?

**Comment by HarryVancao** [comment]
Yes, your assessment is correct. The shape method that you proposed is a good alternative to changing the specification.
