### ISSUE TITLE
Build Fail on Windows with Anaconda

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2349]
The build fails again with my new Anaconda3 with python 3.7, 3.6, and 3.5. All of them produce the same error message.

onnxifi_dummy.vcxproj -> C:\Users\wechi\Repos\onnx\.setuptools-cmake-build\Release\onnxifi_dummy.dll
onnxifi_loader.vcxproj -> C:\Users\wechi\Repos\onnx\.setuptools-cmake-build\Release\onnxifi_loader.lib
Running gen_proto.py on onnx/onnx.in.proto                                                                                                                                                           onnxifi_wrapper.vcxproj -> C:\Users\wechi\Repos\onnx\.setuptools-cmake-build\Release\onnxifi.dll                                                                                                     Processing C:\Users\wechi\Repos\onnx\onnx\onnx.in.proto
Writing C:/Users/wechi/Repos/onnx/.setuptools-cmake-build/onnx\onnx.proto                                                       Writing C:/Users/wechi/Repos/onnx/.setuptools-cmake-build/onnx\onnx.proto3                                    generating C:/Users/wechi/Repos/onnx/.setuptools-cmake-build/onnx\onnx_pb.py                                               Building Custom Rule C:/Users/wechi/Repos/onnx/CMakeLists.txt
Running C++ protocol buffer compiler on C:/Users/wechi/Repos/onnx/.setuptools-cmake-build/onnx/onnx.proto
The system cannot find the path specified.                                                                                                                                                           Writing mypy to onnx/onnx_pb2.pyi
**--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.**

It seems other people encountered this issue a while back ago (https://github.com/onnx/onnx/issues/1924, https://github.com/onnx/onnx/issues/1314). It'd be nice if this can be fixed.

**Comment by askhade** [comment]
@wschin : Can you check PR #2452 I have added detailed instructions on building ONNX on Windows with Anaconda...

**Comment by yuslepukhin** [comment]
This is has been resolved.
