### ISSUE TITLE
NonMaxSuppression with option to output all boxes

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2352]
[NonMaxSuppression](https://github.com/onnx/onnx/blob/master/docs/Operators.md#nonmaxsuppression) has no option to return all the boxes.

This is in the docs:

> max_output_boxes_per_class (optional) : tensor(int64)
Integer representing the maximum number of boxes to be selected per batch per class. It is a scalar. Default to 0, which means no output.

`0` means no output, not very useful. So if I want to get all the boxes I think I should set that to MAX_INT64? but that is not very elegant. Instead the specs could assume `max_output_boxes_per_class < 0` means no limits

**Comment by jinfagang** [comment]
@dashesy Hi. Why do u have this demand? Do u want get fix dimension of final output (using for convert to TensorRT or something?)

**Comment by dashesy** [comment]
I use NMS with a dynamic size of pixels, the network input is `1x3xdyn_size_1xdyn_size_2` and the final number of pixels are `1x3x anchors x dyn_size1/32 x dyn_size_2/32` 
So I cannot set a `max_output_boxes_per_class`. I am certain it will never be `10000` in practice and set it to that number, but it does not sound very nice.

I noticed the slice ops also set a very high number when the upper bound is not set, (`MAX_INT64`) so maybe I should do the same and set to `MAX_INT64`? in which I will close this issue.
