### ISSUE TITLE
Could you add a parameter for Resize OP to suit align_corners =True in resize_bilinear in Paddle

### ISSUE THREAD

**Issue by cjt222** [onnx/onnx#2359]
When i transform paddle to onnx， resize_bilinear OP has diff with Resize OP in onnx when align_corners =True，could you a parameter for Resize OP to suit align_corners =True in resize_bilinear in Paddle? Maybe when  align_corners =True，they has difference in below:

![image](https://user-images.githubusercontent.com/17508662/65663473-80e21980-e069-11e9-9d62-2b2343bae794.png)

![image](https://user-images.githubusercontent.com/17508662/65663441-67d96880-e069-11e9-99e7-c61abe51060e.png)

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/api_cn/layers_cn/nn_cn.html#resize-bilinear

**Comment by askhade** [comment]
Resize was updated as part of opset 11 and align corner support has been added.
Resize op uses coordinate_transformation_mode attribute which accepts align_corners as one of the modes.

Please refer to https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-62 for details

**Comment by askhade** [comment]
Closing this as this attribute has already been added to the resize op. @cjt222 if you have anymore questions or suggestions please reopen this issue or open a new issue.
