### ISSUE TITLE
Merged batches and classes in NonMaxSuppression output are awkward

### ISSUE THREAD

**Issue by Timmmm** [onnx/onnx#2361]
I think batches should be independent (except where they explicitly aren't, e.g. BatchNorm). But NonMaxSuppression allows you to submit multiple batches and get the output as a *merged* list of boxes for all batches. This would be fine if the list size for each batch were the statically determined, but it isn't.

It's fine when running on the CPU, but it is really awkward when running on hardware that does things more statically. A better approach for this hardware would be to output the selected indices (and scores) as a tensor that is the same shape as the input. Then also output an additional tensor that indicates the number of selected boxes for each batch and class. Like this:

> **Outputs**
>
> **selected_indices** : tensor(int64)
> &nbsp;&nbsp;&nbsp;&nbsp;selected indices from the boxes tensor. `{num_batches, num_classes, num_boxes}`. Only the first `N` entries for each batch and class have a valid value, where `N` is the corresponding value from `num_selected_boxes`.
>
> **num_selected_boxes**: tensor(int64)
> &nbsp;&nbsp;&nbsp;&nbsp;number of selected boxes for each batch and class. `{num_batches, num_classes}`

The downside of this approach is that it requires more output memory, but since `max_output_boxes_per_class` is a runtime parameter, on hardware that allocates memory statically we have to allocate enough to hold every input box anyway. On CPU it doesn't matter because they have tons of memory.

**Comment by chuanqi305** [comment]
I have the same problem, and I have to use for loop to process the outputs since the boxes are merged together.
