### ISSUE TITLE
pytorch.onnx.export fails on upsampling

### ISSUE THREAD

**Issue by brekkanegg** [onnx/onnx#2363]
I am trying to export pytorch model  which contains 
torch.nn.funtional.upsample(x, scale_factor=2, mode='bilinear', align_corners=False) to .onnx format. 

I received the error message as follows:
> ~/.local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/symbolic.py in 
> upsample_nearest2d(g, input, output_size)
>           857 @parse_args('v', 'is')
>           858 def upsample_nearest2d(g, input, output_size):
>   ---> 859     height_scale = float(output_size[-2]) / input.type().sizes()[-2]
>           860     width_scale = float(output_size[-1]) / input.type().sizes()[-1]
>           861     scales = g.op("Constant", value_t=torch.tensor([1., 1., height_scale,
> 
>IndexError: list index out of range 

I checked the output_size, and it seems output_size is None. 
I am currently using PyTorch==1.1.0, onnx==1.5.0

**Comment by prasanthpul** [comment]
The problem seems specific to PyTorch. Please file an issue with that project
@spandantiwari as fyi
