### ISSUE TITLE
QuantizeLinear test

### ISSUE THREAD

**Issue by kali** [onnx/onnx#2365]
Test for QuantizeLinear has y_scale and y_zero_point inputs encoded as 1D tensors of length 1. 

According to the operator definition, they should be scalars (0D tensors) instead.

**Comment by askhade** [comment]
@kali : The test already uses scalars for y_scale and y_zero_point

y_scale = np.float32(2)
y_zero_point = np.uint8(128)

https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-82

**Comment by askhade** [comment]
@kali please reopen this issue or create a new one if this is still an issue.
