### ISSUE TITLE
RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION 

### ISSUE THREAD

**Issue by Bbean** [onnx/onnx#2370]
I have an onnx model file, which transformed form tensorflow pb model. when I try to run this model, I got this error:

`RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /Users/vsts/agent/2.155.1/work/1/s/onnxruntime/core/providers/cpu/tensor/split.h:22 onnxruntime::SplitBase::SplitBase(const onnxruntime::OpKernelInfo &) std::all_of(split_sizes_.cbegin(), split_sizes_.cend(), [](int64_t value) { return value > 0; }) was false. Invalid value in 'split' attribute. All values must be > 0`

**Comment by prasanthpul** [comment]
This seems specific to ONNX Runtime. Please file an issue with that [project](https://github.com/microsoft/onnxruntime)
