### ISSUE TITLE
when I check, I got ValidationError

### ISSUE THREAD

**Issue by WilliamZhaoz** [onnx/onnx#2371]
I trained my model in pytorch, then converted it to onnx, then I quantized the onnx model using a tool in onnxruntime, then I check it.
but I got a error:

onnx.onnx_cpp2py_export.checker.ValidationError: No opset import for domain ''
==> Context: Bad node spec: input: "0" output: "249" op_type: "Transpose" attribute { name: "
perm" ints: 4 ints: 0 ints: 1 ints: 2 ints: 3 type: INTS }

the onnx model before quantization is ok.
now my onnx version is 1.5, pytorch version is 1.1, onnxruntime version is 0.5

please help me, thanks.

**Comment by wschin** [comment]
@spandantiwari, do you have idea?

**Comment by spandantiwari** [comment]
@WilliamZhaoz @wschin - I am not sure. If your model is running fine before the quantization step, then it maybe an issue with the onnxruntime tool. 

It may be worth trying to export the model with the latest PyTorch (1.2 at least, but if possible use the latest nightly build), and see if the model works after quantization or not. If not, then maybe open an issue with the onnxruntime repo.

**Comment by prasanthpul** [comment]
Since the problem starts after using the quantization tool in ONNX Runtime, suggest filing an issue in that [project](https://github.com/microsoft/onnxruntime)
