### ISSUE TITLE
op_type type as an enum?

### ISSUE THREAD

**Issue by alrevuelta** [onnx/onnx#2373]
Why is `op_type` a `string` that takes values like `MatMul` or `Relu`. Maybe I'm lacking here the big picture but I think it would make more sense to have it as an enum. According to [this](https://github.com/onnx/onnx/blob/master/docs/Operators.md) around more than 150 operations are supported, which might be too much?

**Comment by wschin** [comment]
It is useful for extending operator list. Say, if you have a matrix multiplication accelerator, you might want to define an operator named `SuperFastMatMul`.
