### ISSUE TITLE
onnx Resize doesn't have scales params how to solve?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx#2374]
![image](https://user-images.githubusercontent.com/21303438/65852739-acc30f00-e389-11e9-8730-8e9eff8cbe96.png)

As you may notice, the model does not have a scales params in Resize....

Does anyone knows why it does needs scales but onnx opset 10 said, Resize op consume 2 inputs which is input nodes and scales.

Compares to yolov3.onnx, much more standared:

![image](https://user-images.githubusercontent.com/21303438/65852838-00cdf380-e38a-11e9-8002-1d1bc27c5ed7.png)

It have a scales params.

This would raise an error when using `onnx2trt` convert to trt model.

What should we do when model have Resize op but has no scales params?

**Comment by dashesy** [comment]
It has scales, but scales is input now. If a constant you should be able to use an initializer for it.

**Comment by jinfagang** [comment]
@dashesy  Exactly, dash. My model (actually maskrcnn.onnx) it using scales from a input, but the problem is. `onnx2trt` convert it will have an assertion:

```
scales.is_weights()
```
this will break, since for somewhat reason, the scales does not weights, it can not passed when import this Resize op.

Do u know why and how to solve it in this situation?

**Comment by askhade** [comment]
@jinfagang : This seems like converter issue and not an ONNX issue. Please open this issue in the converter's issues on github.

If you want anything specific from ONNX then please reopen this issue.

**Comment by 1LOVESJohnny** [comment]
Hi guys, I meet the same problem. May I ask if you have solved the problem? If yes, please share the solution. Expect for your reply.

**Comment by YUHAN666** [comment]
I was managed to slove the problem by replace the `tf.keras.layers.Upsample2D()` in my model by `tf.image.resize_image()` and set `method=tf.image.ResizeMethod.NEAREST_NEIGHBOR`.
