### ISSUE TITLE
Clarification of tensor external data usage in the proto file documentation

### ISSUE THREAD

**Issue by edgchen1** [onnx/onnx#2392]
For reference, here's the [current documentation](https://github.com/onnx/onnx/blob/ca1d5b7e0a3290a1419cb2020511df07d11287fe/onnx/onnx.in.proto#L422):
```
  // Data can be stored inside the protobuf file using type-specific fields or raw_data.
  // Alternatively, raw bytes data can be stored in an external file, using the external_data field.
  // external_data stores key-value pairs describing data location. Recognized keys are:
  // - "location" (required) - POSIX filesystem path relative to the directory where the ONNX
  //                           protobuf model was stored
  // - "offset" (optional) - position of byte at which stored data begins. Integer stored as string.
  //                         Offset values SHOULD be multiples 4096 (page size) to enable mmap support.
  // - "length" (optional) - number of bytes containing data. Integer stored as string.
  // - "checksum" (optional) - SHA1 digest of file specified in under 'location' key.
```

A few points I'm unclear about:
- for offset/length/checksum, what is the behavior if those fields are not provided?
- for location, what character encoding is used for the path?
- for offset, from looking at an implementation in ONNX Runtime ([here](https://github.com/microsoft/onnxruntime/blob/57e00994256ec6394e635f30b085e17bae8d0594/onnxruntime/core/framework/tensorprotoutils.cc#L394) and [here](https://github.com/microsoft/onnxruntime/blob/57e00994256ec6394e635f30b085e17bae8d0594/onnxruntime/core/platform/posix/env.cc#L160)), a multiple of 4096 is not required because it is possible to adjust the parameters to mmap to be page aligned. If this constraint is in fact desired, is page size always 4096?

**Comment by snnn** [comment]
If offset is not provided, it is default to zero.
If length is not provided, it means we will use the whole file.
if checksum is not provided(usually it doesn't),  we don't check checksum.
For location, the encoding should be UTF-8. As in onnx most strings are UTF-8. Conversion from UTF-8 to Windows Unicode(UTF-16) is lossless and easy. And most Linux users use UTF-8 locales nowadays. 

For your last question, page size could be as large as 2MB. But I think it doesn't impact the use of memory mapping.
