### ISSUE TITLE
Got segmentation fault when onnx.checker.check_model(model). (Pytorch->onnx->caffe2)

### ISSUE THREAD

**Issue by WeiyiLi** [onnx/onnx#2394]
Hi,

I am trying to use caffe2 backend but got segmentation fault when run the checker. 
My code: 
```
import onnx
import caffe2.python.onnx.backend as onnx_caffe2_backend

model = onnx.load("large_onnx_model_name.onnx")
onnx.checker.check_model(model)
```

The model is originally pytorch model. And then I converted it to onnx and then caffe2. 

Versions:
Pytorch 1.0.0
onnx 1.6.0
protobuf 3.7.0
ubuntu 18.04

If these versions are not compatible to each other? Can anyone provide a correct version "combination" so that I can convert my pytorch model to onnx and then to caffe2. 

Thank you.

**Comment by reveriel** [comment]
I've got a similar problem. 

Code: save the resnet50 model to onnx, and then load and check it.

``` python
dummpy_input = torch.randn(1, 3, image_size, image_size, device='cuda')
resnet50 = models.resnet50(pretrained=True).cuda()
torch.onnx.export(resnet50, dummpy_input, "resnet50.onnx", verbose=True)
onnx_model = onnx.load("resnet50.onnx")
onnx.checker.check_model(onnx_model)    # segfault, pytorch1.2 pytorch1.3
```

environment:

-  torch 1.2.0/1.3.0
- onnx 1.6.0
-  ubuntu 18.04

**Comment by WeiyiLi** [comment]
@reveriel I have a bypass here...I use pytorch 1.0.0 to export onnx model. And then build from source to compile the latest pytorch code from its github. When I check the version of pytorch, it becomes 1.4.0. Then I load the onnx model (the one from 1.0.0) and check. No error this time...
It can temporally solve my problem but it's definitely not a ideal solution. 

Still need to wait for a better answer or if you have any other solution, please keep updates! Thank you! :)

**Comment by Maximilianxu** [comment]
@reveriel For me, I reinstalled onnx 1.5 and solved this problem. (torch==1.3)

**Comment by skottmckay** [comment]
@reveriel can you share the model you get the checker segfault on? Running the python you have worked for me on Windows (torch 1.3.0, torchvision 0.4., cuda 10.1, onnx 1.6.0) so I'd like to see if the model generated for me was any different.

**Comment by reveriel** [comment]
@skottmckay  
It's the [`torchvision.models.resnet50`](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py)

**Comment by royinx** [comment]
Same here , fine after downgrade to 1.5.0

torch - 1.3.0.dev20190910
torchvision - 0.5.0a0+6ddda3a
efficientnet_pytorch - 0.5.1
onnx - 1.6.0
ubuntu - 1804

**Comment by masahi** [comment]
Try import onnx first before torch. The following works for me, but if swap the order of torch and onnx I get segfault as well even with pytorch 1.4.

```
import onnx
import torch
from torchvision import models


image_size = 224
dummpy_input = torch.randn(1, 3, image_size, image_size)
resnet50 = models.resnet50(pretrained=True)
torch.onnx.export(resnet50, dummpy_input, "resnet50.onnx", verbose=True)
onnx_model = onnx.load("resnet50.onnx")
onnx.checker.check_model(onnx_model)    # segfault, pytorch1.2 pytorch1.3
print("ok")
```

I believe this is a dynamic loader issue. libtorch.so also link against the onnx lib, whose version is not compatible with the one pulled by `import onnx`.

**Comment by xjiao004** [comment]
pytorch and onnx can not load model at the same time? After I torch.onnx.export model to onnx, loading onnx model by onnx got segmentation fault.

**Comment by codeislife99** [comment]
The solution by masahi works, thanks so much

**Comment by Jaftem** [comment]
This is appearing for me with Onnx 1.7 and changing the import order did not fix the issue. Anyone experiencing the same?

**Comment by jcwchen** [comment]
It should be fixed with the latest pytorch and onnx. Please reopen this issue if you still encounter this problem. Thanks!
