### ISSUE TITLE
Read ".pb" files for testing

### ISSUE THREAD

**Issue by alrevuelta** [onnx/onnx#2399]
I have seen that ONNX Backend Test allows to test a new backend, and since I'm implementing a pure C ONNX backend, I would like to use it. Lets say for example that I want to test my `sigmoid` function. There is a [test_sigmoid](https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node/test_sigmoid) folder where I can see the model with the operator under test, and a folder `test_data_set_0` with the `input_0.pb` and expected `output_0.pb`.

My question is, how can I parse that `.pb` files? Which structure are they following? If its a `protocol-buffer` file, I was expecting a `.proto` file describing its structure, but can't find it.

**Comment by snnn** [comment]
Hi,

It's in https://github.com/onnx/onnx/blob/master/onnx/onnx.proto3, TensorProto.

**Comment by skottmckay** [comment]
This PR has some python helpers related to those files so will provide example code at the very least.

https://github.com/microsoft/onnxruntime/pull/2294

**Comment by alrevuelta** [comment]
@skottmckay thats a very useful tool thanks! However I would like to read that directly from C and still haven't figured that out. I'm able to open normal ".onnx" files using "onnx.proto" schema, but can't open that ".pb" files. Tried also "onnx.proto3" as suggested by @snnn but still nothing.

**Comment by skottmckay** [comment]
Some example C++ code that reads the TensorProto:

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/onnx/TestCase.cc#L525-L528
   google::protobuf::io::FileInputStream f(tensor_fd);
    f.SetCloseOnDelete(true);
    ONNX_NAMESPACE::TensorProto tensor;
    if (!tensor.ParseFromZeroCopyStream(&f)) {

**Comment by wangxudong-cq** [comment]
@skottmckay, read ".pb"files and convert to std::vector, have some examples?
