### ISSUE TITLE
Duplicate definition of name after using fuse_bn_into_conv optimization

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2401]
With opset10 model after

```python
optimized_model = optimizer.optimize(onnx_model, ['fuse_bn_into_conv'])
```

I cannot load the model in ORT and get 

> Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /mnt/output/gr/optimized_v.onnx failed:This is an invalid model. Error: Duplicate definition of name (2570).

With

```python
onnx.checker.check_model(onnx_model)
```

I get

> ValidationError: Graph must be in single static assignment (SSA) form, however '2568' has been used as graph input names multiple times.

When I look with `netron` the graph is definitely incorrect! I have 5 output tensors, and some now are disjoint (no correct path from input to output).

Similar to [this issue](https://github.com/onnx/onnx/issues/2024)

**Comment by LaCandela** [comment]
I am having the same issue after using 'fuse_bn_into_conv' optimization.

onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however '508' has been used as output names multiple times.

onnx.__version__ = 1.6.0
onnxruntime.__version__ = 1.1.1

**Comment by tangyanf** [comment]
Is anyone watching this question right now？

**Comment by robinvanemden** [comment]
I hope so, since this issue still seems to persist.

> Is anyone watching this question right now？

**Comment by daquexian** [comment]
It has been fixed in https://github.com/onnx/optimizer :D
