### ISSUE TITLE
Add Support for Additional Input Types for BitShift 

### ISSUE THREAD

**Issue by lara-hdr** [onnx/onnx#2406]
BitShift only supports unsigned types in opset 11.
PyTorch supports BitShift operations on even other types (int8, int64, int32, float32, float64), and the only unsigned type in PyTorch is uint8; so the use of the Bitshift operator in PyTorch is currently restricted to this type.
We would like to add support to additional input types for BitShift to support more cases in the PyTorch exporter, without the use of a subgraph.

**Comment by ebarsoum** [comment]
@lara-hdr can you submit a PR?

**Comment by skottmckay** [comment]
Could the exporter insert a Cast before/after the BitShift instead?

**Comment by hez2010** [comment]
> Could the exporter insert a Cast before/after the BitShift instead?

Nope. PyTorch doesn't support uint32/uint16 so a cast would be invalid. 
BitShift in onnx needs the operand to be unsigned while PyTorch doesn't support unsigned integer, which is unfortunate.
