### ISSUE TITLE
C# inference of Pix2pixHD

### ISSUE THREAD

**Issue by aviel08** [onnx/onnx#2413]
Hi, I trained a model using [Pix2PixHD](https://github.com/NVIDIA/pix2pixHD) then I exported it to onnx and I would like to do inference in C# using UWP.

The input of required by Pix2PixHD is:
- 1 image of semantic labels (512x1024 Grayscale)
- 1 image instances (512x1024 Grayscale)
- Amount of labels used as hot vertors during training ("--label_nc 16" for instance)

I can test my model in python but I have no idea how to bind it in C# so I really appreciate any assistance. 

[This is how my model looks](https://imgur.com/aBI6cE5)

And this is the generated code from Visual Studio:

`
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace Onnx_test_02
{
    
    public sealed class Input
    {
        public TensorFloat label; // shape(1,1,512,1024)
        public TensorInt8Bit inst; // shape(1,1,512,1024)
    }
    
    public sealed class Output
    {
        public TensorFloat synthesized_image; // shape(1,3,512,1024)
    }
    
    public sealed class Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            Model learningModel = new Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<Output> EvaluateAsync(Input input)
        {
            binding.Bind("label", input.label);
            binding.Bind("inst", input.inst);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new Output();
            output.synthesized_image = result.Outputs["synthesized_image"] as TensorFloat;
            return output;
        }
    }
}

`

**Comment by prasanthpul** [comment]
Since this is specific to WinML, please raise your question at https://github.com/Microsoft/Windows-Machine-Learning. The right experts will be able to help you there
