### ISSUE TITLE
Does the NonZero operator really output 2D only?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2415]
In the NonZero operator documentation it says the output is always 2D, but it also says that it implements python nonzero, which has one output dimension for each input dimension. Which is it?

Y : tensor(int64)
output (always 2D tensor)

**Comment by askhade** [comment]
NonZero behaves similar to numpy.nonzero is correct.
output (always 2D) should be removed.

**Comment by ebarsoum** [comment]
Thank you for reporting the issue.
