### ISSUE TITLE
The installed file include/onnx/onnx_pb.h references onnx/onnx.pb.h that isn't installed

### ISSUE THREAD

**Issue by yurivict** [onnx/onnx#2419]
https://github.com/onnx/onnx/blob/master/onnx/onnx_pb.h#L52

Version 1.6.0
FreeBSD 12

**Comment by FrancisMurtagh-arm** [comment]
This seems to effect the debian package of onnx:
https://packages.debian.org/bullseye/amd64/libonnx-dev/filelist

/usr/include/onnx/onnx_pb.h

This file is installed but not onnx/onnx.pb.h

ArmNN depends on  onnx.pb.h

src/armnnOnnxParser/OnnxParser.hpp
#include <onnx/onnx.pb.h>

But there is no onnx.proto included in libonnx-dev either sadly to generate it.
