### ISSUE TITLE
[FeatureRequest] Better error messages

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2421]
I am debugging a converted model from CNTK , that has invalid shapes and am trying to fix it. Now I get 

> Can't merge shape info. Both source and target dimension have values but they differ. Source=96 Target=64 Dimension=1

But there is no information which node has this issue! The error message should include some hints to help in debugging.

**Comment by askhade** [comment]
@dashey : Please reopen this issue if the above PR is not enough to fix this issue.
