### ISSUE TITLE
Slice with step=0 not specified

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#2427]
The specification https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice does not address the case that step=0.  I'm guessing it's not allowed.

Small grammar issue in phrase "it represent number of elements" - should be "represents".

**Comment by askhade** [comment]
Right step == 0 is not allowed. The spec does say that it follows numpy's implementation : https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html 
 
However it's more clear to specify step == 0 not allowed explicitly in the spec
