### ISSUE TITLE
Yolov3 model call shape_inference.infer_shapes can't get shape.

### ISSUE THREAD

**Issue by emelife** [onnx/onnx#2432]
I want to get Network middle layer op input or output tensor shape by shape_inference.infer_shapes,but It doesn't work.
the step following:
g = onnx.load(model_path)
inferred_model = shape_inference.infer_shapes(g)
info = inferred_model.graph.value_info
print(info)
part of  info:
........
, name: "TFNodes/yolo_evaluation_layer_1/strided_slice_55:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/strided_slice_54:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/add_5:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/strided_slice_57:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/strided_slice_56:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/concat_7:0"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "TFNodes/yolo_evaluation_layer_1/mul_17:0"
type {
  tensor_type {
    elem_type: 1
  }
}
''''''''
It just has type inference no dim_value,does onnx support yolov3 shape inference? I try mobilenet network success.
Is there any body know about it ? and is it a bug ?

**Comment by szupzp** [comment]
I also have this problem. Have you resolve it？
