### ISSUE TITLE
Slice spec clarification

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#2433]
The current spec for Slice says - 
```
For slicing to the end of a dimension with unknown size, it is recommended to pass in INT_MAX.
```

This seems logical only for forward stepping. The logical extension for negative stepping is to use INT_MIN or -INT_MAX or some other value less than the negative of the dim value along that dimension. This clarification is probably required...

**Comment by askhade** [comment]
#2429 fixes this
