### ISSUE TITLE
binary build of onnx is failing to load libprotobuf.so.20

### ISSUE THREAD

**Issue by rajarsheem** [onnx/onnx#2434]
Hi, I installed onnx into my conda environment using:

```conda install -c conda-forge onnx``` 

This installs the following packages: 

```
  libprotobuf        conda-forge/linux-64::libprotobuf-3.10.1-h8b12597_0
  onnx               conda-forge/linux-64::onnx-1.6.0-py36he1b5a44_0
  protobuf           conda-forge/linux-64::protobuf-3.10.1-py36he1b5a44_0
```

However, following the installation, when I try to ```import onnx``` I get the following error:

```
In [1]: import onnx
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6f9566fa2ea7> in <module>
----> 1 import onnx

~/.conda/envs/ramitra/lib/python3.6/site-packages/onnx/__init__.py in <module>
      6 import os
      7
----> 8 from .onnx_cpp2py_export import ONNX_ML
      9 from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors
     10 from .onnx_pb import *  # noqa

ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory
```

I am using python 3.6.9 on my machine. 

Can you please help?

**Comment by yyfhaku** [comment]
i also have this program。

**Comment by askhade** [comment]
@rajarsheem : Can you add your machine info - Windows\Linux (distribution of linux)

**Comment by rajarsheem** [comment]
Building from source was a workaround for me.

**Comment by darolt** [comment]
Same issue here after installing from:
conda install -c conda-forge onnx
it comes with protobuf 3.10
solving by downgrading protobuf to 3.9 via:
conda install -c anaconda protobuf

**Comment by tim20120526** [comment]
> Same issue here after installing from:
> conda install -c conda-forge onnx
> it comes with protobuf 3.10
> solving by downgrading protobuf to 3.9 via:
> conda install -c anaconda protobuf

conda install protobuf=3.9 work for me.

**Comment by wangkenpu** [comment]
> Same issue here after installing from:
> conda install -c conda-forge onnx
> it comes with protobuf 3.10
> solving by downgrading protobuf to 3.9 via:
> conda install -c anaconda protobuf

It works for me. Hope ONNX team will fix the bug soon.

**Comment by abramov-oleg** [comment]
Had similar problem, except `conda create -n onnx onnx -c conda-forge` installs

```
libprotobuf        conda-forge/linux-64::libprotobuf-3.11.0-h8b12597_0
onnx               conda-forge/linux-64::onnx-1.6.0-py38he1b5a44_0
protobuf           conda-forge/linux-64::protbuf-3.11.0-py38he1b5a44_0
```

And import fails with following error

```
~$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oleg/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory

```

Fixed with `conda install protobuf=3.10 -c conda-forge`

**Comment by LLNLanLeN** [comment]
I'm also experience this issue and seem like downgrading to protobuf 3.9 works for me as well

**Comment by yaochx** [comment]
Fixed with conda install protobuf=3.9 -c conda-forge

**Comment by vv111y** [comment]
same here. But I can't install protobuf v3.9 or v3.10. Solving the environment errors out. I uninstalled onnx and trying again.

**Comment by LLNLanLeN** [comment]
@vv111y I'm not sure if it might help, when I downgrade it to 3.9, it also having the errors, but it resolve itself and actually downgrade the protobuf version. I'm wondering have you tried to wait it out for a bit longer

**Comment by vv111y** [comment]
@LLNLanLeN thanks, just missed your comment by a second. It works now with a fresh environment

**Comment by LLNLanLeN** [comment]
awesome. Another possible solution I think is to actually install onnx from source as well, I think that might help.

**Comment by jjkislele** [comment]
There might be inconsistent with `conda install` and `pip install`. When you want to uninstall some package, try both `conda uninstall` and `pip uninstall`, like `conda uninstall protobuf`, `conda uninstall libprotobuf` and `pip uninstall protobuf`, to make sure no PROTOBUF-LIKE package exists.
Then, type `conda install protobuf=3.9` and `conda install -c conda-forge onnx`. It works for me.

**Comment by michaelklachko** [comment]
Still the problem 5 months later, why is this not fixed yet?

**Comment by prasanthpul** [comment]
ONNX 1.7 coming this week. @chinhuang007 to comment whether this is addressed

**Comment by chinhuang007** [comment]
Unfortunately the conda builder has not been worked on or updated in recent months. This was identified as a post-1.7 work item owned by the ArchInfra SIG during a discussion in a TSC meeting and shared with the ArchInfra SIG lead. @linkerzhang feel free to comment.

**Comment by michaelklachko** [comment]
I don't understand - `conda install` is the first installation option on the project page. Should we not use conda to install onnx? This method is currently broken, with an obscure error, and the workaround (protobuf downgrade) is only mentioned in this thread. If you don't intend to fix it any time soon, please mention the workaround next to the conda installation command, so people don't waste time googling this error. 

Also keep in mind that conda is the default installation option for Pytorch, so quite a few Pytorch users will probably prefer conda if they want to install onnx.

**Comment by Cloudmersive** [comment]
Guys can we please fix this?

**Comment by SpontaneousDuck** [comment]
Update: the current onnx version available on conda-forge (v1.6) only works with protobuf=3.10 (v3.10.1) right now. That is the only configuration that did not give me the mentioned error.

**Comment by Gloria-LIU** [comment]
I have same problem but cannot solve by install protobuf

**Comment by Gloria-LIU** [comment]
problem solved by degrading protobuf=3.9

**Comment by hwangdeyu** [comment]
This issue is encontered when libprotobuf.so.(verison)20 is incompatoable with protobuf version.

I also meet this error:
>ImportError: libprotobuf.so.25: cannot open shared object file: No such file or directory.

But what I solve this problem by `conda install protobuf=3.14.0`.

Wish this answer can help who clicks on this link.

**Comment by armando-fandango** [comment]
this issue resurfaces with the following:
`libprotobuf               3.21.12              h3eb15da_0    conda-forge
protobuf                  4.21.12          py38h8dc9893_0    conda-forge
onnx                      1.6.0            py38he1b5a44_0    conda-forge`

The error:

python
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/py/lib/python3.8/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libprotobuf.so.21: cannot open shared object file: No such file or directory
