### ISSUE TITLE
Does a shape of "2" denote a column vector or a row vector?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2435]
When you have a Tensor whose shape is [2], is that a row vector or column vector?

It matters, because I encountered an ONNX network that tries to concatenate a Constant Tensor of shape [2] with a Tensor of shape [2 2], along axis 0.  For this to work, the [2] would have to mean [1 2], that is, [2] is a row vector. However, elsewhere I believe I saw an example where [2] would need to denote a column vector.

Which is it?  Or is there some other way I should think about it?

**Comment by dashesy** [comment]
It must be row vector if numpy is the reference:

```python
In [75]: np.arange(4).reshape(2,2) + np.arange(2)
Out[75]:
array([[0, 2],
       [2, 4]])

In [76]: np.arange(4).reshape(2,2) + np.arange(2).reshape(1,2)
Out[76]:
array([[0, 2],
       [2, 4]])

In [77]: np.arange(4).reshape(2,2) + np.arange(2).reshape(2,1)
Out[77]:
array([[0, 1],
       [3, 4]])
```
