### ISSUE TITLE
What is the plan for offline ONNX optimizations

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2440]
It seems [ONNXRuntime now has support for some offline optimizations](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md#python-api-usage) using `optimized_model_filepath`. On the other hand [optimizer is broken now for a while](https://github.com/onnx/onnx/issues/2417) with no sign of any progress.

Is there plan to move more offline optimization passes to ONNXRuntime, or are ONNXRuntime and ONNX going to use a shared code-base for optimizations?

**Comment by prasanthpul** [comment]
great question, i'd like to see the arch/infra sig discuss this and come back with a proposal. @linkerzhang and @houseroad are co-leads for that SIG. Discussions are at https://gitter.im/onnx/Infra as are announcements for the calls.
