### ISSUE TITLE
Operator or function CDist

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#2442]
I'd like to add cdist function. We made some experiments and having a dedicated operator is ten times faster than its onnx implementation with Scan operator (see graph below). What is the best way to add it? As a function or as an operator? In case of a function, should I wait for #1939 to be merged?

![image](https://user-images.githubusercontent.com/22452781/68491559-5d56e500-024b-11ea-9051-36349818039a.png)

**Comment by xadupre** [comment]
More figures about this. I trained a KNearestClassifier on the digits datasets. First graph is without cdist operator, second graph is with the cdist oprator:

* black: scikit-learn (same for both graph)
* blue: onnxruntime
* yellow: onnx runtime implemented with numpy + cdist function from scipy in the second graph

It shows the runtime is 10 times faster with the use of cdist operator.

![image](https://user-images.githubusercontent.com/22452781/69899152-9a9e2680-1362-11ea-9dd6-dfc6df7a532c.png)

**Comment by xadupre** [comment]
It is still relevant. However the list of distances to support can be huge.

**Comment by justinchuby** [comment]
Marked for discussion for 1.16

**Comment by justinchuby** [comment]
From discussion this operator is marked low priority. Please comment or reopen if there is further support to include it in the spec.
