### ISSUE TITLE
Does ONNX support namespace or namescope?

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx#2444]
Hi,
  There are too many nodes in my model to visualize it and they belong to different layers (or different sub-model). I want to use something like namespace or namescope to split them into sub-space. Does ONNX support anything to do this?
  Thanks!

**Comment by wschin** [comment]
No. The closest thing in my mind is to use better names for those nodes. For example, for an attention module in a language model, you can have something like
```
Node(type=MatMul, name=attention1.MatMul)
Node(type=Relu, name=attention1.Activation)
...
in your graph.

**Comment by dashesy** [comment]
Yes this is a good feature to add, when visualizing it will be very helpful to box different nodes in a box to look at the network. Using name could help somewhat but there is no standard way, so name can be anything.

**Comment by JiayiFu** [comment]
> No. The closest thing in my mind is to use better names for those nodes. For example, for an attention module in a language model, you can have something like
> 
> ```
> Node(type=MatMul, name=attention1.MatMul)
> Node(type=Relu, name=attention1.Activation)
> ...
> ```
> 
> in your graph.

Thanks for your reply. I have already used the names like "layer.operations" for more intuitive representation. But when the number of nodes is large, there is still a little complex for the visualization.

**Comment by dashesy** [comment]
I have many `nn.Module` that internally operate on tensors, so the name of the module is lost when converting to ONNX. A namespace/namescope would help a lot with some visualization in netron, or to do a surgery on an already exported model and extract part of the ONNX model for different reasons.
