### ISSUE TITLE
Spec unclear: Gather makes 0 rank tensors. Does Split?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2448]
I noticed in ONNX Runtime, that if you call Gather(indices=2) on a 1D tensor, you get a 0 rank scalar out (not a rank-1 tensor of size [ 1 ]). 

Is the same true of Split? For example, if you Split a 1D tensor of size [ 2 ] into 2 parts, do you get two rank-1 tensors or size [ 1 ], or do you get two scalars of size [ ]?

More generally, are all the outputs of Split the same rank as the input of Split? Or, do all the splits of size 1 have rank one less than the rank of the input?

**Comment by Adeykin** [comment]
Have the same problem
