### ISSUE TITLE
Spec unclear: Can a scalar be Reshaped to a 1D tensor and vice versa?

### ISSUE THREAD

**Issue by mathisdon** [onnx/onnx#2449]
A scalar has shape [ ] and rank 0. Can the Reshape operator be applied to it with a shape of [ 1 ]? And Can a 1D tensor of shape [ 1 ] have Reshape applied with a shape of [ ]?

**Comment by linkerzhang** [comment]
Thanks a lot for bringing this up! I think both should be supported. @ebarsoum  @postrational
