### ISSUE TITLE
Clip support for integer tensors

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2450]
[Clip](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip) inputs in constrained to floating points. I have tensors that are indices, and thus `int64` and would like to `Clip` them to valid ranges.
In general, what is the rationale for limiting operators input types? does it really affect binary sizes?

**Comment by askhade** [comment]
@dashesy : Adding int64_t type for Clip makes sense... Would you mind submitting the PR for this?
