### ISSUE TITLE
Resize use Sizes but Scales is single

### ISSUE THREAD

**Issue by leroyzhao** [onnx/onnx#2451]
In the documentation, it is stated that sizes can be used as long as the name of scales is set to empty string.
![image](https://user-images.githubusercontent.com/36605269/68706466-e75dc100-055d-11ea-9ec2-dddb997247d5.png)
However, after setting the name of scales to an empty string, the graph fails to load.
The error states that `input 2 is marked single but has an empty string in the graph`.

**Comment by erickque** [comment]
`scales` should probably be set as an optional input. In the schema definition, scales is defined as a `Single` input (default FormalParameterOption): https://github.com/onnx/onnx/blob/master/onnx/defs/tensor/defs.cc#L1741.

This contradicts the statement OP highlighted in Operators.md, as the following section of code in the schema verification requires the input to be not `Single` if the name is empty: https://github.com/onnx/onnx/blob/master/onnx/defs/schema.cc#L226

**Comment by askhade** [comment]
That's right... Scales description describes it as optional input BUT it is not defined as one... Therefore right now the only way is to pass an empty tensor. Same goes with roi. Please check the tests for examples

This op needs to be updated to make scales and roi as optional inputs.

**Comment by jinfagang** [comment]
@askhade  scales input if it's initializer type, it will not be able convert to tensorrt.

```
[8] Assertion failed: convert_onnx_weights(initializer, &weights)
```

**Comment by daquexian** [comment]
> That's right... Scales description describes it as optional input BUT it is not defined as one... Therefore right now the only way is to pass an empty tensor. Same goes with roi. Please check the tests for examples
> 
> This op needs to be updated to make scales and roi as optional inputs.

If I remember correctly, I made it non-optional intentionally because I didn't find a way to get whether an optional input is specified, instead, I could only check the input_size, so the "scales" must be specified even if it is not used.

**Comment by HarryVancao** [comment]
Can we revisit updating this operator? Could we merge the sizes and scale inputs into one input and have an attribute tell the operator how to interpret the input? Then, the ROI input could be made optional. 

I feel that just by passing empty to these inputs is wasteful and makes the implementation for other backends of ONNX much harder.  As a side note, the spec should not tell the user to pass an empty string when the inputs is required to be float type as @leroyzhao pointed out.

**Comment by shi-yan** [comment]
is there a solution for this, I must set ROI it seems.

**Comment by askhade** [comment]
Closing this in favor of #3500
