### ISSUE TITLE
ONNX export failed: Couldn't export operator aten::upsample_bilinear2d

### ISSUE THREAD

**Issue by aviaisr** [onnx/onnx#2454]
Hello,
I'm trying to export my model to onnx but I get the following error:

RuntimeError: ONNX export failed: Couldn't export operator **aten::upsample_bilinear2d**

Defined at:
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py(2518): **interpolate**
C:\CP\DL_REPOSITORIES\PoolNet\networks\deeplab_resnet.py(192): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(525): _slow_forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(539): __call__
C:\CP\DL_REPOSITORIES\PoolNet\networks\joint_poolnet.py(174): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(525): _slow_forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(539): __call__
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\__init__.py(352): forward
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py(541): __call__
C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\__init__.py(275): get_trace_graph
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(206): _trace_and_get_graph_from_model
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(249): _model_to_graph
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(382): _export
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py(66): export
C:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\__init__.py(143): export

My onnx version: 1.6.0

**Comment by prasanthpul** [comment]
Please make sure you are using the latest PyTorch.

For further issues, please file in the PyTorch github.
