### ISSUE TITLE
Travis CI does not cancel the old build when PR is updated

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#2457]
If there are intermittent random build failures then the only way to restart the PRs is to Close and Open the PR. This triggers all the CIs to run again. When this is done all CIs should cancel the running jobs for this PR before scheduling a new one. Appveyor does that but not Travis CI. 
This is
1. An inconvenience because most of the time this new run is blocked by the old run
2. Waste of compute as this run will be discarded anyways

**Comment by jcwchen** [comment]
It is doable:
https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by askhade** [comment]
Closing this since we have moved away from Travis CI
