### ISSUE TITLE
Not good behavior -- squeeze raises error if no axis is 1

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#2466]
Related issue: https://github.com/daquexian/onnx-simplifier/issues/33

ONNX Squeeze op spec:

> If an axis is selected with shape entry not equal to one, an error is raised.

I think it is not good behavior. Other frameworks like PyTorch, just remain the shape if no axis equals 1. What's more, this behavior is not fit into ONNX dynamic shape in the future, as it will be uncertain whether a shape contains 1

**Comment by linkerzhang** [comment]
It sounds OK to update the spec to swallow this kind of "error" and let the input data unchanged. @ebarsoum @postrational  thoughts?

**Comment by linkerzhang** [comment]
@daquexian do you want to create a PR for it? and yes, this will ask for operator version bump.
