### ISSUE TITLE
How to judge if the model supports batch processing?

### ISSUE THREAD

**Issue by zxgm** [onnx/onnx#2467]
How to judge if the model supports batch processing?

**Comment by skottmckay** [comment]
Easiest way is to open the onnx file in Netron and look at the graph inputs by clicking the hamburger icon on the top left. If a dimension in an input has an integer value it is fixed to that value. If it has no value or a symbolic name, it is based on the input provided at runtime.

![image](https://user-images.githubusercontent.com/979079/69409606-ffe78b80-0d54-11ea-8e44-ce64c6c96f52.png)

**Comment by zxgm** [comment]
Thanks a lot! The answer is useful to me.

**Comment by zxgm** [comment]
if i want to provide any batch size  at runtime,

**Comment by skottmckay** [comment]
Here's an example of creating a model where the first dimension is the batch size. It uses a string for the symbolic dimension value instead of an integer.

```
nhwc = onnx.helper.make_tensor_value_info(name='nhwc', elem_type=elem_type, shape=['N', 100, 100, 3])
nchw = onnx.helper.make_tensor_value_info(name='nchw', elem_type=elem_type, shape=['N', 3, 100, 100])
node  = onnx.helper.make_node(op_type='Transpose', inputs=['nhwc'], outputs=['nchw'], perm=[0, 3, 1, 2])
graph = onnx.helper.make_graph(nodes=[node], name='nhwc_to_nchw', inputs=[nhwc], outputs=[nchw])
model = onnx.helper.make_model(graph=graph)
```

**Comment by zxgm** [comment]
Thanks a lot!

**Comment by zxgm** [comment]
There have a batch application that used batch process, but the batch size is smaller than the fixed batch_size in the model, can it be support? Must be equal to a fixed batch_size?

**Comment by skottmckay** [comment]
If the model says the input size is fixed I wouldn't expect a runtime to work with sizes that don't match. Implementation dependent though. ONNX Runtime checks that the inputs match their defined sizes and returns an error if they don't. Different implementations may be more generous but there's no guarantee that they would be.

It would be much better to fix the model.

**Comment by linkerzhang** [comment]
or in this case (data batch size is smaller than the fixed one in the model), symbolic shape should be used in the model definition instead of fixed size.
