### ISSUE TITLE
Develop/publish an official set of conformance tests for ONNX interoperability.

### ISSUE THREAD

**Issue by mciprian13** [onnx/onnx#2472]
This is not an issue is just a proposal:
- it would be great if this project would provide/publish an official set of tests for ONNX conformance testing to be used by ML frameworks which provide ONNX support
- what I mean by that is a set of ONNX models which would test the capability of ML frameworks:
  - to parse/interpret ONNX models (different opsets, versions, operators, rules, etc)
  - to run the models with the expect numerical behaviour
- I am currently involved in the Glow project which is a Neural Network compiler which has ONNX support and I know that not only it is hard to develop all the ops/features prescribed by ONNX but it is also hard to test (lots of cases) ... I think this effort is mostly replicated in all the projects involving the ONNX format
- For such frameworks this would provide a clearer view upon:
  - Whether operators were implemented/interpreted correctly
  - What needs to be done for 100% compliance
- Also bringing together the ML framework developers to publish their percentage of ONNX compliance on this projects main page would create some competition. Based on this you could provide some symbolic prizes (e.g. Silver Badge for Basic ONNX support, Gold Badge for Advanced ONNX support and Platinum badge for full ONNX support) ... just saying it would be fun ... more toward popularizing the ONNX standard :)

**Comment by prasanthpul** [comment]
have you seen http://onnx.ai/backend-scoreboard/?

**Comment by mciprian13** [comment]
Wow that is great!
You should put a link in the front page to be more visible.
Thumbs up!

**Comment by mciprian13** [comment]
But I have a question. How can a new framework plug-in into this testing board?
Is there an open interface?

**Comment by prasanthpul** [comment]
Take a look at https://github.com/onnx/backend-scoreboard for instructions on how to add your own.
@postrational can you add a link to the scoreboard front page to instructions on how to submit a new backend?

@mciprian13 this just launched recently - we will look at linking it from onnx.ai main pages soon
