### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by zhaojw219** [onnx/onnx#2480]
When I convert .onnx to caffe2 in docker,I met the problem like this:'onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.'
How can I downgrade?Thanks so much!

**Comment by pyy1128** [comment]
have u solved this problem?

**Comment by pyy1128** [comment]
> When I convert .onnx to caffe2 in docker,I met the problem like this:'onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.'
> How can I downgrade?Thanks so much!

have u solved this problem?

**Comment by TMVector** [comment]
You could try upgrading your ONNX install instead :)
