### ISSUE TITLE
How to save the operator for the ONNX format

### ISSUE THREAD

**Issue by ccu1tn** [onnx/onnx#2484]
Dear everyone
I am looking for a way to save this operator for ONNX format 
This operator (https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/gemm.py)
Please, Could you share for me any way to do it?
Many thank everyone!

**Comment by linkerzhang** [comment]
https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node/ contains all the test models auto-generated based on these test cases. For your case, https://github.com/onnx/onnx/blob/master/onnx/backend/test/data/node/test_gemm_transposeA/model.onnx is one of them.

**Comment by ccu1tn** [comment]
Dear @linkerzhang ;
 I used the command line to run the gemm.py test like this python gemm.py and python cmd_tools.py but it does not generate models/
Please give me tutorial me how to run this test to generate that model.
ok?

**Comment by askhade** [comment]
@ccu1tn : you need to give generate-data argument to the cmd_tools.py script. Try something like this

python onnx\backend\test\cmd_tools.py generate-data --output <some dir where the data can be generated>

--output is optional... If you do not specify this then the data will be generated in onnx/backend/test/data dir

**Comment by ccu1tn** [comment]
Dear @askhade;

I want to generate the GEMM model ONNX format in the test_gemm_all_attributes directory then what the script I will write?  
I tried  python cmd_tools.py generate-data /data/node/test_gemm_all_attributes/ 
But it is not run.

**Comment by askhade** [comment]
What do you mean by it is not run? Do you see any error message? Can you print the error message?
Your output directory is not correct... you cannot specify a particular test ... your command will generate data for all test in this folder "/data/node/test_gemm_all_attributes/"

I would suggest you to run this command :
python cmd_tools.py generate-data 

and then look for the generate model and test data in "/data/node/test_gemm_all_attributes/" directory.

If you see any errors or not expected result please specify the error and or the unexpected behavior.
