### ISSUE TITLE
Really need onnx to support DCN (deformal conv) operator....

### ISSUE THREAD

**Issue by lancasterJie** [onnx/onnx#2485]
Really need onnx to support DCN deformable conv operator

**Comment by linkerzhang** [comment]
Do you mind to come out of the op design (spec) and a sample model using the op please?

**Comment by ebarsoum** [comment]
@lancasterJie can you describe for which model and which framework are you using? 

DCN was added recently to TorchVision (https://github.com/pytorch/vision/pull/1586): https://github.com/pytorch/vision/blob/master/torchvision/ops/deform_conv.py. It is still in PR for TensorFlow (https://github.com/tensorflow/addons/pull/1129). Its original implementation was in mxnet as addon by MSRA researchers and now it is in contrib (https://beta.mxnet.io/api/ndarray/_autogen/mxnet.ndarray.contrib.DeformableConvolution.html). Which mean none of the above implementation, except for PyTorch, are part of the framework release.

As @linkerzhang said, feel free to submit a PR, following the AddNewOP.md.

**Comment by austinmw** [comment]
I think it would be preferable to add DCNv2 instead of original DCN at this point. https://github.com/CharlesShang/DCNv2

**Comment by biyuehuang** [comment]
> I think it would be preferable to add DCNv2 instead of original DCN at this point for both pytorch and onnx. https://github.com/CharlesShang/DCNv2

Yes, you are right. I want to convert yolact_plus to onnx but onnx don't support DCNv2.
```
import DCNv2
torch.onnx.export(net, batch, "yolact_plus.onnx",operator_export_type=DCNv2)
```
Error
> Multiple GPUs detected! Turning off JIT.
> Config not specified. Parsed yolact_plus_base_config from the file name.
> 
> Loading model... Done.
> /home/kiwi/Document/yolact/DCNv2/dcn_v2.py:31: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   ctx.deformable_groups)
> /home/kiwi/Document/yolact/yolact.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if self.last_img_size != (cfg._tmp_img_w, cfg._tmp_img_h):
> Traceback (most recent call last):
>   File "eval.py", line 1123, in <module>
>     evaluate(net, dataset)
>   File "eval.py", line 895, in evaluate
>     evalimage(net, args.image)
>   File "eval.py", line 609, in evalimage
>     torch.onnx.export(net, batch, "yolact_plus.onnx",operator_export_type=DCNv2)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
>     strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
>     dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 416, in _export
>     fixed_batch_size=fixed_batch_size)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
>     fixed_batch_size=fixed_batch_size, params_dict=params_dict)
>   File "/home/kiwi/miniconda3/envs/detectron2/lib/python3.6/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
>     graph = torch._C._jit_pass_onnx(graph, operator_export_type)
> TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
>     1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph

**Comment by EphChem** [comment]
Anyone solve this yet?  I'm also facing same issue when using pytorch onnx parser on object detection model which uses dcn_v2.py.  I'm using pytorch 1.3.0.

/home/.../layers/dcn_v2.py:32: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ctx.deformable_groups)

**Comment by niraj-bhujel** [comment]
**I am having the same issue. Please some one help**


/FairMOT/DCNv2/dcn_v2.py:31: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ctx.deformable_groups)

RuntimeError: ONNX export failed: Couldn't export Python operator _DCNv2

**Comment by hyperfraise** [comment]
This would be very interesting for segmentation models.

**Comment by Toxiang** [comment]
any message about DCNv2 to onnx？

**Comment by hyperfraise** [comment]
I believe it is in fact still relevant

**Comment by hyperfraise** [comment]
I believe this was actually implemented in opset 19 ! Thanks to the devs ! Would be great to have confirmation through a model optimization if this is still relevant for someone in this thread.

**Comment by justinchuby** [comment]
https://onnx.ai/onnx/operators/onnx__DeformConv.html#l-onnx-doc-deformconv
