### ISSUE TITLE
Running example from PythonAPIOverview returns ValidationError

### ISSUE THREAD

**Issue by AlexMuresan** [onnx/onnx#2490]
Running the code given as example in the API Overview, under the [Creating an ONNX Model Using Helper Functions](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md) section returns a ValidationError when checking the model using the ONNX checker.

This is the code snipped to reproduce the issue:

    import onnx
    from onnx import helper
    from onnx import AttributeProto, TensorProto, GraphProto

    # Create one input (ValueInfoProto)
    X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 2])

    # Create one output (ValueInfoProto)
    Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 4])

    # Create a node (NodeProto)
    node_def = helper.make_node(
        'Pad', # node name
        ['X'], # inputs
        ['Y'], # outputs
        mode='constant', # attributes
        value=1.5,
        pads=[0, 1, 0, 1],
    )

    # Create the graph (GraphProto)
    graph_def = helper.make_graph(
        [node_def],
        'test-model',
        [X],
        [Y],
    )

    # Create the model (ModelProto)
    model_def = helper.make_model(graph_def, producer_name='onnx-example')

    onnx.checker.check_model(model_def)
    print('The model is checked!')

Here is the traceback:

    Traceback (most recent call last):
    File "create_onnx_ns_test_graph.py", line 97, in <module>
        onnx.checker.check_model(model_def)
      File "/home/amuresan/anaconda3/envs/pytorch-gpu/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
        C.check_model(model.SerializeToString())
    onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

    ==> Context: Bad node spec: input: "X" output: "Y" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 1 ints: 0 ints: 1 type: INTS } attribute { name: "value" f: 1.5 type: FLOAT }

I am running ONNX 1.6.0 installed from conda-forge.

**Comment by linkerzhang** [comment]
This is a version mismatch problem.

The model you're manually creating is following the "Pad" operator version 1 https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Pad-1 when "Pad" only has one input, others are constant inputs as attributes.

When you run the checker, I believe you're running the latest checker (master branch), which is based on latest "Pad" operator definition, and it has 2-3 inputs (one is optional).

To solve the problem, either using latest “Pad" operator when manually creating the model, or, using the old checker in an old ONNX released package.

**Comment by linkerzhang** [comment]
It will be appreciated if you can help to refine this kind of documentation with your experiences, say, clarifying more on using the right version in this tutorial. Thank you!
