### ISSUE TITLE
"shape" field should not be enforced on TypeProto::kTensorType in onnx checker

### ISSUE THREAD

**Issue by samratdebroy** [onnx/onnx#2492]
When running the onnx checker on a model with a tensor that has a missing "shape" parameter, the checker throws the following error:

```
C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
```

looking at [checker.cc](https://github.com/onnx/onnx/blob/master/onnx/checker.cc) I see that this is a result of the following code:
```
 case TypeProto::kTensorType: {
      const auto& type = value_info.type().tensor_type();
      enforce_has_field(type, elem_type);
      enforce_has_field(type, shape);
    } break;
``` 
but the [ONNX standard](https://github.com/onnx/onnx/blob/master/docs/IR.md#input--output-data-types) clearly states that a missing "shape" parameter on a tensor is how we indicate that the tensor takes in zero or more dimensions of data:

>  A zero-dimension tensor is distinct from a tensor of unknown dimensionality, which is indicated by an absent 'shape' property in the Tensor record.
as well as:

> The use of the string "*" (as a dimension variable) to denote a sequence of zero or more dimensions of unknown cardinality. This is not supported. In the current implementation, the number of dimensions in a shape MUST represent the rank of the tensor. A tensor of unknown rank is represented using a TypeProto::Tensor object with no shape, which is legal.

I encountered this problem while trying to visualize the output of one of the intermediary nodes of the model by marking it as an output of the model itself:
```
model = onnx.load(model_path)
intermediate_layer_value_info = onnx.helper.make_tensor_value_info('output_name', onnx.TensorProto.FLOAT, None)
model.graph.output.extend([intermediate_layer_value_info])
onnx.checker.check_model(model)
```

**Comment by linkerzhang** [comment]
The checker is good in this case.

The standard is saying, every graph's inputs/outputs MUST have detail type information specified in a model. Type information contains "shape".

For your case, as you're actually trying to add an intermediate node's output, whose type information is actually not a MUST (as it can be inferred), as a graph output, so the failure is shown.

To resolve the problem, you may infer the graph/model to understand the intermediate node's output's type information and make the type information complete when adding it into graph output list.

**Comment by samratdebroy** [comment]
Hmm okay that's quite unclear in the [documentation](https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs) as that doesn't actually seem to be explicitly mentioned anywhere that graph input/outputs are an exception to the rule that TensorTypes can omit having a defined shape.

And am I correct in assuming that there's no clean way to infer the output size of an intermediate node unless we know its op_type and inputs? As in if I wanted to make a legal .onnx model where all the intermediary node outputs were also available as graph outputs, then I'd have to manually define the output shape for all of them?

**Comment by samratdebroy** [comment]
Hey, I'm reopening this issue because the new ONNX IR documentation seems to imply even stronger that "shape" is not a required parameter of TypeProto::kTensorType protobuf messages. The [IR Documentation](https://github.com/onnx/onnx/blob/master/docs/IR.md#static-tensor-shapes) states the following:
> When the shape property is absent for an output, the caller should expect that the output value may be of any shape.

Even [ONNX Runtime](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/inference_session.cc#L1324) and the `make_tensor_value_info` in [onnx/helper.py](https://github.com/onnx/onnx/blob/master/onnx/helper.py#L326) don't seem to assume there MUST be a "shape" parameter for tensors. Hence I still don't think shape should be enforced in [onnx/checker.cc](https://github.com/onnx/onnx/blob/master/onnx/checker.cc#L54).

**Comment by aman0330** [comment]
I am also having the same problem. I will be really appreciated if a proper solution can be provided for the issue

**Comment by askhade** [comment]
#2937 address this issue. Closing this issue as the PR is now merged.
