### ISSUE TITLE
how to uninstall onnx?

### ISSUE THREAD

**Issue by ultracxx1997** [onnx/onnx#2495]
I just do

**Instructions to build ONNX on windows in anaconda environment**

```
# Use conda-forge protobuf
conda install -c conda-forge protobuf=3.9.2 numpy

# Get ONNX
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive

# Set environment variable for ONNX to use protobuf shared lib
set CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"

# Build ONNX
# Optional : Set environment variable `ONNX_ML=1` for onnx-ml

python setup.py install
```
but when i done the steps,some errors happened.
my python script running on pycharm didn't work.
`import onnx ` 

can run normally, but when the program run on onnx.xxx()
a error would be caught.  
so now i just want undo the changes of build onnx made to my windows10.
uninstall it.  i try to delete the files **ONNX**,but that doesn't seem to work.
how should i do?

**Comment by jcwchen** [comment]
Hi @ultracxx1997,
Sorry for the late reply.
You can git clean those untracked files and reinstall onnx.
```
git clean -xdf
python setup.py install
```
BTW, to remove those installed files. You need other command to track those installed files:
```
python setup.py install --record installed_files.txt
```
Then you can remove all files in `installed_files.txt`.

**Comment by ultracxx1997** [comment]
thank you
&nbsp;

nnn


&nbsp;
