### ISSUE TITLE
CI Build Error

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#2497]
I see a build error message at [my PR.](https://ci.appveyor.com/project/onnx/onnx/builds/29451341/job/7b9pr6wg1svxg03m) Is anyone aware of it? Thanks. There is also another CI build [failure](https://travis-ci.org/onnx/onnx/jobs/623370061?utm_medium=notification&utm_source=github_status).

ImportError: 
IPython 7.10+ supports Python 3.6 and above.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
See IPython `README.rst` file for more information:

@linkerzhang , any comment?

**Comment by linkerzhang** [comment]
fixed by @bddppq . Thanks @bddppq  a lot! :)

**Comment by kaycapt** [comment]
Hi, I'm currently facing this same issue, can anyone share how to resolve it, please?
