### ISSUE TITLE
ONNX Loop input not match

### ISSUE THREAD

**Issue by joe8086** [onnx/onnx#2498]
When I do onnx backend test "test_range_int32_type_negative_delta_expanded",
This case will generate loop operation.
And I found The Loop body graph input and body graph internal op input not match.
The Graph Serialize result is:
```
node {
  input: "cond"
  output: "cond_out"
  op_type: "Identity"
}
node {
  input: "prev"
  input: "delta"
  output: "current"
  op_type: "Add"
}
node {
  input: "prev"
  output: "range"
  op_type: "Identity"
}
name: "loop_body_attribute"
input {
  name: "i"
  type {
    tensor_type {
      elem_type: 7
      shape {
      }
    }
  }
}
input {
  name: "cond"
  type {
    tensor_type {
      elem_type: 9
      shape {
      }
    }
  }
}
input {
  name: "prev"
}
output {
  name: "cond_out"
}
output {
  name: "current"
}
output {
  name: "range"
}

```
You can see the following information not match
name: "i"
input: "delta"

body graph and internal node input name not match.
My test environment is under onnx1.6.0, Ubuntu.
Not sure is this a test bug or a onnx implement bug.
I didn't find the test case source location, so I'm not sure does this a onnx bug or a test case bug.

Hope I can get some answer form here, Thanks.

**Comment by linkerzhang** [comment]
@skottmckay

**Comment by skottmckay** [comment]
Subgraph input/output matching is based on order not name. 

The ONNX spec defines the order of the subgraph inputs and outputs, and the implementation will figure out the names based on that.

**Comment by linkerzhang** [comment]
@skottmckay would you help to add "Subgraph input/output matching is based on order not name" as a little bit more clarification in the spec https://github.com/onnx/onnx/blob/master/docs/Operators.md#Loop please? Thank you!
