### ISSUE TITLE
Why upsample operator was deprecated??

### ISSUE THREAD

**Issue by tkclimb** [onnx/onnx#2501]
I found upsample op was deprecated since the version 10.
Why is it? is there any alternative operation that the upsampling operator is going to be converted into?
https://github.com/onnx/onnx/blob/master/docs/Operators.md#upsample-deprecated

**Comment by linkerzhang** [comment]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize is the alternative one
