### ISSUE TITLE
onnx.helper.printable_graph

### ISSUE THREAD

**Issue by huang229** [onnx/onnx#2502]
onnx.helper.printable_graph(model.graph)
I called this function, but there was no printout.

####
import onnx
model = onnx.load("alexnet.onnx")
onnx.checker.check_model(model)
####print a human readable representation of the graph
onnx.helper.printable_graph(model.graph)

**Comment by askhade** [comment]
you need to place this in a print statement. Try something like:

print('Model :\n\n{}'.format(onnx.helper.printable_graph(model.graph)))

**Comment by huang229** [comment]
Thank you!
