### ISSUE TITLE
ONNX 3D CNN model converter

### ISSUE THREAD

**Issue by tomanick** [onnx/onnx#2505]
I want to use onnx to convert pytorch 3d cnn model to onnx. But I found some problems. Therefore, I want to ask if onnx support 3d cnn in converting pytorch to onnx?

**Comment by prasanthpul** [comment]
I have a 3D convolution model working in ONNX but it wasn't from pytorch. For your question, I suggest posting it in PyTorch github along with the error you are seeing when you export. That way the right folks can take a look

@spandantiwari as fyi
