### ISSUE TITLE
ONNX model has been generated with INT64 weights?

### ISSUE THREAD

**Issue by student-2018AI** [onnx/onnx#2506]
when train a classifier by using pre-trained resnet18 and then convert the pytorch to onnx,
i meet a error : " WARNING: Your ONNX model has been generated with INT64 weights".

how does the INT64 weight come up?
my pytorch version is 1.1.0 ,torchvision is 0.3.0 and python3.6.

**Comment by prasanthpul** [comment]
This is a PyTorch issue rather than onnx. Can you please file in the PyTorch github so the right folks can take a look?

@spandantiwari as fyi
