### ISSUE TITLE
Reshape operator -- handling zero values is confusing

### ISSUE THREAD

**Issue by jignparm** [onnx/onnx#2507]
The current implementation of `Reshape` states:

`A dimension could also be 0, in which case the actual dimension value is unchanged (i.e. taken from the input tensor).`

This is inconsistent with NumPy and TensorFlow, and moreover causes unexpected shape behavior. For example, if the input has shape **[0,255]** and the request is to reshape to **[255, 0]**, then the current `Reshape` op try to reshape the input to **[255, 255]**, which is not intuitive and seemingly incorrect.

This unexpected behavior is causing some TF models (converted to ONNX) to fail at runtime.

Proposal for opset-12 is to remove the statement above in the current spec, and bring `Reshape` behavior in line with NumPy behavior.

If there are specific reasons why this should not be changed, a clarifying example would be great.

**Comment by linkerzhang** [comment]
looks to me a reasonable fix.

**Comment by jignparm** [comment]
Proposed 2 separate PRs to handle this. Only 1 should be merged (preferably #2553), contingent on feedback.

1> PR #2553 : Make it work like NumPy 
2> PR #2552 : Retain current behavior, but make it work like NumPy if needed via new attribute 'allowzero'

**Comment by neginraoof** [comment]
Can we keep the same behavior with -1 dim value?

**Comment by jignparm** [comment]
> Can we keep the same behavior with -1 dim value?

Can you clarify? The current behavior of reshape is:

* 0 = copy from input
* -1 = infer from remaining dimensions

The 2 PRs above change the meaning of '0' values, but not '-1'. Did you mean that there should be a change in the meaning of -1?
