### ISSUE TITLE
BUG:A interesting problem about shape inference confuses me

### ISSUE THREAD

**Issue by emelife** [onnx/onnx#2508]
ubuntu 16.04
python 3.6
onnx 1.6.0

I need to do some work about network shape inference,so I  convert model to onnx and then use shape_inference.infer_shapes() to do it, but unlucky thing comes up, a lot of ops' shape can't inference successfully,I find the problem is Shape OP, because the output of Shape OP is shape info, for example [1,3,112,112], but in inference phase，it ouput dim information , it's [4]. how do you think of it ? and how to solve shape inference problem? thanks a lot!

**Comment by linkerzhang** [comment]
shape inference in ONNX right now means static shape inference, which happens without input data. So, operators which leads to dynamic shape (in runtime) do not have appropriate static shape inference in-place. "Shape" op is one of them.

**Comment by emelife** [comment]
@linkerzhang  thanks, I don't really understand difference between static shape and dynamic shape, does it mean that static shape is the shape I get when I call shape_inference.infer_shapes() function but dynamic shape is the shape I get when I run model in runtime stage. if it is that ,then I don't know what does "Shape" op's static shape use for? I think "Shape" op is a special op unlike conv /matmul op it should return shape's value not shape' shape in shape_inference stage.It just my opinion,thanks

**Comment by linkerzhang** [comment]
static shape means shape information can be gotten when there's no user inputs running thru the model. dynamic shape means shape information that can only be gotten with user inputs.

For "Shape" op, I think the operator's functionality is to get the input's shape information (as this op's output), while its shape inference function is getting its output's shape information.

Make sense?

**Comment by emelife** [comment]
@linkerzhang thanks for your reply,I understand ,but for static shape inference, I think it also need to be feed input shape information. doesn't it ?

**Comment by linkerzhang** [comment]
you're right. Input shape information is needed. This is why ONNX is asking type and shape information to be present in a model for its all inputs, so that shape and type inference can be done, though it's not guaranteed (shape inference can be broken when having "Shape" op for example, as you see).
