### ISSUE TITLE
calculate the number of layers and operators a onnx model

### ISSUE THREAD

**Issue by aliimani** [onnx/onnx#2511]
how can I calculate the number of each layer and operator by Python?

**Comment by askhade** [comment]
There is no tool to do this today. Can you add some details regarding what you are trying to achieve?

**Comment by aliimani** [comment]
thanks for your response.
Actually, for one of my university projects, I should implement a program to gather the following information from an ONNX model:
•The number of each layer/operator.
•The kernel-size, stride, input/output tensor size of CONV operators.
•The total size of weight data which is read-only for inference workloads.
•Runtime produced and consumed data.
•Connectivity within the neural network graph.

**Comment by askhade** [comment]
We don't have a tool today specially catered to give this info, however please take a look at : 
https://github.com/onnx/onnx/blob/59b9f908fc3698c15dc818653054f4885e402488/onnx/helper.py#L540

This may be helpful... This method walks through the ONNX graph and prints it... you can use similar method to extract the info you want and perhaps check it in as a tool in ONNX too.

For connectivity within the neural network getting a topologically sorted list of nodes from the graph should work.
