### ISSUE TITLE
Resize support

### ISSUE THREAD

**Issue by MandySuperTT** [onnx/onnx#2524]
I’m trying to convert Pytorch model to Onnx model, there is a block where I’ve used

   ```
 import torch.nn.functional as F
    F. interpolate(h, size=(288,528), mode=‘bilinear’, align_corners=False)
```

to achieve `Upsampling`

There is no Bug or any Error during converting process. However, when I ran the onnx model, I’ve got this error

>   Onnx operator Resize is not supported now… By Passing

Failed to run Onnx model.

>  I’ve used Pytorch 1.3 and Opset version = 11

 The way I exported onnx is
 `torch.onnx.export(model, inputs, "pytorch-bilinear.proto", export_params=True,opset_version=11)`

**Comment by linkerzhang** [comment]
@spandantiwari

**Comment by spandantiwari** [comment]
@MandySuperTT  Can you please paste the entire error message? 
Also, we have recently updated export for `F.interpolate` in PyTorch. Could you please try installing the latest nightly build from PyTorch.org and exporting the model?

**Comment by qizhen816** [comment]
@spandantiwari I used `F.interpolate` in PyTorch nightly, and got this:
```
graph(%x : Float(1, 3, 256, 256),
      %12 : Long(2)):
  %2 : Tensor = onnx::Constant[value=[ CPUFloatType{0} ]]()
  %3 : Tensor = onnx::Shape(%x)
  %4 : Tensor = onnx::Constant[value={0}]()
  %5 : Tensor = onnx::Constant[value={0}]()
  %6 : Tensor = onnx::Constant[value={2}]()
  %7 : Tensor = onnx::Slice(%3, %5, %6, %4)
  %9 : Tensor = onnx::Concat[axis=0](%7, %12)
  %10 : Tensor = onnx::Constant[value=[ CPUFloatType{0} ]]()
  %11 : Float(1, 3, 256, 256) = onnx::Resize[coordinate_transformation_mode="pytorch_half_pixel", cubic_coeff_a=-0.75, mode="linear", nearest_mode="floor"](%x, %2, %10, %9) # /home/qizhen/.local/lib/python3.5/site-packages/torch/nn/functional.py:2575:0
  return (%11)
```
It's not working with TensorRT:
`In node 8 (parseGraph): INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)`
And this is my code:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()
    def forward(self, x):
        x = F.interpolate(x, (256, 256), mode = 'bilinear')
        return x
torch_model = TestModel()
dummy_input = torch.randn((1, 3, 256, 256))
torch_out = torch.onnx.export(torch_model,
                              dummy_input,
                              'test_model.onnx',
                              verbose=True,
                              opset_version=11,)
```

**Comment by spandantiwari** [comment]
We will take a look.

**Comment by lara-hdr** [comment]
@qizhen816 I tested your model with:
torch:  1.4.0a0+1ba1799
onnx:  1.6.0
onnxruntime:  1.0.0

The model is exported and runs with matching numbers with onnx runtime (attached is the repro with the exported model).
[issue2524.zip](https://github.com/onnx/onnx/files/4041789/issue2524.zip)

It could potentially be an issue with TensorRT.

**Comment by lara-hdr** [comment]
@MandySuperTT if I understand correctly, the model exports correctly but  the error is happening while running the ONNX model. 
How are you running the ONNX model? It seems that the engine you are using does not have an implementation of Resize; try using the latest version.

**Comment by qizhen816** [comment]
@lara-hdr Yes, it's a TensorRT issue, sorry to bother again.

**Comment by MandySuperTT** [comment]
@lara-hdr @spandantiwari Thanks for all your kindly response. The problem is solved with the latest version of Pytorch.
Would you mind to check an another issue I created related to Upsample? I used the latest version of Pytorch but the output of upsample os still not correct[2535](https://github.com/onnx/onnx/issues/2535)

**Comment by lara-hdr** [comment]
@qizhen816 no worries!
@MandySuperTT, I replied to #2535.

Will close this issue now, feel free to comment again if there are any other problems.

@prasanthpul  could you please close this?

**Comment by kingyj7** [comment]
Hi, @qizhen816, I met the same problem with you. And I'm wondering how you solve it at last. 
Thanks a lot!

**Comment by CuttlefishXuan** [comment]
hi @MandySuperTT , I have met the same problem. When I convert pytorch model to onnx model, the interpolate or upsample operations have been transformed to resize operation in onnx. However, the platform I used for onnx model doesn't support resize op. 
My environment settings:
python==3.7
pytorch==1.6.0
onnx==1.6

Can I ask you how to solve this problem? What I mean is that converting the interpolate operation in pytorch to upsample operation in onnx, not resize.
