### ISSUE TITLE
Integer support for more operators

### ISSUE THREAD

**Issue by TMVector** [onnx/onnx#2528]
I scanned the operator list for operators that should work with integer tensors but are currently only defined for floats. (Had to work around a couple of these for one model).

**Straighforward operators:**
- [x] Clip (#2450) (PR #2532)
- [ ] GlobalMaxPool
- [ ] Hardmax
- [x] Max (PR https://github.com/onnx/onnx/pull/2608)
- [ ] MaxPool
- [ ] MaxRoiPool
- [ ] MaxUnpool
- [x] Min (PR https://github.com/onnx/onnx/pull/2608)
- [x] Relu (PR #3141)
- [ ] ThresholdedRelu

**Operators that could overflow or require larger intermediate types:**
- [ ] Det
- [ ] Pow

I plan to have a go at the non-pooling simple ones, as I think they should also be trivial to add support for in ONNX Runtime. The pooling ones look like they might be okay but I haven't tried it.

**Comment by linkerzhang** [comment]
Thanks! PRs are welcome to add more necessary types' support for existing ops.

**Comment by pbamotra** [comment]
```
  File "/classifier/src/utils/deployer_lib.py", line 297, in deploy
    self.to_triton_onnx(dataloader, model)
  File "/classifier/src/utils/deployer_lib.py", line 376, in to_triton_onnx
    onnx.checker.check_model(converted_model)
  File "/opt/conda/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: min for operator Clip

==> Context: Bad node spec: input: "2161" output: "2162" name: "Clip_1383" op_type: "Clip" attribute { name: "min" f: 1e-12 type: FLOAT }
```

Onnx version 1.6

**Comment by TMVector** [comment]
Hi @pbamotra that looks like an issue with the PyTorch exporter -- it's producing a `Clip` node which doesn't match the [Clip operator definition in opset 11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Clip-11). The operator [changed to take min/max as inputs](https://github.com/onnx/onnx/pull/2096) instead of attributes in that operator set version.

Can you please make sure you are using the most recent version of PyTorch and if it still fails, raise it as an issue on the [PyTorch repo](https://github.com/pytorch/pytorch) (check for existing issues first ofc 🙂). You could also try specifying a different opset version.

**Comment by killTheHostage** [comment]
> ```
>   File "/classifier/src/utils/deployer_lib.py", line 297, in deploy
>     self.to_triton_onnx(dataloader, model)
>   File "/classifier/src/utils/deployer_lib.py", line 376, in to_triton_onnx
>     onnx.checker.check_model(converted_model)
>   File "/opt/conda/lib/python3.6/site-packages/onnx/checker.py", line 91, in check_model
>     C.check_model(model.SerializeToString())
> onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: min for operator Clip
> 
> ==> Context: Bad node spec: input: "2161" output: "2162" name: "Clip_1383" op_type: "Clip" attribute { name: "min" f: 1e-12 type: FLOAT }
> ```
> 
> Onnx version 1.6
> Failing to export because of this issue
> 
> ```python
> torch.onnx.export(
>                 model,
>                 inputs[0],
>                 final_model_path,
>                 verbose=False,
>                 input_names=input_names,
>                 output_names=output_names,
>                 dynamic_axes=dynamic_axes,
>                 opset_version=11,
>             )
> ```

I have the same problem now. Have you found a solution?

**Comment by TMVector** [comment]
@killTheHostage you could try `opset_version=10` as a workaround

**Comment by killTheHostage** [comment]
> @killTheHostage you could try `opset_version=10` as a workaround

First, thanks for your help.
But the operator "einsum" also used in my onnx model, I have no choice but set `opset_version=12`. Are there any solutions?

**Comment by TMVector** [comment]
Aside from editing the graph to manually upgrade the operator, I think your PyTorch issue is the best route forward.

Here is a snippet on how to upgrade the Clip nodes (I haven't tested beyond [this notebook](https://colab.research.google.com/drive/1LUbtFKdjRzOH7SV-nmSAfnt5A5TKE0rh?usp=sharing))

```python
import onnx
from onnx import numpy_helper
from onnx import helper
import numpy as np

model = onnx.load("path/to/model.onnx")

assert {opset.domain: opset.version for opset in model.opset_import}[""] > 10, \
  "ai.onnx opset is not greater than 10, Clip will not be upgraded"

for node in model.graph.node:
  if node.op_type == "Clip" and node.domain == "":
    assert len(node.input) == 1, \
      "Clip already has min/max inputs, no upgrade needed?"
    name_base = node.output[0]
    assert name_base != ""
    
    # Move min/max attributes into initializers and add to node inputs
    for bound in ["min", "max"]:
      tensors = [
        onnx.numpy_helper.from_array(np.array(attr.f, dtype=np.float32), name=f"{name_base}__{bound}")
        for attr in node.attribute if attr.name == bound
        ]
      if len(tensors) == 1:
        model.graph.initializer.extend(tensors)
        node.input.extend([tensors[0].name])
      elif len(tensors) == 0:
        node.input.extend([""])
      else:
        raise ValueError(f"More than one attribute found for {bound}")
    
    del node.attribute[:]

onnx.save(model, "model.upgrade-cast.onnx")
```

**Comment by spandantiwari** [comment]
@killTheHostage - I am not able to find a repro your issue with the Clip op in opset 11. Could you share the exact specific model and export code.
You have opened the PyTorch issue https://github.com/pytorch/pytorch/issues/39053. That is the right place for this issue. Let's track it there. 
cc: @pbamotra

**Comment by v-nhandt21** [comment]
Just for ref, I was successful in converting when using pytorch in CPU, I wonder if should we check we are running with cpu or gpu
