### ISSUE TITLE
numpy_helper does not support string type?

### ISSUE THREAD

**Issue by Exlsunshine** [onnx/onnx#2531]
Reproduce code:
```
import numpy as np
test_data = np.random.random_sample([1,2]).astype(np._string)
numpy_helper.from_array(test_data)
```

Got:
```
File "D:\Program\anaconda3\envs\py3temp\lib\site-packages\onnx\numpy_helper.py", line 113, in from_array
 "Numpy data type not understood yet: {}".format(str(arr.dtype)))
RuntimeError: Numpy data type not understood yet: |S32
, exception is Numpy data type not understood yet: |S32
```

Can we consider supporting numpy string dtype?

**Comment by askhade** [comment]
It does support. 
1. Change the dtype to np.object
2. make sure the contents of array is a string
Example:
>>> test_data =  np.array([[u'0.46503946427687426', u'0.5318961508445769']]).astype(np.object)
>>> numpy_helper.from_array(test_data)
dims: 1
dims: 2
data_type: 8
string_data: "0.46503946427687426"
string_data: "0.5318961508445769"


>>> test_data =  np.array([u'monday', u'tuesday', u'wednesday', u'thursday']).astype(np.object)
>>> numpy_helper.from_array(test_data)
dims: 4
data_type: 8
string_data: "monday"
string_data: "tuesday"
string_data: "wednesday"
string_data: "thursday"
