### ISSUE TITLE
TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float

### ISSUE THREAD

**Issue by santhoshnumberone** [onnx/onnx#2534]
I am trying to convert yolov3 into onnx using [yolov3_to_onnx.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolov3_onnx/yolov3_to_onnx.py)

Following these instructions [ Demo #4: YOLOv3](https://github.com/jkjung-avt/tensorrt_demos?#user-content-demo-4-yolov3)

when I run 

`python3 yolov3_to_onnx.py --model yolov3-416 `
I get this error 

```
    Layer of type yolo not supported, skipping ONNX node generation.
    Layer of type yolo not supported, skipping ONNX node generation.
    Layer of type yolo not supported, skipping ONNX node generation.
    Traceback (most recent call last):
      File "yolov3_to_onnx.py", line 819, in <module>
        main()
      File "yolov3_to_onnx.py", line 807, in main
        verbose=True)
      File "yolov3_to_onnx.py", line 444, in build_onnx_graph
        params)
      File "yolov3_to_onnx.py", line 280, in load_upsample_scales
        name, TensorProto.FLOAT, shape, data)
      File "/home/mysystem/.local/lib/python3.6/site-packages/onnx/helper.py", line 173, in make_tensor
        getattr(tensor, field).extend(vals)
    TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float
```
you can find more details here [Yolo V3 to TensorRT on Ubuntu 18.04 with GeForce GTX 1050Ti](https://devtalk.nvidia.com/default/topic/1069023/tensorrt/yolo-v3-to-tensorrt-on-ubuntu-18-04-with-geforce-gtx-1050ti/post/5415744/?offset=8#5416970)
What is going wrong?

**Comment by santhoshnumberone** [comment]
updating `protobuf` to the latest version fixed the issue

**Comment by KausthubK** [comment]
I was running into the same issue - updating protobuf works. thanks @santhoshnumberone

**Comment by iperov** [comment]
latest protobuf==3.17.3 

```
onnx_helper.make_tensor(name='asd', data_type=TensorProto.FLOAT16, dims=(3,), vals=[0.0, 0.0, 0.0] )
```

```
TypeError: 0.0 has type float, but expected one of: int, long
```
