### ISSUE TITLE
ReduceMean on integer types

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#2557]
How does ReduceMean for integer tensors handle quotients that:
-  are not exact. e.g. the mean of a vector with [0,1,1]?  Using the obvious formula and integer arithmetic yields 0, but 1 would be closer to the mathematical result.
-  involve zero/zero, e.g. the mean of an empty int32 vector.

**Comment by linkerzhang** [comment]
I doubt there is an operator spec bug. Reducemean does not need to support integers? @ebarsoum @postrational
