### ISSUE TITLE
1D tensor type specification for Elu and Softplus operators

### ISSUE THREAD

**Issue by Guriido** [onnx/onnx#2563]
In the documentation, the inputs and outputs of Elu and Softplus operators are specified to be `1D input tensor`.
I think it should be corrected to `Input tensor` , as there should not be restrictions on the input shapes of this operators.

https://github.com/onnx/onnx/blob/master/docs/Operators.md#Elu
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Softplus

**Comment by robertknight** [comment]
This issue is still relevant. The docs state the operator should be 1D, but it is a unary elementwise operator, so there is no reason for this restriction that I can see.
