### ISSUE TITLE
load ONNX model in C++

### ISSUE THREAD

**Issue by SerenaC94** [onnx/onnx#2569]
Hi,
I can load ONNX models in python with
`model = onnx.load('test.onnx')`
and I was looking for a way to do the same in C++. The solution proposed in #418 does not work, I get the following error:
```
error: ‘class onnx::ModelProto’ has no member named ‘ParseFromIstream’; did you mean ‘ParseFromString’?
     model.ParseFromIstream(in);
```
I suppose that things have changed since the question was first asked, so is there a function with a different name that can do the same now? (ParseFromString also does not seem to exist)

**Comment by linkerzhang** [comment]
You may refer to https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/graph/model.cc#L231
