### ISSUE TITLE
Don't know how to translate op Resize

### ISSUE THREAD

**Issue by allen-leapsy** [onnx/onnx#2582]
I have an object detect model, and I convert it to onnx format.

I try to convert it to caffe2 format, but I got this Exception : 

```
Error while processing node: input: "144"
input: "173"
output: "174"
op_type: "Resize"
attribute {
  name: "mode"
  s: "nearest"
  type: STRING
}
. Exception: Don't know how to translate op Resize
```

Is anyone can solve this ?

**Comment by alejo9719** [comment]
I used to convert my PyTorch model to Caffe2 format back in PyTorch v1.0.0, now I try to run the same code and it gives me tens of those errors. Something must have changed in the export functions.

**Comment by zdaiot** [comment]
Hello，anyone solve it？

**Comment by zdaiot** [comment]
> I have an object detect model, and I convert it to onnx format.
> 
> I try to convert it to caffe2 format, but I got this Exception :
> 
> ```
> Error while processing node: input: "144"
> input: "173"
> output: "174"
> op_type: "Resize"
> attribute {
>   name: "mode"
>   s: "nearest"
>   type: STRING
> }
> . Exception: Don't know how to translate op Resize
> ```
> 
> Is anyone can solve this ?
Hello，anyone solve it？

**Comment by askhade** [comment]
If you are having trouble converting the model from pytorch to onnx then please update both pytorch and onnx to latest and give it another try. If the issue is converting from onnx to caffe2 then please open an issue in that repo instead.
