### ISSUE TITLE
Segfault raised on v1.6.0 wheel release when exporting single convolution models in PyTorch

### ISSUE THREAD

**Issue by andfoy** [onnx/onnx#2591]
Thanks for your work on providing an exchange system for all libraries!

It looks that there's some error on the published wheel distributions of ONNX v1.6.0 when trying to export simple convolution-only models, as the following code example fails. 

```python
import torch 
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from torch.autograd import Variable

import onnx
import numpy as np

import sys
import os


class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.layer1 = nn.Conv2d(in_c, num_filters, kernel_size=kdim, 
                                stride=stride, padding=padding, groups=1,
                                bias=False)
        self.layer2 = nn.Conv2d(num_filters, num_filters, kernel_size=kdim, 
                                stride=stride, padding=padding, groups=1,
                                bias=False)

    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        return out


torch.manual_seed(42)
np.random.seed(0)
# set hyperparams
model_names = ['weenet']

model_name = 'weenet'
in_c = 32
num_filters = 32
in_h, in_w = 32, 32
kdim = 3
stride=1
padding=0
in_shape = (1, in_c, in_h, in_w)

test_input = torch.rand(1, in_c, in_h, in_w)
x = test_input
model = ConvNet()

# create model
save_path = '/tmp/'
fname = 'test_model'
g = 1
save_name = save_path + fname + '.onnx'

model.eval()
py_outs = model(x)

torch.onnx.export(model, test_input, save_name)
targets = py_outs.detach().numpy()

onnx_model = onnx.load_model(save_name)
# Segfault is raised here
onnx.checker.check_model(onnx_model)
```

However, when the source distribution for that release is compiled and installed, it works correctly. This behaviour leads to think that there is some kind of error on the distributed wheels for the latest ONNX release, thus a, minor patch release of ONNX might be required here. Please correct me if I'm wrong on this topic.

I'm linking this issue with the corresponding one downstream in PyTorch: https://github.com/pytorch/pytorch/issues/30560

cc @ezyang @rgommers

**Comment by houseroad** [comment]
@andfoy , could you check whether release 1.7 solve the problem or not?

**Comment by ahangchen** [comment]
@houseroad I have the same issues on onnx 1.7

**Comment by Chao86** [comment]
> @houseroad I have the same issues on onnx 1.7

hi, @ahangchen , finally, have you handled this issue?
