### ISSUE TITLE
Incosistent pad attribute on Pad and Conv

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx#261]
Let's make sure it's consistent with the rest of ops and current implementations.

It seems that Pad is right now [x_beg, x_end, y_beg, y_end]: https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/pad.py
While Conv is [x_beg, y_beg, x_end, y_end]

I'd argue it's confusing and we should change it. I'm a bit biased toward Caffe2 which does [x_beg, y_beg, x_end, y_end] - shall we go with that? The good thing about it is that if you have symmetrical padding it's just list*2

@ebarsoum @yuanbyu

**Comment by ebarsoum** [comment]
@dzhulgakov  let's changes all `pads` attributes in Conv, ConvTranspose, MaxPool, AveragePool, LpPool. And the pad pattern in the `pads` OP. To match Caffe 2:

[x1_beg, x2_beg, x3_beg,...,x1_end, x2_end, x3_end...]

Does that sound good?

**Comment by dzhulgakov** [comment]
Done in #268. Still need to fix Caffe2 and PyTorch bindings

**Comment by ezyang** [comment]
Fixed.
