### ISSUE TITLE
import onnx error: image not found

### ISSUE THREAD

**Issue by wly-ai-bj** [onnx/onnx#2610]
import onnx
  File "/opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: dlopen(/opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libprotobuf.20.dylib
  Referenced from: /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/onnx/onnx_cpp2py_export.cpython-37m-darwin.so
  Reason: image not found

onnx                      1.6.0            py37h6de7cb9_0    conda-forge
protobuf                3.9.1            pypi_0                      pypi

how can i resolve the problem?

**Comment by wly-ai-bj** [comment]
my python version is 3.7.5.
I have tried to downgrade protobuf to 3.9 via:
conda install -c anaconda protobuf
but it does not work for me.

**Comment by vinitra** [comment]
Hi @wly-ai-bj. We've recently created a lightweight docker file with the core onnx dependencies that will (hopefully) always work.

https://github.com/onnx/onnx-docker/blob/master/onnx-base/Dockerfile

You can build the dependencies from there. Alternatively, you can download protobuf==3.9 and protobuf-compiler through PyPi.
