### ISSUE TITLE
When are you planning to release windows binaries to conda-forge?

### ISSUE THREAD

**Issue by AlbertSadovnikov** [onnx/onnx#2612]
Readme says:
A binary build of ONNX is available from Conda, in conda-forge:
conda install -c conda-forge onnx

And if you check 
https://anaconda.org/conda-forge/onnx
windows version is ancient 1.1.1

And when you try to build via pip - you end up patching and hacking.

**Comment by prasanthpul** [comment]
@chinhuang007 please address

**Comment by chinhuang007** [comment]
We are currently working on the next release 1.7 and will share the projected date shortly.

**Comment by chinhuang007** [comment]
Should be addressed in the upcoming release, https://github.com/onnx/onnx/issues/2614

**Comment by chinhuang007** [comment]
As we found out during the 1.7 release process, conda-forge publish pipeline is not functional. The enablement of conda-forge deployment will be a post-1.7 task owned by the ArchInfra SIG.

**Comment by jcwchen** [comment]
HI @AlbertSadovnikov,
ONNX conda-forge package (1.7.0) is now available on Windows: https://anaconda.org/conda-forge/onnx
Please check whether it is compatible with your usage. Thank you!

**Comment by jcwchen** [comment]
Closed for now. Reopen it if you still bump into error with the latest conda-forge package on Windows. Thanks.
