### ISSUE TITLE
Shape inference for Slice with param dim is incorrect

### ISSUE THREAD

**Issue by yufenglee** [onnx/onnx#2619]
For example, for a Slice with inputs: 
data: with shape [batch, seq_len, 768], 
starts: [0, 0, 0]
ends: [2147483647, 1, 2147483647]
axes: [0, 1, 2]
The inferenced output shape is [batch, seq_len, 768], but the expected is [batch, 1, 768].

**Comment by pranavsharma** [comment]
@linkerzhang FYI. We should fix this before the ONNX 1.7 release as it affects Bing.

**Comment by linkerzhang** [comment]
thanks for finding out the issue. do you want to create a PR for the fix?

**Comment by pranavsharma** [comment]
This was fixed earlier this year https://github.com/onnx/onnx/commit/0e718913011ec574263f46286237ebe47fe46581#diff-f24e7f9545820de198f21ac7c7d37d10 .
