### ISSUE TITLE
parity with xgboost json serialization ?

### ISSUE THREAD

**Issue by sandys** [onnx/onnx#2621]
xgboost 1.0 is officially switching to a new json format for serialization.

https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html?highlight=json

as per github, the primary reason for not using something like ONNX is 

> we wanted to be able to save a “complete snapshot” of XGBoost objects. ONNX only saves the trees so is not a substitute for this use case.

the JSON schema docs are here - https://xgboost-json-schema.readthedocs.io/en/latest/
and a minimal example of the json is https://xgboost-json-schema.readthedocs.io/en/latest/#example

wanted to quickly check if ONNX plans to add the capability to be at par with the xgboost JSON schema ? this obviously ties into future plans of ONNX.

**Comment by linkerzhang** [comment]
Are you saying "xgboost object" can't be represented with ONNX existing format design (onnx-ml.proto) or "xgboost object" can't be represented with protobuf (instead of json) which onnx is using.

**Comment by sandys** [comment]
I'm specifically talking about ONNX format.

Because the whole advantage is being able to leverage all the other tooling
around ONNX (including the new model serving,etc)

**Comment by linkerzhang** [comment]
Make sense as there shouldn't be any big difference about representation capability between protobuf and json.

To answer your original question, I don't think ONNX has the plan to cover full xgboost schema right now. However, ONNX is fully open, design proposals and engineering commitments are very welcome.

Back to using ONNX format (onnx-ml.proto) to represent xgboost object/models, I would suggest starting from a small model list (some trees for example), to see whether it's a good idea to extend ONNX doing that and how (extending the format or extending the ops/functions)

@gramalingam as FYI.
