### ISSUE TITLE
[CI] Check backend tests have been generated

### ISSUE THREAD

**Issue by TMVector** [onnx/onnx#2629]
### Problem
It's currently easy to merge a PR with missing or out-of-date backend test files.

CI can find issues if those files are present, particularly for functions, where the expanded graph can fail the checker or shape inference, exposing bugs in the body definition. (e.g. #2607 #2623)

### Suggested resolution
It would be good to check in CI: generate backend test data & models and compare with what's checked into git.

### Questions
It's worth noting that model files can have older IR and opset versions, but running [`tools/update_doc.sh`](https://github.com/onnx/onnx/blob/master/tools/update_doc.sh) generates the same files with newer versions.
⇒ _Question: presumably we want to keep these older versions the same -- should we change the python that generates them to explicitly set the versions? Atm it seems like a manual process of choosing which of the many changed files should actually be added to git._

**Comment by linkerzhang** [comment]
@TMVector I'm viewing this issue created to track the work items you're interested in and going to work on :).

Indeed, adding CI to check the files is a great idea, given you're helping creating two PRs to generate the test data which were missed in previous PRs. Thank you!
