### ISSUE TITLE
Convert to ONNX from libtorch

### ISSUE THREAD

**Issue by VitaMusic** [onnx/onnx#2634]
Hello, 
I'd like to know about the support of libtorch project by ONNX.
more precisely I need to convert the models created in libtorch into ONNX format.
this option seems is not implemented in libtorch library yet.
I'd like to know if in onnx roadmap there is the plan to develop this option in near future.
I'm not only person who needs this important option. Thank you for your feedback.

**Comment by linkerzhang** [comment]
This issue should go to "libtorch" instead of onnx. ONNX is only defining a spec (model format + operator sets), while partners working on different support, say, training/predicting onnx model, xxx->onnx conversion etc.

**Comment by ebarsoum** [comment]
@VitaMusic please open an issue in PyTorch.

PyTorch already support ONNX. Can you serialize your libtorch model and loaded in PyTorch, then export it to ONNX?

**Comment by henbucuoshanghai** [comment]
same question
