### ISSUE TITLE
"This is an invalid model" error related to float type and Equal operator

### ISSUE THREAD

**Issue by jbmaxwell** [onnx/onnx#2636]
I've converted the Huggingface DistilBert model to CoreML, via ONNX, and I noticed that the predictions between PyTorch and CoreML were different. Using onnxruntime to validate the ONNX converted model, I get this error: 
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (115) of operator (Equal) in node () is invalid.
```
Opening the model in Netron, and searching for `115` reveals multiple connections between a `ConstantOfShape` node and several `Equal` nodes. Is there any simple solution to this? Presumably the `Equal` operator can't take `float` inputs (which seems reasonable), but I'm honestly not sure what the `ConstantOfShape` is, or how I might be able to fix the problem. 

At this stage I'm only assuming this is the cause of the difference in predictions between PyTorch and CoreML, but that seems reasonable, to me. (Or rather, having an ONNX conversion that validates against PyTorch seems like a good first step in debugging.)

UPDATE: Stepping through my validation code, I'm noticing that the model passes `onnx.checker.check_model()`... The error given above is reported by `onnxruntime.InferenceSession()`. (I can report at onnxruntime, just in case the issue is on their side.)

**Comment by linkerzhang** [comment]
Equal op starts to support "float" since operator set version 11.

Please help to check your model which operator set version it is using. if it's using a version < 11, then the onnx-checker has a bug, it should also fail, otherwise, the onnx runtime has a bug.

**Comment by jbmaxwell** [comment]
Hi @linkerzhang, the model reports opset v9 (in Netron). I've double-checked my Pytorch install, and I am on PyTorch 1.4, so I'm not sure why the converted model indicates v9. It also reports Pytorch 1.3. So the model passes the `onnx.checker.check_model()`, but perhaps because it thinks the model is v9?

**Comment by linkerzhang** [comment]
yes, if the model is saying using operator set version 9, then ORT (ONNX runtime) is doing the right thing, while onnx-checker is doing not good (coverage is not enough).

**Comment by jbmaxwell** [comment]
Hello @spandantiwari, any thoughts about where the problem might be originating for the above issue? I'm on Ubuntu 18.04, PyTorch 1.4, and my converted model indicates `onnx v4, Pytorch 1.3, ai.onnx v9` in Netron ("Model Properties").

**Comment by jbmaxwell** [comment]
Since I couldn't see any good reason for the discrepancy, I decided to manually set `opset_version=11` in my `torch.onnx.export()` call. Testing the model with `onnxruntime` now completes successfully.

**Comment by jbmaxwell** [comment]
I've just discovered that, if I use `opset_version=11`, the model validates using `onnxruntime` but `onnx-coreml` fails with: `NotImplementedError: Unsupported ONNX ops of type: Range`. Checking the ONNX convert log there is clearly a `Range` function added to the model that isn't there with opset v9. Any thoughts as to why this might be, and any possible workarounds?

**Comment by jbmaxwell** [comment]
Here are two exports, with v9 and v11, of the same distilbert model in Netron. You can see that the v11 version (left) includes `Range` and handles input 116 quite differently.

![v9_vs_v11](https://user-images.githubusercontent.com/15166432/75903017-cadbe200-5df5-11ea-9bcb-28903c839064.png)

If it's helpful I can upload the `.onnx` files.

**Comment by linkerzhang** [comment]
with using opset 11, do you get the expected inference result with onnx runtime? if yes, then the failure may be due to onnx-coreml support is not enough. onnx-coreml was created by apple, you may reach out to them to understand more, whether the onnx-coreml is up to date, for example.
