### ISSUE TITLE
Is there a way to remove a layer from onnx model ?

### ISSUE THREAD

**Issue by yncxcw** [onnx/onnx#2638]
Hey. this is the onnx model that converted from a keras model:

```
graph model_1 (
  %input_1[FLOAT, 10x32]
) initializers (
  %dense_2/kernel:0[FLOAT, 16x16]
  %dense_2/bias:0[FLOAT, 16]
  %dense_1/kernel:0[FLOAT, 32x16]
  %dense_1/bias:0[FLOAT, 16]
  %TFNodes/Const:0[FLOAT, 10x32]
) {
  %transformed_tensor1 = MatMul(%TFNodes/Const:0, %dense_1/kernel:0)
  %biased_tensor_name1 = Add(%transformed_tensor1, %dense_1/bias:0)
  %dense_1/Softmax:0 = Softmax[axis = -1](%biased_tensor_name1)
  %transformed_tensor = MatMul(%dense_1/Softmax:0, %dense_2/kernel:0)
  %biased_tensor_name = Add(%transformed_tensor, %dense_2/bias:0)
  %dense_2/Softmax:01 = Softmax[axis = -1](%biased_tensor_name)
  %dense_2/Softmax:0 = Identity(%dense_2/Softmax:01)
  %Const:0 = Identity(%input_1)
  return %dense_2/Softmax:0
}
```

Somehow the onnx just adds layer, `%Const:0 = Identity(%input_1)`, which leads to a new node, ` %TFNodes/Const:0[FLOAT, 10x32]`. Is there anyway I can remove this layer ?

Code for how I built the mode:
```
data = np.random.random_sample(data_shape)
tensor_data = tf.convert_to_tensor(data, np.float32)
 x = keras.Input(tensor=tensor_data)
 y = keras.layers.Dense(16, activation='softmax')(x)
 z = keras.layers.Dense(16, activation='softmax')(y)

model = keras.Model(x, z)
```

Appreciate for any help.

**Comment by cjermain** [comment]
@yncxcw, there are a few ways to solve this.
1. If you are using [keras2onnx](https://github.com/onnx/keras-onnx/), then I would suggest raising an issue there. I've also noticed that `Identity` nodes are created for inputs when they are unnecessary.
2. If you want to edit your own graph directly, you can use the [ONNX Python API](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md). You can copy the nodes from your original model (e.g. `onnx_model.graph.node`), and use them to [make a new graph](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#creating-an-onnx-model-using-helper-functions) after removing the Identity node.

**Comment by ZhangGe6** [comment]
The tool [onnx-modifier](https://github.com/ZhangGe6/onnx-modifier) can serve as an alternative 🚀 . It can help us edit and preview the editing effect in a total visualization fashion, and aims at a more intuitive and efficient ONNX editing, compared with the programmatical way.
