### ISSUE TITLE
ONNX InferenceContext implementation triggers segfault failures

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#2647]
https://github.com/onnx/onnx/blob/master/onnx/shape_inference/implementation.h#L91

ONNX type and shape InferenceContext implementation sets all types as nullptr by default if not manually set, and, current shape inference functions implemented do not check "nullptr" accordingly, with these two, using ONNX package to run inference (type and shape) will sometimes have segfault failures (nullptr exception).

This needs to be fixed by either updating the implementation to make it never have nullptr, or fix all shape inference functions to check that, for example, https://github.com/onnx/onnx/blob/master/onnx/defs/generator/defs.cc#L234 needs checking the input type to ensure it's not nullptr.

**Comment by faxu** [comment]
@linkerzhang are you working on or planning a PR for this?

**Comment by shubhambhokare1** [comment]
https://github.com/onnx/onnx/pull/2946
gets rid of a possible segfault issue in 
https://github.com/onnx/onnx/blob/master/onnx/defs/generator/defs.cc#L234
