### ISSUE TITLE
A question with aten::topk

### ISSUE THREAD

**Issue by ligonzheng** [onnx/onnx#2648]
Hello, 
I have a pytorch model about beam search. When I trid to convert the pytorch model to onnx, a error was happen :
RuntimeError: hasSpecialCase INTERNAL ASSERT FAILED at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300, please report a bug to PyTorch. We don't have an op for aten::topk but it isn't a special case. (analyzeImpl at /pytorch/torch/csrc/jit/passes/alias_analysis.cpp:300).
As we konw ,topk has already been supported by onnx, But why it failed to convert ?
torch version is 1.4.0 
onnx verson  is 1.6.0
Anyone give me some advise ? Thank you in advance.

**Comment by ligonzheng** [comment]
I had figure it out by myself. The reason is this:
There are two style to use torch.topk. 
One is like :
 res, value = torch.topk(input, k).
 Another is like : 
 torch.topk(input, k, out = (res, value)).
I had test that only the first way is OK when convert the pytorch model to onnx.

**Comment by manhongnie** [comment]
@ligonzheng  Hello, brother, if the topk of my onnx model is broken, do you know how to redefine the topk node?
