### ISSUE TITLE
Shape inference doesn't use initializer shapes

### ISSUE THREAD

**Issue by TMVector** [onnx/onnx#2655]
### Issue description
It looks like shape inference doesn't make use of initializer shapes, so even super simple graphs can fail to gain any useful info from shape inference.

I suppose one caveat should be that shape inference shouldn't rely on initializers which are also inputs, since their shape could definitely change at runtime.

### MRE
Run shape inference with the exact same model, but with and without adding explicit value info for the initializer.

<details>

```python
model = onnx.helper.make_model(onnx.helper.make_graph(
    nodes=[
        onnx.helper.make_node("Gemm", ["x", "m"], ["y"]),
        onnx.helper.make_node("Identity", ["y"], ["z"]),
    ],
    name="graph1",
    inputs=[
        onnx.helper.make_tensor_value_info("x", onnx.TensorProto.FLOAT, ["dim1",7]),
    ],
    outputs=[
        onnx.helper.make_tensor_value_info("z", onnx.TensorProto.FLOAT, ["dim2",13]),
    ],
    initializer=[
        onnx.numpy_helper.from_array(np.zeros((7,13), dtype=np.float32), name="m"),
    ],
    value_info=[
    ],
))
```
**Without explicit value info for initializer `m`**
```
>>> onnx.shape_inference.infer_shapes(model).graph.value_info
[name: "y"
type {
  tensor_type {
    elem_type: 1
  }
}
]
```
**_With_ explicit value info for initializer `m`**
```
>>> model.graph.value_info.extend([onnx.helper.make_tensor_value_info("m", onnx.TensorProto.FLOAT, [7,13])])
>>> onnx.shape_inference.infer_shapes(model).graph.value_info
[name: "m"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 7
      }
      dim {
        dim_value: 13
      }
    }
  }
}
, name: "y"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "dim1"
      }
      dim {
        dim_value: 13
      }
    }
  }
}
]
```

</details>

**Comment by linkerzhang** [comment]
there might be a gap of not using initializer when doing shape inference, though, in terms of interface design, we do have getInputData in InferenceContext to support shape inference with known input data (before running model).

**Comment by jcwchen** [comment]
It should be resolved by https://github.com/onnx/onnx/pull/2901. Please reopen it if you still encounter this issue. Thanks.
