### ISSUE TITLE
Get the input and output node name from onnx model

### ISSUE THREAD

**Issue by chiehpower** [onnx/onnx#2657]
Hi all, 
Is there any tool or method which can let us rapidly know the input/ output node names of onnx model?
Because I know there are some good tools which can analyze for TensorFlow pb model such as saved_model_cli or summarize graph. It can not only know the input/ output node names but also output this model uses what total operations are.

I really need to confirm the input and output node names when I get a onnx model which is not generated by myself. 
BTW I already knew the netron this awesome tool. :))

If you have any idea, I will be grateful for any help you can provide.
Thank you!

**Comment by austingg** [comment]
```python
model = onnx.load('xxx.onnx')
output = model.graph.output

input_all = model.graph.input
input_initializer = model.graph.initializer
net_feed_input = set(input_all)  - (input_initializer)

```

**Comment by chiehpower** [comment]
> ```python
> model = onnx.load('xxx.onnx')
> output = model.graph.output
> 
> input_all = model.graph.input
> input_initializer = model.graph.initializer
> net_feed_input = set(input_all)  - (input_initializer)
> ```

Hi @austingg,

Thanks for your reply!!
After I used your code, I got this error message.
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    net_feed_input = set(input_all)  - (input_initializer)
TypeError: unhashable type: 'ValueInfoProto'
```

**Comment by gabrielibagon** [comment]
@chiehpower, if you haven't resolved this already, simply extracting the `name` attribute of each node in `input_all` and `input_initializer` resolves that error, and returns the input and output node names.

Solution:
```
model = onnx.load('xxx.onnx')
output =[node.name for node in model.graph.output]

input_all = [node.name for node in model.graph.input]
input_initializer =  [node.name for node in model.graph.initializer]
net_feed_input = list(set(input_all)  - set(input_initializer))

print('Inputs: ', net_feed_input)
print('Outputs: ', output)
```

**Comment by chiehpower** [comment]
> @chiehpower, if you haven't resolved this already, simply extracting the `name` attribute of each node in `input_all` and `input_initializer` resolves this error.
> 
> Solution:
> 
> ```
> model = onnx.load('xxx.onnx')
> output =[node.name for node in model.graph.output]
> 
> input_all = [node.name for node in model.graph.input]
> input_initializer =  [node.name for node in model.graph.initializer]
> net_feed_input = list(set(input_all)  - set(input_initializer))
> 
> print('Inputs: ', net_feed_input)
> print('Outputs: ', output)
> ```

Hi @gabrielibagon,

Thanks for your sharing!!
It is really useful for me. :)

**Comment by jayarams79** [comment]
Hi,
I am getting the output as,
Inputs:  ['3:0', '2:0', '1:0']
Outputs:  ['log_probabilities', 'logits', 'predictions', 'probabilities']

is inputs is input name ?.
Thanks,
SJ

**Comment by chiehpower** [comment]
> Hi,
> I am getting the output as,
> Inputs: ['3:0', '2:0', '1:0']
> Outputs: ['log_probabilities', 'logits', 'predictions', 'probabilities']
> 
> is inputs is input name ?.
> Thanks,
> SJ

I think it is possible! You can also check your model on Netron.
