### ISSUE TITLE
outputs are different between ONNX and pytorch

### ISSUE THREAD

**Issue by mdztravelling** [onnx/onnx#2662]
I export a pytorch model to onnx and there are not any errors, but the outputs are different when doing inference use same inputs. What is possible solution ?
```
pytorch output:  [-10.975916   -8.120772   -3.1923165 ... -10.976107  -11.38656272   -2.362452 ]
onnx output: [ -9.995668  -4.854749  -3.230622 ...  -9.998256 -10.756512  -3.699711]
```
pytorch model , network and script (export onnx ) in this repo  [https://github.com/mdztravelling/ASR](https://github.com/mdztravelling/ASR)
convert log in https://github.com/mdztravelling/ASR/blob/master/log.txt

- pytorch version: 1.3.0

- OS (e.g., Linux): CentOS 6.3

- Python version: 3.6.5

- onnx opset version: 10

- CUDA/cuDNN version: 10.0/7.4

**Comment by linkerzhang** [comment]
how do you run the exported onnx model? using ONNX runtime?

**Comment by mdztravelling** [comment]
> how do you run the exported onnx model? using ONNX runtime?

yes, I use onnxruntime in tensorrt inference server.

**Comment by linkerzhang** [comment]
@mdztravelling thanks for confirmation. you may move this issue to either pytorch community (pytorch->onnx exporter experts there) or ONNX runtime community (onnx runtime experts there) can help to debug more on the issue (either a conversion issue or an inference running gap).

**Comment by sawyer7246** [comment]
> > how do you run the exported onnx model? using ONNX runtime?
> 
> yes, I use onnxruntime in tensorrt inference server.

I have the same issue, any further solutions?

**Comment by ValerianGonnot** [comment]
Same issue with Pytorch 1.5.1

**Comment by HaoYang0123** [comment]
I also have this problem, I guess it will be related with the if-else in pytorch model?
This is the warning when I run my script: "TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!"

**Comment by Zhang-O** [comment]
add model.eval（） before model.inference()

**Comment by rwickman** [comment]
This is still a problem...

**Comment by lizezheng** [comment]
pytorch1.10.0 same issue.
