### ISSUE TITLE
DCN is supported in frameworks time to add it to ONNX ?

### ISSUE THREAD

**Issue by YumainOB** [onnx/onnx#2665]
As posted by @vlordier in the too quickly closed issue #2395 (IMHO), DCN is now a well supported feature in various frameworks. Maybe time has come to add this feature to ONNX? Is there a plan to have it in future releases?

> But to generate it in ONNX it need to be converted from someplace. If this cause a massive accuracy gain, why no framework implemented it naively? Especially, this was published 2 years ago. To add an OP in ONNX, it needs to be available in one framework at least.

@ebarsoum Deformable Convolutions are also used to process equirectangular projections of omnidirectional images by parametrising the convolution kernel

![74554848-5fb79200-4f52-11ea-9862-8f86c4a097fb](https://user-images.githubusercontent.com/5443125/75030134-62a70b00-549b-11ea-8ee0-15f9f69cdc39.png)

More recent work [Kernel Transformer Networks for Compact Spherical Convolution](https://arxiv.org/pdf/1812.03115.pdf) 

[Distortion-Aware Convolutional Filters for Dense
Prediction in Panoramic Images](http://campar.in.tum.de/pub/tateno2018eccv/tateno2018eccv.pdf
)

or [Corners for Layout: End-to-End Layout Recovery from 360 Images](https://arxiv.org/pdf/1903.08094.pdf)

_Originally posted by @vlordier in https://github.com/onnx/onnx/issues/2395#issuecomment-589613934_

**Comment by linkerzhang** [comment]
are you interested in proposing op definitions PRs needed for it?

**Comment by YumainOB** [comment]
Thanks for your reply @linkerzhang 
As I am not an expert in ONNX  (just a basic user in facts), it maybe quite long if I do this proposal and may results in inaccurate and inefficient solution. Maybe someone with better knowledge of the ONNX project would be better suited for this proposal?

**Comment by Zha0q1** [comment]
I am also interested in this op. Is anyone moving this forward at the moment?

**Comment by hyperfraise** [comment]
Also very interested

**Comment by marcown** [comment]
Any news on DCN for onnx?

**Comment by daixiangzi** [comment]
I find baidu:https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/op_list.md support DCN to onnx

**Comment by Zha0q1** [comment]
> I find baidu:https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/op_list.md support DCN to onnx

but how 🤔

**Comment by daixiangzi** [comment]
use Baidu paddle to train model and convert onnx



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoqi ***@***.***&gt;; 
发送时间: 2021年4月28日(星期三) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [onnx/onnx] DCN is supported in frameworks time to add it to ONNX ? (#2665)





  
I find baidu:https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/op_list.md support DCN to onnx
  
but how 🤔

**Comment by Zha0q1** [comment]
> use Baidu paddle to train model and convert onnx
> 
> 
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人: "Zhaoqi ***@***.***&gt;; 
> 
> 发送时间: 2021年4月28日(星期三) 下午3:29
> 
> 收件人: ***@***.***&gt;; 
> 
> 抄送: ***@***.***&gt;; ***@***.***&gt;; 
> 
> 主题: Re: [onnx/onnx] DCN is supported in frameworks time to add it to ONNX ? (#2665)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>   
> 
> I find baidu:https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/op_list.md support DCN to onnx
> 
>   
> 
> but how 🤔
> 
>  
> 
> —
> 
> You are receiving this because you commented.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

right, but since there is no dch op in onnx what would it translate to

**Comment by daixiangzi** [comment]
error



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoqi ***@***.***&gt;; 
发送时间: 2021年4月28日(星期三) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [onnx/onnx] DCN is supported in frameworks time to add it to ONNX ? (#2665)





  
use Baidu paddle to train model and convert onnx
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人: "Zhaoqi @.***&gt;;
 
发送时间: 2021年4月28日(星期三) 下午3:29
 
收件人: @.***&gt;;
 
抄送: @.&gt;; @.&gt;;
 
主题: Re: [onnx/onnx] DCN is supported in frameworks time to add it to ONNX ? (#2665)
 
I find baidu:https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/op_list.md support DCN to onnx
 
but how 🤔
 
—
 
You are receiving this because you commented.
 
Reply to this email directly, view it on GitHub, or unsubscribe.
  
right, but since there is no dch op in onnx what would it translate to

**Comment by leifengsoul** [comment]
> Any news on DCN for onnx?

The same question. How to convert DCN to ONNX?

**Comment by hyperfraise** [comment]
I believe this is still relevant.

**Comment by allen20200111** [comment]
RuntimeError: ONNX export failed: Couldn't export Python operator ModulatedDeformConvFunction

**Comment by allen20200111** [comment]
why not support for microsoft ?

**Comment by JoshvirN** [comment]
This feature is still relevant. What is the. blocker in pushing this forward?
