### ISSUE TITLE
Model inference - LSTM dynamic inputs

### ISSUE THREAD

**Issue by jamesethatcher** [onnx/onnx#2672]
I'm trying to load an LSTM model in onnx for inference, here is my code:

```
import onnxruntime as ort

so = ort.SessionOptions()
so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
sess = ort.InferenceSession('test/model.onnx', so)

input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name

with open('torchtext.json') as f:
    TEXT = jsonpickle.loads(f.read())

sample_text = "testing model inference"
processed = TEXT.process(([TEXT.preprocess(sample_text)]))
result = sess.run([output_name], {input_name: processed.numpy()})
```

I'm currently getting an error `INVALID_ARGUMENT : Got invalid dimensions for input: input.1 for the following indices
 index: 1 Got: 3 Expected: 731`

I'm assuming the appropriate action is to pad the sequences to 1x731, or are dynamic inputs supported?

Thanks.

**Comment by askhade** [comment]
It depends on your model. If the input shape info does not have symbolic dimension for example [1, 3, 512, 512] then all inputs are expected to have this shape ... however if your input shape has symbolic dims like [N, 3, 512, 512] then N can vary
