### ISSUE TITLE
Converting model using opset 11 to opset 9

### ISSUE THREAD

**Issue by rkpandya** [onnx/onnx#2673]
onnx version 1.6.0
torch version 1.4.0

    converted_model = version_converter.convert_version(original_model, 9)
  File "/cluster/home/pandyar1/env/lib/python3.7/site-packages/onnx/version_converter.py", line 166, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /io/onnx/onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For Conv

**Comment by askhade** [comment]
@rkpandya : PR https://github.com/onnx/onnx/pull/2664 should fix this issue.
