### ISSUE TITLE
fuse_bn_into_conv optimizer in pypi linux wheels is wrong

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#2677]
Reference: https://github.com/daquexian/onnx-simplifier/issues/50

[Here](https://drive.google.com/drive/folders/1TjkfG0IWf9euPGQcvn6VgzIi6zIQyMZU?usp=sharing 
) are some onnx models, where `MBV3_SSD_onnx.onnx` is the original model, `mbv3_ssd_onnx_sim_macos.onnx` is the model  after optimizing and [simplifying](https://github.com/daquexian/onnx-simplifier) on **macOS**, `MBV3_SSD_onnx_sim_onnx_16_pip.onnx` is the model after optimizing and simplifying on **ubuntu**. 

The "1523" tensors of the last two models differ a lot, which is caused by the onnx fuse_bn_into_conv optimizer. The tensor in ubuntu model (no matter produced by onnx 1.5 or 1.6) is totally wrong while the macOS version is right. 

However, if I compiled and install onnx from source on ubuntu, the optimized model is correct and the same as that on macOS.

**Comment by askhade** [comment]
@daquexian : Is this still a problem in the latest onnx version?

**Comment by daquexian** [comment]
@askhade yes, I just verified it still exits on onnx 1.7.0 installed by `pip3 install onnx==1.7.0` on linux. what's more, if I installed onnx by `pip3 install onnx==1.7.0 --no-binary onnx` (which build onnx from source instead of installing the prebuilt binary), the problem disappears

**Comment by daquexian** [comment]
I believe it has been fixed by #3004
