### ISSUE TITLE
onnx model output same result

### ISSUE THREAD

**Issue by alicera** [onnx/onnx#2681]
https://github.com/KaiyangZhou/deep-person-reid

I export the onnx and the onnx result have the same result with two different images
I engine twice, the result is always same
output_data  = engine.run(img)
output_data2 = engine.run(img2)

**Comment by askhade** [comment]
@alicera if this is still an issue then please open a new one with more details (using the new issue template should help you understand what info is needed for someone from the community to be able to help you better)
