### ISSUE TITLE
NameError: name 'expect' is not defined

### ISSUE THREAD

**Issue by tiru1930** [onnx/onnx#2686]
`>>> import onnx
>>> node = onnx.helper.make_node(
...     'Abs',
...     inputs=['x'],
...     outputs=['y'],
... )
>>> import numpy as np
>>> x = np.random.randn(3, 4, 5).astype(np.float32)
>>> y = abs(x)
>>> 
>>> expect(node, inputs=[x], outputs=[y],
...        name='test_abs')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'expect' is not defined
>>> dir(onnx)
['Any', 'AttributeProto', 'DESCRIPTOR', 'EXPERIMENTAL', 'FunctionProto', 'GraphProto', 'IO', 'IR_VERSION', 'IR_VERSION_2017_10_10', 'IR_VERSION_2017_10_30', 'IR_VERSION_2017_11_3', 'IR_VERSION_2019_1_22', 'IR_VERSION_2019_3_18', 'ModelProto', 'NodeProto', 'ONNX_ML', 'OperatorProto', 'OperatorSetIdProto', 'OperatorSetProto', 'OperatorStatus', 'Optional', 'STABLE', 'SparseTensorProto', 'StringStringEntryProto', 'TensorAnnotation', 'TensorProto', 'TensorShapeProto', 'Text', 'TypeProto', 'TypeVar', 'Union', 'ValueInfoProto', 'Version', '_Proto', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_deserialize', '_get_file_path', '_load_bytes', '_save_bytes', '_serialize', 'absolute_import', 'cast', 'checker', 'defs', 'descriptor_pb2', 'division', 'enum_type_wrapper', 'external_data_helper', 'google', 'helper', 'load', 'load_external_data_for_model', 'load_from_string', 'load_model', 'load_model_from_string', 'load_tensor', 'load_tensor_from_string', 'mapping', 'onnx', 'onnx_ONNX_REL_1_6_ml_pb2', 'onnx_cpp2py_export', 'onnx_operators_ONNX_REL_1_6_ml_pb2', 'onnx_operators_pb', 'onnx_pb', 'os', 'print_function', 'save', 'save_model', 'save_tensor', 'string_types', 'sys', 'unicode_literals', 'version', 'write_external_data_tensors']`

**Comment by faxu** [comment]
what are you trying to do? please refer to the onnx python API documentation: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md

**Comment by ytaous** [comment]
This would work in case anyone interested:
>>> from onnx.backend.test.case.node import expect
>>> expect(node, inputs=[x], outputs=[y],
...        name='test_abs')
