### ISSUE TITLE
IndexError: _Map_base::at occured when export mmdetection carafe op

### ISSUE THREAD

**Issue by ghost** [onnx/onnx#2698]
Hi,
I was trying to export custom carafe op in mmdetection using a very simple net:
```python
feat_size = 16
in_channel = 128
scale_factor = 2
out_channel = 256
kernel_size = 3
batch = 2
feat = torch. randn(batch, in_channel, feat_size, feat_size,  device="cuda")
onnx_model_name = "model.onnx"

import torch.nn as nn
import torch.nn.functional as F
from mmdet.ops.carafe import CARAFEPack as Carafe

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channel, out_channel, kernel_size, padding=(1, 1))
        self.carafe = Carafe(out_channel, scale_factor)
    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.carafe(x)
        return x
model = Net().to("cuda")
output = model(feat)                   # I can get correct result here
torch.onnx.export(model, feat, onnx_model_name, verbose=True,
                             keep_initializers_as_inputs=True) # But got an error when export to ONNX model
```
Error message:
IndexError: _Map_base::at

mmdetection is here:
https://github.com/open-mmlab/mmdetection
I know that as a custom op, I need to register the Carafe op using symbolic method in autograd.Function definition. But the error seems to occur during forward run of the model in the trace mode. 

I used Pytorch1.4 built from source.

**Comment by spandantiwari** [comment]
@ghost - please note that only native PyTorch ops are supported in ONNX exporter. I don't believe that Carafe ops will be supported, unless they are implemented using native torch.* ops. I would recommend trying to remove/replace those ops and seeing if the export goes through. And please share a specific repro if you see any issue.
