### ISSUE TITLE
 _importer_ctx.tensors().at(output.name()).is_tensor()

### ISSUE THREAD

**Issue by daixiangzi** [onnx/onnx#2699]
output: "preds_size"
op_type: "Constant"
attribute {
  name: "value"
  t {
    dims: 1
    data_type: INT32
    raw_data: ")\000\000\000"
  }
  type: TENSOR
}

--- End node ---
ERROR: ModelImporter.cpp:492 In function importModel:
[7] Assertion failed: _importer_ctx.tensors().at(output.name()).is_tensor()

pytorch :
#preds.size(0) isc constant
 preds_size = torch.IntTensor([preds.size(0)])

**Comment by askhade** [comment]
@daixiangzi : If this is still an issue please use the latest issue template to create a new template and add all the info stated in the template. Thanks!
