### ISSUE TITLE
Cannot obtain output tensor shape after making conv node

### ISSUE THREAD

**Issue by baynaa7** [onnx/onnx#2702]
Hello, I have a problem.
I'm trying to obtain output tensor shape after making conv node in onnx. In tensorflow, we can easily obtain the output shape information just giving input, weight and parameters. However, as I understand, to make conv node in onnx, we need input, weight, parameters and output tensor information which are all precalculated, then we can make conv node. After that we can use shape inference for checking the shapes. So, my questions are in the following.
1. How to obtain output tensor shape just with input, weight tensor and convolution parameters?
2. From where can I obtain shape inference code that actually calculates the output tensor shape?

Thank you,

**Comment by askhade** [comment]
@baynaa7 : Are you constructing the model from scratch in onnx?

**Comment by baynaa7** [comment]
@askhade Yes, I am.
