### ISSUE TITLE
Shape Inference Failure with Negative Axis Value in Flatten Op

### ISSUE THREAD

**Issue by dibya001** [onnx/onnx#2708]
Onnx Version: 1.6.0

**Comment by linkerzhang** [comment]
do you want to try to send out a fix https://github.com/onnx/onnx/blob/674438c0c01102dd6f726c9e2a38d6738d61f398/onnx/defs/nn/defs.cc#L1916? :)

**Comment by askhade** [comment]
can you add more details... how to repro this etc...
