### ISSUE TITLE
Einsum shape inference logic won't handle trailing scalars in the equation

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#2712]
As an illustrative example, an Einsum equation: 'i,->i' is a valid element-wise multiplication of the first operand with a the second operand (a scalar),. The parsing logic will skip the trailing empty string as it has logic thus which prevents processing the last empty substring after ',':

https://github.com/onnx/onnx/blob/6bdac246617682f9696f0dac40362ef4f4de2cde/onnx/defs/math/defs.cc#L2181

**Comment by linkerzhang** [comment]
#2713 should fix the issue, please review.

**Comment by hariharans29** [comment]
Thanks Ke, reviewed it
