### ISSUE TITLE
remove identity failed

### ISSUE THREAD

**Issue by KingerFzb** [onnx/onnx#2715]
`import onnx
from onnx import optimizer
import keras2onnx
from keras.models import load_model
import onnxmltools

model = load_model('mobile_allgraph_v1.h5',compile=False)

onnx_model = onnxmltools.convert_keras(model,model.name)
#去掉identity层
all_passes = optimizer.get_available_passes()
print("Available optimization passes:")
for p in all_passes:
    print('\t{}'.format(p))

onnx_optimized = 'mobilenet_optimized.onnx'
passes = ['eliminate_identity']
optimized_model = optimizer.optimize(onnx_model, passes)
onnx.save(optimized_model, onnx_optimized)
`
I try to remove the identity,but faild
![Uploading image.png…]()

`Traceback (most recent call last):
  File "modify_onnx.py", line 18, in <module>
    optimized_model = optimizer.optimize(onnx_model, passes)
  File "D:\Anaconda3\envs\tensorflow36\lib\site-packages\onnx\optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: invalid unordered_map<K, T> key`

**Comment by jiafatom** [comment]
For keras2onnx conversion, you can directly use [repo](https://github.com/onnx/keras-onnx/). Currently you use the conversion from onnxmltools which is a wrapper of keras2onnx. Anyway it will do full optimization for you. The onnx optimizer is not actively developed now.

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have questions related to the optimizer, please raise an issue there. Thank you!
