### ISSUE TITLE
request for HardSwish

### ISSUE THREAD

**Issue by haifenghan** [onnx/onnx#2728]
HardSwish is an important activation function in MobileNetV3.
I see the TensorFlow lite has added it as an operator.
Could ONNX add it into the new opset?

**Comment by linkerzhang** [comment]
do you want to propose a PR for it?

**Comment by linkerzhang** [comment]
and also, with this op, will you have a MobileNetV3 model in onnx format so that it may be contributed into the model zoo? thank you!

**Comment by haifenghan** [comment]
OK. Let me try to generate a MobileNetV3 model in onnx format.
BTW, could you guide me about how to file a ONNX PR?

**Comment by linkerzhang** [comment]
Thank you! @haifenghan .

For proposing a new OP to ONNX, please refer to https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md.

For contributing new models into ONNX model zoo,  @vinitra may offer some guidance please.

**Comment by vinitra** [comment]
Hi @haifenghan! You can submit a new model by creating a PR and filling out the default pull request template in the onnx/models repository. More details on the information needed are included here: https://github.com/onnx/models/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by glenn-jocher** [comment]
Any progress on adding hardswish support? Exporting from nn.Hardswish() in pytorch 1.6 produces an error now with onnx 1.7 in our YOLOv5 repo:
https://github.com/ultralytics/yolov5
```python
ONNX export failure: Exporting the operator hardswish to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

**Comment by askhade** [comment]
@ebarsoum @postrational fyi

**Comment by wschin** [comment]
Is the requested `HardSwish` the same as the one in https://paperswithcode.com/method/hard-swish? If yes, I guess we can compose it using existing ONNX ops and we don't need a new op.

**Comment by glenn-jocher** [comment]
@wschin yes, hardswish is essentially x * hardsigmoid(x). We are using this as a current workaround with YOLOv5 exports. The main downside is complication of the viewable model (i.e. with netron viewer).

**Comment by glenn-jocher** [comment]
Current hardswish op in onnx using 4 separate operations, repeat about a hundred times in a YOLOv5 model.

```python
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX
```

<img width="876" alt="Screen Shot 2020-09-23 at 10 56 00 AM" src="https://user-images.githubusercontent.com/26833433/94050779-93ca1f80-fd8b-11ea-9a9b-52c2a6701809.png">

**Comment by padmasreenagarajan** [comment]
@glenn-jocher @wschin 
Even for Mobilenetv3, h-swish is repeated multiple times and definitely it needs to be added in the operator set.
When can we expect this addition in onnx?
Thanks in advance!

**Comment by askhade** [comment]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSwish
