### ISSUE TITLE
opset 11: clip issue

### ISSUE THREAD

**Issue by derekwong66** [onnx/onnx#2737]
hi,

I set opset_version = 11, then met this issue. However, I set opset_version=10, no issue reported>

    use_external_data_format=use_external_data_format)
  File "/home/derek/anaconda3/envs/pyt1.5/lib/python3.6/site-packages/torch/onnx/utils.py", line 515, in _export
    _check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: min for operator Clip

==> Context: Bad node spec: input: "1425" output: "1426" name: "Clip_589" op_type: "Clip" attribute { name: "min" f: 1e-12 type: FLOAT }

**Comment by linkerzhang** [comment]
if you check the operator spec, "min" is indeed NOT an attribute of "Clip" op since operator set version 11
