### ISSUE TITLE
convert pytorch model( pytorch_model.pt) to onnx 

### ISSUE THREAD

**Issue by pumpkinband** [onnx/onnx#2757]
i have, PROJECT(folder)
├── pytorch_model.bin
├── bert_config.json
└── vocab.txt

i would like to convert it to `model.onnx`

thanks a lot.

**Comment by TMVector** [comment]
Hi @pumpkinband, you should take a look at the PyTorch docs for exporting to ONNX: https://pytorch.org/docs/stable/onnx.html
You can also ask questions on https://discuss.pytorch.org/

**Comment by pumpkinband** [comment]
So i used this to convert pytorch_model.pt to pytorch_model.onnx

```
from torch.autograd import Variable
import torch.onnx
import torchvision
import torch

dummy_input = Variable(torch.randn(1, 3, 256, 256))
model = torch.load('./pytorch_model.pt')
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")

```
ERROR :- `The expanded size of the tensor (256) must match the existing size (3) at non-singleton dimension 3. Target sizes: [1, 3, 256, 256]. Tensor sizes: [1, 3]`

Are my `dummy_inputs` incorrect ?

**Comment by TMVector** [comment]
Yes, it sounds like it. The data needs to work if you run it in PyTorch, i.e.
```python
dummy_output = model(dummy_input)
```
If you have data you normally run the model with in PyTorch, you could use that.

**Comment by pumpkinband** [comment]
```
from torch.autograd import Variable
import torch.onnx
import torchvision
import torch 

dummy_output = model(dummy_input)
model = torch.load('./pytorch_model.pt')
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")
```

so i used `dummy_output = model(dummy_input)` as you said but i'm still getting the same error

`The expanded size of the tensor (256) must match the existing size (3) at non-singleton dimension 3.  Target sizes: [1, 3, 256, 256].  Tensor sizes: [1, 3]`

please tell me what am i doing wrong !!

**Comment by TMVector** [comment]
@pumpkinband I'm guessing your code is erroring on the line `dummy_output = model(dummy_input)`? What I meant was: the dummy input needs to be _valid_ input.

You need to provide a valid model input from somewhere:
```python
import torch
import torch.onnx

model = torch.load('./pytorch_model.pt')

dummy_input = XXX # You need to provide the correct input here!

# Check it's valid by running the PyTorch model
dummy_output = model(dummy_input)
print("Input is valid")

# If the input is valid, then exporting should work
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")
```

**Comment by pumpkinband** [comment]
Can you please tell how to get valid inputs.
I only have this files :-
Project (folder containing model)
├── pytorch_model.bin
├── bert_config.json
├── vocab.txt
├──model.ckpt-231879.meta
├──model.ckpt-231879.index
└── model.ckpt-231879.data-00000-of-00001

**Comment by TMVector** [comment]
Hi @pumpkinband do you not have any example data? Have you not been able to run your model in PyTorch either? If you don't have any data with which to run the model then why do you want to export to ONNX?

If you have data you use to run the model in PyTorch, then you should use that. Otherwise the best you can do is generate a tensor of the right shape, but I don't know the right shapes -- you'll have to look at your model.

**Comment by pumpkinband** [comment]
i have graph.pbtxt i'll try that !
