### ISSUE TITLE
unordered_map::at: key not found

### ISSUE THREAD

**Issue by lvbaouu** [onnx/onnx#2758]
I am trying to convert a pytorch model to onnx format and encounter the following error. What is the reason triggering this issue and how should i fix it:
`
Traceback (most recent call last):
  File "convert_to_caffe2_models.py", line 50, in <module>
    init_net, predict_net = c2.onnx_graph_to_caffe2_net(model)
  File "/Users/lz2576/.conda/envs/py36/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 921, in onnx_graph_to_caffe2_net
    return cls._onnx_model_to_caffe2_net(model, device=device, opset_version=opset_version, include_initializers=True)
  File "/Users/lz2576/.conda/envs/py36/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 876, in _onnx_model_to_caffe2_net
    onnx_model = onnx.utils.polish_model(onnx_model)
  File "/Users/lz2576/.conda/envs/py36/lib/python3.6/site-packages/onnx/utils.py", line 21, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/Users/lz2576/.conda/envs/py36/lib/python3.6/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: unordered_map::at: key not found
`

**Comment by TMVector** [comment]
Hi @lvbaouu, I'm not sure what's causing the optimizer to fail, perhaps @ArmenAg(?) or @linkerzhang(?) might have some clue, although I suspect it's hard to tell without seeing the ONNX model.

In the meantime, can you try passing `do_constant_folding=False` to the `torch.onnx.export` call?

_PS: the error message would be much more readable if you kept the newlines and used a [code block](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) :)_

**Comment by BradleyBrown19** [comment]
Hi @TMVector, I'm getting this error as well when executing:

`rep = backend.prepare(onnx_model, device="CPU") `

I have converted the PyTorch model using:

`torch.onnx.export(model, dummy_input, './model.onnx', verbose=True, output_names=['scores', 'boxes'], do_constant_folding=False)`

the stack trace is as follows:

`<ipython-input-14-d945bd6430cc> in <module>
----> 1 rep = backend.prepare(onnx_model, device="CPU")

~/Desktop/COCOUI/create/lib/python3.7/site-packages/caffe2/python/onnx/backend.py in prepare(cls, model, device, raw_values_dict, **kwargs)
    711         device_option = get_device_option(Device(device))
    712 
--> 713         init_net, predict_net = cls._onnx_model_to_caffe2_net(model, device, opset_version, False)
    714 
    715         if raw_values_dict:

~/Desktop/COCOUI/create/lib/python3.7/site-packages/caffe2/python/onnx/backend.py in _onnx_model_to_caffe2_net(cls, onnx_model, device, opset_version, include_initializers)
    874         device_option = get_device_option(Device(device))
    875 
--> 876         onnx_model = onnx.utils.polish_model(onnx_model)
    877         init_model = cls.optimize_onnx(onnx_model, init=True)
    878         pred_model = cls.optimize_onnx(onnx_model, predict=True)

~/Desktop/COCOUI/create/lib/python3.7/site-packages/onnx/utils.py in polish_model(model)
     19     onnx.helper.strip_doc_string(model)
     20     model = onnx.shape_inference.infer_shapes(model)
---> 21     model = onnx.optimizer.optimize(model)
     22     onnx.checker.check_model(model)
     23     return model

~/Desktop/COCOUI/create/lib/python3.7/site-packages/onnx/optimizer.py in optimize(model, passes, fixed_point)
     53         optimized_model_str = C.optimize_fixedpoint(model_str, passes)
     54     else:
---> 55         optimized_model_str = C.optimize(model_str, passes)
     56 
     57     return onnx.load_from_string(optimized_model_str)

IndexError: unordered_map::at: key not found`

Please let me know if you have any suggestions on how to resolve!

**Comment by TMVector** [comment]
HI @BradleyBrown19. So just to check: `torch.onnx.export` runs okay, but once you have the ONNX model and try to run it with Caffe2 you get an error?

Are you able to provide the ONNX file or a minimal reproducible example?

**Comment by linkerzhang** [comment]
interesting.... @spandantiwari are "onnx" optimizers being used when exporting pytorch model to onnx format?

**Comment by spandantiwari** [comment]
@linkerzhang - no, onnx optimizer is not used in PyTorch.

@BradleyBrown19 - can you try to export with the flag keep_initializers_as_input=True when calling the torch.onnx.export API. And then try running the ONNX optimizer. 

If this passes, then I would say there's some improvement to be made for IR v4 and above.

**Comment by lvbaouu** [comment]
add keep_initializers_as_inputs=True solved my issue

Thanks.
________________________________

**Comment by spandantiwari** [comment]
@lvbaouu - that's good to know. 
@linkerzhang - the onnx optimizer seems to work only with IRv3 or lower. This could be an optimizer issue, or some assumption in the graph data structures.

**Comment by TMVector** [comment]
Sounds like it's the same issue as https://github.com/onnx/onnx/issues/2417 then

**Comment by linkerzhang** [comment]
Given that the optimizer in ONNX repo is not that actively maintained/updated with ONNX releases, it's not suggested to rely on it.
