### ISSUE TITLE
Building according to build instructions fails

### ISSUE THREAD

**Issue by katrasnikj** [onnx/onnx#2759]
The build fails at the last step:
`python setup.py install`

The compiler error that is the cause of the failure is:
```
C:\Program Files (x86)\protobuf\include\google/protobuf/io/coded_stream.h(881): error C2220: warning treated as error -
 no 'object' file generated (compiling source file C:\Repos\external\onnx\.setuptools-cmake-build\onnx\onnx-ml.pb.cc) [
C:\Repos\external\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
C:\Program Files (x86)\protobuf\include\google/protobuf/io/coded_stream.h(881): warning C4251: 'google::protobuf::io::C
odedOutputStream::default_serialization_deterministic_': struct 'std::atomic<bool>' needs to have dll-interface to be u
sed by clients of class 'google::protobuf::io::CodedOutputStream' (compiling source file C:\Repos\external\onnx\.setupt
ools-cmake-build\onnx\onnx-ml.pb.cc) [C:\Repos\external\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xxatomic(162): note:
   see declaration of 'std::atomic<bool>' (compiling source file C:\Repos\external\onnx\.setuptools-cmake-build\onnx\on
  nx-ml.pb.cc)
```

**Comment by jacky82226** [comment]
Hi,
It seems like a protobuf issue. Did you follow [the steps](https://github.com/onnx/onnx#instructions-to-build-protobuf-and-onnx-on-windows) to install protobuf?
If you did and it still did not work, maybe you can try to install onnx via anaconda first to check whether it can be built in your computer. 
BTW, what is your protobuf version?

**Comment by linkerzhang** [comment]
you may also try to use https://github.com/onnx/onnx-docker docker files here to avoid figuring out the dependency or env issues.

@vinitra I'd suggest to move the docker files into ONNX repo, btw.

**Comment by askhade** [comment]
Recently updated the instructions for building from source. see #3550 . If this is still relevant please reopen a new issue.
