### ISSUE TITLE
When can we espect python3.8 support ?

### ISSUE THREAD

**Issue by alexandreCameron** [onnx/onnx#2760]
Hi,

Following https://github.com/onnx/onnx/issues/2734, when can we expect python3.8 support for onnx ?

Thank

**Comment by snnn** [comment]
We'll have it for Windows in the upcoming release.

You can get a preview build from:
https://github.com/onnx/onnx/actions/runs/97346969

Please click the "wheels".

**Comment by alexandreCameron** [comment]
Great !

On what date do you plan to publish the release on pypi ?

**Comment by alexandreCameron** [comment]
It happened today :tada:
