### ISSUE TITLE
A "name" field for SparseTensorProto?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#2762]
This issue was raised from https://gitter.im/onnx/Lobby.

Indeed, a "name" is needed for SparseTensorProto if it's used to store the model weights for example. Thoughts? @gramalingam

**Comment by gramalingam** [comment]
A SparseTensorProto has a “TensorProto values” which has a name. Won’t it be enough to use the name in the “values” field? Do we need a separate name?

**Comment by linkerzhang** [comment]
Fair enough. Let's add some comment in place to clarify this "naming" please.

**Comment by askhade** [comment]
This is documented now: https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L608
