### ISSUE TITLE
Update ONNX packages on Anaconda

### ISSUE THREAD

**Issue by vinitra** [onnx/onnx#2775]
The conda-forge release (binary build) of ONNX on Windows with Python 3.6 is on version 1.1.1. As we highlight this installation path in the README, this binary needs to be updated for the new ONNX releases, ideally up to the new 1.7.

Tracking this issue from #2755.

**Comment by AlbertSadovnikov** [comment]
https://github.com/onnx/onnx/issues/2612

**Comment by vinitra** [comment]
Since this is being tracked in #2612, I'll close this issue.
