### ISSUE TITLE
To caffe

### ISSUE THREAD

**Issue by ElegantLin** [onnx/onnx#2776]
Hi, thanks for the great project.

Can it covert `onnx` to `caffe` ?

Thanks a lot.

**Comment by TMVector** [comment]
Hi @ElegantLin, try taking a look at [this tutorial](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html) -- it demonstrates loading an ONNX model in Caffe2 and exporting it with the Caffe2 model exporter.

**Comment by ElegantLin** [comment]
Hi, @TMVector,  thanks for your reply. I will take a look at this :)
