### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by daylight0998** [onnx/onnx#2777]
(1) I try to convert onnx model to mlmodel, but it's error:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

(2) convert onnx model to mlmodel code is:
import os
import onnx
from onnx import onnx_pb
from onnx_coreml import convert

dataset_dir = "./"

model_in = os.path.join(dataset_dir, "vgnet.onnx")
model_out = os.path.join(dataset_dir, "vgnet.mlmodel")
model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
print("prepare to convert...")
# model = onnx.load_model('vgnet.onnx')
coreml_model = convert(model_proto,
            minimum_ios_deployment_target='12')

(3) I debug it, it's interrupted at this file(./anaconda3/lib/python3.7/site-packages/onnx/shape_inference.py) :   inferred_model_str = C.infer_shapes(model_str), the function is:

def infer_shapes(model):  # type: (ModelProto) -> ModelProto
    if not isinstance(model, ModelProto):
        raise ValueError('Shape inference only accepts ModelProto, '
                         'incorrect type: {}'.format(type(model)))
    model_str = model.SerializeToString()
    inferred_model_str = C.infer_shapes(model_str)
    return onnx.load_from_string(inferred_model_str)

(4) my onnx model had checked, it's fine, the code is:
import onnx
import torch

print(onnx.__version__)
device = torch.device('cpu' if torch.cuda.is_available() else 'cpu')
onnx_model = onnx.load("./vgnet.onnx")
onnx.checker.check_model(onnx_model)
print("checker check model")

What can be done to resolve this error

**Comment by TMVector** [comment]
Hi @daylight0998 did you resolve this issue okay in https://github.com/onnx/onnx/issues/2779?
