### ISSUE TITLE
Does onnx support rnn-like models?

### ISSUE THREAD

**Issue by Joejiong** [onnx/onnx#2780]
Does onnx support rnn-like models?

**Comment by TMVector** [comment]
Hi @Joejiong, yes it does. There are operators for [RNN](https://github.com/onnx/onnx/blob/master/docs/Operators.md#RNN), [GRU](https://github.com/onnx/onnx/blob/master/docs/Operators.md#GRU), and [LSTM](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM), and more general [Loop](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Loop) and [Scan](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Scan) operators. It is supported by some exporters.

**Comment by Joejiong** [comment]
> Hi @Joejiong, yes it does. There are operators for [RNN](https://github.com/onnx/onnx/blob/master/docs/Operators.md#RNN), [GRU](https://github.com/onnx/onnx/blob/master/docs/Operators.md#GRU), and [LSTM](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM), and more general [Loop](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Loop) and [Scan](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Scan) operators. It is supported by some exporters.

thx a lot
