### ISSUE TITLE
pip install onnx==1.2.1

### ISSUE THREAD

**Issue by liguoyu666** [onnx/onnx#2782]
Error when I use ’pip install onnx==1.2.1‘

(base) lgy@lgy:~$ pip install onnx==1.2.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting onnx==1.2.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0c/ce/e66db6ac8462eeca295b30749ec3497c8d607d822de03288531577c725ce/onnx-1.2.1.tar.gz (2.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/lgy/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2plxk5wq/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2plxk5wq/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7lzitlei
         cwd: /tmp/pip-install-2plxk5wq/onnx/
    Complete output (6 lines):
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2plxk5wq/onnx/setup.py", line 71, in <module>
        assert CMAKE, 'Could not find "cmake" executable!'
    AssertionError: Could not find "cmake" executable!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

(base) lgy@lgy:~$ pip install onnx
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting onnx
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/fb/3193df06e0feae7884d25e11e41b410ecd3c0a17445b941767c772dc8cf7/onnx-1.7.0-cp37-cp37m-manylinux1_x86_64.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 336 kB/s 
Requirement already satisfied: protobuf in ./.local/lib/python3.7/site-packages (from onnx) (3.9.2)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from onnx) (1.12.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./anaconda3/lib/python3.7/site-packages (from onnx) (3.7.4.2)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from onnx) (1.16.4)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from protobuf->onnx) (41.0.1)
Installing collected packages: onnx
Successfully installed onnx-1.7.0

**Comment by liguoyu666** [comment]
It was installed on python3. and thers was no error on when I installed on python2.

**Comment by take-cheeze** [comment]
> AssertionError: Could not find "cmake" executable!

Seems you need to install cmake since it's building onnx from C++.
What's your python3 version?

**Comment by liguoyu666** [comment]
> > AssertionError: Could not find "cmake" executable!
> 
> Seems you need to install cmake since it's building onnx from C++.
> What's your python3 version?

Thank you, my python3 version is 3.7.3,  I installed cmake, but I still couldn't install onnx version 1.2.1

(base) lgy@lgy:~$ pip install onnx
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting onnx
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d9/fb/3193df06e0feae7884d25e11e41b410ecd3c0a17445b941767c772dc8cf7/onnx-1.7.0-cp37-cp37m-manylinux1_x86_64.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 105 kB/s 
Requirement already satisfied: protobuf in ./.local/lib/python3.7/site-packages (from onnx) (3.9.2)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from onnx) (1.16.4)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from onnx) (1.12.0)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./anaconda3/lib/python3.7/site-packages (from onnx) (3.7.4.2)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from protobuf->onnx) (41.0.1)
Installing collected packages: onnx
Successfully installed onnx-1.7.0


(base) lgy@lgy:~$ pip show onnx
Name: onnx
Version: 1.7.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: bddppq
Author-email: jbai@fb.com
License: UNKNOWN
Location: /home/lgy/anaconda3/lib/python3.7/site-packages
Requires: six, typing-extensions, numpy, protobuf
Required-by: 


(base) lgy@lgy:~$ pip uninstall onnx
Found existing installation: onnx 1.7.0
Uninstalling onnx-1.7.0:
  Would remove:
    /home/lgy/anaconda3/bin/backend-test-tools
    /home/lgy/anaconda3/bin/check-model
    /home/lgy/anaconda3/bin/check-node
    /home/lgy/anaconda3/lib/python3.7/site-packages/onnx-1.7.0.dist-info/*
    /home/lgy/anaconda3/lib/python3.7/site-packages/onnx.libs/libprotobuf-487875fe.so.9.0.1
    /home/lgy/anaconda3/lib/python3.7/site-packages/onnx/*
Proceed (y/n)? y
  Successfully uninstalled onnx-1.7.0


(base) lgy@lgy:~$ pip install onnx==1.2.1
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting onnx==1.2.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0c/ce/e66db6ac8462eeca295b30749ec3497c8d607d822de03288531577c725ce/onnx-1.2.1.tar.gz (2.6 MB)
     |████████████████████████████████| 2.6 MB 254 kB/s 
Requirement already satisfied: protobuf in ./.local/lib/python3.7/site-packages (from onnx==1.2.1) (3.9.2)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from onnx==1.2.1) (1.16.4)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from onnx==1.2.1) (1.12.0)
Requirement already satisfied: typing>=3.6.4 in ./anaconda3/lib/python3.7/site-packages (from onnx==1.2.1) (3.7.4.1)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./anaconda3/lib/python3.7/site-packages (from onnx==1.2.1) (3.7.4.2)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from protobuf->onnx==1.2.1) (41.0.1)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lgy/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9rscdaww
       cwd: /tmp/pip-install-rhp634lo/onnx/
  Complete output (118 lines):
  fatal: Not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- Build type not set - defaulting to Release
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Looking for pthread_create
  -- Looking for pthread_create - not found
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE
  -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so
  CMake Warning at CMakeLists.txt:255 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11" with any
    of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  [  2%] Running gen_proto.py on onnx/onnx.in.proto
  Processing /tmp/pip-install-rhp634lo/onnx/onnx/onnx.in.proto
  Writing /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.proto
  Writing /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.proto3
  generating /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
  [  5%] Running C++ protocol buffer compiler on /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.proto
  [  5%] Built target gen_onnx_proto
  [  8%] Running gen_proto.py on onnx/onnx-operators.in.proto
  Processing /tmp/pip-install-rhp634lo/onnx/onnx/onnx-operators.in.proto
  Writing /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.proto
  Writing /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.proto3
  generating /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
  [ 11%] Running C++ protocol buffer compiler on /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.proto
  Scanning dependencies of target onnx_proto
  [ 16%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o
  [ 16%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o
  In file included from /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.pb.cc:4:0:
  /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:10:40: fatal error: google/protobuf/port_def.inc: 没有那个文件或目录
  compilation terminated.
  In file included from /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.cc:4:0:
  /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:10:40: fatal error: google/protobuf/port_def.inc: 没有那个文件或目录
  compilation terminated.
  CMakeFiles/onnx_proto.dir/build.make:84: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o' failed
  make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o] Error 1
  make[2]: *** 正在等待未完成的任务....
  CMakeFiles/onnx_proto.dir/build.make:108: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o' failed
  make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o] Error 1
  CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/onnx_proto.dir/all' failed
  make[1]: *** [CMakeFiles/onnx_proto.dir/all] Error 2
  Makefile:127: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 327, in <module>
      'backend-test-tools = onnx.backend.test.cmd_tools:main',
    File "/home/lgy/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lgy/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/lgy/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 202, in run
      self.run_command('cmake_build')
    File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 196, in run
      subprocess.check_call(build_args)
    File "/home/lgy/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '6']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lgy/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-auptc4x3/install-record.txt --single-version-externally-managed --compile --install-headers /home/lgy/anaconda3/include/python3.7m/onnx
         cwd: /tmp/pip-install-rhp634lo/onnx/
    Complete output (81 lines):
    fatal: Not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    CMake Warning at CMakeLists.txt:255 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11" with any
      of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build
    [  5%] Built target gen_onnx_proto
    [ 11%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o
    [ 11%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o
    In file included from /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.cc:4:0:
    /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx-operators.pb.h:10:40: fatal error: google/protobuf/port_def.inc: 没有那个文件或目录
    compilation terminated.
    In file included from /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.pb.cc:4:0:
    /tmp/pip-install-rhp634lo/onnx/.setuptools-cmake-build/onnx/onnx.pb.h:10:40: fatal error: google/protobuf/port_def.inc: 没有那个文件或目录
    compilation terminated.
    CMakeFiles/onnx_proto.dir/build.make:108: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o' failed
    make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx-operators.pb.cc.o] Error 1
    make[2]: *** 正在等待未完成的任务....
    CMakeFiles/onnx_proto.dir/build.make:84: recipe for target 'CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o' failed
    make[2]: *** [CMakeFiles/onnx_proto.dir/onnx/onnx.pb.cc.o] Error 1
    CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/onnx_proto.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_proto.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 327, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/home/lgy/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lgy/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lgy/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 202, in run
        self.run_command('cmake_build')
      File "/home/lgy/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lgy/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-rhp634lo/onnx/setup.py", line 196, in run
        subprocess.check_call(build_args)
      File "/home/lgy/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '6']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lgy/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhp634lo/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-auptc4x3/install-record.txt --single-version-externally-managed --compile --install-headers /home/lgy/anaconda3/include/python3.7m/onnx Check the logs for full command output.


(base) lgy@lgy:~$ cmake -version
cmake version 3.5.1

**Comment by take-cheeze** [comment]
https://github.com/facebookarchive/caffe2/blob/b7d983f255ef5496474f1ea188edb5e0ac442761/cmake/ProtoBuf.cmake#L82-L92
?

**Comment by take-cheeze** [comment]
https://github.com/onnx/onnx/blob/78c0ba7abca974436e4de22d6d5f2290c57a2212/CMakeLists.txt#L100-L103

**Comment by liguoyu666** [comment]
> https://github.com/onnx/onnx/blob/78c0ba7abca974436e4de22d6d5f2290c57a2212/CMakeLists.txt#L100-L103

Thank you , but I don't know how to solve this problem，and why could I install onnx version 1.7.0 normally

**Comment by faxu** [comment]
@liguoyu666 is there a reason you need 1.2.1 specifically instead of a newer version?

**Comment by ThiloFink** [comment]
same problem here. I need onnx v1.2.1 to use export a MXNet model to onnx format.

**Comment by liguoyu666** [comment]
> same problem here. I need onnx v1.2.1 to use export a MXNet model to onnx format.

there is onnx on pytorch, maybe you can try it.
`torch_out = torch.onnx.export(model, x, "mobilenetv3.onnx", export_params=True)`

**Comment by faxu** [comment]
@thilofink which version of mxnet arre you using? From github it looks the latest versions of mxnet should support onnx 1.7 - https://github.com/apache/incubator-mxnet/tree/master/python/mxnet/contrib/onnx/mx2onnx
