### ISSUE TITLE
onnx.numpy_helper.to_array does not support tensor with external data

### ISSUE THREAD

**Issue by tianleiwu** [onnx/onnx#2785]
We exported gpt2-large to ONNX model. Since the model is larger than 2GB, so we stored some weights in external. For example, here is one tensor in initializer:

name: "h.0.attn.c_attn.bias"
external_data {
  key: "location"
  value: "h.0.attn.c_attn.bias"
}
data_location: EXTERNAL
dims: 3840
data_type: 1

It will encounter error using numpy_helper.to_array like the following:
    print(numpy_helper.to_array(initializer))
   File "D:\Anaconda3\envs\cpu_env\lib\site-packages\onnx\numpy_helper.py", line 66, in to_array
    .reshape(dims)
   ValueError: cannot reshape array of size 0 into shape (3840,)

My onnx package version is 1.7.0

**Comment by tianleiwu** [comment]
For anyone who encountered same issue, you might try the following for model loading:
  onnx.load_model(input_model_path, format=None, **load_external_data=True**)
This shall avoid the problem.

**Comment by TMVector** [comment]
Thanks for posting a workaround @tianleiwu. It's somewhat odd that it's needed -- I would expect `load_external_data` to be `True` [by default](https://github.com/onnx/onnx/blob/v1.7.0/onnx/__init__.py#L103).

In any case, the error message could be a lot better, I'll have a look at a PR.
