### ISSUE TITLE
Pytorch operator var_mean is not supported

### ISSUE THREAD

**Issue by zlenyk** [onnx/onnx#2786]
Hi!
Do you have a plan to start supporting operator torch.var_mean?
With the newest version of pytorch I'm getting message that it is not supported and my model is using it.
Error message: "Exporting the operator var_mean to ONNX opset version 9 is not supported. Please  open a bug to request ONNX export support for the missing operator."

Thank you.

**Comment by askhade** [comment]
@spandantiwari can we convert pytorch models with var_mean op? Do we need a need a new op here or can it be done with existing ones?

**Comment by askhade** [comment]
@zlenyk : Please create this issue in pytorch repo : https://github.com/pytorch/pytorch/issues

Closing this here.

**Comment by abhiagwl4262** [comment]
@zlenyk  @askhade Any update on this ?

**Comment by zlenyk** [comment]
This just got added to pytorch: https://github.com/pytorch/pytorch/issues/39349
