### ISSUE TITLE
Bart conversion

### ISSUE THREAD

**Issue by pgrandinetti** [onnx/onnx#2790]
Is there a sample of how to use onnx with the BART model?
I tried myself (with `convert` from `transformers.convert_graph_to_onnx`) and got

```
Exporting the operator triu to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

Related to https://github.com/onnx/onnx/issues/2554

**Comment by TMVector** [comment]
Hi @pgrandinetti, you could try changing the `opset_version` to a later opset, but ultimately you probably need to search for/raise a new issue on the PyTorch repo as it's a PyTorch export issue. It looks like there is already an open issue for `triu` here: https://github.com/pytorch/pytorch/issues/32968

**Comment by HenryDashwood** [comment]
opset 11 and 12 have them same issue

**Comment by faxu** [comment]
Closing this as it's a converter issue tracked in the Pytorch repo. Some workarounds are in the linked issue above and improved support is being added
