### ISSUE TITLE
onnGraph initializer

### ISSUE THREAD

**Issue by wshj2020** [onnx/onnx#2792]
I have met a question, when I get initializer tensor from onnGraph.initializer, my node input is not initializerd, how can I add it to my graph initializer. Thank you ~

**Comment by TMVector** [comment]
Hi @wshj2020, I'm not sure I understand the question. Do you have some example code?

**Comment by wshj2020** [comment]
ok,thank you.
my code is as follows:
for (i=0; i <onnGraph.initializer_size( ); i++)
{ if (strcmp(onnxGraph.initializer( i ).name( ).c_str( ),name( ).c_str( ))==0)
     {auto&tensor = onnGraph/initializer( i );
        return (tensor)};
}
the 'name" in code is 2784, now I want to make the equation work ,but 2784 (a node output )  is not in initializer, how can I get it ?

**Comment by TMVector** [comment]
If `2784` is a node output from a [Constant](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant) node, you can get that tensor by finding the node in the [`node` field](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L406) and taking the [`t` field](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L157) of the attribute named `value` belonging to that node.

If you want the output value of a tensor which is not a constant, you need to run the model. One way to do that is with [ONNX Runtime](https://github.com/microsoft/onnxruntime/).

**Comment by wshj2020** [comment]
Ok, 2784 is the Concat result ,I have the same operate  at other location ,it can work ,only this node is unsucess. and I print the datatype of the node , it is null , do you know why?

**Comment by TMVector** [comment]
I'm sorry, I don't understand. What are you trying to do? Maybe you are looking to do [constant folding](https://en.wikipedia.org/wiki/Constant_folding)? If so you can try using ONNX Runtime's constant folding:

```python
def fold_consts_ort(model : onnx.ModelProto):
    """
    Fold constants using ONNX Runtime's constant folding optimizations.
    """
    import onnxruntime as ort
    import tempfile

    with tempfile.TemporaryDirectory() as tdir:
        path = tdir + "/optimized.onnx"

        so = ort.SessionOptions()
        # This level of optimization does constant folding, but also redundant
        # node elimination and some fusion. We trust this shouldn't matter for
        # our purposes.
        so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC
        so.log_severity_level = 3 # Error and above
        so.optimized_model_filepath = path

        # Creating the session should be enough to create the optimized model
        ort.InferenceSession(
            model.SerializeToString(),
            sess_options=so,
            ).set_providers(
            providers = ["CPUExecutionProvider"],
            )

        return onnx.load(path)
```

**Comment by wshj2020** [comment]
thank you,  if I do not get the intrnal result in a layer ,how to get it , for example, I have a 'upsample' layer ,but I do not want to get the unsqueeze, concat etc operates which is the intermediate operation for upsampling.
thank you ~

**Comment by TMVector** [comment]
So you want to add the output of that node as a graph output? If the node is in the top-level graph, you can just add the output name to the list of graph outputs (in Python):
```python
import onnx
model = onnx.load("path/to/model.onnx")
[upsample_node] = [
    n
    for n in model.graph.node
    if n.op_type == "Upsample" and n.domain == ""
    ]
new_output = upsample_node.output[0]
model.graph.output.extend([new_output])
onnx.save(model, "model.add-output.onnx")
```
