### ISSUE TITLE
Convert Keras layer to Onnx

### ISSUE THREAD

**Issue by ptdung** [onnx/onnx#2796]
Hi,
I am stuck trying to convert a keras custom layer ( Depth Maxpool) to Onnx. Is there anyone has done it before or have any idea how to tackle with it?
Thanks.

**Comment by askhade** [comment]
@wenbingl @EmmaNingMS can you take a look?

**Comment by wenbingl** [comment]
The converter supports the custom layer. Can you post more details in the corresponding converter GitHub issue page for support?

**Comment by askhade** [comment]
@ptdung  : As suggested by wenbingl please open an issue in keras converter github repo : https://github.com/onnx/keras-onnx/issues.

Closing this issue here
