### ISSUE TITLE
Bug in Input and output dimension update

### ISSUE THREAD

**Issue by akansal1** [onnx/onnx#2799]
I think there is a **bug**, update input and output dimension flow is iterating over every input and output key in the model, instead it is should iterate only over desired number of keys fed via parameter input.
```python
 update_model_dims.update_inputs_outputs_dims(model, {
                    "input_1": ['b', 3, 'w', 'h'],  "input_2": ['b', 4],
                },{
                    "output": ['b', -1, 5]
                 }   )
```

https://github.com/onnx/onnx/blob/599f3da985cf8a790a619a505abce167d87c2c30/onnx/tools/update_model_dims.py#L70-L81

**Comment by linkerzhang** [comment]
you're right. the current logic may assume that all inputs/outputs dimensions are provided, which may not be the case.

Do you want to propose a PR to fix it?

**Comment by akansal1** [comment]
Sure I give it a try and  put it together

**Comment by kanthagirish-rit** [comment]
May I know when would this be merged to master?
