### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Siset** [onnx/onnx#2800]
Hello everyone,

I am experiencing problems installing onnx and protobuf from source. I am following the instructions for windows and everything looks fine, but it does not. 

The problem is that:
```
D:\>python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\gtx1080ti\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx-1.7.0-py3.6-win-amd64.egg\onnx\__init__.py", line 9, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors
  File "C:\Users\gtx1080ti\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx-1.7.0-py3.6-win-amd64.egg\onnx\external_data_helper.py", line 10, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "C:\Users\gtx1080ti\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx-1.7.0-py3.6-win-amd64.egg\onnx\onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "C:\Users\gtx1080ti\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx-1.7.0-py3.6-win-amd64.egg\onnx\onnx_ml_pb2.py", line 7, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf'

D:\>pip install protobuf
Requirement already satisfied: protobuf in c:\users\gtx1080ti\appdata\local\programs\python\python36\lib\site-packages\protobuf-3.12.2-py3.6.egg (3.12.2)
Requirement already satisfied: setuptools in c:\users\gtx1080ti\appdata\local\programs\python\python36\lib\site-packages (from protobuf) (41.2.0)
Requirement already satisfied: six>=1.9 in c:\users\gtx1080ti\appdata\local\programs\python\python36\lib\site-packages (from protobuf) (1.11.0)

D:\>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import protobuf
>>> import google.protobuf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.protobuf'
>>> exit()

D:\>
```

I think I am missing something, do you have any advice?

Thanks in advanced,

**Comment by linkerzhang** [comment]
@vinitra I think it may be better to move the docker file (for dev) into onnx repo for these kinds of issues.

**Comment by vinitra** [comment]
@Siset, have you tried the [installing ONNX on Windows through anaconda](https://github.com/onnx/onnx#build-onnx-on-windows-with-anaconda) installation path? It seems that a previous installation of protobuf / the PyPi google package is causing versioning problems here. Some people have found a [solution path](https://github.com/tensorflow/tensorflow/issues/6341) in this issue that you can try.

Alternatively, please feel free to use the [onnx-dev docker image](https://hub.docker.com/r/onnx/onnx-dev) that Ke mentioned above.

**Comment by Siset** [comment]
Hi @linkerzhang @vinitra ,

Thanks for the answer! @vinitra  I tried installing with anaconda and I had problems aswell. I will try the solution path and after that I will go to the docker image!

I close the issue and I will reopen if I do not achieve it
Thank you both.
