### ISSUE TITLE
Hiding or delete fine-grained operations in node

### ISSUE THREAD

**Issue by wshj2020** [onnx/onnx#2804]
HI, I have do upsample in my net using F.interpolate function,  the input of the upsample layer is a mul operate, but when I convert my .pth to .onnx , I find some fine_grained operate is added as a node. for example ,upsamle will use unsequeeze ,mul,and concat operate , so my upsamle node have two input ,one is the output of the previous layer, another is the internal op(concat) output, I only need the first one ,so ,I want know ,how to Hiding or delete fine-grained operations in one node.
Thanks!

**Comment by TMVector** [comment]
HI @wshj2020, [`Upsample`](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Upsample-9) does take two required inputs.

**Comment by askhade** [comment]
@wshj2020 : These operators were introduced as part of the conversion from pytorch to onnx. They cannot be hidden. An ONNX model will not necessarily "look" exactly similar to its original framework counterpart.. as long as the inference results are same the conversion is successful.
