### ISSUE TITLE
it not working after installation

### ISSUE THREAD

**Issue by skchinna7** [onnx/onnx#2805]
what am I supposed to do after intsallation

**Comment by askhade** [comment]
Can you elaborate on what are you trying to accomplish and what issue are you facing? Onnx tutorials repo has good content on getting started as well as some of the common onnx usage scenarios :  https://github.com/onnx/tutorials

**Comment by vinitra** [comment]
A good way to check if your installation is successful is to run 
```
python -c "import onnx"
```
and see if any errors appear.

**Comment by skchinna7** [comment]
after that what am I supposed to do maam

**Comment by skchinna7** [comment]
pytest is not working

**Comment by vinitra** [comment]
Can you indicate the error messages you are seeing? You can install the pytest package with `pip install pytest`.

**Comment by skchinna7** [comment]
after that only maam its not working

**Comment by skchinna7** [comment]
i run pytest and  its not working

**Comment by faxu** [comment]
Please provide more detailed information on the error you are seeing if you require assistance for troubleshooting, otherwise it's impossible to help.

**Comment by prasanthpul** [comment]
Please reopen if you are still having an issue and share the information requested
