### ISSUE TITLE
RuntimeError while converting "pytorch_model.pt" to "pytorch_model.onnx"

### ISSUE THREAD

**Issue by pumpkinband** [onnx/onnx#2806]
```
from torch.autograd import Variable
import torch.onnx
import torchvision
import torch

dummy_input = Variable(torch.randn(1, 3))
model = torch.load('./pytorch_model.pt')
torch.onnx.export(model, dummy_input, "pytorch_model.onnx")
```

error :- 

`RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)`

**Comment by TMVector** [comment]
Sounds like `dummy_input` should be a tensor of type `Long`. Try `dummy_input = torch.randn(1, 3, dtype=torch.int64)`. Your dummy input needs to actually match the model; if you have real input that's best. If you get an error running `model(dummy_input)` then your input isn't valid.

**Comment by faxu** [comment]
If there are further follow ups needed, please file them in the [pytorch repo](https://github.com/pytorch/pytorch/issues) for torch.onnx if related to the ONNX export
