### ISSUE TITLE
Pytorch to onnx(OCR model)

### ISSUE THREAD

**Issue by Akshaysharma29** [onnx/onnx#2807]
Hi All,   
I am trying to convert this model(https://github.com/clovaai/deep-text-recognition-benchmark) to onnx but facing the following error.

 Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible.

I have tried pytorch version 1.5,1.4,1.3. 
Any suggestion?
Thanks

**Comment by Akshaysharma29** [comment]
I have two issues
1)  nn.AdaptiveAvgPool2d((None,1)) we have make it static. But making it static reducing model perfomance as well.
2) So, alternative F.adaptive_avg_pool2d is also not supported.

Finally, other operations where tried and the issue has been fixed for now.

**Comment by TMVector** [comment]
Hi @Akshaysharma29 this sounds like a PyTorch converter issue, you probably want to look on the [discussion forums](https://discuss.pytorch.org/) and [github issues](https://github.com/pytorch/pytorch/issues) :)

**Comment by csmcallister** [comment]
@Akshaysharma29  how did you solve the issue? You said other operations were tried and that it got fixed? What was the solution?

**Comment by Akshaysharma29** [comment]
@csmcallister making **(nn.AdaptiveAvgPool2d((None,1)) )** static  like **( nn.AdaptiveAvgPool2d((512,1)) )** will the problem.

**Comment by padmasreenagarajan** [comment]
Hi @Akshaysharma29 ..even i got the same error when importing mobilenetv3 to onnx.
could u pls tell me what changes u made in code and where u made?

When i debugged symbolic_helper.py by printing the node which throws error,
i found this line 70 in my mobilenetv3.py
%549 : Long() = onnx::Gather[axis=0](%546, %548) # C:\Users\PycharmProjects\mbv3\vision\nn\mobilenet_v3.py:70:0


 def forward(self, x):
        batch, channels, height, width = x.size()  **..........>70th line in mobilenetv3.py**
        out = F.avg_pool2d(x, kernel_size=[height, width]).view(batch, -1)
        out = self.dense(out)
        out = out.view(batch, channels, 1, 1)
        # out = hard_sigmoid(out)

        return out * x
