### ISSUE TITLE
Support AdaptiveMaxPool2d

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2809]
How can we export [AdaptiveMaxPool2d](https://pytorch.org/docs/master/generated/torch.nn.AdaptiveMaxPool2d.html)?
Current workaround is to use `RoiAlign` with a single roi.

**Comment by askhade** [comment]
@dashesy : There is a work around then what is the motivation for adding this op? Perf?

**Comment by dashesy** [comment]
They are not exactly the same, only very similar. Feel free to close this issue as Adaptive pooling is not used much nowadays.
We had some old model, but decided to accept the difference and use roi_align anyways.
