### ISSUE TITLE
Predictions from onnx do not match the predictions from a scikit learn random forest model

### ISSUE THREAD

**Issue by asanders-hub** [onnx/onnx#2810]
Here’s an illustration of what the deviations look like with increasing values of the dependent variable. Note that RMSE here is a measure of difference between predictions of the original scikit-learn model and the ONNX model.
 
Attached are the largest differences observed from the predictions of model 9 above.
 
[And](url
[sample_model10.zip](https://github.com/onnx/onnx/files/4727012/sample_model10.zip)
) an illustration of the error rates with increasing number of trees in the forest.
 
![pic1](https://user-images.githubusercontent.com/64091508/83705863-460a8b00-a5d3-11ea-844f-eeea1ed6448d.png)
![pic2](https://user-images.githubusercontent.com/64091508/83705866-46a32180-a5d3-11ea-9fe2-dd59b215fd2f.jpg)
![pic3](https://user-images.githubusercontent.com/64091508/83705867-473bb800-a5d3-11ea-9b12-10a0fde7a9c6.png)

**Comment by askhade** [comment]
@asanders-hub : please open this issue in the skleran-onnx converter repo https://github.com/onnx/sklearn-onnx/issues

**Comment by xadupre** [comment]
This issue is the same as this one raised on onnxruntime: https://github.com/microsoft/onnxruntime/issues/4130.

**Comment by askhade** [comment]
Closing this in favor of: https://github.com/microsoft/onnxruntime/issues/4130 as it contains a lot of context/discussion.
If the issue still persists then please reopen the one in onnxruntime repo
