### ISSUE TITLE
predict nan

### ISSUE THREAD

**Issue by cqray1990** [onnx/onnx#2812]
when i convert to pb to onnx and the result is :
2020-06-04 15:10:45,519 - VERBOSE - tf2onnx.optimizer: Apply remove_back_to_back
2020-06-04 15:10:45,545 - VERBOSE - tf2onnx.optimizer.BackToBackOptimizer: no change
2020-06-04 15:10:45,551 - INFO - tf2onnx.optimizer: After optimization: Add -8 (27->19), Cast -3 (15->12), Const -311 (503->192), Gather +6 (0->6), Identity -1 (1->0), Shape -9 (15->6), Slice -3 (18->15), Squeeze -6 (12->6), Transpose -254 (256->2), Unsqueeze -6 (12->6)
2020-06-04 15:10:45,570 - INFO - tf2onnx:
2020-06-04 15:10:45,570 - INFO - tf2onnx: Successfully converted TensorFlow model ./HT.pb to ONNX
2020-06-04 15:10:46,103 - INFO - tf2onnx: ONNX model is saved at HT.onnx

but when i inference with the converted onnx the result is all nan:
[array([[[[nan, nan, nan, nan, nan, nan],
[nan, nan, nan, nan, nan, nan],
[nan, nan, nan, nan, nan, nan],
...,
[nan, nan, nan, nan, nan, nan],
[nan, nan, nan, nan, nan, nan],
[nan, nan, nan, nan, nan, nan]],

    [[nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     ...,
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan]],

    [[nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     ...,
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan]],

    ...,

    [[nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     ...,
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan]],

    [[nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     ...,
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan]],

    [[nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     ...,
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan],
     [nan, nan, nan, nan, nan, nan]]]], dtype=float32)]
can you help me? thank you so much

**Comment by cqray1990** [comment]
and i get pb file by convert ckpt mode of tensorflow to Pb,and i test pb model ,the result is correct,but when i continue convert pb file to onnx and do some inference,the result is nan

**Comment by jcwchen** [comment]
This should be a converter issue... If you still have this problem, please raise an issue about this there: https://github.com/onnx/tensorflow-onnx. Thanks.
