### ISSUE TITLE
Mish support for YoloV4

### ISSUE THREAD

**Issue by minglu2019** [onnx/onnx#2818]
'Mish' is an activation function used in Yolo v4 model, will ONNX plan to support it in new version?

here are some references for Mish:
TF: https://github.com/tensorflow/addons/blob/093cdfa85d334cbe19a37624c33198f3140109ed/tensorflow_addons/activations/mish.py#L30-L44
Pytorch: https://github.com/thomasbrandon/mish-cuda/blob/master/csrc/mish.h#L26-L31

**Comment by askhade** [comment]
@minglu2019 : Looks like this activation function can be constructed from already existing primitive onnx operators. In such cases we recommend adding then as a function instead of operator. 
Take a look at the guidelines for adding\introducing a new operator : https://github.com/onnx/sigs/blob/master/operators/docs/AddNewOpV3.md#step-1-proposing-a-new-operatorfunction-

**Comment by jay-karan** [comment]
Hi @askhade, I am interested in contributing for this Op as a function using primitives'. How do I move further to contribute ?(I mean to ask about procedure or guidelines)

**Comment by askhade** [comment]
@jay-karan please follow this : https://github.com/onnx/sigs/blob/master/operators/docs/AddNewOpV3.md#proposing-and-submitting-a-new-operator-or-function-to-onnx-
You can also refer to this PR as an example: https://github.com/onnx/onnx/pull/2187

**Comment by wadexu** [comment]
> Hi @askhade, I am interested in contributing for this Op as a function using primitives'. How do I move further to contribute ?(I mean to ask about procedure or guidelines)

May I know if MISH is supported right now? Thank you

**Comment by askhade** [comment]
No it isn't. All available operators and function documentation  can be found here: https://github.com/onnx/onnx/blob/master/docs/Operators.md

**Comment by jcwchen** [comment]
`Mish` has been finally introduced by https://github.com/onnx/onnx/pull/4350. This operator will be included in the next ONNX release. Close here now.
