### ISSUE TITLE
Raw data in Protobuf 

### ISSUE THREAD

**Issue by M-Tonin** [onnx/onnx#2825]
Hey,

I am trying to understand better the proto represation of model's. I know that ONNX allows serializing the “raw data” encoded in a sequence of bytes and 

> When this raw_data field is used to store tensor value, elements MUST be stored in as fixed-width, little-endian order. Floating-point data types MUST be stored in IEEE 754 format. Complex64 elements must be written as two consecutive FLOAT values, real component first. Complex128 elements must be written as two consecutive DOUBLE values, real component first. Boolean type MUST be written one byte per tensor element (00000001 for true, 00000000 for false).

> Note: the advantage of specific field rather than the raw_data field is that in some cases (e.g. int data), protobuf does a better packing via variable length storage, and may lead to smaller binary footprint. When this field is present, the data_type field MUST NOT be STRING or UNDEFINED

I could understand that. But I am not able to identify and parse this values when I try to find same value in proto file and weights and bias values.  And I know there is the _def from_array(arr, name=None)_, my question is a bit more deep of #1572.

![image](https://user-images.githubusercontent.com/21134353/84593995-b90ecf80-ae25-11ea-9af7-0786aefbba34.png)

And in netron we can see the neural network bias values (referer to the image below)

![image](https://user-images.githubusercontent.com/21134353/84594056-fbd0a780-ae25-11ea-9975-1306e78d0ffc.png)

I tried to catch the UTF-8 values between "/", get the bytes corresponding, with little edian order converter to IEEE-754 but I could not find some bias/weights equivalent.

So, I am not able to know where this bucket of bias values in proto represetation, I can not know 
exactly where and how it is stored.

Someone know this issue or some documentation ?
Hope someone can help me

**Comment by TMVector** [comment]
Hi @M-Tonin, I'm not sure exactly what you're asking, so I'll try and list some details that might help, or might help you clarify your question. Apologies if I cover stuff you already know.

The inputs to nodes are identified by ["value name"](https://github.com/onnx/onnx/blob/master/docs/IR.md#names-within-a-graph) which is unique in its scope. This value can originate from a graph input, a node output, or an initializer.

Constant parameters (weights, biases, etc.) are normally stored as initializers in the [`GraphProto.initializer`](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L414) field. This is a repeated message field: a list of [`TensorProto`](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L448-L586)s, which is conceptually a map from the tensor name to the tensor itself. This is the case for the `conv1/7x7_s2_b_0` tensor you highlighted in your screenshots.

Constants can also be stored on [`Constant`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant) nodes, in which case the parameters are stored in one of the attributes, normally in the `value` attribute as a `TensorProto`. Interpreting this `TensorProto` is the same as the `TensorProto`s in the `GraphProto.initializer` field.

Constant parameters can also be not stored at all, but calculated at runtime instead, i.e. with a graph component which always produces the same value.

If you want to access these stored constant values programmatically, you will want to use language with [protobuf](https://developers.google.com/protocol-buffers) support (but note plenty of languages have non-official support), which will let you traverse the data structure and get ahold of the raw byte vector. The structure of the code to access the data will be almost identical in Python, so if you know Python it's often easier to experiment there, in a repl.

[Here](https://github.com/onnx/onnx/issues/1425#issuecomment-636180016) is an example of how to read an initializer, and here is a (brittle) example of reading from a `Constant` node:
```python
import onnx, onnx.numpy_helper
model = onnx.load("path/to/model.onnx")

# Find the constant node.
# FIXME we are only searching the top-level graph which isn't always correct!
[const_node] = [
    n
    for n in model.graph.node
    if n.op_type == "Constant" and n.domain == ""
    if n.output[0] == "mobilenetv20_features_conv0_weight"
    ]

# Get the `value` attribute.
# FIXME: We should really check which attribute is used!
[attr] = [a for a in const_node.attribute if a.name == "value"]

w = numpy_helper.to_array(attr.t)
```

**Comment by M-Tonin** [comment]
Hi @TMVector, thanks for the support.

`
If you want to access these stored constant values programmatically, you will want to use language with protobuf support (but note plenty of languages have non-official support), which will let you traverse the data structure and get ahold of the raw byte vector. The structure of the code to access the data will be almost identical in Python, so if you know Python it's often easier to experiment there, in a repl.
`
So my doubt is somewhat like that. Basically, I'm trying to understand how the value of "raw_data" is represented. I mean, how can I find the float, for example, -2.5272 ... inside the string "& \ 276" ...

I have tried to convert UTF-8 to IEEE-754 (float32) but it does not match..

**Comment by TMVector** [comment]
If you were to access that `raw_data` bytestring via a protobuf API, you would get it as an array of bytes, which would make your job much easier, because you can interpret it as an array of floats and you're done.

The reason you get the wrong value from your interpretation of the protobuf text form is that `\300` means `(byte)300`, not `"\u0300"`. E.g. in Python:
```python
import struct
struct.unpack("f", b"&\276!\300") # = (-2.5272,)
```

**Comment by M-Tonin** [comment]
Thanks!
