### ISSUE TITLE
onnx add nodes

### ISSUE THREAD

**Issue by manhongnie** [onnx/onnx#2827]
Hi, how to add a Sigmoid node to an onnx model? I can't always write this output

**Comment by askhade** [comment]
Check this : https://github.com/onnx/onnx/blob/master/onnx/examples/make_model.ipynb Here you will find an example of creating nodes, its inputs, outputs etc.

**Comment by linkerzhang** [comment]
I'm closing this, and feel free to reopen it if there're more questions.
