### ISSUE TITLE
How to upgrade the opset version of onnx model ?

### ISSUE THREAD

**Issue by wangzhao123456** [onnx/onnx#2829]
Hello, ONNX team:
     I tried to optimize the onnx model using onnx runtime. However, I got the following problem when the model's opset version is below 7. 
"ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher."

    I further tried to upgrade the the opset version of onnx model using the method described in 
 "https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx". I can successfully upgrade onnx model from 6 to 7.  When I tried to convert the opset version from 3 to 7, It failed.

    Is there some ways to slove this problem?  Thanks in advance!

**Comment by askhade** [comment]
@wangzhao123456 : Support for version converter is limited. Investments in version converter are currently driven by whoever needs it. Do you have the original framework model corresponding to your onnx model? The easiest way would be to reconvert the original framework model to onnx. If not then your contributions to version-converter are welcome!

**Comment by askhade** [comment]
@wangzhao123456 : Since you want to convert opset 3 model to opset 7 I highly recommend reconverting the original framework model to onnx. There were also updates to version converter recently to fix a lot of missing adapters and you can try that on newer models.

**Comment by KLL535** [comment]
Thank you but nothing is clear
