### ISSUE TITLE
Iterating ONNX graph

### ISSUE THREAD

**Issue by surya00060** [onnx/onnx#2838]
Hi

Is there a way to iterate ONNX graphs and extract layer-wise details?

Thanks

**Comment by jacky82226** [comment]
Hi @surya00060,
You can try this:
```
import onnx
model = onnx.load('model.onnx')
inits = model.graph.initializer
for init in inits:
  print (init.name)
```
You can also access `init.XXX` to obtain other attributes.

**Comment by surya00060** [comment]
Thanks @jacky82226  for your reply. 
I want to iterate each operation of the given computation graph.
```%123 = Conv[dilations = [1, 1], group = 1, kernel_shape = [7, 7], pads = [3, 3, 3, 3], strides = [2, 2]](%input, %conv1.weight)
  %124 = BatchNormalization[epsilon = 9.99999974737875e-06, momentum = 0.899999976158142](%123, %bn1.weight, %bn1.bias, %bn1.running_mean, %bn1.running_var)
  %125 = Relu(%124)
  %126 = MaxPool[ceil_mode = 0, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [2, 2]](%125)
  %127 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%126, %layer1.0.conv1.weight)
  %128 = BatchNormalization[epsilon = 9.99999974737875e-06, momentum = 0.899999976158142](%127, %layer1.0.bn1.weight, %layer1.0.bn1.bias, %layer1.0.bn1.running_mean, %layer1.0.bn1.running_var)
  %129 = Relu(%128)
```
whereas from your code, I was only able to traverse through operations with parameters in alphabetical orders. 
```
bn1.bias
bn1.running_mean
bn1.running_var
bn1.weight
conv1.weight
fc.bias
fc.weight
layer1.0.bn1.bias
layer1.0.bn1.running_mean
layer1.0.bn1.running_var
layer1.0.bn1.weight
layer1.0.bn2.bias

```

I want to traverse all the operators in the graph in the same order of execution. Is there a way to do that? 

Thanks in Advance for your replies.

**Comment by jacky82226** [comment]
How about this:
```
import onnx
model = onnx.load('model.onnx')
for node in model.graph.node:
  print(node.input)
```
It follows the same order of execution and there are other attributes like `output`, `op_type`, `attribute` or `name`. 

Hope it helps.

**Comment by surya00060** [comment]
Thanks a lot, @jacky82226 . This was the solution I'm searching for !!!

**Comment by surya00060** [comment]
hey @jacky82226 ,  Is there any attribute which returns the output shape of the tensor after each operation in the graph while iterating the graph? (Given a fixed input tensor)

Thanks in Advance.

**Comment by jacky82226** [comment]
As far as I know, you might need to go back to use `model.graph.initializer`
```
for init in model.graph.initializer:
  print(init.dims)
```

**Comment by leimao** [comment]
> As far as I know, you might need to go back to use `model.graph.initializer`
> 
> ```
> for init in model.graph.initializer:
>   print(init.dims)
> ```

This only returns the shape of the weights in each of the nodes in the graph. ONNX itself does not have the capability of predicting the shape of the node output without the assistance from ONNX Runtime.

**Comment by jcwchen** [comment]
Besides ONNXRuntime, ONNX also has onnx.shape_inference to infer output shape. The inferred shapes will be saved as `model.graph.value_info` if successful.

**Comment by wxthu** [comment]
> hey @jacky82226 , Is there any attribute which returns the output shape of the tensor after each operation in the graph while iterating the graph? (Given a fixed input tensor)
> 
> Thanks in Advance.

Same issue！！

**Comment by tomhepworth** [comment]
> How about this:
> 
> ```
> import onnx
> model = onnx.load('model.onnx')
> for node in model.graph.node:
>   print(node.input)
> ```
> 
> It follows the same order of execution and there are other attributes like `output`, `op_type`, `attribute` or `name`.
> 
> Hope it helps.

Is this order defined in the spec anywhere? What if there are branches in the graph. 

Is it a guaranteed property of the onnx graph that in the list of nodes `model.graph.node`, by the time I read node `N` I will have seen any of its potential dependencies in the preceeding elemetns of `model.graph.node`?
