### ISSUE TITLE
pytorch2onnx

### ISSUE THREAD

**Issue by feifeiwei** [onnx/onnx#2841]
hello, When I convert a pytorch model to onnx, I found an error in one of the parameters.
e.g. 
a parameter named anchor=tensor([1.9375, 0.6250]);
but then I use
 `torch.onnx.export(model, dummy_input1, "convert_model2.onnx", verbose=False, input_names=input_names, output_names=output_names)`
the anchor value was set to  tensor([1., 0.],)。
what's the problem??

**Comment by linkerzhang** [comment]
It's better to move the question to pytorch community. @spandantiwari

**Comment by askhade** [comment]
@feifeiwei : Can you add more details here like which operator etc... Best would be to share your model.

**Comment by srisuk2519** [comment]
เมื่อ อา. 21 มิ.ย. 2563 เวลา 17:53 feifeiwei <notifications@github.com>
เขียนว่า:
