### ISSUE TITLE
Will there be support of atomic GroupNorm operator?

### ISSUE THREAD

**Issue by ersheng-ai** [onnx/onnx#2843]
One could use InstanceNorm operator together with some other operators as an alternative solution for GroupNorm like this:

```
GroupNorm =
            reshape +
            InstanceNorm (weights == 1.0, bias == 0.0) +
            reshape back +
            scale with GroupNorm weights +
            add with GroupNorm bias
```

This is sometimes not the most efficient solution for inference boosting.
Atomic GroupNorm operator should be considered.

**Comment by askhade** [comment]
@ersheng-ai : If an operator can be represented using multiple other operators then it should be added as a function instead of an operator. Backends can then add fusions to speed up the sub graphs.
You are welcome to propose a function for GroupNorm
