### ISSUE TITLE
onnx2pb，graph confusion

### ISSUE THREAD

**Issue by lawo123** [onnx/onnx#2845]
I used convert onnx to pb.I used netron open pb,the graph is different from onnx and confusion.

**Comment by askhade** [comment]
Can you add more details:
ONNX version, how did you convert and why are you doing this conversion?

**Comment by lawo123** [comment]
> Can you add more details:
> ONNX version, how did you convert and why are you doing this conversion?
thank you for your reply.My onnx version is 1.7.I want to transfer pthto pb to get a clear graph of pb.Below is my code：

```
trained_model = torchvision.models.resnet18(pretrained=False)
trained_model.eval()

# Export the trained model to ONNX
dummy_input = Variable(torch.randn(1, 3, 256, 128)) # one black and white 28 x 28 picture will be the input to the model
torch.onnx.export(trained_model, dummy_input, "output/resnet.onnx")


import onnx
from onnx_tf.backend import prepare

# Load the ONNX file
model = onnx.load('output/resnet.onnx')
onnx.checker.check_model(model)
# Import the ONNX model to Tensorflow
tf_rep = prepare(model)

# Input nodes to the model
print('inputs:', tf_rep.inputs)

# Output nodes from the model
print('outputs:', tf_rep.outputs)

# All nodes in the model
print('tensor_dict:')
print(tf_rep.tensor_dict)
```
The following is a comparison of onnx files and pb files opened with netron.
![image](https://user-images.githubusercontent.com/44777088/85089478-55b1e280-b215-11ea-8f4b-95773313887d.png)
![image](https://user-images.githubusercontent.com/44777088/85089527-6e21fd00-b215-11ea-870b-c1f8f400f9e4.png)



@askhade

**Comment by askhade** [comment]
Were you able to resolve this? This looks like a converter issue. Can you please open this in the converter repo instead.
