### ISSUE TITLE
Question on "all names should be specified when max limit is finite" please.

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#285]
When registering operators with variadic input, I'm assuming that we also want to follow the API NumberOfInput to specify an (min,max) range to stop some extreme models from stressing a kernel implementation. In this case, we may not want to specify all the names (too many names if enforced :) ).

Shall we relax this rule or any other consideration behind this rule please? Thank you!

"""
// if max limit is finite - all names should be specified
  if (max_input_ < std::numeric_limits<int>::max()) {
    ENFORCE(inputs_.size() == max_input_);
  }
"""

**Comment by bddppq** [comment]
Do you have an example?
My first impression is such limit probably should not be expressed in ONNX, because ONNX model doesn't carry runtime information. A backend could throw unsupported error.when see unfit cases.

**Comment by linkerzhang** [comment]
We have an onnx-ml Op as below. It's functionality is to merge many feature arrays into one with "inputdimension" attribute to specify each feature array's length pre-assigned.

@gramalingam and I discussed offline, we may have .NumInput(1) specified in this case (1 variadic input), and have a way to indicate that this is a variadic input formal parameter. so that the node which refers to this op may have many inputs. @gramalingam may add more comments here please.

OPERATOR_SCHEMA(FeatureVectorizer)
.SetDomain("ai.onnx.ml")
.NumInputs(1, 1000)
.NumOutputs(1)
.SetDoc(R"DOC(
    Concatenates input features into one continuous output.  
    Inputlist is a list of input feature names, inputdimensions is the size of each input feature.
    Inputs will be written to the output in the order of the input arguments.
    All inputs are tensors of float.  Any feature that is not a tensor of float should
    be converted using either Cast or CastMap.
)DOC")
.Input(0, "X", "ordered input tensors", "T")
.Output(
    0,
    "Y",
    "Full output array, in order assigned in the inputlist, as floats",
    "T")
.TypeConstraint("T", { "tensor(float)" }, " allowed types.")
.Attr(
    "inputdimensions",
    "the size of each input in the input list",
    AttrType::INT);

**Comment by gramalingam** [comment]
Operators with variadic inputs introduce multiple issues that are not currently addressed. I believe ONNX ML has operators (like FeatureVectorizer) that are variadic.

First question: what does the "number of inputs" declared for an operator mean when it is variadic?

One interpretation (which I prefer) is that a variadic input is counted as one input when declaring the operator's arity. In this case, there is a check on the number-of-inputs in a node in OpSchema::verify which should be disabled for a variadic operator.

A second interpretation is that we set the number-of-inputs of the operator to be a large value or maxint or something like that for a variadic operator. In this case, the "Finalize(...)" method needs to modified to handle this. I think this is what Ke is referring to.

I prefer going with the first solution. In that case, we need to be able to specify whether an operator is variadic. And if it is, we should not check the number of inputs in a node in "verify".

**Comment by gramalingam** [comment]
If I understand right, Ke is also fine with or prefers the first interpretation above. But either way, we need to change one thing or another in schema.cc

**Comment by gramalingam** [comment]
The other question that has been pending for variadic inputs is the use of input_arg_count to specify how to partition the input list into N different inputs. Are we fine with using input_arg_count?

**Comment by bddppq** [comment]
This case is similar to [Concat](https://github.com/onnx/onnx/blob/60fd8a2c674faf419df3bde302cfc30e044ab7d2/onnx/defs/tensor/defs.cc#L60), we use `NumInputs(1, INT_MAX)` to express variadic inputs, the current checker/Finalize handling is handling it good.

**Comment by bddppq** [comment]
Like I said in my first comment, I feel this "1000" limit should not be expressed in ONNX, but rather individual backend decides whether the real number of inputs is acceptable and throws unsupported error in case not.

**Comment by buehrer** [comment]
bddppq, what is your suggestion to express variadic inputs for operators in ONNX? I see that you don't want to use a max, and I think that makes sense.  gramalingam is suggesting we add the ability to explicitly express the operator has variadic inputs.  Maybe something on the schema like 

instead of .NumInputs(1,1000)

use 

.NumInputs(2)
.Input(0, ...)
.IsVariadicInput(1)   

where input(1) can be of size 0 or more.

Do you agree?

**Comment by gramalingam** [comment]
@buehrer  I think the "Input(0,...)" method already has a last parameter indicating if the corresponding input is optional or not. We could generalize this also (into an enum indicating: single-arity, optional (0 or 1), or variadic (0 or more).

**Comment by buehrer** [comment]
Sounds good to me!

**Comment by dzhulgakov** [comment]
On schema - yes we can change Input() specification to represent single/optional/variadic (with only one op being variadic).

As for input_arg_count - see reasoning in #151: for graph processing it's easier to have all inputs at the same level and be directly addressable. But we can add necessary schematization in schema.

**Comment by linkerzhang** [comment]
Thank you all very much for the great discussion and comments! So,
1), Let's firstly use MAX for current FeatureVectorizer op registration.
2). Let's change the OpSchema .Input API a little bit to specify whether an input is single/optional/variadic. Of course, the verify logic will be adjusted too when making this change.
Correct me if my recap is wrong please. will make the change later if it's correct.

**Comment by gramalingam** [comment]
Sounds good to me too, thanks!
