### ISSUE TITLE
Onnx Installation 

### ISSUE THREAD

**Issue by SudanYogesh23** [onnx/onnx#2851]
while setting up the local library 
cmake -G "Visual Studio 15 2017 Win64" -Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF **-DCMAKE_INSTALL_PREFIX=<protobuf_install_dir>**
msbuild protobuf.sln /m /p:Configuration=Release
msbuild INSTALL.vcxproj /p:Configuration=Release

<protobuf_install_dir> when I give my local installed protobuf directory I get the error of access denied what should I be doing on this.

**Comment by jacky82226** [comment]
Hi @SudanYogesh23,
Sorry that the document might be unclear. Did you set _<protobuf_install_dir>_ to another empty directory where you want to install?
