### ISSUE TITLE
OpSet versions & definition

### ISSUE THREAD

**Issue by peter197321** [onnx/onnx#2858]
Hello guys,

I'm a new to ONNX and I'm trying to locate the OpSet definition and its actual set of operators supported per particular version. Please can you advise or link where can I find this information?

Thank you.

**Comment by jacky82226** [comment]
Hi @peter197321,
For operators document, we have [Operators.md](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and [Operators-ml.mld](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md). It also mentions when these operators has been supported.
For codebase, you can check [here](https://github.com/onnx/onnx/tree/master/onnx/defs).

**Comment by peter197321** [comment]
OK. Thank you.
BTW when it's declared OpSet _version_  (e.g. nn model is encoded in ONNX operator set 8) how to know what ops are defined per specific version (..7,8,9...)?
And is there anyhow possible to migrate between OpSet versions?

**Comment by jacky82226** [comment]
1. Do you mean that given a OpSet version, list all defined operators of that OpSet version? I am not sure whether we have such a thing. Another related [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md) might be helpful.
2. For migration between OpSet versions, [version_converter](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx) can help.

**Comment by linkerzhang** [comment]
There's no doc explicitly telling you which ops does an opset contain.
https://github.com/onnx/onnx/blob/8089428a2838ac5eaebd3ba14ac14975d60837f2/docs/Operators.md may help you a little bit.

https://github.com/onnx/onnx/blob/master/docs/Versioning.md#example is showing you an example on understanding the "versioning" of operator sets.

btw,

**Comment by peter197321** [comment]
Thank you, it helps.
