### ISSUE TITLE
graph.input do not get all input in model

### ISSUE THREAD

**Issue by guispor7** [onnx/onnx#2868]
# Bug Report

### Describe the bug
download onnx model form :
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov2-coco/model/yolov2-coco-9.onnx
Only one node in graph.input when i print graph.input
I find the tensor name is like xx.xx.xx，may be a reason for this bug

### System information
-  Linux Ubuntu 16.04
- ONNX version 1.7.0
- Python version: 3.5.2

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
graph = model.graph
print(graph.input)

======
[name: "input.1"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 3
      }
      dim {
        dim_value: 416
      }
      dim {
        dim_value: 416
      }
    }
  }
}
]

...
```
- Attach the ONNX model to the issue (where applicable)
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov2-coco/model/yolov2-coco-9.onnx
### Expected behavior
I want to get all inputs in the model 
I can get all the tensors shapes   

### Notes

Any additional information

**Comment by askhade** [comment]
@guispor7 : This model has only 1 input. I don't see any issue here. Do you also want to get all weights\initializers? 
You can get a list of initializers like this:
graph.initializers

For getting shapes:
Inputs : model.graph.input[index].type.tensor_type.shape
Initializers : model.graph.initializer[<index>].dims

**Comment by guispor7** [comment]
> 
> 
> @guispor7 : This model has only 1 input. I don't see any issue here. Do you also want to get all weights\initializers?
> You can get a list of initializers like this:
> graph.initializers
> 
> For getting shapes:
> Inputs : model.graph.input[index].type.tensor_type.shape
> Initializers : model.graph.initializer[].dims

@askhade 
print(model.graph.input[1].type.tensor_type.shape)
IndexError: list index (1) out of range

I mean onnx.load function may be has a bug，can not parse all the input in graph.input array，as a result I can not get all tensors shapes。

**Comment by askhade** [comment]
You are seeing 1 input because only 1 input is present in this model. Initializers are not necessarily added as graph inputs. 
graph.input only contains the inputs to the model... intermediate inputs and initializes are not part of this.  
As you can see here this model only has 1 input "input.1"

![image](https://user-images.githubusercontent.com/6475296/86280239-483f1580-bb90-11ea-9526-69671a5f312d.png)

If this is not what you are referring to then please add more details regarding what your expectation is. Did you expect to see more inputs?

**Comment by guispor7** [comment]
> 
> 
> You are seeing 1 input because this model has only 1 defined input. Initializers are not necessarily added as graph inputs.
> graph.input only contains the inputs to the model... intermediate inputs and initializers are not part of this.
> As you can see here this model only has 1 input "input.1"
> 
> ![image](https://user-images.githubusercontent.com/6475296/86280239-483f1580-bb90-11ea-9526-69671a5f312d.png)
> 
> If this is not what you are referring to then please add more details regarding what your expectation is. Did you expect to see more inputs?

@askhade Thank yor for your answer
My expectation is get all tensor shapes ,but i can't get in this model.
code like this: 
graph = onnx.load(model).graph 

    def extract_shape_info(self, graph):
        def extract_value_info(shape_dict, value_info):
            t = tuple([int(dim.dim_value)
                       for dim in value_info.type.tensor_type.shape.dim])
            if t:
                shape_dict[value_info.name] = t

        for vi in graph.value_info:
            extract_value_info(self._graph_shapes_dict, vi)
        for vi in graph.input:
            extract_value_info(self._graph_shapes_dict, vi)
        for vi in graph.output:
            extract_value_info(self._graph_shapes_dict, vi)

**Comment by askhade** [comment]
Per GraphProto : https://github.com/onnx/onnx/blob/3368834cf0b1f0ab9838cf6bdf78a27299d08187/onnx/onnx.in.proto#L404
"It is optional for a value to appear in value_info list."

If you want to extract shapes for all tensors you need to go through initializers too (model.graph.initializer[<index>].dims)

**Comment by guispor7** [comment]
> 
> 
> Per GraphProto :
> 
> https://github.com/onnx/onnx/blob/3368834cf0b1f0ab9838cf6bdf78a27299d08187/onnx/onnx.in.proto#L404
> 
> "It is optional for a value to appear in value_info list."
> 
> If you want to extract shapes for all tensors you need to go through initializers too (model.graph.initializer[].dims)

@askhade Thank you so mush for your answer.
I want to get all tensor shapes , include node inputs & outputs & weights in fact。
so, i use polish_model funtion to do shape inference,just like this

```
onnx_model = onnx.load(src_model_file)
onnx.checker.check_model(onnx_model) 
onnx_model = onnx.utils.polish_model(onnx_model)
  File "/usr/local/lib/python3.5/dist-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input models.0.conv1.weight is undefined!
```
This fun is go well on other models except the model len(graph.input) is 1 .
Such as https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov2-coco/model/yolov2-coco-9.onnx and https://github.com/onnx/models/blob/master/vision/classification/shufflenet/model/shufflenet-v2-10.onnx

**Comment by guispor7** [comment]
When I use shape_inference function like this
```
onnx_model = onnx.load(src_model_file)
onnx.checker.check_model(onnx_model) 
onnx_model = shape_inference.infer_shapes(onnx_model)
onnx.checker.check_model(onnx_model)
print(onnx_model.graph.value_info[0])
name: "135"
type {
  tensor_type {
    elem_type: 1
  }
}
```
name "135" is the first conv output tensor name，but the value_info has not dims.
so  I cant get output shapes using this funtion.

**Comment by achigeor** [comment]
I have the exact same problem with the following enviroment:
* `pytorch==1.5.1`
* `onnx==1.7.0`

Running `onnx.optimizer.optimize(onnx_model) throws 
```
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input conv1.weight is undefined!
```

conv1.weight is the first layer of the graph.

**Comment by guispor7** [comment]
@askhade do you have some advices?

**Comment by guispor7** [comment]
@askhade do you have any advices

**Comment by TMVector** [comment]
@guispor7 ONNX Runtime has a shape inference script for their Nuphar provider which does more work to try and infer shapes (it does symbolic shape inference), so you could try that. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/nuphar/scripts/symbolic_shape_infer.py

It may be that your model is or isn't feasible for complete shape inference, but **if** you have a **fixed size input** and your **model doesn't use dynamic shape behaviour**, then you can get all the shape information by _running_ the model. If so, you can try running https://github.com/daquexian/onnx-simplifier and then run the Nuphar shape inference again.

---

Regarding the error thrown by the optimizer, it looks like `models.0.conv1.weight` is in the initializers list, so I don't know why the optimizer is falling over. If you don't need the optimizer, try just not using it.

**Comment by guispor7** [comment]
@TMVector Thank you so mush

**Comment by askhade** [comment]
Optimizers are not updated for IRv4 and above .i.e it cant handle the case where initializer is not in graph input. Please don't take any dependency on optimizer.

**Comment by askhade** [comment]
@guispor7 : please reopen if you are still experiencing any issue

**Comment by jinfagang** [comment]
@askhade I have an opposite question...

I now get all nodes shapes when using `model.graph.input`, but what I want is just the real input (the begining of the model).

How to do that?
