### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator SwishJitAutoFn

### ISSUE THREAD

**Issue by DJMeng** [onnx/onnx#2871]
When I exported effcientnet b7 to onnx:
my env is torch 1.5, opset11.and I try other's version of torch or opset, it will meet other problems.
someone meet this error? Please help. Thanks.

**Comment by askhade** [comment]
Please open this issue in pytorch repo.

**Comment by DJMeng** [comment]
Thank you, I have opened it in pytorch repo.
