### ISSUE TITLE
Shape inference doesn't work unless initializer tensors are also listed as inputs

### ISSUE THREAD

**Issue by matteosal** [onnx/onnx#2874]
# Bug Report

### Describe the bug
As title says

### System information
- OS Platform and Distribution: Ubuntu 18.04  
- ONNX version: 1.7 release commit
- Python version: 3.6.9
- GCC/Compiler version: 7.5.0
- CMake version: 3.17.3
- Protobuf version: 3.12

### Reproduction instructions
```
import onnx
from onnx import helper, shape_inference
from onnx import TensorProto

print("************************* Without weights as inputs ******************************")
model_path = "without_weights_as_inputs.onnx"
original_model = original_model = onnx.load(model_path)
onnx.checker.check_model(original_model)

print('Model inputs\n{}'.format(original_model.graph.input))
print('\nValue info before shape inference:\n{}'.format(original_model.graph.value_info))

# Apply shape inference on the model
inferred_model = shape_inference.infer_shapes(original_model)

# Check the model and print Y's shape information
onnx.checker.check_model(inferred_model)
print('\nValue info after shape inference:\n{}'.format(inferred_model.graph.value_info))

print("************************* With weights as inputs ******************************")
model_path = "with_weights_as_inputs.onnx"
original_model = original_model = onnx.load(model_path)
onnx.checker.check_model(original_model)

print('Model inputs\n{}'.format(original_model.graph.input))
print('\nValue info before shape inference:\n{}'.format(original_model.graph.value_info))

# Apply shape inference on the model
inferred_model = shape_inference.infer_shapes(original_model)

# Check the model and print Y's shape information
onnx.checker.check_model(inferred_model)
print('\nValue info after shape inference:\n{}'.format(inferred_model.graph.value_info))
```
Model `"without_weights_as_inputs.onnx"` has tensors in the initializer list that are not listed as inputs. Model `"with_weights_as_inputs.onnx"` has those tensors listed as inputs as well. The above script shows that only model `"with_weights_as_inputs.onnx"` has a successful shape inference, while shapes are not inferred for the first one. The [IR documentation](https://github.com/onnx/onnx/blob/master/docs/IR.md) allows initializer tensor not being listed as inputs, stating that
> When an initializer has the same name as a graph input, it specifies a default value for that input. When an initializer has a name different from all graph inputs, it specifies a constant value.

So it seems that shape inference should work on `"without_weights_as_inputs.onnx"`

- ONNX models
[models.zip](https://github.com/onnx/onnx/files/4858662/models.zip)

### Expected behavior
Shape inference should work on both models

**Comment by jcwchen** [comment]
Hi @matteosal,
Thank you for the detailed explanation. I encountered the same problem by your code. 
I would say it's similar to https://github.com/onnx/onnx/issues/2655 and https://github.com/onnx/onnx/issues/2660.

According to the latest IR.md, shape inference should work for those tensors in the initializer list that are not listed as inputs, but it doesn't now... This issue is waiting for a fix.

**Comment by jcwchen** [comment]
It should be resolved by https://github.com/onnx/onnx/pull/2901. Please reopen it if you still encounter this issue. Thanks.
