### ISSUE TITLE
How to iterate over ONNX model layers and weights in order? 

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2883]
# Ask a Question

I would like to be able to iterate over ONNX layers and weights in order. 

### Question
My understanding is that layers are listed in topologically-sorted order in `model.graph.node` and tensors are provided as a list, sorted alphabetically by name, in `model.graph.initializer`. However, I'm not sure how to match the weights to the nodes. My model was written in PyTorch (which does not support layer naming) and then exported with `torch.onnx.export`, so my weight names are rather obscure. 

```
_model = onnx.load("mobilenet_v1_025.onnx")
for initializer in mode..graph.initializer:
  print(initializer.name)

classifier.bias
classifier.weight
features.0.conv.0.weight
features.0.conv.1.bias
features.0.conv.1.running_mean
features.0.conv.1.running_var
features.0.conv.1.weight
...
```
My node names are something like: 
```
for node in model.graph.node:
  print(node.name)

Pad_0
Conv_1
BatchNormalization_2
Clip_3
Conv_4
BatchNormalization_5
Clip_6
Conv_7
BatchNormalization_8
...
```

### Notes
I am trying to create a pipeline for converting ONNX models to an equivalent CMSIS-NN implementation for deployment on microcontrollers. In order to do this, I would like something like:
```
import onnx
model = onnx.load('model.onnx')
for layer in model.layers:
    weight = layer.weight
    # do something with layer, weight depending on whether layer is a Conv layer, a Batchnorm layer, or a ReLU layer. 
```

**Comment by jcwchen** [comment]
Hi @dtch1997,
According to https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs, 
you can try to link `model.graph.initializer[i].name` with `model.graph.node[j].input`.
The `model.graph.node[j].name` is an optional attribute which means it can be empty for some models.

Hope it helps.

**Comment by dtch1997** [comment]
@jcwchen thanks, this works for me. I will close the issue.

**Comment by travislhopkins** [comment]
Can someone please post a full solution to extracting weights from an onnx model to init a torch model? I can't get the order right and my model has 700+ layers so doing it manually isn't really feasible. Thanks!

**Comment by FelixSchwarz** [comment]
> Can someone please post a full solution to extracting weights from an onnx model to init a torch model? I can't get the order right and my model has 700+ layers so doing it manually isn't really feasible. Thanks!

@travislhopkins An existing ticket is probably not the right place to ask your question but if you are still trying to solve that, you might want to check out https://github.com/ENOT-AutoDL/onnx2torch
