### ISSUE TITLE
"Data_type" in model.graph.initializer

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2887]
# What is the meaning of "data_type" in model.graph.initializer? 

### Question
Print tensor with: 
```
def print_tensors(model):
    for init in model.graph.initializer:
        print(init)
        break
```
The result is something like: 

```
dims: 2
data_type: 1
name: "classifier.bias"
raw_data: "b\000}=\256\354A\275"
```

What does "data_type" mean here? 

### Further information
Is there a better way to print the initializer information for inspection?

**Comment by TMVector** [comment]
The onnx proto definition has a [comment](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L483-L485) to say `data_type` is of type `TensorProto.DataType`, even though it's not expressed in the code itself.  cref. https://github.com/onnx/onnx/blob/master/onnx/mapping.py

You might prefer to view `TensorProto`s as numpy arrays -- `onnx.numpy_helper.to_array(init)`. Then the data type and shape are easily accessible.
