### ISSUE TITLE
Building onnx for ARM 64

### ISSUE THREAD

**Issue by nirantarashwin** [onnx/onnx#2889]
# Ask a Question

These are the instructions given in the README.md to build the onnx package from scratch on ARM 64. 

Build ONNX on ARM 64
If you are building ONNX on an ARM 64 device, please make sure to install the dependencies appropriately.

pip install cython protobuf numpy
sudo apt-get install libprotobuf-dev protobuf-compiler
pip install onnx

My question is, the last step - 'pip install onnx' fails because there is no pre-built wheel for onnx on ARM 64. How do I go about installing the package? Is there any other way to do so? 

Thank you!

**Comment by jcwchen** [comment]
Hi @nirantarashwin,
Similar to https://github.com/onnx/onnx/issues/2791?
You can try building onnx from source. 
It seems that ONNX doesn't have a prebuilt package for ARM... In that case, we should update the document.
@vinitra any comment on this?

**Comment by nirantarashwin** [comment]
> Hi @nirantarashwin,
> Similar to #2791?
> You can try building onnx from source.
> It seems that ONNX doesn't have a prebuilt package for ARM... In that case, we should update the document.
> @vinitra any comment on this?

Yes it is similar to that, but even there the solution given was just to install using pip. 

Can you explain a bit more as to how I can build from source?

**Comment by jcwchen** [comment]
```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install
```
Not sure whether it needs to set some environment settings for ARM. Hope it helps.

**Comment by nirantarashwin** [comment]
> ```
> git clone https://github.com/onnx/onnx.git
> cd onnx
> git submodule update --init --recursive
> python setup.py install
> ```
> 
> Not sure whether it needs to set some environment settings for ARM. Hope it helps.

I tried to do similar to ARM, but it's not so straightforward. If anyone at Microsoft has done it before it would be really helpful.

**Comment by nirantarashwin** [comment]
Was able to build by cross-compiling using the following instruction and modifying 'setup.py' to build for ARM 64. 

$ python3 setup.py install.
