### ISSUE TITLE
How to debug ValidationError in onnx.checker.check_graph? 

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2895]
# How to debug ValidationError in `onnx.checker.check_graph`? 

### Question
I am performing some custom modification of the ONNX graph which involves:
- editing node input/output
- removing some nodes from the graph
- modifying the value of some initializers. 

At the end I create a new graph containing all the changes and make a new model from the graph. After I perform this modification I tried to use `onnx.checker.check_graph` to check the new graph, however it throws a `ValidationError`. How can I debug this error? The error message is not informative. 

### Further information
More specifically, I am removing BatchNormalization nodes from the graph by folding them into the previous Conv node. To do so I do:
- Remove BN node from graph using `graph.node.remove`
- Modify preceding node input and output using `inp_node.input.remove(bn_node.input[0])`,  `inp_node.extend([bn_node.output])`
- Create a new list of initializers with modified conv weight and bias, and remove the batchnorm initializers. 

The original graph looks like this: 
```
graph torch-jit-export (
  %input.1[FLOAT, 10x3x128x128]
) initializers (
  %0.weight[FLOAT, 32x3x3x3]
  %1.bias[FLOAT, 32]
  %1.running_mean[FLOAT, 32]
  %1.running_var[FLOAT, 32]
  %1.weight[FLOAT, 32]
  %5.bias[FLOAT, 2]
  %5.weight[FLOAT, 2x32]
) {
  %9 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%input.1, %0.weight)
  %10 = BatchNormalization[epsilon = 9.99999974737875e-06, momentum = 0.899999976158142](%9, %1.weight, %1.bias, %1.running_mean, %1.running_var)
  %11 = Relu(%10)
  %12 = Pad[mode = 'constant', pads = [0, 0, 0, 0, 0, 0, 0, 0], value = 0](%11)
  %13 = AveragePool[kernel_shape = [128, 128], pads = [0, 0, 0, 0], strides = [1, 1]](%12)
  %14 = Flatten[axis = 1](%13)
  %15 = Gemm[alpha = 1, beta = 1, transB = 1](%14, %5.weight, %5.bias)
  return %15
}
```

The modified graph looks like this: 
```
graph torch-jit-export (
  %input.1[FLOAT, 10x3x128x128]
) initializers (
  %0.weight[FLOAT, 32x3x3x3]
  %5.bias[FLOAT, 2]
  %5.weight[FLOAT, 2x32]
  %Conv_0.bias[FLOAT, 32]
) {
  %10 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [1, 1, 1, 1], strides = [1, 1]](%input.1, %0.weight, %Conv_0.bias)
  %11 = Relu(%10)
  %12 = Pad[mode = 'constant', pads = [0, 0, 0, 0, 0, 0, 0, 0], value = 0](%11)
  %13 = AveragePool[kernel_shape = [128, 128], pads = [0, 0, 0, 0], strides = [1, 1]](%12)
  %14 = Flatten[axis = 1](%13)
  %15 = Gemm[alpha = 1, beta = 1, transB = 1](%14, %5.weight, %5.bias)
  return %15
}
```

**Comment by askhade** [comment]
@dtch1997 : Can you paste the validation error that you are seeing?

**Comment by dtch1997** [comment]
@askhade that's just it, the Python program fails with just the singular output "ValidationError" and no further information. 

At the moment I have found a workaround for my use case, so I am closing the issue.
