### ISSUE TITLE
ONNX shape inference does not infer shapes

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2903]
# Bug Report

### Describe the bug
`onnx.shape_inference.infer_shapes` does not correctly infer shape of each layer. 

### System information
- OS Platform and Distribution: Windows 10
- ONNX version: 1.7.0
- Python version: 3.7.4

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
model = onnx.load("models/conv_dummy.onnx")
onnx.checker.check_model(model)
inferred_model = onnx.shape_inference.infer_shapes(model)
print(inferred_model.graph.value_info)
```
output: 
```
[name: "9"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "10"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "11"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "12"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "13"
type {
  tensor_type {
    elem_type: 1
  }
}
, name: "14"
type {
  tensor_type {
    elem_type: 1
  }
}
]
```
Model file: [models.zip](https://github.com/onnx/onnx/files/4927215/models.zip)

### Expected behavior
Expected each entry in `model.graph.value_info` to have tensor shape field which tells me the shape of that layer. 

### Notes

Model was exported from PyTorch using `torch.onnx.export`

**Comment by jcwchen** [comment]
Hi @dtch1997,
It seems like a IR gap issue. It should be fixed by https://github.com/onnx/onnx/pull/2901.
I got the following result by this PR:
```
[name: "9"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
      dim {
        dim_value: 128
      }
      dim {
        dim_value: 128
      }
    }
  }
}
, name: "10"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
      dim {
        dim_value: 128
      }
      dim {
        dim_value: 128
      }
    }
  }
}
, name: "11"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
      dim {
        dim_value: 128
      }
      dim {
        dim_value: 128
      }
    }
  }
}
, name: "12"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
      dim {
        dim_value: 128
      }
      dim {
        dim_value: 128
      }
    }
  }
}
, name: "13"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 1
      }
    }
  }
}
, name: "14"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 10
      }
      dim {
        dim_value: 32
      }
    }
  }
}
]
```

**Comment by dtch1997** [comment]
@jcwchen I'm having trouble building from source (as seen in #2916). is there any workaround I can use while I wait for this to be fixed? E.g. use an older ONNX version or older opset, or manually add all initializer to model input

**Comment by jcwchen** [comment]
For temporary solution, you could manually add all initializer to model input like @TMVector mentioned [here](https://github.com/onnx/onnx/issues/2660). Thanks.

**Comment by dtch1997** [comment]
Good workaround. Adding a line `add_value_info_for_constants(model)` before shape inference runs correctly.

**Comment by jcwchen** [comment]
Hi @dtch1997,
The PR https://github.com/onnx/onnx/pull/2901 has been merged. Now you can solve this issue by using the master branch of onnx. Thanks.

**Comment by deepak0896** [comment]
Hi @jcwchen ,
I'm on the latest branch of onnx but I'm still facing this issue. I'm using shufflenet onnx model which you can get from [here](https://github.com/onnx/models/blob/master/vision/classification/shufflenet/model/shufflenet-v2-10.onnx).

**Comment by jcwchen** [comment]
Hi @deepak0896,
Did you use onnx 1.8? I can successfully shape infer with shufflenet.

**Comment by deepak0896** [comment]
Hi @jcwchen,
yes I'm using onnx 1.8. And I'm getting inferred shapes for some of the nodes not all.

**Comment by jcwchen** [comment]
Thank you for the details. I found the shapes of nodes after every Split node will be missing... There might be a shape inference bug for Split-10... Perhaps https://github.com/onnx/onnx/pull/2549 can help

**Comment by jcwchen** [comment]
I have confirmed that PR can help and you can try that first. I will push that PR forward. Thanks.

**Comment by ryanf123** [comment]
I have tried all of the solutions mentioned and I'm still facing the same issue "IndexError: Input hidden_x1.0.weight is undefined!" with the ONNX model [here](https://drive.google.com/file/d/150M6g2EAzlyhhz2WVKHcBL5862XhO7nC/view?usp=sharing). I'm on ONNX 1.8, do you know what I might be doing wrong?

**Comment by jcwchen** [comment]
> I have tried all of the solutions mentioned and I'm still facing the same issue "IndexError: Input hidden_x1.0.weight is undefined!" with the ONNX model [here](https://drive.google.com/file/d/150M6g2EAzlyhhz2WVKHcBL5862XhO7nC/view?usp=sharing). I'm on ONNX 1.8, do you know what I might be doing wrong?

Actually I can `onnx.shape_inference.infer_shapes` sho_filtter41 with ONNX 1.8. Are you sure you are using ONNX 1.8? Maybe try `pip uninstall -y onnx` several times and `pip install onnx==1.8.0` again. Thank you.

**Comment by jcwchen** [comment]
Hi @nicklhy,
I guess something might be wrong and shape inference was silent -- could you please try `onnx.shape_inference.infer_shapes("your_model.onnx", strict_mode=True)`? If there is no error message, could you please provide the model for me to take a closer look? Thank you.

**Comment by jcwchen** [comment]
Thanks for providing the link -- It seem that I cannot open it somehow. Will try it later

**Comment by nicklhy** [comment]
> Thanks for providing the link -- It seem that I cannot open it somehow. Will try it later

just execute `wget http://aivc.ks3-cn-beijing.ksyun.com/public_data/onnx_shape_infer_bug.tgz`

**Comment by leimao** [comment]
@jcwchen Quick question, is there any way to remove the shape inference information from an ONNX model? Thank you.

**Comment by jcwchen** [comment]
@leimao perhaps try something like `your_model.graph.ClearField('value_info')`

**Comment by leimao** [comment]
> .ClearField('value_info')

That does work. Thank you. Perhaps you guys can consider adding this interface to ONNX Python API.
I suggest we can do
```
model.graph.value_info.clear()
```
which is more similar to Python list syntax, given `value_info` already has `pop` and `append` methods.

**Comment by jcwchen** [comment]
Actually the utilities here come from protobuf since it's a model proto. Perhaps you can raise this concern there. Thank you for the suggestion.

**Comment by mananta** [comment]
The shape inference problem still persists as lot of shapes are missing when trying to parse the gpt2 onnx model from [https://github.com/onnx/models/blob/main/text/machine_comprehension/gpt-2/README.md](url) . I am using onnx version 1.13.1 . Perhaps the problem is about dynamic shape inference. Can anyone suggest any way-out to tackle dynamic shape inference?
