### ISSUE TITLE
Release automation enhancements

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx#2904]
The following are release automation enhancements to be worked on.

1. move building Windows wheel files from ONNX repo (Actions) to wheel-builder repo, https://github.com/onnx/wheel-builder
2. in wheel-builder repo, replace non-functional AppVeyor integration with Azure Pipelines for Windows builds
3. in wheel-builder repo, update the supported environment and software versions
4. in onnx-feedstock repo, https://github.com/conda-forge/onnx-feedstock, enable Windows packaging for ONNX conda install

This issue is to bring awareness to community and encourage developers to contribute to these enhancements.

**Comment by snnn** [comment]
I suggest ONNX should prefer to use Github Actions than Azure Pipelines when possible.  The tech underneath of these two are the same. But, I think Github Actions is the future.  And, by reducing one extra component, it will have less chance to fail. Based on my experience, the comunication channel between Azure DevOps and github isn't that smooth, it can often lose notifications.  
Also, please note that for public projects like this, Azure DevOps only allow you have 10 concurrent running build jobs,  you can't even buy more if you hit the limit.

**Comment by chinhuang007** [comment]
@snnn Are you suggesting we continue to use the current way to create Windows wheel files in Github Actions and then manually upload them to TestPypi and Pypi? That could certainly be an option.

How about the Linux and OSX builds? Do you think that should also be handled in Github Actions? If so, do you suggest we totally stop the wheel-builder project and do all release builds in Github?

Thanks for your input!

**Comment by snnn** [comment]
> @snnn Are you suggesting we continue to use the current way to create Windows wheel files in Github Actions and then manually upload them to TestPypi and Pypi? That could certainly be an option.
> 

Yes. That's my suggestion.

> How about the Linux and OSX builds? Do you think that should also be handled in Github Actions? If so, do you suggest we totally stop the wheel-builder project and do all release builds in Github?
> 

Github Action support all these 3 platform, so it won't be an issue. I don't know why there is a separated "wheel-builder" repo, I haven't done any ONNX release, so my knowledge is limited. Sorry.

**Comment by chinhuang007** [comment]
@snnn The wheel-builder project is to automate the builds for various python versions and operating systems, and also upload wheel files to TestPypi and Pypi. Please take a look, https://github.com/onnx/wheel-builder.

Based on your comments, we should be able to do all builds in Github Action. Then the release manager might need to upload the wheel files manually.

The next release working group meeting is 10-10:30 am Pacific Time 7/29/2020, https://lists.lfai.foundation/g/onnx-wg-release/viewevent?eventid=866498&calstart=2020-07-29. It will be very helpful if you can attend so we could discuss and identify the ONNX builds option for 1.8.

**Comment by askhade** [comment]
Closing this issue. We have now moved all build pipelines to github actions in onnx repo and updated the relevant library versions.
Windows builds for conda are also fixed and we have started releasing those packages as well.
