### ISSUE TITLE
ImportError: cannot import name 'ONNX_ML'

### ISSUE THREAD

**Issue by canozcivelek** [onnx/onnx#2907]
# Where does this originate from?

- I built ONNX from source on my Jetson Nano, the installation completed without error. However when I import onnx, it gives: from .onnx_cpp2py_export import ONNX_ML
ImportError: cannot import name 'ONNX_ML'

Any suggestions? Thanks a lot!

**Comment by SophieFeng** [comment]
I also met this problem, do you solved?

**Comment by lyp0413** [comment]
@SophieFeng @canozcivelek 
How about trying another working directory?

**Comment by anilsathyan7** [comment]
Facing same issue in master branch....

**Comment by arashb** [comment]
the same issue in `master` and  `rel-1.8.0 branch`

**Comment by arashb** [comment]
> Facing same issue in master branch....

@anilsathyan7 @SophieFeng setting `ONNX_ML=1` env. variable before building ONNX fixed the issue for me. see also the [here ](https://github.com/onnx/onnx#linux-and-macos)

**Comment by illiad-tigerdhl** [comment]
@arashb I setting ONNX_ML=1，but also can’t fix it, what can i do to fix it ?

**Comment by leo-paz** [comment]
@arashb I did the same thing but still seeing this error

**Comment by whcjb** [comment]
the same error, build from source, set onnx_ml=1, how to resolve, someone help?

**Comment by whcjb** [comment]
it's path problem, when cd onnx/onnx, it works. pip install may auto set the path. but when it comes to building from source, how to set the path ?

**Comment by xiafeimao** [comment]
> it's path problem, when cd onnx/onnx, it works. pip install may auto set the path. but when it comes to building from source, how to set the path ?

Yes, when switching to other paths instead of run at the onnx/ root path,  then everything is OK

**Comment by 1342757815zhs** [comment]
linux 运行中模型出现cannot import name ONNX_ML from onnx.onnx_cpp2py_export，how to solve it? please!!!
![image](https://github.com/user-attachments/assets/74dd8f69-4d6a-46b8-af88-0080b81e27b7)
