### ISSUE TITLE
Cannot build ONNX 1.7.0 from source in Anaconda

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2916]
# Bug Report

### Describe the bug
Building ONNX 1.7.0 from source with Anaconda fails with error.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Windows 10
- ONNX version (*e.g. 1.7*):  1.7.0
- Python version: 3.8.4
- Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
- Compiler version: 19.25.28612.0
- CMake version: 3.17.2
- Protobuf version: 3.9
- Visual Studio version (if applicable): 

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
# Use conda-forge protobuf
conda install -c conda-forge protobuf=3.12.3 numpy

# Get ONNX
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive

# Set environment variable for ONNX to use protobuf shared lib
set CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"

# Build ONNX
python setup.py install
```

### Expected behavior
ONNX is correctly built from source

### Notes

[Full stack trace](https://github.com/onnx/onnx/files/4959542/onnx_anaconda_build_stack_trace.txt)

**Comment by jcwchen** [comment]
Hi @dtch1997,
I just installed onnx from source on Windows from scratch and it worked. Therefore, this problem looks like an environment issue.
To build onnx from source in Anaconda, please follow the code [here](https://github.com/onnx/onnx#build-onnx-on-windows-with-anaconda), which is slightly different from yours. (Currently using protobuf 3.11.3 might be better)

Other than that, don't forget to uninstall your previous onnx installation first if you have one.

**Comment by dtch1997** [comment]
I did not resolve this issue but I'm going to close the issue as I don't need to build from source anymore. Perhaps it can be chalked up to some problem unique to my computer.
