### ISSUE TITLE
How assign a value to Tensor

### ISSUE THREAD

**Issue by Lisicong9203** [onnx/onnx#2919]
### Question
In pytorch we can assign value to Tensor like this (output is a torch tensor):
`output[i,:,0] = i`

How can i implement this in onnx?

**Comment by liqunfu** [comment]
ONNX does not have assign operator. However, if you convert your PyTorch model with that assign operation to ONNX, you shall be able to see how assign operation is constructed in ONNX. It may not be as simple as using one or two ONNX ops.
