### ISSUE TITLE
What is the layout of weights for Conv and Gemm nodes? 

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2926]
# What is the layout of weights for ONNX Conv and Gemm nodes? 

### Question
I need to convert a model from ONNX to CMSIS-NN. One of the steps is to reshape the weight layout into their desired weight layout. 

For example: CMSIS-NN expects convolutional weights to be in `(in_channel, ker_x_dim, ker_y_dim, out_channel)` layout. If I know the ONNX weight layout, I can use `np.transpose` to correctly convert the layout, but I can't find documentation on ONNX weight layout.

**Comment by jcwchen** [comment]
Hi @dtch1997,
https://github.com/onnx/onnx/blob/master/docs/Operators.md#conv

> The weight tensor that will be used in the convolutions; has size (M x C/group x kH x kW), where C is the number of channels, and kH and kW are the height and width of the kernel, and M is the number of feature maps.

https://github.com/onnx/onnx/blob/master/docs/Operators.md#gemm
 Do you mean attributes?

Examples can also help you to understand the layout. Thanks.

**Comment by dtch1997** [comment]
@jcwchen works for me. thanks!
