### ISSUE TITLE
Canonical way to add weights / biases?

### ISSUE THREAD

**Issue by liob** [onnx/onnx#2938]
What is the canonical way to add weights and biases to an onnx graph, i.e., for a conv layer? When I look at onnx files produced by torch.onnx, it seems, that initializers are used. However, I am unable to find a concise example.

How would one add weight and bias to the conv layer in the following example (mostly ripped from [onnx.ai]):

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import onnx
from onnx import helper
from onnx import TensorProto

# Create one input (ValueInfoProto)
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [None, 1, 224, 224])

# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [None, 16, 224, 224])

# Create a node (NodeProto)
node_def = helper.make_node(
    'Conv', # node name
    ['X', 'W', 'B'],  # inputs
    ['Y'],  # outputs
    auto_pad = 'VALID'
)

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [node_def],
    'test-model',
    [X],
    [Y],
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def, producer_name='onnx-example')
model_def.opset_import[0].version = 10

print('The model is:\n{}'.format(model_def))
onnx.checker.check_model(model_def)

onnx.save(model_def, 'test.onnx')
```

[onnx.ai]: http://onnx.ai/sklearn-onnx/auto_examples/plot_onnx_operators.html

**Comment by liob** [comment]
I think, I can at least partially answer my own question. In the [IR.md] document I found the following snippet about initializers:
 > When an initializer has the same name as a graph input, it specifies a default value for that input. When an initializer has a name different from all graph inputs, it specifies a constant value. It may not be in topological order.

This appears to produce similar results to the torch.onnx module. This is the amended example code:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import onnx
from onnx import helper
from onnx import TensorProto

# Create one input (ValueInfoProto)
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [None, 1, 224, 224])

# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [None, 16, 224, 224])

# Create a node (NodeProto)
node_def = helper.make_node(
    'Conv', # node name
    ['X', 'W'],  # inputs (B is optional and dropped for conciseness)
    ['Y'],  # outputs
    auto_pad = 'VALID'
)

# (M x C/group x kH x kW), where C is the number of channels, and kH and kW are 
# the height and width of the kernel, and M is the number of feature maps.
data = np.random.randn(5,2,3,3)
weight_init = onnx.helper.make_tensor(
            name='W',
            data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[data.dtype],
            dims=data.shape,
            vals=data.flatten())

# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [node_def],
    'test-model',
    [X],
    [Y],
    initializer=[weight_init]
)

# Create the model (ModelProto)
model_def = helper.make_model(graph_def, producer_name='onnx-example')
model_def.opset_import[0].version = 10

print('The model is:\n{}'.format(model_def))
onnx.checker.check_model(model_def)

onnx.save(model_def, 'test.onnx')
```

However, one question remains, is this actually the canonical way to do this?

[IR.md]: https://github.com/onnx/onnx/blob/master/docs/IR.md

**Comment by liqunfu** [comment]
Usually an onnx model is created by onnx converters form PyTorch and TensorFlow, etc. What you did in your code is correct if you want to build an onnx model directly in stead of from an AI framework. you may find examples at:
https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/conv.py

**Comment by liob** [comment]
@liqunfu thanks. I am using tf.keras. However, i was unhappy with the results of keras2onnx (high amount of unnecessary transpose operations). Therefore, I created yet another keras to onnx converter: https://github.com/liob/naive_k2onnx
