### ISSUE TITLE
Export parameters for dynamic and multiple inputs

### ISSUE THREAD

**Issue by ApurvaDani** [onnx/onnx#2939]
# Ask a Question

### Question

I am trying to export a model which takes two inputs where both the inputs can be of different size. Also the output is of varying size. 
How should I provide dynamic axes value to the export function?

This is what I tried:

text = torch.LongTensor(1, 39).fill_(0).to(device)
image = torch.randn(1, 1, 64, 384, requires_grad=True)

torch.onnx.export(model,          
                  (image, text),               
                  "model_onnx.onnx", 
                  export_params=True,       
                  opset_version=11,         
                  do_constant_folding=True, 
                  input_names = ['input1','input2'],  
                  output_names = ['output'],
                  dynamic_axes = {'input1':{0:'batch_size',2:'height', 3:'width'}, 'output':{0:'batch_size'}})

But it throws an error:
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by liqunfu** [comment]
take a look at example:
https://github.com/pytorch/pytorch/blob/326d777e5384a621306330b5af0f2857843fe544/test/onnx/test_operators.py#L277

**Comment by prasanthpul** [comment]
If there are further questions, suggest using the PyTorch Github, since this is specific to PyTorch implementation
