### ISSUE TITLE
how to generate signature.json and sunset.txt from model.ONNX

### ISSUE THREAD

**Issue by quantum-fusion** [onnx/onnx#2944]
# Ask a Question

### Question
Explain your question here.

I am interested in MxNet model server, and had a question: 
https://github.com/onnx/tutorials/blob/master/tutorials/ONNXMXNetServer.ipynb

If we have an already known ONNX model like squeeznet.onnx from the ModelZoo.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

The missing files needed are:
signature.json - defining the input and output of the model
synset.txt - defining the set of classes the model was trained on, and returned by the model

How do we generate these two files from an ONNX file?  

### Notes
Any additional information, code snippets.

**Comment by liqunfu** [comment]
Please create the issue in onnx/tutorials.
