### ISSUE TITLE
The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

### ISSUE THREAD

**Issue by ak9250** [onnx/onnx#2949]
I have a exported version of this pytorch weight in onnx https://github.com/minivision-ai/photo2cartoon

when i try to load the model for inference i get The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

**Comment by liqunfu** [comment]
may you please attach a minimal repo and exact error message? thanks

**Comment by ak9250** [comment]
@liqunfu I think its related to the output dimensions not matching the input dimensions

**Comment by jcwchen** [comment]
Same as https://github.com/onnx/onnx/issues/2956.
