### ISSUE TITLE
Transform from .pth failed.

### ISSUE THREAD

**Issue by Joevaen** [onnx/onnx#2951]
Hi,

### Question
Below picture is the result of a transformation from pth to onnx who are shown in Neutron:

![image](https://user-images.githubusercontent.com/46133615/89705108-ffe3f600-d98c-11ea-9a06-b441cd5df972.png)

My origin network of .pth includes conv3d and the input data is 5-dim. Can the onnx do the operations on conv3d?  
SOS!

**Comment by jcwchen** [comment]
Hi @Joevaen,
As mentioned in the [document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#conv-11), I would say the original Conv operator does support multi-dimensional input.
Do you encounter any error with that onnx model?

**Comment by Joevaen** [comment]
Thanks, Chen.
Sorry I didn't read the document, I will ask for help on the pytorch repo. :)
