### ISSUE TITLE
The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

### ISSUE THREAD

**Issue by ak9250** [onnx/onnx#2956]
get this error when loading onnx model for inference

The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

here is the model 

https://drive.google.com/file/d/1ilvj0sOtK2M_h7JEPPpjqCWP7d8cxuyy/view

**Comment by jcwchen** [comment]
Hi @ak9250,
Thank you for providing the model.
However, I can `onnx.load`, `onnx.checker.check_model` or `onnxruntime.InferenceSession` this model.
Could you provide the code to reproduce your error? Thanks.

**Comment by ak9250** [comment]
@jcwchen hi were you able to run inference with the model and get the output image?

**Comment by jcwchen** [comment]
I just used:
```
import onnx
import onnxruntime
onnx.load('photo2cartoon_b2a5.onnx')
onnx.checker.check_model('photo2cartoon_b2a5.onnx')
onnxruntime.InferenceSession('photo2cartoon_b2a5.onnx')
```
It seems that they work normally from these APIs.

**Comment by ak9250** [comment]
@jcwchen so it might be due to negative operations arent allowed I took that out and torch.expand and now get Shape mismatch in element-wise layer '1243'

**Comment by ak9250** [comment]
@jcwchen here is the link to the updated file
https://drive.google.com/file/d/19_17XnIbLV0cXld39sHUotdoXPkiT3VA/view?usp=sharing

**Comment by jcwchen** [comment]
Hi @ak9250,
The updated model is workable by these APIs as well.
I took a look at the updated model and the '1243' layer looks normal to me.
It is quite hard to debug without the reproduce information.

**Comment by ak9250** [comment]
@jcwchen Hi, this is the repo i am using https://github.com/minivision-ai/photo2cartoon, I think it is due to some unsupported operations

**Comment by jcwchen** [comment]
It's hard to reproduce this error with a third-party app and I am not sure whether this error message comes from onnx because I cannot find this message in the code.
At least I can do all the APIs normally by onnx with your model so I would say onnx should be good in this case.
For those unsupported operations, you can check the details of supported operators [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md).
Sorry that I couldn't be more helpful.

**Comment by rtolps** [comment]
I get this issue too. Does anyone know what's causing it?

**Comment by jcwchen** [comment]
Hi @rtolps,
Do you have the model and code to repro this error? Thanks.

**Comment by rtolps** [comment]
@jcwchen Here's the code/ google collab notebook: https://github.com/rtolps/Cats2dogs_ONNX
Here's the model that I generated from it: https://drive.google.com/file/d/1cAOpqqAqrA46HPEtlLXhD5eI-OLSOLzf/view?usp=sharing

**Comment by jcwchen** [comment]
Thanks for providing the information. Where did you encounter this error? It can be successfully onnx.shape_inference and onnxruntime.InferenceSession from my end.

**Comment by rtolps** [comment]
@jcwchen It's an error that Snapchat's Lens Studio is throwing up. I have no idea what it means? Hoping this thread discovered something.

**Comment by jcwchen** [comment]
It seems to me that it's an issue from their side... ONNX even doesn't have such error message. At least this model can be successfully onnx.shape_inference and onnxruntime.InferenceSession so I will suggest you to contact Snap's team to get the best help. Sorry that I cannot be more helpful.
