### ISSUE TITLE
Support adaptive pooling operators

### ISSUE THREAD

**Issue by ghost** [onnx/onnx#2957]
## Note: A pull request is welcome

-------------------------

adaptive_avg_pool2d from Pytorch

### Describe the operator
https://pytorch.org/docs/stable/generated/torch.nn.AdaptiveAvgPool2d.html

### Can this operator be constructed using existing onnx operators?
No, see https://github.com/pytorch/pytorch/issues/42653

### Is this operator used by any model currently? Which one?
https://github.com/search?q=AdaptiveAvgPool2d&type=Code

### Are you willing to contribute it? (Y/N)
Y

### Notes
Any additional information

**Comment by manesioz** [comment]
Any updates on this? Is it up for grabs or is someone assigned?

**Comment by luvwinnie** [comment]
Any update on this?

**Comment by Zha0q1** [comment]
This is a pretty important op, is it going to be included in the next op set? @jcwchen

**Comment by jcwchen** [comment]
As far as I know, no one is working on this right now. If anyone is interested, feel free to pick it up. Thank you!

**Comment by niffler92** [comment]
+1

**Comment by listener17** [comment]
Hi! I would like to have this operator. When can I expect this to happen?

**Comment by Kromtar** [comment]
Any new ?

**Comment by RUIXUEZHAOFENGNIAN** [comment]
Any new ?

**Comment by Fleyderer** [comment]
+1

**Comment by justinchuby** [comment]
Marked for discussion for 1.16

**Comment by lee101** [comment]
+1

**Comment by justinchuby** [comment]
We welcome a pull request for this issue.

**Comment by thiagocrepaldi** [comment]
ONNX team does not plan to add this oeprator, but contributions are welcome.
