### ISSUE TITLE
Address recommendations from LF scan

### ISSUE THREAD

**Issue by prasanthpul** [onnx/onnx#2960]
https://lfscanning.org/reports/lfai/onnx-2020-06-01-21841503-3b22-47aa-8f07-eab748b0ade0.html
https://lfscanning.org/reports/lfai/onnx-2020-06-01-21841503-3b22-47aa-8f07-eab748b0ade0.xlsx

**Comment by askhade** [comment]
@prasanthpul Can you address these?
