### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: convolution_W in initializer but not in graph input

### ISSUE THREAD

**Issue by wonderzy** [onnx/onnx#2967]
convert from caffe model to tensorflow model
tensorflow version 2.1.0
onnx version 1.7.0

Successfully convert from caffe to coreml to onnx using [caffe2onnx](https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/caffe_coreml_onnx.ipynb)
When using [onnx2tensorflow](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb), i got the error:
```
Traceback (most recent call last):
  File "convert_caffe2onnx2tf.py", line 36, in <module>
    tf_exp = prepare(onnx_model)  # prepare tf representation
  File "/data6/TF_quant/onnx-tensorflow/onnx_tf/backend.py", line 62, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/data5/workshop/anaconda3/lib/python3.6/site-packages/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/data5/workshop/anaconda3/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: convolution_W in initializer but not in graph input
```
Anything to resolve this?

**Comment by jcwchen** [comment]
Hi @wonderzy,
Based on the error message, I guess maybe it's related to this issue https://github.com/onnx/onnx/issues/2655.
It has been fixed by this PR https://github.com/onnx/onnx/pull/2901.
You can try to convert it again with the master branch of onnx.

If it still cannot be fixed, I will suggest you to open an issue in onnx-tensorflow to get the best help since this error occurs in the converter. Thank you.

**Comment by jcwchen** [comment]
Has redirected to the proper repo.

**Comment by padmasreenagarajan** [comment]
@jcwchen Even i am facing the same error with YOLOv3 model when converting onnx to tensorflow.
I have onnx 1.3.0
onnx-tf 1.3.0
tensorflow 1.13.1
Torch 1.3.0
Could u pls guide me in solving this?

**Comment by jcwchen** [comment]
@padmasreenagarajan Using the latest onnx from master branch might help.

**Comment by padmasreenagarajan** [comment]
But, @jcwchen .......i need onnx=1.3.0 only for my inference..

**Comment by padmasreenagarajan** [comment]
Hi @jcwchen ,
I tried using master branch but it worked well for Torch==1.3.0 but failed on Torch==1.5.0 
any idea on this?
The version history of modules are as follows..
onnx==1.6.0
onnx-tf==1.6.0 (not available through pip install;so installed from master branch)
tensorflow==1.15.0
torch==1.3.0
torchvision==0.4.0
opset==11

**Comment by jcwchen** [comment]
It's better to use the master branch of onnx with the latest pytorch (>=1.6.0), but I think the master branch of onnx is compatible with pytorch (1.5.0) as well. What is the exact failure?

**Comment by padmasreenagarajan** [comment]
Yeah...Im getting this error with Torch==1.5.0

**Shape must be rank 1 but is rank 2 for 'Tile_229' (op: 'Tile') with input shapes: [19], [2]**

Also,i have few more doubts on Tensorflow..Could u help me in solving this? @jcwchen 

Im trying to convert Mobilenetv3 onnx model to tensorflow.
I need tensorflow==1.12.0 for my inferencing.
I searched all over to find the onnx and onnx-tf versions corresponding to tensorflow==1.12.0

Could you please suggest me the compatible versions of onnx,onnx-tf and torch for my required tensorflow version?

**Comment by jcwchen** [comment]
So this error occurs while using onnx-tensorflow? (This error message comes from tensorflow)
If so, I suggest you open an issue under onnx-tensorflow to get the best help. I am not familiar with onnx-tensorflow and you can check with onnx-tensroflow folks to understand which version is compatible with `tensorflow==1.12.0`.
As far as I know, both tensorflow and onnx support Mobilenetv3 and yolov3 (at least for the latest version)... If an error happens in the converter, I would say it is more likely a converter issue. Sorry that I cannot be more helpful.

**Comment by padmasreenagarajan** [comment]
No @jcwchen ..
This error occurred with torch==1.5.0 for YOLOv3 model
The tensorflow query i posted is regarding Mobilenetv3 which is completely different.
Anyways i will post this query under onnx-tensorflow section.
Thanks for your time and reply!
Thank you @jcwchen

**Comment by pauldog** [comment]
Got the same error with emotion-ferplus-8.onnx 

onnx::power_exponent::4  in initializer but not in graph input
