### ISSUE TITLE
why deprecate Upsample layer

### ISSUE THREAD

**Issue by hnuhchen** [onnx/onnx#2968]
# Ask a Question

### Question
hello, i want to know why you deprecate upsample layer in onnx-1.7.0(i want to use upsample in opset-11).
And what is difference between upsample(opset-7) and upsample(opset-9)? 

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by faxu** [comment]
Functionality of upsample should be covered by [resize-11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#resize-11)

See:
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#upsample-7
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#upsample-9

**Comment by hnuhchen** [comment]
Got it. Thank you.
