### ISSUE TITLE
please generalize Pad's `value` to `constant_values` as NumPy does

### ISSUE THREAD

**Issue by rryan** [onnx/onnx#297]
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.pad.html

Instead of a single fill value for constant mode, it's useful to be able to customize the front/back pad value per axis.

**Comment by dzhulgakov** [comment]
I'm just curious what are the common use cases for it. We're trying to cover a core subset first with ONNX in order to better map to different hardware libraries and I haven't seen broad support for this style of padding there.
