### ISSUE TITLE
Exporting the operator hardsigmoid to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by glenn-jocher** [onnx/onnx#2970]
# New Operator
hardsigmoid

### Describe the operator
hardsigmoid can be used to create hardswish activations used by mobilenetv3 and [YOLOv5](https://github.com/ultralytics/yolov5). There is a hardswish op request open as well here: https://github.com/onnx/onnx/issues/2728

```python
class HardSwish(nn.Module):  # https://arxiv.org/pdf/1905.02244.pdf
    @staticmethod
    def forward(x):
        # return x * F.hardtanh(x + 3, 0., 6.) / 6.
        return x * F.hardsigmoid(x)
```

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?
Yes, but adding it as a custom function requires more export steps and may result in a more complicated final model.

### Is this operator used by any model currently? Which one?
Mobilenetv3 and [YOLOv5](https://github.com/ultralytics/yolov5) use hardswish, which can be created by x = x * hardsigmoid(x).

### Are you willing to contribute it? (Y/N)
N

### Notes
Any additional information

**Comment by ytaous** [comment]
@faxu - enhancement.

**Comment by askhade** [comment]
HardSigmoid - https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSigmoid
Hardswish was recently added : https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSwish It will be part of ONNX 1.9 release

**Comment by glenn-jocher** [comment]
@askhade awesome thank you! Is there support for exporting pytorch nn.SiLU() to ONNX operator planned for the future also?
