### ISSUE TITLE
MaxPool documentation 

### ISSUE THREAD

**Issue by kraiskil** [onnx/onnx#2971]
I am trying to implement a backend of onnx, and am having trouble interpreting [MaxPool documentation](https://github.com/onnx/onnx/blob/master/docs/Operators.md#MaxPool).
Particularly, the 2d_ceil-example/backend test, copied below: 
```
node = onnx.helper.make_node(
    'MaxPool',
    inputs=['x'],
    outputs=['y'],
    kernel_shape=[3, 3],
    strides=[2, 2],
    ceil_mode=True
)
x = np.array([[[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
]]]).astype(np.float32)
y = np.array([[[
    [11, 12],
    [15, 16]]]]).astype(np.float32)
```

Since the kernel size is 3x3, and strides 2x2, does that not mean that the poolings are:
```
 1  2  3 |  3  4  X
 5  6  7 |  7  8  X
 9 10 11 | 11 12  X
---------+---------
 9 10 11 | 11 12  X
13 14 15 | 15 16  X
 X  X  X |  X  X  X
```
If calculated like this, 3 of the poolings would index outside of the input.

Since `auto_pad` is not set (set to NOTSET) it "_means explicit padding is used_". 
And since `pads` attribute is not given, "_If not present, the padding defaults to 0 along start and end of each spatial axis._". I.e. the specification says to explicitly use zero padding.

What am I misunderstanding here?

**Comment by kraiskil** [comment]
Looks like this is a duplicate of #2927, which is labeled 'bug'.

**Comment by askhade** [comment]
@kraiskil : Yes in this case 0 padding will be used. As the documentation for pads says " If not present, the padding defaults to 0 along start and end of each spatial axis." in this case since pads are not present they should default to 0.

**Comment by kraiskil** [comment]
But the documentation for `pads` attribute also says: "_The value represent the **number of pixels** added to the beginning and end part of the corresponding axis._"  I.e. no padding elements should be added in this case.

This is not mentioned anywhere in the documentations that I could find, but all the other examples in the `Operators.md` documentation seem to implicitly expect that the padding _contents_ is always 0 (when looking at the expected output). Is there a possibility with ONNX to use padding with other than the pad elements being having a zero value?

**Comment by kraiskil** [comment]
Or did I misunderstand your reply @askhade? If you mean pads should not be used, then that means that the output for that back end test is incorrect (like the bug report linked above suggests)?
It should be:
```
y = np.array([[[
    [11]]]]).astype(np.float32)
```
