### ISSUE TITLE
How to update the weights back into the ONNX model

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/onnx#2978]
# Ask a Question

### Question
Using the below code, I can read the weights (in this case the first weight) from the model into a numpy array.
In case if I modify the weight (i.e. numpy array), how to assign it back to model. 

Basically, I am trying to modify the weights.

code:
```
import onnx
from onnx import numpy_helper
model   = onnx.load('test.onnx')
init_0 = model.graph.initializer[0]
init_np = numpy_helper.to_array(init_0)
print(init_np)
init_np[0] = 1.1
// how to modify the actual weight here?
...
// save the new model
```

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
I explored on [from_array](https://github.com/onnx/onnx/blob/eccadceae6134e7b1e24673eab5cf637f63318d7/onnx/numpy_helper.py#L19) but not sure of complete usage

- Is this issue related to a specific model?  No

**Comment by jcwchen** [comment]
Hi @buddhapuneeth,
You can try this:
```
import onnx
from onnx import numpy_helper
model = onnx.load('test.onnx')
# numpy value which you want to update 
numpy_array = numpy.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=float)
# convert numpy to TensorProto
tensor = numpy_helper.from_array(numpy_array)
# copy this TensorProto to target tensor
model.graph.initializer[0].CopyFrom(tensor)
print(model.graph.initializer[0])
// then save the modified model
```

**Comment by buddhapuneeth** [comment]
Hi @jcwchen 
Thanks for your reply. I tried based on your code. It is working, but raw_data format is changed like below:
![image](https://user-images.githubusercontent.com/3439010/91509966-85720c00-e890-11ea-92bb-6150984ff66d.png)
Left: After updating, Right: Before updating
Visualizers like Neutron were not able to show the content like:
![image](https://user-images.githubusercontent.com/3439010/91510122-fca7a000-e890-11ea-819c-771448d278f0.png)
Left: Before updating, Right: After updating
I am not sure, will it cause any issue while reading using ONNX C++ APIs.
Also, in one of the other model, for LSTM in Netron I am seeing some different info for variables like 'sequence_len'. Due to large size, I am not able to convert to .txt and examine the change.
![image](https://user-images.githubusercontent.com/3439010/91510349-a6872c80-e891-11ea-96c8-a83fd93df345.png)
Left: Before updating, Right: After updating

```
def weight_update(onnx_model_path, onnx_updated_model_path, gradient_map, learning_rate = 0.01):
    onnx_model   = onnx.load(onnx_model_path)
    inits  = onnx_model.graph.initializer
    weights_map = {}
    for init in inits:
        W = numpy_helper.to_array(init)
        weights_map[init.name] = W
    print(weights_map.keys())
    for idx, key in enumerate(gradient_map.keys()):
        W_new  = weights_map[key] + learning_rate * gradient_map[key]
        tensor = numpy_helper.from_array(W_new)
        onnx_model.graph.initializer[idx].CopyFrom(tensor)
    onnx.save(onnx_model, onnx_updated_model_path)
```

**Comment by buddhapuneeth** [comment]
@jcwchen 
I am able to partially solve the issue by changing the below line:
```tensor = numpy_helper.from_array(W_new, key)```
One issue now is values are changing from float32 to float64 in this conversion process and almost doubling the size of the model.

**Comment by Lewis-Lu** [comment]
> Hi @buddhapuneeth, You can try this:
> 
> ```
> import onnx
> from onnx import numpy_helper
> model = onnx.load('test.onnx')
> # numpy value which you want to update 
> numpy_array = numpy.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=float)
> # convert numpy to TensorProto
> tensor = numpy_helper.from_array(numpy_array)
> # copy this TensorProto to target tensor
> model.graph.initializer[0].CopyFrom(tensor)
> print(model.graph.initializer[0])
> // then save the modified model
> ```

Hi @jcwchen 

How can we know methods like CopyFrom, is there any list for these methods ? that would be useful.

Thanks,
Lewis

**Comment by jcwchen** [comment]
Hi @Lewis-Lu,
Actually these proto manipulation related functions are from native Protobuf. You can check the full APIs here: https://googleapis.dev/python/protobuf/latest/google/protobuf/message.html
