### ISSUE TITLE
Empty graph model in C++

### ISSUE THREAD

**Issue by Bartekkz** [onnx/onnx#2981]
I am loading simple .onnx model containing addition and division operations with the following code using protobuf
```
std::unique_ptr<ModelProto> model = std::make_unique<ModelProto>();
std::ifstream in("model.onnx", std::ios_base::binary);
model->ParseFromIstream(&in);
in.close();
```
is it normal that when I check input size, nodes, etc. with
```
std::cout << model->graph().input_size() << '\n';
```
it prints 0? 
### Question
Are there any examples how to interact with the model? What I am trying to do is to load arguments from command line and 
then use them in the loaded graph to produce some output. Am I doing right?

Thanks for any help

**Comment by Bartekkz** [comment]
I misspelled the path to the file. Sorry for disturbing.

**Comment by zsy9512** [comment]
> I am loading simple .onnx model containing addition and division operations with the following code using protobuf
> 
> ```
> std::unique_ptr<ModelProto> model = std::make_unique<ModelProto>();
> std::ifstream in("model.onnx", std::ios_base::binary);
> model->ParseFromIstream(&in);
> in.close();
> ```
> 
> is it normal that when I check input size, nodes, etc. with
> 
> ```
> std::cout << model->graph().input_size() << '\n';
> ```
> 
> it prints 0?
> 
> ### Question
> Are there any examples how to interact with the model? What I am trying to do is to load arguments from command line and
> then use them in the loaded graph to produce some output. Am I doing right?
> 
> Thanks for any help

Hello,Sorry to bother you.I try to include onnx in my C++ project, but I don't know How to do it .Can you give me some instructions? For example,how to create a project in VS2019, and include the onnx lib in it？How can I define  "ModelProto mp" like you.
