### ISSUE TITLE
Graph Operations

### ISSUE THREAD

**Issue by Bartekkz** [onnx/onnx#2982]
# Ask a Question
I have searched whole web, but I cannot find any example how to interact with onnx::ModelProto graph values and operations using c++. Is there any c++ code example or documentatoin , how to add, update and evaluate values and operation in graph? 
### Question
At the moment I am able to load custom graph with the follwing code:
```
    std::unique_ptr<ModelProto> model = std::make_unique<ModelProto>();

    std::ifstream in("../model.onnx", std::ios_base::binary);
    model->ParseFromIstream(&in);
    in.close();
```
But I am struggling to find out how to interact with loaded graph. Set values of each node and/or evaluate given graph operation.
Additional is there any documentation how to interact with onnx operators?

Thanks for any help in advance.

**Comment by yywbxgl** [comment]
You can refer to some use cases I wrote.  
https://github.com/yywbxgl/onnx-parser

**Comment by askhade** [comment]
Onnx checker is a good starting point. It loads the model and validates it.
https://github.com/onnx/onnx/blob/master/onnx/checker.cc

**Comment by askhade** [comment]
@Bartekkz : Was this helpful? I am closing this issue now. Please reopen it if you have any questions regarding this.
