### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by quasar66** [onnx/onnx#2986]
# Bug Report

### Is the issue related to model conversion? No
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely
Tried all steps mentioned in the installation note and in the issue #2962.
The first set of attempts failed due to inability to find the Python Library (so added to the CMAKE an explicit Python Library command -DPYTHON_LIBRARY=c:/Python3/Lib. That started showing the warning below (displays 4 times) -
_The onnx_cpp2py_export requests linking to directory "C:/Python3/Lib". Targets may link only to libraries. Cmake is dropping the item._

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows 10 Pro 2004 Edition
- ONNX version (*e.g. 1.7*):  1.7
- Python version: 3.8.5
- GCC/Compiler version (if compiling from source): MSVC 19.27.2911
- CMake version: 3.17.20032601-MSVC_2
- Protobuf version: 3.13.0
- Visual Studio version (if applicable): VS 2019

### Reproduction instructions
- Describe the code to reproduce the behavior.
1. There is a perfectly properly functioning version of protobuf compiler installed. Removed it from the PATH to avoid conflict.
2. Installed pybind11 successfully, and set the environment variable pybind_DIR to the installed directory of pybind11/share/pybind where the configuration files reside.
3. installed protobuf following the commands in #2962. Installed smoothly.
4. Added this new protobuf installation to the PATH inside x64 Native Tools for VS 2019.
5. set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_LITE_PROTO=OFF -DPYTHON_LIBRARY=c:/Python3/Lib -DCMAKE_INSTALL_PREFIX=C:\Users\gautam\onnx
6.python setup.py install

### Expected behavior
A hopefully uneventful installation.

### Notes

Any additional information
[error.txt](https://github.com/onnx/onnx/files/5151678/error.txt)

**Comment by jcwchen** [comment]
Hi @quasar66,
onnx can directly use pybind11 from `third_party/pybind11`. Actually you don't need to manually install pybind11 before installing onnx and the pybind11 version onnx is using is 2.4.3, but yours is 2.6.0. Therefore, You can try to remove pybind11 first and then build onnx again. 
Hope it helps. Thanks.

**Comment by quasar66** [comment]
Hi @jcwchen 
Thanks for your time. I copied the pybind11/include (ver 2.6.0) to the onnx root, and the compilation succeeded.
Huge thanks to @Omniscimus as well - the detailed description helped immensely.
I am closing this issue. Happy to answer any further questions you may have.
