### ISSUE TITLE
ESPNet model conversion into ONNX

### ISSUE THREAD

**Issue by nehasoni3** [onnx/onnx#2988]
Hi,
I am trying to convert ESPNet model (PyTorch as a backend) into ONNX format for edge deployment.
ESPNet is basically for Deep Learning models for Speech.
But I am getting error while conversion - 

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-d59a47acb841> in <module>()
      8 trained_model = Net()
      9 
---> 10 trained_model.load_state_dict(torch.load('output/espnet_d.pth', map_location=DEVICE))

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in load_state_dict(self, state_dict, strict)
   1043         if len(error_msgs) > 0:
   1044             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1045                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1046         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1047 

RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias". 
	Unexpected key(s) in state_dict: "encoder.level1.conv.weight", "encoder.level1.bn.weight", "encoder.level1.bn.bias", "encoder.level1.bn.running_mean...",`

Looking for any possible way of doing this.Thanks.

**Comment by jcwchen** [comment]
Hi @nehasoni3,
It looks like a convert issue. You can open an issue in pytorch repo and provide details to reproduce your error there. Thanks.

**Comment by nehasoni3** [comment]
> Hi @nehasoni3,
> It looks like a convert issue. You can open an issue in pytorch repo and provide details to reproduce your error there. Thanks.

OK. Thanks.
I'll do but PyTorch supports ONNX conversions. So why this fails with ESPNet models?

**Comment by jcwchen** [comment]
Not all models from pytorch are supported for the onnx conversion. Some models might exist some unsupported opsets. According to https://github.com/espnet/espnet/issues/1542, it seems that ESPNet hasn't been supported yet.
