### ISSUE TITLE
Version converter 9-->10 fails with 'Input conv_first.weight is undefined!'

### ISSUE THREAD

**Issue by Lisicong9203** [onnx/onnx#2995]
# Bug Report

### Describe the bug
The version converter fails on the attached model 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Ubuntu 18.04.4 LTS
- ONNX version (*e.g. 1.7*):  1.7.0
- Python version: Python 3.6.9
- GCC/Compiler version (if compiling from source): 
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx import version_converter, helper
model_path = 'deart_model_fp16.onnx'
original_model = onnx.load(model_path)

converted_model = version_converter.convert_version(original_model, 10)

print('The model after conversion:\n{}'.format(converted_model))

```

error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-4409d2eda4ac> in <module>
      6 # https://github.com/onnx/onnx/blob/master/onnx/version_converter.py#L21
      7 # Apply the version conversion on the original model
----> 8 converted_model = version_converter.convert_version(original_model, 10)
      9
     10 print('The model after conversion:\n{}'.format(converted_model))

~/tf.t130/lib/python3.6/site-packages/onnx/version_converter.py in convert_version(model, target_version)
    164         raise ValueError('VersionConverter only accepts int as target_version, incorrect type: {}'.format(type(target_version)))
    165     model_str = model.SerializeToString()
--> 166     converted_model_str = C.convert_version(model_str, target_version)
    167     return onnx.load_from_string(converted_model_str)

IndexError: Input conv_first.weight is undefined!
```

Onnx model:
 [deart_model_fp16.onnx](https://drive.google.com/open?id=1tO3P9ZxxqCZqi-4RoWQxxGYv2c2i4yrI)

**Comment by jcwchen** [comment]
Hi @Lisicong9203,
It seems that you provide a wrong file (`deart_model.pt`). Could you upload the onnx model again? Thanks.

**Comment by Lisicong9203** [comment]
@jcwchen  I'm so sorry about that , i have update the onnx file.

**Comment by Lisicong9203** [comment]
@jcwchen Because it is not convenient to access Google in China, I got it wrong. I updated this link the file named deart_model.onnx  is the file I used when converting. I first converted this file to fp 16  (deart_model_fp16.onnx I will update this file tomorrow ) like this: [https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb](url)  . then when i convert deart_model_fp16.onnx from onnx 9 to onnx 10  I encountered this error.

**Comment by jcwchen** [comment]
No problem. Thank you for providing the onnx model. 
I believe it is a known IR issue like https://github.com/onnx/onnx/issues/2873. The old version_converter expects initializers also be added as graph inputs. A quick workaround would be including all the initializers into the graph inputs. There will be a PR for fixing this.

**Comment by Lisicong9203** [comment]
@jcwchen 
I am not particularly familiar with onnx .  _The old version_converter expects initializers also be added as graph inputs_ . What exactly does initializers here mean? Is it the code we often write in the code model  `sess.run(initialize)` ? 
What should I do if I want to add this 'initializers'  part to onnx model ?
In addition, if I don’t have the original model code, only the onnx file, can I have other ways to fix this problem?

**Comment by jcwchen** [comment]
You can use something like this to add input from initializer:
```
def add_input_from_initializer(model : onnx.ModelProto):
    """
    Currently onnx.shape_inference doesn't use the shape of initializers, so add
    that info explicitly as ValueInfoProtos.
    Mutates the model.
    Args:
        model: The ModelProto to update.
    """
    # All (top-level) constants will have ValueInfos before IRv4 as they are all inputs
    if model.ir_version < 4:
        return

    def add_const_value_infos_to_graph(graph : onnx.GraphProto):
        inputs = {i.name for i in graph.input}
        existing_info = {vi.name: vi for vi in graph.input}
        for init in graph.initializer:
            # Check it really is a constant, not an input
            if init.name in inputs:
                continue

            # The details we want to add
            elem_type = init.data_type
            shape = init.dims

            # Get existing or create new value info for this constant
            vi = existing_info.get(init.name)
            if vi is None:
                vi = graph.input.add()
                vi.name = init.name

            # Even though it would be weird, we will not overwrite info even if it doesn't match
            tt = vi.type.tensor_type
            if tt.elem_type == onnx.TensorProto.UNDEFINED:
                tt.elem_type = elem_type
            if not tt.HasField("shape"):
                # Ensure we set an empty list if the const is scalar (zero dims)
                tt.shape.dim.extend([])
                for dim in shape:
                    tt.shape.dim.add().dim_value = dim

        # Handle subgraphs
        for node in graph.node:
            for attr in node.attribute:
                # Ref attrs refer to other attrs, so we don't need to do anything
                if attr.ref_attr_name != "":
                    continue

                if attr.type == onnx.AttributeProto.GRAPH:
                    add_const_value_infos_to_graph(attr.g)
                if attr.type == onnx.AttributeProto.GRAPHS:
                    for g in attr.graphs:
                        add_const_value_infos_to_graph(g)


    return add_const_value_infos_to_graph(model.graph)
add_input_from_initializer(original_model)
```
Even though it can fix the error you are facing, it will bump into another one after applying this fix:
```
BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For Slice
```
For those supported operators for version_converter, you can check this [file](https://github.com/onnx/onnx/blob/master/onnx/version_converter/convert.h). Sorry that currently the `Slice` operator is unsupported.

**Comment by Lisicong9203** [comment]
OK,I will try some other methods. Thanks
