### ISSUE TITLE
float32/float64 vs float/double inconsistency?

### ISSUE THREAD

**Issue by rryan** [onnx/onnx#300]
The [IR spec](https://github.com/onnx/onnx/blob/master/docs/IR.md) seems to use float16/float32/float64 (:+1:) while the [code](https://github.com/onnx/onnx/blob/master/onnx/defs/schema.h#L325-L326) and [op schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md) use float/double (:-1:). Should this be uniform?

**Comment by gramalingam** [comment]
Thanks, updated the IR spec to be consistent.
