### ISSUE TITLE
Matrix-vector multiplication

### ISSUE THREAD

**Issue by Nimmerwoner** [onnx/onnx#3006]
# The matrix-vector multiplication operator
Pytorch supports an [operator](https://pytorch.org/docs/stable/generated/torch.mv.html) that multiplies a matrix with a vector. Currently, onnx does not. On attempting an export, it fails with the following message for opsets 9 to 12:

```
RuntimeError: Exporting the operator mv to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.
````

### Describe the operator
It allows multiplying a matrix with a vector. It is supported by both pytorch and [tensorflow](https://www.tensorflow.org/api_docs/python/tf/linalg/matvec).

### Can this operator be constructed using existing onnx operators?
It seems similar to MatMul in purpose, so maybe it can share code with that operator. I feel too unfamiliar with the onnx code base to go deeper.

### Is this operator used by any model currently? Which one?
I am not aware of a model that uses it. However, we have built our own model using only pytorch's standard library which led us to this error. Since both pytorch and tensorflow support this operation, it seems like a good candidate for ONNX to support as well.

Update September 10th: The 'guilty' pytorch module is `nn.utils.spectral_norm` ([link](https://pytorch.org/docs/stable/generated/torch.nn.utils.spectral_norm.html)). A recent model using spectral_norm is nVidia's [SPADE](https://github.com/NVlabs/SPADE/blob/master/models/networks/architecture.py).

### Are you willing to contribute it? (Y/N)
I am willing to contribute the implementation. I am new to the onnx codebase, however, so instructions on how to specifically approach this are welcome. I have seen the CONTRIBUTING document.

**Comment by Nimmerwoner** [comment]
The 'guilty' pytorch module is `nn.utils.spectral_norm` ([link](https://pytorch.org/docs/stable/generated/torch.nn.utils.spectral_norm.html)). It uses `torch.mv` in its implementation. A recent model using spectral_norm is nVidia's [SPADE](https://github.com/NVlabs/SPADE/blob/master/models/networks/architecture.py).

**Comment by jcwchen** [comment]
Hi @Nimmerwoner,
https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md This document can help you. Thank you for the proposal!

**Comment by askhade** [comment]
Onnx matmul does support multiplying a matrix with a vector. 

Per my understanding in pytorch you can either use matmul which will then disperse appropriate function based on the dimensions of the input or directly use mv. 

This looks like exporter issue. Please open this issue in pytorch repo for onnx exporter. @spandantiwari 

This is a small example:
`
>>> a = np.random.randn(3, 4).astype(np.float32)
>>> b = np.random.randn(4).astype(np.float32)
>>> np.matmul(a, b)
array([4.141254  , 1.415079  , 0.84458256], dtype=float32)
>>> a_t = torch.from_numpy(a)
>>> b_t = torch.from_numpy(b)
>>> torch.mv(a_t, b_t)
tensor([4.1413, 1.4151, 0.8446])
>>> torch.matmul(a_t, b_t)
tensor([4.1413, 1.4151, 0.8446])
`

**Comment by Nimmerwoner** [comment]
> Per my understanding in pytorch you can either use matmul which will then disperse appropriate function based on the dimensions of the input or directly use mv.

Yes, we discovered that replacing the torch.mv with torch.matmul fixed our issue and we could export to ONNX. This means that pytorch doesn't correctly map torch.mv to ONNX's matmul then?

**Comment by askhade** [comment]
In my opinion conclusion is 
1. ONNX does not need a new operator since matmul does the work. 
2. Pytorch exporter should map mv to onnx matmul (I suggest opening an issue in pytorch repo)

Closing this one. Reopen if you have more questions or concerns.
