### ISSUE TITLE
Preprocessing Operators / Pipelines

### ISSUE THREAD

**Issue by Jonas-Heinrich** [onnx/onnx#3016]
Hello there,

I was wondering on what functionality will be added regarding data preprocessing / pipelines going forward. I know there is an inactive [working group for pipelines](https://github.com/onnx/onnx/blob/master/community/working-groups.md#inactive-working-groups), however the decisions that lead to this result are unclear to me.

In scenarios I am working on, data preprocessing like the [`FullTokenizer` for BERT](https://github.com/onnx/models/blob/master/text/machine_comprehension/bert-squad/dependencies/tokenization.py#L161) has to be done external to ONNX (runtime) for now. Performing these or similar steps at an application level is very inconvenient however, since the latter might not even be written in a language suitable for ML/DL.
Are there plans to support this or is it dead for now? Of course one can add their own custom operator, but that seems like unnecessary work when there are many use cases benefiting by it.

### Further information

- operators
- pipelines
- preprocessing

**Comment by WilliamTambellini** [comment]
cf
https://github.com/onnx/onnx/issues/1474

**Comment by Jonas-Heinrich** [comment]
> cf
> #1474

Thank you for the refrence @WilliamTambellini.

What I got from that issue is that I should use `com.microsoft.Tokenizer` for basic string splitting etc. Are these ops moving to the standard at some point?

The [original issue](https://github.com/onnx/onnx/issues/1474#issuecomment-470193278) (in that thread) remains tough. I guess for more advanced tokenization, a custom operation or move to the application layer makes the most sense.
