### ISSUE TITLE
Wrong Installation Guide in README.md

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#3017]
# Bug Report

### Describe the bug
The installation guide in https://github.com/onnx/onnx#linux-and-macos is wrong :|

It should tell users how to build onnx from source, but `pip install onnx` there will directly install the pre-compiled onnx package from PyPI. 

In my opinion, a `--no-binary` command argument is needed https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary

**Comment by askhade** [comment]
@daquexian :
The instructions for building from source are as follows:

Alternatively, you can also build and install ONNX locally from source code:

git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
python setup.py install

what change are you suggesting here?

**Comment by daquexian** [comment]
@askhade 

> The instructions for building from source are as follows:

No, I think the author of the docs incorrectly thinks that `pip install onnx` is the instruction for building from the source. The reason I think so is the following in the docs:

> You will need an install of Protobuf and NumPy to build ONNX. One easy way to get these dependencies is via Anaconda:
> 
> conda install -c conda-forge protobuf numpy
> You can then install ONNX from PyPi (Note: Set environment variable ONNX_ML=1 for onnx-ml):
> 
> pip install onnx

As we know, we don't need to install protoc or set the environment variable `ONNX_ML` when installing the binary wheel from PyPI.

And the following piece shows the problem more clearly:

> Note: When installing in a non-Anaconda environment, make sure to install the Protobuf compiler before running the pip installation of onnx. For example, on Ubuntu:
> 
> sudo apt-get install protobuf-compiler libprotoc-dev
> pip install onnx

It clearly shows that the author thinks that onnx will be built from source rather than be installed directly when running `pip install onnx`

**Comment by askhade** [comment]
@daquexian: The instructions definitely need to be more precise. In the above 2 cases that you noted the instructions are for installing onnx package from conda or pypi and in both the cases the instructions lack details or are not accurate. Can you send a PR for this?

Regarding installing from source... I pasted the instructions for installing from source above and they seem right to me. If you think additional details are required then please add them in your PR as well.

Thanks!

**Comment by daquexian** [comment]
> Regarding installing from source... I pasted the instructions for installing from source above and they seem right to me. If you think additional details are required then please add them in your PR as well.

Sorry for the late reply. 

I'm afraid I didn't make myself clear :). The instructions I meant by "installing from source" are what appears in the "source" section, which is `pip install onnx`. We experienced developers know that `pip install onnx` installs binaries from PyPI, but not every fresh user will think so (After all, he/she sees this instruction in the "source" section instead of the "binaries" section above). That's the reason I say the installation guide about installing from source is wrong.

I'll send a PR for this when I have time.

**Comment by askhade** [comment]
Ok now I understand what you mean. Moving the sections should help make this more clear.

**Comment by askhade** [comment]
Closing this issue as the it has been resolved with #3550.
