### ISSUE TITLE
Add support for converting ONNX to C code?

### ISSUE THREAD

**Issue by mhamdan91** [onnx/onnx#3031]
# Feature Request

### System information
ONNX version (you are using): ANY

### What is the problem that this feature solves?
Please detail the discrepancy with our current functionality.
Extended feature

### Describe the alternatives you have considered
A clear and concise description of any alternative solutions or features you've considered
Add a plug in to translate ONNX models directly into C equivalent 

### Describe the feature
Why is this feature necessary? What does it accomplish?
Support all microcontrollers that only run C. 

### Will this influence the current api?
If yes, how? 
No

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
Modal usage

### Are you willing to contribute it (Y/N):
Y

### Notes
Any additional information

**Comment by yuslepukhin** [comment]
I must admit this issue does not have a clear description. Would you care to add more details?
My guess is that your request seems to be related to ONNX standard not ONNX Runtime. Would https://github.com/onnx/onnx be a better place to file this issue?

**Comment by mhamdan91** [comment]
Would it be possible to convert the ONNX model to C equivalent?  Basically, have the ONNX model be completely implemented in C. For example, If you've got an onnx model that is composed of 2 fc layers, then this would translate into for loops with MAC operations in C and so forth.

**Comment by jianjunjiang** [comment]
https://github.com/xboot/libonnx

A lightweight, portable pure C99 onnx inference engine for embedded devices with hardware acceleration support.

**Comment by PasaOpasen** [comment]
He meant support `onnx->c` translation: creating optimized C file without dependences. Something like https://github.com/xboot/libonnx or https://github.com/kraiskil/onnx2c (but these projects and opencv still does not work with dynamic layers 👎🏼 )

**Comment by strimo378** [comment]
https://github.com/emmtrix/emx-onnx-cgen/ supports ONNX to C code generation with dynamic layers.
