### ISSUE TITLE
Support for PyTorch torch.distributions.Normal

### ISSUE THREAD

**Issue by itssimon** [onnx/onnx#3033]
# Feature Request

Would be great if ONNX would implement support for the **`broadcast_tensors`** operator in PyTorch.

Currently `torch.onnx.export()` fails if the model uses `torch.distributions.Normal`:

`RuntimeError: Exporting the operator broadcast_tensors to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.`

Also see https://github.com/pytorch/pytorch/issues/30517.

**Comment by mxkrn** [comment]
Same deal in `opset_version=12`. 

`Exporting the operator broadcast_tensors to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.`

The new PyTorch `distributions` module makes extensive use of this method so it would be great to see support for this.

**Comment by Lenbus** [comment]
Have the same deal with PyTorch1.7 on every opset (9 to 12).

**Comment by rickstaa** [comment]
This feature and/or https://github.com/pytorch/pytorch/issues/29843 are the only ones stopping us from moving over to Pytorch from Tensorflow. In Pytorch, I could not find an (easy) way to deploy any of our Gaussian and Baysian algorithms wherein Tensorflow is extremely easy.

**Comment by rickstaa** [comment]
I think this is still relevant.

**Comment by rickstaa** [comment]
Why didn't the bot re-open this 🤔?

**Comment by andife** [comment]
What is the current situation? I'm also interested in "torch.distributions.normal.Normal"

**Comment by rickstaa** [comment]
Maybe somebody of the @pytorch team can reopen this issue 🤔?

**Comment by rickstaa** [comment]
Thanks! 🙏
