### ISSUE TITLE
Pytest dies on AccessViolation in Windows build

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#3039]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Build ONNX outside conda against static protobuf lib and dynamic MSVCRT and run pytest. Pytest does not finish:

`s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s                                                                 [ 95%]
onnx\test\test_external_data.py ............s                                                                                                     [ 96%]
onnx\test\tools_test.py .                                                                                                                         [ 96%]
onnx\test\utils_test.py .                                                                                                                         [ 96%]
onnx\test\version_converter_test.py .....

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows 10 built off the source
- ONNX version (*e.g. 1.7*):  Tip of the master
- Python version: Python 3.6.8
- GCC/Compiler version (if compiling from source):
- CMake version:  3.16.2
- Protobuf version: 3.9.2
- Visual Studio version (if applicable):  Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64
`
Running under debugger produces debugger output:
`The thread 0x29c4 has exited with code -1073741819 (0xc0000005).
The thread 0x5f4 has exited with code -1073741819 (0xc0000005).
The program '[22060] pytest.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
# Build Protobuf
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout 3.9.x

cd cmake
md build && cd build
cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=c:\dev\oss\protobuf_install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_CONFORMANCE=OFF  -Dprotobuf_BUILD_EXAMPLES=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ..

Build and install
msbuild protobuf.sln /m /p:Configuration=Release
msbuild INSTALL.vcxproj /p:Configuration=Release

msbuild protobuf.sln /m /p:Configuration=Debug
msbuild INSTALL.vcxproj /p:Configuration=Debug

# Build ONNX
set PATH=C:\dev\oss\protobuf_install\bin;%PATH%
set ONNX_ML=1
set DEBUG=1
set ONNX_VERIFY_PROTO_3=0
set USE_MSVC_STATIC_RUNTIME=0
set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON
python setup.py install
pytest
```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
All tests should pass

### Notes

Any additional information

**Comment by yuslepukhin** [comment]
I resolved it with installing from the build first `pip install -e  .` Then pytest runs fine. However, test instructions do not mention it.

**Comment by jcwchen** [comment]
Hi @yuslepukhin,
Thank you for reporting this. Either `pip install -e .` or `pip uninstall onnx` before build from source can solve this issue. I have added the description in the document: https://github.com/onnx/onnx/pull/2979#issuecomment-702994188

**Comment by ccl-private** [comment]
![image](https://user-images.githubusercontent.com/36214675/126793674-c49573e1-969d-4035-ab26-2cfe7cebc31c.png)
pytorch to onnx， code -1073741819
windows

**Comment by ccl-private** [comment]
pip install onnx
