### ISSUE TITLE
"No Adapter For Conv", Converting Op Set 7 to Op Set 12, MobileNetV2

### ISSUE THREAD

**Issue by jhkonan** [onnx/onnx#3050]
I would like to convert MobileNetV2 in `onnx/models` ([github.com/onnx/models](https://github.com/onnx/models)) from op set 7 to op set 12. Attempting to convert from op set 7 to op set 12 using `onnx.version_converter.convert_version` fails.

Is this expected behavior? I am using Python: 3.8.5 and ONNX: 1.7.0.

```
import onnx
import onnx.version_converter

original_model = onnx.load("./models/vision/classification/mobilenet/model/mobilenetv2-7.onnx")
onnx.checker.check_model(original_model)

converted_model = onnx.version_converter.convert_version(original_model, 12)
onnx.checker.check_model(converted_model)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-5b72f30d2bc9> in <module>
      5 onnx.checker.check_model(original_model)
      6 
----> 7 converted_model = onnx.version_converter.convert_version(original_model, 12)
      8 onnx.checker.check_model(converted_model)

~\Anaconda3\lib\site-packages\onnx\version_converter.py in convert_version(model, target_version)
    164         raise ValueError('VersionConverter only accepts int as target_version, incorrect type: {}'.format(type(target_version)))
    165     model_str = model.SerializeToString()
--> 166     converted_model_str = C.convert_version(model_str, target_version)
    167     return onnx.load_from_string(converted_model_str)

RuntimeError: C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-fu0d0ib3\onnx/version_converter/BaseConverter.h:64: adapter_lookup: Assertion `false` failed: No Adapter For Conv

```

**Comment by jcwchen** [comment]
Hi @jhkonan,
`conv` conversion is covered in this PR https://github.com/onnx/onnx/pull/2664. Build the latest onnx from source can help. Thanks.

**Comment by jhkonan** [comment]
I followed the instructions to "Build ONNX on Windows with Anaconda" from README.md. I still run into the same error described above. 

Has anyone else successfully converted mobilenetv2 in `onnx/models` to op set 12? Is there anything I can do to make sure I have built the correct onnx where this doesn't fail?

**Comment by jhkonan** [comment]
Converting from Op Set 7 to Op Set 11 gives the same error. 

Converting from Op Set 7 to Op Set 10 does not give an error. 

Converting from Op Set 7 to Op Set 10, then from Op Set 10 to Op Set 12 (or 11) gives the same error.

Is there anything I can do to help diagnose the problem?

**Comment by jcwchen** [comment]
Hi @jhkonan,
I can successfully version_convert MobileNetV2 (from ONNX Model Zoo) to opset 12 with the main branch of ONNX. Could you try to `pip uninstall onnx` first, build onnx from source, and then version_convert again? Thanks.

**Comment by jhkonan** [comment]
Hi @jcwchen, I uninstalled onnx and built from source. I'm now able to convert mobilenetv2 to opset 12.

Thank you for your help!
