### ISSUE TITLE
 RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

### ISSUE THREAD

**Issue by Darshcg** [onnx/onnx#3057]
I was converting our custom Pytorch model to Trt and run it on a Jetson.
While converting pt to ONNX I am getting an error like:
RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

Code for the Conversion:

```
from models import *
from datasets import letterbox #*
from utils import *
import numpy as np
import sys, random
import torch
import torchvision
from torchvision import models, transforms
from PIL import Image
import io
import torch.nn as nn
from torch.autograd import Variable
import cv2
import os
import logging

img_size=(416, 416)
cfg = 'yolov3-spp.cfg'
imgsz = img_size

import torch
import torch.onnx


model_pt_path = "last.pt"
model_def_path = "models.py"

model = Darknet(cfg, imgsz)
model.load_state_dict(torch.load(model_pt_path),strict=False)

dummy_input = torch.randn(1,3,416,416)

torch.onnx.export(model, dummy_input, "SL-PMH.onnx")
```

May I know how this can be resolved?
Torch version: 1.6

**Comment by jcwchen** [comment]
Hi @Darshcg,
It should be a converter issue. I saw you have opened an issue under pytorch and you will get the best help there. Thanks.
To the best of my knowledge, since the default opset_version is 9 for `torch.onnx.export`, you can try this:
```
torch.onnx.export(model, dummy_input, "SL-PMH.onnx", opset_version=11)
```

**Comment by Darshcg** [comment]
Hi @jackwish,

Thanks for your Reply. Actually, I am further converting the ONNX model to TRT Model, but with opset_version=11, the Scatter op is being generated, but Scatter op is not Supported for tensorrt. 

Can you please guide for an Alternative Conversion from the PyTorch model to ONNX other than torch.onnx.export?
And what is the reason for the error with Opset_version=9 and 10?

Thanks

**Comment by jcwchen** [comment]
As far as I know, `torch.onnx.export` should be the only way. I don't know which model you are using, but literally by the error message, your model exists some opsets supported since opset_version=11 (which means you need to export it at least with opset_version=11) and TensorRT does not support certain opset (Scatter op).

**Comment by Darshcg** [comment]
Thanks a lot @jcwchen , this is a great response.
Now I got the Direction and the exact Problem.

Thanks, again

**Comment by jcwchen** [comment]
Close now since the question should be resolved. Please reopen it if you still have question related to ONNX. Thank you!

**Comment by Adhithya-tech** [comment]
Once i move it to opset_version=11, it says Error:Exporting the operator hardsigmoid to ONNX opset version 11 is not supported.

**Comment by jcwchen** [comment]
> Once i move it to opset_version=11, it says Error:Exporting the operator hardsigmoid to ONNX opset version 11 is not supported.

@Adhithya-tech ONNX does have hardsigmoid, but it seems that the converter (torch.onnx.export) has not supported it yet: https://pytorch.org/docs/stable/onnx.html#supported-operators. Please open an issue about this operator support request in pytorch repo. Thanks.

**Comment by wwdok** [comment]
what if there is no 'torch.onnx.export()' ? see https://github.com/waleedka/hiddenlayer/issues/95

**Comment by jcwchen** [comment]
> what if there is no 'torch.onnx.export()' ? see https://github.com/waleedka/hiddenlayer/issues/95

This should be a question for PyTorch-ONNX exporter or the caller. Perhaps you can trace `torch.onnx._optimize_trace` to see where the opset_version can be specified. It's not a public function so the support might be limited.
