### ISSUE TITLE
no checker if use conda install way

### ISSUE THREAD

**Issue by oneTaken** [onnx/onnx#306]
It's really a problem to install onnx with python2.
I have spent lots of time.
I use conda command to install 

`conda_path/conda install -c ezyang onnx`

Everything seems ok.
And when I use 
`python -c 'import onnx'`

It raises` ImportError:No module named onnx.`

**Comment by dzhulgakov** [comment]
Are you running the right python? Can you put the output of `which python` and `conda list` please?

**Comment by oneTaken** [comment]
I think it's because of the conda path conflict.
With an easy but not good way, I uninstall anaconda3. And onnx is installed.
May onnx be installed the right way?
I use the code in the tutorial with
```
import onnx
model = onnx.load(onnx_model_name)
hasattr(onnx, 'checker') # False
hasattr(onnx, 'helper') # False
```
It's not the same as the tutorial.
Is this no problem?
Is this something may be wrong?

**Comment by dzhulgakov** [comment]
That's weird. Try reinstalling it just in case?

Can you do `import onnx; print(onnx)` to get the path from where it gets imported?

**Comment by oneTaken** [comment]
Yeah, It's hard to understand, especially for newer to onnx.
I reinstalled onnx. And nothing has changed.
the `print(onnx)` output is the path I created with 'conda create path python=2.7'

I put out the dir output:
```
import onnx
dir(onnx)
['AttributeProto', 'DESCRIPTOR', 'GraphProto', 'IR_VERSION', 'ModelProto', 'NodeProto', 'SparseTensorProto', 'TensorProto', 'TypeProto', 'ValueInfoProto', 'Version', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'absolute_import', 'descriptor_pb2', 'division', 'enum_type_wrapper', 'load', 'onnx_pb2', 'print_function', 'sys', 'unicode_literals']
```

So, what's wrong?

**Comment by ezyang** [comment]
Hi @oneTaken, this bug report really seems like issues with conda usage, not issues with Python. Can you please give full terminal transcripts of the commands you ran to cause the problem, *including* the command you used to invoke Python, and also *please please* give the output of `which python` before you run Python.

Remember that you *must* use the conda-installed Python to see the conda onnx package. This is probably **not** the default `python` in your path. You can get it using something like `conda_path/python`

**Comment by bddppq** [comment]
It's the released snapshot (https://github.com/onnx/onnx/blob/56f92deff5483f34c3911bd1372f61b2d07ee9b5/onnx/__init__.py) being outdated. A bug fix has been done later https://github.com/onnx/onnx/commit/fea2c0bc02a8323ad6c759ca63663499a538186e

Installing onnx from source should solve the problem.

**Comment by oneTaken** [comment]
@ezyang You're so hot-mind. I fell a little guilty for your ***please please***.

It's not really a good way to redo everything from the 'conda create' command, beacause I installed `pytorch` from source for useing `onnx`, `onnx-coreml`.
If it's the problem. I'll redo everything.

```
which python # in vritual python environment
# /Users/deepmind/anaconda2/anaconda2/envs/it_venv/bin/python

conda info
...
root environment : /Users/deepmind/anaconda2/anaconda2  (writable)
...

which python2 # normal python2, not virtual
# /Users/deepmind/anaconda2/anaconda2/bin/python2
```
So, it's the problem?

**Comment by oneTaken** [comment]
I use `git clone --recursive https://github.com/onnx/onnx.git` and `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install`
solve this problem well. Refer to #6 .
Even though I don't find `checker` attribute after install from source on Ubuntu 14.04.
After check, I found the pooling pad size is 2, and the conv pad size is 4.
And when exchange onnx to core_ml, all pads need to be 4.
Is this a bug?

**Comment by prasanthpul** [comment]
There have been many updates since this issue was last discussed. Please open a new issue if there is still a problem
