### ISSUE TITLE
1.7.0 release notes have outdated links

### ISSUE THREAD

**Issue by siddharth-krishna** [onnx/onnx#3065]
The 1.7.0 [release notes](https://github.com/onnx/onnx/releases/tag/v1.7.0) say
> Operator registration APIs are updated to support dynamic function body (sub-graph) registration. https://github.com/onnx/onnx/blob/master/onnx/defs/schema.h#L674

However, the link is to a line number in the master branch, and the line contains nothing but a closing parenthesis. [Line 674](https://github.com/onnx/onnx/blob/v1.7.0/onnx/defs/schema.h#L674) on the tag `v1.7.0` doesn't to be what was intended either.

What was the intended line number? How can I find out more about the API to dynamically register function bodies for operators?

(@chinhuang007, as the author of the release notes. Thanks!)

**Comment by jcwchen** [comment]
Hi @siddharth-krishna,
I believe this should be the target line: https://github.com/onnx/onnx/blob/d343755dfdfaae46ccdd1591076205e1bfaa67bf/onnx/defs/schema.h#L674

Related PR: https://github.com/onnx/onnx/pull/2597
An example which might be helpful: https://github.com/onnx/onnx/blob/a7a0fec7f25cae567429af62b7eaaee1c3f0e247/onnx/defs/math/defs.cc#L1185

**Comment by siddharth-krishna** [comment]
Thank you, that's really helpful! Can release notes be edited? Otherwise I'm happy to close this issue.

**Comment by jcwchen** [comment]
Glad it helps. @chinhuang007 could you help to update the old link by https://github.com/onnx/onnx/blob/d343755dfdfaae46ccdd1591076205e1bfaa67bf/onnx/defs/schema.h#L674? Thank you.

**Comment by chinhuang007** [comment]
@jcwchen Unfortunately I don't have edit permissions and can't change the release notes for 1.7 now.

**Comment by jcwchen** [comment]
@chinhuang007 No worries. I just updated. If it is good, @siddharth-krishna please close this issue. Thank you all!
