### ISSUE TITLE
covert TasNet from torch to onnx

### ISSUE THREAD

**Issue by oneway234** [onnx/onnx#3067]
# Ask a Question

### Question
I coverted Conv-TasNet from torch to onnx. Then used "testing.assert_almost_equal" from umpy to verify output. The orignal TasNet pre-trained model worked, however the result of onnx are zeros. 

### Further information
- Relevant Area (*model usage*): It didn't report anything when i converted. But i doubt that there are operators which can't be convert. What is it mean about prelu（不支持輸入通道間的單重輸入共享）?  And does onnx support "LayerNorm"?

- Is this issue related to a specific model?  
**Model name** (*Conv-TasNet*):  
**Model opset** (*not sure*):

### Notes
#This is the convert code.
model = ConvTasNet.load_model(args.model_path)
model.eval()
torch.onnx.export(model, input,
                              "/path/to/conv_tasnet.onnx",
                              export_params=True
                              # do_constant_folding=True
                              )

onnx model:https://drive.google.com/file/d/1we2YpPVWVlIPNTXT6N92x_lH6fTRTd4r/view?usp=sharing
conv-tasnet:https://drive.google.com/file/d/1-UEej2yIXsvZWmN-VYdHHwSeIrxrS4BQ/view?usp=sharing

**Comment by jcwchen** [comment]
Hi @oneway234,

> however the result of onnx are zeros

Are you saying the inference result are zeros by onnxruntime?

LayerNorm operator itself hasn't been introduced to ONNX yet: https://github.com/onnx/onnx/issues/2379, but I guess `torch.onnx.export` should export LayerNorm to separated ops for now. I saw you posted this question under pytorch and I believe you will get a better answer from `torch.onnx`'s team. Thanks.

**Comment by oneway234** [comment]
Hi @jcwchen ,
Tanks,
yes, the inference result is zero by onnxruntime.
I update my [project](https://github.com/oneway234/torch_to_onnx), and I also added compare result .py file.

**Comment by oneway234** [comment]
I switched to pytorch==1.6 and onnx==1.7. And it return the error.
> RuntimeError: Unexpected node type: onnx::Cast

Maybe it's the same issue as [this](https://github.com/onnx/onnx/issues/2969).

**Comment by jcwchen** [comment]
> I switched to pytorch==1.6 and onnx==1.7. And it return the error.
> 
> > RuntimeError: Unexpected node type: onnx::Cast
> 
> Maybe it's the same issue as [this](https://github.com/onnx/onnx/issues/2969).

If that is the case, this should be a converter issue. You can also open an issue mentions ONNX under pytorch GitHub repo, which might be more visible than discuss.pytorch. Thank you.

**Comment by oneway234** [comment]
Thanks for your help. 
I opened an new issue in[ torch. ](https://github.com/pytorch/pytorch/issues/46898)

**Comment by oneway234** [comment]
Hi, 
I convert it sucessfuliy, and it work.
My model is very complex. It has single and mutiple inputs.
Please convert it separately.
