### ISSUE TITLE
pip install onnx doesn't generate onnx.pb.h

### ISSUE THREAD

**Issue by AnthonyBarbier** [onnx/onnx#3074]
# Bug Report

### Describe the bug
When installing `onnx` using `pip install onnx`, `onnx.pb.h` doesn't get generated and therefore when trying to build an app that uses for example `onnx/defs/schema.h` it will fail with `venv/lib/python3.6/site-packages/onnx/onnx_pb.h:52:10: fatal error: onnx/onnx.pb.h: No such file or directory`

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 18.04.4
- ONNX version (*e.g. 1.7*):  1.7.0
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Expected behavior
Compiled protobuf files should be installed alongside the regular headers and libraries.

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @AnthonyBarbier,
Have you tried `sudo apt-get install protobuf-compiler libprotoc-dev` before `pip install onnx`?
Otherwise, using conda-forge to install onnx should also work. Thanks.

**Comment by AnthonyBarbier** [comment]
Are there some pip packages for these packages ? (I'd like to be sure they can be installed without root privileges)
The conda package doesn't seem better: there is still an include `onnx.pb.h` but no `onnx.pb.h` anywhere in the venv

**Comment by jcwchen** [comment]
I am afraid there is no such thing in PyPi...
It seems like a known tricky issue. I remember I met this once but it cannot be reproduced now...
How about using `ONNX_ML=1` for `pip install onnx`? (Is `onnx/onnx-ml.pb.h` there?)
I would say conda deserves a shot because most of related issues seemt to happen without conda.

**Comment by AnthonyBarbier** [comment]
There is no `pb.h` at all being installed.
I had a better look and I think comes from `setup.py`: For CMake the files get generated and copied to the install folder but for `setup.py` they're generated in `.setuptools-cmake-build/` but don't get copied over to the build folder.
I've tried to add the following to `setup.py`:
```
diff --git a/setup.py b/setup.py
index 4e7ff8ab..c3bfad5a 100644
--- a/setup.py
+++ b/setup.py
@@ -217,6 +217,7 @@ class build_py(setuptools.command.build_py.build_py):
         self.run_command('cmake_build')
 
         generated_python_files = \
+            glob.glob(os.path.join(CMAKE_BUILD_DIR, 'onnx', '*.h')) + \
             glob.glob(os.path.join(CMAKE_BUILD_DIR, 'onnx', '*.py')) + \
             glob.glob(os.path.join(CMAKE_BUILD_DIR, 'onnx', '*.pyi'))
 
```
And it seems to solve the issue when using `setup.py` locally (As the conda recipe uses setup.py it might solve the issue in conda and pip too ?)

**Comment by AnthonyBarbier** [comment]
I created: https://github.com/onnx/onnx/pull/3077
