### ISSUE TITLE
MLContext.Model.Load fails to load a model

### ISSUE THREAD

**Issue by Suriman** [onnx/onnx#3079]
# Bug Report

### Describe the bug
When trying to load an onnx model into a PredictionEngine I’m getting an error: 
System.IO.InvalidDataException:“End of Central Directory record could not be found.” 
Apparently it’s failing to uncompress the onnx model.

### System information
- OS Platform and Distribution: Windows Server 2019 Standard, Version 1809
- Using Microsoft.ML version 1.5.2:  
- Python version: Using C#
- Visual Studio version (if applicable): 16.7.6

### Reproduction instructions
- Describe the code to reproduce the behavior.
The whole project (in its minimal version) is attached to this issue. Just “Start” it in Debug mode.

MLContext mlContext = new MLContext();
DataViewSchema predictionPipelineSchema;
ITransformer predictionPipeline = mlContext.Model.Load(this.modelLocation, out predictionPipelineSchema);

- Attach the ONNX model to the issue (where applicable)
Also attached inside project assets folder.

### Expected behavior
Model should load and create an OnnxModelScorer object.

### Notes
[Issue code and model.zip](https://github.com/onnx/onnx/files/5459500/Issue.code.and.model.zip)
The model file was downloaded from ML zoo, and opens correctly with Netron. Also tried other models (yolo3, yolo3_tiny) and the compressed tar.gz yolo4 model, always the same error.

The Yolo4.onnx file is in this URL:  
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov4/model 
 This file needs to be copied into assess folder inside the solution tree.

**Comment by ADD-eNavarro** [comment]
I'm having that exact same error. Hoping to see some news about this issue!

**Comment by puppetSpace** [comment]
I'm having the same issue. But when I look at examples, they all seem to load a zip file. 
It would be great to have some more documentation on this. How do we create that zip file?
