### ISSUE TITLE
CircleCI build failing

### ISSUE THREAD

**Issue by annajung** [onnx/onnx#3089]
# Bug Report

### Describe the bug
Bug Report related to a build pipeline

The build pipeline, specifically circleci build script is failing on the main branch. [PR that contains only changes to markdown](https://github.com/onnx/onnx/pull/3087) resulted in a [failed build](https://app.circleci.com/pipelines/github/onnx/onnx/6102/workflows/1082cf00-56c1-413b-8d9d-4fbdb11bafc4/jobs/6174) due to the build step failing

**Comment by jcwchen** [comment]
Hi annajung,
`circleci` is planned to be deprecated so please just ignore it for now. Sorry for the confusion.

**Comment by annajung** [comment]
Thanks for sharing that info. 
Will close this issue as it will no longer be relevant.
