### ISSUE TITLE
error??

### ISSUE THREAD

**Issue by jiagh2010** [onnx/onnx#3091]
# Ask a Question

### Question
runtimeerror:validator error:layer prelu1_11 produces an output named bn1 which is also an output produced by the layer bn1

inceptionv3->onnx

**Comment by snnn** [comment]
Could you please give us more information?  Sorry I couldn't understand it. 
Were you trying to convert the inceptionv3 model?

**Comment by jcwchen** [comment]
Since we haven't received any response, close this issue now. Please reopen it if you still have question. Thanks.
