### ISSUE TITLE
Exception when caffe2.python.onnx.backend.prepare ResNet101-DUC-7.onnx

### ISSUE THREAD

**Issue by bbap-7fat** [onnx/onnx#3096]
# Bug Report

### Is the issue related to model conversion?
check_model("ResNet101-DUC-7.onnx") is okay.

### Describe the bug
In my code, when using 
`session = caffe2.python.onnx.backend.prepare("ResNet101-DUC-7.onnx")`, it will show the following error message:
Exception: [enforce fail at backend.cc:1481] . Don't know how to map unexpected argument spatial (from operator SpatialBN)

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 16.04
- ONNX version (*e.g. 1.7*):  1.7.0
- Python version: 3.5.6

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
import caffe2.python.onnx.backend as onnx_backend
import sys

#sys.argv[1] is my ResNet101-DUC-7.onnx path
model = onnx.load(sys.argv[1])
onnx.checker.check_model(model)

print("model checked")
session2 = onnx_backend.prepare(model)
```
- Attach the ONNX model to the issue (where applicable)
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/duc

### Expected behavior
should not occur exception

### Full error message:
```
ONNX FATAL: Error while processing node: input: "conv1_1_3x3_s2"
Exception: [enforce fail at backend.cc:1481] . Don't know how to map unexpected argument spatial (from operator SpatialBN)
```

**Comment by jcwchen** [comment]
Hi @bbap-7fat,
This model looks good to me and it can be correctly checked and shape_inferred by ONNX. I would say it's more like a converter issue. Have you used the latest caffe2? 
https://github.com/pytorch/pytorch/issues/9375 I don't know whether caffe2 folks have fixed this yet. You can follow up with them there. Thank you!

**Comment by bbap-7fat** [comment]
hi @jcwchen 
Thanks for redirecting me. https://github.com/pytorch/pytorch/issues/9375 seems to handle when spatial = 1, doesn't deal with spatial !=1. My case is spatial = 0 :(

**Comment by jcwchen** [comment]
Tracking this issue in pytorch is better. Please reopen it if you still have other questions related to ONNX. Thanks!
