### ISSUE TITLE
BUG of onnx.helper.make_tensor() : length of val

### ISSUE THREAD

**Issue by waittim** [onnx/onnx#3115]
# BUG of onnx.helper.make_tensor() : length of val

It looks like make_tensor can not deal with the situation that vals argument has a complex shape.
The original code of `make_tensor()` is:
```
def make_tensor(
        name,  # type: Text
        data_type,  # type: int
        dims,  # type: Sequence[int]
        vals,  # type: Any
        raw=False  # type: bool
):  # type: (...) -> TensorProto
    '''
    Make a TensorProto with specified arguments.  If raw is False, this
    function will choose the corresponding proto field to store the
    values based on data_type. If raw is True, use "raw_data" proto
    field to store the values, and values should be of type bytes in
    this case.
    '''
    tensor = TensorProto()
    tensor.data_type = data_type
    tensor.name = name

    if data_type == TensorProto.STRING:
        assert not raw, "Can not use raw_data to store string type"

    # Check number of vals specified equals tensor size
    size = 1 if (not raw) else (mapping.TENSOR_TYPE_TO_NP_TYPE[data_type].itemsize)
    for d in dims:
        size = size * d
    if (len(vals) != size):
        raise ValueError("Number of values does not match tensor's size.")

    if (data_type == TensorProto.COMPLEX64
            or data_type == TensorProto.COMPLEX128):
        vals = split_complex_to_pairs(vals)

    if raw:
        tensor.raw_data = vals
    else:
        field = mapping.STORAGE_TENSOR_TYPE_TO_FIELD[
            mapping.TENSOR_TYPE_TO_STORAGE_TENSOR_TYPE[data_type]]
        getattr(tensor, field).extend(vals)
    tensor.dims.extend(dims)
    return tensor
```

For example, if the dims is `[1, 3, 10, 16, 2, 5]`, the size would be 9600, but` len(vals)` would be 1.
```
    for d in dims:
        size = size * d
    if (len(vals) != size):
        raise ValueError("Number of values does not match tensor's size.")
```
It will cause an error. However, it possible for this kind of node:
![image](https://user-images.githubusercontent.com/34759452/99179908-c0e1e100-26ef-11eb-9b46-b304a0efc670.png)

- Is this issue related to a specific model?  Maybe?
**Model name** : [yolo-fastest.onnx (simplified) ](https://github.com/waittim/mask-detector/blob/master/modeling/weights/yolo-fastest-sim.onnx) 
**Model opset** : 11

I'm working on converting the model from int64-based to int32-based manually. May I know is there any easy way besides *reading node -> making new node in INT32 -> removing old node -> adding new node*?

Thank you so much!

**Comment by yuyijie1995** [comment]
Hi, have you solved this error?

**Comment by Freewavs** [comment]
onnx.helper.make_tensor("name0", onnx.TensorProto.FLOAT, dims=(1, 3, 10, 16, 2, 5), vals=np.ones((1*3*10*16*2*5,), dtype=np.float32))
