### ISSUE TITLE
`polish_model` still uses `onnx.optimizer` which is being removed in ONNX 1.9.0 and produces a warning

### ISSUE THREAD

**Issue by ziyadedher** [onnx/onnx#3116]
# Feature Request

### System information
ONNX version (you are using): 1.8.0

### What is the problem that this feature solves?
`onnx.optimizer` [is being removed](https://github.com/onnx/onnx/blob/master/onnx/optimizer/optimize.cc) in ONNX 1.9.0 but `polish_model` [still uses it](https://github.com/onnx/onnx/blob/master/onnx/utils.py#L17) causing a warning when using the utility.

### Describe the feature
Check for the existence of `onnxoptimizer` and use that optimizer package rather than `onnx.optimizer` if it exists.

### Will this influence the current api?
No.

### Feature Area
ONNX utilities.

### Are you willing to contribute it (Y/N):
Sure, but I think that someone with the environment already set up could do this a lot faster.

**Comment by jcwchen** [comment]
Hi @ziyadedher,
It will be removed with optimizer in ONNX 1.9 https://github.com/onnx/onnx/pull/2834/files. And ONNX 1.8 has just been released recently. Thank you for pointing out.
