### ISSUE TITLE
INT32 supporting for ConstantOfShape Operator

### ISSUE THREAD

**Issue by waittim** [onnx/onnx#3118]
# Feature Request

### System information
ONNX version (you are using): 1.8.0

### What is the problem that this feature solves?
I'm trying to modify the onnx model by hand to make it use INT32 as datatype, which can be handled by ONNX.js. However, I find the Operator **ConstantOfShape** doesn't support INT32 as input. May I know is it possible that add the support for INT32 for ConstantOfShape? Thank you!

The Error met when I'm using onnxruntime to test:
`InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from weights/yolo-fastest-transfer.onnx failed:This is an invalid model. Type Error: Type 'tensor(int32)' of input parameter (1540) of operator (ConstantOfShape) in node (ConstantOfShape_245) is invalid.`

### Describe the alternatives you have considered
Maybe there is an alternative Operator which supports INT32 to replace ConstantOfShape.

### Describe the feature
Why is this feature necessary? What does it accomplish?
It could make ONNX model supported in more environment, considering not all of the environment support INT64.

### Will this influence the current api?
No

### Feature Area
Which area in ONNX does this impact?  operators

### Notes
You can find the model I used [here](https://github.com/waittim/mask-detector/blob/master/modeling/weights/yolo-fastest.onnx). And the modify-process [here](https://github.com/waittim/mask-detector/blob/master/modeling/30-edit-ONNX.ipynb).

**Comment by askhade** [comment]
@waittim : Is there a specific reason you want to convert the input to INT32 for this op? The input to this op is shape of the tensor and does it really matter if it is INT64 vs INT32? Since this is the shape it's not like you can save a considerable amount of memory moving from INT64 to INT32

**Comment by waittim** [comment]
I wanna do the inference in the browser with ONNX.js. The javascript environment doesn't support int64.
