### ISSUE TITLE
'NonZero' has_shape() is false

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/onnx#3123]
# Bug Report

### Is the issue related to model conversion?
No. Model is converted successfully from tf2onnx.

### Describe the bug
While reading the onnx model using C++ APIs, I am getting has_shape as false for 'NonZero' operator.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Mac OS Catalina
- ONNX version (*e.g. 1.7*):  1.7
- Python version: 3.6
- GCC/Compiler version (if compiling from source): pip based
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
onnx::ModelProto model;
ParseOnnx(input_stream, model)
const onnx::GraphProto& onnx_graph =  model.graph();
const OnnxValueInfos& value_infos = onnx_graph.value_info();
for(const auto& value_info : value_infos)
 {
     const onnx::TypeProto_Tensor& type_proto = value_info.type().tensor_type();
    if(!type_proto.has_shape())
                {
                  // error: shape is zero
                }
 }
```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
NonZero will always produces output tensor of RANK 2. It should be empty space.

### Notes

Any additional information

**Comment by buddhapuneeth** [comment]
Adding sample model:
For ONNX Text file:
[where_test.txt](https://github.com/onnx/onnx/files/5592275/where_test.txt)
For Source ONNX and PB files: https://1drv.ms/u/s!Auhnl7nI-7bxgo0xWWM6NCudzN2edA?e=1Xs7XJ

How to reproduce:
```
import onnx
from onnx import helper, shape_inference
from onnx import TensorProto
model1 = onnx.load("where_test.onnx")
# Apply shape inference on the model
inferred_model1 = shape_inference.infer_shapes(model1)

# Check the model and print Y's shape information
onnx.checker.check_model(inferred_model1)
print('After shape inference, the shape info of Y is:\n{}'.format(inferred_model1.graph.value_info))
```
output
```
After shape inference, the shape info of Y is:
[name: "output_raw_output___3:0"
type {
  tensor_type {
    elem_type: 7
  }
}
]
```
Ideally it should contain shape info of `output_raw_output___3:0`

**Comment by jcwchen** [comment]
Hi @buddhapuneeth,
Currently NonZero operator only supports type inference (no shape inference). You can check here: https://github.com/onnx/onnx/blob/6fb8e67863af3118ce73829b99941c2d2c0baaa6/onnx/defs/tensor/defs.cc#L2660 

Since the behavior is same as numpy.nonzero, actually I don't think the output will always be rank 2. Instead, it will depend on the dimension of input. Thanks.

**Comment by buddhapuneeth** [comment]
Hi @jcwchen 
Yes, I noticed there is only type inference for nonZero. I am making a fix for shape inference as well.
I believe it will be always rank 2. 
dim 0: is the rank of input tensor
dim 1: #of non zero values in the input tensor
 value of dim 1 we cannot infer but we know that it will be always of rank 2. 
My current fix is to add shape inference of size (rank of input tensor, max number of non zeros)
where max number of non zeros = product of input tensor dims (idea here is assuming entire tensor is non zeros).
Please let me know your thoughts.

**Comment by jcwchen** [comment]
Thank you for the contribution.

ONNX `NonZero` operator behaves like numpy.nonzero: https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html
Let's say if the input tensor is a 3D array (rank 3), I think the output rank will be 3 as well?

**Comment by buddhapuneeth** [comment]
@jcwchen 
For example in below rank 3 example:
`x = np.array([[[3, 0, 0], [0, 4, 0]],
		     [[0, 1, 0], [5, 6, 0]]])
`
with shape `(2, 2, 3)`.
`y = np.nonzero(x)`
y will have value:
`(array([0, 0, 1, 1, 1]), array([0, 1, 0, 1, 1]), array([0, 1, 1, 0, 1]))`
if we represent it as tensor, it will be like
`[[0, 0, 1, 1, 1]
   [0, 1, 0, 1, 1]
   [0, 1, 1, 0, 1]]`
which is of `shape 3*5` and `RANK 2`

**Comment by jcwchen** [comment]
@buddhapuneeth  Thank you for the detailed explanation.  I believe you are right. The only corner case would be 1D input, but I would say the output should be rank 2 as well. Feel free to submit a PR in ONNX to fix shape_inference for nonzero and let's review there. Thanks!

**Comment by buddhapuneeth** [comment]
Added PR: https://github.com/onnx/onnx/pull/3207

**Comment by jcwchen** [comment]
IIUC, this issue should be solved by https://github.com/onnx/onnx/pull/3364. Close here now. Thanks!
