### ISSUE TITLE
How to change the tensor shape of onnx

### ISSUE THREAD

**Issue by noticedollar** [onnx/onnx#3125]
Hi,
If I want to change the shape from [-1,96,2,2,128,128] to [1,96,2,2,128,128], how to do it? thanks.

![image](https://user-images.githubusercontent.com/62462953/99945472-a4107200-2daf-11eb-8634-16b81e9485e3.png)

**Comment by thiagocrepaldi** [comment]
You can manipulate the dimensions. The prototype can be found at https://github.com/onnx/onnx/blob/925b3657924c0c16cd20b54595f41e76159b03ab/onnx/onnx.proto#L614
