### ISSUE TITLE
would it be possible to have a Python-3.9 wheel for windows 10 ?

### ISSUE THREAD

**Issue by stonebig** [onnx/onnx#3132]
Dream is to have a Python-3.9 wheel under the christmas 2020 tree

**Comment by askhade** [comment]
@stonebig we will plan to support this wheel in the next release. In the meanwhile have you tried building from source? BTW Conda has windows 3.9 package for onnx have you checked that? https://anaconda.org/conda-forge/onnx/files

**Comment by stonebig** [comment]
I didn't attempt to build from source. I'm not using conda

**Comment by jcwchen** [comment]
Hi @stonebig,  Python 3.9 has been supported by recent ONNX 1.9.
