### ISSUE TITLE
Exporting the operator max_unpool2d to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by tlk2abhishek** [onnx/onnx#3138]
raise RuntimeError(msg)
RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing 
operator.

torch version = 1.7.0
onnx = 1.5.0

We re trying to convert a pretrained model file (.pkl format) to ONNX framework.

**Comment by jcwchen** [comment]
Hi @tlk2abhishek,
Yes it's a known problem in pytorcn-onnx converter. https://github.com/pytorch/pytorch/issues/25088 I saw you noticed that issue, too. Track there makes more sense. Thanks!
