### ISSUE TITLE
Onnx Batch Processing 

### ISSUE THREAD

**Issue by agemagician** [onnx/onnx#3143]
# Ask a Question

### Question
I have converted Bert Model from transformers to onnx. When I use single sample per batch, the results matches with the original Pytorch model. However, when I predict the output of many samples per batch, the results are totally different than the original Pytorch model.
Is there anything that we need to modify to make onnx predict batch of samples, or it can only work with a single sample per batch ?

### Further information
- Relevant Area (prediction): 

- Is this issue related to a specific model?  
**Model name** (Bert):  
**Model opset** (12):

### Notes
Code example:
https://github.com/agemagician/ProtTrans/blob/master/Embedding/Onnx/ProtBert-BFD.ipynb

**Comment by askhade** [comment]
@agemagician : Since the issue is related to inferencing for this model please open the issue in the appropriate backend\runtime repository. In your case ONNXRuntime https://github.com/microsoft/onnxruntime/issues

**Comment by agemagician** [comment]
Thanks for the explanation. I will close it here and add it there, as you recommended.
