### ISSUE TITLE
How can one best dequantize the weights of the EfficientNet-Lite4 model?

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [onnx/onnx#3145]
The EfficientNet-Lite4 model states that it is an 'integer-only quantized' model.  Is there a known zero point and scale used to quantize the weights that could be used to dequantize them to float or double?

https://github.com/onnx/models/tree/master/vision/classification/efficientnet-lite4

Thanks!

**Comment by askhade** [comment]
I looked at the model and it is not a quantized model. Not sure why the description says that...
example:
![image](https://user-images.githubusercontent.com/6475296/101556864-9e4e8b00-3970-11eb-8f04-2aeb721b4704.png)
