### ISSUE TITLE
Is there any methods or best practices that can count flops and parameters of the onnx model? 

### ISSUE THREAD

**Issue by ytfksw** [onnx/onnx#3147]
Is there any methods or best practices that can count parameters and flops of the onnx model? 

I found related question #2985.

**Comment by jcwchen** [comment]
Hi @ytfksw,
As you can see in the related question, I don't think ONNX have such a method right now. I have labeled it as an enhancement. Thanks.

**Comment by askhade** [comment]
It should be fairly easy to add a utility method for this. I responded in the discussion thread. Closing this issue. Let's use the discussion thread #2985 to track this.
