### ISSUE TITLE
从onnx转化为TensorRT ，ERROR: reshape dimension of -1

### ISSUE THREAD

**Issue by guangpec1** [onnx/onnx#3149]
从onnx转化为TensorRT ，遇到 reshape dimension of -1 的问题
[TensorRT] VERBOSE: Tactic: 1 time 0.004096
[TensorRT] VERBOSE: Tactic: 2 time 0.004096
[TensorRT] VERBOSE: Fastest Tactic: 1 Time: 0.004096
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,16), Float(1,16) -> Float(1,16) ***************
[TensorRT] VERBOSE: --------------- Timing Runner: (Unnamed Layer* 131) [ElementWise] (ElementWise)
[TensorRT] VERBOSE: Tactic: 1 is the only option, timing skipped
[TensorRT] VERBOSE: Fastest Tactic: 1 Time: 0
[TensorRT] VERBOSE: *************** Autotuning format combination: Float(1,64,(* 64 (BROADCAST_SIZE (# 1 (SHAPE Placeholder_1:0)) (# 1 (SHAPE Placeholder_2:0))))) -> Float(1,36) ***************
[TensorRT] ERROR: shapeMachine.cpp (144) - Shape Error in executeReshape: 0 (reshape dimension of -1 has no solution)
Traceback (most recent call last):
  File "dynamic_shape.py", line 22, in <module>
    with builder.build_engine(network, config) as engine:
AttributeError: __enter__

**Comment by askhade** [comment]
@guangpec1 : There is not enough info to understand what is going on. However it looks like the issue with with runtime and not ONNX. Please open the issue in the relevant repo first. closing this now. If you think this is indeed an issues with ONNX please reopen with more info
