### ISSUE TITLE
Is there any way to know the model framework (e.g. pytorch or tensorflow) from onnx model?

### ISSUE THREAD

**Issue by HelenaBahrami** [onnx/onnx#3156]
I was wondering if there is a way to know the model framework (pytorch or tensorflow) from onnx model?

**Comment by askhade** [comment]
@HelenaBahrami 

ModelProto has a field Producer which stores this info. Please check: 
https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L352

Example:
![image](https://user-images.githubusercontent.com/6475296/101555820-40b93f00-396e-11eb-8a7c-3d034f79d8e3.png)

Closing this issue. Please reopen if need be.

**Comment by HelenaBahrami** [comment]
Thank you Ashwini :+1:
