### ISSUE TITLE
Reload and save the onnx model with external data format will cause runtime error

### ISSUE THREAD

**Issue by wangyems** [onnx/onnx#3157]
# Bug Report

### Is the issue related to model conversion?
NO

### Describe the bug
Please describe the bug clearly and concisely

Having an onnx model that has been exported from pytorch(using external data format) and inference without any issues.
Load the model for whatever modification(or just do nothing) and save to a different path using external data format
The saved model will trigger runtime error like: Error in Node:.... : Data of TensorProto ( tensor name: ....) should be stored in ...., but it doesn't exist or is not accessible. 
Have checked that the file is existed in the path, and with proper content.
Well this issue can be workaround by preventing the problematic tensor to set to external data, but it might be a potential bug on onnx saving with external data format.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version (*e.g. 1.7*):  
- Python version:
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
Having reproduction code and model on shared machine. ping me for details. Thanks

### Expected behavior
The saved model should be valid

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @wangyems,
Do you have an example model and script to repro this issue? Thank you.
