### ISSUE TITLE
not support Python operator 

### ISSUE THREAD

**Issue by jefferyZhan** [onnx/onnx#3158]
when I tried to convert the TSN model to onnx, an runtime error occured, it reported that "RuntimeError: ONNX export failed: Couldn't export Python operator SegmentConsensus". 
I find this function code, and it occured in this sentence:
        return SegmentConsensus().apply(input)
and the "SegmentConsensus" function is:
class SegmentConsensus(torch.autograd.Function):
    @staticmethod
    def forward(self, input_tensor):
        self.shape = input_tensor.size()
        output = input_tensor.mean(dim=1, keepdim=True)
        return output
    @staticmethod
    def backward(self,grad_output):
        grad_in = grad_output.expand(self.shape) / float(self.shape[1])
        return grad_in

onnx:1.8.0
protobuf:3.13.0
pytorch:1.6.0
torchvision:0.7.0

Can someone help me find which operator, function , ot method resulting in this error? Thanks a lot!!!

**Comment by jcwchen** [comment]
Hi @jefferyZhan,
This should be a converter issue. I suggest you open an issue under pytorch to get the best help from the converter team. Close now and please reopen it if you have other ONNX issue. Thank you..

**Comment by zhudongwork** [comment]
> when I tried to convert the TSN model to onnx, an runtime error occured, it reported that "RuntimeError: ONNX export failed: Couldn't export Python operator SegmentConsensus". I find this function code, and it occured in this sentence: return SegmentConsensus().apply(input) and the "SegmentConsensus" function is: class SegmentConsensus(torch.autograd.Function): @staticmethod def forward(self, input_tensor): self.shape = input_tensor.size() output = input_tensor.mean(dim=1, keepdim=True) return output @staticmethod def backward(self,grad_output): grad_in = grad_output.expand(self.shape) / float(self.shape[1]) return grad_in
> 
> onnx:1.8.0 protobuf:3.13.0 pytorch:1.6.0 torchvision:0.7.0
> 
> Can someone help me find which operator, function , ot method resulting in this error? Thanks a lot!!!

I have the same problem, did you solve it？
