### ISSUE TITLE
Type inference for integer input

### ISSUE THREAD

**Issue by matteosal** [onnx/onnx#3161]
Several operators are set to produce integer outputs from integer inputs, even if the operation they perform clearly doesn't conserve the integer type. For example consider this type inference example for `Sin`:
```
import onnx
from onnx import helper, shape_inference
from onnx import TensorProto

node = helper.make_node('Sin', ['X'], ['Y'])

graph = helper.make_graph(
    [node],
    'my-graph',
    [helper.make_tensor_value_info('X', TensorProto.INT64, (2, 3))],
    [helper.make_tensor_value_info('Y', TensorProto.FLOAT, (2, 3))],
)

model = helper.make_model(graph)

shape_inference.infer_shapes(model)
```
If fails with:
```
RuntimeError: Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)
```
But the Sin of an integer number is clearly *not* an integer number! This can mean one of two things:
1) That is a mistake and type inference should produce floats
2) The ONNX definition of the Sin operator for integer inputs is round(sin(x))

In case (2) is true, enforcing such behaviour on `Sin` itself seems undesirable, because:
1) It effectively locks ONNX out of certain operations. `Sin` is a simple example, but this behaviour is also exhibited by important operators like `LSTM`, and it's not crazy to think of some model wanting to feed a sequence of integers to a recurrent layer and expecting floats to be produced for e.g. a softmax classification. It seems that such operation is currently not possible in ONNX (one could put a `Cast` after the rnn to enforce floats, but precision would be lost).
2) ONNX has a `Round` operator already, so if one wants round(sin(x)) that's perfectly possible without having the `Sin` produce integers.

**Comment by TMVector** [comment]
Hi @matteosal, the [`Sin` operator](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Sin) doesn't support integer types (I imagine for exactly the reasons you mentioned). To use `Sin` with integer input, you would need to [`Cast`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast) to a floating point type first.

Unfortunately the onnx checker and shape inference tools cann't guarantee your model is fully correct, only catch some classes of errors. I would recommend you reference the [docs](https://github.com/onnx/onnx/blob/master/docs) to understand limitations and possibilities :)

**Comment by matteosal** [comment]
Ah sorry, I should have checked the docs!
I was lead into thinking ints are supported because both sanity check and shape inference complete without errors when both input and output are integer, on a wide variety of operators (`Sin` was just a simple example). 

Thanks for clarifying!
