### ISSUE TITLE
New Operator Addition

### ISSUE THREAD

**Issue by jay-karan** [onnx/onnx#3164]
### Question in Short
Can we add new operators?

### Question in Brief
- Does the current set of operators [here ](https://github.com/onnx/onnx/blob/master/docs/Operators.md) support all the operations from other frameworks?

- How do I understand the need of new operator (any example is highly appreciated)? 

- How do I contribute to add one?

- Does the implementation of operators [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md) available? If so, is it possible to point to that page.

**Comment by jcwchen** [comment]
Hi @jay-karan,
> ### Question in Short
> Can we add new operators?

Yes. Instruction is here: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md

> ### Question in Brief
> * Does the current set of operators [here ](https://github.com/onnx/onnx/blob/master/docs/Operators.md) support all the operations from other frameworks?

No. If you need an operator which is not listed there, you can propose it by the above method.

> * How do I understand the need of new operator (any example is highly appreciated)?

You can check other issues with tag of operator or enhancement.

> * How do I contribute to add one?

Also check here:  https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md

> * Does the implementation of operators [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md) available? If so, is it possible to point to that page.

More details of definition and inference are here: onnx/onnx/defs/xxx/def.cc

Thank you.

**Comment by jay-karan** [comment]
Thank you @jcwchen 

- How can I find what all operators from different frameworks are being supported?
- Are there any helper functions or documents to find them?

**Comment by jcwchen** [comment]
> Thank you @jcwchen
> 
> * How can I find what all operators from different frameworks are being supported?

pytorch is here: https://github.com/onnx/tensorflow-onnx/blob/master/support_status.md
tensorflow is here: https://github.com/onnx/tensorflow-onnx/blob/master/support_status.md

> * Are there any helper functions or documents to find them?

Basically I think you will need to find them in the converter's repo or website. ONNX doesn't have such things here. Thanks.

**Comment by jay-karan** [comment]
Thanks @jcwchen. Information was helpful.

I assume that adding new operators to ONNX is defining the definition of the operator (inputs, outputs, attributes, constraints) but not writing any implementation/kernel code. Please validate me if I am correct?

**Comment by jcwchen** [comment]
Yes you are right. You can see more related discussion in a recent issue: https://github.com/onnx/onnx/issues/3205
Basically ONNX is a definition and spec, you will need to implement execution logic in other Runtime frameworks. Thanks.

**Comment by jay-karan** [comment]
Yes @jcwchen, thank you. I've gone through it.

Before raising for a PR and following the steps in [here](https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md) , I want to define a new operator (custom operator, like an operator built using primitive operators of onnx) in ONNX and validate. May you help me in pointing out an example and relevant pages which can help me.

Thank you.

**Comment by jcwchen** [comment]
If you are doing operator fusion as a function, you can take the following PRs as examples: https://github.com/onnx/onnx/pull/2606 https://github.com/onnx/onnx/pull/2187
If you are proposing a new operator without using current operators, there is an example in the document already: https://github.com/onnx/onnx/pull/1959

**Comment by jay-karan** [comment]
Thank you @jcwchen 

The operators in #2606 would have been actually implemented in frameworks like tensorflow, etc right. So, the convertor functions like tf2onnx would use the schema defined in #2606 for converting the graph (a graph with operators in #2606)?

Is my understanding correct? May I ask you to validate me?

**Comment by jay-karan** [comment]
Furthermore, May I ask you to help me in pointing out to the implementation page of the operators from #2606 on ONNX Runtime?

**Comment by jcwchen** [comment]
> Thank you @jcwchen
> 
> The operators in #2606 would have been actually implemented in frameworks like tensorflow, etc right. So, the convertor functions like tf2onnx would use the schema defined in #2606 for converting the graph?
> 
> Is my understanding correct? May I ask you to validate me?

Correct.

> Furthermore, May I ask you to help me in pointing out to the implementation page of the operators from #2606 on ONNX Runtime?

This is the related PR:
https://github.com/microsoft/onnxruntime/commit/6037b41c17e415aad99e0c880626cf3c4896918e#diff-f88bf3bdbe0843e5c0012725eac0cac6f0566fee2b0e511ae707db157629c4f8

**Comment by jay-karan** [comment]
Thank you.

Looks like the related PR is only aligned for DirectML Execution Provider. Isn't it for the general CPU ORT?

**Comment by jcwchen** [comment]
Yes they are not included in CPU provider of ORT... If you are looking for CPU's example, you can check this one https://github.com/microsoft/onnxruntime/pull/1697. Thanks.

**Comment by jay-karan** [comment]
Thanks for the complete support!
