### ISSUE TITLE
ONNX export failed on ATen operator new_zeros

### ISSUE THREAD

**Issue by nehasoni3** [onnx/onnx#3165]
Hey,
I am working to convert PyTorch-Tacotreon2 model into ONNX but getting this error:
**UserWarning: ONNX export failed on ATen operator new_zeros because torch.onnx.symbolic_opset10.new_zeros does not exist
  .format(op_name, opset_version, op_name))**

**KeyError: 'new_zeros'**
Please do needful in this regard.

**Comment by jcwchen** [comment]
Hi @nehasoni3,
It looks like a converter issues. Please open an issue under pytorch with keyword ONNX to get the best help. Thank you.

**Comment by spandantiwari** [comment]
@nehasoni3 - I see that you have already opened an issue in PyTorch. I will close this one and track the other one. https://github.com/pytorch/pytorch/issues/49403
