### ISSUE TITLE
UnliftableError: ONNX model to Tensorflow

### ISSUE THREAD

**Issue by nehasoni3** [onnx/onnx#3166]
Hi,
I am working on Tacotron2 PyTorch. I have trying to get its encoder part and successfully converted into ONNX format. But when I am trying to convert ONNX model into Tensorflow. It gives error:

**UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(768, 1024) dtype=float32> because it depends transitively on placeholder <tf.Operation 'split_1/279' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_3 (Split) <- Squeeze_1 (Squeeze) <- split_1 (Split) <- split_1/279 (Placeholder)**

**Comment by jcwchen** [comment]
Hi @nehasoni3,
Similar to this one https://github.com/onnx/onnx/issues/3032? It's a converter issue, please open an issue in onnx-tensorflow.

Besides, you can find some helpful information here: https://github.com/tensorflow/tensorflow/issues/43808 Thanks.

**Comment by jcwchen** [comment]
This issue has been forwarded to a proper place. Please reopen it if you still have any ONNX related issues. Thank you.
