### ISSUE TITLE
How to convert onnx model without dynamic shape tensor?

### ISSUE THREAD

**Issue by mathmax12** [onnx/onnx#3168]
# Ask a Question

### Question
Is there a possible way to replace the dynamic shape of the tensor with a static shape when convert the model to onnx in pytorch?

**Comment by TMVector** [comment]
Hi @mathmax12, normally people ask the opposite -- how can they make tensor dimensions dynamic -- see the first question in https://pytorch.org/docs/stable/onnx.html#frequently-asked-questions. If you are telling PyTorch about any `dynamic_axes` then you could remove the axes you don't want to be dynamic from that dictionary.

If you mean you have unexpected `Shape` ops in your ONNX graph, then you could try @daquexian's tool: https://github.com/daquexian/onnx-simplifier.

**Comment by mathmax12** [comment]
@TMVector  Thanks a lot for that.

The input to the model is the static shape.  My model has some dynamic shape inside of the model:
I wonder is there a way to make that static?

```

%95 = reshape(%94, newshape=[**-1**, 2]);
  %96 = scatter(meta[relay.Constant][4], %v603, %v604, meta[relay.attrs.ScatterAttrs][6]);
  %97 = cast_like(0, %96);
  %98 = less(%96, %97);
  %99 = shape_of(%95, dtype="int32");
  %100 = cast_like(%99, %96);
  %101 = add(%96, %100);
  %102 = where(%98, %101, %96);
  %103 = shape_of(%95, dtype="int64");
  %104 = scatter(%103, %v603, %v605, meta[relay.attrs.ScatterAttrs][7]);
  %105 = scatter(meta[relay.Constant][5], %v603, %v606, meta[relay.attrs.ScatterAttrs][8]);
  %106 = dyn.strided_slice(%95, %102, %104, %105, begin=None, end=None, strides=None);
  %107 = transpose(%106, axes=[1, 0]);
  %108 = reshape(%107, newshape=[**-1**]);
  %109 = cast(%108, dtype="int64");
  %110 = reshape(%109, newshape=[2, **-1**]);
```

**Comment by TMVector** [comment]
@mathmax12 okay, sounds like you should try `onnx-simplifier` then 🙂. The [README](https://github.com/daquexian/onnx-simplifier/blob/master/README.md) (which talks about a very similar problem), explains how to use the command-line interface, or the Python API.
