### ISSUE TITLE
Does onnx support tensorflow ops like TensorArrayV2?

### ISSUE THREAD

**Issue by wangqiaoshi** [onnx/onnx#3172]
# Ask a Question

### Question
Does onnx support tensorflow ops TensorListReserve、TensorListGetItem、TensorListSetItem、TensorListStack、TensorListFromTensor、TensorListConcatV2、TensorListGather...? What is an operation in onnx

**Comment by jcwchen** [comment]
Hi @wangqiaoshi,
Support status is here: https://github.com/onnx/tensorflow-onnx/blob/master/support_status.md
tensorflow-onnx does support TensorListReserve, TensorListGetItem, TensorListSetItem, TensorListStack and TensorListFromTensor.
For conversion details, you might need to check https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/controlflow.py to see what the corresponding ONNX opsets are. Thanks.

**Comment by jcwchen** [comment]
I assume this issue has been resolved. Please reopen it if you still have any ONNX related issues. Thank you.
