### ISSUE TITLE
Pytorch export onnx: RuntimeError  Exporting the operator view_as_complex to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator

### ISSUE THREAD

**Issue by iou2much** [onnx/onnx#3173]
# Feature Request
would you support torch.view_as_complex ? Thanks a lot
### System information
ONNX version (you are using): opset 9~11

**Comment by jcwchen** [comment]
Hi @iou2much,

I suppose this can be done in pytorch-onnx converter with existing ONNX operators. Please open an issue under pytorch repo to request support from the converter team. Thank you.

**Comment by iou2much** [comment]
I'm also trying to do it myself, following this [doc](https://pytorch.org/docs/stable/onnx.html#custom-operators), but I'm quite new to pytorch. I'm not sure how to implement a new method which is not standardized in Onnx.

**Comment by iou2much** [comment]
Thank you for your reply, @jcwchen 
I'm also try to implement it myself. I successfully export a pytorch model to onnx pb file, with the functions adding to symbolic_opset11.py in pytorch.

```python
def view_as_complex(g, self):
    if sym_help._operator_export_type == torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK:
        return g.op("ATen", (self,), operator_s='view_as_complex')

def real(g, self):
    if sym_help._operator_export_type == torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK:
        return g.op("ATen", (self,), operator_s='real')
def imag(g, self):
    if sym_help._operator_export_type == torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK:
        return g.op("ATen", (self,), operator_s='imag')

def view_as_real(g, self):
    if sym_help._operator_export_type == torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK:
        return g.op("ATen", (self,), operator_s='view_as_real')

def atan2(g, self, other):
    if sym_help._operator_export_type == torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK:
        return g.op("ATen", (self,other), operator_s='atan2')
```
And converted it with this code:
```python
    torch.onnx.export(model, net_inp, "/tmp/model.proto",
        operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN, 
        verbose=True,
        opset_version=11)
```

But when I try to run it with onnxruntime, I got this error:

```
Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model.proto failed:Fatal error: ATen is not a registered function/op
```

Could you give me some hint or some links for solving it? Thank you very much.

I try to follow these docs, but still not quite clear about how to solve it .

https://pytorch.org/docs/stable/onnx.html
https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator
https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md

**Comment by EmreOzkose** [comment]
Any improvement in this issue?

**Comment by jcwchen** [comment]
Hi @EmreOzkose,
https://github.com/pytorch/pytorch/issues/49793 I think it hasn't been supported yet.

**Comment by ruanhailiang** [comment]
Any improvement in this issue?

**Comment by jcwchen** [comment]
> pytorch/pytorch#49793 I think it hasn't been supported yet.

I don't think so --  please track this support there since it's a question for the converter. Thanks!
