### ISSUE TITLE
Exporting the operator slogdet to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by Aurimasp** [onnx/onnx#3174]
# Feature Request
**slogdet** operator

### System information
ONNX version (9-12):

### What is the problem that this feature solves?
Hello, I would like to request support for this operator. Thank you.

**Comment by jcwchen** [comment]
Hi @Aurimasp,
I assume you are asking the converter (pytorch.onnx.export) to support such operator. I am not sure whether it can be done by existing ONNX operators so please open the support request under pytorch repo to seek help from the converter team. Thanks.

**Comment by Aurimasp** [comment]
Yes, I'm trying to convert a model, which uses this operator. 
Thank you for the guidelines.
