### ISSUE TITLE
HardSigmoid

### ISSUE THREAD

**Issue by alicera** [onnx/onnx#3179]
onnx version 1.6.0 ，1.7.0
pytorch version  '1.7.0a0+7036e91

Exporting  the operator hardsigmoid to ONNX  fail.

It say the hardsigmoid is supported.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#HardSigmoid

But
Starting ONNX export with onnx 1.6.0...
ONNX export failure: Exporting the operator hardsigmoid to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by jcwchen** [comment]
Hi @alicera,
ONNX does support this operator, but it seems that pytorch converter does not: https://pytorch.org/docs/stable/onnx.html#supported-operators. I see you have already opened this issue there. That is the right place for this issue. Closing now. Thanks.
