### ISSUE TITLE
BUGs about "ir_pb_converter.cc : graphProtoToGraph(const GraphProto& gp, bool nested)"

### ISSUE THREAD

**Issue by anlongstory** [onnx/onnx#3180]
# Bug Report
model = onnx.load_model("conv.onnx")
use model.graph , I get graphproto which has one input (named "input", ir_pb_converter.cc : line 237 set "input" into map)，but model.graph.node has three inputs(names "input", "weight", "bias", ir_pb_converter.cc : line 258 )

ir_pb_converter.cc : line 275,  search->second = ["input", "weight", "bias"], value_by_name_of only has ["", "input" ,"output"]，“weight” and "bias" use initializer struct to present,  so that line 285 is true and throw std::out_of_range(msg.str())

Is this a bug?

### model.graph
node {
  input: "input"
  input: "weight"
  input: "bias"
  output: "3"
  name: "Conv_0"
  op_type: "Conv"
  attribute {
    name: "dilations"
    ints: 1
    ints: 1
    type: INTS
  }
  attribute {
    name: "group"
    i: 1
    type: INT
  }
  attribute {
    name: "kernel_shape"
    ints: 3
    ints: 3
    type: INTS
  }
  attribute {
    name: "pads"
    ints: 0
    ints: 0
    ints: 0
    ints: 0
    type: INTS
  }
  attribute {
    name: "strides"
    ints: 2
    ints: 2
    type: INTS
  }
}
name: "torch-jit-export"
initializer {
  dims: 3
  data_type: 1
  name: "bias"
  raw_data: "\243NB>\330\222\004>m\263\336\275"
}
initializer {
  dims: 3
  dims: 3
  dims: 3
  dims: 3
  data_type: 1
  name: "weight"
  raw_data: "xxxx"
}
input {
  name: "input"
  type {
    tensor_type {
      elem_type: 1
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 3
        }
      }
    }
  }
}
output {
  name: "3"
  type {
    tensor_type {
      elem_type: 1
      shape {
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 1
        }
      }
    }
  }
}

**Comment by jcwchen** [comment]
Hi @anlongstory,
It looks like a known IR issue. Currently IR cannot use the input from the initializer if ir_version >= 4.
https://github.com/onnx/onnx/pull/3007 This PR is a workaround. You can build from source with this PR and see whether it helps this problem.

Could you provide this model? Did you encounter this error while loading it? Thanks.

**Comment by anlongstory** [comment]
got it，thx
