### ISSUE TITLE
accur warning when transform LSTM to ONNX

### ISSUE THREAD

**Issue by yumulinfeng1** [onnx/onnx#3182]
when transform lstm to onnx, there is warning:
**UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")**

onnx version: 1.8.0
 
and onnx model is below:
![image](https://user-images.githubusercontent.com/50360389/102972727-7a757280-4536-11eb-8d29-5a3659065c9b.png)

**Comment by jcwchen** [comment]
Hi @cendelian,
It's a converter issue, but I think this warning is fine: https://github.com/pytorch/pytorch/issues/45653
Did you encounter any issue while using this model?

**Comment by minrui-hust** [comment]
The exported model can only accept data with batch size =1, other batch size throw an error
