### ISSUE TITLE
Does ONNX has any function like nn.Module.children() in Pytorch to get the layer list in onnx model?

### ISSUE THREAD

**Issue by JacksonZyy** [onnx/onnx#3183]
# Ask a Question

### Question
For example, I have a simple fully connected network in ONNX, which is firstly defined in Pytorch by `torch.nn.Sequential(nn.Linear+nn.ReLU+nn.Linear+nn.ReLU+nn.Linear)`. Then I transform this Pytorch network into onnx model and I need to process the network further using onnx model.
How can I segment the example network into two sub-networks and execute these two sub-networks using onnx model?
In Pytorch they provide function `list(model.children())[0][:2]` to collect the first two layers (nn.Linear+nn.ReLU) in the network, and you can wrap these two layers as a sub-network and directly execute this sub-network. 
Does onnx provide any functions to support the process I mentioned in the example?

Many thanks!

**Comment by wschin** [comment]
ONNX model doesn't support this feature. The actual request behind is to design an API to select a sub-graph from a graph. It looks straight for `nn.Sequential` model but it's very complicated for `nn.Module`. I think having such a tool to do model partition is good. For example,
```
sub_model = onnx.helper.select(model, inputs=['tensor_x', 'tensor_y'], outputs=['tensor_z'])
```
may look into `model` and pick the sub-model starting from `tensor_x` and `tensor_y` and ending at `tensor_z`. Maybe it's a great case for contribution.

**Comment by JacksonZyy** [comment]
> ONNX model doesn't support this feature. The actual request behind is to design an API to select a sub-graph from a graph. It looks straight for `nn.Sequential` model but it's very complicated for `nn.Module`. I think having such a tool to do model partition is good. For example,
> 
> ```
> sub_model = onnx.helper.select(model, inputs=['tensor_x', 'tensor_y'], outputs=['tensor_z'])
> ```
> 
> may look into `model` and pick the sub-model starting from `tensor_x` and `tensor_y` and ending at `tensor_z`. Maybe it's a great case for contribution.

Thanks for your reply!
May I ask if you will add this feature to your onnx work?

**Comment by gramalingam** [comment]
I believe that the python utility described in https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#extracting-sub-model-with-inputs-outputs-tensor-names does what @wschin suggests.
