### ISSUE TITLE
 How do I export the onnx model with custom operators that don't seem to be supported in onnx？

### ISSUE THREAD

**Issue by zlbdzhh** [onnx/onnx#3189]
# Ask a Question

### Question
How do I export the onnx model with custom operators that don't seem to be supported in onnx
When training pointnet2, I used the custom FurthestPointSampling operator, but the following error occurred when exporting to onnx model，
How can I fix this error？
### Further information
Traceback (most recent call last):
  File "D:/05projects/PointNet-Train/point_netpp/export_model_test.py", line 179, in <module>
    torch.onnx.export(model, dummy_input, "nodel.onnx", verbose=True, input_names=input_names, output_names=output_names)
  File "D:\03software\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\03software\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "D:\03software\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py", line 650, in _export
    val_add_node_names, val_use_external_data_format, model_file_location)
RuntimeError: ONNX export failed: Couldn't export Python operator FurthestPointSampling

- Is this issue related to a specific model?  
Model name：pointnet2
Model opset：FurthestPointSampling):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @zlbdzhh,
Here is the document which might be helpful: https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md

**Comment by wenbingl** [comment]
@zlbdzhh , this is an example how to export the model with the custom ops support. https://github.com/microsoft/ort-customops/blob/main/test/test_torch_ops.py

**Comment by gepu0221** [comment]
Hi @zlbdzhh, Have you solved the problem? There are custom operators implemented by CUDA in pointnet2.  It's seemed this document doesn't support CUDA implementation. https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md

**Comment by WeilunDai66** [comment]
Hi @zlbdzhh, Have you solved the problem? I found  FurthestPointSampling in lots of point cloud related work and it is difficult to 
export the onnx model. Could you please share your solution.

**Comment by AllenTiTaiWang** [comment]
From PyTorch, you can use [`register_custom_op_symbolic`](https://pytorch.org/docs/stable/onnx.html#custom-operators) to register your own op, but you need to specify which aten::op in TorchScript you would like to replace. And if this is not supported by ONNX, neither by ONNXRUNTIME, please make sure you have the code to support it. Or checkout [onnxruntime-extionsions](https://github.com/microsoft/onnxruntime-extensions) to create your own backend code.
