### ISSUE TITLE
Stateful recursive models in ONNX

### ISSUE THREAD

**Issue by ASorokin27** [onnx/onnx#3190]
# Feature Request

### System information
ONNX version (you are using): 1.6

### What is the problem that this feature solves?
I'm using a vanilla LSTM model in production, currently using tensorflow/keras. I would like to switch to ONNX-runtime, but it seems like there's no stateful version of the model in onnx currently (as per https://github.com/onnx/keras-onnx/issues/676).

### Describe the alternatives you have considered
Using TF2.x works, but long term i would like to switch to onnx.

### Describe the feature
I think a stateful version is pretty much necessary to do inference with any recurrent NN in online mode.

### Will this influence the current api?
It might be a config option i guess.

### Feature Area
backend.

### Are you willing to contribute it (Y/N):
I'm quite new to ONNX; if no one picks it up, i might give it a try but would rather some else did it.

**Comment by gramalingam** [comment]
I assume you mean state that is carried across successive inference-runs? You can model the state-variables as extra inputs, as well as extra outputs, can you not? For every state-variable S, add an extra input S_in and an extra output S_out. The caller will have to pass it back for the next invocation.

**Comment by gramalingam** [comment]
By the way, the training-extensions in ONNX do model state (see https://github.com/onnx/onnx/blob/master/docs/IR.md#training-related-information ), but training-extensions may not be supported by backends yet.

**Comment by ASorokin27** [comment]
> By the way, the training-extensions in ONNX do model state (see https://github.com/onnx/onnx/blob/master/docs/IR.md#training-related-information ), but training-extensions may not be supported by backends yet.

Thanks!!
Understood. Returning a state is not very convenient in my particular task, but yes, it's a working way to do it.
