### ISSUE TITLE
请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。

### ISSUE THREAD

**Issue by Wulingtian** [onnx/onnx#3191]
![IMG_20201231_094134](https://user-images.githubusercontent.com/20986422/103396607-322a0600-4b6f-11eb-82a5-025f6bcffb72.jpg)
onnx转trt int8的推理速度还是很快的，1070显卡，5ms左右，就是不出框。。。
有人能一起交流一下吗？

**Comment by jcwchen** [comment]
Hi @Wulingtian,
ONNX does support yolov5 so it seems to me that it's more like an onnx-tensorrt or tensorrt issue. I saw you have also posted this issue there, which is more proper for this issue.
Could you provide the yolov5 ONNX model? I can take a look at it. Thanks.

ONNX支持yolov5所以我覺得這個更像是onnx-tensorrt或者tensorrt的問題, 我看到您也有在他們的repo(比較適合的地方)中提了這個問題
可以麻煩您提供轉換前的ONNX的模型嗎?我可以幫忙看一下那個model有沒有問題, 謝謝

**Comment by Wulingtian** [comment]
已发送！

> Hi @Wulingtian,
> ONNX does support yolov5 so it seems to me that it's more like an onnx-tensorrt or tensorrt issue. I saw you have also posted this issue there, which is more proper for this issue.
> Could you provide the yolov5 ONNX model? I can take a look at it. Thanks.
> 
> ONNX支持yolov5所以我覺得這個更像是onnx-tensorrt或者tensorrt的問題, 我看到您也有在他們的repo(比較適合的地方)中提了這個問題
> 可以麻煩您提供轉換前的ONNX的模型嗎?我可以幫忙看一下那個ONNX模型有沒有問題, 謝謝

已发送！

**Comment by Wulingtian** [comment]
您好，模型做的是安全帽检测，单分类



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "onnx/onnx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月2日(星期六) 凌晨2:58
收件人:&nbsp;"onnx/onnx"<onnx@noreply.github.com&gt;;
抄送:&nbsp;"willer"<2813389262@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [onnx/onnx] 请问有人遇到 yolov5s 的onnx模型转trt int8不出框的情况吗？不管是yolov5 3.1的版本还是2.0的，都不出框。。。 (#3191)





 
Hi @Wulingtian,
 ONNX does support yolov5 so it seems to me that it's more like an onnx-tensorrt or tensorrt issue. I saw you have also posted this issue there, which is more proper for this issue.
 Could you provide the yolov5 ONNX model? I can take a look at it. Thanks.
 
ONNX支持yolov5所以我覺得這個更像是onnx-tensorrt或者tensorrt的問題, 我看到您也有在他們的repo(比較適合的地方)中提了這個問題
 可以麻煩您提供轉換前的ONNX的模型嗎?我可以幫忙看一下那個model有沒有問題, 謝謝
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

yolov5s-simple.onnx (27.70M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2a64633789e173c9ac8dd3904539051850545755065a54074f5353545314035406054e55510d511a55020704005803535400060e632a374e0d080c41564a1a440b09135b061758590c1c630a&t=exs_ftn_download&code=bdc7c977

**Comment by jcwchen** [comment]
Thank you for providing this model. This model looks good to me and it can be correctly onnx.shape_inference and onnxruntime.inferencesession so ONNX should be good in this case. I suggest you contact onnx-tensorrt or tensorrt team to get the best help.

感謝您提供模型. 這個模型看起來很正常而且他能被正確地onnx和onnxruntime推論shape所以ONNX這邊應該沒有問題.建議您聯絡onnx-tensorrt或者tensorrt取得更好的幫助

**Comment by jcwchen** [comment]
I believe this problem has been resolved. Please reopen it if you still have ONNX issue. Thanks.

**Comment by ttanzhiqiang** [comment]
https://github.com/ttanzhiqiang/onnx_tensorrt_project
