### ISSUE TITLE
Non-zero status code returned while running ScatterND node

### ISSUE THREAD

**Issue by sash-a** [onnx/onnx#3192]
### Question
I am trying to run a pretrained huggingface model that I have converted to onnx, however I am getting a strange error and I cannot find anything on the internet about it:

```
2021-01-02 12:55:53.508040619 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running ScatterND node. Name:'ScatterND_1484' Status Message: invalid indice found, indice = -1
Traceback (most recent call last):
  File "/home/sasha/Documents/AutoNPC/onnx_testing/onnx_to_py.py", line 17, in <module>
    ort_outs = ort_session.run(None, inputs)
  File "/home/sasha/miniconda3/envs/nlp/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ScatterND node. Name:'ScatterND_1484' Status Message: invalid indice found, indice = -1
```

Here is the very short script that is causing it:

```
import onnx
import onnxruntime

from transformers import AutoTokenizer

question = 'How old is Bob?'
context = 'Bob is a man, he is 55.'

tokenizer = AutoTokenizer.from_pretrained("mrm8488/longformer-base-4096-finetuned-squadv2")

model = onnx.load("longformer.onnx")
onnx.checker.check_model(model)

ort_session = onnxruntime.InferenceSession("longformer.onnx")

encoding = tokenizer(question, context, return_tensors="pt")
inputs = {k: v.cpu().detach().numpy() for k, v in encoding.items()}

ort_outs = ort_session.run(None, inputs)
print(ort_outs)
```

**Comment by jcwchen** [comment]
Hi @sash-a,
This error happens in onnxruntime because the model is invalid due to certain invalid node. Therefore this should be an issue either in converter or onnxruntime... Does the model work normally before converting to ONNX? If yes, you can check whether that node is consistent before and after converter. If it is consistent, then there might be some bugs in onnxruntime. If not, the issue might happen during the conversion. Thanks.

**Comment by imtiazBDSgit** [comment]
Hi @sash-a  , Did you figure out a solution , I had the same question so asking . Thanks in Advance.

**Comment by l-i-p-f** [comment]
I come accross the same problem. Have you solved that yet? @sash-a 

`If yes, you can check whether that node is consistent before/after converter. ` How to check if the node is consistent? @jcwchen

**Comment by jcwchen** [comment]
Hi @l-i-p-f,
You can check the node info from the original graph (it could be TensorFlow or PyTorch) and see whether it is consistent to the converted ONNX graph. If the graph is much different, you can ask the converter team for help to look into it. Thanks!

**Comment by zhongerqiandan** [comment]
Have you solved that yet? @sash-a

**Comment by serg06** [comment]
I found one situation that causes this error. When you access a PyTorch tensor like this:
```
tensor = tensor[..., -1]
```
and then try to export the model, you will get the above problem.

The resolution? Meticulously going through the model code to remove all instances of `tensor[..., -1]`.

**Comment by serg06** [comment]
I found a solution: Before exporting the PyTorch model to Onnx, go through the model code and replace all instances of `tensor[..., -1]` with `tensor[..., tensor.shape(-1) - 1]` before exporting the model

**Comment by ZJJHYM** [comment]
> 

what is the tensor?

**Comment by serg06** [comment]
@ZJJHYM Every tensor that uses both `...` and `-1` in square brackets.
