### ISSUE TITLE
unique_consecutive not support

### ISSUE THREAD

**Issue by zackkui** [onnx/onnx#3193]
# Bug Report

RuntimeError: Exporting the operator unique_consecutive to ONNX opset version 10 is not supported. Please open a bug to request ONNX export support for the missing operat

**Comment by jcwchen** [comment]
Hi @zackkui,
Here is the supported operators for pytorch to ONNX: https://pytorch.org/docs/stable/onnx.html#supported-operators
Currently `torch.onnx.export` does not support this operator for ONNX conversion... Please open an issue in **pytorch** repo to request this support. Thanks.

**Comment by zackkui** [comment]
I see.Thanks

**Comment by jcwchen** [comment]
I assume this issue has been resolved. Please reopen it if you still have any ONNX related issues. Thank you.
