### ISSUE TITLE
No module named 'onnx.onnx_cpp2py_export' when freeze onnx 1.4.1 with pyinstaller

### ISSUE THREAD

**Issue by clark-2000** [onnx/onnx#3196]
I write simple code include onnx 1.4.1 on aarch64(ubuntu 18.04 LTS) then freeze with pyinstaller, but return the ModuleNotFoundError
I think that's onnx couldn't found the lib : onnx_cpp2py_export.cpython-36m-aarch64-linux-gnu.so, but still error when i put the so lib and test scrip in the same folder.
Anyone could give me a favor, or some hint to solving.

**freeze with pyinstaller**
pyinstaller --onefile --add-data "/usr/lib/python3.6/dist-packages/onnx:onnx" --add-data "/usr/lib/python3.6/dist-packages/onnx-1.4.1.dist-info:onnx-1.4.1.dist-info" test.py

**test.py**

import onnx
onnx_version = onnx._ _version_ _ # double under line can't show here
print(onnx_version)

**Error output** 

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import onnx
  File "/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "onnx/__init__.py", line 14, in <module>
    import onnx.helper  # noqa
  File "/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'
[26343] Failed to execute script test

**Pip list**

onnx 1.4.1
pyinstaller 4.1
pyinstaller-hooks-contrib 2020.10
protobuf 3.13.0
setuptools 50.3.0
numpy 1.18.5

**Comment by jcwchen** [comment]
Hi @clark-2000,
Same as https://github.com/onnx/onnx/issues/2252?
Maybe this can help too: https://stackoverflow.com/questions/25733467/no-module-named-when-using-pyinstaller.

**Comment by clark-2000** [comment]
Hi @jcwchen 
Thank you for your helps!
It's same error [#2252](https://github.com/onnx/onnx/issues/2252)with me.
But I still not worked.

Finally, I solved this error myself. I used --binaries command, it'll store reference library 'onnx_cpp2py_export.cpython-36m-aarch64-linux-gnu.so' on specific folder (onnx) inside the bundle. Maybe onnx 1.4.1 have specific this path?

**My pyinstaller spec file contained below**
...(ignore)
a = Analysis(['test.py'],
             pathex=[
                          '/usr/local/lib/python3.6/dist-packages/onnx/',
                          '/usr/local/lib/python3.6/dist-packages/onnx/onnx-1.4.1.dist-info/'
                           ],
             binaries=[
('/usr/local/lib/python3.6/dist-packages/onnx/onnx_cpp2py_export.cpython-36m-aarch64-linux-gnu.so','onnx')
],
...(ignore)

**Comment by cezbloch** [comment]
`pyinstaller --hidden-import onnx.onnx_cpp2py_export <script_name.py>`
has worked for me.

**Comment by Piscabo** [comment]
> `pyinstaller --hidden-import onnx.onnx_cpp2py_export <script_name.py>` has worked for me.

new to this and the error is making me crazy, want to try this, but what should the <script_name.py> be?
_No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package_

**Comment by ffdown** [comment]
same trouble `[comfy_mtb] | WARNING -> Web extensions folder at E:\AI\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | STATUS -> Some nodes failed to load:
        Failed to import module faceswap because ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package`
