### ISSUE TITLE
How to decode params

### ISSUE THREAD

**Issue by chenyuqi990215** [onnx/onnx#3201]
When I use `model.graph.initializer` to get the params in the model, I get the following raw_data like data:

```
b'VKL\xbd\x00(\x08:\x85\xf7\x8e\xbd\x942\xd9<J\xb2\x11=\x98-:\xbc\x86Q\x9d=\xdb\xff:\xbdl~"=\x18O\x93=\\\xf8\xbc<\xd0\x8d\x95;
```

Could you explain how I can decode the raw_data to get the origin tensor like `torch.tensor`.

PS: I find that in `pytorch`, when exporting the model, `raw=True` is set in `TensorProto`, and the params are encoded in binary string, I wonder how to get the origin float tensor from your binary string.

**Comment by jcwchen** [comment]
Hi @chenyuqi990215,
You can try something like this:
```
import onnx
from onnx import numpy_helper
model = onnx.load('path/to/your/model')
numpy_helper.to_array(model.graph.initializer[0])
```

**Comment by chenyuqi990215** [comment]
Thanks, it really works!
