### ISSUE TITLE
FP16 TensorProto?

### ISSUE THREAD

**Issue by Zha0q1** [onnx/onnx#3204]
Hi I was trying to convert a fp16 mxnet model to onnx.

I noticed that fp16 has `STORAGE_TENSOR_TYPE` as `UINT16`
https://github.com/onnx/onnx/blob/master/onnx/mapping.py#L41
and in turn `UINT16` corresponds to filed i`nt32_data`
https://github.com/onnx/onnx/blob/master/onnx/mapping.py#L55

This is from onnx.helper
```python
def make_tensor(
        name,  # type: Text
        data_type,  # type: int
        dims,  # type: Sequence[int]
        vals,  # type: Any
        raw=False  # type: bool
):  # type: (...) -> TensorProto
    '''
    Make a TensorProto with specified arguments.  If raw is False, this
    function will choose the corresponding proto field to store the
    values based on data_type. If raw is True, use "raw_data" proto
    field to store the values, and values should be of type bytes in
    this case.
    '''
    tensor = TensorProto()
    tensor.data_type = data_type
    tensor.name = name

    if data_type == TensorProto.STRING:
        assert not raw, "Can not use raw_data to store string type"

    if (data_type == TensorProto.COMPLEX64
            or data_type == TensorProto.COMPLEX128):
        vals = split_complex_to_pairs(vals)
    if raw:
        tensor.raw_data = vals
    else:
        field = mapping.STORAGE_TENSOR_TYPE_TO_FIELD[
            mapping.TENSOR_TYPE_TO_STORAGE_TENSOR_TYPE[data_type]]
        getattr(tensor, field).extend(vals)

  tensor.dims.extend(dims)
    return tensor
```
I am trying to do 
```python
onnx.helper.make_tensor(
                name=name,
                data_type=data_type,
                dims=dims,
                vals=np_arr.flatten().tolist(),
                raw=False
            )

```
My question is how should I pass in `vals`? This code works fine for fp32 because TensorProto has field `float_data`, but it seems like for fp16 I need to do some conversion for my list `vals`?

**Comment by jcwchen** [comment]
Hi @Zha0q1,
It depends on your usage and basically it should be fine. `float16` was designed to stored in `int32_data`. If you want to convert it from TensorProto to numpy.array, `numpy_helper.to_array` will handle that as well: https://github.com/onnx/onnx/pull/3002.

**Comment by Zha0q1** [comment]
Hi @jcwchen thanks for the reply. Without conversion/casting I get this error:

```
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: -0.0273590087890625 has type float, but expected one of: int, long
```

which makes sense because of the float, int32 mismatch. However if I just do a `int()` cast apparently I will lose precision, so that got me thinking if I need to some sort of "reinterpret_cast" as in C++

**Comment by Zha0q1** [comment]
My use case is to convert my fp16 model to onnx and the run inference using onnxruntime/tensorrt. So I need to make sure that when the inference framework loads up the onnx graph it can parse the fp16 parameters correctly

**Comment by jcwchen** [comment]
Thank you for providing your use case. Could you try `np_arr.view(dtype=np.uint16).flatten().tolist()` as your `vals` for `onnx.helper.make_tensor`?

**Comment by Zha0q1** [comment]
It worked! thanks @jcwchen
