### ISSUE TITLE
The individual operator nodes created as a model, using helper.make_node and helper.make_graph has opset version 14 and cannot be executed on ORT. How to change the opset version?

### ISSUE THREAD

**Issue by MLDLwizard** [onnx/onnx#3205]
I am working on a custom activation function and have implemented it to Onnx as a function i.e an operator schema with a combination of primitive Onnx operators.
I even wrote and implemented a backend test file for the same and it was successful.
I wanted to note down the operator execution time and hence, made use of the **helper.make_node and helper.make_graph to create a model with only that operator as a node**. The idea was to execute the operator on ORT and note the inference times.
However,
when the model is visualized in Netron the model parameters are as follows:
**formats - ONNX V7
imports- ai.onnx v14
which means the opset version is 14.**
The opset version is 14 for any model created using helper.make_node, helper.make_graph.
This is resulting in an ORT error that opset 14 is experimental and not supported.
The error is as follows:

_"Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from testng.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only guarantees support for models stamped with official released onnx opset versions. Opset 14 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 13."_

**Please help me know how to change the opset version for a model having only an individual operator created using helper.make_node and helper.make_graph.
Also, @jcwchen   do I need to implement this operator again in ORT to be able to execute it? If yes, what is the flow?**

**Comment by jcwchen** [comment]
Hi @MLDLwizard,
It seems that you used the latest ONNX from source to implement the custom schema? Recently opset_version in ONNX was just updated to 14 (https://github.com/onnx/onnx/pull/3195) so by default it will use 14 and ORT hasn't supported it yet.

There might be 3 ways to workaround this:

1. Use the ONNX release (1.8.0) commit to build with your implementation. In that case the produced opset_version would be 13.
2. Remake the model with specified opset_version
```
import onnx
model = onnx.load('path/to/your/model.onnx')
op = onnx.OperatorSetIdProto()
op.version = 13
update_model = onnx.helper.make_model(model.graph, opset_imports=[op])
onnx.save(update_model, 'path/to/output.onnx')
```
3. (Hacky way) Simply use `onnx_model.opset_import[0].version = 13`

Thank you.

**Comment by MLDLwizard** [comment]
Yes, I did use the latest Onnx built from source to implement my custom op schema. 
Thanks @jcwchen for these workarounds.
I'll definitely try them and let you know. 

Meanwhile, can you please let me know, if I need to implement the new op function written in Onnx in ORT as well, or register it somewhere in the ORT source ? 
Or will it be executed on ORT by default since the op can be split into primitives, which are already implemented in ORT. 
Please let me know what has to be done, if it has to be implemented in ORT again.

**Comment by jcwchen** [comment]
Yes for those operators which are not officially supported by ONNX, you will need to do more things in ORT. There are ways to accomplish this. Please check the document for adding custom op in ORT:
https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md

**Comment by MLDLwizard** [comment]
Hey @jcwchen , thanks for the workaround. I'm successfully able to change the opset of my model, but while trying to execute it on ORT, I get this error.
"InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from testng.onnx failed:This is an invalid model. Error in Node: : No Op registered for Testing_Activation_fn with domain_version of 12"

Does this mean that, I have to write a kernel implementation for the Testing_activation_fn in ORT as you have pointed to in your previous message, or is this a different error?
DO I certainly need to implement the op in ORT or is there any work around for this as well?
Thanks in advance for our patience and guidance :)

**Comment by jcwchen** [comment]
It looks like `Testing_Activation_fn` is your custom operator? If yes, you need to implement this op in ORT otherwise ORT doesn't how to execute it. Thank you.

**Comment by MLDLwizard** [comment]
Yes @jcwchen , Testing_Activation_fn was indeed my custom operator. As you have suggested, I'll try to implement it in ORT.
However,
Could you please confirm, if my understanding of ONNX is correct?
"**ONNX basically is a representation format to to represent the graph of an ML/DL model. 
Frameworks like TF, Pytorch etc have operators which are defined ( inputs, outputs, attributes etc. that they accept) and are implemented (their mathematical code/ kernel level code is written in that frameworks src itself, so that the operator can be scheduled on the hardware CPU/GPU and executed)
but,
The operators in ONNX are just a definition of that corresponding operator i.e their inputs, outputs, attributes, constraints are defined in the OperatorSchema, but it's mathematical code/kernel level code is not written in the ONNX src. 
This implies that ONNX alone cannot execute any model, but it can only define the model.

The ONNX backend can run/execute ONNX models, but the backend is essentially a converter, which converts the ONNX model to a specific framework and executes the model in that framework. The tests written in onnx/backend/test/case utilize this converter backend to assert/verify if the numpy implementation of the operator gives the same output as the defined operator.

Since, ONNX alone cannot execute the converted models, due to lack of implementation of the operators, ORT is used for inferencing with ONNX models.
Thus, ORT is the place where the mathematical code/kernel level code of the ONNX operators is implemented, and hence execution is possible with ORT.**"

Please correct me if I am wrong. Thankyou :)

**Comment by jcwchen** [comment]
Hi @MLDLwizard,
Your understanding looks good to me. Basically ONNX is a general specification and definition for all ML/DL frameworks. Users supposedly can convert their ML/DL models to ONNX.

However, users cannot actually execute their models through ONNX itself.  (Although ONNX does has limited shape inference) Users will need other backend frameworks to do that, for example, ONNXRuntime, onnx-tensorflow, onnx-tensorrt, etc. For those tests under `onnx/backend/test`, users will also need backend frameworks to verify the result. For instance, `onnxruntime/test/python/onnx_backend_test_series.p` in ORT.

Besides, if you users try to use some operators which are not officially supported by ONNX yet, they will need to implement themselves in the backend frameworks.

**Comment by MLDLwizard** [comment]
Thankyou @jcwchen. You really made things easy for me. 
Having understood what ONNX is at it's base, I am willing to make meaningful contributions, if any.
Can you please let me know, if there is a space for contribution in terms of custom operators, optimizations, operator fusion etc. in ONNX.
Thanks again for all the help. :)

**Comment by jcwchen** [comment]
@MLDLwizard Not a problem! Welcome to contribute ONNX. If you encounter anything which are not clear in current documents/codes for your work, feel free to improve/extend it.

If you don't have other issues about ONNX, please close this issue. Thank you :)

**Comment by jcwchen** [comment]
Here is an example code for operator fusion in ORT:
https://github.com/microsoft/onnxruntime/blob/9ec1ed42a809170b87474f5822c4557101812399/onnxruntime/core/optimizer/conv_activation_fusion.cc#L75

**Comment by MLDLwizard** [comment]
Thankyou @jcwchen for pointing it out for me. I'll sure look into what can be done further. 
Thanks again for your patience and guidance :)

**Comment by jcwchen** [comment]
It seems that you have passed the tests you wrote before `pip install build/onnxruntime/OS/Debug/Debug/dist/*.whl`? Did this error happen after you pip install the produced wheel and inference your model? Thanks.

**Comment by MLDLwizard** [comment]
Yeah @jcwchen ,
I actually did inferencing after doing 
pip install /content/onnxruntime/build/Linux/RelWithDebInfo/dist/onnxruntime-1.6.0-cpu36-cp36m-linux_x86_64.whl

I was unable to find the path for *.whl and assumed the above generated whl was the one to be installed. 
So, should I try to install build/onnxruntime/OS/Debug/Debug/dist/*.whl and by doing so the errors wouldn't appear ?

**Comment by MLDLwizard** [comment]
Hey @jcwchen ,
I tried the build from source again , and I was unable to find 

> build/onnxruntime/OS/Debug/Debug/dist/*.whl

The build directory had no subdirectory onnxruntime and I couldn't find directory named OS either, neither debug.

The only .whl file I can find is 

> build/Linux/RelWithDebInfo/dist/onnxruntime-1.6.0-cpu36-cp36m-linux_x86_64.whl

And I did inferencing, after installing this onnxruntime-1.6.0-cpu36-cp36m-linux_x86_64.whl file, and get that error.

The command I used to generate build is 

> !./build.sh --config RelWithDebInfo --build_shared_lib --parallel --build_wheel

Am I doing something wrong here?

**Comment by jcwchen** [comment]
Thank you for providing the details. Yes I believe you are installing the right wheel.

To the best of my knowledge, you can only add existing ONNX operators in cpu_execution_provider.cc since it is using kOnnxDomain domain. That's why only https://github.com/microsoft/onnxruntime/commit/d84799eabef33263c29297e3150b70c0cb830826 can work since it is a existing ONNX operator.

For those undefined operators, you need to follow https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md and add your custom operator as a contri_op under onnxruntime/contrib_ops/. For instance, https://github.com/microsoft/onnxruntime/pull/4195 this one might be a better example. Sorry that I might point you to the wrong direction.

**Comment by MLDLwizard** [comment]
Ok @jcwchen , I ll look into the contrib_ops.
However, I have a doubt. 
Since, I have added DQL to ONNX as well with the same code and opset version as DynamicQunatizeLinear , doesn't it mean that DQL is an existing ONNX operator ? 

Or is it like, only the operator commits merged and released officially in the ONNX repo can be supported by ORT ? But how would they even check that ?

**Comment by jcwchen** [comment]
ORT has its own ONNX submodule under onnxruntime/cmake/external/ so every time if a contributor wants to implement a new ONNX operator in ORT, he/she needs to update the ONNX submodule to let ORT know the corresponding official operator implemented by ONNX.

Theoretically if you update the ONNX submodule under ORT by adding your custom ONNX op, ORT will probably work with you previous PR. But I am not sure whether ORT has any check for official ONNX operators... so basically I will still recommend you to add it as a contri_op first. Thank you.

**Comment by MLDLwizard** [comment]
Hi @jcwchen ,
I was looking into the contrib_ops microsoft/onnxruntime#4195 , but I find it a little complex because of the lines of the code that deal with operator fusion. 
Can you please point me to the PR of any other simple operator which was added to ORT through contrib_ops. 
Thankyou!

**Comment by MLDLwizard** [comment]
Also @jcwchen , updating the Onnx submodule in the ORT solves the error.
However, as you mentioned following the third approach in https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md 
would be appropriate.

It would be really helpful, if you pointed out a PR of a simple operator implemented in ORT through the third approach.
Also, I would love to see a PR pointing out the operator Implementation through second approach as well, to better understand the differences.
Thankyou so much.

**Comment by jcwchen** [comment]
Hi @MLDLwizard,
For second approach, I cannot find a related PR which is doing that in ORT... I think the close example in the document: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/framework/local_kernel_registry_test.cc, although it is just a d test.

For third approach, I have browsed all operators under onnxruntime/contrib_ops/cpu and basically they are not quite easy. I hope this PR is more easier: https://github.com/microsoft/onnxruntime/pull/1277 Hope it helps.Thanks.

**Comment by MLDLwizard** [comment]
Thankyou @jcwchen .
microsoft/onnxruntime#1277 looks much more straightforward. 
Since you said , there aren't any operators in ORT implemented through the second approach, should I assume that most of the operators have been added through 1st and 3rd approach only ? 

But in the https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md 
In the 1st approach it is mentioned that the execution providers can only be CPU and cuda, 
While the third approach has operator Implementations in CPU , cuda and rocm only. 

Hence, I was under the assumption that the operators supported in various EP such as Vitis ai etc in ORT were implemented through the second approach.
Please correct me if I am wrong.

Also, can you please confirm if Dynamic QuantizeLinear microsoft/onnxruntime@d84799e was added using the first approach ?

**Comment by jcwchen** [comment]
> Thankyou @jcwchen .
> [microsoft/onnxruntime#1277](https://github.com/microsoft/onnxruntime/pull/1277) looks much more straightforward.
> Since you said , there aren't any operators in ORT implemented through the second approach, should I assume that most of the operators have been added through 1st and 3rd approach only ?

I believe so.

> But in the https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md
> In the 1st approach it is mentioned that the execution providers can only be CPU and cuda,
> While the third approach has operator Implementations in CPU , cuda and rocm only.
>
> Hence, I was under the assumption that the operators supported in various EP such as Vitis ai etc in ORT were implemented through the second approach.
> Please correct me if I am wrong.

Honestly I don't have the history context here... I would suggest you open an issue about these questions under ONNXRuntime to get the best answer. Sorry that I couldn't be more helpful.
 
> Also, can you please confirm if Dynamic QuantizeLinear [microsoft/onnxruntime@d84799e](https://github.com/microsoft/onnxruntime/commit/d84799e) was added using the first approach ?

I don't think so. DynamicQuantizeLinear should be an official ONNX operator at that moment and that PR is try to implement the supported operator.

**Comment by MLDLwizard** [comment]
Sure thing. Will open a discussion in ORT.
Thankyou @jcwchen

**Comment by MLDLwizard** [comment]
Hello @jcwchen !! 
Thankyou for your support. 
I was able to successfully execute my custom operator on ORT as well. 

 In another case, MobileNet is one of the models that I want to convert to onnx and I have come across this PR  #2728 . Can you please confirm if this HardSwish activation fn has been defined in Onnx.
If not, can I implement the same and push it to onnx and ort?

**Comment by jcwchen** [comment]
Hi @MLDLwizard,
As far as I know, ONNX does not have HardSwish activation fn yet and there is no pending PR for this.

I would say you are welcome to contribute this. Thank you so much!

**Comment by MLDLwizard** [comment]
Hi @jcwchen ,
I further looked into the space of contributing activation functions and have a few queries.

> Is there an existing PR for defining mish op as discussed here, #2818 . If not can I push it as a function , since it can be composed of primitives.

> Is it fine to push HardSwish as a primitive and not write it's function body in the schema? 

> Is Swish/ siLU an existing activation in Onnx ? I couldn't find it's trace in Onnx and this discussion https://github.com/rwightman/gen-efficientnet-pytorch/issues/55
also says the same. 

Thankyou for your guidance 😄

**Comment by jcwchen** [comment]
Hi MLDLwizard Sorry that I updated your comment accidentally.

> Is there an existing PR for defining mish op as discussed here, #2818 . If not can I push it as a function , since it can be composed of primitives.

I don't think there is an existing one for Mish op.

> Is it fine to push HardSwish as a primitive and not write it's function body in the schema? 

I did see someone has a concern that it should be used as a function op, but I don't have the context.

> Is Swish/ siLU an existing activation in Onnx ? I couldn't find it's trace in Onnx and this discussion https://github.com/rwightman/gen-efficientnet-pytorch/issues/55
also says the same. 

Probably no. I don't see any new operators coming after ONNX 1.8 for now.

If you finally decide to contribute it, feel free reply these issues to remind people you are working on this and you may get help from them: https://github.com/onnx/onnx/issues/2728, https://github.com/onnx/onnx/issues/3225. Thank you.
