### ISSUE TITLE
Is there a way to put my author name in the model name?

### ISSUE THREAD

**Issue by JonathanSum** [onnx/onnx#3206]
# Ask a Question

### Question
Is there a way to put my author name in the model name to avoid people simply copying my work or crediting other people?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by prasanthpul** [comment]
You can leverage the metadata fields to add the info. As shown in https://github.com/onnx/onnx/blob/master/docs/IR.md, there are fields in the protobuf you can use: doc_string or metadata_props

**Comment by JonathanSum** [comment]
I will try it when I have time. I will close this now. But I may reopen it if I found out it doesn't work. Thank you for answering @prasanthpul

**Comment by askhade** [comment]
https://github.com/onnx/onnx/blob/master/docs/IR.md#optional-metadata
