### ISSUE TITLE
cannot import name 'ONNX_ML' 

### ISSUE THREAD

**Issue by illiad-tigerdhl** [onnx/onnx#3210]
windows env，I get the issue：
ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx_cpp2py_export' (unknown location)
I also  use the command:
set ONNX_ML=1

and I uninstall the setup.py, reinstall it 
but it is still occur the problem, how can I fix?

**Comment by jcwchen** [comment]
Hi @illiad-tigerdhl,

> Please note that the import onnx command does not work from the source checkout directory; in this case you'll see ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export'. Change into another directory to fix this error.

Have you tried to import onnx in other directories instead of onnx/?

**Comment by illiad-tigerdhl** [comment]
@jcwchen yes，I try import in the last dir，and it works， but  I test the onnx，run “pytest”， it  turn out new  problem：
ERROR  - ModuleNotFoundError: No module named 'pybind11_tests'
I can find the dir “pybind11” in the third-party

**Comment by jcwchen** [comment]
Could you try to `git submodule update --init --recursive`, `python setup.py install` and then `pytest` again? Thanks

**Comment by illiad-tigerdhl** [comment]
@jcwchenThanks, I fellow the  tutorials on the https://github.com/onnx/onnx. do you mean now I should run 
git submodule update --init --recursive, python setup.py install again?

**Comment by illiad-tigerdhl** [comment]
@jcwchen I do that last moment, but get the same issue agian

**Comment by jcwchen** [comment]
Yes, it seem to me that some files under submodule pybind11/ might be missing or not installed correctly... Similar issue: https://github.com/onnx/onnx/issues/2372

**Comment by jcwchen** [comment]
Thanks for the details. Could you help me to check that whether there are `pybind11_tests.cpp` or `pybind11_tests.h` under your `onnx/third_party/pybind11`? A quick workaround would be `pip install pybind11`, but I am curious whether the build bug is and hope to solve it. Thank you.

**Comment by illiad-tigerdhl** [comment]
@jcwchen  sorry, I just clean the onnx  git file, I want to reinstall.

**Comment by illiad-tigerdhl** [comment]
@jcwchen I reinstall onnx and the last  step run occur error：

(torch) PS D:\softinstall\onnx\onnx> python setup.py install
running install
running bdist_egg
running egg_info
creating onnx.egg-info
writing onnx.egg-info\PKG-INFO
writing dependency_links to onnx.egg-info\dependency_links.txt
writing entry points to onnx.egg-info\entry_points.txt
writing requirements to onnx.egg-info\requires.txt
writing top-level names to onnx.egg-info\top_level.txt
writing manifest file 'onnx.egg-info\SOURCES.txt'
reading manifest file 'onnx.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'onnx.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running create_version
running cmake_build
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.28.29335.0
-- The CXX compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/softinstall/vs2019/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/softinstall/vs2019/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: D:/softinstall/miniconda/envs/torch/Library/lib/libprotobuf.lib (found version "3.11.3")
Generated: D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
Generated: D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
Generated: D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
CMake Warning at CMakeLists.txt:412 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11"
  (requested version 2.2) with any of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Found PythonInterp: D:/softinstall/miniconda/envs/torch/python.exe (found suitable version "3.7.9", minimum required is "3.7")
-- Found PythonLibs: D:/softinstall/miniconda/envs/torch/libs/python37.lib (found suitable version "3.7.9", minimum required is "3.7")
--
-- ******** Summary ********
--   CMake version         : 3.18.2
--   CMake command         : D:/softinstall/miniconda/envs/torch/Library/bin/cmake.exe
--   System                : Windows
--   C++ compiler          : D:/softinstall/vs2019/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe
--   C++ compiler version  : 19.28.29335.0
--   CXX flags             : /DWIN32 /D_WINDOWS /W3 /GR /EHsc
--   Build type            : Release
--   Compile definitions   :
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : C:/Program Files (x86)/onnx
--   CMAKE_MODULE_PATH     :
--
--   ONNX version          : 1.8.0
--   ONNX NAMESPACE        : onnx
--   ONNX_BUILD_TESTS      : OFF
--   ONNX_BUILD_BENCHMARKS : OFF
--   ONNX_USE_LITE_PROTO   : OFF
--   ONNXIFI_DUMMY_BACKEND : OFF
--   ONNXIFI_ENABLE_EXT    : OFF
--
--   Protobuf compiler     : D:/softinstall/miniconda/envs/torch/Library/bin/protoc.exe
--   Protobuf includes     : D:/softinstall/miniconda/envs/torch/Library/include
--   Protobuf libraries    : D:/softinstall/miniconda/envs/torch/Library/lib/libprotobuf.lib
--   BUILD_ONNX_PYTHON     : ON
--     Python version      : 3.7
--     Python executable   : D:/softinstall/miniconda/envs/torch/python.exe
--     Python includes     : D:/softinstall/miniconda/envs/torch/include
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_COMPILE_COMMANDS


-- Build files have been written to: D:/softinstall/onnx/onnx/.setuptools-cmake-build
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.2+25e4d540b
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Running gen_proto.py on onnx/onnx.in.proto
  Processing D:\softinstall\onnx\onnx\onnx\onnx.in.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-ml.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-ml.proto3
  generating D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx_pb.py
  Running C++ protocol buffer compiler on D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  Building Custom Rule D:/softinstall/onnx/onnx/CMakeLists.txt
  Writing mypy to onnx/onnx_ml_pb2.pyi
  Building Custom Rule D:/softinstall/onnx/onnx/CMakeLists.txt
  Running gen_proto.py on onnx/onnx-operators.in.proto
  Processing D:\softinstall\onnx\onnx\onnx\onnx-operators.in.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-operators-ml.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-operators-ml.proto3
  generating D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx_operators_pb.py
  Running gen_proto.py on onnx/onnx-data.in.proto
  onnxifi_loader.c
  Processing D:\softinstall\onnx\onnx\onnx\onnx-data.in.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-data.proto
  Writing D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx-data.proto3
  generating D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx\onnx_data_pb.py
  Running C++ protocol buffer compiler on D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
  Writing mypy to onnx/onnx_operators_ml_pb2.pyi
  Running C++ protocol buffer compiler on D:/softinstall/onnx/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
  onnxifi_loader.vcxproj -> D:\softinstall\onnx\onnx\.setuptools-cmake-build\Release\onnxifi_loader.lib
  Writing mypy to onnx/onnx_data_pb2.pyi
  Building Custom Rule D:/softinstall/onnx/onnx/CMakeLists.txt
  Building Custom Rule D:/softinstall/onnx/onnx/CMakeLists.txt
  onnx-ml.pb.cc
  onnx-operators-ml.pb.cc
  onnx-data.pb.cc
  onnxifi_wrapper.c
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): error C2220: 以下警告被视为错误 (编译
源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx\onnx-ml.pb.cc) [D:\softinstall\onnx\onnx\.setuptools-cmake-bu
ild\onnx_proto.vcxproj]
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): error C2220: 以下警告被视为错误 (编译
源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx\onnx-operators-ml.pb.cc) [D:\softinstall\onnx\onnx\.setuptool
s-cmake-build\onnx_proto.vcxproj]
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): error C2220: 以下警告被视为错误 (编译
源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx\onnx-data.pb.cc) [D:\softinstall\onnx\onnx\.setuptools-cmake-
build\onnx_proto.vcxproj]
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): warning C4251: “google::pr
otobuf::internal::LogMessage::message_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有
dll 接口由 class“google::protobuf::internal::LogMessage”的客户端使用  (编译源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\on
nx\onnx-ml.pb.cc) [D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
D:\softinstall\vs2019\VC\Tools\MSVC\14.28.29333\include\xstring(4648): message : 参见“std::basic_string<char,std::char_tr
aits<char>,std::allocator<char>>”的声明 (编译源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx\onnx-ml.pb.cc) [D:\so
ftinstall\onnx\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): warning C4251: “google::pr
otobuf::internal::LogMessage::message_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有
dll 接口由 class“google::protobuf::internal::LogMessage”的客户端使用  (编译源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\on
nx\onnx-operators-ml.pb.cc) [D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
D:\softinstall\vs2019\VC\Tools\MSVC\14.28.29333\include\xstring(4648): message : 参见“std::basic_string<char,std::char_tr
aits<char>,std::allocator<char>>”的声明 (编译源文件 D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx\onnx-operators-ml.pb.
cc) [D:\softinstall\onnx\onnx\.setuptools-cmake-build\onnx_proto.vcxproj]
D:\softinstall\miniconda\envs\torch\Library\include\google/protobuf/stubs/logging.h(102,23): warning C4251: “google::pr

**Comment by jcwchen** [comment]
It looks like another issue about protobuf conflict. Did you use shared protobuf from conda environment on Windows? If so, please `git clean -xdf` and add these env flags:
```
set USE_MSVC_STATIC_RUNTIME=0
set CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON"
```
Then try `python setupy.py install` again. Thanks.

**Comment by YueWenjun** [comment]
It also happen on my Ubuntu 18.04
I found a wired solution: 

run `pip3 install onnx` after `python3.6 setup.py install`

it seems nothing will be installed
```
root@7bf42ec17302:/opt/onnx/onnx/shape_inference# pip3 install onnx
Requirement already satisfied: onnx in /usr/local/lib/python3.6/dist-packages/onnx-1.8.0-py3.6-linux-x86_64.egg
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from onnx)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages/protobuf-4.0.0rc2-py3.6.egg (from onnx)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages/typing_extensions-3.7.4.3-py3.6.egg (from onnx)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf->onnx)
```
but the **ImportError** disappeared
```
root@7bf42ec17302:/opt/onnx/onnx/shape_inference# python3.6 -c "import onnx"
root@7bf42ec17302:/opt/onnx/onnx/shape_inference# 
```

**Comment by jcwchen** [comment]
I think the issues here are quite many. Let me organize:
1. cannot import name 'ONNX_ML: use other directories to use `import onnx` instead of `onnx/`
2. No module named 'pybind11_tests': `git submodule update --init --recursive` first then install
3. \Library\include\google/protobuf/stubs/logging.h(102,23): error C2220 the following warning is treated as an error: if you are using shared protobuf, please add `set USE_MSVC_STATIC_RUNTIME=0
set CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON"` to build ONNX on Windows.

So what's your issue @YueWenjun ? Thanks.

**Comment by whcjb** [comment]
the same problem, set onnx_ml=1, build from source.

**Comment by tothedistance** [comment]
> the same problem, set onnx_ml=1, build from source. someone can help?

it seems not importing onnx under onnx directory works for me.
