### ISSUE TITLE
Parser does not provide the correct output dimension

### ISSUE THREAD

**Issue by marcomgg** [onnx/onnx#3212]
Hello, I was trying to import a model exported with tensorflow that has output size (batch_size, 2)
however the parser returns an output dimension of (-1,-1).

Here is the output of the logger in verbose mode:

ModelImporter.cpp:125: resnet_model/out_layer/MatMul [MatMul] inputs: [resnet_model/dropout_2/Identity:0 -> (-1, 512)], [resnet_model/out_layer/MatMul/ReadVariableOp__273 -> (512, 2)], 
ImporterContext.hpp:150: Registering constant layer: resnet_model/out_layer/MatMul/ReadVariableOp__273 for ONNX initializer: resnet_model/out_layer/MatMul/ReadVariableOp__273
builtin_op_importers.cpp:2120: GEMM: using FC layer instead of MM because all criteria were met.
onnx2trt_utils.cpp:1815: Original shape: (\_, 512), unsqueezing to: (\_,\_, \_,\_)
ImporterContext.hpp:154: Registering layer: resnet_model/out_layer/MatMul for ONNX node: resnet_model/out_layer/MatMul
onnx2trt_utils.cpp:1663: Original shape: (\_, 2, 1, 1), squeezing to: (\_, \_)
ImporterContext.hpp:120: Registering tensor: resnet_model/out_layer/MatMul:0 for ONNX tensor: resnet_model/out_layer/MatMul:0
ModelImporter.cpp:179: resnet_model/out_layer/MatMul [MatMul] outputs: [resnet_model/out_layer/MatMul:0 -> (-1, -1)], 
ModelImporter.cpp:103: Parsing node: Identity [Identity]
ModelImporter.cpp:119: Searching for input: resnet_model/out_layer/MatMul:0
ModelImporter.cpp:125: Identity [Identity] inputs: [resnet_model/out_layer/MatMul:0 -> (-1, -1)], 
ImporterContext.hpp:154: Registering layer: Identity for ONNX node: Identity
ImporterContext.hpp:120: Registering tensor: Identity_raw_output___3:0 for ONNX tensor: Identity_raw_output___3:0
ModelImporter.cpp:179: Identity [Identity] outputs: [Identity_raw_output___3:0 -> (-1, -1)], 
ModelImporter.cpp:103: Parsing node: Identity_graph_outputs_Identity__4 [Identity]
ModelImporter.cpp:119: Searching for input: Identity_raw_output___3:0
ModelImporter.cpp:125: Identity_graph_outputs_Identity__4 [Identity] inputs: [Identity_raw_output___3:0 -> (-1, -1)], 
ImporterContext.hpp:154: Registering layer: Identity_graph_outputs_Identity__4 for ONNX node: Identity_graph_outputs_Identity__4
ImporterContext.hpp:120: Registering tensor: Identity:0_0 for ONNX tensor: Identity:0
ModelImporter.cpp:179: Identity_graph_outputs_Identity__4 [Identity] outputs: [Identity:0 -> (-1, -1)], 
ModelImporter.cpp:510: Marking Identity:0_0 as output: Identity:0

Up until the squeezing everything is fine, then the output dimesion si set to (-1,-1) instead of (-1, 2).

**Comment by jcwchen** [comment]
Hi @marcomgg,
Do you mean that the produced ONNX model (dimension) is different from the original tensorflow?

**Comment by marcomgg** [comment]
Hi @jcwchen,
no, i mean that when I access the output dimension like this: network->getOutput(0)->getDimensions();
i get (-1,-1) instead of (-1, 2) which would be the correct one.  I need the dimension to then allocate the buffers
for inference.

**Comment by jcwchen** [comment]
I see. Could you provide the ONNX model? Where is this parser comes from (onnx-tensorrt)? Thanks.

**Comment by marcomgg** [comment]
The parser is the one included in the nvidia tensorrt package.
You can get the model from this link: https://drive.google.com/file/d/1-gOVBgP93AlBhX11yfv7OJH9IKF1vECO/view?usp=sharing
because it is too big to be shared here.

**Comment by jcwchen** [comment]
Thanks for providing the model. The node `Identity_graph_outputs_Identity__4` looks normal to me. (Output is float32[unk__276,2]) I am not familiar with the parser from onnx-tensorrt. It seems that it will do some shape inference? I think you can open an issue under onnx-tensorrt to get the best help. Thank you!

**Comment by marcomgg** [comment]
Thank you, I posted it in the onnx-tensorrt repo.
