### ISSUE TITLE
Error in conveting pytorch stylegan generator into onnx 

### ISSUE THREAD

**Issue by levindabhi** [onnx/onnx#3215]
I am trying to convert [pixel2style2pixel](https://github.com/eladrich/pixel2style2pixel) ffhq encoder model into onnx format. I am encountering an error in the conversion of custom cuda extensions that StyleGAN uses. [Here is file where custom cuda extensions are written](https://github.com/eladrich/pixel2style2pixel/tree/master/models/stylegan2/op)
Here is the main error message 
`RuntimeError: ONNX export failed: Couldn't export Python operator FusedLeakyReLUFunction`

**Pytorch version**:1.7.0+cu101
**Model opset**:11

**Comment by jcwchen** [comment]
Hi @levindabhi,
It seems that `FusedLeakyReLUFunction` is your custom pytorch operator? ONNX supports most of official pytorch operator as listed here: https://pytorch.org/docs/stable/onnx.html#supported-operators

If you would like to request a support for new operator, please open an issue under pytorch repo to get help from the converter team (torch.onnx.export). Thank you.
