### ISSUE TITLE
IndexError when invoking utils.polish_model

### ISSUE THREAD

**Issue by lemonviv** [onnx/onnx#3219]
# Ask a Question

### Question
Hi,

I am trying to do the following steps on a mobilenet v1 onnx model, 

```
model = onnx.load(infile)
model = shape_inference.infer_shapes(model)
model = utils.polish_model(model)
```

but I received an error at the third step, 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/onnx/utils.py", line 24, in polish_model
    model = onnx.optimizer.optimize(model)
  File "/usr/local/lib/python3.8/site-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: Input 475 is undefined!
```

The .onnx model I used is from [here](https://zenodo.org/record/4313976#.YAJ-YekzZTY), which is converted from Tensorflow format. I also tried to use the .onnx [MobileNet v2 model](https://github.com/onnx/models/tree/master/vision/classification/mobilenet/model), and got the same error. But for the [ResNet .onnx model](https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v2-7.onnx), I can correctly do the above executions. The onnx version is 1.8.0 and python version is 3.8 on Mac.

I wonder why some models are okay but some not. Any suggestions would be highly appreciated. 

Thank you.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*MobileNet v1*):  
**Model opset** (*Default*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @lemonviv,
Similar to https://github.com/onnx/onnx/issues/2902.
This failure is related to a known IR gap issue. For IR<4, graph's initializer needs to be included in graph's input. These failed models follows the new IR (graph's  initializer are not included in graph's input). Then onnx.optimizer cannot find initialzer from graph's input and cause this error.

There are 2 ways to workaround this:
1. build ONNX from source with this PR https://github.com/onnx/onnx/pull/3007
2. https://github.com/onnx/onnx/issues/2660#issuecomment-605874784 Use the python method (add_value_info_for_constant) to make graph's input include graph's initializer.

Thank you.

**Comment by lemonviv** [comment]
Thank you for the suggestions.
