### ISSUE TITLE
 Is there a way to avoid people who look inside of my model?

### ISSUE THREAD

**Issue by JonathanSum** [onnx/onnx#3223]
# Ask a Question

### Question
Is there a way to avoid people who look inside of my model?
I am planning to deploy a few models from Pytorch to ONNX, but I do not want people to use them and say it is their work or they designed it.
Is there a way to avoid people looking into the inside part of the model? I will do things similar in super re-revolution, Gans, or NLP.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
As far I know, official ONNX file does not have this ability... You might need to try other third-party encryption methods to encrypt your model.

**Comment by JonathanSum** [comment]
Closing this issue.
