### ISSUE TITLE
Updates to external data helpers

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#3228]
Add a new API for converting a model to external data. Today the conversion happens in 2 steps
`external_data_helper.convert_model_to_external_data(<model>,
                                                        <all_tensors_to_one_file>, <size_threshold>)
 save_model(model, output_path)
`
We want to add another api which combines the 2 steps
`
save_model_to_external_data(<model>, <output_path>, <all_tensors_to_one_file>, <size_threshold>, <convert_attributes>)
`

**Comment by annajung** [comment]
Hi @askhade, thanks for suggesting me to work on this issue! 
I have a question about `conver_attributes` parameter in the `save_model_to_external_data`.

Neither of `convert_model_to_external_data` and `save_model` has this input. So wondering what your thoughts are in including this in the combined API `save_model_to_external_data`. 

Could you help expand the input and how `convert_attributes` should be used?

**Comment by askhade** [comment]
Sure!
If you look at the external data helpers code you will see we convert every tesnsor to external data even the ones in AttributeProto. This is not ideal since attributes are not usually large and it takes more memory to make them external than just leaving then in the model itself. So by default we should to exclude tensorprotos in attributeproto but also give an option to convert them to external data to preserve existing behaviour. Therefore I am proposing to add a boolean convert_attributes.

**Comment by annajung** [comment]
Thanks for the explanation! I will take a look and let you know if I have more questions

**Comment by annajung** [comment]
Hi @askhade I want to run the logic by you and see if this makes sense.

The `save_model_to_external_data` function takes parameters listed above. 

When the parameter `convert_attribute` is true, it runs the existing `convert_model_to_external_data` function then saves the model. 
If false, it runs the similar code but tensors loops through `_get_initializer_tensors` function instead `_get_all_tensors` function then saves the model. 

Does that logic seem okay to you? I wanted to double-check because I'm running into a few problems with unit tests that I am writing for the `save_model_to_external_data`. There seems to be no difference between the test result when using  `_get_initializer_tensors` vs `_get_all_tensors`. 

In case my logic is wrong, I wanted to get your feedback to determine where to focus on. Any feedback would be appreciated! thanks :D

**Comment by annajung** [comment]
Update: I was a little confused, but found my way! I got confused on why some had `data_location` and some did not. Regardless, only the converted has the field which I can use for testing. I ended up using `MessageToJson`, but not sure if this is the best way. Will try to wrap up and make a PR soon for you to take a look at.

**Comment by askhade** [comment]
> Hi @askhade I want to run the logic by you and see if this makes sense.
> 
> The `save_model_to_external_data` function takes parameters listed above.
> 
> When the parameter `convert_attribute` is true, it runs the existing `convert_model_to_external_data` function then saves the model.
> If false, it runs the similar code but tensors loops through `_get_initializer_tensors` function instead `_get_all_tensors` function then saves the model.
> 
> Does that logic seem okay to you? I wanted to double-check because I'm running into a few problems with unit tests that I am writing for the `save_model_to_external_data`. There seems to be no difference between the test result when using `_get_initializer_tensors` vs `_get_all_tensors`.
> 
> In case my logic is wrong, I wanted to get your feedback to determine where to focus on. Any feedback would be appreciated! thanks :D

for you to see the difference you need to make sure your test case includes an attribute which has data stored in tensorproto otherwise there is no difference. For example if you can test a model with ConstantOfShape node you will see the difference when convert_attribute is set to true vs false.

**Comment by annajung** [comment]
I realize that it's not the operator that was the problem and kept it simple and check for the "data_location" field, hopefully, that's good validation. PR is open to get your feedback :) 

PR: https://github.com/onnx/onnx/pull/3280
