### ISSUE TITLE
ONNX optimizer - fuse_consecutive_reduce_unsqueeze crashes 

### ISSUE THREAD

**Issue by JianhuiD** [onnx/onnx#3229]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
ONNX optimizer - fuse_consecutive_reduce_unsqueeze crashes 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Windows
- ONNX version (*e.g. 1.7*):    1.8.0
- Python version: 3.6.8
- GCC/Compiler version (if compiling from source): N/A
- CMake version: N/A
- Protobuf version: 3.8.0
- Visual Studio version (if applicable): N/A

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
model_optimized = onnx.optimizer.optimize(model, ["fuse_consecutive_reduce_unsqueeze"])
...
```
- Attach the ONNX model to the issue (where applicable)
[reduce_unsqueeze.zip](https://github.com/onnx/onnx/files/5839153/reduce_unsqueeze.zip)

### Expected behavior
Except 1. no crash and 2. fuse for consecutive reduce and unsqueeze op in the attached model

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @JianhuiD,
ONNX will move `onnx.optimizer` to another repo [onnx/optimizer](https://github.com/onnx/optimizer) in ONNX 1.9.0. Transfer this issue there to get the best help. Thanks.

**Comment by JianhuiD** [comment]
okay, copied to https://github.com/onnx/optimizer/issues/29

**Comment by daquexian** [comment]
`onnx.optimizer` is not maintained. This bug is already fixed in https://github.com/onnx/optimizer, please use it instead. :)
