### ISSUE TITLE
Conversion of Pytorch model with custom layer to ONNX

### ISSUE THREAD

**Issue by teobaluta** [onnx/onnx#3236]
# How to export a Pytorch model that has a custom layer?

### Question

I would like to convert binarized neural networks trained in Pytorch [1] that have a `BinarizeLinear` layer extending the `nn.Linear`. However, when I tried to do so, I noticed that the model is missing the `Binarize` operation [2] which translates to `tensor.sign()`. I saw ONNX has support for Sign() so I wondering why it could not detect that the `Binarize` function is essentially a sign operation.

Is it that `Binarize` should be of some other type? What can I do to fix this?

[1] https://github.com/itayhubara/BinaryNet.pytorch
[2] https://github.com/itayhubara/BinaryNet.pytorch/blob/master/models/binarized_modules.py#L76

### Further information
Package Version
- `torch`: 1.7.1
- `torchvision`: 0.2.2
- `onnx`: 1.8.0

- Is this issue related to a specific model?  
**Binarized Neural Networks (MNIST)**

### Notes

This is the sketch of where the export is happening. It is part of the `pytorch2keras` package code.

```
   input_names = ['input_{0}'.format(i) for i in range(len(args))]
    output_names = ['output_{0}'.format(i) for i in range(len(dummy_output))]

    logger.debug('Input_names:')
    logger.debug(input_names)

    logger.debug('Output_names:')
    logger.debug(output_names)

    stream = io.BytesIO()
    torch.onnx.export(model, args, stream, do_constant_folding=do_constant_folding, verbose=verbose, input_names=input_names, output_names=output_names)

    stream.seek(0)
    onnx_model = onnx.load(stream)
    onnx.checker.check_model(onnx_model)
    onnx.save(onnx_model, 'model.onnx')
    import netron
    netron.start('model.onnx')
    if use_optimizer:
        if use_optimizer is True:
            optimizer2run = optimizer.get_available_passes()
        else:
            use_optimizer = set(use_optimizer)
            optimizer2run = [x for x in optimizer.get_available_passes() if x in use_optimizer]
        logger.info("Running optimizer:\n%s", "\n".join(optimizer2run))
        onnx_model = optimizer.optimize(onnx_model, optimizer2run)
```
Here is the saved ONNX model after transformation.
![image](https://user-images.githubusercontent.com/1837924/105624177-98e2cc80-5e5a-11eb-9ae3-8d71e53dc5f0.png)

**Comment by jcwchen** [comment]
Hi @teobaluta,
As you mentioned, it looks to me that ONNX does support the converted operators for your BinarizeLinear so it should be a converter issue. Do you encounter any error or warning message during the conversion? Please open an issue under pytorch repo to get the best help from the converter team (torch.onnx.export). Thanks.

**Comment by teobaluta** [comment]
Hi @jcwchen 

Thanks for your reply! The only warning in the conversion is the following (which I think does not have anything to do with the operation).

```
UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include
dim=X as an argument.
```

**Comment by teobaluta** [comment]
Could it be an issue with tracing? Could I somehow inspect the stream of bytes that is passed to the export?

I have opened an issue with the Pytorch team as well, issue is [here](https://github.com/pytorch/pytorch/issues/51033).

**Comment by jcwchen** [comment]
Yes this warning should be fine... I believe all these questions are related to the converter. Please track this issue there. Thank you!

**Comment by jcwchen** [comment]
It seems that it has been resolved. Please reopen it if you have any ONNX issue. Thank you!
