### ISSUE TITLE
Pad input/output data types documentation is inconsistent

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx#3240]
# Ask a Question

### Question
The input/output data type for Pad opset 13 is documented as "Constrains input and output to only numeric types." while the type constraint is "OpSchema::all_tensor_types_with_bfloat()". Should it be documented as "Constrain input and output types to all tensor types."?

### Further information
The code is https://github.com/onnx/onnx/blob/490895703c82f68e723a8b308369cac4ed0abc0c/onnx/defs/tensor/defs.cc#L3300

### Notes
Please make it consistent so all users and converters know exactly what data types are allowed as inputs (data and constant_value) and output (output). Also nice to provide the default value for constant_value for non-numeric input data, such as string and bool.

**Comment by askhade** [comment]
@chinhuang007 can you send out a PR with the update. Thanks!

**Comment by chinhuang007** [comment]
@askhade I certainly could. Before that, I would like to confirm that the schema is correct. That means all tensor types are valid. And shall we also document the recommended additional defaults for constant_value, empty string "" for string type and False for bool type?

**Comment by chinhuang007** [comment]
A PR is created, assuming the schema is correct and we would like to document the defaults, https://github.com/onnx/onnx/pull/3241.

**Comment by jcwchen** [comment]
Thanks @chinhuang007 for the fix. I think it has been resolved. Please reopen if it is still a problem. Close now.
