### ISSUE TITLE
regard, onnxruntimeinference

### ISSUE THREAD

**Issue by Pushpalathahareesh** [onnx/onnx#3245]
Hi, I need help in resolving this  error:
2021-01-28 18:18:38.4236867 [E:onnxruntime:, inference_session.cc:1268 onnxruntime::InferenceSession::Initialize::<lambda_c608601079ff6a1804107b16babd2631>::operator ()] Exception during
initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2:
 out of memory ; GPU=0 ; hostname=LAPTOP-6EUODJJ7 ; expr=cudaMalloc((void**)&p, size);

Iam getting the above error  when inferencing on onnx file "albert_model_512.onnx".

I got the above onnx file by converting pretarined transformer model ahotrod/albert_xxlargev1_squad2_512 , using below code
torch.onnx.export(model_instance,model_input, "albert_model_512.onnx",opset_version=12,use_external_data_format=True),
but this is not single file i have got ,  have attached the list of files which i got along with  albert_model_512.onnx.

framework:pytorch
IDE:pycharm
pretrained transformer model: ahotrod/albert_xxlargev1_squad2_512
transformer version:4.2.0
regards,
pushpalatha M
system

pls help me to resolve this issue.

**Comment by Pushpalathahareesh** [comment]
when i convert ahotrod/albert_xxlargev1_squad2_512 to onnx i get list of multiple files like(1400,1401,1405.....1604,albert_model_512.onnx,albert.porition.embeddings.....,albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias etc).

please let me know how to inference these files, when i inference alone albert_model_512.onnx i get below error 2021-01-28 18:18:38.4236867 [E:onnxruntime:, inference_session.cc:1268 onnxruntime::InferenceSession::Initialize::<lambda_c608601079ff6a1804107b16babd2631>::operator ()] Exception during
initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2:
out of memory ; GPU=0 ; hostname=LAPTOP-6EUODJJ7 ; expr=cudaMalloc((void**)&p, size);

**Comment by jcwchen** [comment]
Hi @Pushpalathahareesh,
As long as those external data are in the same directory with the ONNX model file, they can be used by ONNX/ONNXRuntime. If you put them in the same directory and still encounter this error, please open an issue under onnxruntime to get the best help. Thank you.

**Comment by Pushpalathahareesh** [comment]
Hi, thanks for the reply
 The external files are in same directory with the onnx model file, but when i inference using below code i get the error.

**Inference Code:**


def create_model_for_provider(model_path: str, provider: str):
    assert provider in get_all_providers(), f"provider {provider} not found, {get_all_providers()}"

    # Few properties that might have an impact on performances (provided by MS)
    options = SessionOptions()#SessionOptions.MakeSessionOptionWithCudaProvider(0)
    options.intra_op_num_threads = 1
    options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL

    # Load the model as a graph and prepare the GPU backend
    session = InferenceSession(model_path, options, providers=[provider])
    session.disable_fallback()

    return session

#run Inference on the onnx model
PROVIDERS = {
    #("CPUExecutionProvider", "ONNX CPU"),
    #Uncomment this line to enable GPU benchmarking
    ("CUDAExecutionProvider", "ONNX GPU")
}
for provider, label in PROVIDERS:
    # Create the model with the specified provider
    model = create_model_for_provider("D:/nlg_albert_optimize/onnx_files/albert_model_512.onnx", provider)


Error:
sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_cal
l.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=LAPTOP-6EUODJJ7 ; expr=cudaMa
lloc((void**)&p, size);

I wanted to know how the multiple files connected  to model file albert_model_512.onnx is processed. Is there a way to do so.Pls  let me know possible solutions

regards,
pushpalatha M

**Comment by jcwchen** [comment]
ONNX/ONNXRuntime considers external data is in the same directory of the model. For instance, if you store the model as `test/dir/model.onnx`, ONNX/ONNXRuntime will find other external data under `test/dir/`. Since you have put them in the same directory, I would say this memory error might be caused by other reasons... This error happens in the runtime and I saw you have opened an issue in ONNXRuntime. Please track this issue there. Thank you.

**Comment by Pushpalathahareesh** [comment]
thanks for response.

regards,
pushpalatha M

**Comment by Ilay33** [comment]
Did u find a solution?
