### ISSUE TITLE
optimization in pytorch can not work in onnx

### ISSUE THREAD

**Issue by WilliamZhaoz** [onnx/onnx#3246]
I did some optimization in pytorch, it get ~4times speed up, but when I convert the model to onnx, it can not work.
I just re-use some middle result in ConvNet, there are some if else branch to decide re-use or not, I store the middle results in a memory cache, and every inference I update the cache, and use some number in it.
Does anyone have any ideas?

**Comment by jcwchen** [comment]
Hi @WilliamZhaoz,
Do you mean that the ONNX model is not converted as expected? I don't think currently `torch.onnx.export` can handle complicated logic and you can check the supported operators here: https://pytorch.org/docs/stable/onnx.html 
Other than these supported operators, the converter would probably fail. Do you encounter any warning/error during the conversion? Thanks.

**Comment by WilliamZhaoz** [comment]
Thanks for your replying
The onnx model actually produce the right output, but not expected speed. My optimization is not complicated at all, it is very simple and straight forward, like, it would process X points, but there are half of X is overlaped in every forward, so I let it just process a half of X, and pad another half of it from a memory cache, of course, I will update the cache every time. In this way, I can feed X point data to model and get X points output with only a half of X data need to be calculated. The model receive X data and the cache, output X points output and updated cache. I expected only a half of the original time is need, and in pytorch it does, but in onnx it still take the same time as processing the X points data. I am thinking that is it possible that onnx fuse or combine some ops and in this process a smaller op is aligned to a bigger op which leads this problem I hit?

**Comment by jcwchen** [comment]
Thank you for providing more details. Are these if-else branches for optimization in pytorch converted to ONNX operators correctly? If so, are you saying that ONNXRuntime cannot gain speed improvement by the same design as pytorch?

**Comment by WilliamZhaoz** [comment]
thanks for your replying. yes, I believe they are converted correctly, because I got the right output, almost exactly same with pytorch output. Yes, I think that's the problem, and I'd like to know the possible reason and how to solve it.

**Comment by jcwchen** [comment]
Maybe a naive question: Even though the output is same as pytorch, it is still possible that this optimization is not applied to the graph, right? (Because it is only related to speed)

Anyway, if the model was converted correctly as your expectation, I think ONNX itself should be fine. This optimization should happen in runtime but it didn't. Please open an issue in ONNXRuntime to get better assistance. Thank you!

**Comment by WilliamZhaoz** [comment]
Thank you @jcwchen so much, yes I expected the model in onnx should get the same speed up, but it did't, and the optimization is so simple, so I doubt that there are some problem when I convert the model. I'll open an issue in ONNXRuntime too. thanks.

**Comment by jcwchen** [comment]
I saw you has raised an issue about this in ONNXRuntime. Close here. Thanks!
