### ISSUE TITLE
Detect the dtype of the input tensor?

### ISSUE THREAD

**Issue by Zha0q1** [onnx/onnx#3248]
I am working on onnx export support for MXNet. I wonder if there is a way to detect the dtype of the input tensor to a node? A sample use case is that while translating MXNet `plus_scalar` to onnx I need to know the dtype of the input tensor so that I can create a onnx scalar of that same type. Currently I use the same dtype of the input to the entire model, but apparently this will not work if the specific input tensor to `plus_scalar` has a different dtype/

**Comment by jcwchen** [comment]
Hi @Zha0q1,
I am not sure whether I understand your question. Are you saying `graph.input`? If so, you can use something like `m.graph.input[0].type.tensor_type.elem_type` to get the type of certain input.

**Comment by Zha0q1** [comment]
Hi @jcwchen, I mean when constructing a graph and connecting nodes, is there a way to know the dtype of the output of the previous node (which is also the input to the current node)?

**Comment by Zha0q1** [comment]
This is before we even call `make_graph()`

**Comment by jcwchen** [comment]
So right now you only have a lot of ONNX nodes and you want to construct a ONNX model graph by them?
I think NodeProto only has "name" information for input/output. You might need to maintain a dictionary (key is unique name and value is dtype) yourself by traversing all nodes first.

**Comment by jcwchen** [comment]
I assume this question has been resolved due to inactivity.... Please reopen it if you still have questions related to ONNX. Thanks!
