### ISSUE TITLE
[regression in 1.8.1] /usr/ports/misc/py-onnx/work-py37/onnx-1.8.1/tools/protoc-gen-mypy.sh: program not found or is not executable

### ISSUE THREAD

**Issue by yurivict** [onnx/onnx#3251]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Build fails:
```
usr/ports/misc/py-onnx/work-py37/onnx-1.8.1/tools/protoc-gen-mypy.sh: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--mypy_out: protoc-gen-mypy: Plugin failed with status code 1.
```

File ```tools/protoc-gen-mypy.sh``` is missing. ```tools/protoc-gen-mypy.sh.in``` hasn't been translated.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  FreeBSD 12.2
- ONNX version (*e.g. 1.7*):  1.8.1
- Python version: 3.7
- GCC/Compiler version (if compiling from source): clang-10
- CMake version: cmake-3.19.2

Build is done with ```python setup.py install```, according to README. It worked in 1.8.0 but not in 1.8.1

**Comment by jcwchen** [comment]
Hi @yurivict,
Thank you for reporting this. Does it also happen with 'pip install onnx'?

We have a recent change about this: https://github.com/onnx/onnx/pull/3221
Maybe in FreeBSD 'DIR' cannot get the correct path?

**Comment by yurivict** [comment]
I had to add this patch to make it build:
```
--- CMakeLists.txt.orig 2021-02-01 05:41:35 UTC
+++ CMakeLists.txt
@@ -18,7 +18,7 @@ project(onnx C CXX)
 option(ONNX_BUILD_BENCHMARKS "Build ONNX micro-benchmarks" OFF)
 option(ONNX_USE_PROTOBUF_SHARED_LIBS "Build ONNX using protobuf shared library. Sets PROTOBUF_USE_DLLS CMAKE Flag " OFF)
 
-option(BUILD_ONNX_PYTHON "Build Python binaries" OFF)
+option(BUILD_ONNX_PYTHON "Build Python binaries" ON)
 option(ONNX_GEN_PB_TYPE_STUBS "Generate protobuf python type stubs" ON)
 option(ONNX_WERROR "Build with Werror" OFF)
 option(ONNX_COVERAGE "Build with coverage instrumentation" OFF)
```

**Comment by jcwchen** [comment]
So it can be fixed by setting BUILD_ONNX_PYTHON=ON? https://github.com/onnx/onnx/blob/b1e0bc9a31eaefc2a9946182fbad939843534984/setup.py#L167  I think `BUILD_ONNX_PYTHON` should already be set as ON while running setup.py. 

I am trying to find the root cause. Maybe this PR is related: https://github.com/onnx/onnx/pull/2961
So does it happen with both `python setup.py install` and `pip install onnx` in your environment? Thanks.

**Comment by yurivict** [comment]
> I think BUILD_ONNX_PYTHON should already be set as ON while running setup.py.

This doesn't appear to be the case since the above patch made a difference.

**Comment by yurivict** [comment]
Current versions of ONNX build fine on FreeBSD.
