### ISSUE TITLE
Float representation in AttributeProto

### ISSUE THREAD

**Issue by Talmaj** [onnx/onnx#3261]
### Question
I would like to understand how the float conversion works for AttributeProto.

### Further information
The conversion to FloatAttribute and back does not return the same float value. I guess it has something to do with float representation or I am doing it wrong.

### Notes
```
value = 0.1
attr = onnx.AttributeProto(type="FLOAT", f=value)
assert attr.f == value
```
The above fails, however it works for round numbers, like 0.5 and 1.
I am running it on MacOS.

**Comment by jcwchen** [comment]
Hi @Talmaj,
Something related to https://github.com/protocolbuffers/protobuf/issues/4569? But I cannot solve this by setting `export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python`...

**Comment by jcwchen** [comment]
Hi @Talmaj,
You can see the explanation here: https://github.com/protocolbuffers/protobuf/issues/8269. Thank you.

**Comment by Talmaj** [comment]
Thanks, that explains it! 
```
value = 0.1
attr = onnx.AttributeProto(type="FLOAT", f=value)
assert attr.f == np.float32(value) # True
```
