### ISSUE TITLE
how to make a node which contains scalar value

### ISSUE THREAD

**Issue by hnuhchen** [onnx/onnx#3262]
# Ask a Question

### Question

Hello, i want to use onnx.helper to make a model, the model contains the clip layer, and i use this code:
```
Clip152_min_val = np.float32(0)
Clip152_min = helper.make_node('Constant', inputs=[], outputs=['Clip152_min'], value=helper.make_tensor(name='const_tensor', data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[Clip152_min_val.dtype], dims=Clip152_min_val.shape, vals=Clip152_min_val))
Clip152_max_val = np.float32(6)
Clip152_max = helper.make_node('Constant', inputs=[], outputs=['Clip152_max'], value=helper.make_tensor(name='const_tensor', data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[Clip152_max_val.dtype], dims=Clip152_max_val.shape, vals=Clip152_max_val))
Clip152     = helper.make_node('Clip', inputs=['BN151', 'Clip152_min', 'Clip152_max'], outputs=['Clip152'], name='Clip152')
```

But the model cannot be generated, the error infomation is:
```
File "/usr/local/lib/python3.5/dist-packages/onnx/helper.py", line 174, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: Value must be iterable
```
Thank you 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):  opset 11

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @hnuhchen,
Similar to https://github.com/onnx/onnx/issues/1799?
I don't think constant operator can take scalar a s input. So you might need to use something like:
```
Clip152_min_val = np.array([0]).astype(np.float32)
Clip152_min = helper.make_node('Constant', inputs=[], outputs=['Clip152_min'], value=helper.make_tensor(name='const_tensor', data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[Clip152_min_val.dtype], dims=Clip152_min_val.shape, vals=Clip152_min_val))
Clip152_max_val = np.array([6]).astype(np.float32)
Clip152_max = helper.make_node('Constant', inputs=[], outputs=['Clip152_max'], value=helper.make_tensor(name='const_tensor', data_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[Clip152_max_val.dtype], dims=Clip152_max_val.shape, vals=Clip152_max_val))
Clip152     = helper.make_node('Clip', inputs=['BN151', 'Clip152_min', 'Clip152_max'], outputs=['Clip152'], name='Clip152')
```

**Comment by hnuhchen** [comment]
@jcwchen, thank you, but  the [file](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Clip-11) shows that


Clip-11
Clip operator limits the given input within an interval. The interval is specified by the inputs 'min' and 'max'. They default to numeric_limits::lowest() and numeric_limits::max(), respectively.

Version
This version of the operator has been available since version 11 of the default ONNX operator set.

Inputs (1 - 3)
input : T
Input tensor whose elements to be clipped
min (optional) : T
Minimum value, under which element is replaced by min. **It must be a scalar(tensor of empty shape)**.
max (optional) : T
Maximum value, above which element is replaced by max. **It must be a scalar(tensor of empty shape).**
Outputs
output : T
Output tensor with clipped input elements
Type Constraints
T : tensor(float16), tensor(float), tensor(double)
Constrain input and output types to float tensors.

So what should i do to build the constant node?

**Comment by jcwchen** [comment]
Sorry that I just found newer Constant operator does support scalar as output tensor: https://github.com/onnx/onnx/pull/2592
Starting from Constant-12, Constant supports value_float to let users use float32 scalar as constant output. So you can use:
```
Clip152_min_val = 0
Clip152_min = helper.make_node('Constant', inputs=[], outputs=['Clip152_min'], value_float=0.)
Clip152_max_val = 6
Clip152_max = helper.make_node('Constant', inputs=[], outputs=['Clip152_max'], value_float=6.)
Clip152     = helper.make_node('Clip', inputs=['BN151', 'Clip152_min', 'Clip152_max'], outputs=['Clip152'], name='Clip152')
```

Thanks.

**Comment by hnuhchen** [comment]
@jcwchen， thank you,   you answer is of great use to me, i can generate the onnx model by the code you provided, and infer the model by using onnxruntime.
But, if i use `onnx.checker.check_model` interface to check the onnx model, it fail(because i must use opset11, the constant node is from opset12). 
I have another onnx model(opset11) which has clip layer with min and max as inputs, and it can be infered by onnxruntime, and it can be checked by `onnx.checker.check_model`, so i want to generate my onnx model like that.
My model(left, opset11, can be infered, but cannot be checked),   another model(right, opset11, can ne infered and checked)
![image2](https://user-images.githubusercontent.com/29193431/107307453-aedec700-6ac1-11eb-987e-39802c2da076.png)

**Comment by jcwchen** [comment]
Is there any reason you need to use a Constant node for it? Otherwise actually you can use an initializer as a scalar for Clip's attribute. For instance,
```
Clip = helper.make_node('Clip', inputs=['clip_input', 'min_v', 'max_v'], outputs=['clip_output'], name='Clip152')
graph_def = helper.make_graph(
  nodes = [Clip],
  name = 'test_graph',
  inputs = [helper.make_tensor_value_info('clip_input', TensorProto.FLOAT, [2])], # use your input
  outputs = [helper.make_tensor_value_info('clip_output', TensorProto.FLOAT, [2])], # use your output
  initializer = [helper.make_tensor('min_v', TensorProto.FLOAT, [], [0.]), helper.make_tensor('max_v', TensorProto.FLOAT, [], [6.])])
```
The output tensor of Constant node before opset_version 11 needs to be a tensor which has a shape. There are some arguments about how to treat scalars. https://github.com/onnx/onnx/issues/2428

Still, I think usually people will use initializers to represent those scalar attributes. Thanks.

**Comment by hnuhchen** [comment]
@jcwchen, thank you, i just want to know how to generate my onnx model like the right of the previous image using opset11(the model can be infered and checked successfully, with min and max as constant scalar nodes)

**Comment by jcwchen** [comment]
Since Constant-11 does not support scalar, I am not sure whether Clip-11 can use Constant-11 to represent its min/max. Instead, typically Clip uses graph.initializer to represent its min/max. Does it meet your requirement? Thanks.

**Comment by hnuhchen** [comment]
@jcwchen, yes, i can generate, check and infer the onnx model successfully by using graph.initializer to represent its min/max, thanks.
