### ISSUE TITLE
Exporting the operator 'triu' to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by laobadao** [onnx/onnx#3263]
# Bug Report

pytorch 1.7.1  torch.triu not supported to onnx 

Exporting the operator 'triu' to ONNX opset version 11 is not supported

### Is the issue related to model conversion?
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version (*e.g. 1.7*):  
- Python version: 3.7.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @laobadao,
Duplicate issue: https://github.com/pytorch/pytorch/issues/32968 https://github.com/onnx/onnx/issues/2554. Thank you.

**Comment by jcwchen** [comment]
Close now. Please track this issue there. Thanks.
