### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by sandeep1671995** [onnx/onnx#3268]
# Ask a Question
Install onnx on Jetson NX (JetPack 4.4 L4T 32.4.3 ) using command "pip3 install onnx" gives Illegal instruction (core dumped)

nvidia@k4:~$ python3 
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Illegal instruction (core dumped)

Tried to build from source but I could not find any solution for this problem. Any help would be appreciated

**Comment by jcwchen** [comment]
Hi @sandeep1671995,
Did it only happen with the latest ONNX (1.8.1)? Could you try to `pip install onnx==1.8.0` and `pip install onnx==1.7.0`? I am trying to understand it's a new issue or an old one. Thank you.

**Comment by sandeep1671995** [comment]
> Hi @sandeep1671995,
> Did it only happen with the latest ONNX (1.8.1)? Could you try to `pip install onnx==1.8.0` and `pip install onnx==1.7.0`? I am trying to understand it's a new issue or an old one. Thank you.

I have tried version 1.6.0, 1.7.0 and 1.8.0 ! All gave the same output ( illegal instruction - core dumped ) ! I get the same error when I import 'onnxruntime' module, i don't know if it's connected. 

I also have jetson nano with same jetpack and L4T version and when I tried to install there and import it, i did not get any error and i was able to import without any problem.  Since i don't have another jetson NX, i don't know whether there is a problem with my NX configuration or a general problem.

**Comment by jcwchen** [comment]
Thank you for providing the details.
How about `pip install torch`?

**Comment by jcwchen** [comment]
Thank you for providing the details. How about `pip install torch` and `pip install numpy`?
I have never seen this error before in ONNX so I would say it's more like an environment issue in your machine. 
I saw some users report it in NVIDIA. Maybe you can try to downgrade your numpy and see whether it helps:
https://forums.developer.nvidia.com/t/illegal-instruction-core-dumped/165488/9

**Comment by sandeep1671995** [comment]
> Thank you for providing the details. How about `pip install torch` and `pip install numpy`?
> I have never seen this error before in ONNX so I would say it's more like an environment issue in your machine.
> I saw some users report it in NVIDIA. Maybe you can try to downgrade your numpy and see whether it helps:
> https://forums.developer.nvidia.com/t/illegal-instruction-core-dumped/165488/9

Hi @jcwchen , Thank you for your quick responses. The problem is with numpy version - 1.19.5. After installing previous minor version. pip3 install numpy==1.19.4, onnx and onnxruntime works.  

Thank you again ! I will be closing this issue now !!
