### ISSUE TITLE
ONNX Training

### ISSUE THREAD

**Issue by Ierezell** [onnx/onnx#3269]
### Question
I know ONNX training is a really early feature for now but it's really nice. 

It would mean that we would be able to train on other framework much less supported like nodejs. 

Indeed, there are not a lot of solutions to have machine learning framework in nodejs and one of the best solution was to use ONNX runtime to run pretrained models in a web stack (Yes there is also tensorflowJS with SavedModels).

So what is the status about Onnx training and it's possible API for web usage ? 

### Further information
Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
    - Area : NLP models (Often hugginface related)
    - Backend : Nodejs
    - Converters : Often using Huggingface or Pytorch
    - Operators : The ones of Bert models and pytorch one for small networks. 

Thanks in advance

**Comment by jcwchen** [comment]
Hi @Ierezell,
I am not at the training team, but according to here: https://github.com/microsoft/onnxruntime/pull/6141#issuecomment-747809068, I would say currently ORT Training focuses on Python API and web usage is not in the short-term goal. Thanks.
