### ISSUE TITLE
What is the relation between onnx.optimizer and onnxoptimizer project?

### ISSUE THREAD

**Issue by zhangliliang** [onnx/onnx#3272]
# Ask a Question

### Question
I find that there is a project named onnxoptimizer. (https://github.com/onnx/optimizer)
The codes in the onnxoptimizer project are very similiar to the codes in onnx.optimizer(https://github.com/onnx/onnx/tree/master/onnx/optimizer)

What is the relation between them? 
It seems that onnxoptimizer project update more frequent than the onnx.optimizer. Would it replace the onnx.optimizer 
  someday?

### Further information
- Relevant Area: 
onnxoptimizer

- Is this issue related to a specific model?  
No.

**Comment by jcwchen** [comment]
Hi @ zhangliliang,
You are right. Currently onnx.optimizer is deprecated, moving to https://github.com/onnx/optimizer, and ONNX will remove it in future 1.9. Please use https://github.com/onnx/optimizer if you are interested. Thank you.

**Comment by zhangliliang** [comment]
Thank you for replying.
