### ISSUE TITLE
ONNX checker can't check model with external data bigger than 2GB

### ISSUE THREAD

**Issue by pmarcinkiewicz** [onnx/onnx#3273]
# Bug Report

### Is the issue related to model conversion?
No related to conversion.

### Describe the bug
ONNX checker throws exemption for maximum protobuf size during check_model execution:
```
----> 1 onnx.checker.check_model(m)

/opt/conda/lib/python3.6/site-packages/onnx/checker.py in check_model(model, full_check)
     97         # If the protobuf is larger than 2GB,
     98         # remind users should use the model path to check
---> 99         protobuf_string = model.SerializeToString()
    100         if sys.getsizeof(protobuf_string) > MAXIMUM_PROTOBUF:
    101             raise ValueError('This protobuf of onnx model is too large (>2GB). Call check_model with model path instead.')

Message ONNX_REL_1_8.ModelProto exceeds maximum protobuf size of 2GB: 4299161854
```

### System information
- Ubuntu 18.04.05
- ONNX version 1.8.0
- Python version: 3.6.10
- PyTorch version 1.8.0a0+17f8c32

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import torch
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(1024, 1024 * 1024)
    def forward(self, x):
        x = self.fc(x)
        return x
model = Net()
input = torch.randn(1024, requires_grad=True)
with torch.no_grad():
    torch.onnx.export(model, (input, ), './net.onnx', do_constant_folding=True, opset_version=13,  use_external_data_format=True, enable_onnx_checker=True)
import onnx
m = onnx.load("net.onnx")
onnx.checker.check_model(m)
```

### Expected behavior
The onnx check should report model as valid.

### Notes

ONNX model is exported from PyTorch.

**Comment by jcwchen** [comment]
Hi @pmarcinkiewicz,
As mentioned in the [doc ](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#checking-a-large-onnx-model-2gb), for models larger than 2GB, please use model_path to check_model. Currently protobuf python object cannot exceed 2GB. Thank you.

**Comment by pmarcinkiewicz** [comment]
THX
