### ISSUE TITLE
ONNX model save fails for model with >2GB tensor

### ISSUE THREAD

**Issue by pmarcinkiewicz** [onnx/onnx#3275]
# Bug Report

### Is the issue related to model conversion?
No related to conversion.

### Describe the bug
ONNX model save throws exception for maximum protobuf size during model save execution for large model:
```
ValueError                                Traceback (most recent call last)
<ipython-input-6-b00585ea848d> in <module>
     14 import onnx
     15 m = onnx.load("net.onnx")
---> 16 onnx.save(m, "failure.onnx")

/opt/conda/lib/python3.6/site-packages/onnx/__init__.py in save_model(proto, f, format)
    188         proto = write_external_data_tensors(proto, basepath)
    189
--> 190     s = _serialize(proto)
    191     _save_bytes(s, f)
    192

/opt/conda/lib/python3.6/site-packages/onnx/__init__.py in _serialize(proto)
     67         return proto
     68     elif hasattr(proto, 'SerializeToString') and callable(proto.SerializeToString):
---> 69         result = proto.SerializeToString()
     70         return result
     71     else:

ValueError: Message ONNX_REL_1_8.ModelProto exceeds maximum protobuf size of 2GB: 4299161854
```

### System information
- Ubuntu 18.04.05
- ONNX version 1.8.0
- Python version: 3.6.10
- PyTorch version 1.8.0a0+17f8c32

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import torch
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(1024, 1024 * 1024)
    def forward(self, x):
        x = self.fc(x)
        return x
model = Net()
input = torch.randn(1024, requires_grad=True)
with torch.no_grad():
    torch.onnx.export(model, (input, ), './net.onnx', do_constant_folding=True, opset_version=13,  use_external_data_format=True, enable_onnx_checker=True)
import onnx
m = onnx.load("net.onnx")
onnx.save(m, "failure.onnx")
```

### Expected behavior
A large model should be saved with tensors using external format.

### Notes

ONNX model is exported from PyTorch.

**Comment by jcwchen** [comment]
Hi @pmarcinkiewicz,
By default protobuf message has 2GB limitation: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#CodedInputStream.SetTotalBytesLimit.details
To prevent memory error, ONNX follows this. 

If you want to manipulate >2GB models, please use `onnx.load('path/to/the/model.onnx', load_external_data=False)`, but in that case the raw_data won't be loaded. Basically ONNX utilities (`onnx.checker.check_model` and `onnx.shape_inference.infer_shapes_path`) accepts 2GB models by passing model_path. ONNXRuntime also uses model_path for inference. Thank you.

**Comment by pmarcinkiewicz** [comment]
Still it is possible to load such large tensors with onnx.load. Why Protobuf 2GB limitation doesn't occur during loading but it occurs during save?

PyTorch exporter can save large tensors but ONNX can't do it. 

I see that model loaded with external data retains fields with locations of tensors:

```
In [5]: m2 = onnx.load("net.onnx")

In [9]: m.graph.initializer[1].name
Out[9]: 'fc.weight'

In [10]: m.graph.initializer[1].dims
Out[10]: [1048576, 1024]

In [11]: m.graph.initializer[1].external_data
Out[11]:
[key: "location"
value: "fc.weight"
]
```
Why onnx.save fails to check those fields and save tensors with external_data to files names here?

It is a clear bug not a useful feature.

**Comment by pmarcinkiewicz** [comment]
Thank your for explanation. It is quite confusing.

**Comment by kenny-reyes** [comment]
Does it mean that we can't convert and save large models?

**Comment by jcwchen** [comment]
Thanks for the details. Two questions:
- What is the ONNX model size after converting by sklearn-onnx?
- What did you do before `onnx.save(onx, "model.onnx", save_as_external_data=True)`?

According to the error message you provided, I suspect you were saving an ONNX model with single large external tensor which exceeds the 2GB limit. Perhaps you can try to modify the parameters for [onnx.save](https://github.com/onnx/onnx/blob/5b1346e30d66e4ec550f6b63c3883b258a2e8e3e/onnx/__init__.py#L170). For instance, all_tensors_to_one_file=False with proper size_threshold.

**Comment by kenny-reyes** [comment]
Hi, thanks for the response, I already decided to leave this implementation, but for don't leave this thread dead, and as someone can be interested we can continue.
I couldn't measure it, cause the method ```onnx.checker.check_model(onnx_model)``` for verify the size also uses the SerializeToString [here](https://github.com/onnx/onnx/blob/c759bce40e40c4e093f7864debaa2a16d33191f0/onnx/checker.py#L104)

I didn't do anything, cause the method failed. 
I also try the tensor exceeds the 2GB limit. 
I will try using the "For instance, all_tensors_to_one_file=False with proper size_threshold."

I will respond later after trying.

**Comment by kenny-reyes** [comment]
The same result with the same message, I think the model previous conversion is 965Mb, converted to ONNX is 3,5Gb.
I meant 'ValueError: Message `onnx.ModelProto exceeds maximum protobuf size of 2GB: 3354372734`. Is this the size, right? **3354372734**

**Comment by jcwchen** [comment]
Thanks for the experiment. For ONNX models which is originally larger than 2GB models, please use `onnx.load('path/to/the/model.onnx', load_external_data=False)` to load this if you really want to do so. 2GB is a limitation from Protobuf. You can still use onnx.checker.check_model and onnx.shape_inference.infer_shapes_path with a ONNX model path to prevent loading entire huge ONNX model and encountering the issue you saw.
