### ISSUE TITLE
Getting the Output from an Intermediate Node in ONNX Model

### ISSUE THREAD

**Issue by Darshcg** [onnx/onnx#3277]
Hi,

I want to inspect the Dimensions and the output from an Intermediate Node in ONNX Model, how do I get the same?

Thanks and Regards,
Darshan

**Comment by jcwchen** [comment]
Hi @Darshcg,
In certain node you can get the output name by `model.graph.node[i].output`. Then according to this output name, you can match the input name in other `model.graph.node`, and get its dimensions if any. Thanks.

**Comment by Darshcg** [comment]
Hi @jcwchen,
Thanks for your response.

Actually, my Question was meant like: How to get the output from an Intermediate node after passing the Inputs?
For, Example: I want to get the Outputs(Tensor Values) from the Einsum node(as shown in the Pic below) on passing the inputs.
![Screenshot from 2021-02-14 02-14-03](https://user-images.githubusercontent.com/48723743/107861301-089d1380-6e6b-11eb-83e1-d2fa2b562364.png)


Thanks

**Comment by jcwchen** [comment]
Not sure whether I understand your question. You could use `onnx.shape_inference.infers_shape` to get the inferred shape of each node, but it is done by graph-level. (You can create a graph only includes single node) Or, if you seek for the exact tensor value, I think you need to use onnxruntime.

**Comment by jcwchen** [comment]
I assume this question has been resolved. Please reopen it if you still have question. Thank you!

**Comment by warren-lei** [comment]
> Hi @jcwchen,
> Thanks for your response.
> 
> Actually, my Question was meant like: How to get the output from an Intermediate node after passing the Inputs?
> For, Example: I want to get the Outputs(Tensor Values) from the Einsum node(as shown in the Pic below) on passing the inputs.
> ![Screenshot from 2021-02-14 02-14-03](https://user-images.githubusercontent.com/48723743/107861301-089d1380-6e6b-11eb-83e1-d2fa2b562364.png)
> 
> Thanks

I have the same requirement, how do you resolve this problem?

**Comment by zhonhel** [comment]
I found a solution at here, can any one try this ?  [link](http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#compute-intermediate-outputs)

**Comment by Tomclancysi** [comment]
Use onnx python module to add middle layer to outputs. 
```
import onnx
model = onnx.load(r'model_path.onnx')
inter_layers = ['349', '368', '369', '374', '375', '355', '376', '427', '478', '733', '819', '972', '1125'] # output tensor names
value_info_protos = []
shape_info = onnx.shape_inference.infer_shapes(model)
for idx, node in enumerate(shape_info.graph.value_info):
    if node.name in inter_layers:
        print(idx, node)
        value_info_protos.append(node)
assert len(value_info_protos) == len(inter_layers)
model.graph.output.extend(value_info_protos)  #  in inference stage, these tensor will be added to output dict.
onnx.checker.check_model(model)
onnx.save(model, './test.onnx')
```

**Comment by fengyuentau** [comment]
> Use onnx python module to add middle layer to outputs.
> 
> ```
> import onnx
> model = onnx.load(r'model_path.onnx')
> inter_layers = ['349', '368', '369', '374', '375', '355', '376', '427', '478', '733', '819', '972', '1125'] # output tensor names
> value_info_protos = []
> shape_info = onnx.shape_inference.infer_shapes(model)
> for idx, node in enumerate(shape_info.graph.value_info):
>     if node.name in inter_layers:
>         print(idx, node)
>         value_info_protos.append(node)
> assert len(value_info_protos) == len(inter_layers)
> model.graph.output.extend(value_info_protos)  #  in inference stage, these tensor will be added to output dict.
> onnx.checker.check_model(model)
> onnx.save(model, './test.onnx')
> ```

Greate! But when I run your script on my model, it complains:
```
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing
```

**Comment by ykk648** [comment]
Add a node to output , model can only run on CPU EP instead of CUDA EP
```
2024-05-11 15:12:27.035304912 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 9 Memcpy nodes are added to the graph torch_jit for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-05-11 15:12:27.039150773 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-05-11 15:12:27.039158541 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
```
