### ISSUE TITLE
Exporting pytorch model to onnx increases the model size

### ISSUE THREAD

**Issue by thehetpandya** [onnx/onnx#3278]
Hi, I'm trying to convert some models from huggingface as follows:

ktrapeznikov/albert-xlarge-v2-squad-v2
albert-xlarge-v1
albert-xlarge-v2
The common issue with exporting all these models is that I get an exception that the protobuf size increases to more than 2gb while all these are less than 800mb. When I use the use_external_data_format=True flag, the exported model files(network layers as I searched in other issues) sum up to in gbs of size. For eg, the model ktrapeznikov/albert-xlarge-v2-squad-v2 is sized to 210mb but when I convert it to onnx using use_external_data_format flag, the model size sums up to 4gb. 

## Code example
```
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

model_name = "ktrapeznikov/albert-xlarge-v2-squad-v2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForQuestionAnswering.from_pretrained(model_name)
model.eval()
question = "what is google specialization"
text = "Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware."
encoding = tokenizer.encode_plus(question, text)
input_ids, attention_mask, token_type_ids = encoding["input_ids"],encoding["attention_mask"], encoding["token_type_ids"]

input_ids = torch.tensor([input_ids])
attention_mask = torch.tensor([attention_mask])
token_type_ids = torch.tensor([token_type_ids])

torch.onnx.export(
    model,
    (input_ids,attention_mask, token_type_ids),
    f"{model_name}.onnx",
    input_names = ['input_ids','attention_mask', 'token_type_ids'],
    output_names = ['qa_outputs'], 
    opset_version=12, ##opset has to be set to 12
    do_constant_folding=True,
    use_external_data_format=True,
    dynamic_axes = {
        'input_ids' : {0: 'batch', 1: 'sequence'},
        'attention_mask' : {0: 'batch', 1: 'sequence'}, 
        'token_type_ids' : {0: 'batch', 1: 'sequence'}, 
        'qa_outputs': {0: 'batch'}
    }
)
```
![image](https://user-images.githubusercontent.com/55797177/106251673-4549f780-623b-11eb-8735-9bf90f18bf4e.png)
![image](https://user-images.githubusercontent.com/55797177/106251758-63aff300-623b-11eb-81e7-defe45429eaf.png)

## System Info
PyTorch version: 1.7.0+cu101
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.8.1+cu101

Any help would be much appreciated.
Thanks in advance!

**Comment by jcwchen** [comment]
Hi @thehetpandya,
I am not familiar with huggingface, but according to https://github.com/huggingface/transformers/issues/8869, there might be something can be optimized during the conversion (pytorch to ONNX). I saw you have opened an issue about this in pytorch as well. There is the better place to get help from the conversion team (pytorch.onnx.export). Thank you.

**Comment by thehetpandya** [comment]
Hi @jcwchen, 
Yes I went through the issue you mentioned. And also I've opened a similar issue in both the places as well if I could find a solution from either of them. I am new to pytorch, but I tried optimizing the torch model without exporting to onnx. That worked but sadly only exporting to onnx seems to have a problem. I shall try connecting with them. Thanks for the efforts!

**Comment by tianleiwu** [comment]
ALBert model has shared weights among layers. I guess torch.onnx.export outputs the weights to different tensors so model size becomes larger.

It is easy to write a python script to remove duplication of weights, and reduce model size. For example, comparing each pair of initializers, when they are the same, just remove one initializer, and update all reference of it to the other initializer.

**Comment by prasanthpul** [comment]
@spandantiwari for torch.onnx.export. should this be filed as issue in pytorch repo?

**Comment by spandantiwari** [comment]
@prasanthpul - I see a similar issue opened in the PyTorch repo https://github.com/pytorch/pytorch/issues/51343, so may be we can close this issue here and track the item in PyTorch repo.

**Comment by thehetpandya** [comment]
Hi, I shall close this issue and look for support from the pytorch team.

**Comment by thehetpandya** [comment]
Hi @tianleiwu, I tried as you stated, but could not succeed. Could you guide me? Or if you have a python script for the same.

**Comment by tianleiwu** [comment]
@thehetpandya , you can refer to [OnnxModel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/onnx_model.py). Pseudo code is like
```
from onnxruntime.transformers.onnx_model import OnnxModel
model=onnx.load(path)
onnx_model=OnnxModel(model)
count = len(model.graph.initializer)
same = [-1] * count
for i in range(count - 1):
  if same[i] >= 0:
	continue
  for j in range(i+1, count):
     if has_same_value(model.graph.initializer[i], model.graph.initializer[j]):
	same[j] = i

for i in range(count):
   if same[i] >= 0:
        onnx_model.replace_input_of_all_nodes(model.graph.initializer[i].name, model.graph.initializer[same[i]].name)

onnx_model.update_graph()
onnx_model.save_model_to_file(output_path)
```

**Comment by thehetpandya** [comment]
@tianleiwu Oh god! Never realized this was that easy! Thank you so much!
