### ISSUE TITLE
Export ONNX model with tensor shapes included

### ISSUE THREAD

**Issue by gyenesvi** [onnx/onnx#3281]
# Ask a Question

### Question
Is it possible to export ONNX models with tensor shapes included so that shape inference need not be run when importing a model? How to do that for example from PyTorch?

### Further information
Relevant Area: shape_inference

When a model is exported with ops not present in ONNX included in them (torch.onnx.export(operator_export_type=ONNX_FALLTHROUGH)), shape inference cannot be run on the resulting ONNX model.

- Is this issue related to a specific model?  
No

### Notes
It would also be a possible solution if a shape inference function could be injected into the Python shape inference code (not C++).

**Comment by jcwchen** [comment]
Hi @gyenesvi,
Not sure whether I understand the question. Are you saying something like to prevent shape_inference error, provide tensor shape while exporting a pytorch model with unsupported operators? I don't think it will work, because ONNX/ONNXRuntime need to know the schema of ONNX operator. To solve unsupported operator problem, please check here: https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md. Thank you!

**Comment by gyenesvi** [comment]
Hi @jcwchen,

Thanks for the reply. Yes I am saying exactly like that. I don't want to use ONNXRuntime for inference, that's not the only way to use ONNX. What I need is the ability to import an ONNX model into a proprietary inference engine by converting it into an internal format for example. I understand that I would loose the ability to run the ONNX checker upon import, let's say I could live with that. The ONNX model can be read even with unknown ops, only the shapes are missing, which would be required for the conversion.
I have already checked the link that you provided. It does not provide a robust solution for all ops. Solutions that would require recompiling C++ code or adding some method into PyTorch code are out of the question, as this would be part of a toolchain, that would be run by other people, who would be running the stock PyTorch/ONNX packages.

**Comment by jcwchen** [comment]
Thank you for providing your use case and detailed explanation. Basically, ONNX is a spec that supports many frameworks. IMO, as ONNX's perspective, every operator needs to be well-defined and therefore it can be utilized by other frameworks.

Still, I think this question is for the converter (pytorch.onnx.export) to provide an option to disable shape_inference and not fail if encountering an unsupported operator during the conversion. I would suggest you could open an issue to request this in pytorch's repo. Thanks.

**Comment by gyenesvi** [comment]
Not sure I understand why shape_inference needs to be disabled during export. The export does not fail, that's what operator_export_type=ONNX_FALLTHROUGH is for. I believe it does not even run ONNX shape inference, as it is generating the ONNX model as output (the one thing I could turn on for export is the ONNX checker to check the resulting model, that would fail I guess, but it's off by default).

So more specifically my questions are:
- Does ONNX format support models with all tensor shapes baked in? If yes, only then is the next step to make sure that the exporter is able to export models in that way. I guess you are not aware of such an ability in the PyTorch exporter, I'll ask that in the PyTorch repo, but first I'd like to know if it's at least theoretically possible.
- If you say all operators should be well defined, what is the way to make custom operators well defined without touching the ONNX code? Does ONNX format support something like that?

**Comment by jcwchen** [comment]
Sorry that I did not aware of ONNX_FALLTHROUGH. Yes it seems to me that it should meet your requirement, but as you mentioned, it's better to confirm it in pytorch's repo.

1. https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs You can store shape/type information of tensors into `your_model.graph.value_info` directly.
2. Actually `onnx.helper.make_node` won't use onnx.shape_inference so you can create any kind of operator you want as long as you don't use onnx.shape_inference or ORT.

**Comment by gyenesvi** [comment]
Okay, thanks for the info.

**Comment by un-knight** [comment]
@gyenesvi Do you find a solution? I meet the same problem as you.

**Comment by gyenesvi** [comment]
@un-knight No I didn't, so I did not pursue this direction further. While it may be technically possible, the existing tools don't do it for me.
