### ISSUE TITLE
use of ONNX logo

### ISSUE THREAD

**Issue by bsannerud** [onnx/onnx#3285]
I work at IBM  in marketing and we would like to include the ONNX logo in a chart where we discuss the use of ONNX for AI
 The presentation would be used with customers. May we have permission? My contact is sannerud@us.ibm.com

**Comment by prasanthpul** [comment]
Followed up offline

**Comment by mathworksjpmarketing** [comment]
Hello. Similar to the inquiry above, MathWorks would like to use ONNX logo in our customer-facing materials. Could we have a permission? My email address is yosadaatmathworks.com. Please replace "at" with "@". Thanks.
