### ISSUE TITLE
onnx is running the whole graph ?

### ISSUE THREAD

**Issue by argman** [onnx/onnx#3294]
assume we have a input and two output (output_0, output_1) , they are all depend on the input, but we only need to get output_0, so when do running, onnx runtime will run both output_0 and output_1 then fetch out output_0 ? i think running the graph part of getting output_0 is enough ?

**Comment by TMVector** [comment]
Duplicate of https://github.com/microsoft/onnxruntime/issues/6790

**Comment by argman** [comment]
anyone use python can see https://github.com/microsoft/onnxruntime/issues/6790#issuecomment-785236442 to get a workaround
