### ISSUE TITLE
transformers albert export onnx error

### ISSUE THREAD

**Issue by jianqianzhou** [onnx/onnx#3295]
# Ask a Question
Albert transformers model export onnx
### Question
RuntimeError: Exporting the operator einsum to ONNX opset version 11 is not supported. Support for this operator was added in version 12, try exporting with this version.

### Further information
`import torch
from transformers import BertTokenizer,AlbertModel,BertConfig,BertModel
import numpy

pretrained = './albert_chinese_base'
tokenizer = BertTokenizer.from_pretrained(pretrained)
model = AlbertModel.from_pretrained(pretrained)
config = BertConfig.from_pretrained(pretrained)
inputtext = "今天心情情很好啊，买了很多东西，我特别喜欢，终于有了自己喜欢的电子产品，这次总算可以好好学习了"
max_length = 128
tokenized_text=tokenizer.encode_plus(inputtext, add_special_tokens = True, # add [CLS], [SEP]
                                 max_length = max_length, # max length of the text that can go to BERT
                                 pad_to_max_length = True, # add [PAD] tokens
                                 return_attention_mask = True, # add attention mask to not focus on pad tokens
                                 return_tensors="pt")
outputs=model(input_ids=tokenized_text["input_ids"], token_type_ids=tokenized_text["token_type_ids"], attention_mask=tokenized_text["attention_mask"])
bert_output = outputs[1]
weight = torch.tensor(numpy.loadtxt("weight.txt"),dtype=torch.float32)
bert_output = torch.matmul(bert_output, weight)

from pathlib import Path
from transformers.convert_graph_to_onnx import convert
from transformers import *
#convert(framework="pt", model=model, tokenizer=tokenizer, output=Path("onnx/albert-chinese-base.onnx"), opset=12)

def export_onnx_model(model, tokenizer, onnx_model_path):
    with torch.no_grad():
        inputs = {'input_ids':      torch.ones(1,128, dtype=torch.int64),
                    'attention_mask': torch.ones(1,128, dtype=torch.int64),
                    'token_type_ids': torch.ones(1,128, dtype=torch.int64)}
        outputs = model(**inputs)

        symbolic_names = {0: 'batch_size', 1: 'max_seq_len'}
        torch.onnx.export(model,                                            # model being run
                    (inputs['input_ids'],                             # model input (or a tuple for multiple inputs)
                    inputs['attention_mask'],
                    inputs['token_type_ids']),                                         # model input (or a tuple for multiple inputs)
                    onnx_model_path,                                # where to save the model (can be a file or file-like object)
                    opset_version=11,                                 # the ONNX version to export the model to
                    do_constant_folding=True,                         # whether to execute constant folding for optimization
                    input_names=['input_ids',                         # the model's input names
                                'attention_mask',
                                'token_type_ids'],
                    output_names=['output'],                    # the model's output names
                    dynamic_axes={'input_ids': symbolic_names,        # variable length axes
                                'attention_mask' : symbolic_names,
                                'token_type_ids' : symbolic_names})
        #logger.info("ONNX Model exported to {0}".format(onnx_model_path))

export_onnx_model(model, tokenizer, "onnx/albert-chinese-base.onnx")`

torch              1.6.0+cpu
torchvision        0.7.0+cpu
onnx               1.8.1
onnxruntime        1.6.0
onnxruntime-tools  1.6.0
transformers       3.0.2

### Notes
RuntimeError: Exporting the operator einsum to ONNX opset version 11 is not supported. Support for this operator was added in version 12, try exporting with this version.

**Comment by jianqianzhou** [comment]
And when modify opset_version=11 to opset_version=12,  convert onnx format, but quantized onnx, the output compare to origin is difference intensity, but modify AlbertModel to BertModel, the output is correct.
tensor([[ -4.9610,  -9.1387, -12.4154,  -2.8640,  -2.9177, -14.1545,  -0.7817,
          -1.6522,  -8.1659,  12.1208]], grad_fn=<MmBackward>)

`from transformers.convert_graph_to_onnx import quantize
from pathlib import Path
# Transformers allow you to easily convert float32 model to quantized int8 with ONNX Runtime
quantized_model_path = quantize(Path("albert.opt.onnx"))

# Then you just have to load through ONNX runtime as you would normally do
quantized_model = create_model_for_provider(quantized_model_path.as_posix(), "CPUExecutionProvider")

# Warm up the overall model to have a fair comparaison
outputs = quantized_model.run(None, inputs_onnx)
outputs = torch.tensor(outputs[1])
bert_output = torch.matmul(outputs, weight)
print(bert_output)

# Benchmark PyTorch quantized model
time_buffer = []
for _ in trange(100, desc=f"Tracking inference time on CPUExecutionProvider with quantized model"):
    with track_infer_time(time_buffer):
        outputs = quantized_model.run(None, inputs_onnx)

# Store the result
results["ONNX CPU Quantized"] = OnnxInferenceResult(
    time_buffer,
    quantized_model_path
)
import numpy as np
# Compute average inference time + std
time_results = {k: np.mean(v.model_inference_time) * 1e3 for k, v in results.items()}
#time_results_std = np.std([v.model_inference_time for v in results.values()]) * 1000
print(time_results.keys())
print(time_results.values())`

tensor([[ -5.6812, -11.3905, -21.9474,   0.0971,  -8.1226, -19.2604,   1.3498,
          -9.9139, -16.5754,   5.7205]])

**Comment by jcwchen** [comment]
Hi @jianqianzhou,
For the first question, yes, you can specify opset_version during the conversion.

ORT does support AlbertModel/BertModel. Could you try to not do quantization for inference and see whether the output still extensively differ? Thank you.

**Comment by jianqianzhou** [comment]
> Hi @jianqianzhou,
> For the first question, yes, you can specify opset_version during the conversion.
> 
> ORT does support AlbertModel/BertModel. Could you try to not do quantization for inference and see whether the output still extensively differ? Thank you.

the onnx and optimizd onnx output is the same and correct，but quantized onnx output is different from optimized and origin onnx，I use quantized onnx like this  ‘quantized_model_path = quantize(Path("albert.opt.onnx"))’ 。

**Comment by jcwchen** [comment]
Thanks for the info. It looks to me that the issue might happen during the quantization runtime. I saw you have opened an issue under onnxruntime and there is the proper place to track this issue. Close now. Please reopen it if you have other ONNX issue. Thank you!
