### ISSUE TITLE
I want the BN parameter could be changed with inputdata in inference, how to?

### ISSUE THREAD

**Issue by AmigoCDT** [onnx/onnx#3298]
In Pytorch inference, we set `model.eval()` to set BN parameters as constant. But in GAN model, the `model.eval()` could not get good result, we hope the BN parameter could be influenced by input data, but not a constant.

So, I want to know how to get similar mode like `model.train(False)` in ONNX, i.e. do not set the BN parameters as constant?

Thanks.

**Comment by jcwchen** [comment]
Hi @AmigoCDT,
I don't quite get it -- Did you mean `onnxruntime.training`, ORT inference or something else? Thanks.

**Comment by jcwchen** [comment]
Since we haven't received any response, close this issue now. Please reopen it if you still have question. Thanks!
