### ISSUE TITLE
Custom data type for model

### ISSUE THREAD

**Issue by josemibnf** [onnx/onnx#3299]
Is it possible to take a protobuf object as a type of variable of a model?

I intend to compare a set of these objects (to know which is the one that gives the best performance based on their attributes), for this I am applying linear regression to the attributes of each of these objects.

My question is if an ONNX model can contain the specification of each object as if it were another dimension (apart from the attributes).

**Comment by jcwchen** [comment]
Hi @josemibnf,
Not sure whether I get you question. I think you can consider the ONNX model as onnx.ModelProto python object and combine other desired attributes with it. Thanks.

**Comment by jcwchen** [comment]
I assume this question has been resolved. Please reopen it if you still have question. Thank you!
