### ISSUE TITLE
torch->pytorch->caffe2

### ISSUE THREAD

**Issue by shamangary** [onnx/onnx#33]
Is it possible using torch model and load it by pytorch and then turn it into caffe2 model?

**Comment by houseroad** [comment]
I think torch does not support ONNX right now.

According to the discussion here: https://discuss.pytorch.org/t/convert-import-torch-model-to-pytorch/37, there are two ways to turn a torch into pytorch:

1) Serialize the torch model, and deserialize it in pytorch using load_lua. The model is imported as legacy modules. So it won't work with ONNX exporter in pytorch.

2) There are some scripts which may be able to port the code to pytorch, such as https://github.com/clcarwin/convert_torch_to_pytorch.

Once you get pytorch serialized model, you can load it and export in ONNX format. Caffe2 can load ONNX models.

**Comment by soumith** [comment]
closing the issue because we dont plan to support any other new codepaths other than what @houseroad commented.
