### ISSUE TITLE
Inverse operator

### ISSUE THREAD

**Issue by robinvanemden** [onnx/onnx#3300]
### Question
Would it be an option to (re)include the Inverse operator? 

It was actually already (partly?) implemented last year:

https://github.com/onnx/onnx/pull/2578
https://github.com/onnx/onnx/pull/2747

It seems that the original commit was reversed because it had not been checked thoroughly enough - is that correct?

**Comment by shijianjian** [comment]
Any updates on this?

**Comment by olesalscheider** [comment]
We are also interested in this. Maybe @codemzs can comment on the plans since he reverted it?

**Comment by hwangdeyu** [comment]
Hi @codemzs, there are several issues include this one requesting this op. Does it have any plan to support this op again?

**Comment by AditiDeepak15** [comment]
Hi @codemzs, I am working on conversion of Pytorch model to ONNX and the Pytorch model code makes use of the torch.inverse operation. I am unable to export to ONNX due to this operation, so I wanted to understand why the inverse operator was reverted.  Is there a workaround for this as this is blocking my project?

**Comment by majacaci00** [comment]
Running into the same problem... ```RuntimeError: Exporting the operator binary_cross_entropy to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.``` the same occurs when I opset_version=10...

**Comment by RobinBaruffa** [comment]
Hi, any updates on this issue ? Did anyone find a workaround ?

**Comment by justinchuby** [comment]
Useful for computer vision. Cc @liqunfu

**Comment by justinchuby** [comment]
Ref http://www.xavierdupre.fr/app/mlprodict/helpsphinx/onnxops/onnx_commicrosoft_Inverse.html

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/issues/3839 can be created instead.

**Comment by justinchuby** [comment]
Closed in favor of https://github.com/onnx/onnx/issues/3839
