### ISSUE TITLE
Exporting the operator log10 to ONNX opset version 9,10, 11, 12 is not supported

### ISSUE THREAD

**Issue by myerznkanyan** [onnx/onnx#3301]
# log10

**Comment by jcwchen** [comment]
Hi @myerznkanyan,
It should be a converter issue. You can see the supported ONNX operators here in pytorch: https://pytorch.org/docs/stable/onnx.html#supported-operators. And log10 is not one of them. Please open an issue under pytorch to request the support of this operator. Thank you.

**Comment by akurmustafa** [comment]
Hi @myerznkanyan, I don't now if this still applicable to your case but, as a temporary workaround by using "0.4342*torch.log(x)" in place of "torch.log10(x)" (0.4342 = log10(euler)) I could convert model to ONNX format." Oddly PyTorch supports torch.log operation for ONNX conversion.
