### ISSUE TITLE
why do transformer onnx model perform slower than pytorch model for longer sequence length?

### ISSUE THREAD

**Issue by Ki6an** [onnx/onnx#3302]
hey, I've exported the huggingface's T5 model to onnx, using `torch.onnx.export() ` and ran it on onnxruntime with the following optimization.

```
options = SessionOptions()
options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL
options.execution_mode = ExecutionMode.ORT_PARALLEL 
options.intra_op_num_threads = 1

# options.execution_order = ExecutionOrder.DEFAULT
# options.inter_op_num_threads = 0
# options.enable_profiling = True
# options.use_deterministic_compute = True 
# options.log_severity_level = 0

provider =  'CPUExecutionProvider' 

decoder_sess = InferenceSession(str(path_decoder), options, providers=[provider] )
encoder_sess = InferenceSession(str(path_encoder), options, providers=[provider] ) 
```
the converted t5 onnx model runs 2-2.5 times faster than the PyTorch model for smaller sequence length under (100 tokens) and beam num (<3). 

however, the onnx model runs slower than the PyTorch model for longer sequence length and higher beam-search number.
what might be causing the model to slow down? is it just the t5 model or do all transformer onnx models perform poorly on large batch size and sequence length?

any suggestions on improving the model speed would be appreciated.

**Comment by jcwchen** [comment]
Hi @Ki6an,
This performance issue happens in Runtime. Please open an issue under ONNXRuntime repo to get the best help from transformer's expert there. Thank you!

**Comment by Ki6an** [comment]
@jcwchen  thank you for the advice, will close this issue.

**Comment by askhade** [comment]
Closing this issue here. Please open the issue in onnxruntime repo: https://github.com/microsoft/onnxruntime/issues
