### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 1, 7, 7], expected input[1, 64, 8, 64, 114] to have 3 channels, but got 64 channels instead

### ISSUE THREAD

**Issue by Darshcg** [onnx/onnx#3303]
Hi ONNX Team,

I am converting the Slowfast pytorch model to ONNX model using` torch.onnx.export()`.
During Conversion, I am getting an error as: **RuntimeError: Given groups=1, weight of size [64, 3, 1, 7, 7], expected input[1, 64, 8, 64, 114] to have 3 channels, but got 64 channels instead**.
Having said that, the pytorch model Inference is working fine, but do no why it is throwing above error during .pt to .onnx conversion.

Can you please assist me to solve this error? Would be a great help from yourside.

**Environment**:
Pytorch version: 1.6.0
Torchvision: 0.7.0
ONNX version: 1.7.0

One Note: Model is Slowfast. The input shape is: input0: (1,3,8,256,455), input1: (1,3,32,256,455). input0 is Slow pathway, and input1 is Fast pathway.

Thanks,
Darshan

**Comment by jcwchen** [comment]
Hi @Darshcg,
This error happened in the converter. I saw you opened an issue under pytorch and that is the better place to track this issue. Close now. Please reopen it if you have other ONNX related issues. Thank you.
