### ISSUE TITLE
What does "expect" function do in onnx?

### ISSUE THREAD

**Issue by jwj04ok** [onnx/onnx#3304]
# Ask a Question

### Question
Explain your question here.
I follow the examples in each operator in https://github.com/onnx/onnx/blob/rel-1.6.1/docs/Operators.md#add
There is an expect function at the end of each example. 
May I know what is the usage of this function? I check the source code. It creates graph and model but return None. Does it mean that it just checks whether there are some issues? When no error occurs, it means everything is fine?  

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @jwj04ok,
Yes, you are right. The expect function here is not doing any logic check. It's a tool to create testcases by numpy for other runtime framework to verify their runtime logic. In the document, it just provides an example to let user know what the input/output and node are for operators.
