### ISSUE TITLE
Wrong classification of 'protobuf' as 'purebasic' on github linguist

### ISSUE THREAD

**Issue by brymer-meneses** [onnx/onnx#3307]
ONNX uses Protobuf for `.pb` files but PureBasic is being assigned by GitHub linguist to these files.

This can be overridden by adding `.gitattributes` to the repository to tell GitHub linguist to classify `.pb` files as ProtoBuf not PureBasic.

Or, we can just remove `.pb` files from appearing at the Languages section of the repository, since ProtoBuf is not a programming language. This also can be done using `.gitattributes`.

**Comment by jcwchen** [comment]
Hi @brymer-meneses,
https://github.com/github/linguist/issues/3816
So linguist didn't fix it? Actually I can repro this... Feel free to submit a PR to workaround this, but it seems to me that it is something needs to be fixed from linguist side. Thank you.

**Comment by brymer-meneses** [comment]
Hello @jcwchen 

We can use `gitattributes` to directly tell linguist to classify `.pb` into ProtoBuff or we can just remove it entirely from the language section.

**Comment by jcwchen** [comment]
I am OK with it, but I don't know other folks' thought. IMO, I think ONNX should be compact and simple so it would be good if it can be fixed from their side. Meanwhile, I will open an issue in linguist for this question. Thank you for bringing up this.

**Comment by brymer-meneses** [comment]
I will submit a PR soon that will override linguist’s file classification.

**Comment by brymer-meneses** [comment]
1.

**Comment by brymer-meneses** [comment]
Hello @jcwchen 
Can you review my PR?
