### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by aviol2** [onnx/onnx#3310]
# New Operator

### Describe the operator
Why is this operator necessary? What does it accomplish?

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?

### Notes
Any additional information

**Comment by jcwchen** [comment]
Hi @aviol2,
Could you elaborate what the Me operator is? Thanks.

**Comment by jcwchen** [comment]
Since we haven't received response, close this issue now. Please reopen it if you still have question. Thanks.
