### ISSUE TITLE
mxnet to onnx conversion- 1 model works correctly, 1 model doesn't

### ISSUE THREAD

**Issue by chinmayjog13** [onnx/onnx#3311]
# Ask a Question
One model converted from mxnet to onnx works correctly while another doesn't.

### Question
I have two models, same architecture. The only difference between them is number of neurons in last layer, and the mxnet version they were trained with.
I converted both to onnx, and resolved common mxnet to onnx conversion issues like reshaping Relu layer, and removing spatial attribute from BatchNorm layer. One of the models works correctly, but the other doesn't. What can be causing this issue?

### Further information
-Info for model that is correctly converted-
mxnet version 1.6.0
intermediate onnx version for mxnet to onnx conversion- 1.3.0
Onnx version for resolving common issues mentioned above- 1.6.0
Num hidden units- 512
Default onnx opset version

-Info for model that is not correctly converted-
mxnet version 1.7.0
intermediate onnx version for mxnet to onnx conversion- 1.3.0
Onnx version for resolving common issues mentioned above- 1.6.0
Num hidden units- 500
Default onnx opset version

### Notes
```
#reshape relu layer
import mxnet as mx
import onnx
from onnx import checker
from mxnet.contrib import onnx as mx_onnx
import numpy as np


print('Mxnet version: ', mx.__version__)
print('Onnx version is: ', onnx.__version__) #models converted with mxnet can only be loaded with onnx <=1.3.0

sym, arg_params, aux_params = mx.model.load_checkpoint('model', 0)
new_arg_params = {}
for k, v in arg_params.items():
    if 'relu' in k:
        v = v.reshape(1, -1, 1, 1)
    new_arg_params[k] = v

save_prefix = 'model_w_reshaped_relu'
mx.model.save_checkpoint(save_prefix, 0, sym, new_arg_params, aux_params)

input_shape = (1,3,112,112)
onnx_file = 'model_w_reshaped_relu.onnx'

sym = 'model_w_reshaped_relu-symbol.json'
params = 'model_w_reshaped_relu-0000.params'

converted_path = mx_onnx.export_model(sym, params, [input_shape], np.float32, onnx_file, verbose=True)

model_proto = onnx.load_model(onnx_file)
checker.check_graph(model_proto.graph)
```

```
#remove spatial attribute from Batchnorm layer
import onnx
from onnx import helper, checker
from onnx import GraphProto

print('Onnx version is: ', onnx.__version__)

onnx_model = onnx.load_model('model_w_reshaped_relu.onnx')
print('Loaded model')
inputs = onnx_model.graph.input
outputs = onnx_model.graph.output
name = onnx_model.graph.name
node_def = []
for i in range(len(onnx_model.graph.node)):
    node = onnx_model.graph.node[i]
    if node.op_type == "BatchNormalization":
        # print(node, '\n')
        # break
        for d in node.attribute:
            if d.name == 'spatial':
                continue
            elif d.name == 'epsilon':
                epsilon = d.f
            else:
                momentum = d.f
        
        temp_node = helper.make_node(node.op_type, inputs=node.input, outputs=node.output, name=node.name, epsilon=epsilon, momentum=momentum)
        # print(temp_node)
        onnx_model.graph.node.remove(node)
        onnx_model.graph.node.insert(i, temp_node)
        node_def.extend([temp_node])
    
checker.check_model(onnx_model)
print('model is checked')

onnx.save(onnx_model, 'model_converted_correctly.onnx')
```

**Comment by jcwchen** [comment]
Hi @chinmayjog13,
It's a known issue in the converter (mxnet-onnx): https://github.com/apache/incubator-mxnet/issues/14589. Spatial attribute has been removed since [BatchNormalization-9](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#batchnormalization-9) in ONNX. Please track this issue under incubator-mxnet. Thanks.

**Comment by jcwchen** [comment]
Thank you for providing more details. If the gap happened in the same architecture, it looks to me that something wrong during the conversion. Since I am not familiar with MXNet and it is still using a pretty old version of ONNX (1.3), I would suggest you open an issue under https://github.com/apache/incubator-mxnet to get the best help.

**Comment by jcwchen** [comment]
Closed due to inactivity. If you still have question related to mxnet to ONNX, please raise an issue under incubator-mxnet. Thanks!
