### ISSUE TITLE
celu get wrong result when alpha is negtive

### ISSUE THREAD

**Issue by zjusaga** [onnx/onnx#3313]
# Bug Report

### Describe the bug
celu get wrong result when alpha is negtive

### System information
- OS Platform and Distribution (Linux Ubuntu 16.04): 
- ONNX version (1.7):  
- Python version: 3.7.5
- 
### Reproduction instructions
when alpha=-0.5,   x = -0.49682534,   celu got -0.49682534,  but according to the  formula， the result should be -0.850585938

**Comment by jcwchen** [comment]
Hi @zjusaga,
How did you get the result? Use Runtime framework like ONNXRuntime?

**Comment by zjusaga** [comment]
> Hi @zjusaga,
> How did you get the result? Use Runtime framework like ONNXRuntime?

yes, ONNXRuntime

**Comment by jcwchen** [comment]
Then, please open an issue in ONNXRuntime about this since this inference error happened in Runtime. Thank you.

**Comment by zjusaga** [comment]
all right

**Comment by zjusaga** [comment]
ok
