### ISSUE TITLE
Confused about  AveragePool op ceil_mode attribute

### ISSUE THREAD

**Issue by blacklong28** [onnx/onnx#3314]
# Ask a Question

### Question
When I was study the AveragePool op, I am confused about the ceil_mode attr.
What I see at  [AveragePool](https://github.com/onnx/onnx/blob/master/docs/Operators.md#AveragePool)

> ceil_mode : int (default is 0)
> Whether to use ceil or floor (default) to compute the output shape.

But I notice when auto_pad is set,
it only uses ceil to compute the output shape.
Is the ceil_mode attr  only used when auto_pad is 'NOTSET'?

### Further information

- This is the python code I find to compute the output shape, the code also is only use ceil to compute output shape.  [get_output_shape](https://github.com/onnx/onnx/blob/1cbd549193661c7e9c870c4e9595144d0c6971c5/onnx/backend/test/case/node/pool_op_common.py#L24)
- I notice pytorch's op AvgPool2d have ceil_mode( [AvgPool2d,](https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html) )I guess the onnx ceil_mode attr is only used when auto_pad is 'NOTSET', and when auto_pad is not 'NOTSET',the ceil_mode default value is 1 ,is true? 

Who can help me? Thanks very much.

**Comment by jcwchen** [comment]
Hi @blacklong28,
I think Operator document is correct and the test script in ONNX you mentioned [get_output_shape](https://github.com/onnx/onnx/blob/1cbd549193661c7e9c870c4e9595144d0c6971c5/onnx/backend/test/case/node/pool_op_common.py#L24) is not updated while introducing ceil_mode. You can check the inference logic here in ONNXRunitme:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/nn/pool_attributes.h
By default, ceil_mode is 0 no matter what auto_pad is. Thanks.

**Comment by kraiskil** [comment]
For reference - I had a similar question about ceil mode in MaxPool #2971 
@jcwchen can you confirm that the onnx test scripts are wrong? Since they seem to be the de-facto acceptance tests for backends, at least I went with the script and not the documentation as the basis for my backend implementation.

**Comment by blacklong28** [comment]
@kraiskil @jcwchen 
I have read this code: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/nn/pool_attributes.h
and I find the output shape compute when auto_pad is SAME_LOWER SAME_UPPER is equal to :
ceil_or_floor(static_cast<float>(in_size + pad_needed - dilation * (kernel - 1) - 1) / stride + 1)
pad_needed = (int((in_size + stride - 1) / stride)-1)*stride+kernel-in_size
dilation = 1 for AveragePool,
output_shape =ceil_or_floor(static_cast\<float\>(**in_size** + (int((in_size + stride - 1) / stride)-1)*stride+**kernel**-**in_size** - **dilation * (kernel - 1) - 1**) / stride + 1)
= ceil_or_floor(
static_cast\<float\>(
    (    **_int( (in_size + stride - 1)  / stride 
               )_**   -1)*stride
    )/stride+1
)
= ceil_or_floor(int( (in_size + stride - 1)/stride-1)+1
=ceil_or_floor( int ( (in_size + stride - 1) / stride ) )
=floor ( (in_size + stride - 1) / stride )
= ceil((in_size + stride) / stride)
We know that int ( (in_size + stride - 1) / stride ) is a int number,
so no matter what the ceil_mode is, the output shape is int ( (in_size + stride - 1) / stride ),int() is a floor method.
And is equal to the python [get_out_shape](https://github.com/onnx/onnx/blob/1cbd549193661c7e9c870c4e9595144d0c6971c5/onnx/backend/test/case/node/pool_op_common.py#L24) function:
```python
  out_shape[i] = int(
      np.ceil(
          float(
              input_spatial_shape[i])
          / float(
              strides_spatial[i])))
```
Does it mean that when auto_pad is equal to SAME_LOWER and SAME_UPPER, no matter what the value of ceil_mode is, the output_shape calculation is independent of ceil_mode?

**Comment by jcwchen** [comment]
HI @kraiskil @blacklong28,
Sorry for the late reply. We are still discussing which behavior is expected while using audo_pad and ceil_mode at the same time. IMO, the implementation in ORT makes more sense to me because ceil_mode should be not silent in any condition. Even if ceil_mode does not apply to auto_pad, then I think ONNX should at least forbid users to use them simultaneously to avoid confusion.

We will update here once @onnx/sig-operators has finalized the decision. It is definitely something needs to be clear in the document/ONNX test code. Thank you for bringing this up!

**Comment by jcwchen** [comment]
Reopen it since this issue hasn't been resolved yet.
