### ISSUE TITLE
support for stateful = True in LSTM, GRU

### ISSUE THREAD

**Issue by aawce** [onnx/onnx#3315]
# Feature Request

### System information
ONNX version (you are using): 1.7

### What is the problem that this feature solves?
Many key applications require stateful=true for LSTM, GRU and Keras+others have this field.  We request onnx support this field in the LSTM and GRU nodes.  I had seen a previous request for this but it was closed.  If the training extension for stateful is the recommended feature or workaround, please explain how keras2onnx can use it to include stateful capability in the onnx model.  Then we would like to see onnxruntime use this too.

### Describe the alternatives you have considered
We've heard about an onnx training extension that adds stateful to LSTM and GRU, but we need more information on how keras2onnx conversion can use this.

The 2nd alternative is to add our own metadata fields to the onnx somehow to indicate the statefulness of each recursive node, and based on this, the runtime implementation will somehow need to pass initial_h and collect Y_h from each recursive node that is stateful=true.

### Describe the feature
Why is this feature necessary?   It allows seamless support of stateful=true from Keras to runtimes (specifically onnxruntime in our case). And these are very common in real-time edge applications.

### Will this influence the current api?
If yes, how?  No, we don't think so.

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*):   backend, best practices, converters, version_converter, operators, test

### Are you willing to contribute it (Y/N):
If someone points us in the right direction and we have the skills, yes we'd be happy to contribute.

### Notes
Any additional information: 
See keras-onnx discussion about this, basically stating that onnx needs to support stateful: https://github.com/onnx/keras-onnx/issues/676

Thanks!

**Comment by jcwchen** [comment]
Similar feature request to https://github.com/onnx/onnx/issues/3190

**Comment by david-macleod** [comment]
I am also keen to contribute to a solution for this. Does the ONNX project have any existing plans to support "stateful" models going forward, or any objections as to why this should not be supported?

**Comment by peiwenhuang27** [comment]
Hi, similar question here. I am also looking for ways for ONNX to support stateful LSTM that will be useful for real-time edge application, is the feature enhancement currently being worked on?

**Comment by aawce** [comment]
Hi,

This is still needed - how can we help move this forward? This should be relatively easy.

Thks

**Comment by garymm** [comment]
ONNX is currently purely functional and implementations such as ONNX Runtime depend on this for how they deal with threading, optimizations, etc. Therefore this would be a major change.

Regarding the stateful training extensions: We don't know of any implementation of those extensions, so it would not be useful to define an operator that relies on those extensions.

Currently the model has to handle the state by adding inputs and outputs which the model user handles and feeds back to the model. This paradigm makes things harder for model producers (converters) but changing the ONNX standard to allow stateful nodes would be extremely disruptive, and there are many successful uses of GRU and LSTM without this, so we're not planning on implementing this.

(Also keras-onnx is no longer being developed. Maybe tensorflow-onnx can convert the stateful LSTM properly?)

If you'd like to make a more detailed case for why this is needed, feel free to reply here or to attend an Operators Special Interest Group (SIG) meeting.
