### ISSUE TITLE
ConvInteger backend test data missing

### ISSUE THREAD

**Issue by kraiskil** [onnx/onnx#3321]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug
[ConvInteger description](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger) has two examples. With and without padding.
In the [backend test data](https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node), there is only one - test_convinteger_with_padding folder.

### System information
relevant on all

### Reproduction instructions
none needed 

### Expected behavior
Both versions described in the documentation exist in the backend tests.

### Notes
none

**Comment by askhade** [comment]
Thanks for reporting this! For the time being you can work around this by generating the test data using the cmd_tools script as follows:
From onnx root dir you can run:
python onnx\backend\test\cmd_tools.py generate_data --op_type ConvInteger --output <path>
if you dont specify output arg it will use the data dir as the default dir which is onnx\backend\test\data

**Comment by etusien** [comment]
@askhade The missing test was added to master. I think we can close the issue.
