### ISSUE TITLE
Celu function seems to be incorrectly composed

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#3323]
# Bug Report

### Describe the bug
Celu's function is composed by dividing (X/alpha) and passing its result to "Elu" and finally multiplying its result by alpha.
Per, Celu's activation formula - this won't handle all cases. For example, if x and alpha are both negative/positive, Elu's result will just be X/alpha as f(x) = x for x>= 0. Celu requires that we compute `exp(X/alpha) -1` irrespective of the sign of X/alpha and not to mention there are the clipping aspect to Celu (min, max portions). All in all, the function seems incorrect. For one breaking case, please see: https://github.com/microsoft/onnxruntime/issues/6906

**Comment by askhade** [comment]
@hariharans29 can you create a PR for the proposed the change?

**Comment by hariharans29** [comment]
Sure - One question I do have though - should the op be versioned because the function bod has changed or can it remain at the same version and the function body change is treated as a "bug fix" ?
