### ISSUE TITLE
Squeeze export issue opset10 vs opset11

### ISSUE THREAD

**Issue by AlexRibard** [onnx/onnx#3324]
PyTorch 1.7.1
I am trying to export a squeeze operator as follows:
```
import torch
class Dummy(torch.nn.Module):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    def forward(self, input_data):
        return input_data.squeeze(1)
a = Dummy()
b = torch.randn((64, 1, 1024))
torch.onnx.export(a, b, "test.onnx", opset_version=10)
```
* Using opset_version=10 the model gets exported to:
![image](https://user-images.githubusercontent.com/12990800/110978597-96b4ce80-8331-11eb-8f6e-41c032ab9575.png)
I get the following warning:
`This model contains a squeeze operation on dimension 1. If the model is intended to be used with dynamic input shapes, please use opset version 11 to export the model`

* Using opset_version=11 the model gets exported to:
![image](https://user-images.githubusercontent.com/12990800/110978558-87358580-8331-11eb-82a2-b9bf01c773d9.png)

**Why the Squeeze gets expanded to a conditional logic check on the first dimension of the tensor?**

Checking the official op definition
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze
I don't see why there should be the need for such logic.

Could someone clarify what is going on?

Thanks

**Comment by askhade** [comment]
@AlexRibard please open this issue in pytorch repo as this belongs to pytorch - onnx exporter.

**Comment by AlexRibard** [comment]
ok got it thanks
