### ISSUE TITLE
Support Resize (10->11) in Versino Converter

### ISSUE THREAD

**Issue by pranav-prakash** [onnx/onnx#3326]
# Feature Request
Currently the onnx opset version converter does not support [Resize v10](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Resize-10) to [v11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Resize-11).

I'd be happy to contribute this, if someone could note down the settings of `coordinate_transformation_mode` and `roi` needed to match the old behavior.

Edit: From the ORT sources

> Coordinate transformation mode attr was introduced in version 11, before that asymmetric mode was the only available transformation mode

However, from the comment that

>        // versions older than 11 did not have nearest_mode attr. Use the original logic in this case
>        // to maintain backward compatibility

It seems that it's not possible to exactly recreate the behavior of v10 op with the nearest_mode of v11?

And I'm not sure why "roi" is a mandatory input in v11 when it is not needed in modes other than `tf_crop_and_resize`

### Feature Area
ONNX Version Converter

### Are you willing to contribute it (Y/N):
Yes

**Comment by jcwchen** [comment]
https://github.com/onnx/onnx/pull/3343 I think the conversion for Resize-10 to Resize-11 has been done recently. Thanks
