### ISSUE TITLE
RuntimeError: Exporting the operator cdist to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by drive087** [onnx/onnx#3327]
# Ask a Question

### Question
I want to convert Prototypical Networks for Few-shot Learning to onnx. 
torch.onnx.export(model,(example_query_images, example_query_labels, x_pred), "super_resolution.onnx")   
And it raise error 'RuntimeError: Exporting the operator cdist to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.'

**Comment by jcwchen** [comment]
Hi @drive087,
As mentioned in the error message, it's a request for the converter (under pytorch). Please open an issue under pytorch to request this unsupported operator. BTW, you can check the supported operators for conversion here: https://pytorch.org/docs/stable/onnx.html#supported-operators. Close now. Please reopen it if you still have other ONNX related questions. Thanks.
