### ISSUE TITLE
support python 3.9 with pypi wheels

### ISSUE THREAD

**Issue by Borda** [onnx/onnx#3329]
# Feature Request

### System information

Any - Linux / MacOS / Win

### What is the problem that this feature solves?

simple installation, no need to build from source and resolving some third party dependencies
https://pypi.org/project/onnx/#files

### Will this influence the current api?

No

### Feature Area

any usage with Python 3.9

### Are you willing to contribute it (Y/N):

I guess just build an extra wheel and push it to pypi

**Comment by jcwchen** [comment]
Similar to https://github.com/onnx/onnx/issues/3132. ONNX will release 1.9 soon and I think 3.9 should be added.
