### ISSUE TITLE
function supposed to return a value but it returns an empty list

### ISSUE THREAD

**Issue by abkhaoula** [onnx/onnx#3336]
# What is the purpose of the merge function

### Question
while I am looking around ONNX source code I found this strange function called merge, it does some operation inside but it return  an empty array.
https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/__init__.py#L171-L179
@rakati

**Comment by jcwchen** [comment]
@gramalingam Could you take a look at this? Thank you.
