### ISSUE TITLE
ONNX_USE_PROTOBUF_SHARED_LIBS should control Protobuf_USE_STATIC_LIBS

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx#3345]
# Bug Report

### Describe the bug
ONNX_USE_PROTOBUF_SHARED_LIBS is set independently of Protobuf_USE_STATIC_LIBS even though the two are dependent on each other. Even the documentation says:

If ONNX_USE_PROTOBUF_SHARED_LIBS is ON then Protobuf_USE_STATIC_LIBS must be OFF and USE_MSVC_STATIC_RUNTIME must be 0. If ONNX_USE_PROTOBUF_SHARED_LIBS is OFF then Protobuf_USE_STATIC_LIBS must be ON.

Rather than relying on the user to set Protobuf_USE_STATIC_LIBS when calling cmake, it should be set before the call to find_package for protobuf based on the value of ONNX_USE_PROTOBUF_SHARED_LIBS. This way the user does not have to rely on their knowledge of what cmake does when find_package is called.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows 10
- ONNX version (*e.g. 1.7*):  1.7
- Python version: 3.8
- GCC/Compiler version (if compiling from source): VS2019
- CMake version:  3.19
- Protobuf version: 3.12.3
- Visual Studio version (if applicable): VS2019

### Reproduction instructions
1. Checkout protobuf 3.12.3
2. Correctly build static libraries with cmake and VS2019
-G "Visual Studio 16 2019" -A x64 -T host=x64
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_INSTALL_PREFIX=/path/to/protobuf/install
-Dprotobuf_BUILD_EXAMPLES=OFF
-Dprotobuf_BUILD_TESTS=OFF
-Dprotobuf_MSVC_STATIC_RUNTIME=OFF
-Dprotobuf_WITH_ZLIB=OFF
3. Checkout onnx-mlir
4. Build with cmake and VS2019
-G "Visual Studio 16 2019" -A x64 -T host=x64
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_PREFIX_PATH=/path/to/protobuf/install

### Expected behavior
Build succeeds

### Actual behavior
The build fails with multiple linker errors:
LNK2001: unresolved external symbol "__declspec(dllimport) ..."
LNK2019: unresolved external symbol "__declspec(dllimport) ..."
because neither onnx-mlir, nor onnx define Protobuf_USE_STATIC_LIBS and cmake silently defines PROTOBUF_USE_DLLS, but our protobuf is a static library.

**Comment by jcwchen** [comment]
Hi @sstamenova,
Yes it is something needs to be fixed (already in the backlog) and there will be a PR to merge these two flags. Thank you for bringing this up.

**Comment by askhade** [comment]
I will send out a fix for this. Thanks!

**Comment by askhade** [comment]
@sstamenova : can you review this PR: #3550
