### ISSUE TITLE
install onnx failure owning to CMAKE

### ISSUE THREAD

**Issue by zeliangDing** [onnx/onnx#3347]
# Ask a Question
when i use following command:
 set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF  
       - DONNX_USE_LITE_PROTO=ON

It report a mistake.
![image](https://user-images.githubusercontent.com/24822200/111876073-fa956200-89d7-11eb-8b66-8d81b72ca31d.png)

what's wrong?

**Comment by jcwchen** [comment]
Hi @zeliangDing,
What's your cmake and protobuf version? `Protobuf_USE_STATIC_LIBS` should be found after cmake 3.9.

**Comment by forestguan** [comment]
My cmake version is 3.19, but it reports the same mistake.

**Comment by jcwchen** [comment]
Hi @forestguan,
Thank you for the report. If you are using Powershell, please use their way to set environment variable instead of `set ENV=XXX`. For instance:
```
$env:CMAKE_ARGS='-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF'
```

**Comment by jcwchen** [comment]
Since we haven't received any response, I assume this bug has been resolved... Close this issue now. Please reopen it if you still have question. Thanks.
