### ISSUE TITLE
 [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION 

### ISSUE THREAD

**Issue by neso613** [onnx/onnx#3350]
Hi,
I have an onnxmodel. Here are the input/output details:
[name: "input_1:0"
type {
  tensor_type {
    elem_type: 6
    shape {
      dim {
        dim_param: "unk__1419"
      }
      dim {
        dim_param: "unk__1420"
      }
    }
  }
}
, name: "input_2:0"
type {
  tensor_type {
    elem_type: 6
    shape {
      dim {
        dim_param: "unk__1421"
      }
    }
  }
}
, name: "input_3:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__1422"
      }
    }
  }
}
]
[name: "output_0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__1423"
      }
      dim {
        dim_param: "unk__1424"
      }
      dim {
        dim_value: 80
      }
    }
  }
}
, name: "output_1"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__1425"
      }
      dim {
        dim_param: "unk__1426"
      }
      dim {
        dim_value: 80
      }
    }
  }
}
, name: "output_2"
type {
  tensor_type {
    elem_type: 6
    shape {
      dim {
        dim_param: "unk__1427"
      }
      dim {
        dim_param: "unk__1428"
      }
    }
  }
}
]
I have tried to run this using onnxruntime. It gives the following error:
`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Unsqueeze node. Name:'Unsqueeze__541' Status Message: /onnxruntime_src/onnxruntime/core/providers/common.h:21 int64_t onnxruntime::HandleNegativeAxis(int64_t, int64_t) axis >= -tensor_rank && axis <= tensor_rank - 1 was false. axis 2 is not in valid range [-2,1]`
Looking forward for some guidance. Thanks!

**Comment by neso613** [comment]
@spandantiwari @huitseeker @ezyang

**Comment by askhade** [comment]
@neso613 : How did you get this onnx model? Which converter? Did you try running onnx checker on this first? As the error suggests axis attr for unsqueeze node is not correctly configured... it is out of the range... Please take a look at the op spec to understand the details...

**Comment by neso613** [comment]
> @neso613 : How did you get this onnx model? Which converter? Did you try running onnx checker on this first? As the error suggests axis attr for unsqueeze node is not correctly configured... it is out of the range... Please take a look at the op spec to understand the details...

Thanks for response.
Yes, I have checked using this `onnx.checker.check_model(onnx_model)`
This is valid.

**Comment by neso613** [comment]
> > @neso613 : How did you get this onnx model? Which converter? Did you try running onnx checker on this first? As the error suggests axis attr for unsqueeze node is not correctly configured... it is out of the range... Please take a look at the op spec to understand the details...
> 
> Thanks for response.
> Yes, I have checked using this `onnx.checker.check_model(onnx_model)`
> 
> I have a TF saved model,using tf2onnx I have converted into ONNX model.

looking forward to hear from the team.

**Comment by neso613** [comment]
any update?
