### ISSUE TITLE
dfs recursive vs dfs iterative

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3351]
i'm checking `extract_model` method and i see you using `dfs` to check the graph [link](https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L132)
you using `dfs` via` recursive` [link](https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L53)
how do you think, if we try to use `iterative dfs`, can we win some time with this?

**Comment by mrry** [comment]
I don't think that code has been optimized for performance, so there are probably a few opportunities to improve it. The implementation seems to be O(N^3) for a graph with N nodes:

1. In the worst case, the search will visit all N nodes in the graph.
2. Each time a node is visited, all N nodes in the graph are scanned to find nodes that output that tensor: https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L61
3. Each time the code considers a neighbor, it will perform a linear search on the `reachable_nodes` list, which potentially contains N nodes:
https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L62-L63

If you want to improve the performance of that code - and we'd certainly welcome contributions here! - then I'd suggest building an index of the nodes to avoid the repeated scans in (2), and using a set for the reachable nodes to avoid the scans in (3). After that, an iterative approach would potentially help avoid overflowing the stack in very deep graphs. It could be BFS or DFS... it doesn't seem like the order is material here (e.g. it's not trying to compute a topological order as part of the search).

**Comment by kylesayrs** [comment]
Made a PR [here](https://github.com/onnx/onnx/pull/4324) to help reduce run time. I agree, the current bfs implementation and data structure is not optimized for speed

**Comment by justinchuby** [comment]
Please reopen the issue with new info if it is still relevant. Thanks!
