### ISSUE TITLE
how i can take Constant initializers?

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3355]
any chance to take `Constant` indicies from model? 

I can take usual initializers just iterating through `model.graph.initializer`. this method takes every `Initializer` kind from model. but can I take `Constant` kinds somehow? 

for example, on image i have node with `Constant` kind weight, so I need to detect this

![image](https://user-images.githubusercontent.com/43114292/112140061-94c9f580-8be4-11eb-9920-03f2de9e5a61.png)

**Comment by germanjke** [comment]
I think I found solution with
```
for node in model.graph.node:
    if node.op_type == 'Constant':
        print(node.output)
```
we can close thread, thanks

**Comment by jcwchen** [comment]
I think you got the answer. Please reopen it if you still have question. Close now. Thanks.
