### ISSUE TITLE
Some (transpose) convolution tests/examples are wrong?

### ISSUE THREAD

**Issue by gineshidalgo99** [onnx/onnx#3357]
# Bug Report

### Is the issue related to model conversion?
No (but it does apply to the tests!)

### Describe the bug
I believe that one of the documentation tests are wrong for [ConvTranpose](https://github.com/onnx/onnx/blob/master/docs/Operators.md#convtranspose):

- convtranspose_pads: The output size of Y cannot be [1, 2, 7, 3], it must be [1, 2, 6, 4].
    - Explanation: Based on the ArXiv link below, `o = s(i-1) + k - 2p`:
    	- First dimension (s = 3): `o = 3x2 + 3 - 3 = 6`
    	- Second dimension (s = 2): `o = 2x2 + 3 - 3 = 4`
    	- Thus, output size should be [1, 2, 6, 4] rather than [1, 2, 7, 3]
    - Sources: https://arxiv.org/pdf/1603.07285.pdf or https://towardsdatascience.com/what-is-transposed-convolutional-layer-40e5e6e31c11
    - With the 6x4 size, Y = [[[[0.0 1.0 1.0 3.0], [0.0 1.0 1.0 3.0], [3.0 7.0 4.0 9.0], [3.0 7.0 4.0 9.0], [3.0 7.0 4.0 9.0], [6.0 13.0 7.0 15.0]], [[0.0 1.0 1.0 3.0], [0.0 1.0 1.0 3.0], [3.0 7.0 4.0 9.0], [3.0 7.0 4.0 9.0], [3.0 7.0 4.0 9.0], [6.0 13.0 7.0 15.0]]]]

I also believe that one of the documentation tests are wrong for [Conv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#conv):

- conv_with_strides (last sub-example): The output size of Y cannot be [1, 1, 4, 2], it must be [1, 1, 3, 2].
    - Explanation: Based on the ArXiv link above, the output should be ceil(([4,2] + [1,1] - [3,3])/2) = [3, 2]
    - With the 3x2 size, Y = [[[[12.0 27.0], [63.0 108.0], [123.0 198.0]]]]

**Happy to do a PR with the updated Y if I am told where I should make the edit!** (not sure which doc is auto-generated and which one is not).

### System information
Any

### Reproduction instructions
Doc/test related, no repro steps

### Expected behavior
It should provide the right results of the transposed convolution.

### Notes

Any additional information

**Comment by gineshidalgo99** [comment]
Still an issue

**Comment by ah-cheng** [comment]
Why do I feel like it is right?  
from https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose
```
`pads` format should be as follow [x1_begin, x2_begin...x1_end, x2_end,...]
```
convtranspose_pads:
`
x (1,1,3,3,)  w(1,2,3,3) , strides(3,2), pads[1,2,1,2]
`
First dimension (s = 3): o = 3x2 + 3 - 2= 7
Second dimension (s = 2): o = 2x2 + 3 - 4 = 3

**Comment by kraiskil** [comment]
I agree with @chengven027-intellif on this one. 
I just implemented ConvTranspose to [onnx2c](https://github.com/kraiskil/onnx2c), and while the ONNX documentation of the algorithm itself skips over a few details ("The convolution transpose operator consumes an input tensor and a filter, and computes the output." :) ), the description on how the output shape or pads are calculated is well defined. 
And based on my interpretation of the docs, the `convtranspose_pads` test run in onnx2c does calculate an output shape of [1, 2, 7, 3].
