### ISSUE TITLE
Nvidia transfer learning toolkit (TLT) model to Pytorch or TensorFlow model conversion?

### ISSUE THREAD

**Issue by talhaanwarch** [onnx/onnx#3360]
I want to know can we convert Nvidia transfer learning toolkit models to PyTorch or TensorFlow models using ONNX?

**Comment by jcwchen** [comment]
Hi @talhaanwarch,
I am not familiar with Nvidia transfer learning toolkit, but according to their [document ](https://developer.nvidia.com/blog/building-and-deploying-conversational-ai-models-using-the-transfer-learning-toolkit/), it looks doable. As long as the operators in the desired model are supported by ONNX, the model should be transmittable between Pytorch and TensorFlow.

**Comment by talhaanwarch** [comment]
can you recommend me any starting point?

**Comment by jcwchen** [comment]
If you are looking for conversions:
TensorFlow to ONNX: https://github.com/onnx/tensorflow-onnx
ONNX to TensorFlow: https://github.com/onnx/onnx-tensorflow
PyTorch to ONNX: https://pytorch.org/docs/stable/onnx.html

For ONNX to pytorch, it is still waiting for a solid solution: https://github.com/pytorch/pytorch/issues/21683

**Comment by mkeyno** [comment]
I search the whole GitHub , it seems nobody has yet import TLT model in onnix

**Comment by askhade** [comment]
@mkeyno : Did you try to convert it? Are you seeing any issues?

**Comment by mkeyno** [comment]
@askhade  can you direct me to your effort & issue

**Comment by jcwchen** [comment]
@mkeyno Have you tried the method mentioned [here](https://developer.nvidia.com/blog/building-and-deploying-conversational-ai-models-using-the-transfer-learning-toolkit/)?

**Comment by mkeyno** [comment]
@jcwchen , @askhade thanks for a link , however, these technical documents mostly focused on how to train the NVIDIA TLT models , whereas I'm seeking the simple converter to change the trained model in a way that can use in OpenCV without any hardware dependency

**Comment by jcwchen** [comment]
It seems that Nvidia Transfer Learning Toolkit does not open-source their code so you could only find how to use it in their developer documents... I would suggest you raise a question here: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/transfer-learning-toolkit/17 to get the best help from NVIDIA experts.
