### ISSUE TITLE
convert_version failed : "No Adapter For Current Version $9 for MaxPool" on opset9 models

### ISSUE THREAD

**Issue by bbap-7fat** [onnx/onnx#3362]
### Question
convert_version failed: "No Adapter For Current Version $9 for MaxPool" on opset9 onnx models
opset9 ->[5,9] : pass
opset9 ->[10,11]: fail

### Further information
- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  alexnet, googlenet
**Model opset** (*e.g. 7*): 9

### Notes
```
model_path = 'model.onnx'
original_model = onnx.load(model_path)
converted_model = version_converter.convert_version(original_model, target_version)
```
```
Traceback (most recent call last):
  File "onnx_opset_convert.py", line 19, in <module>
    converted_model = version_converter.convert_version(original_model, target_version)
  File "***/onnx/version_converter.py", line 166, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /io/onnx/onnx/version_converter/BaseConverter.h:60: adapter_lookup: Assertion `false` failed: No Adapter For Current Version $9 for MaxPool
```
I saw 
```
registerAdapter(make_unique<CompatibleAdapter>("MaxPool",
        OpSetID(9), OpSetID(10)));
```
in https://github.com/onnx/onnx/blob/master/onnx/version_converter/convert.h, cannot understand why the failure shows.

I saw my convert.h only has
```
registerAdapter(make_unique<CompatibleAdapter>("MaxPool",
        OpSetID(7), OpSetID(8)));
      registerAdapter(make_unique<MaxPool_8_7>());
```
Is it the reason which triggered the failure?

Could anyone please give me some hint?
thanks

onnx version: 1.6.0

**Comment by jcwchen** [comment]
Hi @bbap-7fat,
Could you try the latest ONNX? It is supported after ONNX 1.6.0: https://github.com/onnx/onnx/pull/2664
