### ISSUE TITLE
Simpler APIs for building ONNX graphs.

### ISSUE THREAD

**Issue by yaoyuannnn** [onnx/onnx#3370]
# Feature Request
A set of user-friendlier APIs.

### Describe the feature
Why is this feature necessary? What does it accomplish?

Currently, it's a very tedious process to build a model using the ONNX APIs such as `onnx.helper.make_node()` and `onnx.helper.make_graph()`. And it's fairly easy to make mistakes to be honest. For much better usability, similar to other frameworks, the ONNX APIs can look like the following:

```python
with onnx.Graph() as graph:
    a = onnx.Tensor(...)
    b = onnx.Tensor(...)
    out = onnx.Add(a, b)
    out = onnx.Sub(out, a)
graph_proto = graph.to_proto()
# graph_proto is a GraphProto.
```

**Comment by askhade** [comment]
Please check this out: https://github.com/onnx/onnx/blob/master/docs/Syntax.md
This PR was recently submitted.

**Comment by yaoyuannnn** [comment]
> Please check this out: https://github.com/onnx/onnx/blob/master/docs/Syntax.md
> This PR was recently submitted.

Thanks! Does this have similar Python APIs? I suppose things could be greatly simplified at the Python side, even without a domain specific language/syntax like this.

**Comment by askhade** [comment]
No. The goal of adding this parser was really to simply function definitions. If you have suggestions for improving/extending this please open a new discussion and add @gramalingam (author of this Parser). Closing this issue, please reopen if you have more comments.

**Comment by yaoyuannnn** [comment]
As I stated in the original post, the current Python APIs are not easy to work with when creating an ONNX model. So similar to the new parser at the C++ side, a better set of Python APIs can be designed to enable much wider use cases.

Can anyone reopen this? I don't think I have the permission to reopen a closed issue.

**Comment by yaoyuannnn** [comment]
Thanks @gramalingam I'd prefer familiar Python APIs like what TensorFlow and PyTorch provide. Since ONNX already has all the protobuf-level APIs, this would only need to be a few wrapper classes that package things more nicely. Is something like this under the radar?

**Comment by yaoyuannnn** [comment]
In case anyone's interested, looks like ONNX GraphSurgeon is what I'm looking for (https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon). Their high-level Python APIs provide easy ways to create ONNX graphs.
