### ISSUE TITLE
import onnx fails with ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Nirmal-Neel** [onnx/onnx#3374]
Hi,

I have built onnx from source on an ubuntu 18.04 arm64 machine. I am trying to install the generated wheel on an ubuntu 20.04 arm64 machine and getting the following error -

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libprotobuf.so.10: cannot open shared object file: No such file or directory
```
I do not get the error if I try to install it on an ubuntu 18.04 arm64 machine.

On both the machines, the python version is same.

UPDATE - I see that ubuntu 20.04 does not have libprotobuf.so.10. It has libprotobuf.so.17. So isn't it a compatibility issue?

**Comment by jcwchen** [comment]
Hi @Nirmal-Neel,
I met similar issue on Linux before. Could you try to install protobuf==3.11.3 in your 20.04 Ubuntu? Thanks

**Comment by Nirmal-Neel** [comment]
Hi @jcwchen, installing protobuf==3.11.3 didn't help either. I can still see the same error.

**Comment by jcwchen** [comment]
Did you build protobuf 3.11.3 from source? For instance, https://github.com/onnx/onnx/blob/master/.azure-pipelines/Linux-CI.yml#L48-L58. Also, did you see other libprotobuf.so.X after installing protobuf 3.11.3? Thanks.

**Comment by Nirmal-Neel** [comment]
I still doesn't solve the issue. Building protobuf from source adds **libprotobuf.so** file to **/lib/aarch64-linux-gnu**, but in my case, the required file is libprotobuf.so.10.

**Comment by jcwchen** [comment]
Thank you for quick response. Did you see `libprotobuf.so.10` under your `/usr/local/lib`?

**Comment by askhade** [comment]
How are you building onnx? Can you list your cmd arguements? Have you tried building protobuf as static lib?

**Comment by Nirmal-Neel** [comment]
> Thank you for quick response. Did you see `libprotobuf.so.10` under your `/usr/local/lib`?

No @jcwchen , I do not see it.

**Comment by Nirmal-Neel** [comment]
Hi @askhade , I followed the following steps for building onnx - 
```bash
git clone --single-branch --branch v1.7.0 https://github.com/onnx/onnx
cd onnx
python3 setup.py bdist_wheel
```
and for building protobuf - 
```bash
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout 3.11.x
git submodule update --init --recursive
mkdir build_source && cd build_source
sudo make -j4
sudo make install
ldconfig
```

**Comment by jcwchen** [comment]
Could you try set the following environment variable before building ONNX? Thanks
```
export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON"
```

**Comment by Nirmal-Neel** [comment]
Thanks @jcwchen! It worked!

**Comment by jcwchen** [comment]
I think this problem should be solved. Please reopen it if you still have questions. Thank you.

**Comment by Nirmal-Neel** [comment]
Hi @jcwchen, this worked 13 days back. When I tried yesterday, it was failing with the following error message -   

**"/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x468): R_ARM_TLS_LE32 relocation not permitted in shared object"**

The solution that I found was to remove the second argument from _CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON"_.

Thanks!
