### ISSUE TITLE
converting pytorch to onnx with three inputs

### ISSUE THREAD

**Issue by ganitps** [onnx/onnx#3375]
# Ask a Question
Hi I saw in examples how to create and run model with 2 inputs, and that seem to be fine I can convert my model to onnx and run it (I dont know y does it run since I give it 2 inputs instead of 3...) when giving it 3 it crashes:
**ai.onnxruntime.OrtException: Unexpected number of inputs, expected [1,2) found 3** 
when checkin my onnx model using netron.app I do see only 2 inputs!
while my pytorch model has 3.
so I assume my conversion is wrong.

this is how I convert (python):
        example_outputs = model(torch_input_var, meta_arr, cond_view)
        torch.onnx.export(traced_script_module,  
                          (torch_input_var, meta_arr, cond_view),  
                          "converted.onnx",
                          example_outputs=example_outputs,
                          input_names=['x', 'argument_2', 'cond_view'])

this is how I run the model(kotlin):
        val env = OrtEnvironment.getEnvironment()
        val session = env.createSession(File(rootFolder, modelName).absolutePath, SessionOptions())
        val t1: OnnxTensor = OnnxTensor.createTensor(env, mInputTensorBuffer, longArrayOf(1, numberOfFrames.toLong(), IMAGE_SIZE.toLong(), IMAGE_SIZE.toLong()))
        val t2: OnnxTensor = OnnxTensor.createTensor(env, metaBuffer, longArrayOf(1, PATIENT_META_DATA_LEN.toLong()))
        val t3: OnnxTensor = OnnxTensor.createTensor(env, condBuffer,longArrayOf(1, 1, VIEW_INPUT_ARRAY_LENGTH.toLong()))
        val inputs = hashMapOf("x" to t1,"argument_2" to t2, "cond_view" to t3)
        val result = session.run(inputs)

if I try to run without t2 there is no crash. // val inputs = hashMapOf("x" to t1, "cond_view" to t3). 
Thanks!

**Comment by jcwchen** [comment]
Hi @ganitps,
Could you provide the model? Does the model pass `onnx.checker.check_model(model)`? As you mentioned, this looks like a converter issue. I would suggest you also open an issue under pytorch to ask the converter team why the input number mismatches after conversion. Thanks.

**Comment by askhade** [comment]
Please open this in converter repo. Closing this here.
