### ISSUE TITLE
DecodeError: Unexpected end-group tag.

### ISSUE THREAD

**Issue by buliginleo** [onnx/onnx#338]
Hello!

I have a model on pytorch. (Condensenet)

I convert this model to onnx:

```
# Input to the model
x = Variable(torch.randn(1, 3, 224, 224))

# Export the model
torch_out = torch.onnx._export(model,             # model being run
                               x,                       # model input (or a tuple for multiple inputs)
                               "condensenet.onnx", # where to save the model (can be a file or file-like object)
                               export_params=True)      # store the trained parameter weights inside the model file
```

Then I try to load this model to onnx:

```
import onnx
import onnx_caffe2.backend

# Load the ONNX ModelProto object. model is a standard Python protobuf object
model = onnx.load("condensenet.onnx")
```

But I get error:

> /home/leo/anaconda2/lib/python2.7/site-packages/google/protobuf/internal/decoder.pyc in DecodeRepeatedField(buffer, pos, end, message, field_dict)
>     613           # The only reason _InternalParse would return early is if it
>     614           # encountered an end-group tag.
> --> 615           raise _DecodeError('Unexpected end-group tag.')
>     616         # Predict that the next tag is another copy of the same repeated field.
>     617         pos = new_pos + tag_len
> 
> DecodeError: Unexpected end-group tag.

What I can do to fix it?

**Comment by dzhulgakov** [comment]
How fresh is your pytorch and onnx installation? There were breaking changes in protobuf a few months ago, so you maybe running into those. Can you try the latest masters?

We're preparing stable v1 releases of onnx and pytorch/caffe2 so it should work with binary distributions next week.

**Comment by buliginleo** [comment]
@dzhulgakov Yes, the problem was in versions of pytorch, caffe2 and onnx-caffe2. I create docker file with latest versions of modules and this works.  Thank you!
