### ISSUE TITLE
How to convert the raw data to float with protobuf C++ API 

### ISSUE THREAD

**Issue by yangjing69** [onnx/onnx#3380]
Hi, I am using the protobuf C++ API to parse the onnx model, but how do I convert the raw data to float( or int8、int16、int32) type for the weights of the raw data type provided by the onnx model?
Looking forward to everyone's response.

**Comment by askhade** [comment]
You can refer to this: https://github.com/onnx/onnx/blob/master/onnx/defs/tensor_util.cc#L12
Closing this issue... if this does not answer your question then please reopen it.
