### ISSUE TITLE
remove node of onnx model

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/onnx#3382]
Dear All,

I want to remove the softmax operation in the efficientnet-lite4.onnx model (get this file from git repo: https://github.com/hoaquocphan/shared_files.git)

I can remove the softmax node by below code:
```
node = onnx_model.graph.node[187]
onnx_model.graph.node.remove(node)
```
I can remove the softmax:0 output by below code:
```
for node in onnx_model.graph.output:
    if node.name == "Softmax:0":
        print("remove node: ",node)
        onnx_model.graph.output.remove(node)
```
I can create the new output BiasAdd for new model
```
output_value_info = onnx.helper.ValueInfoProto()
output_value_info.name = "efficientnet-lite4/model/head/dense/BiasAdd"
```

but I don't know how to connect the last node with the  new output BiasAdd?
could anyone please help me

**Comment by jcwchen** [comment]
Hi @hoaquocphan,
It seems that you would like to replace certain node in a graph? Basically, after removing certain node, you need to create a desired Tensor:
1. Its input name is the previous node's output name
2. Its output name is the next node's input name

Also please note that the nodes in model.graph.node need to be topologically-sorted according to ONNX's definition, although it still can be run by ONNXRuntime. (ONNXRuntime will apply topologically sort to the graph before inference)

**Comment by hoaquocphan** [comment]
Hi @jcwchen 

Thanks for your support, 
I can remove the node from onnx model without error.
