### ISSUE TITLE
How to register an onnx-graphsurgery(not-pytorch) custom operator to onnx??

### ISSUE THREAD

**Issue by dedoogong** [onnx/onnx#3388]
# New Operator 

I have converted TF model to onnx which contains some unsupported ops with a tool as below;

python3 -m tf2onnx.convert --graphdef frozen_model_v2 --output aslfeatv2.onnx  

Then, as I need to run it on TensorRT, first I needed to check the converted onnx file are correct. 
So, I implemented those unsupported ops with C++/CUDA for onnx-runtime and built, tested. 
But in onnx, it still fails to recognize the custom onnx-runtime ops when running onnx-simplifier 
```
....
....
onnx.checker.check_model(model)
  File "/home/lee/.local/lib/python3.6/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for ASLFeatPluginX with domain_version of 13
```
I've read all tutorials related to the custom ops or pytorch custom ops but nothing can help me yet. 

1. Which onnx code I should modify? ( I guess below ones are the target codes,
    onnx/cpp2py_export.cc 
    onnx/defs/__init__.py 
    onnx/defs/math/defs.cc 
    onnx/defs/operator_sets.h 
    onnx/defs/schema.cc 
    onnx/defs/schema.h 
    onnx/test/shape_inference_test.py 
)
2. Which code I should add?
3. Which onnx API I should reference to make it work with onxx?

I've implemented several custom ops including openvino, tensorrt, pytorch, caffe but onnx custom ops is not clear yet to me. 
Can anybody tell me any hint for surviving this situation?

Thank you

onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for ASLFeatPluginX with domain_version of 13
"""
 
### Further information
- Relevant Area (*e.g. model usage, best practices, shape_inference, version_converter, training, test*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  ASLFeat
**Model opset** (*e.g. 7*):  13
all related codes are in https://github.com/dedoogong/ASLFeat_TRT and the onnx model is linked to
https://github.com/dedoogong/ASLFeat_TRT/blob/main/aslfeatv2_op13_custom_const_padding_v3.onnx

### Notes
Any additional information, code snippets.

### Describe the operator
Target Model is ASLFeat.
Why is this operator necessary? What does it accomplish?
Used in a SOTA Tensorflow model

### Can this operator be constructed using existing onnx operators? NO.
If so, why not add it as a function?

### Is this operator used by any model currently? Which one?
Tensorflow's Meshgrid/Extract Image Patch

### Are you willing to contribute it? (Y/N)
Y

### Notes
Any additional information

**Comment by jcwchen** [comment]
Hi @dedoogong,
So you just want to add it as a custom op to make your model pass onnx.checker without pushing it to be the ONNX standard? If so, you still can reference this file: https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md. Basically what you need to do is adding `ASLFeatPluginX ` as a `ONNX_OPERATOR_SET_SCHEMA` in certain `onnx/onnx/defs/XXX/defs.cc` to register this operator.

**Comment by dedoogong** [comment]
thank you! I will try your guide and be back!

**Comment by dedoogong** [comment]
I added below codes;
```
static const char* ASLFeatPluginX_ver1_doc = R"DOC( LSH's ASLFeatPluginX
)DOC";
static const char* ASLFeatPluginY_ver1_doc = R"DOC( LSH's ASLFeatPluginY
)DOC";
ONNX_OPERATOR_SET_SCHEMA(
    ASLFeatPluginX,
    13,
    OpSchema()
        .SetDoc(ASLFeatPluginX_ver1_doc)
        .Input(
            0,
            "X",
            "Input data tensor from the previous operator; "
            "4-D feature map of shape (N, C, H, W), "
            "where N is the batch size, C is the number of channels, "
            "and H and W are the height and the width of the data.",
            "T")
        .Output(
            0,
            "Y",
            "mesh-pached output, 4-D tensor of shape "
            "(num_rois, C(9), output_height, output_width).",
            "T")
        .TypeConstraint(
            "T",
            {"tensor(float16)", "tensor(float)", "tensor(double)"},
            "Constrain types to float tensors.")
        .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
          propagateElemTypeFromInputToOutput(ctx, 0, 0);     
        //if (hasInputShape(ctx, 0)) 
          const TensorShapeProto& input_shape =
              ctx.getInputType(0)->tensor_type().shape();
          const auto rank = static_cast<int>(input_shape.dim_size());          
          std::cout<<"rank"<<rank<<std::endl;
          if (rank < 2) {
            fail_shape_inference("Input rank must be >= 2.")
          }
          if (rank != 4)
            fail_shape_inference("Input's shape must be 4-D");
          // Shape inference 
          auto* output_shape =
            ctx.getOutputType(0)->mutable_tensor_type()->mutable_shape();            
          auto N=input_shape.dim(static_cast<int>(0)).dim_value();
          auto C=input_shape.dim(static_cast<int>(1)).dim_value();
          auto H=input_shape.dim(static_cast<int>(2)).dim_value();
          auto W=input_shape.dim(static_cast<int>(3)).dim_value(); 

          std::cout<<" N C H W : "<<N<<"x"<<C<<"x"<<H<<"x"<<W<<std::endl; // 1 x 1 x 6 x 4

          auto* n_output_dim = output_shape->add_dim();
          n_output_dim->set_dim_value(N);  
          int64_t pads_data=2;
          auto* c_output_dim = output_shape->add_dim(); 
          c_output_dim->set_dim_value(9); 
          auto* h_output_dim = output_shape->add_dim();
          h_output_dim->set_dim_value(H - pads_data); 
          auto* w_output_dim = output_shape->add_dim();// N, H-2, W-2, 9 in TF -> N, 9, H-2, W-2 !! 
          w_output_dim->set_dim_value(W- pads_data);   

        }));



ONNX_OPERATOR_SET_SCHEMA(
    ASLFeatPluginY,
    13,
    OpSchema()
        .SetDoc(ASLFeatPluginY_ver1_doc)
        .Input(
            0,
            "X",
            "Input data tensor from the previous operator; "
            "4-D feature map of shape (N, C, H, W), "
            "where N is the batch size, C is the number of channels, "
            "and H and W are the height and the width of the data.",
            "T")
        .Output(
            0,
            "Y",
            "mesh-pached output, 4-D tensor of shape "
            "(num_rois, C(9), output_height, output_width).",
            "T")
        .TypeConstraint(
            "T",
            {"tensor(float16)", "tensor(float)", "tensor(double)"},
            "Constrain types to float tensors.")
        .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
          propagateElemTypeFromInputToOutput(ctx, 0, 0);     
        //if (hasInputShape(ctx, 0)) 
          const TensorShapeProto& input_shape =
              ctx.getInputType(0)->tensor_type().shape();
          const auto rank = static_cast<int>(input_shape.dim_size());          
          std::cout<<"rank"<<rank<<std::endl;
          if (rank < 2) {
            fail_shape_inference("Input rank must be >= 2.")
          }
          if (rank != 4)
            fail_shape_inference("Input's shape must be 4-D");
          // Shape inference 
          auto* output_shape =
            ctx.getOutputType(0)->mutable_tensor_type()->mutable_shape();            
          auto N=input_shape.dim(static_cast<int>(0)).dim_value();
          auto C=input_shape.dim(static_cast<int>(1)).dim_value();
          auto H=input_shape.dim(static_cast<int>(2)).dim_value();
          auto W=input_shape.dim(static_cast<int>(3)).dim_value(); 

          std::cout<<" N C H W : "<<N<<"x"<<C<<"x"<<H<<"x"<<W<<std::endl; // 1 x 1 x 6 x 4

          auto* n_output_dim = output_shape->add_dim();
          n_output_dim->set_dim_value(N);  
          int64_t pads_data=2;
          auto* c_output_dim = output_shape->add_dim(); 
          c_output_dim->set_dim_value(9); 
          auto* h_output_dim = output_shape->add_dim();
          h_output_dim->set_dim_value(H - pads_data); 
          auto* w_output_dim = output_shape->add_dim();// N, H-2, W-2, 9 in TF -> N, 9, H-2, W-2 !! 
          w_output_dim->set_dim_value(W- pads_data);   

        }));    
```
to onnx/onnx/defs/tensor/defs.cc and build successfully.
but I got segfault error when run onnx simplifier. 
sudo python3 -m onnxsim aslfeatv2_op13_custom_const_padding_v3.onnx simple.onnx --custom-lib /home/lee/workspace/onnxruntime/build/Linux/RelWithDebInfo/libcustom_op_library.so

**Comment by jcwchen** [comment]
https://github.com/onnx/onnx/blob/de0a5e035798f2936029c268ddcfb05a5e882847/onnx/defs/operator_sets.h#L926 Also need to register your OpSchema here. Thanks

**Comment by jcwchen** [comment]
Close it due to inactivity. Please reopen it if you still have question related to ONNX. Thanks!
