### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by Toxiang** [onnx/onnx#3395]
when i use pip install the lastest onnx1.8.1 it send me an error
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
so i try to install another version onnx
and when i use onnx1.8.0 the error missing 
i don't know why

**Comment by jcwchen** [comment]
@Toxiang,
I guess it's related to protobuf version issue because ONNX has upgraded its protobuf-complier version on Linux since 1.8.1. What's your environment and your protobuf version? Thanks.

**Comment by Toxiang** [comment]
> @Toxiang，
> 我想这与protobuf版本问题有关，因为ONNX从1.8.1开始就在Linux上升级了其protobuf编译器版本。您的环境和protobuf版本是什么？您可以先尝试将protobuf升级到3.11.3，然后查看它是否可以解决此问题。谢谢。

my exist environment was ubuntu16.0.4 with torch=1.2  protobuf=3.4.0 and i will try to create a new environment to try your suggestion 
Thanks for your reply！

**Comment by askhade** [comment]
Closing this issue... please reopen it if you are still experiencing this...
@jcwchen : We have seen multiple such issues.... perhaps it would be nice to add some documentation around this
