### ISSUE TITLE
Differences between BackendRep and Backend?

### ISSUE THREAD

**Issue by machoji** [onnx/onnx#34]
As the title said,  what's the concrete meaning between them?
In this webpage,
https://github.com/onnx/onnx-caffe2/blob/master/onnx_caffe2/backend.py
It seems that Caffe2Backend extends more functions than BackendRep.  th
what is the meaning of "Rep"?
Thank you in advance.

**Comment by bddppq** [comment]
`Rep` stands for (intermediate) representation here. It's returned by backend's `prepare` function and user can run the net by passing inputs to the `Rep`'s `run` function.
