### ISSUE TITLE
Using pytorch model embedded functions once translated to ONNX

### ISSUE THREAD

**Issue by ADD-eNavarro** [onnx/onnx#3400]
# Ask a Question
I have converted a pytorch pretrained model to ONNX to use in a C# project, but I can't find a way to use the model embedded methods.

### Question
I am using [Resemble-ai voice encoder](https://github.com/resemble-ai/Resemblyzer/blob/master/resemblyzer/voice_encoder.py) as ONNX, using:
<pre>
import torch
import torch.onnx
x = torch.randn(1,3,40,requires_grad=True)
torch_out = encoder(x)

torch.onnx.export(encoder,
                  x,
                  "resemblyzer.onnx",
                  opset_version=13,
                  input_names=['input'],
                  output_names=['output'])
</pre>
But I can't figure out how to use the model's embedded functions "embed_utterance" and "embed_speaker". Is that even possible? I mean, do the ONNX model include those functions or just the weights and biases of the trained model?
If the functions are inside de ONNX model, a snippet on how to access to them would be great.

**Comment by jcwchen** [comment]
Hi @ADD-eNavarro,
So the conversion was successful without error/warning?  I think this question is for the converter (pytorch-onnx). I would suggest you open an issue under pytorch repo to get the best help from the converter team. Thank you.

**Comment by ADD-eNavarro** [comment]
Yes, the conversion was flawless. 
I will open an issue under pytorch, thank you.
So, in theory, if the model class comprehends other functions besides "init", "forward" and error calculation, how can we access them once the model is in ONNX format?

**Comment by jcwchen** [comment]
ONNX is a pure model format only including tensor and shape information and you can check the full definition here: https://github.com/onnx/onnx/blob/master/docs/IR.md. I believe anything unrelated to model itself will be rid of by the converters.
