### ISSUE TITLE
Using tensors with statically unknown shapes as inputs/outputs

### ISSUE THREAD

**Issue by adjhawar** [onnx/onnx#3404]
# How do I use tensors with unknown rank and shape as inputs/outputs to a graph?

### Question
From my understanding, ONNX requires that input and output tensors of a graph have their shape defined. However, if I want to use tensors with unknown shape and rank as input/output, then how should I go about that?

### Further information
- Relevant Area : shape_inference, model_extraction

### Notes
I want to break the model at a node where the input to that node does not have a statically defined shape.

**Comment by jcwchen** [comment]
Hi @adjhawar,
Actually you can use `dim_param` as a string name for usage like 'batch' or 'N'.
Or if you want to represent an unknown dimension unrelated to other unknown dimensions,  just leave shape in the ValueInfoProto unset.

More discussions which might be helpful: https://github.com/onnx/onnx/issues/740

**Comment by liqunfu** [comment]
Revisited this issue with @jcwchen:
It is hard to think of a real-world model with unknown rank input tensor. However, if someone can provide a convincing real-world model with unknown rank inputs, we shall extend ONNX IR to express shapes with unknown rank. 
Here is a toy example of this hypothetic problem:

```
import onnx.parser
import onnx.checker
import onnxruntime as ort
import numpy as np

input = '''
        <
        doc_string: "A test model to clip tensors of any shape."
      >
     agraph (float[] x) => (float[] out)
     {
        out = Clip(x)
     }
     '''

model = onnx.parser.parse_model(input)

sess = ort.InferenceSession(model.SerializeToString(), providers=['CPUExecutionProvider'])
sess.run(None, {'x': np.random.rand(1,2,3,4,5).astype(np.float32)})
# [array([[[[[0.6689827 , 0.7752347 , 0.6899522 , 0.33497095, 0.81925666],
        #   [0.4292569 , 0.2605244 , 0.64371866, 0.39683977, 0.52624846],
        #   [0.602037  , 0.5368144 , 0.34024337, 0.3951886 , 0.14181606],

onnx.checker.check_model(model)
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "c:\liqunwa\ort\onnx\onnx\checker.py", line 106, in check_model
#     C.check_model(protobuf_string)
# onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.

```
