### ISSUE TITLE
Issues in auto-exported tests from PyTorch

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx#341]
1. Seems like MaxPool/AvgPool tests (Added in #329) are not well-formed (padding attribute is of length N instead of 2*N) - primarily due to export bug in PyTorch
2. It's better to separate auto-exported tests into a separate category so they can be selectively filtered when running the tests. Right now they fall under ModelTest and interleave with heavy 
 "real" model tests like resnet50

**Comment by houseroad** [comment]
In https://github.com/onnx/onnx/pull/351, 
1) a new folder "generated" contains all the generated test cases. Now they fall into GeneratedTest instead of ModelTest.
2) Fix the MaxPool/AvgPool test cases in test/data/generated folder.

**Comment by houseroad** [comment]
In https://github.com/onnx/onnx/pull/367, we have another type of auto-generated test cases from pytorch-operator.

**Comment by houseroad** [comment]
I think the problems are already fixed by the above PRs.
