### ISSUE TITLE
how to confirm the correctness of ONNX model

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/onnx#3418]
Hi All,

I have a problem need the support from you all.

I down load the model from onnx model zoo: 
https://github.com/onnx/models/blob/master/vision/classification/efficientnet-lite4/model/efficientnet-lite4-11.onnx

I run script to load the **efficientnet-lite4-11.onnx** model and remove softmax node out of the efficientnet-lite4-11.onnx model
the output is **efficientnet-lite4-11_remove_softmax.onnx** (you can get it from my git repo: https://github.com/hoaquocphan/shared_files)

I run the original model **efficientnet-lite4-11.onnx** and the **efficientnet-lite4-11_remove_softmax.onnx** (added softmax to postprocessing) and they have the same result.

When I put the **efficientnet-lite4-11_remove_softmax.onnx**  model to my own tool to convert to other format, it have the error.

So how can I confirm the correctness of **efficientnet-lite4-11_remove_softmax.onnx**  model? (I already used the code "
onnx.checker.check_model(onnx_model)" and it have no issue)

**Comment by jcwchen** [comment]
Hi @hoaquocphan,
Could you also try to run a stricter shape_inference? Something like: `onnx.shape_inference, infer_shapes(model, check_type=True, strict_mode=True)`. Also, what's the exact error during the conversion? Thanks.
