### ISSUE TITLE
Loop inner graph inherited type

### ISSUE THREAD

**Issue by bsledz** [onnx/onnx#3419]
This issue is related to the following model:
https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/node/test_range_int32_type_negative_delta_expanded

Type of inner graph input: _prev_ is not specified. Should type be inherited from related input (_start_) of Loop node? 
In my opinion, this is not clear in the documentation.

**Comment by jcwchen** [comment]
Hi @bsledz,
If you use `onnx.shape_inference.infer_shapes`, the type of prev can be successfully inferred, which is int32, same as the input (`start`).
