### ISSUE TITLE
Engine creation failed using trtexec

### ISSUE THREAD

**Issue by Noam-M** [onnx/onnx#3427]
### Question
I have exported my Pytorch model into ONNX model, and now I want to create a TensorRT engine in order to run it on my Jetson Xavier NX.
The next step is to create the engine. 
Running `trtexec --onnx=<my_path>/ONNX_model --explicitBatch` I got the following error:
```
ModelImporter.cpp:125: Clip_524 [Clip] inputs: [1425 -> (1, 1, 60, 80)], [2162 -> ()], [optional input, not set], 
ERROR: builtin_op_importers.cpp:362 In function importClip:
[8] Assertion failed: inputs.at(2).is_weights() && "Clip max value must be an initializer!"
```
I found this github [Issue](https://github.com/onnx/onnx-tensorrt/issues/562#issuecomment-735436875) relevant to my problem.
The answer recommends to "set the max value in the Clip layer to convert it from ONNX to TensorRT engine. You can edit the ONNX graph to achieve this."
But using the [documentation](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip) I figured that it can also just have neither minimum nor maximum set and that should be just fine. So instead of creating a new constant node and setting it as the clip's "maximum" input, I just deleted the "minimum". (it's the first time I'm editing an ONNX graph and it seemed to be the easier option) 

**rerunning the trtexec command, the error didn't reappear, but is it the right solution?**

after running the trtexec command again, I ran into a different error:
`Layer: Floor_382's output can not be used as shape tensor.`
Below is the relevant snippet from Netron if that helps:

![Screenshot from 2021-04-15 22-48-10](https://user-images.githubusercontent.com/45801356/114929684-caa57700-9e3c-11eb-9692-fea34f2d629b.png)

I am not sure how to solve this one. 
Any ideas? I'd really appreciate some help

Thank you so much!

**Model opset = 11**

**Comment by jcwchen** [comment]
Hi @Noam-M,
Similar to https://github.com/onnx/onnx/issues/3262 ? For Clip-**11**, you should use graph.initializer to represent its max/min. Could you give it a try? Thanks.

**Comment by Noam-M** [comment]
Hello @jcwchen,
Thanks for the quick reply!

I could try that, but right now I think it's better to focus on solving the problem with the floor layer, since it doesn't allow me to complete the engine building.
Only after I will be able to run the inference on the model I will be able to check how different implementations of clip part of the graph make a difference.

Do you have any ideas regarding the floor layer?

Thanks!

**Comment by jcwchen** [comment]
Does this ONNX model pass `onnx.shape inference.infer_shapes(onnx_model, check_type=True, strict_mode=True)`? If so, it's possible that this issue is caused by trtexec. Could you please provide your ONNX model? Thanks

**Comment by Noam-M** [comment]
Hello @jcwchen,

I don't know if the model passes these things. How do you check that?
This is the [original model](https://drive.google.com/file/d/1IT6jIOmMLcqoXAx6Xj6O0wuyNpdhtluo/view?usp=sharing)
This is the ["fixed model](https://drive.google.com/file/d/1ebfrzCLCpAbMdH_OHWozhrZf4iOHszPW/view?usp=sharing) (the one with the "fixed" clip layers)

Thanks again!

**Comment by jcwchen** [comment]
Thank you for providing the models. I did try onnx.shape_inference to run these two models and they both pass. Therefore, from ONNX perspective, these 2 models are fine. As you can see, the error complains while inferring the output of floor node, it seems to me something wrong in the Runtime. I would suggest you to open an issue in TensorRT repo to get the best help from trtexec experts. Thanks

**Comment by daquexian** [comment]
> I also tried the online version of the onnx simplfier on the model, both before and after the manual change of the clip layer, and the behavior didn't change (got the same errors for the clip and the floor respectively)
> @daquexian as a sidenote: it worked with the onnx optimizer, but using the simplifier raised the following error:
> Unknown error: "265104272", you can try to contact onnx developers

@Noam-M Hi :) Could you please try the python version? The online version is in its very early stage

**Comment by Noam-M** [comment]
@jcwchen thanks for checking my model. I have now attempted to check it myself as well, but the first thing that happened after running the following command `onnx.shape_inference.infer_shapes(onnx_model, check_type=True, strict_mode=True)` is the following output: 
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-4a6f99b546c1> in <module>
----> 1 onnx.shape_inference.infer_shapes(onnx_model, check_type=True, strict_mode=True)

TypeError: infer_shapes() got an unexpected keyword argument 'strict_mode'
```
checking the command, I got: Signature: onnx.shape_inference.infer_shapes(model, check_type=False)Docstring: <no docstring>File: /usr/local/lib/python3.6/dist-packages/onnx/shape_inference.pyType: function
So I'm not sure wer're running the same version of onnx (I'm using 1.7.0) I tried without the strict_mode=True, but unfortunately executing it caused my device to run out of RAM.

Also, could it be that the problem is with the following layer, unsqueeze, and not with the floor?


Hello @daquexian 
I tried to use the python version but it failed to install, and I'm not sure why.
I ran the following command;`pip install onnx-simplifier`
and got the following output message:
```
Collecting onnx-simplifier
  Using cached https://files.pythonhosted.org/packages/43/c8/77fa4c21af1f4a90b2fc7f6d9ebb08d5a16a0a2f5bb2d426f918082dbbf8/onnx-simplifier-0.3.4.tar.gz
Requirement already satisfied: onnx in /usr/local/lib/python3.6/dist-packages (from onnx-simplifier)
Collecting onnxoptimizer>=0.2.5 (from onnx-simplifier)
  Could not find a version that satisfies the requirement onnxoptimizer>=0.2.5 (from onnx-simplifier) (from versions: )
No matching distribution found for onnxoptimizer>=0.2.5 (from onnx-simplifier)
Note: you may need to restart the kernel to use updated packages.
```

**Comment by daquexian** [comment]
@Noam-M please upgrade your pip by
```
pip install -U pip
```
and try again :)

**Comment by Noam-M** [comment]
Hello again @jcwchen 

@daquexian I upgraded my pip and it worked.
The reason I hadn't done that up until now is that pip didn't work for me until recently. Apparently, my home WiFi blocked pip usage, and only when I used a mobile hotspot (for other reasons) then it worked.
After that, I installed the onnx simplifier and the trtexec worked well.

But then I encountered another problem.
I followed [this tutorial](https://github.com/NVIDIA/TensorRT/blob/master/quickstart/IntroNotebooks/4.%20Using%20PyTorch%20through%20ONNX.ipynb), trying to run inference on my model, but it didn't work and I got GPU-usage errors. An example is:
`LogicError: cuMemcpyDtoHAsync failed: an illegal memory access was encountered`
triggered by attemting to execute ` cuda.memcpy_dtoh_async(output, d_output, stream)`

@rajeevsrao maybe you could help?

Thank you!

**Comment by Noam-M** [comment]
Hello @jcwchen and @rajeevsrao

Any change you could please help?

Thanks!

**Comment by jcwchen** [comment]
Hi @Noam-M,
I think this error is not related to ONNX itself and please raise this issue in the Runtime repo (TensorRT) and you can get a better support from them. Sorry that I couldn't be more helpful. Thanks.

**Comment by ttanzhiqiang** [comment]
https://github.com/ttanzhiqiang/onnx_tensorrt_project
