### ISSUE TITLE
A parameter cannot be found that matches parameter name 'DProtobuf_USE_STATIC_LIBS=OFF'.

### ISSUE THREAD

**Issue by deadsoul44** [onnx/onnx#3430]
I get this when trying to set args.

onnx> set CMAKE_ARGS=-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_USE_LITE_PROTO=ON
Set-Variable : A parameter cannot be found that matches parameter name 'DProtobuf_USE_STATIC_LIBS=OFF'.
At line:1 char:51
+ ... NX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF -DONNX_ ...
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Variable], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetVariableCommand

How can I solve this issue?

**Comment by jcwchen** [comment]
Hi @deadsoul44,
Similar to https://github.com/onnx/onnx/issues/3347? Could you please upgrade your cmake and try again? Thanks.

**Comment by jcwchen** [comment]
I just figured out it should be related to PowerShell... If you are using Powershell, please use their way to set environment variable instead of `set ENV=XXX`. Thanks. For instance:
```
$env:CMAKE_ARGS='-DONNX_USE_PROTOBUF_SHARED_LIBS=ON -DProtobuf_USE_STATIC_LIBS=OFF'
```

**Comment by deadsoul44** [comment]
Thank you.
