### ISSUE TITLE
FAIL : Load model from segmentation.onnx failed:Node () Op (SequenceConstruct) [TypeInferenceError] Input type for input at index 0 is null. Type info is expected 

### ISSUE THREAD

**Issue by mathmax12** [onnx/onnx#3434]
# Ask a Question
I am testing an onnx model exported from the PyTorch.
The export is succeed :
`torch.onnx.export(net,
                    args=input_tensor,
                    f=onnx_file_name,
                    input_names=["input_0"],
                    output_names=["output_0"],
                    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
                    opset_version=11)#,`

**but with some warning**:

`C:\Users\bigtree\.conda\envs\segmentaionv01\lib\site-packages\torch\onnx\utils.py:243: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
C:\Users\bigtree\.conda\envs\segmentaionv01\lib\site-packages\torch\onnx\utils.py:243: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\yolact.py:273: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for j, i in product(range(conv_h), range(conv_w)):
C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\yolact.py:301: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  self.priors = torch.Tensor(prior_data).view(-1, 4)
C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\yolact.py:301: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self.priors = torch.Tensor(prior_data).view(-1, 4)
C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\layers\functions\detection.py:73: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for batch_idx in range(batch_size):
C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\layers\functions\detection.py:98: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if scores.size(1) == 0:
Succesfully created  yolact_FBB_float32_code11.onnx
`
### Question
When I run the onnx model in onnxrumtime 
`sess = rt.InferenceSession(model_path)`
I got:
`
 File "make_onnx.py", line 1268, in evalvideo_onnx
    sess = rt.InferenceSession(model_path)
  File "C:\Users\bigtree\.conda\envs\segmentation01\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "C:\Users\bigtree\.conda\envs\segmentation01\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 307, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolact_FBB_float32_code11_RI.onnx failed:Node () Op (SequenceConstruct) [TypeInferenceError] Input type for input at index 0 is null. Type info is expected.`
I am not very familiar with the underneath logic of the pytorch->onnx conversion. I wonder is this error relates to the previous warnings?
I suspect it may related to the first warning but not sure.
Anyone could give suggestion about the warnings/error and how to remove them will be appreciated.

**Comment by liqunfu** [comment]
attention @spandantiwari @BowenBao

**Comment by spandantiwari** [comment]
@mathmax12 - it seems you have changed the export type from default `OperatorExportTypes.ONNX` to `OperatorExportTypes.ONNX_ATEN_FALLBACK` (this is the reason for the `add_node_names` warning at the top also). Is there a reason for that? The model exported with the latter option is not a valid ONNX model and cannot be expected to run on ORT. My suggestion would be to export the model with default ONNX type and then try running it in ORT. I would also recommend using the latest PyTorch version and the latest opset 13, if possible. That should minimize any conversion issues. 

If you still see any issues in exporting your model to ONNX, please open an issue in pytorch/pytorch repo. 

If you see any issue in running the model, feel free to reopen this issue.

**Comment by mathmax12** [comment]
@spandantiwari 
Thanks for helping.
Before there is a torch.triu in my code trace, which can't sucess with the OperatorExportTypes.ONNX.
That's why I used the OperatorExportTypes.ONNX_ATEN_FALLBACK.

I remove the torch.triu from the trace and the onnx can be converted.
But I run onnx model in onnxruntime I got the cropped result.

During genrerating onnx model I saw there are several warnings as below:
`C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\yolact.py:273: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs! for j, i in product(range(conv_h), range(conv_w)):`

Do you think this makes the conversion doesn't correct?
Thanks.

**Comment by szgy66** [comment]
> @spandantiwari Thanks for helping. Before there is a torch.triu in my code trace, which can't sucess with the OperatorExportTypes.ONNX. That's why I used the OperatorExportTypes.ONNX_ATEN_FALLBACK.
> 
> I remove the torch.triu from the trace and the onnx can be converted. But I run onnx model in onnxruntime I got the cropped result.
> 
> During genrerating onnx model I saw there are several warnings as below: `C:\Users\bigtree\Documents\prototype\segmentation\segmentaion_simple_make_onnx_eval\yolact.py:273: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs! for j, i in product(range(conv_h), range(conv_w)):`
> 
> Do you think this makes the conversion doesn't correct? Thanks.

Had you solved it?

**Comment by addisonklinke** [comment]
> Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future

This means your model probably contains some operation like

```python
index = torch.tensor([0])
return other_tensor[index, :]
```

and the converter is warning you that `index` will be hardcoded to 0 in the ONNX graph. If you're treating the value as a constant even in Python, then this is safe. However if the value of `index` is conditioned on previous operations, then your model won't accurately represent what happens in Python
