### ISSUE TITLE
How can I construct loop which cond input is optional?

### ISSUE THREAD

**Issue by BakerChenHua** [onnx/onnx#3447]
#0  0x00007fff8fb3b06b in onnxruntime::NodeArg::UpdateTypeAndShape(onnx::TypeProto const&, bool, bool, onnxruntime::logging::Logger const&) ()
   from /usr/local/python3.7/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-37m-x86_64-linux-gnu.so
#1  0x00007fff8fb30f13 in onnxruntime::Graph::InferAndVerifySubgraphTypes(onnxruntime::Node const&, onnxruntime::Graph&, std::vector<onnx::TypeProto const*, std::allocator<onnx::TypeProto const*> > const&, std::vector<onnx::TypeProto const*, std::allocator<onnx::TypeProto const*> >&, onnxruntime::Graph::ResolveOptions const&) ()

I want to construct Loop node which cond is null, but when I run the model, it can't work

add_node = helper.make_node('Add', inputs=['x', 'x'], outputs=['sum'])
    sub_node = helper.make_node('Sub', inputs=['y', 'sum'], outputs=['diff'])
    mul_node = helper.make_node('Mul', inputs=['sum', 'diff'], outputs=['prod'])
    less_node = helper.make_node('Less',
                                 inputs=['sum', 'diff'],
                                 outputs=['new_cond'])
    greater_node = helper.make_node('Greater',
                                    inputs=['sum', 'diff'],
                                    outputs=['new_cond'])

    iter_count_in = helper.make_tensor_value_info('iter_count',
                                                  TensorProto.INT64, [])
    cond_in = helper.make_tensor_value_info('cond', TensorProto.BOOL, [])
    cond_int_in = helper.make_tensor_value_info('cond', TensorProto.INT32, [])
    x_in = helper.make_tensor_value_info('x', TensorProto.INT32, [None])
    y_in = helper.make_tensor_value_info('y', TensorProto.INT32, [None])

    cond_out = helper.make_tensor_value_info('cond', TensorProto.BOOL, [])
    new_cond_out = helper.make_tensor_value_info('new_cond', TensorProto.BOOL,
                                                 [])
    sum_out = helper.make_tensor_value_info('sum', TensorProto.INT32, [None])
    diff_out = helper.make_tensor_value_info('diff', TensorProto.INT32, [None])
    prod_out = helper.make_tensor_value_info('prod', TensorProto.INT32, [None])

    v1_initial = np.array([1, 1], dtype=np.int32)
    v2_initial = np.array([100, 100], dtype=np.int32)

    # test for loop
    graph = helper.make_graph(nodes=[add_node, sub_node, mul_node],
                              name="for_loop_graph",
                              inputs=[iter_count_in, cond_in, x_in, y_in],
                              outputs=[cond_out, sum_out, diff_out, prod_out])
    node_def = helper.make_node('Loop', ['trip_count', '', 'x', 'y'],
                                ['out1', 'out2', 'res_scan'],
                                body=graph)
  trip_count = helper.make_tensor_value_info('trip_count ', TensorProto.INT64, [])
  x= helper.make_tensor_value_info('x', TensorProto.INT32, [None])
  y= helper.make_tensor_value_info('y', TensorProto.INT32, [None])
  out1= helper.make_tensor_value_info('out1', TensorProto.INT32, [None])
  out2= helper.make_tensor_value_info('out2', TensorProto.INT32, [None])
  res_scan= helper.make_tensor_value_info('res_scan', TensorProto.INT32, [])

 graph_def = helper.make_graph([node_def], 'zl-model', [trip_count, x, y], [out1, out2, res_scan])

**Comment by liqunfu** [comment]
Try create a tensor info for cond and pass in value True when running the model.

**Comment by BakerChenHua** [comment]
I tried the code:
graph = helper.make_graph(nodes=[add_node, sub_node, mul_node],
                          name="for_loop_graph",
                          inputs=[iter_count_in, cond_in, x_in, y_in],
                          outputs=[cond_out, sum_out, diff_out, prod_out])
node_def = helper.make_node('Loop', ['trip_count', '', 'x', 'y'],
                            ['out1', 'out2', 'res_scan'],
                            body=graph)

it could generate onnx model, but segement fault when I run the model
