### ISSUE TITLE
Error while trying to install onnx version 1.4.1

### ISSUE THREAD

**Issue by gioriog** [onnx/onnx#3453]
### Question
[log.txt](https://github.com/onnx/onnx/files/6377970/log.txt)

Hello everyone, I am trying to install onnx version 1.4.1 but this error occurs. Can someone encountered the same problem and knows how to fix ? Thanks

**Comment by jcwchen** [comment]
Hi @gioriog,
It looks like an old issue for old ONNX: https://github.com/onnx/onnx/issues/2481

Either cherry-pick this PR: https://github.com/onnx/onnx/pull/2482 or upgrade ONNX should help. Thanks

**Comment by gioriog** [comment]
Thanks man @jcwchen . I was able to fix the problem.
