### ISSUE TITLE
Does ONNX support output activations layer by layer in ONNX model inference?

### ISSUE THREAD

**Issue by ycjcy** [onnx/onnx#3455]
# Ask a Question

### Question
Does ONNX support output activations layer by layer in ONNX model inference?

Can someone point me to what I am doing to output activations layer by layer from ONNX model inference?

**Comment by adityat77** [comment]
Can you please elaborate on what is it that you're looking to achieve ? 
By my understanding, do you want to know how to get a layer by layer / some specific layer outputs. 

If that's the case i'd like you to refer this :  ` https://github.com/microsoft/onnxruntime/issues/1455 `

**Comment by askhade** [comment]
Closing this issue as there has been no response from the author. More info is required in order to answer this.
