### ISSUE TITLE
fuse BN to conv 

### ISSUE THREAD

**Issue by dingguodong-826** [onnx/onnx#3460]
Hello, thank you very much for your work. My project needs to integrate the BN layer in the network into the convolution layer to accelerate the reasoning speed. The fusion code is as follows:
![image](https://user-images.githubusercontent.com/57715990/116676655-d155f180-a9d9-11eb-95f3-d463d6cf313e.png)
According to the above code, I successfully fused BN and the convolution layer, but when I used the onnx files before and after the fusion for visualization, I found that the output nodes of the network were different：
![image](https://user-images.githubusercontent.com/57715990/116677083-5c36ec00-a9da-11eb-9cc6-12da90166942.png)
![image](https://user-images.githubusercontent.com/57715990/116677097-60630980-a9da-11eb-8b93-0095e73fdadb.png)
The following error occurs when I use onnx-tf to convert the model to a PB file
![image](https://user-images.githubusercontent.com/57715990/116677204-838db900-a9da-11eb-8dd5-85d0f6cd0a1f.png)
The code for the conversion is as follows：
![image](https://user-images.githubusercontent.com/57715990/116677253-97391f80-a9da-11eb-9361-c153e6c31794.png)
Could you please help me to see what the reason is and what I should do，thank you

**Comment by jcwchen** [comment]
Hi @dingguodong-826,
ONNX has moved optimizer to another repo since 1.9: https://github.com/onnx/optimizer. You can first try the updated optimizer there and see whether this problem still exists. If so, please raise this optimizer-related issue there. Thanks!
