### ISSUE TITLE
NHWC tf.pb && .onnx model

### ISSUE THREAD

**Issue by dingguodong-826** [onnx/onnx#3469]
Hello, thank you very much for your work. I successfully converted the PyTorch model into a tf.pb file, but I noticed that the input of the converted model was still NCHW, but what I needed for my work was NHWC. I would like to ask about it. How to generate NHWC model. ONNX model, further, how to generate NHWC TF. PB model, I need to use the TF version 1.14.thank you ！

**Comment by yajieC** [comment]
> 

I have the same problem as you, has your problem been solved? How was it resolved?

> Hello, thank you very much for your work. I successfully converted the PyTorch model into a tf.pb file, but I noticed that the input of the converted model was still NCHW, but what I needed for my work was NHWC. I would like to ask about it. How to generate NHWC model. ONNX model, further, how to generate NHWC TF. PB model, I need to use the TF version 1.14.thank you ！
