### ISSUE TITLE
i want to convert  Darknet Yolov4-csp,mish.weights into onnx format ??

### ISSUE THREAD

**Issue by akashAD98** [onnx/onnx#3475]
i was searching on internet,i haven't got any sourse code for converting this mish & CSP weights into onxx format. it will be great help if you add these features in onnx. Thanks in advance.

**Comment by akashAD98** [comment]
@jcwchen its darknet scaled Yolo models i.e Yolov4-mish,yolov4-csp  which is state of art model ,i think onnx will help to convert this weights into onnx format.Thanks in advance.Hope you will help

**Comment by jcwchen** [comment]
Thank you for providing more details.

Related discussion about how to export yolov4-csp to ONNX: https://github.com/WongKinYiu/ScaledYOLOv4/issues/56

For yolov4-mish, I assume it needs Mish operator and this is not supported in ONNX yet. There is an open issue for it already: https://github.com/onnx/onnx/issues/2818.
