### ISSUE TITLE
How to solve this problem  Removing initializer 'Constant_80'. 

### ISSUE THREAD

**Issue by duolabmeng6** [onnx/onnx#3477]
2021-05-07 22:29:34.1767217 [W:onnxruntime:, graph.cc:3106 onnxruntime::Graph::CleanUnusedInitializers] Removing initializer 'Constant_80'. It is not used by any node and should be removed from the model.

**Comment by jcwchen** [comment]
Hi @duolabmeng6,
You could directly remove that initializer, something like:
```
removed_init = model.graph.initializer[n] # the one which is unused
model.graph.initializer.remove(removed_init)
```

**Comment by duolabmeng6** [comment]
> @ duolabmeng6，您好：
> 您可以直接删除该初始化程序，例如：
> 
> ```
> removed_init = model.graph.initializer[n] # the one which is unused
> model.graph.initializer.remove(removed_init)
> ```

thank you

**Comment by jcwchen** [comment]
I assume this question has been resolved. Please reopen it if you have other ONNX questions. Thanks!
