### ISSUE TITLE
[ORT] Inconsistency output from Gemm operator

### ISSUE THREAD

**Issue by Distancehe** [onnx/onnx#3479]
# Ask a Question

### Question
The model is loading by ORT (C#) with GraphOptimizationLevel=ORT_ENABLE_ALL.
Detailed operator property as below,
![image](https://user-images.githubusercontent.com/4394577/117530880-30d38300-b012-11eb-9831-234a4c6b897e.png)

For inputs B, C, they are const metrix with [64, 512] and [1, 64] dimensions.

For input A, we tried with 2 metrix and the operator outputs were different.
First input has [1, 512] dimension, the second one has [2, 512] dimension with same content for each dimension. For example, A is [0.1, 0.2, 0.3] and B is [[0.1, 0.2, 0.3], [0.1, 0.2, 0.3]].

The output for A is [1, 64] dimension while B is [2, 64], but each [1, 64] metrix from B output is not exactly same with A, there are always precision difference as shown below (left: output for A; right: output for B):
![image](https://user-images.githubusercontent.com/4394577/117531143-9ffda700-b013-11eb-83d1-b993ecaa6951.png)

Is this expected for this operator or any suggestion to get consistency result ?

**Comment by jcwchen** [comment]
Hi @Distancehe,
Since the difference is quite small, I am not sure whether it is really a Runtime bug. Still, this issue should be related to ONNXRuntime (not ONNX). Please open an issue there and mention which provider you were using. Thank you.
