### ISSUE TITLE
Remove Negative Values in Pad Tests

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#348]
Hi, the new backend tests contain negative values in pads attribute in pad op. 

I do not understand why anyone would use `Pad` to crop a tensor. TF does not support it, neither does numpy as per this thread:
https://stackoverflow.com/questions/24806174/is-there-an-opposite-inverse-to-numpy-pad-function

The above thread points to `Slice` as the appropriate op for the desired effect.

Maybe remove these tests?

@dzhulgakov @bddppq

**Comment by ebarsoum** [comment]
Negative values in pad doesn't make sense.

**Comment by houseroad** [comment]
@tjingrant I just checked the backend tests. Looks like there is only one pad test containing negative pad values. I fixed them in https://github.com/onnx/onnx/pull/350.

If you find more negative pad cases, please let me know. Thanks!

**Comment by tjingrant** [comment]
@houseroad Yes indeed there's only one.

**Comment by tjingrant** [comment]
Looks good now.
