### ISSUE TITLE
[Tracking] Work for 1.10 release

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#3490]
**Creating this issue to collect and track all the work items for ONNX 1.10 release.**
The release is planned for July 30 2021.
**Note:** Starting from this release we will freeze updates to operators 2 weeks prior to the release date to allow time for validations.

@onnx/sig-archinfra , @onnx/sig-operators , @onnx/steering-committee , @sveta-levitan, @wschin , @chinhuang007 and community members, please add work items here so that we can scope the release.

Thanks!

Currently planned workitems for 1.10
- IR Updates
  - New type in ONNX - SparseTensor Type (Done)
  - New type in ONNX - Optional Type (Done)
  - FunctionProto and ModelProto updates (#3532)
- opset 15 updates
  - Function op Bernoulli (Done)
  - Add reduction with scatter (#3484)
  - Function op Dim - Extended shape op to return slice. Change merged.
  - Other opset 15 updates
- Symbolic shape inference
  - Symbol generation and propagation (#3518) - Done
  - Data propagation - Infra work done and data propagation function added to all the phase 1 identified ops

**Comment by jcwchen** [comment]
Symbolic shape inference: https://github.com/onnx/onnx/issues/3506

**Comment by askhade** [comment]
@rajeevsrao : FYI

**Comment by rajeevsrao** [comment]
Wiki with schedule and logistics tracking for v1.10.0 release: https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.10

**Comment by matteosal** [comment]
Can this be considered for the 1.10 release? https://github.com/onnx/onnx/pull/3344

**Comment by askhade** [comment]
will review #3344 today. We discussed this PR in last week's OP SIG meeting and came to a conclusion that we should push this in 1.10

**Comment by askhade** [comment]
added comments for #3344
