### ISSUE TITLE
cuda version and onnx version

### ISSUE THREAD

**Issue by alicera** [onnx/onnx#3491]
I install nvidia driver 460.73.01 and use the "watch nvidia-smi" to see cuda version 11.2
But I enter the NGC docker  pytorch 20.10, then use the command "nvcc --version
". I see the  release 11.1, V11.1.74.
If I export the onnx model, which cuda version is used?

![image](https://user-images.githubusercontent.com/59388989/118216090-6a3e3f80-b4a5-11eb-9a03-ad5697f8d540.png)

https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_20-10.html#rel_20-10

![image](https://user-images.githubusercontent.com/59388989/118216463-20a22480-b4a6-11eb-8d9f-e8d7da3f49b6.png)

**Comment by jackwish** [comment]
The version `nvidia-smi` displays mean which CUDA runtime version the driver can support (up to).
The `nvcc` version is the CUDA toolkit version (similar to the CUDA runtime version), it can be different (<=) from the driver version.

I don't think exporting the ONNX model won't involve the CUDA, unless running the model with GPU.

Btw, maybe the Nvidia forum is where such questions should go?

**Comment by alicera** [comment]
Thanks for your reply.
