### ISSUE TITLE
Slice Error need help

### ISSUE THREAD

**Issue by YZW-explorer** [onnx/onnx#3494]
Hello author, my error is as follows：
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:Slice_0 : Node (Slice_0) has input size 1 not in range [min=3, max=5].
The node displayed in Netron is：
![image](https://user-images.githubusercontent.com/74363764/118440747-b5ad5380-b71a-11eb-8708-c7c8a207452a.png)
I don't know what to do

**Comment by jcwchen** [comment]
Hi @YZW-explorer,
Similar to https://github.com/onnx/onnx/issues/2245. Slice-10 has moved its attribute to its input since opset 10... Perhaps you could try to use onnx.version_converter to transform your ONNX model to higher opset_version (like 10). I did see there is an adapter for it so it should help: https://github.com/onnx/onnx/blob/master/onnx/version_converter/adapters/slice_9_10.h. Thank you.

**Comment by askhade** [comment]
@YZW-explorer : Which onnx opset does this model import? How did you get this model? Did you modify it after converting to onnx?

**Comment by YZW-explorer** [comment]
> Hi @YZW-explorer,
> Similar to #2245. Slice-10 has moved its attribute to its input since opset 10... Perhaps you could try to use onnx.version_converter to transform your ONNX model to higher opset_version (like 10). I did see there is an adapter for it so it should help: https://github.com/onnx/onnx/blob/master/onnx/version_converter/adapters/slice_9_10.h. Thank you.

Hello, thank you very much for your answers! I tried the method you provided, but it prompted a new error.
![image](https://user-images.githubusercontent.com/74363764/119309390-d0467600-bca0-11eb-8bf8-01286f01eddf.png)

**Comment by YZW-explorer** [comment]
> @YZW-explorer : Which onnx opset does this model import? How did you get this model? Did you modify it after converting to onnx?
Hello, thank you for your reply! I'm trying routines modeled here at https://github.com/Xilinx/finn/blob/master/notebooks/end2end_example/cybersecurity/2-export-to-finn-and-verif y.ipynb

I am trying to deploy the QNN trained by using Brevitas on the Pynq board. I exported QNN using onnx version 1.8.1. I then compiled onnx with Finn, and during validation, an error was reported indicating an error in Slice.

**Comment by jcwchen** [comment]
To solve that version_converter error, you could try the following code to add input from initializer:
```
import onnx
def add_input_from_initializer(model : onnx.ModelProto):
    """
    Currently onnx.shape_inference doesn't use the shape of initializers, so add
    that info explicitly as ValueInfoProtos.
    Mutates the model.
    Args:
        model: The ModelProto to update.
    """
    # All (top-level) constants will have ValueInfos before IRv4 as they are all inputs
    if model.ir_version < 4:
        return

    def add_const_value_infos_to_graph(graph : onnx.GraphProto):
        inputs = {i.name for i in graph.input}
        existing_info = {vi.name: vi for vi in graph.input}
        for init in graph.initializer:
            # Check it really is a constant, not an input
            if init.name in inputs:
                continue

            # The details we want to add
            elem_type = init.data_type
            shape = init.dims

            # Get existing or create new value info for this constant
            vi = existing_info.get(init.name)
            if vi is None:
                vi = graph.input.add()
                vi.name = init.name

            # Even though it would be weird, we will not overwrite info even if it doesn't match
            tt = vi.type.tensor_type
            if tt.elem_type == onnx.TensorProto.UNDEFINED:
                tt.elem_type = elem_type
            if not tt.HasField("shape"):
                # Ensure we set an empty list if the const is scalar (zero dims)
                tt.shape.dim.extend([])
                for dim in shape:
                    tt.shape.dim.add().dim_value = dim

        # Handle subgraphs
        for node in graph.node:
            for attr in node.attribute:
                # Ref attrs refer to other attrs, so we don't need to do anything
                if attr.ref_attr_name != "":
                    continue

                if attr.type == onnx.AttributeProto.GRAPH:
                    add_const_value_infos_to_graph(attr.g)
                if attr.type == onnx.AttributeProto.GRAPHS:
                    for g in attr.graphs:
                        add_const_value_infos_to_graph(g)


    return add_const_value_infos_to_graph(model.graph)
add_input_from_initializer(your_onnx_model)
converted_model = version_converter.convert_version(10)
```

Still, it's a workaround.. The model is not converted correctly in the fast place. It should be converted by onnx_opset
 >= 10. Could you please provide the ONNX model? Thanks!

**Comment by askhade** [comment]
@YZW-explorer : Your model is not in the right state... looks like your are importing a later opset but the schema for slice is from an old opset... In this case version converter wont work either... I suggest reconverting the model from original framework to onnx...
