### ISSUE TITLE
sess.get_inputs()[0].name results in error, inputs apparently missing?   

### ISSUE THREAD

**Issue by Mercury-ML** [onnx/onnx#3495]
My trained Pix2PixHD model is apparently missing inputs.  How can I fix this so I can run inference?

I trained a Pix2PixHD model and exported to ONNX by adding --export_onnx flag to testing (ONNX export is actually embedded in the GitHub repo for the Pix2PixHD model)

The inputs seem to be missing and I get an error, so 

input_name = sess.get_inputs()[0].name
print("input name", input_name)

results in 
    input_name = sess.get_inputs()[0].name
IndexError: list index out of range
_______________

However, when I check out the model with 

import onnx

model_path = 'ONNX-model.onnx'
onnx_model = onnx.load(model_path)

try:
    onnx.checker.check_model(onnx_model)
except onnx.checker.ValidationError as e:
    print('The model is invalid: %s' % e)
else:
    print('The model is valid!')

output = onnx_model.graph.output

input_all = [node.name for node in onnx_model.graph.input]
input_initializer =  [node.name for node in onnx_model.graph.initializer]
net_feed_input = list(set(input_all)  - set(input_initializer))

print('Inputs: ', net_feed_input)
print('Outputs: ', output)

I get:

/usr/local/bin/python3.8 /Users/myname/PycharmProjects/onnx/check_onnx.py
The model is valid!
Inputs:  []
Outputs:  [name: "214"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 3
      }
      dim {
        dim_value: 1024
      }
      dim {
        dim_value: 1024
      }
    }
  }
}
]

Note the inputs are missing.
Here's the beginning of the Netron graph
![netron-graph](https://user-images.githubusercontent.com/60528309/118567526-2e200e80-b733-11eb-9f07-e4dc7e20520a.jpg)

Any help would be greatly appreciated!!!
![netron-graph](https://user-images.githubusercontent.com/60528309/118568249-ab984e80-b734-11eb-9891-f6c8d89c70ac.jpg)

**Comment by askhade** [comment]
@Mercury-ML : The model export needs to be fixed to include the inputs. 
Regarding the checker... looks like we need to fix the checker to catch such issues... can you share your model so that I can take a closer look?

**Comment by Mercury-ML** [comment]
Hi Ashwini,
Thanks for checking this out as well as your advice!  I’ve asked the person who embedded the model export in Pix2PixHD for help.

Here’s the model:
https://drive.google.com/file/d/1hFK9CM_4PYuWGyevBj4byGswozw4ex0i/view?usp=sharing <https://drive.google.com/file/d/1hFK9CM_4PYuWGyevBj4byGswozw4ex0i/view?usp=sharing>


I will let you know if I find a work around.

Best regards,
Stephen Rozmiarek
