### ISSUE TITLE
merge two submodels

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3496]
# Merge two submodels into one model

### Question
in `onnx` we have `onnx.utils.extract_model` to cut model on two different submodels by `inputs` and `outputs` of nodes. Can we merge this two submodels in single model by some method?

### Concat solution with `loop`
I think we can solve this by iterating though `inputs`, `nodes`, `outputs` for two models and after this just concat them all to one model, but maybe `onnx` have some interesting way to do it?

**Comment by jcwchen** [comment]
Hi @germanjke,
As you said, official ONNX does not provide a utility function to merge two submodels, although I did see there are some ways to do it (e.g., https://github.com/scailable/sclblonnx). If you are interested, welcome to contribute :)
