### ISSUE TITLE
Is it possible to convert model from PyTorch and Scikit-learn together into ONNX framework?

### ISSUE THREAD

**Issue by laurence-lin** [onnx/onnx#3497]
# Ask a Question

### Question
I'm watching an introduction of BERT with transformers: https://medium.com/huggingface/distilbert-8cf3380435b5
Which combines a model written with PyTorch backend, and combine the model with logistic regression from scikit-learn to create an sentiment classification model.
I'd learned that ONNX supports convert from scikit-learn and pytorch to ONNX respectively, but what if I have a task that requires both of them?

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  transformers distilbert, Scikit-learn LogisticRegression
**Model opset** (*e.g. 7*): 11

**Comment by jcwchen** [comment]
Hi @laurence-lin,
ONNX is a specification supported by many AI frameworks including PyTorch and Scikit-learn. As long as the targeted models are supported by ONNX (most of BERT models from PyTorch and logistic regression from scikit-learn should be), theoretically it is doable to work with them together in ONNX.

**Comment by jcwchen** [comment]
I assume this question has been resolved...  Please reopen it if you still have questions related to ONNX. Thanks!
