### ISSUE TITLE
unable to use resize with sizes (must set roi)?

### ISSUE THREAD

**Issue by shi-yan** [onnx/onnx#3500]
# Bug Report

### Describe the bug

the document says:
roi (optional, non-differentiable) : T2
1-D tensor given as [start1, ..., startN, end1, ..., endN], where N is the rank of X. The RoIs' coordinates are normalized in the coordinate system of the input image. It only takes effect when coordinate_transformation_mode is "tf_crop_and_resize"

and all Resize examples set empty string for roi,

however I got:

```
onnx.onnx_cpp2py_export.checker.ValidationError: Node (resize_224)'s input 1 is marked single but has an empty string in the graph

```

with 

```

new_node_resize = onnx.helper.make_node(
    'Resize',
    name='resize_224',
    mode='nearest',
    inputs=['conv1x1_out','','','resize224_sizes'],
    outputs=['output1']
)
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): ubuntu 18 but with docker/nvidia-tensorrt 21
- ONNX version (*e.g. 1.7*):                1.9.0
- Python version: 3.8
- GCC/Compiler version (if compiling from source): 
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @shi-yan,
Similar to https://github.com/onnx/onnx/issues/2451... I think it's an existing bug. To work around, have you tried to set an empty tensor for roi and scales? Thanks.

**Comment by askhade** [comment]
@daquexian : can you pick this?

**Comment by askhade** [comment]
@daquexian : Ping again... can you pick this up? There are multiple ONNX issues open regarding resize op. ONNX 1.10 code freeze is on July 15th can this be done before that?

**Comment by daquexian** [comment]
@askhade @jcwchen I can pick this up

**Comment by daquexian** [comment]
@askhade I found it is already fixed this (#3500) and #2451 in https://github.com/onnx/onnx/pull/3026. Could you please help check it again? It is long time ago 😂

**Comment by askhade** [comment]
indeed roi and scales has already been marked optional. Closing this issue

**Comment by SangbumChoi** [comment]
Hi, even though roi and scales is optional function in onnx, is there any way to put arbitary value?
