### ISSUE TITLE
Confusion about TopK-1 tie breaking

### ISSUE THREAD

**Issue by J3698** [onnx/onnx#3501]
# Ask a Question

### Question
I am trying to implement onnxjs TopK-1, it is described here:
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#TopK-1
The spec says that lower indices appear first. Does this mean that they appear first in the sort, or that they appear first if there is a tie as to which element should be in the topk? I think it is the former but would like to make sure.
E.g., is it this:
topk([0, 1, 2, 2], 1) => [2], [3]
or this:
topk([0, 1, 2, 2], 1) => [2], [2]

I have tried seeing what framework this spec is from, but haven't found it.

### Further information
The relevant area is operators

- Is this issue related to a specific model?  
No

**Comment by jcwchen** [comment]
I think the index here should be the original index in input...so topk([0, 1, 2, 2], 1) => [2], [2] should be the right one. I checked both tensorflow and pytorch's topk. Both of them are using the original index. For instance, tensorflow: https://www.tensorflow.org/api_docs/python/tf/math/top_k (If two elements are equal, the lower-index element appears first.).

**Comment by J3698** [comment]
Thanks! Makes perfect sense.
