### ISSUE TITLE
RuntimeError: Unexpected error on find the converter for op <class 'mrcnn.model.BatchNorm'>

### ISSUE THREAD

**Issue by yuyamaoka** [onnx/onnx#3502]
# Bug Report

### Describe the bug
I'm trying to convert a MaskRCNN model (.h5) to .onnx with keras2onnx.

Execution code
`keras2onnx.convert_keras(model.keras_model, "test1.onnx", target_opset=11)`

Error message
`keras2onnx.convert_keras(model.keras_model, "test1.onnx", target_opset=11)`

MaskRCNN's BatchNorm corresponds to BatchNormalization in onnx's [Operator Schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md), 
but the names are different, so we get an error.

### System information
- OS Platform and Distribution : windows10
- ONNX version : 1.9.0
- Python version:  : 3.7.10

### Reproduction instructions
using [maskRCNN](https://github.com/matterport/Mask_RCNN)

import config
import mrcnn.model as modellib  
import os
from mrcnn import utils

model = modellib.MaskRCNN(mode="training", config=config,
                              model_dir="logs/model")
config = Config()

MODEL_PATH = 'mask_all.h5'
model.load_weights(MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc",
                                "mrcnn_bbox", "mrcnn_mask"])

import keras2onnx
keras2onnx.convert_keras(model.keras_model, "mask_all.onnx", target_opset=11)

### Expected behavior
Mask_all.onnx is generated by converting mask_all.h5.

**Comment by jcwchen** [comment]
Hi @yuyamaoka,
As you mentioned, ONNX does have BatchNormalization operator and keras-onnx also has BatchNorm support so it should be a converter problem. Did you use the latest keras-onnx? Please open an issue about this in keras-onnx to get assistance from them. Thank you.
