### ISSUE TITLE
slice by tensor values

### ISSUE THREAD

**Issue by iperov** [onnx/onnx#3503]
# Feature Request

### What is the problem that this feature solves?

I need to slice a channels using provided tensor int value.
Current onnx slice implementation accepts only constant values.

### Describe the alternatives you have considered

alternative is eval value before slicing, slice on cpu(numpy), feed result to the next part of the network

### Will this influence the current api?
i don't know

### Feature Area
model usage

**Comment by jcwchen** [comment]
Hi @iperov,
I think Slice-10 or newer Slice does support dynamic slice (accepts tensor input for slice)? https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-10

**Comment by Fritskee** [comment]
> Hi @iperov, I think Slice-10 or newer Slice does support dynamic slice (accepts tensor input for slice)? https://github.com/onnx/onnx/blob/master/docs/Changelog.md#slice-10

Do you have an example of this? I'm pretty confused with the documentation.

Some context:
I have a 4D tensor which is being sliced in the forward() function. Generally this model cannot be traced with ONNX, however as I understand from your reply, it should be possible iwth slice-10?

**Comment by jcwchen** [comment]
Hi @Fritskee,
Here is a simple example: https://github.com/onnx/onnx/blob/5cf5feef5ec3fd5527b2fdb6c29780e3b705059f/onnx/backend/test/case/node/slice.py#L18. What did you mean by cannot be traced with ONNX? Does it mean it cannot be converted to ONNX?

**Comment by Fritskee** [comment]
> What did you mean by cannot be traced with ONNX? Does it mean it cannot be converted to ONNX?

It can be converted, but the ONNX model cannot perform the slice operation on the tensors itself, which the PyTorch model does. This results in the model taking only a chunck of the tensor that should be sliced (for example going from [0:slice-width][0:slice-height], whereas it should be [8:slice-width+8][12:slice-height+12]. This results in the ONNX model not being able to perform any meaningful inferences (since they are always wrong). 


Here is an example of the warning:

> TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.

And this is the code causing the warning:
`  out[:, :-1, :fold] = x[:, 1:, :fold]`

**Comment by jcwchen** [comment]
Thank you for the details. Although the slice definition in ONNX might be quite different from Pytorch's, IIUC, ideally the converter should handle this conversion. Slice in ONNX does have sufficient inputs/attributes (starts, ends, steps, axes) to represent the case you provided (please correct me if I am wrong). So if the converted ONNX model seems incorrect to you, please raise an issue in the PyTorch-ONNX exporter (in PyTorch repo) about it.
