### ISSUE TITLE
Exporting the operator inverse to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by AyanKumarBhunia** [onnx/onnx#3504]
# New Operator

### Describe the operator
Why is this operator necessary? What does it accomplish?

https://pytorch.org/docs/stable/generated/torch.inverse.html 

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?

### Notes
Any additional information

**Comment by jcwchen** [comment]
Same as https://github.com/onnx/onnx/issues/3300. Please track this issue there. Thank you!
