### ISSUE TITLE
DynamicQuantizeLinear function does not have shape inference function

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#3505]
# Bug Report

### Describe the bug
DynamicQuantizeLinear function op does not have shape inference function defined. In absence of shape inference, function body is used to get the shape inference for the function op and although it works as a fallback option it hurts perf.

### Expected behavior
Add shape inference function for DynamicQuantizeLinear 

### Notes

Any additional information

**Comment by askhade** [comment]
@annajung : Can you pick this up?

**Comment by annajung** [comment]
Yeah, I'll give it a try! :D

**Comment by askhade** [comment]
Thanks we are targeting this for ONNX 1.10 release which is planned for July end.

**Comment by annajung** [comment]
Hi @askhade, started working on this and have a question about if there is a good way to set the dim value for the outputs? Is the right way is to calculate each output in the shape inference function?

**Comment by askhade** [comment]
Each dim value represents the shape for that dimension in TensorShapeProto. Depending on the kind of operator the way output dims are calculated can be different... in some cases we simply propagate input shape to output shape, in some an attribute or input to op explicitly states the output shape and in others we explicitly calculate the value for every dimension.
