### ISSUE TITLE
Symbolic shape inference support

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#3506]
**Current ONNX shape inference limitations**
1. Will stop if it encounters symbolic dimensions. e.g., A (5*2) concat B (N*2) = C (?*2) 
2. Will stop if it bumps into some dynamic scenarios. e.g., Reshape to a dynamically computed shape

**Work items**

1. Extend shape inference with symbol generation and propagation
    - Extend graph-level shape inference
    - e.g., `5*2 + N*2` -> Create a new symbol M to represent its inferred shape
2. Partial data computation and propagation
    - Extend a new optional function `PartialDataPropagationFunction` just like existing `TypeAndShapeInferenceFunction`
    - Targeted operators: Add, Cast, Concat, Gather, Mul, Reshap, Shape, Slice, Size, Squeeze, UnSqueeze
3. (Independent) Propose a new ONNX Op to facilitate shape computation
    - There are examples that they need a few operators to extract certain dimension
    - To simplify these operators, add a new op Dimension for extracting a particular dimension value from the shape of input

I am doing 1. now and we plan to support it in ONNX 1.10.

cc @askhade @gramalingam

**Comment by askhade** [comment]
Closing this as all the identified work has been done. As more items come up in this area lets create a new issue
