### ISSUE TITLE
Export PyTorch model with multiple outputs in a dictionary

### ISSUE THREAD

**Issue by EmmaBYPeng** [onnx/onnx#3507]
I have a pytorch model that returns a dictionary during its forward pass. e.g.
```python
class DictModel(nn.Module):
  ...

  def forward(self, x, y) -> Dict[str, torch.Tensor]:
    ...
    return {"output1": a, "output2": b, ...}
```
I export it to onnx by
```python
torch.onnx.export(
      model,
      {"x": mock_x_data, "y": mock_y_data},
      file_path,
      opset_version=12,
      input_names=["x", "y"],
      output_names=["outputs_dict"],
)
```
However, when I do inference with onnxruntime, the output becomes a list of Tensors instead of a dictionary
```python
session = onnxruntime.InferenceSession(onnx_file_name)
output_dict = session.run(None, {"x": mock_x_data, "y": mock_y_data})  # this is a list of tensors
```

My questions are
- What happens internally during inference? Is the onnx model returning the list of values from the dictionary?
- Is it possible to have the onnx model output a dictionary as the original PyTroch model does? If not, is there a workaround such that we don't have to make the original model return a list?

**Comment by jcwchen** [comment]
Hi @EmmaBYPeng,
I think this is a question for ONNXRuntime. According to the API [here](https://github.com/microsoft/onnxruntime/blob/444cdf712ffe8a8880cdc5ff779e4711e5778fb7/onnxruntime/python/onnxruntime_pybind_state.cc#L1463), it seems that session.run will return a vector (list) anyway... You could rather open an issue in ONNXRuntime to get the best help from them. Thank you!
