### ISSUE TITLE
How to export a model with multiple entry points?

### ISSUE THREAD

**Issue by francisr** [onnx/onnx#3509]
# Ask a Question

### Question
I have a language model that I want to export to onnx. For efficiency reasons in my application, I need to cache some intermediate tensors, and reuse them later, basically bypassing some of the computation graph.   

In the Tensorflow runtime you can feed a tensor to any node of the graph, in `session.run`.  
In Tensorflow XLA, you can define all the operations you need, and you can get a single model out, with one C++ class per operation.  
In TorchScipt you can just define all the functions you need in the class and `@torch.jit.export` them.  

What's the way to do this in onnx? I found no example dealing with this use case.  

### Further information
To avoid having creating one onnx model per function I need, I had a try at this (simplified example, I have 4 different functions I need in the model API):
```
# class def
class LMCore(nn.Module):
    # Rest of the definition of the class 
    # [...]

    def forward(self, input_word_embeddings : Optional[torch.Tensor] = None):
        if input_word_embeddings is not None:
            return self.process_input(input_word_embeddings)

        return self.get_initial_state()

# onnx export
core = LMCore()
core_ts = torch.jit.script(core)

batch_size = 1
input_word_embeddings = torch.zeros(batch_size, core .embedding_size)
input_names = ["input_word_embeddings"]
output_names = ["output_tensor"]
input_dict = {
    "input_word_embeddings" : input_word_embeddings
}
torch.onnx.export(
    core_ts,
    (input_dict,),
    FLAGS.output_onnx,
    opset_version=13,
    input_names=input_names,
    output_names=output_names,
    verbose=True,
    example_outputs=(input_word_embeddings),
    dynamic_axes={
        "input_word_embeddings" : {0:'batch_size'},
        "output_tensor": {0:'batch_size', 1:'output_dim'}
    },
    do_constant_folding=False
)

# onnx runtime
import onnxruntime as ort
options = ort.SessionOptions()
options.intra_op_num_threads = 1
options.inter_op_num_threads = 1
options.log_severity_level = 3
options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
session = ort.InferenceSession(FLAGS.output_onnx, options)
res = session.run(None, input_feed={"input_word_embeddings": None})
```

But I get that error when I call `session.run`:
```
RuntimeError: Unable to handle object of type <class 'NoneType'>
```

The TorchScripted model works fine with `None` parameters, but the onnx model doesn't seem to recognise that it's optional, I don't know if the limitation is in the conversion, the onnx model or the onnx runtime.

**Comment by jcwchen** [comment]
Hi @francisr,
I think ONNXRuntime does not allow using None as its input: https://github.com/microsoft/onnxruntime/blob/d1f0251e3913934e73cee64398e915032618cb01/onnxruntime/python/onnxruntime_pybind_mlvalue.cc#L781

Have you encountered any warning during the conversion (pytorch to ONNX)? I don't know how they handle `if input_word_embeddings is not None` condition. From ONNX perspective, it should be doable. Could you please provide the produced ONNX model? Also I would suggest you open an issue under pytorch to get better help from the converter experts. Thanks!

**Comment by gramalingam** [comment]
Yes to Jacky's response. I don't think currently PyTorch models containing ```Optional[Tensor]``` types can be exported to ONNX. (However, Optional tensor types was just recently added to ONNX, partly to enable exporting such models.) With regards to the original question, ONNX does allow you to encode conditional statements (like the IF in the PyTorch model). However, I think onnxruntime does not directly support feeding arbitrary intermediate variables's values as inputs. You could split the model into two models, in principle. (E.g., the utility https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#utility-functions can be used with ONNX models to extract a submodel.) I guess these are workarounds.

**Comment by francisr** [comment]
Thanks, so in summary in the limitations don't come from ONNX, but from onnxruntime not supporting feeding intermediate values. And in my workound the bottleneck is the Pytorch conversion rather than the ONNX IR.

**Comment by gramalingam** [comment]
So, let me correct myself. Onnxruntime does have a partial-graph execution, but it is enabled only in the training build. Please take a look at https://github.com/microsoft/onnxruntime/pull/7324#issue-614051242 and https://github.com/microsoft/onnxruntime/pull/7324#issue-614051242
