### ISSUE TITLE
How is the Conv operator's output shape calculated in the opset 1 version

### ISSUE THREAD

**Issue by ChristiaanBoe** [onnx/onnx#3511]
Hello everyone,

In the operators document of the ONNX github (https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Conv-1) the output shape of the Conv operator gets described as.

> Output data tensor that contains the result of the convolution. The output dimensions are functions of the kernel size, stride size, and pad lengths.

What are these functions that determine the output shape.

For example in the neural network in the attached image, What is the output shape of  Conv_34?
![convnode](https://user-images.githubusercontent.com/9592052/120221398-a19b4300-c23e-11eb-99ad-831ebf1fc019.JPG)

Help would very much be appreciated.

**Comment by jcwchen** [comment]
Hi @ChristiaanBoe,
For the Conv formula, the document here would be helpful: https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html. 

Using onnx.shape_inference should provide the output shape of Conv_34. For details of Conv-1 shape inference, you can check this function here: https://github.com/onnx/onnx/blob/aa0f464044b1badeb27d2ef86f96066f9bed97a9/onnx/defs/nn/old.cc#L264

**Comment by askhade** [comment]
You can also find some info here: 
https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md
