### ISSUE TITLE
RuntimeError: Exporting the operator grid_sampler to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by Darshcg** [onnx/onnx#3514]
Hi ONNX team,

I am trying to convert the Pytorch model to the ONNX model. But whie exporting I am facing an error as: **RuntimeError: Exporting the operator grid_sampler to ONNX opset version 12 is not supported.**

May I know how to resolve this issue?

Thanks and Regards,
Darshan C G

**Comment by askhade** [comment]
this is because ONNX does not have a 1:1 mapping op for this... Please open this issue in pytorch repo. Make sure you are using the latest  version of pytorch exporter.  I also suggest to you the latest version of ONNX operator set which is 14
