### ISSUE TITLE
AssertionError: Could not find "cmake" executable!

### ISSUE THREAD

**Issue by seyeeet** [onnx/onnx#3520]
going trough the installation locally I get the following error when I do  `python setup.py install`
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    assert CMAKE, 'Could not find "cmake" executable!'
AssertionError: Could not find "cmake" executable!

**Comment by jcwchen** [comment]
Hi @seyeeet,
Do you have installed cmake in your environment?

**Comment by seyeeet** [comment]
no!  thanks, solved
