### ISSUE TITLE
Typo in MaxPool Operator documentation

### ISSUE THREAD

**Issue by GuanLuo** [onnx/onnx#3523]
### Question
There seems to be a typo in formula to [calculate output spatial shape](https://github.com/onnx/onnx/blob/master/docs/Operators.md#maxpool):
where `... dilations[i] + 1 ...` should be `...dilations[i] - 1...` (see the shape section in PyTorch's [documentation](https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html))

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*):  maxpool operator

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @GuanLuo,
I also think this is a typo... Just propose a PR to fix it. Thank you for catching this!

**Comment by gramalingam** [comment]
Hmmm ... I don't think so. Isn't there a parentheses around, like ``` ... - ( ... dilations[i] + 1)``` ? If you remove the parentheses, the minus of +1 becomes minus 1.

**Comment by jcwchen** [comment]
> Hmmm ... I don't think so. Isn't there a parentheses around, like ` ... - ( ... dilations[i] + 1)` ? If you remove the parentheses, the minus of +1 becomes minus 1.

I think you are right. Thank you @gramalingam.

**Comment by gramalingam** [comment]
Ok, I will close this. Please reopen in case there is a problem.
