### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator SwishEfficient

### ISSUE THREAD

**Issue by neso613** [onnx/onnx#3526]
Hey there,
I am working on 3D models for computer vision tasks.
I have 3D-Resnet model, I am trying to convert this into ONNX but got this error-
**RuntimeError: ONNX export failed: Couldn't export Python operator SwishEfficient**
Any suggestion will be very appreciated!!
Note: I am using torch 1.7 and its native ONNX with opset 13

**Comment by jcwchen** [comment]
SwishEfficient op is not supported by pytorch to ONNX converter. You could check the supported operator list here: https://pytorch.org/docs/stable/onnx.html#supported-operators. Please raise an issue under pytorch repo to request this support. Thanks.
