### ISSUE TITLE
Bug with upgrading the Loop operator

### ISSUE THREAD

**Issue by matteosal** [onnx/onnx#3529]
This script creates a `Loop` operator containing a `Squeeze` and an `Unsqueeze` in opset 12 (where they had a static `axes` attribute) and upgrades it to 13 (where the attribute was promoted to input):
```
import onnx
from onnx import version_converter, helper, TensorProto, shape_inference

iter_count = onnx.helper.make_tensor_value_info('iter_count', onnx.TensorProto.INT64, [])
cond_in = onnx.helper.make_tensor_value_info('cond_in', onnx.TensorProto.BOOL, [])
x_in = onnx.helper.make_tensor_value_info('x_in', onnx.TensorProto.FLOAT, [2, 1])
cond_out = onnx.helper.make_tensor_value_info('cond_out', onnx.TensorProto.BOOL, [])
x_out = onnx.helper.make_tensor_value_info('x_out', onnx.TensorProto.FLOAT, [2, 1])
squeeze = onnx.helper.make_node(
    'Squeeze',
    inputs=['x_in'],
    outputs=['squeeze_out'],
    axes=[1]
)
unsqueeze = onnx.helper.make_node(
    'Unsqueeze',
    inputs=['squeeze_out'],
    outputs=['x_out'],
    axes=[1]
)
identity = onnx.helper.make_node(
    'Identity',
    inputs=['cond_in'],
    outputs=['cond_out']
)
loop_body = onnx.helper.make_graph(
    [squeeze, unsqueeze, identity],
    'loop_body',
    [iter_count, cond_in, x_in],
    [cond_out, x_out]
)

max_iter = onnx.helper.make_tensor_value_info('max_iter', onnx.TensorProto.INT64, [])
x_start = onnx.helper.make_tensor_value_info('x_start', onnx.TensorProto.FLOAT, [2, 1])
x_end = onnx.helper.make_tensor_value_info('x_end', onnx.TensorProto.FLOAT, [2, 1])
loop = onnx.helper.make_node(
    'Loop',
    inputs=['max_iter', '', 'x_start'],
    outputs=['x_end'],
    body=loop_body
)
graph = onnx.helper.make_graph(
    [loop],
    'top_graph',
    [max_iter, x_start],
    [x_end]
)
model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 12)])

onnx.checker.check_model(model)
shape_inference.infer_shapes(model, strict_mode=True)

converted = version_converter.convert_version(model, 13)
onnx.checker.check_model(converted)
shape_inference.infer_shapes(converted, strict_mode=True)
```
Shape inference on the upgraded model fails with:
```
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:Loop): [ShapeInferenceError] Graph has 5 inputs but 3 were provided
```

This is because the upgraders for `Squeeze` and `Unsqueeze` create additional inputs in the subgraph for their axes attribute, increasing the number of inputs to the subgraph from 3 to 5. But `Loop` requires the number of subgraph inputs to be the same as its own inputs (2 + N, where N are the loop-carried dependencies), hence the error. I see 3 ways around this:

1) Modifying the version converter to add the extra inputs to `Loop`. This can technically work but it's very clumsy conceptually, because extra `Loop` inputs are loop-carried dependencies and these extra inputs are not supposed to be carried between iterations at all (and they would also require extra `Identity` ops to provide them to outputs in the subgraph)
2) Only add initializers (and don't add graph inputs) for the axes input in the adapters of `Squeeze` and `Unsqueeze`. The documentation allows this but I know currently there are problems if an initializer doesn't also appear in the inputs, so I don't know how viable this is in the current state
3) Modify the version converter to remove the extra inputs in the subgraph. I have tried to do it using `subggraph->eraseInput(i)` but this fails because it requires that the input has no uses. It seems that this requirement should be lifted in case there is an initializer, again because the documentation allows an initializer without an associated input.

Thoughts?

**Comment by gramalingam** [comment]
Just to make sure, I understand this correct: what happens to ```Squeeze``` and ```Unsqueeze``` upgrade when there is no ```Loop```? Is the axes attribute turned into an initializer? If so, (2) seems a reasonable choice. I would like to understand what problems exist in this scenario (is it an issue with the converter or in ONNX side?). Another workaround would be to turn them into initializers in the main graph. The Loop subgraph is still allowed to reference them, if I remember right. (I don't know how easy it is to do this in the converter).

**Comment by gramalingam** [comment]
There is also the option of turning the axes attribute into ```Constant``` nodes.

**Comment by matteosal** [comment]
> Just to make sure, I understand this correct: what happens to Squeeze and Unsqueeze upgrade when there is no Loop? Is the axes attribute turned into an initializer? If so, (2) seems a reasonable choice. I would like to understand what problems exist in this scenario (is it an issue with the converter or in ONNX side?). Another workaround would be to turn them into initializers in the main graph. The Loop subgraph is still allowed to reference them, if I remember right. (I don't know how easy it is to do this in the converter).

The attribute is turned into an initializer and a graph input is created for that initializer. I agree that (2) is a reasonable choice but the IR is outdated and doesn't support initializers without a corresponding input (as reported in https://github.com/onnx/onnx/issues/2873). This is also the reason why `subggraph->eraseInput(i)` requires the input to have no uses while it really shouldn't. I didn't actually try to implement (2) but it seems clear that it's going to fail for this reason.

> There is also the option of turning the axes attribute into Constant nodes.

This is a good idea and it should work around the IR limitation successfully (although it should be good to lift such limitation).

**Comment by matteosal** [comment]
What I don't like with solution (2) or with using `Constant` ops is that it doesn't automatically take care of the problem: all future adapters should also not add graph inputs, which requires a constant human check done by PR reviewers (not to mention that several other existing adapters are probably adding graph inputs and should be changed).

On the other hand solution (3) would allow anyone to implement their adapters however they please, automatically enforcing consistency in loop subgraphs if needed (and possibly other consistency requirements that other ops make to their subgraphs). But solution (3) requires the ability to remove inputs that are used, which is currently not possible due to the outdated IR.

**Comment by gramalingam** [comment]
A ```Constant``` and an "initalizer that does not appear in graph input" are more or less the same. Removing constant initializers from subgraph input would work (if the IR permitted it). However, this is harder to do in the main-graph (outside a Loop). If we convert a constant attribute (for Squeeze/Unsqueeze) into a graph-input + initializer (in the non-loop case), that would be a valid model, but it would prevent constant-folding like optimizations since it would like something that a caller could override when they invoke a graph-execution.

**Comment by matteosal** [comment]
Ok so there is a case for adopting both solutions simultaneously: (3) to make sure that the version converter never produces an invalid model and (2) as a good practice to allow runtime optimizations. Solution (2) alone would already guarantee that models are never invalid but it requires constant checking by reviewers, and in case something slips and (3) is not implemented we don't just lose an opportunity for optimization, but we create an invalid models which is much worse.

Unfortunately only (2) with `Constant` ops is possible right now. Any chance that the IR limitation will be addressed soon?

**Comment by matteosal** [comment]
I have changed all adapters adding initializer + input to add Constant ops instead: https://github.com/onnx/onnx/pull/3344

**Comment by matteosal** [comment]
I would consider this as being still relevant because solution (3) is still a desirable thing to have
