### ISSUE TITLE
Multiple libraries (such as onnx) set WX when building with MSVC even when ONNX_WERROR is set to OFF

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx#3530]
I understand from https://github.com/onnx/onnx/issues/1936 that this may be "by design", however, I see two problems with this:

1) It is inconsistent across platform AND a cursory look at the options leads one to believe that by setting ONNX_WERROR to OFF, warnings won't be treated as errors. This results (at least in my case) in a tracking down of where the issue that came from and time lost. At the very least, ONNX_WERROR should be documented correctly to indicate that even when it is OFF, WX will be passed to the compiler for some libraries.

2) Warnings are treated as errors that the user doesn't really have control over. For example, onnx-mlir includes onnx and uses the same version of protobuf as onnx or newer. When building onnx-mlir, we get the following warnings treated as errors (among others):

```
third_party\onnx\onnx\onnx-data.pb.cc(104): error C2220: the following warning is treated as an error
third_party\onnx\onnx\onnx-data.pb.cc(104): warning C4125: decimal digit terminates octal escape sequence
```

Since this is building unmodified onnx (1.9.0), this should be green, but it is not. So as the user of onnx, onnx-mlir has to explicitly disable those warnings or have build failures with MSVC.

**Comment by askhade** [comment]
will send out a PR soon for this

**Comment by askhade** [comment]
@sstamenova : Can you review #3548
