### ISSUE TITLE
error on on transformers - bert-base-cased, onnx checker

### ISSUE THREAD

**Issue by matthewygf** [onnx/onnx#3533]
# Ask a Question
Is that intentional that onnx checker explicitly disallow ancester having a previous defined node ?
 
### Question
Explain your question here.

When I run onnx.checker.check_model(bert-base-cased.onnx) (optimized through onnxruntime_tools.transformers.onnx_model_bert)

the below error occured: 
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '310' of node

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): shape_inference

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*): bert-base-cased from [Huggingface](https://huggingface.co/models)
**Model opset** (*e.g. 7*): 13

### Notes
Any additional information, code snippets.
you can obtain the optimized model from this [notebook ](https://github.com/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb) code. 

And I added a onnx checker check_model after

**Comment by jcwchen** [comment]
Hi @matthewygf,
Yes, ONNX spec requires ONNX graph to be topological sorted. You can check the details here: https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs. BTW, ONNXRuntime does not have this limitation... You should be able to inference such a model by InferenceSession.

**Comment by matthewygf** [comment]
@jcwchen Understood, thanks for clarifying. Yep no problem with the ONNXRuntime InferenceSession :) My use case requires me to partition the model into parts ... hence I ran into this when I run the checker... another problem anyway. Closing.
