### ISSUE TITLE
Bad node spec for node. Name:  OpType: Unsqueeze

### ISSUE THREAD

**Issue by issamemari** [onnx/onnx#3537]
# Bug Report

### Is the issue related to model conversion?
The issue is not related to model conversion. This is about creating an ONNX model using helper tools provided in the ONNX python package.

### Describe the bug
I'm trying to create an ONNX model using helper.make_graph. My use case is to merge two ONNX model by chaining them, such that one takes as input the output of the other. What I will show here is a simplified script involving only one model to reproduce the issue I'm facing.

### System information
- OS: Linux Ubuntu 18.04
- ONNX version 1.9.0
- Python version: 3.7.4

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
import wget

from onnx import helper

url = 'https://media.githubusercontent.com/media/onnx/models/master/vision/body_analysis/ultraface/models/version-RFB-640.onnx'
wget.download(url, 'reproduction_model.onnx')

model = onnx.load("reproduction_model.onnx")

testy_graph = helper.make_graph(
    list(model.graph.node),
    'testy',
    model.graph.input,
    model.graph.output
)

testy = helper.make_model(testy_graph, producer_name='onnx-example')
onnx.checker.check_model(testy)
```

### Expected behavior
The code snippet downloads an ONNX model from the ONNX repository (ultraface), then tries to create the same model using helper.make_graph by providing the list of nodes in the model and the inputs and outputs. The resulting model fails during check with the following error:

```
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-165-b798c817e29a> in <module>
     17 
     18 testy = helper.make_model(testy_graph, producer_name='onnx-example')
---> 19 onnx.checker.check_model(testy)

~/.pyenv/versions/3.7.4/envs/gender_prediction/lib/python3.7/site-packages/onnx/checker.py in check_model(model, full_check)
    102         C.check_model(protobuf_string)
    103         m = model
--> 104     if full_check:
    105         onnx.shape_inference.infer_shapes(m, check_type=True)
    106 

ValidationError: Node () has input size 1 not in range [min=2, max=2].

==> Context: Bad node spec for node. Name:  OpType: Unsqueeze
```

**Comment by jcwchen** [comment]
Hi @issamemari,

Two things:
1. Please also include graph.initiailizer to create the model graph. Something like:
```
testy_graph = helper.make_graph(
    list(model.graph.node),
    'testy',
    model.graph.input,
    model.graph.output,
    model.graph.initiailizer
)
```
2. Even if you did 1., you will still bump into the Unsqueeze error you mentioned. The reason is onnx.helper creates the model with the latest opset_version by default. The model you downloaded is using opset_version=9. Since Unsqueeze has changed its spec after opset_version=9, the checker inspects an error that this Squeeze does not meet the requrirement of the latest Squeeze. To solve it, you need to specify the opset_imports which creating the model. For instance:
```
testy = helper.make_model(testy_graph, opset_imports=[helper.make_opsetid("", 9)], producer_name='onnx-example')
```

**Comment by issamemari** [comment]
This works for me. Thank you so much @jcwchen!

**Comment by issamemari** [comment]
This works for me. Thanks a lot @jcwchen!
