### ISSUE TITLE
[onnxruntime] - session.run return negative number

### ISSUE THREAD

**Issue by huyhoangle86** [onnx/onnx#3538]
# Ask a Question

### Question
Hi, I converted my Scaled YOLOv4 csp pytorch model which trained on custom datasets to Darknet using this function (https://github.com/WongKinYiu/ScaledYOLOv4/blob/yolov4-csp/models/models.py#L647) from that convert Darket weight to ONNX using this repo(https://github.com/linghu8812/tensorrt_inference/tree/master/Yolov4)
Finally I got Scaled YOLOv4 csp ONNX version. Then I started inference the onnx model but when I execute session.run it gives me negative result as in the pic bellow which strongly affected performance of model causes detect bouding boxes to be incorrect.
what do you think?

![image](https://user-images.githubusercontent.com/42195775/122850840-1cd0b000-d338-11eb-8a3f-961e1965be15.png)

**Comment by askhade** [comment]
@huyhoangle86 : Please open this issue in onnxruntime repo: https://github.com/microsoft/onnxruntime/issues
