### ISSUE TITLE
Add attribute default value when "required == false"?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#354]
There's "required" field in Attribute. When it's set to "false". Should we also allow default value set in operator registration please? (In our current design, I'm assuming that each operator implementation will have to have its own default value in such cases). Thoughts?

**Comment by linkerzhang** [comment]
There's another open issue https://github.com/onnx/onnx/issues/374, which looks to me that should be resolved by adding default value for "optional" attribute. @ezyang @dzhulgakov @yuanbyu @gramalingam

**Comment by dzhulgakov** [comment]
Looks like a great idea. Do you want to send the PR?

As for Concat op per se - commented on that issue, I don't think axis=1 is a useful default

**Comment by linkerzhang** [comment]
@dzhulgakov Sure, PR sent out. Please kindly review it. Thank you very much!

**Comment by ezyang** [comment]
Kindly thanks @linkerzhang. I opened a PR on top of this one to make axis required.
