### ISSUE TITLE
Shape of condition input to If operator

### ISSUE THREAD

**Issue by netaz** [onnx/onnx#3541]
The specification of the [If operator](https://github.com/onnx/onnx/blob/master/docs/Operators.md#If) does not specify how to handle a condition input that is not a scalar.

### Question
A scalar condition (tensor with a single Boolean element) is well understood and is used by both examples in the specification.
```
cond = np.array(1).astype(np.bool)
```
However, the spec does not explicitly require the condition tensor to be limited to a single element.
1. Can the condition tensor have more than one element?
2. How should this be interpreted by an ONNX interpreter?

**Comment by askhade** [comment]
No the condition tensor cannot have more than 1 element. 
A condition as the name suggests indicates which branch should be executed based on the value held by the condition. It should be a scalar.

**Comment by netaz** [comment]
Thanks @askhade,
I am in agreement with your thinking, but I was hoping this can be clarified in the spec.
