### ISSUE TITLE
the output of ONNX is different from the pth's output.

### ISSUE THREAD

**Issue by lucky-xu-1994** [onnx/onnx#3543]
I want to convert the pth to ONNX , the project I worked with is aliyun/conditional-lane-detection.
1. the model build like this.
a. in condlanenet.py
![image](https://user-images.githubusercontent.com/57120921/123218884-d4afba00-d4fe-11eb-9f6a-9878526e67b6.png)
b. in condlanenet_head.py
![image](https://user-images.githubusercontent.com/57120921/123219212-38d27e00-d4ff-11eb-9b16-566c7ecd841d.png)
![image](https://user-images.githubusercontent.com/57120921/123219277-4daf1180-d4ff-11eb-93a6-69d3f3bca7f3.png)
2. Use the following code to convert.
![image](https://user-images.githubusercontent.com/57120921/123220596-af23b000-d500-11eb-947a-bd6624277433.png)
and problem is that, it only converts to the line 417  at condlanenet_head.py, and then output the pres.
![image](https://user-images.githubusercontent.com/57120921/123221134-33763300-d501-11eb-91c7-cb93447eb5de.png)

 Have anyone experienced the same problem? please give me some advise! thank you!

**Comment by jcwchen** [comment]
Hi @lucky-xu-1994,
It should a converter issue. Please raise an issue in pytorch to get the best help from the converter team (torch.onnx.export). Thank you!.
