### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for _DCNv2 with domain_version of 9

### ISSUE THREAD

**Issue by prabhuiitdhn** [onnx/onnx#3544]
**onnx_model: C:/Users/uib43225/PycharmProjects/DSAlgo/onnx_examples/DEFT-pretrained-model/model_mot.onnx** 
_pytorch: 1.4.0
onnx: 1.9.0
python: 3.6
Ubuntu 18.04_

> ONNX model includes DCNv2.  It was working but defined new symbolic named as "_DCNv2". 
```
class _DCNv2(Function):
    @staticmethod
    def symbolic(g, input, offset, mask, weight, bias, stride, padding, dilation, deformable_groups):
        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)

        return g.op("_DCNv2", input, offset, mask, weight, bias, stride_i=stride, padding_i=padding,
                    dilation_i=dilation, deformable_groups_i=deformable_groups, )
```

But now I am checking the model:
```
import onnx
onnx.checker.check_model('/home/uib43225/DEFT/src/models/model_mot.onnx')
print("Done.")
```
Error:

> onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for _DCNv2 with domain_version of 9
> 
> ==> Context: Bad node spec for node. Name:  OpType: _DCNv2

Looking for strong support.

**Comment by prabhuiitdhn** [comment]
At least, Please make me understand the clear error.

**Comment by jcwchen** [comment]
Hi @prabhuiitdhn,
According the error message, this is not an official ONNX operator. You can check all ONNX operators here: https://github.com/onnx/onnx/blob/master/docs/Operators.md. How did you get this model? This op should not be converted by official `torch.onnx.export()`.

**Comment by askhade** [comment]
It is OK to use a custom op but looks like your model does not set the domain for these custom ops correctly. Right now this op is registered with onnx standard domain therefore onnx checker tries to find the schema and complains because it does not find this schema.
https://github.com/onnx/onnx/blob/master/onnx/checker.cc#L544

**Comment by prabhuiitdhn** [comment]
@askhade thanks for explicit explanation, would you please help me to set the custom ops correctly? I mean, Is there any link or any reference where I can set the custom ops correctly?

**Comment by prabhuiitdhn** [comment]
> Hi @prabhuiitdhn,
> According the error message, this is not an official ONNX operator. You can check all ONNX operators here: https://github.com/onnx/onnx/blob/master/docs/Operators.md. How did you get this model? This op should not be converted by official `torch.onnx.export()`.

This is custom ops and I already have generated the onnx model using custom ops but check_model is not running successfully. so, which exact file I will have to modify to run successfully?

**Comment by askhade** [comment]
@prabhuiitdhn : All you need to do is change the domain for your custom op in the schema...  if the domain is not one of the onnx standard domains, checker does not try to fetch its schema.

**Comment by prabhuiitdhn** [comment]
@askhade : I am unable to fix it, Can you give more insights? Also, Do I need to rebuild the onnx If I modify the code?

**Comment by prabhuiitdhn** [comment]
@askhade I modify the code and reinstall/rebuild onnx using 

>  pip install --user --force-reinstall --ignore-installed --no-binary :all: onnx

get an another error:

> 
> from .onnx_cpp2py_export import ONNX_ML
> ImportError: /home/uib43225/.local/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
> 

Please help me to understand/fix it.

**Comment by prabhuiitdhn** [comment]
Hi @askhade: I reinstalled ONNX and Protobufv3.11.3 from the source in virtualenv and tried to check the onnx model again but Still, I am unable to fix the "onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for _DCNv2 with domain_version of 9" issue. Could you please help me to modify the code? 

I presume we are too close to fix it. Thank you.

**Comment by askhade** [comment]
can you share the model and custom op "_DCNv2" spec?

**Comment by askhade** [comment]
Did you check this: https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md especially this https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md#export-the-operator-to-onnx

You need to try something like 
return g.op("**_custom_domin::_**_DCNv2", input, offset, mask, weight, bias, stride_i=stride, padding_i=padding,
                    dilation_i=dilation, deformable_groups_i=deformable_groups, )

**Comment by prabhuiitdhn** [comment]
@askhade Thank you so much for support. yes, I am able to run it successfully. We did it. The following onnx functions is working fine.

> onnx.checker.check_model('/home/uib43225/DEFT/src/models/model_mot.onnx')
> print(onnx.helper.printable_graph(onnx_model.graph))

Thanks again @askhade. Much appreciated.

**Comment by jcwchen** [comment]
Please note that the following question abovehas been resolved by https://github.com/microsoft/onnxruntime/issues/8635#issuecomment-900356985 (pytorch==1.5.0). Thanks @prabhuiitdhn
