### ISSUE TITLE
Adding attributes to node

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3546]
Hello guys!

My question is can we add attributes to node?

For example, my node is 

```
node_def = helper.make_node(
    'Pad',                  # name
    ['X', 'pads', 'value'], # inputs
    ['Y'],                  # outputs
    mode='constant',        # attributes
```
and I want to add one more attribute for this existing node. Maybe ONNX have some solutions? Thanks

**Comment by germanjke** [comment]
nevermind, solution is

```
new_attr = helper.make_attribute("some_attr", True)
model.graph.node[i].attribute.append(new_attr)
```

**Comment by jcwchen** [comment]
Hi @germanjke,
Glad you found it. Besides the document [here](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md), there are other useful functions you can use [here](https://github.com/onnx/onnx/blob/master/onnx/helper.py). Close it now. Please reopen it if you still have questions. Thanks.
