### ISSUE TITLE
Flatten v Reshape

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#355]
Flatten and Reshape have been with us from the beginning, but I must admit to being a bit perplexed as to when to use Flatten, when Reshape is a strict generalization. Does this have to do with symbolic dimensions being easier to handle if you use a flatten instead of a reshape? If so, why is flatten limited to 2D?

**Comment by ebarsoum** [comment]
It is not needed now with GEMM, Flatten is primarily used for connecting Conv with Dense node. Off-course reshape supersede its functionality.

**Comment by euler16** [comment]
Is there any way to bypass Flatten with Reshape? Onnx.js doesn't support Flatten yet as mentioned [here](https://github.com/Microsoft/onnxjs/issues/87) .
