### ISSUE TITLE
[onnx runtime] compile a custom ops error

### ISSUE THREAD

**Issue by liym27** [onnx/onnx#3552]
# Ask a Question
Hello,
I am trying to implement an operator in ONNX Runtime according to https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator

When run `cmake ..`, error raised:
```
CMake Error: The source directory "**/custom_op_path" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

Please help me to resolve this

**Comment by jcwchen** [comment]
Hi @liym27,
According to the [document](https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator#implement-the-custom-operator), have you created a CMakeLists.txt like [this](https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/ort_custom_op/CMakeLists.txt) in your working directory?

**Comment by liym27** [comment]
> Hi @liym27,
> According to the [document](https://github.com/onnx/tutorials/tree/master/PyTorchCustomOperator#implement-the-custom-operator), have you created a CMakeLists.txt like [this](https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/ort_custom_op/CMakeLists.txt) in your working directory?

Yes

**Comment by jcwchen** [comment]
Have you updated the following command in your CMakeLists.txt? (use ORT installed directory): 
`find_library(ONNXRUNTIME_LIBRARY onnxruntime HINTS <PATH_TO_YOUR_INSTALLATION_DIRECTORY>)`
