### ISSUE TITLE
[Operator] BatchNormalization support for 1d input

### ISSUE THREAD

**Issue by mindest** [onnx/onnx#3555]
Noted that BatchNormalization declares to support input `X` of single dim size: https://github.com/onnx/onnx/blob/31f0fd6103e231664d1cfd3b25264f672f5de960/onnx/defs/nn/defs.cc#L1663 but later it requires `X` to have rank greater than 1 ([unifyInputDim()](https://github.com/onnx/onnx/blob/31f0fd6103e231664d1cfd3b25264f672f5de960/onnx/defs/shape_inference.h#L878)): https://github.com/onnx/onnx/blob/31f0fd6103e231664d1cfd3b25264f672f5de960/onnx/defs/nn/defs.cc#L1747 Should this be considered a contradiction?

**Comment by jcwchen** [comment]
Hi @mindest,
It seems like a contradiction to me. @gramalingam @neginraoof,  could you please identify this? Thank you!

**Comment by gramalingam** [comment]
Yes, I agree. We should check if the input rank is 1 or > 1 and treat it accordingly.
