### ISSUE TITLE
Load an onnx large model but cannot be implemented successfully. | Failed to allocate memory for requested buffer of size 9714073600

### ISSUE THREAD

**Issue by chiehpower** [onnx/onnx#3559]
# Bug Report

### Describe the bug
According to my pytorch model which was very large, when we export to an Onnx model, it will encounter the protobuf 2GB issue.
Hence, I save it without external data, so it can avoid a single onnx model size over 2GB issue.  
The directory including onnx model and external data looks like below:
![2021-07-0603](https://user-images.githubusercontent.com/32332200/124688169-e8005380-df08-11eb-9938-0ca90f7bc35d.png)
I referred from [this page](https://github.com/onnx/onnx/blob/master/docs/ExternalData.md).
I have tested the smaller onnx model without external data (totally almost 1.1GB) which can be loaded by the way below.
```
filename = 'model/onnx_model.onnx'
model = onnx.load(filename, load_external_data=False)
load_external_data_for_model(model, 'model/')
``` 
Also, I used this onnx model to successfully do inference.

However, when I tried to load the large model size (almost over 10GB), it encountered the 2GB limitation issue.

The Python code:
```
filename = 'model/onnx_model.onnx'
model = onnx.load(filename, load_external_data=False)
load_external_data_for_model(model, 'model/')
sess = rt.InferenceSession(filename)
input1 = sess.get_inputs()[0].name
```

**Error message:**
```
2021-07-06 17:25:50.807862464 [E:onnxruntime:, inference_session.cc:1341 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:330 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 9714073600

Traceback (most recent call last):
  File "padim_external_data.py", line 52, in <module>
    sess = rt.InferenceSession(filename)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:330 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 9714073600
```

Although I can avoid to save an over 2GB onnx model protobuf issue, it cannot be used after we loaded this large model to do further computations.

I wonder how can we traditionally handle this kind of issue?
Thank you so much!!
 
Sincerely,
Chieh

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  ubuntu 18.04
- ONNX version (*e.g. 1.7*):  1.9
- Python version: 3.6

- Attach the ONNX model to the issue (where applicable)
Model is toooo huge, it is too hard to share.

### Expected behavior
I expect I can load an over 2GB onnx model to do detect.

**Comment by askhade** [comment]
Can you open this issue in onnxruntime repo: https://github.com/microsoft/onnxruntime/issues

Are you sure you have enough resources on your system to load and infer the large model?

**Comment by chiehpower** [comment]
Hi @askhade,

Thanks for your hint!
Indeed, you are right!  I tried to generate another smaller model (that one accounts for almost 3.4GB) and tried to do inference again. And then it works!!

I think it can prove if using this way loads an onnx model, that can resolve the 2GB limitation to do inference.
Thanks!!
