### ISSUE TITLE
ONNX output mismatch with PyTorch. InstanceNormalization layer not using running_mean and running_var

### ISSUE THREAD

**Issue by ravi9** [onnx/onnx#3560]
# Bug Report

### Describe the bug
ONNX output mismatch with PyTorch. After converting the PyTorch model to ONNX, the outputs mismatch. Please see [compare-pyt-onnx-single-infer.ipynb](https://github.com/ravi9/BrainMaGe/blob/master/compare_onnx/compare-pyt-onnx-single-infer.ipynb)
The running_mean and running variance are not used based on the warning messages printed. How do we make sure the ONNX runtime uses these.
I appreciate any suggestions. Thank you.

### System information
- OS Platform and Distribution (*Linux Ubuntu 18.04*): 
- ONNX version (*e.g. 1.9.0*):  
- Python version: 3.6.10

### Reproduction instructions
- Please follow the following steps below to create the conda env. 
- Please see [compare-pyt-onnx-single-infer.ipynb](https://github.com/ravi9/BrainMaGe/blob/master/compare_onnx/compare-pyt-onnx-single-infer.ipynb) to reproduce the error.
```
git clone https://github.com/CBICA/BrainMaGe.git
cd BrainMaGe
git lfs pull
conda env create -f requirements.yml # create a virtual environment named brainmage
conda activate brainmage # activate it
python setup.py install # install dependencies and BrainMaGe

cd compare_onnx
python compare_torch_onnx_il.py

```

### Expected behavior
Outputs from PyTorch model and ONNX model should match.

### Notes
 In [compare_torch_onnx_il.py](https://github.com/ravi9/BrainMaGe/blob/mawhester/compare_onnx/compare_torch_onnx_il.py) , we compared the output after the InstanceNormalization layer where the output starts to differ.
The running_mean and running variance are not used based on the warning messages printed. How do we make sure the ONNX runtime uses these.

```
[W:onnxruntime:, graph.cc:3211 CleanUnusedInitializers] Removing initializer 'ins.in_0.running_mean'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:3211 CleanUnusedInitializers] Removing initializer 'ins.in_0.running_var'. It is not used by any node and should be removed from the model.
```
<img width="857" alt="Screen Shot 2021-07-07 at 5 11 37 PM" src="https://user-images.githubusercontent.com/4837253/124843467-d50c7400-df46-11eb-9c00-7fae5af2887e.png">

**Comment by jcwchen** [comment]
Hi @ravi9,
As the error mentioned, running_mean and running_var are not used by ONNXRuntime... I think this is a question for the converter (torch.onnx.export): why it produce those unused initializers in the graph and how it should handle running_mean and running_var during the conversion. Please raise an issue in pytorch repo to get the best help from the converter team. Thanks!

**Comment by ravi9** [comment]
Created in pytorch: https://github.com/pytorch/pytorch/issues/61430
