### ISSUE TITLE
onnx-tensorflow onnx backend test of case test_identity_sequence_cpu failed

### ISSUE THREAD

**Issue by chudegao** [onnx/onnx#3562]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
When run onnx backend test case of test_identity_sequence_cpu with onnx-tensorflow, hit below error:

======================================================================
ERROR: test_identity_sequence_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/otf/lib/python3.7/site-packages/onnx-1.9.0-py3.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 250, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/opt/anaconda3/envs/otf/lib/python3.7/site-packages/onnx-1.9.0-py3.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 308, in run
    atol=model_test.atol)
  File "/opt/anaconda3/envs/otf/lib/python3.7/site-packages/onnx-1.9.0-py3.7-linux-x86_64.egg/onnx/backend/test/runner/__init__.py", line 172, in assert_similar_outputs
    np.testing.assert_equal(outputs[i].dtype, ref_outputs[i].dtype)
AttributeError: 'list' object has no attribute 'dtype'

----------------------------------------------------------------------
Ran 1 test in 0.970s

FAILED (errors=1)

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version 1.9.0 and master
- Python version:3.7

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx_tf.backend import TensorflowBackend
backend_test = onnx.backend.test.runner.Runner(TensorflowBackend, __name__)
if __name__ == '__main__':
  unittest.main()

...
```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
The test case should pass (when onnx_tf implemented the operator correctly)

### Notes

The root cause is function assert_similar_outputs() in onnx/backend/test/runner/__init__.py does not handle sequence/list as model/node's output, it always check dtype of the output. 

```
np.testing.assert_equal(outputs[i].dtype, ref_outputs[i].dtype)
```

**Comment by chudegao** [comment]
I will submit a PR for this issue.

**Comment by jcwchen** [comment]
@chudegao Thank you for proposing the fix! We will review that PR
