### ISSUE TITLE
`onnx.checker.check_model` cannot detect Broken `Clip` node

### ISSUE THREAD

**Issue by nomaddo** [onnx/onnx#3564]
# Bug Report

### Is the issue related to model conversion?

Related to https://github.com/pytorch/pytorch/issues/61404, but onnx has another problem.

### Describe the bug

[This model](https://gist.github.com/nomaddo/47f460c60e28e7045aa6e701d7ae28e4/raw/585b0ff0caf1ea2a092d88c35ddc7967b631b02b/clip.onnx) is invalid because the second input of `Clip_0` is empty string.

```
ir_version: 6
producer_name: "pytorch"
producer_version: "1.9"
graph {
  node {
    input: "input"
    input: ""
    input: "7"
    output: "output"
    name: "Clip_0"
    op_type: "Clip"
  }
  name: "torch-jit-export"
  initializer {
    data_type: 1
    name: "7"
    raw_data: "\000\000\300@"
  }
  input {
    name: "input"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "output"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
}
opset_import {
  version: 11
}
```

No node or initializer named "" cannot be found but `onnx.checker.check_model` say nothing.

```
import onnx

model = onnx.load("clip.onnx")
onnx.checker.check_model(model)
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Debian 10
- ONNX version (*e.g. 1.7*):  1.8.1
- Python version: 3.7.3
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.

```
import onnx
model = onnx.load('clip.onnx')
onnx.checker.check_model(model)
```
- Attach the ONNX model to the issue (where applicable)

https://gist.github.com/nomaddo/47f460c60e28e7045aa6e701d7ae28e4/raw/585b0ff0caf1ea2a092d88c35ddc7967b631b02b/clip.onnx

### Expected behavior

Abort in `check_model` with an error message.

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @nomaddo,
Thank you for catching this. I think it might happen in all operators whose input is not used by its shape inference function. Please note that shape inference catches such errors (which do not effect its inference result) on a best-effort basis. Feel free to submit a PR to improve it. Thanks!

**Comment by BowenBao** [comment]
Copying comment from the other issue.

@nomaddo, @jcwchen Empty represents optional input in ONNX, please check
https://github.com/onnx/onnx/blob/master/docs/IR.md#optional-inputs-and-outputs
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#clip-11
Thus the model is valid.

**Comment by jcwchen** [comment]
@BowenBao Thanks for the correction and reference. I believe you are right. Other discussions: https://github.com/onnx/onnx/issues/151 Empty string is valid for optional input. Close now. Please reopen it if you still have questions. Thanks!
