### ISSUE TITLE
Operator for fft_rfft2.                ( Exporting the operator fft_rfft2 to ONNX opset version 11 is not supported )

### ISSUE THREAD

**Issue by rushi-the-neural-arch** [onnx/onnx#3573]
# New Operator

I was implementing this new paper - [Global Filter Networks for Image Classification](https://arxiv.org/abs/2107.00645)
([GitHub](https://github.com/raoyongming/GFNet)) which uses 2D Discrete Fourier Transform and 2D Inverse Fourier transform but it seems that the current onnx version does not have support for this. It might be a huge plus point to include this operator as the use of FFTs is increasing steadily and the result seem pretty promising! considering the runtime-accuracy tradeoff

**Comment by jcwchen** [comment]
ONNX does not have FFTs related operators yet, but there is a pending PR for it: https://github.com/onnx/onnx/pull/2625

**Comment by xadupre** [comment]
I'm currently working on converting rfft,rfft2 in tensorflow-onnx (https://github.com/onnx/tensorflow-onnx/pull/1596). rfft, rfft2d produce complex results so the conversion only works when it is followed by a function computing the magnitude. Would that scenario work for you?

**Comment by rushirajsherlocked** [comment]
@xadupre Thanks for the help! Tbh I'm not totally sure at the moment I need to check if your work matches mine, but will surely take a look at this!

**Comment by xadupre** [comment]
If you need a more simple version : [ONNX and FFT](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/onnx_fft.html), the notebook implements rfft, rfft2 in numpy then uses that code to write the ONNX representation of it.

**Comment by rushirajsherlocked** [comment]
This is awesome! This will be useful in understanding properly, thanks for sharing :)

**Comment by chenqq1** [comment]
> # 新操作员
> 我正在实施这篇新论文 - [用于图像分类](https://arxiv.org/abs/2107.00645)的全局过滤网络（[GitHub](https://github.com/raoyongming/GFNet)），它使用2D离散傅里叶变换和2D逆傅里叶变换，但似乎当前的onx版本不支持这一点。包括这个运算符可能是一个巨大的优点，因为FFT的使用正在稳步增加，结果似乎很有希望！考虑运行时精度权衡

Have you solved this problem, please? What code to add to successfully export ONNX files with fft2 and rfft2?

**Comment by xadupre** [comment]
Operator DFT has been added to onnx (https://github.com/onnx/onnx/blob/main/docs/Operators.md#DFT), the converting libraries should be able to use it.

**Comment by chenqq1** [comment]
Does the docs mean to install version 17 of ONNX? Where to download this version?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "onnx/onnx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 晚上10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [onnx/onnx] Operator for fft_rfft2.                ( Exporting the operator fft_rfft2 to ONNX opset version 11 is not supported ) (#3573)





 
Operator DFT has been added to onnx (https://github.com/onnx/onnx/blob/main/docs/Operators.md#DFT), the converting libraries should be able to use it.

**Comment by xadupre** [comment]
onnxruntime 1.13 has just been released and support opset 17 (which includes DFT). Now, tf2onnx can be updated to use those operators. This is tracked by issue https://github.com/onnx/tensorflow-onnx/issues/2017.

**Comment by shengyu27** [comment]
Has it been resolved now? Does onnx support rfft2 now?
I tried converting a pytorch model with rfft2 operation to onnx, but there were still errors.
```
RuntimeError: Unknown number type: complex
```
