### ISSUE TITLE
Can ONNX be used as an intermediary format to translate scikit-learn models to TensorFlow?

### ISSUE THREAD

**Issue by schwenkd** [onnx/onnx#3577]
# Ask a Question

### Question

I would like to be able to use ONNX as an intermediary format to help convert models built in a variety of frameworks to TensorFlow.

There is a tutorial converting a PyTorch model to TensorFlow using this method: https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb

Is this possible for conversions other than just PyTorch to Tensorflow? Of immediate interest to me is scikit-learn, but ideally I am looking for some kind of key that identifies which types of models can be converted between which types of frameworks.

### Further information
I tried converting a simple scikit-learn linear regression to ONNX, then converting the ONNX model to tensorflow. I get the error `BackendIsNotSupposedToImplementIt: LinearRegressor is not implemented.` when attempting inference or exporting with the code

```
tf_rep = prepare(onnx_model)
tf_rep.export_graph("test_model.pb")
```

The error makes it seem that the conversion is not possible, but it would be useful to know which conversions are possible.

I am using: 

Ubuntu 18.04
Python 3.6.9
onnx 1.9.0
onnx-tf 1.8.0
skl2onnx 1.9.0
tensorflow 2.4.1
scikit-learn 0.24.2

- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

Converters

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  Scikit-learn linear regression
**Model opset** (*e.g. 7*): Not sure if I am checking correctly, but when I run `onnx_model.opset_import`, I get

```
[domain: "ai.onnx.ml"
version: 1
]
```

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @schwenkd,
Ideally ONNX models can be converted from popular ML/DL frameworks like PyTorch, TensorFlow, Keras or scikit-learn. However, in practice, it depends on whether the conversion (for all operators which the model uses) is supported by the converter.

In your example, sklearn-onnx does support LinearRegressor op to ONNX, but I think onnx-tensorflow does not support LinearRegressor op to TensorFlow ([reference](https://github.com/onnx/onnx-tensorflow/blob/b2402684e638bdf896fe35772426f1d2acf8e217/onnx_tf/opset_version.py#L84)). If you want to convert such a model, you will need to get assistance from the converter team (onnx-tensorflow) to request a support or implement the conversion yourself.

**Comment by xadupre** [comment]
LinearRegressor can be replaced by a matrix multiplication. The converter does it automatically for double but not for float. You can either modify the ONNX graph to replace the node by yourself or create an issue for [sklearn-onnx](https://github.com/onnx/sklearn-onnx). This would be a small change in the package.
