### ISSUE TITLE
Example for operator Loop does not work any more

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#3584]
# Bug Report

### Describe the bug
The example for operator Loop https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-67 fails because ``AttributeError: module 'onnx.helper' has no attribute 'make_tensor_sequnce_value_info``.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows
- ONNX version (*e.g. 1.7*):  1.9.0
- Python version: 3.9
- Visual Studio version (if applicable): 2019

### Reproduction instructions
Run the example https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-67.

### Expected behavior
The example should be updated.

**Comment by askhade** [comment]
"make_tensor_sequnce_value_info" was recently added. It is not available in the older packages. ONNX 1.10 onwards it will be available. In the interim you can use the tests from 1.9 rel branch.
