### ISSUE TITLE
Exporting the operator kthvalue to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by liamsun2019** [onnx/onnx#3586]
Hi Sir,

I encountered an error while converting a pth model to onnx format reporting:
Exporting the operator kthvalue to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

Will kthvalue be supported in the future?

Thanks

**Comment by jcwchen** [comment]
Hi @liamsun2019,
I think this is a question for the converter (torch.onnx.export). Could you please raise this question under PyTorch repo and tag ONNX? Thanks!
