### ISSUE TITLE
Error in numpy_helper.to_array(tensor) for tensor with external data

### ISSUE THREAD

**Issue by yjydfnhc** [onnx/onnx#3594]
# Bug Report

### Describe the bug
numpy_helper.to_array(tensor) will get error for tensor whose data is saved in an external file. Current implement of to_array() only tried to get data from 'raw_data' field or storage_field(e.g. 'float32_data' field), but never tried to read data from 'external_data' field.  When data of the tensor haven't been loaded into memory and are still in 'external_data', this function will raise an error since it gets empty data from the wrong storage field. 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  win10
- ONNX version (*e.g. 1.7*):  1.9.0
- Python version: 3.8.0

### Reproduction instructions
- Example code:
```
import numpy as np
import onnx
from onnx import  helper, TensorProto, numpy_helper

#======== 1. create an onnx model
dtype = np.float32
x = np.ones((3, 3), dtype)

data_w = np.ones((3, 3), dtype)
w = helper.make_tensor(name = 'w', data_type = TensorProto.FLOAT, dims = data_w.shape, vals = data_w.flatten().astype(dtype).tobytes(), raw=True)

V = helper.make_tensor_value_info('V', TensorProto.FLOAT, [3, 3])
Z = helper.make_tensor_value_info('Z', TensorProto.FLOAT, [3, 3])

# Create node (NodeProto)
X = helper.make_node(
    'Constant',
    inputs=[],
    outputs=['X'],
    value=onnx.helper.make_tensor(
        name='const_tensor_x',
        data_type=onnx.TensorProto.FLOAT,
        dims=x.shape,
        vals=x.flatten().astype(float),
    ),
)
node_cf = helper.make_node(
    'Gemm',
    ['w', 'X'], # inputs
    ['Z1'],                  # outputs
    name = 'tocf'
)
node_sum = helper.make_node(
    'Sum',                  # name
    ['Z1', 'V'], # inputs
    ['Z'],                  # outputs
)
# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [X, node_cf, node_sum],        # nodes
    'test-model',      # name
    [V],  # inputs
    [Z],  # outputs
    initializer = [w],
)
model_def = helper.make_model(graph_def, producer_name='onnx-example')

# #======== 2. save the onnx model: save model with separate data files
path_sep = '../outs/model_sep.onnx'
onnx.save_model(model_def, path_sep
                , save_as_external_data=True
                , all_tensors_to_one_file=False
                , size_threshold=0)

# #======== 3. load and get tensor data, will get error
model = onnx.load(path_sep, load_external_data= False) # load without data
graph = model.graph
if graph.initializer:
    for tensor in graph.initializer:
        tensor_data = numpy_helper.to_array(tensor).flatten()  # will raise error: ValueError: cannot reshape array of size 0 into shape (3,3)
```
- The error:
```
Traceback (most recent call last):
  File "D:/myfiles/workspace/pythonTest/myTest/saved/issue4_to_array.py", line 61, in <module>
    tensor_data = numpy_helper.to_array(tensor).flatten()  # will raise error: ValueError: cannot reshape array of size 0 into shape (3,3)
  File "C:\Users\qingxialiu\AppData\Local\Programs\Python\Python38\lib\site-packages\onnx\numpy_helper.py", line 71, in to_array
    np.asarray(
ValueError: cannot reshape array of size 0 into shape (3,3)
```

### Expected behavior
For a tensor whose data hasn't been read into memory, when calling to_array(tensor), it is expected to read the data from the external file according to the 'data_location' and 'external_data' field.

Thanks.

**Comment by jcwchen** [comment]
Please check the comment here: https://github.com/onnx/onnx/issues/3598#issuecomment-885949761. Thank you!

**Comment by jcwchen** [comment]
Hi @yjydfnhc,
Thank you for catching this issue. The improvement has been merged into the main branch and now numpy_helper.to_array does have additional parameter to specify base_dir for external data: https://github.com/onnx/onnx/blob/51bbc69a62ee0818330f9699b636b4037129789b/onnx/numpy_helper.py#L22. Could you please give it a try? Thank you!

FYI, you can use onnx-weekly (the PR was included) for quick verification: https://test.pypi.org/project/onnx-weekly/

**Comment by yjydfnhc** [comment]
Hi, @jcwchen, thanks for the update.
I have tried to use onnx-weekly version 1.10.1 and found the bug is fixed, so I'll close this issue. Thanks!
