### ISSUE TITLE
Android studio 中能安装onnx吗

### ISSUE THREAD

**Issue by YangLiu0427** [onnx/onnx#3595]
# Ask a Question

### Question
Android studio 中能安装onnx吗？

想在Android studio中利用python调用onnx模型，可以吗？具体该怎么安装onnx，请指教。

**Comment by jcwchen** [comment]
Hi @YangLiu0427,
Android studio is an IDE, so it depends on which OS environment you would like to use. You can check the supported wheel here: https://pypi.org/project/onnx/#files. If it's supported, you can simply use `pip install onnx`. Even if your environment is not supported, you can still try to build ONNX from source. The build document is [here](https://github.com/onnx/onnx#installation).

--

Android studio 是一個集成开发环境，所以能不能安裝是看您使用的作業系統環境，你可以在此https://pypi.org/project/onnx/#files 查看支持的wheel，如果支持您的作業系統，你可以直接用`pip install onnx`安裝；就算不支持，你也可以根據安裝文件https://github.com/onnx/onnx#installation 嘗試從原始碼安裝ONNX。

**Comment by jcwchen** [comment]
I assume this has been resolved. Please reopen it if you still have question. Thanks.
