### ISSUE TITLE
Error when checking model with external data

### ISSUE THREAD

**Issue by yjydfnhc** [onnx/onnx#3598]
# Bug Report

### Describe the bug
I saved a simple model with save_as_external_data=True, then load the model into memory with load_external_data=False, will get an error when using checker.check_model() for this model. 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): win10
- ONNX version (*e.g. 1.7*):  1.9.0
- Python version: 3.8.0

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import numpy as np
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
import json
from google.protobuf.json_format import MessageToJson

#======== 1. create an onnx model
dtype = np.float32
x = np.random.randn(3, 5).astype(dtype)

data_w = np.random.randn(2, 5).astype(dtype)
w = helper.make_tensor(name = 'w', data_type = TensorProto.FLOAT, dims = data_w.shape, vals = data_w.flatten().astype(dtype).tobytes(), raw=True)

Z = helper.make_tensor_value_info('Z', TensorProto.FLOAT, [2, 3])

# Create node (NodeProto)
X = helper.make_node(
    'Constant',
    inputs=[],
    outputs=['X'],
    value=onnx.helper.make_tensor(
        name='const_tensor_x',
        data_type=onnx.TensorProto.FLOAT,
        dims=x.shape,
        vals=x.flatten().astype(float),
    ),
)
node_gemm = helper.make_node(
    'Gemm',                  # name
    ['w', 'X'], # inputs
    ['Z'],                  # outputs
    name = 'gemm1'
)
# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [X, node_gemm],        # nodes
    'test-model',      # name
    [],  # inputs
    [Z],  # outputs
    initializer = [w],
)
model_def = helper.make_model(graph_def, producer_name='onnx-example')

#======== 2. save an onnx model
model_path = '../outs/model.onnx'
# save model with separate data files
onnx.save_model(model_def, model_path
                , save_as_external_data=True
                , all_tensors_to_one_file=False
                , size_threshold=0)

#======== 4. load and try save
# (1) load with data, then check: will success
model_full = onnx.load(model_path)
onnx.checker.check_model(model_full)

# (2) load without data, then check: will fail
model_sep = onnx.load(model_path, load_external_data=False)
onnx.checker.check_model(model_sep)  # onnx.onnx_cpp2py_export.checker.ValidationError: Data of TensorProto ( tensor name: w) should be stored in w, but it doesn't exist or is not accessible.
```
- Error:
```
"C:\Program Files\Python38\python.exe" D:/pythonProject/test/issue1_check_model.py
Traceback (most recent call last):
  File "D:/pythonProject/test/issue1_check_model.py", line 61, in <module>
    onnx.checker.check_model(model_sep)  # onnx.onnx_cpp2py_export.checker.ValidationError: Data of TensorProto ( tensor name: w) should be stored in w, but it doesn't exist or is not accessible.
  File "C:\Program Files\Python38\lib\site-packages\onnx\checker.py", line 104, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Data of TensorProto ( tensor name: w) should be stored in w, but it doesn't exist or is not accessible.
```

**Comment by jcwchen** [comment]
Hi @yjydfnhc,
Thank you for catching these issues related to load_external_data. Initially this feature is designed to be used with load_external_data_for_model. So simply using `onnx.load('model.onnx', load_external_data)` will bump into many issues because most functions/helpers assume data exist in the tensor's raw_data. At this moment, these functions/helpers do not support models without load_external_data. This limitation is known.

However, we saw there are more and more large ONNX models have larger tensors. Loading all tensors from external data will easily reach 2GB protobuf limitation. Therefore, we do want these ONNX functions to have this ability to handle models without load_external_data. It is an item in our backlog and I will tag it as an enhancement.

**Comment by yjydfnhc** [comment]
Hi, @jcwchen Thanks for the reply! Supporting large models is indeed the trend. We expect to use onnx to achieve this by, for example, loading the data for each tensor only when it is necessary for the process and then release the memory when it is no longer needed. About these issues, may I ask about the timeline? when or in which release could we expect these enhancements implemented?  Thanks.

**Comment by jcwchen** [comment]
We are targeting the next release for this feature, but typically ONNX is released semi-annually. (So it will be supported by official release in six months) However, once we have implemented this feature and got it merged, you can still use it from building the latest ONNX from source or weekly TestPyPI package. I will post the updates in this thread in any. Thanks!

**Comment by askhade** [comment]
@yjydfnhc: Where is the data located? The checker here reports an error because it is trying to verify that the data exists and it is trying to locate it in the model directory.

**Comment by askhade** [comment]
@yjydfnhc : Actually try using check_model_path api. If you data is in the same directory as the model dir then checker will not fail for this reason.

**Comment by yjydfnhc** [comment]
> @yjydfnhc: Where is the data located? The checker here reports an error because it is trying to verify that the data exists and it is trying to locate it in the model directory.

Both the model and tensor file are located in the folder "../outs/" related to the python script, e.g. if the path of the python script is D:/mytest/code/issue.py, it will generate data (model.onnx and w file) to the folder D:/mytest/outs/

**Comment by askhade** [comment]
If you load the model first and then call checker it does not know the data dir and therefore tries to find the data in the current working dir and complains if it does not find it. If your script and data are not in the same directory, directly use the checker api and providing the model path .i.e check_model_path("D:/mytest/outs/model.onnx")

**Comment by yjydfnhc** [comment]
> If you load the model first and then call checker it does not know the data dir and therefore tries to find the data in the current working dir and complains if it does not find it. If your script and data are not in the same directory, directly use the checker api and providing the model path .i.e check_model_path("D:/mytest/outs/model.onnx")

great, according to your advice, it truly does not fail by using checker.check_model(model_path) instead, thanks!

**Comment by claeyzre** [comment]
@yjydfnhc did you solve this issue ?
I tried merging decoders and ended up with using check_model_path with an associated path but the check still fails with the same exception as yours. Guys from [optimum ](https://github.com/huggingface/optimum/issues/1044) did try to reproduce but it seems to work on Ubuntu but not on Windows
