### ISSUE TITLE
shape_inference failed after model optimization

### ISSUE THREAD

**Issue by mengniwang95** [onnx/onnx#3600]
# Bug Report

### Describe the bug
After ssd model is optimized with EXTENDED level, it will fail during shape_inference with onnx1.8.0, but can do shape_inference successfully with onnx1.7.0 & 1.9.0
Further if I use BASIC level to optimize, it can do shape_inference successfully with onnx1.8.0.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): CentOS Linux release 7.6.1810 (Core)
- ONNX version: 1.8
- Python version: 3.6.12
- Protobuf version: 3.14.0

### Reproduction instructions
- Describe the code to reproduce the behavior.

```
import onnx
import onnxruntime as ort
from onnx import shape_inference

sess_options = ort.SessionOptions()
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
sess_options.optimized_model_filepath = output_path
_ = ort.InferenceSession(model.SerializeToString(), sess_options)
model = onnx.load(sess_options.optimized_model_filepath)
value_info = shape_inference.infer_shapes(model).graph.value_info
```

- Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mengniwa/miniconda3/envs/mlperf/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type)
RuntimeError: Shape inference error(s): (op_type:Gather, node name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/Gather): [TypeInferenceError] Input 0 expected to have type but instead is null
```

- Attach the ONNX model to the issue (where applicable)

```
export MODEL=ssd_mobilenet_v1_coco_2018_01_28
wget http://download.tensorflow.org/models/object_detection/$MODEL.tar.gz
tar -xvf $MODEL.tar.gz

python -m tf2onnx.convert --graphdef $MODEL/frozen_inference_graph.pb --output ./$MODEL.onnx --fold_const --opset 11 --inputs image_tensor:0 --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0
```

### Want to confirm

If onnx will keep maintaining  shape_inference tool ? Or this tool will be deprecated ?

**Comment by askhade** [comment]
you can set the strict mode to 0 to mask node level shape inference errors. It is best to set the strict mode so that you can find all the issues but for whatever reasons you want to mask these errors then there is an option.

**Comment by mengniwang95** [comment]
> Hi @mengniwang95,
> 
> Thank you for providing the details to repro this error! I can repro it.
> 
> > If onnx will keep maintaining shape_inference tool ? Or this tool will be deprecated ?
> 
> ONNX does keep maintaining/improving shape_inference.
> 
> The story is ONNX has much improved shape_inference in ONNX 1.8.0. For instance, It further checks type equality of every input from every node. ONNX's shape_inference set this enhanced check default. However, some old/deprecated models might not meet this requirement so since ONNX 1.8.1, shape_inference set this type equality check as optional and make shape_inference with unknown ops throw warnings instead of errors. That's probably why you bump this error only in ONNX 1.8.
> 
> Back to your case. I think the reason is this optimized ORT model consists "FusedConv" op which is not a ONNX official op... In ONNX 1.8 it will throw an error, but after ONNX 1.9 it will simply throw a warning and stop shape_inference.

Thank you very much, I try to use BASIC optimization and this bug is removed.
