### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by ccl-private** [onnx/onnx#3601]
# Bug Report

### Is the issue related to model conversion?
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): windows10
- ONNX version (*e.g. 1.7*):  1.9.0 / 1.8.0
- Python version:3.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:3.17.3
- Visual Studio version (if applicable):
- convert PyTorch to onnx failed.
![image](https://user-images.githubusercontent.com/36214675/126794597-2ec8d9ed-79b2-40eb-9f25-52b9f5d85b33.png)

### Reproduction instructions
- Describe the code to reproduce the behavior.

```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
 convert PyTorch to onnx

**Comment by jcwchen** [comment]
Hi @ccl-private,
Could you please provide more details about this crash? Which code and which model led you to this crash? Thanks

**Comment by ccl-private** [comment]
I then find someone who met the same problem.
http://5.9.10.113/63059001/how-to-fix-process-finished-with-exit-code-1073741819-0xc0000005-when-using-c

**Comment by jcwchen** [comment]
Have you resolved that? It seems like a PyTorch (while using torch.onnx.export) issue.

**Comment by ccl-private** [comment]
It still failed in windows, but it succeeds in ubuntu.

**Comment by ccl-private** [comment]
I am trying to convert yolo5 to onnx in windows. https://github.com/ultralytics/yolov5/issues/2153

**Comment by askhade** [comment]
if the export is failing then please open this issue in the pytorch repo.

**Comment by ccl-private** [comment]
I opened in PyTorch here, https://github.com/pytorch/pytorch/issues/62090
