### ISSUE TITLE
Backend test runner needs support for parsing OptionalProto test data

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#3608]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
The equivalent of https://github.com/onnx/onnx/issues/3086 for the new optional type introduced. Opening this issue for tracking.

### System information
N/A

### Reproduction instructions
N/A

### Notes

Any additional information

**Comment by askhade** [comment]
@neginraoof can you pick this up. Thanks!

**Comment by jcwchen** [comment]
Hi @hariharans29,
May I understand more about what the remaining job is for OptionalProto? Isn't [here](https://github.com/onnx/onnx/blob/0978a02e4c394d2b1179a242388576739dc90173/onnx/backend/test/runner/__init__.py#L333) sufficient? Thanks for looking into it.

**Comment by garymm** [comment]
Related TODO:
https://github.com/microsoft/onnxruntime/blob/1f2c92673b2edf75460478d406f84aead7a140f3/onnxruntime/test/testdata/onnx_backend_test_series_filters.jsonc#L75

**Comment by thiagocrepaldi** [comment]
@hariharans29 is this still relevant?
