### ISSUE TITLE
2 onnx sessions are very slow.

### ISSUE THREAD

**Issue by thomas-happify** [onnx/onnx#3614]
# Ask a Question

### Question
I have 2 transformer-based modesl, and both of them were successfully converted into ONNX format.
When running them separately, they are 2X faster than Pytorch CPU.
However, when `session.run()` them sequentially, they are 2X slower than Pytorch CPU.

### Further information
If I only run the `encoder` or `encoder_session`, it's 2X faster than Pytorch CPU full precision
```python
for batch in tqdm(val_dataloader, desc="Evaluating Full Precision"):
    batch = {k: v.to(device) for k, v in batch.items()}
    labels = batch.pop("labels")

    encoder_outputs = encoder(**batch)

#    outputs = classifier(
#        encoder_output=encoder_outputs.last_hidden_state, 
#        extended_attention_mask=encoder_outputs.attention_mask
#    )
#    predictions = outputs.logits.argmax(dim=-1)


for batch in tqdm(val_dataloader, desc="Evaluating Quantized"):
    batch = {k: v.detach().numpy() for k, v in batch.items()}
    labels = batch.pop("labels")

    encoder_outputs = encoder_session.run(None, batch)
#     encoder_outputs = {"encoder_output": encoder_outputs[0], "extended_attention_mask":encoder_outputs[1]}

#     outputs = pnn_session.run(None, encoder_outputs)[0]
#     predictions = np.argmax(outputs, axis=-1)
```
Evaluating Full Precision: 100%|██████████████ 3370/3370 [02:26<00:00, 22.97it/s]
Evaluating Quantized: 100%|██████████████| 3370/3370 [01:06<00:00, 50.44it/s]

If I run them all together, onnx quantized is 2X slower.
```python
for batch in tqdm(val_dataloader, desc="Evaluating Full Precision"):
    batch = {k: v.to(device) for k, v in batch.items()}
    labels = batch.pop("labels")

    encoder_outputs = encoder(**batch)

    outputs = classifier(
        encoder_output=encoder_outputs.last_hidden_state, 
        extended_attention_mask=encoder_outputs.attention_mask
    )
    predictions = outputs.logits.argmax(dim=-1)


for batch in tqdm(val_dataloader, desc="Evaluating Quantized"):
    batch = {k: v.detach().numpy() for k, v in batch.items()}
    labels = batch.pop("labels")

    encoder_outputs = encoder_session.run(None, batch)
    encoder_outputs = {"encoder_output": encoder_outputs[0], "extended_attention_mask":encoder_outputs[1]}

    outputs = pnn_session.run(None, encoder_outputs)[0]
    predictions = np.argmax(outputs, axis=-1)
```
Evaluating Full Precision: 100%|██████████████  3370/3370 [03:17<00:00, 17.08it/s]
Evaluating Quantized: 100%|██████████████| 3370/3370 [05:40<00:00,  9.90it/s]
- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*): 11

### Notes
This is when running 1 model alone

**Comment by jcwchen** [comment]
Hi @thomas-happify,
This should be a Runtime issue since this performance difference happens during Runtime. I assume you are using ONNXRuntime so please raise this issue there: https://github.com/microsoft/onnxruntime. Thanks!
