### ISSUE TITLE
Helper function for ONNX parsing

### ISSUE THREAD

**Issue by GuanLuo** [onnx/onnx#3617]
# Ask a Question

### Question
I am writing a C++ parser that read a ONNX model file and reconstruct the model with my own node / tensor abstraction, it is trouble some to figure out the shape of intermediate tensor as the ONNX file doesn't store it. I notice that the ONNX Python library has a nice `shape_inference` feature for such, I wonder if there is the same utility (and other helper function if available) for C++ and how may I incorporate it into my application (build with ONNX C++ library?)

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

converters, shape_inference

**Comment by jcwchen** [comment]
Hi @GuanLuo,
Are you looking for how to use C++shape_inference? You can check `InferShapes` here: https://github.com/onnx/onnx/blob/master/onnx/shape_inference/implementation.cc#L475-L491

Example: https://github.com/onnx/onnx/blob/04bb946bc2dcc490266e36b810b00dce16b1edd4/onnx/test/cpp/shape_inference_test.cc#L528

FYI, ONNX also has official Python parser and C++ parser. You can check the examples from tests:
Python: https://github.com/onnx/onnx/blob/master/onnx/test/parser_test.py
C++ https://github.com/onnx/onnx/blob/master/onnx/test/cpp/parser_test.cc

**Comment by GuanLuo** [comment]
Thanks, InferShape will be helpful for my case. Is there an instruction to build ONNX with my application? I see that there is CMakeLists.txt and my project uses CMake as well, but the build instruction on README seems to be for Python.

And thanks for the pointer to the parser, but this is not exactly what I am looking for, it is from code (string) to ONNX protobuf, but what I am building is from ONNX protobuf to my own data structures.

**Comment by jcwchen** [comment]
To integrate ONNX code, perhaps add `add_subdirectory(/path/to/onnx/codebase)` with desired build option in your CMakeLists.txt?

**Comment by GuanLuo** [comment]
Thanks, was having trouble with the CMake build, but I worked around it by customizing my own ONNX target with minimal files needed.
