### ISSUE TITLE
Will 1.9.1 tag pushed to the repo?

### ISSUE THREAD

**Issue by CAMOBAP** [onnx/onnx#3618]
### Question

According to git commit history, it looks like 1.9.1 release happens, but there is still not a tag in the repository

### Notes

I need this tag to be able to add a new version 1.9.1 of onnx package to Conan package manager

**Comment by askhade** [comment]
I will do it today or tomorrow. BTW ONNX 1.10 is ready and will be released by Monday

**Comment by CAMOBAP** [comment]
@askhade thanks a lot for your support!

As far as I understand there should not be any breaking changes between 1.9.1 and 1.10, can you confirm this?

**Comment by askhade** [comment]
Right no breaking changes.
