### ISSUE TITLE
numpy_helper.to_array interpretation 

### ISSUE THREAD

**Issue by ocaff1** [onnx/onnx#3619]
Hi,

I need to get the quantized values of weights and bias from a onnxrt quantized model.
These structures are stored in the graph initializer in raw_data format (TensorProto).

To decode raw_data and get values in a numpy array I use:
onnx.numpy_helper.to_array(initializer[n])

In case of weights, dtype is int8 and the array looks like:
array([[[[0x7d, 0x5a], ... f]]]], dtype=int8)
0x7d is 125 which is the right value. It works as expected.

In case of bias, dtype is int32 and the array returned by the numpy_helper.to_array function is (here, 4 bias values):
Bias= array([0xe6, 0x2a, 0x9f, 0xb3], dtype=int32)
We can see that the hexa values are not in np.int32 format.
The expected values are -8218, -5078, -2145 and -4173
I can only get them when I print explicitely Bias[0], Bias[1]...

What is wrong with the array representation in case of dtype=int32?

Why "numpy_helper.to_array" function does not return the array in clear format:
Bias=array([-8218, -5078, -2145,-4173])

Thank you,
Ocaf

**Comment by jcwchen** [comment]
Hi @ocaff1,
Do you have any handy model for me to repro this error? Thank you!

**Comment by ocaff1** [comment]
Hi,

Here is the model with the display confusing issue.

_model=onnx.load("test_conv.quantized.onnx")
gr=model.graph
ini=gr.initializer_

The initializer corresponding to the bias is ini[5]
_dims: 4
data_type: 6
name: "conv1.bias_quantized"
raw_data: "\346\337\377\377*\354\377\377\237\367\377\377\263\357\377\377"_

To get its values in clear format:
bias=onnx.numpy_helper.to_array(ini[5])

I get:
_bias_
_=> **array([0xe6, 0x2a, 0x9f, 0xb3], dtype=int32)**_
_bias[0]=-8218_
_bias[1]=-5078
bias[2]=-2145
bias[3]=-4173_

My question is why _numpy_helper.to_array_ displays an array with unsigned byte array (in **bold** above) instead of int32 array as expected?

[test_conv.quantized.onnx.zip](https://github.com/onnx/onnx/files/7006615/test_conv.quantized.onnx.zip)

Thank you

**Comment by ocaff1** [comment]
Sorry for posting this ticket.  The answer was a deep hidden call to numpy.set_printoptions method in the rest of the code...
So, I close this.
Thank you.

**Comment by jcwchen** [comment]
Hi @ocaff1, no worries. Thank you for figuring out! Actually what onnx.numpy_helper does is just using `np.frombuffer(b.raw_data, dtype=np.int32).reshape(b.dims)`. So the conversion should be good. May I ask you how did you use `numpy.set_printoptions` to make it show correctly?

**Comment by ocaff1** [comment]
Hi,

The part that makes the display confusing was:
```
 np.set_printoptions(
                threshold=sys.maxsize,
                formatter={'int': lambda x: hex(np.uint8(x)) if (
                    x < 0) else hex(np.uint8(x)), }
            )
```
In order to reset the behavior of numpy array display I only add a simple call without any option:
`np.set_printoptions()`
And then, the display works as usual.
Ocaff1
