### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#363]
After a "pip install onnx" that seems to be good.

When I try to do : 
```
python
> import onnx
```

I get the error : 
File "<stdin>", line 1, in <module>
     .../lib/python2.7/site-packages/onnx/__init__.py", line 6, in <module>
    from .onnx_pb import *  # noqa
      .../lib/python2.7/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_pb2 import *  # noqa
     .../lib/python2.7/site-packages/onnx/onnx_pb2.py", line 213, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

Any ideas for this error ?

**Comment by LucasMahieu** [comment]
It was an error due to protobuf compiler incompatibility. 
Solved by regenerating the proto with right version of protoc

**Comment by s-westphal** [comment]
I have the same issue. What is the right version of protoc?

**Comment by LucasMahieu** [comment]
>=2.6 I think, 
Actually I decided to use version 3.5 (from sources) and its works perfectly.

I think that my issue was due to the fact the protoc version was : X.x and the version of python-protobuf was Y.y... 

So I re installed properly both protoc and protobuf with the same version

**Comment by s-westphal** [comment]
Thank you! I had the same version version conflict
