### ISSUE TITLE
RuntimeError: Exporting the operator hardsigmoid to ONNX opset version 11 is not supported.

### ISSUE THREAD

**Issue by Klawens** [onnx/onnx#3631]
RuntimeError: Exporting the operator hardsigmoid to ONNX opset version 11 is not supported.

How to solve this problem?

**Comment by jcwchen** [comment]
Hi @Klawens,
ONNX does support Hardsigmoid and the converter (pytorch to ONNX) supports hardsigmoid conversion as well: https://pytorch.org/docs/stable/onnx.html#supported-operators. If you are using the latest pytorch but still encounter this error, please raise an issue (Why this supported op failed conversion) under pytorch to get the best help from the converter team. Close now. Thank you.
