### ISSUE TITLE
how to fix input names for a model?

### ISSUE THREAD

**Issue by abcde-1447** [onnx/onnx#3632]
# Ask a Question

### Question

Hi, I am trying to export a pytorch model to onnx, and found that my inputs for the exported model are renamed to something like this:

`['xx', '2', 'input.67', 'input.85']`

which is not really readable and could be hard to maintain in the future.  I am wondering if it is possible to manually set names for these input arguments?  Thank you!

**Comment by jcwchen** [comment]
Hi @abcde-1447,
> I am wondering if it is possible to manually set names for these input arguments? 

Yes, it's doable. Something like: `onnx_model.graph.input[i].name = 'your_input_name'`. However, please note that these names must be unique and you also need to update other nodes' input which use these inputs.

Thus, I suggest another approach: I think tortch.onnx.export does provide an option to specify the names for input/output. Could you please give it a try? Thanks.
https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx

**Comment by abcde-1447** [comment]
hi @jcwchen Thanks for your suggestion!

I tested this approach, and find that if I specify input names as `['xx1', 'xx2', 'xx3', 'xx4']`, my exported model would have input names as `['xx1', 'xx3', 'xx4', 'input.85']`, it looks like `xx2` is missing in the output graph and order is not preserved.  Do you have any idea how I may debug this issue?

Thank you!

**Comment by jcwchen** [comment]
It looks like an issue from the converter and sorry I don't have the context here... Could you please raise a question (issue) under PyTorch to get assistance from the converter team (torch.onnx.export)? Thank you!
