### ISSUE TITLE
check_model doesn't fail on malformed model

### ISSUE THREAD

**Issue by GuanLuo** [onnx/onnx#3642]
# Bug Report

### Describe the bug
I created a model with only 'split' node with input that can't be evenly split, but `check_model()` does not return error. However, if I tried `shape_inference.infer_shapes()` on the same model and it will return error

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 20.04
- ONNX version (*e.g. 1.7*):  1.8.0
- Python version: 3.8.10

### Reproduction instructions
- Python script
```
from onnx import helper
from onnx import TensorProto as tp
from onnx import checker
from onnx import save
import sys
import argparse
import os

node = helper.make_node(
    'Split',
    inputs=['input'],
    outputs=['output0', 'output1', 'output2'],
)
graph = helper.make_graph(
    [node], 'test_graph',
    [helper.make_tensor_value_info('input', tp.FLOAT, [4, 1, 6, 6])],
    [helper.make_tensor_value_info('output0', tp.FLOAT, [2, 1, 6, 6]),
      helper.make_tensor_value_info('output1', tp.FLOAT, [1, 1, 6, 6]),
      helper.make_tensor_value_info('output2', tp.FLOAT, [1, 1, 6, 6])])
model = helper.make_model(graph, producer_name='model')

checker.check_model(model) # Not returning error
inferred_model = shape_inference.infer_shapes(model) # Raised "The input is not evenly splittable"
```

### Expected behavior
`check_model()` should return similar error as `infer_shapes()` does

**Comment by jcwchen** [comment]
Hi @GuanLuo,
Actually onnx.checker has two levels of checking -- check_model(model) and check_model(model, full_check=True).
For the second one (full_check=True), it further runs onnx.shape_inference to check the type equality. You should see this error as well while turning on full_check. Thanks.

**Comment by GuanLuo** [comment]
Thanks, setting `full_check` does return the error.
