### ISSUE TITLE
How to concatenate strings in ONNX?

### ISSUE THREAD

**Issue by janjagusch** [onnx/onnx#3653]
# Ask a Question

### Question

We have a use case where we would like to concatenate string tensor pairwise. Here is some pseudo code of what I'm trying to accomplish:

```
tensor1 = ["a", "b", "c"]
tensor2 = ["d", "e", "f"]

concat(tensor1, tensor2)
> ["ad", "be", "cf"]

# Should also support broadcasting
concat(tensor1, "g")
> ["ag", "bg", "cg"]
```

The existing [`concat`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#concat) is not helping me, as it only concats the tensor into a tensor of a higher rank instead of concatenating the strings.

Is it possible to accomplish this with the current ONNX operator set?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*):

- Is this issue related to a specific model? No.

**Comment by gramalingam** [comment]
Unfortunately, I don't think so. ONNX doesn't have a string-concatenator operator.

**Comment by AlexandreEichenberger** [comment]
FYI this feature is one that is being requested in the ONNX Roadmap discussion.
https://onnx.ai/news.html#new60

It will be discussed Sept 8th at 9pm EST
Sept 8th (5:30 to 6pm – PST)
1. Takuya Nakaike (IBM) – New operators for data processing to cover ML pipeline (eg: Stringconcatenator, Stringsplitter, Date)
2. Adam Pocock (Oracle labs) – C API for C++ components of ONNX (to assist in wrapper for model checker functionality)
3. Adam Pocock (Oracle labs) – Better support for emitting ONNX models from other languages beyond Python

Check the link above on how to join.

**Comment by janjagusch** [comment]
> FYI this feature is one that is being requested in the ONNX Roadmap discussion.
> https://onnx.ai/news.html#new60
> 
> It will be discussed Sept 8th at 9pm EST
> Sept 8th (5:30 to 6pm – PST)
> 
> 1. Takuya Nakaike (IBM) – New operators for data processing to cover ML pipeline (eg: Stringconcatenator, Stringsplitter, Date)
> 2. Adam Pocock (Oracle labs) – C API for C++ components of ONNX (to assist in wrapper for model checker functionality)
> 3. Adam Pocock (Oracle labs) – Better support for emitting ONNX models from other languages beyond Python
> 
> Check the link above on how to join.

Thanks @AlexandreEichenberger. I couldn't attend yesterday's session (I'm in CET), so I was wondering if there is a recording/transcript of what has been discussed.

**Comment by AlexandreEichenberger** [comment]
https://www.youtube.com/watch?v=RJKXRgfKjkQ

**Comment by janjagusch** [comment]
> https://www.youtube.com/watch?v=RJKXRgfKjkQ

Thanks! I will close this issue for now.
