### ISSUE TITLE
Update Loop spec to support mixed type of v_initial and v_final_and_scan_outputs

### ISSUE THREAD

**Issue by jiafatom** [onnx/onnx#3655]
# Feature Request

### System information
ONNX version (you are using): 1.9.0

### What is the problem that this feature solves?
I am converting a pytorch model (encoder-decoder), and there is a loop which looks like:
```python
for gen_ix in range(int(self.max_length) - 1):
      outputs, states = self.incremental_decoder(generated[:, -1].unsqueeze(0), encoder_outputs, states)
      ....
      generated = torch.cat((generated, next_token.unsqueeze(0).unsqueeze(0)), dim=1)
```
where `outputs` and `generated` are of type `Long`, but `states` is of type `Float[]`. When we export it to ONNX, the model is invalid because of the mixed type of loop carried dependency values. The ONNX spec just defines a single type `V`, but we want to suggest the types can be different, each value can have its own type.

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
converters, inference.

**Comment by jiafatom** [comment]
cc @hariharans29

**Comment by gramalingam** [comment]
Hi, the ONNX spec already allows different state variables to have different types. (This is what the "heterogeneous" annotation means.) However, the same state variable should have the same type (both initially before the loop as well as the value assigned inside the loop). Is it possible that these are different in the pytorch code? Could it be an exporter error? If the same variable has different types (inside and outside the loop), you could try a cast in one place to make them same.

**Comment by askhade** [comment]
@jiafatom : Is this still relevant?
