### ISSUE TITLE
What happened in the conversion from pytorch to tensorflow

### ISSUE THREAD

**Issue by drh746** [onnx/onnx#3658]
# Ask a Question

### Question
Hi all,
        I am trying to convert a trained Pytorch model to Tensorflow by ONNX, but I would like to know more detail about the process during the conversion. Could you tell me which piece of code would be relevant? 
        Thank you!

### Further information
- Relevant Area (*e.g. model conversion*): 

- Is this issue related to a specific model?  
**Slimmable neural network* (*e.g. *):  

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @drh746,
Two steps:
1. First use `torch.onnx.export` to convert your PyTorch model to ONNX. For instance, https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx
2. Then use `onnx_tf.backend.prepare` to convert the ONNX model to TensorFlow model. For example, https://github.com/onnx/onnx-tensorflow/blob/master/example/onnx_to_tf.py

**Comment by drh746** [comment]
> Hi @drh746,
> Two steps:
> 
> 1. First use `torch.onnx.export` to convert your PyTorch model to ONNX. For instance, https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx
> 2. Then use `onnx_tf.backend.prepare` to convert the ONNX model to TensorFlow model. For example, https://github.com/onnx/onnx-tensorflow/blob/master/example/onnx_to_tf.py

Thank you. 

I am wondering whether you can point out the **source** code of the conversion.  Because what I need to convert is a dynamic model, I want to know what happens inside.

Many Thanks

**Comment by jcwchen** [comment]
- PyTorch to ONNX exporter: https://github.com/pytorch/pytorch/blob/8726f08e1520721ce8ea262ae4c8ff490f47ac20/torch/onnx/__init__.py#L32

- ONNX to TensorFlow:
https://github.com/onnx/onnx-tensorflow/blob/f1ceb91c8593a72b538b5e4eb9f369e70a8d3ed0/onnx_tf/backend.py#L41

These are the main conversion functions and you can trace other function details in their repos. Thanks
