### ISSUE TITLE
What are the dependencies that I would need for a C implementation of the ONNX runtime?

### ISSUE THREAD

**Issue by abhinandanudupa** [onnx/onnx#3660]
I am working on a project where I should build a ONNX runtime that would run on a **C only environment (where security is the top priority)**. And to do that I need to build a _C (Language) equivalent_ to the ONNX runtime that could run the ONNX ML models (for example those in the tutorials section).

I wanted to know if it is possible to do so and more importantly how I would achieve that?
So far I have found out that I need a library like OpenBLAS or a similar Linear Algebra library  (that is compatible with ONNX) and Protobuf (C implementation), and  I would like to know what the rest of the dependencies for the ONNX runtime are. 

I will be using an ARM processor (on Smart Phone) which would run be running linux and supports only applications that are written in C to run my models.

Also I am just a student and have a lot to learn.

**Comment by jcwchen** [comment]
Hi @abhinandanudupa,
I think it should be a question for ONNXRuntime, not ONNX. Some docs which might be helpful: https://onnxruntime.ai/docs/reference/api/c-api.html#builds. If you still have questions, please raise an issue under https://github.com/microsoft/onnxruntime. Thanks!

**Comment by abhinandanudupa** [comment]
> Hi @abhinandanudupa,
> I think it should be a question for ONNXRuntime, not ONNX. Some docs which might be helpful: https://onnxruntime.ai/docs/reference/api/c-api.html#builds. If you still have questions, please raise an issue under https://github.com/microsoft/onnxruntime. Thanks!

I am sorry about that, I saw that in https://github.com/microsoft/onnxruntime the ONNX was a dependency and thought that here is where I should be asking.
Thank you!
