### ISSUE TITLE
Make version_converter be able to parse data from external tensor

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#3662]
# Feature Request

### What is the problem that this feature solves?
ONNX functions will support loading external tensor: https://github.com/onnx/onnx/pull/3630, but version converter won't   be included. Currently version_converter only accesses raw_data from the original tensor and it does not check whether it has data_location and loads data from another external tensor. Two approaches to achieve this support:
1. (Lazy load) Only load external tensor when needed
    - Reshape_5_4: https://github.com/onnx/onnx/blob/c24cd429c4ab47d2b057da8174788c39c60f8760/onnx/version_converter/adapters/reshape_5_4.h#L30
    - Split_13_12: https://github.com/onnx/onnx/blob/c24cd429c4ab47d2b057da8174788c39c60f8760/onnx/version_converter/adapters/split_13_12.h#L30
    - Upsample_9_8: https://github.com/onnx/onnx/blob/c24cd429c4ab47d2b057da8174788c39c60f8760/onnx/version_converter/adapters/upsample_9_8.h#L31
    - And etc. There might be other conversions need ParseData too
2. (Globally load) Load all external tensor while converting ONNX protobuf to IR: https://github.com/onnx/onnx/blob/c24cd429c4ab47d2b057da8174788c39c60f8760/onnx/common/ir_pb_converter.cc#L84

Personally I vote the first approach since it's more efficient. Any input/feedback is appreciated. Thanks!

### Describe the feature
There are more and more large ONNX models have larger tensors. Loading all tensors from external data while loading will easily reach 2GB Protobuf limitation. Therefore, we do want all ONNX functions to have this ability to handle models without loading all external data. It would be great if version converter can support it as well.

### Will this influence the current api?
No

### Feature Area
version_converter

### Notes
@matteosal @annajung Feel free to pick this up if you are interested. Thank you!

**Comment by askhade** [comment]
@jcwchen : Can we close this issue?

**Comment by jcwchen** [comment]
Yes I think we can close it because in practice small shape info should not be stored in external tensor. Therefore, this shouldn't be an issue in version_converter. Moreover, even if that is the case, actually ONNX does have a workaround to reload the model with proper threshold to prevent issue like it, as you mentioned. Close here now. Thanks!
