### ISSUE TITLE
How to make custom operator in onnx and run it in onnx-runtime?

### ISSUE THREAD

**Issue by YuxinWang6** [onnx/onnx#3669]
# Ask a Question
How to make custom operator in onnx and run it in onnx-runtime?
### Question
I learned how to export Pytorch model with custom op to ONNX and run it in ONNX Runtime from https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md
In this way, I have to write the same custom op twice (for pytorch and for onnx runtime)
in my project I only need custom op in onnx and onnx runtime.

How to create custom op and register it in both onnx and onnx-runtime?

**Comment by jcwchen** [comment]
Hi @YuxinWang6,
- For ONNX, you need to [set the domain name](https://github.com/onnx/onnx/blob/c24cd429c4ab47d2b057da8174788c39c60f8760/onnx/helper.py#L87) for opset. Then ONNX checker will know it's an op from your custom domain instead of official ONNX domain.
- For ONNXRuntime, I think you directly use custom op (https://onnxruntime.ai/docs/how-to/add-custom-op.html) with the same domain name you use in the previous step.

**Comment by askhade** [comment]
@YuxinWang6 : A custom op is called "custom op" because it is not part of the ONNX standard. You don't have to register the custom op in ONNX.

**Comment by askhade** [comment]
@YuxinWang6 : Did the replies help? Closing this issue now, please reopen it if this is still an open issue for you.

**Comment by CUGfred** [comment]
@askhade while if i dont register custom op , i cant use it for inference in OnnxRuntime

**Comment by abhiagwl4262** [comment]
Hey @askhade, 
I am able to export a custom torch.autograd.Function to ONNX but not able to do inference with onnxruntime. I am facing the same  
`error: _DCNv2 is not a registered function/op

I am using following code for DCN_V2 class https://github.com/jinfagang/DCNv2_latest/blob/master/dcn_v2_onnx.py

where I have changed the symbolic function like this

```
class _DCNv2(Function):

    @staticmethod
    def symbolic(g, input, offset_mask, weight, bias, stride, padding, dilation, deformable_groups):
        return g.op("ai.onnx.contrib::_DCNv2", input, offset_mask, weight, bias, name_s="DCNv2", info_s=json.dumps({
            "dilation": dilation,
            "padding": padding,
            "stride": stride,
            "deformable_groups": deformable_groups
        }))
```
To export I am using -

```
torch.onnx.export(net, torch.randn(1,3,W,H), "custom_model.onnx", opset_version=13,
                custom_opsets={"ai.onnx.contrib": 13})
```


I am using this piece of code to load the model with onnxruntime

```
 import onnxruntime as _ort
from onnxruntime_extensions import (
            onnx_op, PyCustomOpDef,
            get_library_path as _get_library_path)
# from onnxruntime.tools import pytorch_export_contrib_ops
# pytorch_export_contrib_ops.register()


@onnx_op(op_type='_DCNv2', domain='ai.onnx.contrib',
         inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float,
                 PyCustomOpDef.dt_float], outputs=[PyCustomOpDef.dt_float])
def _DCNv2(x, y, z, p, q):
    return q

so = _ort.SessionOptions()
so.register_custom_ops_library(_get_library_path())

sess = _ort.InferenceSession("model.onnx", None)
```
Can you help me resolving this ?

**Comment by chayliu1991** [comment]
I face the same problem.
I want to change one operator in my onnx model to a  set of substitution operators which can run on my hardware backend.
But, one of the substitution operators is my custom operator.
So,how can I register or add my own operatpr to onnx directly？
