### ISSUE TITLE
pytorch to Onnx with export_params=False

### ISSUE THREAD

**Issue by Yif-Yang** [onnx/onnx#3670]
# Ask a Question

### Question
Explain your question here.

I want to save the computations on Onnx without leaving the model parameters, and then restore the computations using pyTorch's static dictionary. What can I do?

`    torch.onnx.export(
        prune_hugging_face_model,
        tuple([val for val in model_inputs.values()]),
        os.path.join(DIR, output_filename),
        input_names=[key for key in model_inputs.keys()],
        output_names=['out1', 'out2', 'out3','out4'],
        verbose=False,
        export_params=False,
        opset_version=11,
        do_constant_folding=True
    `

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @Yif-Yang,
I think it should be a question for the converter (torch.onnx.export). Could you please raise an issue in PyTorch repo to get the best help from the converter experts? Thanks!
