### ISSUE TITLE
What does negative dimension imply

### ISSUE THREAD

**Issue by GuanLuo** [onnx/onnx#3673]
# Ask a Question

### Question
I was toggling the node parameters for testing and I noticed that the ONNX checker doesn't complain on the following model whose output has negative value for the last two dimensions. I am under the impression that the model is invalid and I wonder if negative value has special meaning.

### Further information
Model gen script
```
from onnx import helper
from onnx import TensorProto as tp
from onnx import checker
from onnx import save
import sys
import argparse
import os

node = helper.make_node('MaxPool',
                        inputs=['input'],
                        outputs=['output'],
                        kernel_shape=[5, 5],
                        strides=[2, 2],
                        dilations=[2, 2])
graph = helper.make_graph(
    [node], 'test_graph',
    [helper.make_tensor_value_info('input', tp.FLOAT, [1, 1, 5, 5])],
    [helper.make_tensor_value_info('output', tp.FLOAT, [1, 1, -1, -1])])
model = helper.make_model(graph, producer_name='model')
checker.check_model(model, full_check=True)
```

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @GuanLuo,
For any converted ONNX model, I think there should be no negative dimension so -1 isn't a valid dim_value. I don't have the history context here about why ONNX checker does not forbid negative dimension, but I guess it grants Runtime have the availability to use it (For instance, https://github.com/microsoft/onnxruntime/issues/3242#issuecomment-669745481)

@gramalingam I saw you suggested that `check for negative dim-value may still be useful.` in an old PR. Is this check still valid now?  (https://github.com/onnx/onnx/pull/2266/files#r318817405) Thanks!

**Comment by gramalingam** [comment]
Yes, in an ONNX ShapeProto, a negative value is not valid. Technically, it makes sense to have the checker catch and report an error for this case. However, some other frameworks use the special value -1 to indicate an unknown dimension. Hence, there may be some older models that incorrectly use -1 to indicate an unknown dimension. So, throwing an error could cause some compatibility issues for such models. I think it might make sense for us to have the notion of a "warning" and flag such issues with a "warning" instead of "error" to balance these requirements.

**Comment by GuanLuo** [comment]
For the compatibility reason that @gramalingam mentioned, should application build with ONNX format also treat -1 to be indicator of dynamic dimension, in addition to string (symbolic variable)? Or if the application is utilizing ONNX shape inference, would that make sense if shape inference will convert -1 entry to symbolic variable so the application can simply assume -1 will not be seen and expect string when the tensor has dynamic dimensions?

**Comment by askhade** [comment]
Depending on what versions of ONNX models the runtimes support then can choose to not allow -1 in shapes. Another approach is to clear the -1 entry and treat this dimension as an unknown dimension - For example this is how ORT handles it: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/graph/graph.cc#L136

Regarding onnx checker - we can add strict mode similar to shape inference APIs. When mode is set to strict such errors can be reported, this way checker will still work for older models.

At some point we do need to think compatibility for older (incorrect models) vs correctness. Perhaps we can add all these improvements to default checker and shape inference in ONNX 2.0?

**Comment by gramalingam** [comment]
Yes for a more flexible checker, to let users control it. There may also be value in a "cleanup" utility for cleaning up minor violations like this (just like in the ORT link above, but as an ONNX utility). An example other such violations that we tolerate is that the standard says identifiers should be valid C identifiers, but many models violate this and use arbitrary strings.

**Comment by askhade** [comment]
agree - another such violation is nodes are not sorted in topological order. I encountered 1 case where the model was valid but the nodes were not in the right order (mostly because some offline optimization script was run) ... ORT allows this too
