### ISSUE TITLE
Onnx shape inference incorrect for ConstantOfShape

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [onnx/onnx#3675]
# Bug Report

The following model is a ConstantOfShape op with a constant input [4, 3].  The output shape should match the value of the constant input, or at least be unknown.  Onnx reports the output shape as [12884901892].  Similar strange results appear for values other than [4, 3].

```python
from onnx import helper, numpy_helper, TensorProto

import onnx
import numpy as np

model = helper.make_model(
    opset_imports=[helper.make_operatorsetid('', 14)],
    ir_version=8,
    graph=helper.make_graph(
        name='infer-graph',
        inputs=[],
        outputs=[helper.make_tensor_value_info('tfl.scatter_nd__12:0', TensorProto.FLOAT, shape=None)],
        initializer=[numpy_helper.from_array(np.array([4, 3], dtype=np.int32), name='std.constant')],
        nodes=[helper.make_node('ConstantOfShape', inputs=['std.constant'], outputs=['tfl.scatter_nd__12:0'], name='tfl.scatter_nd__12')],
    ),
)

model_shapes = onnx.shape_inference.infer_shapes(model)
onnx.checker.check_model(model_shapes)
print(model_shapes.graph.output)
```

Output:
```
[name: "tfl.scatter_nd__12:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 12884901892
      }
    }
  }
}
]
```

Onnx version 1.10.1

**Comment by TomWildenhain-Microsoft** [comment]
In certain cases, this shape inference can cause a Segmentation Fault.

**Comment by jcwchen** [comment]
Hi @TomWildenhain-Microsoft,
I can repro this (int32 input does not work), but I tried it with np.int64 initializer and the output shape worked as expected. According to the [spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#type-constraints-24) of ConstantOfShape-9, it only supports int64 as input so the [shape inference](https://github.com/onnx/onnx/blob/2e947e5a3fb8be172cae549d03ae5aa7059f8747/onnx/defs/generator/defs.cc#L270) only handles the case of parse int64.

Another thing is, if you enable strict_mode (enable type equality check) for shape_inference, you will see an error about it: `[ShapeInferenceError] (op_type:ConstantOfShape, node name: tfl.scatter_nd__12): input typestr: T1, has unsupported type: tensor(int32)`. This check is silent without strict_mode and the output will be unexpected.

**Comment by jcwchen** [comment]
After my recent PR #3702 merged, now ParseData won't go forward if there is a mismatch between given type and the actual tensor type. This kind of unexpected behavior should not happen again. Close it now. Thanks!
