### ISSUE TITLE
I am confused about opset versioning policy

### ISSUE THREAD

**Issue by suhyung-jang** [onnx/onnx#3678]
# Ask a Question

### Question

Why does every node have to have opset information individually? Is it possible to have the same domain (ex: ai.onnx) and different versions (ex: 11,12) for each node in one model?

If so, why did you allow multiple versions for one domain? If the higher version is backwards compatible, wouldn't it be okay to allow only one version?

If not, shouldn't it be okay to have the opset version in the model rather than the node?

Please understand if my question is too naive.

**Comment by linkerzhang** [comment]
opset version is being specified in model https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L353, not in node.

**Comment by suhyung-jang** [comment]
@linkerzhang Thank you for your response. You are right. opset version is contained in model not node. but As I know, a model can have multiple opsets.( https://github.com/onnx/onnx/issues/688 ). so I misunderstand that each node can use other opsets. 
In what cases will the model have multiple opsets?

**Comment by linkerzhang** [comment]
Say, multiple opsets with different domains (for example, one onnx domain opset, one customized domain opset).

**Comment by askhade** [comment]
Please reopen if you still have questions
