### ISSUE TITLE
google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by xinkchen** [onnx/onnx#3682]
# Bug Report

### Describe the bug
when I use onnx.load("googlenet-7.onnx"),but an error raised "google.protobuf.message.DecodeError: Error parsing message"

### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX version :  1.8.0 (1.3.0 is also)
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:3.17.3
- Visual Studio version (if applicable):

### Reproduction instructions
when I use onnx load a googlenet-7.onnx and googlenet-8.onnx
```
import onnx
model = onnx.load('model.onnx')
...
```
- Attach the ONNX model to the issue (where applicable)

### my error

   self._model  = onnx.load_model(model_path)
  File "./network_diagnosis/venvs/frameworks/onnx/1.8.0/lib/python3.6/site-packages/onnx/__init__.py", line 119, in load_model
    model = load_model_from_string(s, format=format)
  File "./network_diagnosis/venvs/frameworks/onnx/1.8.0/lib/python3.6/site-packages/onnx/__init__.py", line 156, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "./network_diagnosis/venvs/frameworks/onnx/1.8.0/lib/python3.6/site-packages/onnx/__init__.py", line 97, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message

### Notes
my onnx and onnxruntime and protobuf all install used  pip3 install *** 
and the googlenet-7.onnx /googlenet-8.onnx was download from https://github.com/onnx/models/tree/master/vision/classification/inception_and_googlenet/googlenet

**Comment by askhade** [comment]
Can you try opening these models with netron? 
I see you are using an older version of onnx. Please update to the latest version and make sure your protobuf version is compatible with onnx. Use 3.16 https://github.com/onnx/onnx/blob/master/requirements-release.txt#L2
