### ISSUE TITLE
Exporting the operator maximum to ONNX opset version 13 is not supported. 

### ISSUE THREAD

**Issue by Liulin1027** [onnx/onnx#3688]
Error converting onnx file, version not supported

**Comment by jcwchen** [comment]
Hi @Liulin1027,
I think the conversion should be doable by existing ONNX ops, but currently maximum is not supported by the converter: https://pytorch.org/docs/stable/onnx.html#supported-operators. Please request this op support in the converter (torch.onnx.export). Thanks!
