### ISSUE TITLE
Feature request : Support data format NHWC and NCHW

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#369]
I opening this thread to ask if is could be possible that ONNX supports different data formats like 'NCHW' and 'NHWC'
Will could imagine an additional optional attribute for Ops concerned by tensor data format.

This would be really convenient to don't transpose than re transpose tensors when proceeding to Front-End -> ONNX -> Back-End.

**Comment by ebarsoum** [comment]
ONNX is disk format, not an in memory format. So the conversion happen during export and import.

**Comment by LucasMahieu** [comment]
Yes, I agree with you but it could be interesting to add this attr to have more flexibility with frameworks. This could permits to don't have to add convertion ops in imported or exported networks

**Comment by sergeigofman** [comment]
It is true that any operation in NHWC layout can be converted to NCHW by inserting Transpose node before and after it that would convert NCHW to NHWC and vice versa. However, it would be cleaner to allow both layouts as there are numerous frameworks that support both.

**Comment by LucasMahieu** [comment]
I think it could be very very interesting.

**Comment by rshlomo** [comment]
Agree, native support is the right way to go

**Comment by LucasMahieu** [comment]
Who could add this feature to ONNX ? And when do you think it could be available ? 
Because this feature could significantly speed up the front end support of tensorflow that we are actively developing.

**Comment by ezyang** [comment]
Yes, this is something we'll have to talk about. Adding this feature would have pretty far-ranging consequences, since every operator would need to know about data formats to know how to adjust themselves depending on the regime; unsure if the complexity cost here is worth it.

**Comment by prasanthpul** [comment]
For consistency the ONNX spec only uses one format. The TF2ONNX converter optimizes the transposes.
