### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

### ISSUE THREAD

**Issue by captain81** [onnx/onnx#3690]
Hi,
I’m trying to convert a pytorch model to onnx, but the conversion gives the following error:

RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

The definition for qfn is:

class qfn(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, k):
        n = float(2**k - 1)
        out = torch.round(input * n) / n
        return out

    @staticmethod
    def backward(ctx, grad_output):
        grad_input = grad_output.clone()
        return grad_input, None

**Comment by jcwchen** [comment]
Hi @captain81,
It should be a question for the converter (torch.onnx.export). I think currently the converter only supports native PyTorch ops. I saw you opened an issue under PyTorch, which is a better place to track this issue. Close it now. Please reopen if you still have other ONNX questions. Thanks!
