### ISSUE TITLE
shape inference

### ISSUE THREAD

**Issue by zhenglongjiepheonix** [onnx/onnx#3693]
I think some ops should propagate its result rather than the shape of its result in order to let following ops work properly during shape inference, for example, consider the following case
<img width="648" alt="截屏2021-09-01 下午10 19 35" src="https://user-images.githubusercontent.com/32992656/131688138-822897eb-cdd9-400d-98c5-c25b25cb131f.png">
the shape op here should propage the exact shape instead of the shape of its own result here for proper work of the shape deduction of the expand op?

**Comment by jcwchen** [comment]
Hi @zhenglongjiepheonix,
Basically, general shape inference in ONNX only propagates "shape" of tensors, but yes we do see the need of propagating "Shape result" after Shape op. Therefore, ONNX 1.10 brought data propagation to handle this kind of scenario: https://github.com/onnx/onnx/pull/3551 However, it still has some limitations:
1. The "shape" data can only be obtained by a following Reshape op (it's a common use case for Bert models)
2. There are only limited ops support data propagation, and Expand is not one of them for now

Ideally, ONNX will support data propagation for more ops (on demand). May I ask you which model you are using and what else ops besides `Expand` you want to support?

> is there a way to define behavior of certain op during shape inference

Shape inference for certain op is defined as `TypeAndShapeInferenceFunction` under onnx/defs/xxx/defs.cc. Take Shape as an example: https://github.com/onnx/onnx/blob/208ac9b998556cbc5112cdf1b43e7ef679831560/onnx/defs/tensor/defs.cc#L431.

**Comment by zhenglongjiepheonix** [comment]
thanks for the response, I think every op which may take a shape as input and the output shape is related with the shape input needs such consideration, and dynamic input could make the situation become more complex, the data result of a shape op is 
simply the real practical shape of the input, symbolic shape may fail to propagate by data

**Comment by zhenglongjiepheonix** [comment]
a shape tracer may be needed where both the dynamic symbolic shape and the shape of shape tensor are propagated, dynamic symbolic shape is propagated and transformed in the exact same way as the data until it meets some reshape or expand or somewhat op

**Comment by jcwchen** [comment]
Thank you for sharing your thought! ONNX will add more ops to support this kind of dynamic situation.

FYI: https://github.com/onnx/onnx/blob/master/docs/proposals/SymbolicShapeInfProposal.md ONNX just released a new document, which mentions more details about this topic. Thanks.

**Comment by wangxudong-cq** [comment]
By the way, how to define a value_info about the non-tensor output, shape inference result is None.

**Comment by jcwchen** [comment]
> By the way, how to define a value_info about the non-tensor output, shape inference result is None.

Not sure I understand this -- did you mean you are looking for shape info of graph's output in graph.value_info? If so, they won't be included in graph.value_info according to IR definition: https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs.
