### ISSUE TITLE
"graph" operator in examples notebook

### ISSUE THREAD

**Issue by MandarinDuck** [onnx/onnx#3701]
### Question
[This](https://github.com/onnx/onnx/blob/master/onnx/examples/Protobufs.ipynb) .ipynb refers to placing a subgraph within a node in the final cell. I can't find any further documentation refering to it, and when I have tried it and executed the resulting model in onnx-runtime it returns the error `onnx failed:This is an invalid model. Error in Node: : No Op registered for Graph with domain_version of 14`. `graph` is not a listed ONNX operator either, so it appears that the construct isn't actually possible. Could someone clarify?

### Notes
USing **Model opset** (*14*)
The example code in question is as follows:
```node_proto = helper.make_node(
    "graph",
    ["Input", "W1", "B1", "W2", "B2"],
    ["Output"],
    graph=[graph_proto],
)```

**Comment by jcwchen** [comment]
Hi @MandarinDuck,
I don't have the history context here, but I would say this example is more like a demo about how to create an attribute, a node, a graph and a node with a subgraph. However, some of them are dummy operators or attributes so they cannot be used by ONNX/ONNXRuntime. For instance, "FC" and "graph" are not official ONNX operators and thus you will see an error saying that there is no opset schema definition for them when using ONNX/ONNXRuntime. 

If you are looking for an example of a node with a subgraph, you can check the Loop node test here: https://github.com/onnx/onnx/blob/780188f3dedf11b1b6c6805b529d1432655f44a5/onnx/backend/test/case/node/loop.py#L112

**Comment by gramalingam** [comment]
As @jcwchen says, this is just to meant to be an illustrative example. Valid ONNX ops that require a subgraph are "If", "Scan" and "Loop". If you want to try something that will run, you will have to create a valid model with one of these control-flow ops.

**Comment by MandarinDuck** [comment]
Thanks - impressively prompt responses.
