### ISSUE TITLE
PythonAPI doesn't provide same nodes as from C

### ISSUE THREAD

**Issue by jangmin-deepx** [onnx/onnx#3708]
# Bug Report

### Describe the bug
onnx checker checks nodes that does not provided from python onnx api

```python3
onnx.checker.check_model(onnx_model)
```
Error Message
```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '__inference_Preprocessor_ResizeToRange_cond_true_20814_15308_Preprocessor/ResizeToRange/cond/resize/Cast_2:0' of node: 
name:  OpType: Div
```
### System information
- Linux Ubuntu 18.04
- ONNX version 1.8.1
- Python version: 3.8.5
- Protobuf version: 3.17.3

### Reproduction instructions
```
import onnx
onnx_model= onnx.load('model.onnx')
onnx.checker.check_model(onnx_model)
```
- [model.onnx](https://drive.google.com/file/d/1V-f4IEtvCtVIsCkC8Pont9lHmIkN8hMS/view?usp=sharing)

### Expected behavior
Checker should return success but it fails with validation Error.
Even If i sorted nodes with topologically, it was no use.

I think what checker consider is differ from what onnx_model.graph.node provides

```
From onnx/checker.cc L:782~

void check_function(const FunctionProto& function, const CheckerContext& ctx, const LexicalScopeContext& parent_lex) {
...
  for (const auto& node : function.node()) {
    // nodes must be in topologically sorted order
    for (const auto& input : node.input()) {
      // explicit optional input
      if (input.empty()) {
        continue;
      }
      if (!lex_ctx.this_graph_has(input)) {
        fail_check(
            "Nodes in a function must be topologically sorted, however input '",
            input,
            "' of node: \n",
            "Name: ",
            node.name(),
            " OpType: ",
            node.op_type(),
            "\n is neither output of any previous nodes nor input of the function.");
      }
    }
```
I think node from ```function.node()``` should be exactly matched with ```onnx_model.graph.node``` but it doesn't

Please kindly tell me any suggestion to remove nodes that doesn't came out from ```onnx_model.graph.node```

**Comment by askhade** [comment]
I am unable to open your model. Does your model have function ops? If yes then the nodes within the function body should also be topologically sorted. 
function.node() returns nodes within the function body

**Comment by askhade** [comment]
Closing this issue now. @jangmin-deepx please add more info and reopen this issue if this is still relevant.
