### ISSUE TITLE
is it possible to compute output shape of operators using onnx.helper?

### ISSUE THREAD

**Issue by iperov** [onnx/onnx#3710]
is it possible to compute output shape of operators using onnx.helper?

for example
```
helper.make_node('GreaterOrEqual', ...
```
requires inputs and output using `helper.make_tensor_value_info` that requires a `shape`, but how to compute output shape of nodes, especially broadcasting nodes?

**Comment by jcwchen** [comment]
Hi @iperov,
`onnx.helper` is mainly for creating model/graph/node/tensor/value_info. If you are looking for computing shapes, you can use `onnx.shape_inference` with a small model to get inferred shapes in `graph.value_info`

**Comment by iperov** [comment]
@jcwchen 
ok, for example for node GreaterOrEqual,
first argument shape (4,2)
second argument shape (8,1,4)

can you provide the code to compute output shape ?

**Comment by iperov** [comment]
I figured out, thanks
