### ISSUE TITLE
TensorProto.FLOAT16 : TypeError: 0.0 has type float, but expected one of: int, long

### ISSUE THREAD

**Issue by iperov** [onnx/onnx#3715]
### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Windows 10
- ONNX version (*e.g. 1.7*):  1.10.1
- Python version: 3.7.9
- Protobuf version: 3.17.3

### Reproduction instructions
 ```
onnx_helper.make_tensor(name='asd', data_type=TensorProto.FLOAT16, dims=(3,), vals=[0.0, 0.0, 0.0] )
```

```
TypeError: 0.0 has type float, but expected one of: int, long
```

### Expected behavior

expected no error

**Comment by jcwchen** [comment]
Hi @iperov,
Similar to https://github.com/onnx/onnx/issues/3204. ONNX uses int32_data to store `float16`: https://github.com/onnx/onnx/blob/a5e7ee51176bf78a60c118758174e13d85a87b46/onnx/mapping.py#L41 So you need a conversion from float16 to uint16 like:
```
original_val = np.array([0.0, 0.0, 0.0]).astype(np.float16)
converted_val = original_val.view(dtype=np.uint16).flatten()
onnx_helper.make_tensor(name='asd', data_type=TensorProto.FLOAT16, dims=converted_val.shape, vals=converted_val.tolist())
```

**Comment by iperov** [comment]
but why? can you fix this shit?
