### ISSUE TITLE
Bert e2e model support? onnx.OneHot: inferShapes() not implemented

### ISSUE THREAD

**Issue by Joejiong** [onnx/onnx#3725]
# Bug Report

### Is the issue related to model conversion? yes
Hi friends,

Is there any bert.onnx -> bert.mlir sample code? 
when I when to onnx model to test 

### System information
- OS Platform and Distribution :Linux Ubuntu 20.04
- ONNX version :(*e.g. 1.10)
- Python version: 3.8
- GCC/Compiler version (if compiling from source): clang12

### Reproduction instructions

```
onnx-mlir --EmitLib bertsquad-10.onnx
error: onnx.OneHot: inferShapes() not implemented
error: shape inference failed
```
- Attach the ONNX model to the issue (where applicable)
in onnx modelzoo bertsquad-10.onnx real model.

**Comment by jcwchen** [comment]
Hi @Joejiong,
This error happened in the converter so it should be a question for the converter (onnx-mlir). I saw you have already created an issue under onnx-mlir, which is a better place to track this issue. Close here now. Please reopen it if you still have other ONNX questions. Thanks
