### ISSUE TITLE
Different shape inference behavior between Python and C++

### ISSUE THREAD

**Issue by GuanLuo** [onnx/onnx#3728]
# Bug Report

### Describe the bug
I obtained a [BERT model](https://github.com/onnx/models/blob/master/text/machine_comprehension/bert-squad/model/bertsquad-8.onnx) from ONNX model zoo and convert it to opset 15 because its original opset is too old for my application. However the shape inference (C++) I added to the application reports the following error, while I tried the same in Python and no error was raised. Is this expected? I would think that the Python version is a wrapper over the C++ one and thus it seems weird to me.
```
[ShapeInferenceError] Shape inference error(s): (op_type:MatMul, node name: bert/encoder/layer_0/attention/self/MatMul_1): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:MatMul, node name: bert/encoder/layer_1/attention/self/MatMul_1): [ShapeInferenceError] Input tensors of wrong rank (0).
... 
(op_type:MatMul, node name: bert/encoder/layer_10/attention/self/MatMul_1): [ShapeInferenceError] Input tensors of wrong rank (0).
(op_type:MatMul, node name: bert/encoder/layer_11/attention/self/MatMul_1): [ShapeInferenceError] Input tensors of wrong rank (0). 
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 20.04
- ONNX version (*e.g. 1.7*):  1.10.1
- Python version: 3.8.10
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
- CMake version:
- Protobuf version: 3.17.1
- Visual Studio version (if applicable):

### Reproduction instructions
- On C++, I can try to provide a minimum source file if requested
- Python side
```
import onnx
from onnx import version_converter
model = onnx.load('bertsquad-8.onnx')
model_opset_15 = version_converter.convert_version(model, 15)
# onnx.save(model_opset_15, "bertsquad-8_opset_15.onnx") # For C++ side to load
inferred_model = onnx.shape_inference.infer_shapes(model_opset_15 )
```
- Attach the ONNX model to the issue (where applicable)
- https://github.com/onnx/models/blob/master/text/machine_comprehension/bert-squad/model/bertsquad-8.onnx

### Expected behavior
Python / C++ behavior should be consistent

### Notes

I build the C++ application with ONNX from source (v1.10.1) while the Python is obtained via `pip install`

**Comment by jcwchen** [comment]
Hi @GuanLuo,
Thanks for the details. I can repro it. However, if I enable data propagation with strict_mode for shape inference: `onnx.shape_inference.infer_shapes(model_opset_15, strict_mode=True, data_prop=True)`, I can see this error as well. Do you also enable data propagation with strict_mode in C++ shape inference?

**Comment by GuanLuo** [comment]
Ahh, yes, for C++ I create the option as following `onnx::ShapeInferenceOptions options{true, 1, true};`, so it seems like I am not setting the correct option for the Python case.

My follow up question is that is  `onnx::ShapeInferenceOptions options{true, 1, true};` the correct setting to check if the model is truly valid? And if so, does that mean the converter does not work as expected?

**Comment by askhade** [comment]
@jcwchen : Are these 2 open issues? Since they belong to 2 separate components please create 2 separate issues and let's add it to out todo list.

**Comment by jcwchen** [comment]
@askhade Good point. Just decouple this issue to 2 new issues for better tracking. Close here now. Thank you @GuanLuo for catching this.

**Comment by askhade** [comment]
Once you create the issues please link this issue to them for better tracking.
