### ISSUE TITLE
clarify the semantics of an optional output followed by a non-optional output

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#373]
RNN and LSTM have outputs of

```
Y (optional) : T
A tensor that concats all the intermediate output values of the hidden. It has shape `[seq_length, num_directions, batch_size, hidden_size]`. It is optional if `output_sequence` is 0.

Y_h : T
The last output value of the hidden. It has shape `[num_directions, batch_size, hidden_size]`.
```

This is pretty weird - if the first output is missing, is it simply an empty tensor, or do the following outputs shift over (which would break any code that tries to access outputs positionally)?

**Comment by linkerzhang** [comment]
We're defining "optional" input/output in this way. In the graph, a node has a "optional" input or output in between (there're non-optional input or output behind), then an empty string "" will be put in the node's input or output as a placeholder accordingly to avoid ambiguity.

**Comment by askhade** [comment]
@anderspapitto : Closing this issue. Please reopen this if you have more questions.
