### ISSUE TITLE
Concat Axis

### ISSUE THREAD

**Issue by sousoux** [onnx/onnx#374]
Unless my protobuf implementation is up the spout (which is possible) the squeezenet model has no axis parameter in the Concat nodes. There is no default indicated. Squeezenet should be concatting on channels. What does no axis parameter indicate since the docs show no default?

**Comment by linkerzhang** [comment]
I personally am thinking of adding default value for "not required“ attribute in operator definition as issue #354 . would like to hear more thoughts from other folks too.

**Comment by sousoux** [comment]
This would seem to me to be essential. How is one supposed to deduce that
Concat has a default axis of 2 when it is mentioned nowhere?

**Comment by dzhulgakov** [comment]
Good catch. The model was originally exported from Caffe2 and the exporter doesn't take care of setting the axis (where's C2 defaults to axis=1 for C in NCHW): https://github.com/caffe2/caffe2/blob/16dacb6b9052e6b75aa1314eabe3f77e23b7c60a/caffe2/operators/concat_split_op.h#L33

It'd a bit awkward to default axis to 1 arbitrary, I'd say it should be really a required argument here. @linkerzhang - what do you think?

@anderspapitto - can you help to fix onnx-caffe2 exporter for Concat and regenerate the models? (@bddppq can point out how to do that)

**Comment by linkerzhang** [comment]
@dzhulgakov making it to be required attribute looks good. We may add checking logic to fail a model without this attribute then :). I will add this logic together with the coming change of adding default value.

**Comment by anderspapitto** [comment]
the squeezenet model in s3 has been updated to include 'axis' with the code in https://github.com/onnx/onnx-caffe2/pull/96

**Comment by ezyang** [comment]
We still need to update the def, and this is a BC-breaking change.

**Comment by linkerzhang** [comment]
To update the def, these test models need to be updated (add value for "axis" attribute) accordingly please. "test_densenet121|test_inception_v1|test_inception_v2|test_shufflenet|test_squeezenet" @ezyang @bddppq
