### ISSUE TITLE
ONNX shape inference for QuantizeLinear fails on empty string as zero_point

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [onnx/onnx#3744]
# Bug Report

### Describe the bug
An ONNX model with QuantizeLinear (opset 13) passes shape inference when it has no input for zero_point, but fails if the input is the empty string.  Trailing optional inputs should be able to be expressed in either way.

onnx version 1.10.1

**Comment by jcwchen** [comment]
Hi @TomWildenhain-Microsoft,
Do you have any handy model/script to repro it? Thanks
