### ISSUE TITLE
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '2']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by qingqinghu1026** [onnx/onnx#3746]
# Ask a Question

### Question
Explain your question here.
when Installing onnx on ubuntu18.04 and executing pip install -e ., " subprocess.CalledProcessError: Command ..."occurs, how to solve it?
### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
- [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:100: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:280: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:135: recipe for target 'all' failed
    make: *** [all] Error 2
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/qqhu/workspace/tools/onnx/setup.py", line 361, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/qqhu/workspace/tools/onnx/setup.py", line 249, in run
        self.run_command('build_py')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/qqhu/workspace/tools/onnx/setup.py", line 233, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/qqhu/workspace/tools/onnx/setup.py", line 227, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '2']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/home/qqhu/workspace/tools/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/qqhu/workspace/tools/onnx/

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.
my cmake version is 3.21.3
/workspace/tools/onnx$ whereis cmake
cmake: /usr/local/bin/cmake /usr/share/cmake

**Comment by jcwchen** [comment]
Hi @qingqinghu1026,
Similar to https://github.com/onnx/onnx/issues/3570. As the error said, the package (/usr/lib/x86_64-linux-gnu/libprotobuf.a) you have cannot used for building ONNX because it was not built with -fPIC... To resolve the erorr, could you please follow the steps [here](https://github.com/onnx/onnx#linux) to build protobuf from source, set the installed protobuf into PATH, and then build ONNX again? Thanks!

**Comment by jcwchen** [comment]
export PATH=$PATH:<your_protobuf_install_dir>/bin

**Comment by askhade** [comment]
Closing this issue now. @qingqinghu1026 hope this is resolved on your end. If not try to follow the instructions here: https://github.com/onnx/onnx#linux and if you still see any problems then report back errors.
