### ISSUE TITLE
Ops doc leaks info about the attr of kind "list of ints" 

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#375]
Hi, 
After lot of time doing retro-engineering on ONNX model, it seems that the attr of kind "list of ints" like strides or kernel_shape of max pool por example are only for Height and Width axes and not for all input axes.
But in the doc we can read : 

> strides : list of ints
>    Stride along each axis. 

So it is very unclear.

Moreover, this king of op doesn't permit to do MaxPool with kernel_shape different of 1 on the batch dimension and different from 1 for channel dimension.

So it would be good to add Ops that can make these tasks. 
Or to modify the attr of these Ops in order to have attr of same len than input dim.
For example, if input is NCHW the attr kernel_shape should be [1, 3, 2, 2] or [16, 3, 2, 2] if we want to apply max_pool over all channels of over all batch input and all channel.

It would be more generic and would cost nothing to add that in ONNX.

**Comment by ezyang** [comment]
Hello @LucasMahieu,

Perhaps I am misunderstanding your report, but what you have requested doesn't make sense to me. The point of batching MaxPool is that you are effectively running
