### ISSUE TITLE
Output of Round is confusing

### ISSUE THREAD

**Issue by tungld** [onnx/onnx#3755]
# Ask a Question

### Question
[In the definition of Round](https://github.com/onnx/onnx/blob/master/docs/Operators.md#round), it said `it finds the nearest integer for each value`, but according to the example
```
round([0.9]) = [1.0]
round([2.5]) = [2.0]
round([2.3]) = [2.0]
round([1.5]) = [2.0]
round([-4.5]) = [-4.0]
```
I am confused whether `2.0` is the nearest integer of `2.5` or `1.5`. How was the nearest integer computed? Thanks!

### Further information
Similar thing happened with the reference output of Round also: https://github.com/onnx/onnx/blob/master/docs/Operators.md#examples-110

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @tungld,
Actually the doc mentions this kind of scenario: ```In case of halfs, the rule is to round them to the nearest "even" integer. The output tensor has the same shape and type as the input.``` And this behavior is similar to numpy.around: https://numpy.org/doc/stable/reference/generated/numpy.around.html

**Comment by tungld** [comment]
Oh, I see, I am not aware of `even`. It would be helpful if we mention numpy.around in the doc. Thanks @jcwchen!
