### ISSUE TITLE
Enhancement: quantized tensors

### ISSUE THREAD

**Issue by sousoux** [onnx/onnx#376]
It would be nice if you could cope with quantized tensors. i.e. Allow fixed point 64 32 16 and 8 bit ints. Add a normalization field to the tensor for these types.

Add FIXP64, FIXP32, FIXP16 and FIXP8 types and manditory normalization field for these types.

**Comment by sergeigofman** [comment]
It would also be nice to allow for flexible enough linear quantization schemes, allowing arbitrary scale (I beleive what is referred to above as "normalization") and offset to allow for non-symmetric dynamic range.

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/616

**Comment by linkerzhang** [comment]
https://github.com/onnx/onnx/wiki/Quantization-Support-In-ONNX shows the principals that are followed when adding quantization support in onnx. The first small set of quantized operators were merged to support linear 8-bit quantization. More may be added as needed.
