### ISSUE TITLE
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3714028571

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx#3775]
```
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3714028571
```

**Comment by jinfagang** [comment]
@jcwchen the question is, the model is not directly load from model_path, is a intermediate model generate by onnxoptimize which is ModelProto.
And it can not pass optimize.

**Comment by jcwchen** [comment]
Yea I think currently onnx/optimizer still has not supported >2GB models yet: https://github.com/onnx/optimizer/issues/46 Please track this issue there. Thanks.

**Comment by simplew2011** [comment]
- https://github.com/onnx/optimizer may be help
