### ISSUE TITLE
AVAILABLE_CONVERTERS[node_type]( KeyError: 'Resize'

### ISSUE THREAD

**Issue by onkarkris** [onnx/onnx#3788]
I am using onnx_to_keras function to convert a onnx model of yolov3 (which is converted from torch model) to keras
k_model = onnx_to_keras(onnx_model,  ['input.1'])

getting error that AVAILABLE_CONVERTERS[node_type]( KeyError: 'Resize'

I have tried this solution https://github.com/gmalivenko/onnx2keras/issues/79 but cant solve the issue!

**Comment by jcwchen** [comment]
Hi @onkarkris,
The error is produced by onnx2keras and it seems like a version conflict issue in onnx2keras. Thus I think it's better to track this issue there. Close here now. Please reopen it you still have other ONNX questions. Thanks!
