### ISSUE TITLE
Add hard size restrictions to initializers and inputs

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#379]
Currently, inputs and initializers can be overridden, potentially with values of different shapes or sizes. Depending on the graph, this may or may not work at all, and in the meantime being unable to rely on static sizes complicates certain operations on the graph (for example, converting to a backend which requires certain operators to specify their size at graph construction time rather than at runtime).

I propose to add to the model explicit sizes for inputs, which may optionally be inferred (but not modified or overridden) from initializers.

**Comment by dzhulgakov** [comment]
Reformulating above a bit it basically means "for 'parameters' of the model" the shapes has to be statically provided in the graph ValueInfo input descriptions. It's totally reasonable and that's what occurs in practice anyway. We currently don't formally define what 'parameter' is in the spec, but all backend implementations explicitly assume it. For practical purposes it's probably fine to just say that inputs with initializers are parameters and their shape can't be changed after conversion.

**Comment by linkerzhang** [comment]
Confirm my understanding about this please. It's being said that "all graph inputs should be statically shaped and typed", am I right? if yes, I think this has been the agreement in ONNX, no?

**Comment by gramalingam** [comment]
Here is my understanding: I believe we want the model to be "statically typable" (using the type information supplied in the model plus type-inference and shape-inference). But we haven't yet fully formalized what this means. As @linkerzhang says, we require the model to specify the types of graph inputs/outputs, which includes shapes of (input/output) tensors. However, shapes are permitted to be symbolic identifiers (representing statically unknown values). The expectation is that such symbolic identifiers are used only when the corresponding operators permit them (that is, are polymorphic with respect to this particular dimension size). To capture this, we need to capture the type-signatures of operators, including shape-information, which we haven't so far.

**Comment by bddppq** [comment]
> For practical purposes it's probably fine to just say that inputs with initializers are parameters and their shape can't be changed after conversion.

Agree, and since the shape information are already provided in each initializer, we probably don't need to enforce them to be provided again as ValueInfoProto.
