### ISSUE TITLE
How to export a detectron2 model in onxx format ? Fatal error: AliasWithName is not a registered function/op

### ISSUE THREAD

**Issue by ghost** [onnx/onnx#3791]
# Ask a Question

### Question
I'm trying to export a detectron2 model in onnx format (model.onnx) and do inference with onnxruntime using the exported file (model.onnx).

To do so, i tried to export the famous instance segmentation model provided by detectron2 ( model_zoo ), i succeeded to get the model.onnx file ( i'm not sure if i did correctly though ) but i can't use it to do inference, can anyone tell me what i'm doing wrong ?

Here is a shared google colab notebook containing my code https://colab.research.google.com/drive/11BB-iufQCmwHoRzS4iBFwH7SqasDOik8?usp=sharing

Note : In order to modify the file, you'll have to make a copy of it in your drive !

And here is the error message ( you can find it in the notebook but i wanted to add it just for SEO purposes, in case someone is looking for a solution to the same problem ) 

```
Fail
Traceback (most recent call last)

<ipython-input-18-8bd369dd3daf> in <module>()
      1 import onnxruntime as rt
      2 
----> 3 session = rt.InferenceSession("output/model.onnx")
      4 input_name = sess.get_inputs()[0].name
      5 print(input_name)

1 frames

/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    356         session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    357         if self._model_path:
--> 358             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    359         else:
    360             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from output/model.onnx failed:Fatal error: AliasWithName is not a registered function/op
```

I Thank you in advance!

**Comment by jcwchen** [comment]
Hi @mountassir-el,
As the error mentioned, AliasWithName is not an official ONNX op so there is no registered schema for it. You can check all official ONNX ops here: https://github.com/onnx/onnx/blob/master/docs/Operators.md Thus, this should be a question for the converter. Please raise this question in detectron2 to ask the exporter only to produce official ONNX ops . Close here now. Please reopen it if you still have other ONNX questions. Thanks!

**Comment by SnowRipple** [comment]
@mountassir-el any luck with AliasWithName op?

**Comment by mountassir-el** [comment]
@SnowRipple Unfortunately no sir!

**Comment by DelanoBannister** [comment]
I really wish this was solved
