### ISSUE TITLE
Debug version of onnx on Windows does not work correctly

### ISSUE THREAD

**Issue by sstamenova** [onnx/onnx#3796]
### Describe the bug
The debug version of onnx on Windows does not work correctly (with onnxruntime)

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows
- ONNX version (*e.g. 1.7*):  1.9, 1.10 (possibly others, these are confirmed)
- Python version: 3.9
- GCC/Compiler version (if compiling from source): MSVC 19.29.30136.0
- CMake version: 3.21.3
- Protobuf version: 3.16.0
- Visual Studio version (if applicable): Visual Studio 16 2019

### Reproduction instructions
1. Build debug version of onnx on Windows:
 `python3 setup.py bdist_wheel`
with the following environment variables:
`CMAKE_ARGS: "-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF -DProtobuf_USE_STATIC_LIBS=ON -DONNX_USE_MSVC_STATIC_RUNTIME=OFF"`
`DEBUG: 1`
2. Install the wheel locally
3. Install onnxruntime
4. `import onnxruntime` from a python script
![image](https://user-images.githubusercontent.com/29738015/138532322-68625c75-79d6-4db7-9760-1959746c4cf2.png)

### Expected behavior
Successfully import onnxruntime.

### Notes
This works fine when we build release or install onnx directly from PyPi. It looks like a memory corruption that is only detected in debug builds on Windows because they do extra memory checks.

**Comment by liqunfu** [comment]
there is likely a conflict between onnxruntime and onnx in terms of protobuf. 

I used only the option:
echo %CMAKE_ARGS%
-DONNX_USE_LITE_PROTO=ON 
to build the onnx package and was able to import onnxruntime without an issue.

I build my local protobuf with these options:
-Dprotobuf_MSVC_STATIC_RUNTIME=OFF -Dprotobuf_BUILD_SHARED_LIBS=OFF -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_EXAMPLES=OFF
