### ISSUE TITLE
Conv_0 OpType: Conv is not output of any previous nodes.

### ISSUE THREAD

**Issue by Aebestach** [onnx/onnx#3800]
# Ask a Question
First run the following code, get 'AlexNet.onnx'.
```
import torch
import torchvision
dummy_input = torch.randn(10, 3, 224, 224, device="cuda")
model = torchvision.models.alexnet(pretrained=True).cuda()

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True)
```
The error was reported when running the following code.(Error as shown by the topic.)
`Conv_0 OpType: Conv is not output of any previous nodes.`
```
import onnx

onnx_model = onnx.load("alexnet.onnx")
graph = onnx_model.graph
node  = graph.node

for input_node in onnx_model.graph.input:
    if 'input.1' == input_node.name:
        print("change input data name")
        input_node.name = '1207'

onnx.checker.check_model(onnx_model)
onnx.save(onnx_model, 'out.onnx')
```
### Question
I want to modify the first CONV node name, but there is no way to modify it.
want to know how to modify it.
![图片](https://user-images.githubusercontent.com/64588584/138552462-5b85e65d-fa91-4ad0-9935-3eada53b6444.png)
![图片](https://user-images.githubusercontent.com/64588584/138552499-10759ed6-8f49-4a94-a589-c2d05ebdccb1.png)

### Operating environment
Python 3.8
PyTorch 1.9

### Seeking assistance
How to make ‘input.1‘ into digital string form for PyTorch turn overnx model.
This `torch.onnx.export` code is kept in ONNX.

**Comment by Aebestach** [comment]
@wangyems 
I tried such a modification, but I would like to change the name to a pure digital form, but he reported a mistake.
![图片](https://user-images.githubusercontent.com/64588584/139526622-3c1b2960-d3ad-4405-87d1-219816be1578.png)
![图片](https://user-images.githubusercontent.com/64588584/139526628-7679bc0f-81b3-42e4-a944-74d2d6441a72.png)

**Comment by askhade** [comment]
PR https://github.com/onnx/onnx/pull/3820 adds a way to modify node names, please take a look
