### ISSUE TITLE
 Exporting the operator grid_sampler to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator

### ISSUE THREAD

**Issue by lihuaqiang0101** [onnx/onnx#3811]
# Bug Report

### Is the issue related to model conversion?
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): 
- ONNX version (*e.g. 1.7*):  
- Python version:
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by EJShim** [comment]
@askhade  Is there a way that I can test exporting torch.nn.functional.grid_sample function to onnx now by build onnx from source? Or do I have to wait for pytorch to be updated to support onnx opset version 16?

**Comment by jcwchen** [comment]
Typically the converter will start to support new ONNX ops after they are officially released by ONNX. So yes I think you might need to wait for the converter support: https://github.com/pytorch/pytorch/issues/27212
