### ISSUE TITLE
how can i get the input names?

### ISSUE THREAD

**Issue by MonTer998** [onnx/onnx#3822]
hi everyone got a model from pytorch and first time dealing with onnx, I can get most of the details that i need there is still one small issue that i didnt find a solution to.
from the image below i can get the values of the input (157, 3.weight...ect) but i want it to like a dictionary where i can get the name X , W, B and the values
![github](https://user-images.githubusercontent.com/93642193/140024274-1ab91e07-218d-404e-ac75-135f2138d68e.png)

**Comment by jcwchen** [comment]
Hi @MonTer998,
You can obtain them by `onnx.defs.get_schema("Conv").inputs`. For example:
```
import onnx
for input in onnx.defs.get_schema("Conv").inputs:
  print(input.name)
```

**Comment by gramalingam** [comment]
Just to clarify: the names X, W, B here denote the formal-parameter names specified in the operator schema (which can be obtained as Jacky describes above). 157, 3.weight, and 3.bias are also names, but they are the names of the actual parameters specified in this specific node/call. I am not sure what it is that you are looking for. Also, are you looking for programmatic access (in python or c++)?

**Comment by MonTer998** [comment]
@gramalingam  yes i just realized that the (X , W , B ) are denoted by the onnx format right after asking this question, @jcwchen got a quick answer so i guess it is the right one  thank you guys.

**Comment by syswyl** [comment]
> Hi @MonTer998, You can obtain them by `onnx.defs.get_schema("Conv").inputs`. For example:
> 
> ```
> import onnx
> for input in onnx.defs.get_schema("Conv").inputs:
>   print(input.name)
> ```

Hello @jcwchen , I’m not sure if this is an onnx export problem or a model construction problem. I want to display the specific layer name of the current operation in the inputs  **W**,  as shown in the figure. 
But I got different results when exporting the same model.
Using  **onnx.export**  and **onnx._export** respectively.
<img width="432" alt="截屏2021-12-24 下午3 52 51" src="https://user-images.githubusercontent.com/29301581/147331488-4d983dbe-31e7-4212-a76e-0ef35f89d850.png">

<img width="483" alt="截屏2021-12-24 下午3 53 03" src="https://user-images.githubusercontent.com/29301581/147331512-0e715b21-c1a7-4bf9-b174-4d905ab5393c.png">

When I switch to another model, using onnx.export can not get the exact name of the input **W** of the current conv layer, but only a number can be displayed. But it can be normal at the bn layer
This troubles me very much. Can you answer the possible reasons for this difference?
<img width="574" alt="截屏2021-12-24 下午3 59 14" src="https://user-images.githubusercontent.com/29301581/147332078-9c643ec8-92a6-48cd-a9f5-5ccd808d2116.png">

<img width="651" alt="截屏2021-12-24 下午3 59 29" src="https://user-images.githubusercontent.com/29301581/147332100-2ce538ed-ba96-4ed0-ad4a-9416bdf64080.png">

**Comment by jcwchen** [comment]
Hi @syswyl,
It seems like a question for the converter. With different conversion, they might apply different methods to create the name for layer names. It will be more readable if the layer name can be a meaningful text as you mentioned. I would suggest you raise this question regarding to the difference on the converter repo. Thanks!
