### ISSUE TITLE
onnx model import to tensorflow is superficial at best.

### ISSUE THREAD

**Issue by gggh000** [onnx/onnx#3823]
https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb
Inspecting the code, it does not really import to tensorflow, not even sure why it is called importing to tf. 
the imported so cald tf_rep appears to be onnx's own stuff.
does not fit into keras model
https://www.tensorflow.org/api_docs/python/tf/keras/Model

Traceback (most recent call last):
        print("Loading onnx model...")
        model_import = onnx.load('output/p297.onnx')
        model = prepare(model_import)
...
  File "<dense>.py", line 68, in <module>
    model.evaluate(X_test, y_test)
AttributeError: 'TensorflowRep' object has no attribute 'evaluate'

I wondered if there is a dedicatd keras converstion but pitifully https://github.com/onnx/tutorials has conversion from onnx to keras but scoring section has none.

**Comment by garymm** [comment]
If the issue is with the `onnx_tf` package, please open an issue in onnx/onnx-tensorflow.
If the issue is just with the tutorial, please open an issue in onnx/tutorials.
