### ISSUE TITLE
Which function should be used on the C++ side to load the onnx model file.

### ISSUE THREAD

**Issue by huang229** [onnx/onnx#3824]
# Ask a Question
### Question
{
language：c++
platform：windows10
vs:             2019
cuda:         10.1
0nnx :        1.10.2
When C + + calls the check_model（） function, the following problems are encountered: ir_version=6， opset_imports=empty().

Throw the following exception information：
fail_check("model with IR version >= 3 must specify opset_import for ONNX");
}
{
language：python3.6.7
platform：windows10
pycharm:          ....
cuda:         10.1
0nnx :        1.10.2
On the python side, it outputs: ir_version=6， opset_imports=11.
}

Is it the wrong use of the model parsing function on the C + + side, and which function should be used on the C + + side to load the onnx model file.

### Further information
int main(/*int argc, char **argv*/) {

  ONNX_NAMESPACE::ModelProto model;
  
  std::string model_onnx = "F:/onnxoptimizer/examples/tooth_seg.onnx";
  std::string output_model = "F:/onnxoptimizer/examples/tooth_seg_opt.onnx";

  std::ifstream ifs(model_onnx);
  bool success = model.ParsePartialFromIstream(&ifs);
  if (!success) {
    std::cout << "load failed" << std::endl;
    return -1;
  }

  onnx::checker::check_model(model);
  const auto new_model = onnx::optimization::Optimize(
      model, onnx::optimization::GetFuseAndEliminationPass());
  onnx::checker::check_model(new_model);
  std::ofstream ofs(output_model);
  success = new_model.SerializePartialToOstream(&ofs);
  if (!success) {
    std::cout << "save failed" << std::endl;
    return -1;
  }
  return 0;
}
############
checher.cc  There are the following codes：
void check_model(const ModelProto& model, CheckerContext& ctx) {
...........................
.............................
  if (model.ir_version() >= 3) {
    std::cout << " 4" << std::endl;
    if (opset_imports.empty()) {
      std::cout << " 5" << std::endl;
      fail_check("model with IR version >= 3 must specify opset_import for ONNX");
    }
....................................
.....................................
############
### Notes
Any additional information, code snippets.

**Comment by askhade** [comment]
Is the model valid? Based on the log info you provided looks like the model does not import any opsets... this is not allowed. "model with IR version >= 3 must specify opset_import for ONNX"

If you are simply looking for a way to load an onnx model you can check the code here: https://github.com/onnx/onnx/blob/1cc5e12f95c168146a912e3a6837d51f5d0f693b/onnx/common/file_utils.h#L15
