### ISSUE TITLE
After ugrade my opt version from 10 to 13, my model is slower than before? If there some specially conf in opt13

### ISSUE THREAD

**Issue by GuoGuiRong** [onnx/onnx#3829]
# Ask a Question

### Question
Explain your question here.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @GuoGuiRong,
Which backend did you use for running ONNX model? Please raise performance issue in the backend repo to get the best the help from the Runtime team. For instance, if you used ONNXRuntime, please raise a question here: https://github.com/microsoft/onnxruntime/issues. Close here now and feel free to reopen it if you still have other ONNX questions. Thanks
