### ISSUE TITLE
WinRT information: Failed to load model with error: Unknown model file format version - How do I change the model format version?

### ISSUE THREAD

**Issue by Westycoot** [onnx/onnx#3836]
# Ask a Question

### Question
I have converted a YoloV5 model to ONNX with the Opset 9. This model works great running a C# program using Microsoft.ML. However, I am now trying to get this model to work with UWP which requires Windows.AI.MachineLearning and I am running into this error:

WinRT information: Failed to load model with error: Unknown model file format version.

I see that my file format version is 7 when I check the model in Netron, whereas example models are format version 4 or 5. How can I change this file format version? I am using an export.py script from Ultralytics - https://github.com/ultralytics/yolov5/issues/251 which perform the conversion from YoloV5 to ONNX. As mentioned above, my model has worked for the Microsoft.ML package, but is not working for Windows.AI.MachineLearning.

I can't find any documentation about the file format version, so I am wondering how I can produce a ONNX model with a different format version as this seems to be the issue.

Many thanks.

**Comment by Westycoot** [comment]
![image](https://user-images.githubusercontent.com/14790704/141142853-6cbfe30a-94d6-4c57-9d7e-9ec383fbfff4.png)
Here is he model format version as seen by Netron

**Comment by jcwchen** [comment]
Hi @Westycoot,
In fact, a opset 9 model should have ir_version 4. You can check the corresponding version map here: https://github.com/onnx/onnx/blob/master/docs/Versioning.md. A quick hacky way would be simply trying: `your_model.ir_version=4`, but it might not work if the model indeed uses some new IR things after ir_version 5... So I would say it's better to check with the converter team and let them take care of old IR format and produce the right ir_version with corresponding opset_version during the conversion. Thanks!

**Comment by Westycoot** [comment]
Hi @jcwchen , 
Here is some more output of what my model looks like from the conversion process:
![image](https://user-images.githubusercontent.com/14790704/141157471-7d922a1e-0a1b-415c-89ae-a1daadc52d18.png)

I will take a look at trying the hack, if that doesnt work I will post a similar thread in the Ultralytics Github. Thanks!

**Comment by garymm** [comment]
This should be fixed in `torch.onnx.export` in PyTorch 1.11 by https://github.com/pytorch/pytorch/pull/67128.

@jcwchen I think you can close this.

**Comment by jcwchen** [comment]
> This should be fixed in `torch.onnx.export` in PyTorch 1.11 by [pytorch/pytorch#67128](https://github.com/pytorch/pytorch/pull/67128).
> 
> @jcwchen I think you can close this.

Great! Thanks for the info. Close here now. @Westycoot feel free to reopen it if you still have other ONNX questions.

**Comment by Westycoot** [comment]
It looks like PyTorch 1.11 doesn't have a release yet, how can I get hold of this new export? Many thanks

**Comment by Westycoot** [comment]
I have managed to get PyTorch 1.11 running, but when I try and export I get this error (I understand this is pre-release):

![image](https://user-images.githubusercontent.com/14790704/141330645-fca43001-f37f-45c2-915b-9ba0ea780502.png)

**Comment by garymm** [comment]
@Westycoot before the 1.11 release you can use the latest PyTorch nightly version.

I guess the model code may not be compatible with the latest version of PyTorch. This PR seems related: https://github.com/pytorch/pytorch/pull/66419

You may have to change the model to be compatible with the latest PyTorch.

But if you've already successfully exported using PyTorch 1.10, I think just editing the ir_version in the exported ONNX file is probably the easiest thing to do.

Something like:
```python
import onnx

model = onnx.load("path/to/model.onnx")
model.ir_version = 4
onnx.save_model(model, "path/to/model.irv4.onnx")
```
