### ISSUE TITLE
Slice opset ver 9 to 11， not support

### ISSUE THREAD

**Issue by tianylijun** [onnx/onnx#3837]
Op：Slice
opset version form 9 to 11, convert_version not support

**Comment by jcwchen** [comment]
Hi @tianylijun,
According to the adapter [file](https://github.com/onnx/onnx/blob/master/onnx/version_converter/convert.h) from version_converter, Slice 9 to 10 and Slice 10 to 11 should be supported. Which ONNX version do you use? Could you please provide the model for me to repro this error? Thank you.

**Comment by jcwchen** [comment]
I think the latest ONNX should support this conversion. Please let me know if it is still an issue to you. Close now. Thanks!
