### ISSUE TITLE
PyTorch 1.11 and exporting - 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by Westycoot** [onnx/onnx#3838]
# Bug Report

### Describe the bug
Original bug/question [https://github.com/onnx/onnx/issues/3836](here)

I have now built my own PyTorch from latest source, to obtain version 1.11.

When running the export on my YoloV5 model I get the following error:

![image](https://user-images.githubusercontent.com/14790704/141331996-e4b76087-c2e3-4aa9-a576-f9f5ab5a49c0.png)

I did not get this error when exporting from PyTorch 1.10, but I did have the issue of the Opset not being inline with the IR version, which is fixed in1.11 (hence me building from source).

**Comment by askhade** [comment]
@Westycoot : This seems like a converter issue. Please open this issue in the pytorch repo. Also check issue #3836 as it was updated a few hours back.

**Comment by glenn-jocher** [comment]
@Westy-Dev @askhade good news 😃! Your original issue may now be fixed ✅ in YOLOv5 🚀 PR https://github.com/ultralytics/yolov5/pull/6932. This PR implements PyTorch 1.11.0 compatibility updates and resolves `AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'` errors.

To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!
