### ISSUE TITLE
how to change the name of outputs?

### ISSUE THREAD

**Issue by lucky-xu-1994** [onnx/onnx#3844]
# Ask a Question

### Question
how to change the name of outputs?

### Further information
1、the current output of ONNX is as follows, which name is scale_0.tmp_1。
![1637131174(1)](https://user-images.githubusercontent.com/57120921/142147587-f970030e-49a8-47f2-b099-744e0a974e54.png)

2、I want to change the output's name ,like to output0. I used the following commands to do it .
![1637131382(1)](https://user-images.githubusercontent.com/57120921/142148046-14346dec-1fb0-4700-8ab5-0fef207b98cd.png)

3、and got nothing wrong, but when I test the ONNX，it errored that there is no output1 in the graph. open the ONNX with netron, the output is as follows:
![1637131595(1)](https://user-images.githubusercontent.com/57120921/142148406-fb90dd5d-4913-4d33-ba03-248d4b062075.png)
 
is there anyone can help me out? thanks!

**Comment by jcwchen** [comment]
Hi @lucky-xu-1994,
Please also update the output name of other nodes which have `scale_0.tmp_1` as output. In that case those nodes can correctly find the updated output node.

**Comment by askhade** [comment]
PR https://github.com/onnx/onnx/pull/3820 adds a way to rename inputs, outputs. Please take a look

**Comment by lucky-xu-1994** [comment]
thanks! @jcwchen @askhade , I have done!  codes as following:

![1637203595(1)](https://user-images.githubusercontent.com/57120921/142342454-49453062-522a-4b1f-9330-3537ab81bc9b.png)
