### ISSUE TITLE
C++ utility for creating ONNX model

### ISSUE THREAD

**Issue by sj120698** [onnx/onnx#3845]
# Ask a Question

### Question
I am writing a C++ application that reads my own node/tensor abstraction and reconstructs it into an ONNX model. I notice that the ONNX Python library has onnx.helper tool for building ONNX model using make_tensor_value_info, make_node, make_graph and make_model functions. I wonder if the same utility (and other onnx.helper functions) is there for C++ and how may I incorporate it into my application (build with ONNX C++ library?).

**Comment by AlexandreEichenberger** [comment]
If you look at the roadmap for ONNX, there are other folks that are interested in having tools to generate models from C/C++/Java. So there is definitely interest here. Hopefully some of these folks would join effort to make one solid offering.

One suggestion would be to do that part in C, as it can then be used in C, C++ as well as to Java using a JNI interface. Below is the roadmap summary. Looks for suggestions by Popock/Oracle. All the presentations are on the roadmap slack channel from ONNX.

[roadmap from the ONNX workshop slides.pdf](https://github.com/onnx/onnx/files/7555997/roadmap.from.the.ONNX.workshop.slides.pdf)
.

**Comment by jcwchen** [comment]
Hi @sj120698,
As @AlexandreEichenberger mentioned, currently there is no C++ utilities for creating ONNX model like Python APIs and it is included in ONNX roadmap. For now, perhaps you can check ONNX parser ([examples](https://github.com/onnx/onnx/blob/master/onnx/test/cpp/parser_test.cc)). It can support making ONNX model, graph and node by a string, which might be useful for your use cases.

**Comment by Craigacp** [comment]
You should be able to write the protobufs directly from C++, by compiling the [proto](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto3). That's how we currently build ONNX models in Java, and how ML.Net does it in C#. Both [Tribuo](https://github.com/oracle/tribuo/tree/main/Core/src/main/java/org/tribuo/onnx) and [ML.Net](https://github.com/dotnet/machinelearning/tree/main/src/Microsoft.ML.OnnxConverter) have their own wrapper classes around the protobuf generation to make it more user friendly, and my proposal for the roadmap which @AlexandreEichenberger mentioned was to write those classes once in C or C++, then add a C API around it which C#, Java and Python could bind to. I'm still working on getting the Tribuo release out the door which has our initial ONNX export support in, but once that's done I plan to start talking to others in the community about this.

**Comment by sj120698** [comment]
> Hi @sj120698, As @AlexandreEichenberger mentioned, currently there is no C++ utilities for creating ONNX model like Python APIs and it is included in ONNX roadmap. For now, perhaps you can check ONNX parser ([examples](https://github.com/onnx/onnx/blob/master/onnx/test/cpp/parser_test.cc)). It supports making ONNX model, graph and node by a string, which might be useful for your use cases.

**Comment by sj120698** [comment]
> As @AlexandreEichenberger mentioned, currently there is no C++ utilities for creating ONNX model like Python APIs and it is included in ONNX roadmap. For now, perhaps you can check ONNX parser ([examples](https://github.com/onnx/onnx/blob/master/onnx/test/cpp/parser_test.cc)). It supports making ONNX model, graph and node by a string, which might be useful for your use cases.

Is there any expected timeline by which this C++ utility gets included in ONNX @AlexandreEichenberger,  @jcwchen?  

Also, using the ONNX parser approach , after creating modelproto using parser, how can it then be exported and saved as ONNX model? 
And in case I need to create some large size fixed tensorproto, then do I need to enter all of it's value in the string or is there any other alternative approach to this?

**Comment by jcwchen** [comment]
> Also, using the ONNX parser approach , after creating modelproto using parser, how can it then be exported and saved as ONNX model?

Here is the example for how to save a ModelProto via C++: https://github.com/onnx/onnx/blob/fa6f8cfdce3d86346e8a7494f3062b98416c85fb/onnx/shape_inference/implementation.cc#L544

> And in case I need to create some large size fixed tensorproto, then do I need to enter all of it's value in the string or is there any other alternative approach to this?

Sorry I am not aware whether there is a better approach to achieve it. Currently such support is quite limited.

**Comment by thiagocrepaldi** [comment]
@gramalingam do you know if this is something ONNX is still looking at? Any recommended 3rd party lib?
