### ISSUE TITLE
Is it possible to use only the decoding part of a pytorch VAE model converted to onnx (and ONNX to TF)?

### ISSUE THREAD

**Issue by ShiLevy** [onnx/onnx#3846]
# Is it possible to use only the decoding part of a pytorch VAE model converted to onnx?

I am using a VAE model from https://github.com/jlalvis/VAE_SGD/blob/master/VAE/autoencoder_in.py
My final goal is to convert the model to TensorFlow and use only the decoding part of the model. Is there a way to use only the decoding part when doing Pytorch-ONNX and ONNX-TF conversion?

**Comment by jcwchen** [comment]
Hi @ShiLevy,
You can manually modify the graph in PyTorch level, ONNX level or TensorFlow level, to only keep the decoding part. IIUC, I don't think the converters can partially export a model.

**Comment by ShiLevy** [comment]
Hi @jcwchen ! Thanks for the reply.
What do you mean by modifying the graph manually? How can I do that in the Pytorch level? (sorry if it's off topic for this forum)

**Comment by jcwchen** [comment]
From my imagination, you should probably be able to create a submodel with corresponding inputs/outputs in PyTorch which only consists the decoding part, by using the decoding code from PyTorch you have. Sorry that I am not a PyTorch expert so I cannot give you concrete code to achieve that.

**Comment by askhade** [comment]
I don't know whether pytorch exporter or onnx-tf converter can support partial conversion... I suggest asking these questions in the respective github repos. However like @jcwchen suggested you can try extracting the decoding specific subgraph from onnx model and then only feed that subgraph to onnx-tf converter. It may work but I cant guarantee. If you were to explore this path we do have a utility to extract sub graphs from a model. You can check this: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#extracting-sub-model-with-inputs-outputs-tensor-names

**Comment by ShiLevy** [comment]
Thanks @askhade that is also a good solution for me!
I tried it and it works well for the encoder, but when I try to extract the decoder it does not recognize the input name to the decoder. It only excepts "input" and than it expects tensor rank 4, which is the rank of the input to the encoder (for the decoder the input is rank 2). What should be the input name to the decoder for the following architecture:
https://github.com/jlalvis/VAE_SGD/blob/master/VAE/autoencoder_in.py
Thanks for the help!!
