### ISSUE TITLE
parsing onnx model to pytorch>

### ISSUE THREAD

**Issue by MonTer998** [onnx/onnx#3847]
# is there a way I can get every onnx model layer and details, and what correspond to them in pytorch?

hi everyone, I am new to machine learning never the less onnx file format, a project was assigned to me for parsing any onnx model to a pytorch model, for start I was wondering from where can I know what correspond to each layer in onnx from pytorch.
something like a dictionary or sort of thing .

### Further information
for example we have the layer conv layer in onnx but we have several conv layers from pytorch  like conv2d and more, so is there a way I can get what correspond to each onnx model in pytorch?

**Comment by jcwchen** [comment]
Hi @MonTer998,
Unfortunately, IIUC, there is no magic dictionary for it... You will need to understand both PyTorch and ONNX knowledge to achieve the conversion. A possible approach is referring how existing converters perform the conversion. Take PyTorch-ONNX exporter as an example. The [code](https://github.com/pytorch/pytorch/blob/980778713588be8a583557c4693634c3782b00c4/torch/onnx/symbolic_opset9.py#L1338) here might be helpful.

**Comment by MonTer998** [comment]
Hi @jcwchen thank you for your help, if i dont have the time to study pytorch and onnx ( the project presentation is within days)  is there any short cut you know, thank you again for the code i will start with it right away

**Comment by jcwchen** [comment]
According to the issue [here](https://github.com/pytorch/pytorch/issues/21683), actually there are a couple of existing tools for converting ONNX to PyTorch. Perhaps you could also refer/utilize them. You can find those repos in the issue. Good luck to your project!
