### ISSUE TITLE
how to change the resize layer`s input type

### ISSUE THREAD

**Issue by aso538** [onnx/onnx#3856]
# Ask a Question

### Question
Hello, I'd like to ask you how to modify the type of the output of the cast layer or the type of the input of the resize layer in the onnx model. When I quantified the onnx model, the output of the cast layer and the input of the resize layer were not quantified successfully and need to be modified manually

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @aso538,
To change the "to" type in a Cast node, you can try something like:
```
from onnx import TensorProto
cast_node = your_model.graph.node[x]
cast_node.attribute[0].i = TensorProto.INT8  # it can be changed to any type you want
```
Please note that probably you will need to change the type in the following nodes. How did you get this ONNX model? Something might be wrong during the conversion.
