### ISSUE TITLE
请问如何获取onnx模型的每层操作名称和类型

### ISSUE THREAD

**Issue by EdwardVincentMa** [onnx/onnx#3862]
你好，我是pytorch模型输出为onnx，但是模型转完后，每层名字完全变了，我看了一下是pytorch 转 onnx 里面的torch._C._create_graph_by_tracing() 函数生成的 graph，里面名字已经变了。但是我需要拿到这些变化后的名字和类型。

**Comment by jcwchen** [comment]
Hi @EdwardVincentMa,
To obtain layer name and type, you can try https://netron.app/ to visually view the converted ONNX, or a code like:
```
import onnx
onnx_model = onnx.load("your/onnx/model.onnx")
for node in onnx_model.graph.node:
    print(node)
```

--

您可以嘗試 (https://netron.app/) 圖像化ONNX模型或者上方的代碼來查看你模型內每層的細節。

**Comment by jcwchen** [comment]
I assume this question has been answered. Please reopen it if you still have other ONNX questions. Thanks!
--
我想這個問題已經被解決, 如果還有問題的話歡迎再打開這個, 謝謝!
