### ISSUE TITLE
Operator roll to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by shiyongming** [onnx/onnx#3863]
# New Operator

### Describe the operator
Why is this operator necessary? What does it accomplish?
torch.roll is used for swin transformer structures. Its function can be found from [here](https://pytorch.org/docs/stable/generated/torch.roll.html?highlight=roll)

![image](https://user-images.githubusercontent.com/42972650/143406086-f9d992da-12bd-454c-840a-8153e6370c33.png)

### Can this operator be constructed using existing onnx operators?
Not sure.

### Is this operator used by any model currently? Which one?
Swin transformer and models using swin transformer as the backbone.

### Notes
[swin transformer](https://github.com/microsoft/Swin-Transformer)

Error log I got:
![image](https://user-images.githubusercontent.com/42972650/143406977-1d6ee749-b037-48d9-8361-a54ac7b201c9.png)

**Comment by jcwchen** [comment]
Hi @shiyongming,
According to the comment [here](https://github.com/pytorch/pytorch/issues/56355#issuecomment-938109211) from PyTorch repo, torch.roll should be supported by the converter recently. Could you please try to convert it with the latest converter (PyTorch)? Thanks.

**Comment by askhade** [comment]
Closing this issue. If you run into any issue please open an issue in pytorch erpo.
