### ISSUE TITLE
About ReverseSequence OP spec description

### ISSUE THREAD

**Issue by RunnerZhong** [onnx/onnx#3872]
# Ask a Question

### Question
Description from doc is here: https://github.com/onnx/onnx/blob/master/docs/Operators.md#ReverseSequence

2 examples :
Example 1: input = [[0.0, 4.0, 8.0, 12.0], [1.0, 5.0, 9.0, 13.0], [2.0, 6.0, 10.0, 14.0], [3.0, 7.0, 11.0, 15.0]] sequence_lens = [4, 3, 2, 1] time_axis = 0 batch_axis = 1

output = [[3.0, 6.0, 9.0,  12.0],
          [2.0, 5.0, 8.0,  13.0],
          [1.0, 4.0, 10.0, 14.0],
          [0.0, 7.0, 11.0, 15.0]]
**Example 2: input = [[0.0, 1.0, 2.0, 3.0 ], [4.0, 5.0, 6.0, 7.0 ], [8.0, 9.0, 10.0, 11.0], [12.0, 13.0, 14.0, 15.0]] sequence_lens = [1, 2, 3, 4] time_axis = 1 batch_axis = 0**

output = [[0.0,  1.0,  2.0,  3.0 ],
          [5.0,  4.0,  6.0,  7.0 ],
          [10.0, 9.0,  8.0,  11.0],
          [15.0, 14.0, 13.0, 12.0]]

**From my understanding, seq_length should have shape [batch_size], in Example 2, input_shape = [2, 4], seq_len shape = [4], time_axis = 1, batch_axis = 0.

the seq_len_shape expected is  input_shape[batch_axis] = [2], right ?  But in the example is [4].**

### Notes
Any additional information, code snippets.

**Comment by askhade** [comment]
Yes your understanding is correct, sequence_lens should have shape [batch_size]. Why do you say input_shape is [2, 4] ? it is [4, 4] and sequence_lens shape is therefore [4].

**Comment by RunnerZhong** [comment]
> Yes your understanding is correct, sequence_lens should have shape [batch_size]. Why do you say input_shape is [2, 4] ? it is [4, 4] and sequence_lens shape is therefore [4].

Oh, my mistake, confused by another one, sorry for that
