### ISSUE TITLE
extract_model, why model is not valid?

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3873]
![image](https://user-images.githubusercontent.com/43114292/144178222-177e2e9c-b354-4a17-9f47-6e385587f91b.png)

hello!

i have this model and i want to cut this into two parts via `onnx.utils.extract_model`

my second model have this inputs and outputs:

`inputs_names = ['627', '668', '633', '656', '639', '645', '667']`
`output_names = ['boxes', 'scores']`

to be honest, model looks not bad (`627`th input is ReLU from input model)

![image](https://user-images.githubusercontent.com/43114292/144178545-464860da-1539-4e2c-b3fb-62e1d164cbf0.png)

but i got error at last stage, when `onnx` checking my model

so what do you think is this? bug? or i'm doing smth wrong? thanks

**Comment by askhade** [comment]
@germanjke what is the error message coming from checker? Can you share your model?

**Comment by germanjke** [comment]
![image](https://user-images.githubusercontent.com/43114292/144181811-cd5eca14-6b45-47a5-b804-823216e611ee.png)

here is [link](https://www.dropbox.com/s/af38abcswcnz6vg/ssd_misha_second_second.onnx?dl=0) to model

**Comment by askhade** [comment]
Thanks for sharing the model. What is the Validation error?

**Comment by germanjke** [comment]
as you can see at line 94 in `onnx` you have some `checker` function which checks valid of the model (is it valid or not) and my model can't pass this test.

**Comment by askhade** [comment]
I got that. I was just wondering whether you have any detailed error message other than just ValidationError. If not I will take a look at the model tomorrow morning and update this thread.

**Comment by germanjke** [comment]
it's not detailed error message right. thanks, see you

**Comment by askhade** [comment]
This is the detailed error message : onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '621' of node:
name: Conv_208 OpType: Conv
 is not output of any previous nodes.

As the error message suggests Conv nodes input 621 is not output of any node in short it is missing. 

![image](https://user-images.githubusercontent.com/6475296/144187256-7cf1f6a3-e60f-442c-844e-853b17b7dcf9.png)

Fix: update input_names to include 621
inputs_names = ['621', '627', '668', '633', '656', '639', '645', '667']

**Comment by germanjke** [comment]
thanks for help! is it true.
