### ISSUE TITLE
Match Op names with test directory names

### ISSUE THREAD

**Issue by philtomson** [onnx/onnx#3881]
# Bug Report

### Describe the bug
I've noticed a mismatch between some operation names and the name used in directory paths for unit tests.

For example:
For the op BatchNormalization the unit tests are directories called:
onnx/backend/test/data/node/test_batchnorm_*

Similar for Trilu where the tests are a in directories called:
onnx/backend/test/data/node/test_tril_*

This makes it difficult for 3rd party users of ONNX to create tooling around tests. More consistent naming would probably also make it easier for onnx's own testing and doc generating scripts.  

### System information
- Any

**Comment by askhade** [comment]
The test names are specified in the <op unit test>.py example: https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/trilu.py#L113

You can create a standard naming scheme for these tests but then you will need to go and change every test in the node test cases. Another option is to fix the existing name mismatches and then add a test to make sure the names use follow test_<op_name>_* format. 

Are you willing to contribute?
