### ISSUE TITLE
Make C++ and Python checker API consistent

### ISSUE THREAD

**Issue by garymm** [onnx/onnx#3884]
Python checker API supports `full_check` arg:
https://github.com/onnx/onnx/blob/fa6f8cfdce3d86346e8a7494f3062b98416c85fb/onnx/checker.py#L94

C++ does not.
It'd be nice for them to be consistent.

**Comment by sechkova** [comment]
Hello, do you mind if I work on this issue?

If I understand correctly, the idea is to add the `full_check` argument (which enables shape inference) to the `check_model` functions of the C++ API (checker.h/checker.cc).

**Comment by garymm** [comment]
Yes that's the request. Feel free to work on it. Thanks!
