### ISSUE TITLE
pad_sequence operator

### ISSUE THREAD

**Issue by vivkvv** [onnx/onnx#3887]
I worked with project https://github.com/stanfordnlp/stanza and tried to convert the pre-trained stanza PyTorch model into onnx format (see https://github.com/stanfordnlp/stanza/issues/893 as well). But I've got an error 
```
Exporting the operator pad_sequence to ONNX opset version 11(12, 13, 14) is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
Is it possible to add this functionality to ONNX?

**Comment by onuryuruten** [comment]
Hey there, we're running into a similar issue in our project: `RuntimeError: Exporting the operator pad_sequence to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub`

Is there a development in this issue? Is there a corresponding issue in PyTorch repository?

**Comment by vivkvv** [comment]
All the links are here https://stackoverflow.com/questions/70205743/how-to-export-stanza-to-onnx-format/70258792#70258792

**Comment by DJMeng** [comment]
Is there a development in this issue? Exporting the operator pad_sequence to ONNX opset version 11(12, 13, 14) is not supported.
