### ISSUE TITLE
extract model on undirected graph 

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3890]
`model = onnx.load('union_model5.onnx')`
`inputs = [x.name for x in model.graph.input]`
`outputs = [x.name for x in model.graph.output]`
`onnx.utils.extract_model('union_model5.onnx', 'union_model5_no_const.onnx', inputs, outputs)`

I can't  use `extract_model` even with original inputs and outputs, so I guess that's because undirected graph?

my model [here](https://www.dropbox.com/s/mkgtgl9jgz6dc6l/union_model5.onnx?dl=0)

![image](https://user-images.githubusercontent.com/43114292/145788527-a8dd73c5-eb6b-4603-8508-1f452303f395.png)

**Comment by jcwchen** [comment]
Hi @germanjke,
The latest ONNX does support to disable onnx.checker for extract_model now: https://github.com/onnx/onnx/pull/3689. However, it is not included in the latest 1.10.2. As a workaround, you can either use [onnx-weekly](https://test.pypi.org/project/onnx-weekly/) or manually remove L161 [here](https://github.com/onnx/onnx/blob/0fa402af4d59df09cf1606e70093f9e4a73eeb58/onnx/utils.py#L161) in your installed ONNX.
