### ISSUE TITLE
how to build an int8 model?

### ISSUE THREAD

**Issue by Chenhait** [onnx/onnx#3895]
hi, I convert a onnx model, and use triton server to infer.
however, the data and the model not in the same computer.
the input and output of ONNX model are fp32, it is too big to transmit.
so, I want to change the input and output to  int8.
is it possible?
thank you very much if any advance!!

**Comment by ytaous** [comment]
dup of https://github.com/microsoft/onnxruntime/issues/10037

**Comment by askhade** [comment]
This question has been answered in onnxruntime repo - microsoft/onnxruntime#10037
