### ISSUE TITLE
onnx extract model mask rcnn error

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3898]
Hello, i'm using `extract_model` and got this error

![image](https://user-images.githubusercontent.com/43114292/146305980-c60135b4-604d-4166-9d40-36ec118b8fc3.png)

```
input_path = os.path.join(path, 'mask_rcnn_modelzoo_no_const.onnx')
output_path = 'test.onnx'

input_names = ['0'],
output_names = ['1204', '1205', '1206', '1228', '1230', '1232', '1234', 
                '1236', '1329', '1360', '1391', '1394', '1531', '1534', 
                '1561', '1568', '1573', '1578', '1583', '1590', '1597', 
                '1604', '911', '919', '927', '935']

onnx.utils.extract_model(input_path, output_path, input_names, output_names)
```

but i can find `1534` node in my onnx model:

![image](https://user-images.githubusercontent.com/43114292/146306078-8fe05a90-9a99-4dc6-8d1d-f770a2b94aaa.png)

my model is [here](https://www.dropbox.com/s/umi5qurionq1tze/mask_rcnn_modelzoo_no_const.onnx?dl=0)

can you help me please with this question, thanks~

**Comment by askhade** [comment]
Your model has this BatchMultiClassNMS op which is not part of ONNX. I checked the model opset imports and it does not import any other domain than onnx. 
1. Make sure your model is valid by running onnx checker
2. Also run onnx checker on extracted model

I am unable to repro because of this OP. If you can share a valid onnx model which exhibits this issue I can try and repro.

**Comment by germanjke** [comment]
Thx, forgot about this BatchMultiClassNMS, so i'm right that, i can't use `extract_models` with unsupported ops by ONNX, even without `checker`?

**Comment by askhade** [comment]
You should be able to use the extract_model utility. I wanted to use checker to make sure the model is valid and I could not because of this op. Where is this op coming from? and why it is registered against onnx domain? If it was registered against a custom domain checker will ignore it.

**Comment by germanjke** [comment]
Thx for the help! Yea, i just rewrite your function without checker for this model! We can close the issue.
