### ISSUE TITLE
How To Use INT8 Input Data in ONNX Runtime Quantized Model?

### ISSUE THREAD

**Issue by Hamptonjc** [onnx/onnx#3904]
I am exporting a LSTM model from PyTorch and quantizing it with ONNX Runtime. However the quantized model still expects fp32 input data. How can I change the model to accept INT8 input data?

**Comment by askhade** [comment]
@Hamptonjc : Please open this issue in [onnxruntime](https://github.com/microsoft/onnxruntime/issues) repo.

Also add the details around how you are quantizing the model. It would be best if you can share the model as well. Closing this issue here.
