### ISSUE TITLE
Cannot read onnx model

### ISSUE THREAD

**Issue by SpOOnySk** [onnx/onnx#3910]
# Bug Report

### Describe the bug
Cannot read onnx file, even after validation

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows 10
- ONNX version (*e.g. 1.7*):  1.10.2
- Python version: 3.7.11
- GCC/Compiler version (if compiling from source): ---
- CMake version: ---
- Protobuf version: liborotoc 3.19.1
- Visual Studio version (if applicable):

### Reproduction instructions
I always get error trying to load onnx model:
cv2.error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\dnn\src\dnn.cpp:3044: error: (-2:Unspecified error) Cannot determine an origin framework of files: models/model-small.onnx in function 'cv::dnn::experimental_dnn_v5::readNet'
```
path_model = "models/"

model_name = "model-small.onnx" 

# Load the DNN model
model = cv2.dnn.readNet(path_model + model_name)
...
```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
I expect to load the model succesfully.

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @SpOOnySk,
It seems like a question for `cv2.dnn.readNet`, not ONNX. Could the ONNX model be loaded successfully by onnx.load and pass by onnx.checker? If so, it should be a valid ONNX file.
