### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'compose

### ISSUE THREAD

**Issue by designerZhou** [onnx/onnx#3912]
I merge 2 model  follow:https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md
failed:
the error as following:
AttributeError: module 'onnx' has no attribute 'compose

**Comment by designerZhou** [comment]
the onnx version:1.10.2

**Comment by jcwchen** [comment]
Hi @designerZhou,
Compose function was supported recently after ONNX 1.10.2 release. If you would like to use this function, please either build ONNX from source or install onnx-weekly package from TestPyPI [here](https://test.pypi.org/project/onnx-weekly/). Thanks.

**Comment by jcwchen** [comment]
Hi @ImEric,
The reason is wget is not available on TestPyPI. You can first use `pip install wget` to get wget from PyPI and then `pip install -i https://test.pypi.org/simple/ onnx-weekly==1.10.2.dev20220110` should work.

**Comment by jackylu0124** [comment]
Hi @jcwchen,
I tried installing the onnx-weekly package from the link above, but still got the `AttributeError: module 'onnx' has no attribute 'compose'` error. Could you please let me know how I can resolve this issue? Thanks a lot in advance!

**Comment by jcwchen** [comment]
Hi @jackylu0124,
Make sure you only have onnx-weekly in your environment. Could you please try the following commands from your end?
```
// It should show Name: onnx-weekly Version: 1.10.2.dev20220124
pip show onnx-weekly
// It should show WARNING: Package(s) not found: onnx
pip show onnx
```

**Comment by jackylu0124** [comment]
Hi @jcwchen,

Thank you very much for your help and suggestions! I was able to resolve the issue with the `--extra-index-url` flag inside the pip install command (https://stackoverflow.com/questions/39910730/python3-is-not-recognized-as-an-internal-or-external-command-operable-program). Still, thanks a lot!

**Comment by jcwchen** [comment]
Close since it should be resolved. Please reopen it if you still have questions. Thanks.
