### ISSUE TITLE
test_qresize

### ISSUE THREAD

**Issue by www516717402** [onnx/onnx#3913]
How to make node and graph for QResize OP like QLinearConv as [follows](https://github.com/onnx/onnx/blob/65974860e20b311d14b642ce22b5a56b8c176ca5/onnx/test/shape_inference_test.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L2322-L2334):
``` python
def test_qlinearconv(self):  # type: () -> None
        graph = self._make_graph(
            [('x', TensorProto.UINT8, (3, 4, 5, 6, 7)),
             ('x_scale', TensorProto.FLOAT, ()),
             ('x_zero_point', TensorProto.UINT8, ()),
             ('w', TensorProto.UINT8, (5, 4, 2, 4, 3)),
             ('w_scale', TensorProto.FLOAT, ()),
             ('w_zero_point', TensorProto.UINT8, ()),
             ('y_scale', TensorProto.FLOAT, ()),
             ('y_zero_point', TensorProto.UINT8, ())],
            [make_node('QLinearConv', ['x', 'x_scale', 'x_zero_point', 'w', 'w_scale', 'w_zero_point', 'y_scale', 'y_zero_point'], 'y', pads=[0, 1, 1, 0, 0, 1], dilations=[1, 2, 2], strides=[1, 1, 2])],
            [])
        self._assert_inferred(graph, [make_tensor_value_info('y', TensorProto.UINT8, (3, 5, 4, 1, 3))])
```

**Comment by jcwchen** [comment]
Hi @www516717402,
IIUC, QResize is not an official ONNX op. Does it come from [ONNXRuntime](https://github.com/microsoft/onnxruntime/blob/a4fdb4dbd9ce1336d4d35b7ae784df04e93c1cf1/onnxruntime/python/tools/quantization/operators/resize.py#L4)? If so, please track this issue there. Close here now. Thanks!
