### ISSUE TITLE
Improper onnx.protot

### ISSUE THREAD

**Issue by artyom-beilis** [onnx/onnx#3914]
# Bug Report

In 1.10 the proto compilation fails

```
onnx.proto:775:3: Expected "required", "optional", or "repeated".
onnx.proto:775:12: Expected field name.
onnx.proto:776:3: Expected "required", "optional", or "repeated".
onnx.proto:776:12: Expected field name.
onnx.proto:780:3: Expected "required", "optional", or "repeated".
onnx.proto:780:12: Expected field name.
onnx.proto:781:3: Expected "required", "optional", or "repeated".
onnx.proto:781:12: Expected field name.
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 18.04*): 
- ONNX version :  master and 1.10
- Protobuf version: protoc `2.6.1`

### Reproduction instructions

```
protoc --proto_path=. --cpp_out=. onnx.proto
```
### Expected behavior
Be able to build with protoc

**Comment by jcwchen** [comment]
Hi @artyom-beilis,
I might encounter similar issue before due to old protobuf version. Could you please try higher protobuf version (>= 3.12.2)? Thanks.

**Comment by artyom-beilis** [comment]
Yes indeed with protobuf `3.0.0` it works.

What is the minimal required version of protobuf?

**Comment by jcwchen** [comment]
https://github.com/onnx/onnx#prerequisites ONNX recommends using protobuf >= 3.12.2. I did see other issues when using protobuf<=3.11.

**Comment by artyom-beilis** [comment]
Thanks
