### ISSUE TITLE
operator nan_to_num to ONNX

### ISSUE THREAD

**Issue by iamlockelightning** [onnx/onnx#3917]
# Feature Request

### System information
ONNX version (you are using):

### What is the problem that this feature solves?
Currently, it is not available.

### Describe the alternatives you have considered
A clear and concise description of any alternative solutions or features you've considered
Get "RuntimeError: Exporting the operator nan_to_num to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub." when using `torch.nan_to_num()`
```python
import torch
import pytorch_lightning as pl

class SimpleModel(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.l1 = torch.nn.Linear(in_features=64, out_features=4)

    def forward(self, x):
        y = self.l1(x.view(x.size(0), -1))
        y = torch.nan_to_num(y)
        return y

filepath = "model.onnx"
model = SimpleModel()
input_sample = torch.randn((1, 64))
model.to_onnx(filepath, input_sample, export_params=True)
```

### Describe the feature
Why is this feature necessary? What does it accomplish?

### Will this influence the current api?
No.

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
operators

### Are you willing to contribute it (Y/N):
N

**Comment by askhade** [comment]
@iamlockelightning: Are you using the latest nightly for pytorch? Please open this issue in pytorch repo to make sure whether this is supported in pytorch converter. Also do you know whether this can be composed using bunch of existing primitive ops?

**Comment by iamlockelightning** [comment]
@askhade No, I am not using the nightly version, just the latest 1.10. I will open this issue in the PyTorch repo. Thanks!
```
pytorch-lightning       1.5.7
torch                   1.10.1
torchaudio              0.10.1
torchmetrics            0.6.2
torchvision             0.11.2
onnx                    1.10.2
onnxruntime             1.9.0
```
