### ISSUE TITLE
The output type of onnx model is list instead of np.array

### ISSUE THREAD

**Issue by wangxudong-cq** [onnx/onnx#3919]
# Ask a Question

### Question
Refer to the Abs example generate an onnx model named 'test', the output type of 'test' model is list instead of np.array.

### Further information
OS:Ubuntu 18.04.5 LTS

onnxruntime
Name: onnxruntime
Version: 1.8.0
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /usr/local/anaconda3/envs/ubuntu/lib/python3.8/site-packages
Requires: protobuf, flatbuffers, numpy
Required-by: 

onnx
Name: onnx
Version: 1.9.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfai.foundation
License: Apache License v2.0
Location: /usr/local/anaconda3/envs/ubuntu/lib/python3.8/site-packages
Requires: six, typing-extensions, numpy, protobuf
Required-by: 

### script
```
node = onnx.helper.make_node(
        "Abs",
        inputs=["x"],
        outputs=["y"]
    )
    x = np.random.randn(3,4).astype(np.float32)
    y = abs(x)
    # print(expect(node, inputs=[x], outputs=[y], name="test"))
    input_vi = [onnx.helper.make_tensor_value_info(
        name="x",
        elem_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[x.dtype],
        shape=x.shape)]
    output_vi = [onnx.helper.make_tensor_value_info(
        name="y",
        elem_type=onnx.mapping.NP_TYPE_TO_TENSOR_TYPE[y.dtype],
        shape=y.shape)]
    graph = onnx.helper.make_graph(
        nodes=[node],
        name="test_abs",
        inputs=input_vi,
        outputs=output_vi)
    model = onnx.helper.make_model(graph)

    ort_session = ort.InferenceSession(model.SerializeToString())
    ort_ins = {"x":x}
    ort_outnames = [x.name for x in ort_session.get_outputs()]

    ort_array = ort_session.run(ort_outnames, ort_ins)
    ort_results = OrderedDict(zip(ort_outnames, ort_array))
    # print(ort_results)
    print(type(y))
    print(type(ort_array))
```

### output
```
<class 'numpy.ndarray'>
<class 'list'>
```

**Comment by jcwchen** [comment]
Hi @wangxudong-cq,
Are you saying that the output of onnxruntime.InferenceSession.run is a list instead of a numpy.array? I think it is by design from onnxruntime. If you compare `ort_array[0]` and `y`, ideally they should be identical.

**Comment by wangxudong-cq** [comment]
@jcwchen  U are right! thanks! I got it!

**Comment by jcwchen** [comment]
It seems resolved. Close here now. Feel free to reopen it if you still have other ONNX questions.
