### ISSUE TITLE
how to  extend output's dim

### ISSUE THREAD

**Issue by mmx110** [onnx/onnx#3920]
# Ask a Question
how to  extend output's dim
### Question
I have a onnx model, the output dims is format NC [batch, 14]. how can I extend outputs dims to NCHW [batch, 14, 1,1] ?

**Comment by gramalingam** [comment]
The python API can be used to update the shape of an output. However, this may not be enough, since it may not successfully get through shape-inference. Is the existing model correct (in terms of shape inference)? If so, you could add Unsqueeze to the output or Reshape to change its shape. I am unclear what exactly is the issue.

**Comment by mmx110** [comment]
> The python API can be used to update the shape of an output. However, this may not be enough, since it may not successfully get through shape-inference. Is the existing model correct (in terms of shape inference)? If so, you could add Unsqueeze to the output or Reshape to change its shape. I am unclear what exactly is the issue.

thanks for your reply.  the existing model is right.  I save my problem by adding reshape layer before output node. 

`def edit_output(onnx_path):
    '''
    desc: reshape output node NC->NHW
    '''
    onnx_model = onnx.load(onnx_path)
    graph = onnx_model.graph
    nodes = graph.node
    dir(graph.node)



    new_shape = onnx.helper.make_tensor(name ='1034_shape', 
                                                data_type = onnx.TensorProto.INT64, 
                                                dims = [3], 
                                                vals = [-1,14,1])
    graph.initializer.append(new_shape)
    new_output = onnx.helper.make_tensor_value_info(name='tensor_kpt_conf', elem_type= 7, shape=['batch_size', 14,1])
    new_scale_node = onnx.helper.make_node(name = '1034_reshape', op_type = 'Reshape', inputs=['1034_reshape', '1034_shape'], outputs=['tensor_output1'])   

    new_qualiyt_shape = onnx.helper.make_tensor(name ='quality_shape', 
                                                data_type = onnx.TensorProto.INT64, 
                                                dims = [3], 
                                                vals = [-1,2,1])
    graph.initializer.append(new_qualiyt_shape)
    new_quality_output =  onnx.helper.make_tensor_value_info(name='tensor_quality', elem_type= 1, shape=['batch_size', 2,1])
    new_quality_node = onnx.helper.make_node(name = 'quality_reshape', op_type = 'Reshape', inputs=['quality_reshape', 'quality_shape'], outputs=['tensor_output2'])  

    for node in nodes:
        if len(node.output)>0  and node.output[0] == 'tensor_output2':
            print(node)
            node.output[0] = 'quality_reshape'
            graph.node.append(new_quality_node)
            break
    
    for output in onnx_model.graph.output:
        d = output.type.tensor_type.shape.dim
        if output.name == 'tensor_output2':
            print(output)
            onnx_model.graph.output.remove(output)
            onnx_model.graph.output.append(new_quality_output)
            break


    for node in nodes:
        if len(node.input) >0 and node.input[0] == '1034':
            print(node)
            node.output[0] = '1034_reshape'
            graph.node.append(new_scale_node)
            break

    for output in onnx_model.graph.output:
        d = output.type.tensor_type.shape.dim
        if output.name == 'tensor_output1':
            print(output)
            onnx_model.graph.output.remove(output)
            onnx_model.graph.output.append(new_output)
            break

    onnx.checker.check_model(onnx_model)
    onnx.save(onnx_model, onnx_path.replace('org', 'fix'))`
