### ISSUE TITLE
Feature Request: Create a script to format both python and cpp code for contributors

### ISSUE THREAD

**Issue by xuzijian629** [onnx/onnx#3934]
# Feature Request
Currently, ONNX has clang-format as formatter for C++, and flake8 and mypy for checking python.
I suggest to create a script (like `format.sh`) that can check format for both c++ and python code at the same time.

### What is the problem that this feature solves?
I (and maybe some other contributors) usually forget formatting and get CI errors.
Moreover, flake8 check is only written in the CI setting (`.azure-pipelines/*-CI.yml`) and it is hard for newcomers to notice this.

If there is an all-in-one script and we can format the whole code by simply running it, it would be much developer-friendly.

### Describe the alternatives you have considered
Since running the whole check may be costly, it would be more useful if we prepare both `./format-cpp.sh` and `./format-python.sh`. We may create more scripts, but at least we need to document somewhere what kind of format tools are used.

### Describe the feature
It formats the whole code.

### Will this influence the current api?
No.

### Are you willing to contribute it (Y/N):
Yes. If you think this feature is good, I can implement it.

**Comment by jcwchen** [comment]
Hi @xuzijian629,
Sounds like a good idea. It will also help to simplify the CIs. Feel free to propose a PR for it. Thank you again for all the contribution!

**Comment by garymm** [comment]
A git commit hook that checks for formatting would be nice too.

**Comment by xuzijian629** [comment]
Where is the code checked by clang-format in CI? I could not find it anywhere...

**Comment by jcwchen** [comment]
> Where is the code checked by clang-format in CI? I could not find it anywhere...

Sorry for the late response. You are right -- there is no clang-format checking in current CIs. It is only for local development now.

**Comment by xuzijian629** [comment]
I created a PR: https://github.com/onnx/onnx/pull/3988

I want to hear more opinions from committers how to organize the scripts. Please share your ideas there!

**Comment by xuzijian629** [comment]
Resolved for python code. For C++, we continue on #4083
