### ISSUE TITLE
Is this concat operation supported by ONNX?

### ISSUE THREAD

**Issue by tensorflowt** [onnx/onnx#3936]
# Source
PaddlePaddle->onnx->onnx-sim 
onnx version:11.0
# Describe
The input feature graph and the two learned feature graphs are spliced in dimension.
# New Operator
![concat](https://user-images.githubusercontent.com/37217594/149057480-b93da9a4-b261-46d9-8ee5-f8b3f03e0906.png)
# one of the two learned feature graphs info:
![a35e8db6072a06bf6ffb120c7e5df03](https://user-images.githubusercontent.com/37217594/149057924-66e281ad-e21f-4e30-84f2-d27a83da0529.png)
# Confused point
How does this work? 
Any suggestions if I need to refactor it with traditional operations by caffe？

# Thanks

I hope I can get your help！
Thanks !

**Comment by jcwchen** [comment]
Yes Conat is a supported ONNX operator https://github.com/onnx/onnx/blob/main/docs/Operators.md#concat. You can check all supported operators in the same document. As you can see, the output shape of concat_8.tmp_0 is 1x130x76x76.

**Comment by askhade** [comment]
@tensorflowt: I don't understand your question. Is it simply - Is concat supported in onnx? or do you need some help for converting the model to onnx?
