### ISSUE TITLE
python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/

### ISSUE THREAD

**Issue by danielbellhv** [onnx/onnx#3937]
Based on [SO post](https://stackoverflow.com/q/70652768/17840900).

Kernel: `conda_pytorch_p36`. I performed Restart & Run All, and refreshed file view in working directory.

I'm following along with this [code tutorial][1], the first Python code module.

```
python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
```

Console:
```
python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
  File "<ipython-input-1-0652039cb84d>", line 1
    python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
                         ^
SyntaxError: invalid syntax
```

Terminal:
```
sh-4.2$ python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/python: Error while finding module specification for 'transformers.onnx' (ModuleNotFoundError: No module named 'transformers')
```

  [1]: https://huggingface.co/docs/transformers/master/serialization

**Comment by jcwchen** [comment]
Hi @danielbellhv,
According to the error message you gave, it said "transformers" module cannot be found.
Please use the following command to check whether transformers was properly installed:
```
# it should show the version of transformers
pip show transformers
# it should just finish without any error
python -c "import transformers"
```

**Comment by danielbellhv** [comment]
Hi @jcwchen . Sorry only just saw this now.

Underneath section **Converting an ONNX model using the transformers.onnx package**

`pip show transformers`
```
Name: transformers
Version: 4.15.0
Summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
Home-page: https://github.com/huggingface/transformers
Author: Thomas Wolf, Lysandre Debut, Victor Sanh, Julien Chaumond, Sam Shleifer, Patrick von Platen, Sylvain Gugger, Suraj Patil, Stas Bekman, Google AI Language Team Authors, Open AI team Authors, Facebook AI Authors, Carnegie Mellon University Authors
Author-email: thomas@huggingface.co
License: Apache
Location: /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages
Requires: dataclasses, filelock, huggingface-hub, importlib-metadata, numpy, packaging, pyyaml, regex, requests, sacremoses, tokenizers, tqdm
Required-by: nn-pruning, optimum
Note: you may need to restart the kernel to use updated packages.
```

`python -c "import transformers"`:
```
  File "<ipython-input-4-ceb8ff756eda>", line 1
    python -c import transformers
                   ^
SyntaxError: invalid syntax
```

**Comment by jcwchen** [comment]
Thanks for the update. Although your `pip show` does show a installed transformers, your default python still cannot find the installed transformers... I guess you might have few different Python environments. Did you activate your conda env (pytorch_p36) before using `python -c "import transformers"`? Or, please try to install transformers in a new Python environment from scratch. (for instance, a new conda env)

**Comment by danielbellhv** [comment]
I setup a new Jupyter Labs, using various PyTorch kernels with the same errors as before

**Comment by jcwchen** [comment]
According to your pip show, your installed transformers locates under anaconda3/envs/pytorch_p36. It's possible that you cannot find it if you did not activate into that coda environment... Could you please try this `/home/ec2-user/anaconda3/envs/pytorch_p36/python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/`?

**Comment by danielbellhv** [comment]
Terminal:
```
sh-4.2$ /home/ec2-user/anaconda3/envs/pytorch_p36/python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/
sh: /home/ec2-user/anaconda3/envs/pytorch_p36/python: No such file or directory
sh-4.2$ 
```

**Comment by jcwchen** [comment]
Oh sorry, on Linux, conda python should locate at `/home/ec2-user/anaconda3/envs/pytorch_p36/bin/python`.  Thus please try `/home/ec2-user/anaconda3/envs/pytorch_p36/bin/python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/`.

> I ran most of the notebook installs, ones that do run, and set the same Kernel.

So this command is at least runnable for certain environment from your end.

Please note that it's not a bug. You need to make sure your using Python has installed transformers. The reason why you can see transformers in `pip show` but you cannot import it through python is your `pip show` and `python` are using different python path.

**Comment by danielbellhv** [comment]
Ah ok, this is an external issue from the original question. So I will close the issue now. Thanks @jcwchen
