### ISSUE TITLE
Mapping input variables to model input variables

### ISSUE THREAD

**Issue by tmbrye** [onnx/onnx#3942]
I have been tasked with creating an ONNX model consumer for a database.  Users will be able to load models into the database and use the model to score a table of input data.  The question I have is how do you map the columns of a table to the necessary inputs of the model?  

For instance, if one user created a model in python on the iris dataset and shared that model with a coworker, do they have to manually tell the coworker the exact order of the input variables or is this information stored somewhere within the onnx model?

When looking at a model I generated in python I only see the input listed as a float array of 4 values but I don't see anything that gives the ordering of that values, say, sepal_length, sepal_width, petal_length, and petal_width.

I'm familiar with PMML and the inputs are spelled out rather clearly and I'm hoping the same exists in the onnx format.

Thanks!

**Comment by jcwchen** [comment]
Hi @tmbrye,
You are right. ONNX format does not provide such a map (value information) for input (also initializer and output). Users need to handle the map (input name to input value) externally.

**Comment by tmbrye** [comment]
Appreciate the answer!  Not the one I had hoped for but it is good to know.  Guess I'll have to get creative and find a nice way for the user to give the mapping of input columns to the model inputs.
