### ISSUE TITLE
No implicit accumulation of a Loop body output if its type is seq? 

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx#3943]
# Ask a Question
No implicit accumulation of Loop body output if its type is seq?

### Question
When a loop body generates a tensor output, the Loop op will accumulate the result from each iteration as part of the output of the Loop.
But from the example (backend/test/node/loop.py: test_loop13_seq) and the shape inference code (defs/controlflow/defs.cc), it seems to me that there is no implicit accumulation by Loop when an output of the loop body is of a seq type. We do not create a tensor of seq (or seq of seq) for the loop. We just direct use that output of loop body as the Loop output.  Is it true?
I did not find the specification in document, or did I miss any document?

### Further information
-  operator:  Loop

**Comment by gramalingam** [comment]
Right, there is no support for implicit accumulation for sequences. The operator spec says "Scan outputs must be Tensors." They are not allowed to be sequence types. (Does the checker complain or accept in this case?)

**Comment by chentong319** [comment]
Thanks. I missed that sentence in spec.

Nothing to do with the checker. I am adding the support for seq in onnx-mlir.
