### ISSUE TITLE
TestAutomaticUpgrade.test_ops_tested fails with Python 3.9 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ggardet** [onnx/onnx#3946]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
`TestAutomaticUpgrade.test_ops_tested` unit test is failing on openSUSE Tumbleweed (x86_64 and aarch64):
```
[  794s] =================================== FAILURES ===================================
[  794s] _____________________ TestAutomaticUpgrade.test_ops_tested _____________________
[  794s] [gw2] linux -- Python 3.9.9 /usr/bin/python3.9
[  794s] 
[  794s] self = <automatic_upgrade_test.TestAutomaticUpgrade testMethod=test_ops_tested>
[  794s] 
[  794s]     def test_ops_tested(self):  # type: () -> None
[  794s]         all_schemas = onnx.defs.get_all_schemas()
[  794s]         all_op_names = [schema.name for schema in all_schemas if schema.domain == '']
[  794s]         excluded_ops = [
[  794s]             # Sequence-based and Optional-based ops disabled because
[  794s]             # the version converter doesn't play nicely with sequences
[  794s]             'ConcatFromSequence',
[  794s]             'SequenceAt',
[  794s]             'SequenceConstruct',
[  794s]             'SequenceEmpty',
[  794s]             'SequenceErase',
[  794s]             'SequenceInsert',
[  794s]             'SequenceLength',
[  794s]             'SplitToSequence',
[  794s]             'Optional',
[  794s]             'OptionalGetElement',
[  794s]             "OptionalHasElement"
[  794s]         ]
[  794s]         all_op_names = [op for op in all_op_names if op not in excluded_ops]
[  794s]     
[  794s]         untested_ops = set(all_op_names) - set(tested_ops)
[  794s] >       assert len(untested_ops) == 0
[  794s] E       AssertionError: assert 111 == 0
[  794s] E         +111
[  794s] E         -0
[  794s] 
[  794s] test/automatic_upgrade_test.py:1057: AssertionError
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): openSUSE Tumbleweed
- ONNX version (*e.g. 1.7*):  1.10.2
- Python version: 3.9
- GCC/Compiler version (if compiling from source): gcc11
- CMake version: 3.22.1
- Protobuf version: 3.17.3
- Visual Studio version (if applicable): n/a

### Reproduction instructions
Run unit tests with `pytest` on openSUSE Tumbleweed

### Expected behavior
All tests should pass.

### Notes
N/A

**Comment by jcwchen** [comment]
Hi @ggardet,
`assert len(untested_ops) == 0` this line makes sure every ONNX operator except `excluded_ops` has been tested. Did you add any operator by yourself? I cannot repro this error with ONNX 1.10.2. If possible, could you please help me to try something from your end:
1. Does `len(set(all_op_names))` equal to 158?
2. What does `len(set(tested_ops))` equal? (47?)
3. Have all other tests in automatic_upgrade_test.py been tested successfully?

Thank you.

**Comment by ggardet** [comment]
All other tests in `automatic_upgrade_test.py` are successful.

I added:
```
assert len(set(all_op_names)) == 158
assert len(set(tested_ops)) == 47
```
just before the failing assert and those 2 asserts passed.

On openSUSE Leap 15.3, with python 3.6.15, the message is a bit more verbose:
```
[  262s] >       assert len(untested_ops) == 0
[  262s] E       AssertionError: assert 111 == 0
[  262s] E        +  where 111 = len({'Abs', 'Acos', 'Add', 'ArgMax', 'Asin', 'Asinh', ...})
```

**Comment by jcwchen** [comment]
Thank you for the update.

> All other tests in automatic_upgrade_test.py are successful.

Could you please check roughly how many tests were tested by `automatic_upgrade_test.py`? It's weird that there were only 47 operators which have been tested. `automatic_upgrade_test.py` should have hundreds of (~195) tests for testing 147 ONNX operators. Also please check what those 47 `tested_ops` are. Thank you for the help!

**Comment by jcwchen** [comment]
Thank you for providing the log. I think I probably know what happened and I can repro this error with `pytest -n 2`. Actually current `automatic_upgrade_test.py` cannot be tested _parallelly_ since it uses global variable for summation. As a workaround, pytest without `-n` should help resolve the error.

**Comment by ggardet** [comment]
Indeed, if I set `-n` to `1` then tests pass properly. Thanks!
