### ISSUE TITLE
Apache Licence template not populated

### ISSUE THREAD

**Issue by matthewhagraphcore** [onnx/onnx#3951]
# Bug Report

### Describe the bug
Hi, The template for use in other projects on the Onnx repo isn't populated [see here](https://github.com/onnx/onnx/blob/67ca4ba9c7f82be5d119aac202516fa7161fbb52/LICENSE#L190)

```
   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at 

....
```

We are trying to use some code in another project and want to use the template, but are hesitant to populate it ourselves. Could you update with the correct info?

### System information
N/A

### Expected behaviour
The licence template should be populated.

### Notes

Any additional information

Thanks, 

Matt

**Comment by askhade** [comment]
@onnx/steering-committee

**Comment by andife** [comment]
Short explanation why filling is not recommended in some cases.

https://reuse.software/faq/#edit-license
