### ISSUE TITLE
[Tracking] Upgrade MacOS to 11.0 from 10.15 in Mac release pipeline

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#3955]
Since MacOS-latest now uses 11.0 by default in GitHub Action, Mac release pipeline should start to use 11.0: https://github.com/onnx/onnx/blob/5668578e64f026f1e59771dc5427d9984680ca9d/.github/workflows/release_mac.yml#L20

Create this issue for tracking this task.

**Comment by jcwchen** [comment]
Hold this for now since 11.0 does not support Python 3.6... Will come back to this item after ONNX deprecates Python 3.6.

**Comment by askhade** [comment]
Can we create a label for Tracking issues? This way querying for them will be much easier.

**Comment by jcwchen** [comment]
Sounds good! Just added tracking on all my tracking issues.
