### ISSUE TITLE
Why is `sorted` attribute of Unique an int instead of bool

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#3956]
The operator Unique has an attribute `axis` of type int, which has only two legal values, 0 or 1. Why wasn't type `bool` chosen for this attribute? Is there a notion that more values might be allowed in the future, or is it just for compatibility with another framework?

**Comment by askhade** [comment]
@gramalingam , @postrational : Do you have any historical context on this?

**Comment by gramalingam** [comment]
ONNX does not have a boolean type attribute. All boolean attributes are encoded as integers, AFAIK.

**Comment by gramalingam** [comment]
The attribute-type system and tensor-element type-system are different in ONNX, and the attribute-type-system is simpler ... only one type of integer, one type for floating point in attribute-type-system.

**Comment by gramalingam** [comment]
As for Unique: I assume you are referring to the `sorted` attribute? The `axis` attribute is not restricted to 0/1 values.

**Comment by ArchRobison** [comment]
Correct, I meant the `sorted` attribute.

**Comment by ArchRobison** [comment]
Thanks for the explanation.
