### ISSUE TITLE
Upgrade mypy to latest version

### ISSUE THREAD

**Issue by stillmatic** [onnx/onnx#3964]
# Feature Request

### System information
ONNX version (you are using): latest

### What is the problem that this feature solves?
The current 

### Describe the alternatives you have considered
N/A

### Describe the feature
The current mypy version on main is 0.760 (17 December 2019), we should upgrade to a more recent version and take advantage of the improvements.

### Will this influence the current api?
Unlikely.

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

### Are you willing to contribute it (Y/N):
I will not likely have substantial additional bandwidth for this.

### Notes
Previous PRs:
* https://github.com/onnx/onnx/pull/3604 -- initial attempt at upgrading everything in one go
* https://github.com/onnx/onnx/pull/3926 -- removing six usages and python 2 support (so no more special casing typechecks)
* https://github.com/onnx/onnx/pull/3939 -- upgraded from 0.600 -> 0.760 and removed vendored protobufs

**Comment by asears** [comment]
As part of the upgrade, should the typing documentation for contributors be updated, if not currently supporting python 2?

https://github.com/onnx/onnx/blob/main/docs/TypeAnnotations.md

![image](https://user-images.githubusercontent.com/7253192/151124023-ba68f23a-3b22-4c58-b3e3-48efa45d889a.png)

Might need some blanket issue to improve the typing from comments to code if necessary...

**Comment by stillmatic** [comment]
Yep the docs should definitely be reworked.


> improve the typing from comments to code
Should be able to do so via https://github.com/ilevkivskyi/com2ann

**Comment by jcwchen** [comment]
ONNX should pass the latest mypy (0.971) after this PR: https://github.com/onnx/onnx/pull/4495. I will close this one. Thanks!
