### ISSUE TITLE
What means "QLinearConv : filter zero point must be constant" error message ?

### ISSUE THREAD

**Issue by 110-kenichi** [onnx/onnx#3967]
# Ask a Question

### Question

Could you please tell me what means the following message?  How to resolve this error message?

>  File "/workspace/train3/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running QLinearConv node. Name:'Conv_5' Status Message: QLinearConv : filter zero point must be constant

### Further information
I'm using the onnx runtime 1.9.0

**Comment by jcwchen** [comment]
Hi @110-kenichi,
Actually this error happened in ONNXRuntime. Could you raise this issue in [ONNXRuntime](https://github.com/microsoft/onnxruntime) to get the best help from quantization experts? Close here now. Please reopen it if you still have other ONNX questions. Thanks!
