### ISSUE TITLE
How can use NoneType on onnx.AttributeProto()

### ISSUE THREAD

**Issue by developerChans** [onnx/onnx#3972]
i want recive Nonetype None for AttributeProto().AttributeType

>>  def _int(name, value = None) : 
>>     attribute = onnx.AttributeProto()
>>     attribute.name = name
>>     attribute.type = onnx.AttributeProto.AttributeType.INT
>>     attribute.i = value

value = None case a problem comes up Casue None is Nonetype but expect Int or long

But I want use NoneType in onnx.AttributeProto() AttributeType How can I use?

**Comment by gramalingam** [comment]
What do you mean by NoneType? Are you trying to export a model from Python or PyTorch to ONNX? In ONNX, the convention is to omit an attribute if it has no value (in a NodeProto).

**Comment by developerChans** [comment]
First of all, I apologize for the inaccurate question and my poor English.

Now, I study that onnx operators python to c language implement
However, during the operator test,
there are something attribute.
some of attribute is optional 
some of attribute is required
some of attribute have default value

And then, some of attribute is optional and dont have dafault value
I used to create functions that return the type of each variable in each test.

example)
def _int(attributeName, attributeValue = None) :
   attribute = onnx.AttributeProto()
   attribute.name = attributeName
   attribute.type = onnx.AttributeProto.AttributeType.INT
   attribute.i = attributeValue
* attributeValue is attribute's defaultValue

CASE : optional and dont have dafault value
> how can I assign attribute.type about attributeVale = None Case

And I think I trying to export a model from onnx to python
Also, Now I solve that problem but I dont know that solve is right...
Thanks you
