### ISSUE TITLE
basic installation fails on ubuntu1804

### ISSUE THREAD

**Issue by gggh000** [onnx/onnx#3977]
Followed the instruction on website for python, cuda10.2, _ubuntu1804
Looking at log there seems to be building from source code is happening, i thought pypi repository is for publishing distribution packages. It seems extremely poor way of distributing in case of onnx by doing source code build during pip install and subsequently it is failing. 

nonroot@nonroot-MS-7B22:~$ sudo pip3 install onnx
The directory '/home/nonroot/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nonroot/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting onnx
  Downloading https://files.pythonhosted.org/packages/16/6a/bdae938babb4bc23de7b599439f3d1f1179748385e4ced099f3b4cb646bd/onnx-1.10.2.tar.gz (9.9MB)
    100% |████████████████████████████████| 9.9MB 149kB/s 
Requirement already satisfied: numpy>=1.16.6 in ./.local/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: protobuf in ./.local/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: six in ./.local/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./.local/lib/python3.6/site-packages (from onnx)
Installing collected packages: onnx
  Running setup.py install for onnx ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_5tw3dku/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1u7xnsh4-record/install-record.txt --single-version-externally-managed --compile:
    fatal: not a git repository (or any of the parent directories): .git
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-build-_5tw3dku/onnx']
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "3.0.0")
    Generated: /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    CMake Warning at CMakeLists.txt:450 (find_package):
      Could not find a configuration file for package "pybind11" that is
      compatible with requested version "2.2".
    
      The following configuration files were considered but not accepted:
    
        /usr/lib/cmake/pybind11/pybind11Config.cmake, version: 2.0.1
    
    
    
    --
    -- ******** Summary ********
    --   CMake version             : 3.10.2
    --   CMake command             : /usr/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       :
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.10.2
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/bin/protoc
    --   Protobuf includes         : /usr/include
    --   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3
    --     Python includes       : /usr/include/python3.6m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build
    Scanning dependencies of target gen_onnx_proto
    Scanning dependencies of target onnxifi_dummy
    Scanning dependencies of target onnxifi_loader
    [  4%] Running gen_proto.py on onnx/onnx.in.proto
    [  4%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
    [  4%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
    /tmp/pip-build-_5tw3dku/onnx/onnx/onnxifi_dummy.c: In function ‘onnxGetExtensionFunctionAddress’:
    /tmp/pip-build-_5tw3dku/onnx/onnx/onnxifi_dummy.c:177:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
               *function = &onnxGetExtensionFunctionAddress;
                         ^
    /tmp/pip-build-_5tw3dku/onnx/onnx/onnxifi_dummy.c:180:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
               *function = &onnxSetIOAndRunGraph;
                         ^
    Processing /tmp/pip-build-_5tw3dku/onnx/onnx/onnx.in.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto3
    generating /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx_pb.py
    [  5%] Linking C static library libonnxifi_loader.a
    [  7%] Running C++ protocol buffer compiler on /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    [  8%] Linking C shared library libonnxifi_dummy.so
    [  8%] Built target onnxifi_loader
    Scanning dependencies of target onnxifi_wrapper
    [  8%] Built target onnxifi_dummy
    [ 10%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
    Writing mypy to onnx/onnx_ml_pb2.pyi
    [ 10%] Built target gen_onnx_proto
    [ 11%] Running gen_proto.py on onnx/onnx-data.in.proto
    [ 13%] Running gen_proto.py on onnx/onnx-operators.in.proto
    [ 14%] Linking C shared module libonnxifi.so
    Processing /tmp/pip-build-_5tw3dku/onnx/onnx/onnx-operators.in.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto3
    generating /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx_operators_pb.py
    Processing /tmp/pip-build-_5tw3dku/onnx/onnx/onnx-data.in.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    Writing /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-data.proto3
    generating /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx_data_pb.py
    [ 17%] Running C++ protocol buffer compiler on /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    [ 17%] Running C++ protocol buffer compiler on /tmp/pip-build-_5tw3dku/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    [ 17%] Built target onnxifi_wrapper
    Writing mypy to onnx/onnx_operators_ml_pb2.pyi
    Writing mypy to onnx/onnx_data_pb2.pyi
    Scanning dependencies of target onnx_proto
    [ 22%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
    [ 22%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
    [ 22%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
    [ 23%] Linking CXX static library libonnx_proto.a
    [ 26%] Built target onnx_proto
    Scanning dependencies of target onnx
    [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
    [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
    [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
    [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
    [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
    [ 35%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
    [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
    [ 38%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
    [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
    [ 41%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
    [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
    [ 44%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
    [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
    [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
    [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
    [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
    [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
    [ 53%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
    [ 55%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
    [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
    [ 58%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
    [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
    [ 61%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
    [ 62%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
    [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
    [ 65%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
    [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
    [ 68%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
    [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
    [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
    [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
    [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
    [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
    [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
    [ 79%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
    [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
    [ 82%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
    [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
    [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
    [ 86%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
    [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
    [ 89%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/training/defs.cc.o
    [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/onnxifi_utils.cc.o
    [ 92%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
    [ 94%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
    [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
    [ 97%] Linking CXX static library libonnx.a
    [ 97%] Built target onnx
    Scanning dependencies of target onnx_cpp2py_export
    [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
    [100%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf5Arena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:98: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:349: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_5tw3dku/onnx/setup.py", line 361, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-_5tw3dku/onnx/setup.py", line 233, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-_5tw3dku/onnx/setup.py", line 227, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '6']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_5tw3dku/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1u7xnsh4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_5tw3dku/onnx/
nonroot@nonroot-MS-7B22:~$

**Comment by jcwchen** [comment]
Two things:
1. Why `pip3 install onnx` does not build from a prebuilt wheel on Ubuntu 18.04
My best guess is because of it: https://github.com/pypa/manylinux/issues/389. If you see your pip version < 19 (`pip3 -V`), could you please try to upgrade your PyPI version?

2. Build from source failure due to protobuf symbol error
Here is a similar issue: https://github.com/onnx/onnx/issues/3570. In short, you need to build protobuf from source with `-fPIC`. You can check more details in the [Readme.md](https://github.com/onnx/onnx#linux).

**Comment by gggh000** [comment]
after upgrading pip3, it appears to work.
