### ISSUE TITLE
Converting Type Comments to Type Annotations

### ISSUE THREAD

**Issue by stroxler** [onnx/onnx#3980]
# Ask a Question

### Question

Would we mind converting type comments to type annotations?

### Further information

I've been working on converting old code that used python 2.7-style type comments (of the form `# type: ...` to use python 3.6-style type annotations.

I came across onnx because it is vendored into a project I'm converting. It looks to me like onnx is now Python 3.6+ only, so I could make the conversion here.

Is this something you'd be interested in? I can see that much of the code already uses type annotations, updating the old type comments makes the types slightly easier to read and makes it less likely that someone forgets to update them when things change.

**Comment by jcwchen** [comment]
Hi @stroxler,
I hope this fresh merged PR has covered all of the cases: https://github.com/onnx/onnx/pull/3962. If you find anything left, feel free to submit a PR for it. Thank you!
