### ISSUE TITLE
Full check cannot detect operator type error under specific opset versions

### ISSUE THREAD

**Issue by ganler** [onnx/onnx#3995]
# Bug Report

### Is the issue related to model conversion?

Partially, PyTorch attempts to generate a wrong model but `onnx.checker.check_model(model, full_check=True)` cannot detect.

### Describe the bug

It seems ONNX checker never checks the data type required of operators under a specific opset version. And it has been widely used as an indication that the exported model is valid by existing DL frameworks (e.g., PyTorch).

For example, `Clip` opset < 12 does not support integer tensors but if PyTorch exports a single `Clip<int>` operator with the opset under 12, the checker does not report errors, thus leading to a silent inconsistency bug in TensorRT (https://github.com/onnx/onnx-tensorrt/pull/788).

Just want to confirm if `onnx.checker.check_model` should be responsible for this. :-)

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Manjaro
- ONNX version (*e.g. 1.7*):  1.10.2
- Python version: 3.8

### Reproduction instructions
- Describe the code to reproduce the behavior.
```python
import torch
import onnx


class Model(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()

    @torch.no_grad()
    def forward(self, x):
        y = torch.clip(x, 0, 1)
        return y


model = Model()
inputs = (torch.randn(10,).to(torch.int32),)
torch.onnx.export(model, inputs, "output.onnx", verbose=False,
                  input_names=["input"], opset_version=7, output_names=["output"])

onnx.checker.check_model(onnx.load("output.onnx"), full_check=True)
# Except some exceptions but nothing happens...
```

### Expected behaviour

An exception regarding the model specification should be thrown.

### Notes

Related issues: https://github.com/onnx/onnx-tensorrt/pull/788

**Comment by jcwchen** [comment]
Hi @ganler,
Actually I cannot repro this error: I used the same code you have provided and it showed the following error:
```
[ShapeInferenceError] (op_type:Clip, node name: Clip_0): input typestr: T, has unsupported type: tensor(int32)
```
I am using ONNX 1.10.2 and PyTorch 1.10.1. What's your version of ONNX and PyTorch? I remembered this error might be silent before ONNX 1.9. Also could you please share the bug model? Thanks!

**Comment by ganler** [comment]
@jcwchen I am sorry I was using another under-dev pytorch version which internally fixes such issues (https://github.com/pytorch/pytorch/pull/72401). I will reinstall the standard PyTorch and try again. But I do think I got such errors a few tweaks ago.

**Comment by ganler** [comment]
> Hi @ganler, Actually I cannot repro this silent behaviour: I used the same code you have provided and it showed the following error:
> 
> ```
> [ShapeInferenceError] (op_type:Clip, node name: Clip_0): input typestr: T, has unsupported type: tensor(int32)
> ```
> 
> I am using ONNX 1.10.2 and PyTorch 1.10.1. What's your version of ONNX and PyTorch? I remembered this error might be silent before ONNX 1.9. Also could you please share the bug model? Thanks!

Thank you for pointing it out. You are right! It seems because I was using older ONNX and my recently upgrading ONNX automatically fixed that but I did not notice it. Sorry for the confusion.
