### ISSUE TITLE
Is it possible to duplicate the "input" value in the mnist model?

### ISSUE THREAD

**Issue by developerChans** [onnx/onnx#4007]
In the mnist model, is the "input" value of each operator equal to the "input" value of another operator?
I see mnist-11-from-torch's quantized model
that model's input is duplicated on NETRON

![image](https://user-images.githubusercontent.com/68864422/153548319-ce10f530-e9cd-4567-b684-7f5c1e678b89.png)

![image](https://user-images.githubusercontent.com/68864422/153548343-b7cbd5ae-6f09-4498-a86a-dcd4bc1ccd9d.png)

is it same input?

**Comment by jcwchen** [comment]
Hi @developerChans,
Yes, it can be the same input for different nodes and you will see there are multiples arrows pointing to different nodes from a same place on Netron if they are not initializers. Thus, for the model you provided, their input x are different input, but their input x_scale and x_zero_point come from the same initializer. You can simply use name to distinguish whether they are the same.

P.S. from [ONNX IR](https://github.com/onnx/onnx/blob/main/docs/IR.md#graphs):
```
The graph MUST adhere to single static assignment (SSA) for all node outputs; this means that all node output names MUST be unique within a graph.
```

**Comment by developerChans** [comment]
Thank you @jcwchen 
I have one more question...
that model input kind is initalizer...
how about attribute??
is it poosible attribute kind is initalizer??
