### ISSUE TITLE
Spec for Scan from opset 9+ has unused type constraint 'I'

### ISSUE THREAD

**Issue by skottmckay** [onnx/onnx#4009]
# Bug Report

### Describe the bug
The ONNX spec for Scan should have dropped the 'I' type constraint in opset 9 when the sequence lengths input was removed. 

Is it possible to update the spec to remove this unused constraint from Scan 9, 11 and 16?

Use case: The spurious constraint makes it harder to validate that an implementation matches the spec.

**Comment by jcwchen** [comment]
Hi @skottmckay,
The fix has been just merged. Thank you for catching it!
