### ISSUE TITLE
Some tf2onnx test cases failed with latest 1.11.0rc1 and 1.11.0rc2 version.

### ISSUE THREAD

**Issue by fatcat-z** [onnx/onnx#4018]
# Bug Report

### Describe the bug
While running tf2onnx test case BackendTests.test_sparse_fill_empty_rows with latest RC2 version, the test case failed with below exception:

======================================================================
ERROR: test_sparse_fill_empty_rows (__main__.BackendTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "repos/fatcat-z/tensorflow-onnx/tests/test_backend.py", line 4806, in test_sparse_fill_empty_rows
    self._run_test_case(func, [_OUTPUT, _OUTPUT1], {_INPUT: i_val, _INPUT1: v_val, _INPUT2: ds_val, _INPUT3: d_val})
  File "repos/fatcat-z/tensorflow-onnx/tests/test_backend.py", line 178, in _run_test_case
    return self.run_test_case(func, feed_dict, [], output_names_with_port, **kwargs)
  File "repos/fatcat-z/tensorflow-onnx/tests/backend_test_base.py", line 400, in run_test_case
    self.assert_shapes_correct(g, self.config.allow_missing_shapes, not self.config.skip_onnx_checker)
  File "repos/fatcat-z/tensorflow-onnx/tests/backend_test_base.py", line 297, in assert_shapes_correct
    raise e
  File "repos/fatcat-z/tensorflow-onnx/tests/backend_test_base.py", line 291, in assert_shapes_correct
    onnx.checker.check_model(model_proto, full_check=True)
  File "anaconda3/envs/tfonnxdebug/lib/python3.8/site-packages/onnx/checker.py", line 107, in check_model
    onnx.shape_inference.infer_shapes(model, check_type=True, strict_mode=True)
  File "anaconda3/envs/tfonnxdebug/lib/python3.8/site-packages/onnx/shape_inference.py", line 41, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode, data_prop)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:Concat, node name: SparseFillEmptyRows/SparseFillEmptyRows_Concat__45): [ShapeInferenceError] All inputs to Concat must have same rank

This exception was thrown by onnx.checker, but only onnx version is changed in the environment so we should take a look.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  
- ONNX version (*e.g. 1.7*):  Ubuntu 20.04.1 LTS
- Python version: 3.8.5
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:  3.14.0
- Visual Studio version (if applicable):

### Reproduction instructions
1. Clone tf2onnx code: https://github.com/onnx/tensorflow-onnx
2. Change the current folder to above local code folder, execute command:

python tests/test_backend.py --opset 11 BackendTests.test_sparse_fill_empty_rows

### Expected behavior
This test should pass.

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @fatcat-z,
Thank you for catching it. I think this PR should cover it: https://github.com/onnx/onnx/pull/4019. Could you please confirm whether it helps? Thanks!

**Comment by jcwchen** [comment]
Close it since the fix has been merged.
