### ISSUE TITLE
How to set up the build process to onnx.pb.h be created?

### ISSUE THREAD

**Issue by khamyl** [onnx/onnx#4023]
# Ask a Question

### Question
1) How to set up the build process to `onnx.pb.h` and `onnx.pb.cc` be installed?

**Comment by jcwchen** [comment]
Hi @khamyl,
Similar to https://github.com/onnx/onnx/issues/1947? By default (-DONNX_ML=ON) you will get `onnx-ml.pb.h` under `.setuptools-cmake-build\onnx`. If you set something like `set CMAKE_ARGS="-DONNX_ML=OFF"`, you will find `onnx.pb.h` instead.
