### ISSUE TITLE
issue in converting from ONNX to Tensorflow due to Resize

### ISSUE THREAD

**Issue by Daveorr** [onnx/onnx#4024]
### Question
Not sure if there's a way to fix this, if someone can point me out a solution or at least a direction on which investigate it would be great, so:

I've converted succesfully my model from MXnet to ONNX but since the original model has 2 layers such as:

```
      "op": "UpSampling", 
      "name": "rf_c3_upsampling", 
      "attrs": {
        "num_args": "1", 
        "sample_type": "nearest", 
        "scale": "2", 
        "workspace": "512"
      }, 
      "inputs": [[227, 0, 0]]
```

This operation is automatically converted in ONNX into a `Resize` operation with `mode=half_pixel` and this is preventing me to achieve the conversion to my target framework which is `Tensorflow`, in fact i get the following error:
```
    RuntimeError: Resize coordinate_transformation_mode=half_pixel and  mode=nearest is not supported in Tensorflow.
```

Is there a way to convert a layer as above in some form that is compatible with tensorflow(lite)???

### Further information
I'm using:
```
tensorflow-addons            0.15.0   
tensorflow-gpu               2.7.0    
tensorflow-probability       0.15.0  
onnx                         1.10.2   
onnx-tf                      1.9.0    
onnxruntime                  1.10.0   
```
Already tried all opset but can't succed please help

**Comment by jcwchen** [comment]
Hi @Daveorr,
It seems like a common issue in onnx-tensorflow that Resize support is limited. Please check here: https://github.com/onnx/onnx-tensorflow/issues/632#issuecomment-653151089. I am not a converter expert, but I would you say perhaps you can try to convert your ONNX model with higher opset_version. (by MXnet converter or onnx.version_converter if applicable)

Still, it should be a question for the converter (onnx-tensorflow). I saw you have opened this issue in the converter repo a well, which is a better place to track this issue. Close here. Thanks.
