### ISSUE TITLE
which op of onnx  did pytorch  upsample Corresponding to?

### ISSUE THREAD

**Issue by cqray1990** [onnx/onnx#4029]
# Ask a Question

### Question
Explain your question here.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by cqray1990** [comment]
@jcwchen but when opset_vesion >= 10 ,unsample convert to onnx op,it wil increase l shape, slice op,but opset_version < 10,only upsamle op

**Comment by cqray1990** [comment]
so when the shape ,slice exists,it mat be failed to convert onnx to another mode such as ncnn
@jcwchen

**Comment by jcwchen** [comment]
If you bump into any error during converting PyTorch UpSample op to ONNX Resize op, please raise an issue in the converter repo (PyTorch-ONNX exporter is in PyTorch repo) and provide the model if possible to let converter team repo and investigate.

**Comment by jcwchen** [comment]
Close it since it should be a question for the exporter. Feel free to reopen it if you still have other ONNX questions.
