### ISSUE TITLE
optimization::GetAvailablePasses()、OptimizeFixed、Optimize， how to replace?

### ISSUE THREAD

**Issue by xinsuinizhuan** [onnx/onnx#4034]
older version have these function,but new version do not have.how to replace?

**Comment by jcwchen** [comment]
Hi @xinsuinizhuan,
ONNX main repo has [removed](https://github.com/onnx/onnx/pull/3288) onnx.optimizer since ONNX 1.9.0. There is another [repo](https://github.com/onnx/optimizer) maintaining the ONNX optimizer now. You can still follow the instruction there and use it.

**Comment by jcwchen** [comment]
Close it now since I believe you can still use these functions from another repo: https://github.com/onnx/optimizer. Feel free to reopen it if you still have other ONNX questions. Thanks.
