### ISSUE TITLE
Generating onnx model for single operators

### ISSUE THREAD

**Issue by LaVieEnRoseSMZ** [onnx/onnx#4036]
# Ask a Question

### Question
In the [Operator doc](https://github.com/onnx/onnx/blob/main/docs/Operators.md), there are specific explanations of each function and test case to verify the correctness of each operator. Therefore, I am wondering if this is a script that can generate all onnx models in the test case?

We actually want to collect these onnx models with a single operator to test the support of onnx operator in some inference libraries for different hardware.

**Comment by LaVieEnRoseSMZ** [comment]
It seems that you have mentioned in the (OnnxBackendTest doc](https://github.com/onnx/onnx/blob/main/docs/OnnxBackendTest.md), and it seems that I am asking for the **model test** part. And you mention that you have uploaded them into the cloud, but it seems that there is no download link on the page. So, can you provide me with the download link?

**Comment by xadupre** [comment]
You may find in this folder [onnx/backend/test/data/node](https://github.com/onnx/onnx/tree/main/onnx/backend/test/data/node) many unit tests to test a backaend. Each subfolder contains a model, the inputs and the expected outputs.

**Comment by LaVieEnRoseSMZ** [comment]
Thanks for your quick response! The folder does answer my question. However, I find that the graph initializer in the model is empty such as for all conv models. Therefore, it cannot be directly tested in some inference libraries such as TensorRT.  Is there any solution to solve this problem? 

Many thanks!

**Comment by snnn** [comment]
See: #4048 

By coincidence I had the same question.
