### ISSUE TITLE
build error using python2.7 in windows

### ISSUE THREAD

**Issue by holymeng** [onnx/onnx#404]
E:\DL\onnx-1.0\onnx/string_utils.h(16) : error C2143: syntax error : missing ','
 before '&'
E:\DL\onnx-1.0\onnx/string_utils.h(21) : error C2143: syntax error : missing ','
 before '...'
E:\DL\onnx-1.0\onnx/string_utils.h(22) : error C4430: missing type specifier - i
nt assumed. Note: C++ does not support default-int
E:\DL\onnx-1.0\onnx/string_utils.h(22) : error C2143: syntax error : missing ','
 before '&'
E:\DL\onnx-1.0\onnx/string_utils.h(32) : error C2912: explicit specialization; '
std::string onnx::MakeString(const std::string &)' is not a specialization of a
function template
E:\DL\onnx-1.0\onnx/string_utils.h(32) : fatal error C1903: unable to recover fr
om previous error(s); stopping compilation
error: command 'C:\\Users\\xiaolin.meng\\AppData\\Local\\Programs\\Common\\Micro
soft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit statu
s 2

when i build onnx using python2.7, errors occurs. it seems that the VS complier doesnot support C++ 11 new future, how can i solve this error. does anyone can help? thanks.

**Comment by bddppq** [comment]
@prasanthpul @linkerzhang Could you guys take a look?

**Comment by prasanthpul** [comment]
Are you able to use Python 3.x successfully? Any reason to stay with 2.7?
