### ISSUE TITLE
Support for SequenceProto in ONNX parser

### ISSUE THREAD

**Issue by jantonguirao** [onnx/onnx#4043]
# Ask a Question

### Question
I'd like to write ONNX models including sequence inputs/outputs. I haven't seen any examples in the code base, or support for it in parser.cc.
Are there any plans to support `SequenceProto` in ONNX parser?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
ONNX parser

- Is this issue related to a specific model?  
No

### Notes
N/A

**Comment by gramalingam** [comment]
Yes, thanks for bringing this up. The parser doesn't yet support sequence-types in the types. It needs to be added.
