### ISSUE TITLE
How can I user onnx for inference on Spark ?

### ISSUE THREAD

**Issue by BurnBury** [onnx/onnx#4047]
# Ask a Question

### Question

I tried to write a demo to run on Spark but it failed and it raised an exception "java.lang.UnsatisfiedLinkError: no onnxruntime in java.library.path" .

I was sure that the demo model is ok, because I tested  it on Windows.

### Further information

OS: Linux amd64
cmd:  
spark-submit --master yarn --deploy-mode client --files model_test.onnx --jars onnxruntime-1.10.0.jar --class OnnxDemo --queue=Spark --driver-memory 2G --executor-memory 6g --num-executors 80 --conf spark.default.parallelism=1000 --conf spark.driver.host=XX.XX.XX.XX --conf spark.driver.port=8882 --executor-cores 2 --executor-memory 2G demo.jar

### Notes
def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder().enableHiveSupport().appName("ONXTest").getOrCreate()

    val localPath = Paths.get("model_test.onnx").toAbsolutePath.toString

    import spark.implicits._
    val df = spark.sparkContext.parallelize(List.range(1, 100000).map(i => (i)).toSeq).toDF("id")

    df.foreachPartition(partition => {
      val env = OrtEnvironment.getEnvironment
      val session = env.createSession(localPath, new OrtSession.SessionOptions)

      partition.foreach(row => {
        val sourceArray = Array.ofDim[Float](1, 10)
        for (i <- 0 until 10) {
          sourceArray(0)(i) = i
        }

        val tensorArray = OnnxTensor.createTensor(env, sourceArray)
        val input = new util.HashMap[String, OnnxTensor]
        input.put("input", tensorArray)

        val res = session.run(input)
        val output = res.get("output")
        val value = output.get.getValue.asInstanceOf[Array[Array[Float]]]
        LOGGER.info(s"value: $value")
      })
    })
  }

**Comment by jornfranke** [comment]
Did you package the libraries in your Jar, ie creating an uberjar? https://www.baeldung.com/gradle-fat-jar
