### ISSUE TITLE
ONNX node tests need to make a distinguish on inputs and weights

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#4048]
# Feature Request
ONNX node tests need to make a distinguish on inputs and weights

### System information
ONNX version (you are using):
1.10.0

### What is the problem that this feature solves?

At first, in the early versions of ONNX we said all model initializer must be a subset of model inputs.  The current test framework was made at that time. Then I remember @gramalingam had a long discussion with me on this. Then he made a change and relaxed it(#1718).  Here I want to continue the discussion: when we implement an inference engine, it is important to know if a weight is constant, which may lead to totally different implementations. 

In C standard library, there is a function called "strstr", which locates a substring in a string. If you need to call the function multiple times and the substring is always the same, better algorithms exist.  The book, "Introduction to Algorithms", lists many of them. Like, Knuth–Morris–Pratt, which often shows up in coding interviews. But all the brilliant algorithms start from one point: the substring doesn't change.  Without this assumption, the plain strstr function works best and you can't find any thing better. Let's assume we need to add string matching operator to ONNX based on the signature of strstr, ones problem of ONNX is it only says the function(or op) has two inputs, it doesn't say which should or could be constant. It's not a problem when we see the full model, because we could just search initializer names in input names. It is not about strstr, the example can be extended to most ONNX operators. For example, Conv. The idea behind of Knuth–Morris–Pratt is very general. 

While @gramalingam helped us make a good move, ONNX's test framework was out of sights.  It's very often an inference engine prepack some weights. It can only be done when weights are constants. However, in ONNX node tests, all of them are not. 

### Describe the alternatives you have considered
A clear and concise description of any alternative solutions or features you've considered
It is possible to add an extra layer on the existing tests that blindly try all the combinations. If a test node has three inputs then there would be 8 possibilities. It will increasing test time greatly. I'm not sure if it is a good idea. In real scenarios, the first input of a Conv node is never constant.  So nobody would write optimizations for it.

### Describe the feature
Why is this feature necessary? What does it accomplish?

I think most inference engines need it.

### Will this influence the current api?
No

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

test

### Are you willing to contribute it (Y/N):
N

**Comment by gramalingam** [comment]
Hi @snnn : just to make sure I understand, I guess you are suggesting adding more test-cases, for specific (op, parameters) combinations, that have constant-values for those parameters (instead of external inputs)? 

In terms of the infrasructure, I assume that the "model" testcases already allow creation of such test-cases? (I mean the folder https://github.com/onnx/onnx/tree/main/onnx/backend/test/case/model ).

I agree these kind of test-cases seem useful, but they also seem specific to a particular type of bug. Not clear if it belongs to the ONNX spec. IMHO, it sounds like a nice-to-have feature, but not core or critical.

**Comment by snnn** [comment]
ONNX has thousands of nodes test, but only has about 10 model tests. 
Conv is one the most important op. TensorRT and xnnpack all require weights being constant. So they can't use these tests. I believe it generally impacts all ML inference engines. 
Most trainable operators have the issue.
