### ISSUE TITLE
ONNX does not work properly with Python 3.10 on Linux i686 environment

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4049]
# Bug Report

### Is the issue related to model conversion?
No
### Describe the bug
Please note that ONNX does not work properly with Python 3.10 on Linux i686 environment. With the Python 3.10 i686 ONNX wheel, `onnx/backend/test/cmd_tools.py generate-data` somehow take forever. It might be because NumPy does not support Python 3.10+i686.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): manylinux2014-i686
- ONNX version (*e.g. 1.7*): 1.11.0 (latest main branch)
- Python version: 3.10

### Reproduction instructions
Follow the steps [here](https://github.com/onnx/onnx/blob/main/.github/workflows/release_linux_i686.yml) to build ONNX. Then using `onnx/backend/test/cmd_tools.py generate-data` will take forever.

### Expected behavior
`onnx/backend/test/cmd_tools.py generate-data` should generate data shortly.

**Comment by garymm** [comment]
Next steps:
* See if we can get PyPi or Conda download stats for i686 wheels
* Propose dropping i686 at operator SIG meeting and on slack and mailing lists

**Comment by jcwchen** [comment]
Surprisingly it seems no one downloaded ONNX i686 package in the past 30 days. Here is the result:
| name | cpu | download_count |
| ------------- | ------------- | ------------- |
| Linux | x86_64  | 1383017  |
| Linux | aarch64  | 2642  |

I chose 30 days because I don't have enough budget to request more results from Google BigQuery. Still, I think it is strong enough to prove we can deprecate i686 packages in next ONNX release due to very low usage. I will announce it in meetings and slack and see whether anyone has objections or concerns.

P.S., I used the following SQL to query from [public PyPI download statistics dataset](https://console.cloud.google.com/bigquery?p=bigquery-public-data&d=pypi&page=dataset).
```
SELECT
  details.cpu,
  COUNT(*) as download_count,
FROM `bigquery-public-data.pypi.file_downloads`
WHERE file.project = 'onnx'
  AND details.system.name = 'Linux'
  AND DATE(timestamp)
    BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY)
    AND CURRENT_DATE()
GROUP BY
  details.cpu
ORDER BY
  download_count DESC
```
