### ISSUE TITLE
Gemm requires (MxK), (KxN) inputs but no reshape are inserted in onnx models.

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#405]
I facing a problem when working with "bvlc_alexnet/model.pb" from [here](https://github.com/onnx/models/tree/master/bvlc_alexnet)

Its include a *Gemm* node with 3 inputs:
- The output of the previous node : pool_5, its shape is : [1, 256, 6, 6]
- A weights tensor presents into the initializers. its shape is : [4096, 9216]
- A bias tensor presents into initializers. its shape is : [4096]

The attrs of the node are : 
- Broadcasting = 1 : it's ok to broadcast the bias tensor.
- transB = 1 : it's ok to transpose the weights tensor.

In the [doc](https://github.com/onnx/onnx/blob/master/docs/Operators.md#gemm) we can read : 

> where input tensor A has dimension (M X K) , input tensor B has dimension (K X N), input tensor C and output tensor Y have dimension (M X N)

So the tensor B will have shape : [9216, 4096] after being transposed.
Si the input A (the output of the previous node) MUST have the shape : [1, 256\*6\*6] = [1, 9216]
This will produce a tensor of shape [1, 4096] which we can add to the bias tensor (input C).

According to me, a reshape is missing between the pool_5 node and the Gemm node.

**Comment by prasanthpul** [comment]
@bddppq are you familiar with this model?

**Comment by LucasMahieu** [comment]
seems to be addressed here : https://github.com/onnx/onnx/issues/724

**Comment by houseroad** [comment]
@LucasMahieu could you try Please try https://s3.amazonaws.com/download.onnx/models/opset_6/bvlc_alexnet.tar.gz?

If you still have the problem, please let me know.

**Comment by houseroad** [comment]
Fixed.
