### ISSUE TITLE
Onnx model consumes huge CPU memory

### ISSUE THREAD

**Issue by avallllll** [onnx/onnx#4050]
# Ask a Question

### Question
We used Onnx 1.9.0 to convert PyTorch model to Onnx model. However, the Onnx model consumes huge CPU memory (>11G) and we have to call GC to reduce the memory usage. Any known issue that could cause Onnx model use huge CPU memory? We use onnx.runtime 1.9.0.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
Transformer model

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @avallllll,
It seems more like a question for ONNXRuntime. Could you please raise this issue in https://github.com/Microsoft/onnxruntime?

**Comment by jcwchen** [comment]
Please track this issue there. Close here now. Feel free to reopen it if you have other ONNX questions. Thanks.
