### ISSUE TITLE
very slow in inference

### ISSUE THREAD

**Issue by meloxuan** [onnx/onnx#4052]
Hello, I am using torch. Onnx. Export to convert the trained PTH model to ONnx, but I find that the reasoning time is obviously slow，thanks

**Comment by jcwchen** [comment]
Hi @meloxuan,
Could you please provide more details? For instance, which backend did you use, what kind of model did you run, did you run it with CPU or GPU, and what's your environment. Thanks.

**Comment by meloxuan** [comment]
> Hi @meloxuan, Could you please provide more details? For instance, which backend did you use, what kind of model did you run, did you run it with CPU or GPU, and what's your environment. Thanks.

Thank you for your reply, the onxx is extremely slow in inference, up to 1.2s, as a comparison, using the original .pth file is only 60ms, I have shared PyTorch2Onnx code, and ONNX model. looking forward to your reply.
PyTorch2Onnx: https://drive.google.com/file/d/1LIJAtZtIemf5lTC5fApmOZF0Dr6qHnkB/view?usp=sharing
ONNX model: https://drive.google.com/file/d/1fhqnh8qNL7wnXRaq1byQK_87TWDwjES2/view?usp=sharing

**Comment by jcwchen** [comment]
I saw you has opened an issue in ONNXRuntime repo, which is a better place to track this issue. Close here now. Please reopen it if you still have other ONNX questions. Thanks
