### ISSUE TITLE
Ragged Tensors in ONNX

### ISSUE THREAD

**Issue by naor2013** [onnx/onnx#4057]
# Ask a Question

### Question
Is there a current or planned support for Ragged tensors for inference using ONNX?

The use case for this is when you want to make a batch of inputs, each input with a different shape.
If there is no support for Ragged Tensors, you'll have to pad each input with zeros to match for the longest input, so they'll be the same size.
This means the model will have to process the zeros as if they were actual data which can impact performance.

**Comment by WilliamTambellini** [comment]
cf
https://www.tensorflow.org/guide/ragged_tensor

**Comment by vincentvic** [comment]
Hello,
Did you find a solution @naor2013 ?
Thank you
