### ISSUE TITLE
Slack URL is broken

### ISSUE THREAD

**Issue by wangxiyuan** [onnx/onnx#4058]
https://slack.lfai.foundation/ is broken. Is there any way to join the slack channel?

**Comment by jcwchen** [comment]
Hi @wangxiyuan,
Thank you for catching this broken url. Could you please try this url instead: https://join.slack.com/t/lfaifoundation/shared_invite/zt-o65errpw-gMTbwNr7FnNbVXNVFkmyNA. I am not quite sure the url (https://slack.lfai.foundation/) is down temporally or for good... I will update the url if needed.

**Comment by wangxiyuan** [comment]
@jcwchen Thanks!! The invate URL works.

Should I close the issue or wait for the `https://slack.lfai.foundation/` works?

**Comment by jcwchen** [comment]
I would say let's keep it open to reminder others as well. I will monitor the old URL. If the URL revives, I will close this issue then. Thank you again for catching this!

**Comment by jcwchen** [comment]
I think the old URL (https://slack.lfai.foundation/) is broken forever and we need to update it. @prasanthpul would you like to submit a PR to fix it? Otherwise I can pick this up. Thanks!

**Comment by divyanshugit** [comment]
@jcwchen the link is still broken. Can I submit a PR to fix it?

**Comment by jcwchen** [comment]
> @jcwchen the link is still broken over [here.](https://github.com/onnx/onnx/blob/main/community/sigs.md) Can I submit a PR to fix it?

Sure. Thanks for the contribution.
