### ISSUE TITLE
Enable Stale Bot on onnx/onnx repo

### ISSUE THREAD

**Issue by garymm** [onnx/onnx#4063]
This repo has many issues and PRs that have not received attention and may no longer be relevant. [Stale](https://github.com/probot/stale/blob/master/README.md) can automatically check if issues still matter to humans, and close those that don't.
Filing this issue to collect feedback about this proposal and then track implementing it.

**Comment by prasanthpul** [comment]
Steering Committee discussed and agreed this sounds good and had the following requests:
1) staleness should be defined as 1 year since last activity on the issue.
2) please share stats/distribution of current age of issues

After these, I can help you set it up on the repo.

**Comment by garymm** [comment]
As of now, there are 445 open issues, of those 280 haven't been updated in a year.
I'll send a PR to configure the bot.

**Comment by garymm** [comment]
@prasanthpul can you please enable the app on the repo? <https://github.com/apps/stale>

**Comment by jcwchen** [comment]
Thanks for introducing the Stale Bot. It seems working diligently now. Shall we close this issue?

**Comment by garymm** [comment]
[Example](https://github.com/onnx/onnx/issues/2273#issuecomment-1081231079)
