### ISSUE TITLE
Proposal and ideas of shape inference with `dim_expr`

### ISSUE THREAD

**Issue by xuzijian629** [onnx/onnx#4064]
Hello, ONNX community. Today, I want to share an idea for better shape inference.

Recently, I'm so motivated to improve shape inference where dimensions are not always int64_t values, but also contain dim_params. Ideally, my goal is to infer all the cases except for those we don't know the actual values until we execute the model (like, `NonZero` operator).

To partially achieve this goal, I've improved the shape inference with data propagation for some ops (see https://github.com/onnx/onnx/pulls/xuzijian629).

However, there are many models where we cannot infer the shapes even if we are going to improve current inference with `dim_values` and `dim_params`.

One common case is `Reshape`. Reshaping tensors with dim_params is a very common practice.
In #3785 (I'm looking forward to feedbacks to this PR, too!), I supported shape inference like

```
x: ("a", "b", 2, 3)
x.reshape("a", -1, 6)
```

and inferred the -1 dim by "b".

However, we cannot currently support the case like

```
x: ("a", "b", 2, 3)
x.reshape(-1, 6).reshape("a", -1, 6)
```

because we'll get an unknown dimension (which should actually be "a * b") after the first reshape.

# Proposal
I would like to propose shape inference with `dim_expr` to support the above case.
In addition to `dim_value` and `dim_params`, I introduce a new member that holds *how the dimension was computed*.

Basically, the idea and the implementation can be summarized as follows.

* A `Dimension` class object has either **one** of `dim_value`, `dim_params` or `dim_expr`.
* Internally, `dim_expr` is something like `std::pair<DimOpType, std::vector<Dimension*>>`, which forms a tree by recursion.
* We implement operator overloads to `Dimension` class. In the overload, we compute the `dim_value` or `dim_param` if possible. Otherwise, we store the results in `dim_expr`.

I think a similar thing is done in https://dl.acm.org/doi/abs/10.1145/3394450.3397465

## Remarks
* We know we don't always want exact expression like `(unk__1 * (unk__2 + unk__3) + unk__4) * unk__5 ...`.
* It will be nice if we replace `dim_expr` with `unk__` at the end, if the expression contains some unknown dimension.
* For example, we will have dimensions like `n + 5` or `3 * n` at the end, but won't have `n + unk__1` or `3 + unk__2`.

## Pros
* Shape inference will be much stronger.
* By the operator overloads, we won't have to write complicated `if/else` in `**/defs.cc`.

## Cons
* To implement this, ONNX ir version must be updated.
* We may need to modify soooo many existing inference functions.

## Background
(This section is my personal feelings about the idea)
I think this feature will be essential anyway in near future. Neural networks have become more and more realistic way to solve various problems, and there are growing demands for optimizing those models. Models written by non-experts could be slow or not efficient on target processors. At such situations, model compiler will play an important role. In model optimization, tensor shapes are the most important information. They give information how long each operator takes or how much memory it uses. Since ONNX would be already the de facto standard in model compilers, I think this feature will be welcomed.

**Comment by snnn** [comment]
But what's the value of it?  The expression needs be evaluated at some time, then what's the difference between evaluating such an expr than executing a piece of C/C++ shape-inference code? For example, if the H or W dimension of the input is unknown, can you express the output dimensions by using such expressions? No.  But if I use a  C/C++ function, it can.

**Comment by xuzijian629** [comment]
Thank you for the comments!
Well, I'm thinking of implementing this for two main purposes.

First, support shape inference like 
```
x: ("a", "b", 2, 3)
x.reshape(-1, 6).reshape("a", -1, 6)
```

In this case, they have actual values. This case may contribute to your usage, too.

The second case is for model optimization. In model optimization, we often want to know how much time it would take (or how much memory it would use) to execute a certain operator with certain inputs. When model inputs are static, we can know the results by simply running shape inference, but I'm now interested in the dynamic case, say, how the memory consumption is related to H or W.

Actually I feel that the second case is something too ideal.
At first, I just want to handle the first case, and I also came up with a new situation where the dim_expr will be useful. That's the second case.

**Comment by snnn** [comment]
For example, like this: 

![image](https://user-images.githubusercontent.com/856316/159407487-8bcc32ce-441d-43c4-95d9-2c151cd19c4f.png)

The left-most dimension of the output could be inferred to use the variable as the input.  But how does it benefit a runtime engine? I couldn't find much. If an engine wants to use this information, it needs a lightweight scripting engine that understands variables/constants/functions/naming scope. For me, I think it's very heavy.  Why don't just operate numbers instead of symbolic names? I only know very a few ML engines. Welcome to let us know what you think.

**Comment by snnn** [comment]
Next, if we take Conv as the example. First, let's assume the input is 4D in NCHW format. N=1, C=3. But H and W are unknown. 
So,  let's consider four cases:
1. All input shapes are known. Then output shape is unknown too.
2. Padding type = SAME and stride = 1. In this case, output H/W would be the same as the input H/W.
3. Padding type = SAME and stride != 1. In this case, output H/W can be expressed as simple arithmetic expressions as you suggested. 
4. Padding type != SAME, then it is rather complicated.

It means, your runtime will need to have 4 different levels support of static/dynamic shaping. Does it worth?

**Comment by xuzijian629** [comment]
I think we are talking about different things.. You say that inferring `dim_expr` does not contribute much to runtimes, and I totally agree with that.
I'm thinking of using `dim_expr` not for runtimes, but for compilers.

Given a onnx model, compilers optimize the graph and generate a new computation graph. In optimization, compilers will insert new nodes, or erase nodes to simplify computation.

Consider the following example (I cite from yours).
```
x: (unk__0, 5, 5, 1)
y = x.reshape(-1, 1, 5, 5).reshape(-1, 5, 5, 1)
```

In the above example, we can simplify the computation as `y = x` if we can correctly infer the shape. Then we can erase the unnecessary reshape operator from the computation graph to produce simpler computation graph (again, note that we are not talking about runtime!).

**Comment by xuzijian629** [comment]
For compiler optimization, we can temporarily fix `dim_value`S and run shape inference (after optimization, we remove them). This way is much simpler and can be accomplished with current implementation.

**Comment by xuzijian629** [comment]
I close this issue because it’s not that important for me now. Please reopen this if needed. Thanks.
