### ISSUE TITLE
Problems with predictions on MacBook Air with M1 chip in Java project based on Maven

### ISSUE THREAD

**Issue by pwittchen** [onnx/onnx#4067]
I have the following problem:

I'm using ONNX runtime in version 1.8.1 in the Java project with Maven.

When I invoke:

```java
final OrtEnvironment environment = OrtEnvironment.getEnvironment();
```

then I get an error:

```
java.lang.NoClassDefFoundError: Could not initialize class ai.onnxruntime.OrtEnvironment
```

and I cannot perform prediction.

It works fine on Linux on different distros, but I have problems with executing it on MacBook Air with M1 chip.

**Comment by jcwchen** [comment]
Hi @pwittchen,
It seems like a question for ONNXRuntime. Could you please raise this issue [there](https://github.com/Microsoft/onnxruntime) to get the best help from the Runtime experts? Thanks.

**Comment by pwittchen** [comment]
Hi @jcwchen,

Thanks for the reply. I raised an issue here https://github.com/microsoft/onnxruntime/issues/10874.

Regards,
Piotr
