### ISSUE TITLE
Error Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice_1/begin:0' of node: name: Add__1005 OpType: Add

### ISSUE THREAD

**Issue by mengniwang95** [onnx/onnx#4070]
# Ask a Question

### Question
Hi, I can not run this quantized model successfully with 'Error Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice_1/begin:0' of node: name: Add__1005 OpType: Add'
But this node is not in this model.

```python
model = onnx.load(model_path)
session = ort.InferenceSession(model.SerializeToString(), None)
```
[order.zip](https://github.com/onnx/onnx/files/8304947/order.zip)

**Comment by jcwchen** [comment]
Hi @mengniwang95,
I think "Add__1005" does exist in the third subgraph. Please note that it is not in the main graph. Here is the view from Netron:
![image](https://user-images.githubusercontent.com/14194980/159041605-6da8332f-6438-4efa-8cf4-71be6856210e.png)

**Comment by mengniwang95** [comment]
Thanks

**Comment by gcunhase** [comment]
@jcwchen what's the solution for this issue?
