### ISSUE TITLE
Exporting the operator _thnn_fused_gru_cell to ONNX opset version 11 is not supported.

### ISSUE THREAD

**Issue by tsnguyen05** [onnx/onnx#4073]
# Feature Request

### System information
ONNX version (you are using): 11

### What is the problem that this feature solves?
Exporting the operator _thnn_fused_gru_cell to ONNX opset version 11 is not supported.

### Describe the alternatives you have considered
I tried to use version 12, but it seems like it did not solve an issue

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 11

### Are you willing to contribute it (Y/N): maybe but not sure because I am still a beginner

**Comment by jcwchen** [comment]
Hi @tsnguyen05,
Yes I think it's still not supported by the converter (PyTorch-ONNX exporter): https://github.com/pytorch/pytorch/issues/51553.

**Comment by tsnguyen05** [comment]
Hello @jcwchen, thank you for pointing this out! I could not find this post before, so I decided to ask question. Because of this, this issue is solved and can be closed. Thank you for your help!

**Comment by wangchangquan** [comment]
> Hello @jcwchen, thank you for pointing this out! I could not find this post before, so I decided to ask question. Because of this, this issue is solved and can be closed. Thank you for your help!

hello , can you tell me  how to solve the problem? I encounter the same.

**Comment by jcwchen** [comment]
IIUC, _thnn_fused_gru_cell is not supported by the PyTorch-ONNX exporter yet. Please this issue there (PyTorch#51553).
