### ISSUE TITLE
Tensor shape description on pb level

### ISSUE THREAD

**Issue by Hiroshi123** [onnx/onnx#408]
We are implementing tensorflow to onnx converter(https://github.com/LeapMind/tf_onnx) and its backend (which is private) as business.

So far, we are following your documentation as much as we could. 

One thing which is difficult to be interpreted is how you identify shapes of a tensor, such as 
(Batch,Channel,Width,Height).

Most of operators do not need comprehensive concrete shape information as their implementation are independent from it.

However, there are some operations such as Conv,Maxpool where you must define explicitly them.
Referring their documentation, it says order should be (Batch,Channel,Width,Height).

But, the optimal order in terms of execution speed is different from target architecture.

Wouldn't it be perhaps better if you could set its overall tensor shape just under graph proto 
so you do not need any transpose function before conv and maxpool without fixing orders in any individual operations?

**Comment by tjingrant** [comment]
Please follow up [here](https://github.com/onnx/onnx/issues/406). This issue is trying to address the same exact issue you see.

**Comment by Hiroshi123** [comment]
I missed it, sure. I will close a current issue.
