### ISSUE TITLE
Selu computes error while set alpha as negative value

### ISSUE THREAD

**Issue by pigeonsoup** [onnx/onnx#4081]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug
I am testing onnx.Selu op and I found that the param alpha and gamma is changable. When I set alpha to a negative value, the compute results is not equal to the result computed by formula. Here is 
input value: -12.33922195
alpha: -2
gamma: 3
output value: 0
output value supposed to be: 5.999973774

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 18.04
- ONNX version (*e.g. 1.7*):  1.7
- Python version:3.7.8

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
node = onnx.helper.make_node(
            'Selu',
            inputs=['x'],
            outputs=['y'],
            alpha=-2.0,
            gamma=3.0
        )
```
- Attach the ONNX model to the issue (where applicable)

### Expected behavior
As above

**Comment by jcwchen** [comment]
Hi @pigeonsoup,
Which Runtime did you use to compute the result?

**Comment by pigeonsoup** [comment]
Hi @jcwchen
It's onnxruntime. Try the following code please. 
```python
import onnx
from onnx import helper
from onnx import AttributeProto, TensorProto, GraphProto
import numpy as np
import onnxruntime as ort
 
x = np.random.randn(1, 2, 3, 4).astype(np.float32)
print(x)
 
# Create one input (ValueInfoProto)
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 2, 3, 4])
 
# Create one output (ValueInfoProto)
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 2, 3, 4])

# Create a node (NodeProto)
node_def = helper.make_node(
    'Selu', # op type
    inputs=['X'], # inputs
    outputs=['Y'], # outputs
    alpha=-2.0,
    gamma=3.0,
)
 
# Create the graph (GraphProto)
graph_def = helper.make_graph(
    [node_def],
    "onnx-exampresult",
    [X],
    [Y],
)
 
# Create the model (ModelProto)
model_def = helper.make_model(graph_def,
                              producer_name='onnx',
                              opset_imports = [helper.make_opsetid("",13)],
                              ir_version = 7)
 
onnx.checker.check_model(model_def)
print('The model is checked!')
 
onnx.save(model_def,"selu_default.onnx")
session = ort.InferenceSession("selu_default.onnx")
pred_onx = session.run(None,{"X":x})[0]
print(pred_onx)
print("output.shape=", pred_onx.shape)
```

**Comment by jcwchen** [comment]
Thanks for providing the code to repro. Since the Runtime logic was implemented in ONNXRuntime, could you please raise this issue there to get the best help from the Runtime experts?

**Comment by pigeonsoup** [comment]
Thanks for your help, I found the same [error](https://github.com/microsoft/onnxruntime/issues/10726) in ONNXRuntime.
