### ISSUE TITLE
quantization aware training

### ISSUE THREAD

**Issue by wpeak58** [onnx/onnx#4082]
Hi. 
Can the quantized model of pytorch be convert to onnx?
thanks.

**Comment by jcwchen** [comment]
Hi @wpeak58,
It should be a question for the converter (torch.onnx.export). IIUC, the PyTorch-ONNX exporter now supports some quantized models, but not all of them: https://discuss.pytorch.org/t/onnx-export-of-quantized-model/76884/20. More supports will be brought in the future.
