### ISSUE TITLE
ONNX support LayerNorm and GroupNorm 

### ISSUE THREAD

**Issue by henry861114** [onnx/onnx#4085]
# Feature Request

### System information
v1.10.1

### What is the problem that this feature solves?
No

### Describe the alternatives you have considered
Using many onnx operator to replace LayerNorm or GroupNorm，but maybe it is not good solution. 

### Describe the feature
ONNX support LayerNorm and GroupNorm, and not need to split little ops to support LayerNorm or GroupNorm.

### Will this influence the current api?
No

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
operators

### Are you willing to contribute it (Y/N):
N

### Notes
Any additional information

**Comment by jcwchen** [comment]
HI @henry861114,
- Regarding to LayerNorm, https://github.com/onnx/onnx/pull/4076 this fresh PR should meet your requirement. Feel free to review it.
- For GroupNorm, IIUC, currently there is no plan to add it to ONNX spec: https://github.com/onnx/onnx/issues/2843, but at least PyTorch-ONNX exporter is able to convert it from PyTorch to ONNX: https://github.com/pytorch/pytorch/pull/27071. Still, anyone interested in proposing a new function op GroupNorm you are welcome to contribute!

**Comment by justinchuby** [comment]
Looks like GroupNorm is a good candidate as a function
