### ISSUE TITLE
Inference result is different between Pytorch and ONNX model

### ISSUE THREAD

**Issue by YsYusaito** [onnx/onnx#4087]
# Problem
Hi,

I converted Pytorch model to ONNX model.
However, output is different between two models like below.
![inference_result](https://user-images.githubusercontent.com/80863816/159861341-e20aafec-cbe6-4847-9b55-95855b25ef59.PNG)

# inference environment
## Pytorch
・python 3.7.11
・pytorch 1.6.0
・torchvision 0.7.0
・cuda tool kit 10.1
・numpy 1.21.5
・pillow 8.4.0

## ONNX
・onnxruntime-win-x64-gpu-1.4.0
・Visual studio 2017
・Cuda compilation tools, release 10.1, V10.1.243

# Network of model
![multi_inout_network](https://user-images.githubusercontent.com/80863816/159861323-83ac4ec8-a2cc-437e-b3f8-a96db441427c.PNG)
[detail information of my model](https://github.com/YsYusaito/Multi-in-out-model)

# Script for converting model from Pytorch to ONNX
```
import torch
import torch.onnx as onnx
import torchvision.models as models
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self, pretrained):
        # スーパークラス（Module クラス）の初期化メソッドを実行 
        super().__init__() 
        
        self.pretrained = pretrained
        
        self.pretrained.fc = nn.Linear(2048, 128)
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(256, 128)
        self.fc_y1 = nn.Linear(128*2, 64)
        self.fc_y1_1 = nn.Linear(64, 32)
        self.fc_y1_2 = nn.Linear(32, 16)
        self.fc_y1_3 = nn.Linear(16, 32)
        self.fc_y1_4 = nn.Linear(32, 16)
        self.fc_y1_5 = nn.Linear(16, 8)
        self.fc_y1_6 = nn.Linear(8, 2)
        
        self.fc_y2 = nn.Linear(128*2, 64)
        self.fc_y2_1 = nn.Linear(64, 32)
        self.fc_y2_2 = nn.Linear(32, 16)
        self.fc_y2_3 = nn.Linear(16, 32)
        self.fc_y2_4 = nn.Linear(32, 16)
        self.fc_y2_5 = nn.Linear(16, 8)
        self.fc_y2_6 = nn.Linear(8, 2)
        
        self.bn_256 = nn.BatchNorm1d(num_features = 256)
        self.bn_128 = nn.BatchNorm1d(num_features = 128)
        self.bn_64 = nn.BatchNorm1d(num_features = 64)
        self.bn_32 = nn.BatchNorm1d(num_features = 32)
        self.bn_16 = nn.BatchNorm1d(num_features = 16)
        self.bn_8 = nn.BatchNorm1d(num_features = 8)

    def forward(self, x0, x1, x2, x3): # 入力から出力を計算するメソッドを定義
        x0 = self.pretrained(x0)
        x1 = F.relu(self.bn_128(self.fc1(x1)))
        x2 = F.relu(self.bn_128(self.fc2(x2)))
        x3 = F.relu(self.bn_128(self.fc3(x3)))
        
        x123 = x1 + x2 + x3
        x = torch.cat((x0, x123), 1)
        
        y0 = F.relu(self.bn_64(self.fc_y1(x)))
        y0 = F.relu(self.bn_32(self.fc_y1_1(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_2(y0)))
        y0 = F.relu(self.bn_32(self.fc_y1_3(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_4(y0)))
        y0 = F.relu(self.bn_8(self.fc_y1_5(y0)))
        y0 = self.fc_y1_6(y0)
        
        y1 = F.relu(self.bn_64(self.fc_y2(x)))
        y1 = F.relu(self.bn_32(self.fc_y2_1(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_2(y1)))
        y1 = F.relu(self.bn_32(self.fc_y2_3(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_4(y1)))
        y1 = F.relu(self.bn_8(self.fc_y2_5(y1)))
        y1 = self.fc_y2_6(y1)
        
        return y0, y1


resnet = models.resnet50(pretrained=True)

model = Net(resnet)
model.load_state_dict(torch.load('path to Pytorch model'))
model.eval()


input_image = torch.randn(1,3,224,224, requires_grad=True)
input_hist_R = torch.randn(1,256, requires_grad=True)
input_hist_G = torch.randn(1,256, requires_grad=True)
input_hist_B = torch.randn(1,256, requires_grad=True)

input_tuple = (input_image,input_hist_R,input_hist_G,input_hist_B)
input_names = [ "input.1","input.154","input.156","input.158" ]
output_names = [ "593","612" ]

onnx.export(model, input_tuple, 'multi_inout.onnx',export_params=True,opset_version=12,do_constant_folding=True,input_names=input_names, output_names=output_names)
```

# Environment for converting model
・python 3.7.11
・pytorch 1.6.0
・torchvision 0.7.0
・numpy 1.21.5
・pillow 8.4.0

Is there something wrong with the way of the model conversion?
If necessary, I can share inference scripts and models via e-mail.

Please help…

**Comment by YsYusaito** [comment]
Hi, @jcwchen 

- Have you compared the original PyTorch model and converted ONNX model?
  → As illustrated in the "Problem" section of this issue, I compared the inference results of original Pytorch model and converted ONNX model.

- Also you can use "onnx.checker.check_model(your_onnx_model, True)" to validate the converted ONNX model. If the converted ONNX model looks good to you and it passes onnx.checker.
 → I added "onnx.checker.check_model(your_onnx_model, True)" and ran the script. However, no error occured.

```
import torch
import torch.onnx as onnx
import torchvision.models as models
import torch.nn as nn
import torch.nn.functional as F
from onnx import checker

class Net(nn.Module):

    def __init__(self, pretrained):
        # スーパークラス（Module クラス）の初期化メソッドを実行 
        super().__init__() 
        
        self.pretrained = pretrained
        
        self.pretrained.fc = nn.Linear(2048, 128)
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(256, 128)
        self.fc_y1 = nn.Linear(128*2, 64)
        self.fc_y1_1 = nn.Linear(64, 32)
        self.fc_y1_2 = nn.Linear(32, 16)
        self.fc_y1_3 = nn.Linear(16, 32)
        self.fc_y1_4 = nn.Linear(32, 16)
        self.fc_y1_5 = nn.Linear(16, 8)
        self.fc_y1_6 = nn.Linear(8, 2)
        
        self.fc_y2 = nn.Linear(128*2, 64)
        self.fc_y2_1 = nn.Linear(64, 32)
        self.fc_y2_2 = nn.Linear(32, 16)
        self.fc_y2_3 = nn.Linear(16, 32)
        self.fc_y2_4 = nn.Linear(32, 16)
        self.fc_y2_5 = nn.Linear(16, 8)
        self.fc_y2_6 = nn.Linear(8, 2)
        
        self.bn_256 = nn.BatchNorm1d(num_features = 256)
        self.bn_128 = nn.BatchNorm1d(num_features = 128)
        self.bn_64 = nn.BatchNorm1d(num_features = 64)
        self.bn_32 = nn.BatchNorm1d(num_features = 32)
        self.bn_16 = nn.BatchNorm1d(num_features = 16)
        self.bn_8 = nn.BatchNorm1d(num_features = 8)

    def forward(self, x0, x1, x2, x3): # 入力から出力を計算するメソッドを定義
        x0 = self.pretrained(x0)
        x1 = F.relu(self.bn_128(self.fc1(x1)))
        x2 = F.relu(self.bn_128(self.fc2(x2)))
        x3 = F.relu(self.bn_128(self.fc3(x3)))
        
        x123 = x1 + x2 + x3
        x = torch.cat((x0, x123), 1)
        
        y0 = F.relu(self.bn_64(self.fc_y1(x)))
        y0 = F.relu(self.bn_32(self.fc_y1_1(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_2(y0)))
        y0 = F.relu(self.bn_32(self.fc_y1_3(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_4(y0)))
        y0 = F.relu(self.bn_8(self.fc_y1_5(y0)))
        y0 = self.fc_y1_6(y0)
        
        y1 = F.relu(self.bn_64(self.fc_y2(x)))
        y1 = F.relu(self.bn_32(self.fc_y2_1(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_2(y1)))
        y1 = F.relu(self.bn_32(self.fc_y2_3(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_4(y1)))
        y1 = F.relu(self.bn_8(self.fc_y2_5(y1)))
        y1 = self.fc_y2_6(y1)
        
        return y0, y1


resnet = models.resnet50(pretrained=True)

model = Net(resnet)
# model.load_state_dict(torch.load('C:\\Users\\10087826\\Documents\\multi_inout_onnx\\multi_inout_weight.pth', map_location='cpu'))
model.load_state_dict(torch.load('C:\\Users\\10087826\\Documents\\multi_inout_onnx\\multi_inout_weight.pth'))
model.eval()

# input_image = torch.zeros((1,3,224,224))
# input_hist_R = torch.zeros((1,256))
# input_hist_G = torch.zeros((1,256))
# input_hist_B = torch.zeros((1,256))

input_image = torch.randn(1,3,224,224, requires_grad=True)
input_hist_R = torch.randn(1,256, requires_grad=True)
input_hist_G = torch.randn(1,256, requires_grad=True)
input_hist_B = torch.randn(1,256, requires_grad=True)

input_tuple = (input_image,input_hist_R,input_hist_G,input_hist_B)
input_names = [ "input.1","input.154","input.156","input.158" ]
output_names = [ "593","612" ]

# onnx.export(model, input_tuple, 'multi_inout.onnx', verbose=False, input_names=input_names, output_names=output_names, export_params=True)
onnx.export(model, input_tuple, 'multi_inout.onnx',export_params=True,opset_version=12,do_constant_folding=True,input_names=input_names, output_names=output_names)

checker.check_model('multi_inout.onnx', True)
```

- This inference difference issue might be caused by either the converter (PyTorch-ONNX exporter) or the Runtime (ONNXRuntime).
 → Actually, I have converted ONNX model into OpenVINO. Then, I have run OpenVINO model in OpenVINO frame work.
The inference results are below(OpenVINO's inference result is the red line). From these results, we can see that there is virtually no difference between the inference results of ONNX model and OpenVINO mdoel. So I think there is no problem in ONNX runtime but there is a problem in ONNX model.

![inference results pth onnx vino](https://user-images.githubusercontent.com/80863816/160036236-e5e86917-2a95-48a1-8550-f90f414540e6.PNG)

- If the converted ONNX model looks abnormal, you can raise this issue in the converter repo (under PyTorch) to get assistance from the converter team.
 → Should I have to post an issue here??([github of Pytorch](https://github.com/pytorch/pytorch/issues))
     By the way, I have already post an issue in [Official Pytorch website](https://discuss.pytorch.org/t/inference-result-is-different-between-pytorch-and-onnx-model/147228/2). However, I was recommend to inquire on the ONNX github...
<img width="608" alt="pytorch question" src="https://user-images.githubusercontent.com/80863816/160037064-1c16e0a1-32d8-4cb9-928c-300054dcbdf9.PNG">

**Comment by jcwchen** [comment]
Hi @YsYusaito,
Thanks so much for providing the details.

> Actually, I have converted ONNX model into OpenVINO. Then, I have run OpenVINO model in OpenVINO frame work.
The inference results are below(OpenVINO's inference result is the red line). From these results, we can see that there is virtually no difference between the inference results of ONNX model and OpenVINO model. So I think there is no problem in ONNX runtime but there is a problem in ONNX model.

Yes I agreed in that case it's more like a converter issue (ONNX model itself is incorrect) since both Runtimes produce the same result. Besides, I saw you said from [here](https://discuss.pytorch.org/t/inference-result-is-different-between-pytorch-and-onnx-model/147228/3):
> I used opset 12.
If I used opset 11, the inference result didn’t change.

It seems like some behaviors changed in the converter (torch.onnx.export) with different opset_versions. I saw you open an issue in the [converter repo](https://github.com/pytorch/pytorch/issues/74732), which is a better place to track this issue. Please mention that opset 11 can work normally, but opset 12 cannot. It would be an important fact for the converter experts to debug. Close here now. Feel free to reopen it if you have other ONNX questions.
