### ISSUE TITLE
high memory occupy when quantization with big calibrate dataset

### ISSUE THREAD

**Issue by ArtyZe** [onnx/onnx#4091]
# Ask a Question
I notice that quantization output collect code is like:
![image](https://user-images.githubusercontent.com/32027268/160101131-2d1b3d01-f19b-4716-9229-b0ee9da271a6.png)
but if my model is complex with many tensors and my calibrate dataset chanced to be big, memory with runs out,
why designed like that instead of update histogram each step

**Comment by jcwchen** [comment]
Hi @ArtyZe,
I think you are talking about the code [here](https://github.com/microsoft/onnxruntime/blob/fe6ab719f3bb389c7368c6be28c1b38884f603cb/onnxruntime/python/tools/quantization/calibrate.py#L219)? It's should be a question for the [ONNXRuntime Quantization Tool](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization). Could you please raise this issue there? Thanks.

**Comment by jcwchen** [comment]
Close here now since this issue has been opened in ONNXRuntime, which is a better place to track it. Please reopen it if you still have other ONNX questions. Thanks!
