### ISSUE TITLE
trying to install either with git or from source returns non-zero exit status 1

### ISSUE THREAD

**Issue by fschvart** [onnx/onnx#4095]
# Bug Report

### Is the issue related to model conversion? No
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely

When I try to install onnx, either through pip install onnx or through downloading the git and pip install -e . 
I always get an error that a subprocess returned non-zero exit status 1

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  Windows 11
- ONNX version (*e.g. 1.7*):   1.11.0
- Python version: 3.10.3
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:3.16.00
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
model = onnx.load('model.onnx')
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @fschvart,
Could you please share the full failed error message? Thanks
