### ISSUE TITLE
version_converter bug

### ISSUE THREAD

**Issue by kshpv** [onnx/onnx#4101]
# Bug Report

### Describe the bug
For all ssd models from https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/ssd/model when I try to convert them from their opset to 13 opset I got the following error:

`Assertion target_shape.size() != 0 failed: Version conversion for Softmax failed because input shape is unknown.`

### System information
I am using ONNX 1.11

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
def add_input_from_initializer(model: onnx.ModelProto) -> None:
          """
          Currently onnx.shape_inference doesn't use the shape of initializers, so add
          that info explicitly as ValueInfoProtos.
          Mutates the model.
          Args:
              model: The ModelProto to update.
          """
          # All (top-level) constants will have ValueInfos before IRv4 as they are all inputs
          if model.ir_version < 4:
              nncf_logger.info('Could not process model, as it has {} < 4'.format(model.ir_version))
              return model

          def add_const_value_infos_to_graph(graph: onnx.GraphProto):
              inputs = {i.name for i in graph.input}
              existing_info = {vi.name: vi for vi in graph.input}
              for init in graph.initializer:
                  # Check it really is a constant, not an input
                  if init.name in inputs:
                      continue

                  # The details we want to add
                  elem_type = init.data_type
                  shape = init.dims

                  # Get existing or create new value info for this constant
                  vi = existing_info.get(init.name)
                  if vi is None:
                      vi = graph.input.add()
                      vi.name = init.name

                  # Even though it would be weird, we will not overwrite info even if it doesn't match
                  tt = vi.type.tensor_type
                  if tt.elem_type == onnx.TensorProto.UNDEFINED:
                      tt.elem_type = elem_type
                  if not tt.HasField("shape"):
                      # Ensure we set an empty list if the const is scalar (zero dims)
                      tt.shape.dim.extend([])
                      for dim in shape:
                          tt.shape.dim.add().dim_value = dim

              # Handle subgraphs
              for node in graph.node:
                  for attr in node.attribute:
                      # Ref attrs refer to other attrs, so we don't need to do anything
                      if attr.ref_attr_name != "":
                          continue

                      if attr.type == onnx.AttributeProto.GRAPH:
                          add_const_value_infos_to_graph(attr.g)
                      if attr.type == onnx.AttributeProto.GRAPHS:
                          for g in attr.graphs:
                              add_const_value_infos_to_graph(g)

          return add_const_value_infos_to_graph(model.graph)

model= onnx.load(onnx_model_path)
model.ir_version = 7
add_input_from_initializer(model)
infered_model = onnx.shape_inference.infer_shapes(model)
modified_model = version_converter.convert_version(infered_model, 13)
```
- Attach the ONNX model to the issue (where applicable)
https://github.com/onnx/models/tree/main/vision/object_detection_segmentation/ssd/model

**Comment by jcwchen** [comment]
Hi @kshpv,
Thank you for catching it. It's a known limitation for Softmax version conversion (https://github.com/onnx/onnx/pull/3861) -- if the input shape for Softmax cannot be inferred, the version conversion will fail. I would say this limitation is related to onnx.shape_inference because shape inference does not infer shapes for SSD-like models. The reason is there are some Reshape nodes need some dynamic computation for its Shape. Although ONNX 1.10 brought data propagation to handle this kind of scenario ([the proposal](https://github.com/onnx/onnx/blob/main/docs/proposals/SymbolicShapeInfProposal.md)), it was only applied to newer opset_version so it cannot work with older opset_versions.

Still, I think the limitation here for version_converter is a strong reason to make older opsets support data propagation as well... I am planning to apply it in the near future and I will check whether that can help resolve this issue.

**Comment by kshpv** [comment]
@jcwchen , thank you!
I am waiting for the information about this feature!

**Comment by jcwchen** [comment]
It should be fixed by https://github.com/onnx/onnx/pull/4974. Please let us if you still bump into issues when converting Softmax-12 to Softmax-13. Thanks!
