### ISSUE TITLE
Add col2im operator

### ISSUE THREAD

**Issue by garymm** [onnx/onnx#4106]
# col2im

### Describe the operator
Rearranges input tensor in blocks. Same behavior as https://pytorch.org/cppdocs/api/function_namespaceat_1a979fbf85d8c7362d60d766bbf1639f10.html

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?

### Is this operator used by any model currently? Which one?

Used by `torch.fold`.

Enables model [SS-DCNet](https://github.com/xhp-hust-2018-2011/SS-DCNet)
Enables model [DSTT](https://github.com/ruiliu-ai/DSTT)

Requests for this on the PyTorch converter:
https://github.com/pytorch/pytorch/issues/41423 https://github.com/pytorch/pytorch/issues/64012

### Are you willing to contribute it? (Y/N)

Y

**Comment by jcwchen** [comment]
cc @thiagocrepaldi for assign purpose

**Comment by thiagocrepaldi** [comment]
https://github.com/onnx/onnx/pull/3948 is a draft for Col2Im with N-dimensional support

**Comment by YuraCobain** [comment]
Is it possible to convert the model with 'fold' op using draft from #3948?

**Comment by thiagocrepaldi** [comment]
> Is it possible to convert the model with 'fold' op using draft from #3948?

Not sure if I understood your question, but ONNX doesnt have a `Fold` operator.
However, the plan is that a future implementation of `Fold` on PyTorch repo will use this present `Col2Im` ONNX operator to convert PyTorch models that have `fold` on them

**Comment by YuraCobain** [comment]
Thank you for replay.
Actually, I need to convert PyTorch model with 'fold' op to ONNX.
Is there any patch with preliminary implementation of 'fold' on PyTorch that is compatible with ONNX?

**Comment by thiagocrepaldi** [comment]
> Thank you for replay. Actually, I need to convert PyTorch model with 'fold' op to ONNX. Is there any patch with preliminary implementation of 'fold' on PyTorch that is compatible with ONNX?

Not yet, as fold implementation will need the Col2Im spec, which might change on this PR
