### ISSUE TITLE
Python 3.10 wheels are missing on PyPI

### ISSUE THREAD

**Issue by jaapz** [onnx/onnx#4110]
PyPI currently doesn't have builds for python 3.10, which means everyone who uses that version of python needs to build onnx on every install.  Could you release a 3.10 build?

https://pypi.org/project/onnx/#files

**Comment by jcwchen** [comment]
Hi @jaapz,
The release CI for ONNX has supported Python 3.10 after ONNX 1.11: https://github.com/onnx/onnx/pull/3734. So next release there will be Python 3.10 wheel. If you would like to use it in advance, you could try the onnx-weekly package from [here](https://test.pypi.org/project/onnx-weekly/#files). (Please note that these wheels were produced by the main branch weekly)

**Comment by jaapz** [comment]
Thanks, is there no possibility for you to upload 3.10 versions of onnx 1.10?

**Comment by jcwchen** [comment]
The old release has been finalized quite a while ago so IMO we shouldn't update such an old release. As a workaround, [here](https://test.pypi.org/project/onnx-weekly/1.11.0.dev20220314/#files) is the first released Python 3.10 wheel in TestPyPI which is similar to ONNX 1.11 with more updates from the main branch.

**Comment by jcwchen** [comment]
ONNX just released 1.12.0 yesterday and Python 3.10 has been included. Thanks.
