### ISSUE TITLE
How to pass in dictionary input when converting from pytorch to onnx

### ISSUE THREAD

**Issue by miayu79** [onnx/onnx#4114]
# Ask a Question
How to pass in dictionary input when converting from pytorch to onnx
### Question
Explain your question here.
I followed instruction here -> https://pytorch.org/docs/stable/onnx.html
My pytorch model has a dictionary input. I exported it like below
dictionary = {} (contains 20 key value pairs)
torch.onnx.export(pt_model, (input_ids_1, input_ids_2, valid_length_1, valid_length_2, None, False, None, dictionary, {}), model_onnx_path, opset_version=14, input_names=["input_ids_1", "input_ids_2", "valid_length_1", "valid_length_2", "l", "e", "w", "dictionary"], output_names=["output"])
I added an empty dictionary at the end because from the documentation, this is needed if I want to pass in a dictionary input.
The conversion succeed, however, when I call onnx inference session, it complains model requires 24 inputs.. so it seems somehow it took this dictionary as key parameters even I have the empty dict at the end.. 
### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*): 14 and 13

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
HI @miayu79,
It should be a question for the converter (torch.onnx.export). I would suggest you raise this issue in the converter repo (under PyTorch) and provide the model if possible to get the best help from the converter experts. Thanks.
