### ISSUE TITLE
Seeking clarity on Slice operator's clamping

### ISSUE THREAD

**Issue by hariharans29** [onnx/onnx#4115]
# Ask a Question

### Question

In https://github.com/onnx/onnx/pull/3908/ which seems to have clarified Slice's operation, there seems to be a contradiction with how Numpy does clamping  (the numpy link reference is also added to the op's spec) versus what is prescribed by the clarification. Furthermore, the clarification is without an opset bump for Slice (indicating that this was the behavior all along).

Prescribed start clamping:
Then `start[axes[i]]` is the adjusted `starts[i]` clamped into range of valid indices, i.e. `[0, dims[axes[i]]-1]`.

This seems to indicate that starts clamping is slicing direction oblivious.

Here is an illustrative example from Numpy which indicates starts clamping is slicing direction dependent.

x = np.array([1, 2, 3])

Positive stepping
>>> x[5:6:1]
array([], dtype=int32)

5 is not clamped to a valid range which would be 2 which would have resulted in a non-empty result

Negative stepping
>>> x[5:0:-1]
array([3, 2])

5 is clamped to a valid range (2) and this results in the printed value.

**Comment by diyessi** [comment]
I used NumPy experiments to come up with that description, so if it differs we should fix the descriptions some more.
