### ISSUE TITLE
Add more documentation for model local function

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4120]
# Feature Request

### System information
ONNX version (you are using): 1.11

### What is the problem that this feature solves?
ONNX has introduced model local function for a while and brought a few enhancements about it recently. Going forward it will be more and more useful and popular so ONNX should add more documentation about it for user reference.

### Describe the feature
We can add a new standalone document for it or at least describe it more in the IR.md.

### Will this influence the current api?
No.

### Feature Area
Model location function, documentation.

**Comment by gramalingam** [comment]
Created https://github.com/onnx/onnx/pull/4180
