### ISSUE TITLE
How to get loop13, loop16 test case input_{}.pb and output_{}.pb??

### ISSUE THREAD

**Issue by developerChans** [onnx/onnx#4121]
# Ask a Question

### Question
I am extracting data from 'pb' file using 'onnx's numpy_helper'. However, there is a phenomenon that the ASCII code value of the inputs data is entered in the dim variable in that part.
in loop13 : in dims data == seq_empty's ASCII number
in loop16 : in dims data == opt_seq's ASCII number

### Further information
I used onnx 1.10.3 and 1.11 realase version. both version make error...

in loop13 error : ValueError: cannot reshape array of size 0 into shape (115,101,113,95,101,109,112,116,121)
in loop16 error : ValueError: cannot reshape array of size 12 into shape (111,112,116,95,115,101,113)

model name 
test_loop13_seq
test_loop16_seq_none

<my test code>

```
import numpy as np
import onnx
import os
import glob
from onnx import numpy_helper

model = onnx.load('test_loop16_seq_none/model.onnx')
test_data_dir = 'test_loop16_seq_none/test_data_set_0'

ref_inputs = []
ref_inputs_num = len(glob.glob(os.path.join(test_data_dir, 'input_*.pb')))
for i in range(ref_inputs_num):
   input_file = os.path.join(test_data_dir, 'input_{}.pb'.format(i))
   tensor = onnx.TensorProto()
   with open(input_file, 'rb') as f:
     tensor.ParseFromString([f.read](http://f.read/)())
   ref_inputs.append(numpy_[helper.to](http://helper.to/)_array(tensor))
print(ref_inputs)
print("\n\n\n")
print(model)
```

### Notes
I think Cant read inputs and outputs
But in loop11 can read input and output data

**Comment by jcwchen** [comment]
Hi @developerChans,
Could you please try the method (onnx_test_data_utils.read_tensorproto_pb_file) [here](https://github.com/microsoft/onnxruntime/blob/d96230065eb7eec492ecdc6492161ac43566754e/tools/python/onnx_test_data_utils.py#L12) to load the input.pb?

**Comment by developerChans** [comment]
Hi @jcwchen 
I try that method(onnx_test_data_utils.read_tensorproto_pb_file)...
But I cant success that pb to tensor..

So I try Debug onnxruntime and onnx help_numpy code....

I compare that test case
loop13 test case : [here](https://github.com/onnx/onnx/tree/main/onnx/backend/test/data/node/test_loop13_seq)
loop16 test case : [here](https://github.com/onnx/onnx/tree/main/onnx/backend/test/data/node/test_loop16_seq_none)
conv_with_autopad_same test case : [here](https://github.com/onnx/onnx/tree/main/onnx/backend/test/data/node/test_conv_with_autopad_same)

It seems that the loop input 'pb' file is stored differently from the existing 'pb' file.

through the debug
To conclude this problem, it seems that 'Attribute name' is being parsed into 'dims'.

Also, in the parsing part for rawdata, int32 type data is parsed, and String value is included in rawdata.

Best regards

**Comment by developerChans** [comment]
Thank you @jcwchen 
I solved that issue
it can use to OptionalHasElement, OptionalGetElement, SequenceInsert... etc
i find that optionalProto, sequenceProto
