### ISSUE TITLE
How to overwrite the shape with shape inference

### ISSUE THREAD

**Issue by jiangjiajun** [onnx/onnx#4122]
I noticed there's a document describe how shape inference work in onnx. And here https://github.com/onnx/onnx/blob/main/docs/proposals/SymbolicShapeInfProposal.md#inferred-shape-does-not-match-output-shape mentioned we can handle the shape problem, after dived into the code, I'm still confused, how to enable the option to overwrite the existing shape information.

**Comment by jcwchen** [comment]
Hi @jiangjiajun,
It's a proposal and I believe such a function (overwrite existing shape with inferred shape if mismatch) has not been supported in current shape inference yet.

**Comment by gramalingam** [comment]
Yes, that feature does not exist yet. One possibility you could try is to write a simple python script to remove the extra shape information and then run shape-inference.
