### ISSUE TITLE
Improve the formula representation

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#413]
We have a lot of formulas in our docs. 
For example: https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM

However without appropriate format, it's hard to read.

As far as I know, Github markdown does not have good support for math formulas. Maybe we can use some online tex service to render the formulas on-the-fly.

**Comment by ebarsoum** [comment]
Do we want to force people to learn Latex? I will add this for our SIG discussion.
