### ISSUE TITLE
ONNX graph optimization cause ONNX model checker to fail

### ISSUE THREAD

**Issue by ramkrishna1121** [onnx/onnx#4143]
# Bug Report

MNIST model from Onnx Model Zoo fails ONNX checker after `ORT_ENABLE_BASIC` graph optimization.
Model is directly downloaded from Onnx Model Zoo. Not converted from other frameworks.

### Describe the bug
`onnx.onnx_cpp2py_export.checker.ValidationError: ConvAddFusion_Add_B_Parameter6 in initializer but not in graph input`

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): 
- ONNX version: 1.10  
- Python version: 3.8.8
- CMake version: 3.20.2

### Reproduction instructions
```
# Download model from onnx model zoo
 wget https://github.com/onnx/models/raw/main/vision/classification/mnist/model/mnist-8.onnx
# Optimize the model using onnxruntime_perf_test
./onnxruntime_perf_test -m times -r 1 -I -o 1 -u mnist-o1.onnx  mnist-8.onnx 

import onnx
from onnxmltools.utils import save_model
from onnxmltools.utils import load_model

model = onnx.load('mnist-o1.onnx')
onnx.checker.check_model(model)
```
`Error: onnx.onnx_cpp2py_export.checker.ValidationError: ConvAddFusion_Add_B_Parameter88 in initializer but not in graph input`

### Expected behavior
Expected to pass onnx model checker

**Comment by jcwchen** [comment]
Hi @ramkrishna1121,
I think onnx.checker is doing the right thing for this case. Please note that IR_VERSION <= 3 (opset 8 is IR_VERSION 3) requires graph.initializers exist in graph.input. Such a constraint was loosened after IR_VERSION 4: https://github.com/onnx/onnx/pull/1718. If you try ONNX models with IR_VERSION >= 4 (opset_version >= 9), checker won't catch this kind of error. The optimizer probably removed duplicate input for optimization purpose, but actually it broke IR rule (for IR_Version <=3).

**Comment by ramkrishna1121** [comment]
Given the constraints were loosened can this error be ignored for models with  IR_VERSION <= 3?

**Comment by jcwchen** [comment]
> Given the constraints were loosened can this error be ignored for models with IR_VERSION <= 3?

I think all released IR needs to be consistent since all implementation for old IR has been finalized. We cannot and should not keep modifying old IR to accommodate newer IR.

A proper approach here would be upgrading your model to IR_VERSION >= 4. Or, requesting the optimizer should follow old IR for old models. Or, you can still use it, but please note that according to the old IR, it is not a valid model so it might fail with some tools. (For example, onnx.checker.)

**Comment by ramkrishna1121** [comment]
Ok makes sense. I believe the best approach would be to upgrade the model to IR_VERSION >= 4 so there are no unexpected failures with other tools.
