### ISSUE TITLE
LSTM export ONNX:Non-zero status code returned while running ScatterElements node. Name:'ScatterElements_880' 

### ISSUE THREAD

**Issue by gadregayatri** [onnx/onnx#4151]
# Question
I have deep learning model with LSTM  layer. While performing model inference, I am getting the below error:
` InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ScatterElements node. Name:'ScatterElements_880' Status Message: Indices vs updates dimensions differs at position=0 32 vs 1`

It works only with batch size = 1, which is slowing down inference process a lot.

### Question
How do I make it work with batch_size >1? 

### Further information

- Is this issue related to a specific model?  
**Model name** :  custom model
**Model opset** : 14
pytorch  version: 1.10
onnx: 1.11.0
onnxruntime: 1.9.0

**Comment by jcwchen** [comment]
Hi @gadregayatri,
Could this model pass by onnx.checker with full_check? If so, it should be a question for ONNXRuntime.

**Comment by gadregayatri** [comment]
Hi @jcwchen , thanks for your response. It passed onnx.checker with full_check. Does ONNX supporting LSTM layers with batch size > 1?

**Comment by jcwchen** [comment]
Thank you for providing more details -- that warning reminded me that it might be an old converter issue: https://github.com/pytorch/pytorch/issues/45653. I think the warning here should be fine, but you will need to run the model by ORT [here](https://github.com/pytorch/pytorch/issues/45653#issuecomment-703955262) to specify h0. If you didn't do it previously, could you please give it a try?
