### ISSUE TITLE
Convert BGR to RGB inside the graph, no suitable operator

### ISSUE THREAD

**Issue by joihn** [onnx/onnx#4152]
Hi,
My input tensor is `B x C x H x W `and represents images.
Inside C, the color are encoded as `BGR`. I want to convert it to `RGB` inside the graph. 

I can't find a suitable  [operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md) or workaround that could achieve this job.
Even `transpose` is not capable of this job. 
Any idea ?

**Comment by jcwchen** [comment]
Hi @joihn,
IIUC, you might need few ONNX operators to achieve this conversion, which is probably not efficient during runtime. Have you considered to preprocess these image inputs offline before feeding them into ONNX graph? Actually ONNX doesn't have good support for data preprocessing yet, but there is an ongoing [workgroup](https://lfaifoundation.slack.com/archives/C02AANGFBJB) working on this. For now doing it offline outside ONNX might be a better approach.

**Comment by joihn** [comment]
I managed to find a workaround with "split" and "concat" operators, but yes your right it's probably not super efficient.
