### ISSUE TITLE
How to integrate Onnx with new frameworks

### ISSUE THREAD

**Issue by alexhallam** [onnx/onnx#4155]
### How to integrate Onnx with new frameworks
If someone wanted to convert `statsmodel` objects to Onnx how would one go about that?

**Comment by jcwchen** [comment]
I am not aware of any support for converting statsmodel to ONNX. However, I barely understand statsmodel so perhaps you can reach out their team and see whether they have existing tool to do it or have plan to do it in the future.

**Comment by cbourjau** [comment]
We had this very problem for our own library and spent a lot of time over the last few months building a library that makes writing converter code much easier and debuggable. We [open-sourced](https://github.com/Quantco/spox/blob/main/README.md) "Spox" a few days ago.

I don't know `statsmodels` itself but the core task seems to be library independent: You have a trained model instance and now you need to convert that into an ONNX graph. In essence, it means that you need to rewrite the `predict` method using ONNX operators. 

Below is a runnable example for the model from statsmodels' "Getting started" [guide](https://www.statsmodels.org/stable/gettingstarted.html). 

```python
import statsmodels.api as sm
from patsy import dmatrices

import onnxruntime as ort
import numpy as np
from spox import Var, argument, build, Tensor
import spox.opset.ai.onnx.v17 as op

# Create a model with statsmodels
# From https://www.statsmodels.org/stable/gettingstarted.html
df = sm.datasets.get_rdataset("Guerry", "HistData").data
y, X = dmatrices('Lottery ~ Literacy + Wealth + Region', data=df, return_type='dataframe')
mod = sm.OLS(y, X)
res = mod.fit()

# Express logic of `OLS.predict` as an ONNX graph (with spox).
# We have to explicitly name the type and shape of the model inputs.
# Output types and shapes are inferred.
onnx_input = argument(Tensor(np.float64, shape=("N", len(X.columns))))
output = op.mat_mul(onnx_input, op.const(res.params.values))

# Build onnx.ModelProto
model_proto = build(inputs={"exog": onnx_input}, outputs={"output": output})

# Run inference and compare results
session = ort.InferenceSession(model_proto.SerializeToString())
onnx_result = session.run(input_feed={"exog": X.values}, output_names=["output"])
sm_result = res.predict(exog=X)

# Minor difference for floating point matrix multiplication are to be expected.
np.testing.assert_almost_equal(onnx_result[0], sm_result)
```

**Comment by nealcha** [comment]
Hi,I have tried your codes, however,it reports`ImportError: cannot import name 'np_dtype_to_tensor_dtype' from 'onnx.helper' (/home/neal/miniconda3/lib/python3.8/site-packages/onnx/helper.py)`in line`from spox import Var, argument, build, Tensor`,my package version are `onnx-1.13.1 protobuf-3.20.3 spox-0.6.0`, is it the package  problem?thanks for your help!

**Comment by cbourjau** [comment]
Very strange! What platform are you on? I just tried the above script in a new environment (on MacOS) and it all works as expected. We tests on Linux in CI. 

```bash
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -U pip
$ pip install statsmodels spox onnxruntime
$ python statsmodel_exampl.py  # The example from above
```

The environment is as follows:
```
$ pip freeze                                                                                                                       ~/groundzero/test_spox_pip_dev
coloredlogs==15.0.1
flatbuffers==23.1.21
humanfriendly==10.0
mpmath==1.2.1
numpy==1.24.2
onnx==1.13.1
onnxruntime==1.14.1
packaging==23.0
pandas==1.5.3
patsy==0.5.3
protobuf==3.20.3
python-dateutil==2.8.2
pytz==2022.7.1
scipy==1.10.1
six==1.16.0
spox==0.6.0
statsmodels==0.13.5
sympy==1.11.1
typing_extensions==4.5.0
```

If the problem persists, I would very much appreciate it if you could open an issue in the Spox repository.

**Comment by justinchuby** [comment]
@gramalingam

**Comment by jbachurski** [comment]
@nealcha The error you're facing is definitely indicative of a legacy ONNX version, as `np_dtype_to_tensor_dtype` was added in `1.13` - and it seems to be missing. The `onnx` import must be getting overridden somehow - did you check the version with `import onnx; print(onnx.__version__)`, too? Unfortunately we didn't maintain compatibility with `onnx<1.13`.
