### ISSUE TITLE
How to convert PreciseRoIPooling to ONNX?

### ISSUE THREAD

**Issue by davidyang180** [onnx/onnx#4158]
I want to speed up the model in the project, but the model contains the prroi pooling library compiled by the third party. Through consulting the documents, I learned that custom operators can be added for conversion, but onnx is still cann't export after simple implementation. How can I convert prroi pooling to onnx?

The following is the implementation details of the defined operator for reference.

```
import torch
import torch.autograd as ag

__all__ = ['prroi_pool2d']


_prroi_pooling = None


def _import_prroi_pooling():
    global _prroi_pooling

    if _prroi_pooling is None:
        try:
            from os.path import join as pjoin, dirname
            from torch.utils.cpp_extension import load as load_extension
            root_dir = pjoin(dirname(__file__), 'src')

            _prroi_pooling = load_extension(
                '_prroi_pooling',
                [pjoin(root_dir, 'prroi_pooling_gpu.c'), pjoin(root_dir, 'prroi_pooling_gpu_impl.cu')],
                verbose=True
            )
        except ImportError:
            raise ImportError('Can not compile Precise RoI Pooling library.')

    return _prroi_pooling


class PrRoIPool2DFunction(ag.Function):
    @staticmethod
    def forward(ctx, features, rois, pooled_height, pooled_width, spatial_scale):
        _prroi_pooling = _import_prroi_pooling()

        assert 'FloatTensor' in features.type() and 'FloatTensor' in rois.type(), \
                'Precise RoI Pooling only takes float input, got {} for features and {} for rois.'.format(features.type(), rois.type())

        pooled_height = int(pooled_height)
        pooled_width = int(pooled_width)
        spatial_scale = float(spatial_scale)

        features = features.contiguous()
        rois = rois.contiguous()
        params = (pooled_height, pooled_width, spatial_scale)

        if features.is_cuda:
            output = _prroi_pooling.prroi_pooling_forward_cuda(features, rois, *params)
            ctx.params = params
            # everything here is contiguous.
            ctx.save_for_backward(features, rois, output)
        else:
            raise NotImplementedError('Precise RoI Pooling only supports GPU (cuda) implememtations.')

        return output

    @staticmethod
    def backward(ctx, grad_output):
        _prroi_pooling = _import_prroi_pooling()

        features, rois, output = ctx.saved_tensors
        grad_input = grad_coor = None

        if features.requires_grad:
            grad_output = grad_output.contiguous()
            grad_input = _prroi_pooling.prroi_pooling_backward_cuda(features, rois, output, grad_output, *ctx.params)
        if rois.requires_grad:
            grad_output = grad_output.contiguous()
            grad_coor = _prroi_pooling.prroi_pooling_coor_backward_cuda(features, rois, output, grad_output, *ctx.params)

        return grad_input, grad_coor, None, None, None


    @staticmethod
    def symbolic(g, *input):
        return g.op("custom_domain::PrRoIPool2DFunction",input[0])


prroi_pool2d = PrRoIPool2DFunction.apply
```
![image](https://user-images.githubusercontent.com/45596935/164735640-ef82ff0a-f416-4f98-be60-a2ab05de99a7.png)

**Comment by jcwchen** [comment]
Hi @davidyang180,
According to the error message you gave, it seems that you have already converted it to ONNX successfully? (Because I saw ONNXRuntime (ORT) complaint the ONNX model has an unknown operator) If so, I think you still need more steps to register your custom operator in ORT. You can check the document [here](https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#register-a-custom-operator).

**Comment by davidyang180** [comment]
> Hi @davidyang180, According to the error message you gave, it seems that you have already converted it to ONNX successfully? (Because I saw ONNXRuntime (ORT) complained the ONNX model has an unknown operator) If so, I think you still need more steps to register your custom operator in ORT. You can check the document [here](https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#register-a-custom-operator).

Hi!Thanks for your reply. Then I encountered this problem again. What caused this?
![image](https://user-images.githubusercontent.com/45596935/164878268-fce0cfce-9b60-45ad-8afb-42efbf23cf46.png)

**Comment by davidyang180** [comment]
> Hi @davidyang180, According to the error message you gave, it seems that you have already converted it to ONNX successfully? (Because I saw ONNXRuntime (ORT) complained the ONNX model has an unknown operator) If so, I think you still need more steps to register your custom operator in ORT. You can check the document [here](https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#register-a-custom-operator).

When I modify the symbolic function of the method class as shown in the figure, there are other errors.
![image](https://user-images.githubusercontent.com/45596935/164879619-8bc16410-dfd7-4d82-9272-46fe8a2374a2.png)

![image](https://user-images.githubusercontent.com/45596935/164879629-de43c23c-6a11-4acc-890b-3e5e1648400e.png)

**Comment by jcwchen** [comment]
Thanks for more details. So actually the error happened during registering custom operators from conversion instead. I think you probably has already followed the instruction [here](https://pytorch.org/docs/stable/onnx.html#custom-operators). If the document cannot help, I would suggest you raise this issue in the converter repo (torch.onnx.export is under PyTorch repo) to get the best assistance from the converter experts.

**Comment by davidyang180** [comment]
> Thanks for more details. So actually the error happened during registering custom operators from conversion instead. I think you probably has already followed the instruction [here](https://pytorch.org/docs/stable/onnx.html#custom-operators). If the document cannot help, I would suggest you raise this issue in the converter repo (torch.onnx.export is under PyTorch repo) to get the best assistance from the converter experts.

Hi! Thanks for your suggestion. Another question is whether onnx conversion provides such a function, when encountering an operator that cannot be converted, it will be ignored and the original mode will be used for calculation.

**Comment by jcwchen** [comment]
> Another question is whether onnx conversion provides such a function, when encountering an operator that cannot be converted, it will be ignored and the original mode will be used for calculation.

Not that I am aware of. IIUC, those unsupported operators need to be registered anyway. You can confirm this with the converter team. Thanks.

**Comment by chengx835** [comment]
I aslo do same thing,  I set enable_onnx_checker=False  when call torch.onnx.export(),then seccessed.
