### ISSUE TITLE
Optional attributes with no default values

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#416]
Hi,

I  am trying to use the resnet 50 onnx model : https://github.com/onnx/models/tree/master/resnet50

And one of the convolution node doesn't have pads values.
If I look at the [doc of Conv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#conv)
nothing informs the user that pads values are optional, and what are default values.

So, I took a look to the defs of Conv [here](https://github.com/onnx/onnx/blob/c3137751923f576d14b4212ea444d1562b127a66/onnx/defs/nn/defs.cc#L170)

And to my surprise, all attributes are noticed as "OPTIONAL".
I also looked at schema.cc/h files, but nothing give me the answer.

Is it a bug in onnx to make all attributes as optional ? 
Or is it implicit in onnx that all attribute are optional and a default value is always provided to fill the attr.
In that case, what is the default value ?

In all cases, the doc is really unclear about this, some attr has the flag "(optional)" just after the name of the attribute like [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-42)
for optional inputs it is in bold with the name like [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-0---1)
and sometimes it is just into the description like [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-55).
Moreover, it is the same with the flag "required" which is present just for few attr like [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-55)

**Comment by linkerzhang** [comment]
Understand that it's somehow confusing here. At the very beginning, ONNX treated all attributes as "optional" without specifying any default value. We realized that's confusing folks. Thus, we changed the API #378 to treat attributes as "required" by default and default value is expected to be set if it's optional. 
API now is in, but we haven't finished to go thru all existing ops to figure out which attributes are really "optional" and set default values for them accordingly. :-)

**Comment by LucasMahieu** [comment]
OK, it makes more sense now ...
Someone is committed to do think task ?
Or can I submit some pull request to fix some required attributes that are optional for now ?

**Comment by linkerzhang** [comment]
@LucasMahieu feel free to contribute and send out PRs to fix required attributes please.

**Comment by LucasMahieu** [comment]
https://github.com/onnx/onnx/pull/423
Can be closed
