### ISSUE TITLE
How to append execution provider DirectML in C++? 

### ISSUE THREAD

**Issue by CHNVigny** [onnx/onnx#4165]
# DirectML/C++

### How to append execution provider DirectML in C++? 
I have to compile my C++ code under x86 mode, I want to accelerate my code by using DirectML but not found DirectML interface in header "onnxruntime_cxx_api.h". How to use DirectML to accelerate inference with C++ API?

### Further information
- model usage  

### Notes
sessionOptions.AppendExecutionProvider(options);

**Comment by jcwchen** [comment]
Hi @CHNVigny,
It should be a question for ONNXRuntime. Please raise this issue there to get the best assistance from runtime experts.

**Comment by CHNVigny** [comment]
Thank you!
