### ISSUE TITLE
Does Opset 9 not support element-wise product between Float tensor and Int tensor?

### ISSUE THREAD

**Issue by dongb5** [onnx/onnx#4169]
# Ask a Question

### Question
There are codes in my model using a mask to set invalid position to zero, like `x = x * mask`, where x is a torch.float tensor, and mask is a torch.int tensor. It was all fine when I used opset 11 to export onnx model, but failed with opeset 9. Since I am using TensorRT 5, seems that I can only use onnx with opset 9. Just wondering if opset 9 supports computation between float and int tensors. If not, I will change all tensors to float.

### Further information
error:
```
x = x * mask
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Int
```

- Is this issue related to a specific model?  
**Model opset** (*e.g. 7*): 9

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @dongb5,
I am not aware of any ONNX change related to it between opset 9 and opset 11. Did this error happen in `torch.onnx.export`? If so, I would suggest you raise this issue in the converter repo (under PyTorch) and tag ONNX to understand the behavior difference between opset 9 and opset 11 in exporter.

**Comment by dongb5** [comment]
Hi @jcwchen , thanks for reply.
Then it maybe the issue of TensorRT 5 and 7. It happened when build TRT engine from onnx.

**Comment by jcwchen** [comment]
Thanks for the info. Then yes I would suggest you contact TRT team to take a closer look at this issue.

**Comment by jcwchen** [comment]
Close here now since it should be a question for TRT. Please reopen it if you still have other ONNX questions. Thanks
