### ISSUE TITLE
MaxPool return indices

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#417]
A user here (https://discuss.pytorch.org/t/problems-converting-pytorch-model-into-onnx/12192?u=pengfei_wang) requested MaxPool with remembered indices, which ONNX doesn't support. Might be worth looking into.

**Comment by ebarsoum** [comment]
Is that needed for backprop?

**Comment by jendrikjoe** [comment]
Hi @ebarsoum,
it is needed for some people working with neural networks that down- and later upsample data, e.g. segmentation networks :)

**Comment by fumihwh** [comment]
@ebarsoum It's something like [`tf.nn.max_pool_with_argmax`](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax).

**Comment by pgtgrly** [comment]
I am trying to export an Unet-like architecture trained on Pytorch and I am facing the same issue. Any updates on the same?

**Comment by BenjaminBout** [comment]
I also have the same issue, any updates, workarounds ?

**Comment by houseroad** [comment]
Look into the issue

**Comment by houseroad** [comment]
@pgtgrly @BenjaminBout @simasima121 do you guys also need `MaxUnpool`?

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/issues/1217 is the follow up.

**Comment by Margrate** [comment]
x1d = self.unpool1(drop_conv_2, id1)


    w.add_graph(parsing, (image, ))
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "python3.6/site-packages/tensorboardX/pytorch_graph.py", line 96, in graph
    torch.onnx._optimize_trace(trace, torch._C._onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
  File "python3.6/site-packages/torch/onnx/__init__.py", line 41, in _optimize_trace
    trace.set_graph(utils._optimize_graph(trace.graph(), operator_export_type))
  File "python3.6/site-packages/torch/onnx/utils.py", line 107, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
RuntimeError: symbolic for max_pool2d_with_indices returned None for the output 1 (indicating conversion for that particular output is not supported), but the network uses this output later
