### ISSUE TITLE
 Exporting the operator col2im to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by FelixFu520** [onnx/onnx#4171]
### Describe the bug
when i export onnx model,   Exporting the operator col2im to ONNX opset version 11 is not supported.

the Troch Model code is below:
```
   def forward(self, x):
        # logger.info("2.1 extract test set features")
        with torch.no_grad():
            _ = self.model(x.to(self.device))
        # get intermediate layer outputs
        for k, v in zip(self.test_outputs.keys(), self.outputs):
            self.test_outputs[k].append(v.cpu().detach())

        # 合并
        for k, v in self.test_outputs.items():
            self.test_outputs[k] = torch.cat(v, 0)

        # logger.info("2.2 covert feature_maps to embedding_vectors ......")
        embedding_vectors = self.test_outputs['layer1']
        for layer_name in ['layer2', 'layer3']:
            embedding_vectors = embedding_concat(embedding_vectors, self.test_outputs[layer_name])

        # logger.info("merge embedding_vectors, and final size {}".format(embedding_vectors.shape))

        # randomly select d dimension
        embedding_vectors = torch.index_select(embedding_vectors, 1, self.select_index)

        return embedding_vectors
```

github:https://github.com/FelixFu520/AICore/blob/main/dao/models/anomaly/PaDiM.py

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): ubuntu18.06
- ONNX version (*e.g. 1.7*):  1.10.1
- Python version:3.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
![image](https://user-images.githubusercontent.com/23306248/165730436-b5090fcb-4bc6-4d1e-a0fb-d2ca58752b65.png)

- Attach the ONNX model to the issue (where applicable)

root@880d76488018:/ai/AICore# python main.py -c configs/AnomalyDetection/anomaly-PaDiM_L-MVTecDataset-export-linux.json
2022-04-28 17:59:57.954 | INFO     | __main__:main:129 - Single Machine, Single GPU
2022-04-28 17:59:57.984 | INFO     | __main__:main_worker:211 - global rank-0, local rank-0, register all modules ......
2022-04-28 17:59:58.278 | INFO     | dao.register:_register_core:118 -  modules dao.dataloaders(core) loaded !
2022-04-28 17:59:58.295 | INFO     | dao.register:_register_core:118 -  modules dao.evaluators(core) loaded !
2022-04-28 17:59:58.296 | INFO     | dao.register:_register_core:118 -  modules dao.losses(core) loaded !
2022-04-28 17:59:58.441 | INFO     | dao.register:_register_core:118 -  modules dao.models(core) loaded !
2022-04-28 17:59:58.442 | INFO     | dao.register:_register_core:118 -  modules dao.optimizers(core) loaded !
2022-04-28 17:59:58.443 | INFO     | dao.register:_register_core:118 -  modules dao.schedulers(core) loaded !
2022-04-28 17:59:58.532 | INFO     | dao.register:_register_core:118 -  modules dao.trainers(core) loaded !
2022-04-28 17:59:59.011 | WARNING  | dao.trainers.trainerAnomaly:_before_export:351 - Anomaly Detection only supported Single Machine and Single GPU !!!!
2022-04-28 17:59:59.011 | INFO     | dao.trainers.trainerAnomaly:_before_export:352 - ....... Export Before, Setting something ......
2022-04-28 17:59:59.011 | INFO     | dao.trainers.trainerAnomaly:_before_export:354 - 1. Logging Setting ...
2022-04-28 17:59:59.012 | INFO     | dao.trainers.trainerAnomaly:_before_export:355 - create log file /ai/data/AILogs/4AR6N-L546S-DQSM9-424ZM-N4DZ2/AnomalyDetection/PaDim/test/export/export_log.txt
2022-04-28 17:59:59.012 | INFO     | dao.trainers.trainerAnomaly:_before_export:359 - create Tensorboard log /ai/data/AILogs/4AR6N-L546S-DQSM9-424ZM-N4DZ2/AnomalyDetection/PaDim/test/export
2022-04-28 17:59:59.014 | INFO     | dao.trainers.trainerAnomaly:_before_export:362 - 2. Model Setting ...
/ai/AICore/dao/models/anomaly/PaDiM.py:321: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  s = int(H1 / H2)    # x对于y的缩小步长
2022-04-28 18:00:06.395 | ERROR    | __main__:main:130 - An error has been caught in function 'main', process 'MainProcess' (228373), thread 'MainThread' (140121706673984):
Traceback (most recent call last):

  File "main.py", line 227, in <module>
    main()
    └ <function main at 0x7f6e990e6c10>

> File "main.py", line 130, in main
    main_worker(parsers.exp_file, parsers.cus_file, parsers)
    │           │       │         │       │         └ Namespace(amp=True, cache=False, cus_file=None, detail=False, devices=1, dist_backend='nccl', dist_url=None, ema=True, exp_fi...
    │           │       │         │       └ None
    │           │       │         └ Namespace(amp=True, cache=False, cus_file=None, detail=False, devices=1, dist_backend='nccl', dist_url=None, ema=True, exp_fi...
    │           │       └ 'configs/AnomalyDetection/anomaly-PaDiM_L-MVTecDataset-export-linux.json'
    │           └ Namespace(amp=True, cache=False, cus_file=None, detail=False, devices=1, dist_backend='nccl', dist_url=None, ema=True, exp_fi...
    └ <function main_worker at 0x7f6e8d36e790>

  File "main.py", line 223, in main_worker
    trainer.run()
    │       └ <function AnomalyExport.run at 0x7f6f88d361f0>
    └ <dao.trainers.trainerAnomaly.AnomalyExport object at 0x7f6e8d371790>

  File "/ai/AICore/dao/trainers/trainerAnomaly.py", line 379, in run
    torch.onnx.export(self.model,
    │     │    │      │    └ PaDiM_export(
    │     │    │      │        (model): ResNet(
    │     │    │      │          (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    │     │    │      │        ...
    │     │    │      └ <dao.trainers.trainerAnomaly.AnomalyExport object at 0x7f6e8d371790>
    │     │    └ <function export at 0x7f6e9eaf6790>
    │     └ <module 'torch.onnx' from '/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py'>
    └ <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'>

  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
           │     │      │      │     │  │              │        └ <TrainingMode.EVAL: 0>
           │     │      │      │     │  │              └ True
           │     │      │      │     │  └ True
           │     │      │      │     └ '/ai/data/AILogs/4AR6N-L546S-DQSM9-424ZM-N4DZ2/AnomalyDetection/PaDim/test/export/export.onnx'
           │     │      │      └ tensor([[[[-0.7612, -1.4139,  0.4594,  ...,  0.4034, -0.0651,  1.2201],
           │     │      │                  [-0.7568, -1.1743,  0.5666,  ...,  0.2088, ...
           │     │      └ PaDiM_export(
           │     │          (model): ResNet(
           │     │            (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
           │     │          ...
           │     └ <function export at 0x7f6feeb1aca0>
           └ <module 'torch.onnx.utils' from '/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py'>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
    │       │      │     │  │              │        │         │            └ ['vectors']
    │       │      │     │  │              │        │         └ ['input']
    │       │      │     │  │              │        └ <TrainingMode.EVAL: 0>
    │       │      │     │  │              └ True
    │       │      │     │  └ True
    │       │      │     └ '/ai/data/AILogs/4AR6N-L546S-DQSM9-424ZM-N4DZ2/AnomalyDetection/PaDim/test/export/export.onnx'
    │       │      └ tensor([[[[-0.7612, -1.4139,  0.4594,  ...,  0.4034, -0.0651,  1.2201],
    │       │                  [-0.7568, -1.1743,  0.5666,  ...,  0.2088, ...
    │       └ PaDiM_export(
    │           (model): ResNet(
    │             (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    │           ...
    └ <function _export at 0x7f6feeaad8b0>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 710, in _export
    _model_to_graph(model, args, verbose, input_names,
    │               │      │     │        └ ['input']
    │               │      │     └ True
    │               │      └ tensor([[[[-0.7612, -1.4139,  0.4594,  ...,  0.4034, -0.0651,  1.2201],
    │               │                  [-0.7568, -1.1743,  0.5666,  ...,  0.2088, ...
    │               └ PaDiM_export(
    │                   (model): ResNet(
    │                     (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    │                   ...
    └ <function _model_to_graph at 0x7f6feeaad5e0>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
            │               │      └ <OperatorExportTypes.ONNX: 0>
            │               └ graph(%0 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cpu),
            │                       %model.conv1.weight : F...
            └ <function _optimize_graph at 0x7f6feeb1ae50>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
            │     │  │              │      └ <OperatorExportTypes.ONNX: 0>
            │     │  │              └ graph(%0 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cpu),
            │     │  │                      %model.conv1.weight : F...
            │     │  └ <built-in method _jit_pass_onnx of PyCapsule object at 0x7f709f879720>
            │     └ <module 'torch._C' from '/opt/conda/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so'>
            └ <module 'torch' from '/opt/conda/lib/python3.8/site-packages/torch/__init__.py'>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
           │     │                       │       └ {}
           │     │                       └ <unprintable tuple object>
           │     └ <function _run_symbolic_function at 0x7f6feeaae040>
           └ <module 'torch.onnx.utils' from '/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py'>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1036, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
                  │                          │       │        │              └ <OperatorExportTypes.ONNX: 0>
                  │                          │       │        └ 11
                  │                          │       └ 'col2im'
                  │                          └ ''
                  └ <function _find_symbolic_in_registry at 0x7f6feeaadf70>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 990, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
           │            │                 │        │       └ 11
           │            │                 │        └ ''
           │            │                 └ 'col2im'
           │            └ <function get_registered_op at 0x7f6feea4bd30>
           └ <module 'torch.onnx.symbolic_registry' from '/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py'>
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 129, in get_registered_op
    raise RuntimeError(msg)
                       └ 'Exporting the operator col2im to ONNX opset version 11 is not supported. Please feel free to request support or submit a pul...

RuntimeError: Exporting the operator col2im to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by jcwchen** [comment]
Hi @FelixFu520,
Similar to https://github.com/onnx/onnx/issues/4106. Please note that col2im is not supported in ONNX yet and there is a pending PR for it: https://github.com/onnx/onnx/pull/3948

**Comment by jcwchen** [comment]
Let's track this support request in #4106. Close this one now. Feel free to reopen it if you still other ONNX questions. Thanks
