### ISSUE TITLE
OnnxRuntime  Error

### ISSUE THREAD

**Issue by FusionModele** [onnx/onnx#4172]
the onnx file is generated with  opset 11.
I'm trying to run an onnx model with onnxruntime and I got this issue.
self.ort_session = ort.InferenceSession(model_path)
---------log------------------------
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,16074,16074}, requested shape:{1,16074,1}
----------env--------
onnxruntime-1.11.1 
 onnx-1.11.0

**Comment by jcwchen** [comment]
Hi @FusionModele,
Does this model pass onnx.checker with full_check? If so, since this error happened during runtime, please raise this issue in ONNX Runtime to get the best assistance from runtime experts.

**Comment by jcwchen** [comment]
I believe this issue has been tracked in a proper place: https://github.com/microsoft/onnxruntime/discussions/11419. Close here now.
