### ISSUE TITLE
Can the quantized model trained by pytorch qat be converted to the onnx model?

### ISSUE THREAD

**Issue by chenxinhua** [onnx/onnx#4174]
Can the quantized model trained by pytorch qat be converted to the onnx model?

**Comment by jcwchen** [comment]
Hi @chenxinhua,
In short, IIUC, PyTorch quantized model was partially supported by the PyTorch-ONNX exporter, which means you might bump into some issues for some models: https://discuss.pytorch.org/t/onnx-export-of-quantized-model/76884. To understand what the limitations are, I would suggest you follow-up converter-related questions in the converter repo to get the best help from them. I saw you have opened a same issue there so I will close this one. Feel free to reopen it if you still have other ONNX questions. Thanks.
