### ISSUE TITLE
ONNX in C/C++

### ISSUE THREAD

**Issue by lburzawa** [onnx/onnx#418]
Is there a way to open a model in ONNX format in C/C++ and access its details as easily as in Python? If not, is there any immediate plan for such support?

**Comment by linkerzhang** [comment]
There's no c++ support for now. We should and will build one in next step to allow users to be able to load/optimize onnx model in c++. :)

**Comment by bddppq** [comment]
ONNX model files are protobuf pb files, you can load them with any protobuf library in any language. In fact, the ONNX checker is implemented in C++. e.g. you can do this to print the number of inputs in a model:

```c++
#include "onnx/onnx_pb.h"
#include "onnx/proto_utils.h"

...
std::unique_ptr<ModelProto> model(new ModelProto());
onnx::ParseProtoFromBytes(model.get(), bytes, nbytes);

std::cout << model->graph().input().size() << std::endl;
...
```

**Comment by houseroad** [comment]
@lburzawa if you just want to access the model in protobuf format, I think @bddppq already gives the right solution. If you would like to do optimization on top of onnx model, I think you may be interested in this PR https://github.com/onnx/onnx/pull/400, which introduces IR infra into ONNX repo.

**Comment by lcskrishna** [comment]
@lburzawa You can view on how to open the model in C/C++ in one of my project [onnx-parser](https://github.com/lcskrishna/onnx-parser) and most of the functions are present. 
Although it's not a perfect solution, you can understand how to use the binary onnx model.

**Comment by Nagamani732** [comment]
@bddppq I built onnx from source I tried to print the number of inputs in a model as you mentioned in the previous message but I am not to get the onnx nanmespace itself.

Can you please help me thid regard?

**Comment by karlTUM** [comment]
Hi all, 
just to be clear, I have a trained onnx model, and would like to use this model for the prediction with c++. Is it possible?

**Comment by houseroad** [comment]
Yes, it is possible. There are different frameworks you can choose: 1) Caffe2 (now part of PyTorch 1.0), 2) CNTK, 3) MxNet, 4) Tensorflow, 5) TensorRT, etc. I think they all have C++ predictor.

**Comment by karlTUM** [comment]
@houseroad Do you mean that I should use C++ version of those frameworks, e.g. MxNet to load onnx model? I just see that they have Python API to load onnx model, but do they also have c++ API to load onnx model?

**Comment by SPark9625** [comment]
For future reference, it seems like the `onnx` namespace has now changed to `ONNX_NAMESPACE` (#999)

Additionally, I also have a question while following through @bddppq 's answer.
I'm trying exactly what is said on his answer, and I'm getting undefined symbol linker error, which says that it can't find `onnx::ModelProto::ModelProto()`. I checked, and it's declared and defined in `onnx.pb.h` and `onnx.pb.cc` respectively. Since these files are generated from the .proto files, I assume that there is no prebuilt library I can link to. Am I correct?

If this *is* the case, should I include all the .cpp files in the onnx directory into my build?

**Comment by eundoosong** [comment]
Hello I also struggled with this for the last few days.
You need to build libraries as described in README.md 
That is `python3 setup.py install` and libraries will be located in `.setuptools-cmake-build`
For your reference, I'm sharing my dockerfile.
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y protobuf-compiler libprotoc-dev git python3 python3-pip cmake
RUN ln -s /usr/bin/python3  /usr/bin/python
RUN git clone https://github.com/onnx/onnx.git

WORKDIR onnx
RUN git checkout v1.3.0
RUN git submodule update --init --recursive
RUN python3 setup.py install

WORKDIR /onnx/.setuptools-cmake-build
COPY test_onnx.cpp ./
COPY mnist.onnx ./
RUN g++ -o test_onnx test_onnx.cpp -lonnx_proto -lprotobuf -L./

CMD ./test_onnx
```
This is just for testing, I generated `mnist.onnx` using pytorch.onnx.
`test_onnx.cpp` looks like this.
```C++
#include "onnx/onnx.pb.h"
#include <fstream>
#include <cassert>
#include <iostream>

int main(void) {
        onnx::ModelProto model;
        std::ifstream in("mnist.onnx", std::ios_base::binary);
        model.ParseFromIstream(&in);
        in.close();
        std::cout<<model.graph().input().size()<<"\n";
}
```

**Comment by SPark9625** [comment]
Nice, @eundoosong!! Your solution worked :)

Do you know how to make forward passes from the now loaded onnx model?

I assumed that it’d be easy to convert it to a C++ caffe2 model(because it was in Python), but I don’t seem to be able to find any documentation on how to do it in C++.

I’m not constraining myself to Caffe2 though, so I’m open to anything.

Tried the Pytorch C++ API, which worked, but I’m quite curious about onnx as well and wanna know if it’s possible this way as well 🤔

**Comment by blueardour** [comment]
Hi  @eundoosong 
I met the following error when compile the test_onnx.cpp:

g++ -o c++-demo/test_onnx c++-demo/test_onnx.cpp -I .setuptools-cmake-build -lonnx_proto -lprotobuf -L .setuptools-cmake-build
In file included from c++-demo/test_onnx.cpp:4:0:
.setuptools-cmake-build/onnx/onnx.pb.h:33:15: error: expected initializer before ‘protobuf_AddDesc_onnx_2fonnx_2eproto’
 void ONNX_API protobuf_AddDesc_onnx_2fonnx_2eproto();
               ^
.setuptools-cmake-build/onnx/onnx.pb.h:64:1: error: ‘ONNX_API’ does not name a type
 ONNX_API bool AttributeProto_AttributeType_IsValid(int value);
 ^
.setuptools-cmake-build/onnx/onnx.pb.h:69:1: error: ‘ONNX_API’ does not name a type
 ONNX_API const ::google::protobuf::EnumDescriptor* AttributeProto_AttributeType_descriptor();
 ^
.setuptools-cmake-build/onnx/onnx.pb.h: In function ‘const string& onnx::AttributeProto_AttributeType_Name(onnx::AttributeProto_AttributeType)’:
.setuptools-cmake-build/onnx/onnx.pb.h:72:45: error: ‘AttributeProto_AttributeType_descriptor’ was not declared in this scope
     AttributeProto_AttributeType_descriptor(), value);


It seems that the compiler could not recognize the namesapce keyword. Do you know what is the problem?  My g++ version is 4.9

**Comment by blueardour** [comment]
I solve the problem by adding "#define ONNX_API " in the main file,

**Comment by charanpool** [comment]
> Hello I also struggled with this for the last few days.
> You need to build libraries as described in README.md
> That is `python3 setup.py install` and libraries will be located in `.setuptools-cmake-build`
> For your reference, I'm sharing my dockerfile.
> 
> ```
> FROM ubuntu:16.04
> 
> RUN apt-get update && apt-get install -y protobuf-compiler libprotoc-dev git python3 python3-pip cmake
> RUN ln -s /usr/bin/python3  /usr/bin/python
> RUN git clone https://github.com/onnx/onnx.git
> 
> WORKDIR onnx
> RUN git checkout v1.3.0
> RUN git submodule update --init --recursive
> RUN python3 setup.py install
> 
> WORKDIR /onnx/.setuptools-cmake-build
> COPY test_onnx.cpp ./
> COPY mnist.onnx ./
> RUN g++ -o test_onnx test_onnx.cpp -lonnx_proto -lprotobuf -L./
> 
> CMD ./test_onnx
> ```
> This is just for testing, I generated `mnist.onnx` using pytorch.onnx.
> `test_onnx.cpp` looks like this.
> 
> ```c++
> #include "onnx/onnx.pb.h"
> #include <fstream>
> #include <iostream>
> 
> int main(void) {
>         onnx::ModelProto model;
>         std::ifstream in("mnist.onnx", std::ios_base::binary);
>         model.ParseFromIstream(&in);
>         in.close();
>         std::cout<<model.graph().input().size()<<"\n";
> }
> ```

Hello, I tried to implement run the sequence of commands as described, but the direc '/onnx/.setuptools-cmake-build' is not created. I tried to add it manually and run, then i encountering an error that says - 'g++: error: =lprotobuf: No such file or directory'. How do i resove it?

**Comment by aliimani** [comment]
> @lburzawa if you just want to access the model in protobuf format, I think @bddppq already gives the right solution. If you would like to do optimization on top of onnx model, I think you may be interested in this PR #400, which introduces IR infra into ONNX repo.

**Comment by VeenaPulicharla** [comment]
> Hi all,
> just to be clear, I have a trained onnx model, and would like to use this model for the prediction with c++. Is it possible?

Hi, were you able to get predictions? if yes could you please tell how you did

**Comment by prasanthpul** [comment]
@VeenaPulicharla if you have a trained ONNX model and want to do predictions on it, you can consider using a C++ inference engine like https://github.com/microsoft/onnxruntime

**Comment by VeenaPulicharla** [comment]
If possible could you please provide an example for doing predictions on sklearn model in c++.

**Comment by JohnCraigPublic** [comment]
Is there no sample code that simply shows how to load a model, give it input, and get the output?   C or C++ ?   I can't find a single example anywhere...

**Comment by prasanthpul** [comment]
@JohnCraigPublic and @VeenaPulicharla: https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md shows how to use the ONNX Runtime C API.

Please file any follow up issues at https://github.com/microsoft/onnxruntime

**Comment by JohnCraigPublic** [comment]
Maybe a dumb question: if I am using the C API with ONNX runtime as in your example, am I doing "WindowsML" ?   Or is WindowsML yet another interface to ONNX?

**Comment by prasanthpul** [comment]
ONNX Runtime is cross platform and runs on Linux, Mac, and Windows. It can integrate with various accelerators like CUDA, TensorRT, nGraph, and OpenVino.

WindowsML is part of the Windows 10 operating system and uses ONNX Runtime internally. It leverages DirectML to provide acceleration on any hardware that supports DirectX 12.

**Comment by JohnCraigPublic** [comment]
prasanthpul - So, just to be clear, If I am a windows desktop developer with an application that wants to do inference on an ONNX model, and I am writing in C/C++ -- then, is it suggested I use "ONNX Runtime C API" or use "WindowsML" ?    Or are they the same thing (if one is on Windows 10 writing C++ code).   If they are different, then why?  Is "WindowsML" yet another wrapping of ONNX?

**Comment by prasanthpul** [comment]
If your app will run on Windows 10 devices and your ONNX models uses the opset supported by Windows, you should use WindowsML. That way you will get hardware acceleration on any GPU that supports DirectX without having to install extra software. See https://docs.microsoft.com/en-us/windows/ai/windows-ml/

If you need to run on other OSs or need to run the latest ONNX version models, then use ONNX Runtime. For GPU acceleration on NVIDIA hardware, you'll need to install CUDA packages.

Hope that helps.

**Comment by Wheest** [comment]
@eundoosong thanks for sharing the Dockerfile.

I have reproduced a simple MWE of it using CMake, [available here](https://github.com/Wheest/onnx-cpp-load-mwe).

On a non-containerised system, I installed Onnx using the `sudo python3 setup.py install` method.

However, compilation of the code fails with 

```
	terminate called after throwing an instance of 'std::system_error'
what():  Unknown error -1
```

The error is not present when onnx_proto is not linked, but it is a necessary dependency.

Any intuitions on what the problem might be?

**Comment by grjulian** [comment]
How do I get the

#include "onnx/onnx.pb.h" ?

I would like to compile a * .onnx file to get some information with a c ++ code.

In my Linux VM I can compile the example code from google without errors:

https://developers.google.com/protocol-buffers/docs/cpptutorial

I would like to compile an pretrained onnx-protobuf-file test.onnx like the addressbook.proto in the excample the same way. But this is not working.

protoc -I=./ --cpp_out=./ ./addressbook.proto

I tried it also with *.pb files but this isn't working either.

Does anybody have some advice for me. How do I get the header / namespace out of the * .onnx-file, to do further analysis?

protoc -I=./ --cpp_out=./ ./test.onnx

is producing a lot of errors like: ... Interpreting non ascii codepoint... I think it's because it is a binary file. But how can I read data out of a pretrained onnx-model?

**Comment by valdemarDuk** [comment]
> ONNX model files are protobuf pb files, you can load them with any protobuf library in any language. In fact, the ONNX checker is implemented in C++. e.g. you can do this to print the number of inputs in a model:
> 
> ```c++
> #include "onnx/onnx_pb.h"
> #include "onnx/proto_utils.h"
> 
> ...
> std::unique_ptr<ModelProto> model(new ModelProto());
> onnx::ParseProtoFromBytes(model.get(), bytes, nbytes);
> 
> std::cout << model->graph().input().size() << std::endl;
> ...
> ```

How would you get access to weights when they're stored in "raw_data" (of the TensorProto message)? I'm trying to store them in an array of doubles. I figured it would be using a method like "google::protobuf::MessageLite::ParseFromString()" but so far no luck in trying to get it to work. any pointers would be greatly appreciated!

**Comment by grjulian** [comment]
Do you know where to get this checker?
I currently have no include files. I can generate them with plaintext protobuf and protoc as mentioned above, but not with the onnx files.

**Comment by jinfagang** [comment]
@prasanthpul  Hi, I am try inference an onnx model using onnxruntime. I can not found any standalone C++ project which using cmake to link the liboonxruntime.a . Does there any standalone project which can using after I built onnxruntime? I want deploy it standalone.

Also, how should I open the backend as TensorRT support when build onnxruntime?

**Comment by prasanthpul** [comment]
@jinfagang please open the issue in https://github.com/microsoft/onnxruntime so the right folks can help you.

**Comment by alrevuelta** [comment]
Answering to the original question `Is there a way to open a model in ONNX format in C/C++ and access its details as easily as in Python? If not, is there any immediate plan for such support?` You can have a look to this [onnx c implementation](https://github.com/alrevuelta/embedded-ml). There is a file that contains debugging tools like `Debug_PrintModelInformation(Onnx__ModelProto *model)` that you can use to print the parameters of your model. Note that you will need to have `protoc` library and `onnx.pb-c.c`/`onnx.pb-c.h` to be able to compile. You might want to read the `doc` section before.

The linked repo aims to provide a pure C99 runtime for onnx with zero dependencies able to run in CPUs without any GPU or accelerators and with the lowest possible footprint. Currently it works with mnist and tinyyolo.

Hope it helps!

**Comment by jianjunjiang** [comment]
This is another library, A lightweight, portable pure C99 onnx inference engine for embedded devices with hardware acceleration support.
[https://github.com/xboot/libonnx](https://github.com/xboot/libonnx)

**Comment by ttanzhiqiang** [comment]
https://github.com/ttanzhiqiang/onnx_tensorrt_project

**Comment by ashwinjoseph95** [comment]
> https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md

Hi Prasanth this link seems broken, could you suggest an alternative place to view the information here.
