### ISSUE TITLE
Concrete Shape Inference

### ISSUE THREAD

**Issue by ganler** [onnx/onnx#4181]
# Ask a Question

### Question

It seems that current shape inference (version 1.11.0) cannot infer all cases, e.g., `Reshape -> Unsqueeze`:

Shape of `Reshape(tensor, target_shape)`

cannot be inferred even if `target_shape` is a constant expression...

<img width="154" alt="image" src="https://user-images.githubusercontent.com/38074777/166330934-c0d8b28b-fbf4-4e04-9ad6-b5101d1f3ca3.png">

```txt
%onnx::Reshape_22[INT64, 1]
%onnx::Unsqueeze_23[FLOAT]
%onnx::Unsqueeze_24[INT64, 1]
%onnx::Gemm_25[FLOAT]
```

So I am curious if there's any runtime to help infer concrete shape information?

cc: @jcwchen

**Comment by jcwchen** [comment]
Hi @ganler,
Have you tried to enable data_prop for [onnx.shape_inference.infer_shapes](https://github.com/onnx/onnx/blob/00738d2032ca0a39d9124b02085a90adda96d018/onnx/shape_inference.py#L27)? If it still doesn't help, probably you can try [SymbolicShapeInference](https://github.com/microsoft/onnxruntime/blob/5023f6750b1078383f60a17bd927ff306f2d4eac/onnxruntime/python/tools/symbolic_shape_infer.py#L2348) from ORT.

**Comment by ganler** [comment]
@jcwchen Thanks for the help. I did not know that before and thank you for letting me know!

**Comment by ganler** [comment]
Unfortunately, both of them did not work. Probably I need to rewrite the ONNX file to mark nodes whose shape information cannot be achieved by the shape inference function, as additional outputs to check their shapes... But really thanks for your info!
