### ISSUE TITLE
tensor.shape[0] return a tensor not a constant

### ISSUE THREAD

**Issue by sjbling** [onnx/onnx#4184]
import torch
image = torch.rand(6,3,64,64).cuda()
.....
torch.onnx.export(model, images,opset_version=13...)

Class Net():

def forward(image):
print(image.shape[0])

Versions
python 3.8.8
torch 1.8.0

**Comment by jcwchen** [comment]
Hi @sjbling,
Seems like a question for PyTorch? The PyTorch-ONNX exporter is under PyTorch repo as well. I saw you has raised this issue there already, which is a better place to track this issue. I will close it here. Feel free to reopen it if you still have other ONNX questions.
