### ISSUE TITLE
onnx.helper.make_graph initializers to inputs

### ISSUE THREAD

**Issue by kartikeyashivigoyal** [onnx/onnx#4186]
# Ask a Question
Is there a way(function) to convert all initializers (operator constants) to inputs in an ONNX graph?

### Question
Explain your question here.

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
- best practices, converters 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @kartikeyashivigoyal,
Perhaps this function (add_input_from_initializer) can help: https://github.com/onnx/onnx/issues/2995#issuecomment-687631931. It was used to solve an IR gap issue by manually adding initializers into inputs. May I understand your use case please? Thanks.
