### ISSUE TITLE
Remove Split op’s dependence on number of outputs

### ISSUE THREAD

**Issue by garymm** [onnx/onnx#4188]
It is desirable to make the behavior of ONNX ops fully determined by its input parameters as well as attributes. The Split op is one of the rare cases where this does not hold. The split op has an optional second parameter that indicates how the split should happen, e.g., into 3 parts of sizes 10, 10, and 4, for example. However, if this parameter is omitted, the current spec says that the split axis is evenly divided among the specified outputs. The behavior is, hence, dependent on the variadic number of outputs specified. It will be cleaner if, instead, we add a specific attribute, say num_outputs, to indicate how many equal parts that the split axis should be divided into.

**Comment by gramalingam** [comment]
Let me clarify the intent here. It is desirable to make the behavior of ONNX ops fully determined by its input parameters as well as attributes. The Split op is one of the rare cases where this does not hold. The split op has an optional second parameter that indicates how the split should happen, e.g., into 3 parts of sizes 10, 10, and 4, for example. However, if this parameter is omitted, the current spec says that the split axis is evenly divided among the specified outputs. The behavior is, hence, dependent on the variadic number of outputs specified. It will be cleaner if, instead, we add a specific attribute, say `num_outputs`, to indicate how many equal parts that the split axis should be divided into.

**Comment by garymm** [comment]
Don't forget the version converter support. Might be non-trivial for this change.

**Comment by gramalingam** [comment]
Yes, the version-converter is non-trivial, but conceptually simple: we should add a num_outputs attribute with value = number of outputs specified in the Node.

**Comment by p-wysocki** [comment]
WIP PR: https://github.com/onnx/onnx/pull/4358

**Comment by p-wysocki** [comment]
PR: https://github.com/onnx/onnx/pull/4481

**Comment by p-wysocki** [comment]
The PR has been merged. Please reopen the issue if needed.
