### ISSUE TITLE
Encoding BFLOAT16 Constant to ONNX Fails 

### ISSUE THREAD

**Issue by manbearian** [onnx/onnx#4189]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug

BFLOAT16 constants are encoded incorrectly when creating tensor initialization data via ONNX Python support. 

This feature was added in v1.11.0 so you need at least that version to reproduce the problem.

I've been able to trace the problem to the following code in `helper.py`. In `make_tensor` there is this code
```Python
        # floa16/bfloat16 are stored as uint16
        elif (data_type == TensorProto.FLOAT16
                or data_type == TensorProto.BFLOAT16):
            vals = np.array(vals).astype(np.float16).view(dtype=np.uint16).flatten().tolist()
```
Notice that the code is converting the value to `np.float16` before writing it out; this is wrong for BFLOAT16 since it doesn't have the same encoding. The result is that this code will write out data in FLOAT16 format when the type is BFLOAT16.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):  N/A
- ONNX version (*e.g. 1.7*):  1.11.0
- Python version: N/A
- GCC/Compiler version (if compiling from source): N/A
- CMake version: N/A
- Protobuf version: N/A
- Visual Studio version (if applicable): N/A

### Reproduction instructions
The following python program reproduces the error when run with ONNX v1.11.0

The program prints the incorrect initialization data and writes out the bad graph to disk (as `test.onnx`)

```Python
import onnx
from onnx import helper, TensorProto

type =  TensorProto.BFLOAT16
dims = [2,2]
input = helper.make_tensor_value_info('input', type, dims, False)

c0 = helper.make_tensor_value_info('c0', type, dims, False)
initializer = helper.make_tensor(c0.name, type, dims, [1.0, 2.0, 3.0, 4.0])

# dims: 2              
# dims: 2              
# data_type: 16        
# int32_data: 15360    | CORRECT_VALUE: 16256 (0x3F80)
# int32_data: 16384    | CORRECT_VALUE: 16384 (0x4000)
# int32_data: 16896    | CORRECT_VALUE: 16448 (0x4040)
# int32_data: 17408    | CORRECT_VALUE: 16512 (0x4080)
# name: "c0"           
print(initializer)

output = helper.make_tensor_value_info('output', type, dims)
add = helper.make_node('Add', [input.name, c0.name], [output.name], 'Add')

graph = helper.make_graph([add], 'test', [input], [output], initializer=[initializer])
model = helper.make_model(graph)

onnx.save(model, 'test.onnx')

```

### Expected behavior
BFLOAT16 should be encoded correctly and the program should print:

```
dims: 2              
dims: 2              
data_type: 16        
int32_data: 16256
int32_data: 16384
int32_data: 16448
int32_data: 16512
name: "c0"           
```

### Notes
There was no FLOAT16 or BFLOAT16 support prior to v1.11.0. Starting in v1.11.0 support was added but the BFLOAT16 encoding support has a bug.

**Comment by manbearian** [comment]
@gramalingam FYI this is the issue i shared with you offline.

**Comment by jcwchen** [comment]
Hi @manbearian,
Thank you for catching this bug. Recently I was reviewing this code and it also seems problematic to me. However, currently there is no bfloat16 support in official NumPy. Do you think it is possible to create a bfloat Constant by ONNX helper with current NumPy (which doesn't have bfloat16 type)? If no, shall we remove this support for now?

**Comment by jcwchen** [comment]
Thank you so much for the update and contribution! That sounds good -- If the upcoming 1.12 release is faster (now targeting 5/23 as code freeze), I will disable bfloat16 support in make_tensor and make it throw a proper error before the code freeze.

**Comment by manbearian** [comment]
Possible fix has been published here: https://github.com/onnx/onnx/pull/4193
