### ISSUE TITLE
some error with onnx transfer to trt

### ISSUE THREAD

**Issue by tongchangD** [onnx/onnx#4205]
some error export
```
[05/19/2022-11:11:38] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
ERROR: builtin_op_importers.cpp:2261 In function importPad:
[8] Assertion failed: mode == "constant" && value == 0.f && "This version of TensorRT only supports constant 0 padding!"
[05/19/2022-11:11:38] [E] Failed to parse onnx file
[05/19/2022-11:11:38] [E] Parsing model failed
[05/19/2022-11:11:38] [E] Engine creation failed
[05/19/2022-11:11:38] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # trtexec --onnx=colorize_infer_model_CPU_sim.onnx --saveEngine=colorize_infer_model_CPU_sim.trt --best
```

How do I convert INT64 to INT32? 
or 
How to fix this type error？

**Comment by tongchangD** [comment]
and environment
```
Input filename:   colorize_infer_model_CPU_sim.onnx
ONNX IR version:  0.0.7
Opset version:    14
Producer name:    pytorch
Producer version: 1.10
Domain:           
Model version:    0
```

**Comment by jcwchen** [comment]
Hi @tongchangD,
Can this ONNX model pass onnx.checker with full_check? If yes, then probably it's a valid model and this should be a question for the converter ([onnx-tensorrt](https://github.com/onnx/onnx-tensorrt)) since this error happened during conversion. I would suggest you raise this issue there to get best help from the converter experts.

**Comment by jackwish** [comment]
@tongchangD Thank you for reporting this issue! As indicated in the log, non-0 padding value is unsupported in TensorRT 7.2. Could you please try if TensorRT 8.2 or 8.4 resolves you issue?

@jcwchen Could you please move this issue to https://github.com/onnx/onnx-tensorrt if possible?

**Comment by tongchangD** [comment]
thanks

**Comment by jcwchen** [comment]
> @jcwchen Could you please move this issue to https://github.com/onnx/onnx-tensorrt if possible?

Sorry I don't have permission for onnx-tensorrt so I cannot transfer this issue there

**Comment by tongchangD** [comment]
Thank you for your reply.
sorry ,This is Tensorrt's mistake,Someone say that upgrading Tensorrt can solve this problem，so I upgrade  tensorrt==8.2.0 and i solved  this problem.
