### ISSUE TITLE
Does ONNX only support Multihead Self-Attetion?

### ISSUE THREAD

**Issue by yq-Liang** [onnx/onnx#4207]
Hi ONNX community！
I am trying to convert a torch net to onnx, however i meet a problem about multihead attention.
When i convert the torch.nn.MultiheadAttention(), if the value of "key" and value of "value" aren't the same,there will be a warning and  an error:
[W ..\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:419] Warning: Constant folding in symbolic shape inference fails: expected scalar type Long but found Float
Exception raised from data_ptr at aten\src\ATen\core\TensorMethods.cpp:5759 (most recent call first):
RuntimeError: expected scalar type Long but found Float.

Does ONNX only support Multihead Self-Attetion? Could you please tell me what i can do?Thanks a lot.

**Comment by jcwchen** [comment]
Hi @yq-Liang,
It should be a question for the exporter (PyTorch-ONNX exporter) since this error happened during conversion. Could you please raise this issue in PyTorch repo instead to get the best assistance from them? (PyTorch-ONNX exporter is under PyTorch repo) Thanks!

**Comment by yq-Liang** [comment]
There is an [answer](https://github.com/pytorch/pytorch/issues/78060#issuecomment-1138862902)

**Comment by dfiru** [comment]
Is there any plan to have a self-attention op in pytorch?

**Comment by dfiru** [comment]
the problem is w/ llama2 and other larger models being open sourced, the resulting ort is incredibly difficult to navigate w/o a native SA op. this onnx should actually be a lot simpler than it looks. 
[llama-2-7b-hf.onnx.zip](https://github.com/onnx/onnx/files/12185843/llama-2-7b-hf.onnx.zip)

**Comment by jcwchen** [comment]
Thanks for the context and yes I think it's a fair reason. Feel free to raise [an independent issue](https://github.com/onnx/onnx/issues/new?assignees=&labels=operator&projects=&template=operator.md&title=) in onnx repo to track this new operator request.

**Comment by nicholaiTukanov** [comment]
I agree with @dfiru. Having attention as an onnx op would also help projects like onnx-mlir to have better lowering schemes.

Has there been any progress on adding this as an operation?

**Comment by dfiru** [comment]
Created a new issue for this: https://github.com/onnx/onnx/issues/5449
