### ISSUE TITLE
Alternative to ConstantOfShape operator

### ISSUE THREAD

**Issue by FabioRomagnolo** [onnx/onnx#4208]
Hi!
I'm trying to execute ONNX models in webgl javascript environment. The problem is that only int32 is supported.
I already succeeded in converting int64 inputs to int32 inputs, but ConstandOfShape node only support int64 input.

So my question is: with which nodes can i replace this node in a script like this?

    for i in range(len(nodes)):
        if nodes[i].op_type == "ConstantOfShape":
            idxs_tofix.append(i)

    for i in idxs_tofix:
        nodes[i] = ...

Thank you!

**Comment by Cortexelus** [comment]
I have the same problem.
According to https://fdwr.github.io/LostOnnxDocs/OperatorFormulas.html
`ConstantOfShape(scalarTensorValue, inputOfDesiredShape) = Expand(scalarTensorValue, Shape(inputOfDesiredShape))` I'm not sure how to swap out onnx ops like this, so I'd like to see an implementation of the fix

**Comment by Cortexelus** [comment]
Hm expand isn't supported either with onnxruntime web using webGL 
`failed to inference ONNX model: TypeError: cannot resolve operator 'Expand' with opsets: ai.onnx v14.`

**Comment by FabioRomagnolo** [comment]
I've done further research and it seems that unfortunately too many operators are not supported in webGL by ONNX Runtime Web...
According to https://github.com/microsoft/onnxruntime/blob/master/js/web/docs/operators.md the list of unavailable operators it's very long, so I thinking to abandon the solution implemented with ONNX Runtime Web since I wasted 1-2 weeks trying to convert a single operator in 32 bit.
The model I'm trying to run in webgl requires 11 actually unsupported operators by ONNX Runtime Web.

I keep you updated if I find another solution for the operators' incompatibility with webGL.

**Comment by FabioRomagnolo** [comment]
You can't cast the shape to 64-bit if you are executing in webgl environment.
This is the reason why ONNX Runtime Web has so many limitations in javascript+webgl environment.

**Comment by FabioRomagnolo** [comment]
Wow, thank you! This is actually an amazing library!
Unfortunately there are still unsopperted nodes by webgl, but this is anyway an amazing optimization for the graph.
