### ISSUE TITLE
BatchNormalization failed when loading Caffe2 model converted from ONNX

### ISSUE THREAD

**Issue by lastlaugher** [onnx/onnx#421]
I converted ONNX format to Caffe2 format. And then, when I load caffe2 model, I've got below error messages.

> WARNING: Logging before InitGoogleLogging() is written to STDERR
E0115 13:50:47.453927  5523 operator.cc:130] Cannot find operator schema for BatchNormalization. Will skip schema checking.
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at operator.cc:190] op. Cannot create operator of type 'BatchNormalization' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "267" input: "3" input: "4" input: "5" input: "6" output: "269" name: "" type: "BatchNormalization" arg { name: "is_test" i: 1 } arg { name: "epsilon" f: 1e-05 } arg { name: "momentum" f: 0.9 } device_option { device_type: 1 }
Aborted (core dumped)

When I did same thing a few month ago, it worked fine. It converted BatchNormalization in ONNX to SpatialBN in Caffe2. However, the latest version of ONNX has this mis-conversion issue.

**Comment by bddppq** [comment]
It's very likely your onnx-caffe2 version is too old. In the current master (and also in the latest released version) onnx-caffe2 converts ONNX's BatchNormarlization to SpatialBN:
https://github.com/onnx/onnx-caffe2/blob/f410acde8840bea64df192fdf275888ff48adc85/onnx_caffe2/backend.py#L134

**Comment by lastlaugher** [comment]
@bddppq, big thanks. After I updated onnx_caffe2, it's working fine.
