### ISSUE TITLE
shape_inference failed with ONNX1.11.0

### ISSUE THREAD

**Issue by mengniwang95** [onnx/onnx#4215]
# Bug Report

### Describe the bug
[TypeInferenceError] Cannot infer type and shape for node name resnetv17_conv0_fwd. No opset im
port for domain optype Conv with ONNX1.11.0
But can work with ONNX 1.10.0

### System information
- ONNX version (*e.g. 1.7*):  1.11.0

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx import shape_inference
model = onnx.load('model.onnx')
shape_inference.infer_shapes(model)
```
model path: https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet50-v1-12.onnx

**Comment by jcwchen** [comment]
Hi @mengniwang95,
Actually I cannot reproduce this error. ONNX 1.11 works fine with `resnet50-v1-12.onnx` from my end. And ONNX weekly CI does routinely check ONNX Model Zoo models with latest commit by onnx.checker and onnx.shape_inference to prevent issues: https://github.com/onnx/onnx/actions/workflows/weekly_mac_ci.yml. Could you please confirm this bug again? Thanks!

**Comment by mengniwang95** [comment]
Hi @jcwchen , sorry for my mistake, it should be another rn50 model, and its(the first) difference with https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet50-v1-12.onnx(the second) is:
![image](https://user-images.githubusercontent.com/65003808/170165421-ce10b5d4-4fc1-4095-b099-574672ed1813.png)
![image](https://user-images.githubusercontent.com/65003808/170166285-b5d1c546-4621-493a-88ff-2ca6d74da9ea.png)

I want to upload the file but it is too large to upload.

**Comment by jcwchen** [comment]
No worries. I would be surprise if the is an original ONNX Model Zoo model fails with onnx.shape_inference (which means there is something wrong in the CI).

So how can I get this model and reproduce this issue? Do you have any handy code for modification? I tried to modify the original model with ir_version, and both ir_version 3 and ir_version 4 worked from my end.

**Comment by mengniwang95** [comment]
The failed model is generated by this way:
```bash
wget https://github.com/onnx/models/raw/main/vision/classification/resnet/model/resnet50-v1-7.onnx
```

```python
import onnx
model = onnx.load('resnet50-v1-7.onnx')
onnx_domain = "ai.onnx"
onnx_op_set_version = 12

opset_info = next((opset for opset in model.opset_import if opset.domain == '' or opset.domain == onnx_domain), None)
if opset_info is not None:
    model.opset_import.remove(opset_info)
    model.opset_import.extend([onnx.helper.make_opsetid("onnx_domain ", onnx_op_set_version)])
onnx.save(model, 'new_model.onnx')
```
Can you explain why this will lead to failure?

**Comment by jcwchen** [comment]
Thank you for providing the repro code! I can reproduce this issue. The reason is both "ai.onnx" and "" refer to default ONNX domain, but the domain check in shape_inference does not handle that. This PR should fix this: https://github.com/onnx/onnx/pull/4224.
