### ISSUE TITLE
some export error with batch_norm

### ISSUE THREAD

**Issue by tongchangD** [onnx/onnx#4217]
# Ask a Question

### Question
I was building this and encountered the following problem when PTH was transferred to ONNX.

```
RuntimeError: Unsupported: ONNX export of batch_norm for unknown channel size.
```

### Further information
in [Face_Enhancement](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/tree/master/Face_Enhancement).

### Notes
Any additional information, code snippets.
my export code
```
torch.onnx.export(self.netG, face, "./Face_Enhancement_Setting_9_epoch_100_latest_net_G_model.onnx",
                  verbose=False,
                  opset_version=13,
                  export_params=True, do_constant_folding=True,
                  input_names=["image"],
                  output_names=["output"]
                  )
```
or 
```
torch.onnx.export(self.netG, data_i, "./Face_Enhancement_Setting_9_epoch_100_latest_net_G_model.onnx",
                  verbose=False,
                  opset_version=13,
                  export_params=True, do_constant_folding=True,
                  input_names=["image","label"],
                  output_names=["output"]
                  )
```

**Comment by jcwchen** [comment]
Hi @tongchangD,
This should be a question for the converter (PyTorch-ONNX exporter) since this error happened during conversion. Could you please raise this issue in PyTorch repo (PyTorch-ONNX exporter is there) instead to get better assistance from them? Thanks.

**Comment by tongchangD** [comment]
@jcwchen 
thanks, try it

**Comment by jcwchen** [comment]
Close it since it should be a question for the exporter. Feel free to reopen it if you still have other ONNX questions.

**Comment by sssyousen** [comment]
> @jcwchen thanks, try it

你有解决这个问题吗？ 我也碰到了类似的问题。
