### ISSUE TITLE
how an i get input.w

### ISSUE THREAD

**Issue by Muxindawang** [onnx/onnx#4218]
# Ask a Question

### Question
how can i get w.type, I can get name using node.input, but when i use node.input.type  there are some error happend. 
Can I modify w's dimension directly？
![image](https://user-images.githubusercontent.com/48120360/169989910-43f5c890-7398-425d-94a8-7682c7ce35ef.png)
![image](https://user-images.githubusercontent.com/48120360/169989807-d39cdd79-055f-4567-b880-4133af785d0a.png)
![image](https://user-images.githubusercontent.com/48120360/169991330-881f91f9-2067-486e-b01e-20c6d9928a4d.png)

**Comment by Muxindawang** [comment]
> Hi @Muxindawang, As you can see in the Netron, actually `backbone.sa_modules.0.confidence_mlp.0.weight` is an initializer... So if you really want to modify it, you need to traverse `onnx_model.graph.initializer` to get this initializer and then modify it, but please note that it is possible that other nodes use this initializer as well, which might cause issues.

Thank you very much, I have found the target weight by traversing initialize, but how can I modify its dimensions? Are there functions available directly? Or do I have to crop out the current convolution and reinsert a new one?

**Comment by Muxindawang** [comment]
> Hi @Muxindawang, As you can see in the Netron, actually `backbone.sa_modules.0.confidence_mlp.0.weight` is an initializer... So if you really want to modify it, you need to traverse `onnx_model.graph.initializer` to get this initializer and then modify it, but please note that it is possible that other nodes use this initializer as well, which might cause issues.

Whether it is possible to reinitialize weight？

**Comment by Muxindawang** [comment]
> Yes in that case at least you can utilize helper.make_node and helper.make_initializer to easily create new nodes with desired shapes. Just please note that you need to make the nodes topological-sorted while inserting new node.
Thank you very much, I have completed the modification of the model. I first clipped out the previous conv1d, then modified the corresponding initializer (with helper.make_tensor) and added a conv2d (with helper.make_node).

**Comment by Muxindawang** [comment]
> You can always modify the graph (Protobuf object) in place, but there is no fancy API to update its attributes, which means probably you will need to update the dimensions one by one -- assign new values to them.
> 
> > Or do I have to crop out the current convolution and reinsert a new one
> 
> Yes in that case at least you can utilize helper.make_node and helper.make_initializer to easily create new nodes with desired shapes. Just please note that you need to make the nodes topological-sorted while inserting new node.

Thank you very much, I have completed the modification of the model. I first clipped out the previous conv1d, then modified the corresponding initializer (with helper.make_tensor) and added a conv2d (with helper.make_node).

**Comment by jcwchen** [comment]
It seems this issue has been resolved so I will close here now. Please reopen it if you still have other ONNX questions. Thanks!
