### ISSUE TITLE
multi-gpu

### ISSUE THREAD

**Issue by milad1378yz** [onnx/onnx#4220]
# Ask a Question

### Question
Hi, is there any way to run a large ONNX model in multi-GPU?
 in short form, I want to convert a model to its subgraphs and then get inference from this model in for example 2 GPUs.

**Comment by jcwchen** [comment]
Hi @milad1378yz,
It seems ONNX Runtime does support it to some extent: https://github.com/microsoft/onnxruntime/issues/8244#issuecomment-873276249. If you still have more related questions, you can ask help in the issue there.
