### ISSUE TITLE
About QuantizeLinear rounding rule...

### ISSUE THREAD

**Issue by developerChans** [onnx/onnx#4225]
# Ask a Question

### Question

[QuantizeLinear ](https://github.com/onnx/onnx/blob/main/docs/Operators.md#QuantizeLinear)

I had a question about operator while using onnx . In operator QuantizeLinear's description, "For (x / y_scale), it's rounding to nearest ties to even." There is an explanation. The 'Rounding Rule' in this syntax is difficult to understand because I have never encountered it. You ask how the 'Rounding Rule' should be applied.

**Comment by yufenglee** [comment]
Are you asking what 'rounding to nearest ties to even' means? It is round half to even in the wiki: https://en.wikipedia.org/wiki/Rounding#Round_half_to_even

**Comment by developerChans** [comment]
I was curious about QlinearAdd's rounding rule, so QuantizeLinear has a similar rounding rule and I left it in an issue. I found a solution for that part by leaving an issue again in onnx_runtime. Sorry for asking the other way around.

[here](https://github.com/microsoft/onnxruntime/issues/11759)
