### ISSUE TITLE
How should i implement a new operator, like multihead-attention?

### ISSUE THREAD

**Issue by lzu-zhanghr** [onnx/onnx#4227]
# How should i implement a new operator, like multihead-attention?

### Question:
Where should my new operator inference script be, in def.cc file ?

I only find the position of shapeinferencefunction in def.cc,  and i am no idea about inference function position

**Comment by jcwchen** [comment]
Hi @lzu-zhanghr,
You can check this document: https://github.com/onnx/onnx/blob/main/docs/AddNewOp.md#step-2-submit-pr-. The shape inference function can be defined in TypeAndShapeInferenceFunction. Take TopK as an example: [here](https://github.com/onnx/onnx/blob/f81558d4b24e910cbd05990f09e4ae78b7452560/onnx/defs/math/defs.cc#L1264-L1321).

**Comment by lzu-zhanghr** [comment]
Thank you

**Comment by jcwchen** [comment]
It seems resolved. I will close this issue now. Please reopen it if you still have questions. Thanks!

**Comment by lzu-zhanghr** [comment]
After implementing a new operator, i cannot build onnx from source script when i run update_doc.py script.
However, i never change any code of corresponding sequence def.cc file.

![Screenshot from 2022-06-08 16-22-44](https://user-images.githubusercontent.com/45324813/172572014-9adb7511-dd61-4e6d-a5c7-dbde2764fd20.png)

**Comment by jcwchen** [comment]
Will continue this discussion in another [issue](https://github.com/onnx/onnx/issues/4257).
