### ISSUE TITLE
When can onnx support AdaptiveAvgPool?

### ISSUE THREAD

**Issue by chen990627** [onnx/onnx#4229]

**Comment by jcwchen** [comment]
Hi @chen990627,
IIUC, AdaptiveAvgPool from PyTorch can be represented as existing ONNX operators and also such a [conversion](https://github.com/pytorch/pytorch/blob/161e931156744acc384ce14e410d3d27d289109a/torch/onnx/symbolic_opset9.py#L1213) is supported by the PyTorch-ONNX exporter now. May I ask you what kind of support you are looking for?
