### ISSUE TITLE
Nested Loop and dynamically modified matrix

### ISSUE THREAD

**Issue by alvaro-budria** [onnx/onnx#4230]
Is it possible to define a computational graph containing a nested loop with ONNX? Moreover, is it possible to modify a matrix position indexed by the inner and outer loops' indexes?
From what I read in [this issue](https://github.com/onnx/onnx/issues/140) it seems that ONNX should already support such a feature (for instance RNNs should be using it already), but I am failing to see how to extend the examples provided for a single Loop to nested loops, and I could not find any example code where a nested loop is defined with ONNX.

For context, I am trying to implement the vanilla Dynamic Time Warping with ONNX:

```
int DTWDistance(s: array [1..n], t: array [1..m]) {
    DTW := array [0..n, 0..m]
    
    for i := 0 to n
        for j := 0 to m
            DTW[i, j] := infinity
    DTW[0, 0] := 0
    
    for i := 1 to n
        for j := 1 to m
            cost := d(s[i], t[j])
            DTW[i, j] := cost + minimum(DTW[i-1, j  ],    // insertion
                                        DTW[i  , j-1],    // deletion
                                        DTW[i-1, j-1])    // match
    
    return DTW[n, m]
}
```

I was thinking of "flattening" the 2D matrix into a 1D array and use just one single Loop, however this makes things a bit more involved and I was hoping there could be a more straightforward answer.

Any pointers or code snippets both for nested loops and dynamically modifying a matrix inside a loop would be appreciated. Thanks!

**Comment by gramalingam** [comment]
I think this can be coded up in ONNX. But what backend do you plan to use it with? That's going to significantly affect the efficiency of execution. With an interpreted backend, the costs of interpreting a loop can be high.

Algorithmically speaking, it seems to me that this dynamic-programming solution proceeds in a wave-like fashion along the diagonals, each diagonal can be computed (in parallel) from the previous two diagonals. That could be one possible encoding, though it may be hard to capture this kind of algorithmic behavior in ONNX, without some kind of "shift" operators.

**Comment by alvaro-budria** [comment]
Hi @gramalingam, I plan to use this on a regular laptop or on an AWS lambda instance, with code either on Python or JavaScript.

Regarding what you said about computing the solution along the diagonals, I am aware that it can allow for parallel computing (as explained for instance in [this paper](https://archives.ismir.net/ismir2020/paper/000343.pdf). But for now all I really need is to see how to go about coding this in ONNX and producing a solution based on nested loops.

I can't seem to find any example code where an ONNX graph is generated containing nested loops. Do you know any current implementations that I can learn from?

**Comment by gramalingam** [comment]
ONNX is just an IR/spec. Are you planning to use onnxruntime or some other backend to execute the ONNX models? My point is that generally using ONNX loops to iterate over the elements of a tensor is not a good idea (from a performance perspective). The typical usage is to have loops where each iteration executes (expensive) tensor-operations, so the loop-iteration overhead is not a concern. If each iteration updates a single element of a tensor, that doesn't seem appropriate (unless  one uses some backend based on optimizing compilers that can generate efficient code for the loops).

**Comment by alvaro-budria** [comment]
@gramalingam Yes, I'm planning to use onnxruntime for doing inference. 
So implementing DTW with two loops is not the best way as it modifies one single element of the tensor per iteration. In that case, can you please expand on these "shift" operators and how you think they could be applied here?
