### ISSUE TITLE
How to dump ONNX model / graph to textual syntax?

### ISSUE THREAD

**Issue by Lyken17** [onnx/onnx#4231]
In the https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#onnx-parser section, there is an example showing that we can convert a textual representation (in ONNX syntax) to ONNX model / graph

```
input = '''
   agraph (float[N, 128] X, float[128, 10] W, float[10] B) => (float[N, 10] C)
   {
        T = MatMul(X, W)
        S = Add(T, B)
        C = Softmax(S)
   }
'''
graph = onnx.parser.parse_graph(input)
```

However, I tried to search docs and test cases and didn't find a way to perform the conversion vice versa. For example, is there any api can achieve following operations?

```
graph.dump_to_text() #? Just a sample API, will not work
'''
   agraph (float[N, 128] X, float[128, 10] W, float[10] B) => (float[N, 10] C)
   {
        T = MatMul(X, W)
        S = Add(T, B)
        C = Softmax(S)
   }
'''
```

**Comment by jcwchen** [comment]
Hi @Lyken17,
[onnx-parser](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#onnx-parser) was created for easier ONNX graph creation (text -> ONNX proto). Reverse conversion is not supported now.

**Comment by Lyken17** [comment]
Thanks @jcwchen 's quick response!

Actually stringfy conversion should be easier parser? I feel this would be a nice feature to have as the stringfied text are much more readable than current onnx json-like output and many other frameworks (e.g., tvm) supports such functions. 

How can I submit a feature request for this utility?

**Comment by gramalingam** [comment]
Just to clarify: the reverse (pretty printing) is supported in C++ (see: https://github.com/onnx/onnx/blob/main/onnx/defs/printer.h ), but it has not yet been exposed in Python. I am planning on creating a PR soon to expose at least the top-level print methods (for model/graph) to Python

**Comment by Lyken17** [comment]
Looking forward to it.  Please let me know once the PR is merged!
