### ISSUE TITLE
Support different modes for float to bfloat conversion

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#4237]
# Feature Request

As discussed in the recent PR https://github.com/onnx/onnx/pull/4193 , it would be good to extend the utility function for converting float32 to bfloat16 to support different modes (e.g., truncation vs rounding; the treatment of NaN could potentially lead to distinguishing pure-truncation vs. truncation with correct NaN handling).

**Comment by jcwchen** [comment]
I guess this has been handled by Ian's fresh PR: https://github.com/onnx/onnx/pull/4238? If yes, feel free to close it. Thanks!
