### ISSUE TITLE
Upgrade Protobuf to make ONNX compatible with Protobuf 4.21+

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4239]
# Feature Request
Now ONNX uses Protobuf 3.16, which is not fully compatible with the latest Protobuf v21. because there are some breaking changes. The required Protobuf version was frozen for now: https://github.com/onnx/onnx/blob/main/requirements.txt. At some point ONNX should upgrade its Protobuf to version 4. Open this issue to track this work item.

**Comment by wild-endeavor** [comment]
hi @jcwchen - do you think the pr will be closed soon?  we're working on an integration between flytekit and onnx and we've internally just bumped proto to 4.x - would be great if onnx supported it as well.  Thank you.

**Comment by jcwchen** [comment]
Hi @wild-endeavor,
ONNX has just released fresh ONNX 1.13 today which is still using Protobuf 3.20 so this Protobuf 4.21 upgrade won't happen soon. Still, we will review this request again in the next release and keep you posted (update in this channel).

**Comment by fg91** [comment]
> Hi @wild-endeavor, ONNX has just released fresh ONNX 1.13 today which is still using Protobuf 3.20 so this Protobuf 4.21 upgrade won't happen soon. Still, we will review this request again in the next release and keep you posted (update in this channel).

@jcwchen is there an update on whether this will be included in the next release? I would really need this as well 🙏 
Thank you

**Comment by jcwchen** [comment]
@fg91 unfortunately we don't have a concrete date for this upgrade yet. It really depends on when the whole ONNX ecosystem is ready (PyTorch and TensorFlow are still using quite old version of Protobuf). I will try to reach out relevant team to understand whether there is any concern about this upgrade. Thank you for your interest and waiting!

**Comment by fg91** [comment]
> @fg91 unfortunately we don't have a concrete date for this upgrade yet. It really depends on when the whole ONNX ecosystem is ready (PyTorch and TensorFlow are still using quite old version of Protobuf). I will try to reach out relevant team to understand whether there is any concern about this upgrade. Thank you for your interest and waiting!

Thanks 🙏 
Tensorflow adopted protobuf 4.x as of [three weeks ago](https://github.com/tensorflow/tensorflow/issues/56815#issuecomment-1409090359), not released yet though.

**Comment by jcwchen** [comment]
@fg91 That's great to know! Thank you for the information. I will focus on the PyTorch part then.

**Comment by fg91** [comment]
@jcwchen I saw that you [recently removed the `protobuf<4` restriction](https://github.com/onnx/onnx/commit/a220317da13d5d00870f5b4a8a45f3304a6097d2). Is there any chance you could do a patch release with this change please? 🙈 🙏

**Comment by jcwchen** [comment]
> @jcwchen I saw that you [recently removed the protobuf<4 restriction](https://github.com/onnx/onnx/commit/a220317da13d5d00870f5b4a8a45f3304a6097d2). Is there any chance you could do a patch release with this change please? 🙈 🙏

Yes, we will have the ONNX 1.14.0 release very soon with this update. Hopefully it can be done this week. Thanks for waiting.

**Comment by jcwchen** [comment]
@fg91 The fresh ONNX 1.14.0 is out last night and it should be compatible with Protobuf v21. I will close this issue. Please let me know if any of you bump into any issue. Thank you all for waiting!

**Comment by fg91** [comment]
> @fg91 The fresh ONNX 1.14.0 is out last night and it should be compatible with Protobuf v21. I will close this issue. Please let me know if any of you bump into any issue. Thank you all for waiting!

Thank you! Will try first thing next week 🙏
