### ISSUE TITLE
Abstract (opaque) data types

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#425]
This is a joint proposal with @linkerzhang 

**Motivation.**

* We'd like to get rid of ONNX-ML variant of the ONNX protobuf. At the moment, the reason we need a separate protobuf for ONNX-ML in order to support two new dynamic types for `Sequence` and `Map`, which we did not want to put into into the mainline ONNX spec because we did not want to force non traditional ML vendors to support these as dynamic evolving types,

* In some cases, a user may need to pass an abstract blob of data from one operator to another to unblock themselves prior to standardizing this data format. At the moment, they have no way to do so without extending the protobuf format (in the same way that ONNX-ML does.)

**Mechanics.** Today, the data model of all values which flow through an ONNX model is hard-coded by `TypeProto`:

```
message TypeProto {
  message Tensor {
    // This field MUST NOT have the value of UNDEFINED
    // This field MUST be present for this version of the IR.
    optional TensorProto.DataType elem_type = 1;
    optional TensorShapeProto shape = 2;
  }
  oneof value {
    // The type of a tensor.
    Tensor tensor_type = 1;
  }
}
```

We propose to add a new variant to this

```
message TypeProto {
  message Tensor ...
  message Abstract {
    string domain,
    string abs_type
  }
  oneof value {
    // The type of a tensor.
    Tensor tensor_type = 1;
    Abstract abstract_type = 3; // (don't reuse ONNX-ML numbers)
  }
}
```

If you want to declare an abstract type as an output or input, you write a message as follows:

```
type = {
  abstract_type = {
    domain = "ai.onnx.ml",
    name = "Map"
  }
}
```

It is not possible to specify an abstract type initializer, and you are expected to define custom operators which manipulate the abstract type in question.

**Comment by linkerzhang** [comment]
Thank you very much! @ezyang  This perfectly aligns with our current type system/verification :).

In our current type system, we use "DataType" (which is actually a global string pointer) to represent a type (say, "tensor(float)", "tensor(int32)", etc).  see, static DataType ToType(const TypeProto& type_proto); in data_type_utils.h. When loading a model, type verification could be done by pointer equal check as well as type inference.

**Comment by gramalingam** [comment]
Yes, we need an extensibility mechanism for types as well. This looks good to me.
