### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by davidmezzetti** [onnx/onnx#4250]
Do you have an estimate on when the next release will be? Most projects would consider the recent protobuf issue (https://github.com/onnx/onnx/pull/4223) a breaking change warranting a dot release. Otherwise, projects are required to limit the version of protobuf being used when they may not even know it's a dependency.

Thank you for any clarity you can provide and thank you for your support, this is a great project!

**Comment by jcwchen** [comment]
Hi @davidmezzetti,
ONNX 1.12 release branch has been cut a few days ago ([Logistics](https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.12.0)) and the Protobuf version fix in requirements.txt was included. I think the official ONNX 1.12 will be released in 2-3 weeks after the release candidate has been well tested.

**Comment by davidmezzetti** [comment]
Thank you, appreciate the update!

**Comment by jcwchen** [comment]
ONNX just released 1.12.0, which has the proper Protobuf version restriction to prevent error in Python Protobuf>=4.21. Thanks for waiting! Close here now. Please reopen it if you still see any issue.

**Comment by davidmezzetti** [comment]
Thank you!
