### ISSUE TITLE
cannot build onnx from source script 

### ISSUE THREAD

**Issue by lzu-zhanghr** [onnx/onnx#4257]
# Bug Report

After implementing a new operator, i cannot build onnx from source script when i run update_doc.py script.
However, i never change any code of corresponding sequence def.cc file.

![Screenshot from 2022-06-08 16-22-44](https://user-images.githubusercontent.com/45324813/172570038-90a53e69-6359-484f-8dd5-67d17b344aa1.png)

error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’) seq_at_node.add_output(g_inputs[inputIndex].name());

**Comment by jcwchen** [comment]
Hi @lzu-zhanghr,
It might be an issue related to old Protobuf version. What's your Protobuf version? The recommend Protobuf version to build ONNX from source is 3.16-3.20.

**Comment by lzu-zhanghr** [comment]
> Hi @lzu-zhanghr, It might be an issue related to old Protobuf version. What's your Protobuf version? The recommend Protobuf version to build ONNX from source is 3.16-3.20.

My Protobuf version is 3.19.4.
When i change my Protobuf version from 3.19.4 to 3.16.0, it does not work.

**Comment by jcwchen** [comment]
Thanks for the info! Could you please try this command: `protoc --version` to check the version again?

**Comment by lzu-zhanghr** [comment]
> Thanks for the info! Could you please try this command: `protoc --version` to check the version again?

libprotoc verison is 3.0.0,
i am reinstalling from source script.

**Comment by lzu-zhanghr** [comment]
Thanks for your guidance.
After successfully building  onnx project, I cannot import custom operator from dynamic library when i try to generate test case.

![Screenshot from 2022-06-10 18-03-46](https://user-images.githubusercontent.com/45324813/173042407-3c153852-8fbc-42fe-9c5f-75062fad73f3.png)

**Comment by jcwchen** [comment]
Have you registered the schema in this [file](https://github.com/onnx/onnx/blob/a92870cdf359297495a118184dca2eaecee4b717/onnx/defs/operator_sets.h#L988)?

**Comment by lzu-zhanghr** [comment]
Yes, I have registered my custom operator in operator_sets.h file.
I would appreciate it if you could help me to check [my script](https://github.com/onnx/onnx/compare/main...lzu-zhanghr:main).

**Comment by lzu-zhanghr** [comment]
> Have you registered the schema in this [file](https://github.com/onnx/onnx/blob/a92870cdf359297495a118184dca2eaecee4b717/onnx/defs/operator_sets.h#L988)?

Yes, I have registered my custom operator in operator_sets.h file.
I would appreciate it if you could help me to check [my script](https://github.com/onnx/onnx/compare/main...lzu-zhanghr:main).

**Comment by jcwchen** [comment]
Thanks for providing the details. They seem fine to me. Could you please remove all ONNX packages you have, `git clean -xdf` under your ONNX directory, and then `pip install -e .` to build ONNX from source again?

**Comment by jcwchen** [comment]
Aha! I might find the issue -- `MultiHeadAttenton` is a typi operator_sets.h. Correct it should help.

**Comment by lzu-zhanghr** [comment]
> Aha! I might find the issue -- `MultiHeadAttenton` is a typo operator_sets.h. Correct it should help.

Sorry, I am no idea about the typo about the typo operator_sets.h. 
Is there a syntax or grammer error in operator_sets.h file ?

**Comment by jcwchen** [comment]
I saw you have corrected the right operator name -- did you still encounter any issue?

**Comment by lzu-zhanghr** [comment]
> I saw you have corrected the right operator name -- did you still encounter any issue?

i cannot regenerate test data

**Comment by jcwchen** [comment]
It's an error about Python Protobuf. (There are some breaking changes in the latest 4.21) Please use `pip show protobuf` to see your Python protobuf version. If it is >=4.21, please use `pip install protobuf==3.20` to use older Protobuf version.

**Comment by lzu-zhanghr** [comment]
> It's an error about Python Protobuf. (There are some breaking changes in the latest 4.21) Please use `pip show protobuf` to see your Python protobuf version. If it is >=4.21, please use `pip install protobuf==3.20` to use older Protobuf version.

Thanks for your help in a long time.

**Comment by lzu-zhanghr** [comment]
Thanks for your help in a long time. 

> It's an error about Python Protobuf. (There are some breaking changes in the latest 4.21) Please use `pip show protobuf` to see your Python protobuf version. If it is >=4.21, please use `pip install protobuf==3.20` to use older Protobuf version.

**Comment by lzu-zhanghr** [comment]
![image](https://user-images.githubusercontent.com/45324813/174699645-8399c643-b914-485f-a002-183fe7bd5936.png)

I am no idea about [this error](https://dev.azure.com/onnx-pipelines/onnx/_build/results?buildId=26139&view=logs&j=26ad7b42-9ea7-5ad4-891d-e581c481314e&t=36dc6483-53ad-5f31-0c8e-c9104543cd82&l=257): git diff returned error.

**Comment by aurelien-m** [comment]
> > Thanks for the info! Could you please try this command: `protoc --version` to check the version again?
> 
> libprotoc verison is 3.0.0, i am reinstalling it from source script.

I'm also having the same issue when building `onnx`. I have `protoc --version 3.0.0`, did you reinstall `protoc`?

**Comment by aurelien-m** [comment]
> > > Thanks for the info! Could you please try this command: `protoc --version` to check the version again?
> > 
> > 
> > libprotoc verison is 3.0.0, i am reinstalling it from source script.
> 
> I'm also having the same issue when building `onnx`. I have `protoc --version 3.0.0`, did you reinstall `protoc`?

I solved my problem. I just installed the same `protoc` version (3.19.4) as the one I have with `pip` by [building it from the sources](https://askubuntu.com/questions/1072683/how-can-i-install-protoc-on-ubuntu-16-04).

**Comment by jcwchen** [comment]
I will close this one since it seems to be solved. Feel free to reopen it if you still have other ONNX questions. One thing I would like to mention is that the current main branch should be compatible even for protoc version 3.0.0 after this PR: https://github.com/onnx/onnx/pull/4354.
