### ISSUE TITLE
Inferred shape and existing shape differ in dimension 0: (1) vs (-1)

### ISSUE THREAD

**Issue by zhoutianzi666** [onnx/onnx#4272]
# Bug Report

### Is the issue related to model conversion?

no

### Describe the bug

when I use `shape_inference.infer_shapes` to infer my onnx model, it reportes Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
the output of gather -1 means the value can be arbitrary, so  why compare them？？

<img width="585" alt="image" src="https://user-images.githubusercontent.com/39978853/173544394-b444b4d2-d464-42e7-ad8f-7818a0becb9e.png">

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 18.04.5
- ONNX version (*e.g. 1.7*):1.9.0  
- Python version:3.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx.tools import update_model_dims
import numpy as np
import onnx.helper as helper
from onnx import shape_inference, TensorProto
import sys

print(onnx.__version__)

ONNX_DTYPE = {
    0: TensorProto.FLOAT,
    1: TensorProto.FLOAT,
    2: TensorProto.UINT8,
    3: TensorProto.INT8,
    4: TensorProto.UINT16,
    5: TensorProto.INT16,
    6: TensorProto.INT32,
    7: TensorProto.INT64,
    8: TensorProto.STRING,
    9: TensorProto.BOOL
}

# load model
#onnx_model = onnx.load("./model.onnx"
graph = onnx_model.graph

# rewrite the input tensor of graph
all_shape = [
             [1,2],
            [1, 3, 608, 608],
           [1,2],
           ]

for i in range(len(all_shape)):
    print(i)
    input_tensor = graph.input[i]
    input_tensor_new = onnx.helper.make_tensor_value_info(name = input_tensor.name, elem_type = 1, 
                                                        shape = all_shape[i])
    graph.input.remove(input_tensor)
    graph.input.insert(i, input_tensor_new)

# run node shape inference
node = graph.node
value_info = graph.value_info
print("Before shape inference: \n")
print(value_info)
print("------------------------------------------------------------")
print("After shape inference: \n")
inferred_onnx_model = shape_inference.infer_shapes(onnx_model)
onnx.checker.check_model(onnx_model)
inferred_graph = inferred_onnx_model.graph
inferred_value_info = inferred_graph.value_info
print(inferred_value_info)
onnx.save(inferred_onnx_model,"./new.onnx")
...
```
- Attach the ONNX model to the issue (where applicable)

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @zhoutianzi666,
To clarify, -1 is not a valid dimension in current ONNX. To represent an unknown dimension, please use an empty dimension without specifying dim_value and dim_param. May I ask you how you got -1 dimension from the ONNX model? It should not be produced by any ONNX's converters.

A possible improvement for onnx.checker might be having a better error message saying something like "-1" is not a valid dimension.
