### ISSUE TITLE
Version v1.12.0 is tagged as v12.0.0

### ISSUE THREAD

**Issue by yan12125** [onnx/onnx#4290]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Seems a wrong tag version? https://github.com/onnx/onnx/releases/tag/v12.0.0

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Arch Linux
- ONNX version (*e.g. 1.7*): 1.12.0
- Python version: 3.10
- GCC/Compiler version (if compiling from source): GC 12.1.0
- CMake version: 3.23.2
- Protobuf version: 21.1
- Visual Studio version (if applicable): N/A

### Reproduction instructions
Check the latest ONNX tag

### Expected behavior
The latest tag is v1.12.0

### Notes
The unofficial Arch Linux package [python-onnx](https://aur.archlinux.org/packages/python-onnx) follows GitHub tags. An automation script updates that package to 12.0.0, while it's actually 1.12.0.

/cc @hubutui

**Comment by jcwchen** [comment]
Hi @yan12125,
Thank you for catching this early! I have corrected the tag name. Now it uses v1.12.0 for ONNX 1.12.0.

**Comment by yan12125** [comment]
Cool, thanks for the fix!
