### ISSUE TITLE
Expected behavior of ConvTranspose with auto_pad and output_padding attribute?

### ISSUE THREAD

**Issue by furiosa-JeongminPark** [onnx/onnx#4299]
# Ask a Question

### Question
ConvTranspose operator with auto_pad and output_padding attribute's inferred output shape and onnxruntime output shape do not match.

https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose
> auto_pad must be either NOTSET, SAME_UPPER, SAME_LOWER or VALID. Where default value is NOTSET, which means explicit padding is used. SAME_UPPER or SAME_LOWER mean pad the input so that `output_shape[i] = input_shape[i] * strides[i]` for each axis `i`. The padding is split between the two sides equally or almost equally (depending on whether it is even or odd). In case the padding is an odd number, the extra padding is added at the end for SAME_UPPER and at the beginning for SAME_LOWER.

ConvTranspose says that output_shape[i] = input_shape[i] * strides[i].

for ConvTranspose with attributes:
strides = [2, 2],
auto_pad="SAME_UPPER",
input shape: [1, 2, 3, 3],
weight shape: [2, 1, 3, 3]

auto_pad will generate pads = [0, 0, 1, 1], since output shape without auto_pad="SAME_UPPER" will generate output with size [1, 1, 6, 6] vs [1, 1, 7, 7] without auto_pad attribute.

Then, when we add output_padding attribute to make a ConvTranspose operator with attributes:
strides = [2, 2],
auto_pad="SAME_UPPER",
output_padding=[1, 1]
input shape: [1, 2, 3, 3],
weight shape: [2, 1, 3, 3]

I think it is natural to generate pads value and be like:
strides = [2, 2],
pads=[0, 0, 1, 1],
output_padding=[1, 1]
input shape: [1, 2, 3, 3],
weight shape: [2, 1, 3, 3]

which will generate output shape [1, 1, 7, 7].

onnx shape inference works that way, but when I execute the script attached below, it outputs:

```
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
2022-06-21 14:43:11.829556612 [W:onnxruntime:, execution_frame.cc:770 VerifyOutputSizes] Expected shape from model of {1,1,7,7} does not match actual shape of {1,1,6,6} for output y
[array([[[[117., 249., 134., 283., 151., 164.],
         [267., 564., 301., 632., 335., 367.],
         [168., 351., 185., 385., 202., 221.],
         [369., 768., 403., 836., 437., 481.],
         [219., 453., 236., 487., 253., 278.],
         [282., 585., 305., 631., 328., 353.]]]], dtype=float32)]
```

Which says that onnxruntime executed output shape is [1, 1, 6, 6].

Is it onnx shape inference, or onnxruntime which implements `auto_pad` with `output_padding` wrongly?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
shape_inference

- Tested on onnx==1.10.2, 1.11.0, 1.12.0, onnxruntime==1.9.0, 1.10.0, 1.11.0, 1.11.1

### Notes
Any additional information, code snippets.
```
#! usr/bin/env python3
import numpy as np
import onnx
import onnxruntime as ort


def main():
    model_name = "conv_transpose"
    graph = onnx.helper.make_graph(
        # nodes
        [
            onnx.helper.make_node(
                'ConvTranspose',
                inputs=['x', 'w'],
                outputs=['y'],
                strides=[2, 2],
                auto_pad="SAME_UPPER",
                # pads=[0, 0, 1, 1],
                output_padding=[1, 1],
            )
        ],
        # graph name
        model_name,
        # input
        [
            onnx.helper.make_tensor_value_info("x", onnx.TensorProto.FLOAT, (1, 2, 3, 3)),
        ],
        # output
        [
            onnx.helper.make_tensor_value_info("y", onnx.TensorProto.FLOAT, (1, 1, 7, 7)),
        ],
        # initializer
        [
            onnx.helper.make_tensor(
                "w", onnx.TensorProto.FLOAT, (2, 1, 3, 3), [i for i in range(2 * 1 * 3 * 3)]
            ),
        ],
    )
    model = onnx.helper.make_model(graph, opset_imports=[onnx.helper.make_opsetid("", 12)])

    model = onnx.shape_inference.infer_shapes(model, check_type=True, strict_mode=True)
    onnx.checker.check_model(model)
    onnx.save_model(model, f'{model_name}.onnx')

    sess = ort.InferenceSession(model.SerializeToString())
    x = np.array([i for i in range(1 * 2 * 3 * 3)]).reshape(1, 2, 3, 3).astype(np.float32)
    print(x)
    print(sess.run(None, {"x": x}))


if __name__ == "__main__":
    main()

```

**Comment by jcwchen** [comment]
Hi @furiosa-JeongminPark,
Thanks for catching this. I think it's a known issue in ORT: https://github.com/microsoft/onnxruntime/issues/9370. I will try to forward https://github.com/microsoft/onnxruntime/pull/9740 to fix it. Feel free to review that PR. Thank you for your contribution. I will close this one and let's track this issue in ORT instead.
