### ISSUE TITLE
install onnx 1.12.0 error

### ISSUE THREAD

**Issue by JohnnMason** [onnx/onnx#4310]
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_2sb68a7/onnx_f8f69200b8f947f8b498bb513688393b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_2sb68a7/onnx_f8f69200b8f947f8b498bb513688393b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sacdej_y
       cwd: /tmp/pip-install-_2sb68a7/onnx_f8f69200b8f947f8b498bb513688393b/
  Complete output (67 lines):
  **fatal: not a git repository (or any of the parent directories): .git**
  /usr/local/lib/python3.6/dist-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  Using cmake args: ['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-_2sb68a7/onnx_f8f69200b8f947f8b498bb513688393b']
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/bin/python3 (found version "3.6.9")
  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9")
  Generated: /tmp/pip-install-_2sb68a7/onnx_f8f69200b8f947f8b498bb513688393b/.setuptools-cmake-build/onnx/onnx-ml.proto
  CMake Error at CMakeLists.txt:299 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:330 (relative_protobuf_generate_cpp)

**Comment by sand-box** [comment]
Same issue here. 1.11.0 works, 1.12.0 fails to install with above error.

**Comment by jcwchen** [comment]
Please note that ONNX 1.12.0 does not support Python 3.6 anymore (and Python 3.10 support was added). ONNX has announced the deprecation in last 1.11 release. Since there isn't a prebuilt ONNX 1.11 wheel on PyPI, you will build ONNX from source and protobuf-compiler is required. That's why you see "Protobuf compiler not found". You can check the supported ONNX 1.12.0 wheel [here](https://pypi.org/project/onnx/#files). Thanks.

**Comment by garymm** [comment]
Python 3.6 is not officially supported. You can build from source if you want.
