### ISSUE TITLE
Basic question - How to export ONNX for an operator.

### ISSUE THREAD

**Issue by stonelazy** [onnx/onnx#4314]
### Question
Am very inclined to try the latest [signal processing operators](https://github.com/onnx/onnx/pull/3741) added in ONNX under opset 17 which got released last week. 
Usually I use torch's export to ONNX API to get my model.onnx file, unfortunately torch seem to support only until opset 15 but these new operators that i want to try are in Opset 17 only. Am not sure of any other way to [export my model to ONNX](https://gist.github.com/stonelazy/481ba4538e8f476636e22ab1f1cc68fb).  

I just want to do these  
1.) Export these signal processing operators such as DFT/STFT as a separate .onnx file so that i can use in any environment.  
2.) If 1 is not possible, then let me wait until Torch supports opset17.. but I want to check how I can verify if the output of ONNX matches the torch's.  

### Notes
The code that am trying to export to ONNX is [this](https://gist.github.com/stonelazy/481ba4538e8f476636e22ab1f1cc68fb)

**Comment by liqunfu** [comment]
If I understand you right, you can use onnx.helper.make_model to create a model with a graph containing the operator you like. There are examples in the repo showing how to do this. 

you may also use parser_model and save the model in onnx format.

**Comment by stonelazy** [comment]
Thank you so much for replying. This worked.
