### ISSUE TITLE
interrupted

### ISSUE THREAD

**Issue by sssimpleboy** [onnx/onnx#4320]
# Ask a Question
failed to make .onnx. 

### Question
Explain your question here.
After running torch.onnx.export() I found nothing in my directory. And the code left didn't work.
It seems interrupted. Could you help me ?
this is my information
![image](https://user-images.githubusercontent.com/100906198/176110929-7177058d-38c2-4d48-bb10-1b0deafd0b03.png)

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
no
- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):   
DBnet
**Model opset** (*e.g. 7*): 

### Notes
Any additional information, code snippets.

![image](https://user-images.githubusercontent.com/100906198/176111978-cbabd1d3-b3a1-4d49-9cdb-b4ba0d766496.png)

**Comment by jcwchen** [comment]
Hi @sssimpleboy,
The conversion seems failed according to the error message. This should be a question for torch.onnx.export(), because the error happened during conversion. Please raise this issue in the converter repo (under PyTorch) and provide the code to repro if possible.
