### ISSUE TITLE
Conversion from the opset-8 Scan op to opset-9 (or newer).

### ISSUE THREAD

**Issue by negiyas** [onnx/onnx#4321]
# Ask a Question

### Question
Can we rewrite(convert) opset-8 of onnx.Scan op with opset-9 (or newer) of onnx.Scan (or another) op?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
Since opset-8 of onnx.Scan op has the batch size dimensions and opset-9 (or newer) does hot have the batch size dimension,
it is not simple to convert opset-8 Scan op to opset-9 scan op. Is there a simple mapping between them?
Any information about the conversion are very welcome.

- Is this issue related to a specific model? 
**Model name** (*e.g. mnist*):  
The bidaf-9 model in model zoo, [text/machine_comprehension/bidirectional_attention_flow/model/bidaf-9.onnx](https://github.com/onnx/models/blob/main/text/machine_comprehension/bidirectional_attention_flow/model/bidaf-9.onnx) includes opset-8 onnx.Scan op.
**Model opset** (*e.g. 7*):
9, but opset of onnx.Scan op should be 8. 
.

**Comment by jcwchen** [comment]
Hi @negiyas,
ONNX does have an [adapter (Scan-8 to Scan-9)](https://github.com/onnx/onnx/blob/main/onnx/version_converter/adapters/scan_8_9.h) to support such a conversion in onnx.version_converter. You can try [the example](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx) to convert your opset 8 ONNX models into opset 9.

**Comment by negiyas** [comment]
Hi @jcwchen,
I am looking at the Scan-8 to Scan-9 adapter. Thank you very much for your helpful answer.
