### ISSUE TITLE
Resolve existing pylint errors after introducing new pylint CI to reduce unrelated warnings

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4328]
# Feature Request

### What is the problem that this feature solves?
Reduce warnings which are not related to the original PR (existing pylint errors).

### Describe the feature
To improve contributor/reviewer's experience, we should resolve existed pylint errors (go through whole repo) after introducing new pylint CI to reduce unrelated warnings.

### Will this influence the current api?
No.

### Feature Area
lint, CI

**Comment by jcwchen** [comment]
Please note that after this PR merged: https://github.com/onnx/onnx/pull/4371, current Python Lint CI should not complain about existing failures if developers do not change those lines in the changed file.

**Comment by jcwchen** [comment]
I think it has been covered by https://github.com/onnx/onnx/pull/4763. Thanks @justinchuby. Please correct me if I am wrong. I will close this issue now.

**Comment by justinchuby** [comment]
We still have some: https://github.com/onnx/onnx/blob/619ef70bd860c5cdedc1c3f02365dfa5da2a4a06/.lintrunner.toml#L225-L230
