### ISSUE TITLE
Set a static batch size for input and output tensors

### ISSUE THREAD

**Issue by wadhwasahil** [onnx/onnx#4329]
# Bug Report

I have a TF model which I converted to ONNX using `tf2onnx` library. 

Input Tensor has a shape = [`UNK_590,` 128, 128, 3]

Output Tensors also have `UNK_590` as first dimension.

### Is the issue related to model conversion?

Used tf2onnx for conerting TF model to ONNX

### Describe the bug

I know that while training I used dynamic batch size hence the token UNK. For inference I want to make it a fixed size eg 4. 

```
import onnx
model = onnx.load("model.onnx")
batch = '4'
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = batch
for i in range(len(model.graph.output)):
    model.graph.output[i].type.tensor_type.shape.dim[0].dim_param = batch
onnx.save(model, "temp.onnx")
```
However it just changes the UNK token to '4' instead of a fixed batch dimension. How can I resolve this issue? How can I make my onnx model to have a static batch size during inference?

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux
- ONNX version (*e.g. 1.7*):  1.10
- Python version: 3.6
- GCC/Compiler version (if compiling from source):
- CMake version: NA
- Protobuf version: NA
- Visual Studio version (if applicable): NA

Any additional information

**Comment by HSQ79815** [comment]
You can set the static shape after input name inside `[]` when using `tf2onnx` by `--inputs` parameter

**Comment by tianleiwu** [comment]
@[wadhwasahil](https://github.com/wadhwasahil), try the following:
```
            for tensor in model.graph.input:
                for dim_proto in tensor.type.tensor_type.shape.dim:
                    if dim_proto.HasField("dim_param"): # and dim_proto.dim_param == 'UNK_590':
                        dim_proto.Clear()
                        dim_proto.dim_value = 1 # fixed batch size
             for tensor in model.graph.output:
                  ...
```
