### ISSUE TITLE
Add changelog entry for BC-breaking changes

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#433]
Right now you have to do a textual diff to see what changed in a BC-breaking change. It would be good to ask people to write a changelog entry inline when they make a BC-breaking change.

**Comment by askhade** [comment]
@ezyang : Can you add more details as to how you envision this? So that we can make this an actionable item.
Thanks!

**Comment by ezyang** [comment]
Suppose you are looking at Abs in the docs. See https://github.com/onnx/onnx/blob/master/docs/Operators.md#abs There is a note saying that there is an earlier version, Abs-1. You can click it to see the old version. Fine. What's the difference? You have to manually diff the two descriptions to see what in the wording changed. It would be better if there was an actual description saying what the change was.
