### ISSUE TITLE
linux arm build error

### ISSUE THREAD

**Issue by yangc1991** [onnx/onnx#4341]
when i install with the source scripts use shell :python setup.py build 
it stoped when Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
and logs:
/home/nvidia/Public/plugins/onnx/onnx/defs/sequence/defs.cc: In function ‘bool onnx::BuildSequenceMapBodyFunc(const onnx::FunctionBodyBuildContext&, const onnx::OpSchema&, onnx::FunctionProto&)’:
/home/nvidia/Public/plugins/onnx/onnx/defs/sequence/defs.cc:675:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
         seq_at_node.add_output(g_inputs[inputIndex].name());
CMakeFiles/onnx.dir/build.make:830: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o' failed
make[2]: *** [CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
who can help me please？thank you for your time

**Comment by jcwchen** [comment]
Hi @yangc1991,
What's your Protobuf version? You can use 'protoc --version' to check. The recommended Protobuf version is 3.16-3.20.
