### ISSUE TITLE
Support for `BitwiseXor`, `BitwiseOr`, `Bitcast`, and `BitwiseAnd` ops

### ISSUE THREAD

**Issue by josephrocca** [onnx/onnx#4343]
# New Operator

### Describe the operator
The ` BitwiseXor`, `BitwiseOr`, `Bitcast`, and `BitwiseAnd` ops:

 1. https://www.tensorflow.org/api_docs/python/tf/raw_ops/Bitcast
 2. https://www.tensorflow.org/api_docs/python/tf/raw_ops/BitwiseAnd
 3. https://www.tensorflow.org/api_docs/python/tf/raw_ops/BitwiseOr
 4. https://www.tensorflow.org/api_docs/python/tf/raw_ops/BitwiseXor

### Can this operator be constructed using existing onnx operators?
[Apparently it is not possible](https://github.com/onnx/tensorflow-onnx/issues/1985#issuecomment-1173456022):

> But after I took a quick check, there is no easy way to do it yet.

### Is this operator used by any model currently? Which one?
Yes, the Flax BART model used by DALL-E Mini, for example, requires this op when trying to convert to ONNX format (via TF Saved Model format).

### Are you willing to contribute it? (Y/N)
Yes, but I would probably require guidance since I haven't done anything like this before.

### Notes
Please see this issue for context: https://github.com/onnx/tensorflow-onnx/issues/1985

**Comment by postrational** [comment]
Do we know other models which require these operations?

**Comment by AlexandreEichenberger** [comment]
In PyTorch: https://pytorch.org/docs/stable/torch.html

```
bitwise_not | Computes the bitwise NOT of the given input tensor.
-- | --
bitwise_and | Computes the bitwise AND of input and other.
bitwise_or | Computes the bitwise OR of input and other.
bitwise_xor | Computes the bitwise XOR of input and other.
bitwise_left_shift | Computes the left arithmetic shift of input by other bits.
bitwise_right_shift | Computes the right arithmetic shift of input by other bits.
[bitwise_not](https://pytorch.org/docs/stable/generated/torch.bitwise_not.html#torch.bitwise_not)
Computes the bitwise NOT of the given input tensor.
[bitwise_and](https://pytorch.org/docs/stable/generated/torch.bitwise_and.html#torch.bitwise_and)
Computes the bitwise AND of input and other.
[bitwise_or](https://pytorch.org/docs/stable/generated/torch.bitwise_or.html#torch.bitwise_or)
Computes the bitwise OR of input and other.
[bitwise_xor](https://pytorch.org/docs/stable/generated/torch.bitwise_xor.html#torch.bitwise_xor)
Computes the bitwise XOR of input and other.
[bitwise_left_shift](https://pytorch.org/docs/stable/generated/torch.bitwise_left_shift.html#torch.bitwise_left_shift)
Computes the left arithmetic shift of input by other bits.
[bitwise_right_shift](https://pytorch.org/docs/stable/generated/torch.bitwise_right_shift.html#torch.bitwise_right_shift)
Computes the right arithmetic shift of input by other bits.
```

I would look into implementing a minimum set that can generates the other ones. Traditionally `nand` is sufficient, or possibly the traditional `not`, `and`, `or`, and the shifts if they are needed in current models. Compilers should be able to transform small logical expressions in the basic HW primitives supported by a given HW.

**Comment by josephrocca** [comment]
@postrational IIRC, these ops tend to pop up in JAX models when PRNG related functions like `jax.random.PRNGKey` and `random.split` are used. I haven't yet seen these ops in non-JAX models yet.

**Comment by jcowles** [comment]
I just hit this in my own model, but the (highly successful) Instant Neural Graphics Primitives paper uses bitwise xor in their fast-hash function for hashing to the shared memory grid; this multi-level hash grid looks like an incredible useful tool in other contexts as well, beyond this specific paper.

https://github.com/NVlabs/instant-ngp

**Comment by justinchuby** [comment]
Please reopen if Bitcast is needed

**Comment by justinchuby** [comment]
@gramalingam
