### ISSUE TITLE
Build ONNX from source error on Windows

### ISSUE THREAD

**Issue by tzhang-666** [onnx/onnx#4346]
# Ask a Question

I run into issues when I build the onnx from source following the [Notes](https://github.com/onnx/onnx/blob/main/README.md#windows)

The error log is listed as below, please kindly have a look if there is anything wrong or missing.

`
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///D:/d/onnx
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.16.6 in c:\users\t\appdata\roaming\python\python39\site-packages (from onnx==1.12.0) (1.23.0)
Requirement already satisfied: protobuf<=3.20.1,>=3.12.2 in c:\users\t\appdata\roaming\python\python39\site-packages (from onnx==1.12.0) (3.20.1)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\t\appdata\roaming\python\python39\site-packages (from onnx==1.12.0) (4.3.0)
Installing collected packages: onnx
  Running setup.py develop for onnx
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [97 lines of output]
        WARNING: The wheel package is not available.
        running develop
        running build_py
        running create_version
        running cmake_build
        Extra cmake args: ['-DONNX_USE_LITE_PROTO=ON']
        Using cmake args: ['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Program Files\\Python39\\include', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp39-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.9', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', 'D:\\d\\onnx']
        Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
        Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
        Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
        -- Could NOT find pybind11 (missing: pybind11_DIR)
        -- pybind11 v2.9.1
        CMake Error at third_party/pybind11/tools/pybind11Tools.cmake:118 (set_property):
          Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
          "debug".  The INTERFACE_LINK_LIBRARIES property may contain
          configuration-sensitive generator-expressions which may be used to specify
          per-configuration rules.
        Call Stack (most recent call first):
          third_party/pybind11/tools/pybind11Common.cmake:206 (include)
          third_party/pybind11/CMakeLists.txt:200 (include)

        CMake Error at third_party/pybind11/tools/pybind11Tools.cmake:132 (set_property):
          Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
          "debug".  The INTERFACE_LINK_LIBRARIES property may contain
          configuration-sensitive generator-expressions which may be used to specify
          per-configuration rules.
        Call Stack (most recent call first):
          third_party/pybind11/tools/pybind11Common.cmake:206 (include)
          third_party/pybind11/CMakeLists.txt:200 (include)

        --
        -- ******** Summary ********
        --   CMake version             : 3.24.0-rc2
        --   CMake command             : C:/Program Files/CMake/bin/cmake.exe
        --   System                    : Windows
        --   C++ compiler              : C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
        --   C++ compiler version      : 19.29.30145.0
        --   CXX flags                 : /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc /wd26812
        --   Build type                : Release
        --   Compile definitions       : __STDC_FORMAT_MACROS
        --   CMAKE_PREFIX_PATH         :
        --   CMAKE_INSTALL_PREFIX      : C:/Program Files/onnx
        --   CMAKE_MODULE_PATH         :
        --
        --   ONNX version              : 1.12.0
        --   ONNX NAMESPACE            : onnx
        --   ONNX_USE_LITE_PROTO       : ON
        --   USE_PROTOBUF_SHARED_LIBS  : OFF
        --   Protobuf_USE_STATIC_LIBS  : ON
        --   ONNX_DISABLE_EXCEPTIONS   : OFF
        --   ONNX_WERROR               : OFF
        --   ONNX_BUILD_TESTS          : OFF
        --   ONNX_BUILD_BENCHMARKS     : OFF
        --   ONNXIFI_DUMMY_BACKEND     : OFF
        --   ONNXIFI_ENABLE_EXT        : OFF
        --
        --   Protobuf compiler         :
        --   Protobuf includes         :
        --   Protobuf libraries        :
        --   BUILD_ONNX_PYTHON         : ON
        --     Python version        : 3.9
        --     Python executable     : C:/Program Files/Python39/python.exe
        --     Python includes       : C:/Program Files/Python39/include
        -- Configuring incomplete, errors occurred!
        See also "D:/d/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "D:\d\onnx\setup.py", line 332, in <module>
            setuptools.setup(
          File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "C:\Program Files\Python39\lib\distutils\core.py", line 148, in setup
            dist.run_commands()
          File "C:\Program Files\Python39\lib\distutils\dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "D:\d\onnx\setup.py", line 239, in run
            self.run_command("build_py")
          File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "D:\d\onnx\setup.py", line 223, in run
            self.run_command("cmake_build")
          File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
            cmd_obj.run()
          File "D:\d\onnx\setup.py", line 209, in run
            subprocess.check_call(cmake_args)
          File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Program Files\\Python39\\include', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp39-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.9', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', 'D:\\d\\onnx']' returned non-zero exit status 1.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [97 lines of output]
    WARNING: The wheel package is not available.
    running develop
    running build_py
    running create_version
    running cmake_build
    Extra cmake args: ['-DONNX_USE_LITE_PROTO=ON']
    Using cmake args: ['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Program Files\\Python39\\include', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp39-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.9', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', 'D:\\d\\onnx']
    Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: D:/d/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    -- Could NOT find pybind11 (missing: pybind11_DIR)
    -- pybind11 v2.9.1
    CMake Error at third_party/pybind11/tools/pybind11Tools.cmake:118 (set_property):
      Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
      "debug".  The INTERFACE_LINK_LIBRARIES property may contain
      configuration-sensitive generator-expressions which may be used to specify
      per-configuration rules.
    Call Stack (most recent call first):
      third_party/pybind11/tools/pybind11Common.cmake:206 (include)
      third_party/pybind11/CMakeLists.txt:200 (include)

    CMake Error at third_party/pybind11/tools/pybind11Tools.cmake:132 (set_property):
      Property INTERFACE_LINK_LIBRARIES may not contain link-type keyword
      "debug".  The INTERFACE_LINK_LIBRARIES property may contain
      configuration-sensitive generator-expressions which may be used to specify
      per-configuration rules.
    Call Stack (most recent call first):
      third_party/pybind11/tools/pybind11Common.cmake:206 (include)
      third_party/pybind11/CMakeLists.txt:200 (include)

    --
    -- ******** Summary ********
    --   CMake version             : 3.24.0-rc2
    --   CMake command             : C:/Program Files/CMake/bin/cmake.exe
    --   System                    : Windows
    --   C++ compiler              : C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    --   C++ compiler version      : 19.29.30145.0
    --   CXX flags                 : /DWIN32 /D_WINDOWS /W3 /GR /EHsc /EHsc /wd26812
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : C:/Program Files/onnx
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.12.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : ON
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         :
    --   Protobuf includes         :
    --   Protobuf libraries        :
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        : 3.9
    --     Python executable     : C:/Program Files/Python39/python.exe
    --     Python includes       : C:/Program Files/Python39/include
    -- Configuring incomplete, errors occurred!
    See also "D:/d/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "D:\d\onnx\setup.py", line 332, in <module>
        setuptools.setup(
      File "C:\Program Files\Python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\Python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\d\onnx\setup.py", line 239, in run
        self.run_command("build_py")
      File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\d\onnx\setup.py", line 223, in run
        self.run_command("cmake_build")
      File "C:\Program Files\Python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\Python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\d\onnx\setup.py", line 209, in run
        subprocess.check_call(cmake_args)
      File "C:\Program Files\Python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Program Files\\Python39\\include', '-DPYTHON_EXECUTABLE=C:\\Program Files\\Python39\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp39-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.9', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', 'D:\\d\\onnx']' returned non-zero exit status 1.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by jcwchen** [comment]
Hi @tzhang-666,
Have you tried `git submodule update --init --recursive` before building ONNX from source?
