### ISSUE TITLE
[W:onnxruntime:, execution_frame.cc:770 VerifyOutputSizes]

### ISSUE THREAD

**Issue by cyinen** [onnx/onnx#4347]
# Ask a Question

### Question
I have a onnx model converted from pth. I inference sucessfully on CPU with CPUExecutionProvider, but meet the warning 
"[W:onnxruntime:, execution_frame.cc:770 VerifyOutputSizes] Expected shape from model of {n,3,h,w} does not match actual shape of {1,3,225,4,225,4} for output output" when I inference with  CUDAExecutionProvider.
![image](https://user-images.githubusercontent.com/56926538/177677941-13a86e46-a5f4-4aa3-b0e8-1743257cfdd1.png)

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.
![image](https://user-images.githubusercontent.com/56926538/177677781-18535f81-9506-42d7-9d8c-89adad2d852c.png)

**Comment by jcwchen** [comment]
Hi @cyinen,
I think it should be a question for ONNX Runtime's CUDAExecutionProvider. Could you please raise this issue in ONNX Runtime's repo instead to get best help from the runtime experts?

**Comment by justin4ai** [comment]
Hi, did you manage to hide or completely resolve the warning message by any chance?
