### ISSUE TITLE
ModuleNotFoundError: No module named 'onnx.numpy_helper'

### ISSUE THREAD

**Issue by qiuxia-alone** [onnx/onnx#4355]
# Ask a Question

### Question
hi, when i `from onnxruntime.quantization import quantize, QuantizationMode`, it show `ModuleNotFoundError: No module named 'onnx.numpy_helper'`,how can i fix this?

### Further information
- onnxruntime             1.11.1

**Comment by qiuxia-alone** [comment]
> Hi @qiuxia-alone, Have you installed onnx? If not, please pip install onnx and you won't see this onnx not found error.

i have installed onnx, and i restart the pycharm, problem solved, thank you for your reply.

**Comment by jcwchen** [comment]
I will close this issue then. Please reopen it if you still have other ONNX questions. Thanks!
