### ISSUE TITLE
onnx doesn't support argwhere

### ISSUE THREAD

**Issue by shengugang** [onnx/onnx#4368]
# New Operator

### Describe the operator
Why is this operator necessary? What does it accomplish?

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?

### Notes
Any additional information

**Comment by gramalingam** [comment]
Would the op just return the indices of elements where the condition is true? (Like the NonZero op: https://github.com/onnx/onnx/blob/main/docs/Operators.md#NonZero )?

**Comment by shengugang** [comment]
I use the Nonezero and transpose to replace the argwhere
