### ISSUE TITLE
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by frankvp11** [onnx/onnx#4376]
# Bug Report
### Describe the bug
When I try to install onnx==1.8.1 onto my virtual environment, I get the following output

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting onnx==1.8.0
  Downloading onnx-1.8.0.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 21.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages (from onnx==1.8.0) (4.3.0)
Requirement already satisfied: numpy in /home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages (from onnx==1.8.0) (1.21.6)
Requirement already satisfied: protobuf in /home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages (from onnx==1.8.0) (3.20.0)
Requirement already satisfied: six in /home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages (from onnx==1.8.0) (1.16.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Generated: /tmp/pip-install-xxjjis2_/onnx_2ebb98abade140ddb36dc12a7201e7b3/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:257 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:288 (relative_protobuf_generate_cpp)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-xxjjis2_/onnx_2ebb98abade140ddb36dc12a7201e7b3/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
      /tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/dist.py:774: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        % (opt, underscore_opt)
      /tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "/home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ecoation/TensorRT/TensorRTVenv/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
          metadata_directory)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 245, in build_wheel
          wheel_directory, config_settings)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 282, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 341, in <module>
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "<string>", line 217, in run
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-j92ykxmi/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "<string>", line 203, in run
        File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.7m', '-DPYTHON_EXECUTABLE=/home/ecoation/TensorRT/TensorRTVenv/bin/python3.7', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-xxjjis2_/onnx_2ebb98abade140ddb36dc12a7201e7b3']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

### System information
- OS Platform and Distribution : Ubuntu 18.04
- ONNX version (*e.g. 1.7*):  (Attemping to get 1.8.1)
- Python version: 3.7.13
- GCC/Compiler version (if compiling from source): Not compiling from source
- CMake version: 3.10.2
- Protobuf version: 3.20.0
- Visual Studio version (if applicable): Not applicable

### Reproduction instructions

pip install onnx==1.8.1
### Expected behavior
I expected onnx-1.8.1 to install

**Comment by jcwchen** [comment]
Hi @frankvp11,
For some reasons, your `pip install onnx==1.8.1` did not download the prebuilt wheel from PyPI and built ONNX from source instead. My best guess would be related to pip version: https://github.com/onnx/onnx/issues/3977#issuecomment-1023357914. Could you please try to upgrade your pip3 (`python -m pip install -q --upgrade pip`) and then try it again?

**Comment by Smyja** [comment]
still experiencing this.

**Comment by jcwchen** [comment]
Hi @Smyja,
Which Python version, ONNX version and platform did you use?

**Comment by frankvp11** [comment]
LOL conviently I had this error earlier today. I just kinda brute forced- tried reinstalling things and upgrading things - I didn't have a set thing that I remembered -sorry

**Comment by gengdata** [comment]
> 你好@Smyja, 你用的是哪个Python版本、ONNX版本和平台？

您好，我遇到了类似的问题：pip install onnx==1.8.1安装失败，用的是python3.10，onnx1.12.0。期望您的解答

**Comment by Smyja** [comment]
> Hi @Smyja,
> Which Python version, ONNX version and platform did you use?

Python 3.10, Ubuntu.

**Comment by Smyja** [comment]
> 您好，我遇到了类似的问题：pip install onnx==1.8.1安装失败，用的是python3.10，onnx1.12.0。期望您的解答

i think i installed protobuf compiler with `sudo apt-get install libprotobuf-dev `

see more solutions [here](https://stackoverflow.com/questions/61433345/errors-when-installing-onnx-with-pip-in-ubuntu-20-04)

**Comment by gengdata** [comment]
> > 您好，我遇到了类似的问题：pip install onnx==1.8.1安装失败，用的是python3.10，onnx1.12.0。期望您的解答
> 
> i think i installed protobuf compiler with `sudo apt-get install libprotobuf-dev `
> 
> see more solutions [here](https://stackoverflow.com/questions/61433345/errors-when-installing-onnx-with-pip-in-ubuntu-20-04)

您好，我用的Windows，不是Ubuntu

**Comment by jcwchen** [comment]
To clarify: onnx==1.8.1 is an old version so it does not provide prebuilt wheel for new Python version like Python 3.9 or 3.10. See the supported list [here](https://pypi.org/project/onnx/1.8.1/#files). If you pip install onnx==1.8.1 with a new Python version, actually you are building onnx from source. To build ONNX from source, protoc (Protobuf compiler is required). Please follow the instruction in [README.md](https://github.com/onnx/onnx#build-onnx-from-source) to install Protobuf first and then install ONNX.

**Comment by hanifizzudinrahman** [comment]
me still get this error, anyone have solved this?

**Comment by jcwchen** [comment]
Hi @hanifizzudinrahman,
What's your Python version and what's your target onnx version? If there is not prebuilt wheel in https://pypi.org/project/onnx/#files, you will need to build onnx from source. In that case, protoc (Protobuf compiler) is required. Please see [README.md](https://github.com/onnx/onnx#build-onnx-from-source).

**Comment by hanifizzudinrahman** [comment]
i used python 3.9 and get this error. Then, i downgrade to python 3.8, and problem solved

**Comment by jcwchen** [comment]
I assume you were using onnx 1.8.1. If yes, there is no prebuilt wheel for Python 3.9: https://pypi.org/project/onnx/1.8.1/#files and it only supports Python 3.5 to Python 3.8.

**Comment by gengdata** [comment]
> I assume you were using onnx 1.8.1. If yes, there is no prebuilt wheel for Python 3.9: https://pypi.org/project/onnx/1.8.1/#files and it only supports Python 3.5 to Python 3.8.
Re install anconda

**Comment by praful-1812** [comment]
### If you are using virtual environment for the installation:

If the environment showing like:
**(conda env)(venv) user@user-dell:~**

Then,
`source venv/bin/activate`

And got,
**(venv)(conda env) user@user-dell:~**

Again run
`pip install onnx==ANYVERSION`

**Comment by mmaciejeamd** [comment]
I find it really hard to believe that there are so many problems with doing something as simple as building a project from source.... I experience similar problems on Windows with the latest version of Python. How do I build it seamlessly or where do I simply download prebuilt binaries from that these could be then included into a C/C++ project built with CMake?

**Comment by swiftcynic** [comment]
I came across this issue and it seems to have been solved in the current develop branch. It looks similar to the issue mentioned at [here](https://github.com/Unity-Technologies/ml-agents/issues/6019).

**Comment by TarioYX** [comment]
Use python <=3.8, not python 3.9.

**Comment by lalalafloat** [comment]
sudo apt-get install protobuf-compiler libprotoc-dev，and then pip install onnx. I solved the problem by this operation.

**Comment by ivberg** [comment]
Just hit this today on Windows. Had to downgrade from the default Python from the Windows Store (3.12) to Python 3.11 which seems has wheel pre-builts that don't fail to compile

**Comment by oliver226** [comment]
install it in conda env. It's ok.
pip3 install onnx==1.8.1

**Comment by inarighas** [comment]
on RHEL-based distributions,  `yum install protobuf-compiler protobuf-devel` solve the problem.

**Comment by xegulon** [comment]
Thanks a lot @inarighas

**Comment by lambda-science** [comment]
Same problem today on windows python 3.12.1 :(

**Comment by STVHA** [comment]
@lambda-science  I experienced the same. Python 3.11 is the way.

**Comment by diegoakel** [comment]
also "solved" it using Python 3.11

**Comment by akesh1235** [comment]
@diegoakel Could you guide me in steps? what did you do to solve in windows.

**Comment by diegoakel** [comment]
> @diegoakel Could you guide me in steps? what did you do to solve in windows.

If you have Python 3.12, you have to uninstall it (you can search for Add or Remove Programs on windows) and then install Python 3.12 from the Python site. Don't forget to check your system environment variable PATH to see if the paths pointing to Python are correctly pointing to Python 3.12 (something like .../Python311/...)

**Comment by akesh1235** [comment]
@diegoakel I uninstalled `python 3.12` and installed `Python 3.9` then my error got fixed.

**Comment by fardinkhanz** [comment]
can anyone guide me? i am using python 3.6 on ubuntu 18 still experiencing this error!

**Comment by diegoakel** [comment]
Have you tried Python 3.11?

**Comment by fardinkhanz** [comment]
No, now i was trying it with python 3.8 will it work or should i try with 3.11?

**Comment by diegoakel** [comment]
Yes, and in case you not doing it, try using a virtualenv as well.

**Comment by morancium** [comment]
> can anyone guide me? i am using python 3.6 on ubuntu 18 still experiencing this error!

hey, did you find the solution?

**Comment by fardinkhanz** [comment]
> > can anyone guide me? i am using python 3.6 on ubuntu 18 still experiencing this error!
> 
> hey, did you find the solution?

Update python version to 3.11

**Comment by itmeicn** [comment]
python 3.11.7 installed is same error.how to ?
Collecting onnx<=1.9.0 (from paddle2onnx>=0.5.1->paddlehub)
  Using cached https://mirrors.163.com/pypi/packages/73/e9/5b953497c0e36df589fc60cc6c6b35a65eb67d9ad1e45a9163663e43426e/onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\python\pyside6Test\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel  
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\zspym\AppData\Local\Temp\pip-build-env-qszjaty2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 86, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]

**Comment by quaeast** [comment]
The Python version is too high, installing Python 3.8 or lower will solve the problem.

**Comment by weiwencengyu** [comment]
> > > 您好，我遇到了类似的问题：pip install onnx==1.8.1安装失败，用的是python3.10，onnx1.12.0。期望您的解答
> > 
> > 
> > i think i installed protobuf compiler with `sudo apt-get install libprotobuf-dev `
> > see more solutions [here](https://stackoverflow.com/questions/61433345/errors-when-installing-onnx-with-pip-in-ubuntu-20-04)
> 
> 您好，我用的Windows，不是Ubuntu

你好你当时解决这个问题了吗

**Comment by weiwencengyu** [comment]
@gengdata 你好你当时解决了这个问题吗

**Comment by hrideshmg** [comment]
On arch run `pacman -S protobuf` to fix the issue
