### ISSUE TITLE
[PR 400 Follow Up] Add support for dlpack

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#438]
We may find an appropriate way to integrate dlpack.

**Comment by houseroad** [comment]
Also, a better solution to organize the names/tensors/initializers.

**Comment by linkerzhang** [comment]
After double looking into the current tensor class, I personally think that it's not needed as it's exactly duplicating the TensorProto data structure. It's not the tensor class that will be used in layers above, say, shape inference, runtime, etc. I'd suggest 1) remove this tensor class and use TensorProto for IR (initializers specifically), 2) introduce dlpack tensor (if all partners agree on it) for future usage (shape inference, runtime etc). Thoughts?

**Comment by prasanthpul** [comment]
Will you be making a PR for this @houseroad ?
