### ISSUE TITLE
New Resize check for sizes and scales breaks some existing models

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4380]
### Question
https://github.com/onnx/onnx/pull/4126 introduces new Resize check for sizes and scales that they cannot exist at the same time. Although I think it's a valid check, there are some existing models have sizes and scales simultaneously. Take yolov4 from ONNX Model Zoo as an example:
![image](https://user-images.githubusercontent.com/14194980/181053459-bddf9b73-bc5a-4fba-a8dd-c31084ce5d61.png)
Its Resize has scales and sizes attributes at the same time, but its scales attribute is an empty tensor. Same thing happens in fcn-resnet as well. You can see the shape inference failures in this [weekly CI with ONNX Model Zoo](https://github.com/onnx/onnx/runs/7491394257?check_suite_focus=true).

To make shape inference be compatible with existing models, is it possible that we kind of relax the check here? For example, further check whether scales or sizes is an empty tensor and do not throw an error if both of them exist but one of them is an empty tensor.

cc @onnx/sig-operators-approvers @jantonguirao

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
Shape inference

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*): yolov4, fcn-resnet
**Model opset** (*e.g. 7*): 11, 12 (Resize)

**Comment by jantonguirao** [comment]
@jcwchen Your proposal sounds reasonable to me.

**Comment by jantonguirao** [comment]
@jcwchen  https://github.com/onnx/onnx/pull/4388 should fix this issue. Thanks for reporting the problem
