### ISSUE TITLE
update_doc.sh does not work

### ISSUE THREAD

**Issue by CharlieL7** [onnx/onnx#4381]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Updating the docs in `onnx/defs/math/defs.cc` and trying to run `/tools/update_doc.sh`. Makes this output:
```
===> recompile onnx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --user not recognized
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 20.04.4 LTS
- ONNX version (*e.g. 1.7*):  Develop
- Python version: 3.8.10
- GCC/Compiler version (if compiling from source): 9.4.0
- CMake version: 3.16.3
- Protobuf version:
- Visual Studio version (if applicable): N/A

### Reproduction instructions
- run `tools/update_doc.sh` from the root directory

### Expected behavior
Docs are updated with changes.

**Comment by jcwchen** [comment]
Hi @CharlieL7,
It might be related to old version of pip or setuptools? Perhaps try to upgrade them first (`pip install --upgrade pip setuptools`) before running `tools/update_doc.sh`.

**Comment by CharlieL7** [comment]
Old version of setuptools seems to be the cause. Thanks.
