### ISSUE TITLE
Enable ONNX Hub to download test_data_set from ONNX Model Zoo

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4390]
# Feature Request

### System information
ONNX version (you are using): 1.12

### What is the problem that this feature solves?
It would be great if ONNX Hub can download test_data_set. It will be helpful for testing ONNX Model Zoo.

### Describe the feature
Currently users can only download models through ONNX Hub. There is no easy API for them to download the test_data_set from.tar.gz

### Will this influence the current api?
New API will be added.

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): ONNX Hub for ONNX Model Zoo

### Are you willing to contribute it (Y/N):
Y. I can do it if I have more bandwidth in the future. Anyone interested you are welcome to contribute.

**Comment by aadith-warrier** [comment]
Willing to work on this. Might need some help as I am new to ONNX.

**Comment by jcwchen** [comment]
Hi @aadith-warrier,
Thank you for picking this up! Feel free to let me know if you need any assistance.

**Comment by aadith-warrier** [comment]
@jcwchen 
I am facing issues with build as mentioned in #4704.

**Comment by jcwchen** [comment]
Thank you for the interest. I have replied there. Please let me know if you have other questions.

**Comment by mathewp88** [comment]
Hello @jcwchen and @aadith-warrier,
Can I help with this?

**Comment by jcwchen** [comment]
I am not actively working on this work item. However, if @aadith-warrier has started to work on this, I would suggest @mathewp88 check other issues: https://github.com/onnx/onnx/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 for contribution. Thank you both! Feel free to let me know if you have any ONNX questions.
