### ISSUE TITLE
Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

### ISSUE THREAD

**Issue by frankvp11** [onnx/onnx#4392]
# Bug Report

### Is the issue related to model conversion?
It possibly is, however I'm not sure yet and would like to find out
### Describe the bug
With success I was able to convert Detectron2 to .onnx model format, however upon testing it with the polygraphy run command it gave me the following output. 

polygraphy run /home/ecoation/Downloads/folded_model.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --tactic-sources CUBLAS
[I] trt-runner-N0-07/29/22-09:10:41     | Activating and starting inference
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:1: Invalid control characters encountered in text.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:12: Invalid control characters encountered in text.
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format onnx2trt_onnx.ModelProto: 1:14: Message type "onnx2trt_onnx.ModelProto" has no field named "pytorch".
[07/29/2022-09:10:44] [TRT] [E] ModelImporter.cpp:735: Failed to parse ONNX model from file: /home/ecoation/Downloads/folded_model.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 18.04
- ONNX version (*e.g. 1.7*):  1.12.0
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 7.5.0
- CMake version: 3.22.5
- Protobuf version: 3.16.0
- Visual Studio version (if applicable): NA

### Reproduction instructions
- Describe the code to reproduce the behavior.
polygraphy run /home/ecoation/Downloads/folded_model.onnx --trt --onnxrt --trt-outputs mark all --onnx-outputs mark all --tactic-sources CUBLAS

(in terminal)

- Attach the ONNX model to the issue (where applicable)
https://drive.google.com/file/d/1iuzG8Wjd5OxN1W6u-aX_lalQVuaSHsdi/view?usp=sharing
This was the model I used -- Note- if it's wrong can you please send me to a place where I can get a new one/if you have a base Detectron2 .onnx model or a script to get one it would be much appreciated. 

### Expected behavior
It would check my model

**Comment by frankvp11** [comment]
I'm currently rebuilding the onnx model, I'll update here if it works/gives different errors

**Comment by jcwchen** [comment]
Hi @frankvp11,
The model you provided is fine from ONNX perspective. I have run onnx.checker with full_check and it didnot complain anything. Since the error happened in `polygraphy` during Runtime, I would suggest you contact their team to get the best support. Thanks.

**Comment by frankvp11** [comment]
Thanks- How should I contact them - make an issue on their page?

**Comment by jcwchen** [comment]
I don't have much context about this tool, but I guess https://github.com/NVIDIA/TensorRT might be a proper place.

**Comment by frankvp11** [comment]
Alright, thanks I'll move there

**Comment by jcwchen** [comment]
It seems you have transferred this issue there. I will close this one then. Feel free to reopen it if you still have other ONNX questions. Thanks!

**Comment by TimNekk** [comment]
Remove `--medvram` or `--lowram` args, it works!
