### ISSUE TITLE
[BUG] ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158447

### ISSUE THREAD

**Issue by michaelroyzen** [onnx/onnx#4394]
@jcwchen Optimizing large models fails in the latest release of onnx (1.12.0) even with use_external_data_format=True.

In the latest version of onnxruntime, calling `OnnxModel.save(self.model, output_path, use_external_data_format, all_tensors_to_one_file)` fails with the following stack trace:

> True
Traceback (most recent call last):
File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 525, in 
main()
File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
optimizer.export(
File "/home/mroyzen/train_files/optimum/optimum/onnxruntime/optimization.py", line 150, in export
optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format=True)
File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 938, in save_model_to_file
OnnxModel.save(self.model, output_path, use_external_data_format, all_tensors_to_one_file)
File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 914, in save
save_model(
File "/opt/conda/lib/python3.8/site-packages/onnx/init.py", line 202, in save_model
s = _serialize(proto)
File "/opt/conda/lib/python3.8/site-packages/onnx/init.py", line 71, in _serialize
result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158447

[Linking my onnxruntime issue as well](https://github.com/microsoft/onnxruntime/issues/12359), and I believe [this feature request](https://github.com/onnx/onnx/issues/3775) is related. Your help would be appreciated. Thanks!

**Comment by jcwchen** [comment]
Hi @michaelroyzen,
If possible, could you please provide the failed model for me to repro? (although it's a huge one) Thanks!

**Comment by michaelroyzen** [comment]
@jcwchen the model is [ahotrod/albert_xxlargev1_squad2_512](https://huggingface.co/ahotrod/albert_xxlargev1_squad2_512)

**Comment by jcwchen** [comment]
Thanks for providing, but there are only original PyTorch and TF models. May I have the converted ONNX model if you have it handy?

**Comment by michaelroyzen** [comment]
@jcwchen I'm running the conversion using this script: https://github.com/huggingface/optimum/blob/main/examples/onnxruntime/optimization/question-answering/run_qa.py

**Comment by jcwchen** [comment]
I don't have handy onnxruntime-gpu so I tried to run your script without `--optimize_for_gpu` and with `CPUExecutionProvider`. The converted ONNX model seems fine. It would be very helpful if you can share the ONNX model you have which you bumped into the load/save errors.

Regarding this issue, my best guess would be `all_tensors_to_one_file=True` might still create a single tensor larger than 2GB. Perhaps you can change it to `all_tensors_to_one_file=False` and then give it one more try.

**Comment by michaelroyzen** [comment]
Did it really work for you @jcwchen? I re-ran the script without `--optimize_for_gpu` and with `CPUExecutionProvider` and it gave the same ValueError as above. I tried setting all_tensors_to_one_file=False, but it refused to save (saying the file already existed, even though it did not).

**Comment by jcwchen** [comment]
> Did it really work for you @jcwchen? I re-ran the script without --optimize_for_gpu and with CPUExecutionProvider and it gave the same ValueError as above. 

Sorry I might not be clear. In detail, the script was not completed (my error is `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Deserialize tensor onnx::MatMul_1440 failed.open file onnx__MatMul_1440 fail, errcode = 2 - The system cannot find the file specified.`), but there is still an converted model (under `albert_xxlargev1_squad2_512_onnx_optimized` directory) and so I played with it by onnx.load and onnx.save, which seems fine without errors.

> I tried setting all_tensors_to_one_file=False, but it refused to save (saying the file already existed, even though it did not).

Could you please share the complete error message? (I was wondering which file has already existed and where complains it)

**Comment by michaelroyzen** [comment]
@jcwchen Setting `all_tensors_to_one_file=False` still leads to:

> Traceback (most recent call last):
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 524, in <module>
    main()
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
    optimizer.export(
  File "/opt/conda/lib/python3.8/site-packages/optimum/onnxruntime/optimization.py", line 149, in export
    optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format, all_tensors_to_one_file=False)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 934, in save_model_to_file
    save_model(self.model, output_path)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 202, in save_model
    s = _serialize(proto)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 71, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 3038449703

as you can see, `all_tensors_to_one_file=False` is set to False in the stack trace

**Comment by jcwchen** [comment]
Thanks for the details. Quick question, did you set `all_tensors_to_one_file=False` with `use_external_data_format=True`? If so, how about `convert_attribute=True` also?

Ideally the setting above will divide the single huge ONNX proto into a few or many small tensors.

**Comment by michaelroyzen** [comment]
`convert_attribute=True`did not work:

`Traceback (most recent call last):
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 524, in <module>
    main()
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
    optimizer.export(
  File "/opt/conda/lib/python3.8/site-packages/optimum/onnxruntime/optimization.py", line 149, in export
    optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format=True, all_tensors_to_one_file=False, convert_attribute=True)
TypeError: save_model_to_file() got an unexpected keyword argument 'convert_attribute'`

However, converting the model to fp16 and _then_ saving it did work.

**Comment by jcwchen** [comment]
> convert_attribute=Truedid not work:

I meant the API for onnx.save_model. Please check [here](https://github.com/onnx/onnx/blob/66480ce6ab0f4c56e27bb120f246c3ddd0d1e19e/onnx/__init__.py#L171).

> However, converting the model to fp16 and then saving it did work.

Good to know you have solved it somehow. From ONNX perspective, save_model provides the options (`save_as_external_data`, `all_tensors_to_one_file`, `size_threshold`, `convert_attribute`) to divide large ONNX models into small external tensors. Setting the options above properly should convert the main proto to be a much smaller one, because large tensors like initializers which have huge raw_data can be converted to smaller external tensors (Usually these large initializers are the main the reason causing large ONNX models). If setting these options anyway cannot resolve this 2GB exceed problem , there might be other situation we need to take care from the ONNX side.

**Comment by JingyaHuang** [comment]
Hi @jcwchen, I tried setting `use_external_data_format=True` + `all_tensors_to_one_file=False` + `convert_attribute=True` with some smaller `size_threshold` (1024->512->256->128), it doesn't seems to solve the issue. 
Here is a screenshot of some files that succeeded in the export:
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/44135271/182421616-21299f07-5624-40cf-9d78-b7932bb9e3d2.png">

**Comment by jcwchen** [comment]
Hi @JingyaHuang,
Thanks for the updates! Have you tried size_threshold=0? I keep trying to repro this error, but I still saw different failures instead of this 2GB issue so it's quite hard for me to debug... Here are my enviorment settings. Please correct me if I am wrong:
```
Optimum 1.2.3
PyTorch 1.12.0,
Transformers 4.19.0,
onnxruntime-gpu 1.12.0
```
I run this command with the branch of optimum v1.2.3:
```
python run_qa.py --model_name_or_path ahotrod/albert_xxlargev1_squad2_512 --dataset_name squad_v2 --optimization_level 99 --do_eval --output_dir albert_xxlargev1_squad2_512_onnx_optimized --execution_provider CUDAExecutionProvider --optimize_for_gpu --overwrite_output_dir
```
I saw failure like
```
transformers\hf_argparser.py", line 223, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--optimization_level', '99', '--optimize_for_gpu']
```

**Comment by JingyaHuang** [comment]
Hi @jcwchen!
By setting `size_threshold=0`, I got the same error message with only `model.onnx` exported.
```
Traceback (most recent call last):
  File "run_qa.py", line 544, in <module>
    main()
  File "run_qa.py", line 329, in main
    optimizer.export(
  File "/workspace/optimum/onnxruntime/optimization.py", line 152, in export
    optimizer.save_model_to_file(
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 938, in save_model_to_file
    OnnxModel.save(self.model, output_path, use_external_data_format, all_tensors_to_one_file)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 915, in save
    save_model(
  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 197, in save_model
    s = _serialize(proto)
  File "/usr/local/lib/python3.8/dist-packages/onnx/__init__.py", line 66, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215159045
```
As for the reproduction, I have the following __setup__:
```
#onnxruntime-gpu nightly
ort-nightly-gpu     1.13.0.dev20220802003
onnx                1.12.0
torch               1.12.0+cu113
transformers        4.21.0
```
For __optimum__, can you maybe try building it __from source__ with 
`pip install git+https://github.com/huggingface/optimum.git@add_onnx_export_options`? (This is a branch with `disable_shape_inference` added to the config, which makes it compatible with the nightly built onnxruntime-gpu.)

Also, use the [__updated qa example__](https://github.com/huggingface/optimum/tree/add_onnx_export_options/examples/onnxruntime/optimization/question-answering) from the same branch and run with the following command:
```
python run_qa.py \
--model_name_or_path albert-xxlarge-v1 \
--dataset_name squad_v2 \
--optimization_level 99 \
--do_eval \
--output_dir /tmp/albert_xxlargev1_squad2 \
--execution_provider CUDAExecutionProvider \
--optimize_for_gpu \
--overwrite_output_dir \
--all_tensors_to_one_file False \
--use_external_data_format
```
However this will only allow configuring `all_tensors_to_one_file` and `use_external_data_format`, as the `OnnxModel.save_model_to_file` don't support configuring `convert_attribute` nor `size_threshold`.

https://github.com/microsoft/onnxruntime/blob/01f3a197d7ef0f35144be01f585f6670421e35ee/onnxruntime/python/tools/transformers/onnx_model.py#L926-L927

So I've done some hacky changes on the `OnnxModel.save` allowing me to set manually the value of `convert_attribute` nor `size_threshold`. 

https://github.com/microsoft/onnxruntime/blob/01f3a197d7ef0f35144be01f585f6670421e35ee/onnxruntime/python/tools/transformers/onnx_model.py#L915-L921

**Comment by jcwchen** [comment]
Hi @JingyaHuang,
Thank you so much for the detailed instructions. They are indeed helpful. Appreciate it. Now I can finally repro this issue from my end. I don't have GPU in my work computer so I run the command as below:
```
python run_qa.py --model_name_or_path ahotrod/albert_xxlargev1_squad2_512 --dataset_name squad_v2 --do_eval --output_dir albert_xxlargev1_squad2_512_onnx_optimized --execution_provider CPUExecutionProvider --overwrite_output_dir
```
And then I saw the error:
```
[INFO|modeling_utils.py:1953] 2022-08-03 15:40:38,923 >> loading weights file https://huggingface.co/ahotrod/albert_xxlargev1_squad2_512/resolve/main/pytorch_model.bin from cache at C:\Users\chunwche/.cache\huggingface\transformers\f91c5efe33bd9eae2353aa0711152f4ca23d5dc0ad8f1cbc8b5c2f36dba0233c.0b363692abe6210ed650f4122e4fda3502a6eef3b9b51f7ef7d9f378d0054425
[INFO|modeling_utils.py:2263] 2022-08-03 15:40:41,985 >> All model checkpoint weights were used when initializing AlbertForQuestionAnswering.

[INFO|modeling_utils.py:2271] 2022-08-03 15:40:41,985 >> All the weights of AlbertForQuestionAnswering were initialized from the model checkpoint at ahotrod/albert_xxlargev1_squad2_512.
If your task is similar to the task the model of the checkpoint was trained on, you can already use AlbertForQuestionAnswering for predictions without further training.
08/03/2022 15:40:42 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at C:\Users\chunwche\.cache\huggingface\datasets\squad_v2\squad_v2\2.0.0\09187c73c1b837c95d9a249cd97c2c3f1cebada06efe667b4427714b27639b1d\cache-f14ff9951ef31f2c.arrow
Traceback (most recent call last):
  File "C:\Users\chunwche\Documents\GitHub\optimum\examples\onnxruntime\quantization\question-answering\run_qa.py", line 694, in <module>
    main()
  File "C:\Users\chunwche\Documents\GitHub\optimum\examples\onnxruntime\quantization\question-answering\run_qa.py", line 641, in main
    quantizer.export(
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\optimum\onnxruntime\quantization.py", line 371, in export
    quantizer.model.save_model_to_file(onnx_quantized_model_output_path, use_external_data_format)
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\onnxruntime\quantization\onnx_model.py", line 264, in save_model_to_file
    onnx.save_model(self.model, output_path)
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\onnx\__init__.py", line 197, in save_model
    s = _serialize(proto)
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\onnx\__init__.py", line 67, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2432513817
```
Then, I tried to set `save_as_external_data=True, all_tensors_to_one_file=False, location="albert_xxlargev1_squad2_512_onnx_optimized", size_threshold= 1024, convert_attribute=True` thru optimum's or onnxruntime's APIs, but as you mentioned currently these attributes are not fully supported there. Therefore, I kind of hacked my local ONNX's API as
```
def save_model(proto: Union[ModelProto, bytes], f: Union[IO[bytes], str], format: Optional[Any] = None, save_as_external_data: bool = False, all_tensors_to_one_file: bool = True, location: Optional[str] = None, size_threshold: int = 1024, convert_attribute: bool = False) -> None:
    if isinstance(proto, bytes):
        proto = _deserialize(proto, ModelProto())
    save_as_external_data = True
    all_tensors_to_one_file = False
    convert_attribute = True
    size_threshold = 1024
    model_filepath = _get_file_path(f)
    if model_filepath:
        basepath = os.path.dirname(model_filepath)
    if save_as_external_data:
        convert_model_to_external_data(proto, all_tensors_to_one_file, basepath, size_threshold, convert_attribute)
    if model_filepath:
        proto = write_external_data_tensors(proto, basepath)
    s = _serialize(proto)
    _save_bytes(s, f)
```
Then onnx.save seems successful because I saw `model-quantized.onnx` under my `albert_xxlargev1_squad2_512_onnx_optimized` directory, although `python run_qa.py` still failed eventually because of the following error:
```
08/03/2022 16:23:37 - INFO - __main__ - *** Evaluate ***
Traceback (most recent call last):
  File "C:\Users\chunwche\Documents\GitHub\optimum\examples\onnxruntime\quantization\question-answering\run_qa.py", line 694, in <module>
    main()
  File "C:\Users\chunwche\Documents\GitHub\optimum\examples\onnxruntime\quantization\question-answering\run_qa.py", line 664, in main
    outputs = ort_model.evaluation_loop(eval_dataset)
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\optimum\onnxruntime\model.py", line 98, in evaluation_loop
    preds = session.run(self.onnx_named_outputs, onnx_inputs)
  File "C:\Users\chunwche\Anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))
```

It seems to me at least onnx.save does work normally with hard-coded setting. @JingyaHuang perhaps you can also try this updated API (onnx.save_model) from your end and see how it goes? Thank you.

**Comment by JingyaHuang** [comment]
Hi @jcwchen, 

Thanks for taking care of this!

However, by hacking `onnx=1.12.0` with your snippet, I still got the same error on the model size as before(also tried reducing the `size_threshold` but it doesn't work either). Can you share more details about your env setup? 

Thanks again!

**Comment by jcwchen** [comment]
Thanks for looking into this -- my env setup:
```
torch 1.11.0
onnx 1.12.0 # with my change in save_model
onnxruntime 1.12.0
optimum 1.12.3
transformers 4.19.0
Windows 10 Python 3.9.7
```
And I ran the command as below:
```
python run_qa.py --model_name_or_path ahotrod/albert_xxlargev1_squad2_512 --dataset_name squad_v2 --do_eval --output_dir albert_xxlargev1_squad2_512_onnx_optimized --execution_provider CPUExecutionProvider --overwrite_output_dir
```

Share how I debug this -- You can set a stop point before the line causes the size error like
```
if model_filepath:
    basepath = os.path.dirname(model_filepath)
    proto = write_external_data_tensors(proto, basepath)
import IPython  # debug
IPython.embed()  # stop point
s = _serialize(proto)
```
Then you can inspect the proto and further use `convert_model_to_external_data` to convert it with different options if needed. From my end after a successful conversion, `proto.ByteSize()` should be a reasonable number (0 <= size < 2147483648). Those large initializers should be converted to external tensors.

**Comment by JingyaHuang** [comment]
Hi @jcwchen,

Thanks a lot for the debug details, it is really helpful!

After several re-tries, unfortunately, I can still not reproduce the success. By changing the export options, the proto size was reduced significantly from 9682228512 to around 2215161809, it seems that even though I have exported all tensors(the case of `size_threshold=0` I think) to external files, the remaining proto still exceeds the 2GB size limit.

Here are some details about the experiment:
(```save_as_external_data=True, all_tensors_to_one_file=False, convert_attribute=True```)

| size_threshold  |  Proto size after external write  | 
|----------------|--------------------------------|
| 1024                  |  2215162687                               | 
| 512                    |  2215161809                               | 
| 256                   |  2215161809                               | 
| 128                    |  2215161809                               | 
| 0                        |  2215162785                               |

As for the environment, I set it up as you have mentioned, except for that I am using Linux instead of Windows. Have I done something wrong?

**Comment by jcwchen** [comment]
Thanks for the update and experiment. One more possible variance I can think of: did you run `run_qa.py` on optimum 1.12.3's commit? (`5a0106d781a8358aa7eab88a8b115a538b4840d1`)

**Comment by JingyaHuang** [comment]
Hi @jcwchen,

Thanks for the suggestion! 

I just found that actually the difference came from the fact that I was using optimization example instead of the quantization example. Now I have successfully exported the proto. 

Thank you so much for helping, I will integrate these large proto export features in optimum. Thanks again for your help!
