### ISSUE TITLE
Unable to build proper onnx python module

### ISSUE THREAD

**Issue by harikmgit** [onnx/onnx#4398]
Hello,
We are building onnxruntime for powerpc for AIX which is big endian. We are successfully able to build onnxruntime and python's dir() is good as below:
>>> dir(onnxruntime)
['ExecutionMode', 'ExecutionOrder', 'GraphOptimizationLevel', 'IOBinding', 'InferenceSession', 'ModelMetadata', 'NodeArg', 'OrtAllocatorType', 'OrtArenaCfg', 'OrtDevice', 'OrtMemType', 'OrtMemoryInfo', 'OrtSparseFormat', 'OrtValue', 'RunOptions', 'SessionIOBinding', 'SessionOptions', 'SparseTensor', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'capi', 'create_and_register_allocator', 'cuda_version', 'disable_telemetry_events', 'enable_telemetry_events', 'get_all_providers', 'get_available_providers', 'get_device', 'import_capi_exception', 'onnxruntime_validation', 'package_name', 'set_default_logger_severity', 'set_default_logger_verbosity', 'set_seed', 'version']
>>>

But for some reason, onnx is not properly built.
On AIX below is output:
>>> dir(onnx)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

On Linux below is output:
>>> dir(onnx)
['Any', 'AttributeProto', 'DESCRIPTOR', 'EXPERIMENTAL', 'FunctionProto', 'GraphProto', 'IO', 'IR_VERSION', 'IR_VERSION_2017_10_10', 'IR_VERSION_2017_10_30', 'IR_VERSION_2017_11_3', 'IR_VERSION_2019_1_22', 'IR_VERSION_2019_3_18', 'IR_VERSION_2019_9_19', 'IR_VERSION_2020_5_8', 'MapProto', 'ModelProto', 'NodeProto', 'ONNX_ML', 'OperatorProto', 'OperatorSetIdProto', 'OperatorSetProto', 'OperatorStatus', 'Optional', 'OptionalProto', 'STABLE', 'SequenceProto', 'SparseTensorProto', 'StringStringEntryProto', 'TensorAnnotation', 'TensorProto', 'TensorShapeProto', 'Text', 'TrainingInfoProto', 'TypeProto', 'TypeVar', 'Union', 'ValueInfoProto', 'Version', '_Proto', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_deserialize', '_get_file_path', '_load_bytes', '_save_bytes', '_serialize', 'absolute_import', 'cast', 'checker', 'convert_model_to_external_data', 'defs', 'division', 'enum_type_wrapper', 'external_data_helper', 'google', 'helper', 'load', 'load_external_data_for_model', 'load_from_string', 'load_model', 'load_model_from_string', 'load_tensor', 'load_tensor_from_string', 'mapping', 'onnx', 'onnx_cpp2py_export', 'onnx_data_pb', 'onnx_data_pb2', 'onnx_dot_onnx__ml__pb2', 'onnx_ml_pb2', 'onnx_operators_ml_pb2', 'onnx_operators_pb', 'onnx_pb', 'os', 'print_function', 'save', 'save_model', 'save_tensor', 'shape_inference', 'string_types', 'unicode_literals', 'utils', 'version', 'write_external_data_tensors']

 Not sure why this is happening. I request your suggestions. Thanks!!! Hari

**Comment by jcwchen** [comment]
Hi @harikmgit,
Not sure whether I understand your question correctly -- are you saying why building onnxruntime from source does not bring ONNX Python module? IIUC, onnxruntime mostly relies on C++ part of ONNX and it won't build Python onnx for users. If you need Python ONNX, you need to either get it from PyPI or build ONNX from source.

**Comment by harikmgit** [comment]
Hello @jcwchen, thanks for information. I cloned and created a build successfully but below issue still exists.
>>> dir(onnx)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__'

(0) root @ fvt-lp: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx
# diff CMakeLists.txt CMakeLists.txt.orig
19,20c19
< #option(ONNX_USE_PROTOBUF_SHARED_LIBS "Build ONNX using protobuf shared library. Sets PROTOBUF_USE_DLLS CMAKE Flag and Protobuf_USE_STATIC_LIBS. " OFF)
< option(ONNX_USE_PROTOBUF_SHARED_LIBS "Build ONNX using protobuf shared library. Sets PROTOBUF_USE_DLLS CMAKE Flag and Protobuf_USE_STATIC_LIBS. " ON)
---
> option(ONNX_USE_PROTOBUF_SHARED_LIBS "Build ONNX using protobuf shared library. Sets PROTOBUF_USE_DLLS CMAKE Flag and Protobuf_USE_STATIC_LIBS. " OFF)
22,25c21
< set(pybind11_DIR /opt/freeware/lib/python3.7/site-packages/pybind11/share/cmake/pybind11)
<
< option(BUILD_ONNX_PYTHON "Build Python binaries" ON)
< #option(BUILD_ONNX_PYTHON "Build Python binaries" OFF)
---
> option(BUILD_ONNX_PYTHON "Build Python binaries" OFF)

(0) root @ fvt-lp: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx
# cmake .
-- Build type not set - defaulting to Release
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/freeware/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/freeware/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /opt/freeware/bin/python (found version "3.7.12")
-- Found PythonLibs: /opt/freeware/lib64/libpython3.7m.a (found version "3.7.12")
-- Found Protobuf: /opt/freeware/lib64/libprotobuf.a (found version "3.19.4")
Generated: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-ml.proto
Generated: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-operators-ml.proto
Generated: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-data.proto
-- Found PythonLibs: /opt/freeware/lib64/libpython3.7m.a
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Failed
-- Found pybind11: /opt/freeware/lib/python3.7/site-packages/pybind11/include (found version "2.7.1" )
--
-- ******** Summary ********
--   CMake version             : 3.22.0
--   CMake command             : /opt/freeware/bin/cmake
--   System                    : AIX
--   C++ compiler              : /opt/freeware/bin/g++
--   C++ compiler version      : 10.3.0
--   CXX flags                 : -I/opt/freeware/include -Wno-unused-variable -Wl,-bbigtoc,-lpython3.7m -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : __STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH         :
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         :
--
--   ONNX version              : 1.12.0
--   ONNX NAMESPACE            : onnx
--   ONNX_USE_LITE_PROTO       : OFF
--   USE_PROTOBUF_SHARED_LIBS  : ON
--   Protobuf_USE_STATIC_LIBS  : OFF
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
--
--   Protobuf compiler         : /opt/freeware/bin/protoc
--   Protobuf includes         : /opt/freeware/include
--   Protobuf libraries        : /opt/freeware/lib64/libprotobuf.a
--   BUILD_ONNX_PYTHON         : ON
--     Python version        :
--     Python executable     : /opt/freeware/bin/python
--     Python includes       : /opt/freeware/include/python3.7m
-- Configuring done
-- Generating done
-- Build files have been written to: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx

(0) root @ fvt-lp: /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx
# cmake --build .
[  1%] Running gen_proto.py on onnx/onnx.in.proto
Processing /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx.in.proto
Writing /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-ml.proto
Writing /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-ml.proto3
generating /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx_pb.py
[  2%] Running C++ protocol buffer compiler on /ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/onnx-ml.proto
Writing mypy to onnx/onnx_ml_pb2.pyi
Target "CMakeFiles/gen_onnx_proto.dir/build" is up to date.
.........
..........
..............
cc1: warning: command-line option '-Wnon-virtual-dtor' is valid for C++/ObjC++ but not for C
[100%] Linking C shared library libonnxifi_dummy
Target "CMakeFiles/onnxifi_dummy.dir/build" is up to date.
[100%] Built target onnxifi_dummy
Target "all" is up to date.
Target "default_target" is up to date.
########################################################
(0) root @ fvtzep4-lp20: /ONNX/ONNX_only_3rdAugust2022_FINAL
# python3
Python 3.7.12 (default, Dec 15 2021, 03:25:47)
[GCC 8.3.0] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> from onnx.onnx_cpp2py_export import ONNX_ML
>>> dir(onnx)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'onnx_cpp2py_export']
>>> import onnx.onnx_data_pb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'onnx.onnx_data_pb'
>>> import onnx.onnx.onnx_data_pb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/__init__.py", line 5, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx.onnx_cpp2py_export' (unknown location)
>>> import onnx.onnx.onnx_data_pb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ONNX/ONNX_only_3rdAugust2022_FINAL/onnx/onnx/__init__.py", line 5, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: cannot import name 'ONNX_ML' from 'onnx.onnx.onnx_cpp2py_export' (unknown location)



Any suggestions will help.

**Comment by jcwchen** [comment]
It seems you didn't build Python ONNX successfully. You can use the following command to confirm:
```
pip show onnx
```
Did you follow [the steps](https://github.com/onnx/onnx#linux) to build ONNX from source?

**Comment by harikmgit** [comment]
Thanks.. I tried now. However, i am seeing some issues.
(0) root @ fvtzep4-lp20: /ONNX/ONNX_only_4thAugust2022_FINAL/onnx
# pip install -e .
Obtaining file:///ONNX/ONNX_only_4thAugust2022_FINAL/onnx
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
......
............
Installing collected packages: onnx
  Running setup.py develop for onnx
    error: subprocess-exited-with-error

    python setup.py develop did not run successfully.
    exit code: 1

    [109 lines of output]
    running develop
    running build_py
    running create_version
    running cmake_build
    Extra cmake args: ['-DONNX_USE_LITE_PROTO=ON']
    Using cmake args: ['/opt/freeware/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/freeware/include/python3.7m', '-DPYTHON_EXECUTABLE=/opt/freeware/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '-DONNX_USE_LITE_PROTO=ON', '/ONNX/ONNX_only_4thAugust2022_FINAL/onnx']
........
............
    -- ******** Summary ********
    --   CMake version             : 3.22.0
    --   CMake command             : /opt/freeware/bin/cmake
    --   System                    : AIX
    --   C++ compiler              : /opt/freeware/bin/g++
    --   C++ compiler version      : 10.3.0
    --   CXX flags                 : -I/opt/freeware/include -Wno-unused-variable -Wl,-bbigtoc,-lpython3.7m -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.12.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : ON
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /opt/freeware/bin/protoc
    --   Protobuf includes         : /opt/freeware/include
    --   Protobuf libraries        : /opt/freeware/lib64/libprotobuf.a
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /opt/freeware/bin/python3
    --     Python includes       : /opt/freeware/include/python3.7m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /ONNX/ONNX_only_4thAugust2022_FINAL/onnx/.setuptools-cmake-build
    **make: 1254-002 Cannot find a rule to create target 24 from dependencies.**
    Stop.
.....
.......
    **/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,**
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/ONNX/ONNX_only_4thAugust2022_FINAL/onnx/setup.py", line 354, in <module>
        "backend-test-tools = onnx.backend.test.cmd_tools:main",
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
        cmd_obj.run()
      File "/ONNX/ONNX_only_4thAugust2022_FINAL/onnx/setup.py", line 239, in run
        self.run_command("build_py")
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
        cmd_obj.run()
      File "/ONNX/ONNX_only_4thAugust2022_FINAL/onnx/setup.py", line 223, in run
        self.run_command("cmake_build")
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-n2s0ulxb/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
        cmd_obj.run()
      File "/ONNX/ONNX_only_4thAugust2022_FINAL/onnx/setup.py", line 217, in run
        subprocess.check_call(build_args)
      File "/opt/freeware/lib64/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    **subprocess.CalledProcessError: Command '['/opt/freeware/bin/cmake', '--build', '.', '--', '-j', '24']' returned non-zero exit status 2.**
    [end of output]
#########################################################

Any suggestions will help.

**Comment by harikmgit** [comment]
I am able to compile onnxruntime successfully in same machine where i failed to compile onnx as in my previous update. I believe i have all required packages also.

# find /opt/freeware/bin . | grep protoc
/opt/freeware/bin/protoc
./freeware/bin/protoc

# find /opt . | grep libprotobuf
/opt/freeware/lib64/libprotobuf-lite.a
/opt/freeware/lib64/libprotobuf.a
./freeware/lib64/libprotobuf-lite.a
./freeware/lib64/libprotobuf.a

# dnf list | grep python3-dev
python3-devel.ppc                               3.7.12-1         @AIX_Toolbox

Not sure if anything is missing.

**Comment by jcwchen** [comment]
> I am able to compile onnxruntime successfully in same machine where i failed to compile onnx as in my previous update. I believe i have all required packages also.

ONNXRuntime builds Protobuf as submodule so although you have built ONNXRuntime from source successfully, you still might bump into Protobuf issue while building ONNX. How did you install your Protobuf? If you get it from apt-get or Conda, then setting `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` is needed. Since I don't see the root cause of your build error, could you please try `python setup.py install` to build instead and share the error message with me? Thank you.

**Comment by harikmgit** [comment]
Thanks for your help. Issue was resolved. AIX "make" command is not suitable for open source work. When i installed "make" from AIX opensource toolbox, issue was resolved.
Thanks,
Hari.
