### ISSUE TITLE
How to modify the output dimension after pytorch is converted to onnx？

### ISSUE THREAD

**Issue by tian123-zxc** [onnx/onnx#4402]
After converting my yolov5s model to onnx, I found that the output is float32[1,21,80,80], but this does not meet my requirements. How can I increase the one-dimensional output, such as [1,7,80,80,3]
I can't find any relevant information, what should I do?
![image](https://user-images.githubusercontent.com/83101407/182307538-883ba4a2-3983-4d55-a798-d838cf4a864a.png)

**Comment by tian123-zxc** [comment]
> I think it is not related to onnx. You need to modify your PyTorch code (e.g. add reshape or/and transpose op) to make the PyTorch model return [1,7,80,80,3] tensor.

> 
Thanks for your suggestion, I just touched on this, where should I change it, or if there is a similar case. Also, do I need to retrain the model.

**Comment by tian123-zxc** [comment]
> > 感谢您的建议，我刚刚谈到了这个，我应该在哪里更改它，或者是否有类似的情况。另外，我是否需要重新训练模型。
> 
> 不需要再培训。有关详细步骤，您可能需要查看[pytorch 教程](https://pytorch.org/tutorials/beginner/basics/intro.html)和[torch.onnx 教程](https://pytorch.org/docs/stable/onnx.html)。

thanks for your help

**Comment by daquexian** [comment]
Closing. Feel free to reopen it if you have further questions.
