### ISSUE TITLE
No shipped stubs and using mypy

### ISSUE THREAD

**Issue by KubinGH** [onnx/onnx#4404]
### Question
It looks like default ONNX (both installed through pip and conda-forge) does not ship with stub files that mypy can use for typing types like `TensorProto`, `AttributeProto`, etc. `*Proto`.  Is there any way to generate them when using the library, or is this a bug?

When I tried using `python setup.py develop` myself, it correctly generated the stubs (`.pyi`s for all the protobuf modules), but it would be nice if this worked when installing through a manager. I tracked down that the `cmake` generates the stubs with the `ONNX_GEN_PB_TYPE_STUBS` flag:

 https://github.com/onnx/onnx/blob/66480ce6ab0f4c56e27bb120f246c3ddd0d1e19e/CMakeLists.txt#L274-L296

However, they don't seem to be generated on a default installation, and I'm not sure why.

### System information
- OS Platform and Distribution: macOS Monterey 12.4
- ONNX version: 1.12.0 
- Python version: 3.10.5

### Further information
- Relevant Area: best practices

### Notes

The main issue is that types like `AttributeProto` end up as `Any`, even though we know that they are concrete.
Additionally, information on what fields they have is lost. 

```py
# test.py
import onnx
reveal_type(onnx.helper.AttributeProto)
```

```py
test.py:1: error: Skipping analyzing "onnx": module is installed, but missing library stubs or py.typed marker
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
test.py:3: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by jcwchen** [comment]
Hi @KubinGH,
Good question -- thank you for catching this. I don't have the history context that why onnx did not ship stubs in PyPI, but it seems something good to have as long as it does not have an impact on performance or binary size. I propose a possible fix for it: https://github.com/onnx/onnx/pull/4412. Please review it. Thanks!

**Comment by KubinGH** [comment]
Are you sure this fully fixes the issue? It still types `AttributeProto` as `Any` for me:

```py
import onnx
reveal_type(onnx.helper.AttributeProto)
```

```
$ mypy test.py 
test.py:2: note: Revealed type is "Any"
Success: no issues found in 1 source file
```

Note: I had to build this myself as I'm on Apple Silicon (sorry for not specifying this), using `python setup.py bdist_wheel`. 

It would seem like there are still no stub files (.pyi) for the protobuf types, they seem to be generated in the `onnx/` directory during build, but are not copied to the wheel.

I didn't manage to find a solution to this just yet due to some issues building, but I would assume the cmake could copy the `.pyi` files to the build as well?

**Comment by jcwchen** [comment]
From my end, I installed the wheel from [here](https://github.com/onnx/onnx/actions/runs/2800030156), which was produced by that PR, and it showed:
```
mypy test.py
test.py:2: note: Revealed type is "google.protobuf.reflection.GeneratedProtocolMessageType"
Success: no issues found in 1 source file
```
I am using Python 3.9.11 with mypy (tried both 0.782 and 0.961) on my Windows. May I understand what's your Python version? It seems that the fix (introducing py.typed) cannot work with some old Pythons.

**Comment by jcwchen** [comment]
I don't have a handy M1 or M2 machine, but I tried to install the prebuilt Mac wheel on my old Mac (not M1/M2) and run `mypy test.py`. It seems mypy can get the correct instead of Any as well.

Did you apply my PR's change in your ONNX codebase and install onnx from `dist/*.whl` after running `python setup.py bdist_wheel`?

**Comment by KubinGH** [comment]
Hi, I think the issue might be indeed related to different architectures/Python versions. But I think I found a fix that also properly lists the attributes of the proto object instead of typing as `Any`.

```py
# test.py
import onnx
reveal_type(onnx.AttributeProto)
reveal_type(onnx.AttributeProto().name)
```

```py
$ mypy test.py                  
test.py:2: note: Revealed type is "def (<snip, attribute list...>) -> onnx.onnx_ml_pb2.AttributeProto"
test.py:3: note: Revealed type is "builtins.str"
Success: no issues found in 1 source file
``` 

Would you consider applying the following patch in `setup.py` in your PR and check if it works for you as well?

```py
-    package_data={"onnx": ["py.typed"]},
+    package_data={"onnx": ["py.typed", "*.pyi"]},
```

**Comment by jcwchen** [comment]
> Would you consider applying the following patch in setup.py in your PR and check if it works for you as well?

Sure. Just added. I can repro the issue you mentioned. The binary size (wheel) just increases by 5KB so adding your patch looks fine to me. Please review it again. Thanks!

**Comment by KubinGH** [comment]
All good!
