### ISSUE TITLE
Exposing a Python interface for calling inference functions

### ISSUE THREAD

**Issue by KubinGH** [onnx/onnx#4405]
# Feature Request

### Feature description
Currently, [the only place](https://github.com/onnx/onnx/blob/d6a0fefa83828dfbaab15e5477ce5c95b12b7be9/onnx/shape_inference/implementation.cc#L332) where `TypeAndShapeInferenceFunction`s (as set in `defs.cc`) are called is the `InferShapes` function. However, for one to call it from the Python API we need a well-formed `ModelProto`, for which inputs and outputs have to be set. 

It seems like for many (all?) cases the output types could be inferred from the inputs, and exposing inference functions could be useful to achieve this for libraries building models - avoiding reimplementing the inference routines instead of using the reference implementation.

The inference functions do not have Python bindings, but it seems like they could. This should be somewhat straightforward following the existing `pybind11` code.

### Alternatives
- Allowing `InferShapes` to work without output shapes specified
  - In this case, we can provide an entire finished model and infer types in one go. Could be useful, but an incremental approach where we can call the inference functions at any point sounds more useful and efficient.
- Reimplementing the standard inferences on Python-side in the reference API.
  - Currently this basically ends up happening in converter libraries, but the implementation could be moved to `onnx.shape_inference`. Doesn't seem like a good idea since the implementation already exists in C++.

### API
Most likely `OpSchema` would receive a new method in Python bindings like `infer_types(node: NodeProto, ...)`, taking objects necessary to construct an `InferenceContext`. It would return the updated objects. 
It may have inference errors thrown in the inference functions, unsure what would be the wanted behaviour when exceptions are disabled.

### Feature Area
Which area in ONNX does this impact?: Python API, shape inference

### Are you willing to contribute it
Yes.

**Comment by gramalingam** [comment]
Sounds good to me. Yes, it is unclear what we could do in builds with exceptions turned off, since it will just crash. It would be useful to see the proposed interface/API. Thanks!

**Comment by KubinGH** [comment]
Please see the draft PR for a proposal - it's not finished yet, as I saw some complications.

- Currently I'm passing in arguments to construct an `InferenceContextImpl` from Python. Some of them, however, make things more complex:
  - `generatedShapeData` basically requires also exposing a similar partial data propagation interface. 
  - Additionally, `graphInferenceContext` takes a lot of arguments, too (it's used for type inference when GraphProto attributes are present), which would complicate the interface.
- The existing bindings don't seem to handle Python Proto types properly, and cast everything to bytes. I do this similarly.

I successfully used this in another project wrapping it in a function similar to the one present in the added test case. Maybe could consider adding something like this to `onnx.helper`?
