### ISSUE TITLE
Can you provide the code of CKPT to onnx?

### ISSUE THREAD

**Issue by xingjunhong** [onnx/onnx#4406]
Can you provide the code of CKPT to onnx?

**Comment by jcwchen** [comment]
It's a model-specific question in PyTorch... Different PyTorch's .ckpt files need different code (with the original PyTorch model's information) to load them back into `torch.nn.Module`. Take SuperResolution as an example: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html.
