### ISSUE TITLE
Can not load onnx model with opset_version=14

### ISSUE THREAD

**Issue by phamkhactu** [onnx/onnx#4407]
Thank for your great repo. I have problem with load model. Here my step by step

I convert onnx model successful
```
torch.onnx.export(model, dummy_input, model_path, verbose=False, input_names=['input'], output_names=['output'], opset_version=14)

``` 
but when I load onn model, I get error:
```
self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from weights/model.onnx failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (5287) of operator (CumSum) in node (CumSum_2919) is invalid.
```
Thank for your respone.

**Comment by jcwchen** [comment]
Hi @phamkhactu,
If possible, could you please provide the model for me to repro this issue? Thanks.

**Comment by phamkhactu** [comment]
> Hi @phamkhactu, If possible, could you please provide the model for me to repro this issue? Thanks.

@jcwchen  here my model [link](https://drive.google.com/file/d/1G35Rmy7pM5lZ3E5Lrx_6S0lSEatSMT4F/view?usp=sharing)

**Comment by jcwchen** [comment]
Thank you for providing the details and I can repro this issue. I think it should be an issue in the exporter (torch.onnx.export), because CumSum does not allow bool as an input but it gets input from previous Equal op, which only outputs bool. The exporter should handle this by something like using a Cast op in the middle. Please raise this issue there (under PyTorch repo) to let exporter experts be aware of it.

**Comment by phamkhactu** [comment]
> because CumSum does not allow bool as an input but it gets input from previous Equal op, which only outputs bool. The exporter should handle this by something like using a Cast op in the middle. Please raise this issue there (under PyTorch repo) to let exporter experts be aware of it.

@jcwchen  Thank you.

**Comment by jcwchen** [comment]
Close here since it has been tracked in the exporter instead. Feel free to reopen it if you still other ONNX questions. Thanks!
