### ISSUE TITLE
ONNX GraphProto Structure

### ISSUE THREAD

**Issue by asyms** [onnx/onnx#4410]
### Question
Hi,

I've been digging into the structure of the GraphProto object, but have a question regarding the DAG aspect. Where is the information stored regarding which nodes are the successor or predecessor of a node? I.e. the edges between the nodes, are they saved anywhere or just inferred from the tensor names?

Thanks.
Arne

**Comment by asyms** [comment]
Hi @jcwchen,

Thanks for your reply. This aligns with my thoughts. One small follow-up question from yoru response. Do you mean the the output tensor's name of a node can be used to infer what the next node is? Or do you mean that you can from that tensor name then search other nodes that have this tensor name as their input? 

In short, do the names of the nodes and the names of the tensors have to be similar in some way or not?

**Comment by jcwchen** [comment]
> Do you mean the the output tensor's name of a node can be used to infer what the next node is? Or do you mean that you can from that tensor name then search other nodes that have this tensor name as their input?

You can find the connection relationship for node to node by matching the previous node's "output name" to the next node's "input name". "Node name" is irrelevant to the connection. Please note that the node's input might come from input or initializer. You can match it by input's or initializer's "tensor name".

> In short, do the names of the nodes and the names of the tensors have to be similar in some way or not?

The name of the node is optional and used for diagnostic purposes only. You can find more details in [IR.md](https://www.1point3acres.com/bbs/thread-916663-1-1.html).

**Comment by jcwchen** [comment]
I assume this question has been resolved. Feel free to reopen it if you still have other ONNX questions. Thanks!
