### ISSUE TITLE
How can I export decoder which takes a list of tensors as input to onnx

### ISSUE THREAD

**Issue by hyuny223** [onnx/onnx#4417]
# Ask a Question

### Question
Hello. First of all, I'm not good at English, so please understand me.

i want to transform weights of monodepth2 to onnx. so I wrote codes.

This model is divided into two parts, encoder and decoder.

input of encoder is image tensor. shape is [1,3,192,640]. output is list of five tensors.
input of decoder is output of encoder and when i evaluated this model, it worked well.

but when i tried to transform this to onnx, it couldn't.

when evaluating, works well.
when exporting, cannot.

```
import argparse, os
import torch
from torch.utils.data import DataLoader
import onnx
import numpy as np

import networks
from src.options import MonodepthOptions

parser = argparse.ArgumentParser(description="onnx for monodepth2")
parser.add_argument("--pretrained_model",
                    type=str,
                    help="put the path of pretrained model")

args = parser.parse_args()


encoder_path = os.path.join(args.pretrained_model,"encoder.pth")
encoder = networks.ResnetEncoder(18, False)

decoder_path = os.path.join(args.pretrained_model, "depth.pth")
depth_decoder = networks.DepthDecoder(encoder.num_ch_enc)

# encoder_dict = torch.load(encoder_path)
# model_dict = encoder.state_dict()
# encoder.load_state_dict({k: v for k, v in encoder_dict.items() if k in model_dict})

# decoder_dict = torch.load(decoder_path)
# depth_decoder.load_state_dict(decoder_dict)

# encoder.cuda()
# encoder.eval()

depth_decoder.cuda()
depth_decoder.eval()

# # model input size에 맞게 b c h w 순으로 파라미터 설정

# f = torch.rand((1,3,192,640)).cuda()
# images = encoder(f)

f0_onnx = torch.rand((1, 64, 160, 256)).cuda()
f1_onnx = torch.rand((1, 64, 80, 128)).cuda()
f2_onnx = torch.rand((1, 128, 40, 64)).cuda()
f3_onnx = torch.rand((1, 256, 20, 32)).cuda()
f4_onnx = torch.rand((1, 512, 10, 16)).cuda()

images = (f0_onnx, f1_onnx, f2_onnx, f3_onnx, f4_onnx)

export_onnx_file = "monodepth.onnx"
torch.onnx.export(depth_decoder,
				  images,
				  export_onnx_file,
				  export_params=True,
				  do_constant_folding=True,
				  opset_version=10,
				  input_names = ['encoder_output_0', 'encoder_output_1', 'encoder_output_2', 'encoder_output_3', 'encoder_output_4'],
				  output_names = ['decoder_output_0', 'decoder_output_1', 'decoder_output_2', 'decoder_output_final'],
				  dynamic_axes={'encoder_output_0' : {0 : 'batch_size'},
				  				'encoder_output_1' : {0 : 'batch_size'},
				  				'encoder_output_2' : {0 : 'batch_size'},
				  				'encoder_output_3' : {0 : 'batch_size'},
				  				'encoder_output_4' : {0 : 'batch_size'},
				  				'decoder_output_0' : {0 : 'batch_size'},
				  				'decoder_output_1' : {0 : 'batch_size'},
				  				'decoder_output_2' : {0 : 'batch_size'},
				  				'decoder_output_final' : {0 : 'batch_size'}}
				  )

# onnx_decoder = onnx.load("monodepth.onnx")
# onnx.checker.check_model(onnx_decoder)
# print("Done: converting decoder to onnx format!")

```

ant this is log

> root@chl-Prestige-15-A11UC:~/ws/src/mono# python3 to_onnx.py --pretrained_model files/weights/models/weights_1
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and will be removed in 0.15. Please use keyword parameter(s) instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "to_onnx.py", line 51, in <module>
    torch.onnx.export(depth_decoder,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 727, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 602, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 517, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 6 were given

is there a way to solve this problem??

### Further information
model : monodepth2
https://github.com/nianticlabs/monodepth2

os : docker nvidia/cuda:11.7.0-devel-ubuntu18.04

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  
**Model opset** (*e.g. 7*):

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment]
Hi @hyuny223,
It's more like a question for the converter (torch.onnx.export). I would suggest you raise this issue in PyTorch repo (converter team is there) and tag ONNX to get the best help from the converter experts.

**Comment by hyuny223** [comment]
> Hi @hyuny223, It's more like a question for the converter (torch.onnx.export). I would suggest you raise this issue in PyTorch repo (converter team is there) and tag ONNX to get the best help from the converter experts.

I understand! Thanks for your help!

**Comment by jcwchen** [comment]
Close here since it should be a question for the exporter. Please reopen it if you still have ONNX questions. Thanks!
