### ISSUE TITLE
[Tracking] Deprecate ONNX Interface for Framework Integration (ONNXIFI)

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4418]
Deprecate ONNX Interface for Framework Integration (ONNXIFI) because related code hasn't been updated for quite a long time and recently there is few vulnerability issues in related code (e.g., https://github.com/onnx/onnx/pull/4377). IMO, we should try to deprecate it if no one is really relying on it. Please let me know if anyone is using it. Thanks!

**Comment by andife** [comment]
Addings some docs for interested readers:
https://github.com/onnx/onnx/wiki/ONNX-Interface-for-Framework-Integration:-API-Proposal
http://www.xavierdupre.fr/app/onnxcustom/helpsphinx/onnxmd/onnx_docs/ONNXIFI.html
