### ISSUE TITLE
Model with input tensor type and output optional type doesn't pass shape type inference

### ISSUE THREAD

**Issue by AllenTiTaiWang** [onnx/onnx#4424]
# Bug Report

### Is the issue related to model conversion?
Yes, but the error happens during shape type inference on Loop(Node)
https://github.com/onnx/onnx/blob/eb634addcbb23ec1baf4d548d826bf3932527533/onnx/defs/shape_inference.cc#L343
which we can track back to 
https://github.com/onnx/onnx/blob/eb634addcbb23ec1baf4d548d826bf3932527533/onnx/defs/shape_inference.cc#L414-L425

### Describe the bug
My model has tensor type input and optional type output, and I am not sure if ONNX intends to support only the same input/output type right now. (see repro code)

### System information
- ONNX version (*e.g. 1.7*):  Nightly
- Pytorch: Nightly
- Python version 3.9

### Reproduction instructions
- Describe the code to reproduce the behavior.
```python
import torch
from torch import Tensor
import io
from typing import Optional
import onnx
import onnxruntime as ort

class LoopNoneInput(torch.nn.Module):
    def forward(self, x):
        y: Optional[Tensor] = None
        for _ in range(x.size(0)):
            y = x
        return y

f = io.BytesIO()
x = torch.ones(1)
dynamic_axis_name = "condition"
model_jit = torch.jit.script(LoopNoneInput()).eval()

torch.onnx.export(
    model_jit,
    (x,),
    f,
    opset_version=16,
    # Ensure condition is not constant
    dynamic_axes={"x": {0: dynamic_axis_name}},
    input_names=["x"],
)

model = onnx.load_model_from_string(f.getvalue())
onnx.checker.check_model(model, full_check=True)
```
Model zip file: [OptionalLoop.zip](https://github.com/onnx/onnx/files/9294879/OptionalLoop.zip)

Error [messages:](url)
```bash
Traceback (most recent call last):
  File "/home/titaiwang/PR_test/loopnoneinput.py", line 32, in <module>
    onnx.checker.check_model(model, full_check=True)
  File "/home/titaiwang/onnx/onnx/checker.py", line 108, in check_model
    onnx.shape_inference.infer_shapes(model, check_type=True, strict_mode=True)
  File "/home/titaiwang/onnx/onnx/shape_inference.py", line 34, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode, data_prop)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:Loop, node name: Loop_5): [TypeInferenceError] Output was expected to have tensor type. Got 9
```

**Comment by jcwchen** [comment]
Appendix:
Visualization of OptionalLoop.onnx from Netron:
![image](https://user-images.githubusercontent.com/14194980/184002786-01d7b3fb-5ca7-4855-a10e-ba6151c662db.png)

**Comment by jcwchen** [comment]
After internal discussion, we thought there might be an issue when exporting Loop's subgraph. It seems the Identify node (`Identify_7`) should further connect with Optional to make it as "optional tensor" and then `x.1` should be "optional tensor" as well. @AllenTiTaiWang will try to change the behavior in the exporter and see whether it can meet ONNX's requirement.

**Comment by AllenTiTaiWang** [comment]
Found it's indeed a converter issue, and trace it with https://github.com/pytorch/pytorch/issues/83600
