### ISSUE TITLE
Proposal: Patch Release 1.0.1

### ISSUE THREAD

**Issue by lupesko** [onnx/onnx#444]
# This is a proposal and RFC for a new release for ONNX.

- Release Version: 1.0.1
- Release Type: Patch Release (backwards compatible bug fixes only) 
(following Semantic Versioning as defined in [semver.org](https://semver.org/))
- Release Manager: @lupesko
- Release Checklist:
  - [ ] Create a new branch from v1.0, named v1.0.1
  - [ ] Cherry pick the approved commits
  - [ ] Ensure all tests are successful, work with the community to address any failing tests
  - [ ] Use GitHub Release feature to tag ("v1.0.1") and publish the release
  - [ ] Release Description: "Backwards compatible bug fixes only on top of v1.0" and details of the commits included
  - [ ] Build and upload a new PyPi package ONNX 1.0.1
  - [ ] Build and upload a new Conda package ONNX 1.0.1
- Release Content:
  - Will be managed via GitHub Milestones: we will create a new Milestone: v1.0.1 Release, and tag all issues and PRs for the release with the Milestone
  - Initial proposal of commits:
    - #430 (issue #432) - PyPi install fails when git is not installed

**Please share your feedback and suggestions for the release**
**Note that a patch release is intended to include bug fixes only, and be backward compatible.**

**Comment by lupesko** [comment]
Thanks @bddppq for adding Conda 🙏🏼

**Comment by lupesko** [comment]
1.0.1 patch release draft is out:
https://github.com/onnx/onnx/releases/tag/untagged-e72ba16f78bee7779041

pytest results identical to 1.0 release (2 tests failing)
I will run a few more tests and plan to publish tomorrow Jan 26 1pm PT - unless there's report of issues.

**Comment by lupesko** [comment]
Tested with a clean ubuntu docker container - pip install now works even without git!
(but does require the protobuf dependencies apt-get separately)

**Comment by linkerzhang** [comment]
Looks good to me. :-)

**Comment by bddppq** [comment]
@lupesko Which 2 tests are failing?

**Comment by lupesko** [comment]
@bddppq 
OnnxBackendModelTest.test_densenet121_cpu
OnnxBackendModelTest.test_densenet121_cuda
it can't find the model files.

**Comment by bddppq** [comment]
@lupesko Doesn't look right to me. Where did your test run? All of the onnx CI are able to download and find the densenet model file :-)

**Comment by lupesko** [comment]
@bddppq I simply followed the instructions [here](https://github.com/onnx/onnx#testing).
Is there a step missing? how are test models being pulled?

**Comment by bddppq** [comment]
@lupesko Ok there is cache mechanism (CI wipes out the workspace every time so it doesn't have this concern). I guess you probably failed to download the models previously. Simply delete `~/.onnx/models` in your environment and run the tests again, it should re-download the models.

**Comment by lupesko** [comment]
@bddppq wiping off the cache solved the issue. Shall we add a note about that in the readme? others may have faced the same issue.

**Comment by bddppq** [comment]
@lupesko Makes senses, go for it

**Comment by lupesko** [comment]
Thanks @bddppq for publishing onnx-1.0.1 to the pypi test instance at: https://test.pypi.org/simple/ 
Tested on a clean Ubuntu container and it looks good.
Publishing.

**Comment by lupesko** [comment]
Release published: https://github.com/onnx/onnx/releases/tag/v1.0.1
@bddppq can you please publish the PyPi and Conda and update the issue when done? Thanks!

**Comment by bddppq** [comment]
@lupesko conda one is coming https://github.com/conda-forge/onnx-feedstock/pull/2
