### ISSUE TITLE
Newbie question about types

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [onnx/onnx#4443]
# Ask a Question

### Question
Hi, I'm wondering how the Cast operation works, I came to realize I have a Cast op in my graph(apparently the very first thing after the input), like this,

In [6]: model.graph.node[0]
Out[6]: 
input: "image"
output: "Cast:0"
name: "Cast"
op_type: "Cast"
attribute {
  name: "to"
  i: 1
  type: INT
}

I would like to know what type of integer that type is, I understand there are 4 types for INTs,

https://github.com/onnx/onnx/blob/main/docs/IR.md#tensor-element-types

Also, as I understood these operators are pretty smart, in the sense that if I input to the graph a UINT8 or a FLOAT16, it will make the conversion to INT properly?

thanks in advance!

### Further information
- Relevant Area: Python 3.7 console on my own laptop for learning purposes. 

- Is this issue related to a specific model?: nope

**Comment by jcwchen** [comment]
Hi @albertoandreottiATgmail,
Attribute only supports int64 (You can check the IR [here](https://github.com/onnx/onnx/blob/main/docs/IR.md#attributes) so the integer can be only int64 for Attribute.

> Also, as I understood these operators are pretty smart, in the sense that if I input to the graph a UINT8 or a FLOAT16, it will make the conversion to INT properly?

ONNX is strongly typed and therefore you will further need Cast operator to handle type conversion if the types are different.

**Comment by albertoandreottiATgmail** [comment]
hi @jcwchen , thanks for the answer. So you mean that I will need a different Cast operator for every different input type?
This is confusing because the Cast operator doesn't seem to have the input type specified... so I assumed it may work with whatever you pass.
How to instantiate a Cast operator implementing a specific mapping between type A, and B ?

Thanks!

**Comment by jcwchen** [comment]
https://github.com/onnx/onnx/blob/main/docs/Changelog.md#cast-13 Cast documentation does explicitly mention the implementation detail for mapping. Please let me know if there is any ambiguity. Thanks!

**Comment by albertoandreottiATgmail** [comment]
hi @jcwchen , thanks for the answer, I think there's no ambiguity, and the rules are clear, I was referring to the fact that a definition of cast doesn't involve a specification of the input type.

**Comment by jcwchen** [comment]
Sorry that I think I misunderstood what you meant previously --

> I would like to know what type of integer that type is, I understand there are 4 types for INTs,

I just realized probably you were asking what the "to" attribute value stands for? "1" represents FLOAT (FLOAT32) and you can check the tenorType-integer mapping [here](https://github.com/onnx/onnx/blob/main/onnx/onnx.proto3#L483) or use the following code to verify:
```
from onnx import TensorProto
print(getattr(TensorProto, 'FLOAT'))
# 1
```
That "type: INT" means the "to" attribute is a int64 type for "i". And the value of "i" is 1. So the target type for this Cast should be FLOAT instead.

May I understand why you think Cast needs specified input type? Such a type information can be inferred from the previous node (started from graph.input). Therefore, Cast only needs "to" attribute to let it know which type it should convert to.

BTW, The type restriction for Cast's input is listed [here](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#type-constraints-299).

**Comment by gramalingam** [comment]
Yes. The type of the input "image" is figured out via inference from the place where "image" is computed. If "image" is an input to the graph, then the graph will specify the type of that input. Otherwise, "image" will be the output of another node, and the inference method will compute the type of "image". You can use ONNX's inference method on a model, and the resulting model will have the inferred types of all variables (if you want to look at it).
