### ISSUE TITLE
Checking if input present in InferenceContext

### ISSUE THREAD

**Issue by gramalingam** [onnx/onnx#4447]
ONNX allows for optional inputs. Inference methods of ONNX ops may need to check if an optional input is provided. The class `InferenceContext` does not provide a method to check for this. The method `getNumInputs` provides only a partial answer because ONNX allows for non-trailing optional inputs to be omitted: eg., `foo('x', '', 'y')` is a call where the first and third inputs are provided, but the second input is omitted.

I suggest that we add a new virtual method `hasInput(i)` to this interface with a default-implementation (for backward-compatibility), with the default-implementation defined as:
```cc
   return (getNumInputs() > i && getInputType(i) != nullptr);
```
which is the workaround currently used in various ops.

Eg., see [this example](https://github.com/onnx/onnx/blob/a5e72dc835a2d67b675fcb635f55222dd7078bbc/onnx/defs/math/defs.cc#L2818)

**Comment by gramalingam** [comment]
Other places where it is used:

https://github.com/onnx/onnx/blob/a5e72dc835a2d67b675fcb635f55222dd7078bbc/onnx/defs/math/defs.cc#L3267

https://github.com/onnx/onnx/blob/a5e72dc835a2d67b675fcb635f55222dd7078bbc/onnx/defs/quantization/defs.cc#L49

https://github.com/onnx/onnx/blob/a5e72dc835a2d67b675fcb635f55222dd7078bbc/onnx/defs/tensor/utils.cc#L95

https://github.com/onnx/onnx/blob/a5e72dc835a2d67b675fcb635f55222dd7078bbc/onnx/defs/tensor/utils.cc#L96

and the ongoing PR: https://github.com/onnx/onnx/pull/4389

etc.

**Comment by p-wysocki** [comment]
It's a great idea, the previous method for checking for inputs was inconvenient. I'll apply it to #4389 as well.
