### ISSUE TITLE
onnx didnot support pytorch_geometric.data input

### ISSUE THREAD

**Issue by vanly89** [onnx/onnx#4453]
# Ask a Question

### Question

Hello, experts！
I am currently deploying a graph neural network. I trained a gnn network with pytorch_geometric，the input is torch_geometric.data.Data which encapsulates many types of data. When converting .pt files to .onnx file, onnx.export function did not support torch_geometric.data.Data type input. Is there any good way to support the input of torch_geometric.data.Data type data for onnx export?
Looking forward to your reply！
### Further information
- Relevant Area: 

- Is this issue related to a specific model?  
**Model name**:   
**Model opset**:

**Comment by jcwchen** [comment]
Hi @vanly89,
It should be a question for the [PyTorch-ONNX exporter](https://github.com/pytorch/pytorch/wiki/PyTorch-ONNX-exporter). I would suggest you raise this question in their repo (under PyTorch) and mention ONNX in the title to get the best answer from the exporter experts.

**Comment by jcwchen** [comment]
Close it since it should be a question for the exporter. Feel free to reopen it if you still have other ONNX questions.
