### ISSUE TITLE
Arguments description of gridSample may be opposite with what it should be.  

### ISSUE THREAD

**Issue by Joevaen** [onnx/onnx#4454]
This is not a code debug, but it was true to spend so much time on this.
In [https://github.com/onnx/onnx/blob/main/docs/Operators.md#GridSample](url), I tested the script and calculate mamually. I found maybe the param named _"align_corners"_ is opposite on what 0 and 1 symbolize. I found it is on the contrast of Pytorch's description.
I am not very sure about that, if it was fact, I this it is good to be fixed, if not, please let me whether I lost some information.
ONNX is a brilliant job.
Thanks!

**Comment by liqunfu** [comment]
I looked at export_gridsample_mode_aligncorners. Take 2nd sample point for example, align_corners = 0 is aligned to the corner so its value is less than when align_corners = 1 (0.5 vs 1.25).

It looks right to me.

**Comment by Joevaen** [comment]
Sorry, maybe I mistake something.
Thamk you all the same.
