### ISSUE TITLE
Newbie question regarding the generation of Operators.md file

### ISSUE THREAD

**Issue by analee28** [onnx/onnx#4461]
It would be beneficial if you could give detailed information about creating the Operators.md file. I tried to modify the definitions of operators in the def folder, specifically def/math/defs.cc, and ran the gen_doc.py file but the changes aren't reflected in the newly created .md file.

**Comment by jcwchen** [comment]
Hi @analee28,
As [CONTRIBUTIING.md](https://github.com/onnx/onnx/blob/main/docs/CONTRIBUTING.md#generated-operator-documentation) mentioned, have you specified `ONNX_ML=0` for updating Operators.md? If not, `gen_doc.py` will update Operators-ml.md instead of Operators.md.

**Comment by analee28** [comment]
Hey @jcwchen,
Yes, I’ve specified ONNX_ML=0. The gen_doc.py generates a new file with .md extension but the contents are not updated. Does it have anything to do with the schema from onnx_cpp2py_export.defs file?

**Comment by jcwchen** [comment]
Thanks for the info.

> Does it have anything to do with the schema from onnx_cpp2py_export.defs file?

No. You should see updated Operators.md by `gen_doc.py` if you directly modify defs.cc and build ONNX from source. I would suggest you remove all installed ONNX first, modify defs.cc file, build ONNX from source and then run `ONNX_ML=0 python onnx/defs/gen_doc.py` again and see whether ` Operators.md` is updated.

**Comment by analee28** [comment]
Thank you so much for the suggestion.

**Comment by jcwchen** [comment]
It seems resolved. I will close this one. Feel free to reopen it if you still have questions.
