### ISSUE TITLE
ReLU not implemented latest nightly Mac

### ISSUE THREAD

**Issue by NicolasNierenbergPersyst** [onnx/onnx#4485]
Using the latest nightly for Mac ReLU is not implemented in the InferenceSession

See example below.
```
import torch
from torch import nn
import onnx
import onnxruntime

y = torch.randn(1)
model = nn.ReLU()
torch.onnx.export(model, y, 'test.onnx', export_params=True)
onnx_model = onnx.load('test.onnx')
onnx.checker.check_model(onnx_model)
ort_session = onnxruntime.InferenceSession('test.onnx')
```

NotImplemented                            Traceback (most recent call last)
Input In [28], in <cell line: 6>()
      4 onnx_model = onnx.load('test.onnx')
      5 onnx.checker.check_model(onnx_model)
----> 6 ort_session = onnxruntime.InferenceSession('test.onnx')

File ~/opt/anaconda3/envs/torch-gpu/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:280, in InferenceSession.__init__(self, path_or_bytes, sess_options, providers, provider_options)
    277 self._read_config_from_model = os.environ.get('ORT_LOAD_CONFIG_FROM_MODEL') == '1'
    279 try:
--> 280     self._create_inference_session(providers, provider_options)
    281 except RuntimeError:
    282     if self._enable_fallback:

File ~/opt/anaconda3/envs/torch-gpu/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:312, in InferenceSession._create_inference_session(self, providers, provider_options)
    309     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    311 # initialize the C++ InferenceSession
--> 312 sess.initialize_session(providers, provider_options)
    314 self._sess = sess
    315 self._sess_options = self._sess.session_options

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node /Relu:Relu(14)

**Comment by jcwchen** [comment]
Hi @NicolasNierenbergPersyst,
Thanks for providing the code to repro, but I cannot repro this issue. What's your onnxruntime version? Mine is the latest 1.12.0.

**Comment by NicolasNierenbergPersyst** [comment]
I was using the latest nightly build.

**Comment by jcwchen** [comment]
It should be a question for onnxruntime. Did you get ort-nightly from [here](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/connect/pip)? Some dependencies for onnxruntime are missing for Mac in that package domain so you might need to manually install them before pip install ort-nightly. After installing ort-nightly, please use `pip show onnxruntime` to check the installed onnxruntime version. IIUC, the latest onnxruntime==1.12.0 (even nightly) should not encounter this error.

**Comment by NicolasNierenbergPersyst** [comment]
This is what I get.   When I do an install this is what it says is the latest version for Mac.

Name: onnxruntime
Version: 1.7.2
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /Users/nicolasnierenberg/opt/anaconda3/envs/torch-gpu/lib/python3.8/site-packages
Requires: numpy, protobuf
Required-by:

**Comment by jcwchen** [comment]
That makes sense. If you don't have some Python dependencies for onnxruntime and still try to install ort-nightly, it is possible that it installs an older version of onnxruntime. I would suggest you manually install these Python packages first: https://github.com/microsoft/onnxruntime/blob/main/requirements.txt.in. They are the Python dependencies for the latest onnxruntime. If you have installed all dependencies, you should be able to get the latest prebuilt wheel of ort-nightly.

If it doesn't work, there might be other issue and please raise an issue in onnxruntime repo instead to let the maintainer be aware of this issue.

**Comment by jcwchen** [comment]
Close here because of https://github.com/microsoft/onnxruntime/issues/12869. Please reopen it if you still have other ONNX questions.
