### ISSUE TITLE
Initial tensors(Initializer in Graph) reading by C++ are empty

### ISSUE THREAD

**Issue by SeHuibixiaoxing** [onnx/onnx#4486]
# Ask a Question

### Question

When I use C + + to parse the *.onnx file by compiling the onnx.proto file in the repository, I can't read the initial value though this value can be read in netron.app.

The code showing this problem is provided later. I use graph.initialzier() to read the initial tensors and print their names, types and some values. For example, in the model addition lstm, there is a none empty value W but I can't read it(size() = 0).

```c++
#include <fstream>
#include <cassert>
#include <vector>
#include <cstdio>
#include <iostream>
#include <cstdlib>
#include <cstring>

#include "onnx.pb.h"

std::string onnxPath = "../model/addition-lstm/addition_lstm.onnx";

int main(int argc, char** argv)
{
    std::ifstream readStream(onnxPath, std::ios::ate | std::ios::in | std::ios::binary); // open file and move current position in file to the end
    if (readStream.is_open()) {
        printf("open successfully!\n");
    }
    std::streamsize size = readStream.tellg(); // get current position in file
    readStream.seekg(0, std::ios::beg);
    std::vector<char> buffer(size);
    readStream.read(buffer.data(), size);
    onnx::ModelProto model;
    model.ParseFromArray(buffer.data(), size);

    auto graph = model.graph();
    auto nodes = graph.node();

    std::cout << graph.input().size() << std::endl;

    std::cout << "initializer" << std::endl;
    for (auto init : graph.initializer()) {
        std::cout << init.name()
            << ", type: " << init.data_type()
            << ", INT32_SIZE:" << init.int32_data().size()
            << ", INT64_SIZE:" << init.int64_data().size()
            << ", FLOAT32_SIZE:" << init.float_data().size();

        std::cout << std::endl;
    }

    return 0;
}
```

[![from_netron.app.jpg](https://s1.ax1x.com/2022/09/04/vTmEHU.jpg)](https://imgse.com/i/vTmEHU)

[![my_output.jpg](https://s1.ax1x.com/2022/09/04/vTmZEF.jpg)](https://imgse.com/i/vTmZEF)

The model can be downloaded from [[addition_lstm_onnx](https://drive.google.com/file/d/1skYS4NRNHSJklS50jN5kjCWl3WlrDhiT/view?usp=sharing)](https://drive.google.com/file/d/1skYS4NRNHSJklS50jN5kjCWl3WlrDhiT/view?usp=sharing). In fact,  The same problem occurs in all the models I have tried.

**Comment by jcwchen** [comment]
Hi @SeHuibixiaoxing,
What's your ONNX version of `onnx.pb.h`? Perhaps you can try `ParseProtoFromBytes` to load the ModelProto instead and here is the example: https://github.com/onnx/onnx/blob/main/onnx/common/file_utils.h#L15-L24.

**Comment by jcwchen** [comment]
Thank you for the quick update! Sorry I was wrong -- I took a closer look at the model you provided and this issue seems unrelated to the API: the model's initializer was stored in `raw_data` instead of `int32_data`, `int64_data`, `float_data`. Therefore, you need to further use [ParseData](https://github.com/onnx/onnx/blob/a525f98d5ed31660b629bab90c680a39658a5c08/onnx/defs/tensor_proto_util.cc#L36) to load data from raw_data.

**Comment by SeHuibixiaoxing** [comment]
@jcwchen Thank  you! Your suggestion succeeded in solving my problem. 
Wish you all the best！

**Comment by hygxy** [comment]
> @jcwchen Thank you! Your suggestion succeeded in solving my problem. Wish you all the best！

Hi, would you please share the code snippet for reading initializer values?

**Comment by SeHuibixiaoxing** [comment]
> > @jcwchen Thank you! Your suggestion succeeded in solving my problem. Wish you all the best！
> 
> Hi, would you please share the code snippet for reading initializer values?

Sure. It looks like:
```c++
auto initializer = graph->initializer();
for (auto tmp : initializer)
{
		if (tmp.data_type() == onnx::TensorProto::DataType::TensorProto_DataType_INT32) {
			auto intVec = ParseData<int32_t>(&tmp);
		}
		else if (tmp.data_type() == onnx::TensorProto::DataType::TensorProto_DataType_INT64) {
		
			auto llVec = ParseData<int64_t>(&tmp);
		}
               ... ...
}
```
The function ParseData is the one mentioned above.
