### ISSUE TITLE
DFT for N-Dimensional Input

### ISSUE THREAD

**Issue by gafr** [onnx/onnx#4494]
### Question
The DFT operator does not support N-Dimensional inputs although it is stated in the specs that it is supported

> "For real input, the following shape is expected: [batch_idx][signal_dim1][signal_dim2]...[signal_dimN][1]"

When inputing a matrix with e.g. shape (10,512,512) onnxruntime returns 

`Unsupported input signal shape. The signal's first dimension must be the batch dimension and its second dimension must be the signal length dimension. It may optionally include a 3rd dimension of size 2 for complex inputs`

Is it a problem of the spec or onnxruntime just does not support it (yet) ?

### Further information
**Model opset**: 17
**ONNXRuntime**: built from current master

**Comment by fdwr** [comment]
@smk2007

**Comment by smk2007** [comment]
Hi,

Per the ONNX operator definition: https://github.com/onnx/onnx/blob/main/docs/Operators.md#DFT

input (non-differentiable) : T1
For real input, the following shape is expected: [batch_idx][signal_dim1][signal_dim2]...[signal_dimN][1]. For complex input, the following shape is expected: [batch_idx][signal_dim1][signal_dim2]...[signal_dimN][2]. The first dimension is the batch dimension. The following N dimentions correspond to the signal's dimensions. **The final dimension represents the real and imaginary parts of the value in that order.**

The final dimension must be either 1 or 2, corresponding to real or complex input.
**(10,512,512) should be (10,512,512,1)**

The error message returned from the ORT CPU kernel is misleading as it was originally implemented to handle real inputs without the trailing [1] dim.

**Comment by gafr** [comment]
Thanks @smk2007 

that worked! 

is there a way to mimic the operation over two axis similar to:

` torch.fft.fftn(input, dim=(-3, -2))`

**Comment by smk2007** [comment]
The multidimensional fftn can be accomplished by merely applying each one dimensional fft in sequence.

Here is how FFT2D is performed in our tests:
https://github.com/microsoft/onnxruntime/blob/55c745eefdeea54ff1e527b2634289dde17ddbc5/winml/test/api/LearningModelSessionAPITest.cpp#L546

![image](https://user-images.githubusercontent.com/6754002/189222174-f1c7ac43-91e2-474b-8120-37bf08c1a94a.png)
