### ISSUE TITLE
RuntimeError: all tensors not be on the same device

### ISSUE THREAD

**Issue by sydat2701** [onnx/onnx#4501]
when try to convert yolov5 weight from torch to ONNX, I got this error **_"RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument weight in method wrapper___slow_conv2d_forward)"_** . I have checked and definitely that input tensor and model loaded on the same device (cuda). Someone can help me? Thank you for your help

**Comment by jcwchen** [comment]
Hi @sydat2701,
It seems like a question for the PyTorch-ONNX exporter since this error happened there. Please raise issue in the exporter repo instead (it's ins PyTorch repo) and mention ONNX in the issue title to get the best help from the converter experts.

**Comment by jcwchen** [comment]
It has been tracked in the exporter repo: https://github.com/pytorch/pytorch/issues/84847. I will close this one. Feel free to reopen it if you still have other ONNX questions.
