### ISSUE TITLE
Dummy layer

### ISSUE THREAD

**Issue by magicse** [onnx/onnx#4504]
### Describe the feature

Please add a "dummy" layer like "noop" layer in ncnn. 
This will make easier the convert process from other models to the onnx model. 
Many converters, if they encounter an unsupported layer, fail with an error. If there is will be a "dummy" layer, then all unsupported layers can be converted into a stub layers and then manually edited s needed.

**Comment by justinchuby** [comment]
Closing because there is no movement. It is always possible for one to create a custom op that does this, and instruct the converter to use that operator. I personally don't think we should include this in the spec.
