### ISSUE TITLE
RuntimeError: /github/workspace/onnx/version_converter/adapters/softmax_12_13.h:53: adapt_softmax_12_13: Assertion `target_shape.size() != 0` failed: Version conversion for Softmax failed because input shape is unknown.

### ISSUE THREAD

**Issue by luchangli03** [onnx/onnx#4529]
when I convert onnx model by
onnx_model = version_convert(onnx_model, tgt_opset=15)
this error happens for some model
actually there are input and output shape for this node
I don't know how to solve this problem by modify the model.

**Comment by luchangli03** [comment]
Is there a way to disable conversion of specific type of node?

**Comment by jcwchen** [comment]
Hi @luchangli03,

It's a known limitation: https://github.com/onnx/onnx/issues/4101. However, if the input shape for that Softmax node does present and you still saw this error, there might be a bug. If possible, could you please share the model you have? I will take a deeper look at it.

> Is there a way to disable conversion of specific type of node?

Currently there is no way to do it.

**Comment by luchangli03** [comment]
> Hi @luchangli03,
> 
> It's a known limitation: #4101. However, if the input shape for that Softmax node does present and you still see this error, there might be a bug. If possible, could you please share the model you have? I will take a deeper look at it.
> 
> > Is there a way to disable conversion of specific type of node?
> 
> Currently there is no way to do it. A workaround I can think of would be: if you are comfortable to build ONNX from source, you can modify the source code by adding "Softmax" in this line:
> 
> https://github.com/onnx/onnx/blob/895593af6ac17d4fe2749091659083d3b1246cae/onnx/version_converter/convert.cc#L81
> 
> to skip the version conversion for it.

I'm sorry I can't upload the model since it's too large.

**Comment by jcwchen** [comment]
It should be fixed by https://github.com/onnx/onnx/pull/4974. Please let us if you still bump into issues when converting Softmax-12 to Softmax-13. Thanks!
