### ISSUE TITLE
Add protobuf-3.20.2 version support

### ISSUE THREAD

**Issue by kiflowb777** [onnx/onnx#4545]
### System information

Onnx 1.12.0, Windows 10

### What is the problem that this feature solves?

Version 3.20.1 of module Protobuf, does not include security fixes.
With version  3.20.12, the following has been added:

- Reduce memory consumption of MessageSet parsing

- This release addresses a [Security Advisory for C++ and Python users](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf)

More info: https://github.com/protocolbuffers/protobuf/releases

### Alternatives considered

Missing fixes in protobuf module.

### Describe the feature

Update protobuf up to verison 3.20.2.

### Will this influence the current api (Y/N)?

I suppose that no.

**Comment by jcwchen** [comment]
Hi @kiflowb777,
This issue will be fixed by this PR: https://github.com/onnx/onnx/pull/4535 in the main branch.

**Comment by jcwchen** [comment]
It should be fixed by #4535
