### ISSUE TITLE
printable_graph error and INVALID_GRAPH (ONNXRuntime) when using bf16 datatype

### ISSUE THREAD

**Issue by brevity2021** [onnx/onnx#4549]
# Bug Report

### Is the issue related to model conversion?
No, ONNX checker does not report issues

### Describe the bug
`onnx.helper.printable_graph` throws key error when loading a model with data type bfloat16. But `onnx.checker.check_model` does not give any error. Also ONNXRuntime throws invalid graph error when loading the model.

The errors are as follows (I also include these in the `Reproduction instructions`):
```
File /usr/local/lib/python3.8/dist-packages/onnx/helper.py:817, in printable_attribute(attr, subgraphs)
 814         content.append("<Tensor>")
    815     else:
    816         # special case to print scalars
--> 817         field = STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type]
    818         content.append(f'<Scalar Tensor {str(getattr(attr.t, field))}>')
    819 elif attr.HasField("g"):

KeyError: 16
```

This may result in the INVALID_GRAPH error when using the ONNXRuntime to create an InferenceSession from it.
```
File /usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:384, in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    382 session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    383 if self._model_path:
--> 384     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    385 else:
    386     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./pegasus_cnn/encoder.onnx failed:This is an invalid model. Type Error: Type 'tensor(bfloat16)' of input parameter (onnx::Pow_284) of operator (Pow) in node (Pow_349) is invalid.
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 20.04
- ONNX version (*e.g., 1.7*):  1.12.0 (installed from pip)
- Python version: 3.8.10
- ONNX Runtime version (*e.g. 1.7*):  1.12.0

### Reproduction instructions
```
from onnxruntime import InferenceSession
import onnx
import torch

from transformers import AutoTokenizer,PegasusForConditionalGeneration

model_path = "google/pegasus-cnn_dailymail"
tokenizer = AutoTokenizer.from_pretrained(model_path)
pytorch_model_bf16: PegasusForConditionalGeneration = PegasusForConditionalGeneration.from_pretrained(model_path, torch_dtype=torch.bfloat16).eval()

# Export onnx model
output_path = "./pegasus_cnn/encoder.onnx"
export_text = "This is for test"
input_ids = tokenizer(export_text,truncation=True,return_tensors="pt").input_ids
def export_encoder(model, args, exported_model_path):
    model.eval()
    with torch.no_grad():
        _ = torch.onnx._export(model,
                           args,
                           exported_model_path,
                           export_params=True,
                           opset_version=14,
                           input_names=['input_ids'],
                           output_names=['hidden_states'],
                           dynamic_axes={
                               'input_ids': {0:'batch', 1: 'sequence'},
                               'hidden_states': {0:'batch', 1: 'sequence'},
                           })
export_encoder(pytorch_model_bf16.model.encoder, input_ids, output_path)


encoder_model_graph = onnx.load(output_path)
# No error from check_model
onnx.checker.check_model(encoder_model_graph)
```
```
# printable_graph error
print(onnx.helper.printable_graph(encoder_model_graph.graph))
```

_File /usr/local/lib/python3.8/dist-packages/onnx/helper.py:817, in printable_attribute(attr, subgraphs)
 814         content.append("<Tensor>")
    815     else:
    816         # special case to print scalars
--> 817         field = STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type]
    818         content.append(f'<Scalar Tensor {str(getattr(attr.t, field))}>')
    819 elif attr.HasField("g"):

KeyError: 16_

```
# OnnxRuntime create inference session error
encoder_session = InferenceSession(output_path, providers=["CUDAExecutionProvider"])
```
File /usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:384, in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    382 session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    383 if self._model_path:
--> 384     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    385 else:
    386     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./pegasus_cnn/encoder.onnx failed:This is an invalid model. Type Error: Type 'tensor(bfloat16)' of input parameter (onnx::Pow_284) of operator (Pow) in node (Pow_349) is invalid.

### Expected behavior
bfloat16 should be supported by ONNX's latest version (v1.12)

### Notes
The STORAGE_TENSOR_TYPE_TO_FIELD in [mapping.py](https://github.com/onnx/onnx/blob/f0d607478424ab9a8d3751a6e15d48c817350f8b/onnx/mapping.py#L56) seems missing `TensorProto.BFloat16` key. 

I'm not sure whether the ONNXRuntime error is related to this. It's weird that `onnx.checker.check_model` does not throw any error, but ONNXRuntime says it's an invalid graph.

If I load the model using fp32 datatype, no error appears.

**Comment by jcwchen** [comment]
Hi @brevity2021,
I think it's an error caused by shape inference. If you use onnx.checker with full_check (full check will run onnx.shape_inference) such as `onnx.checker.check_model(encoder_model_graph, True)`, you will see an error: `[ShapeInferenceError] (op_type:Pow, node name: Pow_349): Y typestr: T1, has unsupported type: tensor(bfloat16)`. Current Pow op does not allow using bfloat16 for its input Y. (See [document](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#pow-15)) Thus, I think it should be a question for the exporter that it should not create an ONNX model which has a Pow node using bfloat16 for its input Y.

**Comment by brevity2021** [comment]
Hi @jcwchen ! Thanks for your pointing me to the shape inference problem.
In the document you referred to, Pow op's Y can take `tensor(bfloat16)` since operator set 15. I tried to export the onnx model with `opset_version=15`, and call `onnx.checker.check_model(encoder_model_graph, True)`. This still shows no error. 
`print(onnx.helper.printable_graph(encoder_model_graph.graph))` still shows the same error in `field = STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type]`, which is still inconsistent. 
`encoder_session = InferenceSession(output_path, providers=["CUDAExecutionProvider"])` throws a new error:
```
--> 395 sess.initialize_session(providers, provider_options, disabled_optimizers)
    397 self._sess = sess
    398 self._sess_options = self._sess.session_options

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ReduceMean(13) node with name 'ReduceMean_346'
```
So IMHO this is also a problem which ONNX may have trouble handling the latest additions like bfloat16.

**Comment by jcwchen** [comment]
Thank you for the correction. Yes Pow-15 does support bfloat for input Y.

> But print(onnx.helper.printable_graph(encoder_model_graph.graph)) still shows the same error in field = > STORAGE_TENSOR_TYPE_TO_FIELD[attr.t.data_type], which is still inconsistent.

I agree it's an issue. This PR should solve this by using the right helper function to get the corresponding field name. Feel free to review that PR or give it a try with your model.

> encoder_session = InferenceSession(output_path, providers=["CUDAExecutionProvider"]) throws a new error: NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ReduceMean(13) node with name 'ReduceMean_346'

Although by ONNX spec ReduceMean-13 should support bfloat16, unfortunately based on ORT's document about CUDA kernel, it does not have implemented ReduceMean kernel for bfloat16 yet: https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md#cudaexecutionprovider.
