### ISSUE TITLE
For Reshape with allowZero=1 and a -1 in output dimensions, what is the behavior?

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#4550]
Suppose I have an input matrix with dimensions [0,4] and use the `Reshape` operator (with `allowZero=1`) to reshape it to [0,-1]. What are the expected output dimensions? Or is this a runtime error?

The [specification](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Reshape) of `Reshape` treats the -1 as a placeholder, and "the value is inferred from the size of the tensor and the remaining dimensions". The usual inference approach, dividing (product of input dimensions)/(product of other output dimensions), results in 0/0, i.e. mathematically undefined.

I looked at some implementations for their interpretation.

- CPU implementation treats it as an error. See `ReshapeHelper` line [here](https://github.com/microsoft/onnxruntime/blob/32c2c4b480c3983de216a92b19ce06b9cf75780c/onnxruntime/core/providers/cpu/tensor/reshape_helper.h#L35). 

- dml implementation appears to be broken. See [ReshapeHelper::GetOutputShapes](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/dml/OperatorAuthorHelper/OperatorHelper.cpp#L2177), where it doesn't even attempt to interpret -1 when allowZero=true.

Specification also says "Reshape the input tensor similar to numpy.reshape." and numpy.reshape treats the example as an error, albeit the [numpy description](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) does not directly address the issue.

**Comment by jackwish** [comment]
@onnx/sig-operators Could you please take a look at this? Thanks!

**Comment by gramalingam** [comment]
Good point/question. IMHO, it seems to me it should be treated as a runtime error (or undefined behavior)? Basically the same as divide-by-zero in an integer context.

**Comment by gramalingam** [comment]
Updated the documentation to clarify this (PR 4601)
