### ISSUE TITLE
New added function generates DeprecatedWarning

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#4552]
# Bug Report

### Describe the bug
Function [tensor_dtype_to_field](https://github.com/onnx/onnx/blob/main/onnx/helper.py#L1162) generates a deprecated warning. This was introduced by PR #4270.

### System information
- ONNX version (*e.g. 1.7*):  github

**Comment by jcwchen** [comment]
Thank you so much for catching this early! I have proposed a PR to fix it: https://github.com/onnx/onnx/pull/4551. Please review.

**Comment by jcwchen** [comment]
It should be covered by #4551. Close here now.
