### ISSUE TITLE
[Documentation] Produce formulae in the doc

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4553]
Produce formulae in the doc based on the reference numpy backend implementation.

**Comment by justinchuby** [comment]
cc @@MaanavD

**Comment by jcwchen** [comment]
Hi @justinchuby,
It looks very useful! After https://github.com/onnx/onnx/pull/4483 gets merged, we should try to apply this.

**Comment by gramalingam** [comment]
What's the proposal to do this? Is there a specific proposal? I guess it is a matter of updating the content produced in this PR: https://github.com/onnx/onnx/pull/4561 ?

**Comment by justinchuby** [comment]
I thought I have seen a lib that would convert np to math renderings. But looking again I was wrong. The lib required its own way of writing which doesn't seem compatible with np.
