### ISSUE TITLE
ExtractImagePatches is not supported

### ISSUE THREAD

**Issue by SzaremehrjardiMT** [onnx/onnx#4560]
# Bug Report

I'm using python 3.8.13, tensorflow-gpu 2.3.0, keras2onnx 1.7.0, tf2onnx 1.12.1 and onnx 1.12.0; I want to convert my model (.h5) to onnx format but I get this error:  ExtractImagePatches] is not supported for two layers of my model.

Do I need to set the domain for these costume op? how?

### Expected behavior
I want to convert my model to onnx format correctly and use in c# application.

**Comment by jcwchen** [comment]
Hi @SzaremehrjardiMT,
It seems to me this TF operator theoretically can be converted by the existing ONNX operators according to the discussion here: https://github.com/onnx/tensorflow-onnx/issues/436, but such a support just hasn't been added into tf2onnx yet. Thus it's more like a question for the converter. I would suggest you track this issue there and perhaps raise your question to see whether anyone has a quick workaround for this op conversion.

**Comment by SzaremehrjardiMT** [comment]
Thank you for your response.
I have Involution layers (https://github.com/keras-team/keras-io/blob/master/examples/vision/involution.py) in the model. I think tf2onnx considers it as a customized layer. I couldn't find a good example to create a custom op using [--custom-ops ability. ](https://github.com/onnx/tensorflow-onnx/blob/v1.8.3/README.md#--custom-ops).

Much appreciated!
