### ISSUE TITLE
ImportError: cannot import name 'ModelProto' from 'onnx'

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [onnx/onnx#4567]
# Bug Report

When I run 

```
python -m onnxruntime.quantization.preprocess ...
```

I got

```
ImportError: cannot import name 'ModelProto' from 'onnx' (/home/zuppif/Documents/Work/RoboFlow/roboflow-interactive-segmentation/onnx/__init__.py)
```

### Describe the bug
Above

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Ubuntu 22.04
- ONNX version (*e.g. 1.7*):  onnxruntime version = 1.12.1
- Python version:
- GCC/Compiler version (if compiling from source):
- CMake version: no idea, just installed following the doc
- Protobuf version: the one installed with onnxruntime
- Visual Studio version (if applicable):

If I try to get `onnx` version I got an error

```
Python 3.9.12 (main, Jun  1 2022, 11:38:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnx' has no attribute '__version__'
```

### Reproduction instructions

Above

### Expected behavior
Should work

### Notes
Thanks

**Comment by mmustafaicer** [comment]
How did you resolve this? I am getting same error

**Comment by FrancescoSaverioZuppichini** [comment]
@mmustafaicer sorry I don't remember hahaha, maybe try to update everything in your system

**Comment by zaoshuizaoqishentihao** [comment]
> 

check whether install onnx , pip install onnx.

**Comment by FrancescoSaverioZuppichini** [comment]
damn people got mad, apologies If I cannot remember everything

**Comment by bhavika** [comment]
Installing onnx was necessary! :D
