### ISSUE TITLE
If operator in onnx-exported NMS

### ISSUE THREAD

**Issue by jonas-doevenspeck** [onnx/onnx#4571]
When exporting a detection network including the torchvision nms op ( https://pytorch.org/vision/stable/generated/torchvision.ops.nms.html), the NMS seems to be exported as the following subgraph including an `If` operator. I would like to understand where the `If` operator originates from and how it can be:   
 1) safely removed in the graph  
2) prevented from being exported by modifying the pytorch source code. 

![image](https://user-images.githubusercontent.com/103593150/194024010-b4a99372-1e35-49a9-a2d0-878aacc62cf0.png)

**Comment by justinchuby** [comment]
Based on https://github.com/pytorch/vision/blob/16967f0920a67d264f1a680c389e16cd94ef7e12/torchvision/ops/_register_onnx_ops.py#L14-L30 it seems the if node is no longer created. If the issue persists please open an issue against the https://github.com/pytorch/vision repository. Thanks!
