### ISSUE TITLE
Support complex number manipulation ops

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4574]
Are ops like `conj` https://pytorch.org/docs/stable/generated/torch.conj.html supported? Curious if there are any plans to support them

**Comment by xadupre** [comment]
Operator [DFT](https://github.com/onnx/onnx/blob/main/docs/Operators.md#DFT) was introduced. The output is complex but appears like a tensor with an extra dimension. Shape looks like `(...., 2)`.

**Comment by justinchuby** [comment]
@xadupre  One need when we work with pytorch is that we need to hand the tensors back as complex to pytorch after computation is done in onnx. Therefore the pair of {complex-to-real (aka https://pytorch.org/docs/stable/generated/torch.view_as_real.html), real-to-complex} would be essential for this. With these two ops conj and others can then be implemented as functions in the real number representations w/o the need for any other new onnx ops.
