### ISSUE TITLE
[op] resize calculate error

### ISSUE THREAD

**Issue by chengven027-intellif** [onnx/onnx#4583]
Dear ONNX team:

Recently encountered a special case that caused the `resize` op calculation error.

# Bug Report
My model is:
```
def verify(ishape, oshape, scales, mode, coord_trans="asymmetric", alpha=0.5, exclude=False):
        nodes = [
            make_constant_node("roi", onnx.TensorProto.FLOAT, (0,), []),
            make_constant_node("scales", onnx.TensorProto.FLOAT, (len(scales),), scales),
        ]
        input_names = ["X", "roi", "scales"]

        if oshape != []:
            nodes.append(
                make_constant_node("sizes", onnx.TensorProto.INT64, (len(oshape),), oshape)
            )
            input_names.append("sizes")
        nodes.append(
            helper.make_node(
                "Resize",
                inputs=input_names,
                outputs=["Y"],
                mode=mode,
                coordinate_transformation_mode=coord_trans,
                cubic_coeff_a=alpha,
                exclude_outside=exclude,
                nearest_mode="round_prefer_ceil",
            )
        )

        if oshape == []:
            oshape = [round(dim * scale) for (dim, scale) in zip(ishape, scales)]
        graph = helper.make_graph(
            nodes,
            "resize_test",
            inputs=[helper.make_tensor_value_info("X", TensorProto.FLOAT, ishape)],
            outputs=[helper.make_tensor_value_info("Y", TensorProto.FLOAT, oshape)],
        )

        model = helper.make_model(graph, producer_name="resize_test")

       verify([1, 1, 20], [1, 1, 6], [] , "nearest", "half_pixel")
```
The model has attr with "nearest, half_pixel, round_prefer_ceil ".
Assume randomly generated input
```
[array([[[0.7809397 , 0.91295964, 0.510135  , 0.7067488 , 0.45204508,
         0.74113446, 0.57529855, 0.17431349, 0.59966135, 0.18572877,
         0.2826753 , 0.34644118, 0.8569564 , 0.5671829 , 0.5620156 ,
         0.07336127, 0.83321315, 0.0343755 , 0.86830616, 0.3005494 ]]],
      dtype=float32)]
```
Then I run the model and got a result with:
```
[array([[[0.91295964, 0.74113446, 0.59966135, 0.34644118, 0.5620156 ,
         0.86830616]]], dtype=float32)]
```
But I run other fraework test and  I got a result is:
```
[array([[[0.91295964, 0.74113446, 0.59966135, 0.34644118, 0.07336127,
         0.86830616]]], dtype=float32)]
```
The different with the two result is the fifth value. I think the second is right. 
According the doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize

```
if coordinate_transformation_mode is "half_pixel",
x_original = (x_resized + 0.5) / scale - 0.5

So x_original  = (4 + 0.5) / （6 / 20） - 0.5 =  14.5
nearest_mode="round_prefer_ceil",

So x_original  = round_prefer_ceil(14.5)  = 15   
data(15) = 0.07336127  not onnx result  0.5620156
```

But I run other case:
verify([1, 1, 20], [1, 1, 5], [] , "nearest", "half_pixel")
verify([1, 1, 20], [1, 1, 7], [] , "nearest", "half_pixel")
verify([1, 1, 20], [1, 1, 8], [] , "nearest", "half_pixel")
The result is ok. :)

Certainly,reseize2d also have the same problem
verify([1, 1, 20, 20], [1, 1, 6, 6], [] , "nearest", "half_pixel") the result is error.

@jcwchen Can you have a look if you have free time. Thanks.

**Comment by jcwchen** [comment]
Hi @chengven027-intellif,
For the first result:

>  I run the model and got a result with:

Where did you get this? (From ONNX Runtime inference or an existing ONNX test file?)

**Comment by chengven027-intellif** [comment]
Actually I ran into this problem while inferring an already existing onnx model. The model is `GLADNet`.  And I import it in TVM.  Then I got two result, one is the ONNX runtime and other is TVM result. The two result got different result.

**Comment by jcwchen** [comment]
Thanks for the information. If possible, could you please list the output result of ONNX Runtime, TVM, NumPy?

**Comment by chengven027-intellif** [comment]
op input: 

[array([[[0.7809397 , 0.91295964, 0.510135  , 0.7067488 , 0.45204508,
         0.74113446, 0.57529855, 0.17431349, 0.59966135, 0.18572877,
         0.2826753 , 0.34644118, 0.8569564 , 0.5671829 , 0.5620156 ,
         0.07336127, 0.83321315, 0.0343755 , 0.86830616, 0.3005494 ]]],
      dtype=float32)]


TVM output:  [array([[[0.91295964, 0.74113446, 0.59966135, 0.34644118, 0.07336127,
         0.86830616]]], dtype=float32)]

ONNX runtime output:
[array([[[0.91295964, 0.74113446, 0.59966135, 0.34644118, 0.5620156 ,
         0.86830616]]], dtype=float32)]

**Comment by jcwchen** [comment]
Hi @chengven027-intellif,
Thank you so much for all the details. Your calculation seems correct to me based on ONNX's spec. I don't know why ONNX Runtime produce index 14 instead and get the value 0.5620156.. Perhaps you can raise this issue in ONNX Runtime repo and let runtime experts take a close look.
