### ISSUE TITLE
Operator: Trunc

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4588]
# New Operator

### Describe the operator

PyTorch has the operator trunc which `Returns a new tensor with the truncated integer values of the elements of input.` (https://pytorch.org/docs/stable/generated/torch.trunc.html). The operator can be used to construct the `trunc_divide` or the tf `truncatediv` (https://www.tensorflow.org/api_docs/python/tf/truncatediv). 

Currently torch.onnx exports `trunc_divide` using cast, which is limited by int64's range and can cause numerical errors when the floating point input is large.

For example `Cast(1e38, int64) => -9223372036854775808`

### Can this operator be constructed using existing onnx operators?

Composition of Where, Greater, Floor, Ceil perhaps? As Bowen pointed out.

### Is this operator used by any model currently? Which one?

Not sure

### Are you willing to contribute it? (Y/N)

Y

**Comment by BowenBao** [comment]
> Can this operator be constructed using existing onnx operators?

Composition of `Where`, `Greater`, `Floor`, `Ceil` perhaps?

**Comment by jbachurski** [comment]
@justinchuby I made an example implementation of `trunc` in [Spox](https://github.com/Quantco/spox).

```py
import onnx.printer
import numpy as np
from spox import argument, build, Tensor, Var
import spox.opset.ai.onnx.v17 as op


def trunc(x: Var) -> Var:
    floors = op.floor(op.abs(x))
    zero = op.cast_like(op.constant(value_int=0), x)  # zero of x's type
    is_negative = op.less(x, zero)
    return op.where(is_negative, op.neg(floors), floors)


for x in [-1e38-0.2, -1e15-0.5, -7, -5.8, -3.4, -1, -0.1, 0, 0.1, 1, 6.8, 8, 1e15+0.5, 1e38+0.2]:
    a = np.trunc(x)
    # Spox eager evaluation isn't stable (yet), _get_value() accesses the value
    b = trunc(op.constant(value=np.array(x, np.float64)))._get_value()
    print('+' if a == b else '-', x, a, b)  # Should print '+' everywhere


arg = argument(Tensor(float, ('N',)))
model = build({'x': arg}, {'y': trunc(arg)})

print(onnx.printer.to_text(model))
```

The ONNX output is:
```
<
   ir_version: 8,
   opset_import: ["" : 16],
   producer_name: "spox",
   doc_string: ""
>
spox_graph (double[N] x) => (double[N] y) {
   Constant_0_output = Constant <value_int = 0> ()
   CastLike_0_output = CastLike (Constant_0_output, x)
   Less_0_C = Less (x, CastLike_0_output)
   Abs_0_Y = Abs (x)
   Floor_0_Y = Floor (Abs_0_Y)
   Neg_0_Y = Neg (Floor_0_Y)
   Where_0_output = Where (Less_0_C, Neg_0_Y, Floor_0_Y)
   y = Identity (Where_0_output)
}
```

Legacy versions of ONNX Runtime have the problem of not supporting `Floor` and `Ceil`, but I've fixed this in the current one [here](https://github.com/microsoft/onnxruntime/pull/13906).

I think it would be a good idea to add this operator as a function, as runtimes should be able to provide a more efficient implementation. I'm sure you can come up with different versions of the above, but this one seemed rather straightforward (you don't have to compute a test of whether a value is an integer).

**Comment by justinchuby** [comment]
Thanks for the elegant implementation! @jbachurski

**Comment by justinchuby** [comment]
https://github.com/microsoft/onnx-script/pull/515

**Comment by fdwr** [comment]
Shorter:
```python
# Implementation
def trunc(x: Var) -> Var:
    return op.floor(op.abs(x)) * op.sign(x)
```
