### ISSUE TITLE
onnx/printer.py is not expose and used

### ISSUE THREAD

**Issue by AllenTiTaiWang** [onnx/onnx#4592]
# Bug Report

### Is the issue related to model conversion?

No
### Describe the bug

onnx/printer.py is not expose and used.
### System information

ONNX nightly

### Expected behavior

printer provides readable text of model, and looks like planned to be exposed.

**Comment by jcwchen** [comment]
Hi @AllenTiTaiWang,
onnx.printer was added after ONNX 1.12: https://github.com/onnx/onnx/pull/4246 so you cannot use it in the latest ONNX 1.12 release. You should be able to use it with the latest main branch.

**Comment by AllenTiTaiWang** [comment]
Should we add printer.py into __init__.py?

**Comment by jcwchen** [comment]
> Should we add printer.py into init.py?

I don't have a strong preference -- it probably depends on how popular it is, as you can see in the [init.py](https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L18-L22), not every functions (e.g, version_converter, parser) are added there.
