### ISSUE TITLE
Why is K input to TopK a 1-D tensor instead of a 0-D tensor?

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#4595]
The second input to TopK is specified as:
```
A 1-D tensor containing a single positive value corresponding to the number of top elements to retrieve
```
Why was it designed to take a 1-D tensor with a single positive value instead of taking a 0-D tensor? Is there some future direction or framework where using a 1-D tensor has an advantage?

**Comment by yuanyao-nv** [comment]
For reference, the `depth` input of `OneHot` is specified as a scalar instead of a 1D vector of length 1. Seems like we can make things more consistent for "scalar-like" inputs like these?

cc: original author of dynamic k TopK @hariharans29 https://github.com/onnx/onnx/pull/1829

**Comment by gramalingam** [comment]
Yes, this is somewhat inconsistent. Ideally, we should fix it, if not for backward compatibility concerns.
