### ISSUE TITLE
ShapeInferenceError for op_type:Range

### ISSUE THREAD

**Issue by ashay** [onnx/onnx#4603]
# Bug Report

### Describe the bug

ShapeInference for Range op seems to be buggy / incorrect.  If the output shape is left unspecified, even if all input values are specified, shape inference produces the following error:

```
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Range): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (1) vs (0)
```

### System information
- OS Platform and Distribution: Ubuntu 20.04.5 LTS
- ONNX version: 1.12.0
- Python version: 3.8.10

### Reproduction instructions
```
import onnx
from onnx import helper, TensorProto

if __name__ == "__main__":
    start = helper.make_tensor_value_info("start", TensorProto.INT32, [])
    limit = helper.make_tensor_value_info("limit", TensorProto.INT32, [])
    delta = helper.make_tensor_value_info("delta", TensorProto.INT32, [])

    start_value = helper.make_tensor("start", TensorProto.INT32, [], (1,))
    limit_value = helper.make_tensor("limit", TensorProto.INT32, [], (10,))
    delta_value = helper.make_tensor("delta", TensorProto.INT32, [], (2,))

    output = helper.make_tensor_value_info("output", TensorProto.INT32, [])

    node = helper.make_node(
            "Range",
            [start.name, limit.name, delta.name],
            [output.name],
    )

    graph_def = helper.make_graph(
            [node],
            "test-model",
            [start, limit, delta],
            [output],
            initializer=[start_value, limit_value, delta_value],
            value_info=[]
    )

    model_def = helper.make_model(graph_def, producer_name="onnx-example")
    onnx.checker.check_model(model_def)
    onnx.shape_inference.infer_shapes(model_def)
```

### Expected behavior

No errors and that the model output has shape `[5]`.

**Comment by jcwchen** [comment]
Hi @ashay,
ONNX IR requires main graph to define its input's and output's types and **shapes**. See https://github.com/onnx/onnx/blob/main/docs/IR.md#graphs. If the model does not specify the shape for its output, it will be considered as an empty shape, which is not align with the inferred shape 5 here. If you specify output shape in the model like:
```
output = helper.make_tensor_value_info("output", TensorProto.INT32, [5])
```
The shape inference will complete successfully.
