### ISSUE TITLE
Perform Integer operation in inference mode

### ISSUE THREAD

**Issue by mdatres** [onnx/onnx#4608]
Dear all, 

I have an onnx model with fake quantised parameters (which means that they are mathematically integers but with dtype float32 - see attachment) and I want to cast them to int type in order to accelerate the inference phase. I have tried to do this brutally, but I think that Conv operator does not support integer inputs. Is it correct? 
Do you know how can I do?

![Screenshot 2022-10-19 at 10 08 40](https://user-images.githubusercontent.com/80750571/196634453-d5ef378d-7641-4978-856d-643735423605.png)

Thanks in advance, 

Max

**Comment by jcwchen** [comment]
Hi @mdatres,
Good question. I am not a quantization expert, but I will try to answer this from my understanding -- There might have two possible approaches to make Conv in ONNX run integer:
- QLinearConv
- ConInteger + QuantizeLinear

You should be able to use either of them based on your use case. The trade-off were discussed in https://github.com/onnx/onnx/issues/2424.
