### ISSUE TITLE
Code changes for additional model converstion adapter support.

### ISSUE THREAD

**Issue by TedThemistokleous** [onnx/onnx#4616]
# Ask a Question

### Question

Adding adapters and relevant components to support conversion between opsets for varying models. Currently debugging models that  the MIGraphX project needs to support and realized some models need to be converted to support our current opset. 

Created a script using some of the tools found in this repo here to do this:
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1413

I've taken a look at the version_converter code in the repo but it seems like I may be missing some additional piece to add support between ops that need conversion.

### Further information
- Relevant Area:  Model conversion between opsets and adding adapters

- Is this issue related to a specific model?  
**Model name**:   resnext50 
**Model opset**:  13

Model in question can be found here:  https://zenodo.org/record/6617879/files/resnext50_32x4d_fpn.onnx
### Notes

Currently opened up a draft PR (#4615) with some changes I've done and tried locally to no avail

Getting the following output error still when trying to convert the model with this script and onnx newly build and installed with my local changes.

```
SyntaxError: invalid syntax
root@6b4c5c2b5d5e:/code# python3 AMDMIGraphX/tools/convert_onnx_version.py --model AMDMIGraphX/resnext50_32x4d_fpn.onnx --opset=12 --output AMDMIGraphX/resnext50_32x4d_fpn_opset12.onnx 
Traceback (most recent call last):
  File "AMDMIGraphX/tools/convert_onnx_version.py", line 82, in <module>
    main()
  File "AMDMIGraphX/tools/convert_onnx_version.py", line 71, in main
    converted_model = version_converter.convert_version(
  File "/usr/local/lib/python3.8/dist-packages/onnx/version_converter.py", line 166, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:63: adapter_lookup: Assertion `false` failed: No Adapter To Version $12 for Sub
root@6b4c5c2b5d5e:/code# 
```

**Comment by jcwchen** [comment]
Hi @TedThemistokleous,
Thanks for catching this. Currently onnx's version_converter more focuses on upgrade so a lot of downgrade might be missing, as you can see. The only different between Sub-7 and Sub-13 is Sub-13 further allows bfloat16 (check the difference by https://onnx.ai/onnx/onnx_doc_folder/text_diff_Sub_7_13.html#l-onnx-op-sub-d7-13). So probably directly using CompatibleAdapter is fine, but please note that it won't work if the original opset-13 model use bfloat16 as Sub's input, because old opset version (Sub-7) does not support bfloat16.

**Comment by TedThemistokleous** [comment]
ah i see I see. I think i'll avoid doing this then as I had an newer model I wanted to pull back using the conversion. Might just handle this on the operator side. 

Thanks for your time @jcwchen !
