### ISSUE TITLE
question of geterfgrad op 

### ISSUE THREAD

**Issue by rGitcy** [onnx/onnx#4626]
# Ask a Question

### Question

Hi,
look at the picture!
![image](https://user-images.githubusercontent.com/8943172/198234638-3cbd95fb-a729-4bef-bbba-ac232a7f70d5.png)

the last 'mul' of erfgrad op is not match the derivative formula  of erf
![image](https://user-images.githubusercontent.com/8943172/198235689-1b8fe48d-3edf-4a8b-8bcc-49e1ec451aba.png)
could you give me a help?thx！
### Further information
- Relevant Area: 

- Is this issue related to a specific model?  
**Model name**:   
**Model opset**:

**Comment by jcwchen** [comment]
Hi @rGitcy,
IIUC, ONNX doesn't have such an operator yet. It should be an operator in orttraining. I saw you have raised this issue there as well, which is a better place to track this. I will close here now. Feel free to reopen it if you still have other ONNX related questions. Thanks!
