### ISSUE TITLE
GPU RAM memory leak when infering with ONNX model converted from Tensorflow

### ISSUE THREAD

**Issue by igormis** [onnx/onnx#4627]
### Describe the bug
The GPU RAM memory gets exhausted after multiple inferences

### System information
- Ubuntu 20.04,  NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4
- ONNX version:  onnxruntime-gpu==1.11.1 
- Python version: 3.9
- Tensorflow: 2.8.2

### Reproduction instructions

```
sess_options = rt.SessionOptions()
sess_options.enable_mem_pattern = False
sess_options.enable_cpu_mem_arena = False
cuda_provider_options = {"arena_extend_strategy": "kSameAsRequested"}
execution_providers = [("CUDAExecutionProvider", cuda_provider_options), "CPUExecutionProvider"]
sess = rt.InferenceSession("roberta_onnx_model/__MODEL_PROTO.onnx",sess_options, providers=execution_providers)
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
logits = sess.run([label_name], {input_name: X_test_sample})[0]
...
```

### Expected behavior
Have a constant GPU memory footpring

**Comment by jcwchen** [comment]
Hi @igormis,
It's more like a question for ONNX Runtime. I saw you have opened this issue there as well. Please track this issue there. I will close it and feel free to reopen it if you still have other ONNX questions. Thanks!

**Comment by igormis** [comment]
OK, tnx
