### ISSUE TITLE
AlmostEqual or Extend Equal Operator

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#463]
Looks like most framework support Equal on floating tensors...
ONNX may support this with different op (AlmostEqual) or by adding an optional attribute.

I personally prefer the latter.

**Comment by tianleiwu** [comment]
If we need another operator like numpy.isclose, I think it is better to be a different op.

**Comment by askhade** [comment]
@houseroad : Is this still required?

**Comment by askhade** [comment]
Closing this issue since it is too old. Please reopen if the requirement comes up.
