### ISSUE TITLE
Installation Error - Python 3.11

### ISSUE THREAD

**Issue by swageeth** [onnx/onnx#4639]
# Ask a Question

### Question
I'm facing issue when installing Onnx in Windows. I'm using Python 3.11 and have upgraded to the latest version of pip. Below is the error I get:

Collecting onnx
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pushewsa\AppData\Local\Temp\pip-install-gssknuf5\onnx_4ffeffe9075840efafff372063afc9bd\setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Any help is appreciated. Thank you

**Comment by jcwchen** [comment]
Similar to https://github.com/onnx/onnx/issues/4631. Currently ONNX doesn't have prebuilt wheel for Python 3.11 so actually you were building ONNX from source and cmake is required.

**Comment by swageeth** [comment]
> Similar to #4631. Currently ONNX doesn't have prebuilt wheel for Python 3.11 so actually you were building ONNX from source and cmake is required.

I already have installed cmake though. I still get the same error:
![image](https://user-images.githubusercontent.com/13758508/200439355-ff42ca63-33b7-441d-8608-a6ca21ea0c88.png)

**Comment by jcwchen** [comment]
May I understand what's your output of command `which cmake`?

**Comment by swageeth** [comment]
> May I understand what's your output of command `which cmake`?

Did you mean to extract the version of cmake?
![image](https://user-images.githubusercontent.com/13758508/200442222-2703d963-b3c9-442f-8521-7337143954b7.png)

**Comment by swageeth** [comment]
it is using 3.24.3 version ( I think this is the latest available too)
![image](https://user-images.githubusercontent.com/13758508/200446698-362f7959-2ee9-43bb-8177-fe717dc49b42.png)

**Comment by jcwchen** [comment]
Thanks for the information. I cannot repro this so it's quite hard for me to debug. Could you please also make sure your `wheel` and `setuptools` are the latest ones? Also, are you using the official Python 3.11.0?

**Comment by swageeth** [comment]
Thank you for looking into this - Wheel is version 0.38.2, setuptools is 65.5.1 (which are both the latest versions). Downloaded Python 3.11.0 from Python.org

**Comment by jcwchen** [comment]
Since the latest main branch seems worked well with Python 3.11 (https://github.com/onnx/onnx/pull/4490), could you please try this latest ONNX weekly package? (use `pip install -i https://test.pypi.org/simple/ onnx-weekly` to install)

**Comment by swageeth** [comment]
> pip install -i https://test.pypi.org/simple/ onnx-weekly



> Since the latest main branch seems worked well with Python 3.11 (#4490), could you please try this latest ONNX weekly package? (use `pip install -i https://test.pypi.org/simple/ onnx-weekly` to install)

Still no luck: it's showing an error with setuptools 40.8.0 when I already have setuptools 65.5.1
![image](https://user-images.githubusercontent.com/13758508/200681208-3282cf25-fc3c-4ffa-b07e-7ce0f8371163.png)

**Comment by swageeth** [comment]
Then there is an issue relating to certificates. Any ETA on when the whl will be released? 
![image](https://user-images.githubusercontent.com/13758508/200928296-fe2988b6-32e5-4f88-8b46-4cf5a6d592e9.png)

**Comment by jcwchen** [comment]
I am adding Python 1.13 support now and the target release date of ONNX 1.13 will be around mid Dec. ([reference](https://github.com/onnx/onnx/pull/4599/files))

**Comment by jcwchen** [comment]
Fresh ONNX 1.13 has been just released with Python 3.11 support: https://pypi.org/project/onnx/1.13.0/#files. I will close this issue now. Please let me know if you see any issues. Thanks!
