### ISSUE TITLE
change onnx:reshape

### ISSUE THREAD

**Issue by RoachNier** [onnx/onnx#4645]
### Question
Hi, I am deploying onnx on android with unity barracuda. The model I used is yolov5. I found a slowly inference speed on mobile. After timing analysis, I found one op called onnx::reshape in yolov5 detect header part need to transfer data from gpu to cpu before executed.  As is known, yolov5 has three branches in detect header part, but only one onnx::reshape is time-cost, Can I change its format to be like another two? The onnx graph is shown in information. The opset_version is 12. Thanks!

### Further information
![image](https://user-images.githubusercontent.com/52225258/200991793-27e490d1-97bf-45ac-ae18-5d9ba079a6ac.png)

- Is this issue related to a specific model?  
**Model name**:yolov5

**Comment by daquexian** [comment]
> After timing analysis, I found one op called onnx::reshape in yolov5 detect header part need to transfer data from gpu to cpu before executed.

To me the three reshape ops don't have any difference, and the inference speed is highly related to the implementation details of the inference framework you are using,  so I'm afraid it doesn't help even if you edit the "slow" reshape op.

BTW, you can try [onnxsim](https://github.com/daquexian/onnx-simplifier) which can remove some redundant ops in your model (like the two identities ops in the screenshot) and make your model slightly faster as a result.
