### ISSUE TITLE
Reference implementation to switch between opset_imports 

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#4653]
### System information

System independent

### What is the problem that this feature solves?

Shall be able to run a model with specified opset_import that are different from the current opset version

### Alternatives considered

None

### Describe the feature

Reference implementation is a great new feature. However, op's version is determined by build-time onnx_opset_version. There should be a way to execute a op with a requested opset version. The opset version usually comes from a models's opset_import which is not necessarily the current opset version of the ONNX repository.

### Will this influence the current api (Y/N)?

No

### Feature Area

backend, opsertors, test

**Comment by xadupre** [comment]
The reference implementation can switch between opset imports. The mechanism in place implies that every new implementation is imported file `_op_list.py`. Class `ReferenceEvaluator` looks into the imported objects to define a list of all available implementations.

**Comment by xadupre** [comment]
I'll close the issue, feel free to reopen it.
