### ISSUE TITLE
[ScatterElements] Why does `indices` and `updates` need to have the same rank and shape in spec?

### ISSUE THREAD

**Issue by titaiwangms** [onnx/onnx#4672]
# Ask a Question

Why does `indices` and `updates` need to have the same rank and shape in spec? According to https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ScatterElements-16

### Question
In [PyTorch scatter_add](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html#torch.Tensor.scatter_add_). The index and src which I believe are equivalent to indices and updates in ONNX, are not required to have same shape (only same rank).

### Further information
Even if I changed the code in converter to let this happen:
https://github.com/pytorch/pytorch/blob/29742786f38d4873576c73917e8509908132dae2/torch/onnx/symbolic_opset16.py#L78-L82

It wouldn't be able to run on ONNXRUNTIME. I suspect it's because of the spec in here

### Notes
A simple repro code on PyTorch is not runnable even if converter successfully exporting it with the change I mentioned above.
```python
src = torch.ones((2, 5))
index = torch.tensor([[0, 1, 2, 0, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)
index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)
```

**Comment by titaiwangms** [comment]
[model.zip](https://github.com/onnx/onnx/files/10106600/model.zip)

Like the above model passing onnx checker, allowing dynamic axes on `indices` and `src`, but it actually doesn't (not runnable on runtime) and it still expects `index` and `scr` should have the same rank and shape. I think it's because we had runtime code first, and then this spec. This discrepancy with [PyTorch](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html#torch.Tensor.scatter_add_) potentially makes runnable PyTorch model be unexecutable on ONNX.

**Comment by gramalingam** [comment]
Based on a quick look, my understanding is that in the ONNX spec `updates` represents the actual values, while `indices` represents the index at which the update should be applied. So, it seems to make sense that there is a one-to-one correspondence between them. Every update, conceptually, consists of an index and a value.

As for the pytorch usage: I wonder if it is just a matter of emitting a `Gather` (of the right kind) to extract the value at the index (from the "source") and then using this as the "updates" input for Scatter?

**Comment by titaiwangms** [comment]
Although using Gather or Slice can handle with static shape cases, it won't solve the dynamic shape cases. If a user tries to imply ONNX that indices and updates have different dynamic shape with different axe names, it will fail in terms of the expectation from ONNX specification (runtime). I have commented on the pytorch symbolic_fn for this restriction: https://github.com/pytorch/pytorch/blob/f628f2ed73df2c28ab369ecad1f87f6dcf67b0e0/torch/onnx/symbolic_opset16.py#L85-L98

**Comment by gramalingam** [comment]
If we consider the update formula (given in ONNX as well as PyTorch), the same indices are used into `indices` and `updates`. So, both are expected to be of same shape when we apply the update. It is possible that PyTorch does a "broadcast" between `indices` and `updates` ... is that what happens? Is it a one-directional broadcast? 

If that is the case, the exporter could emit an `Expand` of `indices` to the shape of `updates`, before doing the Scatter. Does that sound right? Thanks!

**Comment by titaiwangms** [comment]
Let's say we have 
updates: [3, 5]
indices shape: [2, 5]

What PyTorch does is to ignore the extra row in updates, which is why I applied onnx:: Slice there. But the issues rise when there is the case of dynamic:
updates: [*, 5]
indices shape: [*, 5]

And in this case, IIUC adding onnx::Slice is not useful, and ONNX would expect they have the same shape.

**Comment by gramalingam** [comment]
Ok, thanks for clarifying. The PyTorch documentation doesn't clarify this behavior, and it seems a bit artificial/unnatural. The slicing can be done even in the dynamic case, I assume, though it will be somewhat cumbersome: take the two shapes, compute the Min, and then slice to this shape. It could be an interesting exercise in onnxscript.

**Comment by titaiwangms** [comment]
Thanks, I will try with Min
