### ISSUE TITLE
Any difference between a constant input of an operator being `category: Initializer` and `category: Constant`?

### ISSUE THREAD

**Issue by fengyuentau** [onnx/onnx#4677]
# Ask a Question

### Question

I found for a constant input of an operator, its category can be either `Initializer` or `Constant`. Is there any difference between them? Are there other categories?

### Further information
- Relevant Area:  IR

- Is this issue related to a specific model?  
**Model name**:   NA
**Model opset**:  NA

**Comment by gramalingam** [comment]
There is not much difference between them. However, if an initializer X also appears in the graph's input list, X is NOT treated as a constant, since the caller can provide a different value that overrides the specified value.

**Comment by fengyuentau** [comment]
Thank you for your time and answers. I still have the following two questions though:

> if an initializer X also appears in the graph's input list

Is it possible that an initializer X is not in the graph's input list? I've seen many operators with initializers and they are all in the input list of graphs.

> since the caller can provide a different value that overrides the specified value

It sounds like a feature for training. During training, something like conv weight needs to have initial values to get started with training. However, all of the ONNX graphs I've seen so far is for inference. I guess for inference-only ONNX graphs `Constant` is recommended over `Initializer` to keep constants so as to fold constants in inference framework like ONNXRUNTIME?

**Comment by gramalingam** [comment]
Yes, you are right about the original intention. In IR version 4, which is already few years old, a change was made to allow initializers that are not in the graph's input list. Such initializers are correctly handled as constants by onnxruntime.

If you are seeing models with initializers included in the input list, they probably reflect the older usage (it is possible that some exporters still do this). What's the source of these models? You are right, that if initializers are included in the input list, that could hinder constant-folding in a backend. It is better to either use constants or use initializers that are not in the input list.

**Comment by fengyuentau** [comment]
Thank you again for the detailed explanation. I am one of the main developers of the OpenCV DNN module, where we have an importer for ONNX models. So I mainly have models from users and they export ONNX models from different frameworks (most likely PyTorch and Paddle) using old and new conversion tools.

I would like to ask one more question before closing this issue: Is there any open documentation for this kind of information? For example documentation of IR of different versions where I may find this kind of documentation myself?

**Comment by gramalingam** [comment]
The main documentation is https://github.com/onnx/onnx/blob/main/docs/IR.md.

**Comment by fengyuentau** [comment]
Appreciated for your help!
