### ISSUE TITLE
Getting the Input values from an Intermediate Node in ONNX Model

### ISSUE THREAD

**Issue by laumecha** [onnx/onnx#4680]
Hello everyone. After performing the inference, I am trying to get the input tensor values of the intermediate convolution nodes of an ONNX model. However, I can only find the name of these layers but not the values themselves. I have seen in #3277 that one approach is to add middle layers to outputs.

However, when I run "onnx.shape_inference.infer_shapes(onnx_model)" I can see some inputs with different names. For example, if I look into the ONNX graph on the Netron web page, I can see an input of one layer named "resnetv17_stage2_relu5_fwd_quantized"  but in the "onnx.shape_inference.infer_shapes(onnx_model)" I can't see this one. Only a similar input "resnetv17_stage2_relu5_fwd". So, if I put "resnetv17_stage2_relu5_fwd" as an intermediate layer and create a new model, this new output will not be associated with any layer.

My code to add middle layers:
```

def modify_model_2():
    nodes = onnx_model.graph.node
    in_node = []

    for n in nodes:
        if "conv" in n.name:
            print(n.input[0])
            in_node.append(n.input[0])

    value_info_protos = []
    shape_info = onnx.shape_inference.infer_shapes(onnx_model)
    for idx, node in enumerate(shape_info.graph.value_info):
        if node.name in in_node:
            print(idx, node.name)
            value_info_protos.append(node)
        else:
            print("NO: ", node.name)

    onnx_model.graph.output.extend(value_info_protos)  #  in inference stage, these tensor will be added to output dict.
    onnx.checker.check_model(onnx_model)
    onnx.save(onnx_model, './test.onnx')
    exit()
```
An example of how this looks:
![imagen](https://user-images.githubusercontent.com/46852755/204322837-3dd33a8e-480e-449e-89d9-08354274e2b2.png)
If I try to perform the inference of the model of the image I see this error:
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /home/conda/feedstock_root/build_artifacts/onnxruntime_1667467875849/work/onnxruntime/core/graph/graph.cc:1348 void onnxruntime::Graph::InitializeStateFromModelFileGraphProto() This is an invalid model. Graph output (resnetv17_pool0_fwd) does not exist in the graph.
`

The code that generated this model:

```
def modify_model_test():    
    value_info_protos = []
    shape_info = onnx.shape_inference.infer_shapes(onnx_model)
    for idx, node in enumerate(shape_info.graph.value_info):
        if "conv" in node.name:
            print(idx, node)
            value_info_protos.append(node)
    onnx_model.graph.output.extend(value_info_protos)  #  in inference stage, these tensor will be added to output dict.
    onnx.checker.check_model(onnx_model)
    onnx.save(onnx_model, './test.onnx')
    exit()
```

 I was wondering if there is any solution for this or a way to know the input tensor values without creating a new model.

**Comment by gramalingam** [comment]
I don't see anything wrong with the code producing the modified model (unless the input model is erroneous). This is a bit mysterious. Does the onnx.checker.check_model pass on the modified model? If it does, and onnxruntime fails, it might be worth creating an issue in onnxruntime repo.

The error message refers to `resnetv17_pool0_fwd` which does not have the string `conv`. So, this is also strange, because it can't be something modified/added by the above code, right?

**Comment by laumecha** [comment]
Thank you for your answer. You are rigth. The error correspond to other really similar code. Sorry about that. 

However, with the code that I posted I have the same error with other node:

`INVALID_ARGUMENT : Failed to load model with error: /home/conda/feedstock_root/build_artifacts/onnxruntime_1667467875849/work/onnxruntime/core/graph/graph.cc:1348 void onnxruntime::Graph::InitializeStateFromModelFileGraphProto() This is an invalid model. Graph output (resnetv17_conv0_fwd) does not exist in the graph.`

The model does pass the check_model so I will create an issue on onnxruntime repo, thanks for the advice!

**Comment by laumecha** [comment]
Sorry again. I should have mentioned that I am using a zoo-quantized ONNX model. For the non-quantized version, the generated ONNX model loads perfectly. This means that the` onnx.shape_inference.infer_shapes(onnx_model)` returns valid nodes for the floating point model. However, this function does not return the correct ones for the quantized model. So, I think this is not a problem of the onnxruntime.

**Comment by gramalingam** [comment]
Is it the (a) quantized model or (b) quantized model edited as described above that is causing the problem? I assume that (a) passes the inference correctly, but (b) fails? Is that right?

It would help if you attach the failing model.

**Comment by laumecha** [comment]
Exactly. When I evaluate the quantized model ( which can be found [here](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-12-int8.tar.gz)) everything works fine. When I try to evaluate or perform the inference of the new generated model with the new outputs, I get the error mentioned.

**Comment by laumecha** [comment]
I was able to get the intermadiate values using onnx runtime.  My code:

```
    nodes = onnx_model.graph.node
    in_node_name = []
    for n in nodes:
        if "conv" in n.name:
            in_node_name.append(n.input[0])
    
    input_conv = []
    #search the input tensor
    for out in enumerate_model_node_outputs(onnx_model):
        if out in in_node_name:
            input_conv.append(out)

    # Create a new model
    num_onnx = select_model_inputs_outputs(onnx_model, input_conv)
    save_onnx_model(num_onnx, <new_dir>)

```
