### ISSUE TITLE
onnx.compose.add_prefix_graph won't rename subgraph

### ISSUE THREAD

**Issue by Yosshi999** [onnx/onnx#4687]
# Bug Report

### Describe the bug
onnx.compose.add_prefix_graph won't rename subgraph, such as If branch. (also Loop block?)
This means it may break the onnx graph which contains If / Loop nodes.

### System information
Google Colab CPU

### Reproduction instructions
https://gist.github.com/Yosshi999/e6fda24ddc0e26687a2540c5db32d658

### Expected behavior

onnx.checker.check_graph passes.

### Notes
This function has to call the renaming routine recursively when it meets If / Loop nodes.

**Comment by jcwchen** [comment]
Hi @Yosshi999,
Thanks for catching this issue. I can repro it. I have submitted a PR to fix it: https://github.com/onnx/onnx/pull/4718. Feel free to review. Thanks!
