### ISSUE TITLE
ExtractImagePatches is not supported

### ISSUE THREAD

**Issue by kothari1997narayan** [onnx/onnx#4689]
I am trying to convert raft tensorflow model(https://github.com/google-research/opticalflow-autoflow) to onnx model.
And while converting I am facing an error shown below

**ERROR** - Tensorflow op [raft_1/while/ExtractImagePatches: ExtractImagePatches] is not supported
**ERROR** - Unsupported ops: Counter({'ExtractImagePatches': 1})

The command used to convert the model is
python3 -m tf2onnx.convert --saved-model raft_it_ft --inputs input_1:0[1,2,224,224,3] --signature_def 'serving_default' --output model_raft.onnx --opset 17

Any solutions to it?
Thanks

**Comment by jcwchen** [comment]
Hi @kothari1997narayan,
I think unsupportedExtractImagePatches is a known limitation in tensorflow-onnx: https://github.com/onnx/tensorflow-onnx/issues/436. It seems that currently there isn't an official way to convert it. Please track this issue there. Thanks!

**Comment by justinchuby** [comment]
As @jcwchen suggested, this is tracked by https://github.com/onnx/tensorflow-onnx/issues/436
