### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'numpy_helper'

### ISSUE THREAD

**Issue by Littlehong-ai** [onnx/onnx#4690]
# Bug Report

**Comment by jcwchen** [comment]
Hi @Littlehong-ai,
Similar to https://github.com/onnx/onnx/issues/4592#issuecomment-1277700240? Actually ONNX does not expose every utility function: https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L18-L22. Still, you can use numpy_helper by `from onnx import numpy_helper`.
