### ISSUE TITLE
Definition of ONNX DFT question/bug?

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx#4699]
# Bug Report

### Describe the bug

In the description of DFT: https://onnx.ai/onnx/operators/onnx__DFT.html

Axis is defined as below (bold in my emphasis)

* axis: The axis on which to perform the DFT. By default this value is **set to 1**, which corresponds to the **first dimension after the batch index**.

Then the output is described like this:

*  If **axis=1** and onesided is 1, the following shape is expected: [batch_idx][signal_dim1][**floor(signal_dim2/2)+1**]…[signal_dimN][2].

Is that correct? I don't know the operation well, so intuitively I would have expected that the "axis" op is the one that get the `/2+1` modification, but maybe that is not the case. 

Thanks

**Comment by justinchuby** [comment]
I think this is fixed
