### ISSUE TITLE
[Feature request] ONNX checker checks function proto validity 

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4700]
### What is the problem that this feature solves?

ONNX checker currently checks model proto validity with check_model_proto. I would be very helpful to have a similar API that checks for function proto validity.

This greatly helps testing function libraries built with ONNX script.

### Alternatives considered

Make a model. Not all functions can be directly converted into a Model. 

### Feature Area

checker

### Are you willing to contribute it (Y/N)

None

**Comment by jcwchen** [comment]
Hi @justinchuby,
Thanks for proposing this. Currently ONNX only provides [check_function](https://github.com/onnx/onnx/blob/main/onnx/checker.cc#L867-L956) in C++. Does the current check meet your requirement? If it is useful, we can also expose a Python API for it.

**Comment by justinchuby** [comment]
A Python api would be great/necessary for unit testing the function library.
