### ISSUE TITLE
Install ONNX on ubuntu failed

### ISSUE THREAD

**Issue by MicroYu-jt** [onnx/onnx#4704]
# Install issue

### Question

Hi, I am building ONNX1.10.0 from the source . When I run command 'pip install -e .' I get the following error:
~~~
root@ubuntu:/home/yjt/onnx-1.10.0# pip install -e .
Obtaining file:///home/yjt/onnx-1.10.0
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (4.1.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.10.0) (1.11.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (1.19.5)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (3.19.6)
Installing collected packages: onnx
  Running setup.py develop for onnx
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/yjt/onnx-1.10.0/setup.py'"'"'; __file__='"'"'/home/yjt/onnx-1.10.0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/yjt/onnx-1.10.0/
    Complete output (107 lines):
    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    running develop
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-36m-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/home/yjt/onnx-1.10.0']
    CMake Warning at /home/yjt/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/FindProtobuf.cmake:524 (message):
      Protobuf compiler version 21.10 doesn't match library version 3.21.10
    Call Stack (most recent call first):
      CMakeLists.txt:175 (find_package)
    
    
    Generated: /home/yjt/onnx-1.10.0/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /home/yjt/onnx-1.10.0/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /home/yjt/onnx-1.10.0/.setuptools-cmake-build/onnx/onnx-data.proto
    -- Found pybind11: /usr/local/include (found version "2.11.0dev1")
    --
    -- ******** Summary ********
    --   CMake version             : 3.25.1
    --   CMake command             : /home/yjt/cmake-3.25.1-linux-x86_64/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 7.5.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       :
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.10.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/local/bin/protoc
    --   Protobuf includes         : /usr/local/include
    --   Protobuf libraries        : /usr/local/lib/libprotobuf.a
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3
    --     Python includes       : /usr/include/python3.6m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/yjt/onnx-1.10.0/.setuptools-cmake-build
    [  2%] Built target gen_onnx_proto
    [  5%] Built target onnxifi_loader
    [  8%] Built target onnxifi_dummy
    [ 11%] Built target onnxifi_wrapper
    [ 26%] Built target onnx_proto
    [ 97%] Built target onnx
    [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
    /usr/bin/ld: final link failed: Nonrepresentable section on output
    collect2: error: ld returned 1 exit status
    CMakeFiles/onnx_cpp2py_export.dir/build.make:100: recipe for target 'onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:226: recipe for target 'CMakeFiles/onnx_cpp2py_export.dir/all' failed
    make[1]: *** [CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    Makefile:135: recipe for target 'all' failed
    make: *** [all] Error 2
    /usr/local/lib/python3.6/dist-packages/setuptools/dist.py:726: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      % (opt, underscore_opt)
    /usr/local/lib/python3.6/dist-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /usr/local/lib/python3.6/dist-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
      PkgResourcesDeprecationWarning,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/yjt/onnx-1.10.0/setup.py", line 361, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yjt/onnx-1.10.0/setup.py", line 249, in run
        self.run_command('build_py')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yjt/onnx-1.10.0/setup.py", line 233, in run
        self.run_command('cmake_build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yjt/onnx-1.10.0/setup.py", line 227, in run
        subprocess.check_call(build_args)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/yjt/onnx-1.10.0/setup.py'"'"'; __file__='"'"'/home/yjt/onnx-1.10.0/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
~~~

Help please, thanks.

**Comment by jcwchen** [comment]
Hi @MicroYu-jt,
It seems like an issue related to Protobuf. If you install Protobuf from conda or apt-get, please set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` before building ONNX. By contrast, if you install Protobuf from source, please set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF"` (it is default). See [more explanation](https://github.com/onnx/onnx#build-onnx-from-source).

**Comment by MicroYu-jt** [comment]
> Hi @MicroYu-jt, It seems like an issue related to Protobuf. If you install Protobuf from conda or apt-get, please set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"` before building ONNX. By contrast, if you install Protobuf from source, please set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF"` (it is default). See [more explanation](https://github.com/onnx/onnx#build-onnx-from-source).
Well, I build protobuf from source and it's version is 3.21.10. 
Setting the -DONNX_USE_PROTOBUF_SHARED_LIBS on or off didn't help. But I note there is a warning "protobuf compiler version 21.10 doesn't match library version 3.21.10", is it an issue?
Thanks.

**Comment by jcwchen** [comment]
Might be similar to https://github.com/onnx/onnx/issues/3570. Did you build Protobuf from source with ` -fPIC` (or `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`)? If yes, could you please make sure you only have one installed Protobuf, git clean -xdf in your onnx directory, and then build onnx from source again? Thanks!

**Comment by MicroYu-jt** [comment]
> Might be similar to #3570. Did you build Protobuf from source with ` -fPIC` (or `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`)? If yes, could you please make sure you only have one installed Protobuf, git clean -xdf in your onnx directory, and then build onnx from source again? Thanks!

I built protobuf from source whit -DCMAKE_POSITION_INDEPENDENT_CODE=ON and then built onnx from source again successfully.
~~~
root@ubuntu:/home/yjt/onnx-1.10.0# pip install -e .
Obtaining file:///home/yjt/onnx-1.10.0
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (4.1.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.10.0) (1.11.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (1.19.5)
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/dist-packages (from onnx==1.10.0) (3.19.6)
Installing collected packages: onnx
  Running setup.py develop for onnx
Successfully installed onnx
~~~

But when I try to verify installtion , it failed.
~~~
yjt@ubuntu:/$ python3 -c "import onnx"
Segmentation fault (core dumped)
~~~

**Comment by jcwchen** [comment]
Thanks for the experiment. IIRC, there might be an issue in 1.10.0. Have you tried 1.10.1 or 1.10.2?

**Comment by aadith-warrier** [comment]
I am stuck with a similar issue, but with ONNX 1.13.0


    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [161 lines of output]
        running develop
        /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
          warnings.warn(
        /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
          warnings.warn(
        running build_py
        running create_version
        running cmake_build
        -- The C compiler identification is GNU 11.3.0
        -- The CXX compiler identification is GNU 11.3.0
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /usr/bin/cc - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: /usr/bin/c++ - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        Generated: /home/aadithwarrier/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
        Generated: /home/aadithwarrier/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
        Generated: /home/aadithwarrier/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
        -- Could NOT find pybind11 (missing: pybind11_DIR)
        -- pybind11 v2.9.2
        --
        -- ******** Summary ********
        --   CMake version             : 3.25.1
        --   CMake command             : /usr/local/bin/cmake
        --   System                    : Linux
        --   C++ compiler              : /usr/bin/c++
        --   C++ compiler version      : 11.3.0
        --   CXX flags                 :  -Wnon-virtual-dtor
        --   Build type                : Release
        --   Compile definitions       : __STDC_FORMAT_MACROS
        --   CMAKE_PREFIX_PATH         :
        --   CMAKE_INSTALL_PREFIX      : /usr/local
        --   CMAKE_MODULE_PATH         :
        --
        --   ONNX version              : 1.13.0
        --   ONNX NAMESPACE            : onnx
        --   ONNX_USE_LITE_PROTO       : OFF
        --   USE_PROTOBUF_SHARED_LIBS  : OFF
        --   Protobuf_USE_STATIC_LIBS  : ON
        --   ONNX_DISABLE_EXCEPTIONS   : OFF
        --   ONNX_WERROR               : OFF
        --   ONNX_BUILD_TESTS          : OFF
        --   ONNX_BUILD_BENCHMARKS     : OFF
        --
        --   Protobuf compiler         : /usr/bin/protoc
        --   Protobuf includes         : /usr/include
        --   Protobuf libraries        : /usr/local/lib/libprotobuf.a
        --   BUILD_ONNX_PYTHON         : ON
        --     Python version        :
        --     Python executable     : /usr/bin/python3
        --     Python includes       : /usr/include/python3.10
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /home/aadithwarrier/onnx/.setuptools-cmake-build
        [  2%] Built target gen_onnx_proto
        [  8%] Built target gen_onnx_data_proto
        [  8%] Built target gen_onnx_operators_proto
        [ 10%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
        [ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o
        [ 13%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
        [ 14%] Linking CXX static library libonnx_proto.a
        [ 23%] Built target onnx_proto
        [ 28%] Building CXX object CMakeFiles/onnx.dir/onnx/common/interned_strings.cc.o
        [ 28%] Building CXX object CMakeFiles/onnx.dir/onnx/common/assertions.cc.o
        [ 28%] Building CXX object CMakeFiles/onnx.dir/onnx/checker.cc.o
        [ 29%] Building CXX object CMakeFiles/onnx.dir/onnx/common/ir_pb_converter.cc.o
        [ 31%] Building CXX object CMakeFiles/onnx.dir/onnx/common/model_helpers.cc.o
        [ 32%] Building CXX object CMakeFiles/onnx.dir/onnx/common/path.cc.o
        [ 34%] Building CXX object CMakeFiles/onnx.dir/onnx/common/status.cc.o
        [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/defs.cc.o
        [ 37%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/attr_proto_util.cc.o
        [ 38%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/controlflow/old.cc.o
        [ 40%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/data_type_utils.cc.o
        [ 41%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/function.cc.o
        [ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/defs.cc.o
        [ 44%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/generator/old.cc.o
        [ 46%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/defs.cc.o
        [ 47%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/logical/old.cc.o
        [ 49%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/defs.cc.o
        [ 50%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/old.cc.o
        [ 52%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/math/utils.cc.o
        [ 53%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/defs.cc.o
        [ 55%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/nn/old.cc.o
        [ 56%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/defs.cc.o
        [ 58%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/object_detection/old.cc.o
        [ 59%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/defs.cc.o
        [ 61%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/optional/old.cc.o
        [ 62%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/parser.cc.o
        [ 64%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/printer.cc.o
        [ 65%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
        [ 67%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/quantization/old.cc.o
        [ 68%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/defs.cc.o
        [ 70%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/old.cc.o
        [ 71%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/reduction/utils.cc.o
        [ 73%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/defs.cc.o
        [ 74%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/rnn/old.cc.o
        [ 76%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/schema.cc.o
        [ 77%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
        [ 79%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/shape_inference.cc.o
        [ 80%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/defs.cc.o
        [ 82%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/old.cc.o
        [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
        [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
        [ 86%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
        [ 88%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/defs.cc.o
        [ 89%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/traditionalml/old.cc.o
        [ 91%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/training/defs.cc.o
        [ 92%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
        [ 94%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
        [ 95%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/helper.cc.o
        [ 97%] Linking CXX static library libonnx.a
        [ 97%] Built target onnx
        [ 98%] Building CXX object CMakeFiles/onnx_cpp2py_export.dir/onnx/cpp2py_export.cc.o
        [100%] Linking CXX shared module onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so
        /usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
        /usr/bin/ld: failed to set dynamic section sizes: bad value
        collect2: error: ld returned 1 exit status
        gmake[2]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:101: onnx_cpp2py_export.cpython-310-x86_64-linux-gnu.so] Error 1
        gmake[1]: *** [CMakeFiles/Makefile2:240: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
        gmake: *** [Makefile:136: all] Error 2
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/aadithwarrier/onnx/setup.py", line 358, in <module>
            setuptools.setup(
          File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/aadithwarrier/onnx/setup.py", line 250, in run
            self.run_command("build_py")
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/aadithwarrier/onnx/setup.py", line 233, in run
            self.run_command("cmake_build")
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/aadithwarrier/onnx/setup.py", line 227, in run
            subprocess.check_call(build_args)
          File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jcwchen** [comment]
Hi @aadith-warrier,
Please see my reply here: https://github.com/onnx/onnx/issues/4704#issuecomment-1352244039. I would suggest two ways:
1. Install Protobuf from conda and set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON` before installing ONNX from source.
2. Install Protobuf from source with  `-fPIC` (or `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`) and set `export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=OFF` before installing ONNX from source. ([instructions: Installing Protobuf from source](https://github.com/onnx/onnx#linux))

Please remove installed Protobuf before doing 1. and 2.
