### ISSUE TITLE
DeprecatedWarningDict not printing the replacement

### ISSUE THREAD

**Issue by zhongsanming** [onnx/onnx#4706]
# Bug Report

### Describe the bug
https://github.com/onnx/onnx/blob/45f508bb7c3206cf504b923d54076e42d1ed591c/onnx/mapping.py#L86-L105

in line 100, the string should be a f-string

**Comment by jcwchen** [comment]
Hi @zhongsanming,
Thank you for catching this! I will submit a PR to fix this.
