### ISSUE TITLE
Attributes permissible values 

### ISSUE THREAD

**Issue by adityat77** [onnx/onnx#4715]
### Question
Given an operator in ONNX, how can I extract the permissible values for an Attribute. Example: https://github.com/onnx/onnx/blob/main/docs/Operators.md#attributes-51 -->
 `auto_pad must be either **NOTSET**, **SAME_UPPER**, **SAME_LOWER** or **VALID**.` 
### Further information
- I'm working on extracting all the operators which ONNX support and all the attributes and feasible values, so in to create ONNX models dynamically with random attribute values for automated testing. Given some attributes allow a limited set of values how can I possibly create a set of all the permissible/valid value for the attribute. So far I've seen auto-pad supporting the above mentioned string values in the model. I'm able to access the default-value used by an op. 

So far I've went through the gen_doc.py <https://github.com/onnx/onnx/blob/main/onnx/defs/gen_doc.py#L109> code. Here roughly in schema.attribute[0].description I get the string generating this:

`(Pdb) p schema.attribute[0].description.description
'auto_pad must be either NOTSET, SAME_UPPER, SAME_LOWER or VALID. Where default value is NOTSET, which means explicit padding is used. SAME_UPPER or SAME_LOWER mean pad the input so that the output spatial size match the input.In case of odd number add the extra padding at the end for SAME_UPPER and at the beginning for SAME_LOWER. VALID mean no padding.' `

and I could get the default value by schema.attribute[0].default_value 
But Is it possible to get all permissible-values? 

### Notes
Any help or hints would be great.
TIA.

**Comment by jcwchen** [comment]
Hi @adityat77,
I think the attribute's description is the only way to understand all permissible values... In the schema file actually it does not explicitly enumerate all permissible attribute values in other place (take Convtranspose's auto as an [example](https://github.com/onnx/onnx/blob/ee7d2cdfa34b8b3c7e0b68b70daf72aaa48c23ac/onnx/defs/nn/defs.cc#L1361)). All allowed attribute values are only mentioned in the description.
