### ISSUE TITLE
Missing stub for AttributeProto.AttributeType

### ISSUE THREAD

**Issue by theflyingzamboni** [onnx/onnx#4717]
It seems that stubs were added to onnx in 1.13 for static type checkers, but it appears to have been missed for AttributeProto.AttributeType. When I use one of the members of AttributeType (e.g. AttributeProto.AttributeType.INT), Pylance give me the issue: 

```
Cannot access member "INTS" for type "APT"
  Member "INTS" is unknown
```

Please add a stub for this enum.

**Comment by justinchuby** [comment]
Verified that this is fixed.
