### ISSUE TITLE
Formatting issues with equations / code blocks in HTML operator docs

### ISSUE THREAD

**Issue by robertknight** [onnx/onnx#4725]
# Bug Report

### Describe the bug

In the HTML version of the ONNX operator specs equations/code are formatted in italics rather than monospace as they are in Markdown. I find the Markdown version much easier to read, due to both the font and the background color. Additionally line breaks are handled incorrectly, with `<br/>` appearing as text in the HTML version.

HTML example (from Resize operator):

<img width="854" alt="Code docs HTML" src="https://user-images.githubusercontent.com/2458/209636225-fdb37b71-62ba-425d-a6bb-2f1c5e32b190.png">

Markdown docs:

<img width="1038" alt="Code docs markdown" src="https://user-images.githubusercontent.com/2458/209636333-205b4bc3-3bba-4726-90ab-2b8e19c9d3df.png">

**Comment by jcwchen** [comment]
Hi @robertknight,
Thanks for catching this. Similar issue: https://github.com/onnx/onnx/issues/4566. The website has been launched this Oct and I think yes we should figure out a way to both handle original .md file and HTML version.

**Comment by justinchuby** [comment]
Fixed
