### ISSUE TITLE
About how output size is derived in the resize layer

### ISSUE THREAD

**Issue by SmallBlackEgg** [onnx/onnx#4726]
### Further information
- Relevant Area: We manually created a model with only one resize layer, input 1x21x32x32(nchw), sclae 8, if calculated in the half_pixel way (x_original = (x_resized + 0.5) / scale - 0.5) the output size is 259.5 (rounded to 260), But the result calculated by onnxruntime is 256, and the calculation should be (x_original * scale)。
- How should we calculate its size at this point? Why is the result calculated according to the half_pixel inconsistent with the onnxruntime?

- Is this issue related to a specific model?  
**Model name**: The model is built manually, how do I upload it? This model has only one resize layer, 
- input:1x21x32x32, 
- scale:8, 
- output:1x21x256x256(onnxruntime)，1x21x260x260(Use the half pixel calculation formula，259.5 rounded to 260)
- coordinate_transformation_mode:half_pixel, and no other default properties  
**Model opset**: 11

**Comment by jcwchen** [comment]
Hi @SmallBlackEgg,

> The model is built manually, how do I upload it? This model has only one resize layer,

It would be very helpful if we can have the model to repro this issue. Could you please try to attach files in comment here? Simply click Attach files by dragging & dropping, selecting or pasting them at the bottom with your comment.

**Comment by SmallBlackEgg** [comment]
Oh, sorry, after troubleshooting and verification, it was the deviation caused by my side misunderstanding of scale and their coordinate_transformation_mode, and this problem has been solved

**Comment by jcwchen** [comment]
Glad you have solved the issue. I will close this one now. Feel free to reopen it if you still have other ONNX questions.
