### ISSUE TITLE
Empty directories are installed

### ISSUE THREAD

**Issue by yurivict** [onnx/onnx#4728]
Here is the list of empty directories:

```
@dir include/onnx/backend/sample/ops
@dir include/onnx/backend/test/loader
@dir include/onnx/backend/test/report
@dir include/onnx/backend/test/runner
@dir include/onnx/bin
@dir include/onnx/defs/controlflow
@dir include/onnx/defs/generator
@dir include/onnx/defs/logical
@dir include/onnx/defs/nn
@dir include/onnx/defs/object_detection
@dir include/onnx/defs/optional
@dir include/onnx/defs/quantization
@dir include/onnx/defs/rnn
@dir include/onnx/defs/sequence
@dir include/onnx/defs/traditionalml
@dir include/onnx/defs/training
@dir include/onnx/examples/resources
@dir include/onnx/frontend
@dir include/onnx/onnx_cpp2py_export
@dir include/onnx/reference/ops/aionnx_preview_training
@dir include/onnx/reference/ops/experimental
@dir include/onnx/test/cpp
@dir include/onnx/tools
```

Version: 1.13.0
Python-3.9
FreeBSD 13.1

**Comment by jcwchen** [comment]
Hi @yurivict,
I don't see these empty directories from the latest ONNX 1.13 wheel (on my Windows). What did you do for installing ONNX?

**Comment by yurivict** [comment]
It's a plain cmake build/install. BUILD_SHARED_LIBS=ON, BUILD_ONNX_PYTHON=OFF.

**Comment by yurivict** [comment]
All cmake args:
-DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG"  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG"  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_ONNX_PYTHON:BOOL=OFF -GNinja -DPython_ADDITIONAL_VERSIONS=3.9 -DBOOST_PYTHON_SUFFIX:STRING=39
