### ISSUE TITLE
Integrate the header from onnx.ai to the doc https://onnx.ai/onnx/ 

### ISSUE THREAD

**Issue by andife** [onnx/onnx#4730]
I think for an even better appearance of the documentation it would be a bit nicer in my opinion if the documentation could be integrated a bit better into the website onnx.ai. 

We could achieve that by integrating the header from onnx.ai to the doc https://onnx.ai/onnx/

The navigation is located at https://github.com/onnx/onnx.github.io/blob/main/partials/navigation.html

The principle of how to integrate this can be found in 
https://medium.com/@harishboke/components-in-static-website-as-partials-how-to-include-html-df44cec8b610

**Comment by xadupre** [comment]
I tried something simple to see how it would look. It should be better to add new links in the current documentation than adding a header. We could also change the style to be more aligned with https://onnx.ai/.

![image](https://user-images.githubusercontent.com/22452781/210830732-0d1abc14-3d55-4ef1-8cae-d27a233b1bde.png)
