### ISSUE TITLE
Proposal: make master a protected branch

### ISSUE THREAD

**Issue by lupesko** [onnx/onnx#474]
Proposing to configure master as a Protected Branch.

Protected branches are used to disable force pushing, prevent branches from being deleted, and optionally require status checks before merging.
Here's [more](https://help.github.com/articles/defining-the-mergeability-of-pull-requests/).

Votes / Comments?

**Comment by prasanthpul** [comment]
we should.
we should also cleanup abandoned branches - ideally, only have master and release branches

**Comment by dzhulgakov** [comment]
Yep, feel free to go ahead with it. Also we should encourage folks to properly fork instead of creating branches in onnx/onnx itself.

**Comment by bddppq** [comment]
Regarding to development branches in this main repo, why does it matter?

**Comment by linkerzhang** [comment]
+1 on using fork as dev branch.

**Comment by lupesko** [comment]
Done - configured as protected branch.
LMK if there's any issues with the setup.
Closing.
