### ISSUE TITLE
[New Operator Proposal] DType

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4740]
# New Operator

### Describe the operator

This issue proposes the addition of the `DType` operator: `(T) -> INT64` that produces the data type of a tensor.

We come across the need for it when creating the aten function library. Logic that requires different onnx operators when the input dtypes are different cannot be expressed in a single function because onnx does not support dtype dependent logic. With the `DType` operator this becomes possible. 

As an example, `aten::remainder` behaves differently on int/float inputs:

```python
@onnxscript.script()
def aten_remainder(self: TFloatOrBFloat16, other: TFloatOrBFloat16) -> TFloatOrBFloat16:
    # remainder.Tensor(Tensor self, Tensor other) -> Tensor

    # a - a.div(b, rounding_mode="floor") * b
    rounded_quotient = op.Floor(op.Div(self, other))

    return op.Sub(self, op.Mul(rounded_quotient, other))


@onnxscript.script()
def aten_remainder_int(self: TInt, other: TInt) -> TInt:
    # remainder.Tensor(Tensor self, Tensor other) -> Tensor

    return op.Mod(self, other)
```

with `DType` it is possible to create

```python
@onnxscript.script()
def is_float(x) -> BOOL:
    return op.DType(x) == FLOAT.dtype or op.DType(x) == DOUBLE.dtype or op.DType(x) == FLOAT16.dtype or op.DType(x) == BFLOAT16.dtype

@onnxscript.script()
def aten_remainder(self: TReal, other: TReal) -> TReal:
    # remainder.Tensor(Tensor self, Tensor other) -> Tensor

    if is_float(self):
        # a - a.div(b, rounding_mode="floor") * b
        rounded_quotient = op.Floor(op.Div(self, other))

        result = op.Sub(self, op.Mul(rounded_quotient, other))
    else:
        result = op.Mod(self, other)
    return result
```

### Can this operator be constructed using existing onnx operators?

No.

### Are you willing to contribute it? (Y/N)

Potentially

### Notes

cc @gramalingam @xiaowuhu @fatcat-z @BowenBao @abock

**Comment by thiagocrepaldi** [comment]
IIUC the new operator is not meant to enable new models to be expressed in ONNX, but instead the new operator is designed to make easier the implementation of operators with variant?

If that is the case, given that ONNX ops must be implemented by Hardware vendors which have more limited toolchain than regular architectures, I would say it is ok to have `aten_remainder` and `aten_remainder_int` in ONNX Script and save coding from hardware vendors instead.

@gramalingam what do you think?

**Comment by abock** [comment]
I'd think [`CastLike(15)`](https://onnx.ai/onnx/operators/onnx__CastLike.html) already implies hardware vendors support this as an internal implementation detail. The proposal is to expose it as a formal primitive.

**Comment by xadupre** [comment]
I'm wondering how this would work with shape inference. Another way of doing it would be to enable typed parameter in FunctionProto and allow having two functions with the same name and different types. What option would be better for shape inference?

**Comment by gramalingam** [comment]
Yes, I think we could have problems with type-inference for examples such as above. Currently, there is a requirement that the If operator returns values of the same type in the then-branch and the else-branch. It looks like the above example will not satisfy this requirement? Adding the new operator is not a problem. But the above kind of examples won't work if there is a type mismatch. So, this requires some more thinking.

**Comment by gramalingam** [comment]
There are a few different ways we could handle it. (1) We could extend the If operator's type-inference method to allow then/else branch to return different types in the special case when the if-condition is a compile-time-constant. But this is not perfect, since it depends on a constant-propagation to work properly. (2) We could allow overloaded functions as @xadupre mentions above. But this is a somewhat significant semantic change and extension to ONNX, also require adding type-annotations for inputs/outputs of functions, which is currently absent. (3) We could use different function names for the different types (somewhat like C++'s mangled names used to handle overloading). This may be a bit simpler than (2).

**Comment by BowenBao** [comment]
@gramalingam @xadupre How about supporting writing onnx script function with higher order functions? The current static type semantic in ONNX is unchanged, while relaxing the syntactic constraints. It's similar to (3) (or maybe (2)) in the end but the UX in onnx script interacts and defines only one function.

The alternative is adding this op and relying on constant propagation to remove it eventually. These are two solutions I see without semantic changes to ONNX. A safer operator could be `isDtype(dtypes: List[dtype]) -> bool`, which seems enough for this case, but I'm not sure if it covers enough future use cases. 

The atenlib work would reveal more requirements of this kind.

**Comment by xadupre** [comment]
To me, it seems DType is used in that case like a compilation directive. It can be evaluated with no input and used to build the final ONNX graph. The option like `isDType` is more simple to evaluate for shape inference but it still needs to be evaluated. I don't have a clear answer. So I raise other questions: do we need a function which takes some parameters and produces an ONNX graph? Should that place in ONNX? To me, ONNX is similar to what a compiler produces.

**Comment by justinchuby** [comment]
Closing because even if we know the dtype we still cannot create conditional blocks that will output differently dtype tensors in different branches.
