### ISSUE TITLE
Diff in operators documentation is in wrong direction

### ISSUE THREAD

**Issue by NValerij** [onnx/onnx#4754]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
There is a new documentation for operators on [onnx.ai](https://onnx.ai/onnx/operators/index.html). And it is pretty cool, thank you!
Also it can show diff between any two version, but for now this diff is reversed. Look at [any of them](https://onnx.ai/onnx/operators/text_diff_Split_13_18.html): text in green was deleted with version upgrade, text in red — added (just compare to last version).

### System information
Firefox browser.

### Reproduction instructions
Open [any diff page](https://onnx.ai/onnx/operators/text_diff_Slice_11_13.html). Compare [old](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Slice-11) and [new](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Slice-13) versions manually.

### Expected behavior
On diff page text in green should be those added between this two versions and in red — deleted one.

### Notes
—

**Comment by jcwchen** [comment]
Thanks @xadupre for the fix and I think right now the website shows the right direction. I will close this issue. Feel free to reopen it if you still see any. Thank you for catching this!

**Comment by xadupre** [comment]
I wonder, if you look at https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/allocation_planner.cc#L1722, the function PartitionIntoStreams is not doing exactly the same thing when ORT_ENABLE_STREAM is enabled. I think the second version is more generic but I assumed there was a reason why it was done that way.
