### ISSUE TITLE
Bump onnx version in main

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4762]
ONNX nightly shares the same version with the current release (1.13). This makes it harder for consuming packages to adjust behavior based on onnx versions. Would it make sense to bump the version right after release?

**Comment by jcwchen** [comment]
Hi @justinchuby,
It makes sense to me, especially we have a weekly package for testing. I will bring up this discussion internally.

**Comment by gramalingam** [comment]
Sounds good to me too, thanks!
