### ISSUE TITLE
Print dtype of a onnx graph node

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [onnx/onnx#4766]
# Ask a Question

### Question
How do I print a dtype of a graph node?

```python
model = onnx.load("model.onnx")

for node in model.graph.node:
    # I want to print the dtype, I cannot see anything from the debugger
```

Thanks!

**Comment by xadupre** [comment]
There are not stored in the model but can be computed by running shape inference, see https://onnx.ai/onnx/intro/python.html#checker-and-shape-inference.

**Comment by xadupre** [comment]
shape inference updates output with the inferred shapes. It creates another field `value_info` (`inferred_model.value_info` in your case) with the types and shapes for intermediate results. You will get something like:

```
  value_info {
    name: "XA"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "I"
          }
          dim {
            dim_value: 2
          }
        }
      }
    }
```

`elem_type: 1` is the tensor type (see https://onnx.ai/onnx/api/mapping.html to retrieve the meaning of this value). shape is an array. In this case, it is `[I,2]`: it is 2D tensor with 2 columns and an undefined number of of rows.

**Comment by FrancescoSaverioZuppichini** [comment]
copy that, thanks a lot! :heart:

**Comment by vadimkantorov** [comment]
> (see https://onnx.ai/onnx/api/mapping.html

404 :(

I was looking to know if ONNX has complex dtypes / tuple / tile dtypes

![Image](https://github.com/user-attachments/assets/dbf25ed4-0768-4a58-a61b-36ac427d3442)
