### ISSUE TITLE
pad/matmul/slice Test regression

### ISSUE THREAD

**Issue by tianleiwu** [onnx/onnx#477]
When I run "backend-test-tools generate-data", the following files are modified:
        modified:   onnx/backend/test/data/node/test_edge_pad/node.pb
        modified:   onnx/backend/test/data/node/test_constant_pad/node.pb
        modified:   onnx/backend/test/data/node/test_matmul_2d/output_0.pb
        modified:   onnx/backend/test/data/node/test_reflect_pad/node.pb
        modified:   onnx/backend/test/data/node/test_slice/node.pb
        modified:   onnx/backend/test/data/node/test_slice_neg/node.pb

That seems to be regression in recent changes.

**Comment by houseroad** [comment]
Could you post the content of two NodeProtos here?

**Comment by tianleiwu** [comment]
For example, onnx\onnx\backend\test\data\node\test_edge_pad\node.pb

(Old test data) use command "more node.pb":
xy"Pad*
pads@
@
@@@
@
@@ *
mode"edge 


(New test data)
xy"Pad*
mode"edge *
pads@
@
@@@
@
@@ 

**Comment by houseroad** [comment]
Could you load the pb into memory, and print them in text mode, instead of binary mode? My eyes are not able to read ;-)

**Comment by tianleiwu** [comment]
You might notice that position of the highlighted part is changed (moved from end to the middle):

(old data)
xy"Pad*
pads@ @ @@@ @ @@ *
**mode"edge **

(new data)
xy"Pad*
**mode"edge ***
pads@ @ @@@ @ @@ 

**Comment by bddppq** [comment]
I believe it's the order of "**kwargs" in the `make_node` function is not deterministic. #479 should fix it
