### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#4774]
# Bug Report

#4729 for context

```
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwiseand.py:41:
RuntimeWarning: invalid value encountered in cast  x = np.random.randn(3, 4, 5).astype(np.uint64)
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwiseand.py:42:
RuntimeWarning: invalid value encountered in cast  y = np.random.randn(5).astype(np.uint64)
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwiseor.py:40:
RuntimeWarning: invalid value encountered in cast  x = np.random.randn(3, 4, 5).astype(np.uint64)
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwiseor.py:41:
RuntimeWarning: invalid value encountered in cast  y = np.random.randn(5).astype(np.uint64)
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwisexor.py:41:
RuntimeWarning: invalid value encountered in cast  x = np.random.randn(3, 4, 5).astype(np.uint64)
~/env/onnx/lib/python3.10/site-packages/onnx/backend/test/case/node/bitwisexor.py:42:
RuntimeWarning: invalid value encountered in cast  y = np.random.randn(5).astype(np.uint64)
```

@jcwchen

**Comment by jcwchen** [comment]
Hi @lutzroeder,
Thanks for catching this, but I cannot repro it with my Windows and Mac (Python 3.10+NumPy 1.24.1). My Mac is not a M1/M2 machine though. I guess it might be related to different processor: https://github.com/numpy/numpy/issues/16073 (although that issue is float64->uint32)

The warning seems happened while casting float64 to uint64. Bit-related operators were added since recent ONNX 1.13 and probably that's why we start to see these warnings on some environments.

Since I cannot repro this issue with my machines, if you have time, could you please help me try these commands from your machine and see whether every of them causes warning? (They are good without warning from my end)
```
import numpy as np
a = np.random.randn(5).astype(np.uint64)
b = np.random.randn(5).astype(np.uint32)
c = np.float64(3.6).astype(np.uint64)
d = np.float64(3.6).astype(np.uint32)
```

I think anyway ideally we should make these cast code from NumPy work in every kind of processor.

**Comment by lutzroeder** [comment]
```bash
~: pip list | grep numpy
numpy                    1.24.1
~: python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.random.randn(5).astype(np.uint64)
<stdin>:1: RuntimeWarning: invalid value encountered in cast
>>> b = np.random.randn(5).astype(np.uint32)
>>> c = np.float64(3.6).astype(np.uint64)
>>> d = np.float64(3.6).astype(np.uint32)
```

**Comment by jcwchen** [comment]
Sorry for the late reply (was OOF last week). I guess probably casting a negative float number (from `np.random.randn(5)`) to an unsigned integer will cause this. Could you please help me further try:
```
import numpy as np
a = np.random.randint(10, size=(3, 4, 5)).astype(np.uint64)
b = np.random.randint(10, size=(3, 4, 5)).astype(np.uint32)
# np.random.randn(5).dtype  # I was curious about this type in your platform. I thought it should be float64
```
If these 2 commands are good in your platform, I think they are better than `np.random.randn(5).astype(np.uint32)` to ensure consistency among different platforms. This PR https://github.com/onnx/onnx/pull/4804 should help.

**Comment by lutzroeder** [comment]
```
~: python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>>> import numpy as np
>>> a = np.random.randint(10, size=(3, 4, 5)).astype(np.uint64)
>>> 
~: python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>>> import numpy as np
>>> b = np.random.randint(10, size=(3, 4, 5)).astype(np.uint32)
>>> 
~: python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>>> import numpy as np
>>> np.random.randn(5).dtype
dtype('float64')
>>> 
```

**Comment by jcwchen** [comment]
Thank you for the helpful experiments! One last thing I would like to confirm -- casting negative integers to unsigned integers should be fine I think. Could you please try:
```
import numpy as np
a = np.random.randint(-10, 10, size=(3, 4, 5)).astype(np.uint64)
b = np.random.randint(-10, 10, size=(3, 4, 5)).astype(np.uint32)
```
If these are good in your environment also, I will use them to make test more reliable (See comment: https://github.com/onnx/onnx/pull/4804#discussion_r1087910112). Thanks!

**Comment by lutzroeder** [comment]
```
~: python
iPython 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>>> import numpy as np
>>> a = np.random.randint(-10, 10, size=(3, 4, 5)).astype(np.uint64)
>>> 
~: python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>>> import numpy as np
>>> a = np.random.randint(-10, 10, size=(3, 4, 5)).astype(np.uint64)
>>> 
```

**Comment by adisand** [comment]
I also get the error message: "invalid value encountered in cast". Im using the Napari image viewer. Is there something I can change to get rid of this error? Thanks!

**Comment by jcwchen** [comment]
Hi @adisand,
Although the fix has been merged into the main branch, unfortunately such an issue still exists in the latest onnx package (1.13.1). ONNX 1.14.0 with this fix is coming soon in the end of this month. As a workaround, you can either use the developing package: https://pypi.org/project/onnx-weekly/ or build onnx from source main branch.
