### ISSUE TITLE
Can the model be converted between different version of onnx?

### ISSUE THREAD

**Issue by Joevaen** [onnx/onnx#4781]
# Ask a Question

### Further information
- Relevant Area: <!-I noticed a tutorial about how to convert model between different version of ops here: 
- [https://github.com/onnx/onnx/blob/main/docs/VersionConverter.md](url) , is this what I want?-->

**Comment by jcwchen** [comment]
Yes, [version_converter.py](https://github.com/onnx/onnx/blob/main/onnx/version_converter.py) is what you are looking for. Also you can check the supported list in that file. Please note that currently downgrade is not well supported, but it should cover more upgrade scenarios.

**Comment by Joevaen** [comment]
Thanks for your reply.
Furthermore, my source onnx model's info is like below:
![image](https://user-images.githubusercontent.com/46133615/216576541-ecd8fb55-3c11-4c26-8f5d-6dc525c4cf1a.png)
if my target model's info is like below:
![image](https://user-images.githubusercontent.com/46133615/216576582-d96146dc-2f6b-43b4-88e3-0ad3958ab66e.png)
According the version map from [https://onnxruntime.ai/docs/reference/compatibility.html](url), what should I do?
Can you describe it in detail? it is the 1st time to do such thing. Thanks a lot!

**Comment by jcwchen** [comment]
It will be a downgrade then (ONNX v14 to ONNX v8). Please check the [API](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx). For instance, `converted_model = version_converter.convert_version(original_model, 8)`. However, please note that version_converter is not good at downgrade so probably you will see issues during the conversion especially it involves a big version gap.

**Comment by Joevaen** [comment]
Furthermore,
what's the suitable version of onnx which I should use to convert? 1.8.0 or any other version?
I have used 1.12.0, but error occured:
`RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:63: adapter_lookup: Assertion `false` failed: No Adapter To Version $13 for BatchNormalization`.
Where the "$13" comes from? What should I do?

**Comment by Joevaen** [comment]
Another question,
what is the difference between 'format' and 'imports' symbollize? In another word, what they are based on separately?
If I want a v8 onnx model, except getting from another version onnx model via "converter" like above mentioned, it will also work by converting from a .pth model,right? If so, which version of onnx or onnx-runtime should I need?
Thanks!

**Comment by jcwchen** [comment]
> what's the suitable version of onnx which I should use to convert? 1.8.0 or any other version?

I would suggest using the latest ONNX (1.13 now), which should supports the most cases.

> RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:63: adapter_lookup: Assertion false failed: No Adapter To Version $13 for BatchNormalization.

I guess you are trying to convert the model from opset_version 14 to 8 and the error happened while converting certain node, BatchNormalization, from opset_version 14 to 13. Version converter will upgrade/downgrade the opset_version one by one.

> what is the difference between 'format' and 'imports' symbollize? In another word, what they are based on separately?

Good question. Format stands for ir_version and imports stands for opset_version. See https://github.com/onnx/onnx/blob/main/docs/IR.md#operator-sets. The version map is [here](https://github.com/onnx/onnx/blob/main/docs/IR.md#operator-sets). ONNX will only bump its ir_version when there is a breaking change (e.g., changing proto definition).

> If I want a v8 onnx model, except getting from another version onnx model via "converter" like above mentioned, it will also work by converting from a .pth model,right? If so, which version of onnx or onnx-runtime should I need?

https://onnxruntime.ai/docs/reference/compatibility.html#onnx-opset-support ONNX Runtime promises to support backward compatibility. I would still suggest using the latest ONNX/ONNX Runtime, although you are playing with an older opset_version. If you have the original PyTorch model, you can also try the latest exporter (torch.onnx.export) with specified opset_version to convert the model to an ONNX model with old opset_version, which should be more reliable than using downgrade from onnx.version_converter. See [here](https://pytorch.org/docs/stable/onnx.html#functions).

**Comment by Joevaen** [comment]
> I guess you are trying to convert the model from opset_version 14 to 8 and the error happened while converting certain node, BatchNormalization, from opset_version 14 to 13. Version converter will upgrade/downgrade the opset_version one by one.
I have used `converted_model = version_converter.convert_version(original_model, 13)` instead, but error still occured.
`RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:63: adapter_lookup: Assertion `false` failed: No Adapter To Version $13 for BatchNormalization`.ONNX version is 1.13.0, the lastest. What should I do next?

**Comment by Joevaen** [comment]
> > I guess you are trying to convert the model from opset_version 14 to 8 and the error happened while converting certain node, BatchNormalization, from opset_version 14 to 13. Version converter will upgrade/downgrade the opset_version one by one.
> > I have used `converted_model = version_converter.convert_version(original_model, 13)` instead, but error still occured.
> > `RuntimeError: /github/workspace/onnx/version_converter/BaseConverter.h:63: adapter_lookup: Assertion `false` failed: No Adapter To Version $13 for BatchNormalization`.ONNX version is 1.13.0, the lastest. What should I do next?

**Comment by jcwchen** [comment]
As I mentioned above, downgrade is not well supported in the version converter (downgrade is relatively harder than upgrade). The error shows currently there is no adapter for (BatchNormalization-14 to BatchNormalization-13) and so the conversion failed. See https://github.com/onnx/onnx/blob/3747442528c820ab8dd41111ef3e9ab1a4da6062/onnx/version_converter/convert.h#L496-L500. That is, the latest onnx.version_converter does not support such a downgrade for model with BatchNormalization-14.

I would suggest if you have the original PyTorch model, using `torch.onnx.export` with lower opset_version would be a faster approach. Otherwise, I am afraid you will need to implement the adapter for downgrade with your own.

**Comment by Joevaen** [comment]
Thanks, chen.
I found the best way of converting version is make a comparison between the old version operator and the new. Then change the model via modify some nodes or attributes of it. If I want to use onnx official api, I have to make sure the same operator in two version are compatible( their input\output\attribute are same).
