### ISSUE TITLE
bad conversion from torch.split(2d_tensor,splitsize_list) to SplitToSequence OP

### ISSUE THREAD

**Issue by enerai** [onnx/onnx#4782]
# Bug Report

### Describe the bug

1. I find that SplitToSequence supports the 1-D tensor input of the "split" parameter ( https://github.com/onnx/onnx/blob/main/docs/Operators.md#SplitToSequence ) 
2. torch.split(2d_tensor,splitsize_list). In pytorch, splitsize_list also contains numbers for splitting a tensor ( https://pytorch.org/docs/stable/generated/torch.split.html )
3. They has same abilities for splitting tensor.
however, when I use torch.split() in the model. the onnx converter will construct a SplitToSequence with seq(tensor(int64)) type input, which is not supported. How could I change the generated input, and use 1-D tensor instead?

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):
- ONNX version (*e.g. 1.7*): 1.12.0
- onnxruntime: 1.13.1
- Python version: Python 3.6.8
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):

**Comment by jcwchen** [comment]
Hi @enerai,
It seems more related to torch.onnx.export. Could you please raise this issue in PyTorch repo and tag ONNX to get better help from the exporter team? Thanks.

**Comment by enerai** [comment]
@jcwchen Thanks so much. I report another related issue in pytorch repo for showing the bug. https://github.com/pytorch/pytorch/issues/93264

**Comment by jcwchen** [comment]
Thank you! I will close this one here then. Feel free to reopen it if you still have other ONNX questions.
