### ISSUE TITLE
Load weights from ONNX models in C++

### ISSUE THREAD

**Issue by SrikaraPranesh** [onnx/onnx#4789]
I am trying to load weights from an onnx model created in pytroch in C++ using TensorProto in GraphProto. However the
tensors in TensorProto seem to be empty.

**Comment by jcwchen** [comment]
Hi @SrikaraPranesh,
Would you mind to share the model for us to repro this issue? Can't you find these weights in model.graph.initializers either? BTW, using https://netron.app/ would be very useful for visualization if you haven't.
