### ISSUE TITLE
Quantized Transformer Export

### ISSUE THREAD

**Issue by parakh08** [onnx/onnx#4802]
Hi,

I am trying to export the torch-native PTQ model using the timm repo. I am working on exporting the deit_tiny_patch_16 model. 
The model conversion is however failing with runtime error:

RuntimeError: ONNX symbolic expected node type `prim::TupleConstruct`, got `%456 : Tensor = onnx::Concat[axis=1](%quantize_per_tensor_5, %patch_embed_norm) # <eval_with_key>.10:32:0

I am not aware on how to debug this specific type of issue, tried changing the specific layer to suppress if the error is because of that layer, however, I start getting the error in some other layer.

OS: Ubuntu 18.04
ONNX : 1.13.0
Python : 3.8.13

For reproducing, we just need to export the quantized timm network, timm can be directly cloned, and the torch-native quantization can be used from https://pytorch.org/blog/quantization-in-practice/ .

Basically,

```
import timm
import torch
from torch.quantization import quantize_fx

torch_model = timm.create_model('deit_tiny_patch16_224')
backend = "fbgemm"
qconfig_dict = {"": torch.quantization.get_default_qconfig(backend)}

model_prepared = quantize_fx.prepare_fx(torch_model, qconfig_dict)

# We can skip the calibration for the export purpose

model_quantized = quantize_fx.convert_fx(model_prepared)

torch.onnx.export(model_quantized,
                  x, 
                  'model.onnx', 
                  export_params=True, 
                  opset_version=13, 
                  do_constant_folding=False, 
                  input_names=['input'], 
                  output_names=['output'],
                  dynamic_axes={"input":{0:"batch_size"},
                                "output":{0:"batch_size"}}
                  )

```

**Comment by jcwchen** [comment]
Hi @parakh08,
IIUC, quantization has not been fully supported by the torch.onnx.export yet so there might be some limitations. I would suggest you raise this issue in the exporter repo (under PyTorch) instead and mention ONNX in the title to get better assistance from the exporter team.

**Comment by parakh08** [comment]
Hi @jcwchen,

Thanks for the reply. I have now raised an issue on torch repo which can be accessed through [this](https://github.com/pytorch/pytorch/issues/93346#issue-1563954675).

**Comment by jcwchen** [comment]
Thank you for the quick response. I will close this one then. Please track this issue there. Feel free to reopen it if you still have other ONNX questions. Thanks!
