### ISSUE TITLE
[Feature request] CI: compile with UBSan and ASan

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4820]
### What is the problem that this feature solves?

UBSan finds undefined behavior in https://github.com/pytorch/pytorch/issues/93174. We can use it in our CI (maybe)? https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html

### Are you willing to contribute it (Y/N)

None

**Comment by justinchuby** [comment]
Run ASan too if not already?

**Comment by justinchuby** [comment]
We may need to compile with clang in CI first

**Comment by jcwchen** [comment]
Mac release CI seems to run clang: https://github.com/onnx/onnx/blob/19f700e01b05a263d121d6820d35df7dbf1e7918/.github/workflows/release_mac.yml#L48

**Comment by justinchuby** [comment]
Maybe enable the checks on macos first then?
