### ISSUE TITLE
Anyone checked the opreator sets defined in https://github.com/openxla/stablehlo please?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#4821]
At least StableHLO shares part of the vision of ONNX, which were designed as "multiple-layers" operators though. :-)

**Comment by justinchuby** [comment]
@gramalingam @xadupre I kinda like how constraints for specified there https://github.com/openxla/stablehlo/blob/main/docs/spec.md

**Comment by xadupre** [comment]
I see they already added float 8 types.

**Comment by justinchuby** [comment]
I wonder if the constraints are formally expressed and if verification code can be generated.

**Comment by justinchuby** [comment]
fp8 related: https://github.com/openxla/xla/discussions/22
