### ISSUE TITLE
github settings: Turn on "require-sign-off-on-web-based-commits"?

### ISSUE THREAD

**Issue by andife** [onnx/onnx#4822]
Hi,

In my opinion, the DCO leads to problems every now and then, and even experienced Onnx contributors forget about it from time to time. As I currently see it, it is at least that online when changing via the github online interface. 

I would suggest to turn on "require-sign-off-on-web-based-commits" (https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/#how-to-enable-required-signoffs-for-a-repository)

I think there should be nothing against it?

**Comment by prasanthpul** [comment]
This is great! Thanks for finding it Andreas. It's a new feature (well as of June 2022) that didn't exist before when we originally setup DCO. It's now enabled on all active ONNX repos.

**Comment by andife** [comment]
Maybe we should also a small note to the documentation, that the users have to set it also at their own forked repository,  otherwise errors could occur when editing the forked branch during a pull request.
