### ISSUE TITLE
 CPU usage is too high

### ISSUE THREAD

**Issue by jungms4536** [onnx/onnx#4826]
# Ask a Question

### Question
I am using my YOLO model learned with pytorch by converting it to onnx
I am inferring using onnxruntime-gpu in C#.
GPU is used but CPU usage is too high
Is there any way to lower the CPU usage?

### Further information
- Relevant Area: 
![캡처2](https://user-images.githubusercontent.com/82021950/215650570-bce10863-07fa-4695-8520-602991190617.PNG)
![캡처1](https://user-images.githubusercontent.com/82021950/215650569-30a59a83-aff6-441d-aba0-fa18c6434f59.PNG)

- Is this issue related to a specific model?
**Model name**: YOLOv5s
**Model opset**: 12

**Comment by jcwchen** [comment]
Hi @jungms4536,
It seems more like a question for ONNX Runtime. I was you also raise an issue there, which is a better place to track this issue. I will close this one. Feel free to reopen it if you still have other ONNX questions. Thanks.
