### ISSUE TITLE
can opset 13 support triu?

### ISSUE THREAD

**Issue by labmanno004** [onnx/onnx#4830]
# Ask a Question

### Question

For some reasons, I need to get the onnx model with opset version 13.I used torch.onnx.export(). But I encountered this problem during converting: "UnsupportedOperatorError: Exporting the operator ::triu to ONNX opset version 13 is not supported. Support for this operator was added in version 14, try exporting with this version."

### Further information
- Relevant Area: 
- Platform: Linux-4.15.0-196-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.12.1 (True)

- Is this issue related to a specific model?
**Model name**: stable-diffusion-2-1(https://huggingface.co/stabilityai/stable-diffusion-2-1)
**Model opset**: 13

**Comment by jcwchen** [comment]
Hi @labmanno004,
Unfortunately no. ONNX won't add any new operator to an old released opset version. The best way to enable Triu support would be letting the tool (backend, runtime) support newer opset_version 14.

**Comment by labmanno004** [comment]
> Hi @labmanno004, Unfortunately no. ONNX won't add any new operator to an old released opset version. The best way to enable Triu support would be letting the tool (backend, runtime) support newer opset_version 14.

Got it. Thank you.

**Comment by jcwchen** [comment]
It seems resolved. I will close this one. Feel free to reopen it if you have other ONNX questions.
