### ISSUE TITLE
Whether the GeneralizedRCNN model (trained by detectron2) can be converted to Onnx with torch.onnx.export()?

### ISSUE THREAD

**Issue by htlbayytq** [onnx/onnx#4834]
I've been trying for days to use torch.onnx.export() to convert my trained detectron2 model to onnx.

The detectron2 model is a GeneralizedRCNN model, It is also the ideal model that took me a long time to train, using my own data set.

Now I want to convert it to onnx to deploy it, but there are always various errors.

When I read the official document today, I found that it seems that the model of type "recurrent network" cannot be converted with torch.onnx.export()? It is said that torch.jit.trace() cannot convert it.

Sincerely and eagerly requesting an answer, is it possible to use torch.onnx.export() to complete the conversion of the detectron2 trained GeneralizedRCNN model?

I have been tortured for many days, please help me dear experts!

**Comment by jcwchen** [comment]
Hi @htlbayytq,
It is more like a question for the exporter. I saw you have also raised this issue in the exporter repo (PyTorch), which is a better place to track this. I will close this one. Feel free to reopen it if you still have other ONNX questions. Thanks!
