### ISSUE TITLE
InferenceError: [ShapeInferenceError] (op_type:Add): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (2) vs (1)

### ISSUE THREAD

**Issue by xiaokening** [onnx/onnx#4836]
## Question
When I run the following code the program will report an error InferenceError

`import onnx.parser
from onnx import helper, shape_inference

input = '''
    <
        ir_version: 8,
        opset_import: [ "" : 15]
    >
    agraph (float[I,2] X, float[2] B) => (float[I] Y) {
        Y = Add(X, B)
    }
    '''
onnx_model = onnx.parser.parse_model(input)
inferred_model = shape_inference.infer_shapes(onnx_model)
print(onnx_model)`

but when I modify param B shape, it can run successfully, The correct code is below

`import onnx.parser
from onnx import helper, shape_inference

input = '''
    <
        ir_version: 8,
        opset_import: [ "" : 15]
    >
    agraph (float[I,2] X, float[4] B) => (float[I] Y) {
        Y = Add(X, B)
    }
    '''
onnx_model = onnx.parser.parse_model(input)
inferred_model = shape_inference.infer_shapes(onnx_model)
print(onnx_model)`

Who can help me solve this confusion, thanks!

## ONNX information
onnx.__version__='1.13.0', opset=18, IR_VERSION=8

**Comment by jcwchen** [comment]
Hi @xiaokening,
For the case `agraph (float[I,2] X, float[4] B) => (float[I] Y)`, by default shape inference will simply stop without throwing an error if it bumps into a shape inference error in an immediate node. If you further enable strict_mode like ` shape_inference.infer_shapes(onnx_model, strict_mode=True)`, you will find shape inference error: `[ShapeInferenceError] Shape inference error(s): (op_type:Add): [ShapeInferenceError] Incompatible dimensions`.

For the case `agraph (float[I,2] X, float[2] B) => (float[I] Y) {`, the shape_inference will success in the immediate node, but it will bump into an error when comparing the final output shape (The output shape mismatch will be caught regardless of strict_mode). Using `agraph (float[I,2] X, float[2] B) => (float[I, 2] Y) {` should help resolve this error.

**Comment by xiaokening** [comment]
got it! thank you!
