### ISSUE TITLE
fft_rfftn is not supported

### ISSUE THREAD

**Issue by zuixiaosanlang** [onnx/onnx#4843]
about a inpainting model called big-lama.pt from 
https://github.com/saic-mdal/lama

i want to trans it to .onnx， but failed

use torch 1.13.2,
also occur:
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::fft_rfftn' to ONNX opset version 17 is not supported.

**Comment by anyingyi** [comment]
how to do you solve this problem, i meet the same error with you.

**Comment by hajungong007** [comment]
> 

请问你找到解决的办法了没

**Comment by zuixiaosanlang** [comment]
@hajungong007 
没哦，可以的话，自己实现那个算子呗，用两个一维的去实现呗

**Comment by hajungong007** [comment]
> @hajungong007 没哦，可以的话，自己实现那个算子呗，用两个一维的去实现呗

没有办法的办法，能站在巨人的肩膀上是上上策
