### ISSUE TITLE
s3.amazonaws.com/download.onnx/models are forbidden for download

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#4857]
# Bug Report

### Is the issue related to model conversion?

No

### Describe the bug

s3.amazonaws.com/download.onnx/models are forbidden for download. People will see test failure if testing ONNX (pytest under onnx directory) in a fresh envionrment (including current CI pipelines), because the model download link is broken. e.g., https://s3.amazonaws.com/download.onnx/models/opset_10/resnet50.tar.gz.

### Reproduction instructions

```
cd onnx
pytest
```

### Expected behavior

pytest should always succeed.

**Comment by philass** [comment]
Currently `onnx-mlir` pipelines are broken because we pull in these tests

**Comment by jcwchen** [comment]
@philass Unfortunately, these models were setup long time ago and it's hard to find the original owner of s3 instance to fix them. In addition, currently in onnx repo there is a weekly pipeline to test the latest onnx with all ONNX model Zoo models, which should cover the same tests by these models.

Since this issue is blocking pipelines in ONNX as well, I have created a PR to remove them: https://github.com/onnx/onnx/pull/4859. Going forward I would suggest using [onnx.hub](https://github.com/onnx/onnx/blob/main/docs/Hub.md) to download these real ONNX models (you should be able to find corresponding models in https://github.com/onnx/models). Please note that git-lfs quota for onnx/models is quite limited so I would also suggest to cache them somehow in the pipelines or running it less frequently.

**Comment by jcwchen** [comment]
Please note that we have transferred the model from AWS to download.onnxruntime.ai by this PR https://github.com/onnx/onnx/pull/4865. We will have a patch release 1.13.1 for this update soon. Reopen this PR to engage more awareness for a while.

**Comment by philass** [comment]
@jcwchen thanks for explaining the situation and the suggestions for workarounds. It is much appreciated

**Comment by jcwchen** [comment]
The fresh ONNX 1.13.1 patch should resolve this issue by https://github.com/onnx/onnx/pull/4865. Using the latest ONNX should not bump into this issue. I will close this issue here. Please note that going forward we would like to remove these real model tests in next ONNX release. See detail here: https://github.com/onnx/onnx/issues/4885.
