### ISSUE TITLE
Reading onnx models.

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#486]
As I noticed, onnx models have a `model.pb` file and a few zip files. Suppose I want to read and load an onnx model, how should I process the `model.pb` file to generate the data structure using `protoc`, given that there is no `.proto` file? Basically, what should be my steps from reading a `.pb` file to generating the data structures?

PS: I know what onnx models can directly be loaded from other frameworks, but I am trying to make an onnx reader for Julia. Help in any form is appreciated.

**Comment by bddppq** [comment]
@ayush1999 You need the [onnx.proto](https://github.com/onnx/onnx/blob/34ac327093f1a80f3bbbab35f7c73bb09864ba76/onnx/onnx.proto) file to deserialize the `.pb` file.

**Comment by ayush1999** [comment]
@bddppq I found the onnx.proto file in the onnx folder. Then, I generated the Julia data structure using the ProtoBuf.jl Julia package. However , I can't figure out how to deserialize the model.pb file. Can you tell me how this can be done?

**Comment by bddppq** [comment]
@ayush1999 Sorry I'm not familiar with Julia :-).

Here is how we do it in Python: https://github.com/onnx/onnx/blob/34ac327093f1a80f3bbbab35f7c73bb09864ba76/onnx/__init__.py#L34

The Protobuf.jl package repo has some docs, especially the `Using ProtoBuf` section in [this one](https://github.com/JuliaIO/ProtoBuf.jl/blob/master/USAGE.md) should be able to help.
