### ISSUE TITLE
onnx-caffe2 is slower?

### ISSUE THREAD

**Issue by hyer** [onnx/onnx#488]
I try to run this tutorial:[Example: End-to-end AlexNet from PyTorch to Caffe2]( http://pytorch.org/docs/master/onnx.html)
However, I found the reference speed of onnx-caffe2 is 10x slower than the origin pytorch model.
Anyone help? Thanks.

My Machine:

- Ubuntu 14.04
- CUDA 8.0
- cudnn 7.0.3
- Caffe2 latest
- Pytorch 0.3.0

**Comment by jamesr66a** [comment]
Hi @hyer, 

Could you set the net type for the generated `rep.predict_net` to equal `prof_dag`? This will instrument the execution of the caffe2 with timers and print out information on destruction of the net. Please post the results of this profiling and we can dig deeper

**Comment by hyer** [comment]
@jamesr66a I'm new to onnx, so I have no idea to "set the net type for the generated rep.predict_net to equal prof_dag". Would you please point out how to set it. thanks! Here is my code:
``` python
import onnx

# Load the ONNX model
model = onnx.load("alexnet.proto")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a human readable representation of the graph
onnx.helper.printable_graph(model.graph)


# ...continuing from above
import onnx_caffe2.backend as backend
import numpy as np

rep = backend.prepare(model, device="CUDA:0") # or "CPU"

for i in range(10):

    start = time.time()
    outputs = rep.run(np.random.randn(1, 3, 224, 224).astype(np.float32))
    # To run networks with more than one input, pass a tuple
    print time.time() - start
    # rather than a single numpy ndarray.
    # print outputs[0]
    time.sleep(2)
```

BTW, the program output:
```shell
No handlers could be found for logger "caffe2.python.workspace"
0.494230031967
0.0182650089264
0.0340929031372
0.0261168479919
0.0157599449158

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
"exit code 139"? Is there any other problem?

**Comment by bddppq** [comment]
@hyer Insert `rep.predict_net.type = 'prof_dag'` after `rep = backend.prepare(model, device="CUDA:0") # or "CPU"`

**Comment by hyer** [comment]
@bddppq After I insert the  `rep.predict_net.type = 'prof_dag'`, I got error:
```shell
No handlers could be found for logger "caffe2.python.workspace"
Traceback for operator 573515912 in network torch-jit-export
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0130 09:50:35.918893 13694 workspace.cc:263] Error when creating the network.Maybe net type: [prof_dag] does not exist
Traceback (most recent call last):
  File "/home/hyer/workspace/pytorch_master/converter/convert_alexnet2caffe2.py", line 67, in <module>
    outputs = rep.run(np.random.randn(1, 3, 224, 224).astype(np.float32))
  File "/usr/local/lib/python2.7/dist-packages/onnx_caffe2/backend_rep.py", line 48, in run
    workspace.CreateNet(self.predict_net)
  File "/home/hyer/workspace/caffe2/build/caffe2/python/workspace.py", line 163, in CreateNet
    StringifyProto(net), overwrite,
  File "/home/hyer/workspace/caffe2/build/caffe2/python/workspace.py", line 189, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.cc:855] gWorkspace->CreateNet(proto, overwrite). Error creating net with proto: 
torch-jit-export\
1
219
```

**Comment by jamesr66a** [comment]
Hi @hyer, did you bild caffe2 from source? If so, can you set the USE_PROF option for the CMake build to ON? https://github.com/caffe2/caffe2/commit/a40bc312d37a70f704441dac32da6d8eb201c207

Should be as simple as assing `-DUSE_PROF=ON` to your cmake command when  you build caffe2. This will hopefully recompile caffe2 with the profiling net type

**Comment by bddppq** [comment]
@hyer Have you had a chance to run it as prof_dag graph?

**Comment by hyer** [comment]
@jamesr66a @bddppq  Sorry to reply you so late! I will try your advise. BTW, did you have try to run the tutorial http://pytorch.org/docs/master/onnx.html? What about the result? I will post the result of "USE_PROF option" later. Thx!

**Comment by samson-wang** [comment]
I tried the demo too.
Only get a `Segmentation fault (core dumped)`!

**Comment by danFromTelAviv** [comment]
I also get a segmentation fault
