### ISSUE TITLE
running error on an  arm processor

### ISSUE THREAD

**Issue by kaishijeng** [onnx/onnx#489]
I build onnx on firefly3399 which has arm a72 processor. However I got the following error when running python2 -c "import onnx"

/usr/local/lib/python2.7/dist-packages/onnx-0.2.1-py2.7-linux-aarch64.egg/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message13SpaceUsedLongEv

Any idea why this happens?
Thanks,

**Comment by bddppq** [comment]
It might be your protobuf library was compiled with cxx11 abi while your compiler defaults to build with the old one. Please do `nm -C $PATH_TO_LIBPROTOBUF | grep google::protobuf::Message::SpaceUsedLong` and see whether there is a `[abi:cxx11]` tag in the output.
