### ISSUE TITLE
ViT model dramatically degrade in performance speed

### ISSUE THREAD

**Issue by proevgenii** [onnx/onnx#4927]
# Bug Report
### The inference of the ViT model becomes slower in onnx than in the native pytorch
I'm converting timm model to ONNX format and inference time becomes almost 4 times larger 

### Is the issue related to model conversion?
No
### Reproduction instructions
Here script that I'm using
```
### LOAD pretrained ViT model from timm
model_name = 'vit_base_patch32_224_clip_laion2b' 
model = timm.create_model(model_name, pretrained = True)
model = model.eval().to('cuda')

### Torch performance
times = []
with torch.no_grad():
    for i in range(1000):
        inputs = torch.randn(1,3,224,224).to('cuda')
        st = time.time()
        out = model(inputs)
        times.append(time.time()-st)
print(f"Torch time performance: {np.mean(times):.4f}")

### Convert model to ONNX format
dummy_input=torch.randn(1, 3, 224, 224).to('cuda')
torch.onnx.export(model,
                  dummy_input,
                  "models/vit_pytorch.onnx",
                  verbose=True)

### Create ort session
ort_sess = onnxruntime.InferenceSession("models/vit_pytorch.onnx",
                                        providers = ['CUDAExecutionProvider'])
first_input_name = ort_sess.get_inputs()[0].name

### ONNX model performance with CUDA provider
times = []
for i in range(1000):
    inputs = np.random.randn(1, 3, 224, 224).astype(np.float32)
    st = time.time()
    outputs = ort_sess.run([], {first_input_name: inputs})
    times.append(time.time()-st)
print(f"ONNX time performance: {np.mean(times):.4f}")
```
#### And this produce
```
Torch time performance: 0.0093
ONNX time performance: 0.0346
```
### Expected behavior
I expect a speedup or at least the same inference time when using  CUDAExecutionProvider in onnxruntime
### System information

- OS Platform and Distribution: Debian 5.10.149-2
- ONNX : onnxruntime-gpu==1.14.0
- Pytorch = 1.12.1
- Python version: 3.8.10
- GPU: Tesla T4

**Comment by jcwchen** [comment]
Hi @proevgenii,
It's more like a question for ONNX Runtime. Please raise this issue in their repo to let ORT experts take a closer look. Thanks.

**Comment by xadupre** [comment]
In your example, the torch code does not count copy from CPU to GPU and GPU to CPU but the code using onnxruntime does include it. That does not explain everything but that would be a more fair comparison (use `ort_sess.run_with_ortvalues`). onnxruntime can profile the operators to see which one is slow. I would also exclude the first iteration for the average time. onnxruntime might use this time to run some optimization.

**Comment by VoVoR** [comment]
I've got the same issue with Timm's Vits even using TensorRT
Did you resolve it by any chance?
