### ISSUE TITLE
[PR400 Follow UP] API refined to avoid data copies when loading a model for optimization or execution

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#493]

**Comment by houseroad** [comment]
@linkerzhang Could you leave more description in this issue?

**Comment by houseroad** [comment]
I think https://github.com/onnx/onnx/pull/491 should partially address this issue.

**Comment by askhade** [comment]
closing this issue since optimizers are no more part of onnx main repo. They have been moved to a separate repo. If this issue is still relevant please open it there.
