### ISSUE TITLE
Move the test related part of the markdown file to the documentation site?

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4936]
Changes in TestCoverage.md and Operators.md has been a minor annoyance in many PRs that invlove code changes. Running the python doc gen command doesn't always yield the same result as CI (its enviroment needs to be carefully set up. e.g. no competing onnx installation can exist in the environment) I wonder if we can move the usage and test coverage part to CI generated and not commited.

**Comment by jcwchen** [comment]
To confirm, I think you are only talking about the test code part (changes from `onnx/backend/test/case/node`)?

I have similar thought (making these documents auto generated in the CIs without users' commit) before... The only concern pushed me back is having these updated document (for instance Operators.md) in the PR is quite helpful for the reviewers to preview changes in the PR page. I think at least keeping the operator updates in `Operators.md` is helpful and perhaps we can try to move changes from `onnx/backend/test/case/node` out somewhere.

**Comment by justinchuby** [comment]
We _could_ also consider creating a action that publishes the diff as a review comment only for reviewers, for example.
