### ISSUE TITLE
Does ONNX support statsmodel

### ISSUE THREAD

**Issue by nealcha** [onnx/onnx#4946]
Hi, I am trying to convert a statsmodel(like `statsmodels.api.OLS()`) into ONNX model, but I didn't find a way to do it. I am wondering whether ONNX supports statsmodel ？THANKS!

**Comment by jcwchen** [comment]
Hi @nealcha,
Similar to https://github.com/onnx/onnx/issues/4155? Still today I am not aware of any conversion tool for it.

**Comment by nealcha** [comment]
> Hi @nealcha, Similar to #4155? Still today I am not aware of any conversion tool for it.

yeah，it seems ONNX does not support statsmodel for now. thanks anyway!

**Comment by cbourjau** [comment]
@nealcha I added an [example](https://github.com/onnx/onnx/issues/4155#issuecomment-1450938918) to #4155 to show how you might get started.

**Comment by gramalingam** [comment]
@andife : I see you reopened this. Can you clarify what you are looking for? It sounds like this is a request for a converter/exporter to ONNX, which seems out of scope for this repo at any rate.
