### ISSUE TITLE
Size Operator

### ISSUE THREAD

**Issue by jamesr66a** [onnx/onnx#495]
Caffe2: https://caffe2.ai/docs/operators-catalogue.html#size
Pytorch: http://pytorch.org/docs/master/tensors.html#torch.Tensor.size

This is useful if we need to dynamically allocate tensors with shapes derived from the shapes of other tensors, such as in beam search

**Comment by jamesr66a** [comment]
Note: introducing this would introduce the concept of dynamic shapes and likely break static shape inference

**Comment by dzhulgakov** [comment]
Introducing this directly won't break shape inference, will it? The output length would be just a rank of input. But adding dynamic allocation would break it certainly. What's the exact situation when it happens?

**Comment by jamesr66a** [comment]
@dzhulgakov This and following uses https://github.com/caffe2/caffe2/blob/master/caffe2/contrib/script/examples/example_beam_search.c2s#L13

**Comment by dzhulgakov** [comment]
Also we should have `Shape` operator (@Maratyszcza needs it). Any takers to write it up?
