### ISSUE TITLE
checker does not check schema for custom op referenced local functions

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#4957]
# Bug Report

### Is the issue related to model conversion?
No
### Describe the bug
as discussed at: https://github.com/onnx/onnx/pull/4911#discussion_r1122327102
checker does not check schema for custom op referenced local functions. 

### System information
NA

### Reproduction instructions
NA

### Expected behavior
When a local function is called from a op with mis-matching signature, the checker shall raise an error

### Notes
No

**Comment by gramalingam** [comment]
Just to clarify: this may be (partly) need to be under "shape inference", rather than the "checker". Currently, the type-related checking aspects reside under "shape inference", not the "checker".

**Comment by 1372072273** [comment]
> 

how to shape infer with a custom op? its just can be run in onnxruntime when load the custom complie lib
