### ISSUE TITLE
Support for latest protobuf versions > 4 

### ISSUE THREAD

**Issue by Zahlii** [onnx/onnx#4971]
### What is the problem that this feature solves?

Currently, onnx relies on an old version of protobuf (<4). This leads to issues on M1/M2 chips, which only natively support protobuf >4, grpcio >=1.51.3. Tensorflow with the upcoming 2.12 release is going to add support for latest protobuf (see https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38#diff-f526feeafa1000c4773410bdc5417c4022cb2c7b686ae658b629beb541ae9112 ), so it would be nice if we could somehow get an onnx version supporting this , too.

### Are you willing to contribute it (Y/N)

Yes

**Comment by jcwchen** [comment]
It should be fixed by the fresh ONNX 1.14.0. Please let me know if you still bump into this issue. Thank you! I will close this now.
