### ISSUE TITLE
[Feature request] Promote `perm` in `Transpose` to input

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4981]
### What is the problem that this feature solves?

`perm` in `Transpose` as an attribute makes dynamic construction impossible, which leads to incomplete support for `torch.transpose`:

```python
@torch_op("aten::transpose", trace_only=True)
def aten_transpose(self, dim0: int, dim1: int):
    """transpose.int(Tensor(a) self, int dim0, int dim1) -> Tensor(a)"""

    # Use trace only to construct the prem attribute in Transpose
    self_rank = len(self.shape)  # type: ignore[attr-defined]

    if self_rank == 0:
        result = self
    else:
        # Python code, change when onnxscript supports this
        dims = list(range(self_rank))
        dims[dim0], dims[dim1] = dims[dim1], dims[dim0]
        # Python code ends

        result = op.Transpose(self, perm=dims)

    return result
```

### Alternatives considered

Create a new op SwapAxes #4977 

### Describe the feature

Promote `perm` in `Transpose` to input

### Feature Area

operators

### Are you willing to contribute it (Y/N)

Yes

**Comment by justinchuby** [comment]
I suggest creating SwapAxes to avoid disruptive change in the Transpose op.

**Comment by gramalingam** [comment]
My intuition is that this could impact existing optimizations that try to minimize the number of Transposes. Transposes may be often generated to handle layout differences like NCHW and NHWC etc., and this can lead to potentially redundant transposes. So, I would be a bit wary of promoting the attribute into an input for Tranpose. Perhaps SwapAxes would be less disruptive.

**Comment by justinchuby** [comment]
TODO: Investigate optimization impact

**Comment by justinchuby** [comment]
Helpful in https://github.com/microsoft/onnxscript/pull/1042

**Comment by justinchuby** [comment]
@yufenglee @pranavsharma We were wondering what the potential impact will be to ONNX Runtime with this change. Some input will be appreciated!

**Comment by justinchuby** [comment]
Since models usually have a fixed rank, this change is not required for now.
