### ISSUE TITLE
convert onnx takes a long time

### ISSUE THREAD

**Issue by guoyujiang** [onnx/onnx#4988]
# Ask a Question

### Question
Hi, I train  a big swin model,  it costs  21 seconds   inferencing  one picture  by pytorch. Then I  convert  it to onnx, but this convert  takes  6 minutes.  I can't figure out  why this  trace  take so long time, and how can I reduce  the time?  Thank you.

**Comment by justinchuby** [comment]
Maybe try running torch.jit.trace on the model first then pass the jitted model to torch.onnx.export? This question may also be better fitted for the PyTorch repo.
