### ISSUE TITLE
WHY，received an input of unsupported type: int？

### ISSUE THREAD

**Issue by xiao-lin-hub** [onnx/onnx#4989]
```
    def forward(self, input_features):

        x = input_features[-1]
        for i in range(4, -1, -1):

            x = self.convs[("upconv", i, 0)](x)

            x = [upsample(x)]

            if self.use_skips and i > 0:
                x += [input_features[i - 1]]

            x = torch.cat(x, 1)

            x = self.convs[("upconv", i, 1)](x)

            if i in self.scales:  # (0,4)
                self.outputs[("disp", i)] = self.sigmoid(self.convs[("dispconv", i)](x))

        return self.outputs
```
The above is the forward code of the model.

```
torch.onnx.export(depth_decoder, [torch.randn(1,64,128,128),
                                     torch.randn(1,64,64,64),
                                      torch.randn(1,128,32,32),
                                      torch.randn(1,256,16,16),
                                      torch.randn(1,512,8,8)], onnx_encoder_path)
```
Why do I always get this error when I use the following code to convert

RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: int

where is INT 
I CAN‘T understand
who can HELP ME
SO GREATEFUL

**Comment by jcwchen** [comment]
Hi @xiao-lin-hub,
It seems like a question for the exporter (torch.onnx.export). Could you please raise issue in PyTorch repo instead to get the best assistance from the exporter experts? Thanks.
