### ISSUE TITLE
[Feature request] Promote all axis attributes to input

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4991]
### What is the problem that this feature solves?

Axis as an argument tend to be dynamic or become dynamic in frameworks. To support exporting models that use ops that take axis as an argument, it will be helpful to promote them as inputs. Instead of doing this case by case, I feel that doing a sweep on all ONNX ops that take axis is reasonable.

cc @gramalingam @jcwchen @xadupre @liqunfu @BowenBao 

### Describe the feature

LayerNormalization: axis
Transpose: perm
Argmin/Argmax: axis
etc.

### Are you willing to contribute it (Y/N)

None

**Comment by jcwchen** [comment]
See related discussion: https://github.com/onnx/onnx/issues/3420.

I can imagine some of runtime might have huge impact if axis becomes a dynamic input. IMO I still think it's better to promote axis attributes to input **on demand**, instead of promoting all of them in a single time. That is to say, if **currently** there is no dynamic use case for certain operator's axis, I don't see a strong reason that why we want to promote them from attribute to input ().

**Comment by xadupre** [comment]
It would be better to know the full list of impacted operators. Moving an attribute to the list of input has a significant impact on all converting libraries.

I think the implementation in onnxruntime does not take into account the fact the permutation is known in advance however this has a huge impact on optimizer fusing nodes (Transpose + Gemm). The optimizer cannot fuse if the permutation if it is not known. It should detect the permutation is a constant after a code change but it should be highlighted for the release manager.

For operator Argmin, Argmax, the constant let the runtime knows in advance which dimension is the output.  I don't know the implication on the optimizers.

**Comment by gramalingam** [comment]
I agree with Xavier: changing all the ops in one-shot could have a significant impact (on frontends generating onnx, as well as backends consuming onnx). Conceptually it is a simple change, but that doesn't mean that the software-impact is trivial. It's something that could be attempted on something like a transition to ONNX 2.0.

I think we may need to do it in small steps. Eg., for all new ops added, we could use axis as input. For existing ops, we could target high-priority ops first, if it is manageable number.

**Comment by justinchuby** [comment]
SG. Feel free to close if we feel there's a consensus.

**Comment by gramalingam** [comment]
Let me clarify. It depends on how many ops exist. If it is a small number, it can probably be done in one shot.
