### ISSUE TITLE
When converting PyTorch code 'a[:, i] = temp' to ONNX and designating the first dimension as a dynamic batch size, a concatenation operation is generated that features an empty tensor input.

### ISSUE THREAD

**Issue by smartbarbarian** [onnx/onnx#4994]
# Bug Report

### Is the issue related to model conversion?
Yes. I converted a pytorch model to the onnx format.

### Describe the bug
When converting PyTorch code 'a[:, i] = temp' to ONNX and designating the first dimension as a dynamic batch size, a concatenation operation is generated that features an empty tensor input.

### Reproduction instructions
b shape: (1, 1, 256)
a shape: (batch_size, 64, 256)
a[:,0:1,:] = a[:,0:1,:] + b

dynamic_axes = {name: {0: 'batch_size'} for name in input_names + output_names}
torch.onnx.export(torch_model.module, (input_dict, {}), onnx_path, verbose=True, \
                        input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes)

### Expected behavior

type
Concat
name
Concat_1958

axis
0
inputs
name: onnx::Shape_2499
type: int64[3]
name: 2489
category: Initializer
type: int64[0]
Tensor data is empty.
concat_result
name: onnx::Reshape_2533
type: int64[3]

**Comment by jcwchen** [comment]
Hi @smartbarbarian,
It seems something wrong while converting PyTorch graph to ONNX model? If so, please raise an issue in PyTorch repo and mention ONNX in the title to get better help from the converter team. Thanks.
