### ISSUE TITLE
[Feature request] Support text proto

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#4995]
### What is the problem that this feature solves?

Models exported can be stored as text proto for readability. 

cc @jcwchen 

### Are you willing to contribute it (Y/N)

Yes

**Comment by jcwchen** [comment]
Hi @justinchuby,

> This is especially true for the reference test models in this repo. Otherwise they are not verifiable in code reviews.

I am not sure whether I understand it correctly -- Are you saying to make existing .onnx file in this repo as a text format? Do you have a concrete example to demo this proposal?

**Comment by justinchuby** [comment]
Yes. The spec is https://protobuf.dev/reference/protobuf/textformat-spec/. For example:

https://github.com/onnx/onnx/blob/main/onnx/backend/test/data/simple/test_expand_shape_model1/model.onnx

becomes

```pbtxt
ir_version: 4
producer_name: "backend-test"
graph {
  node {
    input: "X"
    input: "shape"
    output: "Y"
    name: "test"
    op_type: "Expand"
  }
  name: "Expand"
  input {
    name: "X"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "shape"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  output {
    name: "Y"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 9
}
```

Which is really just what we see when we print the proto. It can be stored as `pbtxt` or the `onnx` format and it would be compatible with our current load_model apis (I think) and netron. The code to do this is

```python
import google.protobuf.text_format

model = onnx.load_model("model.onnx")

with open("text_model.pbtxt", "w") as f:
    f.write(google.protobuf.text_format.MessageToString(model))
```

**Comment by cbourjau** [comment]
Having a large number of binary files in the repository is certainly not nice for UX and git's performance. Using a text format definitly improves that situation ❤️ . I do wonder what the primary goal of this change is, though. Is it to remove binary blobs from the repository while maintaining compatibility with netron? In that case it makes perfect sense to use protobufs text representation. And/or is it so that humans can quickly read and potentially modify a model in text format. For the latter, I think tha protobuf's text format is not quite delivering because of its verbosity. Might it be reasonable to use ONNX's own [grammar](https://github.com/onnx/onnx/blob/main/docs/Syntax.md#the-api) instead? It might be more fitting for humans?

**Comment by justinchuby** [comment]
> Having a large number of binary files in the repository is certainly not nice for UX and git's performance. Using a text format definitly improves that situation ❤️ . I do wonder what the primary goal of this change is, though. Is it to remove binary blobs from the repository while maintaining compatibility with netron? In that case it makes perfect sense to use protobufs text representation. And/or is it so that humans can quickly read and potentially modify a model in text format. For the latter, I think tha protobuf's text format is not quite delivering because of its verbosity. Might it be reasonable to use ONNX's own [grammar](https://github.com/onnx/onnx/blob/main/docs/Syntax.md#the-api) instead? It might be more fitting for humans?

Yes! It’s more for the former, better engineering and code reviews while maintaining compatibility
