### ISSUE TITLE
When will ncnn be supported?

### ISSUE THREAD

**Issue by nihui** [onnx/onnx#5]
hi
ncnn is an inference framework optimized for mobile platform, and is suitable to be implemented as onnx backend I think.
So when will ncnn be supported ?
Are there any documents on how to implement a backend?
[http://github.com/tencent/ncnn](http://github.com/tencent/ncnn)

**Comment by bddppq** [comment]
PR is welcome :-)

There is a base class `Backend` which has defined the common interface a backend should implement: https://github.com/onnx/onnx/blob/master/onnx/backend/base.py#L48.
For reference, here is caffe2's backend implementation: https://github.com/onnx/onnx-caffe2/blob/master/onnx_caffe2/backend.py#L121.

**Comment by ezyang** [comment]
Just to add, we're definitely open to making API adjustments and refactoring to help support backends. So if you are interested in doing this, give us a shout!

**Comment by zhujie1967** [comment]
This is a fantastic cutting edge AI framework for mobile application development, However, there is not enough docs for hobbyists' reference, If anybody had a time to roll out a reference book, I'd love to provide an assistance,

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/214
;)

**Comment by nihui** [comment]
status update
https://github.com/Tencent/ncnn/tree/master/tools/onnx

what have done
parse onnx graph topology
export ncnn graph topology
dump model weights

todo
convert more op
resolve potential compability issues
test squeezenet
test some other models ...

**Comment by nihui** [comment]
status update
squeezenet and inception_v1 model now can be converted properly  😆

**Comment by prasanthpul** [comment]
@nihui is ONNX officially supported by NCNN now? if so, we can list it on Supported Tools page of onnx.ai

**Comment by nihui** [comment]
@prasanthpul  yes. you may find ncnn icon here https://github.com/Tencent/ncnn/tree/master/images

**Comment by prasanthpul** [comment]
Closing this issue as ncnn is now supporting ONNX
