### ISSUE TITLE
Is there any plans to Consider Predictive Model Markup Language (PMML) ?

### ISSUE THREAD

**Issue by alhabshi3k** [onnx/onnx#50]
Hi everyone, 

Though this project is a start up , the Idea of having a Standard Exchange format for Deep learning model was one of my interest, since majority similar Concepts and Layers.

Here I will share my two cents of what know and what  I think it should be considered , or at least as references:
- [Predictive Model Markup Language (PMML) ](https://en.wikipedia.org/wiki/Predictive_Model_Markup_Language) is an XML-based predictive model interchange format. it provide a way for analytic applications to describe and exchange predictive models produced by data mining and machine learning algorithms, as well neural networks. Other details , you can refer to Wikipedia.
- There are [many GitHub Repositories (142 til this post date)](https://github.com/search?q=PMML) that use it as exchange format between different programming platforms (Python/ Numpy , R , Julia , DL4J, etc...) as well between High-level and low-level frameworks.

- Here are some repositories to consider : 
  - [keras2pmml](https://github.com/vaclavcadek/keras2pmml) Simple PMML exporter for Keras Deep Learning models.
  - [TensorFlowPMML](https://github.com/yogeshhk/TensorFlowPMML) takes a PMML, build and runs tensorflow model.
  -  [jpmml-tensorflow](https://github.com/jpmml/jpmml-tensorflow) converting TensorFlow models to PMML .
 
These is what i can share , excluding other machine learning frameworks such Spark, flink , weka and scikit-learn. I hope these will give you some new thoughts.

Take care and cheers,

**Comment by ezyang** [comment]
Hi @alhabshi3k; it would definitely be interesting if there were a converter between ONNX and PMML, but we ourselves are not currently planning to implement one.

**Comment by schlichtanders** [comment]
Just to add for completeness. Despite not that wide spread, pmml has a successor called Portable Format for Analytics (PFA) http://dmg.org/pfa/index.html

Converters between these model representations would be very useful tools.

**Comment by olegb94** [comment]
Neural networks part is pretty outdated in PMML. In it's current form it can't have any layer but FC. The amount of code it takes to save small network is huge. Take a look how weights of one neuron are presented in PMML:

```
<Neuron id="12">
          <Con from="0" weight="0.904057"/>  
          <Con from="1" weight="1.75084"/>
          <Con from="2" weight="2.51658"/>
          <Con from="3" weight="-0.151895"/>
          <Con from="4" weight="-2.88008"/>
          <Con from="5" weight="0.920063"/>
          <Con from="6" weight="-3.30742"/>
          <Con from="7" weight="-1.72251"/>
          <Con from="8" weight="-1.13156"/>
          <Con from="9" weight="-0.758563"/>
</Neuron>
```
All the NN converters to PMML that exist are able to convert very small subset of networks. And there are almost no converters back from PMML format.
Having all these I don't believe that it is a good candidate for support.
But if ONNX will move towards support of non-neural network models then PMML is worth considering.

**Comment by prasanthpul** [comment]
ONNX actually supports non-DNN since it started thanks to the ONNX-ML profile. Currently we have converters from SciKitLearn and XGBoost to ONNX-ML. If there is value in a PMML to ONNX-ML converter, we'd be happy to accept such a contribution.
