### ISSUE TITLE
[Strategy] NLP strategy

### ISSUE THREAD

**Issue by jamesr66a** [onnx/onnx#501]
Hi folks,

We've released a wiki page about our general strategy for NLP in ONNX: https://github.com/onnx/onnx/wiki/NLP-in-ONNX:-A-Strategy-Proposal

This issue is a place to foster discussion about the strategy

**Comment by RanACohen** [comment]
In your article it seems like you move between High Level primitives (LSTM, GRU) and low level control flow.
I propose in the middle to define as a Tensor-Iterator layer which can execute a sub-network in an iterative fashion a good trade-off between high enough to be optimized and yet low enough to reflect any recurrent pattern?

(If I am not mistaken caffe2 has this as a RecurrentNetwork layer)

**Comment by gramalingam** [comment]
Yes, that's worth considering: see [https://github.com/onnx/onnx/issues/502](https://github.com/onnx/onnx/issues/502) for a related discussion

**Comment by prasanthpul** [comment]
I believe control flow has already address the proposal. Please open a new issue if there are any outstanding gaps
