### ISSUE TITLE
Bounding Boxes pruning (postprocess) directly on ort_sess.run

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [onnx/onnx#5015]
ort_sess.run() return all the candidates bounding boxes in an image. Why isn't there a parameter 'bbox_conf' to directly remove all the bounding boxes that have a confidence inferior at bbox_conf ? 

It seems weird to return a 10 000 item long list to directly post process it, wouldn't it be faster to directly prune it and return a smaller list ?

**Comment by justinchuby** [comment]
This would be a good issue for the microsoft/onnxruntime developers.
