### ISSUE TITLE
Unsupported type of tensor: float Error from operator: 

### ISSUE THREAD

**Issue by YZHANGFPE** [onnx/onnx#503]
I encountered this error when I converted the pytorch model to caffe2. I am attaching the python notebook output.

```python
import torch
from torch.autograd import Variable
import linear

import io
import numpy as np

from torch import nn
from torch.autograd import Variable
import torch.utils.model_zoo as model_zoo
import torch.onnx

import onnx
import onnx_caffe2.backend

# Some standard imports
from caffe2.proto import caffe2_pb2
from caffe2.python import core, net_drawer, net_printer, visualize, workspace, utils

import os
import subprocess
```

```python
model = linear.linear
model.load_state_dict(torch.load('linear.pth'))
model.train(False)
print(model)
```

    Sequential(
      (0): LambdaMap2(
        (0): Sequential(
          (0): Sequential(
            (0): Lambda(
            )
            (1): Embedding(10, 5, padding_idx=0)
          )
          (1): ReLU()
        )
        (1): Sequential(
          (0): Sequential(
            (0): Lambda(
            )
            (1): Embedding(10, 9, padding_idx=0)
          )
          (1): ReLU()
        )
      )
    )

```python
input1 = Variable(torch.LongTensor([1]))
input2 = Variable(torch.LongTensor([2]))
output = model([input1,input2])
print("PyTorch Output")
print(output)
```

    PyTorch Output
    [Variable containing:
    (0 ,.,.) = 
      0.0000  0.1415  1.1059  1.5150  0.1604
    [torch.FloatTensor of size 1x1x5]
    , Variable containing:
    (0 ,.,.) = 
      0.0000  0.0000  0.0820  2.0639  0.2497  0.0529  0.0000  0.0000  0.0000
    [torch.FloatTensor of size 1x1x9]
    ]

```python
torch_out = torch.onnx._export(model,             # model being run
                               [input1, input2],                       # model input (or a tuple for multiple inputs)
                               "linear.onnx", # where to save the model (can be a file or file-like object)
                               export_params=True)      # s
print("Onnx Output")
print(torch_out)
```

    Onnx Output
    [Variable containing:
    (0 ,.,.) = 
      0.0000  0.1415  1.1059  1.5150  0.1604
    [torch.FloatTensor of size 1x1x5]
    , Variable containing:
    (0 ,.,.) = 
      0.0000  0.0000  0.0820  2.0639  0.2497  0.0529  0.0000  0.0000  0.0000
    [torch.FloatTensor of size 1x1x9]
    ]

```python
model = onnx.load("linear.onnx")
prepared_backend = onnx_caffe2.backend.prepare(model)
c2_workspace = prepared_backend.workspace
c2_net_def = prepared_backend.predict_net

# Now import the caffe2 mobile exporter
from caffe2.python.predictor import mobile_exporter

# TODO: remove two lines below - my caffe2 is not up-to-date and there was fix pushed for exporter
from caffe2.python import core
cnet = core.Net(c2_net_def)

# call the Export to get the predict_net, init_net. These nets are needed for running things on mobile
init_net, predict_net = mobile_exporter.Export(c2_workspace, cnet, c2_net_def.external_input)

print(net_printer.to_string(predict_net))
```

    torch-jit-export = core.Net('torch-jit-export')
    torch-jit-export.Reshape(['1'], ['5', 'OC2_DUMMY_0'], shape=[1, -1])
    torch-jit-export.Gather(['3', '5'], ['6'])
    torch-jit-export.Relu(['6'], ['7'])
    torch-jit-export.Reshape(['2'], ['8', 'OC2_DUMMY_1'], shape=[1, -1])
    torch-jit-export.Gather(['4', '8'], ['9'])
    torch-jit-export.Relu(['9'], ['10'])

```python
workspace.RunNetOnce(init_net)
workspace.RunNetOnce(predict_net)
```

    Traceback for operator 1 in network torch-jit-export

    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    <ipython-input-9-6c6a1f41b6bc> in <module>()
          1 workspace.RunNetOnce(init_net)
    ----> 2 workspace.RunNetOnce(predict_net)
    

    ~/anaconda3/lib/python3.6/site-packages/caffe2/python/workspace.py in RunNetOnce(net)
        204         C.Workspace.current._last_failed_op_net_position,
        205         GetNetName(net),
    --> 206         StringifyProto(net),
        207     )
        208 

    ~/anaconda3/lib/python3.6/site-packages/caffe2/python/workspace.py in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
        187 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
        188     try:
    --> 189         return func(*args, **kwargs)
        190     except Exception:
        191         op_id = op_id_fetcher()

    RuntimeError: [enforce fail at operator.h:640] . Unsupported type of tensor: float Error from operator: 
    input: "3" input: "5" output: "6" name: "" type: "Gather" device_option { device_type: 0 cuda_gpu_id: 0 }

**Comment by prasanthpul** [comment]
Both ONNX and PyTorch have changed quite a bit since this issue was opened. Can you reopen with latest details if it is still an issue?

**Comment by shbnm21** [comment]
I am also getting an error when converting onnx model to caffe2
error is in concat operator of caffe2
here is error

Original python traceback for operator `0` in network `torch-jit-export_predict` in exception above (most recent call last):
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-7ed754674748> in <module>()
     25 
     26 # Run the Caffe2 net:
---> 27 c2_out = prepared_backend.run(W)[0]
     28 
     29 # Verify the numerical correctness upto 3 decimal places

3 frames
/usr/local/lib/python3.6/dist-packages/caffe2/python/workspace.py in CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs)
    209 def CallWithExceptionIntercept(func, op_id_fetcher, net_name, *args, **kwargs):
    210     try:
--> 211         return func(*args, **kwargs)
    212     except Exception:
    213         op_id = op_id_fetcher()

RuntimeError: [enforce fail at concat_split_op.h:289] dim == dim_j. Expect dimension = 32 got 1 at axis = 0 for input: 1. The input tensors can only have different dimensions when arg 'add_axis' = 0 and along the axis = 1 <[32, 3, 256, 256]> vs <[1, 512, 8, 8]>.
Error from operator: 
input: "0" input: "1" output: "24" output: "OC2_DUMMY_0" name: "" type: "Concat" arg { name: "axis" i: 1 } device_option { device_type: 0 device_id: 0 }frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f9cb682c441 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
