### ISSUE TITLE
PROTOBUF_LIBDIR in setup.py

### ISSUE THREAD

**Issue by Kindpire** [onnx/onnx#504]
110 libs.append(os.path.join(os.getenv('PROTOBUF_LIBDIR'), "libprotobuf")) should be protobuf?
e.g. if we set PROTOBUF_LIBDIR to be /usr/local/lib, it would yield a warning: 
**no library file corresponding to '/usr/local/lib/libprotobuf' found (skipping)**
after change to protobuf, everything works fine.

**Comment by yinghai** [comment]
Hmm, I see.

**Comment by prasanthpul** [comment]
Please reopen if the linked PR did not address the issue
