### ISSUE TITLE
Error when converting CondensenNet from PyTorch to Caffe2 using ONNX

### ISSUE THREAD

**Issue by newstzpz** [onnx/onnx#505]
I am trying to convert a CondenseNet from PyTorch to caffe2 using ONNX, but I got the following error when I called the torch.onnx._export()

> RuntimeError: ONNX export failed: Couldn't export Python operator Scatter

The condensenet implementation is based on the code [here](https://github.com/ShichenLiu/CondenseNet). Some more related output:

>  %476 : Float(1000)) {
>   %478 : Float(1, 3, 224, 224), %479 : Handle = ^Scatter([0, 1, 2, 3, 4, 5, 6, 7], None, 0)(%1), uses = [[%704.i0], []];
>   %481 : Float(16, 3, 3, 3),

Any suggestions? Thanks!

**Comment by houseroad** [comment]
Looks like, in this case, we need Scatter, @dzhulgakov, @ebarsoum, shall we introduce it as an experimental operator?

**Comment by newstzpz** [comment]
In addition to Scatter, maybe Broadcast and Gather will also be needed, they are all used in condensenet.

**Comment by houseroad** [comment]
@newstzpz we have Gather in ONNX. Expand op is also a candidate to introduce.

**Comment by newstzpz** [comment]
@houseroad Is there any plan or ETA on supporting those operators (Scatter, Expand)?

**Comment by houseroad** [comment]
@newstzpz do we still have problem on exporting?

**Comment by newstzpz** [comment]
Thanks @lvdmaaten's help, we are good now.

**Comment by vd001** [comment]
@newstzpz How did you solve the problem finally?

**Comment by lvdmaaten** [comment]
It turned out that the model @newstzpz was trying to convert was still wrapped in a `nn.DataParallel` module. ONNX doesn't know how to deal with that module (it treats it as a scatter over GPUs).

Removing the `nn.DataParallel` wrapper before doing the ONNX export resolved the issue.

**Comment by younghe** [comment]
> Thanks @lvdmaaten's help, we are good now.

Could you tell me how to move nn.DataParallel? I am new in pytorch.

**Comment by lvdmaaten** [comment]
Simply export `model.module` using ONNX rather than `model` itself.

**Comment by uhvardhan** [comment]
Hi @lvdmaaten ,

I am facing a similar issue. Could you help me with the following? 

`import torch
from torch.autograd import Variable

# Load the trained model from file

path = "huawei_0000_4_4_6_98_160.pth"

pytorch_network = torch.load(path)

pytorch_network.state_dict()

# Export the trained model to ONNX
#pytorch_network = torch.nn.DataParallel(pytorch_network, device_ids=range(torch.cuda.device_count()))
dummy_input = Variable(torch.randn(1, 3, 224, 224))
torch.onnx.export(pytorch_network, dummy_input, "model.onnx")`

I get the same error as the above issue.

Thanks in advance.

**Comment by nipeone** [comment]
@uhvardhan i had got the similar error,you correct "torch.onnx.export(pytorch_network.module, dummy_input, "model.onnx")" to "torch.onnx.export(pytorch_network.module.cuda(), dummy_input, "model.onnx")" can solve this problem
