### ISSUE TITLE
[Question] Support dynamic onnx can be converted to TensorRT

### ISSUE THREAD

**Issue by phamkhactu** [onnx/onnx#5054]
Thanks for excellence repo.

I have successfully converted model to onnx with dynamic batch_size:
```
model_path = f"weights/qat_enn_space_not_fintune_85_int8.onnx"

dummy_input = torch.randn(1, 3, 32, 128)
dynamic_axes= {'input':[0,2,3],
               'output':[0]}

torch.onnx.export(model, dummy_input, model_path, verbose=True, input_names=['input'], 
                  output_names=['output'], opset_version=14, dynamic_axes=dynamic_axes)
```
![image](https://user-images.githubusercontent.com/42369268/228163267-abe2736c-03b2-4d74-bd2d-638bf30dc357.png)

But I encounter problem when convert to Tensorrt, tensorrt can not understand **input_dynamic_axes_1** as above I converted.
If dynamic model input must follow: X(input).shape = [-1,3,-1,-1], Tenssort can convert
I am very happy if you can give me some guide or give me tutorial link for creating dynamic input onnx and convert to Tensorrt
Thank you very much.

**Comment by jcwchen** [comment]
Hi @phamkhactu,
I thought onnx-tensorrt does support dynamic input, but I could be wrong. Are you using the latest [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt)? If yes, please raise this issue there to get the better help from the converter experts. Thanks.

**Comment by phamkhactu** [comment]
@jcwchen Thank you
