### ISSUE TITLE
Backend test `test_optional_get_element_tensor` produces an invalid graph

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5067]
# Bug Report

### Is the issue related to model conversion?

No

### Describe the bug

The graph does not have output type, which is invalid.

https://github.com/onnx/onnx/blob/7fb3d4c2a942cf464e1b5f5df8edd9ab57208369/onnx/backend/test/case/node/optionalgetelement.py#L21-L48

### Reproduction instructions
<!--
- Describe the code to reproduce the behavior.
```
import onnx
import onnxruntime as ort
import numpy as np

input = """
    <
        ir_version: 8,
        opset_import: ["" : 18]
    >
    node_graph (float[4] input0) => (output0) {
        output0 = OptionalGetElement (input0)
    }
"""

model = onnx.parser.parse_model(input)

# model = onnx.shape_inference.infer_shapes(model)
onnx.checker.check_model(model)
```

yields

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/justinchu/anaconda3/envs/onnx/lib/python3.10/site-packages/onnx/checker.py", line 134, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'type' of 'value_info' is required but missing.
```

### Expected behavior

The backend test should be a valid graph

**Comment by jcwchen** [comment]
test_optional_get_element_tensor/model.onnx:
![image](https://user-images.githubusercontent.com/14194980/228966543-4cfd8bdb-a0e5-4581-8e06-d0a6834cf7df.png)

> The graph does not have output type, which is invalid.

I thought the output type is there. Could you please elaborate the issue? Thanks.

**Comment by justinchuby** [comment]
OK. Maybe the bug was in ONNX script
