### ISSUE TITLE
Handle ReduceMean-18 from onnx 1.13 in check_model

### ISSUE THREAD

**Issue by fanny-riols** [onnx/onnx#5076]
# Bug Report

### Describe the bug

After upgrading onnx 1.11 to 1.13, the ReduceMean operator implementation changed the `axes` from being an attribute to an input. However, when checking the model using `onnx.checker.check_graph`, I get this error:
```
onnx.onnx_cpp2py_export.checker.ValidationError: Node (n_mean) has input size 2 not in range [min=1, max=1].
```

### System information
- Python version: 3.9
- ONNX version: 1.13.0 or 1.13.1

### Reproduction instructions

```
x_input = helper.make_tensor_value_info("x_input", TensorProto.FLOAT, [1, 5])
y_output = helper.make_tensor_value_info("y_output", TensorProto.FLOAT, [2, 5])
t_axes = onnx.helper.make_tensor("t_axes", TensorProto.INT64, [1], [0])
n_mean = helper.make_node("ReduceMean", inputs=["x_input", "t_axes"], outputs=["y_output"])
graph = helper.make_graph(nodes=[n_mean], inputs=[x_input], outputs=[y_output], initializer=[t_axes], name="g_test")

op = onnx.OperatorSetIdProto()
op.version = 16
model = onnx.helper.make_model(graph, opset_imports=[op])
onnx.checker.check_model(model, full_check=True)
```
Outputs:
```
File "onnx/checker.py", line 119, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 2 not in range [min=1, max=1].
```

### Expected behavior

The check should work.

**Comment by jbachurski** [comment]
Operator schemas are not dependent on the version of the ONNX package, but the opset version. By setting `op.version = 16`, you are requesting version 16, and not 18 (which is when [ReduceMean-18](https://onnx.ai/onnx/operators/onnx__ReduceMean.html#l-onnx-op-reducemean-18) gets used). Instead this resolves to [ReduceMean-13](https://onnx.ai/onnx/operators/onnx__ReduceMean.html#l-onnx-op-reducemean-13) (as ReduceMean has versions 18, 13, 11, 1), which has exactly one input, as specified by the error.
The solution is to actually specify `op.version = 18`.

Besides that, you specify the type of `x_input` to be `[1, 5]` and `y_output` to be `[2, 5]`. You probably want these to be the other way around, as you want the axis of size `2` to reduce into the `1`.

As a general comment you should probably use `onnx.helper.make_opsetid(domain, version)` to construct a `OperatorSetIdProto`.

**Comment by fanny-riols** [comment]
@jbachurski , the issue with opset version 18 is that pytorch doesn't support opset version 18, so I'm having the following error when trying to export my onnx model later on using `torch.onnx.export`:
```
torch/onnx/_globals.py:74: ValueError: Unsupported ONNX opset version: 18
```

**Comment by jbachurski** [comment]
> But shouldn't we be able to use opset version 16 with onnx 1.13 which is by default taking ReduceMean-18? Or, could I specify somehow that ReduceMean-13 should be used?

ONNX itself should never assume a version by default, as models are always explicitly versioned. You can check the version that a given ONNX model is using by checking the `onnx.ModelProto.opset_import` list, which looks something like this:

```py
opset_import {
  domain: ""
  version: 14
}
```
Which would indicate it's using opset version 14. You could try checking what if the version you're using with PyTorch isn't somehow getting set to 18.

> the issue with opset version 18 is that pytorch doesn't support opset version 18, so I'm having the following error when trying to export my onnx model later on using `torch.onnx.export`:

In that case the example you gave doesn't seem to reflect the issue you're actually having. Did you consider raising an issue with PyTorch / `torch.onnx`? How is the `ReduceMean` operator constructed in the first place with 2 inputs rather than 1, as it should be before version `18`?

**Comment by fanny-riols** [comment]
@jbachurski , yes I am considering raising an issue with PyTorch.

ReduceMean-13:
```
n_mean = helper.make_node(
        "ReduceMean",
        inputs=["y_attributions_slice"],
        outputs=["y_average_attributions"],
        name="n_mean_attributions",
        axes=[0],
    )
```

ReduceMean-18:
```
n_mean = helper.make_node(
        "ReduceMean",
        inputs=["y_attributions_slice", "t_axes"],
        outputs=["y_average_attributions"],
        name="n_mean_attributions",
    )
```

However, when I set opset version to 16 (or something below 18), onnx 1.13, and the `axes=[0]` as an attribute (so for ReduceMean-13), I am getting this error:
```
onnx/checker.py:57: ValidationError: Unrecognized attribute: axes for operator ReduceMean
```

Maybe this is what needs to be fixed?

**Comment by jbachurski** [comment]
The following seems to work for me:

```py
import onnx

x_input = onnx.helper.make_tensor_value_info("x_input", onnx.TensorProto.FLOAT, [2, 5])
y_output = onnx.helper.make_tensor_value_info("y_output", onnx.TensorProto.FLOAT, [1, 5])
n_mean = onnx.helper.make_node("ReduceMean", inputs=["x_input"], outputs=["y_output"], axes=[0])
graph = onnx.helper.make_graph(nodes=[n_mean], inputs=[x_input], outputs=[y_output], name="g_test")

op = onnx.OperatorSetIdProto()
op.version = 16  # Notice ReduceMean-13 is selected, as ReduceMean-18 is at 18 (newer than 16)
model = onnx.helper.make_model(graph, opset_imports=[op])
onnx.checker.check_model(model, full_check=True)
```

I think you'd have to provide the rest of the code, as in a minimal example everything seems to work fine. How are you differentiating `ReduceMean-13` or `ReduceMean-18`? Is this expressed somehow through the PyTorch ONNX converter? Unfortunately, I'm not really familiar with it, but it seems like the issue is with it.

**Comment by fanny-riols** [comment]
Hi, I am not able to have a simple example to reproduce this issue. So it might be some conflicts with my different libraries' versions. I'll spend more time on this, but close this ticket for now.

Thank you @jbachurski .
