### ISSUE TITLE
[Performance] GPU memory usage increased and overflowed.

### ISSUE THREAD

**Issue by masashi4359** [onnx/onnx#5107]
### Question
We are running 3 image detection models and 1 image recognition model with onnx runtime as gstreamer plugin in docker container.
And we are running 4 containers in one PC.

One of the detection models has a variable image size, and various sizes of images are input.
The batch size of the recognition model is variable and various sizes are input.

Measured over time, the results are shown in the image below, and GPU memory overflowed. The containers dropped one by one in the red circled area, and only the last one survived.

In another experiment, when the detection model with variable image size was changed to fixed and the batch size of the recognition model was fixed, GPU memory remained constant at 12 GB.

It seems that variable image size and variable batch size are the cause of memory overflow, is there any countermeasure?
![gpu_memory_230406_1](https://user-images.githubusercontent.com/103468642/230852418-4337730a-be94-4a71-9846-c53b06210e3d.jpg)

### Further information
- Relevant Area: 
  - Ubuntu 20.04
  - gstreamer 1.22.1
  - onnx runtime 1.13.1
  - CPU: Core(TM) i7-10700  2.9GHz
  - CPU Memory: 32GB
  - GPU: RTX3090

**Comment by jcwchen** [comment]
Hi @masashi4359,
This performance issue seems more related to onnxruntime-gpu. Please raise issue in https://github.com/microsoft/onnxruntime/issues to get better help from runtime experts there. Thanks!

**Comment by masashi4359** [comment]
Sorry for the delay in replying. Thank you, @jcwchen 
I referred to the following issue and the problem was solved.
This issue is closed.
https://github.com/microsoft/onnxruntime/issues/9509#issuecomment-951546580
