### ISSUE TITLE
Determine if a NodeProto.input is a constant or a graph input 

### ISSUE THREAD

**Issue by MrGeva** [onnx/onnx#511]
Is there a way to determine if a NodeProto input is a constant (e.g. weights, biases) or a graph input (e.g. image)?
It seems that in both cases they may appear in the model in GraphProto.input and in GraphProto.initializer, so I can't distinguish between them.

**Comment by bddppq** [comment]
initializers are all weights. GraphProto.input includes both weights and graph input, so it’s a super set of initilaizers. Technically initializers are list of TensorProto (which has the values), while GraphProto.input is a list of ValueInfoProto, which only has the type & shape information.

**Comment by MrGeva** [comment]
The documentation in onnx.proto is somewhat misleading because the comment above GraphProto.initializer implies inputs to the graph can be initialized with default values:

> // A list of named tensor values (constants), used to specify default
  // values for some of the inputs of the graph...
  repeated TensorProto initializer = 5;
