### ISSUE TITLE
Exporting the operator ::diag to ONNX opset version 12 is not supported.

### ISSUE THREAD

**Issue by DSP3460** [onnx/onnx#5115]
#

**Comment by wschin** [comment]
Please try a newer opset such as 17. Earlier opset usually has lower coverage.

**Comment by wschin** [comment]
Feel free to reopen if you hit problem. Thanks.

**Comment by DSP3460** [comment]
I hava changed the opset_version=17, but the problem still exist.
**ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported**.
I use diag in my project, but optset13 define diagonal, maybe this have an impact？

**Comment by DSP3460** [comment]
> I hava changed the opset_version=17, but the problem still exist. **ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported**. I use diag in my project, but optset13 define diagonal, maybe this have an impact？


I hava changed the opset_version=17, but the problem still exist.
ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported.
I use diag in my project, but optset13 define diagonal, maybe this have an impact？

**Comment by Bob-X** [comment]
I hava changed the opset_version=17, but the problem still exist.

**Comment by Bob-X** [comment]
ONNX: export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
