### ISSUE TITLE
Why the input of CategoryMapper op must be a tensor of strings or integers, either [N,C] or [C] ?

### ISSUE THREAD

**Issue by negiyas** [onnx/onnx#5118]
# Ask a Question
Why the input of CategoryMapper op must be a tensor of strings or integers, either [N,C] or [C] ?

### Question

According to the onnx.ml.CategoryMapper definition at https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#ai.onnx.ml.CategoryMapper, the input must be a tensor of strings or integers, either [N,C] or [C] (the rank must be one or two).
On the other hand, the bidaf model at https://github.com/onnx/models/tree/main/text/machine_comprehension/bidirectional_attention_flow includes, CategoryMapper op with rank-4 input,.

Accordingly the CategoryMapper operation definition and the bidaf model are inconsistent. Because the ai.onnx.ml.CategoryMapper op is a simple string-to-integer (or integer-to-string) mapper, any input shape can be supported naturally. I am not sure if the operation definition is too strict or the model definition is not very good.

My question is onnx-related software (e.g. [onnx-mlir compiler](https://github.com/onnx/onnx-mlir) or [onnxruntime](https://github.com/microsoft/onnxruntime)) should support rank-4 input of CategoryMapper op or not.

### Further information

**CategoryMapper op definition**
```
ai.onnx.ml.CategoryMapper
Converts strings to integers and vice versa.
...
Inputs
X : T1
    Input data
Outputs
Y : T2
    Output data. If strings are input, the output values are integers, and vice versa.

Type Constraints
T1 : tensor(string), tensor(int64)
    The input must be a tensor of strings or integers, either [N,C] or [C].
T2 : tensor(string), tensor(int64)
    The output is a tensor of strings or integers. Its shape will be the same as the input shape.  
```

**CategeoryMapper in Bidaf**
![image](https://user-images.githubusercontent.com/18544851/231332817-149f0f45-e7cd-47ae-9097-adfa3896110f.png)

**An related issue in onnx.model**
https://github.com/onnx/models/issues/601

**Comment by wschin** [comment]
My answer to `should support rank-4 input of CategoryMapper op or not` would be a `No`. mapping 4-D tensor can be done using
```
[c, 1, 1, 16] -> Reshape(shape=[c, 16]) -> [c, 16] -> CategoryMapper -> [c, 16] -> Reshape(shape=[c, 1, 1, 16]) -> [c, 1, 1, 16]
```

This examples means ONNX can compose the desired N-D `CategoryMapper` using `Reshape`, therefore, we don't need to change the definition of `CategoryMapper`.

**Comment by negiyas** [comment]
@wschin Thank you for useful comments.
I agree that we can manage this issue by fixing the model, and we can say this is an issue comes from the model.

We are thinking if onnx-mlir should support rank-3+ inputs for onnx.CategoryMapper or not, because we can support this case
by removing error checking lines simply.

**Comment by jbachurski** [comment]
My personal hunch says it should be more general, because as @negiyas says the implementation is the same. Avoiding an explicit reshape might be more efficient. Based on this [resource](https://github.com/onnx/onnx/blob/main/docs/AddNewOp.md#step-1-proposing-a-new-operatorfunction-) in the repo:

> The operator should not be made more complex than is required by the use-cases. However, the operator should be made as general as possible, as long as it does not make the implementation more complex. This requires carefully balancing generality and complexity. For example, generalizing from 3-D tensors to N-D tensors is straight-forward (implementation-wise) for some operators, but complex for other operators. The choice in such cases will be made based on the complexity of such a generalization.

This is also because there seems to be a producer creating such instances, it is consistent with ORT (there are more such 'practical' inconsistencies by the way), and explicit `Reshape`s on non-constant shapes might lead to losing shape information in the type if they are carried through improperly by a producer.

**Comment by negiyas** [comment]
@wschin  @jbachurski Thank you for useful suggestions and discussions.

Let me explain my personal feeling. I suppose that CategoryMapper is a kind of element-wise operation for mapping each string element to int element (or vise visa) according to the specified mapping table. Basically speaking element-wise operators allow inputs with any shapes, and generate outputs with the same shape, and there is no reason to limit the input shape.

> However, if there's cases where the implementation is trickier, it seems fair to keep it 2D as suggested.
At least "onnxruntime" already supports rank-4 inputs of CategoryMapper, and it can run bidaf model in the model zoo with no modification (I suppose that it supports any shapes of inputs), although I cannot say every implementation can support the cases naturally.
