### ISSUE TITLE
Can not locate ValueInfoProto class in onnx project with Clion

### ISSUE THREAD

**Issue by smilealvin92** [onnx/onnx#5121]
# Ask a Question

### Question
I download the whole project source code of ONNX from github, open it with clion, trying read the code, But I found the class of ValueInfoProto, TypeProto, TensorProto along with all other protos were marked red, which means clion can not locate the definition of this class. It's weird that the cmake check is fine. Clion depends on CMake to navigate the whole project. More pics below show the the infos. The question is: How can I locate the definition of classes of ALL PROTOS? The reason I read the onnx source code is the failure of compiling onnx-mlir project. I believe the failure comes from missing definitions of ALL PROTOS.

## below is the red marks made by clion.
![2023-04-13 10-29-36 的屏幕截图](https://user-images.githubusercontent.com/48876213/231632332-59fdca5f-549c-42bb-ada8-a22eff71adb0.png)

## below is the error report of compiling onnx-mlir,
 we notes that onnx::TensorShapeProto.Dimension was interpreted to onnx::TensorShapeProto_Dimension, which caused by absence of definitions of TensorShapeProto.

 error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<onnx::TensorShapeProto_Dimension>’ and ‘int’)
  174 |       if (shape_proto.dim()[i].dim_value()) {
 
It's reasonable to say this error come from onnx project.
I'd be very appreciated if any one can help me out of this error.

## below is the output of CMake of clion
Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread (found version "3.0.0") 
Generated: /home/alvin/shuju/private/work/onnx_src/onnx/cmake-build-debug/onnx/onnx-ml.proto
Generated: /home/alvin/shuju/private/work/onnx_src/onnx/cmake-build-debug/onnx/onnx-operators-ml.proto
Generated: /home/alvin/shuju/private/work/onnx_src/onnx/cmake-build-debug/onnx/onnx-data.proto

******** Summary ********
 CMake version             : 3.25.2
CMake command             : /snap/clion/234/bin/cmake/linux/x64/bin/cmake
System                    : Linux
C++ compiler              : /usr/bin/c++
C++ compiler version      : 10.3.0
CXX flags                 :  -Wnon-virtual-dtor
Build type                : Debug
Compile definitions       : __STDC_FORMAT_MACROS
CMAKE_PREFIX_PATH         : 
CMAKE_INSTALL_PREFIX      : /usr/local
CMAKE_MODULE_PATH         : 

ONNX version              : 1.14.0
 ONNX NAMESPACE            : onnx
ONNX_USE_LITE_PROTO       : OFF
 USE_PROTOBUF_SHARED_LIBS  : OFF
  Protobuf_USE_STATIC_LIBS  : ON
  ONNX_DISABLE_EXCEPTIONS   : OFF
 ONNX_WERROR               : OFF
   ONNX_BUILD_TESTS          : OFF
   ONNX_BUILD_BENCHMARKS     : OFF

  Protobuf compiler         : /usr/bin/protoc
   Protobuf includes         : /usr/include
  Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
  BUILD_ONNX_PYTHON         : OFF
Configuring done
 Generating done
Build files have been written to: /home/alvin/shuju/private/work/onnx_src/onnx/cmake-build-debug

**Comment by justinchuby** [comment]
They proto headers should be generated. Did you try to build the project first?
