### ISSUE TITLE
ONNX model can do inference but shape_inference crashed

### ISSUE THREAD

**Issue by xiaowuhu** [onnx/onnx#5125]
# Bug Report

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*):
- ONNX version 1.14
- Python version: 3.10

### Reproduction instructions

```
import onnx
model = onnx.load('shape_inference_model_crash.onnx')
        try:
            onnx_model = onnx.shape_inference.infer_shapes(
                onnx_model, check_type=True, strict_mode=False, data_prop=True
            )
            onnx.checker.check_model(onnx_model, full_check=True)
        except (onnx.checker.ValidationError, onnx.shape_inference.InferenceError) as e:
            warnings.warn(f"ONNX model is invalid: {e}", stacklevel=1)
            logging.debug(
                "ONNX model:\n%s\n\nTorchScript graph:\n%s",
                onnxscript.proto2text(onnx_model),
                self.torch_graph,
            )
.
```

[shape_inference_model_crash.zip](https://github.com/onnx/onnx/files/11227972/shape_inference_model_crash.zip)

**Comment by jcwchen** [comment]
Hi @xiaowuhu,
I cannot repro it by onnx==1.13.1 and the latest onnx-weekly==1.14.0.dev20230410 with your script and model. Which line did you encounter crash?
