### ISSUE TITLE
Cast-19 table in onnx.ai docs is broken

### ISSUE THREAD

**Issue by take-cheeze** [onnx/onnx#5128]
# Bug Report

### Describe the bug

Tables in https://onnx.ai/onnx/operators/onnx__Cast.html#cast-19 is broken but markdown version in https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast is fine.

### Reproduction instructions

See https://onnx.ai/onnx/operators/onnx__Cast.html#cast-19

### Notes

I don't know why but markdown syntax and sphinx syntax seems to have some diff?

**Comment by jcwchen** [comment]
Hu @take-cheeze,
Thanks for catching this. Yes, markdown syntax and sphinx syntax are slightly different. For instance, https://github.com/onnx/onnx/issues/4725. cc @xadupre

**Comment by justinchuby** [comment]
I think we can use myst. We can update https://github.com/onnx/onnx/blob/main/docs/docsgen/source/onnx_sphinx.py to create markdown files.

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/pull/5137

**Comment by jcwchen** [comment]
It seems working now. Thanks @justinchuby for the improvement!

**Comment by take-cheeze** [comment]
Thank you! 🎉
