### ISSUE TITLE
Version converter: invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by hmy-meng** [onnx/onnx#5141]
# Bug Report
error:

Traceback (most recent call last):
  File "D:\yizhu_project\onnx_official\convert_opset.py", line 43, in <module>
    onnx_model = version_converter.convert_version(onnx_model, 15)
  File "C:\Users\hmy\anaconda3\lib\site-packages\onnx\version_converter.py", line 170, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
IndexError: invalid unordered_map<K, T> key

### System information
<!--
- torch version : 1.13.1
- ONNX version: 1.13.1
- Python version: 3.9

code: 

onnx_model = onnx.load(r"models/SSD300_coco.onnx")

onnx_model = version_converter.convert_version(onnx_model, 15)

**Comment by hmy-meng** [comment]
code:
onnx_model = onnx.load(r"models/SSD300_coco.onnx")
onnx_model = version_converter.convert_version(onnx_model, 15)

**Comment by justinchuby** [comment]
What’s the ONNX version you are using? Helpful if you can provide the model as well.

**Comment by justinchuby** [comment]
Marked for 1.16 triage
