### ISSUE TITLE
> I hava changed the opset_version=17, but the problem still exist. **ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported**. I use diag in my project, but optset13 define diagonal, maybe this have an impact？

### ISSUE THREAD

**Issue by DSP3460** [onnx/onnx#5142]
> I hava changed the opset_version=17, but the problem still exist. **ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported**. I use diag in my project, but optset13 define diagonal, maybe this have an impact？

I hava changed the opset_version=17, but the problem still exist.
ONNX export failure: Exporting the operator 'aten::diag' to ONNX opset version 17 is not supported.
I use diag in my project, but optset13 define diagonal, maybe this have an impact？

_Originally posted by @DSP3460 in https://github.com/onnx/onnx/issues/5115#issuecomment-1506608777_

**Comment by xadupre** [comment]
+ @justinchuby

**Comment by justinchuby** [comment]
We can add the op. Is there a good way to decompose diag?
