### ISSUE TITLE
About the coordinate_transformation_mode  formula

### ISSUE THREAD

**Issue by SmallBlackEgg** [onnx/onnx#5148]
# About the coordinate_transformation_mode  formula

### Further information
- Relevant Area: In the process of deriving ONNX coordinates, it was found that when the 23rd pixel of w was calculated according to the rules of half_pixel and round_prefer_floor: (23 + 0.5) / 1.02191 - 0.5= 22.49615426, at this time, 22 pixels should be taken after round down, but I see that the output of ONNX Runtime is taken 23 pixels, and I did not follow this round_ prefer_floor to round up.This example nchw is (1,38,38,38), scale[1,1,1,1.02191]

### How to reproduce
Increment the data from 0 to the shape size once, and the coordinate calculation error will occur in column 23 of row 0.
| index| ...|22|23|24|
|-|-|-|-|-|
|value|...|22|23(According to the formula( (23 + 0.5) / 1.02191 - 0.5= 22.49615426->**22**) it should be **22**)|24|

**Comment by xadupre** [comment]
Is it possible to know the value for the attributes of the operator Resize you defined and the input size as well?
