### ISSUE TITLE
Cannot parse strides attribute in LpPool

### ISSUE THREAD

**Issue by jikechao** [onnx/onnx#5150]
For the below onnx model with LpPool, we can see that `strides = 3,3` in LpPool. However, this model info is shown using the command `print(onnx.load('lppool_model.onnx'))` and it can't include the `strides` attribute. Meanwhile, if we use `model.graph.node[0].attribute` to check the attribute,  the `strides` attribute also missing.

### model structure
![image](https://user-images.githubusercontent.com/29506758/232844355-1d425875-59a7-4570-849f-584b8110a955.png)

### Steps to reproduce
1. download the [model](https://github.com/onnx/onnx/blob/main/onnx/backend/test/data/node/test_lppool_2d_strides/model.onnx)
2. run the following script:

```
import onnx

model = onnx.load('model.onnx')
print(model)
for node in model.graph.node:
    print(node.attribute)

```

@liqunfu @justinchuby, is it a bug of ONNX?

**Comment by xadupre** [comment]
I tried to load your model in netron and with the onnx package. I can't see any attribute `strides`. Is it the same model that you attached?

**Comment by jikechao** [comment]
@xadupre  Sorry for my mistake. You can access the model via this [link](https://github.com/onnx/onnx/blob/main/onnx/backend/test/data/node/test_lppool_2d_strides/model.onnx)

**Comment by jikechao** [comment]
I'm so sorry for wasting your expensive time on my mistake. I confused 2 different models. It's totally correct for onnx to parse the LpPool.
