### ISSUE TITLE
onnx.backend.test.case.collect_snippets executes test code

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#5154]
# Bug Report

### Describe the bug

`collect_snippets` used by [gen_doc.py](https://github.com/onnx/onnx/blob/0d1f14422cf8912e561bcb02d455917935ff3346/onnx/defs/gen_doc.py#L18) is executing test code causing side effects like #5139.

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): macOS M2
- ONNX version (*e.g. 1.13*): main
- Python version: 3.11

### Reproduction instructions

`collect_snippets` prints these warnings from running test code when run on macOS M2. 

```py
>>> import onnx.backend.test.case
>>> snippets = onnx.backend.test.case.collect_snippets()
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwiseand.py:41: RuntimeWarning: invalid value encountered in cast
  x = np.random.randn(3, 4, 5).astype(np.uint64)
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwiseand.py:42: RuntimeWarning: invalid value encountered in cast
  y = np.random.randn(5).astype(np.uint64)
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwiseor.py:40: RuntimeWarning: invalid value encountered in cast
  x = np.random.randn(3, 4, 5).astype(np.uint64)
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwiseor.py:41: RuntimeWarning: invalid value encountered in cast
  y = np.random.randn(5).astype(np.uint64)
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwisexor.py:41: RuntimeWarning: invalid value encountered in cast
  x = np.random.randn(3, 4, 5).astype(np.uint64)
/opt/homebrew/lib/python3.11/site-packages/onnx/backend/test/case/node/bitwisexor.py:42: RuntimeWarning: invalid value encountered in cast
  y = np.random.randn(5).astype(np.uint64)
```

### Notes

@jcwchen @askhade @stillmatic

**Comment by jcwchen** [comment]
Hi @lutzroeder,
I guess initially collect_snippets was implemented for running backend test code and creating input.pb/output.pb: https://github.com/onnx/onnx/pull/207 For other usage like gen_doc.py and stat_coverage.py, they just use the same same function to collect test cases and show the node test code in the documents.

Still, executing test code can sort of ensure the test code is runnable and correct, which will be shown in the documents for users. It seems harmless to keep the original behavior here?
