### ISSUE TITLE
[Tracking] Make ONNX be compatible with protobuf 22.x. 

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#5162]
### System information

Latest main branch

### What is the problem that this feature solves?

Make ONNX be compatible with protobuf 22.x. 

### Describe the feature

To make ONNX be compatible with protobuf 22.x, CMake file will need to updated. Details: https://github.com/onnx/onnx/pull/5120#issuecomment-1507589785

### Will this influence the current api (Y/N)?

N

### Feature Area

build

### Are you willing to contribute it (Y/N)

None

**Comment by guoyuhong** [comment]
@jcwchen I would like to take some of the tasks.
In my opinion, it would take several steps. For example, 
1. make both cmake compatible with both protobuf 21.x and 22.x.
2. change the CI system to use 22.x.
3. Bump the python dependency to 22.x.
4. etc.
I would like to take the first step.

**Comment by jcwchen** [comment]
@guoyuhong Thank you for the contribution! I think 3. (Bump the python dependency to 22.x.) won't happen in the near future since ONNX has just bumped its Protobuf version to 21. in the upcoming release, but definitely we can at least have 1. and 2. done first.
