### ISSUE TITLE
Does ONNX contain the operator that works like np.interp() function?

### ISSUE THREAD

**Issue by Jeremylee1234** [onnx/onnx#5165]
# Ask a Question

### Question
I'm working on transfering sklearn.QuantileTransformer to onnx model, but the issue is that QuantileTransformer used np.interp(), and I've checked the operators that onnx contain that resize operator seems works similarly to np.interp() function.  Does anyone has any thought about it?

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by justinchuby** [comment]
ONNX resize does interpolation. Is there any features missing for your need?

**Comment by Jeremylee1234** [comment]
np.interp() makes an one-dimensional linear interpolation for monotonically increasing sample points. But resize operator seems doens't do one-dimentional linear interpolation.

**Comment by Jeremylee1234** [comment]
> 

np.interp() makes an one-dimensional linear interpolation for monotonically increasing sample points. But resize operator seems doens't do one-dimentional linear interpolation.

**Comment by Jeremylee1234** [comment]
> ONNX resize does interpolation. Is there any features missing for your need?

np.interp() makes an one-dimensional linear interpolation for monotonically increasing sample points. But resize operator seems doens't do one-dimentional linear interpolation.

**Comment by xadupre** [comment]
Resize was meant for images but you could have an image (1x1x1xN) to have 4 dimensions. Coding interp is possible even though the PR implementing it (https://github.com/onnx/sklearn-onnx/pull/705) was left incomplete. I was thinking using TreeEnsembleClassifier to detect which segment a point belong to, compute all the linear approximations and use the first result to weight them.

**Comment by Jeremylee1234** [comment]
> Resize was meant for images but you could have an image (1x1x1xN) to have 4 dimensions. Coding interp is possible even though the PR implementing it ([onnx/sklearn-onnx#705](https://github.com/onnx/sklearn-onnx/pull/705)) was left incomplete. I was thinking using TreeEnsembleClassifier to detect which segment a point belong to, compute all the linear approximations and use the first result to weight them.

Will you continue implement the quantileTransformer converter? I'm currently working on it, and I'm trying to run digitize2tree(bins, right=False) to find the quantile segment that the input belongs to, but it turns out an error. Then, I checked the source code find it can be solved by using :epkg:`ONNX` which I'm not quite sure what's that mean..
![interp()](https://user-images.githubusercontent.com/42887249/234248854-0fa6c1ed-90e4-4a17-bf4a-43b86557e473.png)
