### ISSUE TITLE
What's the correct way of adding your custom_op in onnx and building it from source and using it with onnxruntime?

### ISSUE THREAD

**Issue by PKarhade** [onnx/onnx#5168]
# Ask a Question

Hi,
I want to use onnx to convert my TF graph. However, I've  an operation (which is a bunch of unfused operators in TF) in TF which I want to convert into a single operator in onnx. For this purpose, I've created custom_op on my local machine following most of the guidelines given in this link https://github.com/onnx/onnx/blob/main/docs/AddNewOp.md  and then build onnx from source. I am able to create a model (manually, not using tf2onnx) with this built onnx and now the problem occurs when I try running Python inference using ONNX-runtime. (I used onnx github version 1.13.1 for adding customop and for onnxruntime I directly pip installed the version 1.14.1)
 I get error like following (I've modified the name of the model and op for personal reasons)

onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ../../xyz.onnx failed:This is an invalid model. In Node, , Error No Op registered for XXX with domain_version of 13.

So my question is what is the right way to go about this?  How do I make onnxruntime to point to my custom_op and run inference? Any leads would be appreciated :) 
Thanks.

**Comment by cbourjau** [comment]
As I understand it you are not trying to propose your operation be added to the standard, do you? If so, your issue is with [`microsoft/onnxruntime`](https://github.com/microsoft/onnxruntime), not [`onnx/onnx`](https://github.com/onnx/onnx). The former allows you to load a shared library that follows their c-api. It is documented here: https://onnxruntime.ai/docs/reference/operators/add-custom-op.html

**Comment by xadupre** [comment]
You can also add a custom operator implemented in python with onnxruntime-extensions: https://github.com/microsoft/onnxruntime-extensions#add-a-new-custom-operator-to-onnxruntime-extensions.
