### ISSUE TITLE
Can "Reshape" support dynamic input and output?

### ISSUE THREAD

**Issue by MingZeMa** [onnx/onnx#5171]
# A Question about how to let the "Reshape" support dynamic input and output?

### Question
When I convert my pytorch model to onnx, I want it can support dynamic input and output, so I use the parameter `dynamic_axes` in the function `torch.onnx.export`. But after converting, in onnx file, I find that before "Reshape" the network structure does support dynamic size, but after "Reshape" the output is constant and all subsequent network structures are still static size.

Did I do something wrong? I want to know how to solve this problem,I'd appreciate it if anyone could help me.

I upload my onnx model. In "model.zip",  the "static.onnx" is the original model and the "dynamic.onnx" is the model exported with `dynamic_axes` . In the "dynamic.onnx" you can find that after the first "Reshape", all the data is static again. And this "Reshape" corresponds to my code in python is `Tensor.view()`

My onnx model: [model.zip](https://github.com/onnx/onnx/files/11300628/model.zip)

### Further information
The version I use:
onnx: 1.13.0
pytorch: 1.13.1

**Comment by xadupre** [comment]
The Reshape node reshape the input with a fixed shape. The converter detects it and optimizes the code. The parameter `export_modules_as_functions` changes the conversion. The outcome may be closer to what you are looking for. However, if you did not explicitely reshaped the tensor, it seems like an undesired behaviour of the converter (+ @abock).

**Comment by justinchuby** [comment]
The shapes for reshape need to be known at conversion time. You may incorporate e.g. -1 for the dynamic axis.

**Comment by justinchuby** [comment]
Please reopen if you have further questions.

**Comment by Priyanshu88** [comment]
@justinchuby Can you look into my issue for the reshape https://github.com/onnx/onnx/issues/6029
