### ISSUE TITLE
How to debug the onnx model from pytorch

### ISSUE THREAD

**Issue by JohnHerry** [onnx/onnx#5172]
# Ask a Question

### Question
  How to debug the onnx model exported from a pytorch?

### Further information
I am trying to transform the VITS tts model (pytorch) into onnx format, at last the transformation success and there is a onnx file generated.
My convertion params are:
    opset version=11
    do_constant_folding=True

and when I trying to loading the onnx model for inference, a bug report:

FAIL: Load model from XXX.onnx failed: Type Error: Type parameter(T) of Optype(Concat) bound to different types (Tensor(int64)) and tensor(float) in node (Concat_226)

my python version is  3.8.5, torch==1.10.2+cu111

The original code has no direct node of torch.concat, so I do not know which is the node Concat_226,  how to get its position in the source code so that I can test and debug?

- Is this issue related to a specific model?

VITS

**Comment by xadupre** [comment]
Node concat is implicitely introduced by the converter. There is no exact match between torch code and onnx code. You can use netron to search for node `Concat_226` and see approximatively where it is in the graph and then guess where it could be in your code. onnx is strongly typed and do not support operations (+, -, ... concat) with tensors of different types. The converter should have been able to insert an explicit cast operator. @thiagocrepaldi would probably know more about this.
