### ISSUE TITLE
Relative Links at https://pypi.org/project/onnx/ not working 

### ISSUE THREAD

**Issue by andife** [onnx/onnx#5173]
# Bug Report

### Describe the bug
Relative Links at https://pypi.org/project/onnx/ not working.

### Notes
Maybe make the links absolut for the wheel and Pypi

**Comment by xadupre** [comment]
Nothing has changed since February. It is possible to know more?

**Comment by andife** [comment]
Our readme has the line:

"[ONNX intermediate representation spec](docs/IR.md)"

which results in 

![image](https://user-images.githubusercontent.com/20612932/233996151-f73c3361-9f4d-4bed-8649-7845f064557a.png)

**Comment by jcwchen** [comment]
Thanks for catching this. To provide more history context: previously we thought relative link issue for displaying description in PyPI has been resolved from their end: https://github.com/onnx/onnx/pull/3961, but in fact this issue still exists: https://github.com/pypa/readme_renderer/issues/163. I also think we should use absolute links in ReadMe.md for now.

**Comment by andife** [comment]
I have not investigated it now so, but maybe there is another possibility? Could you prepare the readme file for pypi? Which file is used there? Could you make the links absolute only in the upload process? 

Or maybe adapt the readme better to the target (e.g. how onnx is compiled, might not matter if you get a package with pip). 

=> but maybe that just adds too much unnecessary complexity ?

**Comment by xadupre** [comment]
It is doable by replacing the relative link before just before calling setup: https://github.com/onnx/onnx/blob/main/setup.py#L346.

**Comment by justinchuby** [comment]
I suggest we don’t do too much in setup.py since it will eventually become pyproject.toml
