### ISSUE TITLE
[Feature request] Display the dtype name in shape inference when there is a mismatch

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5178]
### What is the problem that this feature solves?

In check model or shape inference, the types are displayed as numbers (6, 7, etc. ) when there is a type mismatch. It would make the error message friendlier if we show the names of the types (INT64 etc. ) instead. 

https://github.com/onnx/onnx/blob/0715646d1fb1eed830999c8a43dce532ead08491/onnx/shape_inference/implementation.cc#L70-L71

`GetElemTypeString(inferred_type)` seems to be returning numbers.

### Will this influence the current api (Y/N)?

N

### Are you willing to contribute it (Y/N)

None

**Comment by guoyuhong** [comment]
@justinchuby Do you have a way to reproduce the type mismatch and the displayed numbers? If I have a way to repro that, I can try to fix the problem.

**Comment by justinchuby** [comment]
Thanks, I wasn't able to find the place with a quick search. I will update if I see it again.

**Comment by ClifHouck** [comment]
Going to take a look at this. Seems similar to #5442 but on the C++ side of things.

**Comment by ClifHouck** [comment]
Per findings in #5525, it seems like this may already be solved.
