### ISSUE TITLE
[Feature request] Add possibility to pass `pathlib.Path` where filepath is expected

### ISSUE THREAD

**Issue by vahvero** [onnx/onnx#5182]
### System information

 name         : onnx                         
 version      : 1.13.1                       
 description  : Open Neural Network Exchange 

dependencies
 - numpy >=1.16.6
 - protobuf >=3.20.2,<4
 - typing-extensions >=3.6.2.1

required by
 - onnxconverter-common *
 - skl2onnx >=1.2.1

### What is the problem that this feature solves?

`onnx` file handling accepts only `IO[bytes] | str`. If passing Python `pathlib.Path`, static type checkers such as `pyright` and `pylance` emit errors which is incorrect.

```python
import onnx
import pathlib

model = onnx.load(pathlib.Path("model.onnx"))
```
Causes `PyRight` error

```
Argument of type "Path" cannot be assigned to parameter "f" of type "IO[bytes] | str" in function "load_model"
    Type "Path" cannot be assigned to type "IO[bytes] | str"
      "Path" is incompatible with "IO[bytes]"
      "Path" is incompatible with "str" (reportGeneralTypeIssues)
```
Commonly, usage `pathlib` is considered preferential to `str`, as it reduces the risk of manual error.

### Alternatives considered

One can avert this error by

```python
import pathlib
import onnx
import typing
modelpath = pathlib.Path("model.onnx")
model = onnx.load(str(modelpath))
# or
with open(modelpath, "rb") as fobj:
    model = onnx.load(fobj)
# or 
model = onnx.load(typing.cast(str, modelpath))
# or doing over-engineered staff with pathlib.Path
```

Or one can use manual path handling with `str`, which as previously mentioned, is often considered non-optimal.

### Describe the feature

1. Using `pathlib` to handle paths is considered best practice by many.
2. Would remove unnecessary object transformations to satisfy type checkers 
3. Reduces `# type: ignore` usage in user code base. 

These, in general, should benefit general code quality.

### Will this influence the current api (Y/N)?

No. The current code that expects path should work when passed a `pathlib.Path`. This feature should only affect the type hints. 

### Feature Area

best practices, type hinting

### Are you willing to contribute it (Y/N)

Yes

### Notes

This change is very minor and could probably be done in a few hours by a "replace all" `Union[IO[bytes], str`] -> `Union[IO[bytes], str, Path]`.

**Comment by justinchuby** [comment]
We can use `os.fspath` for this when the input is `os.PathLike`. Note we should not use `str`.
