### ISSUE TITLE
ModuleNotFoundError: No module named 'cmake' during pip install -e .

### ISSUE THREAD

**Issue by guoyuhong** [onnx/onnx#5194]
# Bug Report

### Is the issue related to model conversion?

No. It related to the onnx build system.

### System information

1. System: Linux or MacOs
2. ONNX version: main branch
3. GCC/Compiler: Apple clang version 13.1.6 or gcc (GCC) 8.3.1
4. miniconda, python3.10 or python 3.8
5. cmake  installed by `pip install cmake`

### Reproduction instructions

`pip install -e .`
#### MacOs
![image](https://user-images.githubusercontent.com/19584326/235886209-248e5ac2-6ead-459a-9144-63fee0038fc1.png)

#### Linux
![image](https://user-images.githubusercontent.com/19584326/235886073-dcb98f75-e0fe-4a0c-88de-85bc2d4be239.png)

#### Windows
![image](https://user-images.githubusercontent.com/19584326/236002702-d018839a-a3ca-49a2-a516-e6c19fe4ffdf.png)

### Notes

`python setup.py build` works fine.

**Comment by jcwchen** [comment]
Hi @guoyuhong,
I cannot repro this issue somehow, although my `pip install -e .` also added `*-pip-build-env-*` into PYTHONPATH during build. What's your setuptools and pip version? Have you tried the latest setuptools and pip? I wonder why they add pip-build-env into PYTHONPATH and not sure whether it is intentional.

**Comment by guoyuhong** [comment]
@jcwchen In my env, cmake should be installed from pip and the system cmake should not be used. If I use the system cmake, I cannot repro this issue either.  My env setup:
1. cmake version 3.26.3 (installed by pip)
2. pip 22.3.1 or 23.1.2
3. setuptools             67.7.2

**Comment by guoyuhong** [comment]
> @jcwchen In my env, cmake should be installed from pip and the system cmake should not be used. If I use the system cmake, I cannot repro this issue either. My env setup:
> 
> 1. cmake version 3.26.3 (installed by pip)
> 2. pip 22.3.1 or 23.1.2
> 3. setuptools             67.7.2

@jcwchen can you repro this failure with this configuration?

**Comment by jcwchen** [comment]
> @jcwchen can you repro this failure with this configuration?

Yes, thanks for providing the configuration. After removing system cmake and installing cmake from PyPI, I can repro this issue. Also confirmed your PR can solve it.

**Comment by balazon** [comment]
I'm also encountering this. I think "pip install -e ." is installing in a virtual environment, where cmake is not found sometimes. 
Normally this is solved by putting the missing dependency in the pyproject.toml, something like this
[build-system]
requires = ["setuptools", "**cmake**"]

There is a note about the setup.py usage at [setuptools](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html)

> In previous versions of setuptools, this used to be accomplished with the setup_requires keyword but is now considered deprecated in favor of the [PEP 517](https://peps.python.org/pep-0517/) style described above. To peek into how this legacy keyword is used, consult our [guide on deprecated practice (WIP)](https://setuptools.pypa.io/en/latest/deprecated/index.html).

So I managed to solve this by adding this line inside setup.py:
setup_requires.append("cmake")

I'm having different issues now, but cmake is at least found.

**Comment by liqunfu** [comment]
adding "cmake" to requires in pyproject.toml forces out system cmake. cmake in python environment fails to build onnx correctly on Windows: onnx.sln cannot be built with visual studio. https://github.com/onnx/onnx/pull/6045 is to fix this problem. In general, System installed cmake shall be used by default. cmake in a python environment may only be used if it is already installed in a python environment.

**Comment by cjvolzka** [comment]
@liqunfu I had to try some builds on s390x for a [different unrelated issue](https://github.com/onnx/onnx/issues/6047). I had pulled in the latest `main` which included your https://github.com/onnx/onnx/pull/6045 and it worked fine :)
