### ISSUE TITLE
gen_doc.py yields error

### ISSUE THREAD

**Issue by broune** [onnx/onnx#5205]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug

git clone https://github.com/onnx/onnx.git
cd onnx/onnx/defs/
python3.7 gen_doc.py

I get this error:

Traceback (most recent call last):
  File "gen_doc.py", line 415, in <module>
    os.path.join(docs_dir, "Changelog" + ext),
  File "gen_doc.py", line 276, in main
    s += display_schema(schema, [schema])
  File "gen_doc.py", line 184, in display_schema
    option_str = generate_formal_parameter_tags(input_)
  File "gen_doc.py", line 96, in generate_formal_parameter_tags
    if differentiable == formal_parameter.differentiation_category:
AttributeError: 'onnx.onnx_cpp2py_export.defs.FormalParameter' object has no attribute 'differentiation_category'

### System information

Ubuntu 20.04.4 LTS

### Reproduction instructions

See bug description.

### Expected behavior

I expected to generate the documentation files.

**Comment by jcwchen** [comment]
Hi @broune,
I guess there is a gap between your onnx version. `differentiation_category` was introduced to replace the old `differentiationCategory`. To generate document by `gen_doc.py`, please always use the same source code to install onnx first and then run `python onnx/defs/gen_doc.py` to ensure the API consistency. BTW, there is a script to run all the document generation stuff: https://github.com/onnx/onnx/blob/main/tools/update_doc.sh.

**Comment by broune** [comment]
I was able to get this working after a lot of work, it seems to be OK. Closing the bug.
