### ISSUE TITLE
Documentation for QLinearSoftmax?

### ISSUE THREAD

**Issue by fengyuentau** [onnx/onnx#5206]
# Ask a Question

### Question

I have a model and it is quantized by onnxruntime (get the model from [this link](https://github.com/opencv/opencv_zoo/blob/master/models/human_segmentation_pphumanseg/human_segmentation_pphumanseg_2023mar_int8.onnx)). I found the model has a QLinearSoftmax operator but the onnx operator documentation does not provide related content. So I wonder where the documentation is and whether it is missed.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/17219438/236654305-56eca29e-e42c-4222-a9de-3ae3f5a94fef.png">

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by philass** [comment]
These aren't actually operations in the ONNX specification. These are ops that defined in the ONNXRuntime repository. As a result ONNX does not have documentation of these ops.

ONNXRuntime does document these ops. You can find the documentation here https://github.com/microsoft/onnxruntime/blob/2735e0d031b80b66b3d90d0580a14e2e2058da23/docs/ContribOperators.md#com.microsoft.QLinearSoftmax

**Comment by fengyuentau** [comment]
Interesting. I found some operators for quantization in the onnx documentation and thus I naturally think that I can find all the other there. Good to there is another link in ort documentation. Do you consider adding a note somewhere to help users find these contrib operators?

**Comment by philass** [comment]
ONNXRuntime and ONNX are sometimes talked about interchangeably. However they are two very different things.

ONNX is a specification. It also provides facilities for defining operations that don't exist in the specification. The quantization operators you see in the ONNX docs are defined in the specification.

ONNXRuntime is owned by Microsoft. Its is primarily an implementation of the spec, but it also has a bunch of other bells and whistles. This includes defining operations that are useful for their quantization flows.

In practice anybody could create a repository that creates quantization operators (or any operators). Its not the roll of the ONNX specification to be aware of operators that are defined outside of the specification.

That being said it could make sense to add a note in the documentation, especially if its confusing to ONNX users. I don't have strong opinions on that matter.

**Comment by fengyuentau** [comment]
Thank you for the detailed information.

---

> That being said it could make sense to add a note in the documentation, especially if its confusing to ONNX users.

Please do so if possible.

**Comment by fengyuentau** [comment]
@philass I have one more question though: Can I make such a node with `onnx.helper.make_node`? If not, is there any possible way to do that?

**Comment by fengyuentau** [comment]
Looks like we can create any operators from any other domains as long as we do not call `onnx.checker.check_model()` on the model.
