### ISSUE TITLE
Adding sparse_coo_tensor

### ISSUE THREAD

**Issue by alletsr** [onnx/onnx#5213]
# New Operator
sparse_coo_tensor
torch.sparse.FloatTensor(indices, non-zerovalues, torch.Size([2, 100, 128]))

### Describe the operator
This operator creates a sparse tensor, slice through the given indices and assign the non-zero values.  The advantage of using this operator is, this will reduce the memory consumption by the tensor

### Can this operator be constructed using existing onnx operators?
 NO

### Is this operator used by any model currently? Which one?
yes, Voxelnet https://github.com/Hqss/VoxelNet_PyTorch/blob/d7fd0bbaf67257da9975427332ee2f63bdcdfefd/model/group_pointcloud.py#L69

### Are you willing to contribute it? (Y/N)
Y

### Notes
Error while exporting onnx:

Exporting the operator sparse_coo_tensor to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by xadupre** [comment]
This is already a way to create a sparse tensor in onnx (see [Constant](https://onnx.ai/onnx/operators/onnx__Constant.html)). It looks like a converter issue, isn't it?
