### ISSUE TITLE
Unable to create Tensor raw bytes attribute

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#5214]
# Bug Report

The attached script fails to create a model with a single node that has Tensor attribute.
This used to work at some point, not clear what is done wrong.

I noticed, there is not a unit test for creating a single tensor attribute, just a repeated attribute [here](https://github.com/onnx/onnx/blob/main/onnx/test/helper_test.py#L119)

### Is the issue related to model conversion?
No

### Describe the bug
The attached script errors out:

```
$ python .\Test.py
IsTensorProto: True
Attr:  name: "test_bytes"
type: TENSOR
t {
  dims: 12
  data_type: 3
  name: "test_bytes"
  raw_data: "\001\000\000\000\002\000\000\000\003\000\000\000"
}

Traceback (most recent call last):
  File "D:\dev\data\Test.py", line 40, in <module>
    nodes=[helper.make_node('TestNode', inputs=['input'], outputs=['output'], name='TestNode_0', **attrs)]
  File "c:\Python\lib\site-packages\onnx\helper.py", line 162, in make_node
    node.attribute.extend(
  File "c:\Python\lib\site-packages\onnx\helper.py", line 163, in <genexpr>
    make_attribute(key, value)
  File "c:\Python\lib\site-packages\onnx\helper.py", line 884, in make_attribute
    raise TypeError(f"'{value}' is not an accepted attribute value.")
TypeError: 'name: "test_bytes"
type: TENSOR
t {
  dims: 12
  data_type: 3
  name: "test_bytes"
  raw_data: "\001\000\000\000\002\000\000\000\003\000\000\000"
}
' is not an accepted attribute value.
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Windows 10 fully patched
- ONNX version (*e.g. 1.13*): 1.14.0
- Python version:  Python 3.10.11
- Protobuf version: 4.23.0

### Reproduction instructions
```
from onnx import helper, numpy_helper, TensorProto

import onnx
import numpy as np

out_path = "TestModel.onnx"

def clear_field(proto, field):
    proto.ClearField(field)
    return proto

inputs=[helper.make_tensor_value_info('input', TensorProto.FLOAT, shape=[1, 642])]
outputs=[helper.make_tensor_value_info('output', TensorProto.FLOAT, shape=[1, 321])]

# Need an attribute here
data = np.array([1, 2, 3]).tobytes()

tensor = helper.make_tensor(
             name='test_bytes',
             data_type=TensorProto.INT8,
             dims=(len(data),),
             vals=data,
             raw=True)
             
print("IsTensorProto:" , isinstance(tensor, TensorProto));

attr = helper.make_attribute('test_bytes', tensor)
print("Attr: ", attr)

attrs = {}
attrs['test_bytes'] = attr

nodes=[helper.make_node('TestNode', inputs=['input'], outputs=['output'], name='TestNode_0', **attrs)]

graph=helper.make_graph(
    name='TestGraph',
    inputs=inputs, outputs=outputs,
    nodes=nodes)

model=helper.make_model(
    opset_imports=[helper.make_operatorsetid('', 13)],
    ir_version=6,
    graph=graph)

onnx.save(model, out_path)...
```

### Expected behavior
Saved model

**Comment by jbachurski** [comment]
Maybe the error message of `onnx.helper.make_attribute` could be improved, but it seems evident to me that the error is because you provide an attribute with the attribute value of an `AttributeProto`. You want to be providing `attrs = {'test_bytes': tensor}`, not `attrs = {'test_bytes': attr}`. 
I don't think this behaviour has changed in a very long time:

https://github.com/onnx/onnx/blob/da892d3a061b2dea5dbb2fff74612f3af157236a/onnx/helper.py#L161-L166

Though I've refactored `onnx.helper.make_attribute` in https://github.com/onnx/onnx/pull/5063, I don't think this behaviour was ever accepted. It's completely reproducible on `1.13.1`.
