### ISSUE TITLE
`onnx.helper.make_attribute` could not infer type correctly from empty list

### ISSUE THREAD

**Issue by take-cheeze** [onnx/onnx#5216]
# Bug Report

### Describe the bug

Since `all([])` is always `True` passing empty list to `make_attribute` will be always list of ints
https://github.com/onnx/onnx/blob/a02166572855083b3b6f5a329ba438f8cd8635f9/onnx/helper.py#L858-L860

### Reproduction instructions

```python
onnx.helper.make_attribute("attr_name", [])  # Always .type == INTS which isn't always expected
```

### Expected behavior

For empty list `make_attribute` method should fail due to type inference error or there should be an explicit typed `make_attribute` method

**Comment by jbachurski** [comment]
You're right, this behavior is a bit awkward,  though at least it has been like this for a while so it's predictable. It could be sensible to add an explicit `type: Optional[AttributeProto.DataType] = None ` keyword argument, and have an error raised when the iterable is missing and the type can't be inferred.
