### ISSUE TITLE
Softplus operator has a different implementation logic with PyTorch/PaddlePaddle

### ISSUE THREAD

**Issue by jikechao** [onnx/onnx#5226]
In the file `onnx/defs/math/defs.cc`, the implementation of `softplus` in ONNX is as follows:

Line 551-558
```
        .FunctionBody(R"ONNX(
          {
            Softplus_X = Softplus (X)
            TanHSoftplusX = Tanh (Softplus_X)
            Y = Mul (X, TanHSoftplusX)
           }
        )ONNX")
        .TypeAndS
```

The function logic differs from the `softplus` in PyTorch and PaddlePaddle.
PyTorch and PaddlePaddle have the same calculation logic.  
They will consider the threshold, if beta* input > threshold, softplus(x) = x.

see [pytorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.Softplus.html)

![image](https://github.com/onnx/onnx/assets/29506758/2d5b0dc7-c7cd-4bee-ba95-9d2694748b9f)

### Question:
is a feature of a bug about the implementation of softplus without considering the threshold? 

cc @xadupre

**Comment by justinchuby** [comment]
The spec for Softplus did not specify a threshold as an argument. To get the same behavior as PyTorch, you may implement a different function.
