### ISSUE TITLE
Shape inference should handle MapProto

### ISSUE THREAD

**Issue by max-509** [onnx/onnx#5231]
# Bug Report

### Is the issue related to model conversion?
Yes, because used converted model.

### Describe the bug
In the ONNX release version 1.11.0, pull request #3772 add shape inference for MapProto, but pull request #3722 may have accidentally removed this support, so in future versions shape inference is still not supported for graphs with the ZipMap operator.

### System information
ONNX version: >=1.11.0

### Reproduction instructions
```python
import onnx
from onnx import shape_inference

onnx_model = onnx.load("onnx_model.onnx")
onnx.checker.check_model(onnx_model)
inferred_model = shape_inference.infer_shapes(onnx_model)
```
```
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:ZipMap, node name: ProbabilityInverseLabelEncoder_prediction1): [ShapeInferenceError] type case unsupported for symbolic shape inference. inferred=5
```
[onnx_model.zip](https://github.com/onnx/onnx/files/11494738/onnx_model.zip)

### Expected behavior
MapProto support, as assured in the [release](https://github.com/onnx/onnx/releases/tag/v1.11.0)

**Comment by jcwchen** [comment]
Hi @max-509,
Thank you for catching this. It should be fixed by https://github.com/onnx/onnx/pull/5188, but it's quite fresh so it's not included in the recent ONNX 1.14.
