### ISSUE TITLE
onnx.compose.merge_models fails with large models

### ISSUE THREAD

**Issue by jambayk** [onnx/onnx#5234]
# Bug Report

### Is the issue related to model conversion?

No 

### Describe the bug

I don't know if this is considered a bug or an expected behavior. 
When I compose two models using `onnx.compose.merge_models`, it fails at the `checker.check_model(model)` step https://github.com/onnx/onnx/blob/main/onnx/compose.py#L410 if the model is too large (>2GB). It hits this error https://github.com/onnx/onnx/blob/main/onnx/checker.py#L137. 

### System information

- ONNX Version: 1.13.1 

### Reproduction instructions

I do not have a specific example, but the failure can be seen by following the flow of the model merge logic. The final `model` (of type `ModelProto` ) is larger than the max protobuf size so it fails at the `onnx.checker` step.

### Expected behavior

Handle large models successfully.

**Comment by jcwchen** [comment]
Hi @jambayk,
Actually Protobuf has hard limit 2GB and so all related Python API for manipulation cannot work with models>2GB. `check_model` inside `merge_models` can kind of prevent further issues if the merged model is larger than 2GB. Typically large initializer is the main reason causing large models. If that is the case for your model, to avoid hitting 2GB limit, perhaps you can try to load models without external data (save your model with large external data first if not) https://github.com/onnx/onnx/blob/751496fe8282575beb5a5b612dabadaff8034a8f/onnx/__init__.py#L163-L166, but the merge model needs to be saved in the same directory as the previous two models to let external data work correctly.

**Comment by trajepl** [comment]
Then quick question, let us say, we have 2 models to merge:
1. A, 2.1GB, saved in local with external data
2. B, 1.2GB, saved in local directly.

Then we have following merging steps:
1. A_structure = onnx.load(A_path, **load_external_data=False**), B = onnx.load(B_path)
2. C = onnx.compose.merge_models(A_structure, B)
3. C = load_external_data_for_model(C, external_data_dir)

will step 3 run successfully?

**Comment by zhipenghan** [comment]
For check_model function. Even I output the external data in separate files and the *.onnx file is still >2GB. Will you support large models?
