### ISSUE TITLE
AveragePool: When Ceil_mode=1, AveragePool Generates Nan or 0 Values.

### ISSUE THREAD

**Issue by carrieyummy** [onnx/onnx#5235]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Averagepool. 
When ceil_mode=1, count_include_pad=0，there are many nan in result.
When ceil_mode=1, count_include_pad=1，there are many 0 in result.
![image](https://github.com/onnx/onnx/assets/39080899/099ab803-a290-41bd-adda-1dd3afed07f5)
![image](https://github.com/onnx/onnx/assets/39080899/6e93b42e-e718-4b02-a3bf-0773d92c34f9)

- Attach the ONNX model to the issue (where applicable)-->
![image](https://github.com/onnx/onnx/assets/39080899/6723409a-61aa-448a-939d-4645cdddc5fb)

**Comment by jcwchen** [comment]
Hi @carrieyummy,
Which runtime are you referring to? ONNX Runtime, onnx.reference or others?

**Comment by carrieyummy** [comment]
> Hi @carrieyummy, Which runtime are you referring to? ONNX Runtime, onnx.reference or others?

onnxruntime
code:
ort_session = ort.InferenceSession(model)
outputs = ort_session.run(output_names, {names[0]: test_data})[0]
