### ISSUE TITLE
Better documentation for Custom Encoders

### ISSUE THREAD

**Issue by aleeminati** [onnx/onnx#5239]
# Ask a Question

### Question
I'm new to ONNX and I have a use case where I have to use custom encoder and imputers. There is instructions in documentation on how to create a custo encoder but the code explanation is unclear. For example, I don't know what exists in operator.raw_operator, etc. Is there a way where you can run the converter and parser functions to check the outputs or maybe better documentation on how to specify the encoder.

### Further information
- Relevant Area: Converters

- Is this issue related to a specific model?
**Model name**: General
**Model opset**: General

### Notes
![image](https://github.com/onnx/onnx/assets/54157649/ccdb5b57-e6d7-450c-bebf-76469ea70748)

**Comment by jcwchen** [comment]
Hi @aleeminati,
This [doc](https://onnx.ai/sklearn-onnx/auto_tutorial/plot_kcustom_converter_wrapper.html) and [code](https://github.com/onnx/sklearn-onnx/blob/09866555f89c6290f6c47e9eee07f76c8d072aa0/docs/tutorial/plot_kcustom_converter_wrapper.py#L122-L127) seems to come from the [sklearn-onnx converter](https://github.com/onnx/sklearn-onnx), which should be a better place to track this issue.
