### ISSUE TITLE
How to solve the problem of releasing GPU memory in onnxruntime-gpu run, achieving similar functionality to torch.cuda.empty_cache()?

### ISSUE THREAD

**Issue by aoyang-hd** [onnx/onnx#5243]
# How to solve the problem of releasing GPU memory in onnxruntime
### Question
"I have deployed my PyTorch model to a server and after each request, I release the memory using 'torch.cuda.empty_cache()'. However, after converting my model to ONNX and calling it with 'onnxruntime-gpu', I have noticed that the memory is not being released. This is causing excessive memory consumption. Is there a similar method I can use to release memory in this situation?"

thank lots

**Comment by jcwchen** [comment]
Hi @aoyang-hd,
It should be a question for onnxruntime-gpu. Please raise issue in https://github.com/microsoft/onnxruntime instead to get the best help from runtime experts.
