### ISSUE TITLE
How can I locate an unsupported op in my model

### ISSUE THREAD

**Issue by Aracher** [onnx/onnx#5251]
I try to convert a pth model to onnx model in onnx 1.12.0 ; model based on mmdet3d and bevformer
the code reported RuntimeError "operator linspace is not supported" 
I want to locate which linspace is not supported so I put pbd.set_trace() front every linspace(mmdet3d and bevformer) but onnx_export cannot stop.
Could someone help? thx

**Comment by justinchuby** [comment]
That will mean all invocations of linspace are not supported. Please feel free to open an issue in the PyTorch repo.
