### ISSUE TITLE
requirements.txt not found?

### ISSUE THREAD

**Issue by haveabyte** [onnx/onnx#5254]
Windows 11:

C:\sd>python --version
Python 3.11.2

C:\sd>pip install olive-ai[directml]==0.2.1 --pre

...everything going fine...

Preparing metadata (setup.py) ... done
  Downloading onnx-1.10.0.tar.gz (10.0 MB)
     ---------------------------------------- 10.0/10.0 MB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\erikk\AppData\Local\Temp\pip-install-iop73y8m\onnx_b0915bd317d140e78098322b146e0e0c\setup.py", line 318, in <module>
          raise FileNotFoundError("Unable to find " + requirements_file)
      FileNotFoundError: Unable to find requirements.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by jcwchen** [comment]
Hi @haveabyte,
It's a bug in ONNX 1.10.0. Please use ONNX 1.10.1 instead (basically same as 1.10.0 with fix for requirement.txt) or newer ONNX.

**Comment by haveabyte** [comment]
That version does not seem to be available.  I'm trying to do what's noted by Nvidia here to pair SD and Olive:
https://blogs.nvidia.com/blog/2023/05/23/microsoft-build-nvidia-ai-windows-rtx/

1.10.0?

C:\sd>pip install olive-ai[directml]==1.10.0
ERROR: Could not find a version that satisfies the requirement olive-ai[directml]==1.10.1 (from versions: 0.1.0, 0.2.0, 0.2.1)
ERROR: No matching distribution found for olive-ai[directml]==1.10.1

0.2.0 also gives me the same requirements.txt error
0.1.0 did install ok, but not sure if that's going to work with SD...

**Comment by haveabyte** [comment]
actually I solved it thusly:

a) remember I had problems with latest Python 3.11.2 and stablediffusion before
b) swap out to Python 3.8
c)  git clone https://github.com/microsoft/olive --branch v0.2.1
d)  cd Olive
e)  pip install .
f)  cd examples\directml\stable_diffusion
g) pip install -r requirements.txt

all of this seemed to work, haven't actually gone past this but yeah, this is the ticket

**Comment by jcwchen** [comment]
I meant onnx package 1.10.1. onnx package 1.10.0 is missing `requirements.txt` in source distribution and also onnx does not provide prebuilt wheel for Python 3.11. Using onnx>=1.10.1 should fix this issue. Actually I don't see Olive has specified it's onnx version as 1.10.0 (https://github.com/microsoft/Olive/blob/main/requirements.txt) and my `pip install olive-ai[directml]==0.2.1 --pre` will install the latest onnx 1.14.0.

Perhaps try `python -m pip install --upgrade pip` first or install later onnx version before `pip install olive-ai[directml]==0.2.1 --pre` to prevent it installing onnx 1.10.0 somehow.
