### ISSUE TITLE
Installing package on Windows fails on too long filenames

### ISSUE THREAD

**Issue by ivberg** [onnx/onnx#5256]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Can't install onnx on Windows

### System information
 Visual Studio 2022

### Reproduction instructions
>pip install onnx
Collecting onnx
  Using cached onnx-1.14.0-cp311-cp311-win_amd64.whl (13.3 MB)
Requirement already satisfied: numpy in c:\users\ivberg\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from onnx) (1.24.3)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\ivberg\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from onnx) (4.23.1)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\users\ivberg\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from onnx) (4.6.1)
Installing collected packages: onnx
ERROR: Could not install packages due to an OSError: [WinError 206] The filename or extension is too long: 'C:\\Users\\ivberg\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\onnx\\backend\\test\\data\\node\\test_layer_normalization_3d_axis_negative_1_epsilon_expanded_ver18\\test_data_set_0'

### Expected behavior
ONNX can install

### Notes
Blocks running this sample - https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP/mobilenetv2_classification

**Comment by jcwchen** [comment]
Hi @ivberg,
Have you tried the workarounds mentioned in https://github.com/onnx/onnx/issues/2821#issuecomment-662153208? (change config when installing Python or upgrade Windows)

**Comment by ivberg** [comment]
This is python installed from Windows Store - so you don't get the option to enable long paths
It seems based on previous issues, this issue probably needs to be fixed in the onnx pkg to prevent this issue. Note that these other pkgs installed fine on the default config (opencv-python, pillow, onnxruntime)

I did workaround the issue via the following

- https://stackoverflow.com/questions/51019926/python-installer-for-windows-disable-path-length-limit-option-not-available
- gpedit.msc - Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem > "Enable Win32 Long paths"

**Comment by justinchuby** [comment]
I recommend enabling the `Enable Win32 Long paths` policy.
