### ISSUE TITLE
Adding a node to an existing onnx model

### ISSUE THREAD

**Issue by IzanCatalan** [onnx/onnx#5257]
Hello everyone!

I would like to know if it is possible to add a new node (for example, a node with a Clipping Operator) in the middle of an existing onnx model without creating a new model.

The idea is to easily add the new node by loading an onnx model from the file, modify the output of the previous node and the input of the next node, and finally, save the model back to the onnx file.

Thanks!

Izan.

**Comment by justinchuby** [comment]
You may be able to save the model as textproto, edit the text file and save it back to the binary format:

```python
onnx.save_model(model, "model.textproto", "textproto")
# Edit the file
edited = onnx.load_model("model.textproto", "textproto")
onnx.save_model(edited, "edited.onnx", "protobuf")
```

You will need to build onnx from the main branch for this feature.

Alternatively, @jbachurski I wonder if spox supports insertion?

**Comment by jbachurski** [comment]
@justinchuby I think it would be possible to hack something with stable Spox that would allow doing this programmatically, for instance: visit all nodes in the graph (iterate through `GraphProto.nodes`), and rewrite the graph by wrapping every `NodeProto` in `spox.inline`. Then you could have some if-branches that rewrite the node as another node. 

However, this strongly depends on the use case - _where_ should the nodes be inserted? Can you assume you e.g. know the input/output names you want to insert in-between? Or maybe the surrounding structure, like replacing every result after `Add` etc.? I can try to come up with an example implementation if there are some details for this.

**Comment by SrinivasuluCharupally** [comment]
I tried this but output file is not in readable formate

`onnx.save_model(model, "model.textproto", "textproto")`

output  model.textproto file attached...
[model.zip](https://github.com/onnx/onnx/files/11814249/model.zip)

**Comment by justinchuby** [comment]
You may need to use the onnx-weekly build because the feature is not released yet
