### ISSUE TITLE
How to add an op with sparse tensor as input/output

### ISSUE THREAD

**Issue by strgrb** [onnx/onnx#5268]
I want to add some ops for sparse tensor, and I noticed this design #2008 . But there are some questions:
1. currently there are not any op with sparse tensor as input/output, is it proper to use definition such as `"sparsetensor(float)"`?
2. which way is preferred when I want to add sparse support for some existing op such as `ReduceSum`, adding a new op for sparse? or adding a new type of input for the original op?

**Comment by guoyuhong** [comment]
@HectorSVC suggested to involve @askhade to take a look. @askhade could you give some advice?

**Comment by yuslepukhin** [comment]
`sparse_tensor` is recognized by ONNX standard as a valid type. To add a new operator, please, follow the [ONNX standard guidelines](https://github.com/onnx/onnx/blob/main/docs/AddNewOp.md).

**Comment by linkerzhang** [comment]
> 

For your 1st question, let's follow the link that Dmitri showed above to send a PR here; For your second one, I'd suggest to add the type to existing op instead of adding a new op.

**Comment by strgrb** [comment]
OK, I'll follow it.
