### ISSUE TITLE
Is it possible to check that operations are supported without exporting the entire model?

### ISSUE THREAD

**Issue by NatanBagrov** [onnx/onnx#5273]
Is there a way to check a support of an operator with ONNX, without trying to convert to model?

Example:
The [`torch.scatter_reduce(...)`](https://pytorch.org/docs/stable/generated/torch.scatter_reduce.html) function is not supported in ONNX at the moment.

You can wrap the conversion with `try-except` but then you get an error that is in the "model"-level and not the block level.

I'm wondering is it possible to have something like `torch.onnx.is_supported(lambda: torch.scatter_reduce(a,b,c,d))`

**Comment by jcwchen** [comment]
Hi @NatanBagrov,
It seems like a question for the converter (`torch.onnx.export`). Please raise this issue in PyTorch repo instead and mention ONNX in title to get better help from the converter experts. Thanks.

**Comment by justinchuby** [comment]
Closed in favor of the issue in PyTorch
