### ISSUE TITLE
col2im operator in ONNX18

### ISSUE THREAD

**Issue by learner-33** [onnx/onnx#5274]
# Ask a Question

### Question

import onnx
from onnx import helper
import numpy as np

def make_col2im():
    input = helper.make_tensor_value_info("input", onnx.TensorProto.FLOAT, [1, 5, 5])
    image_shape = helper.make_tensor_value_info("image_shape", onnx.TensorProto.INT32, [5, 5])
    block_shape = helper.make_tensor_value_info("block_shape", onnx.TensorProto.INT32, [1, 5])
    output = helper.make_tensor_value_info("output", onnx.TensorProto.FLOAT, [1, 1, 5, 5])

    node = onnx.helper.make_node(
            'Col2Im', inputs=['input', 'image_shape', 'block_shape'], outputs=['output'], padding=[0,0], stride=[1,1], dilation=[1,1]
    )
    graph = helper.make_graph(
                            [node],
                            "test_Col2imV2",
                            [input, image_shape, block_shape],
                            [output])

    model_def = onnx.helper.make_model(graph, producer_name='sch')
    model_def.opset_import[0].version = 18
    onnx.save(model_def, "test_col2imv2_v18.onnx")

if __name__ == '__main__':
    make_col2im()

This is the use case code I used to generate the onnx model.
However, the generated model is obviously not found on the onnx graph. 
![image](https://github.com/onnx/onnx/assets/82145391/fbbb1dfe-6823-4912-92fa-8ac79754422a)

It looks like the three inputs don't correspond.
If it's the correct diagram, it should look like the following
![image](https://github.com/onnx/onnx/assets/82145391/d07739c3-0028-4db2-a1ed-9d6c4e7e8484)
The names of input and output in ONNX can be X and Y respectively, instead of 0, 1, and 2 in the previous figure.

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by jcwchen** [comment]
Hi @learner-33,
Actually onnx.checker can help debug for you by `onnx.checker.check_model("test_col2imv2_v18.onnx")`. It will complain the attribute names are unrecognized. You should create col2Im node as: `node = onnx.helper.make_node('Col2Im', inputs=['input', 'image_shape', 'block_shape'], outputs=['output'], pads=[0,0], strides=[1,1], dilations=[1,1])`.

**Comment by learner-33** [comment]
I created the col2im node in the same way as the example you gave.Okay, thank you. I'll try onnx.check.check_model.

**Comment by learner-33** [comment]
According to your description, the attribute name is changed after the check. However, the ONNX model is still incorrect and is not associated with the ONNX official model.

**Comment by jcwchen** [comment]
There are two more errors and you can further enable full_check to check shape_inference: onnx.checker.check_model("test_col2imv2_v18.onnx", full_check=True)
- image_shape and block_shape only allow int64: https://github.com/onnx/onnx/blob/main/docs/Operators.md#col2im.
- The shape inference is incorrect for your model. I have corrected the model myself, but I am not sure what's your actual usage:
```
    input = helper.make_tensor_value_info("input", onnx.TensorProto.FLOAT, (1, 5, 5))
    image_shape = helper.make_tensor_value_info("image_shape", onnx.TensorProto.INT64, (2,))
    block_shape = helper.make_tensor_value_info("block_shape", onnx.TensorProto.INT64, (2,))
    output = helper.make_tensor_value_info("output", onnx.TensorProto.FLOAT, (1, 1, 5, 5))

    node = onnx.helper.make_node('Col2Im', inputs=['input', 'image_shape', 'block_shape'], outputs=['output'])
    graph = helper.make_graph(
                            [node],
                            "test_Col2imV2",
                            [input, image_shape, block_shape],
                            [output])

    model_def = onnx.helper.make_model(graph, producer_name='sch')
    model_def.opset_import[0].version = 18
    onnx.save(model_def, "test_col2imv2_v18.onnx")
    onnx.checker.check_model("test_col2imv2_v18.onnx", True)
```
