### ISSUE TITLE
Using if node on top of two onnx models then merging with another model not working as it should

### ISSUE THREAD

**Issue by ahmedbelgacem** [onnx/onnx#5278]
# Ask a Question

### Question
I have a model that outputs masks, then there's a postprocessing part to get the final output from those masks. There is two types of postprocessing depending on a boolean value split. I first exported the model from pytorch as onnx, I then exported the two postprocessings. After that I created an onnx model that adds an if node on top of  the two postprocessing models (see code below).
I tried the postprocessing onnx model alone and it works fine but the graph on netron looks a little bit weird. I also tried the backbone onnx model and it works fine
Finally I tried to chain the two models with  onnx.compose.merge_graphs. I get this error:
Nodes in a graph must be topologically sorted, however input 'masks' of node: name: /Greater OpType: Greater is not output of any previous nodes.
This is my code:
```
import onnx

onnx_model_split = onnx.load("split.onnx")
onnx_model_no_split = onnx.load("no_split.onnx")
backbone = onnx.load("model.onnx")
onnx.checker.check_model(onnx_model_no_split, full_check=True)
onnx.checker.check_model(onnx_model_split, full_check=True)
onnx.checker.check_model(backbone, full_check=True)
assert len(onnx_model_split.graph.output) == len(onnx_model_no_split.graph.output)

graph_split: onnx.GraphProto = onnx.helper.make_graph(
    nodes=list(onnx_model_split.graph.node),
    name="graph-split",
    inputs=[],
    outputs=list(onnx_model_split.graph.output),
    initializer=list(onnx_model_split.graph.initializer),
)

graph_no_split: onnx.GraphProto = onnx.helper.make_graph(
    nodes=list(onnx_model_no_split.graph.node),
    name="graph-no-split",
    inputs=[],
    outputs=list(onnx_model_no_split.graph.output),
    initializer=list(onnx_model_no_split.graph.initializer),
)

split = onnx.helper.make_tensor_value_info(name="split", elem_type=onnx.TensorProto.BOOL, shape=[1])

if_node = onnx.helper.make_node(
    op_type="If",
    inputs=["split"],
    outputs=[o.name for o in list(onnx_model_no_split.graph.output)],
    then_branch=graph_split,
    else_branch=graph_no_split,
)

if_graph_def: onnx.GraphProto = onnx.helper.make_graph(
    nodes=[if_node],
    name="if-model",
    inputs=list(onnx_model_split.graph.input) + [split],
    outputs=list(onnx_model_no_split.graph.output),
    initializer=list(onnx_model_no_split.graph.initializer),
)

final = onnx.compose.merge_graphs(backbone.graph, if_graph_def,[("output","masks")], prefix1="backbone_")
model = onnx.helper.make_model(
    final,
    producer_name="model",
    opset_imports=[onnx.helper.make_opsetid(onnx.defs.ONNX_DOMAIN, 12)],
    ir_version=7,
)
onnx.checker.check_model(model, full_check=True)
onnx.save(final, 'final.onnx')
```
This is the weird netron graph:
![image](https://github.com/onnx/onnx/assets/35343081/9e1d27f0-be46-4e76-99d5-8ae1ba0ebfb3)
I tried to look at the merge_graphs function and found that in this part it doesn't find the masks name in node.input but it finds it in reversed_io_map.
```
for node_idx in range(g2_nodes_begin, g2_nodes_end):
    node = g.node[node_idx]
    for index, name in enumerate(node.input):
        if name in reversed_io_map:
            node.input[index] = reversed_io_map[name]
```
I guess the error maybe in the if graph part but i can't really tell since i'm not used to onnx that much. I would be really grateful if someone can enlighten me on this.

**Comment by ahmedbelgacem** [comment]
I experimented a little more and have found the issue: 
- To connect the outputs of the first graph with the inputs of the second, the code for merge graphs checks if the nodes in g in the range between g2_nodes_begin and g2_nodes_end have an input name in reversed_io_map.
- When making the if node the then branch and the else branch are not in the graph.node but graph.attribute.
- When looping over the nodes, the merge graph doesn't find the nodes in the then and else branch so the output of my backbone and input of my if node are never connected even thought i have specified it in the right parameter.
The workaround i did was that i rewrote the merge graph code changing it as follows:
```
for node in g.node[g2_nodes_begin].attribute[0].g.node:
    for idx, name in enumerate(node.input):
        if name in reversed_io_map:
            node.input[idx] = reversed_io_map[name]
for node in g.node[g2_nodes_begin].attribute[1].g.node:
    for idx, name in enumerate(node.input):
        if name in reversed_io_map:
            node.input[idx] = reversed_io_map[name]
```
I think this should be fixed and the if node behaviour should be taken into account. I would be willing to work on this and submit a pull request.

**Comment by jbachurski** [comment]
Hey @ahmedbelgacem! If you're interested in using a more powerful library for building ONNX graphs, maybe [Spox](https://github.com/Quantco/spox) can help solve your issue. 

```py
import onnx
import spox
import spox.opset.ai.onnx.v17 as op

onnx_model_split = onnx.load("split.onnx")
onnx_model_no_split = onnx.load("no_split.onnx")

# Create argument Vars for all the inputs of one of the models
# (Uses a currently protected function for convenience, which converts ONNX types to the Spox representation) 
args = {i.name: spox.argument(spox.Type._from_onnx(i.type)) for i in onnx_model_split.graph.input}

# Create the new argument for split which will become a new model input
split = spox.argument(spox.Tensor(bool, (1,)))

results = op.if_(  # Create an If operator, branching on split, and resulting in one of the sub-models
    split,
    then_branch=lambda: spox.inline(onnx_model_split)(**args).values(),  
    else_branch=lambda: spox.inline(onnx_model_no_split)(**args).values(),
)

output_names = [o.name for o in onnx_model_split.graph.output]
# Build a ModelProto with the inputs and outputs with same names and types as the sub-models
#  additionally with the new split model input
onnx_model = spox.build({**args, "split": split}, {name: res for name, res in zip(output_names, results)})
```

However, Spox is still pretty new, so to use an outdated opset (v12) you might have to use the `onnx.version_converter`, and some graphs might not be inline-able (in the current release, in particular ones which have subgraphs or functions) :)
Working on supporting graph inlining I did implement [a new renaming routine](https://github.com/Quantco/spox/pull/84) which I might try and upstream, since I was aware that the current one (`onnx.compose.add_prefix_graph` which is also used by `merge_models`) doesn't work with subgraphs.

You can inline the backbone similarly to the above, if I understand correctly, you should just create `args` for `backbone.input` and pass them to `inline(backbone)`, and use the results of that call to get the split and inputs to the sub-models. In any case, feel free to check out the [docs](https://spox.readthedocs.io/en/latest/)! (in particular for inlining)
