### ISSUE TITLE
typo in documentation of Einsum operator

### ISSUE THREAD

**Issue by ulfhanebutte** [onnx/onnx#5282]
# Bug Report
https://github.com/onnx/onnx/blob/main/docs/Operators.md#Einsum

Einsum
An einsum of the form term1, term2 -> output-term produces an output tensor using the following equation

output[output-term] = reduce-sum( input1[term1] * input2[term] )                          <<<<need to be:   *input2[term2])
where the reduce-sum performs a summation over all the indices occurring in the input terms (term1, term2) that do not occur in the output-term.

This is a small typo, however it can cause unnecessary confusion.

**Comment by justinchuby** [comment]
cc @gramalingam

**Comment by gramalingam** [comment]
Created PR to fix this, thanks for pointing it out.
