### ISSUE TITLE
due to missing support for quantized `onnx::Concat`

### ISSUE THREAD

**Issue by saeedadeeb103** [onnx/onnx#5293]
# Ask a Question
im trying to do quantization aware training for YOLOx and im using quantize_fx graph mode, and whenever i try to export the model to onnx it will fail due to missing support for quantized 'onnx:Concat'.
### Question

the error i get is  :
SymbolicValueError: ONNX symbolic expected the output of `%input : Tensor = onnx::Concat[axis=1](%quantize_per_tensor, %quantize_per_tensor_2, %quantize_per_tensor_1, 
%quantize_per_tensor_3), scope: models.detection.yolox.yolox.YOLOX::/torch.fx.graph_module.GraphModule::backbone # <eval_with_key>.24:22:0
` to be a quantized tensor. Is this likely due to missing support for quantized `onnx::Concat`. Please create an issue on https://github.com/pytorch/pytorch/issues  [Caused 
by the value 'input defined in (%input : Tensor = onnx::Concat[axis=1](%quantize_per_tensor, %quantize_per_tensor_2, %quantize_per_tensor_1, %quantize_per_tensor_3), scope: 
models.detection.yolox.yolox.YOLOX::/torch.fx.graph_module.GraphModule::backbone # <eval_with_key>.24:22:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Concat'.] 
    (node defined in <eval_with_key>.24(22): forward

the model backbone has torch.cat() but im not sure how to replace it or is there is thing i can do to fix this issue
### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**:  YOLOX
**Model opset**:  opset: 13

**Comment by BCJuan** [comment]
Same issue here 

```
torch.onnx.errors.SymbolicValueError: ONNX symbolic expected the output of `%input.91 : Tensor = onnx::Concat[axis=1](%input.75, %input.83, %out_x), scope: ...
` to be a quantized tensor. Is this likely due to missing support for quantized `onnx::Concat`. Please create an issue on https://github.com/pytorch/pytorch/issues  [Caused by the value 'input.91 defined in (%input.91 : Tensor = onnx::Concat[axis=1](%input.75, %input.83, %out_x), scope: ...
```

I think the problem is using concat with axis=1. Single inputs are supported here but it doesn't mention the axis. My recommendation is to dequant and quant over it.

**Comment by saeedadeeb103** [comment]
> Same issue here
> 
> ```
> torch.onnx.errors.SymbolicValueError: ONNX symbolic expected the output of `%input.91 : Tensor = onnx::Concat[axis=1](%input.75, %input.83, %out_x), scope: ...
> ` to be a quantized tensor. Is this likely due to missing support for quantized `onnx::Concat`. Please create an issue on https://github.com/pytorch/pytorch/issues  [Caused by the value 'input.91 defined in (%input.91 : Tensor = onnx::Concat[axis=1](%input.75, %input.83, %out_x), scope: ...
> ```
> 
> I think the problem is using concat with axis=1. Single inputs are supported here but it doesn't mention the axis. My recommendation is to dequant and quant over it.

or you can use torch 2.0 they fixed the concat Error
