### ISSUE TITLE
How to increase - decrease the maximum number of events during inference profiling?

### ISSUE THREAD

**Issue by Apisteftos** [onnx/onnx#5309]
#  How to increase - decrease the maximum number of events during inference profiling?

### Question
I am trying to profile during the inference with i.e. Efficient-Net-Lite or Faster- RCNN from Models Zoo and each time profiling reach it's maximum number of events. A JSON file has limitation. What's happening exactly?

### Further information
- Relevant Area: Inference 

- Is this issue related to a specific model?

NO

**Comment by justinchuby** [comment]
I think this is a good question for https://github.com/microsoft/onnxruntime/issues
