### ISSUE TITLE
Gemm documentation wording is confusing

### ISSUE THREAD

**Issue by ArchRobison** [onnx/onnx#531]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gemm says:

    If A can be transposed before doing the computation if attribute transA is non-zero, same for B and transB.

The "if A can be" wording is confusing.  Should it say `A is transposed`?

**Comment by houseroad** [comment]
@ArchRobison if transA is set, A will be transposed before the computation. If you can create a PR to fix the ambiguous description, it will be great! Thanks.
