### ISSUE TITLE
[Request] Use the PR description as the commit message when merging

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5311]
## Why

The commits are usually squashed in this repo and the commit messages are usually meaningless. The useful information is in the PR description.

## How to

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

cc @gramalingam @abock

**Comment by jcwchen** [comment]
Sounds good. After discussion, we thought it is better. I have changed it to "Deafult to PR title and description". Close this one since it is done.
