### ISSUE TITLE
How to define condition in Where operator

### ISSUE THREAD

**Issue by IzanCatalan** [onnx/onnx#5314]
Hi everyone, I'm trying to create a graph with a Where operator node. My idea is to use as a condition (a < 5) with 'a' being the output of the previous node. 

I don't know how to assign this condition when creating the node because I don't know how to assign '<' to the output of the previous node. This is because the output is yet to be defined as a Tensor or a numpy array and it has no values, so I get an error when creating the node.

Any examples or help would be very useful

Thanks.

**Comment by justinchuby** [comment]
Perhaps this?

```python
import onnxscript
from onnxscript import FLOAT
from onnxscript import opset18 as op


@onnxscript.script()
def where_example(a: FLOAT["N"]):
    b = op.Where(a > 5, a, a - 1)
    return b


onnx_model = where_example.to_model_proto()

print(onnx_model)
```

Yields

```
ir_version: 8
graph {
  node {
    output: "tmp"
    name: "n0"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        data_type: 7
        int64_data: 5
        name: "tmp"
      }
      type: TENSOR
    }
    domain: ""
  }
  node {
    input: "tmp"
    input: "a"
    output: "tmp_cast"
    name: "n1"
    op_type: "CastLike"
    domain: ""
  }
  node {
    input: "a"
    input: "tmp_cast"
    output: "tmp_0"
    name: "n2"
    op_type: "Greater"
    domain: ""
  }
  node {
    output: "tmp_1"
    name: "n3"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        data_type: 7
        int64_data: 1
        name: "tmp_1"
      }
      type: TENSOR
    }
    domain: ""
  }
  node {
    input: "tmp_1"
    input: "a"
    output: "tmp_1_cast"
    name: "n4"
    op_type: "CastLike"
    domain: ""
  }
  node {
    input: "a"
    input: "tmp_1_cast"
    output: "tmp_2"
    name: "n5"
    op_type: "Sub"
    domain: ""
  }
  node {
    input: "tmp_0"
    input: "a"
    input: "tmp_2"
    output: "b"
    name: "n6"
    op_type: "Where"
    domain: ""
  }
  name: "where_example"
  input {
    name: "a"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "N"
          }
        }
      }
    }
  }
  output {
    name: "b"
  }
}
opset_import {
  domain: ""
  version: 18
}
```

**Comment by justinchuby** [comment]
```
<
   ir_version: 8,
   opset_import: ["" : 18]
>
where_example (float[N] a) => ( b) {
   tmp = Constant <value = int64 tmp {5}> ()
   tmp_cast = CastLike (tmp, a)
   tmp_0 = Greater (a, tmp_cast)
   tmp_1 = Constant <value = int64 tmp_1 {1}> ()
   tmp_1_cast = CastLike (tmp_1, a)
   tmp_2 = Sub (a, tmp_1_cast)
   b = Where (tmp_0, a, tmp_2)
}
```

**Comment by IzanCatalan** [comment]
Thanks @justinchuby for your reply. I see your main function 'where_example'  is for c++ (second message) where you define a graph.  I need help understanding the previous 'where_example' function in python with onnxscript and how it creates the graph.

For python should it work similarly? This is because I work with python API loading and making graphs with ONNX files. Could I add a new node with the 'where_example' op that you defined with onnxscript? Is this possible using Onnx Python Api loading and saving methods like:  onnx.load(model_path) or onnx.save(model_path)?

**Comment by IzanCatalan** [comment]
Okey, thanks  for you help @justinchuby. I think I will try to reproduce your "where example" function by creating the same structure of nodes with Onnx Helper Api.
