### ISSUE TITLE
NaN handling in float based label encoder

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5320]
# Ask a Question
In the specification for a label encoder it says the following:

> For key look-up, bit-wise comparison is used so even a float NaN can be mapped to a value in 'values_' attribute.

I noticed that this doesn't quite work in onnxruntime due to the use of an `std::unordered_map` which will not work with `NaN` keys (as illustrated below). Before working on a patch for the runtime, I wanted to clarify if I'm interpreting the specification correctly here.

The implication of using bit-wise comparison for key lookup seems to me to imply that different `NaN`s can map to different values since `NaN`s occupy a [range](https://en.wikipedia.org/wiki/NaN) in the floating point bit representation. Is that an accurate assessment?

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**: 

### Notes
ORT doesn't appropriately map `NaN`s:

```
import onnxruntime
from spox import build, argument, Tensor
import numpy as np
import spox.opset.ai.onnx.ml.v3 as ml

if __name__ == "__main__":
    VectorFloat32 = Tensor(np.float32, ('N',))
    x = argument(VectorFloat32)
    q = ml.label_encoder(x, keys_floats=[1., 2., 3., np.nan], values_strings=["X", "Y", "Z", "Here"], default_string="Not here")
    model = build({'x': x}, {'r': q})

    session = onnxruntime.InferenceSession(model.SerializeToString())

    result = session.run(None, {
        'x': [1., 2., np.nan]
    })

    print(result)
```

**Comment by cbourjau** [comment]
This has actually been addressed in the documentation of the `LabelEncoder` in the `ai.onnx.ml` opset version 4: https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#aionnxmllabelencoder
