### ISSUE TITLE
New Operator: StringSplit

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5341]
# New Operator: StringSplit

### Describe the operator

ONNX currently lacks the ability to split string tensors on a separator character/substring. A `StringSplit` operator would split each string in an input tensor into a the substrings separated by a `delimiter` character (which would be an attribute).  

This operation is incredibly useful when feature engineering non-categorical strings as it enables users to easily normalise input string data from an external source before being processed by a model. The operator exists in both [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/strings/split) and [numpy](https://numpy.org/devdocs/reference/generated/numpy.char.split.html#numpy.char.split) in very much the same form as described.

Splitting based on a delimiter naturally presents the problem that each string may have a different number of "splits" or occurrences of the delimiter. I'd propose we can resolve this by instead returning a `Sequence`. The `Sequence` would have a "shape" that is the same as the input tensor, then containing string tensors of the substrings separated by the delimiter.

As an example:
`Input: tensor[str] = ["www.google.com", "www.bbc.co.uk/news", "www.bbc.co.uk/news/technology"]`, `Delimiter = "/"`
Would produce the following sequence

`Output: Sequence[tensor[str]] = [["www.google.com"], ["www.bbc.co.uk", "news"], ["www.bbc.co.uk", "news", "technology"]]`.

The user can then use the [SequenceMap](https://github.com/onnx/onnx/blob/main/docs/Operators.md#SequenceMap) and [ConcatFromSequence](https://github.com/onnx/onnx/blob/main/docs/Operators.md#concatfromsequence) operators to produce a tensor for further processing as desired (e.g. take the last element, then convert into a tensor).

### Can this operator be constructed using existing onnx operators?

No

### Is this operator used by any model currently? Which one?
Yes, this operator is very commonly used when cleaning and normalising string inputs generated by a user or upstream process before being passed to a final model. As illustrated direct examples using ragged tensors or arrays of list objects exist in Tensorflow and numpy.

### Are you willing to contribute it? (Y/N)
Y

**Comment by xadupre** [comment]
Currently many string operators are implemented onnxruntime-extensions: https://github.com/microsoft/onnxruntime-extensions/blob/main/docs/custom_ops.md. StringSplit is missing there. I wonder what would be the best place to add it. @gramalingam ?
