### ISSUE TITLE
Automatic deallocation (?) of the Ort::Sessions, memory leak?

### ISSUE THREAD

**Issue by lorenzobattelli** [onnx/onnx#5345]
if I creaate a Ort::Session* pointer, and then dinamically allocate the session with "new", 

do i need to free the memory allocated by using the "delete", for instance into the destructor? 
`Ort::Session* session = new Ort::Session(env, model_wpath, session_options);`
### Question
In a first place i added the delete into my destructor, but at the end of the program, after the destructor be called, i had an exception, and the debugger stopped at the following line of the file onnruntime_cxx_api.h:
`ORT_DEFINE_RELEASE(Session);`

with the following error details:
Exception thrown at 0x00007FFDE2BD44A3 (onnxruntime.dll) in AutomaticImageRecognitionArchiving.exe: 0xC0000005: Access violation reading location 0x00007FFDB81992B8.

But, if I don't delete the memory, and do nothing about it, at the end of the program the exception doesn't occur.
So, does Onnx automatically deals with allocated memory and memory leaks, even if i dinamically allocate Ort::Session with "new" and point it with a Ort::Session* pointer?

**Comment by justinchuby** [comment]
Please consider opening an issue to the microsoft/onnxruntime repository. Thanks!
