### ISSUE TITLE
shape_inference.h compilation failure

### ISSUE THREAD

**Issue by liu12295** [onnx/onnx#5346]
https://github.com/onnx/onnx/blob/main/onnx/defs/shape_inference.h

I encountered compilation failure to due to the missing "#include <algorithm>" for the use of std::transform in the code. PTAL?

**Comment by liu12295** [comment]
Related issue at https://github.com/onnx/onnx-mlir/issues/2327

**Comment by justinchuby** [comment]
Would you like to propose a pull request? It will be appreciated

**Comment by liu12295** [comment]
Sure. Do you have the doc on procedure that I can follow? BTW, why don't
others have this problem?

**Comment by justinchuby** [comment]
Without looking deeper, I suspect it was due to a compiler config? You may simply modify the shape_inference.h file and send a PR. Be sure to sign off your commits: https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md#dco

**Comment by justinchuby** [comment]
@jcwchen are there things we can turn on to check for explicit inclusion of std headers?

**Comment by jcwchen** [comment]
Thanks for catching this. I think onnx itself uses `shape_inference.h` with other code which has included `algorithm` library and so the CI does not catch it. Directly including `shape_inference.h` might hit this issue.

> @jcwchen are there things we can turn on to check for explicit inclusion of std headers?

I am not aware of any and I am happy to see a automatic method to prevent future issues like this. If no, we need to add more unit tests to test it independently, I guess.

**Comment by liu12295** [comment]
I tried, but always encountered the access issue when I git push. (Yes, I
had set up this PAT.) LMK if you know the issue. Or, if not much trouble,
can you please submit a PR for this one-line change? Thanks.

**Comment by jcwchen** [comment]
> I tried, but always encountered the access issue when I git push.

Typically ONNX contributors will need to fork onnx repo and then make a PR from the forked one. Please let me know if you still have problems when submitting a PR from your forked onnx.

> Or, if not much trouble,
can you please submit a PR for this one-line change? Thanks.

Definitely. Just submitted: #5363. Feel free to try it out/review. Thanks!

**Comment by liu12295** [comment]
Excellent.

I see. I didn't fork the onnx repo... will try again next time.

**Comment by liu12295** [comment]
@jcwchen , when will main have your fix? Thanks.

**Comment by jcwchen** [comment]
> @jcwchen , when will main have your fix? Thanks.

The PR should be merged soon. Once it has been merged, this issue will be closed automatically. Thanks for waiting!
