### ISSUE TITLE
Dense operator Issue

### ISSUE THREAD

**Issue by ThomasLesp** [onnx/onnx#5368]
# Seeking advice for single op conversion of dense layers 

Hello ONNX community,

I've encountered an issue while working with image-based models, specifically when converting dense layers from PyTorch and TensorFlow to ONNX. 

The issue is that these dense layers are converted into two separate operations, Matmul and ADD, whenever the input isn't 2D (in this case it's converted into a Gemm ops). This poses a problem in my situation as I'm working on applying quantization methods (like bias correction) and it would be far more efficient to work with a single operation.

Most image-based models naturally have at least 3D inputs, and this leads to the aforementioned issue with the layers not being converted into a single node. This in turn impacts my quantized models.

I'd love to hear any advice or recommendations on how to handle this Matmul/Add scenario. Are there any plans in place to extend the current ONNX operations that could solve this problem? Alternatively, could there be a method to create a dense layer with a single operation instead of two?

I appreciate any suggestions or feedback on this matter. Your insights could be instrumental in resolving this issue and improving the efficiency of my quantization process.

Thank you in advance for your help.

Best Regards,
Thomas Lespargot

**Comment by xadupre** [comment]
Operator Gemm only supports 2D matrices. Matmul is supporting more dimensions but internally, it does multiple Gemm in a loop. So `Matmul(A(N,J,K), B(N,K,L))` is equivalent to N `Gemm(A(.,J,K), B(.,K,L))`. That's difficult to do with a single Gemm. However, Matmul is also supporting broadcasting, so `Matmul(A(N,J,K), B(1,K,L))` is equivalent to N `Gemm(A(.,J,K), B(0,K,L))`. In that case, Gemm could be used after A is reshaped into `A(NJ,K)`. However, it is not always possible to know which scenario is triggered for every model. It is the case for your model?
