### ISSUE TITLE
[Question]  '[TypeInferenceError] Inferred elem type differs from existing elem type : (1) vs (10)'

### ISSUE THREAD

**Issue by SStarver** [onnx/onnx#5374]
# Ask a Question

### Question

> A  '[TypeInferenceError] Inferred elem type differs from existing elem type : (1) vs (10)'  exception occured  when  I tried to implement shape_inferrence on an onnx model  generated from onnxscript.  I wonder if there are any explanation about this ?

![image](https://github.com/onnx/onnx/assets/108868933/6c71f2b3-1dac-459d-b532-5c01053b4b6b)

code is shown below:
```python
from onnx import shape_inference
import onnx

mymodel = onnx.load('sample_mpdel.onnx')
mymodel = shape_inference.infer_shapes(mymodel)

onnx.save(mymodel, "sample_mpdel.onnx")
```

### Further information
- Relevant Area: 
**shape_inference**
- Is this issue related to a specific model?
**Model name**: 
   onnx model is  in model.zip below
   [model.zip](https://github.com/onnx/onnx/files/11891855/model.zip)
**Model opset**: 
   ai.onnx 19

### Notes

python code from which model is generated is shown below for referrence:

```python
import onnx

# We use ONNX opset 15 to define the function below.
from onnxscript import INT8, FLOAT16, FLOAT
from onnxscript import opset19 as op
from onnxscript import script, tensor
import numpy as np
from onnx import helper, TensorProto, shape_inference


kernel_shape = [3, 3]
out_channels = 64
in_channels = 32
pads = [1, 1, 1, 1]
strides = [1, 1]
weight_data = np.random.randint(0, 2, [64, 32, 3, 3]).astype(np.float16)
conv_weight = helper.make_tensor(
    "conv.weight", TensorProto.FLOAT16, (64, 32, 3, 3), weight_data
)

dq_scale = np.float16([0.1])

weight_scale_arr = np.random.randint(0, 2, [64]).astype(np.float16)
dq_scale_val = helper.make_tensor(
    "feature_scale", TensorProto.FLOAT16, dq_scale.shape, dq_scale
)
w_dq_scale_val = helper.make_tensor(
    "weight_scale", TensorProto.FLOAT16, weight_scale_arr.shape, weight_scale_arr
)


@script()
def quantized_conv_model(graph_in: INT8[1, 32, 96, 176]) -> FLOAT16[1, 64, 96, 176]:
    dq_scale = op.Constant(value=dq_scale_val)
    feature_dq = op.DequantizeLinear(graph_in, dq_scale)

    weight = op.Constant(value=conv_weight)

    wq_scale = op.Constant(value=w_dq_scale_val)
    wq = op.QuantizeLinear(weight, wq_scale)
    wdq = op.DequantizeLinear(wq, wq_scale)
    return op.Conv(X=feature_dq, W=wdq, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1])


# onnx_model is an in-memory ModelProto
onnx_model = quantized_conv_model.to_model_proto()
#onnx_model = shape_inference.infer_shapes(onnx_model)
# Save the ONNX model at a given path
onnx.save(onnx_model, "sample_mpdel.onnx")

# Check the model
try:
    onnx.checker.check_model(onnx_model)
except onnx.checker.ValidationError as e:
    print(f"The model is invalid: {e}")
else:
    print("The model is valid!")

# torch.nn.Conv1d
```

**Comment by SStarver** [comment]
> I ran the same code and got
> 
> `onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:DequantizeLinear, node name: n1): y has inconsistent type tensor(float)`
> 
> Using `onnx.checker.check_model(onnx_model, full_check=True)`

Thanks a lot, this is much helpful. I truely was unfamiliar with 'full_check=True' option.
With your suggestion, I think I can just focus on onnxscript, this issue can be closed.

**Comment by SStarver** [comment]
> I ran the same code and got
> 
> `onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:DequantizeLinear, node name: n1): y has inconsistent type tensor(float)`
> 
> Using `onnx.checker.check_model(onnx_model, full_check=True)`

> One more question, I construct a model which contains Dequantizelinear (opset 19) node with float16 output,  but when I tried to  do 'full_check' (or shape inferrence ) on that model, I got same exception. Is this resonable?  Why do shape inferrence always  deduce a float type for   Dequantizelinear's  output  thoung I seemingly already have a float16 output. 
Any ideas about this situation? 
I have gone through [onnx](https://github.com/onnx/onnx/tree/main)/[docs](https://github.com/onnx/onnx/tree/main/docs)
/ShapeInference.md , but haven't got the answer, do I miss anything in this doc?

- model  for test
[model.zip](https://github.com/onnx/onnx/files/11901476/model.zip)

- codes for checking model
```python
import onnx

mymodel = onnx.load('sample_mpdel.onnx')
onnx.checker.check_model(mymodel, full_check=True)
```

- codes for model construction in case of analysis need
```python
from onnxmltools.utils import float16_converter
import onnx

# We use ONNX opset 15 to define the function below.
from onnxscript import INT8, FLOAT, FLOAT
from onnxscript import opset19 as op
from onnxscript import script, tensor
import numpy as np
from onnx import helper, TensorProto, shape_inference
import torch
from torch import nn

'''
conv with q/dq
depwise conv with q/dq

'''
kernel_shape = [3, 3]
out_channels = 64
in_channels = 32
pads = [1, 1, 1, 1]
strides = [1, 1]
weight_data = np.random.random([64, 32, 3, 3]).astype(np.float32)
conv_weight = helper.make_tensor("conv.weight", TensorProto.FLOAT, (64, 32, 3, 3), weight_data)

dq_scale = np.float32([0.1])

weight_scale_arr = np.random.random([64]).astype(np.float32)
dq_scale_val = helper.make_tensor("feature_scale", TensorProto.FLOAT, dq_scale.shape, dq_scale)
w_dq_scale_val = helper.make_tensor(
    "weight_scale", TensorProto.FLOAT, weight_scale_arr.shape, weight_scale_arr
)


@script()
def quantized_conv_model(graph_in: INT8[1, 32, 96, 176]) -> FLOAT[1, 64, 96, 176]:
    dq_scale = op.Constant(value=dq_scale_val)
    feature_dq = op.DequantizeLinear(graph_in, dq_scale)

    weight = op.Constant(value=conv_weight)

    wq_scale = op.Constant(value=w_dq_scale_val)
    wq = op.QuantizeLinear(weight, wq_scale)
    wdq = op.DequantizeLinear(wq, wq_scale)
    return op.Conv(X=feature_dq, W=wdq, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1])


# onnx_model is an in-memory ModelProto
onnx_model = quantized_conv_model.to_model_proto()
onnx_model = shape_inference.infer_shapes(onnx_model)
trans_model = float16_converter.convert_float_to_float16(onnx_model, keep_io_types=False)
# Save the ONNX model at a given path
onnx.save(trans_model, "sample_mpdel.onnx")

# Check the model
try:
    onnx.checker.check_model(trans_model)
    # onnx.checker.check_model(trans_model, full_check=True)
except onnx.checker.ValidationError as e:
    print(f"The model is invalid: {e}")
else:
    print("The model is valid!")
```

**Comment by justinchuby** [comment]
That could potentially be a bug in shape inference code. Will look into this soon

**Comment by justinchuby** [comment]
Tested with the latest onnx-1.15.0 onnxmltools-1.12.0. Output is `The model is valid!`
