### ISSUE TITLE
Include instructions on how to update the documentation in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5379]
We have many PRs that tries to fix typos etc. in op documentation not knowing to regenerate documentation or otherwise did the change in the wrong place. We should document this in `CONTRIBUTING.md` and be able to point contributors to it in the ci.

Or do we have one somewhere already?

cc @jcwchen

**Comment by jcwchen** [comment]
Such a instruction can be found from here: https://github.com/onnx/onnx/blob/main/docs/CONTRIBUTING.md#generated-operator-documentation. BTW, there another undone work item to merge these 2 documents to prevent confusion
- https://github.com/onnx/onnx/blob/main/docs/CONTRIBUTING.md
- https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md
