### ISSUE TITLE
Constants are not written into onnx

### ISSUE THREAD

**Issue by lichunxiang93** [onnx/onnx#5386]
# Ask a Question

### Question
In the process of converting the model of the Transformer structure to onnx, the model conversion is successful and a large number of binary files are generated. However, the model has only one input. After converting to onnx, netron visualization also only has one input. However, when onnxruntime is loaded, constant inputs of werights and bias, cls_token, and add nodes of the layernorm layer are required. These are a large number of binary files generated when converting the model. This causes difficulties when using the inference of the onnx model and converting it to tensorRT. Is there a way to integrate these constants directly into onnx？

### Further information
Model Conversion Command
    cached_file = "/opt/dev/lichunxiang/codes/MiniGPT-4-main/weights/eva_vit_g.pth"
    state_dict = torch.load(cached_file, map_location="cpu")    
    interpolate_pos_embed(model,state_dict)
    incompatible_keys = model.load_state_dict(state_dict, strict=False)
    model.eval()
    dummy_input = Variable(torch.randn(1, 3, 224, 224, device='cpu'))
    input_name = ["input"]
    output_name = ["output"]
    ONNX_name = "./evit.onnx"
    torch.onnx.export(model, dummy_input, ONNX_name,
        verbose=True, input_names=input_name, output_names=output_name, export_params=True,do_constant_folding = True,
        opset_version=18,dynamic_axes={'input':{0:"batch_size"},'output':{0:"batch_size"}})
生成的部分二进制文件：
![image](https://github.com/onnx/onnx/assets/30490690/f82eb076-d033-42db-8e9f-4ac48cf9bb04)
![image](https://github.com/onnx/onnx/assets/30490690/fad8e3c9-d6b9-4f81-bdec-b691aab8e5af)

netron可视化结构：
![image](https://github.com/onnx/onnx/assets/30490690/6ce05e51-f6e9-4211-a9d1-1425237b239d)

加载模型报错：
raceback (most recent call last):
  File "/opt/dev/lichunxiang/codes/MiniGPT-4-main/minigpt4/models/onnx_utils.py", line 87, in <module>
    session = onnxruntime.InferenceSession(onnx_path)
  File "/opt/dev/lichunxiang/anaconda/envs/gpt/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/dev/lichunxiang/anaconda/envs/gpt/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Deserialize tensor blocks.22.norm1.weight failed.GetFileLength for ./blocks.22.norm1.weight failed:Invalid fd was supplied: -1

- Is this issue related to a specific model?
**Model name**: evit
**Model opset**: 11

**Comment by justinchuby** [comment]
You may consider using the new torch.onnx.dynamo_export exporter. For further support please raise the issue in the PyTorch repository. Thanks!
