### ISSUE TITLE
ReduceMean(opset 18):  axes input is empty and ‘noop_with_empty_axes’ is true, but ReduceMean does not act as an identity op.

### ISSUE THREAD

**Issue by LionelSummer** [onnx/onnx#5387]
ReduceMean(opset 18):  axes input is empty and ‘noop_with_empty_axes’ is true, but i found that ReduceMean does not act as an identity op.It reduces over all the dimensions of the input tensor.My sample code is as follows:
onnx version: 1.13.1
onnxruntime version: 1.14.1
Python 3.9.6
Windows platform

`import onnx
from onnx import helper, shape_inference
from onnx import AttributeProto, TensorProto, GraphProto

X = helper.make_tensor_value_info("X", TensorProto.FLOAT, [1, 3, 32, 64])
AXES = helper.make_tensor("axes", TensorProto.INT64, [0], [])

Y = helper.make_tensor_value_info("Y", TensorProto.FLOAT, [1, 3, 32, 64])

node_def = helper.make_node(
    "ReduceMean",  # name
    ["X", "axes"],  # inputs
    ["Y"],  # outputs
    noop_with_empty_axes=1,
)

graph_def = helper.make_graph(
    [node_def],  # nodes
    "test-model",  # name
    [X],  # inputs
    [Y],  # outputs
    initializer=[AXES],
)
model_def = helper.make_model(graph_def,
                              producer_name="onnx-example",
                              opset_imports=[helper.make_operatorsetid("", 18)]
                              )

inferred_model = shape_inference.infer_shapes(model_def)
onnx.checker.check_model(inferred_model)
onnx.save(inferred_model, "model.onnx")`

The reasoning results are as follows:
X.shape: (1, 3, 32, 64)
Y: [array([[[[15.192334]]]], dtype=float32)]
2 0 2 3 - 0 6 - 3 0   2 3 : 3 9 : 0 2 . 2 2 6 0 4 3 9   [ W : o n n x r u n t i m e : ,   e x e c u t i o n _ f r a m e . c c : 8 3 5   o n n x r u n t i m e : : E x e c u t i o n F r a m e : : V e r i f y O u t p u t S i z e s ]   E x p e c t e d   s h a p e   f r o m   m o d e l   o f   { 1 , 3 , 3 2 , 6 4 }   d o e s   n o t   m a t c h   a c t u a l   s h a p e   o f   { 1 , 1 , 1 , 1 }   f o r   o u t p u t   Y 

Why is the output dimension not (1, 3, 32, 64) ？

**Comment by justinchuby** [comment]
I suggest opening an issue with https://github.com/microsoft/onnxruntime because this seems specific to the runtime.

**Comment by LionelSummer** [comment]
ok.thanks.

**Comment by justinchuby** [comment]
https://github.com/microsoft/onnxruntime/issues/16586

**Comment by LionelSummer** [comment]
#> [microsoft/onnxruntime#16586](https://github.com/microsoft/onnxruntime/issues/16586)

After analyzing the source code implementation of the onnxruntime, noop_with_empty_axes takes effect only for the reducesum operator, and other reduce operators do not consume it. This does not comply with the API document of the onnx operator. Is that actually I should use your operator API document?

**Comment by justinchuby** [comment]
Documentation defined in this repo is the source of truth for backends. Any mistakes in the specs should be reported here though.
