### ISSUE TITLE
ONNX Stable Diffusion tensor names incompatible with hundreds of community SafeTensor customizations 😔

### ISSUE THREAD

**Issue by fdwr** [onnx/onnx#5406]
# Preface

The community has eagerly extended the base Stable Diffusion model by contributing hundreds of customizations (custom unet weights, custom text vocabulary embedding rows, unet low rank adaptation...) such as found on [https://civitai.com/](civit.ai) and [huggingface](https://huggingface.co/) (e.g. [I Can't Believe It's Not Photography](https://civitai.com/models/28059/icbinp-i-cant-believe-its-not-photography) or [Waifu Diffusion](https://huggingface.co/hakurei/waifu-diffusion) or [Rev Animated](https://civitai.com/models/7371) or many more...), which are far more popular now than the base SD model. However, all the ONNX exports from PyTorch so far (e.g. [1.4](https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/onnx/unet) and [1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/onnx/unet)) have radically different tensor names, making all the community contributions useless within the ONNX ecosystem because none of the names in the .safetensors map to corresponding ones in the .onnx file 😿.

This impacts cases like...
- Cassie Breviu's [C# ORT demo](https://devblogs.microsoft.com/dotnet/generate-ai-images-stable-diffusion-csharp-onnx-runtime/) ([code](https://github.com/cassiebreviu/StableDiffusion)) shown at Microsoft **//build**
- my little own C++/ORT/DML app (calling ORT's `SessionOptions::AddInitializer` to substitute the new tensor values from the .safetensors file, to no effect)
- [Axodox's UWP Unpaint App](https://github.com/axodox/unpaint) (C++/ORT/DML)
- Popular Web UI apps like [EasyDiffusion](https://github.com/easydiffusion/easydiffusion) (7 thousand ⭐'s) which recently added AMD GPU support via ONNX Runtime (but rather than just override the base model weights, it has to go all the way through the PyTorch convertor each time to regenerate a temporary .onnx file 😕).

### Question
Who on the ONNX consortium is the best contact to work with and drive community engagement for Stable Diffusion within the ONNX format, seeing this scenario work end-to-end? I realize this is ultimately probably more of a convertor issue (needing an issue here too https://github.com/pytorch/pytorch/issues), but I opened it here deliberately for visibility tracking in ONNX-land. Of course, it's not possible to have 100% mapping between PyTorch and ONNX in *all* cases and *all* models, since they have different operator overlap, but I suspect it *should* be possible in the case of SD (or at least have a much higher overlap than currently).

### Further information
- Relevant Area: transformer models, image generation

- Is this issue related to a specific model?
**Model name**: Stable Diffusion
**Model opset**: 14

### Notes
You can reproduce the issue with:

```
# Either download SD 1.5 PyTorch via browser to d:\SomeInputFolder, or clone it:
git clone https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main d:\SomeInputFolder

# Install Diffusers library.
git clone https://github.com/huggingface/diffusers

# Convert PyTorch to ONNX.
python diffusers\scripts\convert_stable_diffusion_checkpoint_to_onnx.py --output_path="d:\SomeOutputFolder" --model_path="d:\SomeInputFolder\StableDiffusion\1.5-float32-pytorch"
```

```
Python==3.10.6-64
torch==1.13.1
numpy==1.21.6
onnx==1.14.0
onnxruntime==1.14.1
```

Then look inside `unet\model.onnx` (via hex editor or [Netron](https://netron.app/)), and compare the initializer names to any of those in custom weight files (like `icbinpICantBelieveIts-relapse-unet-28059@civitai-baseSD1.5.safetensors`), and you'll see a great disconnect. 🔗💔

**Comment by fdwr** [comment]
FYI @cassiebreviu

**Comment by justinchuby** [comment]
I think this is more of a converter issue. We are working on the new converter which will preserve tensor names. @BowenBao @abock

**Comment by axodox** [comment]
It is also a question what happens when provider specific optimizers are used (which make ONNX performance much better, but import custom operators), e.g. when doing this: https://github.com/axodox/unpaint/wiki/Model-import

I have also built a converter / optimizer for ControlNet and ONNX, which I have integrated into axodox-machinelearning and unpaint, but the naming conventions are a problem there as well: https://github.com/axodox/Olive/tree/unpaint/examples/directml/stable_diffusion

**Comment by justinchuby** [comment]
The new exporter `torch.onnx.dynamo_export` will preserve tensor names:
![image](https://github.com/onnx/onnx/assets/11205048/b337e901-c514-4a0f-8e52-1782480b8668)

The best way to start playing with it is to install `torch-nightly` and from pip https://pypi.org/project/onnxscript-preview/.

**I also created a package for working with `safetensors` in ONNX:** https://github.com/justinchuby/onnx-safetensors. Please let me know if you experiment with it!

**Comment by justinchuby** [comment]
Considered done. Please let me know if this isn’t the case. Thanks!
