### ISSUE TITLE
[Feature request] LabelEncoder with Tensor attributes

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5412]
### What is the problem that this feature solves?

Since version 2 of the `ai.onnx.ml` opset, [LabelEncoder](https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md#aionnxmllabelencoder) has encoded its attributes as lists of specific type (e.g. `keys_int64s`, `keys_strings`, `keys_floats`) where only one "keys_*" attribute should be set and only one "values_*" attribute should be set. This arrangement prevents the use of [External Data](https://github.com/onnx/onnx/blob/main/docs/IR.md#external-tensor-data) which can be very beneficial for users with large LabelEncoders. It also enforces a very strict cross product of types for keys and values, a decision which has pros (explicitly defining the necessary pairings of key, value types to implement for backends) and cons (forces users to downcast/upcast to conform to the API).

### Describe the feature

Having 1D tensors attributes instead of lists would make for a cleaner API with just one `keys` and one `values` attribute. It would also enable the use of External Data for models with large label encoders. 

We can continue to retain the benefits of specifying strictly the cross product of key and value element types by specifying explicitly in the standard what type of tensors are permitted, thereby not suddenly permitting every possible LabelEncoder implementation.

### Will this influence the current api (Y/N)?

Yes - it would require an opset bump for `ai.onnx.ml`.

### Feature Area

Operators

### Are you willing to contribute it (Y/N)

Yes

**Comment by xadupre** [comment]
Something similar was done for TreeEnsemble* operators. New attributes were added suffixed by `_as_tensor` (current attributes were kept). Would that work for you? Would you like to contribute?

**Comment by adityagoel4512** [comment]
Thanks for the tip. I've created a PR.

It looks like the version converter infrastructure isn't set up to support anything other than the default domain. I'm going to implement this in a follow up PR.
