### ISSUE TITLE
I want to konw which version and this version'time i can bulid in my ppc64le cpu. How can i find them?

### ISSUE THREAD

**Issue by miaowahexiaohuolong** [onnx/onnx#5414]
I want to konw which version and this version'time i can bulid in my ppc64le cpu. How can i find them?

**Comment by jcwchen** [comment]
Hi @miaowahexiaohuolong,
There is not prebuilt wheel for ppc64le on PyPI. But 1.14.0 seems worked from https://anaconda.org/conda-forge/onnx/files. You can follow the steps mentioned in https://github.com/onnx/onnx#linux to build onnx from source.
