### ISSUE TITLE
Adding output type attribute to QuantizeLinear

### ISSUE THREAD

**Issue by yuanyao-nv** [onnx/onnx#5418]
### What is the problem that this feature solves?

Currently, `QuantizeLinear` relies on `y_zero_point` to figure out the output data type. However, since PyTorch doesn't support FP8 yet, there is no way to define an FP8 tensor and one would have to do post-processing on the exported ONNX files to achieve FP8 quantization. It's unclear when PyTorch will officially support FP8. Adding an optional `output_type` attribute allows one to more easily do FP8 quantization.

### Describe the feature

Add an optional attribute `output_type` to `QuantizeLinear`.

### Feature Area

Operators

### Are you willing to contribute it (Y/N)

Yes

**Comment by xadupre** [comment]
Maybe I already asked this question in a meeting. Is it possible to replace it by a sequence `Cast(0, to=TensorProto.FLOAT8E4M3FN) -> zero` followed by `QuantizeLinear(x, scale, zero) -> ...`?

**Comment by nzmora-nvidia** [comment]
Hi @xadupre,
I am not able to do that using Torch's ONNX exporter (I think because of schema validation) - see [this code](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/te_onnx_extensions.py#L84) for example. OTOH, there's no validation when we use an unsupported/proprietary operator attribute such as `output_type`.

**Comment by justinchuby** [comment]
There is a way to modify the PyTorch source and add the nodes, but I think operating on the ONNX graph is easier. Would https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon#graph help for now? cc @shubhambhokare1 @BowenBao on graph transforms.

**Comment by nzmora-nvidia** [comment]
I don't follow your question @xadupre: zp has the quantized type; and scale has the high-precision type. What do we gain by changing this definition?

**Comment by yuanyao-nv** [comment]
PyTorch has added [FP8 ](https://github.com/pytorch/pytorch/pull/104242) so additional output type attribute is no longer necessary here. Closing this ticket. 
Thanks for the input, everyone!
