### ISSUE TITLE
Add multi-device support to ONNX

### ISSUE THREAD

**Issue by yuanyao-nv** [onnx/onnx#5419]
### What is the problem that this feature solves?

Currently ONNX doesn't have a way of encoding how a model can be parallelized across multiple devices.

### Describe the feature

A proposal was presented at the ONNX community meetup in June 2023: https://youtu.be/3t0PGSWsBhQ

There are three things that would need to be added:
1. Add optional fileds `tile_pattern` and `tile_assignment` to TensorProto which describe how a tensor is split up and how the individual slices are distributed across devices.
2. New ONNX operators `InstanceSplit` and `InstanceJoin` to give more granular control over cross-device communications.
3. Add a `topology` field to model proto that describes the network topology of the devices.

Note that these three do not have to be incorporated into the ONNX spec at the same time.

### Feature Area

Model usage.

### Are you willing to contribute it (Y/N)

Yes

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> Currently ONNX doesn't have a way of encoding how a model can be parallelized across multiple devices.

Yes I think parallel model across devices includes two dimension <StageId, SubgraphId>:

1. how a graph is partitioned to subgraphs : `[subgraph_0, subgraph_1, ...]`
2. how subgraphs are placed onto devices : `[ [subgraph_0, subgraph_M], [subgraph_1], [subgraph_2, subgraph_3], ...]`

Currently onnx only supports the first concept by creating subgraphs, but we also need placement description of subgraphs.
The relationship between subgraph and device is M : 1 relationship.

But usually we perform the second optimization in local IR which is more friendly to the target devices.

Doing this is possible in ONNX, but this requires changes on how we lowering ONNX graph. It must requires support of ONNX device backend, while many framework just treats ONNX as model descriptions and perform some useful ONNX passes, graph surgery operations before lowering to local IR system.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
One thing I want to say is, multi-device support is more like specific, different backend has its own strategy to do the partition. You can add some attributes to the node to annotate node manually. The backend due to its budget of resources, may ignore and adjust it. 

A wrapper upon top of ONNX with device specific information maybe required. @cbourjau
