### ISSUE TITLE
[Feature request] how to use it in offline application

### ISSUE THREAD

**Issue by zooeyking** [onnx/onnx#5421]
### System information

1.15.0

### What is the problem that this feature solves?

my application used in an offline environment,  i try it by document  like this 
![image](https://github.com/onnx/onnx/assets/16650705/f8351f97-989e-4421-94ab-49981866ebec)
it work well in dev environment, by i start server by "npm run start" to boot an local serve.   while i need my application worked in offline environment.  after i build it, i click index.html open it by chrome,  something is wrong.  
![image](https://github.com/onnx/onnx/assets/16650705/ae65d8e1-28e2-469f-b8eb-8c42cfb333be)
i try to solve it, i fond that the code need to fetch the model.onnx or some other xxx.wams file.  but the fetch need local serve, otherwise the chrome's cors policy will forbidden this file.
i can"t find a right way to resolve it.

### Will this influence the current api (Y/N)?

n

### Are you willing to contribute it (Y/N)

None

**Comment by zooeyking** [comment]
maybe i need a webpack-loader to read these file, but it is too hard for me. can you give me some tips to solve it.

**Comment by justinchuby** [comment]
https://github.com/microsoft/onnxjs/blob/master/docs/migration-to-ort-web.md this may be relavent as onnxjs is no longer supported. You may post further questions to the onnxruntime repository. Thanks!

**Comment by zooeyking** [comment]
> https://github.com/microsoft/onnxjs/blob/master/docs/migration-to-ort-web.md this may be relavent as onnxjs is no longer supported. You may post further questions to the onnxruntime repository. Thanks!

thanks
