### ISSUE TITLE
Onnx does not have any objects

### ISSUE THREAD

**Issue by OnlySoaring** [onnx/onnx#5423]
# Ask a Question

### Question
I just want to upgrade my onnx1.8.1 to 1.14.1. But when I import onnx and print the onnx.__version__, it tell me  module 'onnx' has no attribute '__version__'. Of course “export","load_model" dont work too. I dont know what happened.

### Further information
I try to pip uninstall,install,upgrade,delete the onnx in site-packages. I try to reinstall 1.8, 1.10, 1.12, 1.14. It's completely useless
I dont want to build a new python env, I want know how to repair it.
My onnx is break.  :((((
please help me

**Comment by justinchuby** [comment]
Try `onnx.__version__`? Can you post the full script show what doesn’t work for you?

**Comment by OnlySoaring** [comment]
> Contributor
of course
![企业微信截图_16896426071888](https://github.com/onnx/onnx/assets/136061683/1cfa57d2-1b97-4db4-b47c-332775e5fa4f)

**Comment by justinchuby** [comment]
Your onnx installation is likely broken. I would try reinstalling it.

**Comment by OnlySoaring** [comment]
> Your onnx installation is likely broken. I would try reinstalling it.

![企业微信截图_16896440906191](https://github.com/onnx/onnx/assets/136061683/e20cf02f-e445-43a9-8006-6a355cf68334)
I have already tried

**Comment by xadupre** [comment]
Do you have a folder `onnx`? It is now considered as a possible candidate for `import` even if there is no `__init__.py` in it.

**Comment by OnlySoaring** [comment]
ok, this is anaconda's bug. I must go to anaconda/envs/<your env>/bin/ and use ./pip to install onnx. If use pip to install onnx,python will not be bale to find onnx path,even if the pip does correspond to your Python and there is an onnx folder in the site package.
