### ISSUE TITLE
-std=gnu++14 by default?

### ISSUE THREAD

**Issue by jiapei100** [onnx/onnx#5430]
# Ask a Question

### Question
Whenever I tried to use **cmake/ccmake** to build **onnx**, I obtained the following **ERROR** message:

```console
......
[ 12%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o
/usr/bin/c++ -DONNX_API="__attribute__((__visibility__(\"default\")))" -DONNX_ML=1 -DONNX_NAMESPACE=onnx -D__STDC_FORMAT_MACROS -Donnx_proto_EXPORTS -I....../onnx/build -std=c++17 -fPIC -Wnon-virtual-dtor -O3 -DNDEBUG -std=gnu++14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o -MF CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o.d -o CMakeFiles/onnx_proto.dir/onnx/onnx-operators-ml.pb.cc.o -c ....../onnx/build/onnx/onnx-operators-ml.pb.cc
/usr/bin/c++ -DONNX_API="__attribute__((__visibility__(\"default\")))" -DONNX_ML=1 -DONNX_NAMESPACE=onnx -D__STDC_FORMAT_MACROS -Donnx_proto_EXPORTS -I....../onnx/build -std=c++17 -fPIC -Wnon-virtual-dtor -O3 -DNDEBUG -std=gnu++14 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o -MF CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o.d -o CMakeFiles/onnx_proto.dir/onnx/onnx-data.pb.cc.o -c ....../onnx/build/onnx/onnx-data.pb.cc
In file included from /usr/local/include/google/protobuf/stubs/common.h:44,
                 from /usr/local/include/google/protobuf/io/coded_stream.h:130,
                 from ....../onnx/build/onnx/onnx-data.pb.h:24,
                 from ....../onnx/build/onnx/onnx-data.pb.cc:4:
/usr/local/include/absl/strings/string_view.h:52:26: error: ‘string_view’ in namespace ‘std’ does not name a type
   52 | using string_view = std::string_view;
      |                          ^~~~~~~~~~~
/usr/local/include/absl/strings/string_view.h:52:21: note: ‘std::string_view’ is only available from C++17 onwards
   52 | using string_view = std::string_view;
      |                     ^~~
                   ^~~
......
```

### Further information
As you can see from the above **ERROR** message, I explicitly did **-std=c++17**, there is an extra **-std=gnu++14** added by default. 

By manually remove this **-std=gnu++14** and do **make** directly, **onnx** successfully built. However, whenever I configure **onnx** again with **cmake/ccmake**, this **-std=gnu++14** would be added again automatically, which is quite annoying.

- Is this issue related to a specific model?
Not a model issue, looks like an issue of **the default C++ version in cmake** ?

### Notes
Is there a way to **avoid adding `-std=gnu++14`** but only consider my **explicity emphasized `-std=c++17`**  ?

**Comment by xadupre** [comment]
Did you try something like this `set(CMAKE_CXX_STANDARD 17)`?

**Comment by jcwchen** [comment]
CMAKE_CXX_STANDARD was fixed as 14 for non-Windows before and this recent PR https://github.com/onnx/onnx/pull/5355 enabled users to manually set `CMAKE_CXX_STANDARD` before build. The main branch has included that improvement.
