### ISSUE TITLE
onnx maxpool padding interpretation

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#544]
I have an  onnx model with a Maxpool node  with padding value set as ,  pads: 0,0,1,2 for input  Tensor (NxCxWxH)
How do I interpret the padding?

Is the padding (0,1) applied to W and  (0,2) applied to H ?
Interpretation:
0 ,           0,             1,          2
start_W, start _H   end_W  end_H

**Comment by bddppq** [comment]
onnx uses NCHW as the Tensor storage format, and `pads` format should be `[x1_begin, x2_begin...x1_end, x2_end,...]`, so in your case the interpretation should be:

`start_H = 0`
`start_W = 0`
`end_H = 1`
`end_W = 2`

**Comment by spidyDev** [comment]
@bddppq  Thanks.

For non image format : (N x C x D1 x D2 ... Dn)    and pads = [x1_begin, x2_begin...x1_end, x2_end,...]
```
 D1 = x1_begin
D2 = x2 begin
.
.
```
Is this correct ?

**Comment by houseroad** [comment]
Yes, you are right, no padding on N and C dimensions

**Comment by spidyDev** [comment]
Thanks
