### ISSUE TITLE
`helper.make_attribute` should print attribute names in error messages

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5442]
https://github.com/onnx/onnx/blob/9a17d4d64c210b86107e152d98539fc93aa8f329/onnx/helper.py#L911

prints the enum as ints: `TypeError: Inferred attribute type 2 mismatched with specified type 1`, which is not very readable. We should print the enum names instead.

**Comment by ClifHouck** [comment]
Going to take a look at this.
