### ISSUE TITLE
If ScatterElements document  of reduction mode needs update?

### ISSUE THREAD

**Issue by zhenhuaw-me** [onnx/onnx#5443]
The [document](https://github.com/onnx/onnx/blob/ce6257a/docs/Operators.md#scatterelements) says that:

> When reduction is set to some reduction function f, the update corresponding to the [i][j] entry is performed as below:

```
output[indices[i][j]][j] += f(output[indices[i][j]][j], updates[i][j]) if axis = 0,
output[i][indices[i][j]] += f(output[i][indices[i][j]], updates[i][j]) if axis = 1,
```

Should it be like (change `+=` to `=`)?
```
output[indices[i][j]][j] = f(output[indices[i][j]][j], updates[i][j]) if axis = 0,
output[i][indices[i][j]] = f(output[i][indices[i][j]], updates[i][j]) if axis = 1,
```

In [Torch doc](https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_): 

> Given a 3-D tensor and reduction using the multiplication operation, self is updated as:

```
self[index[i][j][k]][j][k] *= src[i][j][k]  # if dim == 0
self[i][index[i][j][k]][k] *= src[i][j][k]  # if dim == 1
self[i][j][index[i][j][k]] *= src[i][j][k]  # if dim == 2
```

@onnx/sig-operators

**Comment by xadupre** [comment]
Yes you are right, += needs to be replaced by =. Would you like to contribute?

**Comment by zhenhuaw-me** [comment]
Close as the fix https://github.com/onnx/onnx/pull/5446 has been merged.
