### ISSUE TITLE
infer_shapes does not produce shapes for all edges (Slice operator)

### ISSUE THREAD

**Issue by kshpv** [onnx/onnx#5444]
# Bug Report

### Describe the bug
After calling the `shape_inference` on the model, not all edges have any shape information.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Ubuntu 20.04
- ONNX version : 1.13 - 1.14
- Python version: 3.8.10

### Reproduction instructions

```
import onnx
model = onnx.load_model('shufflenet_v2_x1_0.onnx')
infered_model = onnx.shape_inference.infer_shapes(model, data_prop=True)
for v_i in infered_model.graph.value_info:
    if v_i.name == '/stage2/stage2.1/Slice_1_output_0':
        print (v_i)
```
Output:
```
name: "/stage2/stage2.1/Slice_1_output_0"
type {
  tensor_type {
    elem_type: 1
  }
}
```

### Expected behavior
```
name: "/stage2/stage2.1/Slice_1_output_0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: X_1
      }
      dim {
        dim_value: X_2
      }
      dim {
        dim_value: X_3
      }
      dim {
        dim_value: X_4
      }
    }
  }
}
```

### Model
[shufflenet_v2_x1_0.zip](https://github.com/onnx/onnx/files/12166160/shufflenet_v2_x1_0.zip)

**Comment by xadupre** [comment]
In this model, operator Slice has constants inputs and dynamic inputs. The dynamic inputs are usually not known. It would require the execution of a few nodes. And only then it would be possible to infer the output shape. That's one limitation of the shape inference algorithm as it is implemented right now.

**Comment by kshpv** [comment]
Hi @xadupre! 
If I run shape inference on the model, then I can get the dimension of the input edges of Slice node. Please, take a look at the screenshot.
![image](https://github.com/onnx/onnx/assets/32935044/7312febc-f330-4db1-a3c0-32ebf5b874d4)

If there are constant shapes of input nodes, is it possible to get the output shape of that node?

**Comment by xadupre** [comment]
It is true the shape of every input is known in this example but the dimension of the output of operator Slice depends on the value of starts and ends, not only the shape. Shape inference only knows there is one integer but does not know it and the output shape is `ends[0] - starts[0]` on axis 1.

**Comment by kshpv** [comment]
@xadupre 
Can we say that the output shape will be `[1, unk_1, 28, 28]`?
Want to repeat my other question - I thought that every edge has to have a shape whether dynamic or static after `infer_shapes`. Is it the correct expectation?

Thank you!

**Comment by xadupre** [comment]
In your case, that should be doable but it is not implemented: https://github.com/onnx/onnx/blob/main/onnx/defs/tensor/defs.cc#L1057. The shape inference implemented in onnxruntime may be more accurate: https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/symbolic_shape_infer.py. It relies on sympy to deal with unknown variables.

**Comment by kshpv** [comment]
I tried `onnxruntime` approach and it works fine for this particular model.
Thank you!

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it if needed.
