### ISSUE TITLE
[Feature request] Promote `axis` in `DFT` to dynamic

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5447]
### System information

1.15dev

### What is the problem that this feature solves?

PyTorch accepts a dynamic list (https://github.com/pytorch/pytorch/blob/e773f28ee307e2a246a4b765f3a51117661b45ba/aten/src/ATen/native/native_functions.yaml#L2914) of axes as input to its `_fft_c2c` operator. Currently `DFT-17` requires `axis` to be static (https://onnx.ai/onnx/operators/onnx__DFT.html). To fully support `_fft_c2c` we need axis to be dynamic in `DFT`.

With this we are also able to express a n-d DFT with functions (with a loop inside).

### Will this influence the current api (Y/N)?

N

### Feature Area

operators

### Are you willing to contribute it (Y/N)

Yes

**Comment by xadupre** [comment]
Technically, it is possible to go around that (see https://github.com/microsoft/onnxscript/blob/main/onnxscript/tests/models/signal_dft.py#L309).
