### ISSUE TITLE
ONNX model issue: RUNTIME_EXCEPTION : Non-zero status code returned while running _DCNv2 node. Name:'_DCNv2_95' Status Message: TypeError: symbolic() missing 1 required positional argument: 'g'

### ISSUE THREAD

**Issue by SathwikaNandimadalam** [onnx/onnx#5458]
# RUNTIME_EXCEPTION : Non-zero status code returned while running _DCNv2 node. Name:'_DCNv2_95' Status Message: TypeError: symbolic() missing 1 required positional argument: 'g'
I have converted my model to onnx. in my model i have custom operator DCNv2 i have given that like this 

```
class _DCNv2(Function):
    @staticmethod
    def symbolic(g, input, offset_mask, weight, bias, stride, padding, dilation, deformable_groups):
        return g.op("ai.onnx.contrib::_DCNv2", input, offset_mask, weight, bias, name_s="DCNv2", info_s=json.dumps({
            "dilation": dilation,
            "padding": padding,
            "stride": stride,
            "deformable_groups": deformable_groups
        }))
    sym_registry.register_op("DCNv2", symbolic, "", 13)
    #register_custom_op_symbolic('ai.onnx.contrib::_DCNv2', symbolic, 13)

    @staticmethod
    def forward(ctx, input, offset_mask, weight, bias,
                stride, padding, dilation, deformable_groups):
        ctx.stride = _pair(stride)
        ctx.padding = _pair(padding)
        ctx.dilation = _pair(dilation)
        ctx.kernel_size = _pair(weight.shape[2:4])
        ctx.deformable_groups = deformable_groups

        o1, o2, mask = torch.chunk(offset_mask, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)

        output = _backend.dcn_v2_forward(input, weight, bias,offset, mask,ctx.kernel_size[0], 
                                         ctx.kernel_size[1],ctx.stride[0], ctx.stride[1],ctx.padding[0], 
                                         ctx.padding[1],ctx.dilation[0], ctx.dilation[1],
                                         ctx.deformable_groups)
        ctx.save_for_backward(input, offset, mask, weight, bias)
        return output
        
```
This symbolic function is our custom operator .

To convert my model to onnx:
```
torch.onnx.export(
           self.model, input_data, f="/workspace/centerfusion_python/CenterFusion/src/onnx/model_cal4.onnx",
           input_names=["input", "a", "pc_dep", "calib"], output_names=["hm", "reg", "wh", "dep", "rot", "dim", "amodel_offset", "pc_hm", "velocity", "nuscenes_att", "dep_sec", "rot_sec"], verbose=True,
           custom_opsets={"ai.onnx.contrib": 13}
        )
```
when i am converting i need to pass only 3 inputs but when i am passing this input_names=["input",  "pc_dep", "calib"] it is not taking the value of pc_dep  instead pc_dep is taking calib value and calib is showing none so i have given that input as ["input", "a", "pc_dep", "calib"] when i am passing a as an torch.tensor(0) then it was successfully converted to onnx model. In the onnx model i need to have 3 inputs but it has only 2 inputs it has taken calib as constant.

to make DCNv2 register in onnxruntime :
```
@onnx_op(op_type='_DCNv2', domain='ai.onnx.contrib',
        inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float], outputs=[PyCustomOpDef.dt_float])
    def symbolic(g, input, offset_mask, weight, bias, stride=1, padding=1, dilation=1, deformable_groups=1):
        return g.op("ai.onnx.contrib::_DCNv2", input, offset_mask, weight, bias, name_s="DCNv2", info_s=json.dumps({
            "dilation": dilation,
            "padding": padding,
            "stride": stride,
            "deformable_groups": deformable_groups
        }))
so = onnxruntime.SessionOptions()
so.register_custom_ops_library(_get_library_path())
self.model = onnxruntime.InferenceSession("./onnx/model_cal3.onnx", so)
```

In the inference it is giving an error as follows:
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running _DCNv2 node. Name:'_DCNv2_95' Status Message: TypeError: symbolic() missing 1 required positional argument: 'bias'

(Note:In the symbolic function: **symbolic(g, input, offset_mask, weight, bias, stride, padding, dilation, deformable_groups):** we need to pass 4 inputs but it is taking g as parameter and raising the above error)

### System information

- OS Platform and Distribution :20.04
- ONNX version :1.11.0
- ONNXruntime:1.14.1
- Python version:3.7.12
- Protobuf version:3.19.1

@askhade 
@prabhuiitdhn

**Comment by wenbingl** [comment]
onnx_op is a decorator for Python function which can implement the ONNX op which doesn't have C++ implementation. So it's not the symblic function to create a function node.

Check this doc for details: https://github.com/microsoft/onnxruntime-extensions/blob/main/docs/pyop.md

**Comment by SathwikaNandimadalam** [comment]
Hi wenbingl and xadupre ,thank you for your replies.
i have tried the above link but it is raising another error
when i am passing this 
```
@onnx_op(op_type='_DCNv2', domain='ai.onnx.contrib',
        inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float], 
        outputs=[PyCustomOpDef.dt_float]
        attrs={"info_s": PyCustomOpDef.dt_int64 , "name_s": PyCustomOpDef.dt_string})
    
    def _DCNv2(input, offset_mask, weight, bias, stride=1, padding=1, dilation=1, deformable_groups=1):
        #g = onnx.helper.printable_graph("ai.onnx.contrib::_DCNv2")
        # name="DCNv2"
        #return input, offset_mask, weight, bias, dilation, padding, stride, deformable_groups
        name_s ="DCNv2"
        info_s=json.dumps({"dilation": dilation,
                          "padding": padding,
                          "stride": stride,
                          "deformable_groups": deformable_groups
                            })
        return input, offset_mask, weight, bias, name_s, info_s
```
it is throwing this error that:
 File "/workspace/centerfusion_python/CenterFusion/src/lib/detector.py", line 52
    attrs={"info_s": PyCustomOpDef.dt_int64, "name_s": PyCustomOpDef.dt_string})
        ^
SyntaxError: invalid syntax

**Comment by xadupre** [comment]
I think one comma is missing in your code: `outputs=[PyCustomOpDef.dt_float]` **,**

**Comment by SathwikaNandimadalam** [comment]
Thank you for your reply @xadupre .

i am actually facing this error,

File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: Unable to find attribute 'info' due to 'Attibute name and type don't match'.

```
@onnx_op(op_type='_DCNv2', domain='ai.onnx.contrib',
        inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float], 
        outputs=[PyCustomOpDef.dt_float],
        attrs={"info": PyCustomOpDef.dt_int64, "name": PyCustomOpDef.dt_string})
    
    def _DCNv2(input, offset_mask, weight, bias, stride=1, padding=1, dilation=1, deformable_groups=1):
        name_s ="DCNv2"
        info_s=json.dumps({"dilation": dilation,
                          "padding": padding,
                          "stride": stride,
                          "deformable_groups": deformable_groups
                            })
        return input, offset_mask, weight, bias, name_s, info_s
```

here in my model the DCNv2 node is like this 
![image](https://github.com/onnx/onnx/assets/124979758/c773117d-0ebf-4e6e-a394-a40872d89c9d)

in attributes i have info which is a dictionary how can i define this type like this "info": PyCustomOpDef.dt_int64

**Comment by wenbingl** [comment]
> Thank you for your reply @xadupre .
> 
> i am actually facing this error,
> 
> File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session sess.initialize_session(providers, provider_options, disabled_optimizers) onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: Unable to find attribute 'info' due to 'Attibute name and type don't match'.
> 
> ```
> @onnx_op(op_type='_DCNv2', domain='ai.onnx.contrib',
>         inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float], 
>         outputs=[PyCustomOpDef.dt_float],
>         attrs={"info": PyCustomOpDef.dt_int64, "name": PyCustomOpDef.dt_string})
>     
>     def _DCNv2(input, offset_mask, weight, bias, stride=1, padding=1, dilation=1, deformable_groups=1):
>         name_s ="DCNv2"
>         info_s=json.dumps({"dilation": dilation,
>                           "padding": padding,
>                           "stride": stride,
>                           "deformable_groups": deformable_groups
>                             })
>         return input, offset_mask, weight, bias, name_s, info_s
> ```
> 
> here in my model the DCNv2 node is like this ![image](https://user-images.githubusercontent.com/124979758/258751509-c773117d-0ebf-4e6e-a394-a40872d89c9d.png)
> 
> in attributes i have info which is a dictionary how can i define this type like this "info": PyCustomOpDef.dt_int64

PyCustomOpDef.dt_int64 is a integer tensor. In your case, you can specify 'info' as PyCustomOpDef.dt_string, and then decoding the string to dict by yourself.

**Comment by SathwikaNandimadalam** [comment]
Hi @wenbingl ,

i have tried by giving info as PyCustomOpDef.dt_string 
```
def _DCNv2(input, offset_mask, weight, bias, stride=1, padding=1, dilation=1, deformable_groups=1):
        name ="DCNv2"
        info=json.dumps({"dilation": dilation,
                          "padding": padding,
                          "stride": stride,
                          "deformable_groups": deformable_groups
                            })
        return input, offset_mask, weight, bias, name, info
```

but it is throwing this error
File "/workspace/centerfusion_python/CenterFusion/src/lib/detector.py", line 401, in process
    output = self.model.run(output_names,{'input': images.cpu().numpy(),'pc_dep': pc_dep.cpu().numpy()})[0]
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running _DCNv2 node. Name:'_DCNv2_95' Status Message: TypeError: _DCNv2() got an unexpected keyword argument 'info'
