### ISSUE TITLE
Is pow's test case wrong? 

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#546]
https://github.com/onnx/onnx/blob/6270bb68c54647f6c9ca56d640a73fe2dec2ad80/onnx/backend/test/case/node/pow.py#L49-L60

The case above seems wrong.
As [docs](https://github.com/onnx/onnx/blob/master/docs/Operators.md#pow) says, 
```
If necessary the right-hand-side argument will be broadcasted to match the shape of left-hand-side argument. 
When broadcasting is specified, the second tensor can either be of size 1 (a scalar value), or having its shape as a contiguous subset of the first tensor's shape. 
The starting of the mutually equal shape is specified by the argument "axis", and if it is not set, suffix matching is assumed. 1-dim expansion doesn't work yet.
```

So in this case, shape of `x` is (2, 3), `axis=0`, then shape of `y` should be in `((2,), (2,3))`.
But shape of `y = np.array([2, 3, 4]).astype(np.float32)` is (3,).

Did I miss something?
If not, I will create a pr to fix this.

**Comment by houseroad** [comment]
@fumihwh yes, you are right. Good catch! Please create a PR to fix this, thanks!

**Comment by houseroad** [comment]
Fixed in https://github.com/onnx/onnx/pull/548. Thanks!
