### ISSUE TITLE
Is it possible to load an ONNX model that only includes graph nodes(exclude initializers)

### ISSUE THREAD

**Issue by yiliu30** [onnx/onnx#5464]
# Ask a Question

### Question
As the LLM (Large Language Model) is quite large (100+ GB), loading all initializers into the RAM becomes challenging. However, there is a need to inspect the graph structure of the model. Is it possible to load an ONNX model that includes only graph nodes and excludes initializers to address this issue?

### Further information
- Relevant Area: model usage, best practices

**Comment by jcwchen** [comment]
Hi @yiliu30,
Technically yes, you can set load_external_data=False while `onnx.load` to prevent loading models with large external initializers:
https://github.com/onnx/onnx/blob/0d68f4995a49a62f4bccd69c83edf4f3d4dcf2b2/onnx/__init__.py#L200-L203

BTW, `convert_model_to_external_data` can help convert your model's large initializer to external data:
https://github.com/onnx/onnx/blob/0d68f4995a49a62f4bccd69c83edf4f3d4dcf2b2/onnx/external_data_helper.py#L102

**Comment by yiliu30** [comment]
Thank you for your guidance. It works for me. :)
