### ISSUE TITLE
Can ONNX handle a task-incremental model?

### ISSUE THREAD

**Issue by Parsifal133** [onnx/onnx#5465]
# Ask a Question

### Question
Can ONNX handle a task-incremental model? I got a task-incremental model, it requires a task-ID ( int number) in inference, and this task ID  can determine which branch to use when inferencing. The parameters of each branch are independent of each other. However, when exporting an ONNX model, only part of the model structure (branch) can be traced at a time. How can I export the complete model structure, i.e. all task branches?

### Further information
- Relevant Area: continual learning

Here is my code: the module to be exported 

    def forward(self, x, task_id, task_type='LORA'):
        if task_id == 0:
            # pretrain model
            return self.act(self.bn[task_id]((self.conv(x))))
        print(f'layer index :{task_id - 1}')

        if task_type == 'LORA':
            conv_out = self.conv(x) + self.eft[task_id - 1](x)
        else:
            conv_out = self.eft[task_id - 1](self.conv(x))
        # print(f'bn layer index :{task_id}')
        return self.act(self.bn[task_id](conv_out))

**Comment by xadupre** [comment]
I assume this question is related to torch exporter. The exporter retains the execution path, one fixed task_id and task_type. It is technically possible to express the logic you describe with onnx operators. But it can be tricky to implement from the exporter point of view. cc @thiagocrepaldi

**Comment by Parsifal133** [comment]
Thanks for the reply. The problem has been solved by means of optimising the forward method.
