### ISSUE TITLE
Default tensor attributes

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5467]
# Ask a Question

### Question
Currently it is not really possible to have a default tensor attribute where we may want to have a different default value depending on some logic available at build time. Is it worth making it possible to "infer" a default attribute?

### Further information
More context can be found in https://github.com/onnx/onnx/pull/5453. Here, it would be nice if we could have a default value for the `default_as_tensor` attribute in case the user does not specify it. This is straightforward for attributes with fixed element types like `default_int64` but for a default  `default_as_tensor`, we really need to be able to inspect the element type of the `values_*` attributes (one of which is required) and then produce an appropriately typed default. This should technically be feasible, however because this influences how documentation is automatically generated it is not completely straightforward to do.

### Notes

Simply editing the InferenceContext's `attributesByName_` within the shape inference pass has a couple of drawbacks:
- `attributesByName_` stores `const AttributeProto*`s and ownership is not clear so I'm not sure you can safely just add a new AttributeProto in its place
- We still need to update documentation cohesively

I'm happy to provide a PR for this, canvassing thoughts first.

**Comment by xadupre** [comment]
Can you add a concrete example on how you would like to describe a node LabelEncoder with such logic?

**Comment by adityagoel4512** [comment]
I've got a proposal in https://github.com/adityagoel4512/onnx/commit/bd774714213fd87d545987568cd0fd1c5d9dce77. The user just needs to provide a lambda that builds the desired default and a [human readable](https://github.com/adityagoel4512/onnx/commit/bd774714213fd87d545987568cd0fd1c5d9dce77#diff-cf90e45168824f70d9af1f90cd777a4542f2637bb4f3871542679c1a0a204b82R396) explanation of the default behaviour which makes its way through to the documentation via the `doc_string` AttributeProto attribute.
