### ISSUE TITLE
pytorch to onnx

### ISSUE THREAD

**Issue by QZZZZZYF** [onnx/onnx#5471]
RuntimeError: Exporting the operator repeat_interleave to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by jcwchen** [comment]
Hi @QZZZZZYF,
It should be a question for the converter (torch.onnx.export). repeat_interleave seems supported by the latest exporter: https://github.com/pytorch/pytorch/issues/39067. Are you using the latest PyTorch? Or have you tried higher opset_version?

**Comment by QZZZZZYF** [comment]
I have tried Pytorch versions 1.12 and 2.00, opset_ Version 11, 12. But there is still an error reported.

**Comment by justinchuby** [comment]
Thanks for the info - could you open an issue in the PyTorch repository? Be sure to include the full error stack which will help a lot.
