### ISSUE TITLE
Document `perm` in `Transpose` need to have the same length as the input rank

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5481]
https://onnx.ai/onnx/operators/onnx__Transpose.html does not specify if the `perm` attribute need to have length `rank(input)`. It does not define the behavior if `len(perm) != rank(input)`.

Related: https://github.com/microsoft/onnxruntime/pull/17041

cc @gramalingam

**Comment by gramalingam** [comment]
Yes, if the attribute is specified, it should have the same length as the rank. (Of course, it makes sense for a runtime to check and validate this, since that is better than crashing unexpectedly.)
