### ISSUE TITLE
Shape Inference code assumes that FunctionProto attribute has an entry for every attribute_proto entries

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#5482]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
To resolve ref_attribute names within `FunctionProto` nodes, the code builds a map name -> `AttributeProto`.
To do so it iterates over `attribute` entries and then queries `attribute_proto` entries. However, in this case a single attribute is represented by attribute_proto entry alone. The resulting resolution map is empty.

The [offending code ](https://github.com/onnx/onnx/blob/v1.14.0/onnx/shape_inference/implementation.cc#L598)in 1.14.

Thus, instead of resolving the ref attribute name, it removes a required attribute. In this specific case, it was `Constant` node that has `value_float` ref attribute name.

According to ONNX proto file, only one of the `attribute` or `attribute_proto`[ should represent the attribute](https://github.com/onnx/onnx/blob/main/onnx/onnx.proto#L801).  Not clear how though.

This is a bug #1

The end result is that `Constant` node in this specific case fails the inference.

The resulting exception is caught and recorded, but the recorded errors are never reported and the program continues as nothing happed. This is a bug #2.

### System information
Windows, ONNX version 1.14.0 Platform independent code.

**Comment by jcwchen** [comment]
Thanks for catching these issues!

For the first one, it seems still valid in the latest ONNX shape inference code (https://github.com/onnx/onnx/pull/5238 probably doesn't solve it). Shape inference for the new attribute_proto was just brought in the recent IR bump. cc @liqunfu @gramalingam who should have more context with this topic.

For the second issue, I guess https://github.com/onnx/onnx/pull/5488 will help? Previously strict_mode was always disabled in graph inference and function inference and these kind of errors will never be caught. If we expose the strict_mode options in onnx, we should be able to catch this kind of issue in ORT as well to prevent crash or allocation issue.

**Comment by yuslepukhin** [comment]
I am seeing that 1.14.1 actually resolves. The first issue.

**Comment by liqunfu** [comment]
https://github.com/onnx/onnx/pull/5488 will fix the bug # 2
