### ISSUE TITLE
[Feature request] field to represent shape/type for nodes within function

### ISSUE THREAD

**Issue by BowenBao** [onnx/onnx#5487]
### What is the problem that this feature solves?

Unlike `value_info` for `GraphProto`, structure such as this is missing for `FunctionProto`. As a result, the shape type related feature is a bit lacking for nodes within.

- Netron cannot display shape/type for inner nodes.
- Model producer cannot provide shapes inside functions and cross check with shape inference and checker.

### Will this influence the current api (Y/N)?

N

### Feature Area

model usage, backend, converters, shape_inference

### Are you willing to contribute it (Y/N)

None

**Comment by justinchuby** [comment]
Shapes in a function can change based on its input. Any thoughts on how should this info be stored in the proto?

**Comment by BowenBao** [comment]
As how this should be handled for shapes in a graph, I suppose symbols should work.

There are indeed two other concerns around `rank`, and `dtype`. IIRC these two must be static for `ValueInfoProto`, but they might be dynamic for function nodes.

**Comment by justinchuby** [comment]
Should we store materialized shape/type with regards to each function call (node)? Would that be more useful?

**Comment by justinchuby** [comment]
So if we have a function node that is aten_abs_1, and inside the function definition there is a tensor "result", we can store a ValueInfo for the phantom node `aten_abs_1.result`. 

I wonder how we handle subgraphs right now? Is it similar to this? Or is the value info part of the graph?

**Comment by BowenBao** [comment]
> Should we store materialized shape/type with regards to each function call (node)? Would that be more useful?

This is done today for outer most function nodes because they are inside GraphProto. Cannot be done for inner function nodes as reason stated by this issue.

> So if we have a function node that is aten_abs_1, and inside the function definition there is a tensor "result", we can store a ValueInfo for the phantom node `aten_abs_1.result`.

Indeed, sounds like a valid solution.

> I wonder how we handle subgraphs right now? Is it similar to this? Or is the value info part of the graph?

value info is part of GraphProto.

**Comment by justinchuby** [comment]
@jcwchen 

I think if we define the names for uniquely representing intermediate values in a function invocation, then the ValueInfos can just use these names like any other names.

So this naming convention is not just for ValueInfos but standardized in the graph.

**Comment by justinchuby** [comment]
This is especially useful when we wrap nn.Modules as functions because otherwise we lose known shape/type info

**Comment by gramalingam** [comment]
I think it would be better to add fields to represent this in a FunctionProto (and be explicit about it) and avoid implicit representations using qualified names in the graph.

**Comment by justinchuby** [comment]
Thing with Function proto is that each invocation may be a different type, so we don't have definitive types in a FunctionProto?

**Comment by justinchuby** [comment]
@justinchuby will start implementing it in torchlib as an experiment before modifying the onnx spec

**Comment by gramalingam** [comment]
Adding notes here about several points that came up in offline discussion last week:

* The challenge with storing the types with a FunctionProto (just like in a GraphProto) is that functions are polymorphic, and may be invoked with different input types and attribute values, which may impact inferred types of locals in the function. (As Justin mentions above.)
* It is useful to consider the intended applications and use-cases for the feature. Some of the use-cases, at least, have alternative solutions.
* Eg., one compelling use-case is optimizing the function-body: for example, specializing an if-then-else when the if-condition can be statically evaluated. Scenarios include if-conditions that test the rank of a tensor (to see if it is a scalar, for example). However, such optimizations necessarily require:
  - inlining the function body, or
  - having distinct function bodies for different call-sites (when only some of them can be optimized), or
  - all call-sites to the functions-site share the same context (enabling the optimization to be performed for all of them).
* Thus, in all these cases, there is no need for a naming-convention to allow main graph to refer to locals of function-calls corresponding to specific call-sites. What seems potentially more useful is to allow overloaded functions, as in [this PR](https://github.com/onnx/onnx/pull/5011). That allows the specialization of function-bodies for specific contexts.
* Another question to consider is whether it is useful to extend the type/shape inference utilities to return an in-memory representation of the types of locals of a function: scenarios that need this do not need to update the proto definition, and can just use an in-memory representation.
* Another issue that was brought up (as counter to above point) is that an exporter might know type/shape information for specific call-sites that it would like to embed in the generated model. More details about this would be useful. Eg., would this benefit more from overloaded functions?
* There might be an opportunity to integrate the overloaded function proposal with type/shape information stored in function-protos ... the extra string field used in the overloaded function proto is analogous to having a name to refer to a call-site (though not completely equivalent).

**Comment by BowenBao** [comment]
Closing as completed by https://github.com/onnx/onnx/pull/5903
