### ISSUE TITLE
ONNX doesn't have "pooling_convention" attribute  for pooling(Max/Avg)

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#549]
For Pooling:
**pytorch** has " ceil_mode"  to specify which value(ceil/floor) to use while calculating output shape.
http://pytorch.org/docs/master/nn.html#maxpool2d

Similarly, **MXNET** has "pooling_convention" for using ceil or floor for  output shape from maxpool.
https://mxnet.incubator.apache.org/api/python/symbol.html#mxnet.symbol.Pooling

But in **ONNX** pooling , there is  no attribute to determine if the input framework used ceil or floor for pooling operations? https://github.com/onnx/onnx/blob/6270bb68c54647f6c9ca56d640a73fe2dec2ad80/docs/Operators.md#MaxPool

Is there a reason ONNX does not have this attribute?  How can we determine this ?

@bddppq

**Comment by houseroad** [comment]
@Yangqing @dzhulgakov @prasanthpul @ebarsoum

**Comment by bddppq** [comment]
@spidyDev In ONNX it's floor. Since ONNX is meant to be an IR, frontend frameworks can adjust the pads before exporting to ONNX.

**Comment by spidyDev** [comment]
@bddppq  Thanks for clarification. 
Is this mentioned in the ONNX documentation? Could you please point me to it ?
If not, It would be great to have it  for future references.

**Comment by bddppq** [comment]
@spidyDev I don't think it's explicitly mentioned in the doc (mainly because I thought floor is the default setting and so without explicitly mentioning everyone will assume it) Would you mind help creating a PR to polish our doc? :-)

**Comment by ebarsoum** [comment]
@bddppq should we add this attribute?

**Comment by dzhulgakov** [comment]
How common is this attribute in practice? For fixed input sizes (which is usually the case with image models) exporting from framework can convert the sizes to be appropriate with floor.

**Comment by spidyDev** [comment]
Restarting this thread: 
@dzhulgakov  for MXNet models this is definitely used pretty frequently. I have seen in few pytorch models too.  Also, as you mentioned the frameworks can convert sizes to be appropraite with "floor" but I think that solution seems to be more of a workaround to comply with ONNX. It would be great to have the "ceil_mode" attribute added to the operator.

**Comment by spidyDev** [comment]
Also , we see in the onnx export code for pytorch , if the model has "ceil_mode" , its marked as unimplemented, i think adding this attribute would be helpful for all frameworks export functionality too.  Would definitely like to push for this

PYTORCH: https://github.com/pytorch/pytorch/blob/c496a4a347f45be52f972fd6dba9173178b54253/torch/onnx/symbolic.py#L415

@bddppq  @houseroad

**Comment by devymex** [comment]
We need this attribute. We have a 3rd party model trained with "pool_convention=full" in mxnet format, and need to inference the model by TensorRT.

Would you please considering to add this attribute? @dzhulgakov

**Comment by raviv** [comment]
+1

**Comment by tzaumiaan** [comment]
+1 for this feature!

Let's say, we based our model on some pretrained network (like inception from TF/Caffe) using ceil_mode already. And we built the extended model on PyTorch and trained it. It makes no sense not able to port such trained model, does it?

**Comment by rrkotik** [comment]
+1 for this feature

**Comment by panyuetj** [comment]
+1 for this feature

**Comment by xermak00** [comment]
+1 for this feature, thanks)

**Comment by yxchng** [comment]
When will this feature be supported? Much needed!

**Comment by xDooooot** [comment]
+1 for this feature , really needed

**Comment by prasanthpul** [comment]
It's merged! #1860 
Thanks for the feedback!

**Comment by zimenglan-sysu-512** [comment]
+1 for this feature, thanks)
