### ISSUE TITLE
collect_snippets requires cv2 dependency not available on macOS

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#5491]
# Bug Report

### Describe the bug
#5294 added a `cv2` dependency to `onnx.backend.test.case.collect_snippets()` which is not available on macOS. 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): macOS 13.4
- ONNX version (*e.g. 1.13*): main
- Python version: 3.11.4

### Reproduction instructions
```
~/: python -m venv onnx-env  
~/: source ./onnx-env/bin/activate
(onnx-env) ~/: git clone --quiet --recursive https://github.com/onnx/onnx.git
(onnx-env) ~/: pip install ./onnx
(onnx-env) ~/: python
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx.backend.test.case
>>> onnx.backend.test.case.collect_snippets()
  File "~/onnx-env/lib/python3.11/site-packages/onnx/reference/ops/op_image_decoder.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
>>> ^D
(onnx-env) ~/: pip install cv2
ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2
```

### Expected behavior
`collect_snippets` should succeed without error if `cv2` is not available, for example by delaying load?

### Notes

@jantonguirao @xadupre @gramalingam

**Comment by jcwchen** [comment]
Hi @lutzroeder,
Thank you for catching this fresh issue. 

> collect_snippets should succeed without error if cv2 is not available, for example by delaying load?

I agreed with you, we can do delaying load (import only when running reference for that operator) just like 

https://github.com/onnx/onnx/blob/4ad6d3126a9c1ab9b21a8b5c421fe31880d53d20/onnx/reference/ops/op_regex_full_match.py#L14-L21

**Comment by lutzroeder** [comment]
@jcwchen thank you. Looks like there was another reference add in `image_decoder.py`. Created #5498.

**Comment by jcwchen** [comment]
Let's reopen it because it's still an issue in the latest main branch. https://github.com/onnx/onnx/pull/5511 should fix this.
