### ISSUE TITLE
What happens when axis of `DFT - 17` is `0`?

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5493]
In https://onnx.ai/onnx/operators/onnx__DFT.html, default of `axis` is `1` which "corresponds to the first dimension after the batch index."

What happens when `axis` is 0? Does it transform the batch dimension? Should we remove to notion of the "batch dimension" altogether then, because with or without it `axis` is defined the same?

cc @xadupre @gramalingam

**Comment by xadupre** [comment]
This default value may not be very intuitive but do we want to add a new version in opset 20 just to change it?
