### ISSUE TITLE
Map aten bitwise operators to existing ONNX ones

### ISSUE THREAD

**Issue by leandro-gracia-gil** [onnx/onnx#5497]
Currently the aten bitwise operators are not supported in ONNX as listed [here](https://pytorch.org/docs/stable/onnx_supported_aten_ops.html). However, as far as I can tell these operators are pretty straightforward (see [CPU](https://github.com/pytorch/pytorch/blob/03414081ff7ee011e17ee10f9ddb2584811bf965/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L321) and [CUDA](https://github.com/pytorch/pytorch/blob/03414081ff7ee011e17ee10f9ddb2584811bf965/aten/src/ATen/native/cuda/BinaryBitwiseOpsKernels.cu#L16) implementations) so it should be possible to map them to existing ONNX bitwise operators.

In particular:
- aten::bitwise_and -> BitwiseAnd
- aten::bitwise_or -> BitwiseOr
- aten::bitwise_not -> BitwiseNot
- aten::bitwise_xor -> BitwiseXor
- aten::left_shift -> BitShift
- aten::right_shift -> BitShift

As a workaround until these ops are available, it also seems to be possible to do the mapping at export time.

```python
torch.onnx.register_custom_op_symbolic(
    symbolic_name='aten::bitwise_and',
    symbolic_fn=lambda g, *args: g.op('BitwiseAnd', *args),
    opset_version=18)
```

**Comment by justinchuby** [comment]
Thanks for reporting the issue. I would open the same issue on the PyTorch. Contributions would be appreciated!

**Comment by leandro-gracia-gil** [comment]
Thanks for pointing out the implementation. I wonder why pyTorch was failing to export it then, even when using recent ONNX opset versions.

**Comment by justinchuby** [comment]
The implementation is for the new PyTorch exporter: torch.onnx.dynamo_export. You may experiment with it using the latest torch nightly build.
