### ISSUE TITLE
Batching in SequenceLength Operator

### ISSUE THREAD

**Issue by praj-0** [onnx/onnx#5499]
# Ask a Question

### Question
I want to use the `SequenceLength` Operator in a feature pipeline, in the [documentation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#SequenceLength) it says that it only accepts a `Sequence` as an input, but there is no mention of batch size. So here are my questions:
- Can the `SequenceLength` operator only be used with batch size 1?
- If the above is true, then all operators with `Sequence` as input do not support batch processing?
- Is there a way run such an operator with others that do support batching, with batch size >1?
- Can ONNX support [RaggedTensor](https://www.tensorflow.org/guide/ragged_tensor) like in tensorflow for this use case?

### Further information
- Relevant Area: Operators

- Is this issue related to a specific model?
No

**Comment by justinchuby** [comment]
Do you have variable length sequences? Otherwise batching can happen within the sequence?
