### ISSUE TITLE
How to select GPU to execute a model in NNAPI EP

### ISSUE THREAD

**Issue by Uwenisme** [onnx/onnx#5509]
# Ask a Question

### Question

I follow the example code to run a model by using NNAPI EP. But I can't find any example to run a model in gpu or npu. How can I select different devices (cpu, gpu or npu) ? Please give me some tips! Thanks a lot!
```
    Ort::Env onnx_env = Ort::Env{ORT_LOGGING_LEVEL_ERROR, "Default"};
    Ort::SessionOptions so;
    so.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    uint32_t nnapi_flags = 0;
    nnapi_flags |= NNAPI_FLAG_CPU_DISABLED;
    //nnapi_flags |= NNAPI_FLAG_USE_NCHW;
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(so, nnapi_flags));
    Ort::Session session(onnx_env, model_content.data(), fileSize,so);
```

**Comment by jcwchen** [comment]
Hi @Uwenisme,
It should be a question for onnxruntime. I saw you also raised this question there: https://github.com/microsoft/onnxruntime/discussions/17159, which is a better place for this question. I will close this one here. Feel free to reopen it if you still have other ONNX questions.
