### ISSUE TITLE
if value of constant op is None,and the op convert to Parameter Variable will cause a problem, so can I remove this constant op and not affect the model?

### ISSUE THREAD

**Issue by KuaiQuXueX1** [onnx/onnx#5527]
# Ask a Question

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by xadupre** [comment]
It seems an issue related to a converter library? Which one are you using?

**Comment by KuaiQuXueX1** [comment]
> 



> 这似乎是一个与转换库有关的问题。您使用的是哪一个？

I'm using a quantification framework named ppq that formats constant to parameter when reading the ONNX model.
the website of the ppq framwork is https://github.com/openppl-public/ppq/blob/master/ppq/api/interface.py line 593.

**Comment by gramalingam** [comment]
Not sure I understand the question.

If the value returned by a Constant op is not used anywhere in the model, it can be safely removed.

If a constant op node specifies no value, that is erroneous. (But, nevertheless, if it is not used in the model, it can be removed. But if it is used in the model, unclear what it means.)

Don't understand what you mean by "op convert to parameter variable".
