### ISSUE TITLE
A more generic ReverseSequence

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5530]
Described in #1526 , ReverseSequence https://onnx.ai/onnx/operators/onnx__ReverseSequence.html#l-onnx-doc-reversesequence cannot support flipping an arbitrarily axis. To support https://pytorch.org/docs/stable/generated/torch.flip.html as a function, we need either ReverseSequence to take a dynamic axis as input, or use a dynamic Transpose to swap axis back and forth in a loop before using ReverseSequence.

**Comment by justinchuby** [comment]
Marked for discussion for 1.16

**Comment by justinchuby** [comment]
Looks like we use slice to implement flip: https://github.com/pytorch/pytorch/blob/d4a99631dd589afbb972b3401e56f029192c9b0f/torch/onnx/symbolic_opset10.py#L483. Does it mean we can deprecate ReverseSequence?

**Comment by gramalingam** [comment]
Looks like ReverseSequence is for reversing variable-length sequences (stored in a tensor format). Different functionality, which can't be achieved using slice.
