### ISSUE TITLE
[Feature request] Onnx convert_model_to_external_data support GraphProto

### ISSUE THREAD

**Issue by inisis** [onnx/onnx#5541]
### System information

onnx 1.14.0

### What is the problem that this feature solves?

when creating an onnx model from onnx api, below is an example code
```
onnx_graph = onnx.helper.make_graph(nodes, ***)
model = onnx.helper.make_model(onnx_graph, ***)
```
when onnx_graph is smaller thant 2GB, it works fine, but when it exceeds the limit,  [this ](https://github.com/onnx/onnx/blob/main/onnx/helper.py#L289) will casue a core dump,, but currently convert_model_to_external_data only support ModelProto, so GraphProto should be added too.

### Alternatives considered

I think we shoudl make [convert_model_to_external_data](https://github.com/onnx/onnx/blob/main/onnx/external_data_helper.py#L102) compatible with GraphProto, and a deep dive into the code, it actually requires only GraphProto

### Describe the feature

This feat helps a lot for users who use onnx api

### Will this influence the current api (Y/N)?

Probably not, if name changed, it will.

### Are you willing to contribute it (Y/N)

Yes

**Comment by gramalingam** [comment]
Good point. But I think that a better solution would be support a version of `make_model` that doesn't copy the graph. It doesn't seem like a good idea to copy it, especially for large models. However, for backward compatibility, we should probably also support the copying behavior. We could add an option to `kwargs` to indicate whether to copy or not.

**Comment by inisis** [comment]
> Good point. But I think that a better solution would be support a version of `make_model` that doesn't copy the graph. It doesn't seem like a good idea to copy it, especially for large models. However, for backward compatibility, we should probably also support the copying behavior. We could add an option to `kwargs` to indicate whether to copy or not.

Well, it seems that the graph filed doesn't support direct assignment, and CopyFrom or MergeFrom is needed. I think we can provide a *convert_graph_to_external_data* and *write_external_data_tensors_graph* or make original *convert_model_to_external_data* and *write_external_data_tensors* compatible with GraphProto.
