### ISSUE TITLE
how to add a gather node in onnx model?

### ISSUE THREAD

**Issue by xingxinghanzi** [onnx/onnx#5542]
# Ask a Question

### Question
I want to add a softmax and gather node to my onnx model, which output shape is [1, 19, 512, 1024]. but i get error. I don't find the usage example about creating gather node in official document. 
 
error:  `onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_851): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 1: (1) vs (19)`

![image](https://github.com/onnx/onnx/assets/71701360/b7c92e4f-c0b6-48cc-99f4-75e7046c5a52)

Only adding softmax node is successed. 
![image](https://github.com/onnx/onnx/assets/71701360/0c8d405c-79cd-49a2-97d3-58dd0bcbf589)

I want to get the weight map of index 10 in channel dimension, but failed.
ideal network: origin onnx output (1x19x512x1024)----> softmax node (1x19x512x1024)-------->gather (index: 10, axis: 1) -->output (1 x 512 x1024)

![image](https://github.com/onnx/onnx/assets/71701360/9cdd66c7-d820-42ae-9bc4-1aa1a76e30b0)

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by gramalingam** [comment]
Hi: I think if you apply Gather (axis = 1, index=[single-value]) to an input tensor of shape 1x19x512x1024, you will get an output of shape 1x1x512x1024, right? Gather's output won't have shape 1x19x512x1024. 

If you want to return an output of shape 1x512x1024, you should squeeze or reshape the first dimension out.

**Comment by xingxinghanzi** [comment]
> Hi: I think if you apply Gather (axis = 1, index=[single-value]) to an input tensor of shape 1x19x512x1024, you will get an output of shape 1x1x512x1024, right? Gather's output won't have shape 1x19x512x1024.
> 
> If you want to return an output of shape 1x512x1024, you should squeeze or reshape the first dimension out.

@gramalingam 
Thank you for your reply. I want to get the ouput of shape 1x1x512x1024 by gather node. But the problem now is that adding gather nodes will report an error.

**Comment by xingxinghanzi** [comment]
@gramalingam  Thank you, I finally know the cause of this problem. I forgot to change the shape of output.  Adding below code   
works for me.

`graph.output[0].type.tensor_type.shape.dim[1].dim_value  = 1
`
