### ISSUE TITLE
Build failure with protoc v23.4, protobuf 4.23.4

### ISSUE THREAD

**Issue by samuela** [onnx/onnx#5563]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug
Building with
* onnx 1.14.0
* protobuf library 3.23.4 (protoc version 23.4)
* protobuf python library 4.23.4

fails:
```
In file included from /tmp/nix-build-python3.10-onnx-1.14.0.drv-0/source/.setuptools-cmake-build/onnx/onnx-operators-ml.pb.cc:4:
In file included from /tmp/nix-build-python3.10-onnx-1.14.0.drv-0/source/.setuptools-cmake-build/onnx/onnx-operators-ml.pb.h:11:
/nix/store/0p8xnxq6h6jc7g7kj7dlxy3f6fgb92ag-protobuf-3.23.4/include/google/protobuf/port_def.inc:205:1: error: static_assert failed due to requirement '201103L >= 201402L' "Protobuf only supports C++14 and newer."
static_assert(PROTOBUF_CPLUSPLUS_MIN(201402L), "Protobuf only supports C++14 and newer.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
 Full build log [here](https://gist.github.com/samuela/ec22566e0526679d4e4aed427ed9ffd6).

This is peculiar to me since protobuf4 support is advertised in https://github.com/onnx/onnx/issues/4239 and it looks like cmake builds with C++ standard by default:
https://github.com/onnx/onnx/blob/d2f1a483c8c3fddc1e37071a6dc2d65a4c64d5eb/CMakeLists.txt#L58-L67

I have also added `'-DCMAKE_CXX_STANDARD=17'` to "Extra cmake args" to no avail.

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): macOS 13.4.1 (22F82), building with nix
- ONNX version (*e.g. 1.13*): 1.14.0
- Python version: 3.10.12
- GCC/Compiler version (if compiling from source): Clang 11.1.0
- CMake version: 3.26.4
- Protobuf version: protobuf library 3.23.4 (protoc version 23.4), protobuf python library 4.23.4
- Visual Studio version (if applicable): n/a

### Reproduction instructions
1. Checkout nixpkgs@e2f02c7c18cb9cdfe4dbf62bfb5273fc37ad0a57
2. Replace `pkgs/development/python-modules/onnx/default.nix` with the contents in [this gist](https://gist.github.com/samuela/ec22566e0526679d4e4aed427ed9ffd6)
3. Run `nix-build -A python3Packages.onnx`

### Expected behavior
The build to succeed.

### Notes
See https://github.com/NixOS/nixpkgs/issues/252741 for context

**Comment by Atemu** [comment]
I can reproduce this on aarch64-darwin using the same environment (clang). Interestingly, I cannot reproduce on both aarch64 and x86_64 Linux using almost the same environment but with GCC and a few other small differences.

On Linux you also quickly run into an issue that Darwin also runs into a bit in the log which is that onnx seems to depend on headers that aren't propagated by newer versions of protobuf's abseil-cpp:

```
fatal error: /nix/store/jrkm9494y1zgvgz9500nnl25rhlgsm7z-protobuf-3.23.4/include/google/protobuf/io/coded_stream.hfatal error:130'absl/strings/string_view.h' file not found:
```

**Comment by Atemu** [comment]
So, `CMAKE_CXX_STANDARD` seems to always be `11`, even if you manually force another standard. This might be a bug on the Nix side since clang-11 should ordinarily default to c++14.

This should be breaking a lot of other packages though? I'm confused.

**Comment by samuela** [comment]
> We don’t validate ONNX with nix-build so unexpected things may happen. I do agree that figuring out how to set the c++ standard correctly may help you here.

Makes sense -- I think that this should be reproducible outside of nix tho

**Comment by sl1pkn07** [comment]
manual

sed 's|CMAKE_CXX_STANDARD 11|CMAKE_CXX_STANDARD 14|g' \
    -i onnx/CMakeLists.txt

seems https://github.com/onnx/onnx/pull/5119 is reverted

**Comment by jhol** [comment]
Just doing some testing here. Abseil-cpp is a polyfill library designed to backport new C++ library features to older C++ standards.

Depending on how the abseil-cpp build is configured, it probes the compiler to test if `std::string_view` is present, which it will be for compilers that support C++17 and newer. If it is, `ABSL_OPTION_USE_STD_STRING_VIEW` will be set to `1` in `include/absl/base/options.h`. However, the onnx `CMakeLists.txt` is downgrading the C++ standard.

So, I think this has something to do with `ABSL_PROPAGATE_CXX_STD`. The project has to be built with whatever C++ standard protocol buffers was built with.
