### ISSUE TITLE
Shape inference error for reducemin/max when rank is 0

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5576]
When input rank is 0, `axis=0`, the following error is raise:

```
[ShapeInferenceError] Inference error(s): (op_type:ReduceMin, node name: /ReduceMin): [ShapeInferenceError] axis must be in [-rank, rank-1]. input rank was 0
(op_type:ReduceMax, node name: /ReduceMax): [ShapeInferenceError] axis must be in [-rank, rank-1]. input rank was 0

Inputs:
(tensor(6.8287),)
kwargs:
{'dim': 0, 'keepdim': True}
```

I expect the model to be valid because `0 is in [-1, -0]`

**Comment by jbachurski** [comment]
I'm not sure this is consistent with the current error message - the actual interval is [-0, -1], which is empty as 0 > -1. A scalar has no axes, so this makes sense. Do you think it's worth adding a special case just so that scalars can work in all the reductions?

**Comment by justinchuby** [comment]
> the actual interval is [-0, -1], which is empty as 0 > -1. A scalar has no axes, so this makes sense.

That's a good catch. 🤔

**Comment by gramalingam** [comment]
Agree with @jbachurski ... the existing error message makes sense and is more logical. (We can add a special case for scalars, but that would require backends, like onnxruntime, also to be extended to add the special case ... doesn't seem worth it unless there is a compelling reason.)
