### ISSUE TITLE
Pipeline Badges display "never built"

### ISSUE THREAD

**Issue by andife** [onnx/onnx#5577]
Currently our github shows 
![image](https://github.com/onnx/onnx/assets/20612932/2e83ed4b-67ac-4147-9ab9-d5af7e85c996) : 

Could we update the links that the status shown? Maybe the visible setting was changed in Azure? Or should we switch to display badges from the github pipelines?

**Comment by jcwchen** [comment]
I can confirm with this PR: https://github.com/onnx/onnx/pull/5581, after midnight, now README.md does show the badges as succeeded.
