### ISSUE TITLE
[ShapeInferenceError] Inferred shape and existing shape differ in dimension 1: (64) vs (75)

### ISSUE THREAD

**Issue by farah-rostom98** [onnx/onnx#5578]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
when I use shape_inference.infer_shapes to infer my onnx model, it reports Inferred shape and existing shape differ in dimension 1: (64) vs (75)
This happens at the split node where (1 x 151 x 6300) is split into (1 x 87 x 6300) and (1 x 64 x 6300)
![Screenshot from 2023-09-10 17-21-44](https://github.com/onnx/onnx/assets/130547998/7c6e0b2b-8e03-4785-962d-a6a1f872937d)

### System information
- OS Platform and Distribution :  Linux Ubuntu 20.04
- ONNX version : 1.14.1
- Python version: 3.8.10
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:

### Reproduction instructions

- Describe the code to reproduce the behavior.
from onnxruntime.quantization import shape_inference

shape_inference.quant_pre_process(
        input_model_path,
        output_model_path,
    )

- Attach the ONNX model to the issue (where applicable)
https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-seg.pt

**Comment by justinchuby** [comment]
How did you create the model? It seems the existing shape is incorrect based on your description.

**Comment by farah-rostom98** [comment]
I tried the on this model [Yolov8n-seg](https://docs.ultralytics.com/tasks/segment/)
1- used yolo export to export the model in onnx form with fp32 weigh
 using CLI
!yolo export model='Yolo.pt' opset=15 imgsz=480,640 format=onnx

**Comment by justinchuby** [comment]
This may be an issue in the yolo export code. You may consider saving the model out to a text format then hand fix the inferred shape to the node to unblock your use case.

**Comment by farah-rostom98** [comment]
Can you please elaborate more?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
