### ISSUE TITLE
Reference implementation of Softmax does not match the spec?

### ISSUE THREAD

**Issue by IngmarVoigt2** [onnx/onnx#5586]
https://onnx.ai/onnx/operators/onnx__Softmax.html#softmax-13 says 

> The operator computes the normalized exponential values for the given input:
> Softmax(input, axis) = Exp(input) / ReduceSum(Exp(input), axis=axis, keepdims=1)

This seems to be completely different from https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/softmax.py:

```
def softmax(x: np.ndarray, axis: int = -1) -> np.ndarray:
    x_max = np.max(x, axis=axis, keepdims=True)
    tmp = np.exp(x - x_max)
    s = np.sum(tmp, axis=axis, keepdims=True)
    return tmp / s
 ``` 

Am I missing something here?

**Comment by justinchuby** [comment]
They should be equivalent for numerical stability: https://jamesmccaffrey.wordpress.com/2016/03/04/the-max-trick-when-computing-softmax/#:~:text=A%20trick%20to%20avoid%20this,you%20avoid%20extreme%20large%20numbers.&text=which%20are%20the%20same%20softmax%20values%20as%20when%20computed%20directly.

**Comment by IngmarVoigt2** [comment]
I see - thanks for clarifying! It would be great to point this out in the documentation though

**Comment by xadupre** [comment]
To complete the answer, the softmax function is usually implemented that way to avoid overflows (exp(700) = inf with float64). So the implementation is using the property  exp(a + b) = exp(a) * exp(b) to avoid computing exp of positive numbers.
