### ISSUE TITLE
RuntimeError: Exporting the operator heaviside to ONNX opset version 9 is not supported. 

### ISSUE THREAD

**Issue by mhmd97z** [onnx/onnx#5587]
Hi,
Could you help me bypass this issue (any similar supported functions) or give me some hints on extending ONNX to support "heaviside"?
Thanks!

**Comment by justinchuby** [comment]
The heaviside function can be implemented as an ONNX function like so https://github.com/microsoft/onnxscript/blob/b6c5e3bb9729f939e979a41d8d724009df9f3b58/onnxscript/function_libs/torch_lib/ops/core.py#L3593-L3601

```python
import onnxscript


@onnxscript.script()
def aten_heaviside(self: TReal, values: TReal) -> TReal:
    """heaviside(Tensor self, Tensor values) -> Tensor"""

    zero = op.CastLike(0, self)
    one = op.CastLike(1, self)
    intermediate = op.Where(op.Less(self, zero), zero, one)

    return op.Where(op.Equal(self, zero), values, intermediate)
```

You may register the function like so:

```python
def heaviside_symbolic(g, self, values):
    return g.onnxscript_op(aten_heaviside, self, values).setType(self.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::heaviside",
    symbolic_fn=heaviside_symbolic,
    opset_version=opset_version,
)
```

before calling torch.onnx.export

**Comment by justinchuby** [comment]
Closing for now. Please let us know if to resolves your issue. For more reference: https://pytorch.org/docs/stable/onnx.html#adding-support-for-operators
