### ISSUE TITLE
Is it possible to merge graphs for multiple onnx models that expect the same input?

### ISSUE THREAD

**Issue by divinit7** [onnx/onnx#5592]
# Ask a Question

### Question

I have three models that accept the same input image of size 1x3x224x224. Instead of getting inference seperately from these models I want to combine them into a single onnx. I have prefix every node and initializer with the model name to make it unique but some how it just wont work.

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:  all models are opset 11

### Notes

```
nodes = []
outputs = []
inputs = []
for model in models:
        inputs.extend(model.graph.input.name)
        nodes.extend(model.graph.node)
        outputs.extend(model.graph.output.name)

graph = helper.make_graph(
        nodes, 
        "combined_model",
        inputs=inputs,
        outputs=outputs
    )
    model = helper.make_model(graph)

    onnx.save(model, "combined_model.onnx")
```

**Comment by cbourjau** [comment]
I posted a reply to a similar question elsewhere and it is is my recommendation: https://github.com/onnx/onnx/discussions/5096#discussioncomment-5539886

**Comment by justinchuby** [comment]
Thanks @cbourjau !
