### ISSUE TITLE
[Feature request] Support tensorflow unravel_index

### ISSUE THREAD

**Issue by hmaarrfk** [onnx/onnx#5599]
### System information

latest

### What is the problem that this feature solves?

I would like to support
https://www.tensorflow.org/api_docs/python/tf/unravel_index

### Alternatives considered

Manually writing it, but that would require knowledge of both tensorflow and onnx, which is difficult to come by

### Describe the feature

Describe scenario use case

https://github.com/onnx/tensorflow-onnx/issues/2019

### Will this influence the current api (Y/N)?

no

### Feature Area

ONNX converters

### Are you willing to contribute it (Y/N)

Yes

### Notes

xref: https://github.com/microsoft/onnxruntime/issues/17585#issuecomment-1723972755
xref: https://github.com/onnx/tensorflow-onnx/issues/2019

**Comment by justinchuby** [comment]
https://github.com/onnx/tensorflow-onnx/issues/2019 is the right place for the issue. Do you think a new primitive operator is needed to support the tf op?

cc @fatcat-z

**Comment by hmaarrfk** [comment]
i'm not too sure. I feel like unravel_index should just be "easy to implement" but I'm not an expert in onnx, or the python onnx aspects, which is what scares me in writing my own implementation

**Comment by justinchuby** [comment]
I will close this and allow https://github.com/onnx/tensorflow-onnx/issues/2019 to track the issue. If it becomes apparent that we need a new primitive operator in ONNX, please feel free to reopen.

**Comment by hmaarrfk** [comment]
understood thanks.
