### ISSUE TITLE
Support `data_location=MESSAGE` in `convert_model_to_external_data`

### ISSUE THREAD

**Issue by Jason-Young-AI** [onnx/onnx#5608]
# Ask a Question

### Question
I want to convert all parameters of the ONNX model into separate external data storage file.
However, I found that the method 'convert_model_to_external_data' check the tensors whether have the field 'raw_data' ([source code](https://github.com/onnx/onnx/blob/bc424cd4764afc7fb8a940023cdf07b6081b02e6/onnx/external_data_helper.py#L139C17-L139C17)).
This means that 'data_location' should not be set to 0 (as shown in [here](https://github.com/onnx/onnx/pull/678#issue-309788967)).

Is there a ready-made method to convert tensors with data_location=0 into external data？

**Comment by justinchuby** [comment]
cc @jcwchen

**Comment by jcwchen** [comment]
Hi @Jason-Young-AI,
Yes it's a known limitation that currently `convert_model_to_external_data` only supports converting tensors with raw_data and IIUC there is no handy function to convert tensors without raw_data to external data. You might be able to manually use `onnx.numpy_helper.to_array` and then `onnx.numpy_helper.from_array` to convert your tensors using raw_data.

Such an enhancement might be just trivial. Welcome to contribute!
