### ISSUE TITLE
ONNX PyPI page has broken links

### ISSUE THREAD

**Issue by yuslepukhin** [onnx/onnx#5616]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
The first and the last links on the screenshot are broken, there may be others.

![image](https://github.com/onnx/onnx/assets/11303988/d0ea912e-2618-47e5-88dc-b66a8f2050de)

### Reproduction instructions

Go to: https://pypi.org/project/onnx/

### Expected behavior
The links should work

**Comment by jcwchen** [comment]
Similar as https://github.com/onnx/onnx/issues/5173. I think we should just use absolute link instead of relative link in the main README.md for now to make it work both on GitHub and PyPI.

**Comment by jcwchen** [comment]
Actually there are still few relative links in README.md and will be fixed by https://github.com/onnx/onnx/pull/5663.
