### ISSUE TITLE
some questions about AveragePool pads behavior

### ISSUE THREAD

**Issue by nihui** [onnx/onnx#562]
hello
I've recently tried to implement the onnx backend for ncnn, and encountered some problems about the pooling pads behavior.
I originally think it is the same as convolution, which takes the padding values and padding area.

example follows
kernel_shape 3x3
pads 0,0,1,1

Input 2x2
```
2 4
6 8
```

In convolution, it will be padded with zeros
```
2 4 0
6 8 0
0 0 0
```
```
2*k[0] + 4*k[1] + 0*k[2] + 6*k[3] + 8*k[4] + 0*k[5] + 0*k[6] + 0*k[7] + 0*k[8]
```

----
I wonder how the padding actually works in pooling
Is padding value always zero?
Is the padding area taken into account in average calculation?
Does onnx always ensure that the Input size after padding is always equals to or larger than the kernel shape? ( input 2x2  with pads 0,0,1,1 and kernel_shape 4x4 never happens)

Input after zero padding 2x2
```
2 4 0
6 8 0
0 0 0
```

AveragePool result (with the padding values and with padding area, likes the convolution)
```
2.22222      (2+4+6+8+0+0+0+0+0) / 9
```

AveragePool result (without the padding values and with padding area)
```
2.22222      (2+4+6+8) / 9
```

AveragePool result (without the padding values and without padding area)
```
5      (2+4+6+8) / 4
```

**Comment by fumihwh** [comment]
In your case, pads should be [0, 1, 0, 1]
```
`pads` format should be as follow [x1_begin, x2_begin...x1_end, x2_end,...], 
where xi_begin the number of pixels added at the beginning of axis `i` and xi_end, the number of pixels added at the end of axis `i`.
```
https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-4

**Comment by fumihwh** [comment]
`Is the padding area taken into account in average calculation?`
No. `5      (2+4+6+8) / 4` is correct.

I think ` input 2x2 with pads 0,0,1,1 and kernel_shape 4x4` will cause error at backend.
