### ISSUE TITLE
Is it possible to log intermediate nodes in onnx execution graph ?

### ISSUE THREAD

**Issue by mvanzulli** [onnx/onnx#5647]
# Ask a Question

### Question
We want to extract and log intermediate values from an ONNX model during inference. Is there an integrated way in ONNX or ONNX Runtime to accomplish this without modifying the ONNX graph?

### Further information
Relevant Area: model usage, backend

Thanks in advance!

**Comment by justinchuby** [comment]
It's possible to specify output names as the first argument in `session.run`: https://github.com/microsoft/onnxruntime/blob/1bc115719c0d07ad658a9bb458ddf8f1bf379a41/onnxruntime/python/onnxruntime_inference_collection.py#L202

**Comment by xadupre** [comment]
You may use the ReferenceEvaluator to show intermediate results by increasing verbosity (`sess = ReferenceEvaluator("model.onnx", verbose=10)`), see https://onnx.ai/onnx/api/reference.html#onnx.reference.ReferenceEvaluator. There is no option to record them but it could be possible to implement it (see https://github.com/onnx/onnx/pull/5413).

**Comment by mvanzulli** [comment]
Thank you so much for your clarification 🥇 🙏🏼 💯 !
