### ISSUE TITLE
Input size error when generating a slice node with onnx

### ISSUE THREAD

**Issue by CZXIANGOvO** [onnx/onnx#5649]
#  Bug Report

### Is the issue related to model conversion?

 NO,There is an issue with using API (onnx. helper. make_model) to generate slices
### Describe the bug

 I want to make a slice node with onnx, first I build the slice node slice_node with the API (onnx.helper.make_node), then I define the model inputs and outputs with the API (onnx.helper.make_graph), then I define the model inputs and outputs with the API (onnx.helper.make _model) to make model model, then I call API (onnx.checker.check_model(model)),it reports error Node (Slice) has input size 1 not in range [min=3, max=5]. Then I saved the model directly with API (onnx.save_model), and during inference modeling, API(ort_session = onnxruntime.InferenceSession(model.SerializeToString(), providers=providers )) also reports an error InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. in Node, ("Slice", Slice, "", -1) : ("367": tensor(float),) -> ( "412": tensor(float),) , Error Node (Slice) has input size 1 not in range [min=3, max=5].
### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*):windows11
- ONNX version (*e.g. 1.13*):1.14.1
- Python version:3.9.16
- Protobuf version:4.23.3

### Reproduction instructions

```
import onnx
from onnx import helper, numpy_helper

slice_node = helper.make_node(
    'Slice',
    inputs=['input'],
    outputs=['output'],
    name='Slice_74',
    axes=[0, 1, 2, 3],
    starts=[256, 256, 46, 46],
    ends=[256, 19, 46, 46]
)

graph = helper.make_graph(
    [slice_node],
    'slice_model_graph',
    [helper.make_tensor_value_info('input', onnx.TensorProto.FLOAT, [256, 256, 46, 46])],
    [helper.make_tensor_value_info('output', onnx.TensorProto.FLOAT, [256, 19, 46, 46])]
)


model = helper.make_model(graph, producer_name='slice_model')
onnx.checker.check_model(model)
onnx_filename = 'slice_model.onnx'
onnx.save_model(model, onnx_filename)
```

- [slice_model.zip](https://github.com/onnx/onnx/files/12812761/slice_model.zip)

### Expected behavior

 Without the bug, I don't get an error when calling the API (onnx.checker.check_model) because I set the input.shape of the slice node to be 4 dimensional, not 1 dimensional as the error shows. And I don't report error Error Node (Slice_74) has input size 1 not in range [min=3, max=5] when I reason about the model.
### Screenshot of the error
![c65da76108f855c40dbe366602fe665](https://github.com/onnx/onnx/assets/121651120/430b4cce-624a-4e08-97cf-3f69eac23bf2)
![image](https://github.com/onnx/onnx/assets/121651120/97a044a8-f719-4ad3-a50e-fd7ddebde027)

**Comment by CZXIANGOvO** [comment]
> # Bug Report
> ### Is the issue related to model conversion?
> ### Describe the bug
> ### System information
> ### Reproduction instructions
> [slice_model.zip](https://github.com/onnx/onnx/files/12812761/slice_model.zip)
> ### Expected behavior

**Comment by justinchuby** [comment]
Did you set the size of the input?

**Comment by gramalingam** [comment]
I think the problem is that Slice expects axes/starts/ends as inputs, not attributes. (It has been like this opset version 10. I am not sure if you want to create an earlier opset version model, if so you need to specify that.) The error message is not about the size/shape of the first input, it is about the number of inputs.
