### ISSUE TITLE
IsInf for float types need saturate attribute

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#5651]
# Ask a Question

### Question
for float8 type, representation of inf depends on saturate argument. it is impossible to evaluate inf without knowing the saturate argument.

https://github.com/microsoft/onnxruntime/blob/be7541ef4a39fe41a7a616c621c1fdd163c27035/include/onnxruntime/core/framework/float8.h#L48

maybe saturate is a system wise setting. I put this as question but need to get clarification before ORT can implement the op.

### Further information

- Is this issue related to a specific model?

**Comment by xadupre** [comment]
There are four float 8 types defined in onnx specifications. Two of them can represent inf (E4M3FN, E5M2), the two others don't, they can only represent NaN. I don't think we need an extra parameter saturate.

**Comment by liqunfu** [comment]
> There are four float 8 types defined in onnx specifications. Two of them can represent inf (E4M3FN, E5M2), the two others don't, they can only represent NaN. I don't think we need an extra parameter saturate.

Thanks. It was my miss-understanding of saturate which actual means converting inf in float32 to max in float8. 

Regarding E4M3FN, I do not see it supports inf from both the onnx doc (https://onnx.ai/onnx/technical/float8.html) and the reference (https://arxiv.org/pdf/2209.05433.pdf table 1). ORT code implementation also set float32 inf to Float8E4M3FN NaN (https://github.com/microsoft/onnxruntime/blob/be7541ef4a39fe41a7a616c621c1fdd163c27035/include/onnxruntime/core/framework/float8.h#L51C16-L51C16). Do I miss-understand again?

**Comment by xadupre** [comment]
True, E4M3FN has no infinite values. That's what `FN` means.

**Comment by justinchuby** [comment]
Closed as resolved. LMK if that’s not the case
