### ISSUE TITLE
Build failed for v1.12.0

### ISSUE THREAD

**Issue by kylekam** [onnx/onnx#5653]
# Bug Report

### Is the issue related to model conversion?
No.

### Describe the bug
A clean git clone of the the onnx repo followed by git checkout v1.12.0 and then the build command leads to a build failure involving protobuf.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Windows 10
- ONNX version (*e.g. 1.13*): 1.12.0
- Python version: 3.11.4
- GCC/Compiler version (if compiling from source):
- CMake version: 3.24.3
- Protobuf version: v3.20.2
- Visual Studio version (if applicable): 2019

### Reproduction instructions
 git clone --recursive https://github.com/Microsoft/onnxruntime.git
git checkout v1.12.0
run the following build command:
.\build.bat --config RelWithDebugInfo --parallel --skip_tests --cmake_generator "Visual Studio 16 2019" --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=80 --use_cuda --cuda_version 11.2 --cudnn_home "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2" --cuda_home "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2"

### Expected behavior
Build .lib or .dll files for onnx.

### Notes
Build error output is attached.

**Comment by kylekam** [comment]
[onnx_build_error.txt](https://github.com/onnx/onnx/files/12835920/onnx_build_error.txt)

**Comment by justinchuby** [comment]
This looks like an onnx runtime error. Please open an issue against https://github.com/microsoft/onnxruntime
