### ISSUE TITLE
Bug of Softmax op with different axis

### ISSUE THREAD

**Issue by Tunaaaaa** [onnx/onnx#5655]
# Bug Report

### Describe the bug
we hava a seg model here [https://github.com/Tunaaaaa/softmax_bug/blob/main/face_seg.onnx](url)
we generate random input here [https://github.com/Tunaaaaa/softmax_bug/blob/main/x.txt](url)
the last op is Softmax with axis=1
when run this onnx model as follow, we got wrong result
```
import numpy as np
import onnxruntime as rt


with open('x.txt', 'r') as f:
    data = [float(line.strip()) for line in f]


input_data = np.array(data, dtype=np.float32).reshape(1,3,224,128)


sess = rt.InferenceSession("face_seg.onnx")


input_name = sess.get_inputs()[0].name
output_names = [output.name for output in sess.get_outputs()]


results = sess.run(output_names, {input_name: input_data})


for i, output_name in enumerate(output_names):
    with open('out/' + output_name + '.txt', 'w') as f:
        for item in results[i].flatten():
            f.write("%s\n" % item)
```
1. the original model(axis=1) [https://github.com/Tunaaaaa/softmax_bug/blob/main/face_seg.onnx](url) get [https://github.com/Tunaaaaa/softmax_bug/blob/main/softmax_0.tmp_0_onnx.txt](url)
2. the modified model (axis = 0/1/2/3) [https://github.com/Tunaaaaa/softmax_bug/blob/main/modified_modified_face_seg.onnx](url) get 
[https://github.com/Tunaaaaa/softmax_bug/blob/main/custom_output_0.txt](url) 
[https://github.com/Tunaaaaa/softmax_bug/blob/main/custom_output_1.txt](url)
[https://github.com/Tunaaaaa/softmax_bug/blob/main/custom_output_2.txt](url)
[https://github.com/Tunaaaaa/softmax_bug/blob/main/custom_output_3.txt](url)
3. we dump the result of the -2th op [https://github.com/Tunaaaaa/softmax_bug/blob/main/bilinear_interp_v2_8.tmp_0_onnx.txt](url) , and using python to do softmax(dim=1), the result is here [https://github.com/Tunaaaaa/softmax_bug/blob/main/pyout-dim1.txt](url)
code is here
```
import numpy as np
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=1, keepdims=True)

with open('bilinear_interp_v2_8.tmp_0_onnx.txt', 'r') as f:
    data = [float(line.strip()) for line in f]

data=np.array(data).reshape(1, 2, 224, 128)

result = softmax(data)

with open('pyout-dim1.txt', 'w') as f:
    for item in result.flatten():
        f.write("%s\n" % item)
```
4. we dump the result of the -2th op, and using python to do softmax for all flatten data, the result is here [https://github.com/Tunaaaaa/softmax_bug/blob/main/pyout.txt](url)
code is here
```
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

with open('bilinear_interp_v2_8.tmp_0_onnx.txt', 'r') as f:
    data = [float(line.strip()) for line in f]

result = softmax(np.array(data))

with open('pyout.txt', 'w') as f:
    for item in result:
        f.write("%s\n" % item)
```
from above we find:
**there are 4 kinds of result,** 
1. python flatten softmax = onnx softmax axis 0 = onnx softmax axis 1
2. onnx softmax axis 2
3. onnx softmax axis 3
4. python softmax dim1 
**only the 4th (python softmax dim1 ) looks like the right one.**

could you please help us to solve this problem? 

### Other information
![image](https://github.com/onnx/onnx/assets/59496849/1d9c0c18-8d78-4399-83cd-028a5d2851ba)
![image](https://github.com/onnx/onnx/assets/59496849/13c42fd4-9350-491a-aff3-09ddf141e867)
![image](https://github.com/onnx/onnx/assets/59496849/b2c634ce-24d6-4f11-9a09-2488bedfa97b)

**Comment by hariharans29** [comment]
Please see response in the ORT issue
