### ISSUE TITLE
Why are there two backend tests for the reference runtime?

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5662]
There is onnx/test/test_backend_reference.py and reference_evaluator_backend_test.py. I wonder how they are related? cc @xadupre

**Comment by xadupre** [comment]
One is using the API implemented in onnx.backend.base.BackendRep and supports multiple devices (test_backend_reference.py). The other one is the one I used to implement the reference evaluation. I added error messages with more information in them to help finding the issues. It could be dropped now the implementation is complete.

**Comment by justinchuby** [comment]
Are there pieces we can migrate from the reference_evaluator test we can migrate to the backend_reference file to make it more informative? Or should I just go ahead and remove the file?
