### ISSUE TITLE
Clarification of Specs: LayerNormalization op should define broadcasting rules for B and Scale inputs

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx#5666]
# Bug Report

### Is the issue related to model conversion?
no

### Describe the bug

The LayerNormalization operation is defined as a sequences of ops. In this sequence, the LayerNormalization inputs 'B' and 'Scales' are used, respectively, by `Add` and `Mul`, both ops that support Multi-Directional Broadcasting.

However, in the context of LayerNormalization, I believe only the Uni-Directional Broadcasting from `B` and `Scales` to their respective other operands (with shapes derived from input `X`) makes sense.

Does the community agree with this observation?

If yes, I recommend to add this clarification to the current op. Let me know if you need help for this. 

In general, I would suggest to be more explicit with broadcasting rules when applicable.

### Notes
This is a documentation issue.

**Comment by AlexandreEichenberger** [comment]
Initial Issue: #2379

**Comment by AlexandreEichenberger** [comment]
How should I proceed @justinchuby ?

**Comment by justinchuby** [comment]
cc @gramalingam @xadupre. I think a PR would be the most effective and much appreciated, thanks!

**Comment by gramalingam** [comment]
Agree that it would be good to clarify the shape requirements on Bias and Scale. I looked at the documentation, and it says that "Y and X have the same shape". So, I think this implicitly says that Bias/Scale are only unidirectionally broadcast, and not multidirectionally broadcast. Also, I think it is common to use scalar constants like 0 and 1 (when there is no bias or scale), so I think unidirectional broadcast is common. So, I agree with the interpretation.
