### ISSUE TITLE
Inference reports an error when the three inputs to the slice node are inputs from the same node.

### ISSUE THREAD

**Issue by CZXIANGOvO** [onnx/onnx#5671]
# Bug Report

### Is the issue related to model conversion?

no

### Describe the bug

When I make a slice node with the api (onnx.helper.make_node), I first create a constant node with (onnx.helper.make_node), set outputs=['constant_output'], and then when I make a slice node, I set inputs=['constant_output','constant_output','constant_output'], and finally export onnx model, but when reasoning about the model with api(ort.InferenceSession), it will report error This is an invalid model. Type Error: Type 'tensor(float)' of input parameter ("constant_output") of operator (Slice) in node () is invalid, but when I create two or three constant nodes, I set inputs =['constant1_output','constant2_output','constant3_output'], the model inference does not report an error.
### System information

OS Platform and Distribution (e.g. Linux Ubuntu 20.04):windows11
ONNX version (e.g. 1.13):1.14.1
Python version:3.9.16
Protobuf version:4.23.3

### Reproduction instructions

one constant
```
import onnx
from onnx import numpy_helper
import numpy as np

constant_value = np.array([1, 2, 3, 4], dtype=np.float32)
constant_tensor = numpy_helper.from_array(constant_value, "constant_tensor")
starts = np.array([np.random.randint(0, 4)], dtype=np.int64)
ends = np.array([np.random.randint(1, 5)], dtype=np.int64)

constant_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['constant_output'],
    value=constant_tensor
)

slice_node = onnx.helper.make_node(
    'Slice',
    inputs=['constant_output','constant_output','constant_output'],
    outputs=['slice_output']
)
outshape = (256, 19, 46, 46)

graph = onnx.helper.make_graph(
    nodes=[constant_node, slice_node],
    name='constant_to_slice',
    inputs=[],  
    outputs=[onnx.helper.make_tensor_value_info('slice_output', onnx.TensorProto.FLOAT, outshape)]
)

model = onnx.helper.make_model(graph)
onnx.checker.check_model(model)
onnx.save(model, 'constant_to_slice.onnx')
```
three constant
```
import onnx
from onnx import numpy_helper
import numpy as np
from onnx import helper
from onnx import TensorProto

random_starts = np.array([np.random.randint(0, 4)], dtype=np.int64)
random_ends = np.array([np.random.randint(1, 5)], dtype=np.int64)

constant_starts = numpy_helper.from_array(random_starts, "starts")
constant_ends = numpy_helper.from_array(random_ends, "ends")
outshape = (256, 19, 46, 46)

constant_starts_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['starts'],
    value=constant_starts
)

constant_ends_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['ends'],
    value=constant_ends
)

constant_value = np.array([1, 2, 3, 4], dtype=np.float32)
constant_tensor = numpy_helper.from_array(constant_value, "constant_tensor")

# 创建Constant节点
constant_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['constant_output'],
    value=constant_tensor
)

slice_node = onnx.helper.make_node(
    'Slice',
    inputs=['constant_output', 'starts', 'ends'],
    outputs=['output']
)
outshape = (256, 19, 46, 46)

graph = onnx.helper.make_graph(
    nodes=[constant_starts_node, constant_ends_node, constant_node, slice_node],
    name='constant_to_slice',
    inputs=[],
    outputs=[helper.make_tensor_value_info('output', TensorProto.FLOAT, outshape)]
)

model = onnx.helper.make_model(graph)
onnx.checker.check_model(model)
onnx.save(model, 'constant_to_slice_random.onnx')
```

### Expected behavior

Same input, should not report an error
### Screenshot of the error

![image](https://github.com/onnx/onnx/assets/121651120/9a9a291a-c8cf-48b5-8cc8-59b6df99d588)
![image](https://github.com/onnx/onnx/assets/121651120/2c0bba38-36c4-48f9-8652-ac2cdb43f316)
![image](https://github.com/onnx/onnx/assets/121651120/0c95ce4e-a486-4676-b859-a9ac0d742c74)

**Comment by justinchuby** [comment]
Slice inputs start and end need to take INT64 inputs. The first constant is float32 so it is not a valid input to start or end.
