### ISSUE TITLE
How to determine the correspondence between the inputs of `model.graph.node` and `OpSchema` that contain multiple optional inputs?

### ISSUE THREAD

**Issue by Jason-Young-AI** [onnx/onnx#5675]
# Ask a Question

### Question
For operators in ONNX, their `OpSchema` defines the input order and optionality.
For each `node`, due to the possibility of multiple optional inputs of `OpSchema` indicated by the node's `op_type`, it is necessary to determine which inputs are actually provided for that node and which ones are omitted.

For example, when an `OpSchema` defines its inputs as `[A, B (optional), C (optional)]`, and if a node provides only 2 inputs, they could correspond to either `[A, B]` or `[A, C]`.
How does ONNX determine which specific case it is?
Regrettably, I haven't found the corresponding interface in ONNX. Could you please provide an answer?

### Notes
Like in `OpSchema`: `Clip`, its inputs have `input`, `min (optional)`, and `max (optional)` [(doc)](https://github.com/onnx/onnx/blob/main/docs/Operators.md#inputs-1---3) , if there is a node that `op_type` is `Clip` that contains 2 inputs `A` and `B`, how to determine whether `B` is `min` or `max`?

**Comment by justinchuby** [comment]
The inputs are always provided in order. When an optional input is not provided and is followed by other inputs, ONNX uses `""` as the placeholder: e.g. `[A, "", C]`

**Comment by Jason-Young-AI** [comment]
@justinchuby Thank you for your response. I now understand, but I would like to know if the content you provided can be found in any part of the ONNX official documentation or corresponds to a specific section in the source code or Python interface.

**Comment by justinchuby** [comment]
You may refer to https://github.com/onnx/onnx/blob/main/docs/IR.md#optional-inputs-and-outputs

**Comment by Jason-Young-AI** [comment]
Thank you for your explanation and response!
