### ISSUE TITLE
[Feature request] Python 3.12 support

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5680]
Support Python 3.12

**Comment by isdanni** [comment]
> Support Python 3.12

Does this mean Python 3.8 will be deprecated across CI yml configs? Since the max Azure Pipeline allowed is 4.

**Comment by justinchuby** [comment]
> > Support Python 3.12
> 
> Does this mean Python 3.8 will be deprecated across CI yml configs? Since the max Azure Pipeline allowed is 4.

I think we should be able to have many azure pipelines?

**Comment by isdanni** [comment]
> I think we should be able to have many azure pipelines?

I see! I got it confused with max parallel pipeline in #5432
