### ISSUE TITLE
onnx.load/onnx.save breaks the model functionality

### ISSUE THREAD

**Issue by zhipenghan** [onnx/onnx#5683]
# Bug Report

### Is the issue related to model conversion?

No.
### Describe the bug

I have export RWKV model as `rwkv.onnx` with corresponding constants/weights in the same folder. When I use onnx.load, onnx.save to checkpoint the model with all tensors_to_one_file. I get the `rwkv_modified.onnx`.
I inference with these 2 models and the `rwkv.onnx` get correct result, but the `rwkv_modified.onnx` get wrong results. This simple load/save function modify and break the model functionality .
### System information

Windows 10
Python 3.11.4
onnx==1.14.1

### Reproduction instructions

```
import os
import onnx

model_file = "rwkv.onnx"
model_rwkv = onnx.load(model_file)

new_model_file = "rwkv.modified.onnx")
onnx.save_model(model_rwkv, new_model_file, save_as_external_data=True, all_tensors_to_one_file=True, location="rwkv.modified.bin", size_threshold=1024, convert_attribute=False)
```
### Expected behavior

Expect both model get parity results.

**Comment by jcwchen** [comment]
Hi @zhipenghan,
I would suggest using `model_rwkv = onnx.load(model_file, load_external_data=False)` instead if the loaded model_file in total is larger than 2GB. Even if `onnx.load(model_file)` works for >2GB model somehow (doesn't crash or throw an error), the loaded `model_rwkv` might be incomplete when it is larger than 2GB.

**Comment by xadupre** [comment]
Which runtime do you use to compare the outputs? onnxruntime, onnx.reference, other?
