### ISSUE TITLE
resnet18 and inception cannot use simplify method

### ISSUE THREAD

**Issue by deng-ShiFu** [onnx/onnx#5690]
# Ask a Question
resnet18 and inception cannot use simplify method
### Question

I downloaded the onnx files for the following four models.
- [x] [ResNet18-v2](https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet18-v2-7.onnx)
- [x] [DenseNet-121-12](https://github.com/onnx/models/blob/main/vision/classification/densenet-121/model/densenet-12.onnx)
- [x] [Inception-2](https://github.com/onnx/models/blob/main/vision/classification/inception_and_googlenet/inception_v2/model/inception-v2-9.onnx)
- [x] [EfficientNet-Lite4](https://github.com/onnx/models/blob/main/vision/classification/efficientnet-lite4/model/efficientnet-lite4-11.onnx)

The simplify method can be used normally for DenseNet and EfficientNet, but this method cannot be used for ResNet18 and Inception.
The following errors occurred for ResNet18 and Inception respectively.
![1](https://github.com/onnx/onnx/assets/73120065/b76bdfbc-a694-4c93-b13b-a9ad6de32c3f)
![2](https://github.com/onnx/onnx/assets/73120065/73137a29-1aa4-4aa5-9d56-7b716461c110)

### Further information
- Relevant Area: 
model usage
- Is this issue related to a specific model?
**Model name**: ResNet18、Inception
**Model opset**: I tried two versions of resnet18, v1-7 and v2-7, and both had this problem.

### Notes

Below is the code I use.
`
import onnx
from onnxsim import simplify

onnxModel = onnx.load("test/inception-v2-9.onnx")
model_simp, check = simplify(onnxModel)
`

I used the online tool([convertmodel.com](https://www.convertmodel.com/#input=onnx&output=onnx)) you provided to apply resnet18, and found that this tool can be applied to resnet18, and the output model (resnet18_sim) will not have this error when using the simplify method.
My onnxsim version is 0.4.33.
I am a beginner and I am not familiar with onnx and deep learning models. I am not sure whether my wrong operation caused the problem.

**Comment by justinchuby** [comment]
Please open an issue in the https://github.com/daquexian/onnx-simplifier repository. Thanks!
