### ISSUE TITLE
onnx-weekly distribution missing pyi files

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5696]
It looks like the onnx-weekly distribution is missing pyi files.

cc @jcwchen @liqunfu

**Comment by jcwchen** [comment]
I think onnx doesn't have these .pyi in previous releases as well -- why you need .pyi in the source distribution? If we really want to , we can just add include .pyi files in https://github.com/onnx/onnx/blob/main/MANIFEST.in.

**Comment by justinchuby** [comment]
We need the pyi files for intellisense and type checking etc. in the editor. Users will also be able to click on a c++ symbol and see its signature etc.

**Comment by justinchuby** [comment]
I thought this line https://github.com/onnx/onnx/blob/abb445738d5052b5226c697142e5277f8669dba1/pyproject.toml#L42

will include the pyi files but looks like I was wrong.

**Comment by justinchuby** [comment]
I think it is because the glob pattern should have been `**/*.pyi`. Based on https://setuptools.pypa.io/en/latest/userguide/datafiles.html either should work
