### ISSUE TITLE
Shape inference not correct for Sequence

### ISSUE THREAD

**Issue by xiaowuhu** [onnx/onnx#5698]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
```
    unique_indices = op.Unique(indices)
    unique_indices_Y = op.SequenceAt(unique_indices, 0)
```

When do model checker, failed with msg below:
```
onnx.onnx_cpp2py_export.shape_inference.InferenceError:  [ShapeInferenceError] Shape inference error(s): (op_type:aten_embedding_renorm, node name: aten_embedding_renorm_0): [ShapeInferenceError] (op_type:SequenceAt,
 node name: n2): input_sequence typestr: S, has unsupported type: tensor(int64)
```
Seems it treat unique_indices as tensor(int64), but actually it is seq(tensor(int64))

**Comment by justinchuby** [comment]
Hmm this doesn’t look like a bug now that I look at it

**Comment by cbourjau** [comment]
I am not familiar with onnxscript (which I assume this is?), but `Unique` does not return a sequence (i.e. a "single output"). Instead, it has explicitly four tensors as output:  https://github.com/onnx/onnx/blob/main/docs/Operators.md#Unique. At no point would a `Unique` operator produce a ` seq(tensor(int64))` in the final model.

This seems to me like a purely onnxscript related issue. I'd expect something like this to work:

```
(Y, indices, inverse_indices, counts) = op.Unique(indices)
# or simply
(Y, *_) = op.Unique(indices)
```

**Comment by justinchuby** [comment]
Fixed in https://github.com/microsoft/onnxscript/pull/1123. Like @cbourjau explained we need to unpack the outputs correctly.
