### ISSUE TITLE
 Is there a way to expand all the functions and subgraphs within the graph?

### ISSUE THREAD

**Issue by Jason-Young-AI** [onnx/onnx#5699]
# Ask a Question

### Question
I am attempting to expand all the functions and subgraphs into a group of nodes and integrate these nodes into the original ONNX model's graph.
For example, the model [`ResNet-preproc`](https://github.com/onnx/models/blob/main/vision/classification/resnet/README.md?plain=1#L129) provided in the ONNX Model Zoo can be visualized as show in the figure1:
 <img width="295" alt="graph" src="https://github.com/onnx/onnx/assets/33598143/2b149130-c740-4f3e-81c0-f42ca0f30d1b">[Figure 1]

The `preprocess` node is a function node, which can be expanded as depicted below:
<img width="347" alt="function_node" src="https://github.com/onnx/onnx/assets/33598143/84c402c3-57a1-4cda-b470-8a32693bd34d">[Figure 2]

Additionally, the `SequenceMap` node contains an attribute `body` which represents another graph, as shown in:
<img width="626" alt="body" src="https://github.com/onnx/onnx/assets/33598143/ee8e1edc-5afc-4283-9be7-3c3bb033164f">[Figure 3]

As a result, I aim to expand all nodes that cannot be further expanded into basic nodes and include them in the nodes of the original graph.
Is there an existing method to achieve this?

### Further information
- Relevant Area: converters, operators

**Comment by xadupre** [comment]
You may use function [inline_local_functions](https://github.com/onnx/onnx/blob/main/onnx/inliner.py#L11).

**Comment by justinchuby** [comment]
Please reopen for follow up questions, thanks!
