### ISSUE TITLE
Is it legal that 2 onnx Loop nodes in a model have body subgraph with nodes of identical name?

### ISSUE THREAD

**Issue by victorsoda** [onnx/onnx#5702]
# Ask a Question

### Question

Hi, I have an ONNX model that has 2 onnx Loop nodes, say Loop A and Loop B.
In Loop A's body subgraph, there is an Add node with the name "my_add".
In Loop B's body subgraph, there is also an Add node with the identical name "my_add".
**Is this illegal or legal, according to ONNX rules? (2 subgraphs having nodes with identical names)**

In addition, suppose that Loop A's body subgraph has an output with the name "my_output", and so does Loop B.
**Is this illegal or legal? (2 subgraphs having outputs with identical names)**

Thanks a lot for your kind reply :-)

**Comment by xadupre** [comment]
Are they nested loops? The node names is not an issue, the name is optional and can be left empty. The same output name may be an issue. The inner loop knows every existing result when the loops begin. There may be a name conflict depending on what you need to to. The other loop only knows the inner loop outputs. +@gramalingam

**Comment by victorsoda** [comment]
@xadupre  Thanks a lot for your timely reply!
In fact, the situation I am meeting is not nested loops, but two separate loop nodes.
The ONNX model is like this:
              ... other nodes ...
                |                    |
            Loop A          Loop B 
                |                    |
              ... other nodes ...
Inside Loop A (body subgraph):
                max_trip    cond          y_in    ------> inputs
                     \              |             /
                       ... some nodes ...
                                    |
                              Add node (name = "Add_522")
                                    |
                       ... some nodes ...
                     /             |              \
           cond_out         y_out       scan_out   ---------> outputs
 (name = "cond_234")
Inside Loop B (body subgraph):
                max_trip    cond          y_in    ------> inputs
                     \              |             /
                       ... some nodes ...
                                    |
                              Add node (name = "Add_522")
                                    |
                       ... some nodes ...
                     /             |              \
           cond_out         y_out       scan_out   ---------> outputs
 (name = "cond_234")

For this case, what I really wonder is:
1. There is a node with the name "Add_522" inside Loop A, and simultaneously there is another node with an identical name "Add_522". Is this illegal?
2. Loop A's body subgraph has an output with the name "cond_234", and simultaneously Loop B's body subgraph also has an output with the name "cond_234". Is this illegal?

Thx again for your response!

**Comment by victorsoda** [comment]
@gramalingam Hi, would you please take a look at this question? I really appreciate your help!

**Comment by xadupre** [comment]
There should not be any issue since any intermediate result in a graph is similar to a local variable. Did you experience any issue with a particular runtime?

**Comment by victorsoda** [comment]
@xadupre Thank you very much! If the case I've mentioned is legal, then my question is exactly answered, and I will close this question.
The background is as follows: I successfully ran the model by onnxruntime without experiencing any issues, but I found the case was not supported by another framework that I was developing. Therefore, I want to find out whether it was an issue of the model or my framework.
Really appreciate your prompt reply :-)

**Comment by gramalingam** [comment]
Hi, I agree that it should be legal.

First, the [IR document](https://github.com/onnx/onnx/blob/main/docs/IR.md) mentions that "Within a namespace, each name MUST be unique for each given graph." Further, the checker does not check or complain about this.

If it were nested subgraphs, at least, one could argue (since for tensor names, duplicate names are not allowed in nested subgraphs either and one could argue for uniformity in the rules), but this is not a case of nested subgraphs. Finally, the node names are not critical for the semantics of the execution (it is present primarily for documentation/debugging).
