### ISSUE TITLE
[Feature request] Listing ops that have a function prototype.

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx#5707]
### What is the problem that this feature solves?

Is there a way to list the ops in the spec that have a function prototype / function build?

### Are you willing to contribute it (Y/N)

Yes

**Comment by AlexandreEichenberger** [comment]
I guess I can grep for `schema.BuildFunction` in the onnx repo?

**Comment by justinchuby** [comment]
Do you mean whether the op is defined as a function? I can see 
<img width="558" alt="image" src="https://github.com/onnx/onnx/assets/11205048/f746c571-6aaf-4615-95c0-fd2b6f128f49">

**Comment by justinchuby** [comment]
Exposed as `schema.has_function` and `schema.has_context_dependent_function` according to https://github.com/onnx/onnx/blob/21bff4e55dcefecc069c679115baae6b00caa0d5/docs/docsgen/source/onnx_sphinx.py#L94C28-L94C82

**Comment by AlexandreEichenberger** [comment]
Got it, good to know. Never paid attentions to these fields, now I know where to look at.
