### ISSUE TITLE
New Release for Onnx

### ISSUE THREAD

**Issue by anirudhacharya** [onnx/onnx#571]
Can we have a new release for Onnx repo. I see that since the [v1.0.1](https://github.com/onnx/onnx/releases/tag/v1.0.1) release there has been no new release, while there has been considerable progress in support for new operators and their corresponding tests.

**Comment by lupesko** [comment]
@anirudhacharya not objecting, but would be useful to list the operators and functionality added since 1.0.1

**Comment by anirudhacharya** [comment]
I think the following is the change list. 
@houseroad @bddppq Please  do let me know if I have missed any changes.

* Operators fixed and added - cast, reshape, Pool, Shape, Size, concat, Pow, Slice, TopK, structured, reducible control flow, Unsqueeze op 
(PR #497) (PR #436) (PR #496) (PR #529) (PR #513) (PR #525) (PR #390) (PR #532) (PR #587) (PR #569) (PR #552)

* Test cases added and fixed - global avg, max pool, Slice,  cast, pow, Concat, Reshape, TopK, softplus, softsign, softmax, logsoftmax, hardmax transpose, Max, Min, Mean, Sum. +9 math operators, reciprocal, logic operators,  Clip, Div, Mul, Pow, Sub; Elu, LeakyRelu, Selu, HardSigmoid, gather, Conv  
(PR #468) (PR #472) (PR #487) (PR #500) (PR #507) (PR #516) (PR #529) (PR #506) (PR #509) (PR #546) (PR #548) (PR #543) (PR #574) (PR #596)

* Build Issues on various platforms -
   ** Provide option to enforce /MD or /MT when building with MSVC (PR #602)
   ** Fix ONNX library build for Windows
   ** Add to_string for Android (PR #597)
   ** Handle situations where protobuf is built on the fly (PR #592)
   ** fix CMakeLists on Windows (PR #589)
   ** travis tweaks to make sure the correct versions of python are installed (PR #584)
   ** Improve CMakefile of ONNX (PR #563)
   ** Don't include pybind11 if its target is alreadt exported (PR #550)
   ** Call gen_proto.py in cmake (PR #538)
   ** Couple cmake fixes (PR #521)
   ** Fix build on mac (PR #514)
   ** setup cmake (PR #469)
   ** Remove onnx-caffe2 reference (PR #558)

* Naming and Convention changes -
   ** Add ONNX_NAMESPACE around rnn/old.cc (PR #605)
   ** Change the model file extension from .pb to .onnx (PR #541)
   ** Make onnx namespace configurable (PR #484)

* Bug Fixes -
   ** Fix `get_attribute_value` can not get `g` field bug (PR #599)
   ** Fix treatment of optional inputs.

* Test Framework Changes -
   ** Add outputs_info into run_node backend interface (PR #588)

* IR Changes -
   ** Add option to use customized protoc (PR #594)
   ** preserve value infos if they are needed (PR #561)
   ** Check whether perm exists before using it (PR #559)
   ** Adding int32, int64 and double input data types for featurevectorizer (PR #547)
   ** Sort the attributes of NodeProto generated by make_node (PR #479)

* Other Changes -
   ** Change the cached model checking logic (PR #545)
   ** Fix the way we find protobuf library (PR #539)
   ** Modulize ONNX libraries (PR #528)
   ** Printable Graph support for nested graphs + sugar (PR #483)
   ** Lexical scoping in checker (PR #485)
   ** osx travis support (PR #566)

**Comment by lupesko** [comment]
This is a pretty significant set of changes.
I'm supportive of cutting a new release.
I propose v1.1 since we're adding a bunch of new operators with this release (per [semver guidance](https://semver.org/#spec-item-7))

Any comments/suggestions?

**Comment by dzhulgakov** [comment]
@anirudhacharya - thanks a lot for compiling the change list! This looks good (maybe add that "control flow" is formally is still in experimental)

v1.1 sounds great

Also cc @prasanthpul @linkerzhang

**Comment by lupesko** [comment]
Bounce. @prasanthpul ?

**Comment by prasanthpul** [comment]
we are good with the listed items, i.e. up to and including #605

**Comment by jspisak** [comment]
+1 we are good as well.
