### ISSUE TITLE
[Feature request][RecSys][LLM] An example showing how to do embedding lookup with sparse tensor as input in onnx?

### ISSUE THREAD

**Issue by pmixer** [onnx/onnx#5717]
### System information

onnx 1.15

### What is the problem that this feature solves?

More concrete examples concerning the use of sparse tensor.

### Describe the feature

Connecting https://github.com/onnx/onnx/issues/3685 and https://github.com/onnx/onnx/pull/3398

For 2D sparse tensor cases, tensorflow-onnx could convert tf.nn.safe_embedding_lookup_sparse operator to onnx model.

Well, it actually break the operator into too many pieces, will looks far from the best possible from the performance view.

I tried to utilize onnx sparse tensor to make things simpler, write code as below:

```python
import onnx
import numpy as np

indices = onnx.helper.make_sparse_tensor_value_info('indices', onnx.TensorProto.INT64, [1024, 1024])

gathered_embeddings = onnx.helper.make_sparse_tensor_value_info('gathered_embeddings', onnx.TensorProto.FLOAT, [None, None, 128])

embeddings_np_mat = np.zeros((10000, 128)).astype(np.float32)

embedding_table = onnx.numpy_helper.from_array(embeddings_np_mat, 'embedding_table')

lookup_op = onnx.helper.make_node('Gather', ['indices', 'embedding_table'], ['gathered_embeddings'])

graph = onnx.helper.make_graph([lookup_op], 'sparse_lookup', [indices], [gathered_embeddings], [embedding_table])

model = onnx.helper.make_model(graph)

model.opset_import[0].version = 19

onnx.checker.check_model(model)

with open('sparse_lookup.onnx', 'wb') as f:
    f.write(model.SerializeToString())

# import pdb; pdb.set_trace()

inferred_model = onnx.shape_inference.infer_shapes(model)

# from onnx.reference import ReferenceEvaluator

# sess = onnx.reference.ReferenceEvaluator(model)

# sparse_tensor = onnx.helper.make_sparse_tensor(indices=onnx.numpy_helper.from_array(np.array([[0, 0], [512, 233]])), values=onnx.numpy_helper.from_array(np.array([2333,999])), dims=[1024,1024])

# sess.run(['gathered_embeddings'], {'indices': sparse_tensor})

import onnxruntime as ort

sess = ort.InferenceSession('sparse_lookup.onnx') # Type Error: Type 'sparse_tensor(int64)' of input parameter (indices) of operator (Gather) in node () is invalid. 
```

any idea to make it the above embedding lookup with sparse tensor as input example work? THX!

BTW, may anyone tell whether the onnx supported 2D sparse tensor could be used for converting tf.RaggedTensor as well?

### Are you willing to contribute it (Y/N)

None

**Comment by justinchuby** [comment]
cc @gramalingam @xadupre around sparse tensor usage

**Comment by xadupre** [comment]
Sparse support is very limited in ONNX, operator [Gather](https://onnx.ai/onnx/operators/onnx__Gather.html#l-onnx-doc-gather) does not support sparse tensors in the documentation. That's why it does not work in the ReferenceEvaluator. The RaggedTensor in tf2onnx is exported as two arrays. The converter takes care of it that way.

**Comment by justinchuby** [comment]
Does ORT support sparse tensors? I learned from someone that it does

**Comment by pmixer** [comment]
> Does ORT support sparse tensors? I learned from someone that it does

it does, e.g. for a model with tf.nn.safe_embedding_lookup_sparse call, the model could be converted to onnx and run by ORT.

well, the problem is, tf2onnx breaks the original tf op into 100+ onnx operators, looks bad from performance view.

**Comment by pmixer** [comment]
> Sparse support is very limited in ONNX, operator [Gather](https://onnx.ai/onnx/operators/onnx__Gather.html#l-onnx-doc-gather) does not support sparse tensors in the documentation. That's why it does not work in the ReferenceEvaluator. The RaggedTensor in tf2onnx is exported as two arrays. The converter takes care of it that way.

thx for the clarification, thus I'm sure Gather could only tensor and dense embedding table lookup now.

I'll try tf2onnx to check it's implementation details for RaggedTensor support later.

**Comment by justinchuby** [comment]
@fatcat-z on tf2onnx
