### ISSUE TITLE
Release discrepencies

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5719]
The recent GitHub release of [ONNX 1.15](https://github.com/onnx/onnx/releases/tag/v1.15.0) diverges from both the sdist on PyPI and 1.15.0 release branch head. Is this intentional? For example the changes in https://github.com/onnx/onnx/pull/5355 are present in the PyPI release but not the GitHub release.

**Comment by adityagoel4512** [comment]
Is it possible that the release tagging has gone wrong? It looks like essentially the main branch was released instead.

**Comment by liqunfu** [comment]
I just fixed it. The tag was incorrectly linked to the main branch. Now it is associated with the release 1.15.0 branch. Thanks for pointing this out.
