### ISSUE TITLE
ONNX 1.15.0: missing symbols (absl) onnx_gtests

### ISSUE THREAD

**Issue by sl1pkn07** [onnx/onnx#5740]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
fail build due missing absl symbols

```
[ 87%] Linking CXX executable onnx_gtests
/usr/bin/ld: CMakeFiles/onnx_gtests.dir/onnx/test/cpp/data_propagation_test.cc.o: undefined reference to symbol '_ZN4absl12lts_2023080212log_internal17MakeCheckOpStringIllEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'
/usr/bin/ld: /usr/lib/libabsl_log_internal_check_op.so.2308.0.0: error adding symbols: DSO missing from command line
```

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Archlinux
- ONNX version (*e.g. 1.13*): 1.15.0
- Python version: 3.11
- GCC/Compiler version (if compiling from source): gcc  13.2.1
- CMake version: 3.27.7
- Protobuf version: 25
- abseil-cpp: 20230802.1

### Reproduction instructions
  cmake -S onnx -B build \
    -DCMAKE_BUILD_TYPE='None' \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON \
    -DONNX_BUILD_TESTS=ON \
    -DONNX_USE_LITE_PROTO=ON \
    -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DCMAKE_CXX_STANDARD=17

  cmake --build build

### Expected behavior
build ok

**Comment by liqunfu** [comment]
It could be a breaking change introduced by the new abseil. see: https://github.com/onnx/onnx/blob/2cf3749d475e513cb9a2124f89308e214d4020db/CMakeLists.txt#L231

Please downgrade and try. Or follow this: https://github.com/protocolbuffers/protobuf/issues/14500

**Comment by sl1pkn07** [comment]
fails only if enable unitest (builds sucessfull without it). disable it works, so i keep disable unfil proper fix

please keep open until that (for trace)

greetings
