### ISSUE TITLE
Onnx.checker.check_ Model (model) reports an error with no edges, but when Netron opens the model, it shows that there are edges

### ISSUE THREAD

**Issue by CZXIANGOvO** [onnx/onnx#5742]
# Ask a Question

### Question

I have a model that, after loading, onnx. checker. check_ Model (model) error：onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input '94' of node:name: BatchNormalization_77 OpType: BatchNormalization  is not output of any previous nodes., but when Netron opens the model, it shows edges。When I use ort. ReferenceSession for inference, there is no error but it will terminate directly.
### Further information
- Relevant Area: 
onnx：1.15.0
onnxruntime:1.14.1

- Is this issue related to a specific model?
**Model name**: 
**Model opset**: 

### Notes

![image](https://github.com/onnx/onnx/assets/121651120/c36bb73f-356a-4ea7-8d98-051782ca1bc6)
![image](https://github.com/onnx/onnx/assets/121651120/4ee07aa6-8b60-4377-baf0-e040266e5181)

### Model 
https://drive.google.com/file/d/1JyCy8sjyndEyxlrEyvQH4NYNkhluZOv1/view?usp=drive_link

**Comment by gcunhase** [comment]
Any updates on this?
