### ISSUE TITLE
MeanVarianceNormalization not working with float16 inputs

### ISSUE THREAD

**Issue by harrisonvanderbyl** [onnx/onnx#5753]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
MeanVarianceNormalization fails type checking if it has float16 inputs
(op_type:MeanVarianceNormalization): [ShapeInferenceError] (op_type:Add): B has inconsistent type tensor(float)

### System information
- OS Platform and Distribution : Ubuntu 23.04
- ONNX version (*e.g. 1.13*): 1.15.0
- Python version: 3.11.4
- GCC/Compiler version (if compiling from source): N/A
- CMake version: N/A
- Protobuf version: 3.20.2 (Only version that works anyway)
- Visual Studio version (if applicable):--> N/A

### Reproduction instructions
```
node = onnx.helper.make_node(
                'MeanVarianceNormalization',
                inputs=[x],
                outputs=[name],
                axes=dim,
            )

```
- Attach the ONNX model to the issue (where applicable) : Will do if needed

### Expected behavior
For the node to output float16 output if float16 input given to it

### Notes
This wouldnt even be needed if your groupnormalization worked the same way as pytorch

**Comment by justinchuby** [comment]
Cc @liqunfu
