### ISSUE TITLE
[shape inference] Shape inference does not produce shapes for gridsample

### ISSUE THREAD

**Issue by WillPen** [onnx/onnx#5759]
I have a onnx model contains a  gridsample node like below
![image](https://github.com/onnx/onnx/assets/26559655/ae752633-0853-4bcb-8dc1-5cb3c7e0e248)

but after infer_shapes.the gridsample has not got the output shape.

**My system information:**
onnx version:1.14.1/1.15.0

**Expected behavior**
The output shape of operator Gridsample should appear.

**Comment by justinchuby** [comment]
Cc @liqunfu
