### ISSUE TITLE
pytorch converted AvgPool test case with wrong pads size

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#576]
@houseroad 
https://github.com/onnx/onnx/tree/master/onnx/backend/test/data/model/pytorch-converted/test_AvgPool3d
pads in graph is [0, 0, 0] not [0, 0, 0, 0, 0, 0]. For 3d input, pads size should be 6.

I have not checked similar cases (other AvgPool3d and MaxPool3d). Please take a look.

**Comment by spidyDev** [comment]
@fumihwh @houseroad 
All  AvgPool3d tests have same issue ( pad is (0,0,0) )
MaxPool3d pads are correct.

**Comment by houseroad** [comment]
I have updated the cases in this pr: https://github.com/onnx/onnx/pull/677
