### ISSUE TITLE
Support Unicode characters in proto paths

### ISSUE THREAD

**Issue by captainIT** [onnx/onnx#5761]
# Bug Report

### Is the issue related to model conversion?

No
### Describe the bug

1. the onnx name is simple   Chinese，such as  **“士大夫.onnx”** 
2. ```
     output_file_path = 'D:\\士大夫.onnx'
     onnx.checker.check_model(output_file_path)```
3. after run ，throw  **ValidationError**
```
   onnx.onnx_cpp2py_export.checker.ValidationError: Unable to open proto file: D:\士大夫.onnx. Please check if it is a valid proto. 
 [fail_check("Unable to open proto file: ", proto_path, ". Please check if it is a valid proto. ");]
```

https://github.com/onnx/onnx/blob/b60f69412abb5393ab819b936b473f83867f6c87/onnx/common/file_utils.h#L21

### System information

Windows
onnx version 1.15.0

**Comment by justinchuby** [comment]
Do we need this: https://en.cppreference.com/w/cpp/filesystem/path/u8path? Need to get around `std::fstream` it seems like

**Comment by captainIT** [comment]
https://github.com/onnx/onnx/pull/5806
