### ISSUE TITLE
How to initial an internal node with random value like np.random.rand using parser

### ISSUE THREAD

**Issue by Jack-liu1998** [onnx/onnx#5770]
I meet another problem
How can i initial an internal node with random value like np.random.rand，I don't find any example to do that in  parser_test.cc

my code
```
graph_txt = """
            agraph (float%s input) => (float%s output)
            <float%s filter, float%s bias>
            {
                fc = MatMul(input, filter)
                output = Add(fc, bias)
            }
            """ % (input_shape, output_shape, filter_shape, bias_shape)
        graph_def = onnx.parser.parse_graph(graph_txt)
```
error
```
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'filter' of node: 
name:  OpType: MatMul
 is not output of any previous nodes.
```
Thanks

**Comment by liqunfu** [comment]
Is that because you did not assign value to "filter"? regarding your question on random value. there are random ops you can use. e.g. https://github.com/onnx/onnx/blob/main/docs/Operators.md#randomnormal

**Comment by Jack-liu1998** [comment]
Got it, randomnormal op can initial data,
**but i want its val to be const, for i need to compare the result of onnx and other format like ncnn that converted from onnx.**

I think about two ways to do that, both ugly:
1. convert np array to str and pass to parser
2. change internal node to input

Both way are ugly，do I have a more graceful way to do that

**Comment by liqunfu** [comment]
See if this works:
filter = helper.make_tensor('filter', TensorProto.FLOAT, [2, 2], np.random.rand(4).astype(float).tolist())
model.graph.initializer.extend(filter)

**Comment by Jack-liu1998** [comment]
Thanks, It works!
And extend need a list input ,so it should be model.graph.initializer.extend([filter])

Thanks for your help
