### ISSUE TITLE
Different results of consecutive runs for same input

### ISSUE THREAD

**Issue by lmatt-bit** [onnx/onnx#5780]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
Model Arch: GRU based seq2seq + attention.
With certain input, i will get different results of consecutive runs(for loop). The 1st result is the expected one, 2nd and later results are different  but they are the same.
However if i set enable_mem_pattern=False in python or setMemoryPatternOptimization(false) in java, the 2nd and later results are the same the 1st run. I don't know why.
Beside, for most inputs, the result is the same, except few inputs. And i couldn't figure out the pattern in the bad inputs. 

### System information
window + onnxruntime 1.16.1 + python api
linux + onnxruntime 1.15.1 + java api

### Reproduction instructions
see above

### Expected behavior

see above

**Comment by cbourjau** [comment]
This is an [onnxruntime](https://github.com/microsoft/onnxruntime) issue. This repository is about the ONNX standard itself and some fundamental tooling.

**Comment by justinchuby** [comment]
Please create an issue against ONNX Runtime as @cbourjau suggested. Thanks!
