### ISSUE TITLE
[Feature request] onnx.printer / parser support ID with '/', ':', etc

### ISSUE THREAD

**Issue by yocox** [onnx/onnx#5784]
### What is the problem that this feature solves?

Currently the onnx.printer prints ID without quoted, like

```
<
  ir_version: 7,
  opset_import: [ "" : 10 ]
>
agraph (float[N, 128] X, float[128, 10] W, float[10] B) => (float[N, 10] C)
{
    Foo = MatMul(X, W)
    Bar = Add(Foo, B)
    C = Softmax(Bar)
}
```

It is fine if the ID contains only `[a-zA-Z_]` however, a lot of models has special character in the ID of node, for example the llama has and node named `/model/layers.0/self_attn/Mul_3_output_0` it contains `.`, `/`, some other op even has `:`. I want to enhance the printer / parser, But I am not sure which spec is better:

1. Single quoted ID, any char except `'` can be used in the name. The printed ID is quoted. The parser respect that , too.
2. Don't quoted, just treat `/`, `:`, `.` as `_`. But I am not sure will it confused with other syntax.

Dose anyone have any suggestions? Thank you.

### Describe the feature

Quoted the ID or extend the acceptable char in the parser.

### Are you willing to contribute it (Y/N)

Yes

**Comment by justinchuby** [comment]
These are invalid names according to the ONNX spec. If you are seeing graphs with these names (as we have seen practically) please raise an issue with the producers of the graph. Thanks!
