### ISSUE TITLE
test_qlinearmatmul_3D_int8_float16 failed with MacRelease

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#5792]
# Bug Report
https://github.com/onnx/onnx/actions/runs/7080240890/job/19271566562

### Is the issue related to model conversion?
No

### Describe the bug
Test failed with test_qlinearmatmul_3D_int8_float16, etc. See link to the release ci

### System information
 na

### Reproduction instructions
NA
### Expected behavior
CI for MacRelease should pass
### Notes
None

**Comment by justinchuby** [comment]
cc @xadupre
