### ISSUE TITLE
Runtime behavior incorrect when removing the weights from the initializer prior to constant folding

### ISSUE THREAD

**Issue by GertDekkersMagics** [onnx/onnx#5801]
# Bug Report

### Describe the bug
As an example, I've created a model that comprises of a Conv layer encapsulated with Quantize and Dequantize operations in a QDQ manner. Specifically, a quantize-dequantize op is added to the input, weight and output of the conv operation.  In order to transform such a model to a QOP representation, we typically use the [graph optimization available in onnx](https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html). For this to work we need to fold the Quantize operation into the weight values of the model. For this, we adopted a piece of code that was used [here](https://github.com/microsoft/onnxruntime/blob/d673e39ad89a709d5896510bcd496927567b4b79/tools/python/remove_initializer_from_input.py#L14) and [here](https://github.com/daquexian/onnx-simplifier/blob/e0ddd0e61bfda8f6da52cc9d9890ba6b6493a198/onnxsim/onnx_simplifier.py#L60), which essentially removes the initializer for a specific input (i.e. that of the weight). 

However, when adopting this code it destroys ONNX runtime, in that sense that the outputs are incorrect. 

### System information
- OS Platform and Distribution: Ubuntu 22.04
- ONNX version: 1.14.1
- Python version: 3.10.12
- Numpy version: 1.26.0
- Protobuf version: 4.24.3

### Reproduction instructions
To reproduce, first download the following onnx model.
[model_qdq.zip](https://github.com/onnx/onnx/files/13649407/model_qdq.zip)

And then run the following script.
```
import os

import numpy as np
import onnx
import onnxruntime


def onnx_inference(model_path: str, data: np.ndarray):
    sess_options = onnxruntime.SessionOptions()
    session = onnxruntime.InferenceSession(
        model_path, sess_options, providers=["CPUExecutionProvider"]
    )
    input_name = session.get_inputs()[0].name
    return session.run([], {input_name: data})


input_shape = (1, 2, 9, 9)
data = np.random.random(input_shape).astype(np.float32)

onnx_model = onnx.load("model_qdq.onnx")

inputs = onnx_model.graph.input
name_to_input = {}
for input_ in inputs:
    name_to_input[input_.name] = input_
for initializer in onnx_model.graph.initializer:
    if initializer.name in name_to_input:
        inputs.remove(name_to_input[initializer.name])

model_qdq_opt_path = os.path.join("model_qdq_opt.onnx")
onnx.save(onnx_model, model_qdq_opt_path)

output_model_qdq = onnx_inference("model_qdq.onnx", data)
output_model_qdq_opt = onnx_inference("model_qdq_opt.onnx", data)

np.testing.assert_allclose(output_model_qdq, output_model_qdq_opt)
```

### Expected behavior
Given the code I would've expect that the behaviour would not change such that *output_model_qdq* and *output_model_qdq_opt* are identical.

**Comment by justinchuby** [comment]
Hi! For ONNX Runtime issues, please open an issue in the microsoft/onnxruntime repository for better support. Thanks!
