### ISSUE TITLE
[DISCUSSION] ONNX R Binding

### ISSUE THREAD

**Issue by terrytangyuan** [onnx/onnx#581]
Hi ONNX developers,

I put together an R package for ONNX on top of ONNX Python API. The repo is currently located [here](https://github.com/terrytangyuan/onnx-r). I had a comment in https://github.com/onnx/onnx/issues/426 but I feel like it's worth discussing in a separate issue here. 

The R API is already usable but still needs some additional work on examples/documentations/testing, etc.  I wonder if you would consider the following two options for next steps:
 1) transferring ownership of the repo to ONNX Github org
 2) placing the R package inside a separate folder under this onnx/onnx repo. 

It would be good to leverage the infrastructure you setup and make sure Python and R APIs are always up-to-date and consistent with each other. 

Thanks,
Yuan

**Comment by houseroad** [comment]
@dzhulgakov @prasanthpul shall we adopt https://github.com/terrytangyuan/onnx-r in our onnx org?

Shall we keep the r wrappers in the onnx-r repo instead of merged into onnx major repo?

**Comment by thiusl** [comment]
@terrytangyuan Wow been waiting for this! I just tried it and everything seems to be working already!  Thanks for your efforts! My $0.02:
* It might be good to move the package to here to have more visibility so more people from the community could contribute to it (it doesn't make sense for the package to be located under a personal account since it's totally community efforts).
* It's tightly-coupled to the Python API so better to keep them altogether for testing purposes. 
* From user perspective, install via `devtools::install_github("onnx/onnx", subdir = "xxx")` is much easier to remember unless I find the repo url in the CRAN page for this package.

**Comment by prasanthpul** [comment]
I think we can host it in under the ONNX GitHub in an onnx-r repo for now.  @terrytangyuan will you be maintaining it?

**Comment by terrytangyuan** [comment]
@prasanthpul Yes, I’ll maintain it.

**Comment by terrytangyuan** [comment]
@prasanthpul Could you grant me permission to ONNX Github so I can start the transfer process?

**Comment by prasanthpul** [comment]
@terrytangyuan I'm going to create a repo called onnx/r-bindings that you have permissions to. Sound good?

**Comment by terrytangyuan** [comment]
@prasanthpul It might be better to add me to the org so I can just transfer the repo over (commit histories will be maintained and redirect from old location would also work). We can discuss the name later if needed.

**Comment by terrytangyuan** [comment]
When I was trying to transfer the repo, I got message like "You don’t have the permission to create repositories on onnx". I believe I just need minimal access in the org. ["By default, all organization members can create repositories for the organization and transfer repositories into the organization."](https://help.github.com/articles/repository-permission-levels-for-an-organization/#creating-repositories).

**Comment by fumihwh** [comment]
@terrytangyuan Don't worry. I think they will create a onnx/onnx-r repository and give you permission to.

**Comment by bddppq** [comment]
@terrytangyuan Sorry for late reply. I have just created the new repo here: https://github.com/onnx/r-bindings and added you as admin.

**Comment by terrytangyuan** [comment]
Thanks! I've renamed it to be onnx-r (onnx-bindings sounds really weird and onnx-r is the one that makes sense to me) and moved everything over there. Closing this issue for now.

**Comment by terrytangyuan** [comment]
Could anyone from ONNX team activate Travis for onnx-r repo for me? - https://github.com/onnx/onnx-r Thanks!
