### ISSUE TITLE
Why is uint32 mapped to uint64 in _STORAGE_TENSOR_TYPE_TO_FIELD

### ISSUE THREAD

**Issue by bhshp** [onnx/onnx#5819]
# Ask a Question

### Question

Mapped value duplicated in `_STORAGE_TENSOR_TYPE_TO_FIELD` on [the current main branch](https://github.com/onnx/onnx/blob/8e61b60d81e5eea32acf664d222d7e4048f71c8c/onnx/mapping.py#L179), which is incorrect by its naming.

[onnx/mapping.py:179](https://github.com/onnx/onnx/blob/main/onnx/mapping.py#L179)
```python
    # ... omitted
    int(TensorProto.UINT32): "uint64_data",
    # ... omitted
```

### Further information
- Relevant Area: internal representation

- Is this issue related to a specific model?
No

### Notes
No

**Comment by justinchuby** [comment]
I assume it is because the spec uses this field to store unsigned 32 and 64 data. 

https://github.com/onnx/onnx/blob/a66b596981156097da5988cf6f9527817e5bcad7/onnx/onnx.proto#L633

**Comment by bhshp** [comment]
@justinchuby Thanks for your reply!. Now I see, but the naming is still seemingly weird.
