### ISSUE TITLE
ImportError: No module named optimizer

### ISSUE THREAD

**Issue by dinglong1020** [onnx/onnx#582]
Problem:
         while running OnnxCaffe2Import.ipynb, there is import error
 environment:
         ubuntu 1604
         onnx (1.0.1) 
         onnx-caffe2 (1.0.0)

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2f7422fdd6e7> in <module>()
      1 import onnx
----> 2 import caffe2.python.onnx.backend
      3 
      4 # Prepare the inputs, here we use numpy to generate some random inputs for demo purpose
      5 import numpy as np

/home/dinglong1020/caffe2/build/caffe2/python/onnx/backend.py in <module>()
     40 import onnx.numpy_helper
     41 import onnx.defs
---> 42 import onnx.optimizer
     43 from onnx.backend.base import Backend, Device, DeviceType, namedtupledict
     44 

ImportError: No module named optimizer

**Comment by bddppq** [comment]
`onnx.optimizer` is a new module added recently and it's not included in any of previous releases. Please re-install onnx from our latest github master.

**Comment by dinglong1020** [comment]
Is not use commond "pip install onnx" to install latest version onnx, and the latest version of the github master's tag is as same as my installer. Please tell how to install onnx from lastest github master

**Comment by bddppq** [comment]
We don't bump the version tag for each master commit.
Please do `pip install git+git://github.com/onnx/onnx.git@master` to directly install from github.

**Comment by bddppq** [comment]
https://github.com/onnx/onnx/issues/571

**Comment by sdews** [comment]
Please remember do 'pip uninstall onnx' and then do 'pip install git+git://github.com/onnx/onnx.git@master'.

**Comment by sdews** [comment]
Please remember do `pip uninstall onnx` firstly and then do `pip install git+git://github.com/onnx/onnx.git@master`.

**Comment by bddppq** [comment]
@dinglong1020 have you had a chance to see whether directly installing from github solve your issue?

**Comment by leoll2** [comment]
As of 2021 March 15th, the optimizer is no longer part of the `onnx` repo ([source](https://github.com/onnx/onnx/pull/3288)).  

If you're installing code that depends on it and get errors, an easy workaround is to install a slightly older version of onnx:
```
pip install onnx==1.8.1
```
