### ISSUE TITLE
Different behavior between python 3.6 and python 2.7 in `make_attribute`

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#585]
Assume I have an attribute like `pads=[1, 1, 1, 1]` passed to `helper.py` L151 `make_attribute`. https://github.com/onnx/onnx/blob/master/onnx/helper.py#L151

In L187 `attr.ints.extend(int(v) for v in value)`,
python 3.6 - will extend normally as int `attr.ints=[1, 1, 1, 1]`
python 2.7 - will extend as long `attr.ints=[1L, 1L, 1L, 1L]`

This different behavior will cause some problems when frameworks attr type checker is strict.

For more information,
attr.ints is `RepeatedScalarFieldContainer` and its `_type_checker._TYPE` is `long` in python 2.7 and `int` in python 3.6. All of them are `Int64ValueChecker`.
Maybe instantiating of `AttributeProto` is different?

**Comment by bddppq** [comment]
There is no `long` in python3, it has unified what `int` and `long` in python2 to `int`.
`int(v)` with `v=1` should not return `1L` in python2. Could you give a small code snippet to reproduce the error you have seen?

**Comment by fumihwh** [comment]
@bddppq 
![image](https://user-images.githubusercontent.com/6838753/37070326-370beb8a-21fa-11e8-8839-dfad4fa7e777.png)

```
from onnx.helper import make_node

node_def = make_node("ReduceL1", ["X"], ["Y"], axes=[1, 2])
print(node_def.attribute[0].ints)
print(all([isinstance(i, long) for i in node_def.attribute[0].ints]))
```

**Comment by prasanthpul** [comment]
Is this still an issue with latest versions of everything? If so, @fumihwh can you make a PR with the fix?

**Comment by prasanthpul** [comment]
python 2.7 is end of life: https://www.python.org/downloads/
