### ISSUE TITLE
UnsatisfiableError during installation of onnx and caffe2

### ISSUE THREAD

**Issue by labsurde** [onnx/onnx#586]
I am trying to install onnx and try any converter tool such as caffe2 to onnx on a Ubuntu 16.04 box.

CASE 1) install onnx and then caffe2
So.. I installed onnx as mentioned in the onnx/README.md.
`$ conda install -c conda-forge onnx`

And then when I try to run caffe-to-onnx exporter,
I found that I needed caffe2 to download squeeznet.

So I installed caffe2 as follows (mentioned in caffe2 homepage for pre-build binaries on ubuntu) : 
`$ conda install -c caffe2 caffe2`

and conda throws an error life the following:
```
    UnsatisfiableError: The following specifications were found to be in conflict:
      - caffe2 -> protobuf >=3.4,<3.5.0a0 -> libprotobuf 3.4.0
      - onnx -> protobuf 3.5.* -> libprotobuf >=3.5.1,<3.6.0a0
    Use "conda info <package>" to see the dependencies for each package.
```

It seems like protobuf versions of caffe2 and onnx are different.

How can I run onnx and caffe2

CASE 2) install caffe2 and then onnx
So, I ran 
```
    $ conda remove onnx 
    $ conda remove protobuf 
```
and ran
```
    $ conda install -c caffe2 caffe2
```
(conda list shows protobuf version is now 3.4.1)

and then I ran
```
    $ conda install -c conda-forge onnx
```
and somehow installation does not throw any error.
(conda list shows protobuf version is 3.4.1)

In such case, when I run the top python code of Caffe2OnnxExport.ipynb, it shows error like the following: 
```
    ImportError: /home/eric/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
```

Would you let me know how I can solve these issues and run Caffe2OnnxExport.ipynb?
Thank you!

**Comment by alexionby** [comment]
Mb u can try this command:
`conda install -c ezyang onnx onnx-caffe2` 
because it rly based on protobuff 3.4.1

**Comment by labsurde** [comment]
@alexionby, thank you for the comment.
I tried 
`conda install -c ezyang onnx onnx-caffe2`
it installed 3.5.1 version of `protobuf` and `libprotobuf`. (same with the above case 1)
Again while installing caffe2 by `conda install -c caffe2 caffe2`, conda try to downgrade `protobuf` and `libprotobuf` to 3.4.1.

Interesting thing is that `tutorials/tutorials/Caffe2OnnxExport.ipynb` failed while running `import caffe2.python.onnx.frontend`. First, Jupyter Notebook shows warning message below:
<pre>
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named 'caffe2.python.caffe2_pybind11_state_gpu'​
</pre>
and then
shows a message box, saying 'The kernel appears to have died. It will restart automatically.' 

 The console of Jupyter Notebook says not much. I just logs the following: 
<pre>
[I 10:36:50.399 NotebookApp] KernelRestarter: restarting kernel (1/5)
kernel 6066ecde-7538-4198-856a-a0557616953d restarted
</pre>

gdb shows the following backtrace about this dump:
<pre>
#0  0x00007f00d7b0f64d in pybind11::detail::make_new_python_type (rec=...)
   from /home/eric/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#1  0x00007f00d7b16861 in pybind11::detail::generic_type::initialize (this=this@entry=0x7ffff2e2c4e0, 
    rec=...)
   from /home/eric/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#2  0x00007f00d7b03be3 in pybind11::class_<onnx::OpSchema>::class_<> (name=0x7f00d7c5b8de "OpSchema", 
    scope=..., this=0x7ffff2e2c4e0)
   from /home/eric/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#3  onnx::pybind11_init ()
    at /data/users/ezyang/anaconda2/conda-bld/onnx_1508902035545/work/onnx/cpp2py_export.cc:20
#4  0x00007f00d7b05752 in onnx::PyInit_onnx_cpp2py_export ()
   from /home/eric/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so
#5  0x00005652de877c14 in _PyImport_LoadDynamicModuleWithSpec ()
#6  0x00005652de877e15 in _imp_create_dynamic ()
#7  0x00005652de7713a1 in PyCFunction_Call ()
#8  0x00005652de8279b3 in _PyEval_EvalFrameDefault ()
#9  0x00005652de7f9f24 in _PyEval_EvalCodeWithName ()
#10 0x00005652de7fadc1 in fast_function ()
#11 0x00005652de800f95 in call_function ()
#12 0x00005652de82262a in _PyEval_EvalFrameDefault ()
...
</pre>

**Comment by wzhongyuan** [comment]
I met the same error as well, does anybody have solution how to fix it ?

**Comment by abhi9716** [comment]
Any solution for fixing this error? I am facing same kind of problem.

**Comment by daniel-j-h** [comment]
I just ran into this. The problem is the conda caffe2 package is built against libprotobuf version x and the onnx conda package from the conda-forge channel seems to be build against libprotobuf y. This leads to undefined symbols, or even segfaults when importing both onnx and caffe in the same Python application.

My workaround is to install caffe2 from the caffe2 channel with conda and compile onnx against the libraries from the conda caffe2 environment. This makes sure onnx is compiled against the same libprotobuf version caffe2 was compiled against.

Something along the lines of

```
conda install -c caffe2 caffe2

git clone https://github.com/onnx/onnx.git
cd onnx
git checkout vX.Y.Z
git submodule update --init --recursive
python setup.py install
```

Replace X.Y.Z with the latest version tag.

Note: compiling onnx requires additional dependencies (such as cmake, make).

**Comment by prasanthpul** [comment]
@houseroad has caffe2 been updated?
