### ISSUE TITLE
If it is not continuous inference, the running speed will be slower, how to improve?

### ISSUE THREAD

**Issue by hurri2000** [onnx/onnx#5870]
following code is used to test the onnx inferance speed with GPU
the first time is very long, which is reasonable,  the first 10 times is continuouse infer， the speed is normal, ~10ms

but the last 10 times, when put a interval (2s) between each inference, the speed becomes lower, ~100ms, seems need some time to  innitialize CUDA.

how to solve this problem? because interval inference is what we usually meet in real situation. too long inferance time is unacceptable

code:
  sess = ort.InferenceSession(onnx_path, providers=[provider])
  input = np.random.rand(*input_shape).astype(np_type)   
  epoch = 20
  for i in range(epoch):
      start_time = time.time()
      output = sess.run(["output"], {"input": input})[0]
      end_time = time.time()
      elapsed_time = (end_time - start_time) * 1000

      print(f"ONNX Runtime: {provider}. Running time: {elapsed_time:.0f} ms")
      times.append(elapsed_time)
      print(i)
      if i>10:
          time.sleep(2)

result:
ONNX Runtime: CUDAExecutionProvider. Running time: 9465 ms
0
ONNX Runtime: CUDAExecutionProvider. Running time: 10 ms
1
ONNX Runtime: CUDAExecutionProvider. Running time: 9 ms
2
ONNX Runtime: CUDAExecutionProvider. Running time: 9 ms
3
ONNX Runtime: CUDAExecutionProvider. Running time: 9 ms
4
ONNX Runtime: CUDAExecutionProvider. Running time: 10 ms
5
ONNX Runtime: CUDAExecutionProvider. Running time: 10 ms
6
ONNX Runtime: CUDAExecutionProvider. Running time: 9 ms
7
ONNX Runtime: CUDAExecutionProvider. Running time: 9 ms
8
ONNX Runtime: CUDAExecutionProvider. Running time: 10 ms
9
ONNX Runtime: CUDAExecutionProvider. Running time: 11 ms
10
ONNX Runtime: CUDAExecutionProvider. Running time: 10 ms
11
ONNX Runtime: CUDAExecutionProvider. Running time: 30 ms
12
ONNX Runtime: CUDAExecutionProvider. Running time: 72 ms
13
ONNX Runtime: CUDAExecutionProvider. Running time: 123 ms
14
ONNX Runtime: CUDAExecutionProvider. Running time: 123 ms
15
ONNX Runtime: CUDAExecutionProvider. Running time: 124 ms
16
ONNX Runtime: CUDAExecutionProvider. Running time: 124 ms
17
ONNX Runtime: CUDAExecutionProvider. Running time: 119 ms
18
ONNX Runtime: CUDAExecutionProvider. Running time: 123 ms

**Comment by justinchuby** [comment]
Please feel free to create an issue in the [microsoft/onnxruntime](https://github.com/microsoft/onnxruntime/issues) repository. Be sure to include version numbers for relevant packages in your environment. Thanks!
