### ISSUE TITLE
Python3.12 release

### ISSUE THREAD

**Issue by stellaraccident** [onnx/onnx#5881]
Hi, I'm starting to get requests for python3.12 builds (https://github.com/llvm/torch-mlir/issues/2798#issuecomment-1916181382) and we have a dep on this project.

Do you know if the next release will have 3.12 support?

**Comment by justinchuby** [comment]
Yes

**Comment by justinchuby** [comment]
You may test with the main branch or the latest onnx-weekly release, which supports Python 3.12 already.
