### ISSUE TITLE
[Feature request] Provide a means to convert to numpy array without byteswapping

### ISSUE THREAD

**Issue by tehbone** [onnx/onnx#5885]
### System information

ONNX 1.15

### What is the problem that this feature solves?

Issue onnx/tensorflow-onnx#1902 in tf2onnx occurs on big endian systems, and it is my observation that attributes which end up converting to integers are incorrectly byteswapped because the original data resided within a tensor. If `numpy_helper.to_array()` could be updated to optionally not perform byteswapping, then that could help solve this issue.

### Alternatives considered

As an alternative, additional logic could be added in tf2onnx to perform byteswapping on the data again, but this seems excessive.

### Describe the feature

I believe this feature is necessary to improve support for big endian systems.

### Feature Area

converters

### Are you willing to contribute it (Y/N)

Yes

**Comment by gramalingam** [comment]
I am not sure I understand. Byteswap is called only on big endian systems, because the numpy array layout needs to be swapped to get the ONNX's layout. Are you saying that the original numpy array does not have a valid big-endian layout?

**Comment by tehbone** [comment]
Not exactly. The tensor does have the appropriate layout, but that in the specific context that the tensor data is being used in `tf2onnx` it requires the data in the native byte order as opposed to little endian byte order.

**Comment by xadupre** [comment]
Why not adding a parameter to to_array?

**Comment by tehbone** [comment]
That was my thinking. However, I no longer think this is needed after some additional debugging. I opened #5901 to address the actual underlying problem.
