### ISSUE TITLE
exporting pytorch to onnx fails, instead of an error, prints infinite number calculations

### ISSUE THREAD

**Issue by ninono12345** [onnx/onnx#5886]
# Bug Report

When exporting a model to onnx using this code:
torch.onnx.export(self.track_wrapper,
                    (im_patches, self.train_feat, self.target_labels, self.train_ltrb),
                    "new_full_implicit_batch1t.onnx",
                    verbose=False,
                    export_params=True,
                    do_constant_folding=True,
                    opset_version=17,
                    input_names=['im_patches','train_feat','target_labels','train_ltrb'],
                    output_names=['scores_raw','bbox_preds'])

I get an output like this, only it is like this for an infinite amount:

(243,512,.,.) =
 0.001 *
 -8.2217

(244,512,.,.) =
 0.01 *
  2.7684

(245,512,.,.) =
 0.01 *
  7.3573

(246,512,.,.) =
 0.01 *
 -2.2212

(247,512,.,.) =
 0.001 *
  8.3807

(248,512,.,.) =
 0.01 *
 -7.1563

(249,512,.,.) =
 -0.1012

(250,512,.,.) =
 0.01 *
  2.5295

(251,512,.,.) =
 0.001 *
 -8.2534

(252,512,.,.) =
 0.001 *
  3.6239

(253,512,.,.) =
 0.01 *
 -1.9034

(254,512,.,.) =
 0.001 *
 -2.5435

(255,512,.,.) =
 0.001 *
  2.9510

(256,512,.,.) =
 0.01 *
 -1.2922
[ torch.cuda.FloatTensor{256,512,1,1} ]

Perhaps anybody knows why this is happening. I dried moving all the tensors and weights to cuda, then to cpu, but I'm still getting the same result...
Like I said this output goes for infinity, this is just the ending...
The pytorch model by itself works perfectly fine

If any more info is required please ask

Thank you

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Windows 10
- ONNX version (*e.g. 1.13*): onnx with pytorch 2.1.2+cu121
- Python version: 3.10.13

**Comment by gramalingam** [comment]
Please ask this in the pytorch repo, which seems more appropriate for this question.
