### ISSUE TITLE
CI Pipeline broken after onnxruntime 1.17 release

### ISSUE THREAD

**Issue by galagam** [onnx/onnx#5894]
# Bug Report

### Describe the bug
The Mac OS CI pipeline is failing due to failures in pytest onnx/test/test_backend_onnxruntime.py
ONNXRunTime 1.17 was released yesterday (01/31/2024) https://pypi.org/project/onnxruntime/
which means that tests that were previously skipped are now getting executed (and fail). 
See condition to skip tests: https://github.com/onnx/onnx/blob/main/onnx/test/test_backend_onnxruntime.py#L263

Also, it seems like these tests aren't running in the Linux CI because it passes there (fails on local Linux after updating ONNXRunTime to v1.17).

### Reproduction instructions
pip install onnxruntime==1.17.0
pytest onnx/test/test_backend_onnxruntime.py

### Expected behavior
All tests should pass

**Comment by liqunfu** [comment]
thank you @galagam
