### ISSUE TITLE
#5812 breaks Linux release pipeline

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5900]
https://github.com/onnx/onnx/pull/5812 breaks the release pipeline by using np.broadcast_shapes which is not available until numpy 1.20, but the release pipeline specifies a minimally supported version to be 1.16. 

We can either avoid the use of np.broadcast_shapes, or bump the min supported numpy version to 1.20. 

@galagam

**Comment by justinchuby** [comment]
I think bumping the version is a reasonable move.

**Comment by adityagoel4512** [comment]
For what it's worth, NumPy's recommended [deprecation schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) for the community suggests bumping the version should be fine.

**Comment by galagam** [comment]
Thanks for letting me know.
I only use `np.broadcast_shapes` for an assertion, so it's not really critical for my logic.
However, it looks like a good opportunity to bump the minimal Numpy version. `1.20.0` was released 3 years ago, so it's a reasonable requirement IMO.

I've issued #5902 to bump the numpy version

**Comment by justinchuby** [comment]
Thanks!
