### ISSUE TITLE
test FAILED   QuantizeLinearOpMLFloat16Test.Float8

### ISSUE THREAD

**Issue by daviddrell** [onnx/onnx#5907]
# Bug Report

When executing the build command given below, the build failed with a failed test case. Also, there appear to be memory leaks detected. The build.log is attached.

### Describe the bug
[  FAILED  ] QuantizeLinearOpMLFloat16Test.Float8

[----------] Global test environment tear-down
[==========] 4054 tests from 285 test suites ran. (2197772 ms total)
[  PASSED  ] 4053 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] QuantizeLinearOpMLFloat16Test.Float8

 1 FAILED TEST
  YOU HAVE 15 DISABLED TESTS

### System information

Edition	Windows 10 Pro for Workstations
Version	22H2
Installed on	‎6/‎29/‎2022
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0

Microsoft Visual Studio Community 2022
Version 17.6.5
VisualStudio.17.Release/17.6.5+33829.357
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA907
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.6.326.62524
Azure Functions and Web Jobs Tools

C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23087.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

GitExtensions   1.0
Git Extensions is a graphical user interface for Git that allows you to control Git without using the command-line

GitHub Copilot   1.100.0.0 (v1.100.0.0@6ff082509)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.100.306 (v1.100.0)

Linux Core Dump Debugging   1.0.9.33801
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 11.7 Wizards   11.7
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2022.2.0.22095
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2022.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•Icons from Axialis Software used under the licensing terms found here: www.axialis.com
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•Breakpad Copyright ©2006, Google Inc. All rights reserved.
•The OpenGL Extension Wrangler Library
Copyright ©2008-2016, Nigel Stewart (nigels@users.sourceforge.net), Copyright ©2002-2008, Milan Ikits (milan.ikits@ieee.org), Copyright ©2002-2008, Marcelo E. Magallon (mmagallo@debian.org), Copyright ©2002, Lev Povalahev. 
All rights reserved. 
•LIBSSH2 Copyright ©2004-2007 Sara Golemon (sarag@libssh2.org), Copyright ©2005,2006 Mikhail Gusarov (dottedmag@dottedmag.net),Copyright ©2006-2007 The Written Word, Inc.,Copyright ©2007 Eli Fant (elifantu@mail.ru),Copyright ©2009-2014 Daniel Stenberg., Copyright ©2008, 2009 Simon Josefsson.
All rights reserved. 
•Protobuf Copyright ©2014, Google Inc. All rights reserved.
•xxHASH Library Copyright ©2012-2014, Yann Collet. All rights reserved. 
•FMT Copyright ©2012 - 2016, Victor Zverovich 
•Font Awesome Copyright 2018 Fonticons, Inc. 
•ELF Definitions Copyright (c) 2010 Joseph Koshy, All rights reserved.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2022.2.0.22095
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

Python - Django support   17.0.23087.1
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.23087.1
Profiling support for Python projects.

Python with Pylance   17.0.23087.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.6.0.2327201+a6a61fdfa748eaa65aab53dab583276e26af4a3e
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.33606.364
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.33801
Visual C++ for Linux Development

Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

- windows :
- ONNX version (*e.g. 1.13*):
- Python version:
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:
- Visual Studio version (if applicable):-->

ONNX source git hash

commit 2ac381c55397dffff327cc6efecf6f95a70f90a1 (HEAD, tag: v1.16.3, origin/rel-1.16.3)

### Reproduction instructions

.\build.bat  --use_cuda  --cudnn_home "C:\Program Files\NVIDIA\CUDNN\v8.9" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7"

**Comment by daviddrell** [comment]
[LastTestsFailed.log](https://github.com/onnx/onnx/files/14166314/LastTestsFailed.log)
[LastTest.log](https://github.com/onnx/onnx/files/14166316/LastTest.log)
[CTestCostData.txt](https://github.com/onnx/onnx/files/14166319/CTestCostData.txt)

**Comment by gramalingam** [comment]
Hi, I think it would be better to create this issue in onnxruntime: https://github.com/microsoft/onnxruntime/issues 

Also, @xadupre, in case you have any ideas, thanks!

**Comment by xadupre** [comment]
Looking at the code, the tests were enabled when onnx was updated. Before, it was only working on a development version of onnx as it requires opset 19. The test should fail on every OS not only windows. It is an issue for onnxruntime.
