### ISSUE TITLE
AllowConsumed and EnforceConsumed would not be part of op definition?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#595]
AllowConsumed and EnforceConsumed are in the scope of implementation optimization. It would be better to have backend to decide how to handle it. Thoughts? @ezyang @dzhulgakov @ebarsoum @gramalingam

**Comment by gramalingam** [comment]
I agree. These should be removed from the operator registration mechanism since we are not talking about any specific implementation of an operator.

**Comment by bddppq** [comment]
Removing these sounds reasonable to me

**Comment by houseroad** [comment]
https://github.com/onnx/models/issues/26

**Comment by houseroad** [comment]
It's already removed. :-)
