### ISSUE TITLE
Need to know the setuptools version for using onnx in developer mode

### ISSUE THREAD

**Issue by Abhishek-TyRnT** [onnx/onnx#5978]
# Ask a Question

I am trying to install onnx using `pip install -e .`. But I get the following error 

> Traceback (most recent call last):
>   File "/project/setup.py", line 321, in <module>
>     setuptools.setup(
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/project/setup.py", line 253, in run
>     return super().run()
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 34, in run
>     self.install_for_development()
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
>     self.run_command('build_ext')
>   File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "/project/setup.py", line 259, in run
>     return super().run()
>   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
>     self.build_extensions()
>   File "/project/setup.py", line 288, in build_extensions
>     if self.editable_mode:
>   File "/usr/lib/python3.10/distutils/cmd.py", line 103, in __getattr__
>     raise AttributeError(attr)
> AttributeError: editable_mode
> 
> 

The problem seems to be that setuptools version is probably wrong

My current version for setuptools is 59.5.0 . Can anyone help me to know what is lask working version of setuptools. Also requirements.txt do not have hardcoded version.

**Comment by justinchuby** [comment]
>64. You may find the information in pyproject.toml. Pip should be able to install the correct version for you though.

**Comment by Abhishek-TyRnT** [comment]
I used a clean python environment... Now it is working... Maybe some dependency version got meesed up. Thanks..
