### ISSUE TITLE
Installation OSX

### ISSUE THREAD

**Issue by jexp** [onnx/onnx#6]
(You should add the requirement of installing protobuf so that protoc is available to the readme).

Trying to install on OSX, any idea what I'm doing wrong?

```
Ich:onnx mh$ pip install onnx
Requirement already satisfied: onnx in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from onnx)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/site-packages (from onnx)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/site-packages (from protobuf->onnx)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from protobuf->onnx)
Ich:onnx mh$ pip3 install onnx
Requirement already satisfied: onnx in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: protobuf in /usr/local/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/site-packages (from onnx)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf->onnx)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.6/site-packages (from protobuf->onnx)
Ich:onnx mh$ python -c 'import onnx'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "onnx/__init__.py", line 7, in <module>
    from . import checker, helper
  File "onnx/checker.py", line 14, in <module>
    from onnx import defs
  File "onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export as C
ImportError: No module named onnx_cpp2py_export
```

**Comment by jexp** [comment]
Installation from source also fails:

```
pip install -e .
Obtaining file:///Users/mh/d/python/onnx
Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages (from onnx==0.1)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from onnx==0.1)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/site-packages (from onnx==0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from protobuf->onnx==0.1)
Installing collected packages: onnx
  Found existing installation: onnx 0.1
    Uninstalling onnx-0.1:
      Successfully uninstalled onnx-0.1
  Running setup.py develop for onnx
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/mh/d/python/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to onnx.egg-info/requires.txt
    writing onnx.egg-info/PKG-INFO
    writing top-level names to onnx.egg-info/top_level.txt
    writing dependency_links to onnx.egg-info/dependency_links.txt
    reading manifest file 'onnx.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'third_party'
    writing manifest file 'onnx.egg-info/SOURCES.txt'
    running build_ext
    running build_proto
    compiling /Users/mh/d/python/onnx/onnx/onnx.proto
    building 'onnx.onnx_cpp2py_export' extension
    clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mh/d/python/onnx -I/Users/mh/d/python/onnx/third_party/pybind11/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /Users/mh/d/python/onnx/onnx/cpp2py_export.cc -o build/temp.macosx-10.10-x86_64-2.7/Users/mh/d/python/onnx/onnx/cpp2py_export.o -std=c++11 -stdlib=libc++
    /Users/mh/d/python/onnx/onnx/cpp2py_export.cc:1:10: fatal error: 'pybind11/pybind11.h' file not found
    #include <pybind11/pybind11.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of onnx
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/Users/mh/d/python/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/mh/d/python/onnx/
```

**Comment by galv** [comment]
Not sure what's going in your first message, but I'm guessing you forgot to pull the pybind11 submodule.

`git clone --recursive https://github.com/onnx/onnx.git` works when you initially cloned

Otherwise, if you've already cloned, `git submodule update --init` (I think)

**Comment by bddppq** [comment]
I believe in the first case it's because your current path is at the top level of the source? So when you do `import onnx` python will try use the "onnx" directory in the source directory, which doesn't have all the generated files. Try `cd` to other path then it should work.

In the second case (i.e. install from source), you need to add `--recursive` flag to the `git clone` command as stated in the installation instruction.

**Comment by Savant92** [comment]
I'm using windows 7 , i have tried installing protobuf but protoc is not being installed . Is there any other libraries to be add or am i making some mistakes ?

`D:\Neural Network>pip install onnx
Collecting onnx
  Using cached onnx-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Could not find "protoc" executable!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sidharth\appdata\local\temp\pip-build-frmbzo\onnx\`

**Comment by Savant92** [comment]
`D:\Neural Network>pip install onnx
Collecting onnx
  Using cached onnx-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Could not find "protoc" executable!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sidharth\appdata\local\temp\pip-build-frmbzo\onnx\`

**Comment by Savant92** [comment]
hi, I'm using windows 7.I have tried to install protobuf but protoc is not being installed.Do i need to add some libraries or am i making some mistakes?

`D:\Neural Network>pip install onnx
Collecting onnx
  Using cached onnx-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Could not find "protoc" executable!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sidharth\appdata\local\temp\pip-build-frmbzo\onnx\`

**Comment by tidyjiang8** [comment]
I got the same issue as @Savant92 mentioned above on Ubuntu 16.04.
Tried by pip `sudo pip install onnx` or from source `sudo pip install -e onnx/`
Attach the log:
```
Obtaining file:///home/work/ai/onnx
    Complete output from command python setup.py egg_info:
    Could not find "protoc" executable!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/work/ai/onnx/
```

**Comment by ezyang** [comment]
Hello @tidyjiang8 and @Savant92, you can solve the missing protoc issues by getting a protobuf installation. I've opened a PR for the README which suggests using conda to get it: https://github.com/onnx/onnx/pull/8  Please give it a try and let me know how it goes.

**Comment by bddppq** [comment]
@tidyjiang8 and @Savant92 the issue should be `protoc` is not properly installed on your system.
On ubuntu I think `sudo apt-get install protobuf-compiler` will do the installation.
On windows, please see here https://github.com/google/protobuf/blob/master/src/README.md#c-installation---windows

**Comment by tidyjiang8** [comment]
Thanks for all your response.
- Previous issue is fixed but get another after `conda install -c conda-forge protobuf numpy`.I don't know why it say version error:
```
 cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /tmp/pip-build-8kUJka/onnx/onnx/defs/schema.h:18:0,
                   from /tmp/pip-build-8kUJka/onnx/onnx/cpp2py_export.cc:7:
  /tmp/pip-build-8kUJka/onnx/onnx/onnx.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
   #error This file was generated by a newer version of protoc which is
    ^
  /tmp/pip-build-8kUJka/onnx/onnx/onnx.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
   #error incompatible with your Protocol Buffer headers.  Please update
    ^
  /tmp/pip-build-8kUJka/onnx/onnx/onnx.pb.h:14:2: error: #error your headers.
   #error your headers.
    ^
```
- Then after **`sudo apt-get install protobuf-compiler`**, all problems disappeared. CNNX is correctly installed now.

**Comment by ezyang** [comment]
@tidyjiang8 Yes, this is a pretty famous problem with protobufs, which is that it's very easy to end up in a situation where your PATH (which is how protoc is determined) mismatches with your include path (which is how the include headers are done.) Clearly our setup.py isn't robust enough in this case. Would be good to fix!

**Comment by Savant92** [comment]
Thank you for the response.

The previous issue is fixed with `conda install -c conda-forge protobuf numpy` .But new issue has been raised.

`    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'`
`    cpp2py_export.cc`
 `   c:\users\sidharth\appdata\local\temp\pip-build-``40h46a\onnx\third_party\pybind11\include\pybind11\detail/common.h(70) : fatal error`
`C1189: #error :  pybind11 requires MSVC 2015 update 3 or newer`
`    error: command 'C:\\Users\\Sidharth\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ ``for Python\\9.0\\VC\\Bin\\cl.exe' fail`
`ed with exit status 2`

**Comment by bddppq** [comment]
@Savant92 From the error message it's one of the onnx dependencies [pybind11](https://github.com/pybind/pybind11) requires MSVC 2015 update 3 or newer.

onnx uses pybind11 to create Python bindings to C++ code.

**Comment by bddppq** [comment]
I'm closing this one now, since the original issue was about installation issues on OSX, which I believe should have been resolved.

@Savant92 If you still have issues when installing `onnx` on windows platform, please create a new issue so we can better keep track of it. Thanks.

**Comment by darknoon** [comment]
@bddppq I just encountered this on macOS 10.12.6 (16G1114), using pip & python 2.7

I was able to make progress via `$ brew install protobuf` but had to reference this issue to get onnx to install.
