### ISSUE TITLE
There is an error in converting LLaVA model. It should not be adapted to this model. How should this model be converted to onnx

### ISSUE THREAD

**Issue by woaichixihong** [onnx/onnx#6004]
# Ask a Question

### Further information

```
`The argument `from_transformers` is deprecated, and will be removed in optimum 2.0.  Use `export` instead
Framework not specified. Using pt to export the model.
Traceback (most recent call last):
  File "/root/llava-v1.5-7b-hf/2onnx2.py", line 8, in <module>
    model = ORTModelForCausalLM.from_pretrained(model_id, from_transformers=True, export=True)
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 662, in from_pretrained
    return super().from_pretrained(
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/modeling_base.py", line 399, in from_pretrained
    return from_pretrained_method(
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/onnxruntime/modeling_decoder.py", line 603, in _from_transformers
    main_export(
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/exporters/onnx/__main__.py", line 279, in main_export
    model = TasksManager.get_model_from_task(
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/exporters/tasks.py", line 1867, in get_model_from_task
    model = model_class.from_pretrained(model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.`
```

- Is this issue related to a specific model?
**Model name**: LLaVA

**Comment by woaichixihong** [comment]
> # Ask a Question
> ### Question
> ### Further information
> `The argument `from_transformers`is deprecated, and will be removed in optimum 2.0. Use`export` instead Framework not specified. Using pt to export the model. Traceback (most recent call last): File "/root/llava-v1.5-7b-hf/2onnx2.py", line 8, in <module> model = ORTModelForCausalLM.from_pretrained(model_id, from_transformers=True, export=True) File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 662, in from_pretrained return super().from_pretrained( File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/modeling_base.py", line 399, in from_pretrained return from_pretrained_method( File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/onnxruntime/modeling_decoder.py", line 603, in _from_transformers main_export( File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/exporters/onnx/__main__.py", line 279, in main_export model = TasksManager.get_model_from_task( File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/optimum/exporters/tasks.py", line 1867, in get_model_from_task model = model_class.from_pretrained(model_name_or_path, **kwargs) File "/root/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained raise ValueError( ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM. Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.`
> 
> * Is this issue related to a specific model?
>   **Model name**:LLaVA

> 
> ### Notes

**Comment by justinchuby** [comment]
The error is `ValueError: Unrecognized configuration class <class 'transformers.models.llava.configuration_llava.LlavaConfig'> for this kind of AutoModel: AutoModelForCausalLM.`. It doesn't seem like an onnx-related error. I suggest checking with the huggingface transformers maintainers
