### ISSUE TITLE
ONNX build issue with python-3.5.2

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#601]
I am trying to compile ONNX from source, using below command line on conda env with python 3.5.2

MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ sudo python setup.py install

I get error:

building 'onnx.onnx_cpp2py_export' extension
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/srajanku/anaconda2/envs/work-env-python-3.5.2/include -arch x86_64 -DONNX_NAMESPACE=onnx -I/Volumes/Data/mxnet/onnx -I/Volumes/Data/mxnet/onnx/third_party/pybind11/include -I/Users/srajanku/anaconda2/envs/work-env-python-3.5.2/include/python3.5m -I/Users/srajanku/anaconda2/envs/work-env-python-3.5.2/include/python3.5m -c /Volumes/Data/mxnet/onnx/onnx/checker.cc -o build/temp.macosx-10.6-x86_64-3.5/Volumes/Data/mxnet/onnx/onnx/checker.o -std=c++11 -stdlib=libc++
**clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)**

If I use conda env with python 2.7 , the same command works fine

**Comment by bddppq** [comment]
Looks like it's the python 3.5.2 in your conda environment doesn't support MACOSX_DEPLOYMENT_TARGET=10.9, should not be related to onnx. Maybe try `MACOSX_DEPLOYMENT_TARGET=10.7`?

**Comment by spidyDev** [comment]
Tried with python 3.6 , seems to work. Thanks @bddppq
