### ISSUE TITLE
[Feature request] Shape Inference for Einsum instead of Rank Inference

### ISSUE THREAD

**Issue by peishenyan** [onnx/onnx#6011]
### System information

v1.15.0

### What is the problem that this feature solves?

In the development of ONNX Runtime, we need know the output shape of each Op node for static graph compilation. However, we found that we could use onnx shape inference to achieve almost all output shapes except the output shape of Einsum. In `onnx/defs/math/defs.cc`, we found that there was only Rank Inference function for Einsum instead of Shape Inference. In a nutshell, shape inference for Einsum will be helpful for static graph compilations.

### Describe the feature

Just like the shape inference for all other ops, shape inference for Einsum should infer the output shape instead of rank according to the input shapes and the equation attribute. 
We have developed a prototype version, which can be found in PR https://github.com/onnx/onnx/pull/6010. We would be delighted if this feature request is accepted. Alternatively, we are more than willing to provide assistance in incorporating this feature.

### Will this influence the current api (Y/N)?

No

### Feature Area

shape_inference

### Are you willing to contribute it (Y/N)

Yes

**Comment by gramalingam** [comment]
Completed by https://github.com/onnx/onnx/pull/6010
