### ISSUE TITLE
When will outstanding security vulnerabilities be fixed?

### ISSUE THREAD

**Issue by micahstairs** [onnx/onnx#6018]
# Ask a Question

### Question
When are you planning to release the next version of Onnx so that the outstanding security vulnerabilities are patched?

### Further information
- https://vuldb.com/?id.254653 (fixed by https://github.com/onnx/onnx/commit/66b7fb630903fdcf3e83b6b6d56d82e904264a20)
- https://vuldb.com/?id.254654 (fixed by https://github.com/onnx/onnx/commit/08a399ba75a805b7813ab8936b91d0e274b08287)

- Is this issue related to a specific model?
No

**Comment by andife** [comment]
The release logistics for the next release 1.16 (which will contain the fixes) could be found here: https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.16.0

@cjvolzka

**Comment by andife** [comment]
The current release 1.16.0 addresses the security issues
