### ISSUE TITLE
onnx.load() -> Can't Open this page

### ISSUE THREAD

**Issue by 6894556** [onnx/onnx#6023]
# Ask a Question

### Question

Hi, when I run `onnx.load(path/to/onnx)` on my jupyter notebook, it starts buffer and turns out like the attached images.
How can I load my onnx file?

### Further information
- versions
> - onnx==1.15.0
> - super_gradients==3.6.1

- Is this issue related to a specific model?
> I have no idea. My model is fine-tuned YOLO_NAS_M from super-gradients.

### Notes

![q1](https://github.com/onnx/onnx/assets/96480127/651558c4-e9a1-41f8-ab3d-311e4a0f8960)
![q2](https://github.com/onnx/onnx/assets/96480127/69fc3e44-a04a-4988-a91e-8c9f1f8bd278)
![q3](https://github.com/onnx/onnx/assets/96480127/29ec0b91-aa80-40dc-8bde-b19c59b17fd1)
![q4](https://github.com/onnx/onnx/assets/96480127/265eabe6-3b42-444e-a158-a8c45ca17ac0)

**Comment by justinchuby** [comment]
Assign the model to a variable. Otherwise jupyter notebook tries to print the model out which can be huge and crash the page.
