### ISSUE TITLE
Support for collective operations / MPI primitives

### ISSUE THREAD

**Issue by vincent-mayer** [onnx/onnx#6026]
## Ask a Question

Hi, 
I'd like to understand whether ONNX has planned to add support for collective operations / MPI primitive likes `reduce_scatter`, `all_gather` and the like, similar to what [StableHLO](https://github.com/openxla/stablehlo/blob/main/docs/spec.md) offers? If not, I'd be really curious about the reasoning and how onnx supports LLMs and distributed inference?
Thanks!

**Comment by gramalingam** [comment]
There is an on-going working-group on ONNX extensions to support multi-device (distributed) inference. See the [slack channel](https://lfaifoundation.slack.com/archives/C05JY32GCCS) for more info. Opinions and suggestions welcome. Onnxruntime uses custom operators for such collective operations. If there is interest in the community, PRs to promote these ops into ONNX standard are also welcome.

**Comment by vincent-mayer** [comment]
Thanks for the info @gramalingam! Unfortunately I can't access the workspace. Is there a way to get access?

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx#discuss

**Comment by vincent-mayer** [comment]
Thanks!
