### ISSUE TITLE
RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node.

### ISSUE THREAD

**Issue by Priyanshu88** [onnx/onnx#6029]
# Bug Report

### Is the issue related to model conversion?

Yes
### Describe the bug

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_16_output_0_ReduceMax_Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1}, requested shape:{1}

### System information

onnx 1.15.0
onnxruntime 1.16.3
python 3.8.10

### Reproduction instructions

I am using the below config to convert the rtmo model to onnx model with the help of mmdeploy
https://github.com/open-mmlab/mmdeploy/blob/main/configs/mmpose/pose-detection_rtmo_onnxruntime_dynamic.py
```
onnx_config = dict(
    output_names=['dets', 'keypoints'],
    dynamic_axes={
        'input': {
            0: 'batch',
        },
        'dets': {
            0: 'batch',
        },
        'keypoints': {
            0: 'batch'
        }
    })

codebase_config = dict(
    post_processing=dict(
        score_threshold=0.05,
        iou_threshold=0.5,
        max_output_boxes_per_class=200,
        pre_top_k=2000,
        keep_top_k=50,
        background_label_id=-1,
    ))
```
### Expected behavior

Full log describing the path
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/quantization/quantize.py", line 435, in quantize_static
    calibrator.collect_data(calibration_data_reader)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/quantization/calibrate.py", line 304, in collect_data
    self.intermediate_outputs.append(self.infer_session.run(None, inputs))
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_15_output_0_ReduceMax_Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1}, requested shape:{1}

### Notes

Kindly help me in conversion as I needed it.

**Comment by gramalingam** [comment]
Hi, I don't understand the issue. The onnxruntime error message seems a valid error: you cannot reshape a zero-sized tensor into a tensor of size 1. So, it looks like an error in the model (or model-conversion).

**Comment by Priyanshu88** [comment]
@gramalingam I have edited the issue of input shape and requested shape.

When keeping the  batch size as 32, am getting below failure.
`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Reshape_16_output_0_ReduceMax_Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1}, requested shape:{1}
`
When keeping the batch size as 1, am getting below failure. 
`[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/Tile_output_0_ReduceMax_Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,0,1}, requested shape:{1}
`

**Comment by gramalingam** [comment]
@Priyanshu88 : You could ask in the onnxruntime repo (https://github.com/microsoft/onnxruntime/issues). It would help if you provide the onnx model and input to reproduce the error. I still think the error looks like a valid error message, so it could be an error in the model/exporter ... and maybe asking in mmlab would be more appropriate.

**Comment by Priyanshu88** [comment]
But this is at the time of conversion through the onnx_config i mentioned earlier. I am not yet on training or inference generation, i hope this to be the right place to ask.

**Comment by justinchuby** [comment]
For open-mmlab generated models, it may be a good idea to consult with developers of https://github.com/open-mmlab.

**Comment by gramalingam** [comment]
> But this problem is coming up for the conversion of model from .pth to .onnx through the onnx_config i mentioned earlier

The onnx config you mention seems to be a feature of open-mmlab, not ONNX itself.
