### ISSUE TITLE
When exporting from torch, the result of the input varies depending on the dummy input.

### ISSUE THREAD

**Issue by parkkyungjun** [onnx/onnx#6031]
# Ask a Question

### Question

When exporting from torch, the result of the input varies depending on the dummy input. What's wrong with this?

### Further information
- Relevant Area: 

torch.onnx.export(model, (dummy_input, th), model_path, verbose=True, export_params=True,
                      opset_version=12,
                      do_constant_folding=True,
                      input_names=['input', 'threshold'], output_names=['output1', 'output2'])
      
in my model forward
there is torch.cdist function 

I am comparing the value saved in advance when performing the cdist operation with the output of the model after storing it in the model class's self.

I think cdist is the cause. And when using cdist, the speed is also very slow (cdist take almost 6 second )
help me
        
        

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by gramalingam** [comment]
I think it would be better to ask this question in the pytorch (to onnx converter) repo. @thiagocrepaldi

**Comment by parkkyungjun** [comment]
> I think it would be better to ask this question in the pytorch (to onnx converter) repo. @thiagocrepaldi 

 I solved cause from another issue. Thank you
