### ISSUE TITLE
Clarify default value of `axis` for `DequantizeLinear` when input rank is 1

### ISSUE THREAD

**Issue by mgehre-amd** [onnx/onnx#6067]
# Ask a Question

### Question
[DequantizeLinear](https://onnx.ai/onnx/operators/onnx__DequantizeLinear.html) says both that
- the default value of `axis` is `1` 
- and that for `axis`, the `accepted range is [-r, r-1] where r = rank(input)`.

What happens when the rank of the input is 1 and `axis` is not specified?
According to the spec, this seems to be illegal.
`onnxruntime` successfully executes such models.

**Comment by gramalingam** [comment]
Good question! It is a bit mystifying. Looking at the rest of the spec., my interpretation is that `axis` is a relevant attribute only when not doing a per-tensor quantization (that is, when doing a per-axis or blocked-quantization). And that rank of the `x_scale` input is being used to determine if it is per-tensor quantization or not. And that the default-value of axis applies only if it is not per-tensor quantization.

It would be great to improve the documentation, but the behavior seems reasonable (with some minor tradeoff to having a default-value ... it might have been better not to have a default-value and produced a warning message if the attribute is specified for per-tensor quantization).
