### ISSUE TITLE
docs/Operators.md missing input type description at Constant

### ISSUE THREAD

**Issue by IAMAl** [onnx/onnx#6146]
# Bug Report

### Is the issue related to model conversion?
NO

### Describe the bug
docs/Operators.md missing input type description at Constant.
https://github.com/onnx/onnx/blob/main/docs/Operators.md#constant

### Expected behavior
Describe input types as same as other operators.

**Comment by justinchuby** [comment]
Constant does not have an input. So there is no type constraints for input.
