### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by DevNomadAbhi** [onnx/onnx#6147]
# Ask a Question

### Question

Hi, I'm trying to integrate the onnx model in a react native project based on CLI. I've gone through the example of expo given in the docs, but it's not working (nor in expo as well as in CLI). In CLI, react native is not able to locate the onnx file and it gives me - 
![Screenshot_20240523_144034](https://github.com/onnx/onnx/assets/61016956/53f754c7-9b14-42c8-ba64-c3dfb0fc6292)

Is there any way or steps to integrate it?

**Comment by justinchuby** [comment]
If you are using ort-web, you may want to raise this issue in the microsoft/onnxruntime repository.
