### ISSUE TITLE
The PixelUnshuffle op Cannot be converted to SpaceToDepth

### ISSUE THREAD

**Issue by iamweiweishi** [onnx/onnx#6162]
# Ask a Question

### Question
The Pytorch PixelUnshuffle operator is converted as Reshape->Transpose->Reshape. 
But what I expect is SpaceToDepth in ONNX. 

### Further information
![image](https://github.com/onnx/onnx/assets/23145532/13197f5a-aef0-4af5-9f5d-bfc76dcaff2a)

**Comment by justinchuby** [comment]
You may use the rewriter to rewrite the graph as you wish: https://onnxscript.ai/tutorial/rewriter/rewrite_patterns.html

**Comment by shubhambhokare1** [comment]
Can look into this.

**Comment by DenDen047** [comment]
The Step 3 in page 4 could be useful.
https://openaccess.thecvf.com/content/CVPR2023W/MobileAI/supplemental/Berger_QuickSRNet_Plain_Single-Image_CVPRW_2023_supplemental.pdf
