### ISSUE TITLE
Any operation to convert "Tile" to "Slice"

### ISSUE THREAD

**Issue by zw-xxx** [onnx/onnx#6168]
I am working on some Low-Rank Adaptation (LoRA) models, in which two set of `torch.nn.Parameters` are initialized and then multiplied into a complete weight matrix of Conv/Attention during inference. 

I noticed that, the weight of original Conv is converted into `Slice` type, while the torch.nn.Parameters designed for LoRA Conv/Attention are converted into `Tile` type. 

Is it possible to convert the self-designed `torch.nn.Parameters` into `Slice` type, or is it possible to convert any `Tile` type into `Slice` type?

**Comment by justinchuby** [comment]
You may consider using the rewriter for this purpose: https://onnxscript.ai/tutorial/rewriter/rewrite_patterns.html

**Comment by zw-xxx** [comment]
@justinchuby Thanks!
