### ISSUE TITLE
How to use onnx.utils.extract_model to extract more than 2GB child  onnx  model ?

### ISSUE THREAD

**Issue by Lenan22** [onnx/onnx#6172]
`    input_name = "sample"  #'/conv_in/Conv_output_0' 
    output_name = "/down_blocks.1/resnets.0/norm1/Reshape_output_0"  # 

    onnx.utils.extract_model(original_model_path, extracted_model_path, [input_name], [output_name])
`

    onnx.utils.extract_model(original_model_path, extracted_model_path, [input_name], [output_name])
  File "/home/tiger/.local/lib/python3.10/site-packages/onnx/utils.py", line 209, in extract_model
    e = Extractor(model)
  File "/home/tiger/.local/lib/python3.10/site-packages/onnx/utils.py", line 16, in __init__
    self.model = onnx.shape_inference.infer_shapes(model)
  File "/home/tiger/.local/lib/python3.10/site-packages/onnx/shape_inference.py", line 45, in infer_shapes
    model_str = model if isinstance(model, bytes) else model.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 10275992708

**Comment by xadupre** [comment]
You need to save the weights as external weights before saving the model: https://onnx.ai/onnx/api/external_data_helper.html#onnx.external_data_helper.convert_model_from_external_data.

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it if this answer does not solve it.
