### ISSUE TITLE
onnx importerror

### ISSUE THREAD

**Issue by dmoham1476** [onnx/onnx#618]
Hi 

I am trying to install onnx and then onnx-tf on ubuntu Ubuntu 16.04.3 LTS.
I ran the following commands
sudo apt-get install protobuf-compiler libprotoc-dev
pip install onnx
python -c "import onnx"

(venv_p3) dmohan@archlab1:~/ml_work/venv_p3$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dmohan/ml_work/venv_p3/lib/python3.5/site-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/home/dmohan/ml_work/venv_p3/lib/python3.5/site-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/home/dmohan/ml_work/venv_p3/lib/python3.5/site-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/dmohan/ml_work/venv_p3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf8internal26GeneratedMessageReflection29NewGeneratedMessageReflectionEPKNS0_10DescriptorEPKNS0_7MessageEPKiiiiPKviiii

Can you please help?

Deepa

**Comment by dmoham1476** [comment]
I have protobuf installed
Successfully installed protobuf-3.5.2 setuptools-38.5.2 six-1.11.0

**Comment by bddppq** [comment]
Very likely there are two versions of protobuf in your system. Could you do `protoc --version` and paste the output here?

**Comment by dmoham1476** [comment]
This is what I see
dmohan@archlab1:~/ml_work/venv_p3$ protoc --version
libprotoc 3.0.0

**Comment by bddppq** [comment]
Right and I believe the system libprotobuf installed through apt-get on Ubuntu 16.04.3 is not of protobuf version 3. Did you install the `protoc` currently in your PATH from conda? (do `which protoc`).

**Comment by dmoham1476** [comment]
I installed protoc using 

sudo apt-get install protobuf-compiler libprotoc-dev

When I do which protoc, I get this -

dmohan@archlab1:~/ml_work/venv_p3$ which protoc
/usr/local/bin/protoc

Kindly suggest if I am doing this wrong

**Comment by dmoham1476** [comment]
I checked that the libprotobuf-dev that I installed is already the newest version - 2.6.1-1.3

**Comment by bddppq** [comment]
Ok so this explains the issue. Your protoc is of version 3.0.0 while libprotobuf is of version 2.6.1. These two need to have same versions.

**Comment by dmoham1476** [comment]
I now installed protobuf 3.5.1 from https://github.com/google/protobuf/blob/master/src/README.md

Did make/etc and then tried the onnx import again, same error. My protoc --version now returns libprotoc 3.5.1.

**Comment by dmoham1476** [comment]
Anything else I can try?

**Comment by houseroad** [comment]
Have you uninstalled libprotobuf in your system? The easiest solution is keeping only one protobuf in your system.

**Comment by dmoham1476** [comment]
I tried that and it didnt work. I tried the conda install after installing anaconda, creating a conda virtualenv and installing onnx there with conda-forge, after this when i try to import onnx, I get "aborted core dumped'. I installed pytest and ran pytest, it is not able to collect any items and hence reports 0 tests ran.

**Comment by hossein1387** [comment]
I am facing the same issue, has anyone been able to fix this issue?
