### ISSUE TITLE
Shape inference check fails with external data.

### ISSUE THREAD

**Issue by stswidwinski** [onnx/onnx#6182]
# Bug Report

### Is the issue related to model conversion?
Related to it.

### Describe the bug

Consider the following code snippet (I am using `torch` for ease of model definition. This will reproduce with pure `onnx` as well):

```
import torch
import onnx

class Linear(torch.nn.Module):
    def __init__(self, input_shape: int = 784):
        super(Linear, self).__init__()
        self.input_shape = input_shape
        self.fc = torch.nn.Linear(input_shape, 10)

    def forward(self, x):
        x = torch.concat((x, torch.randn(10, 784)), 0)
        x = x.view(
            x.shape[0], self.input_shape
        )  # num samples is first dim. Then flatten the rest
        x = self.fc(x)
        return x

# Simple model representation 
model_path="/tmp/model.onnx"
torch.onnx.export(Linear(), args=(torch.randn(10, 784)), f=model_path)
onnx.checker.check_model(model_path, full_check=True)

# Ensure that the weights aren't inlined.
model = onnx.load(model_path)
onnx.save(
        model,
        model_path,
        save_as_external_data=True,
        all_tensors_to_one_file=True,
        location="external",
        size_threshold=0,
        convert_attribute=True)

# Check the model
onnx.checker.check_model(model_path, full_check=True)
```

When run, the script will produce the following output:

```
Traceback (most recent call last):
  File "/tmp/repro.py", line 35, in <module>
    onnx.checker.check_model(model_path, full_check=True)
  File "/Users/stan/.pyenv/versions/3.11.8/lib/python3.11/site-packages/onnx/checker.py", line 163, in check_model
    C.check_model_path(
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Inference error(s): (op_type:Reshape, node name: /Reshape): [ShapeInferenceError] Cannot parse data from external tensors. Please load external data into raw data for tensor: 
(op_type:Gemm, node name: /fc/Gemm): [TypeInferenceError] Input 0 expected to have type but instead is null
```

Despite the fact that `onnx.checker.check_model` is advertised to work well with external data (also see:  https://github.com/onnx/onnx/issues/3598), the full inference does not. The issue seems to be similar to https://github.com/microsoft/onnxruntime/issues/11137 which was never addressed.

### System information
```
onnx               1.16.1
onnx2torch         1.5.14
onnxscript         0.1.0.dev20240605
```

### Reproduction instructions
See above

### Expected behavior
Type inference shouldn't require the data itself, but rather just the shape information of the data. That information is still available within the `TensorProto` object.

**Comment by xadupre** [comment]
It seems an issue with the attributes. It works with ``convert_attribute=False``.

**Comment by gramalingam** [comment]
I suggest using a size_threshold value such that shape-tensors are stored in model, and not turned into external tensors. Please see discussion in https://github.com/onnx/onnx/issues/5880 ... by design, shape inference does not (can not) load external tensors.

**Comment by gramalingam** [comment]
Ok, after trying it out, my suggestion is still the same: please use an appropriate size_threshold value (or the default value). Using 0, forces shape values to be stored externally. Shape-inference for "Reshape" cannot do a proper job. This triggers the first error message (and the second error message is just a cascading error message as inference attempts to do inference for remaining nodes anyway).
