### ISSUE TITLE
ONNX export failed: Couldn't export operator narrow

### ISSUE THREAD

**Issue by fangmingbnu** [onnx/onnx#621]
I think current ONNX could not support narrow operator, could someone help to fix that? Thank you!

**Comment by houseroad** [comment]
Looks like the narrow does not have symbolic function, so the exporter in pytorch does not know how to export it. It will be great if you can follow [this tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md) to add the support in pytorch. :-)

I think in onnx, you can use slice to represent the op.

**Comment by fangmingbnu** [comment]
I try to add the narrow function (follow the slice function) in the symbolic function like this. But it doesn't work. 

def slice(g, self, dim, start, end, step):
    if step != 1:
        _unimplemented("slice", "step!=1 is currently not supported")
    return g.op("Slice", self, axes_i=[dim], starts_i=[start], ends_i=[end])


def narrow(g, self, dimension, start, length):
    # if step != 1:
    #     _unimplemented("slice", "step!=1 is currently not supported")
    return g.op("Slice", self, axes_i=[dimension], starts_i=[start], ends_i=[start+length])



It give such error. I am not familiar with this operator. Could you please help me about this? Thank  you!

 
Traceback (most recent call last):
  File "/Users/mingfang/Desktop/ming/torch_caffe/1.py", line 29, in <module>
    torch_out = torch.onnx._export(torch_model, x, "super_resolution.onnx", export_params=True)
  File "/Users/mingfang/Anaconda/anaconda2/lib/python2.7/site-packages/torch/onnx/__init__.py", line 122, in _export
    _optimize_trace(trace)
  File "/Users/mingfang/Anaconda/anaconda2/lib/python2.7/site-packages/torch/onnx/__init__.py", line 81, in _optimize_trace
    torch._C._jit_pass_onnx(trace)
  File "/Users/mingfang/Anaconda/anaconda2/lib/python2.7/site-packages/torch/onnx/__init__.py", line 248, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/Users/mingfang/Anaconda/anaconda2/lib/python2.7/site-packages/torch/onnx/symbolic.py", line 175, in addmm
    return g.op("Gemm", mat1, mat2, self, beta_f=_scalar(beta), alpha_f=_scalar(alpha))
  File "/Users/mingfang/Anaconda/anaconda2/lib/python2.7/site-packages/torch/onnx/symbolic.py", line 28, in _scalar
    return x.item()
AttributeError: 'torch.DoubleTensor' object has no attribute 'item'

**Comment by houseroad** [comment]
Here is the signature of narrow function:
```
virtual Tensor narrow(const Tensor & self, int64_t dim, int64_t start, int64_t length) const override;
```

Please follow the above to create the symbolic.

**Comment by fangmingbnu** [comment]
I found I do not have torch/csrc/autograd/generated/VariableType.h. I also do not have csrc in torch folder. Whether I should rebuild pytorch from source? Thank you!

**Comment by fangmingbnu** [comment]
Thank you for your advice! I try to install pytorch from source. Now it works.
