### ISSUE TITLE
version_converter can't convert model to opset21

### ISSUE THREAD

**Issue by mengniwang95** [onnx/onnx#6210]
# Bug Report

### Describe the bug

```
import onnx
model = onnx.load('model.onnx')
from onnx import version_converter
converted_model = version_converter.convert_version(model,21)

```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sdp/miniconda3/envs/mengni/lib/python3.10/site-packages/onnx/version_converter.py", line 37, in convert_version
    converted_model_str = C.convert_version(model_str, target_version)
RuntimeError: /github/workspace/onnx/version_converter/convert.h:86: assertInVersionRange: Assertion `version >= version_range.first && version <= version_range.second` failed: Warning: invalid version (must be between 1 and 21)
```

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*):
- ONNX version (*e.g. 1.13*): 1.16.1
- Python version: 3.12
- GCC/Compiler version (if compiling from source): 
- CMake version:
- Protobuf version:

### Reproduction instructions

optimum-cli export onnx --model meta-llama/Llama-2-7b-hf --task text-generation-with-past llama2_onnx

import onnx
model = onnx.load('llama2_onnx/model.onnx')
from onnx import version_converter
converted_model = version_converter.convert_version(model,21)

### Expected behavior
upgrade the opset to 21

**Comment by gramalingam** [comment]
Strange, I am unable to reproduce this. (I was using another model, which seemed reasonable given the error message, haven't tried generating the said llama model.)

I do get this error message, if I try to convert to version 22, but works fine for version 21 ... which makes sense, given the error-message above.

**Comment by mengniwang95** [comment]
Hi @gramalingam, which model do you try? I try llama2-7b, facebook/opt-2.7b and hf-internal-testing/tiny-random-gptj, only hf-internal-testing/tiny-random-gptj can be converted to version  21 successfully.

**Comment by justinchuby** [comment]
Can you share the model file? You may remove all the initializers to keep it small.

**Comment by mengniwang95** [comment]
you can get it by 
```bash
optimum-cli export onnx -m facebook/opt-2.7b --opset 20 --task text-generation-with-past model
```
