### ISSUE TITLE
ONNX check SIGSEV when checking the attached model

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#6211]
When checking this model:

[model.onnx.zip](https://github.com/user-attachments/files/16072892/model.onnx.zip)

**Comment by gramalingam** [comment]
Hmmm ... checker or shape-inference? with what parameters? Actually, I tried all combinations ... I get a bunch of error message, but not a crash ... wonder if it is OS-dependent? Or, may be because I have Xavier's PR from last week that fixed some shape-inference errors?

**Comment by justinchuby** [comment]
I am using `onnx.checker.check_model(..., full_check=True)`, using the latest released ONNX.

**Comment by gramalingam** [comment]
> I am using `onnx.checker.check_model(..., full_check=True)`, using the latest released ONNX.

Ok. May be Xavier's PR has already fixed this.
