### ISSUE TITLE
External Data Conversion is not saving most data with alignment support. Therefore, mmap support disabled for these initializers

### ISSUE THREAD

**Issue by ivberg** [onnx/onnx#6226]
# Bug Report

### Is the issue related to model conversion?
Yes, but the conversion is taking place in ONNX code

### Describe the bug
External Data Conversion is not saving most data in page aligned 4k sizes. Therefore, mmap support disabled for these initializers.

Here is the doc for External Data format - https://github.com/onnx/onnx/blob/main/docs/ExternalData.md
It says ""offset" (optional) - position of byte at which stored data begins. Integer stored as string. Offset values SHOULD be multiples 4096 (page size) to enable mmap support."

When using [convert_model_to_external_data](https://github.com/onnx/onnx/blob/c7717bb39c684a6d86c82a5bb1d4c0e5d90353fe/onnx/external_data_helper.py#L103)() most of the initializers ARE NOT aligned, especially all the big ones.

I created some scripts below to dump the .onnx protobuf as text, read in the offsets, and determine if they are page aligned

Related:
[ORT 21195 ](https://github.com/microsoft/onnxruntime/issues/21195) – ORT failing to fully map data tensor file (1.85GB) & instead read entire file

### System information
Windows 11
ONNX 1.16.1 
Python 3.11.9
libprotoc 27.2

### Expected behavior
MMap support is helpful to optimize memory usage for performance reasons. Using memory mapped files takes up less process commit (reserved chunk of the pagefile), and the memory can be backed by disk. System commit is a finite resource.

### Notes
Here are some scripts to help decode and determine how external data is saved, and if it's aligned

--DecodeModel.bat--
```
@echo off
if "%1"=="" (
    echo Usage: decodeModel.bat model.onnx
    exit /b 1
)

set ONNX_MODEL=%1

protoc\bin\protoc.exe --proto_path=. --decode=onnx.ModelProto onnx.proto < "%ONNX_MODEL%"
```
--
where protoc is from https://github.com/protocolbuffers/protobuf/releases
onnx.proto is from https://github.com/onnx/onnx/blob/main/onnx/onnx.proto

--checkModelExtDataAlignment.py--
```
import re
import csv
import os
import sys

def parse_initializers(text_file, csv_file):
    with open(text_file, 'r') as f:
        content = f.read()

    # Regular expression to match the initializers with external data
    initializer_regex = re.compile(
        r'initializer \{\s*(.*?)\s*\}\s*data_location: EXTERNAL',
        re.DOTALL
    )

    # Regular expression to match the name, location, offset, and length
    fields_regex = re.compile(
        r'name: "(.*?)".*?'
        r'key: "location"\s*value: "(.*?)".*?'
        r'key: "offset"\s*value: "(.*?)".*?'
        r'key: "length"\s*value: "(.*?)"',
        re.DOTALL
    )

    initializers = []

    def check_4k_alignment(offset):
        return int(offset) % 4096 == 0

    matches = list(initializer_regex.finditer(content))
    print(f"Found {len(matches)} initializers")  # Debug output

    for initializer_match in matches:
        initializer_text = initializer_match.group(1)
        # print(f"Initializer text: {initializer_text}")  # Debug output
        fields_match = fields_regex.search(initializer_text)
        if fields_match:
            name, location, offset, length = fields_match.groups()
            is_4k_aligned = check_4k_alignment(offset)
            initializers.append({
                "name": name,
                "location": location,
                "offset": offset,
                "length": length,
                "is4kaligned": is_4k_aligned
            })
            # print(f"Parsed initializer: {name}, {location}, {offset}, {length}, {is_4k_aligned}")  # Debug output

    if not initializers:
        print("No initializers with external data found.")  # Debug output

    with open(csv_file, 'w', newline='') as csvfile:
        fieldnames = ["name", "location", "offset", "length", "is4kaligned"]
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for initializer in initializers:
            writer.writerow(initializer)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python parse_initializers.py <input_text_file>")
        sys.exit(1)

    text_file = sys.argv[1]
    if not os.path.isfile(text_file):
        print(f"Error: File '{text_file}' not found.")
        sys.exit(1)

    csv_file = os.path.splitext(text_file)[0] + ".csv"
    parse_initializers(text_file, csv_file)

    print(f"CSV file created: {csv_file}")
```

**Comment by titaiwangms** [comment]
@liqunfu @gramalingam @justinchuby Any thoughts on this?

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/pull/6248#issuecomment-2407646132 we should fix the bugs mentioned in a separate PR.
