### ISSUE TITLE
Create 1.16.2 release?

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx#6239]
# Ask a Question

### Question
Should we cut a 1.16.2 release to pull in some commits from main or wait for 1.17.0?

### Further information
Primary PRs of interest to pull (will add to list if more are requested):
* https://github.com/onnx/onnx/pull/6164
* https://github.com/onnx/onnx/pull/6222

### Notes
I tried a smoke test cherry-picking the above PRs into a 1.16.1 based branch at https://github.com/onnx/onnx/pull/6238 but ran into issues. 

The Linux CI tests look like they will be the biggest issue. They are failing for "Verify ONNX with the latest numpy", "Verify ONNX with the laset protobuf", and "Verify ONNX with the minimumly supported packages".

I'm guessing the numpy issue will be related to numpy 2.0 now being the latest. Support for numpy 2.0 was added to `main` just recently via https://github.com/onnx/onnx/pull/6196. However it's a large PR that touches a lot for a patch release. Also I tried to locally cherry-pick it into my smoke test branch but hit a bunch of conflicts. 

So to create a 1.16.2, we'd have to either:
* cherry-pick numpy 2.0 support and an unknown number of other `main` commits so it can be cleanly picked
* cherry-pick numpy 2.0 and manually fixing the conflicts.
* In a 1.16.2 branch, alter the CI so it doesn't pull in the packages that are causing the issues.

There were also Windows CI issues. At a glance that might be as easy as pulling in #6173 and #6179. They cherry-pick cleanly but I don't know if there would be more issues after pulling those in.

My bandwidth is currently limited so there's not more more I can do related to getting the CIs passing for a 1.16.2 release. I can create a 1.16.2 branch and handle straight forward cherry-picks but I'd need someone else to get past the issues above. Once the CIs are passing I'd be able to finished the process and get it released if we decided to go forward with a 1.16.2.

**Comment by andife** [comment]
I tried to to limit numpy to <2 (see here: https://github.com/onnx/onnx/pull/6241),
but then Issues with pillow start to appear... I stopped there because i didn't know what ci changes made it work for python 3.12 .

Cherry-Picking numpy 2 support wouldn't be a minor upgrade according to semver in my opinion any more. 

What pillow version does 1.16.1 use? need?

**Comment by cjvolzka** [comment]
> Cherry-Picking numpy 2 support wouldn't be a minor upgrade according to semver in my opinion any more.

Agreed. I think that touches too many things to be an ONNX patch fix.

> I tried to to limit numpy to <2 (see here: https://github.com/onnx/onnx/pull/6241),
but then Issues with pillow start to appear... I stopped there because i didn't know what ci changes made it work for python 3.12 
...
What pillow version does 1.16.1 use? need?

* Short answer: I'm not sure. I'm guessing 10.3 was used based on the release dates between ONNX and pillow. 
* Long answer: See [comment](https://github.com/onnx/onnx/pull/6241#issuecomment-2243197525) in  (#6241)

**Comment by cjvolzka** [comment]
It look's like we have some prototype PRs that pull the fixes into 1.16 passing CI's. 

@gramalingam can we add an agenda item for tomorrow's meeting to decide on if we want to cut a 1.16.2 or not?

**Comment by gramalingam** [comment]
> It look's like we have some prototype PRs that pull the fixes into 1.16 passing CI's.
> 
> @gramalingam can we add an agenda item for tomorrow's meeting to decide on if we want to cut a 1.16.2 or not?

Sure. The only items for discussion tomorrow are release related (1.17 included).

**Comment by gramalingam** [comment]
@liqunfu @xadupre @justinchuby FYI

**Comment by gramalingam** [comment]
Another PR of interest for a 1.16.2 release is https://github.com/onnx/onnx/pull/6195 which fixes a few crashes in shape-inference. And the open PR https://github.com/onnx/onnx/pull/6195

**Comment by andife** [comment]
@gramalingam which open pr do you mean?

**Comment by gramalingam** [comment]
This: https://github.com/onnx/onnx/pull/6217 ... sorry about that, the copy didn't work before I did a paste

**Comment by gramalingam** [comment]
Can we not change the "Verify ONNX with the latest numpy" CI (for this release) to "Verify ONNX with latest numpy < 2.0" ? Not sure about the "latest protobuf" issue though.

**Comment by cjvolzka** [comment]
> Another PR of interest for a 1.16.2 release is #6195 which fixes a few crashes in shape-inference. And the open PR #6217

@gramalingam, 
* #6195 won't cherry-pick into 1.16 cleanly. 
    * At a glance it looks like #6195 would need #6099 which adds support for a new datatype (ie beyond scope for a fix update like 1.16.2).
    * If it's critical, we could have someone try and manually backport the #6195 fixes into the `rel-1.16.2` branch (once I create it). My initial thought is to have it wait for 1.17 as it's not too much further away.
* #6217 cherry-picked cleanly.

**Comment by cjvolzka** [comment]
Closing question as we decided to proceed with a 1.16.2 release.
