### ISSUE TITLE
Error exporting models in caffe2 

### ISSUE THREAD

**Issue by amandeepsaini** [onnx/onnx#624]
I followed the tutorial for exporting a caffe2 model (squeezenet) to ONNX, but got the error below:

> Traceback (most recent call last):
  File "caffe2toOnnx.py", line 24, in <module>
    value_info,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 589, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 469, in caffe2_net_to_onnx_graph
    op, shapes=shapes))
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 384, in caffe2_op_to_onnx_node
    nodes = translator(op_def, shapes)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 221, in _create_conv_pool_op
    assert not node.op_type.startswith("Global")
AssertionError

In addition, if I try to export googlenet instead, I get the following error:

> Traceback (most recent call last):
  File "caffe2toOnnx.py", line 24, in <module>
    value_info,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 591, in caffe2_net_to_onnx_model
    producer_name='onnx-caffe2',  # producer name
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 66, in make_model
    setattr(model, k, v)
AttributeError: Assignment not allowed (no field "opset_imports" in protocol message object).

Any thoughts on what the problem may be?

**Comment by houseroad** [comment]
I just fixed the bug what caused your first failure here: https://github.com/caffe2/caffe2/pull/2292

Please upgrade your ONNX and Caffe2 package (I would suggest you install them from source )

**Comment by amandeepsaini** [comment]
Thanks! So installing ONNX and Caffe2 from the latest source fixed the issues with the googlenet export, but now squeezenet has a new problem:

> WARNING:caffe2.python.onnx.frontend:Converting legacy padding to explicit padding.
> Traceback (most recent call last):
>   File "caffe2toOnnx.py", line 24, in <module>
>     value_info,
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 626, in caffe2_net_to_onnx_model
>     model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 524, in caffe2_net_to_onnx_graph
>     checker.check_graph(graph_def)
>   File "/home/artur/Desktop/onnxInstallSource/onnx/onnx/checker.py", line 46, in checker
>     proto.SerializeToString(), ctx)
> onnx.onnx_cpp2py_export.checker.ValidationError: Field 'name' of graph is required to be non-empty.

**Comment by Nagamani732** [comment]
I built caffe2 and onnx  from source and tried to export squeezenet model but ended up the same error:
> onnx.onnx_cpp2py_export.checker.ValidationError: Field 'name' of graph is required to be non-empty.

I couldn't find any solution to fix this. By any chance you got this fixed ?
Thanks in advance !!
