### ISSUE TITLE
opset_import is not available for testing node

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#625]
As https://github.com/onnx/onnx/pull/608 was merged, some test case should be fixed also.
- PixelShuffle (OnnxBackendPyTorchConvertedModelTest)
- inception_v1 (OnnxBackendRealModelTest)
- shufflenet (OnnxBackendRealModelTest)

**Comment by houseroad** [comment]
We have the opset_import to specify the opset version, so if backend supports opset correctly, it should also be able to run these models.

**Comment by fumihwh** [comment]
Thanks. Let me try.

**Comment by fumihwh** [comment]
@houseroad 
I've checked. So if I didn't misunderstand, backend should prepare servals opset's handlers to deal with different versions of op, right?

**Comment by houseroad** [comment]
Yes, correct. When some breaking changes are introduce into ONNX, the opset version should also increase. Before you run the ONNX model, you should check the opset version to make sure your backend is able to handle it. Right now, the spec of the most ops are pretty stable already, usually one opset version change should only affect one op spec.

**Comment by fumihwh** [comment]
@houseroad 
I didn't find `opset_import` in `NodeProto`, only in `ModelProto`.
So in node level tests, how to figure out which version should backend use?
Also I can't pass context to `onnx.checker.check_node` when inheriting `Backend` class and call `run_node` method.
https://github.com/onnx/onnx/blob/master/onnx/backend/base.py

**Comment by houseroad** [comment]
@fumihwh you are right, only `ModelProto` contains `opset_import`. The `context` is created by parsing meta-data in `ModelProto`. Right now, all the node test's `opset_import` should use the newest `opset_import`. We plan to turn all the node tests into simple model tests. After that they will also contain such meta-data needed by the backend.

**Comment by fumihwh** [comment]
#651
