### ISSUE TITLE
Documentation for RNN, LSTM, GRU shall specify output sequence order when direction is set to reverse

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#626]

**Comment by houseroad** [comment]
@liqunfu do you mind creating a PR to fix the issue?

**Comment by dzhulgakov** [comment]
also cc @anderspapitto to include backend tests for it (it's already covered by pytorch integration tests for some cases)

**Comment by askhade** [comment]
@liqunfu : Can you submit a PR for this?
