### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator renorm

### ISSUE THREAD

**Issue by fangmingbnu** [onnx/onnx#627]
I try to transfer the sphere face model (https://github.com/clcarwin/sphereface_pytorch) from pytorch to caffe2. But the code remind me such error. 

RuntimeError: ONNX export failed: Couldn't export operator renorm

Could you please help me about this? Thank you!

**Comment by houseroad** [comment]
I think we don't have p-norm op in ONNX right now. Two things you need to do to fix the problem:
1) Propose a p-norm op in ONNX
2) After it gets into ONNX, add a symbolic function for renorm to export.
