### ISSUE TITLE
Precision Loss During Weight Transfer from ONNX to MLPack Model

### ISSUE THREAD

**Issue by kumarutkarsh1248** [onnx/onnx#6278]
I am currently working on transferring weights from an ONNX model to an MLPack model (MLPack is a machine learning library in C++). While the weight transfer process completes correctly and the output appears to be accurate, I am experiencing precision issues in the initial layer. Specifically, there are inaccuracies after the 4th decimal place in the initial layer's weights, which propagate and amplify through subsequent layers, leading to larger errors after several passes.

can i get some suggestion on how can i eliminate this error??

**Comment by andife** [comment]
Unfortunately I can't answer the question, 

I'm just wondering if it wouldn't be interesting to document this as an example so that others could also benefit from it.

**Comment by justinchuby** [comment]
> there are inaccuracies after the 4th decimal place in the initial layer's weights

do you mean the layer output (instead of weights)? Depending on the data type used in your model, some degree of precision loss is expected as the actual computation is implemented differently by different frameworks. So MLPack in this case needs to provide precision guarantees.

**Comment by kumarutkarsh1248** [comment]
Actually, there was a mistake on our side. Now we have resolved the issue and everything is working fine.

I want to thank the ONNX community for being so active and helpful. It is really impressive that ONNX models are working so well in such different frameworks like MLPack
