### ISSUE TITLE
error when importing onnx_cpp2py_export

### ISSUE THREAD

**Issue by Dodonicc** [onnx/onnx#6279]
# Bug Report

### Is the issue related to model conversion?
I dont know. I have no idea what i am doing

### Describe the bug
i am following this tutorial:
 https://www.youtube.com/watch?v=_6yP3Gv04-w 
 
 and when doing the step at 19:40 i recieve the following error:

Traceback (most recent call last):
  File "C:\Users\Domin\Desktop\convert_stable_diffusion_checkpoint_to_onnx.py", line 20, in <module>
    import onnx
  File "C:\Users\Domin\miniconda3\envs\sd39new\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

### Reproduction instructions
I have no idea what i am doing so i dont know how to reproduce it

...
```
- Attach the ONNX model to the issue (where applicable)-->

### Expected behavior
Expected it to just install

### Notes
Sorry but i am just following this tutorial so i have no idea about how to properly do a bug report

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/issues/6267

**Comment by justinchuby** [comment]
Closed as duplicate
