### ISSUE TITLE
Shape inference segfaults when adding tensors of shapes `(0,)` and `(1,)`

### ISSUE THREAD

**Issue by MatejUrbanQC** [onnx/onnx#6294]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
The example graph consists of a single add node with two `int64` inputs with initializers. One is initialized to `[]` and the other to `[0]`.

According to broadcasting rules these should broadcast:

> In ONNX, a set of tensors are multidirectional broadcastable to the same shape if one of the following is true:
> * The tensors all have exactly the same shape.
> * **The tensors all have the same number of dimensions and the length of each dimensions is either a common length or 1.**
> * The tensors that have too few dimensions can have their shapes prepended with a dimension of length 1 to satisfy property 2.

A = [], shape(A) = (0,)
B = [0], shape(B) = (1,)
shape(result) = (0,)

Running shape inference on this graph results in segmentation fault.

The error only occurs with integer dtypes and `data_prop=True`

### System information
OS Platform and Distribution (e.g. Linux Ubuntu 20.04): macOS 13.6.7
ONNX version (e.g. 1.13): 1.16.1
Python version: 3.12.4

### Reproduction instructions
```Python
import onnx
model = onnx.load('model.onnx')
onnx.shape_inference.infer_shapes(model, data_prop=True)
```
[model.onnx.zip](https://github.com/user-attachments/files/16601828/model.onnx.zip)

Alternatively using spox
```Python
import spox.opset.ai.onnx.v21 as op
import numpy as np

a = op.const([], dtype=np.int64)
b = op.const([0], dtype=np.int64)
result = op.add(a, b) # segfault
```

**Comment by gramalingam** [comment]
This is an interesting question. I am guessing that the original description of broadcasting did not anticipate the case of empty-tensors. We can handle them (I am assuming that the output would end up being an empty tensor, with a shape determined as per the broadcasting logic). But the same issue may show up, then, in ONNX backends ... I wonder if they do handle them correctly. Do numpy/pytorch/tensorflow support this case?
