### ISSUE TITLE
Unrecognized attribute: exhaustive_search

### ISSUE THREAD

**Issue by amandeepsaini** [onnx/onnx#630]
When I try to export the LeNet model from the caffe2 [Python MNIST Tutoria](https://github.com/caffe2/caffe2/blob/master/caffe2/python/tutorials/MNIST.ipynb)l, I get the following error:

> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0320 15:12:48.514922 31221 operator.cc:178] Engine CUDNN is not available for operator Conv.
> I0320 15:12:48.514981 31221 operator.cc:178] Engine CUDNN is not available for operator Conv.
> Traceback (most recent call last):
>   File "caffe2toOnnx.py", line 24, in <module>
>     value_info,
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 626, in caffe2_net_to_onnx_model
>     model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/frontend.py", line 524, in caffe2_net_to_onnx_graph
>     checker.check_graph(graph_def)
>   File "/home/artur/Desktop/onnxInstallSource/onnx/onnx/checker.py", line 46, in checker
>     proto.SerializeToString(), ctx)
> onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: exhaustive_search
> 
> ==> Context: Bad node spec: input: "data_0" input: "conv1_w_0" input: "conv1_b_0" output: "conv1_1" name: "" op_type: "Conv" attribute { name: "exhaustive_search" i: 0 type: INT } attribute { name: "kernel_shape" ints: 5 ints: 5 type: INTS }

As a reference, here is the code I added to the tutorial code to export the model:
```

def save_net(INIT_NET, PREDICT_NET, model) :
    """Save the net to the locations specified by INIT_NET and PREDICT_NET """
    with open(PREDICT_NET, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    init_net = caffe2_pb2.NetDef()
    for param in model.params:
        blob = workspace.FetchBlob(param)
        shape = blob.shape
        op = core.CreateOperator("GivenTensorFill", [], [param],arg=[ utils.MakeArgument("shape", shape),utils.MakeArgument("values", blob)])
        init_net.op.extend([op])
    init_net.op.extend([core.CreateOperator("ConstantFill", [], ["data"], shape=(1,30,30))])
    with open(INIT_NET, 'wb') as f:
        f.write(init_net.SerializeToString())

def saveModel(deploy_model, modelSaveDir):
    """Save Model"""    
    with core.DeviceScope(core.DeviceOption(caffe2_pb2.CPU, 0)):

        workspace.RunNetOnce(deploy_model.param_init_net)
        workspace.CreateNet(deploy_model.net, overwrite=True)
        INIT_NET = modelSaveDir + '/init_net.pb'
        PREDICT_NET = modelSaveDir + '/predict_net.pb'
        save_net(INIT_NET, PREDICT_NET, deploy_model)

saveModel(deploy_model, 'path/to/save/dir')

```

Other networks that I've trained from scratch also result in the same error. Any ideas on how I can resolve this issue?

**Comment by houseroad** [comment]
This seems a bug in Caffe2 onnx frontend (exporter). When you convert the model from Caffe2 to ONNX, some caffe2 specific attributes are also carried to ONNX model.

**Comment by suryaprakaz** [comment]
Facing the exact error. Were you able to find a solution?

**Comment by suryaprakaz** [comment]
Solved it by adding exhaustive_search to _blacklist_caffe2_args in frontend.py

`
    # caffe2 arguments that are completely removed in onnx
    _blacklist_caffe2_args = {
        'order': {b'NCHW'},
        'cudnn_exhaustive_search': {0, 1},
        'exhaustive_search': {0, 1},
        'use_cudnn': {0, 1},
    }
`

**Comment by paduraru2009** [comment]
Hello, I'm having the same issue with Caffe2 and ONNX latest, both built from sources.

I can't see where _blacklist_caffe2_args are used...
I call the export func like below:
```

	initNet, predictNet = load_net(INIT_NET, PREDICT_NET, False, device_opts)
	data_type = onnx.TensorProto.FLOAT
	data_shape = (1, 1, 28, 28)
	value_info = { 'data' : (data_type, data_shape)}
	onnx_model = Caffe2Frontend.caffe2_net_to_onnx_model(predictNet, initNet, value_info)
```

**Comment by parth1595** [comment]
Hi @suryaprakaz @houseroad 

I still see this issue while converting the mnist model from caffe2 to onnx. Also I have added the exhaustive_search attribute in _blacklist_caffe2_args but still found the same error as mentioned above in comment.

**Comment by houseroad** [comment]
I guess your packages may be too old. Can you try the master branch of the repository of caffe2 https://github.com/pytorch/pytorch/?
