### ISSUE TITLE
test failed with No module named 'onnx.onnx_pb'

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#631]
On a windows 10 anaconda python 3.6 environment, I followed the installation instruction:
git clone --recursive https://github.com/onnx/onnx.git
conda install -c conda-forge protobuf numpy
(in cntk)
pip install onnx
(in cntk/cntk in order to avoid ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export')
python -c "import onnx"
pip install pytest-cov nbval
(no error from above steps.)
pytest
(I am getting following type of errors when running pytest)
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: D:\onnx, inifile: setup.cfg
plugins: nbval-0.9.0, cov-2.5.1
collected 9 items / 10 errors
----------- coverage: platform win32, python 3.6.1-final-0 -----------
Name Stmts Miss Cover Missing
init.py 22 17 23% 7-49
=================================== ERRORS ====================================
__________________ ERROR collecting onnx/backend/test_rnn.py __________________
ImportError while importing test module 'D:\onnx\onnx\backend\test_rnn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
init.py:6: in 
from .onnx_pb import * # noqa
E ModuleNotFoundError: No module named 'onnx.onnx_pb'
__________________ ERROR collecting onnx/test/basic_test.py ___________________

**Comment by liqunfu** [comment]
Does ONNX installation instruction miss this step?
pip install -e .

**Comment by dzhulgakov** [comment]
You're probably better off using the sources from github (which you do) - in which case you indeed need to do `pip install -e .` instead of `pip install onnx`. Which instructions are you referring to?

**Comment by liqunfu** [comment]
I did use the source. However the instruction (for installing from source on ONNX GitHub home page) does not say "pip install -e .". It instead has "pip install onnx" which will fail (at least on windows) as I has showed.

**Comment by bddppq** [comment]
@liqunfu In non-develop installation (i.e. without `-e`), import onnx from the top level directory in the github source checkout doesn't work, you will need to change your current path to somewhere else as mentioned in the Installation section in our README:
>Note that this command does not work from a source checkout directory

If you wanna do development (and thus will need to invoke tests in the source directory), please follow the development installation instructions here: https://github.com/onnx/onnx/blob/master/docs/CONTRIBUTING.md.

btw. I saw you are helping adding backend test cases, thanks for your contribution :-)

**Comment by liqunfu** [comment]
Thanks @bddppq.  I am following CONTRIBUTING.md now.

BTW, glad to work with ONNX.
