### ISSUE TITLE
Want to substitute Expand operator with some other operator in ONNX due to compatibility issues with hardware

### ISSUE THREAD

**Issue by AkshatDogra** [onnx/onnx#6311]
I have an expand operator in the middle of a model that takes 2 inputs with the following shapes:

Output from sigmoid: 1,256,1,1 (tensor to be expanded)

Shape operator: 1,256,80,80 (output shape expected)

I can't use Expand, Tile, Constant and Slice operator due to some external issues. I need to substitute this expand operator to some other operator(s) to get the equivalent functionality.

I tried to substitute them with Reshape + Concat as these are well supported for my hardware but I can't exactly figure out how I can modify the model structure using Onnx.helper.

I wanted to reshape it first to 1,256 and then concat along last dimension 80 times to get 1,256,80 and then again in second last dimension for 1,256,80,80

But I don't understand how to modify the node. If the node is like:
```
Input: "701"

input: "900"

output: "703"

axis: -1

name: "custom_added_Concat1"

op_type: "Concat"
```
I tried changing input 900 to ["701"] * 80 but it didn't work and as I can't create a constant node, I don't want to add 80 concat nodes for a single dimension.
I am very new to Onnx and protobuf and I tried all this from the documentation available but I couldn't find any reference to this.

**Comment by justinchuby** [comment]
You may use the rewriter from onnxscript for this purpose: https://onnxscript.ai/tutorial/rewriter/index.html
