### ISSUE TITLE
RuntimeError: ONNX export failed: Could not export a broadcasted operation; ONNX likely does not support this form of broadcasting.

### ISSUE THREAD

**Issue by happywu** [onnx/onnx#636]
Hi, 
I'm trying to convert a pytorch model to onnx, however, I got this:
### RuntimeError: ONNX export failed: Could not export a broadcasted operation; ONNX likely does not support this form of broadcasting.

Is this indicating I have to implement a broadcasted operator myself?
Thanks.

**Comment by ezyang** [comment]
Some forms of broadcasting are not officially supported by the ONNX spec, and so there's no obvious translation (ONNX doesn't have an Expand operator yet) and so we fail the export.

If you post your model we might be able to say more.

**Comment by happywu** [comment]
Hi, 
the pytorch model structure I am trying to convert is from https://github.com/NVIDIA/flownet2-pytorch/blob/master/networks/FlowNetS.py.

**Comment by springishere** [comment]
onnx has added expand operator (https://github.com/onnx/onnx/commit/2a3a226a96b3dc9e50e739490dd38eaae4f2d8f3).
I wonder if the exporter can now add this support?

**Comment by askhade** [comment]
Closing this issue. If this is still a problem please reopen it.
