### ISSUE TITLE
graph.input disappeared in extract_model

### ISSUE THREAD

**Issue by tonypottera24** [onnx/onnx#6368]
# Bug Report

### Describe the bug

I'm planning to split a UNet model.
I use  `optimum-cli export onnx -m "CompVis/stable-diffusion-v1-4" models`
to get the onnx of the UNet2DConditionModel (in `models/unet/model.onnx` after the above command is executed).
Assume the unet model is `y = M(x)`
Now I want to split it into two models M1 and M2 s.t. `M2(M1(x)) = y`.
I'm facing problems in extracting M1.
The `extract_model` function keeps complaining that it cannot identify the input from the graph.

### System information

- OS Platform and Distribution Linux Ubuntu 24.04:
- ONNX version: 1.16.2
- Python version: 3.12.3

### Reproduction instructions
- Describe the code to reproduce the behavior.
```python
import onnx
model_path = "unet/model.onnx"
model = onnx.load(model_path)
utils.extract_model(
    input_path=model_path,
    output_path=new_model_1_path,
    input_names=[node.name for node in model.graph.input],
    output_names=outputs_M1,
)
```

Error messages:

```
Traceback (most recent call last):
  File ".../utils/split_model.py", line 86, in split_model_and_save
    utils.extract_model(
  File ".../venv/lib/python3.12/site-packages/onnx/utils.py", line 219, in extract_model
    extracted = e.extract_model(input_names, output_names)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/onnx/utils.py", line 173, in extract_model
    inputs = self._collect_new_inputs(input_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/onnx/utils.py", line 52, in _collect_new_inputs
    return self._collect_new_io_core(self.graph.input, names)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../venv/lib/python3.12/site-packages/onnx/utils.py", line 45, in _collect_new_io_core
    new_io_tensors.append(self.vimap[name])
                          ~~~~~~~~~~^^^^^^
KeyError: 'sample'
```

According to my inspection, this error is caused by the loss of `graph.input` after line `self.model = onnx.shape_inference.infer_shapes(model)` at
https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L20
The `graph.input` becomes an empty list after the `infer_shapes`.

I'm new to onnx and please let me know if you need any other information. Thanks.

**Comment by xadupre** [comment]
I assume you checked that every output in outputs_M1 are part of the graph. Is it possible to check that shape_inference returns types and shapes for the desired outputs?

**Comment by tonypottera24** [comment]
@xadupre Thank you for helping me.
The issue persists even if the input and the output are the same as the original model.

```python
#!/usr/bin/env python3

import onnx

model_path = "models/unet/model.onnx"
new_model_path = "models/unet/model_new.onnx"

model = onnx.load(model_path)

onnx.utils.extract_model(
    input_path=model_path,
    output_path=new_model_path,
    input_names=[node.name for node in model.graph.input],
    output_names=[node.name for node in model.graph.output],
)

```

**Comment by tonypottera24** [comment]
I tried to print the input and output of the graph before and after
https://github.com/onnx/onnx/blob/fe2433d3dd677ed5c582e194a49a632e707d0543/onnx/utils.py#L20

```python
print("model.graph.input", model.graph.input)
print("model.graph.output", model.graph.output)
self.model = onnx.shape_inference.infer_shapes(model)
print("self.model.graph.input", self.model.graph.input)
print("self.model.graph.output", self.model.graph.output)
```

It gives the following output.
```
model.graph.input [name: "sample"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "batch_size"
      }
      dim {
        dim_value: 4
      }
      dim {
        dim_param: "height"
      }
      dim {
        dim_param: "width"
      }
    }
  }
}
, name: "timestep"
type {
  tensor_type {
    elem_type: 7
    shape {
      dim {
        dim_param: "steps"
      }
    }
  }
}
, name: "encoder_hidden_states"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "batch_size"
      }
      dim {
        dim_param: "sequence_length"
      }
      dim {
        dim_value: 768
      }
    }
  }
}
]
model.graph.output [name: "out_sample"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "batch_size"
      }
      dim {
        dim_value: 4
      }
      dim {
        dim_param: "height"
      }
      dim {
        dim_param: "width"
      }
    }
  }
}
]
self.model.graph.input []
self.model.graph.output []
```

**Comment by tonypottera24** [comment]
The core issue is the parser does not support models larger than 2GB. I solve the problem by lowering the precision to fp16.
