### ISSUE TITLE
CI not compatible with ubuntu-24.04; Change the runner from ubuntu-latest to ubuntu-22.04?

### ISSUE THREAD

**Issue by andife** [onnx/onnx#6374]
# Ask a Question

While testing python 3.13 I realized that our current pipeline does not work for ubuntu-24.04.

Currently we are using ubuntu-latest, if 24.04 will become "latest"  our build will fail first. 

A quick search didn't turn up a roadmap

Example run could be found here
https://github.com/onnx/onnx/actions/runs/10902364296/job/30254115460?pr=6373

Should we change the runner from ubuntu-latest to ubuntu-22.04?

**Comment by justinchuby** [comment]
Maybe just bump protobuf version ?

**Comment by justinchuby** [comment]
This just looks like a compiler version update. I think we should maintain the ability to compile with the latest os

**Comment by andife** [comment]
We definitely need to make sure that it also works with the new version. My approach is that I don't like to have a broken build due to an external change, that's why I prefer commit-hashes github actions.... For me, this goes in a similar direction in terms of transparency and traceability.

**Comment by justinchuby** [comment]
SGTM!
