### ISSUE TITLE
[Feature request] Allow specifying external tensor data as a buffer when creating a session

### ISSUE THREAD

**Issue by cyanic-selkie** [onnx/onnx#6386]
### System information

1.16.2

### What is the problem that this feature solves?

I have several versions of the external tensor data (e.g., LoRA) from which I want to create different sessions using the same base model. The way it is implemented right now, I would have to manually switch out the files on the disk which is somewhat cumbersome, especially since my model and the weights are all embedded in a binary (for edge inference).

I would like to be able to specify the external data from a buffer, just like I am able to specify the model from a buffer.

### Alternatives considered

The first alternative is merging the model beforehand (which, in the LoRA case would be extremely inefficient).

The second alternative is writing the weights out to the disk and swapping the external tensor data when needed. 

### Describe the feature

It makes the set-up simpler for the LoRA on edge inference that I described.

### Will this influence the current api (Y/N)?

Yes, by adding a new option when initializing the session for specifying the external data as buffers.

### Feature Area

Model usage.

### Are you willing to contribute it (Y/N)

Yes

**Comment by justinchuby** [comment]
This would be a runtime feature and should be already supported by ONNX Runtime and/or ONNX Runtime gen-ai. Please open issues in the corresponding repositories if needed. Thanks.
