### ISSUE TITLE
Request for ONNX Library to Support SHARED Mode Compilation

### ISSUE THREAD

**Issue by linshokaku** [onnx/onnx#6394]
https://github.com/onnx/onnx/blob/d14634e0e59c0799228e2eb1d9665a1a03a2a87a/CMakeLists.txt#L524-L530

I am working on a project implemented in C++ that involves adding a new schema to ONNX. To achieve this, I have cloned ONNX as a submodule and linked the ONNX library using CMake. We have also built `onnx_cpp2py_export.so` to use the new schema via the Python interface.

However, when trying to retrieve the list of schemas through `onnx_cpp2py_export.defs.get_all_schemas()`, the newly added schema does not appear as expected. The issue seems to stem from the fact that the ONNX library is a static library. Consequently, both `onnx_cpp2py_export` and the library that includes our newly added schema are utilizing separate instances of the ONNX library, leading to independent creation of the internal singleton variable (`OpSchemaRegistry`).

Is there a possibility to add functionality that allows the ONNX library to be built in `SHARED` mode to enable shared usage? Your consideration would be greatly appreciated.

**Comment by xadupre** [comment]
Feel free to propose a change through a PR.

**Comment by linshokaku** [comment]
Thank you. I'm about to start working on the PR, but I have one thing to confirm.
For the build in SHARED, should I add it as a new mode that can be selected with a flag, rather than replacing the current build in static mode?

**Comment by xadupre** [comment]
Keep the current behaviour as default, add a flag to trigger the new behaviour. That would be better to avoid breaking packages taking a dependency on onnx.

**Comment by justinchuby** [comment]
For future reference: set cmake -DBUILD_SHARED_LIBS=ON to force shared libraries
