### ISSUE TITLE
Changing conv input tensors from 'Constant' to 'Initializer' and populating the graph initializer

### ISSUE THREAD

**Issue by ecenurustun** [onnx/onnx#6404]
I have a previously exported model (`<path_to_file>/model.onnx`) and after loading it I realized that its graph initializer list (`model.graph.initializer`) is empty because weights of Conv layers are somehow saved as "Constant" instead of "Initializer". Please see the Netron screenshot below for one such tensor. So my question is, how can I add these tensors to graph initializer? I can access their names through node.input[1] but how about their values? Will it require onnxruntime? Thank you.

![weight](https://github.com/user-attachments/assets/146c7cf6-54fc-4a1f-abd2-6bea5c30fdcd)

**Comment by justinchuby** [comment]
You may use the ONNX IR in onnxscript to do this.

1. First find the constant node you want to replace
2. Then create the values to represent the initializers
3. Finally replace the values

```python
"""Replace constants with initializers."""

from onnxscript import ir
from onnxscript.ir import convenience as ir_convenience

model = ir.load("<path_to_file>/model.onnx")


def is_conv_weight(node: ir.NodeProtocol) -> bool:
    uses = {(node.name, idx) for node, idx in node.outputs[0].uses()}
    return ("Conv", 1) in uses


for node in model.graph:
    if node.name == "Constant" and is_conv_weight(node):
        # Obtain the constant tensor from the Constant node
        value = node.outputs[0]
        tensor: ir.TensorProtocol = node.attributes["value"].value
        # Create an initializer value
        initializer_name = value.name
        assert initializer_name
        initializer = ir.Value(name=initializer_name, const_value=tensor)
        model.graph.initializers[initializer_name] = initializer
        # Replace the Constant node with an initializer
        ir_convenience.replace_all_uses_with(value, initializer)
        # Remove the constant node from the graph
        model.graph.remove(node, safe=True)

ir.save(model, "<path_to_file>/model_updated.onnx")
```

**Comment by ecenurustun** [comment]
Thanks @justinchuby
