### ISSUE TITLE
ONNX Windows build relies on MS Store python, fails with official python launcher

### ISSUE THREAD

**Issue by petewarden** [onnx/onnx#6406]
# Bug Report

### Description

I'm using a Windows Arm-based PC, and the protobuf compilation stage of the pip installation fails with a fatal error. The error indicates that the mypy plugin is failing because the `python` command isn't found. I believe this is because I'm using the official download from Python dot org that only installs the `py` executable, which is a launcher for Python. This is listed as the recommended option at [docs.python.org/3/using/windows.html](https://docs.python.org/3/using/windows.html), with the Microsoft Store version of `python` listed as an alternative.

Unfortunately the Store version of Python is still x86-based, so I can't use it on a Windows/Arm PC (technically it can run under emulation but having both installed causes other problems). This also seems like a common setup in the Windows world, regardless of architecture, so it would be nice to support it.

### System information

- Windows 11, ARM
- ONNX version 1.18
- Python version: 3.11 (Arm)

### Reproduction instructions

```bash
git clone https://github.com/onnx/onnx
cd onnx
py setup.py install
```

This also currently happens with plain `pip install onnx`.

### Expected behavior

I expect the wheel to be built and installed.

### Actual behavior

The build fails with the following error messages (trimmed to the most relevant):

```bash
  Building Custom Rule C:/Users/pete/onnx/CMakeLists.txt
  Running C++ protocol buffer compiler on C:/Users/pete/onnx/.setuptools-cmake-build/onnx/onn
  x-ml.proto
  Python was not found; run without arguments to install from the Microsoft Store, or disable
   this shortcut from Settings > Manage App Execution Aliases.
  --mypy_out: protoc-gen-mypy: Plugin failed with status code 9009.
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.C 
ppCommon.targets(254,5): error MSB8066: Custom build for 'C:\Users\pete\onnx\.setuptools-cmak 
e-build\CMakeFiles\1cc123d7a88b38a07b5d702bea4bbab7\onnx-ml.proto.rule;C:\Users\pete\onnx\.se 
tuptools-cmake-build\CMakeFiles\1cc123d7a88b38a07b5d702bea4bbab7\onnx-ml.pb.cc.rule;C:\Users\ 
pete\onnx\.setuptools-cmake-build\CMakeFiles\2613932fd8912cf9addf99599c963206\gen_onnx_proto. 
rule;C:\Users\pete\onnx\CMakeLists.txt' exited with code 1. [C:\Users\pete\onnx\.setuptools-c 
make-build\gen_onnx_proto.vcxproj]
Traceback (most recent call last):
...
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', '.', '--config', 'Release', '--', '/maxcpucount:12']' returned non-zero exit status 1.
```

### Notes

From my debugging, this is caused by the [tools/protoc-gen-mypy.bat](https://github.com/onnx/onnx/blob/main/tools/protoc-gen-mypy.bat) batch file calling the `python` command directly. I will be submitting a patch to try both versions of the command, so that:

```bash
python -u "%~dp0\protoc-gen-mypy.py"
```

becomes

```bash
python -u "%~dp0\protoc-gen-mypy.py" || py -u "%~dp0\protoc-gen-mypy.py"
```

I will submit this as a PR linking back to this issue shortly.

**Comment by justinchuby** [comment]
I think the solution should be https://github.com/onnx/onnx/pull/6096. Could you help push that forward?

**Comment by petewarden** [comment]
Unfortunately I'm a first-time contributor to ONNX, and #6096 looks like a fairly complex change, so I can't take that on right now. Feel free to close this if you do see that as the correct solution, at least this leaves a trail of breadcrumbs for anyone else who hits the same error.

**Comment by armwaheed** [comment]
Got this working:

- [Windows embeddable package (ARM64)](https://www.python.org/ftp/python/3.10.1/python-3.10.1-embed-arm64.zip)
  - NOTE: Python 3.10.1 seems to be the ONLY version that supports Windows on Arm 64, so I suspect this was the source of your problem
- [Install get-pip.py](https://pip.pypa.io/en/stable/installation/), if you have issues with pip not working with embeddable Python
- Do the above environment variables step:
  ```
  	set PATH=C:\Users\waheedbrown\Downloads\python-3.10.1-embed-arm64;C:\Users\waheedbrown\Downloads\python-3.10.1-embed-arm64\Scripts;%PATH%
	set PY_LIBS=C:\Users\waheedbrown\Downloads\python-3.10.1-embed-arm64\Lib;C:\Users\waheedbrown\Downloads\python-3.10.1-embed-arm64\Lib\site-packages
	set PY_PIP=C:\Users\waheedbrown\Downloads\python-3.10.1-embed-arm64\Scripts

	mkdir C:\tmp
	set TMP=C:\tmp
	set TEMP=C:\tmp
  ```
- Create a virtualenv environment for doing your build
  - NOTE: I suspect this is another crucial step
- Build following the official instructions for windows:
  ```
  .\build.bat --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync
  ```
  - Optionally add the `--build_wheel` parameter at the end, if you want to more easily manage to build output as a Python wheel; I.E., upload it to Pypi for sharing
    ```
    .\build.bat --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --build_wheel
    ```
