### ISSUE TITLE
How to compare two values in an onnx model?

### ISSUE THREAD

**Issue by jmren168** [onnx/onnx#6409]
Hi,

I would like to compare two values in an onnx model, if the first one is greater than (>=) the second one, then the model outputs 1; otherwise, the model outputs -1. How to implement this logic function via onnx operators?

Many thanks.

**Comment by xadupre** [comment]
This can be done with operator [If](https://onnx.ai/onnx/operators/onnx__If.html). You can find an example here: https://onnx.ai/onnx/intro/python.html#if.
