### ISSUE TITLE
Incorrect averagepool expected output.

### ISSUE THREAD

**Issue by spidyDev** [onnx/onnx#641]
@fumihwh @houseroad 

The expected output for averagepool_2d_precomputed_pads looks incorrect. 
I think it should be : 
```
[[[[  2.51999998,   3.5999999 ,    4.80000019,     4.07999992,  3.24000001],
    [  4.55999994,   6.4000001 ,    8.39999962,    7.03999996,  5.51999998],
    [  7.19999981,    10.               ,   13. ,                 10.80000019,    8.39999962],
    [  6.96000004,   9.60000038,  12.39999962,  10.23999977,  7.92000008],
    [  6.11999989,   8.39999962,  10.80000019,    8.88000011,    6.84000015]]]]
```

but given:
```
[[[[7, 7.5, 8, 8.5, 9],
    [9.5, 10, 10.5, 11, 11.5],
    [12, 12.5, 13, 13.5, 14],
    [14.5, 15, 15.5, 16, 16.5],
    [17, 17.5, 18, 18.5, 19]]]]
```

Am I missing something here ?

**Comment by spidyDev** [comment]
Below is the average pool test replicated in mxnet, gives the same result I mentioned above:
```
import mxnet as mx
x = mx.nd.array(np.arange(1, 26).reshape(1,1,5,5))
output  = mx.ndarray.Pooling(data=x, kernel=(5,5), pad=(2,2), pool_type='avg')
```

**Comment by fumihwh** [comment]
@spidyDev 
```
0 0 0 0 0
0 0 0 0 0
0 0 1 2 3
0 0 6 7 8
0 0 11 12 13
```
↑ first pool window

We can get average is `(1 + 2 + 3 + 6 + 7 + 8 + 11 + 12 + 13) / 9 = 7` for first element.

https://github.com/onnx/onnx/blob/master/docs/Operators.md#AveragePool
`The output of each pooling window is divided by the number of elements exclude pad.`
So we don't divide by 25 here, which can get 2.52 as you did.

**Comment by spidyDev** [comment]
@fumihwh  Thanks for clarification.

**Comment by houseroad** [comment]
@fumihwh Thanks for answering the question. Yeah, most of the existing framework does not count the pad when computing the average.
