### ISSUE TITLE
Converter for different opset version

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#642]
Ideally this can help developers convert the models between different opset version. @ezyang @bddppq

**Comment by ezyang** [comment]
Yep. Forwards + backwards, as far as possible.

**Comment by kit1980** [comment]
What's the status of this idea?
Any suggestion what's currently the easiest way to convert, for example, a model using IR version 3 to a model with IR version 7?

**Comment by houseroad** [comment]
Ongoing PR is here: https://github.com/onnx/onnx/pull/1148

Feedback is welcome
