### ISSUE TITLE
How to test the correctness

### ISSUE THREAD

**Issue by wzhongyuan** [onnx/onnx#643]
Hi,
I am new to onnx, From my understanding, it just defines common format and operators and what these operators mean, but there is no operator implementation, right ? so how should I know the correctness ? For example, if I implement a `Abs` and convert to onnx model, how to test ?

**Comment by fumihwh** [comment]
I think you can use backend of others framework to run.

**Comment by wzhongyuan** [comment]
@fumihwh   Do you mean use backend of other framework to load exported onnx model and run with the sampe input to see if it generates the same output as my framework?

**Comment by fumihwh** [comment]
@wzhongyuan Yes.

**Comment by wzhongyuan** [comment]
@fumihwh  Thanks very much, just one more question,  what does `check_model` generally do ?

**Comment by houseroad** [comment]
@wzhongyuan `check_model` will check your model is compliant with ONNX specification, for example whether the required fields appear, whether the operators in your model follow the ONNX's specification

**Comment by wzhongyuan** [comment]
@houseroad   thanks,
