### ISSUE TITLE
Onix frontend docs and tutorial

### ISSUE THREAD

**Issue by KOLANICH** [onnx/onnx#645]
Hello. Do I understand right that onnx frontend is model -> onnx converter? Could you write a tutorial on writing it? I have looked into projects, there are plenty of files I don't know why do we need them all. So could you create a very minimalistic toy frontend showing all the aspects of using onxx library? I wonder if I can create a tree of nodes in the manner I construct python AST and make the library prepare and serialize it automatically?

**Comment by houseroad** [comment]
Frontend means the onnx exporter, which exports the models from your framework to onnx format.

An ONNX model is in protobuf format, and the schema is defined here: https://github.com/onnx/onnx/blob/master/onnx/onnx.proto

If you want to write a frontend for your framework or just for fun, you probably should check the [helper.py](https://github.com/onnx/onnx/blob/master/onnx/helper.py) first. 

We also have a lot tutorials here: https://github.com/onnx/tutorials.

**Comment by bddppq** [comment]
just to add an example frontend implementation (in caffe2): https://github.com/caffe2/caffe2/blob/master/caffe2/python/onnx/frontend.py

**Comment by KOLANICH** [comment]
Thank you.
