### ISSUE TITLE
compilation error: invalid instruction mnemonic 'vcvtneeph2ps'

### ISSUE THREAD

**Issue by saiden89** [onnx/onnx#6469]
# Bug Report

### Describe the bug
Compiling onnxruntime raises an error, possibly related to the AVX512 instruction set.

### System information
- OS Platform and Distribution: SUSE Linux Enterprise Server 15 SP5
- ONNX version: v17.0
- Python version: 3.12.7
- GCC/Compiler version (if compiling from source): AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-6.0.3 24012 af27734ed982b52a9f1be0f035ac91726fc697e4). 
- CMake version: 3.30.4

### Reproduction instructions
```bash
module purge

module load PrgEnv-amd
module load rocm/6.0.3
module load craype-accel-amd-gfx90a craype-x86-trento

cd /tmp || exit
git clone --single-branch --branch main --recursive https://github.com/Microsoft/onnxruntime onnxruntime
cd onnxruntime || exit

mamba install rust -y
pip install cmake

./build.sh --config Release \
    --build_wheel \
    --update \
    --build \
    --parallel \
    --use_rocm \
    --rocm_home "/opt/rocm-6.0.3" \
    --cmake_extra_defines CMAKE_HIP_ARCHITECTURES=gfx90a \
    --cmake_extra_defines CMAKE_C_COMPILER=amdclang \
    --cmake_extra_defines CMAKE_CXX_COMPILER=amdclang++
```

### Expected behavior
No error should be raised
### Notes
I am using a Cray supercomputer, but compiling with normal AMD Clang without Cray optimizations, instead of their compiler wrapper (which causes even more errors).

### Logs
[log.txt](https://github.com/user-attachments/files/17437774/log.txt)

**Comment by xadupre** [comment]
You should post this issue on onnxruntime repository. This is not related to onnx.

**Comment by saiden89** [comment]
Oh, how did I miss that? Sorry for the mishap
