### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::polar' to ONNX opset version 18 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### ISSUE THREAD

**Issue by chaodreaming** [onnx/onnx#6480]
Does not support freqs_cis=torch. solar (torch. ones. like (freqs), freqs) # complex64

**Comment by xadupre** [comment]
Complex is not well supported right now. onnxruntime does not support complex so the exporter tries to use real instead but it does not cover all the possible scenarios.

**Comment by justinchuby** [comment]
Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!

please open a follow up issue on the PyTorch github repository if needed.
