### ISSUE TITLE
Mistakes in Release

### ISSUE THREAD

**Issue by spgoswami1** [onnx/onnx#6481]
I am using this release: https://github.com/microsoft/onnxruntime/releases/download/v1.19.2/onnxruntime-linux-x64-gpu-1.19.2.tgz

Issue 1:
`onnxruntimeTargets-release.cmake:11`
`IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib64/libonnxruntime.so.1.19.2"`
It tries to find lib64 folder but the release does not have this. Manually creating this folder and copying contents of lib to lib64 worked.

same for 
`onnxruntimeTargets-release.cmake:16`

Issue 2:
`onnxruntimeTargets.cmake:63`
`INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/onnxruntime"`
But the release has all the headers inside /include only, not inside /include/onnxruntime. Again, I had to make onnxruntime folder inside /inlude and copy all the headers inside /include/onnxruntime, then it worked.

Kindly check these issues. Thanks

**Comment by andife** [comment]
Hi, 
the bug report should be opened at the onnxruntime repository: https://github.com/microsoft/onnxruntime

**Comment by spgoswami1** [comment]
Oh sorry, thanks Andreas

I had both of them opened. I'll open it there.
