### ISSUE TITLE
What is `unk__16`

### ISSUE THREAD

**Issue by IonBoleac** [onnx/onnx#6505]
# Ask a Question
Hello everyone. I'd like to know what is `unk__16` when I ask the metadata form the onnx model. Anyone can help me?

```log
name: "output"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__16"
      }
      dim {
        dim_value: 2300
      }
    }
  }
}
```

**Comment by justinchuby** [comment]
unk__16 is a dimension with unknown size. For example if you have a tensor with shape `[1, unk__16, 42]`, it is saying it is a tensor of rank 3, whose second dimension is dynamic.
