### ISSUE TITLE
Some pipelines are blocked because of onnxruntime 1.20 release

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#6522]
We should pin onnxruntime version.

**Comment by andife** [comment]
https://github.com/Microsoft/onnxruntime/releases/tag/v1.20.0

ONNX Runtime packages will stop supporting Python 3.8 and Python 3.9. This decision aligns with NumPy Python version support. To continue using ORT with Python 3.8 and Python 3.9, you can use ORT 1.19.2 and earlier.

We should adapted the pipelines to use older ORT for python 3.8 and python 3.9

**Comment by andife** [comment]
My suggestion would be  to remove python 3.8 support for onnx 1.19?

**Comment by andife** [comment]
https://github.com/onnx/onnx/pull/6524

**Comment by justinchuby** [comment]
> My suggestion would be to remove python 3.8 support for onnx 1.19?

I agree we should do that (for 1.18)
