### ISSUE TITLE
[Feature request] aten::_native_mutli-head_attention

### ISSUE THREAD

**Issue by wcycqjy** [onnx/onnx#6532]
### System information

1.17

### What is the problem that this feature solves?

When trying to export the pytorch model with MHA to onnx format, this problem appears. It seems like the pytorch creates the "aten::_native_multi_head_attention node" which isn't supported by onnx yet, see ref [https://discuss.pytorch.org/t/multiheadattention-export-to-onnx-fails-when-using-torch-no-grad/198843](url). Although in this thread someone proposed a solution but it doesn't work for me.

### Describe the feature

Onnx will support the pytorch MHA implementation in the latest version which is the base of many attention variants.

### Will this influence the current api (Y/N)?

No

### Feature Area

operators

### Are you willing to contribute it (Y/N)

No

**Comment by justinchuby** [comment]
Please open an issue in the PyTorch repository as this is framework specific, thanks. 

Please test with `torch.onnx.export(..., dynamo=True, report=True)` using the latest torch-nightly. Attach the generated report if there is an error. Thanks!
