### ISSUE TITLE
The macOS 12 Actions runner image will begin deprecation on 10/7/24 and will be fully unsupported by 12/3/24 for GitHub and ADO

### ISSUE THREAD

**Issue by andife** [onnx/onnx#6537]
<img width="1352" alt="image" src="https://github.com/user-attachments/assets/940e857f-953e-472d-800d-3cbed4d967de">

https://github.com/actions/runner-images/issues/10721

Does this affect us?

@justinchuby @liqunfu

**Comment by andife** [comment]
<img width="593" alt="image" src="https://github.com/user-attachments/assets/77f15c7e-2967-4c83-bbd9-dd93488ffcb2">

**Comment by andife** [comment]
I think we could drop support for mac-os12 now, as we will not do a release before "December 3rd, 2024"?
@justinchuby @liqunfu

**Comment by justinchuby** [comment]
Agreed
