### ISSUE TITLE
Dynamic dummy input when exporting a PyTorch model?

### ISSUE THREAD

**Issue by HeliWang** [onnx/onnx#654]
When I export a PyTorch model, I need to have a dummy_input like this:
        print("Saving model to ONNX...")
        x = torch.rand(1000, 47, 300) # shape 1000x47x300
        dummy_input = Variable(x, requires_grad=True)
        torch.onnx.export(self.model, dummy_input, export_file, verbose=True)

However, the shape of my input when doing inference using the onnx model could be not the same as 1000x47x300. I want the model to handle dynamic shape, for example, 1000x50x300 or 1000x10x300. Is there an existing way in ONNX letting me to have a dummy_input with dynamic shape? Thanks.

**Comment by houseroad** [comment]
Input and output shape info is required to be static, shall we relax this requirement? @ezyang @Yangqing @dzhulgakov @bddppq @ebarsoum

**Comment by bddppq** [comment]
This is a very good question and it's a topic we have been discussing repeatedly recently. The answer has three parts:
1. whether onnx supports representing models with dynamic shape
2. whether frontends (like pytorch) supports exporting models with dynamic shape
3. whether backends (like caffe2) supports importing models with dynamic shape

For 1, in serialization format's level, onnx supports representing models with dynamic shape. If you look at `TensorShapeProto` which is used to describe the shape of the inputs and outputs, it has `dim_param` to represent symbolic/dynamic shape. **However**, at this point, all the tooling (checker, shape inference, etc) basically don't handle symbolic shape but simply assume them to be static. There are ongoing work to update them, e.g. https://github.com/onnx/onnx/issues/632 is going to address this issue in shape inference. The work should not be too much and we can expect it happening soon.

For 2, depends on the type of frontends:
- For tensorflow->onnx and caffe2->onnx, these frontends are doing static graph to static graph conversion, they normally support dynamic shape out of the box. But I do have seen few cases where due to different semantics of some operators between these frameworks and onnx, even the static conversion needs some shapes information, but these can be solved relatively easy (e.g. by adding support of the onnx semantics in the framework).

- For pytorch->onnx or other similar frontends that use tracing (on limited set of inputs sample inputs), dynamic shape is a natural limitation but not technically impossible. By rewriting few places in the model that operates directly on concrete sizes to a form that can let the tracer be aware of these operations (see here for a pytorch example https://github.com/onnxbot/onnx-fb-universe/blob/b2bfc236bcdca882144bfffa24ac83e0ab0ebf4a/test/test_caffe2.py#L635), exported models will be compatible with dynamic shapes. Recently we have scanned through some real world pytorch models (e.g. https://github.com/pytorch/examples) and found actually all the size operations are pretty simple and thus easily rewritable.

For 3, the technical difficulties are similar to frontends that do static conversions, and thus should be relatively easy to tackle.

So my conclusion is, yes, dynamic shape is definitely something we should and will support in the near future, just it's not ready yet at this point.

**Comment by HeliWang** [comment]
Thanks a lot @bddppq for your detailed answer. Currently I am converting models from PyTorch -> ONNX -> MxNet. For 3 I think @anirudhacharya mentioned in https://github.com/onnx/onnx-mxnet/issues/44 that onnx-mxnet will soon support Gluon.

**Comment by nehz** [comment]
For now, I temporarily modify the onnx graph inputs:

```
model = onnx.load('model.onnx')
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
onnx.save(model, 'dynamic_model.onnx')
```

This seems to work with the tensorflow backend, but I haven't tested it on any others

**Comment by wangyunxiaa** [comment]
@nehz 
I have modified the onnx input with the method you mentioned,but I got an error
`ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.`  
I am tracking the source code,and found that the input of lstm layer is `Tensor("Reshape_1:0", shape=(?, ?, ?), dtype=float32)`
The original input shape is (10,1,1000)  correspond to (num_step, batchsize,dim) I just do the modify as following:`onnx_model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'`
what's wrong with me?

**Comment by leemengtaiwan** [comment]
Do we have better solution for dynamic input (especially dynamic **width** and **height** of images) now?

I encountered the same issue but can't solve it by using @nehz 's approach when I want to export the onnx model to TensorFlow.

The approach shown above can only solve dynamic `batch_size`, but not dynamic size of, say, width and height of a input image because onnx model will need concrete number when computing common image processing operation like convolutions, for example.

```python
onnx_model.graph.input[0].type.tensor_type.shape.dim[2].dim_param = '?'
onnx_model.graph.input[0].type.tensor_type.shape.dim[3].dim_param = '?'
onnx_model.graph.input[0]

# output
name: "input.1"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1  # batch_size
      }
      dim {
        dim_value: 3  # channel
      }
      dim {
        dim_param: "?"  # width
      }
      dim {
        dim_param: "?"  # height
      }
    }
  }
}

tf_rep = prepare(onnx_model)

# output
onnx-tensorflow/onnx_tf/handlers/backend/conv_mixin.py in <listcomp>(.0)
     85           conv_output_shape += [
     86               strides[i] * (x_spatial_shape[i] - 1) + weights_shape[i]
---> 87               for i in list(range(spatial_size))
     88           ]
     89         else:

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by liangt** [comment]
PyTorch 1.2 supports dynamic input now, such as:

> 
  model = models.resnet18()
  dummy_input = torch.zeros(1, 3, 224, 224)
  inputs = ['images']
  outputs = ['scores']
  dynamic_axes = {'images': {0: 'batch'}, 'scores': {0: 'batch'}}
  torch.onnx.export(model, dummy_input, 'test.onnx', input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes)

**Comment by sonu1-p** [comment]
I am trying to export a pytorch model with 3 lstms. I was able to specify the input's seq lens as dynamic using dynamic_axes but the LSTM Op is still using the hard coded seq_lens value from dummy_input.

![image](https://user-images.githubusercontent.com/1289895/63203358-bdbaf980-c043-11e9-9eeb-ab1232f635d9.png)


Is there any good way to work around this?

**Comment by DJinsis** [comment]
> PyTorch 1.2 supports dynamic input now, such as:
> 
> > 
> 
> model = models.resnet18()
> dummy_input = torch.zeros(1, 3, 224, 224)
> inputs = ['images']
> outputs = ['scores']
> dynamic_axes = {'images': {0: 'batch'}, 'scores': {0: 'batch'}}
> torch.onnx.export(model, dummy_input, 'test.onnx', input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes)

but i can't change 'width' and 'height', when i got the onnx which used pytorch1.2. i got the wrong message

![1567080479662](https://user-images.githubusercontent.com/9247758/63939097-ff629000-ca98-11e9-8b17-4b205125fb81.jpg)


> PyTorch 1.2 supports dynamic input now, such as:
> 
> > 
> 
> model = models.resnet18()
> dummy_input = torch.zeros(1, 3, 224, 224)
> inputs = ['images']
> outputs = ['scores']
> dynamic_axes = {'images': {0: 'batch'}, 'scores': {0: 'batch'}}
> torch.onnx.export(model, dummy_input, 'test.onnx', input_names=inputs, output_names=outputs, dynamic_axes=dynamic_axes)

but i can't change 'width' and 'height', when i got the onnx which used pytorch1.2. i got the wrong message
![Uploading 1567080479662.jpg…]()

**Comment by callmeliuchu** [comment]
> @nehz
> I have modified the onnx input with the method you mentioned,but I got an error
> `ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.`
> I am tracking the source code,and found that the input of lstm layer is `Tensor("Reshape_1:0", shape=(?, ?, ?), dtype=float32)`
> The original input shape is (10,1,1000) correspond to (num_step, batchsize,dim) I just do the modify as following:`onnx_model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'`
> what's wrong with me?

hi,did you solve that problem,I also got that proble.@wangyunxiaa

**Comment by lxl910915** [comment]
> For now, I temporarily modify the onnx graph inputs:
> 
> ```
> model = onnx.load('model.onnx')
> model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
> onnx.save(model, 'dynamic_model.onnx')
> ```
> 
> This seems to work with the tensorflow backend, but I haven't tested it on any others

Have you test it ?

**Comment by sizhky** [comment]
Hi all,

I'm also facing a similar problem with variable width and height. I've created code as below

def export_onnx_model(model, input_shape, onnx_path, input_names=None, output_names=None, dynamic_axes=None):
    inputs = torch.ones(*input_shape)
    model(inputs)
    torch.onnx.export(model, inputs, onnx_path, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes)
```python
input_shape = (10, 3, 112, 112)
onnx_path = "test.onnx"
input_names=['input']
output_names=['output']
dynamic_axes= {'input':[0, 2, 3], 'output':[0,2,3]}
export_onnx_model(model, input_shape, onnx_path, input_names, output_names, dynamic_axes)
```

**Comment by lxl910915** [comment]
> > For now, I temporarily modify the onnx graph inputs:
> > ```
> > model = onnx.load('model.onnx')
> > model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
> > onnx.save(model, 'dynamic_model.onnx')
> > ```
> > 
> > 
> > This seems to work with the tensorflow backend, but I haven't tested it on any others
> 
> Only one dim can be dynamic? Have you test dim[1]='?' and dim[2]='?' ? Thank you! @nehz

We have tested dim[1]='?' and dim[2]='?', and we run dynamic_model.onnx using onnxruntime.InferenceSession(). If we set set_providers(['TensorrtExecutionProvider']) for InferenceSession, we get this error:
`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Concat node. Name:'feature_fusion/concat_3' Status Message: /onnxruntime/onnxruntime/core/providers/cpu/tensor/concat.cc:64 onnxruntime::common::Status onnxruntime::ConcatBase::PrepareForCompute(onnxruntime::OpKernelContext*, const std::vector<const onnxruntime::Tensor*>&, onnxruntime::Prepare&) const inputs_n_rank == inputs_0_rank was false. Ranks of input data are different, cannot concatenate them. expected rank: 4 got: 0`

If we set set_providers(['CUDAExecutionProvider']) for InferenceSession, it works well. 

We will perf it more.

**Comment by asmitakhaneja** [comment]
> Hi all,
> 
> I'm also facing a similar problem with variable width and height. I've created code as below
> 
> ```python
> def export_onnx_model(model, input_shape, onnx_path, input_names=None, output_names=None, dynamic_axes=None):
>     inputs = torch.ones(*input_shape)
>     model(inputs)
>     torch.onnx.export(model, inputs, onnx_path, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes)
> 
> input_shape = (10, 3, 112, 112)
> onnx_path = "test.onnx"
> input_names=['input']
> output_names=['output']
> dynamic_axes= {'input':[0, 2, 3], 'output':[0,2,3]}
> export_onnx_model(model, input_shape, onnx_path, input_names, output_names, dynamic_axes)
> ```
> 
> But the model won't accept anything other than an image of size (3, 112, 112). Is the `dynamic_axes` argument supposed to work only for batch size?! Please help

In order to make it dynamic, initialize  the dynamic variables
batch_size= 10
width =112,
height=112
input_shape = (batch_size, 3, width, height)
onnx_path = "test.onnx"
input_names=['input']
output_names=['output']
dynamic_axes= {'input':{0:'batch_size' , 2:'width', 3:'height'}, 'output':{0:'batch_size' , 2:'width', 3:'height'}} #adding names for better debugging
export_onnx_model(model, input_shape, onnx_path, input_names, output_names, dynamic_axes)

**Comment by ak9250** [comment]
I am getting this error The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

**Comment by mchalecki** [comment]
> I am getting this error The ONNX model's constant layer tensor dimensions size must be 1, 2 or 4

Onnx does not support 3 channels. Why do you need 3 channels. Probably you want tensor with batch size 1 and that would be 4 dimension tensor with first dimension equal 1

**Comment by ak9250** [comment]
@mchalecki I have the exported pytorch model of this in onnx https://github.com/minivision-ai/photo2cartoon not sure

**Comment by ak9250** [comment]
@mchalecki so I think you are right, this is my output tensor now, but I still get that error
torch.Size([1, 3, 256, 256])

**Comment by AD-HO** [comment]
I would like to know how to unfreeze the input size of an exported Onnx model?
Example: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

Super-Resolution is an image-to-image translation, i can’t see how i would consume this model without resizing the input to 224 x 224 , and this mean the input quality will decrease
thank you.

**Comment by farleylai** [comment]
Dynamic width/height may not archive the expected performance improvement with some backend such as TensorRT though.

**Comment by kventinel** [comment]
> I am trying to export a pytorch model with 3 lstms. I was able to specify the input's seq lens as dynamic using dynamic_axes but the LSTM Op is still using the hard coded seq_lens value from dummy_input.
> 
> ![image](https://user-images.githubusercontent.com/1289895/63203358-bdbaf980-c043-11e9-9eeb-ab1232f635d9.png)
> 
> Is there any good way to work around this?

@sonu1-p, can you say, please, what a tool is it? This looks very pretty.

**Comment by satrya-spotrai** [comment]
> > Hi all,
> > I'm also facing a similar problem with variable width and height. I've created code as below
> > ```python
> > def export_onnx_model(model, input_shape, onnx_path, input_names=None, output_names=None, dynamic_axes=None):
> >     inputs = torch.ones(*input_shape)
> >     model(inputs)
> >     torch.onnx.export(model, inputs, onnx_path, input_names=input_names, output_names=output_names, dynamic_axes=dynamic_axes)
> > 
> > input_shape = (10, 3, 112, 112)
> > onnx_path = "test.onnx"
> > input_names=['input']
> > output_names=['output']
> > dynamic_axes= {'input':[0, 2, 3], 'output':[0,2,3]}
> > export_onnx_model(model, input_shape, onnx_path, input_names, output_names, dynamic_axes)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But the model won't accept anything other than an image of size (3, 112, 112). Is the `dynamic_axes` argument supposed to work only for batch size?! Please help
> 
> In order to make it dynamic, initialize the dynamic variables
> 
> ```
> batch_size= 10
> width =112,
> height=112
> input_shape = (batch_size, 3, width, height)
> onnx_path = "test.onnx"
> input_names=['input']
> output_names=['output']
> dynamic_axes= {'input':{0:'batch_size' , 2:'width', 3:'height'}, 'output':{0:'batch_size' , 2:'width', 3:'height'}} #adding names for better debugging
> export_onnx_model(model, input_shape, onnx_path, input_names, output_names, dynamic_axes)
> ```

This one didn't work unfortunately

**Comment by awethaileslassie** [comment]
> For now, I temporarily modify the onnx graph inputs:
> 
> ```
> model = onnx.load('model.onnx')
> model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
> onnx.save(model, 'dynamic_model.onnx')
> ```
> 
> This seems to work with the tensorflow backend, but I haven't tested it on any others

But also do not forget to modify the output batch size. To support dynamic batch fully add `model.graph.output[0].type.tensor_type.shape.dim[0].dim_param = '?'`. It should be like this:
```
model = onnx.load('model.onnx')
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
model.graph.output[0].type.tensor_type.shape.dim[0].dim_param = '?'
onnx.save(model, 'dynamic_model.onnx')
```

**Comment by thelou1s** [comment]
> tensor_type

hi, mine print error like this, how to mod python to export dym? thank you

AttributeError: 'DyMN' object has no attribute 'graph'

        ```
# .onnx
        # PyTorch 1.2 supports dynamic input now, such as: https://github.com/onnx/onnx/issues/654
        # dynamic_axes = {'input': {3: 'wav_len'}, 'output': {3: 'wav_len'}}
        model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
        model.graph.output[0].type.tensor_type.shape.dim[0].dim_param = '?'

        onnx_model_uri = model_name + '_eat.onnx'
        output_model = onnx_model_uri
        torch.onnx.export(
            model,
            dummy_input,
            output_model,
            do_constant_folding=True,
            verbose=False,
            opset_version=12,
            input_names=['feats'],
            output_names=['prob'],
            # dynamic_axes=dynamic_axes,
        )
        print(model_name, onnx_model_uri)
```
