### ISSUE TITLE
Travis Throttling

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#658]
Hi, 

We are facing an increasing problem with Travis throttling builds in onnx-tensorflow repo.

Are there any ways to deal with Travis throttling builds? I think Travis may be limiting concurrent jobs in an organization. Can we do something about the automatic bot in Core-ML converter repo? Are there any ways to make these bots commit in bulk?

We have to wait for hours before seeing a CI result. Would be nice if the wait time can be shortened.

cc @fumihwh for more perspective

Best wishes,
Tian Jin.

**Comment by ezyang** [comment]
I recommend switching CI services. Though I have not used it before, many folks I know have happily switched from Travis to CircleCI

On March 23, 2018 11:18:07 PM EDT, Tian Jin <notifications@github.com> wrote:
>Hi, 
>
>We are facing an increasing problem with Travis throttling builds in
>onnx-tensorflow repo.
>
>Are there any ways to deal with Travis throttling builds? I think
>Travis may be limiting concurrent jobs in an organization. Can we do
>something about the automatic bot in Core-ML converter repo? Are there
>any ways to make these bots commit in bulk?
>
>We have to wait for hours before seeing a CI result. Would be nice if
>the wait time can be shortened.
>
>cc @fumihwh for more perspective
>
>Best wishes,
>Tian Jin.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/onnx/onnx/issues/658

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tjingrant** [comment]
@ezyang thanks I'll give that a try, closing for now.
