### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'protobuf.lib'

### ISSUE THREAD

**Issue by logen1004** [onnx/onnx#660]
Hi, I'm trying to install onnx using 
`pip install onnx`
But facing the error:
> LINK : fatal error LNK1181: cannot open input file 'protobuf.lib'

My environment is Python 3.6, protobuf 3.5.1, Windows 10.

**Comment by prasanthpul** [comment]
Before pip install, did you do "conda install -c conda-forge protobuf numpy" ?

**Comment by raymondxyang** [comment]
We just published the wheel for onnx==1.0.1 version.

**Comment by yuslepukhin** [comment]
Please, check the updated build instructions for Windows. That includes recommended protobuf version and also shows how to build protobuf yourself.

**Comment by yuslepukhin** [comment]
Is this still relevant?

**Comment by yuslepukhin** [comment]
I am closing this. Please, follow the most recent build instructions for Windows. Reopen if necessary.
