### ISSUE TITLE
Installing onnxrruntime (GPU) -1.14.1 on Ubuntu 22.04 reports an error

### ISSUE THREAD

**Issue by yuan-kai-design** [onnx/onnx#6602]
# Ask a Question
When I installed ONNXruntime v1.14.1 on Ubuntu, I executed the command "./build. sh -- skipthests -- config Release -- build_sthared_lib -- parallel -- use_cuda -- CUDA_ home/var/local/CUDA-11.1-- CUDNN_home/var/local/CUDA-11.1-- use_tensorrt -- tensort_home/home/ps/rain/YK/task/TensorRT-8.5.3.1" and reported a subprocess CalledProcessError: Command， The currently recommended methods on GitHub, such as exporting CMAKE-ARGS="- DYNNX-USE-PROTOBUF-SHARED_LEBS=ON" and git submodule update -- init -- recursive, still report errors! Looking forward to seeking help!

### Question
<2024-12-30 09:59:00,650 util.run [DEBUG] - Subprocess completed. Return code: 0
2024-12-30 09:59:00,651 build [INFO] - Building targets for Release configuration
2024-12-30 09:59:00,651 util.run [INFO] - Running subprocess in '/home/ps/train/YK/task/onnxruntime'
  /usr/local/bin/cmake --build /home/ps/train/YK/task/onnxruntime/build/Linux/Release --config Release -- -j80
[  1%] Running gen_proto.py on onnx/onnx.in.proto
[  1%] Built target absl_spinlock_wait
[  2%] Built target absl_log_severity
[  2%] Built target onnxruntime_providers_shared
[  2%] Building CUDA object CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/home/ps/train/YK/task/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o
[  2%] Built target absl_exponential_biased
[  2%] Built target absl_int128
[  3%] Built target clog
[  3%] Generating onnxruntime.lds, generated_source.c
[  3%] Built target flatbuffers
[  3%] Built target absl_civil_time
[  3%] Built target custom_op_invalid_library
[  3%] Built target onnxruntime_mocked_allocator
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
[  3%] Built target gtest
gmake[2]: *** [CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/build.make:77：**CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/home/ps/train/YK/task/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o] error 1**
[  3%] Building CUDA object CMakeFiles/custom_op_library.dir/home/ps/train/YK/task/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o
gmake[1]: *** [CMakeFiles/Makefile2:2222：CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/all] error 2
gmake[1]: *** Waiting for unfinished tasks....
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
gmake[2]: *** [CMakeFiles/custom_op_library.dir/build.make:77：**CMakeFiles/custom_op_library.dir/home/ps/train/YK/task/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o] error 1**
**gmake[1]: *** [CMakeFiles/Makefile2:2796：CMakeFiles/custom_op_library.dir/all] error 2**
[  3%] Built target absl_time_zone
[  4%] Built target absl_raw_logging_internal
[  6%] Built target nsync_cpp
[  7%] Built target cpuinfo
[  8%] Built target re2
Generating symbol file for ['cpu', 'cuda', 'tensorrt']
VERSION:1.14.1
Processing /home/ps/train/YK/task/onnxruntime/build/Linux/Release/_deps/onnx-src/onnx/onnx.in.proto
Writing /home/ps/train/YK/task/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto
Writing /home/ps/train/YK/task/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto3
generating /home/ps/train/YK/task/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx_pb.py
[ 10%] Built target flatc
[ 10%] Built target onnxruntime_generate_def
[ 10%] Running C++ protocol buffer compiler on /home/ps/train/YK/task/onnxruntime/build/Linux/Release/_deps/onnx-build/onnx/onnx-ml.proto
[ 15%] Built target onnxruntime_mlas
[ 15%] Built target gen_onnx_proto
**gmake: *** [Makefile:166：all] error 2**
Traceback (most recent call last):
  File "/home/ps/train/YK/task/onnxruntime/tools/ci_build/build.py", line 2737, in <module>
    sys.exit(main())
  File "/home/ps/train/YK/task/onnxruntime/tools/ci_build/build.py", line 2634, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/ps/train/YK/task/onnxruntime/tools/ci_build/build.py", line 1395, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/ps/train/YK/task/onnxruntime/tools/ci_build/build.py", line 764, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/ps/train/YK/task/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/home/ps/anaconda3/envs/mmagic/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/ps/train/YK/task/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j80']' returned non-zero exit status 2.>

### Further information
version:
**onnxruntime(GPU): v1.14.1,**
ubuntu 22.04 LTS,
**cuda:11.1,
tensorRT:8.5.3.1,**
GPU: RTX 3090,
cmake: 3.30.6,
python: 3.10.0
protobuf: 3.20.3

**Comment by justinchuby** [comment]
Please feel free to create a feature request in the [microsoft/onnxruntime](https://github.com/microsoft/onnxruntime/issues) repository. Thanks.
