### ISSUE TITLE
Travis failed without clear reason

### ISSUE THREAD

**Issue by liqunfu** [onnx/onnx#670]
I had a pull request:
https://github.com/onnx/onnx/pull/668
which failed at: 
https://travis-ci.org/onnx/onnx/jobs/359111591

There is no clear error message on why it failed. AppVeyor build passed however. 

May someone help? Thanks!

**Comment by bddppq** [comment]
ONNX doc is auto-generated and the python/numpy code of each test case will be attached as example code snippet to the doc. You will need to invoke `python onnx/defs/gen_doc.py` to regenerate the doc.

**Comment by liqunfu** [comment]
Thanks @bddppq for your suggestion. It was because my git configuration for line break conversion. I did:
git config core.autocrlf input
which would convert CRLF on Windows to Linux LF. This solved my problem.
