### ISSUE TITLE
Getting errors when running the mean and average pooling tests

### ISSUE THREAD

**Issue by jendrikjoe** [onnx/onnx#673]
Hey everyone,

I am currently trying to incorporate the new submissions to the average pool and max pool testing in to my PR #575 . To test actual processing, I build a script to replace the fake backend with caffe2:

    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function
    from __future__ import unicode_literals

    import os
    import unittest
    import onnx.backend.base
    import onnx.backend.test
    import caffe2.python.onnx.backend

    class DummyBackend(onnx.backend.base.Backend):
        @classmethod
        def prepare(cls, model, device='CPU', **kwargs):
            super(DummyBackend, cls).prepare(model, device, **kwargs)
            raise unittest.SkipTest("This is the dummy backend test that doesn't verify the results but does run the checker")

        @classmethod
        def run_node(cls, node, inputs, device='CPU'):
            super(DummyBackend, cls).run_node(node, inputs, device)
            raise unittest.SkipTest("This is the dummy backend test that doesn't verify the results but does run the checker")

    backend_test = onnx.backend.test.BackendTest(caffe2.python.onnx.backend, __name__)
    if os.getenv('APPVEYOR'):
    backend_test.exclude(r'(test_vgg19|test_vgg16)')

    # import all test cases at global scope to make them visible to python.unittest
    globals().update(backend_test.test_cases)

    if __name__ == '__main__':
        unittest.main()

However, this leads to some of the written pooling tests to fail.
Could anyone tell me if it is just my script producing these errors and if the actual execution of the tasks is performed by the online build script?

Input is highly appreciated :)

Cheers,

Jendrik

**Comment by houseroad** [comment]
same_lower is not supported by Caffe2, and same_upper's support is here: https://github.com/caffe2/caffe2/pull/2325
I will get it landed soon.

**Comment by jendrikjoe** [comment]
Thanks for the input @houseroad! Will ignore them then :)
