### ISSUE TITLE
Tensor's name is missing in backend tests' example models

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#679]
Download squeezenet model from https://s3.amazonaws.com/download.onnx/models/opset_6/squeezenet.tar.gz
Unzip it and run the script below with squeezenet\test_data_set_0\input_0.pb
```python
import onnx
import sys

from onnx import TensorProto

proto = TensorProto()

# Read the existing address book.
f = open(sys.argv[1], "rb")
proto.ParseFromString(f.read())
f.close()
print(proto.name)
```

The output is empty.

**Comment by houseroad** [comment]
@snnn you are right, we don't provide the name in the TensorProto in this case.
According to the spec, the name of TensorProto is optional, only one is required, which is initializer: https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L241

So in run_model, inputs should be passed in the right order. :-)

**Comment by snnn** [comment]
Hi @houseroad ,

However, It's hard to know this tensor is for which input. 
For example, for the inception_v2 model in ONNX's model zoo, it has about 400 inputs.
```
data_0
conv1/7x7_s2_w_0
conv1/7x7_s2/bn_scale_0
conv1/7x7_s2/bn_bias_0
conv1/7x7_s2/bn_mean_0
conv1/7x7_s2/bn_var_0
conv1/7x7_s2/bn/sc_w_0
conv1/7x7_s2/bn/sc_b_0
conv2/3x3_reduce_w_0
conv2/3x3_reduce/bn_scale_0
conv2/3x3_reduce/bn_bias_0
conv2/3x3_reduce/bn_mean_0
conv2/3x3_reduce/bn_var_0
conv2/3x3_reduce/bn/sc_w_0
conv2/3x3_reduce/bn/sc_b_0
...
```
And 1 output 
```
prob_1
```
 
There is only 1 input tensor in each test data set. Though I know it should be for input "data_0", it's based on human guessing.

**Comment by houseroad** [comment]
@snnn Sure, it's on my list :-)

**Comment by snnn** [comment]
What's your planning? Do we have a issue here for tracking that?

**Comment by houseroad** [comment]
I would suggest you open an issue in onnx/models repo. We can track this issue there. :-)
