### ISSUE TITLE
Bundle TensorShapeProto with Tensor protos

### ISSUE THREAD

**Issue by NiklasGustafsson** [onnx/onnx#68]
Shape is a property of tensor types, one that no other type in the type system has. Rather than placing TensorShapeProto everywhere TypeProto appears, it would make more sense to move TensorShapeProto inside the Tensor messages.

This is a syntactic change, and should have any impact on the semantics or processing of shapes for inferencing or otherwise.

**Comment by bddppq** [comment]
TensorShapeProto has been merged into TensorTypeProto and SparseTensorTypeProto now.
