### ISSUE TITLE
Add a helper wrapper for constructing tensor initializers

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx#680]
Simple task - add helper utilities for constructing and manipulating initializers to https://github.com/onnx/onnx/blob/master/onnx/helper.py

Example code doing something similar: `make_tensor` in https://github.com/onnx/onnxmltools/blob/master/onnxmltools/proto/helper.py#L77

**Comment by bddppq** [comment]
For construction, initializers are a list of TensorProto, so `make_tensor`.

**Comment by dzhulgakov** [comment]
I think numpy_helper was what people on Gitter were looking for. Totally forgot about it :)
