### ISSUE TITLE
broadcasting semantics differ for Matmul and (Add, Max, Min, etc.) ? 

### ISSUE THREAD

**Issue by newling** [onnx/onnx#686]
The basic binary operators (Add, Max, Min, etc.) allow for the second tensor to be broadcast to the shape of the first tensor, the first tensor is never broadcast. 

According to the Matmul operator documentation, Matlum allows for the more general numpy-like broadcasting:
> If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly
 
Moreover, matmul does not require an explicit broadcast flag. I'd prefer broadcasting semantics to be the same for all Operators. 

I have read issue https://github.com/onnx/onnx/issues/83, how close are we to coming to an agreement on how broadcasting will work?

**Comment by houseroad** [comment]
MatMul is not an element-wise operator, so the broadcasting has different meaning. And our MatMul behavior is the same as numpy's.

**Comment by newling** [comment]
I agree that MatMul is not element-wise per se, but if one considers the matrices (final 2 dimensions of tensors) as elements, it is element-wise. Taking this into consideration numpy broadcasting is exactly the same for MatMul as the element-wise operations. 

Why have you chosen to follow numpy broadcasting for MatMul and not the element-wise operations? It seems inconsistent to me.

**Comment by houseroad** [comment]
2D matmul is actually quite different from add/sub/... and other element-wise ops.

For example:
a's shape (2, 3)
b's shape (3, 4)
matmul(a,b)'s shape is (2, 4)

The broadcasting is quite different from other element-wise ops.

**Comment by newling** [comment]
But Matmul is not 2D. It is not just the numpy dot operator. The distinction between matmul and dot is exactly it's broadcasting. There's no broadcasting in your example. 

a.shape = (1,1,2,3)
b.shape = (3,4,3,4)
matmul(a,b).shape = (3,4,2,4)

a.shape = (3,4,1,2,3)
b.shape = (3,1,2,3,4)
matmul(a,b).shape = (3,4,2,2,4)

etc. 

These broadcasting rules are exactly the same as for add/sub/etc in numpy. in onnx they are not.

**Comment by houseroad** [comment]
Yeah, your example makes sense. Right now, ONNX broadcasting style is different from Numpy, but this MatMul. We are considering whether we should change ONNX's broadcast to be compliant with Numpy. We can move our discussion to our gitter room: https://gitter.im/onnx/test_compliance

**Comment by newling** [comment]
ok, thanks for the update. Moving over to gitter now.

**Comment by ezyang** [comment]
As another data point, PyTorch's matrix multiply broadcasting is compatible with Numpy's and so more flexible than the broadcasting ONNX supports here.

**Comment by bddppq** [comment]
onnx has updated the broadcast semantics to match numpy in opset 7
