### ISSUE TITLE
model domain and opset_imports domain

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#688]
From https://github.com/onnx/onnx/blob/master/docs/IR.md#model,
I get model has a string domain.
And opset_imports(list of OperatorSetIdProto) also have domains.

So how to deal with model contains opset from multiple domains?
As my understanding, model domain is just for user using, let them can set custom domain, e.g. "com.abcdefg"
And opset_imports' domains come from onnx, they should be in defs.cc and compiled first. Model domain doesn't need to be contained in opset_imports' domains. 
They are almostly different things, am I right?

**Comment by houseroad** [comment]
Yes @fumihwh, you are right. The domain in model is just for the model itself.
The domains in opset_imports will be used when the model is loaded by the backend.
The default domain is "" or "ai.onnx". If you have any customized ops which are not in the official onnx opset, you can use the opset domain to distinguish them from the official ones. Then you backend will give some special handling on them. :-)

**Comment by fumihwh** [comment]
@houseroad So it is ok for opset_imports has multiple OperatorSetIdProto. Ok, I see. Thanks.

**Comment by houseroad** [comment]
Yes, one model may contain multiple OperatorSetIdProtos
