### ISSUE TITLE
Is it ok and better to get rid of using static variables in onnx?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#696]
Currently, op registration happens during static initialization, whose order is undefined. To support adding operators for customized domain, dynamically adding a domain should happen before customized op registration. There may be two options,
1. Move all operator registration into a static function to ensure domain customization will happen before op registration.
2. Not use static variables in onnx so that backends may control the initialization in right order.

Thoughts? @bddppq @houseroad @gramalingam  @ebarsoum

**Comment by bddppq** [comment]
I think we just need to change the [OpSchemaRegisterOnce ctor](https://github.com/onnx/onnx/blob/2af45df08182f26c2279c8177e3f736fc66e77ae/onnx/defs/schema.h#L533) to allow dynamically register domain.

A related question: why do we need to hardcode min&max version for each domain in `DomainToVersionRange`? I think we can instead programmatically figure out these versions in the registry?

**Comment by houseroad** [comment]
@linkerzhang @bddppq 
I vote for deterministic initialization order. This is quite important. Without it, we may have unexpected errors when using different compilers.

**Comment by linkerzhang** [comment]
Let's use this issue to track this work item to get rid of using static variables to initialize the op schema map.

**Comment by bddppq** [comment]
@linkerzhang sorry I don't get why we need get rid of static variables?

**Comment by bddppq** [comment]
@houseroad what's the error you are referring to?

**Comment by houseroad** [comment]
@linkerzhang I have synced with @anderspapitto and @bddppq offline. We would like to make sure the initialization order, and at the same, also please keep the interface user-friendly.

**Comment by bddppq** [comment]
@houseroad  @linkerzhang  Sorry why do we need to make sure the order of the schemas registration?

**Comment by houseroad** [comment]
What I can think of is that at the compile time we can make sure all the schemas are registered in the right order. So when register some different ops (at compilation time), we can have some legit assumption.

On the other hand, because schema is so important, little change may break a lot of things, @linkerzhang I think @bddppq's concern makes sense. We don't want to go too far and introduce unnecessary changes/complexity.

**Comment by linkerzhang** [comment]
Great! Let me see whether I may come out of a solution of not impacting the current API (or at least not big change) as well as supporting non-static registration.
