### ISSUE TITLE
supports_device() always true in backend base.py

### ISSUE THREAD

**Issue by raymondxyang** [onnx/onnx#698]
[Source](https://github.com/onnx/onnx/blob/master/onnx/backend/base.py#L73)

This leads to enabling CUDA testcases on Appveyor, and there is no clear documentation AppVeyor for CUDA support.

**Comment by houseroad** [comment]
I will create a PR to fix this. :-)

**Comment by houseroad** [comment]
@raymondxyang I have discussed with @bddppq offline. In base.py, this design is intended. I have added the implementation for the DummyBackend https://github.com/onnx/onnx/pull/701
