### ISSUE TITLE
Plans for Supporting Torch

### ISSUE THREAD

**Issue by sbodenstein** [onnx/onnx#7]
@soumith: I know that there are plans for supporting PyTorch. Are there any plans for supporting Torch? Or will it be supported indirectly via a Torch to PyTorch converter?

**Comment by soumith** [comment]
we have no plans of supporting lua torch, and are unlikely to look into it.

**Comment by sbodenstein** [comment]
Ok, thanks for the rapid response!

**Comment by ezyang** [comment]
However, we are planning to support importing onnx models into PyTorch. The priority for this particular feature is not high, but we may need it for some high priority work that is going on.

**Comment by jsenellart** [comment]
Hello, I have a first draft of luatorch > onnx extraction here: https://github.com/jsenellart/luatorch-onnx-convert. Still work in progress, but it works end-to-end and converts discovered `nn`, `nngraph` and `onmt` modules to onnx - infering shapes when necessary, and building initializers. Contact me if you need specific support.
