### ISSUE TITLE
during test, use output node's schema to check the output type

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#703]
I don't think current solution is perfect.
Ops always allow multiple types, e.g. tensor(float16), tensor(float), tensor(double).
Just do `np.testing.assert_equal(ref_outputs[i].dtype, outputs[i].dtype)` is not enough.
The better way is use output node's schema to check the type.

I did some work about this and will create a PR to fix this.
One problem is I am not sure where put onnx type string to np type mapping to. Please give your advice.

**Comment by bddppq** [comment]
There are ops that can have multiple outputs types, however, given inputs types, the outputs types are **determined**. e.g. [Add](https://github.com/onnx/onnx/blob/master/docs/Operators.md#add)'s output type needs to be the same as its input's type.

**Comment by fumihwh** [comment]
`given inputs types, the outputs types are determined`
I get it. Thanks.
