### ISSUE TITLE
Verifying the node test data in CI

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#715]
We should verify the node test data using cmd_tools.py.

**Comment by fumihwh** [comment]
@houseroad 
It's a little bit hard to do this without constraint fields which are not in descriptor currently. (current is string, something like 
![image](https://user-images.githubusercontent.com/6838753/38503510-38efc3e6-3c4d-11e8-82d0-eb23099a8147.png)
)
I know output's type should as same as input's mostly.
But how about [Argmax](https://github.com/onnx/onnx/blob/master/docs/Operators.md#argmax)?
ArgMax has a total differently output `reduced` with type `tensor(int64)`.
Of course we could get `tensor(int64)` from defs.
Should we add a mapping for such case?

**Comment by houseroad** [comment]
In every PR, the CI should automatically run the cmd_tools.py to generate the testing data for node test. Ideally, they should be exact the same as the data generated on users' machine. However, cmd_tools.py may generate slightly different results in different environment, due to different versions of numpy, different versions of python, etc... So we cannot blindly compare them bytes by bytes.

The plan is to load the data and compare the content with small tolerance. The serialized pb file should already contain enough information for this comparison.

**Comment by askhade** [comment]
Closing this issue... There is discussion ongoing to remove test data from onnx packages and instead generate it on the fly using the scripts and the checked in test cases. 
https://github.com/onnx/onnx/issues/2912 and https://github.com/onnx/onnx/issues/2917
