### ISSUE TITLE
Gemm inputs of Inception v1/v2 inconsistent with ONNX spec

### ISSUE THREAD

**Issue by duli2012** [onnx/onnx#724]
In ONNX tests [Inception v1](https://github.com/onnx/onnx/blob/5716e2076b445b6c5bd017aaadc05d59ac43bdc3/onnx/backend/test/data/real/test_inception_v1) and [Inception v2](https://github.com/onnx/onnx/blob/5716e2076b445b6c5bd017aaadc05d59ac43bdc3/onnx/backend/test/data/real/test_inception_v2), the first input to GEMM op has 4 dimensions while the [ONNX spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gemm) states it should have only 2 dimensions. A possible quick fix would be inserting a reshape node before Gemm node. More fundamental changes might be needed in the model converter that produces this model.

Could someone take a look at it?

Thanks.

**Comment by houseroad** [comment]
Looks like in inception v2, the op before gemm is an average pool, which will generate a 4d tensor. indeed we should regenerate the model.

**Comment by duli2012** [comment]
Thanks for quick response, @houseroad !
Now, both inception v1 and v2 work. However, bvlc_alexnet has the same issue as well. Could you please take a look?

**Comment by houseroad** [comment]
All models should not have the problem any more, just updated :-)

Please try https://s3.amazonaws.com/download.onnx/models/opset_6/bvlc_alexnet.tar.gz

**Comment by LucasMahieu** [comment]
Same as : https://github.com/onnx/onnx/issues/405
Thanks
