### ISSUE TITLE
There is a bug in run_model()

### ISSUE THREAD

**Issue by kuke** [onnx/onnx#734]
When using run_model() to execute my own ONNX model, I got an error
```
File "/xxx/lib/python2.7/site-packages/onnx/backend/base.py", line 57, in run_model
    return cls.prepare(model, device, **kwargs).run(inputs)
AttributeError: 'NoneType' object has no attribute 'run'
```

Seems that [onnx/models/#4](https://github.com/onnx/models/issues/4) has not been fixed yet, and @bddppq  could you please help to check this problem again?

**Comment by fumihwh** [comment]
I guess you are not using any implement of Backend.
I suggest you could check https://github.com/onnx/onnx/blob/master/docs/ImplementingAnOnnxBackend.md

**Comment by kuke** [comment]
@fumihwh Thanks! Yeah, I tend to caffe2 Backend and succeeded to run the model. But why don't ONNX implements the runnable backend for itself.
