### ISSUE TITLE
We need to be able to distinguish "no shape information" from "scalar"

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#736]
Currently, we have (with some bits cut out)

```
message TensorShapeProto {
  ...
  repeated Dimension dim = 1;
}

message TypeProto {
  message Tensor {
    ...
    optional TensorShapeProto shape = 2;
  }
  ...
}
```

In theory, we can represent "no shape information" by having `has_shape()` be false, and we can represent "scalar" as "`has_shape()` is true, and `dim_size()` is zero".

However, the C++ protobuf api doesn't distinguish between these two cases (it can be done in python, for example see https://gist.github.com/anderspapitto/f772b697ced651ff3aefba0dbcab02ee)

So we may need to add an additional field to the protobuf definitions to represent "no shape information"

**Comment by dzhulgakov** [comment]
Hm, are you sure C++ doesn't distinguish? There's `has_shape` in the API:

```
  // accessors -------------------------------------------------------

  // optional .onnx.TensorShapeProto shape = 2;
  bool has_shape() const;
  void clear_shape();
  static const int kShapeFieldNumber = 2;
  const ::onnx::TensorShapeProto& shape() const;
  ::onnx::TensorShapeProto* release_shape();
  ::onnx::TensorShapeProto* mutable_shape();
  void set_allocated_shape(::onnx::TensorShapeProto* shape);
```

**Comment by bddppq** [comment]
per offline discussion, c++ `has_shape` can be used to distinguish these two cases.
