### ISSUE TITLE
Statically unknown sizes of dimensions

### ISSUE THREAD

**Issue by stgrue** [onnx/onnx#740]
Hi,

according to the ONNX specification, it is possible for a model to have inputs with dimensions whose size is statically unknown:

> The types of the inputs and outputs of the model must be specified, including the shapes of tensors. While the ranks of input and output tensors are statically specified, the sizes of specific dimensions (axis) may be statically unknown and are indicated so using symbolic identifiers in the shape.

Unfortunately, I wasn't able to find any more information about these "symbolic identifiers". Is there any information available on how to use them?

More specifically, I have a tensor – resulting from a PyTorch export – that is supposed to serve as the input for an LSTM node. It looks like this:

```
input {
  name: "0"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: 5
        }
        dim {
          dim_value: 1
        }
        dim {
          dim_value: 3
        }
      }
    }
  }
}
```

The first two dimensions describe sequence length and batch size, respectively, which is why it makes no sense for them to be statically specified; after all, the whole point of an RNN is to handle sequences of varying length. What I want is a tensor that looks something like this:

```
input {
  name: "0"
  type {
    tensor_type {
      elem_type: FLOAT
      shape {
        dim {
          dim_value: ?
        }
        dim {
          dim_value: ?
        }
        dim {
          dim_value: 3
        }
      }
    }
  }
}
```

Could you give me some pointers on how to create a tensor similar to this? I have already tried `lstm_input_node.type.tensor_type.shape.dim[0].dim_value = None`, but that just results in a type error. Any help would be greatly appreciated.

**Comment by bddppq** [comment]
For unknown shape, use [dim_param](https://github.com/onnx/onnx/blob/3e560dd7cb76006c15591c9180eedfd8d4c68587/onnx/onnx.proto#L381).

**Comment by stgrue** [comment]
This works perfectly, thank you for your help!

As a follow-up question: Right now, I use `"?"` as the value for `dim_param`, but that seems rather arbitrary. Is there any convention on which value to specify for `dim_param`?

**Comment by bddppq** [comment]
There is no well defined convention yet, but I would encourage you to use some normal variable name.
Besides, marking them all as `?` is not ok because our shape inference actually treat params with same name as the same variable. If you want to represent "unknown", then just leave `shape` in the ValueInfoProto unset.

**Comment by linkerzhang** [comment]
I think what @bddppq  suggested here is for the dimension with unknown size, keep it not set so that its value_case should be TensorShapeProto_Dimension::VALUE_NOT_SET.

**Comment by bddppq** [comment]
@linkerzhang No, not set to NOT_SET, I meant don't set it. See here: https://github.com/onnx/onnx/issues/736

**Comment by JiayiFu** [comment]
Is there any update about the support of dynamic shape? Most of the discussion was a year ago and I haven't found any official docs about dynamic shape.

**Comment by gramalingam** [comment]
Dynamic shapes are supported. Please see: https://github.com/onnx/onnx/blob/master/docs/IR.md#static-tensor-shapes

**Comment by Liujingxiu23** [comment]
@stgrue I am  a newer of onnx, I don't understand how to sovle the problem. For example, for tensor [1, seqlen, 80] , what is the right expression?  
dummy_input = Variable(torch.randn(1, TensorShapeProto::dim_para, 80))  ？

**Comment by gramalingam** [comment]
Do  you mean in Pytorch? If you are using Pytorch, the Pytorch exporter should do the job for you. Or, are you creating an ONNX model by hand? In ONNX, a shape is a list of dimensions, and each dimension is either a string containing an identifier (e.g., "N") or an integer value or unspecified. Both unspecified dimensions and a symbolic identifier denote an unknown dimension, with the difference that if an identifier is used, then all dimensions that have that identifier must have the same value at runtime.
