### ISSUE TITLE
Undefined Symbol

### ISSUE THREAD

**Issue by wesleyw72** [onnx/onnx#745]
I'm trying to build ONNX, I have tried several times.
I have a Conda distribution, Python 3. I have installed protobuf using Conda (no system protobuf installed).
OS: Ubuntu 16.04
ONNX builds fine, but when I try to import it I get the following:

`>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ww/anaconda3/lib/python3.6/site-packages/onnx-1.1.1-py3.6-linux-x86_64.egg/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/home/ww/anaconda3/lib/python3.6/site-packages/onnx-1.1.1-py3.6-linux-x86_64.egg/onnx/helper.py", line 14, in <module>
    import onnx.defs as defs
  File "/home/ww/anaconda3/lib/python3.6/site-packages/onnx-1.1.1-py3.6-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C  # type: ignore
ImportError: /home/ww/anaconda3/lib/python3.6/site-packages/onnx-1.1.1-py3.6-linux-x86_64.egg/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

**Comment by wesleyw72** [comment]
Just tried this on a freshly built machine with Ubuntu 16.04, following the instructions in this repo. I had the same problem again.

**Comment by houseroad** [comment]
looks like it's a protobuf lib issue. Could you make sure that you only install one version of protobuf. Either system one or conda one.

**Comment by wesleyw72** [comment]
@houseroad I tried it with only the conda version installed and it did not work.

**Comment by houseroad** [comment]
It seems protobuf related shared library cannot be detected. Could you check your virtual env? Maybe try to include protobuf lib into LD_LIBRARY_PATH。

**Comment by guoyejun** [comment]
i also met this issue with 'conda install -c conda-forge protobuf numpy', and the issue is gone with 'conda install protobuf numpy', there is no error to run 'python setup.py install'.

**Comment by jendrikjoe** [comment]
Hey @guoyejun, I have the exact same issue on 18.04. I tried your fix which simply leads to a Segmentation Fault when importing onnx (however think that is really a protbuf bug...)

**Comment by jendrikjoe** [comment]
Hey @guoyejun, thank you for the hint. unluckily that didn't solve the issue :(

**Comment by elboyran** [comment]
I have exactly the same issue with 18.04! In a conda environment. I have installed both:

-  onnx from  source (installing it from binaries  doe snotinstall the latest onnx and some funcitonality was missing like save!)

- first the protobbuf then onnx

I get exactly the same error from the checkout directory as well as from another one!

Can you, please, advice.

**Comment by hhxxttxsh** [comment]
@guoyejun  I repeated what you suggested and got: ImportError: /home/ruoyan01/anaconda2/lib/python2.7/site-packages/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

No idea why. Can we build onnx from source using anaconda dependencies at all?

**Comment by rutayanp** [comment]
^^I am also seeing the same issue

**Comment by toffebjorkskog** [comment]
Any news on how to solve this?

**Comment by elboyran** [comment]
I haven't tried to install it again recently.

**Comment by bpinaya** [comment]
On Ubuntu 16.04, with protobuf installed from apt:
```
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  libprotoc-dev:amd64                           2.6.1-1.3                   amd64                       protocol buffers compiler library (development files)
ii  protobuf-compiler                             2.6.1-1.3                   amd64                       compiler for protocol buffer definition files

```
The instalation from source with `python setup.py install` succeds but after trying to load it:
```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bpinaya/anaconda3/envs/onnxtrt/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-x86_64.egg/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "/home/bpinaya/anaconda3/envs/onnxtrt/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-x86_64.egg/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "/home/bpinaya/anaconda3/envs/onnxtrt/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-x86_64.egg/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/bpinaya/anaconda3/envs/onnxtrt/lib/python3.6/site-packages/onnx-1.3.0-py3.6-linux-x86_64.egg/onnx/onnx_cpp2py_export.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
>>> 

```

`conda list` output:
```
# packages in environment at /home/bpinaya/anaconda3/envs/onnxtrt:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0  
certifi                   2018.10.15               py36_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libstdcxx-ng              8.2.0                hdf63c60_1  
ncurses                   6.1                  hf484d3e_0  
numpy                     1.15.4                    <pip>
onnx                      1.3.0                     <pip>
openssl                   1.1.1                h7b6447c_0  
pip                       18.1                     py36_0  
protobuf                  3.6.1                     <pip>
python                    3.6.7                h0371630_0  
readline                  7.0                  h7b6447c_5  
setuptools                40.6.2                   py36_0  
six                       1.11.0                    <pip>
sqlite                    3.25.3               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
typing                    3.6.6                     <pip>
typing-extensions         3.6.6                     <pip>
wheel                     0.32.2                   py36_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               ha838bed_2
```
It also fails when installing protobuf from conda-forge, any ideas? Installing the binaries directly does work but I'm having issues getting it to work with tensorrt as backend.

**Comment by YueshangGu** [comment]
same question.
```
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/kai/anaconda2/lib/python2.7/site-packages/onnx-1.3.0-py2.7-linux-x86_64.egg/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```
and about protobuf
```
libprotobuf               3.5.2                hd28b015_1    conda-forge
protobuf                  3.5.2            py27hd28b015_0    conda-forge
```

**Comment by yufenglee** [comment]
I met the same issue and found the reason is that ONNX is built with cxx11 abi but protobuf is built with old abi (non cxx11). Adding 'add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)' in the CMakeLists.txt works around the issue.

**Comment by ghltshubh** [comment]
I am on a shared machine so don't have sudo access any work around for that? I am getting the same error.

```
$ python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pytorch-1.0-p3/anaconda3/lib/python3.6/site-packages/onnx/__init__.py", line 11, in <module>
    import onnx.helper  # noqa
  File "pytorch-1.0-p3/anaconda3/lib/python3.6/site-packages/onnx/helper.py", line 13, in <module>
    import onnx.defs as defs
  File "pytorch-1.0-p3/anaconda3/lib/python3.6/site-packages/onnx/defs/__init__.py", line 7, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError:pytorch-1.0-p3/anaconda3/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE
```

**Comment by ghltshubh** [comment]
@yufenglee I added this to my CMakeLists file but didn't help. I am using python 3.6.8, Cmake 3.11, protobuf 3.6.1

**Comment by DanlanChen** [comment]
I am also seeing the same issue, i installed protobuf in conda environment, and install onnx using pip.

**Comment by espectre** [comment]
I also met the same problem.
ImportError: /usr/local/lib/libnvonnxparser.so.0: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
And have solved with next:
Firstly,execute your file in onnx_tensorrt directory
Secondly,in the file,lay `import onnx_tensorrt.backend as backend` on the top.
Namely,
```
import onnx_tensorrt.backend as backend
import onnx
import numpy as np
```
instead of 
```
import onnx
import onnx_tensorrt.backend as backend
import numpy as np
```
