### ISSUE TITLE
Spec clarity: Versioning -- 64 bits vs 32 bits.

### ISSUE THREAD

**Issue by NiklasGustafsson** [onnx/onnx#746]
In all the places where version numbers are used in the protobuf specification, they are represented using 64 bits. 

However, the 'Versioning.md' document unambiguously states that version numbers are packed in 32 bits:

``
For efficiency, ONNX serializes the MAJOR, MINOR, and PATCH values as a bit-packed 32-bit integer; the most significant byte is the MAJOR component, the second most significant byte is the MINOR component, the least significant two bytes are the PATCH component.
``

This difference leads to confusion around what the correct encoding is, and needs to be straightened out. 

I see three options:

1. Using 64 bits to store the integer, but only using 32 bits. This is odd, but would require only that the documentation clearly explains the oddity.
2. We simply change the documentation to reflect packing of version numbers into 64 bits. Instead of one byte for each of the major/minor numbers, we would use two for each, and instead of two bytes for the PATCH component, we would use four.
3. Change the proto files to hold the version numbers in 32 bits. This would be a breaking change.

Option no. 1 would be the least impactful, but would perpetuate something rather odd.

So far, neither the IR versions or the operator set versions actually depends on the stated 32-bit encoding, so as long as no published models rely on the encoding described in 'Versioning.md,' going with option no. 2 would not impact anything, but I'm not sure whether we know that.

No. 3 seems to me the least desirable, since it's a breaking change to fix something rather trivial.

**Comment by linkerzhang** [comment]
vote for 2.

**Comment by prasanthpul** [comment]
spec was clarified
