### ISSUE TITLE
Interpretation of graph-valued and tensor-valued attributes underspecified

### ISSUE THREAD

**Issue by donbox** [onnx/onnx#75]
For graph-valued attributes:
1. Does the name of the graph have significance, and if so, how is it referenced?
1. Do the nodes in the graph valued attribute have access to the same Value namespace as the parent graph?
1. What scenarios are we trying to satisfy with graph-valued attributes? Are they meant to be a poor-man's function definition?  Are they meant to allow operators to work as scheme/lisp-style special forms?

For tensor-valued attributes:
1. Is the tensor value available as a Node/Graph input or output?
1. If so, is it referenced by TensorProto.name or AttributeProto.name?

**Comment by dzhulgakov** [comment]
For graph valued the main use case would be control-flowing like operations, e.g. generic recurrent nets where graph-value attribute might represent the cell net. It probably makes sense to postpone the discussion till we get to design details on rnns.

For tensor-valued:
1. Similarly to other attributes the value is local to the node and is not exposed in the output
2. I think we can clarify that TensorProto.name should be empty if the tensor is used as an attribute (primarily for Constant-type of ops)

**Comment by ezyang** [comment]
> Are they meant to be a poor-man's function definition? Are they meant to allow operators to work as scheme/lisp-style special forms?

Note that because ONNX has no side-effects and is not Turing complete, subgraphs/lambdas serve both. All special forms can be implemented with functions when you don't have side effects :)
