### ISSUE TITLE
LRN definition clarification

### ISSUE THREAD

**Issue by newling** [onnx/onnx#750]
Please confirm for LRN: 
Normalization is pixelwise across channels ( as per Tensorflow ) and is not within-channel in spatial rectangle. That is, it is like Caffe LRN with ACROSS_CHANNELS = 1.
The onnx info for LRN is  https://github.com/onnx/onnx/blob/master/docs/Operators.md#LRN

**Comment by newling** [comment]
Moreover, assuming it's ACROSS_CHANNELS = 1, how exactly is the local region defined? Is it the same as in tensorflow https://github.com/tensorflow/tensorflow/blob/e489b600f388ae345387881a85368af3cd373ba2/tensorflow/compiler/tf2xla/kernels/lrn_ops.cc#L44

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/965 addresses the problem.

**Comment by newling** [comment]
Looks good, thanks.
