### ISSUE TITLE
How to make backend tests

### ISSUE THREAD

**Issue by newling** [onnx/onnx#752]
I am encountering issues generating backend Operator tests.

```
..onnx/onnx/backend/test$ python cmd_tools.py generate_data
```
gives 
```
AttributeError: 'TestCase' object has no attribute 'kind'
```
ipython with
```
In [1]: run -i cmd_tools.py
 ```
gives
```
ModuleNotFoundError: No module named 'onnx.backend.test.case.utils'
```

The info at https://github.com/onnx/onnx/blob/master/docs/OnnxBackendTest.md
seems old (generates node.pb not model.onnx) and assumes onnx is installed .

Can a detailed description of how the model.onnx files, 
```
..onnx/onnx/backend/test/data/node/test_*/model.onnx  
```
are generated please be provided (I can provide new tests if so ;)) ?

**Comment by houseroad** [comment]
`python onnx/backend/test/cmd_tools.py generate-data` works for me.

I will add more details about in the markdown file.

**Comment by newling** [comment]
I'm up and running. I had some weird issues with the way I was building (wasn't using setup.py, now I am). 

Thanks!
James
