### ISSUE TITLE
Apply attribute to input transform uniformly / outline best practices

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#76]
In https://github.com/onnx/onnx/pull/63 we came to the conclusion that, whenever possible, we should prefer representing operators as taking a zero-dim tensor input (i.e., scalar) rather than an attribute. The motivation is that scalars as tensor inputs is strictly more expressive than attributes, because their values can vary at runtime (as opposed to attributes, which are fixed), so you're going to need the tensor input variants anyway, and so you might as well drop the attribute.

However, the PR only handles Pow and Slice, but there are a number of other operators (e.g., `AddConstant`) which take scalars, and need to be harmonized by removing the `AddConstant` version and deferring it to `Add`. We may also need to determine a coherent story for broadcasting, because the most parsimonious way to give meaning to addition of a tensor with a zero-dim tensor is through broadcasting, but may operators today (e.g., Gemm) explicitly specify whether or not broadcasting on a particular argument takes place. (Though, we may be able to sidestep this issue by special casing scalar.)

Furthermore, writing ONNX in this style needs some logic from frontends-backends, which we should document, to help frontend/backend writers.

1. If you are a frontend, and you convert from an attribute as opposed to an input, you have to allocate a Scalar to pass into the operator. We should make sure it's clear and easy how to allocate a zero-dim tensor in this case.
2. If you are a backend, and you convert to a scalar to an attribute as opposed to an input, because, perhaps, you don't support broadcasting, or you have a more efficient non-broadcasting implementation. In this case, you need to implement a simple constant propagation analysis on ONNX, so that at any point in time, you know if tensor inputs are constants or not. This is perhaps best prototyped in onnx-caffe2.

List of operators to look at:

* Split (split input/attribute, is a list; this is particularly perplexing because it looks like PyTorch is emitting slices as non-attributes right now)
* AddConstant/SubConstant (which are experimental)
* (probably more experimental ops)

**Comment by ebarsoum** [comment]
@ezyang  thanks for the summary, this preference should be based on the OP, not every OP need such flexibility, right?

**Comment by bddppq** [comment]
@ezyang I see you have explicitly said "zero-dim", "scalar". Attributes can be a list, are these attributes excluded from this discussion?

@ebarsoum I think this proposal is more of adding a constraint rather than flexibility? But anyway I think we should have a consistent setup for all the ops.
