### ISSUE TITLE
For Gemm operator, are all attributes compulsory?

### ISSUE THREAD

**Issue by newling** [onnx/onnx#761]
I'm running the resnet-50 model from 
https://github.com/onnx/models/tree/master/resnet50
and the only attributes set are `transB` and `broadcast`.

However the spec does not mention default values. 

Thanks for clarifying.

**Comment by bddppq** [comment]
Yeah all attributes of Gemm have default values: https://github.com/onnx/onnx/blob/c9f825fc68b96b6a8c8895f4f2102f8630f75bf0/onnx/defs/math/defs.cc#L563
In the doc, required attributes have been annotated with `(required)`, those don't have this tag are optional. It would be more ideal to beef up the doc to also render the default values.

**Comment by newling** [comment]
Ok, got it. Yes, I guess it'd be good if the defaults could be generated in gen_doc.py too.
