### ISSUE TITLE
Problems installing ONNX 1.1.0

### ISSUE THREAD

**Issue by franchenstein** [onnx/onnx#762]
I am trying to install ONNX 1.1.0 to try out the tensorflow 2 onnx converter but I am having trouble with that. I tried to install both on Linux (Ubuntu) and Windows 10.

On Linux I basically get an error while running the setup.py saying that the protobuf headers were compiled for a previous version, incompatible with protoc. I get this even after purging protobuf and installing its latest version (3.5.1, both the Python version and compiling from the C++ source). I also checked protoc --version, which gives me protobuf 3.5.1.

On Windows it simply complains about the lack of protoc, although I downloaded it, extracted it and added the folder to PATH.

On the other hand, I am able to install version 1.1.1 with no problem. Is there any way to make the converter work with version 1.1.1? Or how can I solve these issues on installing version 1.1.0?

**Comment by franchenstein** [comment]
The tf2onnx converter (https://github.com/onnx/tensorflow-onnx) specifically requires 1.1.0. The setup script even tries to downgrade to 1.1.0 when I already have 1.1.1 installed

**Comment by bddppq** [comment]
@franchenstein Our v1.1.0 source distribution was released incorrectly (that it has bundled the protobuf 3.4 generated header files). To unblock you, please downgrade your protobuf to 3.4.
@anirudhacharya We need to take down the v1.1.0 source distribution from pypi.
@linkerzhang @guschmue @raymondxyang The v.1.1.0 release is considered invalid, please update tensorflow-onnx to use newer release.

To see more details:
https://github.com/onnx/onnx/issues/639

**Comment by guschmue** [comment]
updated tensorflow-onnx ...
