### ISSUE TITLE
import onnx segfaults with python 2.7 and python 3.6 on Ubuntu 16.04

### ISSUE THREAD

**Issue by MaheshRavishankar** [onnx/onnx#767]
I am trying to install ONNX as desribed in the installation page. These are the steps I followed

```bash
$> conda create --name onnx_py36 python=3.6
$> conda activate onnx_py36
(onnx_py36) $> conda install -c conda-forge onnx
```

(similar process for python 2.7). I get a segfault when i do 

```bash
$>python -c "import onnx"
```

[onnx_py27.log](https://github.com/onnx/onnx/files/1918190/onnx_py27.log)
[onnx_py36.log](https://github.com/onnx/onnx/files/1918191/onnx_py36.log)
[onnx_py27.log](https://github.com/onnx/onnx/files/1918192/onnx_py27.log)

I am running Ubuntu 16.04. Please let me know if there are other details that I need to provide.

**Comment by lukemurray** [comment]
In fact it segfaults on `import onnx.onnx_cpp2py_export.defs as C` in `defs/__init__.py`

**Comment by prasanthpul** [comment]
Please reopen if you are still having issues with latest versions
