### ISSUE TITLE
Output tensor type for size op (in node/test_size)

### ISSUE THREAD

**Issue by newling** [onnx/onnx#768]
Hi -- 
There seems to be an issue with the exact type of output TensorProtos in at least one node test. Signed vs unsigned. 

in directory node/test_size/test_data_set_0:

```
import onnx
f_out = open("output_0.pb", "rb")
new_tensor = onnx.TensorProto()
new_tensor.ParseFromString(f_out.read())
```
At this point `new_tensor.data_type` is 7. Looking in onnx.pb.h I see, 
```
TensorProto_DataType_INT64 = 7,
```
(aside : is there a function to get a string like `"signed long"` from an enum type in Python ONNX API)?

However the Size Operator spec specifies UINT64 (`13`) as output. So I'd expect the type of the tensor loaded from `output_0.pb` here to be `13` and not `7`.

**Comment by houseroad** [comment]
Refer to the newest version of our doc, Size's output is INT64.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#size

I have manually checked the output. They are good, which is INT64.

More details please check onnx/mapping.py I will add more explanation in the doc, too.

Thanks for reporting this.

**Comment by houseroad** [comment]
Actually, we should have used int64 in the spec, however, there was a typo. The test data is right since the very beginning. Sorry for the inconsistence. For any input/output related to index/size in onnx, we decide to use int64, this won't change any more.
