### ISSUE TITLE
Change the name of shape inference function into shape&type inference function

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#769]
Per current type constraint, it's still hard to do the type inference. It's only doable when inputs/outputs refer to same type key "T" for example. If there're multiple keys, no way to do good type inference for outputs' types per inputs' types.

**Comment by bddppq** [comment]
I believe the shape inference is already doing type inference together.
@anderspapitto

**Comment by linkerzhang** [comment]
Yep. It's a benefit from we having shape located in type :). The InferenceContext API does support doing type inference. Then we may change the name a little bit to reflect it. ShapeInferenceFunction --> TypeAndShapeInferenceFunction ?

**Comment by anderspapitto** [comment]
yes i can change the name

**Comment by linkerzhang** [comment]
this is done.
