### ISSUE TITLE
Please update all the pytorch-converted test data to opset version 6

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#773]
There are still some models in older version. For example, onnx\backend\test\data\pytorch-converted\test_PReLU_1d\model.onnx is in version 2.

**Comment by houseroad** [comment]
Yes, sir!

**Comment by linkerzhang** [comment]
Thank you very much! @houseroad

**Comment by snnn** [comment]
Thank you @houseroad

**Comment by houseroad** [comment]
there are 4 cases not updated. I am investigating the reasons.

**Comment by houseroad** [comment]
It's done
