### ISSUE TITLE
Install from sourec failed with Anaconda3 on Windows

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#778]
I am trying to install onnx from its source via

`pip install -e onnx`

but got the following error.

    LINK : fatal error LNK1104: cannot open file 'python36.lib' [D:\onnx\.setuptools-cmake-build\onnx_cpp2py_export.vcxproj]
    Done Building Project "D:\onnx\.setuptools-cmake-build\onnx_cpp2py_export.vcxproj" (default targets) -- FAILED.
    Done Building Project "D:\onnx\.setuptools-cmake-build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Is it Anaconda's problem?

**Comment by wschin** [comment]
By changing ${PY_VERSION}$ in onnx/CMakeLists.txt, I am able to build onnx finally.

Before:
  if(MSVC)
    find_package(PythonInterp ${PY_VERSION}$ REQUIRED)
    find_package(PythonLibs ${PY_VERSION}$ REQUIRED)
    target_link_libraries(onnx_cpp2py_export PRIVATE ${PYTHON_LIBRARIES})

After
  if(MSVC)
    find_package(PythonInterp REQUIRED)
    find_package(PythonLibs 3.6 REQUIRED)
    target_link_libraries(onnx_cpp2py_export PRIVATE ${PYTHON_LIBRARIES})

The problem was that my py36 interpreter is trying to find python35.lib.

**Comment by raymondxyang** [comment]
@bddppq I found removing the py_version for find_package(PythonInterp ...) help too in some previous cases. Can you help look into the root cause for it?

**Comment by bddppq** [comment]
In general cmake's find python is pretty messed up (especially finding python lib, but to be fair python needs to share the blame because there is no way to programmatically find libpython), and so it's better to try remove find python in cmake all together. The only reason we still do find python in cmake right now is we couldn't find a way to not link with libpython in windows build (we already do this in builds on other platform).

**Comment by bddppq** [comment]
See whether we can get rid of cmake's find python #780

**Comment by raymondxyang** [comment]
Well as far as I tested locally we cant.. I ll do some research to see if there is alternative methods..

**Comment by bddppq** [comment]
@raymondxyang what's the error messages?

**Comment by raymondxyang** [comment]
LINK : fatal error LNK1104: cannot open file 'python36.lib' [C:\xxxxx\onnx\.setuptools-cmake-build\onnx_cpp2py_export.vcxproj]

**Comment by bddppq** [comment]
@raymondxyang I'm quite curious what makes cmake looking for python36.lib :-)

**Comment by yuslepukhin** [comment]
Worked with @wschin This is now addressed.
