### ISSUE TITLE
Protobuf naming consistency / nested protos

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#78]
We've been keeping an eye on annoyances when we adjust PyTorch for latest changes in the ONNX proto, and we noticed some for https://github.com/onnx/onnx/pull/51

* Not all protobuf messages have the `Proto` suffix anymore; in particular, the nested protobuf `Dimension` doesn't have the suffix. This makes it look strange when compared with all the other protobuf messages. Can we make this consistent?

* Additionally, `TypeProto` defines nested protobufs. I wasn't sure how this was going to look in tooling, but we have discovered what happens with nanopb: you now get extremely ugly protobuf names like `TypeProto_TensorTypeProto`. This is especially ugly because `Type` is redundantly specified twice. Can we just put it at the top level of the protobuf?

**Comment by donbox** [comment]
The Proto/no-Proto suffix inconsistency has bothered me as well.

I'm fine unnesting the message definitions. Again, we are inconsistent.

If we are doing this, we should do it today or tomorrow.

It won't be a breaking change on the wire format so we shouldn't have to regen the PBs in AWS, but it will break all of our code.

Who wants to prep the PR?

**Comment by yuanbyu** [comment]
I am also in favor of getting rid of the nesting. But let us do it after 10/10, please.

**Comment by prasanthpul** [comment]
Sorry @yuanbyu - I managed to delete your comment. :(

I agree with you that this makes sense to do.

**Comment by ezyang** [comment]
Yes, I think we should still do it.
