### ISSUE TITLE
the `kernel_shape` parameter to Conv is redundant

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#785]
Rather than provide kernel_shape as an argument to Conv, one can simply provide a ValueInfoProto for the W input (with dimensions M and C left blank if they are unknown).

I propose to deprecate/remove kernel_shape from Conv.

**Comment by linkerzhang** [comment]
Using ValueInfoProto to specify the type/shape will ask value_info to be required. But I agree with you that kernel shape may be redundant since it should be inferred from the input.
