### ISSUE TITLE
"check-model" should check if the graph's every output is valid

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#793]
If some output isn't an output of any node, check-model should discover that and report an error.

**Comment by houseroad** [comment]
You mean some output is never initialized, (neither in initializer nor generated by any operator)?

Do you mind to provide any test case to reproduce the problem?

**Comment by snnn** [comment]
See https://github.com/onnx/onnx/issues/792

I don't think it's a valid model. Because every output must come from a node.

**Comment by houseroad** [comment]
As long as it is defined, it should be fine... In that case, it is defined by the input.
