### ISSUE TITLE
Is dilated convolution supported?

### ISSUE THREAD

**Issue by BenPYeh** [onnx/onnx#796]
I am converting a model from Caffe to CNTK, then from CNTK to ONNX. The Caffe model includes a dilated convolution, which is not supported on CNTK yet (at least not CPU). Is it supported by ONNX? Because the ONNX model I have won't load and I am wondering if it is due to this operation.

**Comment by houseroad** [comment]
Yes, it is supported by ONNX, which means the onnx model can contain dilated convolution operator. However, different backends provide different operator/attribute coverage, which means your onnx model may not be supported by some backend. Ideally, each backend should support all the operators.

**Comment by ebarsoum** [comment]
What the error? Are you trying to load ONNX model in CNTK?

**Comment by BenPYeh** [comment]
@ebarsoum yes I was. The model I was trying to run had a dilated convolution which isn't supported on the cpu in cntk yet so I guess that's why I was getting the error.

**Comment by houseroad** [comment]
@BenPYeh I think it is not an ONNX issue. Probably you should open an issue in CNTK.

**Comment by houseroad** [comment]
Not an ONNX issue.
