### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by Aakash456** [onnx/onnx#800]
One of the issues I have come across is that in python, arguments are initialized when function is defined not during each execution leading to issue in case argument is mutable e.x. list or dictionary. In that case it behaves like a static variable existing over all call to that function. 

>>> def foo(counter=[0]):
...   counter[0] += 1
...   print("Counter is %i." % counter[0]);
... 
>>> foo()
Counter is 1.
>>> foo()
Counter is 2.
>>>

**Comment by bddppq** [comment]
Feel free to reopen if you have found mutable default args in onnx (and please point out the specific places). Thanks
