### ISSUE TITLE
Got ERRORS in pytest

### ISSUE THREAD

**Issue by VincentLin78** [onnx/onnx#806]
Just install ONNX from source and run pytest.

==================================== ERRORS ====================================
__________ ERROR collecting onnx/test/backend_shape_inference_test.py __________
ImportError while importing test module '/Users/mingchelin/GitHub/onnx/onnx/test/backend_shape_inference_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
onnx/test/backend_shape_inference_test.py:15: in <module>
    from onnx.backend.test.runner import BackendIsNotSupposedToImplementIt
E   ImportError: cannot import name 'BackendIsNotSupposedToImplementIt'
______________ ERROR collecting onnx/test/shape_inference_test.py ______________
ImportError while importing test module '/Users/mingchelin/GitHub/onnx/onnx/test/shape_inference_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
onnx/test/shape_inference_test.py:9: in <module>
    import onnx.shape_inference
E   ModuleNotFoundError: No module named 'onnx.shape_inference'
_______________ ERROR collecting onnx/test/test_backend_test.py ________________
ImportError while importing test module '/Users/mingchelin/GitHub/onnx/onnx/test/test_backend_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
onnx/test/test_backend_test.py:11: in <module>
    from onnx.backend.test.runner import BackendIsNotSupposedToImplementIt
E   ImportError: cannot import name 'BackendIsNotSupposedToImplementIt'
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 3 error in 0.71 seconds ============================

**Comment by stihl1210** [comment]
I have the same problem. I have MacOS caffe2 version. So ONNX cannot be used in non-gpu enviroment (assumption from the warnings).

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rafalpilarczyk/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/onnx/backend.py", line 37, in <module>
    import onnx.shape_inference
  File "/Users/rafalpilarczyk/anaconda3/envs/caffe2/lib/python2.7/site-packages/onnx/shape_inference.py", line 11, in <module>
    import onnx.onnx_cpp2py_export.shape_inference as C
ImportError: No module named shape_inference
>>>

**Comment by anderspapitto** [comment]
@stihl1210 onnx does not require a gpu at all (those gpu-related warnings you see are coming from Caffe2, not from Onnx. also they are only warnings, you can still run models on the CPU).

Which version of caffe2 are you running, and how did you install it?

**Comment by stihl1210** [comment]
@anderspapitto Ok I understand. I installed the latest version of caffe2 from prebuilt binaries. Probably this issue is related with Matlab ONNX exporter, I see that there were few changes in ONNX so it is not compatible with Matlab exporter. When I tried to port Caffe2 model to something different via ONNX like MXNet I had no problems.
