### ISSUE TITLE
test data test_operator_selu is wrong

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#816]
<onnx root>\onnx\backend\test\data\pytorch-operator\test_operator_selu contains the model for selu, attribute default values are: alpha = 1.6732f, and gamma = 1.0507f. I found pytorch uses a different default value for selu with alpha = 1.6732632423543772848170429916717 and gamma = 1.0507009873554804934193349852946. 

pytorch saved the node with default attribute, not the actual one it used in computation

**Comment by linkerzhang** [comment]
@houseroad ,

**Comment by houseroad** [comment]
I have done some research, all the implementations using alpha = 1.6732632423543772848170429916717 and gamma = 1.0507009873554804934193349852946 as default values. If we use float, the decimal precision is 7, for double, it's 16. Apparently, the default values in our current spec are not precise enough (which is 4 now), I prefer to change our spec.

**Comment by houseroad** [comment]
More reference:

The original authors' implementation, Tensorflow (Keras), PyTorch, Caffe2, and even CNTK use the same default values.

**Comment by houseroad** [comment]
Proposed fix here: https://github.com/onnx/onnx/pull/839

**Comment by houseroad** [comment]
Already fixed.
