### ISSUE TITLE
Loss functions in ONNX

### ISSUE THREAD

**Issue by SimiPro** [onnx/onnx#824]
Is there any plan to support loss functions in the future?

**Comment by ebarsoum** [comment]
There is a work track to add training support to ONNX, which will probably cover loss function. However, even withoout loss function, you should be able to implement them using ONNX primitive.

**Comment by SimiPro** [comment]
Yes of course. This is exactly what we've done. <br>
Is this work track visible anywhere online ?

**Comment by linkerzhang** [comment]
Training
Leader: Sukwon Kim sukwokim@amazon.com
Discussion: Training Gitter Room
The goal of the group is to explore the possibility of expanding ONNX to support training as well as inference.

**Comment by SimiPro** [comment]
thanks!
