### ISSUE TITLE
What if the "permutation" is not a static attribute?

### ISSUE THREAD

**Issue by yehenrytian** [onnx/onnx#825]
https://github.com/onnx/onnx/blob/15289e3d77a9014f70c413c757a5805261dd94ec/onnx/optimizer/passes/eliminate_nop_transpose.h#L15

In ONNX, you define the permutation as an attribute with a constant value of the "Transpose" Op, but what if the permutation is a tensor that comes in as a parameter (like in TensorFlow), then at static compile time, how can we perform this optimization check? Thanks!

**Comment by houseroad** [comment]
In onnx's spec, `perm` is an attribute of `Transpose`, which means `perm` is determined statically. So it won't be a problem in our optimizer.

In your case, if `perm` cannot be exported statically, existing onnx spec is not able to express it. However, this should be rare. If you have such use case, please send feedback to us. Thanks.
