### ISSUE TITLE
OptimizePass:  declaration of 'name' hides class member

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#826]
onnx\onnx\optimizer\passes\optimize_pass.h(31): warning C4458: declaration of 'name' hides class member (compiling source file C:\src\Lotus\external\onnx\onnx\optimizer\optimize.cc)
onnx\onnx\optimizer\passes\optimize_pass.h(19): note: see declaration of 'ONNX_NAMESPACE::optimization::OptimizePass::name' (compiling source file C:\src\Lotus\external\onnx\onnx\optimizer\optimize.cc)

Introduced in commit 3cb4d61387658f9f38a6a4fd2cc4557a7beb8816

**Comment by jcwchen** [comment]
ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this issue, please raise an issue there. Thank you!
