### ISSUE TITLE
ONNX_OPERATOR_SCHEMA(Split) should check if axis is negative

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#827]
ONNX_OPERATOR_SCHEMA(Split) should check if axis is negative before calling "ctx.getInputType(0)->tensor_type().shape().dim(axis);"

```c++
auto axisAttr = ctx.getAttribute("axis");
      int axis = axisAttr ? static_cast<int>(axisAttr->i()) : 0;
      std::vector<int64_t> split;
      if (!getRepeatedAttribute(ctx, "split", split)) {
        if (!ctx.getInputType(0)->tensor_type().has_shape()) {
          return;
        }
        const auto& splitDim =
            ctx.getInputType(0)->tensor_type().shape().dim(axis);
       ...
      }
```

Otherwise, it may access wrong memory location.

**Comment by houseroad** [comment]
There are two different issues:
1) Whether we should support negative axis, (open question)
2) The shape inference should check the attributes before using them.

**Comment by snnn** [comment]
For question one, onnx have such things in the pytorch converted test data.

**Comment by bddppq** [comment]
1. yes
2. maybe add something like this: https://github.com/pytorch/pytorch/blob/master/caffe2/core/tensor.h#L636.

As a side note, we should prioritize the work of adding specific checks into individual Operator.

**Comment by snnn** [comment]
This is definitely a security bug must be fixed.
