### ISSUE TITLE
"test_Softsign" should contain only 1 OP

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#837]
onnx\backend\test\data\pytorch-converted\test_Softsign\model.onnx

Now it is a mix of: Abs/Constant/Add/Div

**Comment by houseroad** [comment]
@snnn I am confused, why should this test case only contain only one op?

**Comment by snnn** [comment]
we have softsign op for that？

**Comment by snnn** [comment]
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Softsign

**Comment by fumihwh** [comment]
@snnn 
This is how pytorch exports softsign now... Of course, it could be improved.
