### ISSUE TITLE
Index operator? Reconsider slice?

### ISSUE THREAD

**Issue by ezyang** [onnx/onnx#84]
Currently, indexing is implemented using the `Slice` operator, which is more general. But the conversion is not very nice: ~~quite disgusting: because slice as implemented only supports slicing in 1D tensors, we have to first reshape a tensor into 1D, convert the indices into a scalar representation, and then shape back to the correct thing. This is a bit awful. Pave the cowpaths.~~ we have to compute a dim-size array specifying what our slice is going to be, and the squeeze away the dimension we want to remove. Should we make it easier to do this?

**Comment by ebarsoum** [comment]
Why slice is restricted to 1D? The one in ONNX is for ND.

OPERATOR_SCHEMA(Slice)
     Produces a slice of the input tensor along multiple axes.

**Comment by ezyang** [comment]
You're right. Let me take a look what's going on...

**Comment by ezyang** [comment]
OK, it is not as bad as I originally thought. I updated the top description with a more accurate description of what's going on.

**Comment by prasanthpul** [comment]
The ops have been updated and new ones added since this issue was last commented on. Please re-open if there is still a concern.
