### ISSUE TITLE
Negative Axis Support

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#842]
Shall we support negative axis in ONNX spec?

This is unclear, and worth more discussion.

**Comment by bddppq** [comment]
Yes we should. It's necessary to represent "from the end" in some cases with dynamic shape (e.g. Slice). And to make it consistent, we should allow negative axis everywhere. This also aligns with numpy semantics (which the Test and Compliance working group agreed on in last workshop).

**Comment by linkerzhang** [comment]
does this mean we only want to have "-1" to represent sth, instead of having any negative value, right? btw, for unknown type, we have symbolic shape parameter for the purpose.

**Comment by gramalingam** [comment]
It seems well-defined and useful. I am fine with supporting it (though it is a generalization of the current spec so we may want to add it to a suitable version of ONNX.) @linkerzhang , this seems orthogonal to the use of symbolic dimensions (or negative values) to represent statically unknown dimension values. This is allowing attributes that specify an axis to specify it from the left end or right end.

**Comment by askhade** [comment]
Support for negative axis has been added. If there are any gaps then open a new issues to track it.
