### ISSUE TITLE
tf2onnx tool: "StridedSlice not implemented"

### ISSUE THREAD

**Issue by jiangsuliji** [onnx/onnx#844]
While I was converting a frozen tensorflow model, it errors out with "StridedSlice not implemented".
I checked the node and this operation just raises an error.
I was wondering when it could be implemented. Thanks a lot.

Details:
File "C:\Program Files\Python35\lib\site-packages\tf2onnx\tfonnx.py", line 668, in stridedslice_op
raise ValueError("StridedSlice not implemented")
ValueError: StridedSlice not implemented

**Comment by houseroad** [comment]
Could you move the issue to https://github.com/onnx/tensorflow-onnx?

**Comment by jiangsuliji** [comment]
Sure, i will do that
