### ISSUE TITLE
Checker Issue for BatchNorm in ONNX-1.1.2

### ISSUE THREAD

**Issue by wschin** [onnx/onnx#851]
Hello,
The [doc](https://github.com/onnx/onnx/blob/rel-1.1.2/docs/Operators.md#BatchNormalization) in onnx-1.1.2 doesn't contain "consumed" attribute for BatchNorm, but the checker reports an error below. If we're targeting onnx-1.1.2, can we use op_version=2 to bypass this bug? Thanks.

Input index 3 must be set to ***consumed*** for operator BatchNormalization

==> Context: Bad node spec: input: "conv1_output" input: "BatchNormalization_scale" input: "BatchNormalization_B" input: "BatchNormalization_mean" input: "BatchNormalization_variance" output: "bn_conv1_output" name: "batchnorm" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT } attribute { name: "momentum" f: 0 type: FLOAT } attribute { name: "spatial" i: 1 type: INT } domain: ""

**Comment by fumihwh** [comment]
I assume your model does not contain `opset_imports`?

**Comment by wschin** [comment]
We have an operator set below in the model.

opset_import {
  domain: ""
  version: 1
}

**Comment by fumihwh** [comment]
So you do already try setting `version: 2`?
```
opset_import {
domain: ""
version: 2
}
```

**Comment by bddppq** [comment]
Hmm this is because our 1.1.2 release only cherry picked couple minor changes and paired with the newest opset version. @raymondxyang @linkerzhang

**Comment by dougsouza** [comment]
Same problem here

**Comment by linkerzhang** [comment]
yes, this is an issue due to the cherry pick in the 1.1.2 release.

Please try to onnx 1.2.1 now
