### ISSUE TITLE
defs.cc:379 warning C4389: '==': signed/unsigned mismatch

### ISSUE THREAD

**Issue by snnn** [onnx/onnx#864]
onnx\defs\tensor\defs.cc(379): warning C4389: '==': signed/unsigned mismatch

```c++
          if (j < axes.size() && axes[j] == i) {
```

axes[j] is int64_t
i is size_t

**Comment by ebarsoum** [comment]
Can you submit a fix?

**Comment by jcwchen** [comment]
I think these warnings have been resolved. Close it now. Thanks
