### ISSUE TITLE
Trigonometric functions support?

### ISSUE THREAD

**Issue by zasdfgbnm** [onnx/onnx#866]
Is there any plan, or is it contribute welcome, to support trigonometric functions?
sin, cos, tan, asin, acos, atan

These functions are widely supported, for example the cosine function can be found in:
[pytorch](http://pytorch.org/docs/master/tensors.html#torch.Tensor.cos), [tensorflow](https://www.tensorflow.org/api_docs/python/tf/cos), [numpy](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.cos.html), [mxnet](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.cos), [cntk](https://cntk.ai/pythondocs/cntk.ops.html#cntk.ops.cos)

**Comment by bddppq** [comment]
I agree these should be added to onnx. Are you interested in writing up a PR? :-)

**Comment by bddppq** [comment]
@zasdfgbnm thanks. here is a previous PR that adds a new operator into onnx: https://github.com/onnx/onnx/pull/496 you can take a look to use it as a reference.

**Comment by zasdfgbnm** [comment]
Fixed.
