### ISSUE TITLE
onnx.onnx_pb2'

### ISSUE THREAD

**Issue by pribadihcr** [onnx/onnx#872]
Hi,

when run onnx_tf.backend import prepare, I got error:

anaconda3/lib/python3.6/site-packages/onnx_tf/backend.py", line 24, in <module>
    from onnx.onnx_pb2 import GraphProto, TensorProto, AttributeProto
ModuleNotFoundError: No module named 'onnx.onnx_pb2'

**Comment by raymondxyang** [comment]
try from onnx.onnx_pb import GraphProto?

**Comment by raymondxyang** [comment]
close since there is no further message. feel free to reopen if there are still issues.

**Comment by TIanCat** [comment]
I meet the same problem!  How to solve it?
