### ISSUE TITLE
ONNX-Keras Repo

### ISSUE THREAD

**Issue by leodestiny** [onnx/onnx#877]
Our group has written a ONNX-Keras repo(not finished yet) https://github.com/leodestiny/onnx-keras converted between Keras and ONNX, which we found is a missing part in official repos.
Could this repo merge into official repos? If the answer is yes, what requirements do we need? If answer is no, how should we make contributions to ONNX by this repo?

**Comment by jspisak** [comment]
thanks @leodestiny for the great work! Can you tell us a bit more about your group?

**Comment by leodestiny** [comment]
We are students from  NASP Lab in CS Department of Tsinghua University.

**Comment by wschin** [comment]
Awesome! We also have a [plan ](https://github.com/onnx/onnxmltools/pull/28) to support Keras-to-ONNX in ONNXMLTools. Would you mind to take a look and see how we can collaborate? Our parser currently supports shared model structure and recursive models.

**Comment by pliniosilveira** [comment]
@wschin you called it a plan. It means it is not ready yet? Can you give an overview on how completed it is (what it has vs what it is missing)?

**Comment by prasanthpul** [comment]
Closing this old thread as https://github.com/onnx/onnxmltools/ has Keras->ONNX conversion for some time now. Feel free to contribute additional functionality!
