### ISSUE TITLE
## Error ONNX export failed: Couldn't export Python operator GridSampler ？？

### ISSUE THREAD

**Issue by heils003** [onnx/onnx#883]
I tried to use ONNX to transform my Pytorch model but with error like this:
```
proto = trace.export(list(model.state_dict().values()), _onnx_opset_version)
RuntimeError: ONNX export failed: Couldn't export Python operator GridSampler
```
It seems ONNX can't find the same method like the Pytorch Function GridSampler. And it was setted `UNKNOWN_TYPE` on the Layer Operator???  How can I solve it ?

**Comment by houseroad** [comment]
This means PyTorch does not know how to translate this op. Please check [the tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md) to fix the problem.

**Comment by IbnlaAhed** [comment]
@heils003 i have the same error, have you find the solution?

**Comment by IbnlaAhed** [comment]
@houseroad unfortunately Grid Sampler is not standardized in ONNX. Have you any proposition?
thx

**Comment by RunningLeon** [comment]
@heils003 i have the same error, have you find the solution? thx

**Comment by OrkhanHI** [comment]
any updates?

**Comment by tejal567** [comment]
+1

**Comment by askhade** [comment]
https://github.com/onnx/onnx/pull/3557 draft for grid sample

**Comment by askhade** [comment]
duplicate of #2383. Closing this one.
