### ISSUE TITLE
PReLU slope design/doc issue

### ISSUE THREAD

**Issue by KeDengMS** [onnx/onnx#889]
I hit a broadcasting issue in implementing PReLU op recently, for the slope parameter. [The document](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#prelu-6) says:
```
 If Slope is of size 1, the value is shared across different channels
```
However, it is not clear what channel means from the doc. I managed to get the test pass by padding 1s in Slope's shape to support 1d/2d/3d multiparam case (NC, NCH, NCHW in my understanding). At minimal, we should fix the doc to clarify that channel means the second dimension of input tensor, and it needs to match slope size when slope is not scalar.

Thinking further, I don't think this is a good design for this op, as it cannot support N being more than one dimension. IMO the slope parameter here should be treated with standard numpy broadcasting rules for element-wise ops discussed in #83.

**Comment by houseroad** [comment]
We have a redesign here: https://github.com/onnx/onnx/pull/580

However it didn't move forward.

**Comment by KeDengMS** [comment]
Thanks for pointing out #580. As you may find out in #83, there are several other issues related to broadcasting rules. If we are going to redesign PReLU instead of clarifying its doc, I'd prefer to redesign it in the numpy broadcasting rules. I can submit a PR for that if needed.

**Comment by houseroad** [comment]
I think we are moving our broadcasting to numpy style. If you have bandwidth, could you create a proposal in our github wiki on this numpy style broadcasting topic?

**Comment by KeDengMS** [comment]
Here are the [numpy broadcasting rules](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules). Should I just copy them to wiki?

**Comment by houseroad** [comment]
Instead of copying, you can just refer to it. :-)

**Comment by KeDengMS** [comment]
Seems I don't have write access to wiki, so I put the proposal [here](https://gist.github.com/KeDengMS/76337ca350aaa222318a3dda47a6839a). Would you please help me upload to wiki for public discussion. Thanks!

**Comment by houseroad** [comment]
Ongoing PR: https://github.com/onnx/onnx/pull/907

**Comment by linkerzhang** [comment]
PR merged.
