### ISSUE TITLE
NNVM Compiler and Interpolation

### ISSUE THREAD

**Issue by tqchen** [onnx/onnx#89]
Last month we saw the splashing release of onnx, which I think personally think is a great step toward common model exchange format of deep learning frameworks. I am glad that the community has been moving toward more interpolation and collaboration. First in case of [dlpack](https://github.com/dmlc/dlpack) for tensor structure and now in terms of model exchange. I also see a lot of common spirits when we develop NNVM. 

We did not immediately jump into discussion issues because we think we should bring something to the community that can work with common exchange formats and focus on graph and tensor level optimization, thus the  [NNVM Compiler](http://www.tvmlang.org/2017/10/06/nnvm-compiler-announcement.html).

We would like now to jump in and discuss potential ways to work together. In the very least, now nnvm compiler provides an end to end solution to bring onnx to bare metal. As I mentioned to  @soumith and @Yangqing personally before, I would like to see more interpolations happen and make nnvm compiler and onnx to work together to benefit the users.

Technically there is a barrier to code migration, barrier of the institutions or barrier of pride. But I think at least we can have an openminded discussion on what each member of the community think the exchange layer and compilation layer should look like, for example

- Serialized IR(onnx) for exchange v.s. in memory IR(nnvm or pytorch's jit ir) for graph optimization
- What can nnvm learn from onnx, vice versa
- What should be good in-memory structure for graph IR
- What is a good strategy for operator extension
- Should numpy be supported as a basic primitive or lower level op for ease of vendor implementation

Through the discussion maybe there would be more interesting ways of interpolation and lessons learned.

**Comment by dzhulgakov** [comment]
Thanks @tqchen and congrats on releasing nnvm/tvm!

Here are my 2 cents:
- ONNX has a value as a spec that is serializable and framework-independent. Thus it's explicitly put separately from any framework or toolchain, but it's welcoming contribution both to the spec and to importers/exporters
- we totally share the view that the more standardized the community stack becomes - the better. For example, even if in-memory IR representations are different code, it's easier if they share the same operator semantics
- we'd be very happy to collaborate on making NNVM/TVM stack work smoothly with ONNX and we're welcoming spec suggestions as well
- you've mentioned great topics for discussion - we're always happy to have a exchange experience on tech issues and lessons learned

**Comment by yuanbyu** [comment]
@tqchen There are certainly ambitions to have a good shared in-memory graph structure to facilitate further collaboration on graph-based optimizations.

**Comment by tqchen** [comment]
@yuanbyu  For in-memory graph structure, I would recommend nnvm as one of a starting point, as it already being framework agnostic and comes with a bunch of graph optimizations that already provides end to end compilation for onnx. And we would be more than happy to get involved in the discussion

**Comment by tqchen** [comment]
i am going to close this for now as specific discussion can happen in separate issues
