### ISSUE TITLE
Composable Operators

### ISSUE THREAD

**Issue by binarybana** [onnx/onnx#9]
There was an off-topic discussion in #3 about what the right level of abstraction is regarding ONNX operators. I'd like to further that discussion here and propose a potential solution.

This classic tradeoff was summarized by @soumith as:
> Side 1: a mathematical IR, so that things are extremely expressive (also requested by the compiler efforts)
Side 2: vendors (particularly mobile vendors) implementing the operators in the IR efficiently

This tension between higher/coarser (side 2) and lower/finer (side 1) levels of abstraction is real and valid, but why not enable both levels to be represented simultaneously in a single data flow graph representation? By enabling operators to (optionally) be defined by other operators, it gives the mobile vendor the choice to match on the coarse operators (eg: SELU) and ignore the implementation of SELU provided for nascent backends.

One possibility then is to distribute the set of non-primitive operators in a 'standard library' of reference implementations using primitive operators (in addition to or in lieu of the C++ reference implementations), which can potentially grow/evolve at a more rapid pace from the primitive operators (mirroring something like libc++/libc and syscall interfaces).

Additionally, this enables a lifecycle for operators to make their way from researchers to hand tuned kernels: A researcher creates a new operator and defines it using ONNX primitives, this allows for all frameworks to implement this operator at some (potential) loss of performance immediately, but then once/if this operator becomes popularized, it can be matched by name directly to an optimized kernel.

This parallels the transition from assembly programming to higher (C) languages that enabled procedural programming and libraries, only in this case the domain of operators/functions is somewhat more constrained, so it is feasible for backends to pattern match on functions as well as instructions/blocks.

Another nice aspect of this design is that these composed operators are also useful for representing RNN cells, fused kernels, and managing the increasing levels of abstraction that we see in DL topologies (fprop, bprop, critic, generator, discriminator, etc), that will potentially be valuable for selecting/addressing regions of computation for manipulation (take all weights from 'generator' and quantize them for this backend). Or loading in a large graph and then subselecting a 'chunk' of it.

**Comment by ebarsoum** [comment]
@binarybana what in the current design prevent us from adding primitive OPs in the future to satisfy both goals?

**Comment by binarybana** [comment]
Looking at it more closely, perhaps the primary gap in `onnx.proto` for enabling something like this is the distinction made between the `operator` and `graph` namespaces. Eg: operators are (or can be) nothing more than references to other subgraphs, and operators with `op_type` names that are not resolved against the set of `graph`s in a ONNX file (module?) can resolve against the set of intrinsic names for primitive ops.

XLA has something similar to this now with their [`Call`](https://www.tensorflow.org/performance/xla/operation_semantics#call) op, but I believe this is closer to supporting anonymous functions, whereas for matching purposes it is important that ONNX represents named 'functions'.

**Comment by Yangqing** [comment]
We've definitely discussed about functions and subgraphs in the design discussions. One example is that in onnx.proto, the AttributeProto has a graph field that can allow us to e.g. put a subgraph ("function" like) as an op. We believe it's fairly advanced and decided to defer the introduction, but the current codebase should be ready for future extension on this front.

**Comment by binarybana** [comment]
> One example is that in onnx.proto, the AttributeProto has a graph field that can allow us to e.g. put a subgraph ("function" like) as an op.
My initial thought is that this is not enough to support the types of use cases I mentioned above. One example is that this only allows 'inlined' functions to be represented since it is not possible to reason about a subgraph referenced in several places. Eg: if I have a `ReLuPrime` operator, then I'd need to copy its 'definition' into every time it is referenced.

**Comment by yuanbyu** [comment]
As Yangqing said, It was discussed quite a bit in our design meetings, and we even had some preliminary design. In the end, we decided to release only the parts that we felt safe and essential to get things started.

I think you are right. The graph field in AttributeProto would not be enough to support the kind of function abstraction we would like to have. However, it is good enough to define control flows such as conditionals and while loops.

**Comment by prasanthpul** [comment]
@binarybana: functions were added this summer. there may still be some gaps on what you envisioned and what is currently in the spec. take a look at let @linkerzhang know
