### ISSUE TITLE
Remove "Graph" attribute type to cut circle proto message dependency in onnx.proto

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#900]
In ONNX, we're having a different bunch of types for attributes from input/output types. This introduces two main problems.
1. Circle dependency among proto messages. all messages in onnx.proto have to be put in one file due to this.
2. Attribute can't have flexible type per input/output type. For example, “max” and "min" attribute in Clip op. It should have same type as input/output.

Solution:  Remove AttributeProto, having TensorProto for attributes too. In order to not make a big change like this, the first step may be, Remove "Graph" attribute type. All places referring a graph attribute will use "String" (graph name) to refer to a graph, and the graph referred will be located in a model separately.

Thoughts?

@bddppq @houseroad @ezyang @dzhulgakov  @ebarsoum @NiklasGustafsson @yuanbyu @gramalingam

**Comment by bddppq** [comment]
Hmm looks to me Attribute and Tensor are two pretty different concepts (as the current AttributeProto::AttributeType indicates, their relation is that TensorProto is one of the value type of Attribute) At the serialization format level, it's probably true that's we can use one proto message to represent both (like as an extreme case you can use A proto message that has one single repeated bytes field to represent everything), but considering they are representing different concepts, I will still prefer to have separate proto messages.

For the problems you listed, 1. hasn't caused any issue as far as I know, 2. it's more like the job of checker or type constraints to enforce.

Also, this is a BIG BIG change, I would really encourage everyone to consider the cost/benefit ratio.

**Comment by linkerzhang** [comment]
It's not a checker job. The problem is that there's no way to specify same type for input/output and attribute. I believe attributeproto does the same thing as tensorproto. We're adding ints/strings/floats into AttributeProto as shortcuts, actually they can be presented by tensor too. 

The only thing special in AttributeProto now is "Graph" type, which should be cut and using "String" to refer its graph name.

It's not that big change, as we're now only having If/Loop experimental operators using this "graph" attribute. We should do it as early as possible before we're using them more in stable scenarios/ops.
