### ISSUE TITLE
World Language Model Checker Fails (Reshape Input Size Mismatch)

### ISSUE THREAD

**Issue by chrisaberger** [onnx/onnx#906]
When I run the provided world language model from PyTorch (https://github.com/pytorch/examples/blob/master/word_language_model) with:

```
import onnx
onnx.checker.check_model(onnx.load(path))
```

added after this line https://github.com/pytorch/examples/blob/master/word_language_model/main.py#L185. I get the following error on the reshape operator:

```
onnx.onnx_cpp2py_export.checker.ValidationError: Input size 2 not in range [min=1, max=1].

==> Context: Bad node spec: input: "67" input: "68" output: "actual_output_0" op_type: "Reshape"
```

I am running with ONNX 1.1.1 and PyTorch 0.4.0.

**Comment by fumihwh** [comment]
Seems checker checks model by using opset version < 5.
Check your model's opset_import and installation of ONNX first.

**Comment by chrisaberger** [comment]
Thanks! Yes my model is using opset version 6. Any references on how to make this consistent?

**Comment by fumihwh** [comment]
@chrisaberger 
Could you reinstall your onnx?
First clean your local files by like `git clean -xfd`.

**Comment by chrisaberger** [comment]
This fixed it. Thanks!
