### ISSUE TITLE
lstm - pytorch exported pb doesn't match specification

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx#921]
Use Netron open onnx/backend/test/data/pytorch-operator/test_operator_lstm/model.onnx can get:
![image](https://user-images.githubusercontent.com/6838753/39824565-a4bf96d2-53ea-11e8-87c5-edb132a839e7.png)

Here, output from first LSTM should have shape [seq_length, num_directions, batch_size, hidden_size] following the docs. (In pytorch, should have  (seq_len, batch, hidden_size * num_directions))
And then pass to next nodes [Shape, Gather, Unsqueeze ....] to get second LSTM's initial_h and initial_c which has shape [num_directions, batch_size, hidden_size].

Here is the problem,
normally, Gather should gather batch_size from output, and Concat with num_directions and hidden_size to obtain [num_directions, batch_size, hidden_size].
But pytorch export pb with index 1 of Gather and get num_directions because output shape changed from (seq_len, batch, hidden_size * num_directions) to [seq_length, num_directions, batch_size, hidden_size]. batch_size is no longer at index 1.
Finally get [num_directions, num_directions, hidden_size] to make a wrong initial_h and initial_c for second LSTM.

**Comment by houseroad** [comment]
@anderspapitto would you mind to take a look?

**Comment by anderspapitto** [comment]
@fumihwh is this the same issue as https://github.com/pytorch/pytorch/issues/6879?

**Comment by fumihwh** [comment]
@anderspapitto 
Nearly, but that issue claims weight tensors `W`, `R`, `B`. 
However this issue focuses on output tensors `Y`, `Y_h`, `Y_c`.

**Comment by jekbradbury** [comment]
It also needs to be fixed in onnx-tensorflow, which assumes yet another distinct format for outputs, but we're on that :+1:. Thanks Anders!
