### ISSUE TITLE
is there a c library to load onnx model and trained parameters in memory

### ISSUE THREAD

**Issue by guoyejun** [onnx/onnx#929]
hi,

i'm interested to bring onnx into my c/c++ project for inference (i do not choose the deep learning frameworks such as tensorflow because they might be too heavy to port to some mobile device). The key thing I want is the onnx format interpretation, i can write my own inference engine to execute the onnx model.

so, is there a demo to show the c/c++ APIs to  load onnx model and trained parameters in memory, (and also execute the model). Just like the usage at https://github.com/onnx/models, but i'd like the C API. Thanks.

**Comment by newling** [comment]
It is possible, see https://github.com/onnx/onnx/issues/418 .

**Comment by guoyejun** [comment]
thanks
