### ISSUE TITLE
Writing backend tests for a Julia framework

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#935]
I was working on ONNX.jl, a Julia package for importing ONNX files to the Julia Flux framework. I needed some advice regarding writing the backend tests for this. How should I start with writing these tests, since the package is written in Julia and the tests are written in Python. 

Any advice/suggestions will be helpful.

**Comment by ebarsoum** [comment]
Would the R binding help? https://github.com/onnx/onnx-r

**Comment by bddppq** [comment]
@ayush1999 The source of truth of our tests are the protobuf data files here https://github.com/onnx/onnx/tree/master/onnx/backend/test/data. We just have a [python test harness](https://github.com/onnx/onnx/tree/master/onnx/backend/test/runner) to load these data files and export python test cases. So for your case, you can simply load the protobuf files and do the comparison in Julia.

**Comment by ayush1999** [comment]
I see. Thanks a lot @bddppq . Closing this issue now.
