### ISSUE TITLE
Unable to find attribute holding data

### ISSUE THREAD

**Issue by ayush1999** [onnx/onnx#942]
The docs https://github.com/onnx/onnx/blob/master/docs/IR.md#attributes state that the `_type` attribute of `AttributeProto` stores information regarding where the data is present. In a few ONNX models, I noticed the `_type` to be 0. What does this imply? And given any other numeric value of` _type`, how can I infer which attribute holds the data?

**Comment by ayush1999** [comment]
@bddpqq I noticed several `AttributeProto`s having the same `_type` but referring to different fields. Why is this happening?

**Comment by bddppq** [comment]
@ayush1999 Thanks for reporting. For onnx models with `ir_version >= 2` the `type` field of AttributeProto should be present and != 0 (0 means undefined).
@houseroad @mx-iao Please correct the mnist model file. Beside the `type` field issue mentioned above, the `opset_import` field is already missing, which is required for model with `ir_version >= 3`.

**Comment by bddppq** [comment]
I think the mnist model file has been fixed according to https://github.com/onnx/onnx/issues/942
