### ISSUE TITLE
Getting error in tutorial code

### ISSUE THREAD

**Issue by kartk** [onnx/onnx#964]
I tried converting a Pytorch model to onnx format by following the PytorchOnnxExport.ipynb from the Tutorials repo. I get the following error 
`model with IR version < 3 cannot have opset_import specified`
while running the following line
`onnx.checker.check_model(model)`

What could be the issue here ?

**Comment by houseroad** [comment]
Could you check your pytorch version? Maybe its version is too old.

**Comment by kartk** [comment]
Yes, It was. I had a pytorch v0.3.1. I updated it v0.4.0 and issue was solved
