### ISSUE TITLE
Error exporting squeezenet model in caffe2 !!

### ISSUE THREAD

**Issue by Nagamani732** [onnx/onnx#980]
I built caffe2 and onnx from source and tried to export squeezenet model but ended up the following  error:

> onnx.onnx_cpp2py_export.checker.ValidationError: Field 'name' of graph is required to be non-empty.

I couldn't find any solution to fix this. Could anyone help me in this regard ?
Thanks in advance !!

**Comment by inkawhich** [comment]
I think you can just manually set the name like this...

```
# Prepare the nets
predict_net = caffe2_pb2.NetDef()
with open(pnet, 'rb') as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open(inet, 'rb') as f:
    init_net.ParseFromString(f.read())

# Make sure the net has a name. Otherwise, the checker will fail.
if predict_net.name == "":
    predict_net.name = "ModelNameHere"
```

The problem I am having with the Caffe2->ONNX squeezenet export is with the is_test attribute of the dropout layers

```
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: is_test

==> Context: Bad node spec: input: "fire9/concat_1" output: "fire9/concat_2" output: "_fire9/concat_mask_1" name: "" op_type: "Dropout" attribute { name: "ratio" f: 0.5 type: FLOAT } attribute { name: "is_test" i: 1 type: INT }
```

Have you encountered this error?

**Comment by Nagamani732** [comment]
Thanks for your reply. I haven't encountered that error. You could find squeezenet here
https://github.com/onnx/models/tree/master/squeezenet

**Comment by ShaunZheng** [comment]
@Nagamani732 Hello, I have encountered the same mistakes as you, I hope to know how you solved it, I hope to get your reply, thank you！

**Comment by Nagamani732** [comment]
@ShaunZheng Sorry, I did not fix that issue. So I could not help you. Rather I downloaded the squeezenet model from the above link. You could try the @inkawhich suggestion. But I am not sure, that will fix your issue. You could open a new issue / raise a query in StackOverflow if you are not able to fix further. Thanks
