### ISSUE TITLE
Proposal: remove explicitly optional outputs

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#985]
Unlike optional inputs, optional outputs add no expressiveness or implementation flexibility. In a sense, all outputs of every operator are already optional - if the graph does not contain a consumer for that output, the backend is free to skip computing it as an optimization.

However some operators have outputs which are explicitly tagged as optional, which is just redundant and confusing. I propose to remove all references to "optional outputs" from the spec.

**Comment by gramalingam** [comment]
I agree. It sounds like a good idea.

(However, I think it does require some work in the backend implementation: the intention is to allow some operator implementations avoid computing some output if it is not required (e.g., for example RNN where we want only the final state and not the entire sequence of states); at the same time, we do not want to burden all operator implementations with having to check if some output is required or not (admittedly, this is relevant only when they compute multiple outputs). So, the annotation can play a useful role, but it is more of a backend implementation issue, and should probably not be in the ONNX spec.

**Comment by linkerzhang** [comment]
Removing "optional" tag from optional output will make all output be optional by default, which will make the number of outputs check not as good as current logic. For example, For Add op, its number of output should be always 1, can't be 0 (we're checking this in checker); and for batchnormalization, it's number of output should be 1 or 5. if we remove explicit "optional" output tag, then number of outputs for add will be [0,1].

So, I'd prefer keeping as it is.

@gramalingam is also working on clarifying clearly on "optional" semantics and usage in a model. That should be good enough for us, I think.
