### ISSUE TITLE
Definition of Tile changed without bumping the opset version

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#996]
Documentation in the master branch:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Tile

versus

Documentation in the v1.1.0 release:
https://github.com/onnx/onnx/blob/v1.1.0/docs/Operators.md#Tile

@ezyang @bddppq

**Comment by houseroad** [comment]
The old one is kind of buggy. But I agree with that it's better to keep the old definition in old.cc. I will fix it.

**Comment by tjingrant** [comment]
@houseroad the problem I had is that recently, we started test onnx-tensorflow against onnx master and a onnx release (v1.1.0). In this case, there is no non-hacky way (e.g., matching specific onnx version and so on) to differentiate between two different tile op schema, which means we cannot have onnx-tensorflow + onnx-master and onnx-tensorflow + onnx-v1.1.0 both working at the same time.

I am guessing that retroactively bumping the version number might fix this problem; but this may introduce mess of another kind, please let me know your plan of action.

**Comment by houseroad** [comment]
@tjingrant thanks for the information. My plan is adding the previous version in old.cc, and mark the current version with opset_version 7. So you can check the opset_version before execute it.

**Comment by tjingrant** [comment]
@houseroad in that case, things would be a lot better for us if you can ensure that the current master does not make its way into a v 1.1.3 release.

**Comment by houseroad** [comment]
Not sure about this, because very likely, the 1.2 will be a snapshot release, instead of cherrypicking some commits.

**Comment by bddppq** [comment]
The current master won't be made to next release, as @houseroad said, let's add the previous version of Tile to Tile-v1 and make the current definition Tile-v7, so in next release you will see two versions of Tile.

**Comment by bddppq** [comment]
@tjingrant Yes Cast should be fixed as well

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/1007 and https://github.com/onnx/onnx/pull/1008 addresses Tile and Cast separately. Now we have two versions, v1 and v6 (because the changes are introduce in opset_6)

**Comment by tjingrant** [comment]
Thanks @houseroad that would greatly help us.

**Comment by houseroad** [comment]
Close the issue since two PRs are merged.
