### ISSUE TITLE
onnx namespace error in c++

### ISSUE THREAD

**Issue by Nagamani732** [onnx/onnx#999]
I built onnx from source I tried to print the number of inputs in a model as @bddppq mentioned in one of the previous closed issues but I ended up with an error in the onnx namespace. Though I have included the headers compiler couldn't find onnx namespace

Can you please help me to resolve this issue?

`#include "onnx/onnx_pb.h"`
`#include "onnx/proto_utils.h"`

`std::unique_ptr<ModelProto> model(new ModelProto());`
`onnx::ParseProtoFromBytes(model.get(), bytes, nbytes);`  --> Error
`std::cout << model->graph().input().size() << std::endl;`

**Comment by linkerzhang** [comment]
the namespace used in onnx c++ codes now is "ONNX_NAMESPACE", if you want to use "onnx" as the namespace you'd run cmake with option "-DONNX_NAMESPACE=onnx". otherwise, please change your code as, 

ONNX_NAMESPACE::ParseProtoFromBytes(model.get(), bytes, nbytes);

**Comment by Nagamani732** [comment]
OK. Thank you. It worked out
